import type { SiteLocale } from "./site-config";

export type ClassDifficultyFactsCopy = {
  editorial: string;
  notTier: string;
  weapon: string;
  role: string;
  overall: string;
  scale: string;
  assessed: string;
  method: string;
  confidence: string;
  medium: string;
  metrics: {
    inputs: string;
    positioning: string;
    resourceManagement: string;
    partyResponsibility: string;
    errorRecovery: string;
  };
  comparisonTitle: string;
  comparisonIntro: string;
  class: string;
  details: string;
  open: string;
};

export const classDifficultyFactsCopy = {
  "zh-hans": {
    editorial: "KINA 编辑难度评估",
    notTier: "不是官方评级，也不是强度或 Tier 排名",
    weapon: "官方武器",
    role: "官方定位",
    overall: "综合学习负担",
    scale: "1 较低 · 5 较高",
    assessed: "评估日期",
    method: "方法版本",
    confidence: "可信度",
    medium: "中等",
    metrics: {
      inputs: "连段与输入",
      positioning: "站位与闪避",
      resourceManagement: "技能与资源管理",
      partyResponsibility: "队伍责任",
      errorRecovery: "失误恢复负担",
    },
    comparisonTitle: "九职业五维难度表",
    comparisonIntro:
      "同一分数只比较学习负担，不代表伤害、治疗、坦度、胜率或版本强弱。",
    class: "职业",
    details: "完整攻略",
    open: "查看",
  },
  en: {
    editorial: "KINA editorial difficulty",
    notTier: "Not an official rating, power score, or tier list",
    weapon: "Official weapon",
    role: "Official role",
    overall: "Overall learning load",
    scale: "1 lower · 5 higher",
    assessed: "Assessed",
    method: "Method",
    confidence: "Confidence",
    medium: "Medium",
    metrics: {
      inputs: "Inputs & chains",
      positioning: "Positioning & evasion",
      resourceManagement: "Skill & resource management",
      partyResponsibility: "Party responsibility",
      errorRecovery: "Error-recovery burden",
    },
    comparisonTitle: "Nine-class difficulty matrix",
    comparisonIntro:
      "A score compares learning load only; it does not rank damage, healing, durability, win rate, or patch strength.",
    class: "Class",
    details: "Full guide",
    open: "Open",
  },
  fr: {
    editorial: "Évaluation de difficulté KINA",
    notTier: "Ni note officielle, ni score de puissance, ni classement de tiers",
    weapon: "Arme officielle",
    role: "Rôle officiel",
    overall: "Charge d'apprentissage globale",
    scale: "1 faible · 5 élevée",
    assessed: "Évalué le",
    method: "Méthode",
    confidence: "Confiance",
    medium: "Moyenne",
    metrics: {
      inputs: "Commandes et enchaînements",
      positioning: "Placement et esquive",
      resourceManagement: "Compétences et ressources",
      partyResponsibility: "Responsabilité du groupe",
      errorRecovery: "Récupération après erreur",
    },
    comparisonTitle: "Matrice de difficulté des neuf classes",
    comparisonIntro:
      "Le score compare uniquement la charge d'apprentissage, pas les dégâts, les soins, la résistance, le taux de victoire ou la puissance d'une mise à jour.",
    class: "Classe",
    details: "Guide complet",
    open: "Ouvrir",
  },
  de: {
    editorial: "KINA-Redaktionsbewertung der Schwierigkeit",
    notTier: "Keine offizielle Wertung, Stärkezahl oder Tier-Liste",
    weapon: "Offizielle Waffe",
    role: "Offizielle Rolle",
    overall: "Gesamte Lernlast",
    scale: "1 niedriger · 5 höher",
    assessed: "Bewertet",
    method: "Methode",
    confidence: "Verlässlichkeit",
    medium: "Mittel",
    metrics: {
      inputs: "Eingaben und Kombos",
      positioning: "Positionierung und Ausweichen",
      resourceManagement: "Fähigkeiten und Ressourcen",
      partyResponsibility: "Gruppenverantwortung",
      errorRecovery: "Fehlerkorrektur",
    },
    comparisonTitle: "Schwierigkeitsmatrix für neun Klassen",
    comparisonIntro:
      "Die Punktzahl vergleicht nur die Lernlast, nicht Schaden, Heilung, Widerstandsfähigkeit, Siegesrate oder Patch-Stärke.",
    class: "Klasse",
    details: "Vollständiger Guide",
    open: "Öffnen",
  },
  es: {
    editorial: "Evaluación editorial de dificultad de KINA",
    notTier: "No es una valoración oficial, puntuación de poder ni lista de niveles",
    weapon: "Arma oficial",
    role: "Función oficial",
    overall: "Carga total de aprendizaje",
    scale: "1 menor · 5 mayor",
    assessed: "Evaluado",
    method: "Método",
    confidence: "Confianza",
    medium: "Media",
    metrics: {
      inputs: "Entradas y cadenas",
      positioning: "Posición y evasión",
      resourceManagement: "Habilidades y recursos",
      partyResponsibility: "Responsabilidad de grupo",
      errorRecovery: "Recuperación tras errores",
    },
    comparisonTitle: "Matriz de dificultad de nueve clases",
    comparisonIntro:
      "La puntuación solo compara la carga de aprendizaje; no clasifica daño, curación, resistencia, victorias ni poder del parche.",
    class: "Clase",
    details: "Guía completa",
    open: "Abrir",
  },
  ja: {
    editorial: "KINA編集部による難度評価",
    notTier: "公式評価、強さ、Tierランキングではありません",
    weapon: "公式武器",
    role: "公式ロール",
    overall: "総合学習負担",
    scale: "1 低い · 5 高い",
    assessed: "評価日",
    method: "評価方法",
    confidence: "確度",
    medium: "中",
    metrics: {
      inputs: "入力と連携",
      positioning: "位置取りと回避",
      resourceManagement: "スキルとリソース管理",
      partyResponsibility: "パーティー責任",
      errorRecovery: "ミスからの復帰負担",
    },
    comparisonTitle: "9クラス・5項目の難度表",
    comparisonIntro:
      "同じ点数は学習負担だけを比較します。ダメージ、回復、防御、勝率、アップデート時の強さを示す順位ではありません。",
    class: "クラス",
    details: "完全ガイド",
    open: "見る",
  },
  "pt-br": {
    editorial: "Avaliação editorial de dificuldade da KINA",
    notTier: "Não é nota oficial, pontuação de poder nem lista de tiers",
    weapon: "Arma oficial",
    role: "Função oficial",
    overall: "Carga total de aprendizado",
    scale: "1 menor · 5 maior",
    assessed: "Avaliado em",
    method: "Método",
    confidence: "Confiança",
    medium: "Média",
    metrics: {
      inputs: "Comandos e sequências",
      positioning: "Posicionamento e esquiva",
      resourceManagement: "Habilidades e recursos",
      partyResponsibility: "Responsabilidade no grupo",
      errorRecovery: "Recuperação de erros",
    },
    comparisonTitle: "Matriz de dificuldade das nove classes",
    comparisonIntro:
      "A pontuação compara apenas a carga de aprendizado; não classifica dano, cura, resistência, taxa de vitória ou força do patch.",
    class: "Classe",
    details: "Guia completo",
    open: "Abrir",
  },
  ru: {
    editorial: "Редакционная оценка сложности KINA",
    notTier: "Это не официальная оценка, показатель силы или тир-лист",
    weapon: "Официальное оружие",
    role: "Официальная роль",
    overall: "Общая учебная нагрузка",
    scale: "1 ниже · 5 выше",
    assessed: "Дата оценки",
    method: "Методика",
    confidence: "Уверенность",
    medium: "Средняя",
    metrics: {
      inputs: "Ввод и серии",
      positioning: "Позиционирование и уклонение",
      resourceManagement: "Навыки и ресурсы",
      partyResponsibility: "Ответственность за группу",
      errorRecovery: "Восстановление после ошибок",
    },
    comparisonTitle: "Матрица сложности девяти классов",
    comparisonIntro:
      "Баллы сравнивают только учебную нагрузку и не ранжируют урон, лечение, выживаемость, победы или силу в текущем патче.",
    class: "Класс",
    details: "Полное руководство",
    open: "Открыть",
  },
  ko: {
    editorial: "KINA 편집 난이도 평가",
    notTier: "공식 등급, 성능 점수 또는 티어표가 아닙니다",
    weapon: "공식 무기",
    role: "공식 역할",
    overall: "종합 학습 부담",
    scale: "1 낮음 · 5 높음",
    assessed: "평가일",
    method: "평가 방법",
    confidence: "신뢰도",
    medium: "중간",
    metrics: {
      inputs: "입력과 연계",
      positioning: "위치 선정과 회피",
      resourceManagement: "스킬과 자원 관리",
      partyResponsibility: "파티 책임",
      errorRecovery: "실수 회복 부담",
    },
    comparisonTitle: "아홉 직업 5개 기준 난이도표",
    comparisonIntro:
      "점수는 학습 부담만 비교하며 공격력, 치유량, 방어력, 승률 또는 패치 성능 순위가 아닙니다.",
    class: "직업",
    details: "전체 공략",
    open: "보기",
  },
  "zh-hant": {
    editorial: "KINA 編輯難度評估",
    notTier: "不是官方評級，也不是強度或 Tier 排名",
    weapon: "官方武器",
    role: "官方定位",
    overall: "綜合學習負擔",
    scale: "1 較低 · 5 較高",
    assessed: "評估日期",
    method: "方法版本",
    confidence: "信心",
    medium: "中等",
    metrics: {
      inputs: "連段與輸入",
      positioning: "站位與閃避",
      resourceManagement: "技能與資源管理",
      partyResponsibility: "隊伍責任",
      errorRecovery: "失誤恢復負擔",
    },
    comparisonTitle: "九職業五維難度表",
    comparisonIntro:
      "同一分數只比較學習負擔，不代表傷害、治療、坦度、勝率或版本強弱。",
    class: "職業",
    details: "完整攻略",
    open: "查看",
  },
} as const satisfies Record<SiteLocale, ClassDifficultyFactsCopy>;

export type ItemFactsCopy = {
  label: string;
  snapshot: string;
  id: string;
  quality: string;
  category: string;
  itemLevel: string;
  equipLevel: string;
  race: string;
  class: string;
  acquisition: string;
  description: string;
  effect: string;
  enchant: string;
  exceed: string;
  magicStone: string;
  godStone: string;
  states: string;
  storable: string;
  tradable: string;
  personalTradable: string;
  enchantable: string;
  decomposable: string;
  mainStats: string;
  stat: string;
  value: string;
  official: string;
  none: string;
  unknown: string;
  yes: string;
  no: string;
};

export const itemFactsCopy = {
  "zh-hans": {
    label: "官方物品资料",
    snapshot: "数据更新日",
    id: "官方 ID",
    quality: "品质",
    category: "分类",
    itemLevel: "道具等级",
    equipLevel: "装备等级限制",
    race: "种族限制",
    class: "职业限制",
    acquisition: "获得处",
    description: "官方说明",
    effect: "官方效果",
    enchant: "强化上限",
    exceed: "突破强化",
    magicStone: "魔石槽",
    godStone: "神石槽",
    states: "系统状态",
    storable: "可存放",
    tradable: "可交易",
    personalTradable: "可个人交易",
    enchantable: "可强化",
    decomposable: "可分解",
    mainStats: "官方主要属性",
    stat: "属性",
    value: "数值",
    official: "查看官方物品页",
    none: "无限制",
    unknown: "官方未提供",
    yes: "是",
    no: "否",
  },
  en: {
    label: "Official item record",
    snapshot: "Data updated",
    id: "Official ID",
    quality: "Grade",
    category: "Category",
    itemLevel: "Item level",
    equipLevel: "Equip level",
    race: "Race restriction",
    class: "Class restriction",
    acquisition: "Acquisition",
    description: "Official description",
    effect: "Official effect",
    enchant: "Max enchant",
    exceed: "Exceed enchant",
    magicStone: "Manastone slots",
    godStone: "Theostone slots",
    states: "System states",
    storable: "Storable",
    tradable: "Tradable",
    personalTradable: "Personal trade",
    enchantable: "Enchantable",
    decomposable: "Decomposable",
    mainStats: "Official main stats",
    stat: "Stat",
    value: "Value",
    official: "Open official item page",
    none: "None",
    unknown: "Not supplied by the official record",
    yes: "Yes",
    no: "No",
  },
  fr: {
    label: "Fiche officielle de l'objet",
    snapshot: "Données mises à jour",
    id: "ID officiel",
    quality: "Qualité",
    category: "Catégorie",
    itemLevel: "Niveau de l'objet",
    equipLevel: "Niveau requis",
    race: "Restriction de race",
    class: "Restriction de classe",
    acquisition: "Obtention",
    description: "Description officielle",
    effect: "Effet officiel",
    enchant: "Enchantement maximal",
    exceed: "Enchantement de dépassement",
    magicStone: "Emplacements de pierres de mana",
    godStone: "Emplacements de pierres divines",
    states: "États système",
    storable: "Stockable",
    tradable: "Échangeable",
    personalTradable: "Échange personnel",
    enchantable: "Enchantable",
    decomposable: "Décomposable",
    mainStats: "Caractéristiques officielles principales",
    stat: "Caractéristique",
    value: "Valeur",
    official: "Ouvrir la page officielle de l'objet",
    none: "Aucune",
    unknown: "Non indiqué dans la fiche officielle",
    yes: "Oui",
    no: "Non",
  },
  de: {
    label: "Offizieller Gegenstandsdatensatz",
    snapshot: "Datenstand",
    id: "Offizielle ID",
    quality: "Qualität",
    category: "Kategorie",
    itemLevel: "Gegenstandsstufe",
    equipLevel: "Ausrüstungsstufe",
    race: "Volksbeschränkung",
    class: "Klassenbeschränkung",
    acquisition: "Fundort",
    description: "Offizielle Beschreibung",
    effect: "Offizieller Effekt",
    enchant: "Maximale Verzauberung",
    exceed: "Überschreitungsverzauberung",
    magicStone: "Manasteinplätze",
    godStone: "Göttersteinplätze",
    states: "Systemstatus",
    storable: "Lagerfähig",
    tradable: "Handelbar",
    personalTradable: "Persönlich handelbar",
    enchantable: "Verzauberbar",
    decomposable: "Zerlegbar",
    mainStats: "Offizielle Hauptwerte",
    stat: "Wert",
    value: "Betrag",
    official: "Offizielle Gegenstandsseite öffnen",
    none: "Keine",
    unknown: "Im offiziellen Datensatz nicht angegeben",
    yes: "Ja",
    no: "Nein",
  },
  es: {
    label: "Registro oficial del objeto",
    snapshot: "Datos actualizados",
    id: "ID oficial",
    quality: "Calidad",
    category: "Categoría",
    itemLevel: "Nivel del objeto",
    equipLevel: "Nivel de equipamiento",
    race: "Restricción de raza",
    class: "Restricción de clase",
    acquisition: "Obtención",
    description: "Descripción oficial",
    effect: "Efecto oficial",
    enchant: "Encantamiento máximo",
    exceed: "Encantamiento de superación",
    magicStone: "Ranuras de piedras de maná",
    godStone: "Ranuras de piedras divinas",
    states: "Estados del sistema",
    storable: "Almacenable",
    tradable: "Intercambiable",
    personalTradable: "Intercambio personal",
    enchantable: "Encantable",
    decomposable: "Descomponible",
    mainStats: "Atributos principales oficiales",
    stat: "Atributo",
    value: "Valor",
    official: "Abrir la página oficial del objeto",
    none: "Ninguna",
    unknown: "No indicado en el registro oficial",
    yes: "Sí",
    no: "No",
  },
  ja: {
    label: "公式アイテム情報",
    snapshot: "データ更新日",
    id: "公式ID",
    quality: "グレード",
    category: "カテゴリー",
    itemLevel: "アイテムレベル",
    equipLevel: "装備レベル",
    race: "種族制限",
    class: "クラス制限",
    acquisition: "入手先",
    description: "公式説明",
    effect: "公式効果",
    enchant: "最大強化",
    exceed: "超越強化",
    magicStone: "魔石スロット",
    godStone: "神石スロット",
    states: "システム状態",
    storable: "倉庫保管",
    tradable: "取引",
    personalTradable: "個人取引",
    enchantable: "強化",
    decomposable: "分解",
    mainStats: "公式主要ステータス",
    stat: "ステータス",
    value: "数値",
    official: "公式アイテムページを開く",
    none: "制限なし",
    unknown: "公式情報に記載なし",
    yes: "可能",
    no: "不可",
  },
  "pt-br": {
    label: "Registro oficial do item",
    snapshot: "Dados atualizados",
    id: "ID oficial",
    quality: "Qualidade",
    category: "Categoria",
    itemLevel: "Nível do item",
    equipLevel: "Nível para equipar",
    race: "Restrição de raça",
    class: "Restrição de classe",
    acquisition: "Obtenção",
    description: "Descrição oficial",
    effect: "Efeito oficial",
    enchant: "Encantamento máximo",
    exceed: "Encantamento de superação",
    magicStone: "Espaços de pedras de mana",
    godStone: "Espaços de pedras divinas",
    states: "Estados do sistema",
    storable: "Armazenável",
    tradable: "Negociável",
    personalTradable: "Troca pessoal",
    enchantable: "Encantável",
    decomposable: "Decomponível",
    mainStats: "Atributos principais oficiais",
    stat: "Atributo",
    value: "Valor",
    official: "Abrir a página oficial do item",
    none: "Nenhuma",
    unknown: "Não informado no registro oficial",
    yes: "Sim",
    no: "Não",
  },
  ru: {
    label: "Официальная карточка предмета",
    snapshot: "Дата обновления данных",
    id: "Официальный ID",
    quality: "Качество",
    category: "Категория",
    itemLevel: "Уровень предмета",
    equipLevel: "Уровень экипировки",
    race: "Ограничение по расе",
    class: "Ограничение по классу",
    acquisition: "Получение",
    description: "Официальное описание",
    effect: "Официальный эффект",
    enchant: "Максимальное усиление",
    exceed: "Предельное усиление",
    magicStone: "Ячейки магических камней",
    godStone: "Ячейки божественных камней",
    states: "Системные состояния",
    storable: "Можно хранить",
    tradable: "Можно передавать",
    personalTradable: "Личная передача",
    enchantable: "Можно усиливать",
    decomposable: "Можно разобрать",
    mainStats: "Официальные основные характеристики",
    stat: "Характеристика",
    value: "Значение",
    official: "Открыть официальную страницу предмета",
    none: "Нет",
    unknown: "Не указано в официальной записи",
    yes: "Да",
    no: "Нет",
  },
  ko: {
    label: "공식 아이템 정보",
    snapshot: "데이터 업데이트",
    id: "공식 ID",
    quality: "등급",
    category: "분류",
    itemLevel: "아이템 레벨",
    equipLevel: "착용 제한 레벨",
    race: "종족 제한",
    class: "직업 제한",
    acquisition: "획득처",
    description: "공식 설명",
    effect: "공식 효과",
    enchant: "최대 강화",
    exceed: "초월 강화",
    magicStone: "마석 슬롯",
    godStone: "신석 슬롯",
    states: "시스템 상태",
    storable: "창고 보관",
    tradable: "거래",
    personalTradable: "개인 거래",
    enchantable: "강화",
    decomposable: "분해",
    mainStats: "공식 주요 능력치",
    stat: "능력치",
    value: "수치",
    official: "공식 아이템 페이지 열기",
    none: "제한 없음",
    unknown: "공식 정보 없음",
    yes: "가능",
    no: "불가",
  },
  "zh-hant": {
    label: "官方物品資料",
    snapshot: "資料更新日",
    id: "官方 ID",
    quality: "品質",
    category: "分類",
    itemLevel: "道具等級",
    equipLevel: "裝備等級限制",
    race: "種族限制",
    class: "職業限制",
    acquisition: "獲得處",
    description: "官方說明",
    effect: "官方效果",
    enchant: "強化上限",
    exceed: "突破強化",
    magicStone: "魔石槽",
    godStone: "神石槽",
    states: "系統狀態",
    storable: "可存放",
    tradable: "可交易",
    personalTradable: "可個人交易",
    enchantable: "可強化",
    decomposable: "可分解",
    mainStats: "官方主要屬性",
    stat: "屬性",
    value: "數值",
    official: "查看官方物品頁",
    none: "無限制",
    unknown: "官方未提供",
    yes: "是",
    no: "否",
  },
} as const satisfies Record<SiteLocale, ItemFactsCopy>;

export const trustContactEyebrowCopy = {
  "zh-hans": "编辑联系",
  en: "EDITORIAL CONTACT",
  fr: "CONTACT ÉDITORIAL",
  de: "REDAKTIONELLER KONTAKT",
  es: "CONTACTO EDITORIAL",
  ja: "編集部への連絡",
  "pt-br": "CONTATO EDITORIAL",
  ru: "СВЯЗЬ С РЕДАКЦИЕЙ",
  ko: "편집 문의",
  "zh-hant": "編輯聯絡",
} as const satisfies Record<SiteLocale, string>;
