import { articleCopy, guideLabels, localizations, publishedVerified, section } from "./trending-september-10-shared";
import type { ContentEntry, ContentHeroImage, ContentSource } from "./content-registry";

/* ARTICLE 5 — How the Snowfield of Sorrow first clear was done: 10-man composition, 4h16m, Hard-mode meta */

const gametokSource: ContentSource = {
  id: "gametok-snowfield-first-clear-2026-09-09",
  kind: "third-party",
  publisher: "GameToc (게임톡)",
  label: "Aion 2: 'Snowfield of Sorrow' First-Cleared Within 4 Hours",
  url: "https://v.daum.net/v/20260909150237053",
  publishedAt: "2026-09-09",
  retrievedAt: "2026-09-10",
  verifiedAt: "2026-09-10",
  localizations: localizations({
    "zh-hans": "Aion 2：『Snowfield of Sorrow』4 小时内被首杀",
    en: "Aion 2: 'Snowfield of Sorrow' First-Cleared Within 4 Hours",
    fr: "Aion 2 : « Snowfield of Sorrow » vaincu en moins de 4 heures",
    de: "Aion 2: „Snowfield of Sorrow“ in unter 4 Stunden erstgecleart",
    es: "Aion 2: 'Snowfield of Sorrow' superado en menos de 4 horas",
    ja: "Aion 2：「Snowfield of Sorrow」が4時間足らずで初クリア",
    "pt-br": "Aion 2: 'Snowfield of Sorrow' zerado em menos de 4 horas",
    ru: "Aion 2: «Snowfield of Sorrow» пройден менее чем за 4 часа",
    ko: "아이온2: '비탄의 설원' 4시간 만에 최초 격파",
    "zh-hant": "Aion 2：『Snowfield of Sorrow』4 小時內被首殺",
  }, "https://v.daum.net/v/20260909150237053"),
};

const ncOfficialSource: ContentSource = {
  id: "nc-official-a2-update-2026-09-09",
  kind: "official",
  publisher: "NC Corporation",
  label: "NC's AION 2: New Sanctuary 'Snowfield of Sorrow' Update (Press Release)",
  url: "https://about.ncsoft.com/news/article/A2_update_20260909",
  publishedAt: "2026-09-09",
  retrievedAt: "2026-09-10",
  verifiedAt: "2026-09-10",
  localizations: localizations({
    "zh-hans": "NC 的 AION 2：新 Sanctuary「Snowfield of Sorrow」更新（新闻稿）",
    en: "NC's AION 2: New Sanctuary 'Snowfield of Sorrow' Update (Press Release)",
    fr: "AION 2 de NC : mise à jour du Sanctuary « Snowfield of Sorrow » (communiqué)",
    de: "NCs AION 2: Update „Snowfield of Sorrow“ (Pressemitteilung)",
    es: "AION 2 de NC: actualización del Santuario «Snowfield of Sorrow» (nota de prensa)",
    ja: "NCのAION 2：新サンクチュアリ「Snowfield of Sorrow」アップデート（プレスリリース）",
    "pt-br": "AION 2 da NC: atualização do Santuário 'Snowfield of Sorrow' (comunicado)",
    ru: "AION 2 от NC: обновление Святилища «Snowfield of Sorrow» (пресс-релиз)",
    ko: "엔씨 AION 2: 신규 성역 '비탄의 설원' 업데이트 (보도자료)",
    "zh-hant": "NC 的 AION 2：新 Sanctuary「Snowfield of Sorrow」更新（新聞稿）",
  }, "https://about.ncsoft.com/news/article/A2_update_20260909"),
};

const compHero: ContentHeroImage = {
  src: "https://blogfiles.ncsoft.net/news/af7330da-4ff6-4b58-aece-400e6061a3be.jpg",
  width: 1200, height: 630,
  credit: "NC Corporation",
  sourceUrl: "https://aion2.plaync.com/en-us/",
  rights: "linked-official-media",
  translations: {
    "zh-hans": { alt: "Aion 2 Snowfield of Sorrow 首杀阵容指南横幅", caption: "韩服首杀队采用 10 人双队结构：一队吟游/守护/暗杀/弓/治愈，二队把守护换成剑星——开发预期 5-6 小时，实际 4 小时 16 分完成 Hard。" },
    en: { alt: "Aion 2 Snowfield of Sorrow first-clear composition guide banner", caption: "The Korean first-clear group used a 10-player two-party structure: Chanter/Templar/Assassin/Ranger/Cleric in party one, and party two swapping the Templar for a Gladiator — clearing Hard in 4h16m against the developers' 5-6 hour forecast." },
    fr: { alt: "Bannière du guide de composition du premier clear de Snowfield of Sorrow d'Aion 2", caption: "Le groupe coréen du premier clear utilisait une structure à deux groupes de 5 : Chanteur/Templier/Assassin/Chasseur/Prêtre, le second remplaçant le Templier par un Gladiateur — clear Hard en 4 h 16, contre 5-6 h prévues." },
    de: { alt: "Banner zum Erst-Clear-Aufstellungs-Leitfaden von Snowfield of Sorrow in Aion 2", caption: "Die koreanische Erst-Clear-Gruppe nutzte eine 10-Spieler-Zwei-Parteien-Struktur: Chanter/Templer/Assassine/Jäger/Kleriker, die zweite Partei tauschte den Templer gegen einen Gladiator — Hard-Clear in 4 h 16 min statt der erwarteten 5-6 Stunden." },
    es: { alt: "Banner de la guía de composición del primer clear de Snowfield of Sorrow de Aion 2", caption: "El grupo coreano del primer clear usó una estructura de 10 jugadores en dos grupos: Bardo/Templario/Asesino/Cazador/Sacerdote, y el segundo cambió al Templario por un Gladiador — clear en Hard en 4 h 16, frente a las 5-6 h previstas." },
    ja: { alt: "Aion 2 Snowfield of Sorrow 初クリア編成ガイドバナー", caption: "韓国初クリア部隊は10人2パーティ構成：1PTは吟遊/守護/暗殺/弓/治癒、2PTは守護を剣星に変更——開発想定5〜6時間に対し4時間16分でHardクリア。" },
    "pt-br": { alt: "Banner do guia de composição do primeiro clear de Snowfield of Sorrow do Aion 2", caption: "O grupo coreano do primeiro clear usou uma estrutura de 10 jogadores em dois grupos: Cantor/Templário/Assassino/Caçador/Sacerdote, e o segundo trocou o Templário por um Gladiador — clear no Hard em 4h16, contra as 5-6h previstas." },
    ru: { alt: "Баннер гайда по составу первого клира Snowfield of Sorrow в Aion 2", caption: "Корейская группа первого клира использовала структуру 10 игроков в двух партиях: Хантер/Темплар/Ассасин/Рейнджер/Клерик, во второй Темплара заменил Гладиатор — клир на Hard за 4 ч 16 мин против ожидаемых 5–6 часов." },
    ko: { alt: "Aion 2 비탄의 설원 최초 격파 조합 가이드 배너", caption: "한국 최초 격파 공격대는 10인 2파티 구조를 사용했습니다: 1파티 호법성·수호성·살성·궁성·치유성, 2파티는 수호성을 검성으로 교체——개발진 예상 5~6시간 대비 4시간 16분 만에 Hard 클리어." },
    "zh-hant": { alt: "Aion 2 Snowfield of Sorrow 首殺陣容指南橫幅", caption: "韓服首殺隊採用 10 人雙隊結構：一隊吟遊/守護/暗殺/弓/治癒，二隊把守護換成劍星——開發預期 5-6 小時，實際 4 小時 16 分完成 Hard。" },
  },
};

export const trendingSeptember10Article5: ContentEntry = {
  section: "guides",
  slug: "aion-2-snowfield-of-sorrow-first-clear-composition-guide",
  schemaType: "Article",
  publishedAt: "2026-09-10",
  updatedAt: "2026-09-10",
  readingMinutes: 6,
  publication: publishedVerified,
  sources: [gametokSource, ncOfficialSource],
  heroImage: compHero,
  related: [
    { kind: "content", section: "news", slug: "aion-2-snowfield-of-sorrow-first-clear" },
    { kind: "content", section: "guides", slug: "aion-2-snowfield-of-sorrow-farming-guide" },
    { kind: "content", section: "guides", slug: "aion-2-korea-server-class-tier-guide" },
    { kind: "content", section: "guides", slug: "aion-2-class-roles-trinity-guide" },
  ],
  translations: {
    en: articleCopy(guideLabels, "en", 6, {
      eyebrow: "META GUIDE",
      title: "How the Snowfield of Sorrow First Clear Was Done: 10-Man Composition, 4h16m, and the Hard-Mode Meta",
      description: "Breaking down the first Hard clear of Snowfield of Sorrow: the 10-player two-party composition that beat the raid in 4h16m (faster than the devs' 5-6h forecast), the 6,200 item-level gate, and what it tells raiders about the Hard meta",
      intro: "Korea's first Hard clear of the Snowfield of Sorrow Sanctuary took 4 hours and 16 minutes on September 9 — faster than the 5-6 hours the developers expected. This guide breaks down the winning 10-player composition, the 6,200 item-level entry bar, and what the record tells us about the Hard-mode meta.",
      sourceNote: "Based on GameToc's September 9, 2026 report of the first clear (via Daum), cross-checked with NCsoft's official press release (both retrieved September 10, 2026). Class names use the global English naming.",
      keywords: ["Aion 2 first clear composition", "Aion 2 Snowfield of Sorrow 10 man composition", "Aion 2 Hard mode meta raid", "Aion 2 Gladiator raid composition", "Aion 2 item level 6200 raid"],
      sections: [
        section("the-record", "The Record: 4h16m on Day One", ["The Snowfield of Sorrow Sanctuary opened with the September 9 maintenance, and the first Hard clear was recorded at 14:16 KST — about 4 hours 16 minutes after servers returned at 10:00.", "The development team had predicted 5-6 hours for a first clear during the preview livestream. Clearing below that forecast on day one indicates both strong prep by the top Korean forces and a read on the raid's actual difficulty at the 6,200 item-level bar."]),
        section("the-composition", "The Winning 10-Man Composition", ["The first-clear group ran a two-party structure. Party 1: Chanter, Templar, Assassin, Ranger, Cleric. Party 2: the same five — Chanter, Assassin, Ranger, Cleric — but with a Gladiator in the Templar slot.", "In practice that means one dedicated tank (Templar), one off-tank that doubles as damage (Gladiator), two healers (Clerics), two buffers/off-healers (Chanters), and four damage dealers split between melee (Assassins) and ranged (Rangers). The single-Templar choice trades safety for damage — a statement about how much healing and mitigation the fight actually demands."]),
        section("what-it-tells-us", "What the Composition Tells Us", ["Two healers and a Chanter per party points to sustained damage over burst: the fight likely pressures the group steadily rather than in one-shots, so healing output and mana management matter more than a second tank.", "The Gladiator swap suggests the Templar's defensive toolkit is sufficient on its own, and the extra melee/ranged damage was more valuable than a second mitigation layer. For groups planning Hard attempts, this is the baseline to compare against — not a strict requirement, but a strong signal."]),
        section("entry-bar", "The 6,200 Item-Level Bar", ["Hard requires item level 6,200 (Easy is 5,800, Normal 6,000). The first-clear group was operating at or above that bar on day one.", "That confirms Hard is a gear-check plus mechanics-check: reaching 6,200 is the entry ticket, but the 4h16m learning curve shows mechanics still dominate the clear time. Expect wipe-and-adapt pulls to be the norm before your group locks in the fight."]),
        section("preparing-for-hard", "Preparing for Hard: Checklist", ["1. Reach 6,200 item level first — farm Easy/Normal for gear and Seal upgrades; 2. Build around two healers and one tank; a Gladiator off-tank is proven, but a second Templar is safer while learning; 3. Expect reaction-heavy mechanics — assign a caller and practice visual-cue responses before the boss pulls; 4. Use World Marks to pre-pin boss positions and split-phase spots; 5. Remember the first-clear race: the first 20 Hard clears earn Void pets, so schedule attempts while the event window is open.", "For global players: this is Korean-service meta. The global build launches October 5 with a modified Season 1, and this raid arrives in the content pipeline later — the composition here is your blueprint for when it does."]),
      ],
    }),
    "zh-hans": articleCopy(guideLabels, "zh-hans", 6, {
      eyebrow: "打法分析",
      title: "Snowfield of Sorrow 首杀复盘：10 人阵容、4 小时 16 分与 Hard 打法生态",
      description: "拆解 Snowfield of Sorrow 首个 Hard 击杀：以 4 小时 16 分通关（快于开发预期 5-6 小时）的 10 人双队阵容、6,200 装分门槛，以及它揭示的 Hard 打法生态",
      intro: "韩服首个 Hard 击杀——Snowfield of Sorrow Sanctuary——在 9 月 9 日耗时 4 小时 16 分完成，快于开发团队预期的 5-6 小时。本指南拆解获胜的 10 人阵容、6,200 装分入场门槛，以及这一纪录揭示的 Hard 打法生态。",
      sourceNote: "基于 게임톡（GameToc）2026 年 9 月 9 日对首杀的报道（经 Daum），并与 NCsoft 官方新闻稿交叉核对（均于 2026-09-10 抓取）。职业名采用全球版英文命名。",
      keywords: ["Aion 2 首杀阵容", "Aion 2 Snowfield of Sorrow 10人阵容", "Aion 2 Hard 打法 副本", "Aion 2 剑星 副本阵容", "Aion 2 6200装分 副本"],
      sections: [
        section("the-record", "纪录：首日 4 小时 16 分", ["Snowfield of Sorrow 随 9 月 9 日维护开放，首个 Hard 击杀记录于 14:16 KST——即 10:00 开服后约 4 小时 16 分。", "开发团队在预览直播中曾预测首杀需要 5-6 小时。首日即低于该预测完成，既说明韩服顶级队伍的准备程度，也给出了 6,200 装分门槛下副本真实难度的读数。"]),
        section("the-composition", "获胜的 10 人阵容", ["首杀队采用双队结构。一队：吟游、守护、暗杀、弓、治愈。二队：同样五人——吟游、暗杀、弓、治愈——但守护位换成了剑星。", "实际配置即一名专职坦克（守护）、一名兼职伤害的副坦（剑星）、两名治疗（治愈）、两名增益/副治疗（吟游），以及两名近战（暗杀）与两名远程（弓）输出。单选守护的选择用安全换伤害——这是对战斗实际治疗与减伤需求的一种表态。"]),
        section("what-it-tells-us", "阵容说明了什么", ["每队两名治疗与一名吟游指向持续伤害而非爆发：战斗很可能是持续施压而非一击秒杀，因此治疗量与法力管理比第二个坦克更重要。", "剑星替换说明守护的防御工具包单独已足够，额外的近战/远程伤害比第二层减伤更有价值。计划 Hard 尝试的队伍应以此为基线对照——不是硬性要求，但是强信号。"]),
        section("entry-bar", "6,200 装分门槛", ["Hard 要求装分 6,200（Easy 5,800、Normal 6,000）。首杀队在首日已在该线或以上。", "这确认 Hard 是装备检查+机制检查：到 6,200 只是入场券，而 4 小时 16 分的摸索曲线说明机制仍主导通关时间。灭团-调整-再试将是队伍磨合战斗前的常态。"]),
        section("preparing-for-hard", "Hard 备战清单", ["1. 先到 6,200 装分——刷 Easy/Normal 拿装备与印章升级；2. 围绕双治疗+单坦克构建；剑星副坦已验证可行，但学习期第二守护更稳；3. 预期反应型机制——指派指挥并提前练习视觉提示应对；4. 用世界标记预标 Boss 位置与阶段拆散点；5. 记得首杀竞速：前 20 个 Hard 通关获得 Void 宠物，趁活动窗口内安排尝试。", "对全球玩家：这是韩服生态。全球版 10 月 5 日以改良版 Season 1 上线，该副本稍后进入内容管线——这里的阵容就是届时你的蓝图。"]),
      ],
    }),
    fr: articleCopy(guideLabels, "fr", 6, {
      eyebrow: "GUIDE META",
      title: "Comment le premier clear de Snowfield of Sorrow a été fait : composition de 10, 4 h 16, meta Hard",
      description: "Décryptage du premier clear Hard de Snowfield of Sorrow : la composition à deux groupes de 5 qui a vaincu le raid en 4 h 16 (plus vite que les 5-6 h prévues), la barre des 6 200 et ce que ça dit de la meta Hard",
      intro: "Le premier clear coréen en Hard du Sanctuary Snowfield of Sorrow a pris 4 h 16 le 9 septembre — plus vite que les 5-6 h attendues. Ce guide détaille la composition gagnante (10 joueurs), la barre des 6 200 et la meta Hard.",
      sourceNote: "Basé sur le rapport de GameToc du 9 septembre 2026 (via Daum), recoupé avec le communiqué officiel de NCsoft (récupérés le 10 septembre 2026). Noms de classes en anglais global.",
      keywords: ["Aion 2 composition premier clear", "Aion 2 composition 10 joueurs", "Aion 2 meta Hard raid", "Aion 2 Gladiator composition raid", "Aion 2 niveau 6200 raid"],
      sections: [
        section("the-record", "Le record : 4 h 16 dès le premier jour", "Ouvert le 9 septembre, le premier clear Hard est tombé à 14:16 KST, ~4 h 16 après l'ouverture. Les développeurs prévoyaient 5-6 h — record sous les prévisions le jour même, entre préparation des forces coréennes et lecture de la difficulté réelle à 6 200."),
        section("the-composition", "La composition gagnante (10 joueurs)", "Deux groupes de 5. Groupe 1 : Chanteur, Templier, Assassin, Chasseur, Prêtre. Groupe 2 : idem mais Gladiateur au lieu du Templier. Soit 1 tank (Templier), 1 off-tank DPS (Gladiateur), 2 soigneurs, 2 buffers, 4 DPS (2 mêlée, 2 distance). Le choix du Templier unique échange sécurité contre dégâts."),
        section("what-it-tells-us", "Ce que ça révèle", "Deux soigneurs et un Chanteur par groupe = dégâts soutenus plutôt que burst ; la pression est continue. Le swap Gladiateur suggère que le kit défensif du Templier suffit seul — un signal fort pour les groupes visant Hard."),
        section("entry-bar", "La barre des 6 200", "Hard exige 6 200 (Easy 5 800, Normal 6 000). Le groupe jouait à ce niveau le premier jour. Hard = gear check + mécaniques ; les 4 h 16 montrent que les mécaniques dominent le temps de clear."),
        section("preparing-for-hard", "Checklist Hard", "1. Atteindre 6 200 (farm Easy/Normal pour équipement et Sceaux) ; 2. Deux soigneurs + un tank ; off-tank Gladiateur prouvé, second Templier plus sûr en apprentissage ; 3. Mécaniques à réactions — désigner un caller ; 4. Marques mondiales pour les positions de boss ; 5. La course aux 20 premiers Hard (pets Void) est ouverte. Pour le global : cette méta arrivera avec la Saison 1 modifiée du 5 octobre."),
      ],
    }),
    de: articleCopy(guideLabels, "de", 6, {
      eyebrow: "META-LEITFADEN",
      title: "Wie der Erster-Clear von Snowfield of Sorrow gelang: 10-Spieler-Komposition, 4 h 16 min, Hard-Meta",
      description: "Zerlegung des ersten Hard-Clears von Snowfield of Sorrow: die 10-Spieler-Zwei-Parteien-Komposition (4 h 16 min, schneller als die erwarteten 5-6 h), die 6 200er-Hürde und was das über die Hard-Meta sagt",
      intro: "Koreas erster Hard-Clear des Sanctuary Snowfield of Sorrow dauerte am 9. September 4 h 16 min — schneller als die erwarteten 5-6 Stunden. Dieser Leitfaden zerlegt die Gewinner-Komposition, die 6 200er-Hürde und die Hard-Meta.",
      sourceNote: "Basierend auf dem GameToc-Bericht vom 9. September 2026 (via Daum), abgeglichen mit der offiziellen NCsoft-Pressemitteilung (abgerufen am 10. September 2026). Klassennamen in globalem Englisch.",
      keywords: ["Aion 2 Erster-Clear Komposition", "Aion 2 10-Spieler-Komposition", "Aion 2 Hard-Meta Raid", "Aion 2 Gladiator Raid-Komposition", "Aion 2 Itemlevel 6200 Raid"],
      sections: [
        section("the-record", "Der Rekord: 4 h 16 min am ersten Tag", "Am 9. September geöffnet, fiel der erste Hard-Clear um 14:16 KST, ~4 h 16 min nach Öffnung. Die Entwickler erwarteten 5-6 h — Rekord unter den Prognosen am ersten Tag, dank Vorbereitung und als Realitätscheck der Schwierigkeit bei 6 200."),
        section("the-composition", "Die Gewinner-Komposition (10 Spieler)", "Zwei Parteien. Partei 1: Chanter, Templer, Assassine, Jäger, Kleriker. Partei 2: gleich, aber Gladiator statt Templer. Also 1 Tank (Templer), 1 Off-Tank-DPS (Gladiator), 2 Heiler, 2 Buffer, 4 DPS (2 Nah, 2 Fern). Der Ein-Templer-Weg tauscht Sicherheit gegen Schaden."),
        section("what-it-tells-us", "Was das verrät", "Zwei Heiler und ein Chanter pro Partei = anhaltender Schaden statt Burst; der Druck ist kontinuierlich. Der Gladiator-Swap zeigt, dass das defensive Kit des Templers allein reicht — ein starkes Signal für Hard-Gruppen."),
        section("entry-bar", "Die 6 200er-Hürde", "Hard verlangt 6 200 (Easy 5 800, Normal 6 000). Die Gruppe spielte am ersten Tag auf diesem Niveau. Hard = Gear- + Mechanik-Check; die 4 h 16 zeigen, dass Mechaniken die Clear-Zeit dominieren."),
        section("preparing-for-hard", "Hard-Checkliste", "1. 6 200 erreichen (Easy/Normal für Ausrüstung und Siegel farmen); 2. Zwei Heiler + ein Tank; Gladiator-Off-Tank bewiesen, zweiter Templer sicherer zum Lernen; 3. Reaktionsmechaniken — einen Caller benennen; 4. Weltmarken für Boss-Positionen; 5. Das Rennen (erste 20 Hard, Void-Begleiter) läuft. Für Global: diese Meta kommt mit der modifizierten Season 1 am 5. Oktober."),
      ],
    }),
    es: articleCopy(guideLabels, "es", 6, {
      eyebrow: "GUÍA META",
      title: "Cómo se logró el primer clear de Snowfield of Sorrow: composición de 10, 4 h 16 min, meta Hard",
      description: "Análisis del primer clear en Hard de Snowfield of Sorrow: la composición de 10 jugadores en dos grupos que superó el raid en 4 h 16 (más rápido de lo previsto, 5-6 h), la barrera de 6 200 y lo que dice de la meta Hard",
      intro: "El primer clear coreano en Hard del Santuario Snowfield of Sorrow tardó 4 h 16 min el 9 de septiembre — más rápido de lo esperado (5-6 h). Esta guía desglosa la composición ganadora, la barrera de 6 200 y la meta Hard.",
      sourceNote: "Basado en el informe de GameToc del 9 de septiembre de 2026 (vía Daum), cotejado con la nota de prensa oficial de NCsoft (recuperados el 10 de septiembre de 2026). Nombres de clases en inglés global.",
      keywords: ["Aion 2 composición primer clear", "Aion 2 composición 10 jugadores", "Aion 2 meta Hard raid", "Aion 2 Gladiador composición raid", "Aion 2 nivel 6200 raid"],
      sections: [
        section("the-record", "El récord: 4 h 16 min el primer día", "Abierto el 9 de septiembre, el primer clear en Hard llegó a las 14:16 KST, ~4 h 16 tras la apertura. Los desarrolladores preveían 5-6 h — récord por debajo de las previsiones el mismo día."),
        section("the-composition", "La composición ganadora (10 jugadores)", "Dos grupos de 5. Grupo 1: Bardo, Templario, Asesino, Cazador, Sacerdote. Grupo 2: igual pero Gladiador en vez de Templario. Es decir, 1 tanque (Templario), 1 off-tank DPS (Gladiador), 2 sanadores, 2 buffers, 4 DPS (2 cuerpo a cuerpo, 2 distancia). El Templario único cambia seguridad por daño."),
        section("what-it-tells-us", "Qué revela", "Dos sanadores y un Bardo por grupo = daño sostenido más que burst; la presión es continua. El cambio a Gladiador sugiere que el kit defensivo del Templario basta solo — una señal fuerte para los grupos de Hard."),
        section("entry-bar", "La barrera de 6 200", "Hard exige 6 200 (Easy 5 800, Normal 6 000). El grupo jugaba a ese nivel el primer día. Hard = chequeo de equipo + mecánicas; las 4 h 16 muestran que las mecánicas dominan el tiempo de clear."),
        section("preparing-for-hard", "Checklist para Hard", "1. Alcanzar 6 200 (farm de Easy/Normal para equipo y Sellos); 2. Dos sanadores + un tanque; off-tank Gladiador probado, segundo Templario más seguro al aprender; 3. Mecánicas de reacción — nombrar un caller; 4. Marcas mundiales para posiciones de jefes; 5. La carrera (primeros 20 Hard, mascotas Void) está abierta. Para el global: esta meta llega con la Temporada 1 modificada del 5 de octubre."),
      ],
    }),
    ja: articleCopy(guideLabels, "ja", 6, {
      eyebrow: "メタガイド",
      title: "Snowfield of Sorrow 初クリアの内訳：10人編成、4時間16分、Hardメタ",
      description: "Snowfield of Sorrow 最初のHardクリアを分解：開発想定5〜6時間を上回る4時間16分でクリアした10人2パーティ編成、6,200の入場条件、Hardメタへの示唆",
      intro: "韓国サーバー初のHardクリア——Snowfield of Sorrow——は9月9日、4時間16分で達成されました（開発想定5〜6時間より速い）。本ガイドは勝因の10人編成、6,200の入場条件、Hardメタへの示唆を分解します。",
      sourceNote: "ゲームトーク2026年9月9日付の初クリア報道（Daum経由）に基づき、NC公式プレスリリース（いずれも2026-09-10取得）と照合しました。職業名はグローバル版英語表記です。",
      keywords: ["Aion 2 初クリア編成", "Aion 2 10人編成", "Aion 2 Hardメタ レイド", "Aion 2 剣星 レイド編成", "Aion 2 装備スコア6200 レイド"],
      sections: [
        section("the-record", "記録：初日4時間16分", "Snowfield of Sorrowは9月9日のメンテで実装され、最初のHardクリアは14:16 KST——10:00オープンから約4時間16分。開発陣はプレビュー配信で5〜6時間を予想していました。初日で予想を下回ったことは、韓国トップ部隊の準備度と、6,200水準での実際の難易度の両方を示しています。"),
        section("the-composition", "勝因の10人編成", "初クリア部隊は2パーティ構成でした。1PT：吟遊・守護・暗殺・弓・治癒。2PT：同じ5職——吟遊・暗殺・弓・治癒——ですが守護の枠を剣星に変更。", "実質1タンク（守護）、ダメージ兼任のオフタンク（剣星）、ヒーラー2（治癒）、バッファー2（吟遊）、近接2（暗殺）＋遠隔2（弓）のDPS4。単タンク選択は安全をダメージに交換する判断で、戦闘が実際に要求するヒール量と軽減量の読みを反映します。"),
        section("what-it-tells-us", "編成が示すこと", "各PTにヒーラー2と吟遊1＝持続ダメージ主体（バーストではない）。戦闘はワンショットでなく継続的に圧力をかける構成で、ヒール量とマナ管理が2枚目のタンクより重要です。", "剣星への交換は、守護の防御ツールキットが単独で十分で、2枚目の軽減より追加ダメージの価値が高いことを示します。Hard挑戦を計画するPTはこの編成をベースラインに比較すべきです——絶対条件ではありませんが強いシグナルです。"),
        section("entry-bar", "6,200の入場条件", "Hardは装備スコア6,200が必要です（Easy 5,800、Normal 6,000）。初クリア部隊は初日からこの水準で運用していました。", "Hardは装備チェック＋メカニクスチェックです：6,200到達は入場券に過ぎず、4時間16分の習熟曲線はメカニクスがクリア時間を支配することを示しています。本番までに全滅→調整の繰り返しを想定しましょう。"),
        section("preparing-for-hard", "Hard挑戦チェックリスト", "1. まず装備スコア6,200へ（Easy/Normalで装備とシール昇級をファーム）; 2. ヒーラー2＋タンク1で構成。剣星オフタンクは実証済みですが、練習期は守護2枚が安全; 3. 反応型メカニクスを想定——コーラーを決め、視覚合図の対応を事前練習; 4. ワールドマークでボス位置とフェーズ分断地点を事前ピン; 5. 初クリアレース中——先着20HardでVoidペット、イベント窓口が開いているうちに挑戦を。グローバル向け：このメタは10月5日の改良版シーズン1とともに後日到来します。"),
      ],
    }),
    "pt-br": articleCopy(guideLabels, "pt-br", 6, {
      eyebrow: "GUIA META",
      title: "Como o primeiro clear de Snowfield of Sorrow foi feito: composição de 10, 4h16, meta Hard",
      description: "Análise do primeiro clear no Hard de Snowfield of Sorrow: a composição de 10 jogadores em dois grupos que zerou o raid em 4h16 (mais rápido do que as 5-6h previstas), a barreira de 6.200 e o que isso diz sobre a meta Hard",
      intro: "O primeiro clear coreano no Hard do Santuário Snowfield of Sorrow levou 4h16 em 9 de setembro — mais rápido do que o esperado (5-6h). Este guia detalha a composição vencedora, a barreira de 6.200 e a meta Hard.",
      sourceNote: "Baseado no relatório da GameToc de 9 de setembro de 2026 (via Daum), cruzado com o comunicado oficial da NCsoft (recuperados em 10 de setembro de 2026). Nomes de classes em inglês global.",
      keywords: ["Aion 2 composição primeiro clear", "Aion 2 composição 10 jogadores", "Aion 2 meta Hard raid", "Aion 2 Gladiador composição raid", "Aion 2 nível 6200 raid"],
      sections: [
        section("the-record", "O recorde: 4h16 no primeiro dia", "Aberto em 9 de setembro, o primeiro clear no Hard veio às 14:16 KST, ~4h16 após a abertura. Os desenvolvedores previam 5-6h — recorde abaixo das previsões no mesmo dia."),
        section("the-composition", "A composição vencedora (10 jogadores)", "Dois grupos de 5. Grupo 1: Cantor, Templário, Assassino, Caçador, Sacerdote. Grupo 2: igual, mas Gladiador no lugar do Templário. Ou seja, 1 tank (Templário), 1 off-tank DPS (Gladiador), 2 curandeiros, 2 buffers, 4 DPS (2 corpo a corpo, 2 à distância). O Templário único troca segurança por dano."),
        section("what-it-tells-us", "O que revela", "Dois curandeiros e um Cantor por grupo = dano sustentado em vez de burst; a pressão é contínua. A troca por Gladiador sugere que o kit defensivo do Templário basta sozinho — um sinal forte para grupos de Hard."),
        section("entry-bar", "A barreira de 6.200", "Hard exige 6.200 (Easy 5.800, Normal 6.000). O grupo jogava nesse nível no primeiro dia. Hard = cheque de gear + mecânicas; as 4h16 mostram que as mecânicas dominam o tempo de clear."),
        section("preparing-for-hard", "Checklist para o Hard", "1. Alcançar 6.200 (farm de Easy/Normal para equipamento e Selos); 2. Dois curandeiros + um tank; off-tank Gladiador comprovado, segundo Templário mais seguro ao aprender; 3. Mecânicas de reação — nomear um caller; 4. Marcas mundiais para posições de chefes; 5. A corrida (primeiros 20 Hard, mascotes Void) está aberta. Para o global: esta meta chega com a Temporada 1 modificada de 5 de outubro."),
      ],
    }),
    ru: articleCopy(guideLabels, "ru", 6, {
      eyebrow: "ГАЙД ПО МЕТЕ",
      title: "Как прошли первый клир Snowfield of Sorrow: состав 10, 4 ч 16 мин, мета Hard",
      description: "Разбор первого клира Hard в Snowfield of Sorrow: состав 10 игроков в двух партиях (4 ч 16 мин, быстрее ожидаемых 5–6 часов), порог 6 200 и что это говорит о мете Hard",
      intro: "Первый корейский клир Hard в Святилище Snowfield of Sorrow занял 4 ч 16 мин 9 сентября — быстрее ожидаемых 5–6 часов. Гайд разбирает победный состав, порог 6 200 и мету Hard.",
      sourceNote: "На основе отчёта GameToc от 9 сентября 2026 г. (через Daum), сверено с официальным пресс-релизом NCsoft (получены 10 сентября 2026 г.). Названия классов — в глобальной английской версии.",
      keywords: ["Aion 2 состав первого клира", "Aion 2 состав 10 игроков", "Aion 2 мета Hard рейд", "Aion 2 Гладиатор рейд состав", "Aion 2 уровень 6200 рейд"],
      sections: [
        section("the-record", "Рекорд: 4 ч 16 мин в первый день", "Святилище открылось 9 сентября, первый клир Hard — в 14:16 KST, ~4 ч 16 мин после открытия. Разработчики ожидали 5–6 часов — рекорд ниже прогноза в первый же день."),
        section("the-composition", "Победный состав (10 игроков)", "Две партии. Партия 1: Хантер, Темплар, Ассасин, Рейнджер, Клерик. Партия 2: то же, но Гладиатор вместо Темплара. Итого 1 танк (Темплар), 1 офф-танк-ДПС (Гладиатор), 2 хила, 2 баффера, 4 ДПС (2 ближних, 2 дальних). Выбор одного Темплара меняет безопасность на урон."),
        section("what-it-tells-us", "Что это показывает", "Два хила и Хантер в партии = устойчивый урон, а не бёрст; давление непрерывное. Замена на Гладиатора говорит, что защитного набора Темплара достаточно — сильный сигнал для групп на Hard."),
        section("entry-bar", "Порог 6 200", "Hard требует 6 200 (Easy 5 800, Normal 6 000). Группа играла на этом уровне в первый день. Hard = проверка шмота + механик; 4 ч 16 мин показывают, что механики доминируют во времени клира."),
        section("preparing-for-hard", "Чек-лист Hard", "1. Дойти до 6 200 (фарм Easy/Normal на шмот и Печати); 2. Два хила + один танк; офф-танк-Гладиатор проверен, второй Темплар безопаснее при обучении; 3. Реакционные механики — назначьте коллера; 4. Мировые метки для позиций боссов; 5. Гонка (первые 20 Hard, питомцы Void) открыта. Для глобала: эта мета придёт с модифицированным Сезоном 1 5 октября."),
      ],
    }),
    ko: articleCopy(guideLabels, "ko", 6, {
      eyebrow: "메타 가이드",
      title: "비탄의 설원 최초 격파 분석: 10인 조합, 4시간 16분, 어려움 메타",
      description: "비탄의 설원 첫 어려움(Hard) 격파를 분해합니다: 개발진 예상 5~6시간을 앞지른 4시간 16분 클리어의 10인 2파티 조합, 6,200 장비 점수 문턱, 어려움 메타에 대한 시사점",
      intro: "한국 서버 첫 어려움 격파——비탄의 설원——은 9월 9일 4시간 16분 만에 나왔습니다(개발진 예상 5~6시간보다 빠름). 이 가이드는 승리한 10인 조합, 6,200 장비 점수 입장 조건, 그리고 이 기록이 알려주는 어려움 메타를 분석합니다.",
      sourceNote: "게임톡 2026년 9월 9일자 첫 격파 보도(Daum 경유)를 기반으로, NC 공식 보도자료(모두 2026-09-10 확인)와 교차 검증했습니다. 직업명은 글로벌 영어 표기입니다.",
      keywords: ["아이온2 최초 격파 조합", "아이온2 10인 조합", "아이온2 어려움 메타 레이드", "아이온2 검성 레이드 조합", "아이온2 장비점수 6200 레이드"],
      sections: [
        section("the-record", "기록: 첫날 4시간 16분", "비탄의 설원은 9월 9일 점검과 함께 열렸고, 첫 어려움 격파는 14:16 KST——10:00 오픈 후 약 4시간 16분 만에 나왔습니다.", "개발진은 프리뷰 라이브에서 첫 격파에 5~6시간을 예상했습니다. 첫날 예상보다 빠른 기록은 한국 톱 포스의 준비도와 함께, 6,200 문턱에서 이 레이드의 실제 난이도에 대한 신호를 줍니다."),
        section("the-composition", "승리한 10인 조합", "최초 격파 공격대는 2파티 구조였습니다. 1파티: 호법성·수호성·살성·궁성·치유성. 2파티: 같은 5명——호법성·살성·궁성·치유성——이지만 수호성 자리를 검성으로 교체했습니다.", "실질 구성은 전담 탱커 1(수호성), 딜 겸 오프탱커 1(검성), 힐러 2(치유성), 버퍼 2(호법성), 그리고 근접 2(살성)·원거리 2(궁성)의 딜러 4입니다. 단일 수호성 선택은 안전을 딜로 맞바꾼 결정으로, 이 전투가 실제로 요구하는 힐량과 감소량을 읽은 결과입니다."),
        section("what-it-tells-us", "조합이 말해주는 것", "파티마다 힐러 2와 호법성 1은 지속 딜 중심(버스트가 아님)을 시사합니다. 전투는 한방에 죽이는 방식이 아니라 꾸준히 압박하는 방식이라, 힐량과 마나 관리가 두 번째 탱커보다 중요합니다.", "검성 교체는 수호성의 방어 툴킷이 단독으로 충분하고, 두 번째 경감보다 추가 근접·원거리 딜의 가치가 더 높았음을 보여줍니다. 어려움 도전을 계획하는 공대는 이 조합을 기준선으로 삼아 비교하면 됩니다——절대 조건은 아니지만 강력한 신호입니다."),
        section("entry-bar", "6,200 장비 점수 문턱", "어려움은 장비 점수 6,200이 필요합니다(쉬움 5,800, 보통 6,000). 최초 격파 공대는 첫날 이 기준 이상으로 운영했습니다.", "즉 어려움은 장비 점수+메커닉 점검입니다: 6,200 도달은 입장권에 불과하고, 4시간 16분의 학습 곡선은 메커닉이 클리어 시간을 지배함을 보여줍니다. 공대가 전투를 숙련하기 전까지 전멸-조정-재도전이 일상이 될 것입니다."),
        section("preparing-for-hard", "어려움 도전 체크리스트", "1. 먼저 장비 점수 6,200 달성——쉬움/보통에서 장비와 인장 승급 재료를 파밍; 2. 힐러 2+탱커 1로 구성. 검성 오프탱커는 실증됐지만, 학습기에는 수호성 2명이 더 안전합니다; 3. 반응형 메커니즘을 예상——콜러를 정하고 시각 신호 대응을 사전 연습; 4. 월드 징표로 보스 위치와 페이즈 분산 지점을 사전 지정; 5. 첫 클리어 레이스 진행 중——선착 20개 어려움 클리어에 보이드 펫, 이벤트 창이 닫히기 전에 일정을 잡으세요.", "글로벌 플레이어에게: 이것은 한국 서버의 메타입니다. 글로벌은 10월 5일 수정판 시즌 1로 시작하며, 이 레이드는 콘텐츠 파이프라인에서 나중에 도착합니다——여기 조합이 그때의 청사진입니다."),
      ],
    }),
    "zh-hant": articleCopy(guideLabels, "zh-hant", 6, {
      eyebrow: "打法分析",
      title: "Snowfield of Sorrow 首殺復盤：10 人陣容、4 小時 16 分與 Hard 打法生態",
      description: "拆解 Snowfield of Sorrow 首個 Hard 擊殺：以 4 小時 16 分通關（快於開發預期 5-6 小時）的 10 人雙隊陣容、6,200 裝分門檻，以及它揭示的 Hard 打法生態",
      intro: "韓服首個 Hard 擊殺——Snowfield of Sorrow Sanctuary——在 9 月 9 日耗時 4 小時 16 分完成，快於開發團隊預期的 5-6 小時。本指南拆解獲勝的 10 人陣容、6,200 裝分入場門檻，以及這一紀錄揭示的 Hard 打法生態。",
      sourceNote: "基於 게임톡（GameToc）2026 年 9 月 9 日對首殺的報導（經 Daum），並與 NCsoft 官方新聞稿交叉核對（均於 2026-09-10 抓取）。職業名採用全球版英文命名。",
      keywords: ["Aion 2 首殺陣容", "Aion 2 Snowfield of Sorrow 10人陣容", "Aion 2 Hard 打法 副本", "Aion 2 劍星 副本陣容", "Aion 2 6200裝分 副本"],
      sections: [
        section("the-record", "紀錄：首日 4 小時 16 分", ["Snowfield of Sorrow 隨 9 月 9 日維護開放，首個 Hard 擊殺記錄於 14:16 KST——即 10:00 開服後約 4 小時 16 分。", "開發團隊在預覽直播中曾預測首殺需要 5-6 小時。首日即低於該預測完成，既說明韓服頂級隊伍的準備程度，也給出了 6,200 裝分門檻下副本真實難度的讀數。"]),
        section("the-composition", "獲勝的 10 人陣容", ["首殺隊採用雙隊結構。一隊：吟遊、守護、暗殺、弓、治癒。二隊：同樣五人——吟遊、暗殺、弓、治癒——但守護位換成了劍星。", "實際配置即一名專職坦克（守護）、一名兼職傷害的副坦（劍星）、兩名治療（治癒）、兩名增益/副治療（吟遊），以及兩名近戰（暗殺）與兩名遠程（弓）輸出。單選守護的選擇用安全換傷害——這是對戰鬥實際治療與減傷需求的一種表態。"]),
        section("what-it-tells-us", "陣容說明了什麼", ["每隊兩名治療與一名吟遊指向持續傷害而非爆發：戰鬥很可能是持續施壓而非一擊秒殺，因此治療量與法力管理比第二個坦克更重要。", "劍星替換說明守護的防禦工具包單獨已足夠，額外的近戰/遠程傷害比第二層減傷更有價值。計畫 Hard 嘗試的隊伍應以此為基線對照——不是硬性要求，但是強訊號。"]),
        section("entry-bar", "6,200 裝分門檻", ["Hard 要求裝分 6,200（Easy 5,800、Normal 6,000）。首殺隊在首日已在該線或以上。", "這確認 Hard 是裝備檢查+機制檢查：到 6,200 只是入場券，而 4 小時 16 分的摸索曲線說明機制仍主導通關時間。滅團-調整-再試將是隊伍磨合戰鬥前的常態。"]),
        section("preparing-for-hard", "Hard 備戰清單", ["1. 先到 6,200 裝分——刷 Easy/Normal 拿裝備與印章升級；2. 圍繞雙治療+單坦克構建；劍星副坦已驗證可行，但學習期第二守護更穩；3. 預期反應型機制——指派指揮並提前練習視覺提示應對；4. 用世界標記預標 Boss 位置與階段拆散點；5. 記得首殺競速：前 20 個 Hard 通關獲得 Void 寵物，趁活動視窗內安排嘗試。", "對全球玩家：這是韓服生態。全球版 10 月 5 日以改良版 Season 1 上線，該副本稍後進入內容管線——這裡的陣容就是屆時你的藍圖。"]),
      ],
    }),
  },
};
