import { articleCopy, guideLabels, localizations, publishedVerified, section } from "./trending-august-17-shared";
import type { ContentEntry, ContentHeroImage, ContentSource } from "./content-registry";

/* ARTICLE 3 — Housing system preview */

const housingSource1: ContentSource = {
  id: "msn-housing-teaser-2026-08-17",
  kind: "third-party", publisher: "MSN",
  label: "Aion 2 reveals new dungeons and class concept enhancements; 'housing' up next",
  url: "https://www.msn.com/en-us/entertainment/general/aion-2-reveals-new-dungeons-and-class-concept-enhancements-housing-up-next/ar-AA29QqfP",
  publishedAt: "2026-08-11",
  retrievedAt: "2026-08-17",
  verifiedAt: "2026-08-17",
  localizations: localizations({
    "zh-hans": "Aion 2 公布新副本与职业概念增强，住房系统紧随其后",
    en: "Aion 2 reveals new dungeons and class concept enhancements; 'housing' up next",
    fr: "Aion 2 dévoile de nouveaux donjons et des améliorations de concepts de classes ; 'housing' à venir",
    de: "Aion 2 enthüllt neue Dungeons und Klassenkonzept-Verbesserungen; 'Housing' als Nächstes",
    es: "Aion 2 revela nuevas mazmorras y mejoras de conceptos de clases; 'housing' a continuación",
    ja: "Aion 2、新ダンジョンとクラスコンセプト強化を発表、『ハウジング』は次に",
    "pt-br": "Aion 2 revela novos calabouços e melhorias de conceitos de classes; 'housing' por vir",
    ru: "Aion 2 показал новые подземелья и улучшения концепций классов; дальше — 'жильё'",
    ko: "Aion 2, 새 던전과 클래스 콘셉트 개선 공개, '하우징'은 다음",
    "zh-hant": "Aion 2 公布新副本與職業概念增強，住房系統緊隨其後",
  }, "https://www.msn.com/en-us/entertainment/general/aion-2-reveals-new-dungeons-and-class-concept-enhancements-housing-up-next/ar-AA29QqfP"),
};

const housingSource2: ContentSource = {
  id: "aion2hub-housing-2026-08-17",
  kind: "third-party", publisher: "AION2Hub",
  label: "AION 2 Global — Release Date & Pre-registration Hub",
  url: "https://aion2hub.com/",
  publishedAt: "2026-08-01",
  retrievedAt: "2026-08-17",
  verifiedAt: "2026-08-17",
  localizations: localizations({
    "zh-hans": "AION 2 全球版——上线日期与预注册中心",
    en: "AION 2 Global — Release Date & Pre-registration Hub",
    fr: "AION 2 Global — Hub de date de sortie et de pré-inscription",
    de: "AION 2 Global — Hub für Veröffentlichungsdatum und Vorregistrierung",
    es: "AION 2 Global — Centro de fecha de lanzamiento y preinscripción",
    ja: "AION 2 グローバル — リリース日・事前登録ハブ",
    "pt-br": "AION 2 Global — Hub de data de lançamento e pré-registro",
    ru: "AION 2 Global — Хаб даты релиза и предрегистрации",
    ko: "AION 2 글로벌 — 출시일·사전등록 허브",
    "zh-hant": "AION 2 全球版——上線日期與預註冊中心",
  }, "https://aion2hub.com/"),
};

const housingSource3: ContentSource = {
  id: "mmobomb-dev-stream-housing-2026-08-17",
  kind: "third-party", publisher: "MMOBomb",
  label: "NC Shares What Aion 2 Players Can Expect At Launch On First Global Dev Stream",
  url: "https://www.mmobomb.com/news/nc-shares-what-aion-2-players-can-expect-launch-first-global-dev-stream",
  publishedAt: "2026-08-10",
  retrievedAt: "2026-08-17",
  verifiedAt: "2026-08-17",
  localizations: localizations({
    "zh-hans": "NC 首次全球开发者直播：Aion 2 玩家可期待什么",
    en: "NC Shares What Aion 2 Players Can Expect At Launch On First Global Dev Stream",
    fr: "NC partage ce que les joueurs d'Aion 2 peuvent attendre du lancement lors du premier dev stream mondial",
    de: "NC teilt mit, was Aion 2-Spieler beim Launch vom ersten globalen Dev-Stream erwarten können",
    es: "NC comparte lo que los jugadores de Aion 2 pueden esperar en el lanzamiento en el primer dev stream global",
    ja: "NCが初のグローバル開発者ストリームでAion 2プレイヤーが発売時に期待できることを共有",
    "pt-br": "NC compartilha o que os jogadores de Aion 2 podem esperar no lançamento no primeiro dev stream global",
    ru: "NC делится тем, что игроки Aion 2 могут ожидать от запуска на первом глобальном стриме разработчиков",
    ko: "NC, 첫 글로벌 개발자 스트림에서 Aion 2 플레이어가 출시 시 기대할 수 있는 것 공유",
    "zh-hant": "NC 首次全球開發者直播：Aion 2 玩家可期待什麼",
  }, "https://www.mmobomb.com/news/nc-shares-what-aion-2-players-can-expect-launch-first-global-dev-stream"),
};

const housingHero: ContentHeroImage = {
  src: "https://blogfiles.ncsoft.net/news/af7330da-4ff6-4b58-aece-400e6061a3be.jpg",
  width: 1100, height: 605,
  credit: "NC Corporation",
  sourceUrl: "https://aion2.plaync.com/ko-kr/board/notice",
  rights: "linked-official-media",
  translations: {
    "zh-hans": { alt: "Aion 2 住房系统前瞻配图", caption: "NC 官方配图；住房系统被预告为第一章第二部分之后的下一个重大新增内容。" },
    en: { alt: "Aion 2 housing system preview image", caption: "Official NC artwork; housing was teased as the next major addition after Chapter 1 Part 2." },
    fr: { alt: "Image d'aperçu du système de logement Aion 2", caption: "Visuel officiel NC ; le logement a été teasé comme prochain ajout majeur après le chapitre 1 partie 2." },
    de: { alt: "Aion 2 Housing-System-Vorschau-Bild", caption: "Offizielles NC-Artwork; Housing wurde als nächste große Ergänzung nach Kapitel 1 Teil 2 angedeutet." },
    es: { alt: "Imagen de avance del sistema de vivienda de Aion 2", caption: "Arte oficial de NC; se adelantó la vivienda como próxima gran adición tras el capítulo 1 parte 2." },
    ja: { alt: "Aion 2 ハウジングシステムプレビュー画像", caption: "NC公式アートワーク；ハウジングが第1章パート2後の次なる大型追加として予告されました。" },
    "pt-br": { alt: "Imagem de prévia do sistema de housing do Aion 2", caption: "Arte oficial da NC; housing foi adiantado como próxima grande adição após o capítulo 1 parte 2." },
    ru: { alt: "Превью-изображение системы жилья Aion 2", caption: "Официальный арт NC; жильё анонсировано как следующее крупное дополнение после главы 1 части 2." },
    ko: { alt: "Aion 2 하우징 시스템 프리뷰 이미지", caption: "NC 공식 이미지입니다. 하우징이 챕터 1 파트 2 이후 다음 주요 추가 기능으로 예고되었습니다." },
    "zh-hant": { alt: "Aion 2 住房系統前瞻配圖", caption: "NC 官方配圖；住房系統被預告為第一章第二部分之後的下一個重大新增內容。" },
  },
};

export const trendingAugust17Article3: ContentEntry = {
  section: "guides",
  slug: "aion-2-housing-system-preview",
  schemaType: "Article",
  publishedAt: "2026-08-17",
  updatedAt: "2026-08-17",
  readingMinutes: 5,
  publication: publishedVerified,
  sources: [housingSource1, housingSource2, housingSource3],
  heroImage: housingHero,
  related: [
    { kind: "content", section: "news", slug: "aion-2-update-preview-new-dungeons-housing" },
    { kind: "content", section: "guides", slug: "chapter-1-content-guide-global" },
    { kind: "content", section: "guides", slug: "aion-2-global-server-regions-guide" },
  ],
  translations: {
    en: articleCopy(guideLabels, "en", 5, {
      eyebrow: "SYSTEM PREVIEW",
      title: "Aion 2 Housing System Preview: What NCSoft's Teaser Tells Us & What to Expect",
      description: "NCSoft teased a housing system as the next major addition after Aion 2's Chapter 1 Part 2 update. Here's what we know, what it could include, and realistic timelines for KR and global players.",
      intro: "During the August 11, 2026 update preview broadcast, NCSoft confirmed that a housing system is 'up next' after Chapter 1 Part 2 — the first official mention of player housing in Aion 2. Details are scarce by design, so this guide separates what's confirmed from what's speculative, and gives you realistic expectations for both the Korean service and the September 30 global launch.",
      sourceNote: "Based on MSN's August 11 coverage of the preview broadcast, AION2Hub's global service hub, and MMOBomb's dev stream recap. Speculative content is clearly labeled as such.",
      keywords: ["Aion 2 housing", "Aion 2 housing system", "Aion 2 player housing", "Aion 2 future content", "Aion 2 global housing timeline"],
      sections: [
        section("confirmed", "What Was Confirmed", ["NCSoft confirmed housing is the next major system following the Chapter 1 Part 2 update on the Korean service. That's the extent of official detail — no release date, feature list, or screenshots were shared during the preview broadcast.", "The positioning is significant: housing was teased as a headline roadmap item rather than a minor QoL addition, which suggests it will be a substantial feature investment for the game."]),
        section("expectations", "What Housing Could Include (Speculative)", ["This section is speculatory. Based on MMO conventions and the legacy Aion's housing offerings, players reasonably expect private instanced or neighborhood-based homes, decoration and furnishing options, and social features such as visiting friends' homes.", "Aion 2's strong customization systems — 200+ customization options and transmogrification — make cosmetic-heavy housing a natural fit. Whether housing will offer gameplay bonuses (storage, buffs, crafting stations) or stay purely cosmetic is unknown, and NCSoft has made no statements either way."]),
        section("timeline", "Timeline: KR vs Global", ["On the Korean service, housing arrives after Chapter 1 Part 2 — expect the earliest information to surface in the months following the August 12 patch. NCSoft typically details roadmap features in preview broadcasts before deployment.", "For global players, the September 30 early access is the priority milestone. Housing will almost certainly not be available at global launch; realistic expectations put it months after launch, in line with how NCSoft has rolled out KR content to the global build."]),
        section("what-to-do", "What Players Should Do Now", ["Do not build launch plans around housing. Instead, prepare for the systems confirmed for launch: eight classes, five server regions, Founder's Packs, and the core dungeon-to-raid endgame.", "Keep an eye on KR preview broadcasts and the official notice board after the August 12 patch — that's where housing details will first appear. Bookmark our hub for coverage the moment NCSoft shares more."]),
      ],
    }),
    "zh-hans": articleCopy(guideLabels, "zh-hans", 5, {
      eyebrow: "系统前瞻",
      title: "Aion 2 住房系统前瞻：NCSoft 的预告告诉我们什么，以及可期待什么",
      description: "NCSoft 预告住房系统将是 Aion 2 第一章第二部分更新后的下一个重大新增内容。以下是我们已知的信息、它可能包含什么，以及韩服与全球玩家现实的时间预期。",
      intro: "在 2026 年 8 月 11 日的更新预览直播中，NCSoft 确认住房系统将在第一章第二部分之后到来——这是 Aion 2 首次官方提及玩家住房。细节刻意从简，因此本攻略将已确认的信息与推测区分开，并为韩服和 9 月 30 日全球上线的玩家提供现实预期。",
      sourceNote: "基于 MSN 8 月 11 日预览直播报道、AION2Hub 全球服信息中心及 MMOBomb 开发者直播总结。推测内容均已明确标注。",
      keywords: ["Aion 2 住房", "Aion 2 住房系统", "Aion 2 玩家住房", "Aion 2 未来内容", "Aion 2 全球住房时间线"],
      sections: [
        section("confirmed", "已确认的信息", ["NCSoft 确认住房系统是韩服第一章第二部分更新后的下一个重大系统。官方细节仅此而已——预览直播期间未分享上线日期、功能清单或截图。", "定位意义重大：住房被作为路线图头条项目而非次要体验优化提及，这表明它将是游戏一项实质性的功能投入。"]),
        section("expectations", "住房可能包含什么（推测）", ["本节为推测内容。基于 MMO 惯例和初代 Aion 的住房设定，玩家合理地期待私人实例或街区式住宅、装饰与布置选项，以及拜访好友住宅等社交功能。", "Aion 2 强大的自定义系统（200+ 自定义选项与幻化）使重度外观型住房成为自然选择。住房是否提供玩法增益（仓库、增益、制作台）或保持纯外观未知，NCSoft 未就此发表任何声明。"]),
        section("timeline", "时间线：韩服 vs 全球服", ["在韩服，住房在第一章第二部分之后到来——最早的信息预计在 8 月 12 日补丁后的数月内公布。NCSoft 通常在预览直播中详述部署前的路线图功能。", "对全球玩家而言，9 月 30 日抢先体验是优先里程碑。住房几乎肯定不会在全球上线时提供；现实预期是上线后数月，与 NCSoft 将韩服内容推向全球版本的节奏一致。"]),
        section("what-to-do", "玩家现在应该做什么", ["不要围绕住房制定上线计划。相反，请为已确认的上线系统做准备：八个职业、五个服务器区域、创始人包，以及从副本到团本的核心后期玩法。", "请关注 8 月 12 日补丁后韩服预览直播与官方公告板——住房细节将首先在那里出现。收藏本站，NCSoft 公布更多信息时我们将第一时间报道。"]),
      ],
    }),
    ko: articleCopy(guideLabels, "ko", 5, {
      eyebrow: "시스템 프리뷰",
      title: "Aion 2 하우징 시스템 프리뷰: NCSoft 티저가 알려주는 것과 기대할 것",
      description: "NCSoft는 하우징 시스템이 Aion 2 챕터 1 파트 2 업데이트 다음으로 오는 주요 추가 기능임을 예고했습니다. 확인된 정보, 포함될 가능성, KR·글로벌 플레이어를 위한 현실적인 일정입니다.",
      intro: "2026년 8월 11일 업데이트 프리뷰 방송에서 NCSoft는 하우징 시스템이 챕터 1 파트 2 이후에 온다고 확인했습니다 — Aion 2에서 플레이어 하우징에 대한 첫 공식 언급입니다. 세부 사항은 의도적으로 최소화되어 있어, 이 가이드는 확인된 정보와 추측을 구분하고 한국 서비스와 9월 30일 글로벌 출시에 대한 현실적인 기대치를 제공합니다.",
      sourceNote: "MSN의 8월 11일 프리뷰 방송 보도, AION2Hub 글로벌 서비스 허브, MMOBomb 개발자 스트림 요약에 기반합니다. 추측 내용은 명확히 표시되어 있습니다.",
      keywords: ["Aion 2 하우징", "Aion 2 하우징 시스템", "Aion 2 플레이어 하우징", "Aion 2 미래 콘텐츠", "Aion 2 글로벌 하우징 일정"],
      sections: [
        section("confirmed", "확인된 정보", ["NCSoft는 하우징 시스템이 한국 서비스의 챕터 1 파트 2 업데이트 이후 오는 다음 주요 시스템임을 확인했습니다. 공식 세부 사항은 여기까지입니다 — 프리뷰 방송에서 출시일, 기능 목록, 스크린샷은 공유되지 않았습니다.", "이 배치는 의미가 큽니다: 하우징은 사소한 QoL 추가가 아니라 로드맵 헤드라인 항목으로 공개되었으며, 이는 상당한 기능 투자가 될 것임을 시사합니다."]),
        section("expectations", "하우징에 포함될 수 있는 것 (추측)", ["이 섹션은 추측입니다. MMO 관례와 원작 Aion의 하우징을 고려할 때, 플레이어는 개인 인스턴스 또는 이웃 기반 주택, 장식·배치 옵션, 친구 집 방문 같은 소셜 기능을 합리적으로 기대합니다.", "200개 이상의 커스터마이징 옵션과 트랜스모그를 갖춘 Aion 2의 강력한 커스터마이징 시스템은 외관 중심의 하우징과 자연스럽게 어울립니다. 하우징이 게임플레이 보너스(창고, 버프, 제작 스테이션)를 제공할지, 순수 코스메틱으로 유지될지는 알 수 없으며 NCSoft는 어느 쪽도 언급하지 않았습니다."]),
        section("timeline", "일정: KR vs 글로벌", ["한국 서비스에서 하우징은 챕터 1 파트 2 이후에 도착합니다 — 가장 이른 정보는 8월 12일 패치 이후 수개월 내에 공개될 것으로 예상합니다. NCSoft는 일반적으로 배포 전 프리뷰 방송에서 로드맵 기능을 상세히 설명합니다.", "글로벌 플레이어에게 9월 30일 얼리 액세스가 우선 이정표입니다. 하우징은 글로벌 출시 때 제공될 가능성이 거의 없으며, 현실적인 기대치는 NCSoft가 KR 콘텐츠를 글로벌 빌드에 적용해온 방식에 비춰 출시 후 수개월입니다."]),
        section("what-to-do", "플레이어가 지금 해야 할 일", ["하우징을 중심으로 출시 계획을 세우지 마세요. 대신 출시 확정 시스템을 준비하세요: 8개 클래스, 5개 서버 지역, 파운더스 팩, 그리고 던전에서 레이드로 이어지는 핵심 엔드게임.", "8월 12일 패치 이후 KR 프리뷰 방송과 공식 게시판을 주시하세요 — 하우징 세부 사항이 가장 먼저 나타날 곳입니다. NCSoft가 더 공개하면 저희 허브가 가장 먼저 다룹니다."]),
      ],
    }),
    ja: articleCopy(guideLabels, "ja", 5, {
      eyebrow: "システムプレビュー",
      title: "Aion 2 ハウジングシステムプレビュー：NCSoft のティーザーが示すことと期待できること",
      description: "NCSoft は、ハウジングシステムが Aion 2 の第1章パート2アップデート後の次なる大型追加機能であると予告しました。判明していること、含まれうるもの、KR・グローバルプレイヤー向けの現実的な時期をまとめます。",
      intro: "2026年8月11日のアップデートプレビュー放送で、NCSoft はハウジングシステムが第1章パート2の後に来ることを確認しました — Aion 2 におけるプレイヤーハウジングへの初の公式言及です。詳細は意図的に最小限で、このガイドでは確定情報と推測を分け、韓国サービスと9月30日のグローバルローンチに現実的な期待値を提供します。",
      sourceNote: "MSN の8月11日プレビュー放送報道、AION2Hub のグローバルサービスハブ、MMOBomb の開発者ストリーム要約に基づきます。推測内容は明確にラベルされています。",
      keywords: ["Aion 2 ハウジング", "Aion 2 ハウジングシステム", "Aion 2 プレイヤーハウジング", "Aion 2 将来コンテンツ", "Aion 2 グローバルハウジング時期"],
      sections: [
        section("confirmed", "確認されていること", ["NCSoft は、ハウジングシステムが韓国サービスの第1章パート2アップデート後の次の主要システムであることを確認しました。公式の詳細はここまでです — プレビュー放送ではリリース日、機能リスト、スクリーンショットは公開されませんでした。", "この位置づけは重要です：ハウジングは軽微なQoL追加ではなく、ロードマップのヘッドライン項目として公開されており、実質的な機能投資になることが示唆されます。"]),
        section("expectations", "ハウジングに含まれうるもの（推測）", ["このセクションは推測です。MMO の慣例と旧作 Aion のハウジングを踏まえると、プレイヤーはプライベートインスタンスまたは近隣ベースの住居、装飾・配置オプション、フレンドの家を訪問するようなソーシャル機能を合理的に期待します。", "200以上のカスタマイズオプションとトランスモグを備えた Aion 2 の強力なカスタマイズシステムは、外観重視のハウジングと自然に合致します。ハウジングがゲームプレイボーナス（倉庫、バフ、クラフトステーション）を提供するか、純粋にコスメティックに留まるかは不明で、NCSoft はどちらも言明していません。"]),
        section("timeline", "時期: KR vs グローバル", ["韓国サービスでは、ハウジングは第1章パート2の後に到着します — 最も早い情報は8月12日パッチ後の数ヶ月以内に表面化すると予想されます。NCSoft は通常、展開前にプレビュー放送でロードマップ機能を詳述します。", "グローバルプレイヤーにとって、9月30日の早期アクセスが優先マイルストーンです。ハウジングがグローバルローンチ時に利用可能になることはほぼなく、現実的には NCSoft が KR コンテンツをグローバルビルドに展開してきた方針に合わせ、ローンチ後数ヶ月となるでしょう。"]),
        section("what-to-do", "プレイヤーが今すべきこと", ["ハウジングを中心にローンチ計画を立てないでください。代わりに、ローンチ確定システムを準備しましょう：8クラス、5サーバーリージョン、ファウンダーズパック、ダンジョンからレイドへのコアなエンドゲーム。", "8月12日パッチ後の KR プレビュー放送と公式掲示板に注目してください — ハウジングの詳細はそこに最初に現れます。NCSoft がさらに公開したら、当ハブが最初に報じます。"]),
      ],
    }),
    fr: articleCopy(guideLabels, "fr", 5, {
      eyebrow: "APERÇU SYSTÈME",
      title: "Aperçu du système de logement d'Aion 2 : ce que le teaser de NCSoft nous dit et ce qu'il faut attendre",
      description: "NCSoft a teasé un système de logement comme prochain ajout majeur après le chapitre 1 partie 2. Voici ce que l'on sait, ce qu'il pourrait inclure et des délais réalistes pour KR et global.",
      intro: "Le 11 août 2026, NCSoft a confirmé qu'un système de logement 'arrive après' le chapitre 1 partie 2 — la première mention officielle du logement joueur dans Aion 2. Ce guide distingue le confirmé du spéculatif.",
      sourceNote: "Basé sur la couverture MSN du 11 août, le hub AION2Hub et le récapitulatif MMOBomb. Le contenu spéculatif est clairement étiqueté.",
      keywords: ["Aion 2 logement", "Aion 2 système de logement", "Aion 2 contenu futur", "Aion 2 délai logement global"],
      sections: [
        section("confirmed", "Ce qui a été confirmé", ["NCSoft a confirmé que le logement est la prochaine grande nouveauté après le chapitre 1 partie 2 sur le service coréen. Aucune autre précision n'a été donnée.", "La position est significative : le logement est présenté comme un élément de feuille de route majeur, pas une simple amélioration de confort."]),
        section("expectations", "Ce que le logement pourrait inclure (spéculatif)", ["À en juger par les conventions MMO et l'Aion original : maisons instanciées ou quartiers, décoration et fonctionnalités sociales.", "Les systèmes de personnalisation d'Aion 2 s'y prêtent naturellement. Les bonus de gameplay restent inconnus."]),
        section("timeline", "Calendrier : KR vs global", ["Sur KR, le logement arrive après le chapitre 1 partie 2. Pour le global, le lancement du 30 septembre est la priorité — attendez-vous au logement des mois après le lancement."]),
        section("what-to-do", "Que faire maintenant", ["Ne bâtissez pas votre plan de lancement autour du logement. Préparez les systèmes confirmés : huit classes, cinq régions, packs Fondateur et l'endgame donjons-raids."]),
      ],
    }),
    de: articleCopy(guideLabels, "de", 5, {
      eyebrow: "SYSTEMVORSCHAU",
      title: "Aion 2 Housing-System-Vorschau: Was NCSofts Teaser uns sagt & was zu erwarten ist",
      description: "NCSoft teaserte ein Housing-System als nächste große Ergänzung nach Aion 2s Kapitel-1-Teil-2-Update. Was wir wissen, was es enthalten könnte und realistische Zeitpläne.",
      intro: "Am 11. August 2026 bestätigte NCSoft, dass ein Housing-System 'als Nächstes' nach Kapitel 1 Teil 2 kommt. Dieser Guide trennt Bestätigtes von Spekulativem.",
      sourceNote: "Basierend auf MSNs Berichterstattung vom 11. August, AION2Hub-Hub und MMOBomb-Recap. Spekulative Inhalte sind klar gekennzeichnet.",
      keywords: ["Aion 2 Housing", "Aion 2 Housing-System", "Aion 2 zukünftige Inhalte", "Aion 2 Housing-Zeitplan"],
      sections: [
        section("confirmed", "Was bestätigt wurde", ["NCSoft bestätigte, dass Housing die nächste große Erweiterung nach Kapitel 1 Teil 2 auf dem koreanischen Dienst ist. Weitere Details gibt es nicht.", "Die Positionierung ist bedeutsam: Housing gilt als Headline-Roadmap-Punkt, nicht als kleine QoL-Funktion."]),
        section("expectations", "Was Housing enthalten könnte (spekulativ)", ["Nach MMO-Konventionen und dem Original-Aion: instanziierte Häuser oder Nachbarschaften, Dekoration und soziale Funktionen.", "Die starken Anpassungssysteme von Aion 2 passen natürlich dazu. Gameplay-Boni bleiben unklar."]),
        section("timeline", "Zeitplan: KR vs. Global", ["Auf KR kommt Housing nach Kapitel 1 Teil 2. Für Global ist der 30. September Vorrang; Housing erst Monate nach dem Launch."]),
        section("what-to-do", "Was Spieler jetzt tun sollten", ["Planen Sie nicht um Housing herum. Bereiten Sie sich auf die bestätigten Systeme vor: acht Klassen, fünf Regionen, Founder's Packs und Dungeon-Raid-Endgame."]),
      ],
    }),
    es: articleCopy(guideLabels, "es", 5, {
      eyebrow: "AVANCE DEL SISTEMA",
      title: "Avance del sistema de vivienda de Aion 2: qué nos dice el adelanto de NCSoft y qué esperar",
      description: "NCSoft adelantó un sistema de vivienda como la próxima gran adición tras el capítulo 1 parte 2. Qué sabemos, qué podría incluir y plazos realistas para KR y global.",
      intro: "El 11 de agosto de 2026, NCSoft confirmó que un sistema de vivienda 'viene después' del capítulo 1 parte 2. Esta guía separa lo confirmado de lo especulativo.",
      sourceNote: "Basado en la cobertura de MSN del 11 de agosto, el hub de AION2Hub y el resumen de MMOBomb. El contenido especulativo está claramente etiquetado.",
      keywords: ["Aion 2 vivienda", "Aion 2 sistema de vivienda", "Aion 2 contenido futuro", "Aion 2 plazo de vivienda global"],
      sections: [
        section("confirmed", "Lo que se confirmó", ["NCSoft confirmó que la vivienda es la próxima gran novedad tras el capítulo 1 parte 2 en el servicio coreano. No se dieron más detalles.", "La posición es significativa: la vivienda se presenta como un punto clave de la hoja de ruta, no una simple mejora."]),
        section("expectations", "Qué podría incluir la vivienda (especulativo)", ["Por convenciones MMO y el Aion original: casas instanciadas o barrios, decoración y funciones sociales.", "Los sistemas de personalización de Aion 2 encajan de forma natural. Los bonos de juego siguen siendo desconocidos."]),
        section("timeline", "Cronograma: KR vs global", ["En KR, la vivienda llega tras el capítulo 1 parte 2. Para global, el 30 de septiembre es la prioridad; la vivienda llegará meses después del lanzamiento."]),
        section("what-to-do", "Qué hacer ahora", ["No construyas tu plan de lanzamiento alrededor de la vivienda. Prepara los sistemas confirmados: ocho clases, cinco regiones, paquetes de fundador y el endgame de mazmorras y raids."]),
      ],
    }),
    "pt-br": articleCopy(guideLabels, "pt-br", 5, {
      eyebrow: "PRÉVIA DO SISTEMA",
      title: "Prévia do sistema de housing de Aion 2: o que o teaser da NCSoft nos diz e o que esperar",
      description: "A NCSoft deu um teaser de um sistema de housing como próxima grande adição após o capítulo 1 parte 2. O que sabemos, o que pode incluir e prazos realistas para KR e global.",
      intro: "Em 11 de agosto de 2026, a NCSoft confirmou que um sistema de housing 'vem a seguir' ao capítulo 1 parte 2. Este guia separa o confirmado do especulativo.",
      sourceNote: "Baseado na cobertura da MSN de 11 de agosto, no hub da AION2Hub e no resumo da MMOBomb. Conteúdo especulativo claramente rotulado.",
      keywords: ["Aion 2 housing", "Aion 2 sistema de housing", "Aion 2 conteúdo futuro", "Aion 2 prazo de housing global"],
      sections: [
        section("confirmed", "O que foi confirmado", ["A NCSoft confirmou que housing é a próxima grande novidade após o capítulo 1 parte 2 no serviço coreano. Nenhum outro detalhe foi dado.", "A posição é significativa: housing é apresentado como um item de destaque do roteiro, não uma mera melhoria."]),
        section("expectations", "O que housing pode incluir (especulativo)", ["Por convenções de MMO e o Aion original: casas instanciadas ou bairros, decoração e funções sociais.", "Os sistemas de personalização de Aion 2 se encaixam naturalmente. Bônus de gameplay permanecem desconhecidos."]),
        section("timeline", "Cronograma: KR vs global", ["Na KR, housing chega após o capítulo 1 parte 2. Para o global, 30 de setembro é a prioridade; housing virá meses após o lançamento."]),
        section("what-to-do", "O que fazer agora", ["Não construa seu plano de lançamento em torno de housing. Prepare os sistemas confirmados: oito classes, cinco regiões, pacotes de fundador e o endgame de masmorras e raids."]),
      ],
    }),
    ru: articleCopy(guideLabels, "ru", 5, {
      eyebrow: "ПРЕВЬЮ СИСТЕМЫ",
      title: "Превью системы жилья Aion 2: что говорит тизер NCSoft и чего ждать",
      description: "NCSoft намекнула на систему жилья как следующее крупное дополнение после главы 1 части 2. Что известно, что может войти и реальные сроки для KR и глобала.",
      intro: "11 августа 2026 года NCSoft подтвердила, что система жилья 'идёт следующей' после главы 1 части 2. Этот гайд отделяет подтверждённое от предположительного.",
      sourceNote: "На основе материала MSN от 11 августа, хаба AION2Hub и резюме MMOBomb. Предположительный контент явно помечен.",
      keywords: ["Aion 2 жильё", "Aion 2 система жилья", "Aion 2 будущий контент", "Aion 2 сроки жилья"],
      sections: [
        section("confirmed", "Что подтверждено", ["NCSoft подтвердила, что жильё — следующее крупное дополнение после главы 1 части 2 на корейском сервисе. Больше деталей нет.", "Позиционирование значимо: жильё представлено как заглавный пункт дорожной карты, а не мелкое улучшение."]),
        section("expectations", "Что может включать жильё (предположительно)", ["По конвенциям MMO и оригинальному Aion: инстанс-дома или районы, декор и социальные функции.", "Сильные системы кастомизации Aion 2 естественно подходят. Игровые бонусы остаются неизвестны."]),
        section("timeline", "Сроки: KR против глобала", ["На KR жильё придёт после главы 1 части 2. Для глобала приоритет — 30 сентября; жильё — месяцы после запуска."]),
        section("what-to-do", "Что делать сейчас", ["Не стройте план запуска вокруг жилья. Готовьтесь к подтверждённым системам: восемь классов, пять регионов, наборы основателя и эндгейм данжи-рейды."]),
      ],
    }),
    "zh-hant": articleCopy(guideLabels, "zh-hant", 5, {
      eyebrow: "系統前瞻",
      title: "Aion 2 住房系統前瞻：NCSoft 的預告告訴我們什麼，以及可期待什麼",
      description: "NCSoft 預告住房系統將是 Aion 2 第一章第二部分更新後的下一個重大新增內容。以下是我們已知的資訊、它可能包含什麼，以及韓服與全球玩家現實的時間預期。",
      intro: "在 2026 年 8 月 11 日的更新預覽直播中，NCSoft 確認住房系統將在第一章第二部分之後到來——這是 Aion 2 首次官方提及玩家住房。細節刻意從簡，因此本攻略將已確認的資訊與推測區分開，並為韓服和 9 月 30 日全球上線的玩家提供現實預期。",
      sourceNote: "基於 MSN 8 月 11 日預覽直播報導、AION2Hub 全球服資訊中心及 MMOBomb 開發者直播總結。推測內容均已明確標註。",
      keywords: ["Aion 2 住房", "Aion 2 住房系統", "Aion 2 玩家住房", "Aion 2 未來內容", "Aion 2 全球住房時間線"],
      sections: [
        section("confirmed", "已確認的資訊", ["NCSoft 確認住房系統是韓服第一章第二部分更新後的下一個重大系統。官方細節僅此而已——預覽直播期間未分享上線日期、功能清單或截圖。", "定位意義重大：住房被作為路線圖頭條項目而非次要體驗最佳化提及，這表明它將是遊戲一項實質性的功能投入。"]),
        section("expectations", "住房可能包含什麼（推測）", ["本節為推測內容。基於 MMO 慣例和初代 Aion 的住房設定，玩家合理地期待私人實例或街區式住宅、裝飾與佈置選項，以及拜訪好友住宅等社交功能。", "Aion 2 強大的自訂系統（200+ 自訂選項與幻化）使重度外觀型住房成為自然選擇。住房是否提供玩法增益（倉庫、增益、製作台）或保持純外觀未知，NCSoft 未就此發表任何聲明。"]),
        section("timeline", "時間線：韓服 vs 全球服", ["在韓服，住房在第一章第二部分之後到來——最早的資訊預計在 8 月 12 日補丁後的數月內公佈。NCSoft 通常在預覽直播中詳述部署前的路線圖功能。", "對全球玩家而言，9 月 30 日搶先體驗是優先里程碑。住房幾乎肯定不會在全球上線時提供；現實預期是上線後數月，與 NCSoft 將韓服內容推向全球版本的節奏一致。"]),
        section("what-to-do", "玩家現在應該做什麼", ["不要圍繞住房制定上線計畫。相反，請為已確認的上線系統做準備：八個職業、五個伺服器區域、創始人包，以及從副本到團本的核心後期玩法。", "請關注 8 月 12 日補丁後韓服預覽直播與官方公告板——住房細節將首先在那裡出現。收藏本站，NCSoft 公佈更多資訊時我們將第一時間報導。"]),
      ],
    }),
  },
};