import { articleCopy, localizations, newsLabels, publishedVerified, section } from "./trending-september-1-shared";
import type { ContentEntry, ContentHeroImage, ContentSource } from "./content-registry";

/* ARTICLE 5 — Samjong KPMG: Korean game industry faces six changes; what they mean for Aion 2 / July-batch anchor */

const kpmgSource1: ContentSource = {
  id: "intn-kpmg-six-changes-2026-08-31",
  kind: "third-party", publisher: "intn.co.kr",
  label: "삼정KPMG “게임 산업, IP·피지컬 AI·중국·비용 등 ‘6대 변화’ 직면”",
  url: "https://news.google.com/rss/search?q=%EC%82%BC%EC%A0%95KPMG%20%EA%B2%8C%EC%9E%84%20%EC%82%B0%EC%97%85&hl=ko&gl=KR&ceid=KR:ko",
  publishedAt: "2026-08-31",
  retrievedAt: "2026-09-01",
  verifiedAt: "2026-09-01",
  localizations: localizations({
    "zh-hans": "三正 KPMG：「游戏产业面临 IP、物理 AI、中国、成本等 6 大变化」",
    en: "Samjong KPMG: the game industry faces six changes — IP, physical AI, China, cost, and more",
    fr: "Samjong KPMG : l'industrie du jeu face à six mutations — IP, IA physique, Chine, coûts, etc.",
    de: "Samjong KPMG: Die Games-Branche steht vor sechs Veränderungen — IP, physische KI, China, Kosten u.a.",
    es: "Samjong KPMG: la industria del videojuego enfrenta seis cambios — IP, IA física, China, costes, etc.",
    ja: "サムジョンKPMG：「ゲーム産業はIP・フィジカルAI・中国・コストなど『6大変化』に直面」",
    "pt-br": "Samjong KPMG: a indústria de jogos enfrenta seis mudanças — IP, IA física, China, custos, etc.",
    ru: "Samjong KPMG: игровая индустрия сталкивается с шестью изменениями — IP, физический ИИ, Китай, издержки и др.",
    ko: "삼정KPMG “게임 산업, IP·피지컬 AI·중국·비용 등 ‘6대 변화’ 직면”",
    "zh-hant": "三正 KPMG：「遊戲產業面臨 IP、物理 AI、中國、成本等 6 大變化」",
  }, "https://news.google.com/rss/search?q=%EC%82%BC%EC%A0%95KPMG%20%EA%B2%8C%EC%9E%84%20%EC%82%B0%EC%97%85&hl=ko&gl=KR&ceid=KR:ko"),
};

const kpmgSource2: ContentSource = {
  id: "kpmg-insights-six-questions-2026-08-28",
  kind: "third-party", publisher: "KPMG (Samjong)",
  label: "6대 핵심 질문으로 본 게임 산업의 변화 (KPMG report, title-verified)",
  url: "https://news.google.com/rss/search?q=%ED%95%B5%EC%8B%AC%20%EC%A7%88%EB%AC%B8%EC%9C%BC%EB%A1%9C%20%EB%B3%B8%20%EA%B2%8C%EC%9E%84%20%EC%82%B0%EC%97%85%20%EB%B3%80%ED%99%94&hl=ko&gl=KR&ceid=KR:ko",
  publishedAt: "2026-08-28",
  retrievedAt: "2026-09-01",
  verifiedAt: "2026-09-01",
  localizations: localizations({
    "zh-hans": "通过 6 个核心问题看游戏产业的变化（KPMG 报告）",
    en: "Changes in the game industry through six key questions (KPMG report)",
    fr: "Les mutations de l'industrie du jeu à travers six questions clés (rapport KPMG)",
    de: "Wandel der Games-Branche anhand von sechs Kernfragen (KPMG-Bericht)",
    es: "Cambios en la industria del videojuego a través de seis preguntas clave (informe KPMG)",
    ja: "6つの核心的質問から見るゲーム産業の変化（KPMGレポート）",
    "pt-br": "Mudanças na indústria de jogos por seis questões-chave (relatório KPMG)",
    ru: "Изменения игровой индустрии через шесть ключевых вопросов (отчёт KPMG)",
    ko: "6대 핵심 질문으로 본 게임 산업의 변화 (KPMG 보고서)",
    "zh-hant": "透過 6 個核心問題看遊戲產業的變化（KPMG 報告）",
  }, "https://news.google.com/rss/search?q=%ED%95%B5%EC%8B%AC%20%EC%A7%88%EB%AC%B8%EC%9C%BC%EB%A1%9C%20%EB%B3%B8%20%EA%B2%8C%EC%9E%84%20%EC%82%B0%EC%97%85%20%EB%B3%80%ED%99%94&hl=ko&gl=KR&ceid=KR:ko"),
};

const kpmgHero: ContentHeroImage = {
  src: "https://blogfiles.ncsoft.net/news/af7330da-4ff6-4b58-aece-400e6061a3be.jpg",
  width: 1100, height: 605,
  credit: "NC Corporation",
  sourceUrl: "https://aion2.plaync.com/ja-jp/board/notice/list",
  rights: "linked-official-media",
  translations: {
    "zh-hans": { alt: "三正 KPMG 游戏产业报告新闻配图", caption: "NC 官方配图；三正 KPMG 报告指韩国游戏产业面临 IP、物理 AI、中国、成本等 6 大变化，Aion 2 作为全球化样本被置于该语境。" },
    en: { alt: "Samjong KPMG game industry report news image", caption: "Official NC artwork; a Samjong KPMG report says the Korean game industry faces six changes — IP, physical AI, China, costs — and this site reads Aion 2's global launch against that backdrop." },
    fr: { alt: "Image du rapport Samjong KPMG sur l'industrie du jeu", caption: "Visuel officiel NC ; un rapport Samjong KPMG évoque six mutations pour l'industrie : IP, IA physique, Chine, coûts — le lancement mondial d'Aion 2 se lit dans ce contexte." },
    de: { alt: "Bild zum Samjong-KPMG-Branchenbericht", caption: "Offizielles NC-Artwork; ein Samjong-KPMG-Bericht nennt sechs Veränderungen für die Branche — IP, physische KI, China, Kosten; Aion 2s Weltstart liest sich vor diesem Hintergrund." },
    es: { alt: "Imagen del informe Samjong KPMG sobre la industria", caption: "Arte oficial de NC; un informe de Samjong KPMG menciona seis cambios para la industria — IP, IA física, China, costes; el lanzamiento mundial de Aion 2 se lee en ese contexto." },
    ja: { alt: "サムジョンKPMGゲーム産業レポート画像", caption: "NC公式アートワーク；サムジョンKPMG報告はゲーム産業がIP・フィジカルAI・中国・コストなど6大変化に直面するとし、アイオン2のグローバル発売はその文脈で読みます。" },
    "pt-br": { alt: "Imagem do relatório Samjong KPMG sobre a indústria", caption: "Arte oficial da NC; um relatório da Samjong KPMG cita seis mudanças para a indústria — IP, IA física, China, custos; o lançamento global do Aion 2 se lê nesse contexto." },
    ru: { alt: "Изображение отчёта Samjong KPMG об индустрии", caption: "Официальный арт NC; отчёт Samjong KPMG называет шесть изменений для индустрии — IP, физический ИИ, Китай, издержки; мировой запуск Aion 2 читается на этом фоне." },
    ko: { alt: "삼정KPMG 게임 산업 보고서 뉴스 이미지", caption: "NC 공식 이미지입니다. 삼정KPMG 보고서는 게임 산업이 IP·피지컬 AI·중국·비용 등 6대 변화에 직면한다고 하며, 아이온2의 글로벌 출시를 그 맥락에서 봅니다." },
    "zh-hant": { alt: "三正 KPMG 遊戲產業報告新聞配圖", caption: "NC 官方配圖；三正 KPMG 報告指韓國遊戲產業面臨 IP、物理 AI、中國、成本等 6 大變化，Aion 2 作為全球化樣本被置於該語境。" },
  },
};

export const trendingSeptember1Article5: ContentEntry = {
  section: "news",
  slug: "aion-2-korea-game-industry-six-changes-kpmg",
  schemaType: "NewsArticle",
  publishedAt: "2026-09-01",
  updatedAt: "2026-09-01",
  readingMinutes: 5,
  publication: publishedVerified,
  sources: [kpmgSource1, kpmgSource2],
  heroImage: kpmgHero,
  related: [
    { kind: "content", section: "news", slug: "aion-2-ncsoft-global-strategy-korea-playbook" },
    { kind: "content", section: "news", slug: "aion-2-ncsoft-h1-record-pc-revenue" },
    { kind: "content", section: "news", slug: "aion-2-release-date-october-5-2026" },
    { kind: "content", section: "guides", slug: "aion-2-monetization-f2p-cosmetics-guide" },
  ],
  translations: {
    en: articleCopy(newsLabels, "en", 5, {
      eyebrow: "INDUSTRY WATCH",
      title: "Korean Game Industry Faces Six Changes, KPMG Report Says: Where Aion 2 Fits",
      description: "A late-August Samjong KPMG report says the Korean game industry faces six structural changes — headlines name IP, physical AI, China, and costs — as publishers pivot to global-first strategies. Aion 2's October 5 launch is one concrete example of that pivot.",
      intro: "Behind every Aion 2 headline there is an industry context, and a late-August Samjong KPMG report supplies it. Korean business media on August 31 covered the report's finding that the local game industry faces six major changes — with headlines naming IP, physical AI, China, and cost pressure. This report summarizes what is verifiable about the report and reads Aion 2's global push against that backdrop.",
      sourceNote: "Based on Korean business-press coverage (intn.co.kr, August 31) of the Samjong KPMG report published August 28; headline-level facts only, as the full report text was not retrievable in this session.",
      keywords: ["Korean game industry 2026", "KPMG game industry report", "physical AI gaming", "Korean MMO global expansion", "Aion 2 industry context"],
      sections: [
        section("what-kpmg-says", "What the Report Is Reported to Say", ["On August 31, Korean business media covered a Samjong KPMG report (published August 28) under headlines stating the game industry faces six major changes — IP, physical AI, China, and cost pressure among them.", "The report's working title in the coverage is about “the changes in the game industry through six key questions”. Because the full text was not retrievable in this session, this article stays at the headline level for the six-change list.", "The thematic direction is consistent across outlets: users, IP, and AI are the reorganization axes, and physical AI — robotics, autonomous driving, manufacturing, defense, mobility — is presented as a new growth front for games companies."]),
        section("aion2-in-context", "Where Aion 2 Sits in That Picture", ["Aion 2's October 5 global launch is a direct product of the IP-driven pivot the report describes: NCsoft is extending a proven MMO IP beyond its domestic base rather than starting from a new market with a new lore.", "Cost pressure is visible in the report's framing: global-first development amortizes content spending across a worldwide audience instead of a single market — matching NCsoft's stated approach with the global build.", "China sits in the report as a market-shift factor; NCsoft's own China partnership (Shengqu, as tracked by Korean media since July) is an example of the same strategic current the report describes."]),
        section("physical-ai-angle", "The Physical AI Angle, Briefly", ["Coverage of the report highlights physical AI as the industry's newest expansion front: games companies applying simulation, AI, and engine expertise to robotics, autonomous driving, manufacturing, defense, and mobility.", "That is a corollary of the IP life-extension thesis — companies extracting value from their technology stacks beyond games. It does not change Aion 2's roadmap, but it explains why the sector's strategic center of gravity is shifting.", "For players, the practical upshot is that major Korean publishers are investing broadly — which historically correlates with healthier long-term live-service budgets."]),
        section("what-it-means", "What It Means for the Oct 5 Launch", ["An industry report does not move a release date, but it does frame expectations. The six-change thesis suggests Korean publishers will keep pushing global-first launches — Aion 2 being one of the most visible in October.", "The China factor is double-edged: a growing addressable market for NCsoft's IP, alongside the regulatory complexity the report's coverage implies for market entry.", "Cost discipline is the one to watch operationally: a global launch funded by a record PC quarter (see our separate NC H1 coverage) is in a stronger position than one funded on optimism."]),
        section("takeaway", "The Takeaway", ["The KPMG-report news cycle is a macro backdrop, not an Aion 2 event: treat it as context for why the industry is moving global-first, IP-first, and physical-AI-adjacent.", "For Aion 2 specifically, the relevant takeaway is simpler — the October 5 launch is a free-to-play, global-simultaneous bet by a company that, per Korean press, is on its strongest PC revenue run on record.", "The report's six changes are worth reading when the full text is public; until then, the financial- and strategy-headline coverage is the verifiable record."]),
      ],
    }),
    "zh-hans": articleCopy(newsLabels, "zh-hans", 5, {
      eyebrow: "行业观察",
      title: "三正 KPMG 报告称韩游戏产业面临 6 大变化：Aion 2 的位置",
      description: "8 月底三正 KPMG 报告指韩国游戏产业面临 6 大结构性变化——标题点名 IP、物理 AI、中国与成本——恰逢厂商转向全球先行策略。Aion 2 的 10 月 5 日上线正是该转向的具体样本。",
      intro: "每条 Aion 2 头条背后都有行业语境，8 月底的三正 KPMG 报告提供了它。8 月 31 日韩媒报道了该报告关于本土游戏产业面临 6 大变化的结论——标题点名 IP、物理 AI、中国与成本压力。本报告汇总该报告可核实的内容，并把 Aion 2 的全球推进放在这一背景下解读。",
      sourceNote: "基于韩媒（intn.co.kr，8/31）对三正 KPMG 8 月 28 日报告的报道；本次仅标题级事实，报告全文未能在本次会话中获取。",
      keywords: ["韩国游戏产业 2026", "KPMG 游戏产业报告", "物理AI 游戏", "韩国 MMO 全球化", "Aion 2 行业背景"],
      sections: [
        section("what-kpmg-says", "报道称报告的内容", ["8 月 31 日韩媒报道三正 KPMG 报告（8 月 28 日发布），标题称游戏产业面临 6 大变化——IP、物理 AI、中国与成本压力等在列。", "报道中的报告题目围绕「通过 6 个核心问题看游戏产业的变化」。因全文本次不可取，本文对 6 项清单停留在标题级。", "跨媒体的主题方向一致：用户、IP 与 AI 是重组主轴，物理 AI（机器人、自动驾驶、制造、国防、移动）被表述为游戏公司的新增长前沿。"]),
        section("aion2-in-context", "Aion 2 在图景中的位置", ["Aion 2 的 10 月 5 日全球上线是报告所述 IP 驱动转向的直接产物：NC 是在既有 MMO IP 上做域外延伸，而非带着全新设定进入新市场。", "成本压力在报告的框架中可见：全球先行开发把内容开支摊薄到全球受众而非单一市场——与 NC 全球版的公开做法一致。", "中国在报告中被列为市场变化因素；NC 自己的中国合作（6 月起韩媒跟踪的盛趣）正是同一战略流向的例证。"]),
        section("physical-ai-angle", "物理 AI 角度，简述", ["报道强调物理 AI 是行业最新的扩展前沿：游戏公司把仿真、AI 与引擎能力应用到机器人、自动驾驶、制造、国防与移动。", "这是 IP 生命周期延长论的推论——公司从技术栈中获取游戏之外的价值。它不改变 Aion 2 的路线图，但解释了行业战略重心为何转移。", "对玩家的实际结果：主要韩厂在广泛投资——历史上这与更健康的长期长线运营预算相关。"]),
        section("what-it-means", "对 10/5 上线的含义", ["行业报告不会移动发售日期，但设定预期。6 大变化论暗示韩厂会继续推进全球先行——Aion 2 是 10 月最显眼者之一。", "中国因素是双刃剑：NC IP 的可寻址市场扩大，同时伴随报道所暗示的市场准入监管复杂性。", "运营上值得留意的是成本纪律：由创纪录 PC 季度资助的全球上线（见本站 NC 上半年报道）比靠乐观情绪资助的更强。"]),
        section("takeaway", "结论", ["KPMG 报告的新闻周期是宏观背景而非 Aion 2 事件：把它当作行业为何转向全球先行、IP 先行、贴近物理 AI 的语境。", "对 Aion 2 具体而言，相关结论更简单——10 月 5 日上线是免费游玩、全球同步的一次押注，而该公司据韩媒正处在 PC 营收纪录期。", "报告全文公开后值得一读那 6 项变化；在那之前，财经与战略头条报道是可核实的记录。"]),
      ],
    }),
    ko: articleCopy(newsLabels, "ko", 5, {
      eyebrow: "업계 워치",
      title: "삼정KPMG 보고서, 한국 게임 산업 6대 변화 직면 — 아이온2의 위치",
      description: "8월 말 삼정KPMG 보고서가 한국 게임 산업이 6대 구조 변화(IP·피지컬 AI·중국·비용 등)에 직면했다고 했고, 이는 글로벌 우선 전환과 맞물립니다. 아이온2의 10월 5일 출시가 그 구체적 사례입니다.",
      intro: "모든 아이온2 헤드라인 뒤에는 산업 맥락이 있습니다. 8월 28일 발간된 삼정KPMG 보고서와 8월 31일 한국 언론 보도가 그것을 줍니다. 본 기사는 검증 가능한 범위를 정리하고, 그 배경에서 아이온2의 글로벌 추진을 읽습니다.",
      sourceNote: "intn.co.kr(8/31)의 삼정KPMG 보고서(8/28) 보도 기반. 세션에서 전문을 얻을 수 없어 헤드라인 수준 사실만 사용합니다.",
      keywords: ["한국 게임 산업 2026", "KPMG 게임 산업 보고서", "피지컬AI 게임", "한국 MMO 글로벌화", "아이온2 산업 맥락"],
      sections: [
        section("what-kpmg-says", "보고서가 무엇을 말하는가", "8월 31일 한국 비즈니스 언론이 삼정KPMG 보고서(8월 28일)를 '게임 산업 6대 변화 — IP·피지컬 AI·중국·비용' 헤드라인으로 다뤘습니다. 보고서 제목은 '6대 핵심 질문으로 본 게임 산업의 변화'입니다. 전문을 얻지 못해 이 기사는 6대 목록을 헤드라인 수준에서 다룹니다."),
        section("aion2-in-context", "아이온2는 그 그림의 어디에", "아이온2의 10월 5일 글로벌 출시는 IP 중심 전환의 직접 산물입니다: 검증된 MMO IP를 국내를 넘어 확장합니다. 비용 압박은 글로벌 우선 개발이 콘텐츠 비용을 전 세계로 분산하는 보고서의 프레임과 일치합니다. 중국은 시장 이동 요인으로, NC의 셩취 파트너십이 같은 흐름의 예입니다."),
        section("physical-ai-angle", "피지컬 AI 각도", "보도는 피지컬 AI를 산업의 최신 확장 전선으로 강조합니다: 로봇·자율주행·제조·방산·모빌리티로의 기술 적용. 이는 아이온2 로드맵을 바꾸지 않지만, 전략 중심이 왜 이동하는지 설명합니다. 이용자에게는 장기 운영 예산의 건강함과 연결됩니다."),
        section("what-it-means", "10월 5일 출시에 주는 의미", "산업 보고서는 날짜를 움직이지 않지만 기대를 잡습니다. 중국 요소는 양날의 검입니다. 운영상 비용 규율이 핵심: 기록적인 PC 분기(본지 NC 상반기 보도 참조)가 뒷받침하는 출시는 낙관론만으로 시작하는 것보다 강합니다."),
        section("takeaway", "결론", "KPMG 보고서 뉴스 사이클은 매크로 배경이지 아이온2 이벤트가 아닙니다. 아이온2에게는 더 단순한 메시지 — 10월 5일은 무료·전역 동시 출시이며, 한국 언론에 따르면 회사는 최강 PC 매출기를 지나고 있습니다."),
      ],
    }),
    ja: articleCopy(newsLabels, "ja", 5, {
      eyebrow: "業界ウォッチ",
      title: "サムジョンKPMG報告、韓国ゲーム産業は6大変化に直面 — アイオン2の位置",
      description: "8月末のサムジョンKPMG報告が韓国ゲーム産業の6大構造変化（IP・フィジカルAI・中国・コスト等）を指摘し、これはグローバル先行への転換と重なります。アイオン2の10月5日発売がその具体例です。",
      intro: "すべてのアイオン2見出しには産業の文脈があります。8月28日発刊のサムジョンKPMG報告と8月31日の韓国報道がそれを与えます。本記事は検証可能な範囲を整理し、その背景でアイオン2のグローバル推進を読むものです。",
      sourceNote: "intn.co.kr（8/31）によるサムジョンKPMG報告（8/28）報道に基づきます。セッション内で全文を取得できなかったため、見出しレベルの事実のみ使用します。",
      keywords: ["韓国ゲーム産業 2026", "KPMGゲーム産業報告", "フィジカルAI ゲーム", "韓国MMO グローバル化", "アイオン2 産業文脈"],
      sections: [
        section("what-kpmg-says", "報告が何を言うか", "8月31日、韓国ビジネスメディアがサムジョンKPMG報告（8月28日）を『ゲーム産業6大変化 — IP・フィジカルAI・中国・コスト』見出しで報じました。報告タイトルは『6대 핵심 질문으로 본 게임 산업의 변화』。全文を取得できず、本記事は6大リストを見出しレベルで扱います。"),
        section("aion2-in-context", "アイオン2はその図のどこに", "アイオン2の10月5日グローバル発売はIP中心転換の直接の産物です。コスト圧力はグローバル先行開発がコンテンツ費を全世界へ分散する報告のフレームと一致します。中国は市場移動要因で、NCの셩취パートナーシップが同じ流れの例です。"),
        section("physical-ai-angle", "フィジカルAIの角度", "報道はフィジカルAIを産業の最新拡張戦線と強調します：ロボット・自動運転・製造・防衛・モビリティへの技術適用。これはアイオン2のロードマップを変えませんが、戦略重心の移動を説明します。"),
        section("what-it-means", "10月5日発売への含意", "産業報告は日付を動かしませんが、期待を設定します。中国要素は両刃の剣です。運営上はコスト規律が核心: 記録的なPC四半期（本紙NC上半期報道参照）が支える発売は、楽観だけで始まるより強いです。"),
        section("takeaway", "結論", "KPMG報告のニュースサイクルはマクロ背景でありアイオン2イベントではありません。アイオン2にはより単純なメッセージ — 10月5日は無料・全地域同時の発売であり、会社は韓国報道によれば最強のPC売上期にあります。"),
      ],
    }),
    fr: articleCopy(newsLabels, "fr", 5, {
      eyebrow: "VEILLE INDUSTRIE",
      title: "Le rapport KPMG et les six mutations de l'industrie coréenne : où se place Aion 2",
      description: "Un rapport Samjong KPMG de fin août évoque six mutations structurelles pour l'industrie coréenne — IP, IA physique, Chine, coûts — au moment où les éditeurs basculent vers le global-first. Le lancement d'Aion 2 le 5 octobre en est un exemple.",
      intro: "Chaque gros titre Aion 2 a un contexte industriel, et le rapport Samjong KPMG de fin août le fournit. La presse du 31 août a couvert la thèse des six mutations. Cet article résume ce qui est vérifiable et lit la poussée mondiale d'Aion 2 sur cet arrière-plan.",
      sourceNote: "Basé sur la couverture (intn.co.kr, 31 août) du rapport Samjong KPMG du 28 août ; faits de niveau titre uniquement, le texte complet n'étant pas récupérable.",
      keywords: ["industrie du jeu coréenne 2026", "rapport KPMG jeux", "IA physique jeux", "MMO coréen expansion mondiale", "Aion 2 contexte"],
      sections: [
        section("what-kpmg-says", "Ce que le rapport est réputé dire", "Le 31 août, la presse coréenne a couvert le rapport Samjong KPMG (28 août) sous des titres évoquant six mutations majeures — IP, IA physique, Chine et coûts. Le titre de travail mentionne six questions clés. Faits de niveau titre faute du texte complet."),
        section("aion2-in-context", "Où se place Aion 2", "Le lancement mondial d'Aion 2 le 5 octobre est un produit direct du pivot IP : NCsoft étend un IP MMO éprouvé hors de sa base. La pression sur les coûts correspond à l'amortissement mondial des contenus. La Chine figure comme facteur de déplacement des marchés."),
        section("physical-ai-angle", "L'angle IA physique", "La couverture souligne l'IA physique comme nouveau front : robotique, conduite autonome, fabrication, défense, mobilité. Cela explique le déplacement du centre de gravité stratégique sans changer la feuille de route d'Aion 2."),
        section("what-it-means", "Pour le 5 octobre", "Un rapport ne déplace pas une date mais cadre les attentes. Le facteur Chine est à double tranchant. La discipline des coûts est le point à suivre : une sortie financée par un trimestre PC record est mieux placée."),
        section("takeaway", "Conclusion", "Le cycle KPMG est un arrière-plan macro. Pour Aion 2 : une sortie mondiale simultanée et gratuite, portée par une société sur sa lancée de revenus PC la plus forte, selon la presse coréenne."),
      ],
    }),
    de: articleCopy(newsLabels, "de", 5, {
      eyebrow: "BRANCHEN-BEOBACHTUNG",
      title: "Sechs Veränderungen für die koreanische Spielebranche: Wo Aion 2 steht",
      description: "Ein Samjong-KPMG-Bericht von Ende August nennt sechs strukturelle Veränderungen — IP, physische KI, China, Kosten — passend zur Global-first-Wende der Publisher. Der Start von Aion 2 am 5. Oktober ist ein Beispiel.",
      intro: "Hinter jeder Aion-2-Schlagzeile steht ein Branchenkontext, und der Samjong-KPMG-Bericht von Ende August liefert ihn. Dieser Artikel fasst Verifizierbares zusammen und liest die globale Offensive von Aion 2 vor diesem Hintergrund.",
      sourceNote: "Basierend auf der Berichterstattung (intn.co.kr, 31. August) zum Samjong-KPMG-Bericht vom 28. August; nur titel-level Fakten, da der Volltext nicht abrufbar war.",
      keywords: ["koreanische Spielebranche 2026", "KPMG-Branchenbericht", "physische KI Spiele", "koreanisches MMO globale Expansion", "Aion 2 Kontext"],
      sections: [
        section("what-kpmg-says", "Was der Bericht berichtet wird", "Am 31. August berichtete die koreanische Wirtschaftspresse über den Samjong-KPMG-Bericht (28. August) mit sechs großen Veränderungen — IP, physische KI, China, Kosten. Arbeitstitel: sechs Kernfragen. Titel-level Fakten."),
        section("aion2-in-context", "Wo Aion 2 steht", "Der weltweite Start am 5. Oktober ist ein direktes Produkt des IP-Pivots: NCsoft erweitert eine etablierte MMO-IP über die Heimatbasis hinaus. Kostendruck passt zur weltweiten Amortisation. China erscheint als Marktverschiebungsfaktor."),
        section("physical-ai-angle", "Der physische-KI-Winkel", "Die Berichterstattung betont physische KI als neues Feld: Robotik, autonomes Fahren, Fertigung, Verteidigung, Mobilität. Das erklärt die strategische Schwerpunktverlagerung, ohne die Aion-2-Roadmap zu ändern."),
        section("what-it-means", "Für den 5. Oktober", "Ein Bericht verschiebt kein Datum, setzt aber Erwartungen. Der China-Faktor ist zweischneidig. Kostendisziplin: Ein Start, finanziert durch ein Rekord-PC-Quartal (siehe unser NC-Halbjahresbericht), steht stärker dar."),
        section("takeaway", "Fazit", "Der KPMG-Zyklus ist Makro-Kontext. Für Aion 2: ein weltweiter, gleichzeitiger, kostenloser Start durch ein Unternehmen, das laut koreanischer Presse die stärkste PC-Umsatzphase durchläuft."),
      ],
    }),
    es: articleCopy(newsLabels, "es", 5, {
      eyebrow: "VIGILANCIA DE LA INDUSTRIA",
      title: "El informe KPMG y los seis cambios de la industria coreana: dónde encaja Aion 2",
      description: "Un informe de Samjong KPMG de finales de agosto menciona seis cambios estructurales — IP, IA física, China, costes — justo cuando los editores viran al global-first. El lanzamiento de Aion 2 el 5 de octubre es un ejemplo.",
      intro: "Cada titular de Aion 2 tiene un contexto industrial, y el informe de Samjong KPMG de finales de agosto lo aporta. Este artículo resume lo verificable y lee la ofensiva global de Aion 2 sobre ese fondo.",
      sourceNote: "Basado en la cobertura (intn.co.kr, 31 de agosto) del informe Samjong KPMG del 28 de agosto; solo hechos a nivel de titular, al no recuperarse el texto completo.",
      keywords: ["industria del juego coreana 2026", "informe KPMG juegos", "IA física juegos", "MMO coreano expansión mundial", "Aion 2 contexto"],
      sections: [
        section("what-kpmg-says", "Qué se dice del informe", "El 31 de agosto, la prensa coreana cubrió el informe Samjong KPMG (28 de agosto) con titulares sobre seis grandes cambios — IP, IA física, China, costes. Título de trabajo: seis preguntas clave. Hechos de nivel titular."),
        section("aion2-in-context", "Dónde encaja Aion 2", "El lanzamiento mundial del 5 de octubre es producto directo del giro por IP: NCsoft extiende un IP MMO probado más allá de su base. La presión de costes cuadra con la amortización mundial. China aparece como factor de desplazamiento de mercado."),
        section("physical-ai-angle", "El ángulo de la IA física", "La cobertura subraya la IA física como nuevo frente: robótica, conducción autónoma, fabricación, defensa, movilidad. Explica el cambio de gravedad estratégica sin alterar la hoja de ruta de Aion 2."),
        section("what-it-means", "Para el 5 de octubre", "Un informe no mueve una fecha pero fija expectativas. El factor China es de doble filo. La disciplina de costes: un lanzamiento financiado por un trimestre PC récord está mejor posicionado."),
        section("takeaway", "Conclusión", "El ciclo KPMG es fondo macro. Para Aion 2: una salida mundial simultánea y gratuita, respaldada por una compañía en su mejor racha de ingresos de PC, según la prensa coreana."),
      ],
    }),
    "pt-br": articleCopy(newsLabels, "pt-br", 5, {
      eyebrow: "OBSERVATÓRIO DA INDÚSTRIA",
      title: "O relatório KPMG e as seis mudanças da indústria coreana: onde o Aion 2 se encaixa",
      description: "Um relatório da Samjong KPMG do fim de agosto cita seis mudanças estruturais — IP, IA física, China, custos — enquanto as editoras viram para o global-first. O lançamento do Aion 2 em 5 de outubro é um exemplo.",
      intro: "Cada manchete do Aion 2 tem um contexto industrial, e o relatório da Samjong KPMG do fim de agosto o fornece. Este artigo resume o verificável e lê a ofensiva global do Aion 2 nesse fundo.",
      sourceNote: "Com base na cobertura (intn.co.kr, 31 de agosto) do relatório Samjong KPMG de 28 de agosto; apenas fatos de nível de manchete, já que o texto completo não foi recuperável.",
      keywords: ["indústria de jogos coreana 2026", "relatório KPMG jogos", "IA física jogos", "MMO coreano expansão mundial", "Aion 2 contexto"],
      sections: [
        section("what-kpmg-says", "O que se diz do relatório", "Em 31 de agosto, a imprensa coreana cobriu o relatório Samjong KPMG (28 de agosto) com manchetes sobre seis grandes mudanças — IP, IA física, China e custos. Título de trabalho: seis questões-chave. Fatos de nível de manchete."),
        section("aion2-in-context", "Onde o Aion 2 se encaixa", "O lançamento mundial de 5 de outubro é produto direto da virada por IP: a NCSoft estende um IP MMO comprovado além da base doméstica. A pressão de custos casa com a amortização mundial. A China aparece como fator de deslocamento de mercado."),
        section("physical-ai-angle", "O ângulo da IA física", "A cobertura destaca a IA física como nova frente: robótica, direção autônoma, manufatura, defesa, mobilidade. Explica a mudança de gravidade estratégica sem alterar o roteiro do Aion 2."),
        section("what-it-means", "Para 5 de outubro", "Um relatório não move uma data, mas define expectativas. O fator China é faca de dois gumes. Disciplina de custos: um lançamento financiado por um trimestre PC recorde está melhor posicionado."),
        section("takeaway", "Conclusão", "O ciclo KPMG é pano de fundo macro. Para o Aion 2: um lançamento mundial simultâneo e gratuito, apoiado por uma empresa no seu melhor período de receita de PC, segundo a imprensa coreana."),
      ],
    }),
    ru: articleCopy(newsLabels, "ru", 5, {
      eyebrow: "НАБЛЮДЕНИЕ ЗА ИНДУСТРИЕЙ",
      title: "Отчёт KPMG и шесть изменений корейской индустрии: где место Aion 2",
      description: "Отчёт Samjong KPMG конца августа называет шесть структурных изменений — IP, физический ИИ, Китай, издержки — как раз на фоне глобально-первого разворота издателей. Запуск Aion 2 5 октября — пример.",
      intro: "За каждым заголовком об Aion 2 стоит отраслевой контекст, и отчёт Samjong KPMG конца августа даёт его. Эта статья резюмирует проверяемое и читает глобальное наступление Aion 2 на этом фоне.",
      sourceNote: "На основе освещения (intn.co.kr, 31 августа) отчёта Samjong KPMG от 28 августа; только факты уровня заголовков, полный текст недоступен.",
      keywords: ["корейская игровая индустрия 2026", "отчёт KPMG игры", "физический ИИ игры", "корейская MMO глобальная экспансия", "Aion 2 контекст"],
      sections: [
        section("what-kpmg-says", "Что, как сообщается, говорит отчёт", "31 августа корейская пресса осветила отчёт Samjong KPMG (28 августа) заголовками о шести больших изменениях — IP, физический ИИ, Китай, издержки. Рабочее название: шесть ключевых вопросов. Факты уровня заголовков."),
        section("aion2-in-context", "Где место Aion 2", "Мировой запуск 5 октября — прямой продукт разворота к IP: NCsoft расширяет проверенный MMO-IP за пределы домашнего рынка. Давление издержек совпадает с мировой амортизацией. Китай — фактор смещения рынков."),
        section("physical-ai-angle", "Угол физического ИИ", "Освещение подчёркивает физический ИИ как новый фронт: робототехника, беспилотники, производство, оборона, мобильность. Это объясняет сдвиг стратегического центра тяжести без изменения дорожной карты Aion 2."),
        section("what-it-means", "Для 5 октября", "Отчёт не двигает дату, но задаёт ожидания. Фактор Китая обоюдоострый. Дисциплина издержек: запуск, финансируемый рекордным PC-кварталом, стоит прочнее."),
        section("takeaway", "Вывод", "Цикл KPMG — макрофон. Для Aion 2: мировой одновременный бесплатный запуск, поддержанный компанией на её сильнейшем этапе ПК-выручки, по данным корейской прессы."),
      ],
    }),
    "zh-hant": articleCopy(newsLabels, "zh-hant", 5, {
      eyebrow: "行業觀察",
      title: "三正 KPMG 報告稱韓遊戲產業面臨 6 大變化：Aion 2 的位置",
      description: "8 月底三正 KPMG 報告指韓國遊戲產業面臨 6 大結構性變化——標題點名 IP、物理 AI、中國與成本——恰逢廠商轉向全球先行策略。Aion 2 的 10 月 5 日上線正是該轉向的具體樣本。",
      intro: "每條 Aion 2 頭條背後都有行業語境，8 月底的三正 KPMG 報告提供了它。8 月 31 日韓媒報導了該報告關於本土遊戲產業面臨 6 大變化的結論。本報告彙總該報告可核實的內容，並把 Aion 2 的全球推進放在這一背景下解讀。",
      sourceNote: "基於韓媒（intn.co.kr，8/31）對三正 KPMG 8 月 28 日報告的報導；本次僅標題級事實，報告全文未能在本次會話中取得。",
      keywords: ["韓國遊戲產業 2026", "KPMG 遊戲產業報告", "物理AI 遊戲", "韓國 MMO 全球化", "Aion 2 行業背景"],
      sections: [
        section("what-kpmg-says", "報導稱報告的內容", ["8 月 31 日韓媒報導三正 KPMG 報告（8 月 28 日發布），標題稱遊戲產業面臨 6 大變化——IP、物理 AI、中國與成本壓力等在列。因全文本次不可取，本文對 6 項清單停留在標題級。"]),
        section("aion2-in-context", "Aion 2 在圖景中的位置", ["Aion 2 的 10 月 5 日全球上線是報告所述 IP 驅動轉向的直接產物。成本壓力在報告的框架中可見：全球先行開發把內容開支攤薄到全球受眾。中國被列為市場變化因素。"]),
        section("physical-ai-angle", "物理 AI 角度，簡述", ["報導強調物理 AI 是行業最新的擴展前沿：機器人、自動駕駛、製造、國防與移動。它不改變 Aion 2 的路線圖，但解釋了行業戰略重心為何轉移。"]),
        section("what-it-means", "對 10/5 上線的含義", ["行業報告不會移動發售日期，但設定預期。中國因素是雙刃劍。營運上值得留意的是成本紀律：由創紀錄 PC 季度資助的全球上線（見本站 NC 上半年報導）更強。"]),
        section("takeaway", "結論", ["KPMG 報告的新聞週期是宏觀背景而非 Aion 2 事件。對 Aion 2 具體而言，相關結論更簡單——10 月 5 日上線是免費遊玩、全球同步的一次押注，而該公司據韓媒正處在 PC 營收紀錄期。"]),
      ],
    }),
  },
};