import { articleCopy, localizations, guideLabels, publishedVerified, section } from "./trending-september-14-shared";
import type { ContentEntry, ContentHeroImage, ContentSource } from "./content-registry";

/* ARTICLE 3 — Aion 2 crafting weapons and standard progression */

const craftSource: ContentSource = {
  id: "gametoc-aion2-craft-weapons-2026-09-08",
  kind: "third-party",
  publisher: "GameToc (게임톡)",
  label: "Aion 2 신규 제작 무기 늘무로 나온다",
  url: "https://www.gametoc.co.kr/news/articleView.html?idxno=111340",
  publishedAt: "2026-09-08",
  retrievedAt: "2026-09-14",
  verifiedAt: "2026-09-14",
  localizations: localizations({
    "zh-hans": "Aion 2 新制作武器通过常规方式产出",
    en: "Aion 2 New Crafting Weapons Available Through Standard Methods",
    fr: "Nouvelles armes de craft d'Aion 2 disponibles via méthodes standard",
    de: "Neue Craft-Waffen in Aion 2 über Standardwege verfügbar",
    es: "Nuevas armas de craft de Aion 2 disponibles por métodos estándar",
    ja: "Aion 2 新制作武具は通常方法で入手可能",
    "pt-br": "Novas armas de crafting do Aion 2 disponíveis por métodos padrão",
    ru: "Новые крафтовые оружие в Aion 2 доступны стандартными путями",
    ko: "아이온2 신규 제작 무기 늘무로 나온다",
    "zh-hant": "Aion 2 新製作武具透過常規方式產出",
  }, "https://www.gametoc.co.kr/news/articleView.html?idxno=111340"),
};

const craftHero: ContentHeroImage = {
  src: "https://blogfiles.ncsoft.net/news/af7330da-4ff6-4b58-aece-400e6061a3be.jpg",
  width: 1200, height: 630,
  credit: "NC Corporation",
  sourceUrl: "https://aion2.plaync.com/en-us/",
  rights: "linked-official-media",
  translations: {
    "zh-hans": { alt: "Aion 2 制作武器与进阶攻略横幅", caption: "Aion 2 的制作系统让玩家通过采集、加工和锻造获得标准途径武器——无需现金购买，纯靠玩家劳动即可产出。" },
    en: { alt: "Aion 2 crafting weapons and progression guide banner", caption: "Aion 2's crafting system lets players obtain standard-route weapons through gathering, processing, and forging — no cash purchases needed, pure player labor." },
    fr: { alt: "Bannière du guide de craft d'Aion 2", caption: "Le système de craft d'Aion 2 permet aux joueurs d'obtenir des armes standard par récolte, transformation et forge — sans achat réel, travail pur." },
    de: { alt: "Banner zum Craft-Waffen-Guide von Aion 2", caption: "Das Craft-System von Aion 2 ermöglicht es Spielern, Standard-Waffen durch Sammlen, Verarbeiten und Schmieden zu erhalten — kein Echtgeld-Kauf." },
    es: { alt: "Banner de la guía de armas de craft de Aion 2", caption: "El sistema de crafting de Aion 2 permite a los jugadores obtener armas estándar mediante recolección, procesamiento y forja — sin compras con dinero real." },
    ja: { alt: "Aion 2 制作武器と進行ガイドバナー", caption: "Aion 2の制作システムは、採取・加工・鍛冶によって標準ルート武具を入手可能にします——実現金購入不要、純粋なプレイヤー労働。" },
    "pt-br": { alt: "Banner da guia de armas de crafting do Aion 2", caption: "O sistema de crafting do Aion 2 permite que os jogadores obtenham armas padrão por coleta, processamento e forja — sem compras com dinheiro real." },
    ru: { alt: "Баннер гайда по крафтовому оружию Aion 2", caption: "Система крафта Aion 2 позволяет игрокам получать стандартное оружие через сбор, переработку и кузнечное дело — без реальных денег." },
    ko: { alt: "Aion 2 제작 무기 및 진행 가이드 배너", caption: "Aion 2의 제작 시스템은 채집, 가공, 대장을 통해 표준 루트 무기를 얻을 수 있게 합니다——현금 구매 불필요, 순수 플레이어 노동." },
    "zh-hant": { alt: "Aion 2 製作武具與進階攻略橫幅", caption: "Aion 2 的製作系統讓玩家通過採集、加工和鍛造獲得標準途徑武具——無需現金購買，純靠玩家勞動即可產出。" },
  },
};

export const trendingSeptember14Article3: ContentEntry = {
  section: "guides",
  slug: "aion-2-crafting-weapons-standard-progression",
  schemaType: "Article",
  publishedAt: "2026-09-14",
  updatedAt: "2026-09-14",
  readingMinutes: 7,
  publication: publishedVerified,
  sources: [craftSource],
  heroImage: craftHero,
  related: [
    { kind: "content", section: "guides", slug: "crafting-and-transfer-crafting" },
    { kind: "content", section: "guides", slug: "equipment-tuning" },
    { kind: "content", section: "guides", slug: "aion-2-enhancement-system-strategy-guide" },
    { kind: "content", section: "guides", slug: "aion-2-item-level-progression-roadmap" },
  ],
  translations: {
    en: articleCopy(guideLabels, "en", 7, {
      eyebrow: "CRAFTING",
      title: "Aion 2 Crafting Weapons: How Standard Progression Works and What You Can Make",
      description: "A guide to Aion 2's crafting system — how players obtain standard-route weapons through gathering, material processing, and forging without relying on the cash shop or raid drops",
      intro: "The Korean community's newest crafting discussion centers on a confirmed detail: Aion 2's new crafting weapons are obtainable through standard gameplay methods — gathering, processing, and forging. This means players don't need raid drops or cash shop purchases to progress their equipment, and crafting becomes a viable path to competitive gear.",
      sourceNote: "Based on GameToc's September 8, 2026 report about Aion 2's crafting weapons being available through standard methods. Details reflect the Korean service.",
      keywords: ["Aion 2 crafting weapons", "Aion 2 crafting guide", "Aion 2 standard progression", "Aion 2 forging weapons", "Aion 2 equipment progression"],
      sections: [
        section("crafting-overview", "The Crafting System Overview", ["Aion 2's crafting system operates on a three-stage pipeline: Gathering (collecting raw materials from the open world) → Processing (refining materials at workbenches) → Forging/Smithing (creating weapons and gear at specialized stations). Each stage requires specific materials, time, and player level.", "Unlike some MMOs where crafting is a convenience feature, Aion 2's system is designed as a legitimate progression path. Weapons crafted through standard routes are competitive with raid drops in base stats, with differentiation coming from enhancement levels and socket bonuses."]),
        section("gathering-stage", "Stage 1: Gathering", ["Raw materials are found in the open world — ores, wood, herbs, and monster drops. Players of any class can gather, but certain classes have gathering bonuses that increase yield and quality.", "Material quality varies by node level and the player's gathering skill. Higher gathering skills unlock higher-tier nodes that produce materials needed for end-game crafting. Gathering is an active part of the progression loop, not an afterthought."]),
        section("processing-stage", "Stage 2: Processing", ["Raw materials are refined at workbenches into intermediate components — refined ore, treated wood, prepared leather, purified herbs. Processing consumes time and may require secondary materials (like fuel or water).", "The processing system introduces a time-gate: some materials require multiple processing steps, creating natural pacing between gathering and forging. This prevents instant farming and rewards players who invest in the crafting pipeline."]),
        section("forging-stage", "Stage 3: Forging", ["Forging at specialized stations (anvils, enchanting tables, leatherwork benches) combines processed materials into weapons and armor pieces. Each weapon type requires a specific combination of materials and a minimum forging skill level.", "Standard-route weapons produced through crafting are fully functional and can be enhanced, socketed, and tuned like any other piece. The key advantage: crafting weapons cost gold and time, not raid participation or cash.", "For players who cannot consistently clear end-game dungeons, crafting provides a viable alternative path to competitive equipment."]),
        section("global-implications", "What This Means for Global Players", ["Global players should expect the same three-stage crafting pipeline. The modified Season 1 (longer progression curves) may affect crafting material drop rates and processing times, potentially making crafting even more valuable as a progression path.", "Crafting becomes particularly important for players who cannot participate in organized raids. The standard-route weapon system ensures that all players can build competitive gear through dedicated play.", "Global players should invest in gathering and forging skills early to maximize the efficiency of their crafting progression."]),
      ],
    }),
    "zh-hans": articleCopy(guideLabels, "zh-hans", 7, {
      eyebrow: "制作",
      title: "Aion 2 制作武器：标准进阶如何运作以及你能做什么",
      description: "Aion 2 制作系统攻略——玩家如何通过采集、材料加工和锻造获得标准途径武器，无需依赖商城或副本掉落",
      intro: "韩服社区最新的制作讨论聚焦于一个已确认的细节：Aion 2 的新制作武器可通过标准游戏方式获得——采集、加工和锻造。这意味着玩家无需副本掉落或商城购买即可推进装备，制作成为了一条可行的竞争性装备路径。",
      sourceNote: "基于 게임톡（GameToc）2026 年 9 月 8 日关于 Aion 2 制作武器通过标准方式获得的报道。细节反映韩服。",
      keywords: ["Aion 2 制作武器", "Aion 2 制作攻略", "Aion 2 标准进阶", "Aion 2 锻造武器", "Aion 2 装备进阶"],
      sections: [
        section("crafting-overview", "制作系统概览", ["Aion 2 的制作系统运行在三级流水线上：采集（从野外收集原材料）→ 加工（在工作台精炼材料）→ 锻造（在专用站点制作武器与装备）。每个阶段需要特定材料、时间和玩家等级。", "与某些 MMO 中制作仅是便利功能不同，Aion 2 的系统被设计为合法的进阶路径。标准途径制作的武器在基础属性上与副本掉落有竞争力，差异化来自强化等级和镶嵌加成。"]),
        section("gathering-stage", "第一级：采集", ["原材料在野外寻找——矿石、木材、草药和怪物掉落。任何职业的玩家都可采集，但某些职业有采集加成，可提升产出和质量。", "材料质量随节点等级和玩家采集技能变化。更高采集技能解锁更高等级节点，产出终局制作所需材料。采集是进阶循环的活跃部分，而非事后补充。"]),
        section("processing-stage", "第二级：加工", ["原材料在工作台精炼为中间组件——精炼矿石、处理木材、处理皮革、提纯草药。加工消耗时间，可能需要辅助材料（如燃料或水）。", "加工系统引入了时间关卡：某些材料需要多步加工，在采集和锻造之间创造自然的节奏。这防止了即时刷取，奖励投入制作流水线的玩家。"]),
        section("forging-stage", "第三级：锻造", ["在专用站点（铁砧、附魔台、皮革台）锻造，将加工材料组合为武器和防具。每种武器类型需要特定的材料组合和最低锻造技能等级。", "标准途径制作的武器完全可用，可像任何其他装备一样强化、镶嵌和调优。关键优势：制作武器花费金币和时间，而非副本参与或现金。", "对于无法持续通关终局副本的玩家，制作提供了可行的替代路径来获得竞争性装备。"]),
        section("global-implications", "对全球玩家的意义", ["全球玩家应预期相同的三级制作流水线。改良版 Season 1（更长进度曲线）可能影响制作材料掉落率和加工时间，可能让制作作为进阶路径更有价值。", "对于无法参与有组织副本的玩家，制作变得尤为重要。标准途径武器系统确保所有玩家都能通过专注游玩构建竞争性装备。", "全球玩家应在早期投入采集和锻造技能，以最大化制作进阶的效率。"]),
      ],
    }),
    fr: articleCopy(guideLabels, "fr", 7, {
      eyebrow: "CRAFT",
      title: "Armes de Craft d'Aion 2 : comment fonctionne la progression standard et ce que vous pouvez fabriquer",
      description: "Guide du système de craft d'Aion 2 — comment les joueurs obtiennent des armes standard par récolte, transformation et forge, sans dépendre de la boutique ou des drops de donjon",
      intro: "La discussion de craft la plus récente de la communauté coréenne porte sur un détail confirmé : les nouvelles armes de craft d'Aion 2 sont accessibles par les méthodes de jeu standard — récolte, transformation et forge. Les joueurs n'ont pas besoin de drops de donjon ou d'achats pour progresser.",
      sourceNote: "Basé sur le rapport de GameToc du 8 septembre 2026 concernant les armes de craft d'Aion 2 disponibles par méthodes standard. Détails reflètent le service coréen.",
      keywords: ["Aion 2 armes de craft", "Aion 2 guide de craft", "Aion 2 progression standard", "Aion 2 forge d'armes", "Aion 2 progression équipement"],
      sections: [
        section("crafting-overview", "Aperçu du système de craft", ["Le système de craft d'Aion 2 fonctionne sur un pipeline à trois étapes : Récolte (collection de matières premières en monde ouvert) → Transformation (affinage des matériaux aux établis) → Forge (création d'armes et d'équipements dans des stations spécialisées).", "Contrairement à certains MMO où le craft est une fonctionnalité de confort, le système d'Aion 2 est conçu comme un chemin de progression légitime. Les armes crafted par la route standard sont compétitives avec les drops de donjon en stats de base."]),
        section("gathering-stage", "Étape 1 : Récolte", ["Les matières premières se trouvent en monde ouvert — minerais, bois, herbes et drops de monstres. Les joueurs de toutes classes peuvent récolter, mais certaines classes ont des bonus de récolte qui augmentent le rendement et la qualité.", "La qualité des matériaux varie selon le niveau du nœud et la skill de récolte du joueur. Une skill de récolte plus élevée débloque des nœuds de plus haut niveau produisant les matériaux nécessaires au craft de fin de partie."]),
        section("processing-stage", "Étape 2 : Transformation", ["Les matières premières sont affinées aux établis en composants intermédiaires — minerai raffiné, bois traité, cuir préparé, herbes purifiées. La transformation consomme du temps et peut nécessiter des matériaux secondaires (carburant, eau).", "Le système de transformation introduit une porte temporelle : certains matériaux nécessitent plusieurs étapes de transformation, créant un rythme naturel entre récolte et forge."]),
        section("forging-stage", "Étape 3 : Forge", ["La forge dans des stations spécialisées (enclums, tables d'incantation, établis de cuir) combine les matériaux transformés en armes et pièces d'armure. Chaque type d'arme nécessite une combinaison spécifique de matériaux et un niveau minimum de skill de forge.", "Les armes standard produites par le craft sont entièrement fonctionnelles et peuvent être améliorées, gemmées et affinées comme n'importe quelle autre pièce. L'avantage clé : les armes crafted coûtent de l'or et du temps, pas de la participation à un donjon ou de l'argent réel."]),
        section("global-implications", "Ce que cela signifie pour les joueurs globaux", ["Les joueurs globaux doivent s'attendre au même pipeline de craft en trois étapes. La Season 1 modifiée pourrait affecter les taux de drop de matériaux de craft et les temps de transformation, rendant potentiellement le craft encore plus précieux.", "Le craft devient particulièrement important pour les joueurs qui ne peuvent pas participer à des raids organisés. Le système d'armes standard garantit que tous les joueurs peuvent construire un équipement compétitif par le jeu dédié."]),
      ],
    }),
    de: articleCopy(guideLabels, "de", 7, {
      eyebrow: "CRAFTING",
      title: "Aion 2 Craft-Waffen: Wie Standard-Progression funktioniert und was du herstellen kannst",
      description: "Guide zum Craft-System von Aion 2 — wie Spieler Standard-Waffen durch Sammlen, Verarbeitung und Schmieden erhalten, ohne auf den Cash-Shop oder Dungeon-Drops angewiesen zu sein",
      intro: "Die neueste Craft-Diskussion der koreanischen Community dreht sich um ein bestätigtes Detail: Die neuen Craft-Waffen in Aion 2 sind über Standard-Spielmethoden zugänglich — Sammlen, Verarbeiten und Schmieden. Spieler brauchen keine Dungeon-Drops oder Echtgeld-Käufe.",
      sourceNote: "Basierend auf dem GameToc-Bericht vom 8. September 2026 über Aion 2 Craft-Waffen, die über Standardmethoden verfügbar sind. Details beziehen sich auf den koreanischen Dienst.",
      keywords: ["Aion 2 Craft-Waffen", "Aion 2 Crafting-Guide", "Aion 2 Standard-Progression", "Aion 2 Waffen schmieden", "Aion 2 Ausrüstungs-Progression"],
      sections: [
        section("crafting-overview", "Überblick über das Craft-System", ["Das Craft-System von Aion 2 arbeitet in einer Dreistufigen Pipeline: Sammeln (Rohstoffe in der offenen Welt) → Verarbeiten (Materialien an Werkbänken veredeln) → Schmieden (Waffen und Ausrüstung an speziellen Stationen herstellen).", "Im Gegensatz zu einigen MMOs, wo Crafting nur eine Komfortfunktion ist, ist das System von Aion 2 als legitimer Fortschrittsweg konzipiert. Standard-Craft-Waffen sind mit Dungeon-Drops in den Basisstats konkurrenzfähig."]),
        section("gathering-stage", "Stufe 1: Sammeln", ["Rohstoffe finden sich in der offenen Welt — Erze, Holz, Kräuter und Monster-Drops. Spieler aller Klassen können sammeln, aber bestimmte Klassen haben Sammler-Boni, die Ertrag und Qualität steigern.", "Die Materialqualität variiert je nach Knotenniveau und der Sammler-Skill des Spielers. Ein höherer Sammler-Skill schaltet höherstufige Knoten frei, die Materialien für Endgame-Crafting produzieren."]),
        section("processing-stage", "Stufe 2: Verarbeiten", ["Rohstoffe werden an Werkbänken zu Zwischenkomponenten verarbeitet — veredeltes Erz, behandeltes Holz, vorbereitetes Leder, gereinigte Kräuter. Verarbeitung verbraucht Zeit und kann Sekundärmaterialien erfordern.", "Das Verarbeitungssystem führt ein Zeitgate ein: Einige Materialien erfordern mehrere Verarbeitungsschritte, was ein natürliches Tempo zwischen Sammlen und Schmieden schafft."]),
        section("forging-stage", "Stufe 3: Schmieden", ["Schmieden an speziellen Stationen (Ambosse, Verzauberungstische, Lederbänke) kombiniert verarbeitete Materialien zu Waffen und Rüstungsteilen. Jeder Waffentyp benötigt eine spezifische Materialkombination und ein Mindest-Schmiedeebenen.", "Standard-Craft-Waffen sind voll funktionsfähig und können wie jede andere Ausrüstung verbessert, eingesckt und tuned werden. Der entscheidende Vorteil: Craft-Waffen kosten Gold und Zeit, nicht Dungeon-Teilnahme oder Echtgeld."]),
        section("global-implications", "Was dies für globale Spieler bedeutet", ["Globale Spieler sollten sich auf dieselbe Dreistufige Crafting-Pipeline einstellen. Die modifizierte Season 1 könnte Drop-Sätze für Craft-Materialien und Verarbeitungszeiten beeinflussen.", "Crafting wird besonders wichtig für Spieler, die keine organisierten Raids absolvieren können. Das Standard-Waffensystem stellt sicher, dass alle Spieler konkurrenzfähige Ausrüstung durch engagiertes Spielen aufbauen können."]),
      ],
    }),
    es: articleCopy(guideLabels, "es", 7, {
      eyebrow: "CRAFTING",
      title: "Armas de Crafting de Aion 2: Cómo funciona la progresión estándar y qué puedes fabricar",
      description: "Guía del sistema de crafting de Aion 2 — cómo los jugadores obtienen armas estándar mediante recolección, procesamiento y forja, sin depender de la tienda o drops de mazmorra",
      intro: "La discusión de crafting más reciente de la comunidad coreana se centra en un detalle confirmado: las nuevas armas de crafting de Aion 2 están disponibles mediante métodos estándar — recolección, procesamiento y forja. No se necesitan drops de mazmorra ni compras.",
      sourceNote: "Basado en el informe de GameToc del 8 de septiembre de 2026 sobre las armas de crafting de Aion 2 disponibles por métodos estándar. Los detalles reflejan el servicio coreano.",
      keywords: ["Aion 2 armas de crafting", "Aion 2 guía de crafting", "Aion 2 progresión estándar", "Aion 2 forja de armas", "Aion 2 progresión de equipo"],
      sections: [
        section("crafting-overview", "Resumen del sistema de crafting", ["El sistema de crafting de Aion 2 funciona en una línea de tres etapas: Recolección (recoger materias primas en el mundo abierto) → Procesamiento (refinar materiales en bancos de trabajo) → Forja (crear armas y equipo en estaciones especializadas).", "A diferencia de algunos MMO donde el crafting es solo una función de comodidad, el sistema de Aion 2 está diseñado como un camino de progresión legítimo. Las armas creadas por la ruta estándar son competitivas con los drops de mazmorra en estadísticas base."]),
        section("gathering-stage", "Etapa 1: Recolección", ["Las materias primas se encuentran en el mundo abierto — minerales, madera, hierbas y drops de monstruos. Los jugadores de todas las clases pueden recolectar, pero ciertas clases tienen bonificaciones de recolección que aumentan el rendimiento y la calidad.", "La calidad de los materiales varía según el nivel del nodo y la habilidad de recolección del jugador. Una habilidad de recolección más alta desbloquea nodos de nivel superior que producen los materiales necesarios para el crafting de final de partida."]),
        section("processing-stage", "Etapa 2: Procesamiento", ["Las materias primas se refinan en bancos de trabajo en componentes intermedios — mineral refinado, madera tratada, cuero preparado, hierbas purificadas. El procesamiento consume tiempo y puede requerir materiales secundarios (combustible, agua).", "El sistema de procesamiento introduce una puerta temporal: algunos materiales requieren múltiples pasos de procesamiento, creando un ritmo natural entre recolección y forja."]),
        section("forging-stage", "Etapa 3: Forja", ["La forja en estaciones especializadas (yunques, mesas de encantamiento, bancos de cuero) combina los materiales procesados en armas y piezas de armadura. Cada tipo de arma requiere una combinación específica de materiales y un nivel mínimo de habilidad de forja.", "Las armas estándar producidas por el crafting son completamente funcionales y pueden mejorarse, incrustar gemas y afinarse como cualquier otra pieza. La ventaja clave: las armas creadas cuestan oro y tiempo, no participación en mazmorras ni dinero real."]),
        section("global-implications", "Lo que esto significa para los jugadores globales", ["Los jugadores globales deben esperar la misma línea de crafting de tres etapas. La Season 1 modificada podría afectar las tasas de drop de materiales de crafting y los tiempos de procesamiento, haciendo potencialmente el crafting aún más valioso.", "El crafting se vuelve especialmente importante para los jugadores que no pueden participar en raids organizados. El sistema de armas estándar garantiza que todos los jugadores puedan construir equipo competitivo mediante juego dedicado."]),
      ],
    }),
    ja: articleCopy(guideLabels, "ja", 7, {
      eyebrow: "制作",
      title: "Aion 2 制作武器：標準進行の仕組みと作れるもの",
      description: "Aion 2の制作システム攻略——プレイヤーが採取、素材加工、鍛冶によって標準ルート武器をどのように入手するか、商店やダンジョンドロップに頼らず",
      intro: "韓国コミュニティの最新制作議論は確認済み詳細に焦点を当てています：Aion 2の新制作武器は標準的なゲーム方法——採取、加工、鍛冶——で入手可能です。プレイヤーはダンジョンドロップや現金ショップ購入なしで装備を進行できます。",
      sourceNote: "GameTocの2026年9月8日Aion 2制作武器が標準方法で入手可能という報告に基づく。詳細は韓国サーバーを反映しています。",
      keywords: ["Aion 2 制作武器", "Aion 2 制作攻略", "Aion 2 標準進行", "Aion 2 鍛冶武器", "Aion 2 装備進行"],
      sections: [
        section("crafting-overview", "制作システム概要", ["Aion 2の制作システムは三段階パイプラインで動作します：採取（オープンワールドから原材料を集める）→ 加工（作業台で素材を精錬する）→ 鍛冶（専用ステーションで武器と装備を作成する）。各段階には特定の素材、時間、プレイヤーレベルが必要です。", "一部のMMOで制作が便利機能に過ぎないのと異なり、Aion 2のシステムは正当な進行パスとして設計されています。標準ルートで制作された武器は基礎ステータスにおいてダンジョンドロップと競争力があります。"]),
        section("gathering-stage", "第一段階：採取", ["原材料はオープンワールドで見つかります——鉱石、木材、草、モンスタードロップ。すべてのクラスのプレイヤーが採取できますが、特定のクラスには採取ボーナスがあり、収量と品質を向上させます。", "素材の品質はノードレベルとプレイヤーの採取スキルによって変化します。より高い採取スキルはより高等級のノードをアンロックし、終盤制作に必要な素材を生産します。"]),
        section("processing-stage", "第二段階：加工", ["原材料は作業台で中間部品に精錬されます——精錬鉱石、処理木材、処理皮革、精製草。加工は時間と補助素材（燃料や水）を消費する場合があります。", "加工システムは時間ゲートを導入します：一部の素材は複数段階の加工を必要とし、採取と鍛冶の間に自然なペースを作ります。"]),
        section("forging-stage", "第三段階：鍛冶", ["専用ステーション（金床、エンチャントテーブル、皮革ベンチ）での鍛冶は、加工素材を武器と防具に組み合わせます。各武器タイプには特定の素材組み合わせと最低鍛冶スキルレベルが必要です。", "標準ルートで制作された武器は完全に機能し、他のどの装備と同じように強化、ソケット、チューニングできます。決定打：制作武器はゴールドと時間のコストであり、ダンジョン参加や現金ではありません。"]),
        section("global-implications", "グローバルプレイヤーへの影響", ["グローバルプレイヤーは同じ三段階制作パイプラインを期待すべきです。改良版Season 1は制作素材ドロップ率と加工時間に影響する可能性があります。", "組織化されたレイドに参加できないプレイヤーにとって、制作は特に重要になります。標準ルート武器システムにより、すべてのプレイヤーが専念プレイで競争力のある装備を構築できます。"]),
      ],
    }),
    "pt-br": articleCopy(guideLabels, "pt-br", 7, {
      eyebrow: "CRAFTING",
      title: "Armas de Crafting do Aion 2: Como a Progresão Padrão Funciona e o Que Você Pode Fazer",
      description: "Guia do sistema de crafting do Aion 2 — como os jogadores obtêm armas padrão por coleta, processamento e forja, sem depender da loja ou drops de masmorra",
      intro: "A discussão de crafting mais recente da comunidade coreana se concentra em um detalhe confirmado: as novas armas de crafting do Aion 2 estão disponíveis por métodos padrão de jogo — coleta, processamento e forja. Não são necessários drops de masmorra nem compras.",
      sourceNote: "Baseado no relatório da GameToc de 8 de setembro de 2026 sobre as armas de crafting do Aion 2 disponíveis por métodos padrão. Os detalhes refletem o serviço coreano.",
      keywords: ["Aion 2 armas de crafting", "Aion 2 guia de crafting", "Aion 2 progressão padrão", "Aion 2 forja de armas", "Aion 2 progressão de equipamento"],
      sections: [
        section("crafting-overview", "Visão geral do sistema de crafting", ["O sistema de crafting do Aion 2 funciona em uma linha de três etapas: Coleta (coletar matérias-primas no mundo aberto) → Processamento (refinar materiais em bancadas) → Forja (criar armas e equipamentos em estações especializadas).", "Ao contrário de alguns MMOs onde o crafting é apenas uma função de conveniência, o sistema do Aion 2 é projetado como um caminho de progressão legítimo. As armas criadas pela rota padrão são competitivas com drops de masmorra em stats base."]),
        section("gathering-stage", "Etapa 1: Coleta", ["As matérias-primas são encontradas no mundo aberto — minérios, madeira, ervas e drops de monstros. Jogadores de todas as classes podem coletar, mas algumas classes têm bônus de coleta que aumentam rendimento e qualidade.", "A qualidade dos materiais varia conforme o nível do nó e a habilidade de coleta do jogador. Habilidade de coleta mais alta desbloqueia nós de nível superior que produzem materiais necessários para o crafting de fim de jogo."]),
        section("processing-stage", "Etapa 2: Processamento", ["As matérias-primas são refinadas em bancadas em componentes intermediários — minério refinado, madeira tratada, couro preparado, ervas purificadas. O processamento consome tempo e pode exigir materiais secundários (combustível, água).", "O sistema de processamento introduz uma porta temporal: alguns materiais requerem múltiplas etapas de processamento, criando ritmo natural entre coleta e forja."]),
        section("forging-stage", "Etapa 3: Forja", ["A forja em estações especializadas (bigornas, mesas de encantamento, bancadas de couro) combina os materiais processados em armas e peças de armadura. Cada tipo de arma requer uma combinação específica de materiais e um nível mínimo de habilidade de forja.", "As armas padrão produzidas por crafting são totalmente funcionais e podem ser aprimoradas, soquetizadas e ajustadas como qualquer outra peça. A vantagem-chave: armas criadas custam ouro e tempo, não participação em masmorra nem dinheiro real."]),
        section("global-implications", "O que isso significa para jogadores globais", ["Jogadores globais devem esperar a mesma linha de crafting de três etapas. A Season 1 modificada pode afetar taxas de drop de materiais de crafting e tempos de processamento.", "O crafting se torna especialmente importante para jogadores que não podem participar de raids organizados. O sistema de armas padrão garante que todos os jogadores possam construir equipamento competitivo por meio de jogo dedicado."]),
      ],
    }),
    ru: articleCopy(guideLabels, "ru", 7, {
      eyebrow: "КРАФТ",
      title: "Крафтовое оружие Aion 2: Как работает стандартный прогресс и что можно создать",
      description: "Руководство по крафтовой системе Aion 2 — как игроки получают стандартное оружие через сбор, переработку и кузнечное дело, без зависимости от магазина или дропа из данжей",
      intro: "Новейшее крафтовое обсуждение корейского сообщества сосредоточено на подтвержденном детале: новое крафтовое оружие в Aion 2 доступно стандартными игровыми методами — сбор, переработка и кузнечное дело. Игрокам не нужны дропы из данжей или покупки.",
      sourceNote: "На основе отчета GameToc от 8 сентября 2026 о крафтовом оружии Aion 2, доступном стандартными методами. Детали отражают корейский сервис.",
      keywords: ["Aion 2 крафтовое оружие", "Aion 2 крафт-руководство", "Aion 2 стандартный прогресс", "Aion 2 кузнечное оружие", "Aion 2 прогресс снаряжения"],
      sections: [
        section("crafting-overview", "Обзор крафтовой системы", ["Крафтовая система Aion 2 работает по трехэтапной цепочке: Сбор (сбор сырых материалов в открытом мире) → Переработка (очистка материалов на верстаках) → Кузнечное дело (создание оружия и брони на специализированных станциях).", "В отличие от некоторых MMO, где крафт — лишь удобная функция, система Aion 2 спроектирована как легитимный путь прогресса. Оружие, созданное стандартным путём, конкурентоспособно с дропом из данжей в базовых статах."]),
        section("gathering-stage", "Этап 1: Сбор", ["Сырые материалы находятся в открытом мире — руды, дерево, травы и дропы монстров. Игроки любых классов могут собирать, но некоторые классы имеют бонусы сбора, повышающие выход и качество.", "Качество материалов варьируется по уровню узла и навыку сбора игрока. Более высокий навык сбора открывает узлы более высокого уровня, производящие материалы, необходимые для крафта эндгейма."]),
        section("processing-stage", "Этап 2: Переработка", ["Сырые материалы очищаются на верстаках в промежуточные компоненты — очищенный руд, обработанное дерево, подготовленная кожа, очищенные травы. Переработка занимает время и может требовать вспомогательных материалов (топливо, вода).", "Система переработки вводит временной гейт: некоторые материалы требуют нескольких этапов переработки, создавая естественный ритм между сбором и кузнечным делом."]),
        section("forging-stage", "Этап 3: Кузнечное дело", ["Кузнечное дело на специализированных станциях (наковальни, столы заклинаний, кожевенные верстаки) объединяет переработанные материалы в оружие и доспехи. Каждый тип оружия требует определённого сочетання материалов и минимального уровня навыка кузнечного дела.", "Стандартное оружие, созданное крафтом, полностью функционально и может быть улучшено, вставлено сокеты и настроено, как любое другое снаряжение. Ключевое преимущество: крафтовое оружие стоит золота и времени, а не участия в данже или реальных денег."]),
        section("global-implications", "Что это означает для глобальных игроков", ["Глобальные игроки должны ожидать ту же трёхэтапную крафтовую цепочку. Модифицированная Season 1 может повлиять на ставки дропа крафтовых материалов и время переработки.", "Крафт становится особенно важным для игроков, которые не могут участвовать в организованных рейдах. Система стандартного оружия гарантирует, что все игроки могут построить конкурентоспособное снаряжение через посвящённую игру."]),
      ],
    }),
    ko: articleCopy(guideLabels, "ko", 7, {
      eyebrow: "제작",
      title: "Aion 2 제작 무기: 표준 진행이 어떻게 작동하는지와 만들 수 있는 것",
      description: "Aion 2 제작 시스템 가이드——플레이어가 채집, 재료 가공, 대장을 통해 표준 루트 무기를 어떻게 얻는지, 상점이나 던전 드랍에 의존하지 않고",
      intro: "한국 커뮤니티의 최신 제작 토론은 확인된 상세 내용에 초점을 맞춥니다: Aion 2의 신형 제작 무기는 표준 게임 방법——채집, 가공, 대장——으로 얻을 수 있습니다. 플레이어는 던전 드랍이나 현금 구매 없이 장비 진행이 가능합니다.",
      sourceNote: "게임톡의 2026년 9월 8일 Aion 2 제작 무기가 표준 방법으로 얻을 수 있다는 보고에 기반. 상세 내용은 한국 서버를 반영합니다.",
      keywords: ["Aion 2 제작 무기", "Aion 2 제작 가이드", "Aion 2 표준 진행", "Aion 2 대장 무기", "Aion 2 장비 진행"],
      sections: [
        section("crafting-overview", "제작 시스템 개요", ["Aion 2의 제작 시스템은 세 단계 파이프라인으로 작동합니다: 채집(오픈 월드에서 원자재를 수집)→ 가공(작업대에서 재료를 정련)→ 대장(전용 스테이션에서 무기와 장비를 제작). 각 단계에는 특정 재료, 시간, 플레이어 레벨이 필요합니다.", "일부 MMO에서 제작이 편의 기능에 그치지 않고, Aion 2의 시스템은 합법적 진행 경로로 설계되었습니다. 표준 루트로 제작된 무기는 기본 능력치에서 던전 드랍과 경쟁력이 있습니다."]),
        section("gathering-stage", "1단계: 채집", ["원자재는 오픈 월드에서 찾을 수 있습니다——광석, 목재, 약초, 몬스터 드랍. 모든 직업의 플레이어가 채집할 수 있지만, 일부 직업에는 채집 보너스가 있어 수율과 품질을 높입니다.", "재료 품질은 노드 레벨과 플레이어의 채집 스킬에 따라 달라집니다. 더 높은 채집 스킬은 더 높은 등급 노드를 해제하고, 후반 제작에 필요한 재료를 생산합니다."]),
        section("processing-stage", "2단계: 가공", ["원자재는 작업대에서 중간 부품으로 정련됩니다——정련 광석, 처리 목재, 가공 가죽, 정화 약초. 가공은 시간과 보조 재료(연료, 물)를 소모할 수 있습니다.", "가공 시스템은 시간 게이트를 도입합니다: 일부 재료는 여러 단계의 가공이 필요하여 채집과 대장 사이에 자연스러운 리듬을 만듭니다."]),
        section("forging-stage", "3단계: 대장", ["전용 스테이션(대장간, 마법 부여대, 가죽 가공대)에서의 대장은 가공된 재료를 무기와 방어구로 조합합니다. 각 무기 유형에는 특정 재료 조합과 최소 대장 스킬 레벨이 필요합니다.", "표준 루트로 제작된 무기는 완전히 기능적이며 다른 모든 장비와 마찬가지로 강화, 소켓팅, 튜닝할 수 있습니다. 핵심 이점: 제작 무기는 골드와 시간의 비용이며, 던전 참가나 현금 비용이 아닙니다."]),
        section("global-implications", "글로벌 플레이어에게 의미하는 바", ["글로벌 플레이어는 동일한 세 단계 제작 파이프라인을 기대해야 합니다. 수정된 Season 1이 제작 재료 드랍률과 가공 시간에 영향을 줄 수 있습니다.", "조직된 레이드에 참가할 수 없는 플레이어에게 제작은 특히 중요해집니다. 표준 루트 무기 시스템은 모든 플레이어가 전념 플레이로 경쟁력 있는 장비를 구축할 수 있음을 보장합니다."]),
      ],
    }),
    "zh-hant": articleCopy(guideLabels, "zh-hant", 7, {
      eyebrow: "製作",
      title: "Aion 2 製作武具：標準進階如何運作以及你能做什麼",
      description: "Aion 2 製作系統攻略——玩家如何通過採集、材料加工和鍛造獲得標準途徑武具，無需依賴商城或副本掉落",
      intro: "韓服社群最新的製作討論聚焦於一個已確認的細節：Aion 2 的新製作武具可透過標準遊戲方式獲得——採集、加工和鍛造。這意味著玩家無需副本掉落或商城購買即可推進裝備，製作成為了一條可行的競爭性裝備路徑。",
      sourceNote: "基於 게임톡（GameToc）2026 年 9 月 8 日關於 Aion 2 製作武具透過標準方式獲得的報道。細節反映韓服。",
      keywords: ["Aion 2 製作武具", "Aion 2 製作攻略", "Aion 2 標準進階", "Aion 2 鍛造武具", "Aion 2 裝備進階"],
      sections: [
        section("crafting-overview", "製作系統概覽", ["Aion 2 的製作系統運行在三級流水線上：採集（從野外收集原材料）→ 加工（在工作台精煉材料）→ 鍛造（在專用站點製作武器與裝備）。每個階段需要特定材料、時間和玩家等級。", "與某些 MMO 中製作僅是便利功能不同，Aion 2 的系統被設計為合法的進階路徑。標準途徑製作的武具在基礎屬性上與副本掉落有競爭力，差異化來自強化等級和鑲嵌加成。"]),
        section("gathering-stage", "第一級：採集", ["原材料在野外尋找——礦石、木材、草藥和怪物掉落。任何職業的玩家都可採集，但某些職業有採集加成，可提升產出和品質。", "材料品質隨節點等級和玩家採集技能變化。更高採集技能解鎖更高等級節點，產出終局製作所需材料。採集是進階循環的活躍部分，而非事後補充。"]),
        section("processing-stage", "第二級：加工", ["原材料在工作台精煉為中間組件——精煉礦石、處理木材、處理皮革、提純草藥。加工消耗時間，可能需要輔助材料（如燃料或水）。", "加工系統引入了時間關卡：某些材料需要多步加工，在採集和鍛造之間創造自然的節奏。這防止了即時刷取，獎勵投入製作流水線的玩家。"]),
        section("forging-stage", "第三級：鍛造", ["在專用站點（鐵砧、附魔台、皮革台）鍛造，將加工材料組合為武器和防具。每種武器類型需要特定的材料組合和最低鍛造技能等級。", "標準途徑製作的武具完全可用，可像任何其他裝備一樣強化、鑲嵌和調優。關鍵優勢：製作武具花費金幣和時間，而非副本參與或現金。", "對於無法持續通關終局副本的玩家，製作提供了可行的替代路徑來獲得競爭性裝備。"]),
        section("global-implications", "對全球玩家的意義", ["全球玩家應預期相同的三級製作流水線。改良版 Season 1（更長進度曲線）可能影響製作材料掉落率和加工時間，可能讓製作作為進階路徑更有價值。", "對於無法參與有組織副本的玩家，製作變得尤為重要。標準途徑武具系統確保所有玩家都能通過專注遊玩構建競爭性装備。", "全球玩家應在早期投入採集和鍛造技能，以最大化製作進階的效率。"]),
      ],
    }),
  },
};
