import { articleCopy, localizations, guideLabels, publishedVerified, section } from "./trending-september-16-shared";
import type { ContentEntry, ContentHeroImage, ContentSource } from "./content-registry";

const a11ySource: ContentSource = {
  id: "nc-aion2-official-accessibility",
  kind: "official",
  publisher: "NC Corporation",
  label: "Aion 2 Official — Settings & Accessibility",
  url: "https://aion2.plaync.com/en-us/gameplay/",
  publishedAt: "2026-08-15",
  retrievedAt: "2026-09-16",
  verifiedAt: "2026-09-16",
  localizations: localizations({
    "zh-hans": "Aion 2 官方 — 设置与无障碍", en: "Aion 2 Official — Settings & Accessibility",
    fr: "Aion 2 Officiel — Paramètres et Accessibilité", de: "Aion 2 Offiziell — Einstellungen & Barrierefreiheit",
    es: "Aion 2 Oficial — Configuración y Accesibilidad", ja: "Aion 2 公式 — 設定とアクセシビリティ",
    "pt-br": "Aion 2 Oficial — Configurações e Acessibilidade", ru: "Aion 2 Официальный — Настройки и Доступность",
    ko: "Aion 2 공식 — 설정 및 접근성", "zh-hant": "Aion 2 官方 — 設置與無障礙",
  }, "https://aion2.plaync.com/en-us/gameplay/"),
};

const a11yHero: ContentHeroImage = {
  src: "https://blogfiles.ncsoft.net/news/af7330da-4ff6-4b58-aece-400e6061a3be.jpg",
  width: 1200, height: 630,
  credit: "NC Corporation", sourceUrl: "https://aion2.plaync.com/en-us/", rights: "linked-official-media",
  translations: {
    "zh-hans": { alt: "Aion 2 无障碍功能攻略横幅", caption: "Aion 2 无障碍功能完整指南——视觉、听觉、输入自定义和性能优化选项。" },
    en: { alt: "Aion 2 Accessibility Features Guide Banner", caption: "Complete guide to Aion 2 accessibility features — visual, audio, input customization, and performance options." },
    fr: { alt: "Bannière Guide Accessibilité Aion 2", caption: "Guide complet des fonctionnalités d'accessibilité d'Aion 2 — visuel, audio, personnalisation des entrées et options de performance." },
    de: { alt: "Aion 2 Barrierefreiheit-Guide Banner", caption: "Kompletter Guide zu Aion 2 Barrierefreiheit — visuelle, auditive, Eingabe-Anpassung und Leistungsoptionen." },
    es: { alt: "Banner Guía Accesibilidad Aion 2", caption: "Guía completa de funciones de accesibilidad de Aion 2 — visual, audio, personalización de entrada y opciones de rendimiento." },
    ja: { alt: "Aion 2 アクセシビリティ機能ガイドバナー", caption: "Aion 2アクセシビリティ機能完全ガイド——視覚、聴覚、入力カスタマイズ、パフォーマンスオプション。" },
    "pt-br": { alt: "Banner Guia Acessibilidade Aion 2", caption: "Guia completo de acessibilidade do Aion 2 — visual, áudio, personalização de entrada e opções de performance." },
    ru: { alt: "Баннер Гайд Доступность Aion 2", caption: "Полное руководство по доступности Aion 2 — визуальная, звуковая, настройка ввода и параметры производительности." },
    ko: { alt: "Aion 2 접근성 기능 가이드 배너", caption: "Aion 2 접근성 기능 완전 가이드 — 시각, 오디오, 입력 커스터마이징, 성능 옵션." },
    "zh-hant": { alt: "Aion 2 無障礙功能攻略橫幅", caption: "Aion 2 無障礙功能完整指南——視覺、聽覺、輸入自定義和性能優化選項。" },
  },
};

export const trendingSeptember16Article5: ContentEntry = {
  section: "guides",
  slug: "aion-2-accessibility-features-guide",
  schemaType: "Article",
  publishedAt: "2026-09-16",
  updatedAt: "2026-09-16",
  readingMinutes: 5,
  publication: publishedVerified,
  sources: [a11ySource],
  heroImage: a11yHero,
  related: [
    { kind: "content", section: "guides", slug: "aion-2-system-requirements-pc-optimization-guide" },
    { kind: "content", section: "guides", slug: "aion-2-pc-performance-guide" },
    { kind: "content", section: "guides", slug: "aion-2-language-support-8-languages-guide" },
    { kind: "content", section: "guides", slug: "aion-2-cross-platform-guide" },
  ],
  translations: {
    en: articleCopy(guideLabels, "en", 5, {
      eyebrow: "ACCESSIBILITY",
      title: "Aion 2 Accessibility Features Guide: Visual, Audio, Input Customization and Performance Options",
      description: "Complete guide to Aion 2 accessibility features — colorblind modes, UI scaling, audio cues, key remapping, controller support, and performance settings for every player.",
      intro: "Aion 2 includes a comprehensive set of accessibility options designed to make the game playable and enjoyable for everyone. This guide covers every accessibility feature available, from visual aids and audio customization to input remapping and performance optimization for low-spec systems.",
      sourceNote: "Based on NC's official settings documentation and Korean service accessibility features as of September 2026.",
      keywords: ["Aion 2 accessibility", "Aion 2 colorblind mode", "Aion 2 UI scaling", "Aion 2 key remapping", "Aion 2 controller support"],
      sections: [
        section("visual-accessibility", "Visual Accessibility Options", ["Aion 2 includes three colorblind modes (protanopia, deuteranopia, tritanopia) that adjust UI element colors and indicators to improve visibility for colorblind players. These modes also adjust skill effect colors and enemy highlight outlines.", "UI scaling allows you to adjust the size of all interface elements independently. You can scale the minimap, action bars, chat window, and tooltips separately — useful for players who need larger text or have specific display requirements.", "High contrast mode increases the visual distinction between interactive elements and the background. Text outlines are thickened, button borders are more prominent, and important indicators glow more brightly. This mode is particularly useful for players with low vision or those playing on smaller screens.", "Reduced motion options minimize screen shake, particle effects, and camera animations. These options help players sensitive to motion-induced discomfort while still maintaining gameplay clarity."]),
        section("audio-accessibility", "Audio Accessibility Features", ["Aion 2 provides granular volume controls for each audio channel: master, music, sound effects, ambient, dialogue, and UI sounds. Each channel can be adjusted independently or muted entirely.", "Visual audio cues replace or supplement important sound-based gameplay elements. Skill cooldown completions, incoming attacks, and environmental alerts can all be displayed as on-screen indicators for hearing-impaired players.", "Directional audio indicators show the direction of important sounds on your minimap or as screen-edge markers. This helps players who cannot rely on spatial audio to identify threats and opportunities.", "Subtitle support includes full dialogue subtitles, system message captions, and optional descriptions for ambient sounds and music changes. Subtitles are customizable in size, position, and background opacity."]),
        section("input-customization", "Input Customization and Controller Support", ["Full key remapping is available for every action in the game. Every skill, menu command, and interface interaction can be rebound to any key or key combination. Multiple profiles can be saved and switched between for different content types.", "Controller support includes full button remapping, adjustable sensitivity for analog sticks, and configurable dead zones. Both PlayStation and Xbox controller layouts are supported natively, with custom layouts also available.", "Alternative input methods include mouse sensitivity adjustment, one-handed mode options that consolidate actions to one side of the keyboard, and toggle vs. hold options for movement and targeting.", "The macro system allows binding multiple actions to a single keypress. However, macros are limited to non-combat actions to comply with anti-cheat policies — combat macros that automate skill rotations are not permitted."]),
        section("performance-optimization", "Performance Optimization for Accessibility", ["FPS cap options allow you to limit frame rate for consistent performance on lower-spec systems. Options include 30, 60, 120, and uncapped FPS limits. The 30 FPS mode significantly reduces GPU load for older hardware.", "Low-spec mode automatically reduces graphical quality across all settings to prioritize performance. This mode disables shadows, reduces texture quality, simplifies particle effects, and lowers draw distance — making the game playable on integrated graphics and older GPUs.", "DLSS and FSR integration allows compatible graphics cards to render at lower resolution while maintaining visual quality through AI upscaling. This can dramatically improve frame rates on supported hardware.", "Loading optimization options include preloading assets for the next zone and reducing transition animation lengths. These options help players with slower storage drives experience shorter loading times."]),
        section("community-support", "Community Support and Feedback", ["NC maintains an accessibility feedback channel through the official forums and in-game support ticket system. Players can report accessibility issues, suggest improvements, and share their configuration presets with other players.", "Community-created accessibility presets are shared through the official forums. These presets bundle optimal settings for various accessibility needs and can be imported directly into your settings profile.", "The accessibility roadmap outlines planned future improvements including expanded colorblind options, text-to-speech integration for dialogue, and additional controller support for specialized input devices.", "For technical support with accessibility features, the in-game help system includes a dedicated accessibility section with troubleshooting guides and recommended settings for common accessibility needs."]),
      ],
    }),
    "zh-hans": articleCopy(guideLabels, "zh-hans", 5, {
      eyebrow: "无障碍",
      title: "Aion 2 无障碍功能指南：视觉、听觉、输入自定义和性能选项",
      description: "Aion 2 无障碍功能完整指南——色盲模式、UI 缩放、音频提示、按键重映射、手柄支持和性能设置。",
      intro: "Aion 2 包含全面的无障碍选项，旨在让每位玩家都能享受游戏。本指南覆盖所有无障碍功能——从视觉辅助和音频自定义到输入重映射和低配系统性能优化。",
      sourceNote: "基于 NC 官方设置文档和韩服无障碍功能（截至 2026 年 9 月）。",
      keywords: ["Aion 2 无障碍", "Aion 2 色盲模式", "Aion 2 UI 缩放", "Aion 2 按键重映射", "Aion 2 手柄支持"],
      sections: [
        section("visual-accessibility", "视觉无障碍选项", ["Aion 2 包含三种色盲模式（红色盲、绿色盲、蓝色盲），调整 UI 元素颜色和指示器以提高色盲玩家的可见性。这些模式还调整技能效果颜色和敌人高亮轮廓。", "UI 缩放允许独立调整所有界面元素大小。可以分别缩放迷你地图、动作栏、聊天窗口和工具提示——对需要更大文字或有特定显示需求的玩家很有用。", "高对比度模式增加交互元素和背景之间的视觉区分。文字轮廓加粗，按钮边框更突出，重要指示器更亮。此模式对低视力玩家或在较小屏幕上游戏的玩家特别有用。", "减少动态效果选项最小化屏幕震动、粒子效果和相机动画。帮助对动态不适敏感的玩家同时保持游戏清晰度。"]),
        section("audio-accessibility", "听觉无障碍功能", ["Aion 2 为每个音频通道提供精细音量控制：主音量、音乐、音效、环境、对话和 UI 声音。每个通道可独立调节或完全静音。", "视觉音频提示替代或补充基于声音的游戏元素。技能冷却完成、来袭攻击和环境警报都可以显示为屏幕指示器，帮助听障玩家。", "方向音频指示器在迷你地图上或屏幕边缘标记重要声音的方向。帮助无法依赖空间音频的玩家识别威胁和机会。", "字幕支持包括完整对话字幕、系统消息字幕和环境声音/音乐变化的可选描述。字幕可自定义大小、位置和背景透明度。"]),
        section("input-customization", "输入自定义与手柄支持", ["游戏中每个操作都支持完整按键重映射。每个技能、菜单命令和界面交互都可以绑定到任何按键或组合键。可保存多个配置方案并按内容类型切换。", "手柄支持包括完整按钮重映射、可调摇杆灵敏度和可配置死区。原生支持 PlayStation 和 Xbox 手柄布局，也可自定义布局。", "替代输入方式包括鼠标灵敏度调整、将操作集中到键盘一侧的单手模式选项，以及移动和瞄准的切换/按住选项。", "宏系统允许将多个动作绑定到单个按键。但宏仅限于非战斗操作以符合反作弊政策——自动化技能循环的战斗宏不被允许。"]),
        section("performance-optimization", "无障碍性能优化", ["帧率上限选项允许在低配系统上限制帧率以获得稳定性能。选项包括 30、60、120 和无上限。30 FPS 模式显著降低旧硬件的 GPU 负载。", "低配模式自动降低所有图形设置以优先保证性能。禁用阴影、降低纹理质量、简化粒子效果、降低渲染距离——使游戏在集成显卡和旧 GPU 上可玩。", "DLSS 和 FSR 集成允许兼容显卡以较低分辨率渲染同时通过 AI 放大保持视觉质量。可在支持的硬件上大幅提升帧率。", "加载优化选项包括预加载下一区域资源和减少过场动画长度。帮助使用较慢存储设备的玩家体验更短的加载时间。"]),
        section("community-support", "社区支持与反馈", ["NC 通过官方论坛和游戏内支持工单系统维护无障碍反馈渠道。玩家可以报告问题、建议改进并与其他玩家分享配置方案。", "社区创建的无障碍方案通过官方论坛分享。这些方案为各种无障碍需求打包了最优设置，可直接导入你的设置配置。", "无障碍路线图概述了计划中的未来改进，包括扩展色盲选项、对话文字转语音集成，以及对专用输入设备的额外手柄支持。", "关于无障碍功能的技术支持，游戏内帮助系统包含专门的无障碍部分，提供故障排除指南和常见无障碍需求的推荐设置。"]),
      ],
    }),
    fr: articleCopy(guideLabels, "fr", 5, {
      eyebrow: "ACCESSIBILITÉ",
      title: "Guide Accessibilité d'Aion 2 : Options Visuelles, Audio, Personnalisation des Entrées",
      description: "Guide complet des fonctionnalités d'accessibilité d'Aion 2 — modes daltoniens, échelle UI, indices audio, remappage de touches et options de performance.",
      intro: "Aion 2 inclut un ensemble complet d'options d'accessibilité conçues pour rendre le jeu jouable et agréable pour tous.",
      sourceNote: "Basé sur la documentation officielle des paramètres de NC (septembre 2026).",
      keywords: ["Accessibilité Aion 2", "Mode daltonien Aion 2", "Échelle UI Aion 2"],
      sections: [
        section("visual-accessibility", "Options d'Accessibilité Visuelle", ["Aion 2 inclut trois modes daltoniens qui ajustent les couleurs des éléments UI et les indicateurs.", "L'échelle UI permet d'ajuster la taille de tous les éléments d'interface indépendamment.", "Le mode contraste élevé augmente la distinction visuelle entre les éléments interactifs et l'arrière-plan.", "Les options de mouvement réduit minimisent les tremblements d'écran et les effets de particules."]),
        section("audio-accessibility", "Fonctionnalités d'Accessibilité Audio", ["Aion 2 fournit des contrôles de volume granulaires pour chaque canal audio.", "Les indices audio visuels remplacent les éléments de gameplay basés sur le son.", "Les indicateurs audio directionnels montrent la direction des sons importants.", "Le support des sous-titres inclut des sous-titres de dialogue complets et des personnalisations."]),
        section("input-customization", "Personnalisation des Entrées et Support Manette", ["Le remappage complet des touches est disponible pour chaque action.", "Le support manette inclut le remappage complet et la sensibilité ajustable.", "Les méthodes d'entrée alternatives incluent le mode à une main et les options toggle/maintenir.", "Le système de macros est limité aux actions non-combat pour la conformité anti-triche."]),
        section("performance-optimization", "Optimisation de Performance", ["Les options de limite FPS permettent de limiter le taux de rafraîchissement.", "Le mode low-spec réduit automatiquement la qualité graphique.", "L'intégration DLSS et FSR permet un upscaling par IA.", "Les options d'optimisation de chargement réduisent les temps de chargement."]),
        section("community-support", "Support Communautaire et Feedback", ["NC maintient un canal de feedback accessibilité via les forums officiels.", "Les presets d'accessibilité créés par la communauté sont partagés via les forums.", "La feuille de route accessibilité décrit les améliorations futures prévues.", "Le système d'aide en jeu inclut une section accessibilité dédiée."]),
      ],
    }),
    de: articleCopy(guideLabels, "de", 5, {
      eyebrow: "BARRENFREIHEIT",
      title: "Aion 2 Barrierefreiheit-Guide: Visuelle, Audio, Eingabe-Anpassung und Leistung",
      description: "Kompletter Guide zu Aion 2 Barrierefreiheit — Farbmodus, UI-Skalierung, Audio-Hinweise, Tastenbelegung und Leistungsoptionen.",
      intro: "Aion 2 umfasst ein umfassendes Set an Barrierefreiheitsoptionen für alle Spieler.",
      sourceNote: "Basierend auf NCs offizieller Einstellungs-Dokumentation (September 2026).",
      keywords: ["Aion 2 Barrierefreiheit", "Aion 2 Farbmodus"],
      sections: [
        section("visual-accessibility", "Visuelle Barrierefreiheitsoptionen", ["Aion 2 enthält drei Farbmodi für Farbenblinde.", "UI-Skalierung ermöglicht unabhängige Anpassung aller Interface-Elemente.", "Hochkontrast-Modus erhöht die visuelle Unterscheidung.", "Reduzierte Bewegungsoptionen minimieren Bildschirmshake und Partikeleffekte."]),
        section("audio-accessibility", "Audio-Barrierefreiheit", ["Granulare Lautstärkeregelung für jeden Audiokanal.", "Visuelle Audio-Hinweise ersetzen soundbasierte Gameplay-Elemente.", "Direktionale Audio-Indikatoren zeigen Richtung wichtiger Sounds.", "Untertitel-Unterstützung mit Anpassungsmöglichkeiten."]),
        section("input-customization", "Eingabe-Anpassung und Controller-Support", ["Vollständige Tastenbelegung für jede Aktion.", "Controller-Support mit voller Neubelegung und einstellbarer Empfindlichkeit.", "Alternative Eingabemethoden einschließlich Einhand-Modus.", "Makro-System auf Nicht-Kampf-Aktionen beschränkt."]),
        section("performance-optimization", "Leistungsoptimierung", ["FPS-Cap-Optionen für konsistente Leistung.", "Low-Spec-Modus reduziert automatisch Grafikqualität.", "DLSS- und FSR-Integration für AI-Upscaling.", "Ladeoptimierung für langsamere Speicher."]),
        section("community-support", "Community-Support und Feedback", ["NC unterhält einen Barrierefreiheits-Feedback-Kanal.", "Community-Erstellte Presets werden geteilt.", "Barrierefreiheits-Roadmap skizziert zukünftige Verbesserungen.", "In-Game-Hilfe mit dediziertem Barrierefreiheits-Bereich."]),
      ],
    }),
    es: articleCopy(guideLabels, "es", 5, {
      eyebrow: "ACCESIBILIDAD",
      title: "Guía de Accesibilidad de Aion 2: Visual, Audio, Personalización de Entrada",
      description: "Guía completa de funciones de accesibilidad de Aion 2 — modos daltonismo, escala UI, pistas de audio, remapeo de teclas y opciones de rendimiento.",
      intro: "Aion 2 incluye un conjunto completo de opciones de accesibilidad para todos los jugadores.",
      sourceNote: "Basado en la documentación oficial de configuración de NC (septiembre 2026).",
      keywords: ["Accesibilidad Aion 2", "Modo daltonismo Aion 2"],
      sections: [
        section("visual-accessibility", "Opciones de Accesibilidad Visual", ["Aion 2 incluye tres modos de daltonismo.", "La escala UI permite ajustar elementos de interfaz independientemente.", "El modo alto contraste aumenta la distinción visual.", "Opciones de movimiento reducido minimizan el shake de pantalla."]),
        section("audio-accessibility", "Funciones de Accesibilidad Audio", ["Controles de volumen granulares por canal.", "Pistas visuales de audio para jugadores con discapacidad auditiva.", "Indicadores direccionales de audio.", "Soporte de subtítulos personalizable."]),
        section("input-customization", "Personalización de Entrada y Soporte de Mando", ["Remapeo completo de teclas.", "Soporte de mando con remapeo y sensibilidad ajustable.", "Métodos de entrada alternativos incluyendo modo a una mano.", "Sistema de macros limitado a acciones no combate."]),
        section("performance-optimization", "Optimización de Rendimiento", ["Opciones de límite de FPS.", "Modo low-spec reduce calidad gráfica automáticamente.", "Integración DLSS y FSR.", "Optimización de carga."]),
        section("community-support", "Soporte Comunitario y Feedback", ["Canal de feedback de accesibilidad de NC.", "Presets de accesibilidad de la comunidad.", "Hoja de ruta de accesibilidad.", "Sistema de ayuda con sección de accesibilidad."]),
      ],
    }),
    ja: articleCopy(guideLabels, "ja", 5, {
      eyebrow: "アクセシビリティ",
      title: "Aion 2 アクセシビリティ機能ガイド：視覚、聴覚、入力カスタマイズとパフォーマンスオプション",
      description: "Aion 2アクセシビリティ機能完全ガイド——色覚モード、UIスケーリング、オーディオキュー、キーリマッピング、パフォーマンス設定。",
      intro: "Aion 2はすべてのプレイヤーにゲームを楽しんでもらうための包括的なアクセシビリティオプションを備えています。",
      sourceNote: "NC公式設定文書基準（2026年9月）。",
      keywords: ["Aion 2 アクセシビリティ", "Aion 2 色覚モード"],
      sections: [
        section("visual-accessibility", "視覚アクセシビリティオプション", ["3つの色覚モードを搭載。", "UIスケーリングでインターフェース要素を独立調整。", "ハイコントラストモードで視覚的区別を強化。", "動作軽減オプションで画面揺れとパーティクルを最小化。"]),
        section("audio-accessibility", "聴覚アクセシビリティ機能", ["各オーディオチャンネルの細かな音量制御。", "聴覚障害者向け視覚オーディオキュー。", "方向性オーディオインジケーター。", "カスタマイズ可能な字幕サポート。"]),
        section("input-customization", "入力カスタマイズとコントローラーサポート", ["全アクションの完全キーリマッピング。", "完全リマッピングと感度調整可能なコントローラーサポート。", "片手モードを含む代替入力方法。", "マクロシステムは非戦闘アクションに制限。"]),
        section("performance-optimization", "パフォーマンス最適化", ["FPSキャップオプション。", "ロースペックモードで自動画質低下。", "DLSS/FSR統合。", "読み込み最適化。"]),
        section("community-support", "コミュニティサポートとフィードバック", ["NC公式フォーラムのアクセシビリティフィードバックチャンネル。", "コミュニティ作成アクセシビリティプリセット。", "将来の改善計画のアクセシビリティロードマップ。", "専用アクセシビリティセクション付きゲーム内ヘルプ。"]),
      ],
    }),
    "pt-br": articleCopy(guideLabels, "pt-br", 5, {
      eyebrow: "ACESSIBILIDADE",
      title: "Guia de Acessibilidade do Aion 2: Visual, Áudio, Personalização de Entrada",
      description: "Guia completo de acessibilidade do Aion 2 — modos daltonismo, escala UI, pistas de áudio, remapeamento de teclas e opções de performance.",
      intro: "Aion 2 inclui um conjunto abrangente de opções de acessibilidade para todos os jogadores.",
      sourceNote: "Baseado na documentação oficial de configurações da NC (setembro 2026).",
      keywords: ["Acessibilidade Aion 2", "Modo daltonismo Aion 2"],
      sections: [
        section("visual-accessibility", "Opções de Acessibilidade Visual", ["Três modos de daltonismo.", "Escala UI para ajuste independente.", "Modo alto contraste.", "Opções de movimento reduzido."]),
        section("audio-accessibility", "Recursos de Acessibilidade de Áudio", ["Controles granulares de volume por canal.", "Pistas visuais de áudio.", "Indicadores direcionais de áudio.", "Suporte a legendas personalizável."]),
        section("input-customization", "Personalização de Entrada e Suporte a Controle", ["Remapeamento completo de teclas.", "Suporte a controle com remapeamento e sensibilidade.", "Métodos alternativos incluindo modo de uma mão.", "Sistema de macros limitado a ações não combate."]),
        section("performance-optimization", "Otimização de Performance", ["Opções de limite de FPS.", "Modo low-spec reduz qualidade automaticamente.", "Integração DLSS e FSR.", "Otimização de carregamento."]),
        section("community-support", "Suporte da Comunidade e Feedback", ["Canal de feedback de acessibilidade da NC.", "Presets de acessibilidade da comunidade.", "Roteiro de acessibilidade.", "Ajuda no jogo com seção dedicada."]),
      ],
    }),
    ru: articleCopy(guideLabels, "ru", 5, {
      eyebrow: "ДОСТУПНОСТЬ",
      title: "Гайд по Доступности Aion 2: Визуальная, Звуковая, Настройка Ввода и Производительность",
      description: "Полное руководство по доступности Aion 2 — режимы дальтонизма, масштабирование UI, звуковые подсказки, переназначение клавиш и настройки производительности.",
      intro: "Aion 2 включает полный набор опций доступности для всех игроков.",
      sourceNote: "На основе официальной документации настроек NC (сентябрь 2026).",
      keywords: ["Доступность Aion 2", "Режим дальтонизма Aion 2"],
      sections: [
        section("visual-accessibility", "Визуальные Опции Доступности", ["Три режима дальтонизма.", "Масштабирование UI для независимой настройки.", "Режим высокого контраста.", "Опции уменьшения движения."]),
        section("audio-accessibility", "Звуковые Функции Доступности", ["Гранулярное управление громкостью по каналам.", "Визуальные звуковые подсказки.", "Направленные индикаторы звука.", "Настраиваемая поддержка субтитров."]),
        section("input-customization", "Настройка Ввода и Поддержка Контроллера", ["Полное переназначение клавиш.", "Поддержка контроллера с переназначением и чувствительностью.", "Альтернативные методы ввода включая однорукий режим.", "Система макросов ограничена не-боевыми действиями."]),
        section("performance-optimization", "Оптимизация Производительности", ["Опции ограничения FPS.", "Режим low-spec автоматически снижает качество.", "Интеграция DLSS и FSR.", "Оптимизация загрузки."]),
        section("community-support", "Поддержка Сообщества и Обратная Связь", ["Канал обратной связи NC по доступности.", "Пресеты доступности от сообщества.", "Дорожная карта доступности.", "Внутриигровая справка с выделенным разделом."]),
      ],
    }),
    ko: articleCopy(guideLabels, "ko", 5, {
      eyebrow: "접근성",
      title: "Aion 2 접근성 기능 가이드: 시각, 오디오, 입력 커스터마이징 및 성능 옵션",
      description: "Aion 2 접근성 기능 완전 가이드 — 색각 모드, UI 스케일링, 오디오 큐, 키 리매핑, 컨트롤러 지원 및 성능 설정.",
      intro: "Aion 2는 모든 플레이어가 게임을 즐길 수 있도록 포괄적인 접근성 옵션을 포함합니다.",
      sourceNote: "NC 공식 설정 문서 기준 (2026년 9월).",
      keywords: ["Aion 2 접근성", "Aion 2 색각 모드"],
      sections: [
        section("visual-accessibility", "시각 접근성 옵션", ["세 가지 색각 모드.", "UI 요소 독립 조정이 가능한 UI 스케일링.", "시각적 구분을 높이는 하이컨트라스트 모드.", "화면 흔들림과 파티클 효과를 최소화하는 동작 감소 옵션."]),
        section("audio-accessibility", "오디오 접근성 기능", ["각 오디오 채널의 세밀한 볼륨 제어.", "청각 장애 플레이어를 위한 시각 오디오 큐.", "방향성 오디오 인디케이터.", "커스터마이즈 가능한 자막 지원."]),
        section("input-customization", "입력 커스터마이징 및 컨트롤러 지원", ["모든 동작의 완전한 키 리매핑.", "리매핑 및 감도 조절이 가능한 컨트롤러 지원.", "한 손 모드 포함 대체 입력 방법.", "치트 방지 정책을 위한 비전투 동작으로 제한된 매크로 시스템."]),
        section("performance-optimization", "접근성 성능 최적화", ["일관된 성능을 위한 FPS 캡 옵션.", "자동으로 그래픽 품질을 낮추는 저사양 모드.", "AI 업스케일링을 위한 DLSS 및 FSR 통합.", "느린 스토리지 드라이브를 위한 로딩 최적화."]),
        section("community-support", "커뮤니티 지원 및 피드백", ["공식 포럼을 통한 NC 접근성 피드백 채널.", "커뮤니티 제작 접근성 프리셋 공유.", "향후 개선 계획을 담은 접근성 로드맵.", "전용 접근성 섹션이 포함된 게임 내 도움말."]),
      ],
    }),
    "zh-hant": articleCopy(guideLabels, "zh-hant", 5, {
      eyebrow: "無障礙",
      title: "Aion 2 無障礙功能指南：視覺、聽覺、輸入自定義和性能選項",
      description: "Aion 2 無障礙功能完整指南——色盲模式、UI 縮放、音頻提示、按鍵重映射、手柄支持和性能設置。",
      intro: "Aion 2 包含全面的無障礙選項，旨在讓每位玩家都能享受遊戲。",
      sourceNote: "基於 NC 官方設置文檔和韓服無障礙功能（截至 2026 年 9 月）。",
      keywords: ["Aion 2 無障礙", "Aion 2 色盲模式"],
      sections: [
        section("visual-accessibility", "視覺無障礙選項", ["三種色盲模式。", "UI 縮放獨立調整所有界面元素。", "高對比度模式增加視覺區分。", "減少動態效果選項最小化屏幕震動和粒子效果。"]),
        section("audio-accessibility", "聽覺無障礙功能", ["每個音頻通道的精細音量控制。", "視覺音頻提示替代聲音遊戲元素。", "方向音頻指示器。", "可自定義的字幕支持。"]),
        section("input-customization", "輸入自定義與手柄支持", ["每個操作的完整按鍵重映射。", "手柄支持包括按鈕重映射和靈敏度調整。", "替代輸入方式包括單手模式。", "宏系統僅限非戰鬥操作。"]),
        section("performance-optimization", "無障礙性能優化", ["幀率上限選項。", "低配模式自動降低圖形質量。", "DLSS 和 FSR 集成。", "加載優化選項。"]),
        section("community-support", "社區支持與反饋", ["NC 通過官方論壇維護無障礙反饋渠道。", "社區創建的無障礙方案分享。", "無障礙路線圖概述未來改進。", "遊戲內幫助系統包含專門的無障礙部分。"]),
      ],
    }),
  },
};
