import { articleCopy, localizations, guideLabels, publishedVerified, section } from "./trending-september-7-shared";
import type { ContentSource, ContentHeroImage } from "./content-registry";

/* ARTICLE 5 — Cross-server matching and faction balance in PvP (newly detailed at Gamescom, September 6 report) */

const csSource1: ContentSource = {
  id: "guided-news-matching-2026-09-06",
  kind: "third-party",
  publisher: "Guided News",
  label: "AION 2: NC will beim westlichen Release vieles besser machen (PvP & matching section)",
  url: "https://guided.news/en/opinion/aion-2-nc-wants-to-do-a-lot-better-with-the-western-release/",
  publishedAt: "2026-09-06",
  retrievedAt: "2026-09-07",
  verifiedAt: "2026-09-07",
  localizations: localizations({
    "zh-hans": "AION 2：NC 要让西区发行做得更好（PvP 与匹配章节）",
    en: "AION 2: NC wants to do a lot better with the western release (PvP & matching section)",
    fr: "AION 2 : NC veut faire mieux à l'Ouest (section PvP et matchmaking)",
    de: "AION 2: NC will es im Westen besser machen (Abschnitt PvP & Matching)",
    es: "AION 2: NC quiere hacerlo mejor en Occidente (sección PvP y emparejamiento)",
    ja: "AION 2：NCは西側でより良くしたい（PvP・マッチング節）",
    "pt-br": "AION 2: a NC quer fazer melhor no Ocidente (seção PvP e matchmaking)",
    ru: "AION 2: NC хочет сделать лучше на Западе (раздел PvP и подбора)",
    ko: "AION 2: NC, 서구에서 더 잘 하고 싶다 (PvP·매칭 섹션)",
    "zh-hant": "AION 2：NC 要讓西區做得更好（PvP 與匹配章節）",
  }, "https://guided.news/en/opinion/aion-2-nc-wants-to-do-a-lot-better-with-the-western-release/"),
};

const csSource2: ContentSource = {
  id: "aion2-official-teaser-2026-09-07",
  kind: "official",
  publisher: "NCSoft",
  label: "AION 2 Official Site — Game Overview (Elyos vs Asmodians, Abyss)",
  url: "https://aion2.plaync.com/en-us/",
  publishedAt: "2026-08-25",
  retrievedAt: "2026-09-07",
  verifiedAt: "2026-09-07",
  localizations: localizations({
    "zh-hans": "AION 2 官网——游戏总览（天族 vs 魔族、深渊）",
    en: "AION 2 Official Site — Game Overview (Elyos vs Asmodians, Abyss)",
    fr: "Site officiel d'AION 2 — Présentation (Elyos vs Asmodiens, Abysse)",
    de: "AION 2 Offizielle Website — Spielübersicht (Elyos vs Asmodier, Abyss)",
    es: "Sitio oficial de AION 2 — Resumen (Elyos vs Asmodianos, Abismo)",
    ja: "AION 2 公式サイト——ゲーム概要（天族 vs 魔族、アビス）",
    "pt-br": "Site oficial do AION 2 — Visão geral (Elyos vs Asmodianos, Abismo)",
    ru: "Официальный сайт AION 2 — Обзор (Элиос против Асмодиан, Бездна)",
    ko: "AION 2 공식 사이트 — 게임 개요(엘리오스 vs 아스모디안, 아비스)",
    "zh-hant": "AION 2 官網——遊戲總覽（天族 vs 魔族、深淵）",
  }, "https://aion2.plaync.com/en-us/"),
};

const csHero: ContentHeroImage = {
  src: "https://blogfiles.ncsoft.net/news/af7330da-4ff6-4b58-aece-400e6061a3be.jpg",
  width: 1200, height: 630,
  credit: "NC Corporation",
  sourceUrl: "https://aion2.plaync.com/en-us/",
  rights: "linked-official-media",
  translations: {
    "zh-hans": { alt: "Aion 2 跨服匹配指南横幅", caption: "NC 的跨服匹配系统将阵营与服务器组合配对，避免 90/10 一边倒的阵营失衡。" },
    en: { alt: "Aion 2 cross-server matching guide banner", caption: "NC's cross-server matching pairs factions and servers to avoid lopsided 90/10 faction imbalances." },
    fr: { alt: "Bannière du guide de matchmaking inter-serveur d'AION 2", caption: "Le matchmaking inter-serveur de NC combine factions et serveurs pour éviter les déséquilibres 90/10." },
    de: { alt: "Banner zum Cross-Server-Matching in Aion 2", caption: "NCS Cross-Server-Matching kombiniert Fraktionen und Server, um 90/10-Imbalancen zu vermeiden." },
    es: { alt: "Banner de la guía de emparejamiento entre servidores de AION 2", caption: "El emparejamiento entre servidores de NC combina facciones y servidores para evitar desequilibrios 90/10." },
    ja: { alt: "Aion 2 クロスサーバーマッチングガイドバナー", caption: "NCのクロスサーバーマッチングは陣営とサーバーを組み合わせ、90/10の一方的不均衡を防ぎます。" },
    "pt-br": { alt: "Banner do guia de matchmaking entre servidores do AION 2", caption: "O matchmaking entre servidores da NC combina facções e servidores para evitar desequilíbrios 90/10." },
    ru: { alt: "Баннер гайда по кросс-серверному подбору Aion 2", caption: "Кросс-серверный подбор NC сочетает фракции и серверы, избегая перекоса 90/10." },
    ko: { alt: "Aion 2 크로스 서버 매칭 가이드 배너", caption: "NC의 크로스 서버 매칭이 진영과 서버를 조합해 90/10 편중을 막습니다." },
    "zh-hant": { alt: "Aion 2 跨服配對指南橫幅", caption: "NC 的跨服配對系統將陣營與伺服器組合配對，避免 90/10 一邊倒的陣營失衡。" },
  },
};

export const trendingSeptember7Article5: ContentEntry = {
  section: "guides",
  slug: "aion-2-cross-server-matching-faction-balance-guide",
  schemaType: "Article",
  publishedAt: "2026-09-07",
  updatedAt: "2026-09-07",
  readingMinutes: 6,
  publication: publishedVerified,
  sources: [csSource1, csSource2],
  heroImage: csHero,
  related: [
    { kind: "content", section: "guides", slug: "aion-2-abyss-system-complete-guide" },
    { kind: "content", section: "guides", slug: "aion-2-pvp-guide" },
    { kind: "content", section: "guides", slug: "aion-2-abyss-rift-zone-guide" },
  ],
  translations: {
    en: articleCopy(guideLabels, "en", 6, {
      eyebrow: "FACTION BALANCE GUIDE",
      title: "Aion 2 Cross-Server Matching: How NCsoft Plans to Keep Faction PvP Balanced",
      description: "The cross-server matching system detailed at Gamescom: combining factions and servers for balanced encounters, cross-server realm-vs-realm battles, and what it means for Abyss faction wars and your server choice",
      intro: "Faction MMOs live or die on population balance — on a server that drifts to 90% Elyos, the Asmodian side stops being fun. At Gamescom, NCsoft described its answer: a cross-server matching system that pairs factions and servers so encounters stay balanced, with realm-vs-realm battles running across servers rather than inside one.",
      keywords: ["Aion 2 cross-server matching", "Aion 2 faction balance PvP", "Aion 2 realm vs realm server", "Aion 2 Abyss faction war balance", "Aion 2 server population imbalance"],
      sourceNote: "Based on Guided News' September 6 report of its Gamescom appointment with NCsoft (PvP and matching details), cross-checked with the official AION 2 site describing faction and Abyss concepts (retrieved September 7, 2026).",
      sections: [
        section("the-imbalance-problem", "The Classic 90/10 Faction Problem", ["Faction-based MMORPGs share a recurring failure: one side eventually dominates a server so heavily that PvP stops being fun for the losing faction. Guided News' report put exactly this question — what if a server ends up 90% Elyos and 10% Asmodian? — to the studio during the Gamescom briefing.", "That question matters for Aion 2 because Elyos vs Asmodian is not cosmetic: the two factions start on opposite sides of the world, and in faction PvP the mirror matchups decide who controls content."]),
        section("cross-server-matching", "The Answer: Cross-Server Matching", ["NCsoft's described solution is a server-transcending matching system: factions and servers are combined as much as possible so that encounters are balanced.", "Concretely, the big realm-vs-realm battles also operate cross-server — the system does not have to work only with the players of a single server. The report judges this a more sensible technical foundation than a rigid server structure, while noting long-term fairness still has to prove itself."]),
        section("how-pvp-is-structured", "How Aion 2 PvP Is Structured Around It", ["The PvP spectrum runs from classic 1-vs-1 duels and 4-vs-4 arenas up to large realm-vs-realm battles where players from different servers meet.", "The Abyss returns as the central faction-based PvP zone: Elyos and Asmodians begin on different sides of the world, their paths inevitably converge, and peaceful sky exploration flips quickly into war — exactly where the matching system is meant to keep numbers fair."]),
        section("what-it-means-for-free-players", "What It Means for Free Players and Server Choice", ["Because encounters are matched across servers, faction population math becomes less punishing: a minority faction on your home server is not automatically doomed in cross-server battles.", "Server choice therefore becomes more about community, language, and latency (see our server region guide for the NA/SA/EU/JP map) than about 'which side has more players' — and the western F2P model keeps Abyss access unlimited for free players, so participation is open to everyone."]),
        section("what-to-watch", "What to Watch After Launch", ["Watch how the matchmaker treats peak-hour waits: cross-server balancing can mean longer queues when population is thin, especially in off-peak windows.", "Before launch, your practical moves: pick your faction by playstyle and community rather than population guesses, confirm your region's server (and the Taiwan-English option if applicable), and re-check this guide after the October 5 launch once NCsoft confirms matchmaking details in patch notes."]),
      ],
    }),
    "zh-hans": articleCopy(guideLabels, "zh-hans", 6, {
      eyebrow: "阵营平衡攻略",
      title: "Aion 2 跨服匹配：NC 如何维持阵营 PvP 平衡",
      description: "Gamescom 披露的跨服匹配系统：阵营与服务器组合配对保证对战均衡、跨服阵营大战，以及对深渊阵营战与服务器选择的含义",
      intro: "阵营 MMO 的成败取决于人口平衡——当服务器漂移到九成天族时，魔族一侧就不再好玩。在 Gamescom，NCsoft 描述了它的答案：一套跨服匹配系统，将阵营与服务器配对，让对战保持均衡；大型阵营战也跨服运作，而非局限于单服。",
      sourceNote: "基于 Guided News 9 月 6 日 Gamescom 约谈报道（PvP 与匹配细节），并与 AION 2 官网中阵营与深渊概念（2026-09-07 抓取）交叉核对。",
      keywords: ["Aion 2 跨服匹配", "Aion 2 阵营平衡 PvP", "Aion 2 跨服阵营战", "Aion 2 深渊阵营战平衡", "Aion 2 服务器人口失衡"],
      sections: [
        section("the-imbalance-problem", "经典的九成一边倒问题", ["阵营制 MMORPG 有一个常见失败模式：某一阵营最终严重碾压服务器，输方 PvP 失去乐趣。Guided News 在 Gamescom 简报中直接把这个问题抛给了官方——如果某服变成 90% 天族、10% 魔族会怎样？", "这个问题对 Aion 2 尤为关键：天族 vs 魔族不是装饰——两阵营从世界两端出发，阵营 PvP 的对局决定内容归属。"]),
        section("cross-server-matching", "答案：跨服匹配", ["NCsoft 描述的方案是跨服务器匹配系统：尽可能组合阵营与服务器，让对战保持均衡。", "具体而言，大型阵营战同样跨服运作——系统不必只依赖单服玩家。报道评价这比僵化的服务器结构更合理，但长期公平仍需验证。"]),
        section("how-pvp-is-structured", "围绕它的 PvP 结构", ["PvP 谱系从经典的 1v1 决斗、4v4 竞技场直到多服玩家会师的大型阵营战。", "深渊作为核心阵营 PvP 区域回归：天族与魔族从世界两端出发，道路必然交汇，和平的天空探索很快变成战争——这正是匹配系统要保证人数公平的战场。"]),
        section("what-it-means-for-free-players", "对免费玩家与服务器选择的意义", ["因为对战跨服匹配，阵营人口数学的惩罚变轻：主服少数阵营不会在跨服战中自动出局。", "服务器选择因此更关乎社区、语言与延迟（见本站服务器区域指南，NA/SA/EU/JP 四区域），而西区 F2P 模型对免费玩家保持深渊无时限——人人可参战。"]),
        section("what-to-watch", "上线后观察什么", ["观察匹配器在高峰时段的等待表现：跨服平衡在人口稀疏的深夜可能带来更长队列。", "上线前你的务实动作：按玩法偏好与社区而非人口猜测选阵营；确认所属区域的服务器（如适用考虑台服英文班）；10 月 5 日上线、NC 在补丁说明确认匹配细节后再回来复核本指南。"]),
      ],
    }),
    fr: articleCopy(guideLabels, "fr", 6, {
      eyebrow: "GUIDE ÉQUILIBRE FACTION",
      title: "Matchmaking inter-serveur d'Aion 2 : comment NC compte équilibrer le PvP de factions",
      description: "Le matchmaking inter-serveur présenté à la Gamescom : combiner factions et serveurs, batailles inter-serveurs, et ce que cela change pour l'Abysse et le choix du serveur",
      intro: "Les MMO à factions vivent ou meurent sur l'équilibre des populations — sur un serveur à 90 % Elyos, le côté Asmodien n'est plus amusant. À la Gamescom, NCsoft a décrit sa réponse : un matchmaking inter-serveur qui combine factions et serveurs pour des affrontements équilibrés.",
      sourceNote: "Basé sur le rapport de Guided News du 6 septembre (PvP et matchmaking), recoupé avec le site officiel d'AION 2 (7 septembre 2026).",
      keywords: ["Aion 2 matchmaking inter-serveur", "Aion 2 équilibre factions PvP", "Aion 2 combat factions serveur", "Aion 2 Abysse équilibre", "Aion 2 déséquilibre population"],
      sections: [
        section("the-imbalance-problem", "Le problème 90/10", "Dans les MMO à factions, un côté domine et le PvP perd son intérêt pour l'autre ; la question du 90 % Elyos / 10 % Asmodien a été posée directement à NC à la Gamescom."),
        section("cross-server-matching", "La réponse : matchmaking inter-serveur", "Un système qui combine factions et serveurs pour des rencontres équilibrées ; les grandes batailles inter-serveurs ne dépendent pas d'un seul serveur — une base plus saine qu'une structure rigide, selon le rapport."),
        section("how-pvp-is-structured", "La structure PvP autour de lui", "Du duel 1v1 aux arènes 4v4 jusqu'aux grandes batailles inter-serveurs ; l'Abysse reste la zone PvP centrale de factions, les chemins des deux camps convergeant forcément."),
        section("what-it-means-for-free-players", "Pour les gratuits et le choix du serveur", "La minorité de faction d'un serveur n'est plus condamnée ; le choix du serveur devient communauté/langue/latence, et l'accès à l'Abysse reste illimité pour les gratuits."),
        section("what-to-watch", "À surveiller après le lancement", "Files d'attente possibles en heures creuses ; avant le lancement : choisissez la faction par style, confirmez le serveur de votre région, et revérifiez ce guide après le 5 octobre."),
      ],
    }),
    de: articleCopy(guideLabels, "de", 6, {
      eyebrow: "FRAKTIONSBALANCE",
      title: "Aion 2 Cross-Server-Matching: So will NC die Fraktions-PvP-Balance halten",
      description: "Das in Gamescom vorgestellte Cross-Server-Matching: Fraktionen und Server kombinieren, Cross-Server-Realmkämpfe — und was das für den Abyss und die Serverwahl bedeutet",
      intro: "Fraktions-MMOs stehen und fallen mit der Populationsbalance — auf einem Server mit 90 % Elyos verliert die Asmodier-Seite den Spaß. In Gamescom beschrieb NCsoft die Antwort: ein Cross-Server-Matching, das Fraktionen und Server kombiniert, damit Begegnungen ausgeglichen bleiben.",
      sourceNote: "Basierend auf dem Guided-News-Bericht vom 6. September (PvP und Matching), abgeglichen mit der offiziellen AION-2-Seite (7. September 2026).",
      keywords: ["Aion 2 Cross-Server-Matching", "Aion 2 Fraktionsbalance PvP", "Aion 2 Realm-Schlacht Server", "Aion 2 Abyss Balance", "Aion 2 Server-Imbalance"],
      sections: [
        section("the-imbalance-problem", "Das 90/10-Problem", "Bei Fraktions-MMOs dominiert irgendwann eine Seite so stark, dass PvP für die Verlierer keinen Spaß mehr macht; genau diese Frage (90 % Elyos / 10 % Asmodier) wurde NC in Gamescom gestellt."),
        section("cross-server-matching", "Die Antwort: Cross-Server-Matching", "Ein System, das Fraktionen und Server möglichst kombiniert; auch große Realm-Schlachten laufen serverspannend — eine vernünftigere Basis als starre Serverstruktur, laut Bericht."),
        section("how-pvp-is-structured", "Die PvP-Struktur darum herum", "Vom 1v1-Duell über 4v4-Arenen bis zu großen serverübergreifenden Schlachten; der Abyss bleibt die zentrale Fraktions-PvP-Zone, beide Seiten treffen sich unweigerlich."),
        section("what-it-means-for-free-players", "Für Gratisspieler und Serverwahl", "Die Fraktionsminderheit des Heimservers ist nicht mehr automatisch verloren; die Serverwahl wird zu Community/Sprache/Latenz, und der Abyss bleibt für Gratisspieler unbegrenzt."),
        section("what-to-watch", "Nach dem Start beobachten", "Mögliche Wartezeiten in Schwachlastzeiten; vor dem Start: Fraktion nach Spielstil wählen, Regionsserver bestätigen, und diese Seite nach dem 5. Oktober erneut prüfen."),
      ],
    }),
    es: articleCopy(guideLabels, "es", 6, {
      eyebrow: "EQUILIBRIO DE FACCIÓN",
      title: "Emparejamiento entre servidores de Aion 2: cómo planea NC mantener el equilibrio del PvP de facciones",
      description: "El emparejamiento entre servidores presentado en Gamescom: combinar facciones y servidores, batallas inter-servidores, y su impacto en el Abismo y la elección de servidor",
      intro: "Los MMO de facciones viven o mueren por el equilibrio de población — en un servidor con 90 % de Elyos, el lado Asmodiano deja de ser divertido. En Gamescom, NCsoft describió su respuesta: un emparejamiento entre servidores que combina facciones y servidores para encuentros equilibrados.",
      sourceNote: "Basado en el informe de Guided News del 6 de septiembre (PvP y emparejamiento), cotejado con el sitio oficial de AION 2 (7 de septiembre de 2026).",
      keywords: ["Aion 2 emparejamiento servidores", "Aion 2 equilibrio facciones PvP", "Aion 2 batalla facciones servidor", "Aion 2 Abismo equilibrio", "Aion 2 desequilibrio población"],
      sections: [
        section("the-imbalance-problem", "El problema 90/10", "En los MMO de facciones, un lado acaba dominando y el PvP deja de ser divertido para el perdedor; la pregunta del 90 % Elyos / 10 % Asmodiano se planteó directamente a NC en Gamescom."),
        section("cross-server-matching", "La respuesta: emparejamiento entre servidores", "Un sistema que combina facciones y servidores para encuentros equilibrados; las grandes batallas entre servidores no dependen de uno solo — una base más sana que una estructura rígida, según el informe."),
        section("how-pvp-is-structured", "La estructura PvP alrededor", "Del duelo 1v1 a las arenas 4v4 hasta grandes batallas entre servidores; el Abismo sigue siendo la zona PvP central de facciones y los caminos convergen inevitablemente."),
        section("what-it-means-for-free-players", "Para gratuitos y elección de servidor", "La minoría de facción de tu servidor ya no está condenada; la elección pasa a ser comunidad/idioma/latencia, y el acceso al Abismo sigue ilimitado para gratuitos."),
        section("what-to-watch", "Qué observar tras el lanzamiento", "Posibles colas en horas valle; antes del lanzamiento: elige facción por estilo, confirma el servidor de tu región y revisa esta guía tras el 5 de octubre."),
      ],
    }),
    ja: articleCopy(guideLabels, "ja", 6, {
      eyebrow: "陣営バランスガイド",
      title: "Aion 2クロスサーバーマッチング：NCが陣営PvPの均衡をどう保つか",
      description: "Gamescomで披露されたクロスサーバーマッチング：陣営とサーバーを組み合わせ、クロスサーバー陣営戦——アビス陣営戦とサーバー選択への意味",
      intro: "陣営制MMOは人口バランスで生き死にします——サーバーが天族90%に傾けば魔族側は面白くありません。GamescomでNCsoftはその答えを説明しました：陣営とサーバーを組み合わせて対戦を均衡させるクロスサーバーマッチングです。",
      sourceNote: "Guided News 9月6日付Gamescom取材報道（PvP・マッチング節）に基づき、AION 2公式サイトの陣営・アビス概念（2026-09-07取得）と照合。",
      keywords: ["Aion 2 クロスサーバーマッチング", "Aion 2 陣営バランスPvP", "Aion 2 レルム戦 サーバー", "Aion 2 アビス陣営戦バランス", "Aion 2 サーバー人口偏り"],
      sections: [
        section("the-imbalance-problem", "古典的90/10問題", "陣営制MMOの定番の失敗：片方がサーバーを支配し、負け陣営のPvPが面白くなくなる。Gamescomの取材で「天族90%・魔族10%になったら？」という質問が直接投げられました。"),
        section("cross-server-matching", "答え：クロスサーバーマッチング", "陣営とサーバーを可能な限り組み合わせ、対戦を均衡させる仕組み。大規模レルム戦もクロスサーバーで進行——固定サーバー構造より合理的な土台と評価されています。"),
        section("how-pvp-is-structured", "PvPの構造", "1v1デュエル、4v4アリーナから、複数サーバーのプレイヤーが会する大規模戦まで。アビスは中心的な陣営PvPエリアとして回帰し、両陣営の道は必ず交わります。"),
        section("what-it-means-for-free-players", "無課金とサーバー選択への意味", "対戦がクロスサーバーなのでホームサーバー少数陣営も自動的に負けません。サーバー選択はコミュニティ・言語・遅延が基準になり、アビスは無課金に無制限です。"),
        section("what-to-watch", "リリース後に見る点", "閑散時間帯の待機が長くなる可能性。リリース前はプレイスタイルで陣営選択、圏域サーバー確認、10月5日後に本ガイドを再確認を。"),
      ],
    }),
    "pt-br": articleCopy(guideLabels, "pt-br", 6, {
      eyebrow: "EQUILÍBRIO DE FACÇÃO",
      title: "Matchmaking entre servidores do Aion 2: como a NC planeja manter o equilíbrio do PvP de facções",
      description: "O matchmaking entre servidores apresentado na Gamescom: combinar facções e servidores, batalhas entre servidores, e o impacto no Abismo e na escolha de servidor",
      intro: "MMOs de facções vivem ou morrem pelo equilíbrio de população — num servidor com 90 % de Elyos, o lado Asmodiano deixa de ser divertido. Na Gamescom, a NCsoft descreveu sua resposta: um matchmaking entre servidores que combina facções e servidores para encontros equilibrados.",
      sourceNote: "Baseado no relato da Guided News de 6 de setembro (PvP e matchmaking), cruzado com o site oficial do AION 2 (7 de setembro de 2026).",
      keywords: ["Aion 2 matchmaking servidores", "Aion 2 equilíbrio facções PvP", "Aion 2 batalha facções servidor", "Aion 2 Abismo equilíbrio", "Aion 2 desequilíbrio população"],
      sections: [
        section("the-imbalance-problem", "O problema 90/10", "Em MMOs de facções, um lado acaba dominando e o PvP perde a graça para o outro; a pergunta do 90 % Elyos / 10 % Asmodiano foi feita diretamente à NC na Gamescom."),
        section("cross-server-matching", "A resposta: matchmaking entre servidores", "Um sistema que combina facções e servidores para encontros equilibrados; grandes batalhas entre servidores não dependem de um só — base mais sólida que estrutura rígida, segundo o relato."),
        section("how-pvp-is-structured", "A estrutura PvP em volta", "Do duelo 1v1 às arenas 4v4 até grandes batalhas entre servidores; o Abismo segue como zona PvP central de facções, com caminhos que convergem inevitavelmente."),
        section("what-it-means-for-free-players", "Para gratuitos e escolha de servidor", "A minoria de facção do seu servidor não está mais condenada; a escolha vira comunidade/idioma/latência, e o acesso ao Abismo segue ilimitado para gratuitos."),
        section("what-to-watch", "O que observar após o lançamento", "Possíveis filas em horários de baixa; antes do lançamento: escolha facção pelo estilo, confirme o servidor da sua região e reveja este guia após 5 de outubro."),
      ],
    }),
    ru: articleCopy(guideLabels, "ru", 6, {
      eyebrow: "БАЛАНС ФРАКЦИЙ",
      title: "Кросс-серверный подбор Aion 2: как NC планирует сохранить баланс фракционного PvP",
      description: "Кросс-серверный подбор, представленный на Gamescom: сочетание фракций и серверов, межсерверные битвы — и что это значит для Бездны и выбора сервера",
      intro: "Фракционные MMO живут и умирают на балансе населения — на сервере с 90 % Элиос стороне Асмодиан становится невесело. На Gamescom NCsoft описала ответ: кросс-серверный подбор, сочетающий фракции и серверы для сбалансированных боёв.",
      sourceNote: "На основе отчёта Guided News от 6 сентября (PvP и подбор), сверено с официальным сайтом AION 2 (7 сентября 2026 г.).",
      keywords: ["Aion 2 кросс-серверный подбор", "Aion 2 баланс фракций PvP", "Aion 2 межсерверные битвы", "Aion 2 Бездна баланс", "Aion 2 дисбаланс населения"],
      sections: [
        section("the-imbalance-problem", "Проблема 90/10", "Во фракционных MMO одна сторона со временем доминирует, и PvP проигравшим становится неинтересен; вопрос «90 % Элиос / 10 % Асмодиан» задали NC прямо на Gamescom."),
        section("cross-server-matching", "Ответ: кросс-серверный подбор", "Система, максимально сочетающая фракции и серверы для равных боёв; большие межсерверные сражения не зависят от одного сервера — более разумная основа, чем жёсткая структура, по мнению отчёта."),
        section("how-pvp-is-structured", "Структура PvP вокруг", "От дуэлей 1x1 и арен 4x4 до крупных межсерверных битв; Бездна остаётся центральной фракционной PvP-зоной, пути сторон неизбежно сходятся."),
        section("what-it-means-for-free-players", "Для бесплатных и выбора сервера", "Меньшинство фракции домашнего сервера больше не обречено; выбор сервера становится вопросом сообщества/языка/пинга, а Бездна остаётся безлимитной для бесплатных."),
        section("what-to-watch", "Что смотреть после запуска", "Возможные очереди в часы низкой активности; до запуска: выбирайте фракцию по стилю, подтвердите сервер региона и перепроверьте гайд после 5 октября."),
      ],
    }),
    ko: articleCopy(guideLabels, "ko", 6, {
      eyebrow: "진영 밸런스 가이드",
      title: "아이온2 크로스 서버 매칭: NC가 진영 PvP 균형을 유지하는 방법",
      description: "Gamescom에서 공개된 크로스 서버 매칭: 진영과 서버를 조합해 대전 균형 유지, 크로스 서버 진영전——아비스 진영전과 서버 선택에 주는 의미",
      intro: "진영제 MMO는 인구 균형으로 흥망이 갈립니다——서버가 천족 90%로 기울면 마족은 재미를 잃습니다. Gamescom에서 NC소프트는 그에 대한 답을 설명했습니다: 진영과 서버를 조합해 대전을 균형 있게 만드는 크로스 서버 매칭 시스템입니다.",
      sourceNote: "Guided News 9월 6일자 Gamescom 미팅 보도(PvP·매칭 절)를 기반으로, AION 2 공식 사이트의 진영·아비스 개념(2026-09-07 확인)과 교차 확인했습니다.",
      keywords: ["아이온2 크로스 서버 매칭", "아이온2 진영 밸런스 PvP", "아이온2 레름전 서버", "아이온2 아비스 진영전", "아이온2 서버 인구 불균형"],
      sections: [
        section("the-imbalance-problem", "고전적 90/10 문제", "진영제 MMORPG의 단골 실패: 한쪽이 서버를 지배하고 패배한 진영의 PvP가 재미를 잃는다. 게임스컴에서 '천족 90%, 마족 10%가 되면?'이란 질문이 NC에 직접 제기됐습니다."),
        section("cross-server-matching", "답: 크로스 서버 매칭", "진영과 서버를 최대한 조합해 대전을 균형 있게 만드는 시스템. 대규모 레름전도 크로스 서버로 진행——고정 서버 구조보다 합리적인 토대라는 평가입니다."),
        section("how-pvp-is-structured", "이를 중심으로 한 PvP 구조", "1대1 듀얼, 4대4 아레나부터 여러 서버의 유저가 만나는 대규모 진영전까지. 아비스가 핵심 진영 PvP 구역으로 돌아오고, 두 진영의 길은 반드시 교차합니다."),
        section("what-it-means-for-free-players", "무과금과 서버 선택의 의미", "대전이 크로스 서버로 이뤄지므로 홈 서버 소수 진영도 자동으로 지지 않습니다. 서버 선택은 커뮤니티·언어·지연이 기준이 되고, 아비스는 무과금에게 무제한입니다."),
        section("what-to-watch", "출시 후 지켜볼 점", "한산한 시간대 대기열이 길어질 수 있습니다. 출시 전에는 플레이 스타일로 진영 선택, 지역 서버 확인, 10월 5일 이후 본 가이드 재확인을 권합니다."),
      ],
    }),
    "zh-hant": articleCopy(guideLabels, "zh-hant", 6, {
      eyebrow: "陣營平衡攻略",
      title: "Aion 2 跨服配對：NC 如何維持陣營 PvP 平衡",
      description: "Gamescom 披露的跨服配對系統：陣營與伺服器組合配對保證對戰均衡、跨服陣營大戰，以及對深淵陣營戰與伺服器選擇的含義",
      intro: "陣營 MMO 的成敗取決於人口平衡——當伺服器漂移到九成天族時，魔族一側就不再好玩。在 Gamescom，NCsoft 描述了它的答案：一套跨服配對系統，將陣營與伺服器配對，讓對戰保持均衡；大型陣營戰也跨服運作，而非侷限於單服。",
      sourceNote: "基於 Guided News 9 月 6 日 Gamescom 約談報導（PvP 與配對細節），並與 AION 2 官網中陣營與深淵概念（2026-09-07 抓取）交叉核對。",
      keywords: ["Aion 2 跨服配對", "Aion 2 陣營平衡 PvP", "Aion 2 跨服陣營戰", "Aion 2 深淵陣營戰平衡", "Aion 2 伺服器人口失衡"],
      sections: [
        section("the-imbalance-problem", "經典的九成一邊倒問題", ["陣營制 MMORPG 有一個常見失敗模式：某一陣營最終嚴重碾壓伺服器，輸方 PvP 失去樂趣。Guided News 在 Gamescom 簡報中直接把這個問題拋給了官方——如果某服變成 90% 天族、10% 魔族會怎樣？", "這個問題對 Aion 2 尤為關鍵：天族 vs 魔族不是裝飾——兩陣營從世界兩端出發，陣營 PvP 的對局決定內容歸屬。"]),
        section("cross-server-matching", "答案：跨服配對", ["NCsoft 描述的方案是跨伺服器配對系統：盡可能組合陣營與伺服器，讓對戰保持均衡。", "具體而言，大型陣營戰同樣跨服運作——系統不必只依賴單服玩家。報導評價這比僵化的伺服器結構更合理，但長期公平仍需驗證。"]),
        section("how-pvp-is-structured", "圍繞它的 PvP 結構", ["PvP 譜系從經典的 1v1 決鬥、4v4 競技場直到多服玩家會師的大型陣營戰。", "深淵作為核心陣營 PvP 區域回歸：天族與魔族從世界兩端出發，道路必然交匯，和平的天空探索很快變成戰爭——這正是配對系統要保證人數公平的戰場。"]),
        section("what-it-means-for-free-players", "對免費玩家與伺服器選擇的意義", ["因為對戰跨服配對，陣營人口數學的懲罰變輕：主服少數陣營不會在跨服戰中自動出局。", "伺服器選擇因此更關乎社群、語言與延遲（見本站伺服器區域指南，NA/SA/EU/JP 四區域），而西區 F2P 模型對免費玩家保持深淵無時限——人人可參戰。"]),
        section("what-to-watch", "上線後觀察什麼", ["觀察配對器在高峰時段的等待表現：跨服平衡在人口稀疏的深夜可能帶來更長佇列。", "上線前你的務實動作：按玩法偏好與社群而非人口猜測選陣營；確認所屬區域的伺服器（如適用考慮台服英文）；10 月 5 日上線、NC 在補丁說明確認配對細節後再回來複核本指南。"]),
      ],
    }),
  },
};