import { articleCopy, localizations, newsLabels, publishedVerified, section } from "./trending-september-2-shared";
import type { ContentEntry, ContentHeroImage, ContentSource } from "./content-registry";

/* ARTICLE 1 — Aion 2 global launch confirmed without an Oceania server; regions NA/SA/EU/JP + KR/TW; TW supports English */

const ocSource1: ContentSource = {
  id: "massivelyop-oceania-2026-09-01",
  kind: "third-party", publisher: "Massively Overpowered",
  label: "Aion 2 confirms that its global launch will not be arriving with an Oceania server",
  url: "https://massivelyop.com/2026/09/01/aion-2-confirms-that-its-global-launch-will-not-be-arriving-with-an-oceania-server/",
  publishedAt: "2026-09-01",
  retrievedAt: "2026-09-02",
  verifiedAt: "2026-09-02",
  localizations: localizations({
    "zh-hans": "Aion 2 确认全球上线不含大洋洲服务器",
    en: "Aion 2 confirms that its global launch will not be arriving with an Oceania server",
    fr: "Aion 2 confirme l'absence de serveur Océanie au lancement mondial",
    de: "Aion 2 bestätigt: kein Ozeanien-Server beim weltweiten Start",
    es: "Aion 2 confirma que su lanzamiento mundial no incluirá un servidor de Oceanía",
    ja: "Aion 2 はグローバル発売でオセアニアサーバーを用意しないと確認",
    "pt-br": "Aion 2 confirma que o lançamento global não terá servidor da Oceania",
    ru: "Aion 2 подтверждает: мирового запуска без сервера в Океании",
    ko: "아이온2 글로벌 출시, 오세아니아 서버 없음 확정",
    "zh-hant": "Aion 2 確認全球上線不含大洋洲伺服器",
  }, "https://massivelyop.com/2026/09/01/aion-2-confirms-that-its-global-launch-will-not-be-arriving-with-an-oceania-server/"),
};

const ocSource2: ContentSource = {
  id: "steam-store-aion2-2026-09-02",
  kind: "platform", publisher: "Steam",
  label: "AION 2 — Steam Store Page (Release 5 Oct 2026; regions)",
  url: "https://store.steampowered.com/app/3393110/AION_2/",
  publishedAt: "2026-08-26",
  retrievedAt: "2026-09-02",
  verifiedAt: "2026-09-02",
  localizations: localizations({
    "zh-hans": "AION 2——Steam 商店页（2026-10-05 发售）",
    en: "AION 2 — Steam Store Page (Release 5 Oct 2026)",
    fr: "AION 2 — Page boutique Steam (sortie le 5 oct. 2026)",
    de: "AION 2 — Steam-Store-Seite (Release 5. Okt. 2026)",
    es: "AION 2 — Página de Steam (lanzamiento 5 oct 2026)",
    ja: "AION 2 — Steam ストアページ（2026-10-05発売）",
    "pt-br": "AION 2 — Página da Steam (lançamento 5 out 2026)",
    ru: "AION 2 — Страница Steam (выход 05.10.2026)",
    ko: "AION 2 — Steam 상점 페이지(2026-10-05 출시)",
    "zh-hant": "AION 2——Steam 商店頁（2026-10-05 發售）",
  }, "https://store.steampowered.com/app/3393110/AION_2/"),
};

const ocHero: ContentHeroImage = {
  src: "https://blogfiles.ncsoft.net/news/af7330da-4ff6-4b58-aece-400e6061a3be.jpg",
  width: 1100, height: 605,
  credit: "NC Corporation",
  sourceUrl: "https://aion2.plaync.com/ja-jp/board/notice/list",
  rights: "linked-official-media",
  translations: {
    "zh-hans": { alt: "Aion 2 服务器区域新闻配图", caption: "NC 官方配图；Aion 2 全球上线服务器为北美、南美、欧洲与日本（韩服/台服维持），不含大洋洲——官方对澳洲玩家建议使用支持英文的台服版本。" },
    en: { alt: "Aion 2 server regions news image", caption: "Official NC artwork; Aion 2's global launch servers are North America, South America, Europe and Japan (Korea/Taiwan continue), with no Oceania server — NCsoft suggests the English-supported Taiwanese version for Australian players." },
    fr: { alt: "Image des régions de serveurs d'Aion 2", caption: "Visuel officiel NC ; serveurs mondiaux d'Aion 2 : Amérique du Nord, du Sud, Europe et Japon (Corée/Taiwan maintenus), sans Océanie — NCsoft suggère la version taïwanaise en anglais aux joueurs australiens." },
    de: { alt: "Bild zu den Serverregionen von Aion 2", caption: "Offizielles NC-Artwork; weltweite Aion-2-Server: Nord-/Südamerika, Europa und Japan (Korea/Taiwan bleiben), ohne Ozeanien — NCsoft empfiehlt australischen Spielern die englische taiwanesische Version." },
    es: { alt: "Imagen de las regiones de servidores de Aion 2", caption: "Arte oficial de NC; servidores mundiales de Aion 2: Norteamérica, Sudamérica, Europa y Japón (Corea/Taiwán continúan), sin Oceanía — NCsoft sugiere a los jugadores australianos la versión taiwanesa en inglés." },
    ja: { alt: "Aion 2 サーバーリージョンニュース画像", caption: "NC公式アートワーク；Aion 2 のグローバルサーバーは北米・南米・欧州・日本（韓国・台湾は継続）で、オセアニアはありません。NCソフトは豪州プレイヤーに英語対応の台湾版を案内しています。" },
    "pt-br": { alt: "Imagem das regiões de servidores do Aion 2", caption: "Arte oficial da NC; servidores globais do Aion 2: América do Norte, do Sul, Europa e Japão (Coreia/Taiwan continuam), sem Oceania — a NCSoft sugere aos jogadores australianos a versão taiwanesa em inglês." },
    ru: { alt: "Изображение регионов серверов Aion 2", caption: "Официальный арт NC; мировые серверы Aion 2: Северная/Южная Америка, Европа и Япония (Корея/Тайвань продолжаются), без Океании — NCsoft предлагает австралийцам тайваньскую версию на английском." },
    ko: { alt: "Aion 2 서버 리전 뉴스 이미지", caption: "NC 공식 이미지입니다. 아이온2 글로벌 출시 서버는 북미·남미·유럽·일본이며(한국·대만 유지) 오세아니아는 없습니다. NC소프트는 호주 플레이어에게 영어 지원 대만 버전을 안내합니다." },
    "zh-hant": { alt: "Aion 2 伺服器區域新聞配圖", caption: "NC 官方配圖；Aion 2 全球上線伺服器為北美、南美、歐洲與日本（韓服/台服維持），不含大洋洲——官方對澳洲玩家建議使用支援英文的台服版本。" },
  },
};

export const trendingSeptember2Article1: ContentEntry = {
  section: "news",
  slug: "aion-2-global-launch-no-oceania-server",
  schemaType: "NewsArticle",
  publishedAt: "2026-09-02",
  updatedAt: "2026-09-02",
  readingMinutes: 5,
  publication: publishedVerified,
  sources: [ocSource1, ocSource2],
  heroImage: ocHero,
  related: [
    { kind: "content", section: "news", slug: "aion-2-release-date-october-5-2026" },
    { kind: "content", section: "guides", slug: "aion-2-language-support-8-languages-guide" },
    { kind: "content", section: "guides", slug: "aion-2-global-version-changes-guide" },
    { kind: "content", section: "news", slug: "aion-2-steam-store-countdown-four-weeks" },
  ],
  translations: {
    en: articleCopy(newsLabels, "en", 5, {
      eyebrow: "SERVER REGIONS",
      title: "Aion 2 Global Launch Has No Oceania Server — NCsoft Suggests Taiwan (English) for AU Players",
      description: "Massively Overpowered confirmed with NCsoft that Aion 2's October 5 global launch will offer North America, South America, Europe, and Japan servers — no Oceania. For Australian and New Zealand players, the studio's answer is that the Taiwanese version supports English.",
      intro: "Players in Australia and New Zealand have been asking where they will play Aion 2's global launch since the October 5 date was announced. On September 1, Massively Overpowered put the question to NCsoft directly, and the answer is now official: the global version launches with North America, South America, Europe, and Japan servers, and there will be no Oceania server. This report lays out the confirmed region list, what it means for ANZ players, and how the Taiwanese version fits in.",
      sourceNote: "Based on Massively Overpowered's September 1 report (direct studio confirmation via press email), cross-checked with the Aion 2 Steam store page (retrieved September 2, 2026) for the release-date and region framing.",
      keywords: ["Aion 2 Oceania server", "Aion 2 Australia server", "Aion 2 server regions", "Aion 2 Taiwan English", "Aion 2 ANZ players"],
      sections: [
        section("confirmed-regions", "The Confirmed Region List", ["The studio reaffirmed that the global version will support servers in North America, South America, Europe, and Japan, and that it will continue to support builds in Korea and Taiwan as one would expect, per Massively Overpowered's September 1 report.", "Notably absent: Oceania — Australia, New Zealand, and the surrounding regions get no dedicated server at the October 5 launch.", "The release remains October 5, 2026, matching the Steam store page listing and the Gamescom confirmations; region structure is the news here, not the date."]),
        section("the-answer-for-anz", "What NCsoft Told ANZ Players", ["Massively Overpowered asked specifically about Australian players, and the studio's reply, quoted directly: “The Taiwanese version supports English.”", "That is the official workaround: ANZ players can use the Taiwanese service, which carries English-language support, rather than a dedicated local server.", "The report itself adds a candid note: “Here's hoping that it's not too laggy when the MMORPG launches October 5th” — acknowledging that playing on Taiwan from Australia is a compromise on latency, not a clean local option."]),
        section("why-it-matters", "Why This Matters", ["Latency decides a lot in Aion 2's large-scale PvP and rift content. Without an Oceania node, ANZ players will route to either Taiwan or (in some cases) North America, with the physical distance showing up in combat responsiveness.", "For a game whose flagship content is open-world faction warfare (see the September 2 Spacetime Rift Domination update), server proximity is a real gameplay factor, not just a login preference.", "It also means players in the region should weigh the trade-off between the English-language Taiwanese build and a higher-latency English server — a choice this site's region/guide content can help navigate."]),
        section("what-it-does-not-change", "What It Does Not Change", ["The global release date (October 5), the free-to-play model, and the four-region server plan for the Western launch are all unchanged.", "The Taiwanese service is a separate build with its own update cadence; using it for the global launch is a practical suggestion from NCsoft, not a merge of the two services.", "Language support for the global build is unaffected: the eight-language list from our language-support guide stands, and the Taiwan-English path is an additional option for ANZ players specifically."]),
        section("takeaway", "The Takeaway", ["Aion 2's October 5 launch has no Oceania server; the confirmed regions are North America, South America, Europe, and Japan, with Korea and Taiwan continuing separately.", "For Australian and New Zealand players, NCsoft's official suggestion is the Taiwanese version, which supports English — with the caveat that latency will be a factor.", "If you are in the region, your decision is between an English global server with higher ping and the English-capable Taiwanese build — and checking the actual ping from your connection before launch is the practical next step."]),
      ],
    }),
    "zh-hans": articleCopy(newsLabels, "zh-hans", 5, {
      eyebrow: "服务器区域",
      title: "Aion 2 全球上线不含大洋洲服务器——官方建议澳洲玩家使用支持英文的台服",
      description: "Massively Overpowered 向 NCsoft 直接确认：Aion 2 10 月 5 日全球上线提供北美、南美、欧洲与日本服务器，无大洋洲。对澳洲与新西兰玩家，官方回答是「台服支持英文」。",
      intro: "自 10 月 5 日全球上线日期公布以来，澳洲与新西兰玩家一直在问自己该去哪里玩。9 月 1 日，Massively Overpowered 直接向 NCsoft 求证，答案现已官方化：全球版将提供北美、南美、欧洲与日本服务器，且不会有 Oceania 服务器。本报告列出已确认的区域名单、对澳新玩家的意义，以及台服如何介入。",
      sourceNote: "基于 Massively Overpowered 9 月 1 日报道（经新闻邮件直接获得官方确认），并与 Aion 2 Steam 商店页（2026-09-02 抓取）的发售日期与区域表述交叉核对。",
      keywords: ["Aion 2 大洋洲服务器", "Aion 2 澳洲服务器", "Aion 2 服务器区域", "Aion 2 台服英文", "Aion 2 澳新玩家"],
      sections: [
        section("confirmed-regions", "已确认的区域名单", ["Massively Overpowered 9 月 1 日报道：官方重申全球版将支持北美、南美、欧洲与日本服务器，且按预期维持韩国与台湾版本。", "显著缺席：Oceania——澳洲、新西兰及周边地区在 10 月 5 日上线时没有专属服务器。", "发售日仍为 2026 年 10 月 5 日，与 Steam 商店页及 Gamescom 确认一致；本新闻点是区域结构而非日期。"]),
        section("the-answer-for-anz", "官方对澳新玩家的回答", ["Massively Overpowered 专门询问了澳洲玩家，官方直接引述：「台服支持英文。」", "这是官方变通方案：澳新玩家可使用台湾服务，它带英文支持，而非专属本地服务器。", "报道附了一句直白的提醒：「希望 10 月 5 日 MMORPG 上线时不会太卡」——承认从澳洲连台湾是延迟上的妥协，而非干净的本地选项。"]),
        section("why-it-matters", "为什么重要", ["延迟在 Aion 2 的大型 PvP 与裂隙内容中决定很多。没有 Oceania 节点，澳新玩家将路由到台湾或（部分情况下）北美，物理距离会显现在战斗响应上。", "对一款旗舰内容是开放世界阵营战争（见 9/2 时空裂隙·统治战更新）的游戏，服务器距离是真实的玩法因素，不只是登录偏好。", "这也意味着该地区玩家需权衡英文台服与更高延迟的英文全球服——本站区域/攻略内容可帮助抉择。"]),
        section("what-it-does-not-change", "不变的内容", ["全球发售日期（10 月 5 日）、免费游玩模式与西方四区域服务器计划均不变。", "台服是独立版本，有自身的更新节奏；将其用于全球上线是 NCsoft 的实用建议，不是两个服务的合并。", "全球版语言支持不受影响：语言支持指南中的 8 语言名单依旧，台服英文路径是特别面向澳新玩家的额外选项。"]),
        section("takeaway", "结论", ["Aion 2 的 10 月 5 日上线没有大洋洲服务器；已确认区域为北美、南美、欧洲与日本，韩国与台湾分开维持。", "对澳洲与新西兰玩家，官方建议是支持英文的台服——但需注意延迟因素。", "若你在该地区，你的选择是在更高延迟的英文全球服与可英文的台服之间权衡；上线前实测你的连接延迟是务实的下一步。"]),
      ],
    }),
    ko: articleCopy(newsLabels, "ko", 5, {
      eyebrow: "서버 리전",
      title: "아이온2 글로벌 출시, 오세아니아 서버 없음 — 호주 플레이어에게는 영어 지원 대만 버전 안내",
      description: "Massively Overpowered가 NC소프트에 직접 확인: 아이온2의 10월 5일 글로벌 출시 서버는 북미·남미·유럽·일본이며 오세아니아는 없습니다. 호주·뉴질랜드 플레이어에게는 '대만 버전이 영어를 지원한다'가 공식 답변입니다.",
      intro: "10월 5일 글로벌 출시일 발표 이후 호주·뉴질랜드 플레이어는 어디서 플레이할지 물어왔습니다. 9월 1일 Massively Overpowered가 NC소프트에 직접 물었고, 답은 공식화됐습니다. 본 기사는 확정된 리전 목록과 호주 플레이어의 선택지를 정리합니다.",
      sourceNote: "Massively Overpowered의 9월 1일 보도(공식 확인)와 Aion 2 Steam 상점 페이지(2026-09-02)를 교차 확인했습니다.",
      keywords: ["아이온2 오세아니아 서버", "아이온2 호주 서버", "아이온2 서버 리전", "아이온2 대만 영어", "아이온2 호주 플레이어"],
      sections: [
        section("confirmed-regions", "확정된 리전 목록", "9월 1일 보도에 따르면 글로벌 버전은 북미·남미·유럽·일본 서버를 지원하고 한국·대만 빌드는 유지됩니다. 오세아니아는 10월 5일 출시에 없습니다. 출시일은 10월 5일 그대로이며, 이번 뉴스는 지역 구조입니다."),
        section("the-answer-for-anz", "공식 답변", "NC소프트는 '대만 버전이 영어를 지원한다'고 답했습니다. 호주 플레이어에게는 전용 서버 대신 영어 지원 대만 서비스를 제안하는 구조입니다. 보도는 '10월 5일 출시 때 너무 렉이 없길'이라는 솔직한 평가도 붙였습니다."),
        section("why-it-matters", "왜 중요한가", "아이온2의 대규모 PvP·균열 콘텐츠에서 레이턴시는 많은 것을 좌우합니다. 오세아니아 노드가 없으면 호주 플레이어는 대만이나 북미로 경로가 잡히고, 전투 반응에 물리적 거리가 나타납니다. '오픈월드 진영전'이 주력 콘텐츠인 게임에서 서버 거리는 실제 플레이 요소입니다."),
        section("what-it-does-not-change", "바뀌지 않는 것", "출시일(10월 5일)·무료 플레이·서부 4리전 계획은 그대로입니다. 대만 서비스는 별도 빌드이며, 언어 지원도 8개 언어 목록이 유지됩니다."),
        section("takeaway", "결론", "오세아니아 서버 없음이 공식입니다. 호주·뉴질랜드 플레이어는 영어 지원 대만 버전이 공식 제안이며, 출시 전 실제 핑을 측정해 보는 것이 실무적 다음 단계입니다."),
      ],
    }),
    ja: articleCopy(newsLabels, "ja", 5, {
      eyebrow: "サーバーリージョン",
      title: "Aion 2 グローバル発売はオセアニアサーバーなし — 豪州向けに英語対応の台湾版を案内",
      description: "Massively OverpoweredがNCソフトに直接確認：Aion 2 の10月5日グローバル発売サーバーは北米・南米・欧州・日本で、オセアニアはありません。豪州・NZプレイヤーには「台湾版が英語対応」が公式回答です。",
      intro: "10月5日のグローバル発売日発表以来、豪州・NZプレイヤーはどこで遊べるのか問うてきました。9月1日、Massively OverpoweredがNCソフトに直接確認し、答えが公式化しました。本記事は確定リージョンと選択肢を整理します。",
      sourceNote: "Massively Overpoweredの9月1日報道（公式確認）とAion 2 Steamストアページ（2026-09-02）を照合しました。",
      keywords: ["Aion 2 オセアニアサーバー", "Aion 2 豪州サーバー", "Aion 2 サーバーリージョン", "Aion 2 台湾英語", "Aion 2 豪州プレイヤー"],
      sections: [
        section("confirmed-regions", "確定リージョン一覧", "9月1日報道によれば、グローバル版は北米・南米・欧州・日本のサーバーをサポートし、韓国・台湾ビルドは維持されます。オセアニアは10月5日の発売にありません。発売日は10月5日のままです。"),
        section("the-answer-for-anz", "公式回答", "NCソフトは「台湾版が英語に対応している」と回答しました。豪州プレイヤーには専用サーバーではなく英語対応の台湾サービスを提案する形です。報道は「発売時にあまりラグがないことを願う」と率直に付け加えました。"),
        section("why-it-matters", "なぜ重要か", "Aion 2 の大規模PvP・亀裂コンテンツではレイテンシが多くを決めます。オセアニアノードが無いと豪州からは台湾か北米へ経路が取られ、戦闘反応に物理的距離が表れます。オープンワールド陣営戦が主役のゲームで、サーバー距離は実際のプレイ要素です。"),
        section("what-it-does-not-change", "変わらないもの", "発売日（10月5日）・基本無料・西部4リージョン計画はそのままです。台湾サービスは別ビルドで、言語対応も8言語リストが維持されます。"),
        section("takeaway", "結論", "オセアニアサーバーなしが公式です。豪州・NZプレイヤーには英語対応の台湾版が公式提案であり、発売前に実際のpingを測ることが実務的な次の一手です。"),
      ],
    }),
    fr: articleCopy(newsLabels, "fr", 5, {
      eyebrow: "RÉGIONS DE SERVEURS",
      title: "Aion 2 : pas de serveur Océanie au lancement mondial — NCsoft propose Taiwan (anglais) aux joueurs australiens",
      description: "Massively Overpowered a confirmé auprès de NCsoft : le lancement mondial d'Aion 2 le 5 octobre offrira des serveurs Amérique du Nord, Amérique du Sud, Europe et Japon — sans Océanie. Pour l'Australie et la NZ, la réponse est « la version taïwanaise supporte l'anglais ».",
      intro: "Depuis l'annonce du 5 octobre, les joueurs australiens et néo-zélandais demandaient où jouer. Le 1er septembre, Massively Overpowered a posé la question à NCsoft et la réponse est officielle : pas de serveur Océanie, quatre régions pour l'Ouest plus Corée/Taiwan maintenus.",
      sourceNote: "Basé sur le rapport de Massively Overpowered du 1er septembre (confirmation studio), recoupé avec la page Steam d'Aion 2 (2 septembre 2026).",
      keywords: ["Aion 2 serveur Océanie", "Aion 2 Australie serveur", "Aion 2 régions serveurs", "Aion 2 Taiwan anglais", "Aion 2 joueurs ANZ"],
      sections: [
        section("confirmed-regions", "Les régions confirmées", "Serveurs mondiaux : Amérique du Nord, du Sud, Europe et Japon ; Corée et Taiwan maintenus. Absent : Océanie. Date inchangée au 5 octobre 2026 — la structure des régions est la nouvelle, pas la date."),
        section("the-answer-for-anz", "La réponse aux joueurs ANZ", "Citation directe : « La version taïwanaise supporte l'anglais. » C'est la solution officielle : utiliser le service taïwanais en anglais. Massively OP ajoute l'honnête « espérons que ce ne soit pas trop laggy »."),
        section("why-it-matters", "Pourquoi c'est important", "La latence compte dans le PvP et les failles d'Aion 2. Sans nœud Océanie, l'ANZ route vers Taiwan ou l'Amérique du Nord — la distance se voit en combat. Pour un jeu dont le contenu phare est la guerre de factions, c'est un vrai facteur de jeu."),
        section("what-it-does-not-change", "Ce qui ne change pas", "Date (5 octobre), free-to-play et plan 4 régions de l'Ouest inchangés ; Taiwan reste une build séparée ; les 8 langues globales restent."),
        section("takeaway", "Conclusion", "Pas de serveur Océanie au 5 octobre. Pour l'ANZ, Taiwan en anglais est la suggestion officielle ; mesurez le ping réel avant le lancement."),
      ],
    }),
    de: articleCopy(newsLabels, "de", 5, {
      eyebrow: "SERVERREGIONEN",
      title: "Aion 2: Kein Ozeanien-Server beim Weltstart — NCsoft empfiehlt Taiwan (Englisch) für AU-Spieler",
      description: "Massively Overpowered hat bei NCsoft bestätigt: Der globale Start von Aion 2 am 5. Oktober bietet Server in Nord-/Südamerika, Europa und Japan — ohne Ozeanien. Für Australien/NZ lautet die Antwort „die taiwanesische Version unterstützt Englisch“.",
      intro: "Seit dem 5.-Oktober-Datum fragen Spieler in Australien und Neuseeland, wo sie spielen sollen. Am 1. September hat Massively Overpowered direkt bei NCsoft nachgefragt — Antwort: kein Ozeanien-Server, vier Regionen im Westen plus Korea/Taiwan weiterhin.",
      sourceNote: "Basierend auf dem Massively-Overpowered-Bericht vom 1. September (Studio-Bestätigung), abgeglichen mit der Aion-2-Steampage (2. September 2026).",
      keywords: ["Aion 2 Ozeanien-Server", "Aion 2 Australien-Server", "Aion 2 Serverregionen", "Aion 2 Taiwan Englisch", "Aion 2 ANZ-Spieler"],
      sections: [
        section("confirmed-regions", "Die bestätigten Regionen", "Weltweite Server: Nord-/Südamerika, Europa, Japan; Korea und Taiwan bleiben. Fehlt: Ozeanien. Datum unverändert 5. Oktober 2026 — die Regionenstruktur ist die Nachricht."),
        section("the-answer-for-anz", "Die Antwort für ANZ", "Direktzitat: „Die taiwanesische Version unterstützt Englisch.“ Das ist die offizielle Lösung: den taiwanesischen Dienst auf Englisch nutzen. Massively OP ergänzt ehrlich: „hoffen wir, dass es nicht zu sehr laggt“."),
        section("why-it-matters", "Warum es wichtig ist", "Latenz entscheidet in Aion 2s PvP und Rift-Inhalten. Ohne Ozeanien-Knoten routet ANZ nach Taiwan oder Nordamerika — die Distanz zeigt sich im Kampf. Bei einem Spiel mit Open-World-Fraktionen-Krieg ist die Servernähe ein echter Spielfaktor."),
        section("what-it-does-not-change", "Was sich nicht ändert", "Datum (5. Oktober), Free-to-play und 4-Regionen-Plan des Westens bleiben; Taiwan bleibt eine eigene Build; die 8 globalen Sprachen bleiben."),
        section("takeaway", "Fazit", "Kein Ozeanien-Server zum 5. Oktober. Für ANZ ist Taiwan auf Englisch der offizielle Vorschlag; messt vor dem Start den echten Ping."),
      ],
    }),
    es: articleCopy(newsLabels, "es", 5, {
      eyebrow: "REGIONES DE SERVIDORES",
      title: "Aion 2: sin servidor de Oceanía en el lanzamiento mundial — NCsoft sugiere Taiwán (inglés) a los jugadores de AU",
      description: "Massively Overpowered confirmó con NCsoft: el lanzamiento mundial de Aion 2 el 5 de octubre tendrá servidores en Norteamérica, Sudamérica, Europa y Japón — sin Oceanía. Para Australia y NZ, la respuesta es «la versión taiwanesa soporta inglés».",
      intro: "Desde el anuncio del 5 de octubre, los jugadores de Australia y Nueva Zelanda preguntaban dónde jugar. El 1 de septiembre, Massively Overpowered preguntó a NCsoft y la respuesta es oficial: sin servidor de Oceanía, cuatro regiones en Occidente más Corea/Taiwán.",
      sourceNote: "Basado en el informe de Massively Overpowered del 1 de septiembre (confirmación del estudio), cotejado con la página de Steam de Aion 2 (2 de septiembre de 2026).",
      keywords: ["Aion 2 servidor Oceanía", "Aion 2 Australia servidor", "Aion 2 regiones servidores", "Aion 2 Taiwán inglés", "Aion 2 jugadores ANZ"],
      sections: [
        section("confirmed-regions", "Las regiones confirmadas", "Servidores mundiales: Norteamérica, Sudamérica, Europa y Japón; Corea y Taiwán continúan. Ausente: Oceanía. Fecha sin cambios: 5 de octubre de 2026 — la estructura de regiones es la noticia."),
        section("the-answer-for-anz", "La respuesta a los jugadores ANZ", "Cita directa: «La versión taiwanesa soporta inglés». Esa es la solución oficial: usar el servicio taiwanés en inglés. Massively OP añade el honesto «esperemos que no sea demasiado laggy»."),
        section("why-it-matters", "Por qué importa", "La latencia decide en el PvP y las fisuras de Aion 2. Sin nodo de Oceanía, ANZ enruta a Taiwán o Norteamérica — la distancia se nota en combate. Para un juego cuyo contenido estrella es la guerra de facciones, es un factor real."),
        section("what-it-does-not-change", "Lo que no cambia", "Fecha (5 de octubre), free-to-play y plan de 4 regiones en Occidente; Taiwán sigue siendo una build aparte; los 8 idiomas globales siguen."),
        section("takeaway", "Conclusión", "Sin servidor de Oceanía el 5 de octubre. Para ANZ, Taiwán en inglés es la sugerencia oficial; mide el ping real antes del lanzamiento."),
      ],
    }),
    "pt-br": articleCopy(newsLabels, "pt-br", 5, {
      eyebrow: "REGIÕES DE SERVIDORES",
      title: "Aion 2: sem servidor da Oceania no lançamento global — NCSoft sugere Taiwan (inglês) para jogadores da AU",
      description: "A Massively Overpowered confirmou com a NCSoft: o lançamento global do Aion 2 em 5 de outubro terá servidores na América do Norte, do Sul, Europa e Japão — sem Oceania. Para Austrália e NZ, a resposta é «a versão taiwanesa suporta inglês».",
      intro: "Desde o anúncio de 5 de outubro, jogadores da Austrália e Nova Zelândia perguntavam onde jogar. Em 1º de setembro, a Massively Overpowered perguntou à NCSoft e a resposta é oficial: sem servidor da Oceania, quatro regiões no Ocidente mais Coreia/Taiwan.",
      sourceNote: "Com base no relato da Massively Overpowered de 1º de setembro (confirmação do estúdio), cruzado com a página da Steam do Aion 2 (2 de setembro de 2026).",
      keywords: ["Aion 2 servidor Oceania", "Aion 2 Austrália servidor", "Aion 2 regiões de servidores", "Aion 2 Taiwan inglês", "Aion 2 jogadores ANZ"],
      sections: [
        section("confirmed-regions", "As regiões confirmadas", "Servidores mundiais: América do Norte, do Sul, Europa e Japão; Coreia e Taiwan continuam. Ausente: Oceania. Data sem mudanças: 5 de outubro de 2026 — a estrutura de regiões é a notícia."),
        section("the-answer-for-anz", "A resposta aos jogadores ANZ", "Citação direta: «A versão taiwanesa suporta inglês». Essa é a solução oficial: usar o serviço taiwanês em inglês. A Massively OP acrescenta o honesto «esperamos que não seja muito laggy»."),
        section("why-it-matters", "Por que importa", "A latência decide no PvP e nas fendas do Aion 2. Sem nó da Oceania, a ANZ roteia para Taiwan ou América do Norte — a distância aparece em combate. Para um jogo cujo carro-chefe é a guerra de facções, é um fator real."),
        section("what-it-does-not-change", "O que não muda", "Data (5 de outubro), free-to-play e plano de 4 regiões no Ocidente; Taiwan segue como build separada; os 8 idiomas globais seguem."),
        section("takeaway", "Conclusão", "Sem servidor da Oceania em 5 de outubro. Para ANZ, Taiwan em inglês é a sugestão oficial; meça o ping real antes do lançamento."),
      ],
    }),
    ru: articleCopy(newsLabels, "ru", 5, {
      eyebrow: "РЕГИОНЫ СЕРВЕРОВ",
      title: "Aion 2: без океанийского сервера на мировом запуске — NCsoft предлагает Тайвань (англ.) игрокам из Австралии",
      description: "Massively Overpowered подтвердила у NCsoft: мировой запуск Aion 2 5 октября предложит серверы в Северной/Южной Америке, Европе и Японии — без Океании. Для Австралии и NZ ответ: «тайваньская версия поддерживает английский».",
      intro: "С анонса 5 октября игроки Австралии и Новой Зеландии спрашивали, где играть. 1 сентября Massively Overpowered задала вопрос NCsoft, и ответ официальный: без океанийского сервера, четыре региона на Западе плюс Корея/Тайвань.",
      sourceNote: "На основе отчёта Massively Overpowered от 1 сентября (подтверждение студии), сверено со страницей Steam Aion 2 (2 сентября 2026).",
      keywords: ["Aion 2 сервер Океании", "Aion 2 Австралия сервер", "Aion 2 регионы серверов", "Aion 2 Тайвань английский", "Aion 2 игроки ANZ"],
      sections: [
        section("confirmed-regions", "Подтверждённые регионы", "Мировые серверы: Северная/Южная Америка, Европа и Япония; Корея и Тайвань продолжаются. Отсутствует: Океания. Дата без изменений — 5 октября 2026; структура регионов и есть новость."),
        section("the-answer-for-anz", "Ответ игрокам ANZ", "Прямая цитата: «Тайваньская версия поддерживает английский». Это официальное решение: использовать тайваньский сервис на английском. Massively OP добавляет честное «надеемся, не будет слишком лагать»."),
        section("why-it-matters", "Почему это важно", "Латентность решает в PvP и разломах Aion 2. Без океанийского узла ANZ идёт через Тайвань или Северную Америку — расстояние видно в бою. Для игры с открытым миром и войной фракций это реальный игровой фактор."),
        section("what-it-does-not-change", "Что не меняется", "Дата (5 октября), free-to-play и план 4 регионов на Западе; Тайвань остаётся отдельной сборкой; 8 глобальных языков сохраняются."),
        section("takeaway", "Вывод", "Без океанийского сервера к 5 октября. Для ANZ официальное предложение — Тайвань на английском; замерьте реальный пинг до запуска."),
      ],
    }),
    "zh-hant": articleCopy(newsLabels, "zh-hant", 5, {
      eyebrow: "伺服器區域",
      title: "Aion 2 全球上線不含大洋洲伺服器——官方建議澳洲玩家使用支援英文的台服",
      description: "Massively Overpowered 向 NCsoft 直接確認：Aion 2 10 月 5 日全球上線提供北美、南美、歐洲與日本伺服器，無大洋洲。對澳洲與紐西蘭玩家，官方回答是「台服支援英文」。",
      intro: "自 10 月 5 日全球上線日期公布以來，澳洲與紐西蘭玩家一直在問自己該去哪裡玩。9 月 1 日，Massively Overpowered 直接向 NCsoft 求證，答案現已官方化。本報告列出已確認的區域名單、對澳新玩家的意義，以及台服如何介入。",
      sourceNote: "基於 Massively Overpowered 9 月 1 日報導（經新聞郵件直接獲得官方確認），並與 Aion 2 Steam 商店頁（2026-09-02 抓取）交叉核對。",
      keywords: ["Aion 2 大洋洲伺服器", "Aion 2 澳洲伺服器", "Aion 2 伺服器區域", "Aion 2 台服英文", "Aion 2 澳新玩家"],
      sections: [
        section("confirmed-regions", "已確認的區域名單", ["Massively Overpowered 9 月 1 日報導：官方重申全球版將支援北美、南美、歐洲與日本伺服器，且按預期維持韓國與台灣版本。顯著缺席：大洋洲。發售日仍為 2026 年 10 月 5 日，本新聞點是區域結構而非日期。"]),
        section("the-answer-for-anz", "官方對澳新玩家的回答", ["Massively Overpowered 專門詢問了澳洲玩家，官方直接引述：「台服支援英文。」這是官方變通方案：澳新玩家可使用台灣服務，它帶英文支援，而非專屬本地伺服器。報導附了一句直白的提醒：「希望 10 月 5 日上線時不會太卡」。"]),
        section("why-it-matters", "為什麼重要", ["延遲在 Aion 2 的大型 PvP 與裂隙內容中決定很多。沒有大洋洲節點，澳新玩家將路由到台灣或北美，物理距離會顯現在戰鬥響應上。對旗艦內容是開放世界陣營戰爭的遊戲，伺服器距離是真實的玩法因素。"]),
        section("what-it-does-not-change", "不變的內容", ["全球發售日期（10 月 5 日）、免費遊玩模式與西方四區域伺服器計畫均不變。台服是獨立版本；全球版語言支援不受影響。"]),
        section("takeaway", "結論", ["Aion 2 的 10 月 5 日上線沒有大洋洲伺服器。對澳洲與紐西蘭玩家，官方建議是支援英文的台服——但需注意延遲因素；上線前實測你的連線延遲是務實的下一步。"]),
      ],
    }),
  },
};