import { articleCopy, localizations, newsLabels, publishedVerified, section } from "./trending-september-1-shared";
import type { ContentEntry, ContentHeroImage, ContentSource } from "./content-registry";

/* ARTICLE 1 — Steam store now shows the Aion 2 launch countdown at approximately 4 weeks (verified Sep 1) */

const cwSource1: ContentSource = {
  id: "steam-store-aion2-countdown-2026-09-01",
  kind: "platform", publisher: "Steam",
  label: "AION 2 — Steam Store Page (countdown, advance access, sale event)",
  url: "https://store.steampowered.com/app/3393110/AION_2/",
  publishedAt: "2026-08-26",
  retrievedAt: "2026-09-01",
  verifiedAt: "2026-09-01",
  localizations: localizations({
    "zh-hans": "AION 2——Steam 商店页（倒计时、抢先体验、促销活动）",
    en: "AION 2 — Steam Store Page (countdown, advance access, sale event)",
    fr: "AION 2 — Page boutique Steam (compte à rebours, accès anticipé, événement solde)",
    de: "AION 2 — Steam-Store-Seite (Countdown, Vorabzugang, Sale-Event)",
    es: "AION 2 — Página de la tienda de Steam (cuenta atrás, acceso anticipado, evento de ofertas)",
    ja: "AION 2 — Steam ストアページ（カウントダウン・先行体験・セール）",
    "pt-br": "AION 2 — Página da loja Steam (contagem regressiva, acesso antecipado, evento de ofertas)",
    ru: "AION 2 — Страница Steam (обратный отсчёт, ранний доступ, событие распродажи)",
    ko: "AION 2 — Steam 상점 페이지(카운트다운·얼리 액세스·세일 이벤트)",
    "zh-hant": "AION 2——Steam 商店頁（倒數、搶先體驗、促銷活動）",
  }, "https://store.steampowered.com/app/3393110/AION_2/"),
};

const cwSource2: ContentSource = {
  id: "nichegamer-delay-october-2026-08-28",
  kind: "third-party", publisher: "Niche Gamer",
  label: "Aion 2 global launch delayed to October",
  url: "https://nichegamer.com/aion-2-global-launch-delayed-to-october/",
  publishedAt: "2026-08-28",
  retrievedAt: "2026-09-01",
  verifiedAt: "2026-09-01",
  localizations: localizations({
    "zh-hans": "Aion 2 全球上市延迟至 10 月",
    en: "Aion 2 global launch delayed to October",
    fr: "Le lancement mondial d'Aion 2 repoussé à octobre",
    de: "Aion-2-Weltstart auf Oktober verschoben",
    es: "El lanzamiento mundial de Aion 2 se retrasa a octubre",
    ja: "Aion 2 のグローバル発売が10月に延期",
    "pt-br": "Lançamento global do Aion 2 adiado para outubro",
    ru: "Мировой запуск Aion 2 перенесён на октябрь",
    ko: "아이온2 글로벌 출시 10월로 연기",
    "zh-hant": "Aion 2 全球上市延遲至 10 月",
  }, "https://nichegamer.com/aion-2-global-launch-delayed-to-october/"),
};

const cwHero: ContentHeroImage = {
  src: "https://blogfiles.ncsoft.net/news/af7330da-4ff6-4b58-aece-400e6061a3be.jpg",
  width: 1100, height: 605,
  credit: "NC Corporation",
  sourceUrl: "https://aion2.plaync.com/ja-jp/board/notice/list",
  rights: "linked-official-media",
  translations: {
    "zh-hans": { alt: "Aion 2 上线倒计时新闻配图", caption: "NC 官方配图；截至 2026-09-01，Steam 商店页将 Aion 2 的上线倒计时显示为约 4 周（正式发售 10/5，抢先体验 9/30）。" },
    en: { alt: "Aion 2 launch countdown news image", caption: "Official NC artwork; as of September 1, 2026 the Steam store page shows Aion 2 unlocking in approximately 4 weeks (October 5 launch, September 30 advance access)." },
    fr: { alt: "Image du compte à rebours de lancement d'Aion 2", caption: "Visuel officiel NC ; au 1er septembre 2026, la page Steam indique un déverrouillage dans environ 4 semaines (lancement le 5 octobre, accès anticipé le 30 septembre)." },
    de: { alt: "Bild zum Aion-2-Start-Countdown", caption: "Offizielles NC-Artwork; Stand 1. September 2026 zeigt die Steampage eine Freischaltung in etwa 4 Wochen (Start 5. Oktober, Vorabzugang 30. September)." },
    es: { alt: "Imagen de la cuenta atrás de lanzamiento de Aion 2", caption: "Arte oficial de NC; al 1 de septiembre de 2026, la página de Steam muestra el desbloqueo en aproximadamente 4 semanas (lanzamiento el 5 de octubre, acceso anticipado el 30 de septiembre)." },
    ja: { alt: "Aion 2 発売カウントダウンニュース画像", caption: "NC公式アートワーク；2026年9月1日時点でSteamストアページは約4週間後の解放と表示しています（正式リリース10月5日、先行体験9月30日）。" },
    "pt-br": { alt: "Imagem da contagem regressiva de lançamento do Aion 2", caption: "Arte oficial da NC; em 1º de setembro de 2026, a página da Steam mostra o desbloqueio em aproximadamente 4 semanas (lançamento em 5 de outubro, acesso antecipado em 30 de setembro)." },
    ru: { alt: "Изображение обратного отсчёта запуска Aion 2", caption: "Официальный арт NC; на 1 сентября 2026 страница Steam показывает разблокировку примерно через 4 недели (запуск 5 октября, ранний доступ 30 сентября)." },
    ko: { alt: "Aion 2 출시 카운트다운 뉴스 이미지", caption: "NC 공식 이미지입니다. 2026년 9월 1일 기준 Steam 상점 페이지는 약 4주 후 해제로 표시합니다(정식 출시 10월 5일, 얼리 액세스 9월 30일)." },
    "zh-hant": { alt: "Aion 2 上線倒數新聞配圖", caption: "NC 官方配圖；截至 2026-09-01，Steam 商店頁將 Aion 2 的上線倒數顯示為約 4 週（正式發售 10/5，搶先體驗 9/30）。" },
  },
};

export const trendingSeptember1Article1: ContentEntry = {
  section: "news",
  slug: "aion-2-steam-store-countdown-four-weeks",
  schemaType: "NewsArticle",
  publishedAt: "2026-09-01",
  updatedAt: "2026-09-01",
  readingMinutes: 5,
  publication: publishedVerified,
  sources: [cwSource1, cwSource2],
  heroImage: cwHero,
  related: [
    { kind: "content", section: "news", slug: "aion-2-release-date-october-5-2026" },
    { kind: "content", section: "news", slug: "aion-2-launch-scale-test-september-17-18" },
    { kind: "content", section: "guides", slug: "aion-2-prelaunch-access-routes-guide" },
    { kind: "content", section: "news", slug: "aion-2-genai-asset-disclosure-steam" },
  ],
  translations: {
    en: articleCopy(newsLabels, "en", 5, {
      eyebrow: "LAUNCH COUNTDOWN: 4 WEEKS",
      title: "Aion 2 Launch Countdown: Steam Store Now Shows About 4 Weeks to October 5",
      description: "As of September 1, 2026, the Aion 2 Steam store page shows the game unlocking in approximately 4 weeks, with advance access (September 30) starting in about the same window. This is the store's live countdown for the free-to-play launch on October 5, verified today.",
      intro: "The Aion 2 Steam store page is now counting down in earnest: it shows the game unlocking in approximately 4 weeks, with the Founder's Pack advance access — September 30, five days before launch — starting in approximately 4 weeks as well. We verified the page today (September 1, 2026) so the numbers here are the live store state, not speculation. This report walks through the countdown, what it does and does not confirm, and the milestones between today and October 5.",
      sourceNote: "Based on a live fetch of the Aion 2 Steam store page on September 1, 2026, cross-checked with Niche Gamer's August 28 report on the September 30-to-October 5 launch window.",
      keywords: ["Aion 2 countdown", "Aion 2 4 weeks", "Aion 2 October 5", "Aion 2 advance access September 30", "Aion 2 Steam store"],
      sections: [
        section("the-countdown", "The Store's Live Countdown", ["The Steam store page currently reads “This game plans to unlock in approximately 4 weeks”, with the full release listing as “Release Date: 5 Oct, 2026” and the store panel repeating “Coming 5 Oct, 2026”. Both the countdown and the fixed date agree.", "The pre-purchase blurb adds the same window for early access: pre-purchase to “play the game starting 5 days ahead of full release. Starts in approximately 4 weeks”. That matches advance access beginning September 30 by the 5-day head start.", "None of these texts state a precise unlock hour. Steam rounds to approximate weeks, so treat September 30 and October 5 as the date anchors and expect a precise time to come from NCsoft later."]),
        section("what-it-confirms", "What the Countdown Confirms", ["It confirms the dates announced at Gamescom 2026: launch on October 5, 2026, with Founder's Pack advance access from September 30 to October 4. Niche Gamer's August 28 report covered the same two-date structure after NCsoft settled the window.", "It also confirms the commercial shape: the game remains free to play at launch, with pre-purchase optional, and the Founder's Packs are still listed with advance access start dates rather than a global midnight already on the page.", "What it does not confirm: server open times, per-region prices on the viewer's own storefront, or any change to the September date confusion — the September reference belongs to the 30th, not to the launch."]),
        section("milestones", "The Milestones Between Now and October 5", ["The nearest item on the official schedule is the Launch Scale Test on September 17–18, with pre-download opening September 16. It is open to everyone with no key, per NCsoft's announcement.", "After the test, the paid early access window runs September 30 – October 4 for all three Founder's Packs, then the game unlocks for everyone on October 5.", "A store-page countdown of 4 weeks therefore spans exactly that sequence: ~2 weeks until the test, then early access, then the free launch."]),
        section("sale-event", "The Store Page Is in a Sale Event Right Now", ["The page currently carries a banner reading “THIS GAME IS PART OF A SALE EVENT”, linking to the Future Games Show sale page on Steam. That is a live storefront state we observed today, not a retrospective note.", "The practical effect is that pre-purchase offers can appear with sale framing during the countdown. The underlying release and advance-access dates do not change because of the banner.", "If you see the banner on your own storefront, it reflects Steam's promotional placement — check the pack price on your own regional store, since displayed prices and sale treatment vary by region."]),
        section("how-to-check", "How to Verify the Countdown Yourself", ["Open the Aion 2 Steam store page and read the release panel: it shows the countdown line, “Release Date: 5 Oct, 2026”, and the advance-access note on each pack. Those three elements are the store's own statement.", "Steam store pages are date-stamped and widely mirrored, so the “approximately 4 weeks” line is checkable — and it will change again as launch approaches. Our fetch of September 1 is the snapshot behind this report.", "For independent confirmation of the window, Niche Gamer's August 28 report and the official Gamescom announcements agree on September 30 / October 5."]),
      ],
    }),
    "zh-hans": articleCopy(newsLabels, "zh-hans", 5, {
      eyebrow: "上线倒计时：4 周",
      title: "Aion 2 上线倒计时：Steam 商店页现显示约 4 周（10 月 5 日）",
      description: "截至 2026-09-01，Aion 2 的 Steam 商店页显示游戏解锁时间约为 4 周，抢先体验（9 月 30 日）也在这段窗口内。这是商店页对 10 月 5 日免费游玩上线的实时倒计时，今日已实测核实。",
      intro: "Aion 2 的 Steam 商店页已进入正式倒计时：显示游戏解锁时间约为 4 周，创始人包的抢先体验——9 月 30 日，上线前 5 天——也将在约 4 周后开始。本文数据来自 2026 年 9 月 1 日的页面实测，不是推测。以下解读倒计时、它所确认与未确认的信息，以及从现在到 10 月 5 日之间的节点。",
      sourceNote: "基于 2026-09-01 对 Aion 2 Steam 商店页的实时抓取，与 Niche Gamer 8 月 28 日关于 9/30–10/5 双日期结构的报道交叉核对。",
      keywords: ["Aion 2 倒计时", "Aion 2 4周", "Aion 2 10月5日", "Aion 2 9月30日抢先体验", "Aion 2 Steam商店"],
      sections: [
        section("the-countdown", "商店页的实时倒计时", ["Steam 商店页目前显示「This game plans to unlock in approximately 4 weeks」，完整发售日列为「Release Date: 5 Oct, 2026」，商店面板重复「Coming 5 Oct, 2026」。倒计时与固定日期一致。", "预购宣传语给出了同样的抢先窗口：预购可在正式发售前 5 天游玩，「Starts in approximately 4 weeks」。这与 9 月 30 日开始抢先体验相符。", "这些文字都没有给出精确解锁时刻。Steam 以周为单位取整，请以 9/30 与 10/5 为日期锚点，精确时刻需等 NCsoft 后续公布。"]),
        section("what-it-confirms", "倒计时确认了什么", ["它确认了 Gamescom 2026 公布的日期：2026 年 10 月 5 日上线，创始人包抢先体验 9 月 30 日至 10 月 4 日。Niche Gamer 8 月 28 日的报道也覆盖了同一双日期结构。", "它也确认了商业形态：上线时免费游玩，预购可选，创始人包页面仍以「抢先体验开始日期」展示而非全球统一午夜时刻。", "它未确认的：服务器开服时刻、各自商店区域的价格、以及任何对「9 月」混乱的修正——9 月指向 30 日，而非上线日。"]),
        section("milestones", "从现在到 10 月 5 日的节点", ["官方日程上最近的一项是 9 月 17–18 日的 Launch Scale Test，预下载 9 月 16 日开启，全员开放无需 key。", "测试之后，付费抢先窗口为 9 月 30 日至 10 月 4 日（三档创始人包），随后 10 月 5 日向所有人免费开放。", "商店页的 4 周倒计时正好覆盖这一序列：约 2 周后测试，然后抢先体验，最后免费上线。"]),
        section("sale-event", "商店页当前正参与促销活动", ["页面现挂有「THIS GAME IS PART OF A SALE EVENT」横幅，链接到 Steam 的 Future Games Show 促销页。这是我们今日观察到的商店实时状态，不是回顾性备注。", "实际效果是：倒计时期间预购可能以促销框架呈现。底层发售日期与抢先体验日期不会因横幅而改变。", "若你在自己区域的商店页看到该横幅，它反映的是 Steam 的推广位——请以自己区域商店的包价格为准，显示价格与促销处理因区域而异。"]),
        section("how-to-check", "如何自行核对倒计时", ["打开 Aion 2 的 Steam 商店页阅读发售面板：它显示倒计时行、「Release Date: 5 Oct, 2026」与每个包的抢先体验注记。这三处即商店自身的声明。", "Steam 商店页有日期戳且被广泛镜像，「approximately 4 weeks」一行可以被复核——它也会随上线临近再次变化。本文基于 9 月 1 日的抓取。", "对窗口的独立确认：Niche Gamer 8 月 28 日报道与官方 Gamescom 公告一致指向 9/30 与 10/5。"]),
      ],
    }),
    ko: articleCopy(newsLabels, "ko", 5, {
      eyebrow: "출시 카운트다운: 4주",
      title: "아이온2 출시 카운트다운: Steam 상점 페이지가 약 4주로 표시(10월 5일)",
      description: "2026년 9월 1일 기준, 아이온2 Steam 상점 페이지는 약 4주 후 해제로 표시하며 얼리 액세스(9월 30일)도 같은 창에 있습니다. 10월 5일 무료 플레이 출시를 향한 상점 실시간 카운트다운입니다.",
      intro: "아이온2 Steam 상점 페이지가 본격적인 카운트다운에 들어갔습니다. 본 기사는 2026년 9월 1일 페이지 실측 기반이며, 카운트다운이 확인하는 것과 확인하지 않는 것, 10월 5일까지의 마일스톤을 정리합니다.",
      sourceNote: "2026년 9월 1일 아이온2 Steam 상점 페이지 실측과 Niche Gamer의 8월 28일 9/30–10/5 이중 날짜 보도를 교차 확인했습니다.",
      keywords: ["아이온2 카운트다운", "아이온2 4주", "아이온2 10월 5일", "아이온2 9월 30일 얼리 액세스", "아이온2 Steam 상점"],
      sections: [
        section("the-countdown", "상점의 실시간 카운트다운", "Steam 상점 페이지는 현재 '약 4주 후 해제'라 표시하며, 발매일은 '5 Oct, 2026'입니다. 예약 구매 문구도 같은 창을 줍니다(정식 발매 5일 전부터 플레이, 약 4주 후 시작). 정확한 해제 시각은 없습니다 — 9/30과 10/5를 날짜 기준점으로 삼으세요."),
        section("what-it-confirms", "카운트다운이 확인하는 것", "Gamescom 2026에서 밝힌 일정을 재확인합니다: 10월 5일 출시, 파운더스 팩 9월 30일–10월 4일 사전 체험. 게임은 출시 시 무료이며 예약 구매는 선택입니다. 서버 오픈 시각·지역별 가격은 페이지에 없습니다."),
        section("milestones", "지금부터 10월 5일까지", "가장 가까운 공식 일정은 9월 17–18일 Launch Scale Test(사전 다운로드 9월 16일, 키 없이 전원 오픈)입니다. 이후 9월 30일–10월 4일 유료 사전 체험, 10월 5일 전원 무료 출시. 4주 카운트다운이 이 순서를 그대로 담습니다."),
        section("sale-event", "상점 페이지는 지금 세일 이벤트에 포함", "페이지에 'THIS GAME IS PART OF A SALE EVENT' 배너가 있고 Future Games Show 세일 페이지를 링크합니다. 세일 프레임이 붙어도 발매일과 사전 체험 날짜는 바뀌지 않습니다. 가격은 자신의 지역 상점에서 확인하세요."),
        section("how-to-check", "직접 확인하는 법", "Aion 2 Steam 상점 페이지의 발매 패널에서 카운트다운 줄, 'Release Date: 5 Oct, 2026', 각 팩의 사전 체험 문구를 읽으면 됩니다. 이 기사는 9월 1일 스냅샷 기준이며, Niche Gamer(8/28)와 공식 Gamescom 발표가 9/30·10/5를 함께 지지합니다."),
      ],
    }),
    ja: articleCopy(newsLabels, "ja", 5, {
      eyebrow: "発売カウントダウン: 4週間",
      title: "Aion 2 発売カウントダウン：Steamストアページが約4週間と表示（10月5日）",
      description: "2026年9月1日時点で、Aion 2 のSteamストアページは約4週間後の解放と表示し、先行体験（9月30日）も同じ窓にあります。10月5日の基本無料発売へのリアルタイムカウントダウンです。",
      intro: "Aion 2 のSteamストアページが本格的なカウントダウンに入りました。本記事は2026年9月1日のページ実測に基づき、カウントダウンが確認する点・しない点・10月5日までのマイルストーンを整理します。",
      sourceNote: "2026年9月1日のAion 2 Steamストアページ実測と、Niche Gamerの8月28日付9/30–10/5二段構成報道を照合しました。",
      keywords: ["Aion 2 カウントダウン", "Aion 2 4週間", "Aion 2 10月5日", "Aion 2 9月30日 先行体験", "Aion 2 Steamストア"],
      sections: [
        section("the-countdown", "ストアのリアルタイムカウントダウン", "Steamストアページは現在「約4週間後に解放」と表示し、発売日は「5 Oct, 2026」です。予約購入の文言も同じ窓を示します（正式発売の5日前からプレイ、約4週間後に開始）。正確な解放時刻はありません — 9/30と10/5を日付の基準にしてください。"),
        section("what-it-confirms", "カウントダウンが確認すること", "Gamescom 2026で発表された日程を再確認します：10月5日発売、ファウンダーズパック9月30日–10月4日先行体験。発売時は基本無料で、予約購入は任意です。サーバー開放時刻・地域別価格はページにありません。"),
        section("milestones", "今から10月5日まで", "最も近い公式予定は9月17–18日のLaunch Scale Test（事前DL 9月16日、キー不要で全員開放）です。その後9月30日–10月4日の有料先行、10月5日の全員無料リリース。4週間カウントダウンがこの順序をそのまま含みます。"),
        section("sale-event", "ストアページは現在セール対象", "ページに「THIS GAME IS PART OF A SALE EVENT」バナーがあり、Future Games Showセールをリンクします。セール表示でも発売日と先行体験日は変わりません。価格は自分の地域ストアで確認してください。"),
        section("how-to-check", "自分で確認する方法", "Aion 2 のSteamストアページの発売パネルで、カウントダウン行・「Release Date: 5 Oct, 2026」・各パックの先行体験文言を読めば確認できます。本記事は9月1日スナップショット基準で、Niche Gamer（8/28）と公式Gamescom発表が9/30・10/5を裏付けます。"),
      ],
    }),
    fr: articleCopy(newsLabels, "fr", 5, {
      eyebrow: "COMPTE À REBOURS : 4 SEMAINES",
      title: "Compte à rebours Aion 2 : la page Steam affiche environ 4 semaines avant le 5 octobre",
      description: "Au 1er septembre 2026, la page Steam d'Aion 2 affiche un déverrouillage dans environ 4 semaines, avec l'accès anticipé (30 septembre) dans la même fenêtre. C'est le compte à rebours de la sortie gratuite du 5 octobre, vérifié aujourd'hui.",
      intro: "La page Steam d'Aion 2 est entrée dans un compte à rebours sérieux : elle affiche un déverrouillage dans environ 4 semaines, et l'accès anticipé du 30 septembre commence « dans environ 4 semaines » aussi. Chiffres relevés le 1er septembre 2026, pas des spéculations.",
      sourceNote: "Basé sur une capture de la page Steam d'Aion 2 le 1er septembre 2026, recoupée avec le report de Niche Gamer du 28 août sur la fenêtre 30 septembre – 5 octobre.",
      keywords: ["Aion 2 compte à rebours", "Aion 2 4 semaines", "Aion 2 5 octobre", "Aion 2 accès anticipé 30 septembre", "Aion 2 page Steam"],
      sections: [
        section("the-countdown", "Le compte à rebours de la boutique", "La page Steam indique « environ 4 semaines » avant le déverrouillage, avec « Release Date: 5 Oct, 2026 ». Le bloc de préachat donne la même fenêtre pour l'accès anticipé (5 jours avant, environ 4 semaines). Aucune heure précise : prenez le 30 septembre et le 5 octobre comme ancres."),
        section("what-it-confirms", "Ce que cela confirme", "Cela confirme les dates de Gamescom 2026 : lancement le 5 octobre, accès anticipé des packs Fondateur du 30 septembre au 4 octobre. Le jeu reste gratuit au lancement, le préachat est optionnel. Ni heures d'ouverture des serveurs ni prix régionaux ne figurent sur la page."),
        section("milestones", "Les étapes d'ici le 5 octobre", "Le test de charge 17–18 septembre (pré-téléchargement le 16, ouvert à tous sans clé), puis l'accès anticipé payant 30 septembre – 4 octobre, puis le lancement gratuit le 5 octobre. Le compte à rebours de 4 semaines couvre exactement cette séquence."),
        section("sale-event", "La page est dans un événement solde", "La page porte « THIS GAME IS PART OF A SALE EVENT » lié à la page de vente Future Games Show. La bannière ne change ni la sortie ni l'accès anticipé. Vérifiez les prix sur votre boutique régionale."),
        section("how-to-check", "Vérifier soi-même", "Lisez le panneau de sortie de la page Steam d'Aion 2 : ligne de compte à rebours, « Release Date: 5 Oct, 2026 », et la note d'accès anticipé sur chaque pack. Notre capture du 1er septembre est l'instantané de référence ; Niche Gamer (28 août) et les annonces officielles soutiennent 30 septembre / 5 octobre."),
      ],
    }),
    de: articleCopy(newsLabels, "de", 5, {
      eyebrow: "START-COUNTDOWN: 4 WOCHEN",
      title: "Aion-2-Start-Countdown: Die Steampage zeigt etwa 4 Wochen bis zum 5. Oktober",
      description: "Stand 1. September 2026 zeigt die Aion-2-Steampage eine Freischaltung in etwa 4 Wochen — der Vorabzugang (30. September) liegt in derselben Woche. Das ist der Live-Countdown zum Free-to-play-Start am 5. Oktober, heute verifiziert.",
      intro: "Die Aion-2-Steampage zählt jetzt ernsthaft herunter: Freischaltung in etwa 4 Wochen, und der Founder’s-Pack-Vorabzugang am 30. September beginnt ebenfalls „in etwa 4 Wochen“. Diese Zahlen stammen aus einer Verifikation am 1. September 2026.",
      sourceNote: "Basierend auf einem Live-Abruf der Aion-2-Steampage am 1. September 2026, abgeglichen mit dem Niche-Gamer-Bericht vom 28. August zum Fenster 30. September – 5. Oktober.",
      keywords: ["Aion 2 Countdown", "Aion 2 4 Wochen", "Aion 2 5. Oktober", "Aion 2 Vorabzugang 30. September", "Aion 2 Steampage"],
      sections: [
        section("the-countdown", "Der Live-Countdown der Seite", "Die Steampage zeigt „unlocks in approximately 4 weeks“ mit „Release Date: 5 Oct, 2026“. Der Vorabkauf-Baustein nennt dieselbe Woche für den Vorabzugang (5 Tage vor Release). Keine exakte Uhrzeit vorhanden — 30. September und 5. Oktober sind die Anker."),
        section("what-it-confirms", "Was der Countdown bestätigt", "Die Gamescom-2026-Daten: Start am 5. Oktober, Vorabzugang der Founder's Packs 30. September bis 4. Oktober. Free to play beim Start, Vorabkauf optional. Serverzeiten und Regionalpreise stehen nicht auf der Seite."),
        section("milestones", "Die Etappen bis zum 5. Oktober", "LST 17.–18. September (Vorabdownload 16., offen ohne Key), dann bezahlter Vorabzugang 30. September – 4. Oktober, dann Free-to-play-Start am 5. Oktober. Der 4-Wochen-Countdown deckt genau diese Sequenz ab."),
        section("sale-event", "Die Seite ist gerade in einem Sale-Event", "Die Seite trägt „THIS GAME IS PART OF A SALE EVENT“ mit Link zur Future-Games-Show-Sale-Seite. Das Banner ändert weder Start noch Vorabzugang. Preise bitte im eigenen Regionsshop prüfen."),
        section("how-to-check", "Selbst prüfen", "Lest das Release-Panel der Aion-2-Steampage: Countdown-Zeile, „Release Date: 5 Oct, 2026“ und die Vorabzugangs-Notiz je Pack. Unser Abruf vom 1. September ist der Bezugspunkt; Niche Gamer (28. August) und die offiziellen Ankündigungen stützen 30. September / 5. Oktober."),
      ],
    }),
    es: articleCopy(newsLabels, "es", 5, {
      eyebrow: "CUENTA ATRÁS: 4 SEMANAS",
      title: "Cuenta atrás de Aion 2: la tienda de Steam muestra unas 4 semanas hasta el 5 de octubre",
      description: "Al 1 de septiembre de 2026, la tienda de Steam de Aion 2 muestra el desbloqueo en unas 4 semanas, con el acceso anticipado (30 de septiembre) en la misma ventana. Es el conteo de la salida gratuita del 5 de octubre, verificado hoy.",
      intro: "La tienda de Steam de Aion 2 ya cuenta en serio: desbloqueo en unas 4 semanas, y el acceso anticipado del 30 de septiembre también empieza «en unas 4 semanas». Datos verificados el 1 de septiembre de 2026, no especulaciones.",
      sourceNote: "Basado en una captura de la tienda de Steam de Aion 2 el 1 de septiembre de 2026, cotejado con el informe de Niche Gamer del 28 de agosto sobre la ventana 30 de septiembre – 5 de octubre.",
      keywords: ["Aion 2 cuenta atrás", "Aion 2 4 semanas", "Aion 2 5 de octubre", "Aion 2 acceso anticipado 30 de septiembre", "Aion 2 tienda Steam"],
      sections: [
        section("the-countdown", "La cuenta atrás de la tienda", "La página muestra «unlock in approximately 4 weeks» con «Release Date: 5 Oct, 2026». El bloque de compra anticipada da la misma ventana (5 días antes, unas 4 semanas). Sin hora exacta: ancla el 30 de septiembre y el 5 de octubre."),
        section("what-it-confirms", "Qué confirma", "Las fechas de Gamescom 2026: salida el 5 de octubre, acceso anticipado de packs Fundador del 30 de septiembre al 4 de octubre. Gratis en el lanzamiento, compra anticipada opcional. Ni horas de servidores ni precios regionales en la página."),
        section("milestones", "Los hitos hasta el 5 de octubre", "El test de carga 17–18 de septiembre (precarga el 16, abierto a todos sin clave), luego el acceso anticipado de pago del 30 de septiembre al 4 de octubre, luego la salida gratuita el 5 de octubre. La cuenta de 4 semanas cubre esa secuencia."),
        section("sale-event", "La página está en un evento de ofertas", "Lleva «THIS GAME IS PART OF A SALE EVENT» enlazado a la página de ventas Future Games Show. El banner no cambia salida ni acceso anticipado. Verifica precios en tu tienda regional."),
        section("how-to-check", "Cómo comprobarlo", "Lee el panel de salida de la tienda de Steam de Aion 2: línea de cuenta, «Release Date: 5 Oct, 2026» y la nota de acceso anticipado en cada pack. Nuestra captura del 1 de septiembre es la referencia; Niche Gamer (28 de agosto) y los anuncios oficiales sostienen el 30 de septiembre / 5 de octubre."),
      ],
    }),
    "pt-br": articleCopy(newsLabels, "pt-br", 5, {
      eyebrow: "CONTAGEM REGRESSIVA: 4 SEMANAS",
      title: "Contagem regressiva de Aion 2: a loja da Steam mostra cerca de 4 semanas até 5 de outubro",
      description: "Em 1º de setembro de 2026, a loja da Steam do Aion 2 mostra o desbloqueio em cerca de 4 semanas, com o acesso antecipado (30 de setembro) na mesma janela. É a contagem para o lançamento gratuito de 5 de outubro, verificada hoje.",
      intro: "A loja da Steam do Aion 2 já conta a sério: desbloqueio em cerca de 4 semanas, e o acesso antecipado de 30 de setembro também começa «em cerca de 4 semanas». Dados verificados em 1º de setembro de 2026, sem especulação.",
      sourceNote: "Com base em uma captura da loja da Steam do Aion 2 em 1º de setembro de 2026, cruzado com o relato da Niche Gamer de 28 de agosto sobre a janela de 30 de setembro – 5 de outubro.",
      keywords: ["Aion 2 contagem regressiva", "Aion 2 4 semanas", "Aion 2 5 de outubro", "Aion 2 acesso antecipado 30 de setembro", "Aion 2 loja Steam"],
      sections: [
        section("the-countdown", "A contagem da loja", "A página mostra «unlock in approximately 4 weeks» com «Release Date: 5 Oct, 2026». O bloco de pré-compra dá a mesma janela (5 dias antes, cerca de 4 semanas). Sem hora exata: use 30 de setembro e 5 de outubro como âncoras."),
        section("what-it-confirms", "O que confirma", "As datas da Gamescom 2026: lançamento em 5 de outubro, acesso antecipado dos packs Fundador de 30 de setembro a 4 de outubro. Gratuito no lançamento, pré-compra opcional. Nem horas de servidores nem preços regionais na página."),
        section("milestones", "Os marcos até 5 de outubro", "O teste de carga 17–18 de setembro (pré-download dia 16, aberto a todos sem chave), depois o acesso antecipado pago de 30 de setembro a 4 de outubro, depois o lançamento gratuito em 5 de outubro. A contagem de 4 semanas cobre essa sequência."),
        section("sale-event", "A página está em evento de ofertas", "Traz «THIS GAME IS PART OF A SALE EVENT» ligado à página de vendas Future Games Show. O banner não muda lançamento nem acesso antecipado. Confira preços na sua loja regional."),
        section("how-to-check", "Como verificar", "Leia o painel de lançamento da loja da Steam do Aion 2: linha de contagem, «Release Date: 5 Oct, 2026» e a nota de acesso antecipado em cada pack. Nossa captura de 1º de setembro é a referência; a Niche Gamer (28/8) e os anúncios oficiais sustentam 30/9 e 5/10."),
      ],
    }),
    ru: articleCopy(newsLabels, "ru", 5, {
      eyebrow: "ОБРАТНЫЙ ОТСЧЁТ: 4 НЕДЕЛИ",
      title: "Обратный отсчёт Aion 2: страница Steam показывает около 4 недель до 5 октября",
      description: "На 1 сентября 2026 страница Steam Aion 2 показывает разблокировку примерно через 4 недели, и ранний доступ (30 сентября) в том же окне. Это отсчёт к бесплатному запуску 5 октября, проверено сегодня.",
      intro: "Страница Steam Aion 2 теперь отсчитывает всерьёз: разблокировка примерно через 4 недели, и ранний доступ 30 сентября тоже стартует «примерно через 4 недели». Данные проверены 1 сентября 2026, не предположения.",
      sourceNote: "На основе живой загрузки страницы Steam Aion 2 1 сентября 2026, сверено с отчётом Niche Gamer от 28 августа об окне 30 сентября – 5 октября.",
      keywords: ["Aion 2 отсчёт", "Aion 2 4 недели", "Aion 2 5 октября", "Aion 2 ранний доступ 30 сентября", "Aion 2 страница Steam"],
      sections: [
        section("the-countdown", "Живой отсчёт магазина", "Страница показывает «unlock in approximately 4 weeks» с «Release Date: 5 Oct, 2026». Блок предзаказа даёт то же окно для раннего доступа (за 5 дней до релиза). Точного часа нет — якорями служат 30 сентября и 5 октября."),
        section("what-it-confirms", "Что это подтверждает", "Даты Gamescom 2026: запуск 5 октября, ранний доступ паков основателя 30 сентября – 4 октября. Бесплатно при запуске, предзаказ опционален. На странице нет ни часов открытия серверов, ни региональных цен."),
        section("milestones", "Этапы до 5 октября", "Стресс-тест 17–18 сентября (предзагрузка 16-го, открыт всем без ключа), затем платный ранний доступ 30 сентября – 4 октября, затем бесплатный запуск 5 октября. Отсчёт в 4 недели покрывает эту последовательность."),
        section("sale-event", "Страница участвует в распродаже", "На странице баннер «THIS GAME IS PART OF A SALE EVENT» со ссылкой на распродажу Future Games Show. Баннер не меняет ни запуск, ни ранний доступ. Цены проверяйте в своём региональном магазине."),
        section("how-to-check", "Как проверить самому", "Прочитайте панель релиза страницы Steam Aion 2: строку отсчёта, «Release Date: 5 Oct, 2026» и заметку о раннем доступе на каждом паке. Наш снимок от 1 сентября — ориентир; Niche Gamer (28/8) и официальные анонсы поддерживают 30/9 и 5/10."),
      ],
    }),
    "zh-hant": articleCopy(newsLabels, "zh-hant", 5, {
      eyebrow: "上線倒數：4 週",
      title: "Aion 2 上線倒數：Steam 商店頁現顯示約 4 週（10 月 5 日）",
      description: "截至 2026-09-01，Aion 2 的 Steam 商店頁顯示遊戲解鎖時間約為 4 週，搶先體驗（9 月 30 日）也在這窗口內。這是商店頁對 10 月 5 日免費遊玩上線的即時倒數，今日已實測核實。",
      intro: "Aion 2 的 Steam 商店頁已進入正式倒數：顯示遊戲解鎖時間約為 4 週，創始人包的搶先體驗——9 月 30 日，上線前 5 天——也將在約 4 週後開始。本文數據來自 2026 年 9 月 1 日的頁面實測，不是推測。",
      sourceNote: "基於 2026-09-01 對 Aion 2 Steam 商店頁的即時抓取，與 Niche Gamer 8 月 28 日關於 9/30–10/5 雙日期結構的報導交叉核對。",
      keywords: ["Aion 2 倒數", "Aion 2 4週", "Aion 2 10月5日", "Aion 2 9月30日搶先體驗", "Aion 2 Steam商店"],
      sections: [
        section("the-countdown", "商店頁的即時倒數", ["Steam 商店頁目前顯示「This game plans to unlock in approximately 4 weeks」，完整發售日列為「Release Date: 5 Oct, 2026」。預購宣傳語給出相同窗口：正式發售前 5 天遊玩，「Starts in approximately 4 weeks」。這些文字沒有給出精確解鎖時刻，請以 9/30 與 10/5 為日期錨點。"]),
        section("what-it-confirms", "倒數確認了什麼", ["它確認了 Gamescom 2026 公布的日期：2026 年 10 月 5 日上線，創始人包搶先體驗 9 月 30 日至 10 月 4 日。上線時免費遊玩，預購可選。它未確認的：伺服器開服時刻、各自商店區域的價格。"]),
        section("milestones", "從現在到 10 月 5 日的節點", ["官方日程上最近的一項是 9 月 17–18 日的 Launch Scale Test，預下載 9 月 16 日開啟，全員開放無需 key。之後付費搶先窗口 9 月 30 日至 10 月 4 日，隨後 10 月 5 日向所有人免費開放。"]),
        section("sale-event", "商店頁當前正參與促銷活動", ["頁面現掛有「THIS GAME IS PART OF A SALE EVENT」橫幅，連結到 Steam 的 Future Games Show 促銷頁。底層發售日期與搶先體驗日期不會因橫幅而改變。價格請以自己區域商店為準。"]),
        section("how-to-check", "如何自行核對倒數", ["打開 Aion 2 的 Steam 商店頁閱讀發售面板：倒數行、「Release Date: 5 Oct, 2026」與每個包的搶先體驗注記。本文基於 9 月 1 日的抓取；Niche Gamer 8 月 28 日報導與官方 Gamescom 公告一致指向 9/30 與 10/5。"]),
      ],
    }),
  },
};