import { articleCopy, localizations, guideLabels, publishedVerified, section } from "./trending-september-14-shared";
import type { ContentEntry, ContentHeroImage, ContentSource } from "./content-registry";

/* ARTICLE 5 — Aion 2 skill system deep dive */

const skillSource: ContentSource = {
  id: "aion2-skill-system-guide-2026-09-12",
  kind: "third-party",
  publisher: "YouTube Community Guide",
  label: "Aion 2: Complete Skill Systems Guide",
  url: "https://www.youtube.com/@aion2guide",
  publishedAt: "2026-09-12",
  retrievedAt: "2026-09-14",
  verifiedAt: "2026-09-14",
  localizations: localizations({
    "zh-hans": "Aion 2：完整技能系统攻略",
    en: "Aion 2: Complete Skill Systems Guide",
    fr: "Aion 2 : Guide complet des systèmes de compétences",
    de: "Aion 2: Kompletter Fähigkeiten-System Guide",
    es: "Aion 2: Guía completa del sistema de habilidades",
    ja: "Aion 2：完全スキルシステムガイド",
    "pt-br": "Aion 2: Guia completo do sistema de habilidades",
    ru: "Aion 2: Полное руководство по системе навыков",
    ko: "Aion 2: 완전한 스킬 시스템 가이드",
    "zh-hant": "Aion 2：完整技能系統攻略",
  }, "https://www.youtube.com/@aion2guide"),
};

const skillHero: ContentHeroImage = {
  src: "https://blogfiles.ncsoft.net/news/af7330da-4ff6-4b58-aece-400e6061a3be.jpg",
  width: 1200, height: 630,
  credit: "NC Corporation",
  sourceUrl: "https://aion2.plaync.com/en-us/",
  rights: "linked-official-media",
  translations: {
    "zh-hans": { alt: "Aion 2 技能系统深度攻略横幅", caption: "Aion 2 的技能系统包含主动/被动技能、技能树和技能点分配——上线前理解这些机制将让你提前规划构建。" },
    en: { alt: "Aion 2 skill system deep dive guide banner", caption: "Aion 2's skill system features active and passive skills, skill trees, and skill point allocation — understanding these pre-launch helps you plan builds early." },
    fr: { alt: "Bannière du guide approfondi des compétences d'Aion 2", caption: "Le système de compétences d'Aion 2 comprend compétences actives et passives, arbres et points de compétence." },
    de: { alt: "Banner des vertiefenden Fähigkeiten-Guides von Aion 2", caption: "Das Fähigkeitensystem von Aion 2 umfasst aktive und passive Fähigkeiten, Bäume und Punkte." },
    es: { alt: "Banner de la guía profunda del sistema de habilidades de Aion 2", caption: "El sistema de habilidades de Aion 2 incluye habilidades activas y pasivas, árboles y puntos." },
    ja: { alt: "Aion 2 スキルシステム深掘りガイドバナー", caption: "Aion 2のスキルシステムにはアクティブ/パッシブスキル、スキルツリー、スキルポイントが含まれます。" },
    "pt-br": { alt: "Banner da guia aprofundada do sistema de habilidades do Aion 2", caption: "O sistema de habilidades do Aion 2 inclui habilidades ativas e passivas, árvores e pontos." },
    ru: { alt: "Баннер подробного руководства по навыкам Aion 2", caption: "Система навыков Aion 2 включает активные и пассивные навыки, деревья и очки." },
    ko: { alt: "Aion 2 스킬 시스템 심층 가이드 배너", caption: "Aion 2의 스킬 시스템에는 활성/패시브 스킬, 스킬 트리, 스킬 포인트가 포함되어 있습니다." },
    "zh-hant": { alt: "Aion 2 技能系統深度攻略橫幅", caption: "Aion 2 的技能系統包含主動/被動技能、技能樹和技能點分配——上線前理解這些機制將讓你提前規劃構建。" },
  },
};

export const trendingSeptember14Article5: ContentEntry = {
  section: "guides",
  slug: "aion-2-skill-system-deep-dive",
  schemaType: "Article",
  publishedAt: "2026-09-14",
  updatedAt: "2026-09-14",
  readingMinutes: 7,
  publication: publishedVerified,
  sources: [skillSource],
  heroImage: skillHero,
  related: [
    { kind: "content", section: "guides", slug: "aion-2-skill-preset-overhaul-guide" },
    { kind: "content", section: "classes", slug: "class-planning-framework" },
    { kind: "content", section: "guides", slug: "aion-2-item-level-progression-roadmap" },
    { kind: "content", section: "guides", slug: "aion-2-enhancement-system-strategy-guide" },
  ],
  translations: {
    en: articleCopy(guideLabels, "en", 7, {
      eyebrow: "BUILDING",
      title: "Aion 2 Skill System Deep Dive: Pre-Launch Build Guide for Every Class",
      description: "A complete breakdown of Aion 2's skill system — active and passive skills, skill trees, skill points, cooldown management, and build optimization strategies for global launch",
      intro: "Aion 2's skill system is the core of every character's identity. Unlike its predecessor, Aion 2 reworked the skill framework from the ground up — introducing skill trees, shared passive pools, and a more fluid cooldown system. Understanding these mechanics before the global launch will give you a significant head start.",
      sourceNote: "Based on YouTube community skill system guides and the Korean service skill system as of September 2026. Global values may differ under the modified Season 1.",
      keywords: ["Aion 2 skill system guide", "Aion 2 skill tree build", "Aion 2 skill points guide", "Aion 2 pre-launch build", "Aion 2 cooldown management"],
      sections: [
        section("skill-structure", "How the Skill System Works", ["Every class in Aion 2 has two types of skills: Active Skills (offensive, defensive, and utility abilities with cooldowns) and Passive Skills (stat bonuses, damage modifiers, and survival enhancements with no cooldown).", "Skills are organized into trees — each class has a unique tree layout with nodes that unlock progressively as you earn skill points. Some nodes have prerequisites, creating branching paths that define your build philosophy."]),
        section("skill-points", "Skill Points and Allocation", ["Skill points are earned through character leveling, quest completion, and certain achievements. Unlike Aion 1, skill points in Aion 2 are largely class-specific with a smaller shared pool for passive abilities.", "Most classes receive between 50-80 skill points by the time they reach the max content level. Allocation strategy matters — some builds invest heavily in offense, while tank builds prioritize survivability passives."]),
        section("cooldowns", "Cooldown Management and Rotation", ["Active skills have cooldowns ranging from 2 seconds (basic attacks) to 60+ seconds (ultimate abilities). Effective builds focus on minimizing downtime by staggering cooldowns — combining short-cooldown nukes with longer cooldowns that overlap their recovery.", "The skill preset system (covered in a separate guide) allows you to save multiple configurations — one for dungeons, one for PvP, one for farming. Switching presets is instant, making it easy to adapt to different content types."]),
        section("class-examples", "Build Examples for Popular Classes", ["For damage-dealing classes, the typical approach is investing in offensive passive bonuses (damage, critical hit rate, skill speed) while building an active rotation around the highest-damage skills available. Avoid spreading points across too many branches — specialization wins.", "For tank classes, survivability passives (damage reduction, health regeneration, immunity durations) are essential. Active skills should focus on threat generation and crowd control to keep enemies in range for your party's damage dealers."]),
        section("pre-launch-tips", "Pre-Launch Build Preparation Tips", ["Study the Korean service data. While global values may be adjusted, the fundamental skill structures and tree layouts are expected to remain similar. Community guides from Korean content creators are the best pre-launch resource.", "Plan for flexibility. The modified Season 1 will likely include balance adjustments in the first weeks. Choose builds that are versatile enough to remain viable even after tuning.", "Use the skill preset system to your advantage. Test different builds during the Launch Scale Test and save your favorites. You can refine and iterate without losing your current configuration."]),
      ],
    }),
    "zh-hans": articleCopy(guideLabels, "zh-hans", 7, {
      eyebrow: "构建",
      title: "Aion 2 技能系统深度攻略：上线前全职业构建指南",
      description: "Aion 2 技能系统全面解析——主动/被动技能、技能树、技能点、冷却管理和上线前的构建优化策略",
      intro: "Aion 2 的技能系统是每个角色身份的核心。与前作不同，Aion 2 从底层重新设计了技能框架——引入了技能树、共享被动池和更流畅的冷却系统。在全球上线前理解这些机制将让你获得显著的先发优势。",
      sourceNote: "基于 YouTube 社区技能系统攻略与 2026 年 9 月韩服技能系统。全球数值可能在改良版 Season 1 下有所不同。",
      keywords: ["Aion 2 技能系统攻略", "Aion 2 技能树构建", "Aion 2 技能点攻略", "Aion 2 上线前构建", "Aion 2 冷却管理"],
      sections: [
        section("skill-structure", "技能系统如何运作", ["Aion 2 中的每个职业都有两种技能：主动技能（有冷却的攻击、防御和辅助能力）和被动技能（属性加成、伤害修正和生存增强，无冷却）。", "技能按树组织——每个职业都有独特的树布局，节点随着技能点获取逐步解锁。部分节点有前置条件，形成分支路径来定义你的构建哲学。"]),
        section("skill-points", "技能点与分配", ["技能点通过角色升级、任务完成和特定成就获得。与 Aion 1 不同，Aion 2 的技能点大部分为职业专属，同时有一个较小的共享池用于被动能力。", "大多数职业在达到最大内容等级时获得 50-80 技能点。分配策略很重要——有些构建重投攻击，而坦克构建优先生存被动。"]),
        section("cooldowns", "冷却管理与循环", ["主动技能的冷却范围从 2 秒（基础攻击）到 60+ 秒（终极能力）。有效的构建通过交错冷却来最小化空窗期——将短冷却爆发与长冷却技能重叠恢复时间。", "技能预设系统（在另一篇攻略中详述）允许你保存多个配置——副本、PvP、刷怪各一套。切换预设是瞬时的，便于适应不同内容类型。"]),
        section("class-examples", "热门职业构建示例", ["对于输出职业，典型方法是投资攻击被动加成（伤害、暴击率、技能速度），同时围绕最高伤害技能构建主动循环。避免将技能点分散在过多分支上——专精为王。", "对于坦克职业，生存被动（伤害减免、生命回复、免疫时长）至关重要。主动技能应聚焦威胁生成和控场，将敌人保持在队伍的输出射程内。"]),
        section("pre-launch-tips", "上线前构建准备建议", ["研究韩服数据。虽然全球数值可能调整，但基础技能结构和树布局预计保持不变。韩国内容创作者的社区攻略是最好的上线前资源。", "规划灵活性。改良版 Season 1 可能在前几周包含平衡调整。选择足够通用的构建，即使在调整后仍保持可行性。", "善用技能预设系统。在 Launch Scale Test 期间测试不同构建并保存你喜欢的。你可以精化迭代而不丢失当前配置。"]),
      ],
    }),
    fr: articleCopy(guideLabels, "fr", 7, {
      eyebrow: "BUILD",
      title: "Aion 2 Système de Compétences : Guide de Build Pré-Lancement",
      description: "Une analyse complète du système de compétences d'Aion 2 — compétences actives et passives, arbres, points et stratégies d'optimisation",
      intro: "Le système de compétences d'Aion 2 est le cœur de l'identité de chaque personnage. Comprendre ces mécaniques avant le lancement global vous donnera un avantage significatif.",
      sourceNote: "Basé sur les guides communautaires YouTube et le système coréen de septembre 2026. Les valeurs globales peuvent différer.",
      keywords: ["Aion 2 guide compétences", "Aion 2 arbre compétences", "Aion 2 points compétences", "Aion 2 build pré-lancement"],
      sections: [
        section("skill-structure", "Fonctionnement du Système", ["Chaque classe a des compétences actives (avec cooldowns) et passives (bonus de statistiques). Les compétences sont organisées en arbres."]),
        section("skill-points", "Points de Compétence", ["Les points sont gagnés par le level et les quêtes. La plupart des classes reçoivent 50-80 points au niveau maximal."]),
        section("cooldowns", "Gestion des Cooldowns", ["Les cooldowns vont de 2 secondes à 60+. Un build efficace minimise le temps mort en décalant les cooldowns."]),
        section("class-examples", "Exemples de Builds", ["Pour les DPS, investissez dans les passives offensives. Pour les tanks, priorisez la survivabilité."]),
        section("pre-launch-tips", "Conseils Pré-Lancement", ["Étudiez les données coréennes. Planifiez la flexibilité. Utilisez le système de presets."]),
      ],
    }),
    de: articleCopy(guideLabels, "de", 7, {
      eyebrow: "BUILD",
      title: "Aion 2 Fähigkeitensystem: Pre-Launch Build Guide",
      description: "Eine umfassende Analyse des Fähigkeitensystems von Aion 2 — aktive und passive Fähigkeiten, Bäume, Punkte und Optimierung",
      intro: "Das Fähigkeitensystem von Aion 2 ist der Kern jeder Charakteridentität. Das Verständnis dieser Mechaniken vor dem Global-Launch gibt Ihnen einen Vorsprung.",
      sourceNote: "Basierend auf YouTube-Community-Guides und dem koreanischen System von September 2026.",
      keywords: ["Aion 2 Fähigkeiten Guide", "Aion 2 Fähigkeit Baum", "Aion 2 Fähigkeit Punkte", "Aion 2 Pre-Launch Build"],
      sections: [
        section("skill-structure", "Funktionsweise", ["Jede Klasse hat aktive Fähigkeiten (mit Cooldowns) und passive Fähigkeiten (Status-Boni). Fähigkeiten sind in Bäumen organisiert."]),
        section("skill-points", "Fähigkeits-Punkte", ["Punkte werden durch Leveln und Quests verdient. Die meisten Klassen erhalten 50-80 Punkte."]),
        section("cooldowns", "Cooldown-Management", ["Cooldowns reichen von 2 bis 60+ Sekunden. Ein effektiver Build minimiert Leerlauf durch gestaffelte Cooldowns."]),
        section("class-examples", "Build-Beispiele", ["Für DPS: offensive Passives. Für Tanks: Überlebens-Passives."]),
        section("pre-launch-tips", "Pre-Launch Tipps", ["Studieren Sie koreanische Daten. Planen Sie Flexibilität. Nutzen Sie Presets."]),
      ],
    }),
    es: articleCopy(guideLabels, "es", 7, {
      eyebrow: "BUILD",
      title: "Aion 2 Sistema de Habilidades: Guía de Build Pre-Lanzamiento",
      description: "Un desglose completo del sistema de habilidades de Aion 2 — habilidades activas y pasivas, árboles, puntos y optimización",
      intro: "El sistema de habilidades de Aion 2 es el corazón de la identidad de cada personaje. Comprender estas mecánicas antes del lanzamiento global te dará una ventaja significativa.",
      sourceNote: "Basado en guías comunitarias de YouTube y el sistema coreano de septiembre de 2026.",
      keywords: ["Aion 2 guía habilidades", "Aion 2 árbol habilidades", "Aion 2 puntos habilidades", "Aion 2 build pre-lanzamiento"],
      sections: [
        section("skill-structure", "Cómo Funciona el Sistema", ["Cada clase tiene habilidades activas (con cooldowns) y pasivas (bonificaciones). Las habilidades están organizadas en árboles."]),
        section("skill-points", "Puntos de Habilidad", ["Los puntos se ganan por nivel y misiones. La mayoría de las clases reciben 50-80 puntos."]),
        section("cooldowns", "Gestión de Cooldowns", ["Los cooldowns van de 2 a 60+ segundos. Un build efectivo minimiza el tiempo muerto."]),
        section("class-examples", "Ejemplos de Build", ["Para DPS: pasivas ofensivas. Para tanks: pasivas de supervivencia."]),
        section("pre-launch-tips", "Consejos Pre-Lanzamiento", ["Estudia los datos coreanos. Planifica flexibilidad. Usa el sistema de presets."]),
      ],
    }),
    ja: articleCopy(guideLabels, "ja", 7, {
      eyebrow: "ビルド",
      title: "Aion 2 スキルシステム深掘り：リリース前ビルドガイド",
      description: "Aion 2のスキルシステムの完全解析——アクティブ/パッシブスキル、スキルツリー、スキルポイント、冷却管理",
      intro: "Aion 2のスキルシステムは各キャラクターのアイデンティティの核です。グローバルリリース前にこれらを理解することは大きなアドバンテージとなります。",
      sourceNote: "YouTubeコミュニティガイドおよび2026年9月の韓国サーバーシステムに基づきます。",
      keywords: ["Aion 2 スキルガイド", "Aion 2 スキルツリー", "Aion 2 スキルポイント", "Aion 2 リリース前ビルド"],
      sections: [
        section("skill-structure", "スキルシステムの仕組み", ["各クラスにはアクティブスキル（クールダウンあり）とパッシブスキル（ステータスボーナス）があります。スキルはツリーで構成されます。"]),
        section("skill-points", "スキルポイントと割り当て", ["ポイントはレベルアップとクエストで獲得します。多くのクラスが50-80ポイントを取得します。"]),
        section("cooldowns", "クールダウン管理", ["クールダウンは2秒から60秒以上。有効なビルドはクールダウンを調整して空窗期を最小化します。"]),
        section("class-examples", "ビルド例", ["DPSは攻撃パッシブに投資。タンクは生存パッシブを優先。"]),
        section("pre-launch-tips", "リリース前ヒント", ["韓国データを研究。柔軟性を計画。プリセットを活用。"]),
      ],
    }),
    "pt-br": articleCopy(guideLabels, "pt-br", 7, {
      eyebrow: "BUILD",
      title: "Aion 2 Sistema de Habilidades: Guia de Build Pré-Lançamento",
      description: "Uma análise completa do sistema de habilidades do Aion 2 — habilidades ativas e passivas, árvores, pontos e otimização",
      intro: "O sistema de habilidades do Aion 2 é o coração da identidade de cada personagem. Entender estas mecânicas antes do lançamento global dará uma vantagem significativa.",
      sourceNote: "Baseado em guias comunitários do YouTube e no sistema coreano de setembro de 2026.",
      keywords: ["Aion 2 guia habilidades", "Aion 2 árvore habilidades", "Aion 2 pontos habilidades", "Aion 2 build pré-lançamento"],
      sections: [
        section("skill-structure", "Como Funciona o Sistema", ["Cada classe tem habilidades ativas (com cooldowns) and passivas (bônus de status). Habilidades são organizadas em árvores."]),
        section("skill-points", "Pontos de Habilidade", ["Pontos são ganhos por level e missões. A maioria das classes recebe 50-80 pontos."]),
        section("cooldowns", "Gestão de Cooldowns", ["Cooldowns vão de 2 a 60+ segundos. Um build efetivo minimiza o tempo morto."]),
        section("class-examples", "Exemplos de Build", ["Para DPS: passivas ofensivas. Para tanks: passivas de sobrevivência."]),
        section("pre-launch-tips", "Dicas Pré-Lançamento", ["Estude os dados coreanos. Planeje flexibilidade. Use o sistema de presets."]),
      ],
    }),
    ru: articleCopy(guideLabels, "ru", 7, {
      eyebrow: "БИЛД",
      title: "Aion 2 Система Навыков: Руководство по Билду До Запуска",
      description: "Полный разбор системы навыков в Aion 2 — активные и пассивные навыки, деревья, очки и оптимизация",
      intro: "Система навыков в Aion 2 — ядро идентичности каждого персонажа. Понимание этих механик до глобального запуска даст значительное преимущество.",
      sourceNote: "На основе YouTube-гидов сообщества и корейской системы сентября 2026 г. Глобальные значения могут отличаться.",
      keywords: ["Aion 2 гид навыки", "Aion 2 дерево навыков", "Aion 2 очки навыков", "Aion 2 билд до запуска"],
      sections: [
        section("skill-structure", "Как Работает Система", ["Каждый класс имеет активные навыки (с кулдаунами) и пассивные навыки (бонусы характеристик). Навыки организованы в деревья."]),
        section("skill-points", "Очки Навыков", ["Очки получаются через уровень и квесты. Большинство классов получают 50-80 очков."]),
        section("cooldowns", "Управление Кулдаунами", ["Кулдауны от 2 до 60+ секунд. Эффективный билд минимизирует простой через чередование кулдаунов."]),
        section("class-examples", "Примеры Билдов", ["Для DPS: offensive passives. Для танков: пассивки выживаемости."]),
        section("pre-launch-tips", "Советы До Запуска", ["Изучайте корейские данные. Планируйте гибкость. Используйте пресеты."]),
      ],
    }),
    ko: articleCopy(guideLabels, "ko", 7, {
      eyebrow: "빌드",
      title: "Aion 2 스킬 시스템 심층: 사전 출시 빌드 가이드",
      description: "Aion 2의 스킬 시스템 완전 분석 — 활성/패시브 스킬, 스킬 트리, 스킬 포인트, 쿨타임 관리",
      intro: "Aion 2의 스킬 시스템은 모든 캐릭터 아이덴티티의 핵심입니다. 글로벌 출시 전에 이들을 이해하는 것은 큰 이점이 됩니다.",
      sourceNote: "YouTube 커뮤니티 가이드 및 2026년 9월 한국 서버 시스템에 기반합니다.",
      keywords: ["Aion 2 스킬 가이드", "Aion 2 스킬 트리", "Aion 2 스킬 포인트", "Aion 2 사전 출시 빌드"],
      sections: [
        section("skill-structure", "스킬 시스템 작동 방식", ["각 클래스에는 활성 스킬(쿨타임 포함)과 패시브 스킬(스테이터스 보너스)이 있습니다. 스킬은 트리 형태로 구성됩니다."]),
        section("skill-points", "스킬 포인트", ["포인트는 레벨업과 퀘스트로 획득합니다. 대부분의 클래스가 50-80 포인트를 받습니다."]),
        section("cooldowns", "쿨타임 관리", ["쿨타임은 2초에서 60초 이상. 효과적인 빌드는 쿨타임을 조정해 공백기를 최소화합니다."]),
        section("class-examples", "빌드 예시", ["DPS는 공격 패시브에 투자. 탱크는 생존 패시브 우선."]),
        section("pre-launch-tips", "사전 출시 팁", ["한국 데이터를 연구. 유연성을 계획. 프리셋을 활용."]),
      ],
    }),
    "zh-hant": articleCopy(guideLabels, "zh-hant", 7, {
      eyebrow: "構建",
      title: "Aion 2 技能系統深度攻略：上線前全職業構建指南",
      description: "Aion 2 技能系統全面解析——主動/被動技能、技能樹、技能點、冷卻管理和上線前的構建優化策略",
      intro: "Aion 2 的技能系統是每個角色身份的核。與前作不同，Aion 2 從底層重新設計了技能框架——引入了技能樹、共享被動池和更流暢的冷卻系統。在全球上線前理解這些機制將讓你獲得顯著的先發優勢。",
      sourceNote: "基於 YouTube 社區技能系統攻略與 2026 年 9 月韓服技能系統。全球數值可能在改良版 Season 1 下有所不同。",
      keywords: ["Aion 2 技能系統攻略", "Aion 2 技能樹構建", "Aion 2 技能點攻略", "Aion 2 上線前構建", "Aion 2 冷卻管理"],
      sections: [
        section("skill-structure", "技能系統如何運作", ["Aion 2 中的每個職業都有兩種技能：主動技能（有冷卻的攻擊、防禦和輔助能力）和被動技能（屬性加成、傷害修正和生存增強，無冷卻）。", "技能按樹組織——每個職業都有獨特的樹布局，節點隨著技能點獲取逐步解鎖。部分節點有前置條件，形成分支路徑來定義你的構建哲學。"]),
        section("skill-points", "技能點與分配", ["技能點通過角色升級、任務完成和特定成就獲得。與 Aion 1 不同，Aion 2 的技能點大部分為職業專屬，同時有一個較小的共享池用於被動能力。", "大多數職業在達到最大內容等級時獲得 50-80 技能点。分配策略很重要——有些構建重投攻擊，而坦克構建優先生存被動。"]),
        section("cooldowns", "冷卻管理與循環", ["主動技能的冷卻範圍從 2 秒（基礎攻擊）到 60+ 秒（終極能力）。有效的構建通過交錯冷卻來最小化空窗期——將短冷卻爆發與長冷卻技能重疊恢復時間。", "技能預設系統（在另一篇攻略中詳述）允許你保存多個配置——副本、PvP、刷怪各一套。切換預設是瞬時的，便於適應不同內容類型。"]),
        section("class-examples", "熱門職業構建示例", ["對於輸出職業，典型方法是投資攻擊被動加成（傷害、暴擊率、技能速度），同時圍繞最高傷害技能構建主動循環。避免將技能點分散在過多分支上——專精為王。", "對於坦克職業，生存被動（傷害減免、生命回復、免疫時長）至關重要。主動技能應聚焦威脅生成和控場，將敵人保持在隊伍的輸出射程內。"]),
        section("pre-launch-tips", "上線前構建準備建議", ["研究韓服數據。雖然全球數值可能調整，但基礎技能結構和樹布局預計保持不變。韓國內容創作者的社區攻略是最好的上線前資源。", "規劃靈活性。改良版 Season 1 可能在前幾週包含平衡調整。選擇足夠通用的構建，即使在調整後仍保持可行性。", "善用在技能預設系統。在 Launch Scale Test 期間測試不同構建並保存你喜歡的。你可以精化迭代而不丟失當前配置。"]),
      ],
    }),
  },
};
