import { articleCopy, guideLabels, localizations, publishedVerified, section } from "./trending-august-28-shared";
import type { ContentEntry, ContentHeroImage, ContentSource } from "./content-registry";

/* ARTICLE 4 — Tenth class (Slayer) + upcoming content datamine */

const tcSource1: ContentSource = {
  id: "aion2t-datamine-2026-08-28",
  kind: "third-party", publisher: "AION2T",
  label: "Aion 2 — A Tenth Class, a War for the Fields, and a Temple Nobody Can Enter Yet",
  url: "https://aion2t.com/news/41",
  publishedAt: "2026-08-26",
  retrievedAt: "2026-08-27",
  verifiedAt: "2026-08-27",
  localizations: localizations({
    "zh-hans": "Aion 2 —— 第十个职业、田野之战，以及一座尚无人能进入的寺庙",
    en: "Aion 2 — A Tenth Class, a War for the Fields, and a Temple Nobody Can Enter Yet",
    fr: "Aion 2 — Une dixième classe, une guerre des champs et un temple inaccessible",
    de: "Aion 2 — Eine zehnte Klasse, ein Krieg um die Felder und ein noch unbetretbarer Tempel",
    es: "Aion 2 — Una décima clase, una guerra por los campos y un templo inaccesible",
    ja: "Aion 2 — 10番目のクラス、野の戦争、そしてまだ誰も入れない寺院",
    "pt-br": "Aion 2 — Uma décima classe, uma guerra pelos campos e um templo inacessível",
    ru: "Aion 2 — Десятый класс, война за поля и недоступный храм",
    ko: "Aion 2 — 열 번째 클래스, 들판의 전쟁, 아직 아무도 들어갈 수 없는 사원",
    "zh-hant": "Aion 2 —— 第十個職業、田野之戰，以及一座尚無人能進入的寺廟",
  }, "https://aion2t.com/news/41"),
};

const tcSource2: ContentSource = {
  id: "nc-official-classes-2026-08-28",
  kind: "official", publisher: "NC",
  label: "AION 2 Official Website — Classes & Dev Notes",
  url: "https://aion2.plaync.com/ko-kr/board/notice",
  publishedAt: "2026-08-01",
  retrievedAt: "2026-08-27",
  verifiedAt: "2026-08-27",
  localizations: localizations({
    "zh-hans": "AION 2 官方网站——职业与开发者笔记",
    en: "AION 2 Official Website — Classes & Dev Notes",
    fr: "Site officiel AION 2 — classes et notes des devs",
    de: "AION 2 Offizielle Website — Klassen & Dev-Notizen",
    es: "Sitio web oficial de AION 2 — clases y notas de desarrolladores",
    ja: "AION 2 公式サイト — クラス＆開発者ノート",
    "pt-br": "Site oficial do AION 2 — classes e notas de devs",
    ru: "Официальный сайт AION 2 — классы и заметки разработчиков",
    ko: "AION 2 공식 사이트 — 클래스 및 개발자 노트",
    "zh-hant": "AION 2 官方網站——職業與開發者筆記",
  }, "https://aion2.plaync.com/ko-kr/board/notice"),
};

const tcHero: ContentHeroImage = {
  src: "https://blogfiles.ncsoft.net/news/af7330da-4ff6-4b58-aece-400e6061a3be.jpg",
  width: 1100, height: 605,
  credit: "NC Corporation",
  sourceUrl: "https://aion2.plaync.com/ko-kr/board/notice",
  rights: "linked-official-media",
  translations: {
    "zh-hans": { alt: "Aion 2 第十职业数据挖掘指南配图", caption: "NC 官方配图；数据挖掘（8 月 26 日）指向第十个职业『Slayer』与新阵营战争系统，均为未官方公布的开发中内容。" },
    en: { alt: "Aion 2 tenth class datamine guide image", caption: "Official NC artwork; datamining (August 26) points to a tenth class 'Slayer' and a new faction war system — all unannounced, in-development content." },
    fr: { alt: "Image du guide sur la dixième classe d'Aion 2 (datamining)", caption: "Visuel officiel NC ; le datamining (26 août) évoque une dixième classe « Slayer » et un nouveau système de guerre de faction — non annoncés." },
    de: { alt: "Bild zum Guide zur zehnten Aion-2-Klasse (Datamining)", caption: "Offizielles NC-Artwork; Datamining (26. August) deutet auf eine zehnte Klasse „Slayer“ und ein neues Fraktionskriegssystem hin — unangekündigt." },
    es: { alt: "Imagen de la guía de la décima clase de Aion 2 (datamining)", caption: "Arte oficial de NC; el datamining (26 de agosto) apunta a una décima clase «Slayer» y un nuevo sistema de guerra de facciones — sin anunciar." },
    ja: { alt: "Aion 2 十番目のクラス（データマイニング）ガイド画像", caption: "NC公式アートワーク；データマイニング（8月26日）は十番目のクラス「スレイヤー」と新陣営戦争システムを示唆 — 未発表の開発中コンテンツです。" },
    "pt-br": { alt: "Imagem do guia da décima classe do Aion 2 (datamining)", caption: "Arte oficial da NC; o datamining (26 de agosto) aponta para uma décima classe «Slayer» e um novo sistema de guerra de facções — não anunciado." },
    ru: { alt: "Изображение гайда по десятому классу Aion 2 (датамайнинг)", caption: "Официальный арт NC; датамайнинг (26 августа) указывает на десятый класс «Слэер» и новую систему фракционной войны — не анонсировано." },
    ko: { alt: "Aion 2 열 번째 클래스(데이터 마이닝) 가이드 이미지", caption: "NC 공식 이미지입니다. 데이터 마이닝(8월 26일)은 열 번째 클래스 '슬레이어'와 새 진영 전쟁 시스템을 암시합니다 — 미공개 개발 중 콘텐츠입니다." },
    "zh-hant": { alt: "Aion 2 第十職業資料挖掘指南配圖", caption: "NC 官方配圖；資料挖掘（8 月 26 日）指向第十個職業『Slayer』與新陣營戰爭系統，均為未官方公布的開發中內容。" },
  },
};

export const trendingAugust28Article4: ContentEntry = {
  section: "guides",
  slug: "aion-2-tenth-class-guide",
  schemaType: "Article",
  publishedAt: "2026-08-27",
  updatedAt: "2026-08-27",
  readingMinutes: 5,
  publication: publishedVerified,
  sources: [tcSource1, tcSource2],
  heroImage: tcHero,
  related: [
    { kind: "content", section: "news", slug: "second-new-class-teased" },
    { kind: "content", section: "guides", slug: "aion-2-launch-classes-guide" },
    { kind: "content", section: "guides", slug: "class-selection-pve-pvp-guide-global" },
  ],
  translations: {
    en: articleCopy(guideLabels, "en", 5, {
      eyebrow: "DATAMINE — UNOFFICIAL",
      title: "Aion 2's Tenth Class: 'Slayer' & What Dataminers Found (Aug 26)",
      description: "Datamining of the August 26 update points to a tenth class called 'Slayer', a 32-fortress faction war, and an inaccessible temple. Here is what was found, clearly marked as unofficial.",
      intro: "Every Aion 2 patch brings a wave of datamining, and the August 26 update was no exception. Community dataminers found references to a tenth class — 'Slayer' — alongside a large-scale faction war system and an unreachable temple. None of this is officially announced, so this guide presents the findings with that caveat front and center, and explains what it could mean for players and for the global launch.",
      sourceNote: "Based on AION2T's August 26 datamine report. All items in this article are unconfirmed, unofficial, in-development content pulled from the game client; NC has not announced any of it. Treat everything as speculative.",
      keywords: ["Aion 2 tenth class", "Aion 2 Slayer class", "Aion 2 new class 2026", "Aion 2 faction war", "Aion 2 datamine"],
      sections: [
        section("slayer", "The Tenth Class: 'Slayer'", ["Dataminers found references to a tenth class named 'Slayer' (also translated as killer). The found data includes a first skill, a projectile, a glide ability, and — notably — a weapon type that no existing class uses.", "The 'new weapon type' is the most interesting signal, because Aion 2's classes are defined as much by their weapon as by their role. A fresh weapon family would make Slayer feel mechanically distinct rather than a re-skin of an existing class.", "There is no official confirmation of any of this. Class balance is a live topic (see the Great Rebalance guide), so any new class will likely land after the current balance pass settles."]),
        section("rift-war", "Spacetime Rift Domination (Field War)", ["Alongside the class, dataminers found an interface for 'Spacetime Rift Domination' — an open-world faction war built around 32 fortresses, with the UI fully coded in the client.", "If accurate, this is a large-scale open-world PvPvE structure: territory spread across 32 fortresses, presumably contested by Elyos and Asmodians in a persistent or scheduled war.", "The site's existing Abyss and PvP guides cover the current open-world PvP; a 32-fortress system would be a major expansion of that loop if it ships. Treat it as a roadmap rumor until NC confirms."]),
        section("temple", "The Temple Nobody Can Enter Yet", ["The datamine also flagged six dungeon maps for a 'temple' room that no player can enter yet — content that shipped in the update's data but has no access in the current build.", "Six maps for one area suggests a substantial instanced dungeon or raid zone being staged for a future update. This matches the pattern of content being pushed ahead of its unlock, as seen with the game's ongoing chapter structure.", "Players familiar with the roadmap pattern should expect this to be gated behind a future patch rather than appearing immediately."]),
        section("other-finds", "Other Finds in the Patch", ["Dataminers also logged more than 2,000 new creature spawn points in the Eltnen and Morheim regions (with no attached attributes yet), two unrevealed cash-shop spending caps, and six Unique wings locked behind padlocks in the client.", "The 2,000+ spawn points suggest future open-world content density in two launch regions, while the padlocked wings point to premium cosmetics planned for later.", "None of these have been announced either — read them as early signals of where NC is spending development effort."]),
        section("takeaway", "What It Means", ["For class players: if Slayer ships, it will become a tenth option to weigh against the current lineup — and a new weapon type means new build theory to explore. Until then, plan around the nine existing classes.", "For meta and PvP players: a 32-fortress field war would reshape open-world endgame if confirmed, making the Abyss expansion a likely 2026-2027 roadmap item.", "Above all, treat this page as speculative. Official class and content announcements are the only things that should change your decisions; everything here is a datamined hint."]),
      ],
    }),
    "zh-hans": articleCopy(guideLabels, "zh-hans", 5, {
      eyebrow: "数据挖掘——非官方",
      title: "Aion 2 第十职业『Slayer』与数据挖掘发现（8月26日）",
      description: "对 8 月 26 日更新的数据挖掘指向第十个职业『Slayer』、32 要塞阵营战争与一座无法进入的寺庙。以下为发现内容，均明确标注为非官方。",
      intro: "每次 Aion 2 补丁都伴随一轮数据挖掘，8 月 26 日更新也不例外。社区挖掘者发现第十个职业『Slayer』的引用，以及大规模阵营战争系统与一座不可达寺庙。以上均未官方公布，本指南将此警告放在最前，并解释其对玩家与全球上线的可能意义。",
      sourceNote: "基于 AION2T 8 月 26 日数据挖掘报告。本文全部内容为未确认、非官方的开发中内容；NC 未公布任何一项，请一律视为推测。",
      keywords: ["Aion 2 第十职业", "Aion 2 Slayer 职业", "Aion 2 新职业 2026", "Aion 2 阵营战争", "Aion 2 数据挖掘"],
      sections: [
        section("slayer", "第十职业『Slayer』", ["挖掘者发现名为『Slayer』（杀手）的第十职业引用，包含首个技能、投射物、滑翔能力，以及——关键——一个现有职业均未使用的武器类型。", "『新武器类型』是最有趣信号：Aion 2 职业由武器与定位共同定义，新武器家族会让 Slayer 在机制上区别于现有职业。", "以上均无官方确认。"]),
        section("rift-war", "时空裂缝支配（田野之战）", ["与职业一同，挖掘者发现『时空裂缝支配』的界面——围绕 32 座要塞的开放世界阵营战争，UI 已完整写入客户端。", "若属实，这是大规模开放世界 PvPvE 结构：领土分布于 32 座要塞，由 Elyos 与 Asmodians 争夺。", "请视为路线图传闻，待 NC 确认。"]),
        section("temple", "无人能进入的寺庙", ["挖掘还标记了六张『寺庙』房间的地下城地图，当前构建中无任何玩家可进入——内容随更新数据推送但未开放。", "一个区域六张地图暗示大型实例副本或团队本正在为未来更新排期。", "预计被后续补丁解锁，而非立即出现。"]),
        section("other-finds", "补丁中的其他发现", ["Eltnen 与 Morheim 新增 2000+ 生物刷新点（尚无属性）、两项未公布的商城消费上限、六件上锁的 Unique 翅膀。", "2000+ 刷新点暗示两个首发区域的未来开放世界密度；上锁翅膀指向计划中的高级外观。", "以上均未公布，仅作早期信号。"]),
        section("takeaway", "意义", ["职业玩家：若 Slayer 上线，将成为需要权衡的第十选项，新武器类型意味着新的构筑理论。届时再规划。", "版本/PvP 玩家：32 要塞田野之战若确认，将重塑开放世界终局，深空扩张或成 2026-2027 路线图项目。", "最重要：视本页为推测。只有官方公告才应改变你的决策。"]),
      ],
    }),
    ko: articleCopy(guideLabels, "ko", 5, {
      eyebrow: "데이터 마이닝 — 비공식",
      title: "Aion 2 열 번째 클래스 '슬레이어'와 데이터 마이닝 발견(8월 26일)",
      description: "8월 26일 업데이트 데이터 마이닝은 열 번째 클래스 '슬레이어', 32개 요새 진영 전쟁, 들어갈 수 없는 사원을 가리킵니다. 발견된 내용을 비공식임을 명시해 정리합니다.",
      intro: "모든 Aion 2 패치는 데이터 마이닝의 물결을 동반하며, 8월 26일 업데이트도 예외가 아니었습니다. 커뮤니티는 열 번째 클래스 '슬레이어', 대규모 진영 전쟁 시스템, 도달 불가능한 사원을 발견했습니다. 모두 미공개이므로 추측임을 강조해 다룹니다.",
      sourceNote: "AION2T의 8월 26일 데이터 마이닝 보고 기반. 본문의 모든 내용은 미확정·비공식 개발 중 콘텐츠이며 NC가 공개하지 않았습니다.",
      keywords: ["Aion 2 열 번째 클래스", "Aion 2 슬레이어 클래스", "Aion 2 신규 클래스 2026", "Aion 2 진영 전쟁", "Aion 2 데이터 마이닝"],
      sections: [
        section("slayer", "열 번째 클래스 '슬레이어'", "첫 스킬, 투사체, 활공 능력, 그리고 기존 클래스가 쓰지 않는 무기 유형이 발견됐습니다. 무기 유형이 핵심 신호입니다. 공식 확인 없음."),
        section("rift-war", "시공간 균열 지배 (들판 전쟁)", "32개 요새를 중심으로 한 오픈월드 진영 전쟁 인터페이스가 발견됐습니다. 로드맵 루머로 취급하세요."),
        section("temple", "아무도 들어갈 수 없는 사원", "6장의 던전 지도가 있는 접근 불가 영역. 대형 인스턴스/레이드가 향후 업데이트로 준비되고 있을 가능성."),
        section("other-finds", "기타 발견", "엘트넨·모르헤임 2000+ 생물 스폰 포인트, 미공개 상점 소비 상한 2개, 잠긴 유니크 날개 6개."),
        section("takeaway", "의미", "슬레이어가 나오면 열 번째 옵션이 됩니다. 32요새 전쟁은 확정 시 오픈월드 엔드게임을 바꿉니다. 모두 추측이며 공식 발표만 신뢰하세요."),
      ],
    }),
    ja: articleCopy(guideLabels, "ja", 5, {
      eyebrow: "データマイニング — 非公式",
      title: "Aion 2 十番目のクラス『スレイヤー』とデータマイニングの発見（8月26日）",
      description: "8月26日アップデートのデータマイニングは、十番目のクラス『スレイヤー』、32要塞の陣営戦争、入れない寺院を示唆します。非公式であることを明示して紹介します。",
      intro: "毎回の Aion 2 パッチはデータマイニングの波を伴い、8月26日のアップデートも例外ではありませんでした。コミュニティは十番目のクラス『スレイヤー』、大規模陣営戦争、到達不能な寺院を発見。いずれも未発表のため、推測であることを強調して扱います。",
      sourceNote: "AION2T の8月26日データマイニング報告に基づきます。本記事の内容はすべて未確認・非公式の開発中コンテンツです。",
      keywords: ["Aion 2 十番目のクラス", "Aion 2 スレイヤー", "Aion 2 新クラス 2026", "Aion 2 陣営戦争", "Aion 2 データマイニング"],
      sections: [
        section("slayer", "十番目のクラス『スレイヤー』", "最初のスキル、投射物、滑空能力、そして既存クラスが使わない武器タイプが発見されました。武器タイプが核心のシグナルです。公式確認なし。"),
        section("rift-war", "時空裂け目支配（野の戦争）", "32要塞を中心とするオープンワールド陣営戦争のUIが発見されました。ロードマップの噂として扱ってください。"),
        section("temple", "まだ誰も入れない寺院", "6枚のダンジョンマップを持つアクセス不可エリア。大型インスタンス/レイドが今後のアップデートで準備されている可能性。"),
        section("other-finds", "その他の発見", "エルトネン・モルヘイムに2000以上の生物スポーン、未公開のショップ消費上限2件、ロックされたユニーク翼6つ。"),
        section("takeaway", "意味", "スレイヤーが出れば十番目の選択肢になります。32要塞戦争は確定時にオープンワールドエンドゲームを変えます。すべて推測であり、公式発表だけを信頼してください。"),
      ],
    }),
    fr: articleCopy(guideLabels, "fr", 5, {
      eyebrow: "DATAMINE — NON OFFICIEL",
      title: "La dixième classe d'Aion 2 : « Slayer » et ce que le datamining a trouvé (26 août)",
      description: "Le datamining de la mise à jour du 26 août évoque une dixième classe « Slayer », une guerre de faction à 32 forteresses et un temple inaccessible. Trouvailles clairement non officielles.",
      intro: "Chaque patch d'Aion 2 apporte son lot de datamining, et le 26 août n'a pas fait exception. Des références à une dixième classe « Slayer », un système de guerre de faction et un temple inaccessible ont été trouvées. Rien n'est officiel.",
      sourceNote: "Basé sur le datamining d'AION2T du 26 août. Tout est non confirmé, non officiel, en développement ; NC n'a rien annoncé.",
      keywords: ["Aion 2 dixième classe", "Aion 2 classe Slayer", "Aion 2 nouvelle classe 2026", "Aion 2 guerre de faction", "Aion 2 datamining"],
      sections: [
        section("slayer", "La dixième classe « Slayer »", "Un nom, un premier sort, un projectile, une capacité de glisse et — surtout — un type d'arme qu'aucune classe n'utilise. Aucune confirmation officielle."),
        section("rift-war", "Dominion de la faille spatio-temporelle", "Interface d'une guerre de faction en monde ouvert autour de 32 forteresses, codée dans le client. À traiter comme une rumeur."),
        section("temple", "Le temple inaccessible", "Six cartes de donjon pour une zone que personne ne peut rejoindre — contenu poussé avant son déblocage."),
        section("other-finds", "Autres trouvailles", "2 000+ points d'apparition à Eltnen et Morheim, deux plafonds de dépense inédits, six ailes Uniques verrouillées."),
        section("takeaway", "Ce que cela signifie", "Slayer deviendrait un dixième choix avec une nouvelle famille d'armes. Une guerre à 32 forteresses redessinerait l'endgame. Tout est spéculatif."),
      ],
    }),
    de: articleCopy(guideLabels, "de", 5, {
      eyebrow: "DATAMINE — INOFFIZIELL",
      title: "Die zehnte Klasse von Aion 2: „Slayer“ & was Datamining fand (26. August)",
      description: "Das Datamining vom 26. August deutet auf eine zehnte Klasse „Slayer“, einen Fraktionskrieg um 32 Festungen und einen unzugänglichen Tempel hin. Funde klar als inoffiziell markiert.",
      intro: "Jeder Aion-2-Patch bringt Datamining-Wellen, und das Update vom 26. August war keine Ausnahme. Gefunden wurden Hinweise auf eine zehnte Klasse „Slayer“, ein großes Fraktionskriegssystem und einen unerreichbaren Tempel. Nichts davon ist offiziell.",
      sourceNote: "Basierend auf dem Datamining-Bericht von AION2T vom 26. August. Alles hier ist unbestätigt, inoffiziell, in Entwicklung; NC hat nichts angekündigt.",
      keywords: ["Aion 2 zehnte Klasse", "Aion 2 Slayer-Klasse", "Aion 2 neue Klasse 2026", "Aion 2 Fraktionskrieg", "Aion 2 Datamining"],
      sections: [
        section("slayer", "Die zehnte Klasse „Slayer“", "Ein Name, ein erster Skill, ein Projektil, Gleiten und — entscheidend — eine Waffenart, die keine Klasse nutzt. Keine offizielle Bestätigung."),
        section("rift-war", "Spacetime-Rift-Domination", "UI eines Open-World-Fraktionskriegs um 32 Festungen, komplett im Client. Als Roadmap-Gerücht behandeln."),
        section("temple", "Der unzugängliche Tempel", "Sechs Dungeon-Karten für eine Zone, die niemand betreten kann — Inhalt vor seiner Freischaltung gepusht."),
        section("other-finds", "Weitere Funde", "2000+ Spawnpunkte in Eltnen und Morheim, zwei unenthüllte Shop-Obergrenzen, sechs gesperrte Unique-Flügel."),
        section("takeaway", "Was es bedeutet", "Slayer würde eine zehnte Option mit neuer Waffenfamilie. Ein 32-Festungs-Krieg würde den Open-World-Endgame umformen. Alles spekulativ."),
      ],
    }),
    es: articleCopy(guideLabels, "es", 5, {
      eyebrow: "DATAMINE — NO OFICIAL",
      title: "La décima clase de Aion 2: «Slayer» y lo que encontró el datamining (26 de agosto)",
      description: "El datamining de la actualización del 26 de agosto apunta a una décima clase «Slayer», una guerra de facciones de 32 fortalezas y un templo inaccesible. Hallazgos claramente no oficiales.",
      intro: "Cada parche de Aion 2 trae su oleada de datamining, y el del 26 de agosto no fue la excepción. Se hallaron referencias a una décima clase «Slayer», un sistema de guerra de facciones y un templo inaccesible. Nada es oficial.",
      sourceNote: "Basado en el datamining de AION2T del 26 de agosto. Todo es no confirmado, no oficial, en desarrollo; NC no ha anunciado nada.",
      keywords: ["Aion 2 décima clase", "Aion 2 clase Slayer", "Aion 2 nueva clase 2026", "Aion 2 guerra de facciones", "Aion 2 datamining"],
      sections: [
        section("slayer", "La décima clase «Slayer»", "Un nombre, una primera habilidad, un proyectil, planeo y —clave— un tipo de arma que ninguna clase usa. Sin confirmación oficial."),
        section("rift-war", "Dominio de la fisura espacio-temporal", "UI de una guerra de facciones en mundo abierto alrededor de 32 fortalezas, codificada en el cliente. Trátalo como rumor."),
        section("temple", "El templo inaccesible", "Seis mapas de mazmorra para una zona que nadie puede alcanzar — contenido adelantado a su desbloqueo."),
        section("other-finds", "Otros hallazgos", "Más de 2000 puntos de aparición en Eltnen y Morheim, dos topes de gasto inéditos, seis alas Únicas bloqueadas."),
        section("takeaway", "Qué significa", "Slayer sería una décima opción con nueva familia de armas. Una guerra de 32 fortalezas remodelaría el endgame. Todo es especulativo."),
      ],
    }),
    "pt-br": articleCopy(guideLabels, "pt-br", 5, {
      eyebrow: "DATAMINE — NÃO OFICIAL",
      title: "A décima classe do Aion 2: «Slayer» e o que o datamining encontrou (26 de agosto)",
      description: "O datamining da atualização de 26 de agosto aponta para uma décima classe «Slayer», uma guerra de facções de 32 fortalezas e um templo inacessível. Achados claramente não oficiais.",
      intro: "Todo patch do Aion 2 traz sua onda de datamining, e o de 26 de agosto não foi exceção. Encontrou-se referências a uma décima classe «Slayer», um sistema de guerra de facções e um templo inacessível. Nada é oficial.",
      sourceNote: "Baseado no datamining da AION2T de 26 de agosto. Tudo é não confirmado, não oficial, em desenvolvimento; a NC não anunciou nada.",
      keywords: ["Aion 2 décima classe", "Aion 2 classe Slayer", "Aion 2 nova classe 2026", "Aion 2 guerra de facções", "Aion 2 datamining"],
      sections: [
        section("slayer", "A décima classe «Slayer»", "Um nome, uma primeira habilidade, um projétil, planagem e —crucial— um tipo de arma que nenhuma classe usa. Sem confirmação oficial."),
        section("rift-war", "Domínio da fenda espaço-temporal", "UI de uma guerra de facções em mundo aberto em torno de 32 fortalezas, codificada no cliente. Trate como boato."),
        section("temple", "O templo inacessível", "Seis mapas de masmorra para uma zona que ninguém pode alcançar — conteúdo adiantado ao seu desbloqueio."),
        section("other-finds", "Outros achados", "Mais de 2000 pontos de aparição em Eltnen e Morheim, dois tetos de gasto inéditos, seis asas Únicas bloqueadas."),
        section("takeaway", "O que significa", "Slayer seria uma décima opção com nova família de armas. Uma guerra de 32 fortalezas remodelaria o endgame. Tudo é especulativo."),
      ],
    }),
    ru: articleCopy(guideLabels, "ru", 5, {
      eyebrow: "ДАТАМАЙНИНГ — НЕОФИЦИАЛЬНО",
      title: "Десятый класс Aion 2: «Слэер» и что нашёл датамайнинг (26 августа)",
      description: "Датамайнинг обновления от 26 августа указывает на десятый класс «Слэер», войну фракций вокруг 32 крепостей и недоступный храм. Находки явно неофициальные.",
      intro: "Каждый патч Aion 2 приносит волну датамайнинга, и обновление от 26 августа не стало исключением. Найдены отсылки к десятому классу «Слэер», системе фракционной войны и недоступному храму. Ничего официального.",
      sourceNote: "На основе отчёта датамайнинга AION2T от 26 августа. Всё здесь неподтверждённо, неофициально, в разработке; NC ничего не анонсировала.",
      keywords: ["Aion 2 десятый класс", "Aion 2 класс Слэер", "Aion 2 новый класс 2026", "Aion 2 война фракций", "Aion 2 датамайнинг"],
      sections: [
        section("slayer", "Десятый класс «Слэер»", "Имя, первый навык, снаряд, планирование и — ключевое — тип оружия, который не использует ни один класс. Без официального подтверждения."),
        section("rift-war", "Господство пространственно-временного разлома", "UI открытой фракционной войны вокруг 32 крепостей, полностью в клиенте. Считайте слухом."),
        section("temple", "Недоступный храм", "Шесть карт данжа для зоны, куда никто не может попасть — контент, завезённый до разблокировки."),
        section("other-finds", "Другие находки", "2000+ точек спавна в Эльтнене и Морхейме, два нераскрытых лимита трат в магазине, шесть заблокированных Уникальных крыльев."),
        section("takeaway", "Что это значит", "Слэер стал бы десятым вариантом с новой семьёй оружия. Война на 32 крепости перестроила бы эндгейм. Всё спекулятивно."),
      ],
    }),
    "zh-hant": articleCopy(guideLabels, "zh-hant", 5, {
      eyebrow: "資料挖掘——非官方",
      title: "Aion 2 第十職業『Slayer』與資料挖掘發現（8月26日）",
      description: "對 8 月 26 日更新的資料挖掘指向第十個職業『Slayer』、32 要塞陣營戰爭與一座無法進入的寺廟。以下為發現內容，均明確標註為非官方。",
      intro: "每次 Aion 2 修補程式都伴隨一輪資料挖掘，8 月 26 日更新也不例外。社群挖掘者發現第十個職業『Slayer』的引用，以及大規模陣營戰爭系統與一座不可達寺廟。以上均未官方公布，本指南將此警告放在最前。",
      sourceNote: "基於 AION2T 8 月 26 日資料挖掘報告。本文全部內容為未確認、非官方的開發中內容；NC 未公布任何一項，請一律視為推測。",
      keywords: ["Aion 2 第十職業", "Aion 2 Slayer 職業", "Aion 2 新職業 2026", "Aion 2 陣營戰爭", "Aion 2 資料挖掘"],
      sections: [
        section("slayer", "第十職業『Slayer』", ["挖掘者發現名為『Slayer』（殺手）的第十職業引用，包含首個技能、投射物、滑翔能力，以及——關鍵——一個現有職業均未使用的武器類型。", "『新武器類型』是最有趣訊號：Aion 2 職業由武器與定位共同定義。", "以上均無官方確認。"]),
        section("rift-war", "時空裂縫支配（田野之戰）", ["與職業一同，挖掘者發現『時空裂縫支配』的介面——圍繞 32 座要塞的開放世界陣營戰爭，UI 已完整寫入用戶端。", "若屬實，這是大規模開放世界 PvPvE 結構。", "請視為路線圖傳聞，待 NC 確認。"]),
        section("temple", "無人能進入的寺廟", ["挖掘還標記了六張『寺廟』房間的地下城地圖，當前建置中無任何玩家可進入。", "一個區域六張地圖暗示大型實例副本或團隊本正在排期。", "預計被後續修補程式解鎖。"]),
        section("other-finds", "修補程式中的其他發現", ["Eltnen 與 Morheim 新增 2000+ 生物刷新點（尚無屬性）、兩項未公布的商城消費上限、六件上鎖的 Unique 翅膀。", "以上均未公布，僅作早期訊號。"]),
        section("takeaway", "意義", ["職業玩家：若 Slayer 上線，將成為需要權衡的第十選項。", "版本/PvP 玩家：32 要塞田野之戰若確認，將重塑開放世界終局。", "最重要：視本頁為推測。只有官方公告才應改變你的決策。"]),
      ],
    }),
  },
};