import { articleCopy, localizations, newsLabels, publishedVerified, section } from "./trending-august-29-shared";
import type { ContentEntry, ContentHeroImage, ContentSource } from "./content-registry";

/* ARTICLE 5 — Japan official hub is live; August 28 livestream today */

const jpSource1: ContentSource = {
  id: "nc-jp-special-site-2026-08-29",
  kind: "official", publisher: "NC",
  label: "AION 2 Official Site (Japan) — Launch Confirmed: October 5, LST & Live Broadcast",
  url: "https://aion2.ncsoft.jp/ja/contents",
  publishedAt: "2026-08-01",
  retrievedAt: "2026-08-28",
  verifiedAt: "2026-08-28",
  localizations: localizations({
    "zh-hans": "AION 2 官方网站（日本）——上线确认 10 月 5 日、LST 与生放送",
    en: "AION 2 Official Site (Japan) — Launch Confirmed: October 5, LST & Live Broadcast",
    fr: "Site officiel AION 2 (Japon) — sortie confirmée le 5 octobre, LST et émission en direct",
    de: "AION 2 Offizielle Website (Japan) — Start bestätigt: 5. Oktober, LST & Live-Sendung",
    es: "Sitio oficial de AION 2 (Japón) — lanzamiento confirmado el 5 de octubre, LST y transmisión en vivo",
    ja: "AION 2 公式サイト（日本）— 正式サービス決定：10月5日、LST・生放送情報",
    "pt-br": "Site oficial do AION 2 (Japão) — lançamento confirmado em 5 de outubro, LST e transmissão ao vivo",
    ru: "Официальный сайт AION 2 (Япония) — запуск подтверждён 5 октября, LST и прямой эфир",
    ko: "Aion 2 공식 사이트 (일본) — 출시 확정 10월 5일, LST·생방송 정보",
    "zh-hant": "AION 2 官方網站（日本）——上線確認 10 月 5 日、LST 與生放送",
  }, "https://aion2.ncsoft.jp/ja/contents"),
};

const jpSource2: ContentSource = {
  id: "nc-jp-notice-board-2026-08-29",
  kind: "official", publisher: "NC",
  label: "AION 2 Official Notices (Japan) — News & Schedule Board",
  url: "https://aion2.plaync.com/ja-jp/board/notice/list",
  publishedAt: "2026-08-01",
  retrievedAt: "2026-08-28",
  verifiedAt: "2026-08-28",
  localizations: localizations({
    "zh-hans": "AION 2 官方公告（日本）——新闻与日程板",
    en: "AION 2 Official Notices (Japan) — News & Schedule Board",
    fr: "Annonces officielles AION 2 (Japon) — actualités et calendrier",
    de: "AION 2 Offizielle Ankündigungen (Japan) — News & Zeitplan",
    es: "Avisos oficiales de AION 2 (Japón) — noticias y calendario",
    ja: "AION 2 公式お知らせ（日本）— ニュース＆スケジュール掲示板",
    "pt-br": "Avisos oficiais do AION 2 (Japão) — notícias e calendário",
    ru: "Официальные объявления AION 2 (Япония) — новости и расписание",
    ko: "Aion 2 공식 공지 (일본) — 뉴스 & 일정 게시판",
    "zh-hant": "AION 2 官方公告（日本）——新聞與行程板",
  }, "https://aion2.plaync.com/ja-jp/board/notice/list"),
};

const jpHero: ContentHeroImage = {
  src: "https://blogfiles.ncsoft.net/news/af7330da-4ff6-4b58-aece-400e6061a3be.jpg",
  width: 1100, height: 605,
  credit: "NC Corporation",
  sourceUrl: "https://aion2.plaync.com/ja-jp/board/notice/list",
  rights: "linked-official-media",
  translations: {
    "zh-hans": { alt: "Aion 2 日本官方生放送报道配图", caption: "NC 官方配图；Aion 2 日本官方特别页已上线，生放送定于 8 月 28 日（周五）20:00 JST，正式服务确认自 2026 年 10 月 5 日开始。" },
    en: { alt: "Aion 2 Japan official livestream report image", caption: "Official NC artwork; the Aion 2 Japan official special site is live, the live broadcast airs today August 28 (Fri) at 20:00 JST, and official service is confirmed from October 5, 2026." },
    fr: { alt: "Image du report sur l'émission en direct officielle japonaise d'Aion 2", caption: "Visuel officiel NC ; le site spécial japonais est en ligne, l'émission en direct aura lieu le 28 août à 20:00 JST, service officiel confirmé au 5 octobre 2026." },
    de: { alt: "Bild zum offiziellen japanischen Livestream-Report von Aion 2", caption: "Offizielles NC-Artwork; die japanische offizielle Spezialseite ist live, die Live-Sendung läuft heute, 28. August 20:00 JST, offizieller Start am 5. Oktober 2026." },
    es: { alt: "Imagen del reporte del livestream oficial japonés de Aion 2", caption: "Arte oficial de NC; el sitio especial japonés está en vivo, la transmisión será el 28 de agosto a las 20:00 JST y el servicio oficial se confirma para el 5 de octubre de 2026." },
    ja: { alt: "Aion 2 日本公式生放送レポート画像", caption: "NC公式アートワーク；Aion 2 日本公式特設サイトが公開され、生放送は本日8月28日（金）20:00 JST、正式サービスは2026年10月5日から確定です。" },
    "pt-br": { alt: "Imagem do relatório do livestream oficial japonês do Aion 2", caption: "Arte oficial da NC; o site especial japonês está no ar, a transmissão ao vivo acontece hoje 28 de agosto às 20:00 JST e o serviço oficial é confirmado para 5 de outubro de 2026." },
    ru: { alt: "Изображение отчёта о японском официальном эфире Aion 2", caption: "Официальный арт NC; японский официальный спецсайт запущен, прямой эфир сегодня 28 августа в 20:00 JST, официальный запуск подтверждён с 5 октября 2026." },
    ko: { alt: "Aion 2 일본 공식 생방송 리포트 이미지", caption: "NC 공식 이미지입니다. Aion 2 일본 공식 특설 사이트가 공개됐고, 생방송은 오늘 8월 28일(금) 20:00 JST, 정식 서비스는 2026년 10월 5일부터 확정입니다." },
    "zh-hant": { alt: "Aion 2 日本官方生放送報導配圖", caption: "NC 官方配圖；Aion 2 日本官方特別頁已上線，生放送定於 8 月 28 日（週五）20:00 JST，正式服務確認自 2026 年 10 月 5 日開始。" },
  },
};

export const trendingAugust29Article5: ContentEntry = {
  section: "news",
  slug: "aion-2-japan-livestream-august-28-2026",
  schemaType: "NewsArticle",
  publishedAt: "2026-08-28",
  updatedAt: "2026-08-28",
  readingMinutes: 4,
  publication: publishedVerified,
  sources: [jpSource1, jpSource2],
  heroImage: jpHero,
  related: [
    { kind: "content", section: "news", slug: "aion-2-release-date-october-5-2026" },
    { kind: "content", section: "guides", slug: "aion-2-global-version-changes-guide" },
    { kind: "content", section: "guides", slug: "aion-2-steam-release-guide" },
    { kind: "content", section: "guides", slug: "aion-2-pre-launch-checklist" },
  ],
  translations: {
    en: articleCopy(newsLabels, "en", 4, {
      eyebrow: "JP OFFICIAL HUB + LIVESTREAM",
      title: "Aion 2 Japan: Official Special Site Live, August 28 Livestream Today at 20:00 JST",
      description: "The Aion 2 Japan official special site is up, confirming official service from October 5 and Japan-specific Launch Scale Test times. Today's August 28 livestream at 20:00 JST is the next milestone to watch.",
      intro: "Aion 2's Japan marketing engine has shifted into launch gear. The dedicated Japanese special site now confirms official service from October 5, 2026, carries the Japan times for the September 17–18 Launch Scale Test, and lists a live broadcast for today, August 28 at 20:00 JST. This report summarizes what the Japanese hub confirms, what the stream is expected to cover, and what Japanese players should do next.",
      sourceNote: "Based on the AION 2 Japan official special site (aion2.ncsoft.jp) and the official Japanese notice board, both fetched on August 28, 2026.",
      keywords: ["Aion 2 Japan livestream", "Aion 2 8月28日 生放送", "Aion 2 Japan release October 5", "Aion 2 正式サービス 10月5日", "Aion 2 Japan Launch Scale Test"],
      sections: [
        section("site", "The Japan Special Site Is Live", ["The dedicated Japanese portal (aion2.ncsoft.jp/ja/contents) now confirms 正式サービス決定 (official service decided) for October 5, 2026 — aligning Japan with the global window announced at Gamescom.", "Pre-registration has been running since June 6, and Founder's Packs have been on sale since July 22 with the 5-day early access and 30-day membership included — Japan participates in the September 30 early access window.", "The site also lists the four starting Expeditions (4-player dungeons) — クラオ洞窟, ウルググ峡谷, 炎の神殿, ドラウプニル — giving Japanese players a concrete view of the opening content."]),
        section("lst-jp", "Japan Times for the Launch Scale Test", ["The September 17–18 Launch Scale Test has Japan-specific windows on the official site: pre-download from September 16 at 22:00 JST, Day 1 on September 17 from 22:00 JST to September 18 at 04:00 JST, and Day 2 on September 19 from 04:00 to 10:00 JST.", "The test has no entry requirements for Japanese players — same open, keyless format as the global announcement, on Steam and PURPLE.", "These times mirror the global windows converted to JST; use the LST guide on this site for the full list of limitations (level cap 37, no shop, progression wiped)."]),
        section("stream", "Today's Livestream: August 28, 20:00 JST", ["The official site lists a live broadcast for today, Friday August 28 at 20:00 JST on YouTube — the first broadcast since the Gamescom week.", "Based on the launch cadence, expect the stream to walk through launch preparation: more founder-pack details, LST participation steps, and possibly fresh gameplay or trailer material feeding the final push to September 30.", "Japan is at 20:00 JST / 13:00 CEST / 04:00 PDT — European players should time-shift accordingly if they want to catch it live."]),
        section("whats-next", "What Japanese Players Should Do", ["Pre-register if you have not, decide on a Founder's Pack before early access opens on September 30, and join the LST on September 17–18 to lock in your client install and settings.", "Follow the official notice board (aion2.plaync.com/ja-jp/board/notice/list) — the September maintenance schedule and the Advanced Access client download will be announced there first.", "Keep the local version-changes guide handy: the KR/TW updates (Great Rebalance, server transfers) preview the tuning Japan and the global version will receive at launch."]),
        section("timing", "Timing Note", ["This report publishes on August 28, ahead of or around the 20:00 JST stream depending on your timezone. If you are reading after the stream, check the official site's archive link for the VOD and our next batch for the recap.", "We will update this article with confirmed stream highlights once NC publishes the VOD and any follow-up announcements."]),
      ],
    }),
    "zh-hans": articleCopy(newsLabels, "zh-hans", 4, {
      eyebrow: "JP 官方枢纽 + 生放送",
      title: "Aion 2 日本：官方特别页上线，8 月 28 日 20:00 JST 生放送今晚播出",
      description: "Aion 2 日本官方特别页上线，确认正式服务自 10 月 5 日开始，并给出日本适用的上线规模测试时间。今晚 8 月 28 日 20:00 JST 的生放送是下一个节点。",
      intro: "Aion 2 的日本宣发已进入上线档期：专属日文特别页确认正式服务自 2026 年 10 月 5 日开始，列出 9 月 17-18 日上线规模测试的日本时间，并预告今天 8 月 28 日 20:00 JST 的生放送。本报道汇总日本枢纽确认的内容、生放送预期话题，以及日本玩家接下来要做的事。",
      sourceNote: "基于 2026 年 8 月 28 日抓取的 AION 2 日本官方特别页（aion2.ncsoft.jp）与日本官方公告板。",
      keywords: ["Aion 2 日本生放送", "Aion 2 8月28日 生放送", "Aion 2 日本10月5日上线", "Aion 2 正式服务 10月5日", "Aion 2 日本上线规模测试"],
      sections: [
        section("site", "日本特别页已上线", ["专属日文门户（aion2.ncsoft.jp/ja/contents）确认『正式服务决定』为 2026 年 10 月 5 日——与 Gamescom 公布的全球窗口一致。", "事前登录自 6 月 6 日起持续，创始人包自 7 月 22 日起贩售（含 5 天抢先体验与 30 天会员）——日本参与 9 月 30 日抢先体验窗口。", "页面还列出四个起始远征（4 人副本）——クラオ洞窟、ウルググ峡谷、炎の神殿、ドラウプニル——给出开篇内容的具象视图。"]),
        section("lst-jp", "上线规模测试的日本时间", ["9 月 17-18 日 LST 在官方页有日本专属时间：9 月 16 日 22:00 JST 起预载，第 1 天 9 月 17 日 22:00 JST 至 9 月 18 日 04:00 JST，第 2 天 9 月 19 日 04:00-10:00 JST。", "日本玩家无任何入场条件——与全球公告一致的全开放、免密钥形式，覆盖 Steam 与 PURPLE。", "这些时间即全球窗口的 JST 转换；完整限制清单（等级上限 37、无商店、进度清空）见站内 LST 指南。"]),
        section("stream", "今晚生放送：8 月 28 日 20:00 JST", ["官方页预告今天周五 8 月 28 日 20:00 JST 于 YouTube 播出生放送——Gamescom 周后的首次。", "按上线节奏推断，节目将围绕上线准备展开：更多创始人包细节、LST 参加步骤，乃至冲击 9 月 30 日的新实机或预告物料。", "日本时间 20:00 JST = 13:00 CEST = 04:00 PDT——欧洲玩家如需收看请自行换算时间。"]),
        section("whats-next", "日本玩家接下来要做的事", ["尚未预登录的请预登录；9 月 30 日抢先体验开放前决定创始人包；参加 9 月 17-18 日 LST 以锁定客户端安装与设置。", "关注官方公告板（aion2.plaync.com/ja-jp/board/notice/list）——9 月维护计划与抢先体验客户端下载将首先在此公布。", "备好站内本地版本变动指南：韩/台更新（大平衡、服务器转移）预览日本与全球版上线时将获得的调校。"]),
        section("timing", "时间说明", ["本报道 8 月 28 日发布，视时区而定在 20:00 JST 直播前或前后。若你在直播后阅读，请访问官网存档链接查看回放，并留意下一批次的重播整理。", "NC 发布 VOD 与后续公告后，本文将更新已确认的直播亮点。"]),
      ],
    }),
    ko: articleCopy(newsLabels, "ko", 4, {
      eyebrow: "일본 공식 허브 + 생방송",
      title: "Aion 2 일본: 공식 특설 사이트 공개, 8월 28일 20:00 JST 생방송 오늘 방송",
      description: "Aion 2 일본 공식 특설 사이트가 공개되며 정식 서비스가 10월 5일부터 시작됨을 확인하고, 출시 규모 테스트 일본 시간을 안내합니다. 오늘 8월 28일 20:00 JST 생방송이 다음 마일스톤입니다.",
      intro: "Aion 2의 일본 홍보가 출시 기어로 전환됐습니다. 전용 일본 특설 사이트는 2026년 10월 5일부터 정식 서비스를 확정하고, 9월 17~18일 출시 규모 테스트(LST)의 일본 시간을 안내하며, 오늘 8월 28일 20:00 JST 생방송을 예고합니다.",
      sourceNote: "2026년 8월 28일 확인한 Aion 2 일본 공식 특설 사이트(aion2.ncsoft.jp)와 일본 공식 공지 게시판 기반.",
      keywords: ["Aion 2 일본 생방송", "Aion 2 8월 28일 생방송", "Aion 2 일본 10월 5일 출시", "Aion 2 정식 서비스 10월 5일", "Aion 2 일본 출시 규모 테스트"],
      sections: [
        section("site", "일본 특설 사이트 공개", "일본 포털이 정식 서비스 10월 5일을 확정. 사전 등록 6월 6일부터, 파운더스 팩 7월 22일부터(5일 조기 접속+30일 멤버십). 시작 원정 4종: 클라오 동굴, 우르그그 협곡, 불의 사원, 드라우프니르."),
        section("lst-jp", "LST 일본 시간", "9월 16일 22:00 JST 사전 다운로드, 1일차 9월 17일 22:00~9월 18일 04:00 JST, 2일차 9월 19일 04:00~10:00 JST. 입장 조건 없음, Steam·PURPLE 모두 가능."),
        section("stream", "오늘 생방송: 8월 28일 20:00 JST", "게임스컴 주 이후 첫 생방송이 오늘 20:00 JST에 YouTube로 방송됩니다. 출시 준비(파운더스 팩, LST 참여, 신규 영상)를 다룰 것으로 예상합니다. 20:00 JST = 13:00 CEST = 04:00 PDT."),
        section("whats-next", "일본 플레이어의 다음 단계", "사전 등록, 파운더스 팩 결정, 9월 17~18일 LST 참여로 클라이언트 설치를 확정하세요. 공식 공지 게시판(aion2.plaync.com/ja-jp/board/notice/list)에서 9월 일정을 확인하세요."),
        section("timing", "시간 안내", "본 보고는 8월 28일 발행되며 시점에 따라 방송 전후일 수 있습니다. 방송 후에는 VOD와 다음 배치 요약을 확인하세요."),
      ],
    }),
    ja: articleCopy(newsLabels, "ja", 4, {
      eyebrow: "日本公式ハブ＋生放送",
      title: "Aion 2 日本：公式特設サイト公開、8月28日20:00 JST 生放送を今夜配信",
      description: "Aion 2 日本公式特設サイトが公開され、正式サービスが10月5日から始まることを確認し、日本向けローンチスケールテスト時間を案内します。今夜8月28日20:00 JSTの生放送が次の節目です。",
      intro: "Aion 2 の日本プロモーションはローンチ体制に入りました。専用日本語特設サイトは2026年10月5日からの正式サービスを確定し、9月17日〜18日のローンチスケールテスト（LST）の日本時間を掲載し、本日8月28日20:00 JSTの生放送を予告しています。",
      sourceNote: "2026年8月28日に確認した Aion 2 日本公式特設サイト（aion2.ncsoft.jp）と日本公式お知らせ掲示板に基づきます。",
      keywords: ["Aion 2 日本生放送", "Aion 2 8月28日 生放送", "Aion 2 日本10月5日 正式サービス", "Aion 2 LST 日本", "Aion 2 事前登録"],
      sections: [
        section("site", "日本特設サイト公開", "日本語ポータルが正式サービスを10月5日に確定。事前登録は6月6日から、ファウンダーズパックは7月22日から販売中（5日間アーリーアクセス＋30日メンバーシップ）。開始遠征4種：クラオ洞窟、ウルググ峡谷、炎の神殿、ドラウプニル。"),
        section("lst-jp", "LSTの日本時間", "9月16日22:00 JSTから事前DL、1日目9月17日22:00 JST〜9月18日04:00 JST、2日目9月19日04:00〜10:00 JST。参加条件なしでSteam・PURPLEの両方が対象です。"),
        section("stream", "今夜の生放送：8月28日20:00 JST", "ゲームズコム週以来初の生放送が本日20:00 JSTにYouTubeで放送されます。ローンチ準備（パック詳細、LST参加手順、新映像）が中心になると予想されます。20:00 JST＝13:00 CEST＝04:00 PDT。"),
        section("whats-next", "日本のプレイヤーがすべきこと", "事前登録、ファウンダーズパックの判断、9月17日〜18日のLST参加でクライアントを確定させてください。公式お知らせ掲示板（aion2.plaync.com/ja-jp/board/notice/list）で9月のメンテ予定を確認しましょう。"),
        section("timing", "時間の説明", "本記事は8月28日発行で、時間帯により20:00 JST放送の前後になります。放送後に読む場合はVODと次回バッチのまとめを確認してください。"),
      ],
    }),
    fr: articleCopy(newsLabels, "fr", 4, {
      eyebrow: "HUB OFFICIEL JP + LIVE",
      title: "Aion 2 Japon : site officiel en ligne, émission en direct le 28 août à 20:00 JST",
      description: "Le site spécial japonais d'Aion 2 confirme le service officiel à partir du 5 octobre et les heures japonaises du test à grande échelle. L'émission en direct de ce soir 28 août à 20:00 JST est le prochain jalon.",
      intro: "La promotion japonaise d'Aion 2 passe en mode lancement : le site spécial confirme le service officiel au 5 octobre 2026, donne les heures japonaises du LST (17-18 septembre) et annonce une émission en direct aujourd'hui, 28 août à 20:00 JST.",
      sourceNote: "Basé sur le site officiel japonais (aion2.ncsoft.jp) et le tableau d'annonces officiel, consultés le 28 août 2026.",
      keywords: ["Aion 2 livestream Japon", "Aion 2 8月28日 生放送", "Aion 2 sortie Japon 5 octobre", "Aion 2 test Japon"],
      sections: [
        section("site", "Le site spécial japonais est en ligne", "Service officiel confirmé au 5 octobre 2026, aligné sur la fenêtre mondiale. Préinscription depuis le 6 juin ; packs Fondateur depuis le 22 juillet (5 jours d'accès anticipé + 30 jours de membre). Quatre expéditions de départ listées."),
        section("lst-jp", "Heures japonaises du LST", "Préchargement le 16 septembre à 22:00 JST ; Jour 1 le 17 septembre 22:00–04:00 JST ; Jour 2 le 19 septembre 04:00–10:00 JST. Sans condition d'entrée, sur Steam et PURPLE."),
        section("stream", "Émission de ce soir", "L'émission du 28 août à 20:00 JST sur YouTube couvrira probablement la préparation au lancement : packs, LST, nouvelles images. Vérifiez votre fuseau : 20:00 JST = 13:00 CEST = 04:00 PDT."),
        section("whats-next", "À faire pour les joueurs JP", "Préinscription, décision pack Fondateur, participation au LST du 17-18 septembre pour installer le client. Suivez le tableau d'annonces officiel pour les maintenances de septembre."),
        section("timing", "Note de timing", "Publie le 28 août, avant ou aux alentours du direct selon votre fuseau. Après le direct, consultez le VOD et notre prochain récap."),
      ],
    }),
    de: articleCopy(newsLabels, "de", 4, {
      eyebrow: "JP-OFFIZIELLER HUB + LIVE",
      title: "Aion 2 Japan: Offizielle Spezialseite live, Livestream heute um 20:00 JST",
      description: "Die japanische Spezialseite von Aion 2 bestätigt den offiziellen Start am 5. Oktober und die japanischen Zeiten des Launch Scale Tests. Der Livestream heute, 28. August um 20:00 JST, ist der nächste Meilenstein.",
      intro: "Die japanische Vermarktung von Aion 2 geht in den Launch-Modus: Die Spezialseite bestätigt den offiziellen Start am 5. Oktober 2026, nennt die japanischen Zeiten des LST (17.–18. September) und kündigt einen Livestream für heute, 28. August um 20:00 JST an.",
      sourceNote: "Basierend auf der japanischen offiziellen Website (aion2.ncsoft.jp) und dem offiziellen Ankündigungsboard, abgerufen am 28. August 2026.",
      keywords: ["Aion 2 Japan Livestream", "Aion 2 8月28日 生放送", "Aion 2 Japan Start 5. Oktober", "Aion 2 Japan LST"],
      sections: [
        section("site", "Spezialseite ist live", "Offizieller Start am 5. Oktober 2026 bestätigt. Vorregistrierung seit 6. Juni; Founder's Packs seit 22. Juli (5 Tage Early Access + 30 Tage Mitgliedschaft). Vier Start-Expeditionen gelistet."),
        section("lst-jp", "Japanische LST-Zeiten", "Vorabdownload 16. September 22:00 JST; Tag 1 am 17. September 22:00–04:00 JST; Tag 2 am 19. September 04:00–10:00 JST. Ohne Bedingungen, auf Steam und PURPLE."),
        section("stream", "Livestream heute Abend", "Die Sendung um 20:00 JST auf YouTube behandelt voraussichtlich Launch-Vorbereitung: Packs, LST-Teilnahme, neues Material. Zeitzone beachten: 20:00 JST = 13:00 CEST = 04:00 PDT."),
        section("whats-next", "Nächste Schritte für JP-Spieler", "Vorregistrierung, Pack-Entscheidung, LST-Teilnahme (17.–18. September) zur Client-Installation. Offizielles Board für September-Wartungen verfolgen."),
        section("timing", "Timing-Hinweis", "Veröffentlicht am 28. August, je nach Zeitzone vor oder um den Stream herum. Nach dem Stream: VOD und nächster Batch-Recap beachten."),
      ],
    }),
    es: articleCopy(newsLabels, "es", 4, {
      eyebrow: "HUB OFICIAL JP + EN DIRECTO",
      title: "Aion 2 Japón: sitio oficial activo, transmisión en vivo el 28 de agosto a las 20:00 JST",
      description: "El sitio especial japonés de Aion 2 confirma el servicio oficial a partir del 5 de octubre y las horas japonesas de la prueba de escala. La transmisión de esta noche a las 20:00 JST es el próximo hito.",
      intro: "La promoción japonesa de Aion 2 entra en modo lanzamiento: el sitio especial confirma el servicio oficial para el 5 de octubre de 2026, da las horas japonesas del LST (17-18 de septiembre) y anuncia una transmisión en vivo hoy, 28 de agosto a las 20:00 JST.",
      sourceNote: "Basado en el sitio oficial japonés (aion2.ncsoft.jp) y el tablón oficial, consultados el 28 de agosto de 2026.",
      keywords: ["Aion 2 livestream Japón", "Aion 2 8月28日 生放送", "Aion 2 lanzamiento Japón 5 octubre", "Aion 2 LST Japón"],
      sections: [
        section("site", "El sitio especial japonés está activo", "Servicio oficial confirmado para el 5 de octubre de 2026. Preinscripción desde el 6 de junio; packs de fundador desde el 22 de julio (5 días de acceso anticipado + 30 días de membresía). Cuatro expediciones iniciales listadas."),
        section("lst-jp", "Horas japonesas del LST", "Precarga el 16 de septiembre a las 22:00 JST; día 1 el 17 de septiembre 22:00-04:00 JST; día 2 el 19 de septiembre 04:00-10:00 JST. Sin condiciones, en Steam y PURPLE."),
        section("stream", "Transmisión de esta noche", "La emisión a las 20:00 JST en YouTube tratará presumiblemente la preparación al lanzamiento: packs, pasos del LST, material nuevo. Zona horaria: 20:00 JST = 13:00 CEST = 04:00 PDT."),
        section("whats-next", "Próximos pasos para jugadores JP", "Preinscripción, decisión de pack, participación en el LST del 17-18 de septiembre para instalar el cliente. Seguir el tablón oficial para los mantenimientos de septiembre."),
        section("timing", "Nota de horario", "Publica el 28 de agosto, antes o alrededor del directo según tu zona. Tras el directo, consulta la VOD y nuestro próximo resumen."),
      ],
    }),
    "pt-br": articleCopy(newsLabels, "pt-br", 4, {
      eyebrow: "HUB OFICIAL JP + AO VIVO",
      title: "Aion 2 Japão: site oficial no ar, transmissão ao vivo em 28 de agosto às 20:00 JST",
      description: "O site especial japonês do Aion 2 confirma o serviço oficial a partir de 5 de outubro e os horários japoneses do teste de escala. A transmissão de hoje às 20:00 JST é o próximo marco.",
      intro: "A promoção japonesa do Aion 2 entra em modo lançamento: o site especial confirma o serviço oficial para 5 de outubro de 2026, dá os horários japoneses do LST (17-18 de setembro) e anuncia uma transmissão ao vivo hoje, 28 de agosto às 20:00 JST.",
      sourceNote: "Com base no site oficial japonês (aion2.ncsoft.jp) e no quadro oficial, consultados em 28 de agosto de 2026.",
      keywords: ["Aion 2 livestream Japão", "Aion 2 8月28日 生放送", "Aion 2 lançamento Japão 5 outubro", "Aion 2 LST Japão"],
      sections: [
        section("site", "O site especial japonês está no ar", "Serviço oficial confirmado para 5 de outubro de 2026. Pré-registro desde 6 de junho; pacotes de fundador desde 22 de julho (5 dias de acesso antecipado + 30 dias de assinatura). Quatro expedições iniciais listadas."),
        section("lst-jp", "Horários japoneses do LST", "Pré-download em 16 de setembro às 22:00 JST; dia 1 em 17 de setembro 22:00-04:00 JST; dia 2 em 19 de setembro 04:00-10:00 JST. Sem condições, na Steam e PURPLE."),
        section("stream", "Transmissão de hoje", "A emissão às 20:00 JST no YouTube tratará provavelmente da preparação para o lançamento: pacotes, passos do LST, novo material. Fuso: 20:00 JST = 13:00 CEST = 04:00 PDT."),
        section("whats-next", "Próximos passos para jogadores JP", "Pré-registro, decisão de pacote, participação no LST de 17-18 de setembro para instalar o cliente. Acompanhar o quadro oficial para as manutenções de setembro."),
        section("timing", "Nota de horário", "Publica em 28 de agosto, antes ou em torno do ao vivo conforme seu fuso. Após o ao vivo, consulte a VOD e nosso próximo resumo."),
      ],
    }),
    ru: articleCopy(newsLabels, "ru", 4, {
      eyebrow: "ОФИЦИАЛЬНЫЙ ХАБ JP + ЭФИР",
      title: "Aion 2 Япония: официальный сайт запущен, прямой эфир 28 августа в 20:00 JST",
      description: "Японский специальный сайт Aion 2 подтверждает официальный запуск с 5 октября и японские времена масштабного теста. Прямой эфир сегодня, 28 августа в 20:00 JST — следующая веха.",
      intro: "Японское продвижение Aion 2 входит в режим запуска: спецсайт подтверждает официальный запуск 5 октября 2026, даёт японские времена LST (17–18 сентября) и анонсирует прямой эфир сегодня, 28 августа в 20:00 JST.",
      sourceNote: "На основе японского официального сайта (aion2.ncsoft.jp) и официальной доски, полученных 28 августа 2026.",
      keywords: ["Aion 2 лайвстрим Япония", "Aion 2 8月28日 生放送", "Aion 2 запуск Япония 5 октября", "Aion 2 LST Япония"],
      sections: [
        section("site", "Японский спецсайт запущен", "Официальный запуск подтверждён на 5 октября 2026. Предрегистрация с 6 июня; наборы основателя с 22 июля (5 дней раннего доступа + 30 дней членства). Четыре стартовые экспедиции."),
        section("lst-jp", "Японские времена LST", "Предзагрузка 16 сентября в 22:00 JST; день 1 — 17 сентября 22:00–04:00 JST; день 2 — 19 сентября 04:00–10:00 JST. Без условий, в Steam и PURPLE."),
        section("stream", "Эфир сегодня вечером", "Трансляция в 20:00 JST на YouTube, вероятно, о подготовке к запуску: наборы, шаги LST, новые материалы. Часовой пояс: 20:00 JST = 13:00 CEST = 04:00 PDT."),
        section("whats-next", "Что делать японским игрокам", "Предрегистрация, решение по набору, участие в LST 17–18 сентября для установки клиента. Следите за официальной доской для сентябрьских обслуживаний."),
        section("timing", "Примечание о времени", "Публикуется 28 августа, до или около эфира в зависимости от часового пояса. После эфира смотрите VOD и наш следующий обзор."),
      ],
    }),
    "zh-hant": articleCopy(newsLabels, "zh-hant", 5, {
      eyebrow: "JP 官方樞紐 + 生放送",
      title: "Aion 2 日本：官方特別頁上線，8 月 28 日 20:00 JST 生放送今晚播出",
      description: "Aion 2 日本官方特別頁上線，確認正式服務自 10 月 5 日開始，並給出日本適用的上線規模測試時間。今晚 8 月 28 日 20:00 JST 的生放送是下一個節點。",
      intro: "Aion 2 的日本宣傳已進入上線檔期：專屬日文特別頁確認正式服務自 2026 年 10 月 5 日開始，列出 9 月 17-18 日上線規模測試的日本時間，並預告今天 8 月 28 日 20:00 JST 的生放送。本報導彙總日本樞紐確認的內容、生放送預期話題，以及日本玩家接下來要做的事。",
      sourceNote: "基於 2026 年 8 月 28 日抓取的 AION 2 日本官方特別頁（aion2.ncsoft.jp）與日本官方公告板。",
      keywords: ["Aion 2 日本生放送", "Aion 2 8月28日 生放送", "Aion 2 日本10月5日上線", "Aion 2 正式服務 10月5日", "Aion 2 日本上線規模測試"],
      sections: [
        section("site", "日本特別頁已上線", ["專屬日文入口（aion2.ncsoft.jp/ja/contents）確認『正式服務決定』為 2026 年 10 月 5 日——與 Gamescom 公布的全球視窗一致。", "事前登錄自 6 月 6 日起持續，創始人包自 7 月 22 日起販售（含 5 天搶先體驗與 30 天會員）——日本參與 9 月 30 日搶先體驗視窗。", "頁面還列出四個起始遠征（4 人副本）——クラオ洞窟、ウルググ峡谷、炎の神殿、ドラウプニル——給出開篇內容的具象視圖。"]),
        section("lst-jp", "上線規模測試的日本時間", ["9 月 17-18 日 LST 在官方頁有日本專屬時間：9 月 16 日 22:00 JST 起預載，第 1 天 9 月 17 日 22:00 JST 至 9 月 18 日 04:00 JST，第 2 天 9 月 19 日 04:00-10:00 JST。", "日本玩家無任何入場條件——與全球公告一致的全開放、免密鑰形式，覆蓋 Steam 與 PURPLE。", "這些時間即全球視窗的 JST 轉換；完整限制清單（等級上限 37、無商店、進度清空）見站內 LST 指南。"]),
        section("stream", "今晚生放送：8 月 28 日 20:00 JST", ["官方頁預告今天週五 8 月 28 日 20:00 JST 於 YouTube 播出生放送——Gamescom 週後的首次。", "按上線節奏推斷，節目將圍繞上線準備展開：更多創始人包細節、LST 參加步驟，乃至衝擊 9 月 30 日的新實機或預告物料。", "日本時間 20:00 JST = 13:00 CEST = 04:00 PDT——歐洲玩家如需收看請自行換算時間。"]),
        section("whats-next", "日本玩家接下來要做的事", ["尚未預登錄的請預登錄；9 月 30 日搶先體驗開放前決定創始人包；參加 9 月 17-18 日 LST 以鎖定用戶端安裝與設定。", "關注官方公告板（aion2.plaync.com/ja-jp/board/notice/list）——9 月維護計畫與搶先體驗用戶端下載將首先在此公布。", "備好站內本地版本變動指南：韓/台更新（大平衡、伺服器轉移）預覽日本與全球版上線時將獲得的調校。"]),
        section("timing", "時間說明", ["本報導 8 月 28 日發布，視時區而定在 20:00 JST 直播前或前後。若你在直播後閱讀，請造訪官網存檔連結查看回放，並留意下一批次的重播整理。", "NC 發布 VOD 與後續公告後，本文將更新已確認的直播亮點。"]),
      ],
    }),
  },
};