import { articleCopy, localizations, newsLabels, publishedVerified, section } from "./trending-september-9-shared";
import type { ContentEntry, ContentHeroImage, ContentSource } from "./content-registry";

/* ARTICLE 1 — Korean service adds new Sanctuary raid "Snowfield of Grief" (Sep 9 update): three difficulties, Deltras, Tier 4 gear, Seal slot, Chapter 1 follow-ups */

const invenSource: ContentSource = {
  id: "inven-aion2-snowfield-preview-2026-09-08",
  kind: "third-party",
  publisher: "Inven Global",
  label: "Aion 2 Unveils New Raid Content 'Snowfield of Grief'",
  url: "https://www.invenglobal.com/articles/25688/aion-2-unveils-new-raid-content-snowfield-of-grief",
  publishedAt: "2026-09-08",
  retrievedAt: "2026-09-09",
  verifiedAt: "2026-09-09",
  localizations: localizations({
    "zh-hans": "Aion 2 公布新团队副本内容「Snowfield of Grief」",
    en: "Aion 2 Unveils New Raid Content 'Snowfield of Grief'",
    fr: "Aion 2 dévoile un nouveau raid « Snowfield of Grief »",
    de: "Aion 2 enthüllt neuen Raid „Snowfield of Grief“",
    es: "Aion 2 desvela el nuevo raid «Snowfield of Grief»",
    ja: "Aion 2 新レイド「Snowfield of Grief」を公開",
    "pt-br": "Aion 2 revela novo conteúdo de raid 'Snowfield of Grief'",
    ru: "Aion 2 анонсирует новый рейд «Snowfield of Grief»",
    ko: "아이온2 신규 레이드 '슬픔의 설원' 공개",
    "zh-hant": "Aion 2 公布新團隊副本內容「Snowfield of Grief」",
  }, "https://www.invenglobal.com/articles/25688/aion-2-unveils-new-raid-content-snowfield-of-grief"),
};

const officialPatchSource: ContentSource = {
  id: "aion2-official-update-2026-09-09",
  kind: "official",
  publisher: "NC Corporation",
  label: "AION 2 Update Notes — September 9, 2026 (Snowfield of Lament, Seal slot)",
  url: "https://aion2.plaync.com/ko-kr/board/update/view?articleId=6aa062386b722c561dc6a46c",
  publishedAt: "2026-09-09",
  retrievedAt: "2026-09-09",
  verifiedAt: "2026-09-09",
  localizations: localizations({
    "zh-hans": "AION 2 更新说明——2026-09-09（Snowfield of Lament、印章栏）",
    en: "AION 2 Update Notes — September 9, 2026 (Snowfield of Lament, Seal slot)",
    fr: "Notes de mise à jour AION 2 — 9 septembre 2026 (Snowfield of Lament, emplacement Sceau)",
    de: "AION-2-Update-Notizen — 9. September 2026 (Snowfield of Lament, Seal-Platz)",
    es: "Notas de actualización de AION 2 — 9 de septiembre de 2026 (Snowfield of Lament, ranura de Sello)",
    ja: "AION 2 アップデートノート——2026-09-09（Snowfield of Lament、シール枠）",
    "pt-br": "Notas de atualização do AION 2 — 9 de setembro de 2026 (Snowfield of Lament, slot de Selo)",
    ru: "Заметки об обновлении AION 2 — 9 сентября 2026 (Snowfield of Lament, слот Печати)",
    ko: "AION 2 업데이트 노트 — 2026-09-09 (슬픔의 설원, 인장 칸)",
    "zh-hant": "AION 2 更新說明——2026-09-09（Snowfield of Lament、印章欄）",
  }, "https://aion2.plaync.com/ko-kr/board/update/view?articleId=6aa062386b722c561dc6a46c"),
};

const sHero: ContentHeroImage = {
  src: "https://blogfiles.ncsoft.net/news/af7330da-4ff6-4b58-aece-400e6061a3be.jpg",
  width: 1200, height: 630,
  credit: "NC Corporation",
  sourceUrl: "https://aion2.plaync.com/en-us/",
  rights: "linked-official-media",
  translations: {
    "zh-hans": { alt: "Aion 2 新团队副本 Snowfield of Grief 新闻横幅", caption: "韩服 9 月 9 日更新上线新 Sanctuary 团队副本「Snowfield of Grief」（泪之雪原）：Easy/Normal/Hard 三难度、最终 Boss Deltras、Hard 掉落 Tier 4「Liberated White Night」武器与守护者，并新增印章装备栏。" },
    en: { alt: "Aion 2 new Sanctuary raid Snowfield of Grief news banner", caption: "The September 9 Korean update adds the new Sanctuary raid 'Snowfield of Grief' with Easy/Normal/Hard difficulties, final boss Deltras, Tier 4 'Liberated White Night' weapons and guarders on Hard, and a new Seal equipment slot." },
    fr: { alt: "Bannière d'actualité du nouveau raid Snowfield of Grief d'Aion 2", caption: "La mise à jour coréenne du 9 septembre ajoute le raid Sanctuary « Snowfield of Grief » en trois difficultés, avec Deltras en boss final, l'équipement de rang 4 « Liberated White Night » en Hard, et un nouvel emplacement Sceau." },
    de: { alt: "News-Banner zum neuen Raid Snowfield of Grief von Aion 2", caption: "Das koreanische Update vom 9. September fügt den neuen Sanctuary-Raid „Snowfield of Grief“ in drei Schwierigkeitsgraden hinzu, mit Endboss Deltras, Tier-4-„Liberated White Night“-Waffen und Guardern auf Hard sowie einem neuen Seal-Platz." },
    es: { alt: "Banner de noticias del nuevo raid Snowfield of Grief de Aion 2", caption: "La actualización coreana del 9 de septiembre añade el nuevo raid de Santuario «Snowfield of Grief» en tres dificultades, con Deltras como jefe final, equipo Tier 4 «Liberated White Night» en Hard y una nueva ranura de Sello." },
    ja: { alt: "Aion 2 新レイド Snowfield of Grief ニュースバナー", caption: "9月9日の韓国アップデートで新サンクチュアリレイド「Snowfield of Grief」が追加：Easy/Normal/Hardの3難易度、ラスボスDeltras、HardでTier4「Liberated White Night」武器・ガーダー、新シール枠も実装。" },
    "pt-br": { alt: "Banner de notícias do novo raid Snowfield of Grief do Aion 2", caption: "A atualização coreana de 9 de setembro adiciona o novo raid de Santuário 'Snowfield of Grief' em três dificuldades, com Deltras como chefe final, equipamento Tier 4 'Liberated White Night' no Hard e um novo slot de Selo." },
    ru: { alt: "Баннер новостей о новом рейде Snowfield of Grief в Aion 2", caption: "Корейское обновление 9 сентября добавляет новый рейд Святилища «Snowfield of Grief» на трёх сложностях, с финальным боссом Deltras, оружием и гардами Tier 4 «Liberated White Night» на Hard и новым слотом Печати." },
    ko: { alt: "Aion 2 신규 레이드 슬픔의 설원 뉴스 배너", caption: "9월 9일 한국 업데이트로 신규 성역 레이드 '슬픔의 설원'이 추가됩니다: Easy/Normal/Hard 3단계 난이도, 최종 보스 델트라스, Hard에서 Tier 4 '해방된 화이트 나이트' 무기·가더 드랍, 신규 인장 장비 칸도 도입." },
    "zh-hant": { alt: "Aion 2 新團隊副本 Snowfield of Grief 新聞橫幅", caption: "韓服 9 月 9 日更新上線新 Sanctuary 團隊副本「Snowfield of Grief」（淚之雪原）：Easy/Normal/Hard 三難度、最終 Boss Deltras、Hard 掉落 Tier 4「Liberated White Night」武器與守護者，並新增印章裝備欄。" },
  },
};

export const trendingSeptember9Article1: ContentEntry = {
  section: "news",
  slug: "aion-2-snowfield-of-grief-sanctuary-raid",
  schemaType: "NewsArticle",
  publishedAt: "2026-09-09",
  updatedAt: "2026-09-09",
  readingMinutes: 6,
  publication: publishedVerified,
  sources: [invenSource, officialPatchSource],
  heroImage: sHero,
  related: [
    { kind: "content", section: "guides", slug: "aion-2-trials-raids-guide" },
    { kind: "content", section: "guides", slug: "aion-2-raid-boss-split-merge-design" },
    { kind: "content", section: "guides", slug: "aion-2-endgame-gear-guide" },
    { kind: "content", section: "guides", slug: "aion-2-korea-server-class-tier-guide" },
  ],
  translations: {
    en: articleCopy(newsLabels, "en", 6, {
      eyebrow: "KOREA UPDATE",
      title: "Aion 2 Korean Update Adds New Sanctuary Raid 'Snowfield of Grief': Three Difficulties, Deltras, Tier 4 Gear",
      description: "The September 9 Korean service update launches the new Sanctuary raid 'Snowfield of Grief' with Easy/Normal/Hard, final boss Deltras, Tier 4 Liberated White Night gear on Hard, and a new Seal equipment slot",
      intro: "During a September 8 livestream, NCsoft previewed the new Sanctuary raid 'Snowfield of Grief' (also translated 'Snowfield of Lament'), which goes live in Korea on September 9. It is a mechanics-driven raid with three difficulties, drops top-tier Tier 4 weapons and guarders on Hard, and introduces a new Seal equipment slot.",
      sourceNote: "Based on Inven Global's September 8, 2026 report of NCsoft's livestream, cross-checked with the official Korean update notes of September 9, 2026 (both retrieved September 9, 2026). All content applies to the Korean service; the global version launches October 5 with a modified Season 1 and will receive this content later.",
      keywords: ["Aion 2 Snowfield of Grief raid", "Aion 2 Snowfield of Lament sanctuary", "Aion 2 new raid September 2026", "Aion 2 Deltras boss", "Aion 2 Tier 4 Liberated White Night"],
      sections: [
        section("raid-details", "The New Sanctuary: Snowfield of Grief", ["The Sanctuary 'Snowfield of Grief' is a mechanics-driven raid that explicitly avoids 'cyber boot camp' encounters requiring every party member to execute perfectly synchronized routines. NCsoft stressed that immediate responses — reading and predicting boss patterns or reacting upon visual confirmation — will be crucial.", "It launches across three difficulty levels: Easy, Normal, and Hard. On Hard, the Sanctuary adds a Hall of Fame that records the server-wide first, second, and third kills of the final boss Deltras, along with the character name, server, Legion, class, combat power and item level at the time of the clear."]),
        section("hard-rewards", "Hard Rewards: Tier 4 Weapons and Guarders", ["Hard difficulty drops top-tier weapons and guarders from the 'Liberated White Night' (Tier 4) series — the current highest crafted tier for the Korean service.", "For crafted Tier 4 gear, '[True] Genesis Dragon Lord' and '[True] Nemesis Dragon Lord' weapons and guarders are added through a stepped growth structure: Shining Azure Dragon / Extinction Dragon equipment can be upgraded to the True versions via Succession Crafting, and the extendable effect is provided as a default stat without occupying a Soul Imprint option."]),
        section("seal-slot", "A New Seal Equipment Slot", ["The update also adds a new equipment slot: Seal. The new accessory 'Deltras's Seal (Unique)' can be obtained starting from Easy difficulty.", "Fabled-grade seals can be crafted via Handicrafting, and Unique-grade seals obtained in Snowfield of Grief can be upgraded to Heroic grade through Succession Crafting. Its Breakthrough option increases Weapon Damage Amplification."]),
        section("chapter1-followups", "Chapter 1 Follow-Ups Announced", ["The same livestream detailed upcoming Chapter 1 content: a Soul Imprint Auto-Tuning system, a new Trial 'Temple of Fire', expanded sources for Manastones, Spirit Stones, Heroic Tuning Stones and Soul Crystals, reduced difficulty for Pet Familiarity, and Arcana adjustments.", "On Temple of Fire, NCsoft said the current Trial Bakron 'tended to be easier than intended' and promised: 'It will be a truly difficult, literal trial.' Class balance is also under comprehensive review to address over-preference during Abyss field boss fights and dungeon runs while reinforcing each class's identity."]),
        section("global-relevance", "What This Means for Global Players", ["The update applies to the Korean service, which is running Chapter 1 content that the global version does not have yet. Per the content model confirmed on September 7, the global launch on October 5 ships a modified Season 1 and will follow Korea with roughly three-month seasons.", "For global players, treat Snowfield of Grief as a preview of the raiding difficulty curve to expect: reaction-based mechanics, three difficulties, and Tier 4-level progression are the shape of the endgame roadmap."]),
      ],
    }),
    "zh-hans": articleCopy(newsLabels, "zh-hans", 6, {
      eyebrow: "韩服更新",
      title: "Aion 2 韩服新团队副本「Snowfield of Grief」：三难度、Deltras、Tier 4 装备",
      description: "9 月 9 日韩服更新上线新 Sanctuary 团队副本「Snowfield of Grief」：Easy/Normal/Hard 三难度、最终 Boss Deltras、Hard 掉落 Tier 4 Liberated White Night 装备，并新增印章装备栏",
      intro: "在 9 月 8 日直播中，NCsoft 预览了新的 Sanctuary 团队副本「Snowfield of Grief」（亦译 Snowfield of Lament），韩服 9 月 9 日上线。该副本以机制驱动为卖点，设三档难度，Hard 掉落 Tier 4 顶级武器与守护者，并引入新的印章装备栏。",
      sourceNote: "基于 Inven Global 2026 年 9 月 8 日对 NCsoft 直播的报道，并与 2026 年 9 月 9 日官方韩服更新说明交叉核对（均于 2026-09-09 抓取）。全部内容针对韩服；全球版 10 月 5 日以改良版 Season 1 上线，此内容后续才会到达。",
      keywords: ["Aion 2 Snowfield of Grief 团队副本", "Aion 2 Snowfield of Lament 副本", "Aion 2 新副本 2026年9月", "Aion 2 Deltras Boss", "Aion 2 Tier 4 Liberated White Night"],
      sections: [
        section("raid-details", "新 Sanctuary：Snowfield of Grief", ["「Snowfield of Grief」是以机制驱动的副本，明确避开要求全员完美同步执行的「电竞集训式」机制。NCsoft 强调即时反应——预读/预判 Boss 动作或凭视觉确认做出反应——将至关重要。", "副本设三档难度：Easy、Normal、Hard。Hard 的 Sanctuary 新增名人堂，记录全服对最终 Boss Deltras 的第一、二、三次击杀，以及通关时的角色名、服务器、军团、职业、战力与装备评分。"]),
        section("hard-rewards", "Hard 奖励：Tier 4 武器与守护者", ["Hard 难度掉落「Liberated White Night」（Tier 4）系列的顶级武器与守护者——这是韩服当前最高制作阶。", "制作 Tier 4 装备方面，新增「[True] 创世龙神 / [True] 灭绝龙神」武器与守护者，沿用逐步成长结构：闪亮蓝龙/灭绝龙装备可经传承制作升级为 True 版，可延展效果作为默认属性提供，不占用灵魂刻印位。"]),
        section("seal-slot", "新的印章装备栏", ["更新还新增一个装备栏：印章。新饰品「Deltras's Seal（Unique）」从 Easy 难度起即可获得。", "Fabled 级印章可通过手工制作获得；Snowfield of Grief 中获得的 Unique 印章可经传承制作升级为 Heroic 级。其突破选项可提升武器伤害增幅。"]),
        section("chapter1-followups", "Chapter 1 后续前瞻", ["同一直播公布了后续 Chapter 1 内容：灵魂刻印自动调优系统、新试炼「Temple of Fire」、玛瑙石/灵魂石/英雄调谐石/灵魂水晶获取途径扩展、宠物亲密度难度下调、Arcana 调整。", "关于 Temple of Fire，NCsoft 表示现有试炼 Bakron「偏简单了」，并承诺「这将是一场真正困难、名副其实的试炼」。职业平衡也在全面审查，以解决深渊野外 Boss 与副本中的职业偏科，同时强化各职业特色。"]),
        section("global-relevance", "对全球玩家的意义", ["本次更新针对韩服——它正在运行全球版尚未拥有的 Chapter 1 内容。按 9 月 7 日确认的内容模型，全球版 10 月 5 日以改良版 Season 1 上线，之后以约三个月一季的节奏跟随韩服。", "对全球玩家而言，把 Snowfield of Grief 视为终局副本难度曲线的预告：机制反应向、三档难度、Tier 4 级成长，这就是终局路线的形态。"]),
      ],
    }),
    fr: articleCopy(newsLabels, "fr", 6, {
      eyebrow: "MISE À JOUR CORÉE",
      title: "La mise à jour coréenne d'Aion 2 ajoute le raid « Snowfield of Grief » : trois difficultés, Deltras, équipement de rang 4",
      description: "La mise à jour coréenne du 9 septembre lance le raid Sanctuary « Snowfield of Grief » (Easy/Normal/Hard), Deltras en boss final, l'équipement de rang 4 Liberated White Night en Hard et un nouvel emplacement Sceau",
      intro: "Lors d'un livestream du 8 septembre, NCsoft a présenté le nouveau raid Sanctuary « Snowfield of Grief » (aussi traduit « Snowfield of Lament »), en ligne en Corée le 9 septembre. Un raid axé mécaniques, trois difficultés, équipement de rang 4 en Hard, et un nouvel emplacement Sceau.",
      sourceNote: "Basé sur le rapport d'Inven Global du 8 septembre 2026 sur le livestream de NCsoft, recoupé avec les notes de mise à jour officielles coréennes du 9 septembre 2026 (toutes récupérées le 9 septembre 2026).",
      keywords: ["Aion 2 raid Snowfield of Grief", "Aion 2 Snowfield of Lament sanctuaire", "Aion 2 nouveau raid septembre 2026", "Aion 2 boss Deltras", "Aion 2 rang 4 Liberated White Night"],
      sections: [
        section("raid-details", "Le nouveau Sanctuary : Snowfield of Grief", "Un raid axé mécaniques, sans les « cyber boot camps » exigeant une synchronisation parfaite : les réactions immédiates — lire les patterns ou réagir sur confirmation visuelle — seront cruciales. Trois difficultés ; en Hard, un Hall of Fame enregistre les 1re, 2e et 3e kills du boss final Deltras."),
        section("hard-rewards", "Récompenses Hard : armes et gardes de rang 4", "Le Hard droppe les armes et gardes « Liberated White Night » (rang 4). Les armes et gardes « [True] Genesis / Nemesis Dragon Lord » arrivent via la structure de croissance : les équipements Shining Azure / Extinction Dragon passent en True par l'artisanat de succession, l'effet extensible étant un statut par défaut sans occuper d'option Soul Imprint."),
        section("seal-slot", "Un nouvel emplacement Sceau", "Nouvel emplacement Sceau ; l'accessoire « Deltras's Seal (Unique) » dès Easy. Les sceaux Fabled via l'artisanat ; les Unique upgradables en Heroic par artisanat de succession ; l'option Breakthrough augmente l'amplification des dégâts d'arme."),
        section("chapter1-followups", "La suite du Chapitre 1", "Auto-réglage Soul Imprint, nouveau Trial « Temple of Fire » (Bakron « plus facile que prévu » ; « un véritable défi »), sources élargies (Manastones, Spirit Stones, Tuning Stones héroïques, Soul Crystals), familiarité des familiers adoucie, ajustements Arcana, revue de l'équilibrage des classes."),
        section("global-relevance", "Ce que cela signifie pour le global", "Mise à jour du service coréen (Chapitre 1, absent du global). Le lancement global du 5 octobre part d'une Saison 1 modifiée puis suit la Corée (~3 mois/saison) : considérez ce raid comme un aperçu de la courbe de difficulté à venir."),
      ],
    }),
    de: articleCopy(newsLabels, "de", 6, {
      eyebrow: "KOREA-UPDATE",
      title: "Koreanisches Update fügt neuen Raid „Snowfield of Grief“ hinzu: drei Schwierigkeiten, Deltras, Tier-4-Ausrüstung",
      description: "Das Update vom 9. September startet den neuen Sanctuary-Raid „Snowfield of Grief“ (Easy/Normal/Hard), Endboss Deltras, Tier-4-„Liberated White Night“-Ausrüstung auf Hard und einen neuen Seal-Platz",
      intro: "In einem Livestream am 8. September zeigte NCsoft den neuen Sanctuary-Raid „Snowfield of Grief“ (auch „Snowfield of Lament“), der in Korea am 9. September live geht: mechanikgetrieben, drei Schwierigkeiten, Tier-4-Drops auf Hard, neuer Seal-Platz.",
      sourceNote: "Basierend auf dem Inven-Global-Bericht vom 8. September 2026 über den NCsoft-Livestream, abgeglichen mit den offiziellen koreanischen Update-Notizen vom 9. September 2026 (abgerufen am 9. September 2026).",
      keywords: ["Aion 2 Raid Snowfield of Grief", "Aion 2 Snowfield of Lament Sanctuary", "Aion 2 neuer Raid September 2026", "Aion 2 Deltras Boss", "Aion 2 Tier 4 Liberated White Night"],
      sections: [
        section("raid-details", "Der neue Sanctuary: Snowfield of Grief", "Ein mechanikgetriebener Raid ohne „Cyber-Bootcamp“-Mechaniken: sofortige Reaktionen — Muster lesen oder auf visuelle Bestätigung reagieren — sind entscheidend. Drei Schwierigkeiten; auf Hard zeichnet eine Hall of Fame die ersten drei Kills von Endboss Deltras auf."),
        section("hard-rewards", "Hard-Belohnungen: Tier-4-Waffen und -Garder", "Hard droppt „Liberated White Night“ (Tier 4). „[True] Genesis/Nemesis Dragon Lord“-Waffen und -Garder kommen per gestufter Struktur: Shining Azure/Extinction Dragon wird per Succession Crafting zu True; der erweiterbare Effekt ist Standard-Stat ohne Soul-Imprint-Platz."),
        section("seal-slot", "Ein neuer Seal-Platz", "Neuer Ausrüstungsplatz Seal; „Deltras's Seal (Unique)“ ab Easy. Fabled-Siegel per Handwerk; Unique → Heroic per Succession Crafting; Breakthrough erhöht die Waffenschadens-Verstärkung."),
        section("chapter1-followups", "Kapitel-1-Ausblick", "Soul-Imprint-Auto-Tuning, neues Trial „Temple of Fire“ (Bakron „einfacher als beabsichtigt“; „eine echte Herausforderung“), mehr Quellen (Manasteine, Geiststeine, heroische Tuning-Steine, Seelenkristalle), leichtere Vertrautheit der Begleiter, Arcana-Anpassungen, Klassen-Balance-Review."),
        section("global-relevance", "Was das für Global bedeutet", "Koreanisches Update (Kapitel 1, das Global noch nicht hat). Global startet am 5. Oktober mit modifizierter Season 1 und folgt Korea (~3 Monate/Saison): Betrachte diesen Raid als Vorschau auf die kommende Schwierigkeitskurve."),
      ],
    }),
    es: articleCopy(newsLabels, "es", 6, {
      eyebrow: "ACTUALIZACIÓN COREA",
      title: "La actualización coreana de Aion 2 añade el raid «Snowfield of Grief»: tres dificultades, Deltras, equipo Tier 4",
      description: "La actualización del 9 de septiembre lanza el raid de Santuario «Snowfield of Grief» (Easy/Normal/Hard), Deltras como jefe final, equipo Tier 4 Liberated White Night en Hard y una nueva ranura de Sello",
      intro: "En un livestream del 8 de septiembre, NCsoft mostró el nuevo raid de Santuario «Snowfield of Grief» (también «Snowfield of Lament»), que llega a Corea el 9 de septiembre: raid de mecánicas, tres dificultades, equipo Tier 4 en Hard y nueva ranura de Sello.",
      sourceNote: "Basado en el informe de Inven Global del 8 de septiembre de 2026 sobre el livestream de NCsoft, cotejado con las notas de actualización oficiales coreanas del 9 de septiembre de 2026 (recuperadas el 9 de septiembre de 2026).",
      keywords: ["Aion 2 raid Snowfield of Grief", "Aion 2 Snowfield of Lament santuario", "Aion 2 nuevo raid septiembre 2026", "Aion 2 jefe Deltras", "Aion 2 Tier 4 Liberated White Night"],
      sections: [
        section("raid-details", "El nuevo Santuario: Snowfield of Grief", "Un raid de mecánicas que evita los «cyber boot camps»: las reacciones inmediatas —leer patrones o reaccionar a confirmación visual— serán cruciales. Tres dificultades; en Hard, un Salón de la Fama registra los kills 1º, 2º y 3º de Deltras."),
        section("hard-rewards", "Recompensas Hard: armas y guardas Tier 4", "Hard deja caer «Liberated White Night» (Tier 4). Las armas y guardas «[True] Genesis/Nemesis Dragon Lord» llegan con la estructura escalonada: Shining Azure/Extinction Dragon se actualiza a True por artesanía de sucesión; el efecto extensible es estadística por defecto sin ocupar opción de Soul Imprint."),
        section("seal-slot", "Una nueva ranura de Sello", "Nueva ranura Sello; «Deltras's Seal (Unique)» desde Easy. Los sellos Fabled por artesanía; Unique → Heroic por artesanía de sucesión; Breakthrough aumenta la amplificación de daño de arma."),
        section("chapter1-followups", "Lo que sigue del Capítulo 1", "Autoajuste de Soul Imprint, nuevo Trial «Temple of Fire» (Bakron «más fácil de lo previsto»; «una prueba realmente difícil»), más fuentes (Manastones, Spirit Stones, Tuning Stones heroicas, Soul Crystals), familiaridad de mascotas más fácil, ajustes de Arcana, revisión de equilibrio de clases."),
        section("global-relevance", "Qué significa para el global", "Actualización del servicio coreano (Capítulo 1, aún no en global). El global lanza el 5 de octubre con Temporada 1 modificada y seguirá a Corea (~3 meses/temporada): trata este raid como un adelanto de la curva de dificultad."),
      ],
    }),
    ja: articleCopy(newsLabels, "ja", 6, {
      eyebrow: "韓国アップデート",
      title: "Aion 2 韓国アップデートで新レイド「Snowfield of Grief」追加：3難易度、Deltras、Tier 4装備",
      description: "9月9日の韓国サービス更新で新サンクチュアリレイド「Snowfield of Grief」が登場：Easy/Normal/Hard、ラスボスDeltras、HardでTier 4 Liberated White Night装備、新シール枠も",
      intro: "9月8日のライブ配信でNCが新サンクチュアリレイド「Snowfield of Grief」（別訳：Snowfield of Lament）を公開。韓国では9月9日に実装され、メカニクス重視のレイドで3難易度、HardでTier 4装備、新シール枠も導入されます。",
      sourceNote: "Inven Global 2026年9月8日付のNCライブ配信レポートに基づき、2026年9月9日付公式韓国アップデートノート（いずれも2026-09-09取得）と照合しました。",
      keywords: ["Aion 2 Snowfield of Grief レイド", "Aion 2 Snowfield of Lament サンクチュアリ", "Aion 2 新レイド 2026年9月", "Aion 2 Deltras ボス", "Aion 2 Tier 4 Liberated White Night"],
      sections: [
        section("raid-details", "新サンクチュアリ：Snowfield of Grief", "全員の完璧な同期を求める「サイバー合宿」的ギミックを排したメカニクス重視のレイド。パターンの先読み・予測、視覚確認への即時反応が鍵です。3難易度で、Hardでは最終ボスDeltrasのサーバー内1〜3位撃破を記録する栄誉の殿堂が追加されます。"),
        section("hard-rewards", "Hard報酬：Tier 4武器・ガーダー", "Hardで「Liberated White Night」（Tier 4）シリーズの最上位武器・ガーダーがドロップ。制作Tier 4では「[True]創世竜神/[True]滅絶竜神」武器・ガーダーが段階的成長で追加され、Splendent系から継承制作でTrueへ、拡張効果はソウル刻印を占有せずデフォルトステータスとして付与されます。"),
        section("seal-slot", "新装備枠「シール」", "新装備枠シールが追加され、Easyから「Deltras's Seal（Unique）」を取得可能。Fabled級は手工芸で制作、Snowfield of Griefで入手したUniqueは継承制作でHeroicへ。ブレークスルーで武器ダメージ増幅が上昇します。"),
        section("chapter1-followups", "Chapter 1の今後", "ソウル刻印オートチューニング、新トライアル「Temple of Fire」（現行Bakronは「想定より簡単」とし「真に困難な試練」と明言）、マナストーン/精霊石/英雄チューニングストーン/ソウルクリスタルの入手源拡大、ペット親密度の緩和、アルカナ調整、職業バランス見直し。"),
        section("global-relevance", "グローバルプレイヤーへの意味", "対象は韓国サービス（Chapter 1はグローバル未実装）。グローバルは10月5日に改良版シーズン1で開始し、韓国に約3カ月遅れで追従します。このレイドを今後の難易度カーブのプレビューとして捉えましょう。"),
      ],
    }),
    "pt-br": articleCopy(newsLabels, "pt-br", 6, {
      eyebrow: "ATUALIZAÇÃO COREIA",
      title: "Atualização coreana do Aion 2 adiciona o raid 'Snowfield of Grief': três dificuldades, Deltras, equipamento Tier 4",
      description: "A atualização de 9 de setembro lança o raid de Santuário 'Snowfield of Grief' (Easy/Normal/Hard), Deltras como chefe final, equipamento Tier 4 Liberated White Night no Hard e um novo slot de Selo",
      intro: "Durante um livestream de 8 de setembro, a NCsoft mostrou o novo raid de Santuário 'Snowfield of Grief' (também 'Snowfield of Lament'), que chega à Coreia em 9 de setembro: raid de mecânicas, três dificuldades, equipamento Tier 4 no Hard e novo slot de Selo.",
      sourceNote: "Baseado no relatório da Inven Global de 8 de setembro de 2026 sobre o livestream da NCsoft, cruzado com as notas de atualização oficiais coreanas de 9 de setembro de 2026 (recuperadas em 9 de setembro de 2026).",
      keywords: ["Aion 2 raid Snowfield of Grief", "Aion 2 Snowfield of Lament santuário", "Aion 2 novo raid setembro 2026", "Aion 2 chefe Deltras", "Aion 2 Tier 4 Liberated White Night"],
      sections: [
        section("raid-details", "O novo Santuário: Snowfield of Grief", "Um raid de mecânicas que evita os 'cyber boot camps': reações imediatas — ler padrões ou reagir à confirmação visual — serão cruciais. Três dificuldades; no Hard, um Salão da Fama registra os kills 1º, 2º e 3º de Deltras."),
        section("hard-rewards", "Recompensas do Hard: armas e guardas Tier 4", "O Hard dropa 'Liberated White Night' (Tier 4). As armas e guardas '[True] Genesis/Nemesis Dragon Lord' chegam pela estrutura escalonada: Shining Azure/Extinction Dragon sobe para True via artesanato de sucessão; o efeito extensível é stat padrão sem ocupar opção de Soul Imprint."),
        section("seal-slot", "Um novo slot de Selo", "Novo slot Selo; 'Deltras's Seal (Unique)' desde Easy. Selos Fabled por artesanato; Unique → Heroic via artesanato de sucessão; Breakthrough aumenta a amplificação de dano de arma."),
        section("chapter1-followups", "O que vem no Capítulo 1", "Autoajuste de Soul Imprint, novo Trial 'Temple of Fire' (Bakron 'mais fácil que o previsto'; 'um teste realmente difícil'), mais fontes (Manastones, Spirit Stones, Tuning Stones heroicas, Soul Crystals), familiaridade de mascotes mais fácil, ajustes de Arcana, revisão de equilíbrio de classes."),
        section("global-relevance", "O que isso significa para o global", "Atualização do serviço coreano (Capítulo 1, ainda não no global). O global lança em 5 de outubro com Temporada 1 modificada e seguirá a Coreia (~3 meses/temporada): trate este raid como prévia da curva de dificuldade."),
      ],
    }),
    ru: articleCopy(newsLabels, "ru", 6, {
      eyebrow: "ОБНОВЛЕНИЕ КОРЕИ",
      title: "Корейское обновление Aion 2 добавляет рейд «Snowfield of Grief»: три сложности, Deltras, экипировка Tier 4",
      description: "Обновление 9 сентября запускает рейд Святилища «Snowfield of Grief» (Easy/Normal/Hard), финального босса Deltras, экипировку Tier 4 Liberated White Night на Hard и новый слот Печати",
      intro: "В стриме 8 сентября NCsoft показала новый рейд Святилища «Snowfield of Grief» (также «Snowfield of Lament»), который выходит в Корее 9 сентября: механико-ориентированный рейд, три сложности, экипировка Tier 4 на Hard и новый слот Печати.",
      sourceNote: "На основе репортажа Inven Global от 8 сентября 2026 г. о стриме NCsoft, сверено с официальными корейскими заметками об обновлении от 9 сентября 2026 г. (получены 9 сентября 2026 г.).",
      keywords: ["Aion 2 рейд Snowfield of Grief", "Aion 2 Snowfield of Lament святилище", "Aion 2 новый рейд сентябрь 2026", "Aion 2 босс Deltras", "Aion 2 Tier 4 Liberated White Night"],
      sections: [
        section("raid-details", "Новое Святилище: Snowfield of Grief", "Механико-ориентированный рейд без «кибер-курсов» с идеальной синхронизацией: мгновенные реакции — чтение паттернов или реакция на визуальное подтверждение — будут ключом. Три сложности; на Hard Зал славы фиксирует 1-й, 2-й и 3-й килы финального босса Deltras."),
        section("hard-rewards", "Награды Hard: оружие и гарды Tier 4", "На Hard падают «Liberated White Night» (Tier 4). Оружие и гарды «[True] Genesis/Nemesis Dragon Lord» добавляются ступенчатой структурой: Shining Azure/Extinction Dragon улучшается до True через наследование; расширяемый эффект — базовый стат без слота Soul Imprint."),
        section("seal-slot", "Новый слот Печати", "Новый слот Печати; аксессуар «Deltras's Seal (Unique)» с Easy. Fabled-печати — ремеслом; Unique → Heroic через наследование; Breakthrough повышает усиление урона оружия."),
        section("chapter1-followups", "Дальнейший план Главы 1", "Автоподстройка Soul Imprint, новое Испытание «Temple of Fire» (Bakron «проще задуманного»; «по-настоящему трудное испытание»), больше источников (Манастоуны, Духовные камни, героические камни настройки, Кристаллы душ), легче привязанность питомцев, правки Арканы, ревизия баланса классов."),
        section("global-relevance", "Что это значит для глобала", "Обновление корейского сервиса (Глава 1, которой в глобале ещё нет). Глобал стартует 5 октября с модифицированным Сезоном 1 и следует за Кореей (~3 месяца/сезон): считайте этот рейд превью будущей кривой сложности."),
      ],
    }),
    ko: articleCopy(newsLabels, "ko", 6, {
      eyebrow: "한국 업데이트",
      title: "아이온2 신규 성역 레이드 '슬픔의 설원': 3단계 난이도, 델트라스, Tier 4 장비",
      description: "9월 9일 한국 서버 업데이트로 신규 성역 레이드 '슬픔의 설원'(Snowfield of Grief) 등장: Easy/Normal/Hard, 최종 보스 델트라스, Hard에서 Tier 4 해방된 화이트 나이트 장비, 신규 인장 장비 칸도 도입",
      intro: "9월 8일 라이브 방송에서 NC가 신규 성역 레이드 '슬픔의 설원'(Snowfield of Grief, 일부 번역 Snowfield of Lament)을 공개했습니다. 한국 서버에는 9월 9일 적용되며, 메커닉 중심 레이드에 3단계 난이도, Hard에서 Tier 4 장비, 신규 인장 장비 칸이 도입됩니다.",
      sourceNote: "Inven Global 2026년 9월 8일자 NC 라이브 방송 보도를 기반으로, 2026년 9월 9일자 공식 한국 업데이트 노트(모두 2026-09-09 확인)와 교차 검증했습니다.",
      keywords: ["아이온2 슬픔의 설원 레이드", "아이온2 Snowfield of Lament 성역", "아이온2 신규 레이드 2026년 9월", "아이온2 델트라스 보스", "아이온2 Tier 4 해방된 화이트 나이트"],
      sections: [
        section("raid-details", "신규 성역: 슬픔의 설원", "전원의 완벽한 동기화를 요구하는 '사이버 합숙'식 메커닉을 배제한, 반응 중심의 신규 레이드입니다. 보스 패턴의 선독·예측이나 시각 확인 즉시 대응이 핵심이라고 NC는 강조했습니다.", "Easy/Normal/Hard 세 단계 난이도로 출시되며, Hard에서는 최종 보스 델트라스의 서버 내 1·2·3위 격파를 기록하는 명예의 전당이 추가됩니다(캐릭터명·서버·혈맹·직업·전투력·장비 점수 등)."),
        section("hard-rewards", "Hard 보상: Tier 4 무기와 가더", "Hard 난이도에서 '해방된 화이트 나이트'(Tier 4) 시리즈 최상위 무기와 가더가 드롭됩니다——현재 한국 서버 최고 제작 등급입니다.", "제작 Tier 4 장비로는 '[True] 창세 용신 / [True] 멸절 용신' 무기·가더가 단계적 성장 구조로 추가됩니다. 샤이닝 아주르/멸절 드래곤 장비를 계승 제작으로 True로 승급할 수 있고, 확장 효과는 소울 각인 옵션을 차지하지 않는 기본 스탯으로 제공됩니다."),
        section("seal-slot", "신규 장비 칸 '인장'", "이번 업데이트에서 새로운 장비 칸인 '인장'이 추가됩니다. 신규 액세서리 '델트라스의 인장(Unique)'은 Easy 난이도부터 획득할 수 있습니다.", "페이블드 등급 인장은 수공예로 제작할 수 있고, 슬픔의 설원에서 얻은 Unique 인장은 계승 제작으로 히어로 등급까지 승급됩니다. 브레이크스루 옵션은 무기 피해 증폭을 올려줍니다."),
        section("chapter1-followups", "Chapter 1 후속 일정", "같은 방송에서 향후 Chapter 1 콘텐츠가 공개됐습니다: 소울 각인 오토 튜닝, 신규 시련 '불의 사원', 마나스톤·정령석·영웅 튜닝 스톤·소울 크리스탈 획득처 확대, 펫 친밀도 난이도 하향, 아르카나 조정, 그리고 직업 밸런스 종합 점검입니다.", "불의 사원에 대해 NC는 기존 시련 바크론이 \"의도보다 쉬웠다\"고 평가하며 \"진정으로 어려운, 말 그대로의 시련이 될 것\"이라고 밝혔습니다. 직업 밸런스는 아비스 필드 보스전과 던전에서의 특정 직업 쏠림을 해소하고 각 직업의 개성을 강화하는 방향으로 검토 중입니다."),
        section("global-relevance", "글로벌 플레이어에게 주는 의미", "이번 업데이트는 한국 서버 대상이며, 글로벌에는 아직 없는 Chapter 1 콘텐츠입니다. 9월 7일 확인된 콘텐츠 모델에 따라 글로벌은 10월 5일 수정판 시즌 1로 출시된 뒤 약 3개월 주기로 한국을 따라갑니다.", "글로벌 플레이어는 이 레이드를 앞으로 맞이할 엔드게임 난이도 곡선의 예고편으로 보면 됩니다: 반응형 메커닉, 3단계 난이도, Tier 4급 성장 구조가 로드맵의 모습입니다."),
      ],
    }),
    "zh-hant": articleCopy(newsLabels, "zh-hant", 6, {
      eyebrow: "韓服更新",
      title: "Aion 2 韓服新團隊副本「Snowfield of Grief」：三難度、Deltras、Tier 4 裝備",
      description: "9 月 9 日韓服更新上線新 Sanctuary 團隊副本「Snowfield of Grief」：Easy/Normal/Hard 三難度、最終 Boss Deltras、Hard 掉落 Tier 4 Liberated White Night 裝備，並新增印章裝備欄",
      intro: "在 9 月 8 日直播中，NCsoft 預覽了新的 Sanctuary 團隊副本「Snowfield of Grief」（亦譯 Snowfield of Lament），韓服 9 月 9 日上線。該副本以機制驅動為賣點，設三檔難度，Hard 掉落 Tier 4 頂級武器與守護者，並引入新的印章裝備欄。",
      sourceNote: "基於 Inven Global 2026 年 9 月 8 日對 NCsoft 直播的報導，並與 2026 年 9 月 9 日官方韓服更新說明交叉核對（均於 2026-09-09 抓取）。全部內容針對韓服；全球版 10 月 5 日以改良版 Season 1 上線，此內容後續才會到達。",
      keywords: ["Aion 2 Snowfield of Grief 團隊副本", "Aion 2 Snowfield of Lament 副本", "Aion 2 新副本 2026年9月", "Aion 2 Deltras Boss", "Aion 2 Tier 4 Liberated White Night"],
      sections: [
        section("raid-details", "新 Sanctuary：Snowfield of Grief", ["「Snowfield of Grief」是以機制驅動的副本，明確避開要求全員完美同步執行的「電競集訓式」機制。NCsoft 強調即時反應——預讀/預判 Boss 動作或憑視覺確認做出反應——將至關重要。", "副本設三檔難度：Easy、Normal、Hard。Hard 的 Sanctuary 新增名人堂，記錄全服對最終 Boss Deltras 的第一、二、三次擊殺，以及通關時的角色名、伺服器、軍團、職業、戰力與裝備評分。"]),
        section("hard-rewards", "Hard 獎勵：Tier 4 武器與守護者", ["Hard 難度掉落「Liberated White Night」（Tier 4）系列的頂級武器與守護者——這是韓服當前最高製作階。", "製作 Tier 4 裝備方面，新增「[True] 創世龍神 / [True] 滅絕龍神」武器與守護者，沿用逐步成長結構：閃亮藍龍/滅絕龍裝備可經傳承製作升級為 True 版，可延展效果作為預設屬性提供，不佔用靈魂刻印位。"]),
        section("seal-slot", "新的印章裝備欄", ["更新還新增一個裝備欄：印章。新飾品「Deltras's Seal（Unique）」從 Easy 難度起即可獲得。", "Fabled 級印章可透過手工製作獲得；Snowfield of Grief 中獲得的 Unique 印章可經傳承製作升級為 Heroic 級。其突破選項可提升武器傷害增幅。"]),
        section("chapter1-followups", "Chapter 1 後續前瞻", ["同一直播公布了後續 Chapter 1 內容：靈魂刻印自動調優系統、新試煉「Temple of Fire」、瑪瑙石/靈魂石/英雄調諧石/靈魂水晶獲取途徑擴展、寵物親密度難度下調、Arcana 調整。", "關於 Temple of Fire，NCsoft 表示現有試煉 Bakron「偏簡單了」，並承諾「這將是一場真正困難、名副其實的試煉」。職業平衡也在全面審查，以解決深淵野外 Boss 與副本中的職業偏科，同時強化各職業特色。"]),
        section("global-relevance", "對全球玩家的意義", ["本次更新針對韓服——它正在運行全球版尚未擁有的 Chapter 1 內容。按 9 月 7 日確認的內容模型，全球版 10 月 5 日以改良版 Season 1 上線，之後以約三個月一季的節奏跟隨韓服。", "對全球玩家而言，把 Snowfield of Grief 視為終局副本難度曲線的預告：機制反應向、三檔難度、Tier 4 級成長，這就是終局路線的形態。"]),
      ],
    }),
  },
};
