import { articleCopy, guideLabels, localizations, publishedVerified, section } from "./trending-september-9-shared";
import type { ContentEntry, ContentHeroImage, ContentSource } from "./content-registry";

/* ARTICLE 5 — September events & Daeva Pass guide: Chalice race, Daeva Look Change Week, Daeva Pass "Flower Bloomed at Night" */

const officialPatchSource: ContentSource = {
  id: "aion2-official-update-2026-09-09",
  kind: "official",
  publisher: "NC Corporation",
  label: "AION 2 Update Notes — September 9, 2026 (events, Daeva Pass)",
  url: "https://aion2.plaync.com/ko-kr/board/update/view?articleId=6aa062386b722c561dc6a46c",
  publishedAt: "2026-09-09",
  retrievedAt: "2026-09-09",
  verifiedAt: "2026-09-09",
  localizations: localizations({
    "zh-hans": "AION 2 更新说明——2026-09-09（活动、Daeva Pass）",
    en: "AION 2 Update Notes — September 9, 2026 (events, Daeva Pass)",
    fr: "Notes de mise à jour AION 2 — 9 septembre 2026 (événements, Daeva Pass)",
    de: "AION-2-Update-Notizen — 9. September 2026 (Events, Daeva Pass)",
    es: "Notas de actualización de AION 2 — 9 de septiembre de 2026 (eventos, Daeva Pass)",
    ja: "AION 2 アップデートノート——2026-09-09（イベント、Daeva Pass）",
    "pt-br": "Notas de atualização do AION 2 — 9 de setembro de 2026 (eventos, Daeva Pass)",
    ru: "Заметки об обновлении AION 2 — 9 сентября 2026 (события, Daeva Pass)",
    ko: "AION 2 업데이트 노트 — 2026-09-09 (이벤트, 데바 패스)",
    "zh-hant": "AION 2 更新說明——2026-09-09（活動、Daeva Pass）",
  }, "https://aion2.plaync.com/ko-kr/board/update/view?articleId=6aa062386b722c561dc6a46c"),
};

const hubSource: ContentSource = {
  id: "aion2hub-update-2026-09-09",
  kind: "third-party",
  publisher: "Aion2Hub",
  label: "AION 2 Patch Notes — September 9, 2026 (Chalice event, Daeva Pass Flower Bloomed at Night)",
  url: "https://aion2hub.com/updates/aion-2-update-2026-09-09",
  publishedAt: "2026-09-09",
  retrievedAt: "2026-09-09",
  verifiedAt: "2026-09-09",
  localizations: localizations({
    "zh-hans": "AION 2 补丁说明——2026-09-09（圣杯活动、Daeva Pass 夜绽之花）",
    en: "AION 2 Patch Notes — September 9, 2026 (Chalice event, Daeva Pass Flower Bloomed at Night)",
    fr: "Notes de patch AION 2 — 9 septembre 2026 (événement Calice, Daeva Pass Flower Bloomed at Night)",
    de: "AION-2-Patch-Notizen — 9. September 2026 (Kelch-Event, Daeva Pass Flower Bloomed at Night)",
    es: "Notas del parche de AION 2 — 9 de septiembre de 2026 (evento Cáliz, Daeva Pass Flower Bloomed at Night)",
    ja: "AION 2 パッチノート——2026-09-09（聖杯イベント、Daeva Pass Flower Bloomed at Night）",
    "pt-br": "Notas de patch do AION 2 — 9 de setembro de 2026 (evento Cálice, Daeva Pass Flower Bloomed at Night)",
    ru: "Патчноуты AION 2 — 9 сентября 2026 (событие Чаши, Daeva Pass Flower Bloomed at Night)",
    ko: "AION 2 패치 노트 — 2026-09-09 (성배 이벤트, 데바 패스 Flower Bloomed at Night)",
    "zh-hant": "AION 2 補丁說明——2026-09-09（聖杯活動、Daeva Pass 夜綻之花）",
  }, "https://aion2hub.com/updates/aion-2-update-2026-09-09"),
};

const eHero: ContentHeroImage = {
  src: "https://blogfiles.ncsoft.net/news/af7330da-4ff6-4b58-aece-400e6061a3be.jpg",
  width: 1200, height: 630,
  credit: "NC Corporation",
  sourceUrl: "https://aion2.plaync.com/en-us/",
  rights: "linked-official-media",
  translations: {
    "zh-hans": { alt: "Aion 2 9 月活动与 Daeva Pass 指南横幅", caption: "9/9 韩服上线三大活动：Snowfield of Lament 首杀竞速（前 20 团获 Void 宠物）、Daeva 换装周（9/9-9/30 装饰半价）、Daeva Pass「夜绽之花」（9/9-10/6）。" },
    en: { alt: "Aion 2 September events and Daeva Pass guide banner", caption: "The September 9 Korean update brings three events: the Snowfield of Lament first-clear race (Void pets for the first 20 forces), Daeva Look Change Week (half-price decoration, Sep 9-30), and the 'Flower Bloomed at Night' Daeva Pass (Sep 9 – Oct 6)." },
    fr: { alt: "Bannière du guide des événements de septembre et du Daeva Pass d'Aion 2", caption: "La mise à jour coréenne du 9 septembre apporte trois événements : la course au premier clear (pets Void pour les 20 premières forces), la Semaine du changement d'apparence (décoration −50 %, 9-30 sept.) et le Daeva Pass « Flower Bloomed at Night » (9 sept. – 6 oct.)." },
    de: { alt: "Banner zum September-Events- und Daeva-Pass-Leitfaden von Aion 2", caption: "Das koreanische Update vom 9. September bringt drei Events: das Erster-Clear-Rennen (Void-Begleiter für die ersten 20 Forces), die Daeva-Look-Change-Week (Dekoration −50 %, 9.-30. Sept.) und den Daeva Pass „Flower Bloomed at Night“ (9. Sept. – 6. Okt.)." },
    es: { alt: "Banner de la guía de eventos de septiembre y Daeva Pass de Aion 2", caption: "La actualización coreana del 9 de septiembre trae tres eventos: la carrera por el primer clear (mascotas Void para las 20 primeras fuerzas), la Semana de Cambio de Apariencia Daeva (decoración al 50 %, 9-30 sept.) y el Daeva Pass «Flower Bloomed at Night» (9 sept. – 6 oct.)." },
    ja: { alt: "Aion 2 9月イベント・Daeva Passガイドバナー", caption: "9/9韓国アップデートで3つのイベント：Snowfield of Lament初クリアレース（上位20部隊にVoidペット）、デ바外見変更ウィーク（9/9-9/30装飾半額）、Daeva Pass「Flower Bloomed at Night」（9/9-10/6）。" },
    "pt-br": { alt: "Banner do guia de eventos de setembro e Daeva Pass do Aion 2", caption: "A atualização coreana de 9 de setembro traz três eventos: a corrida pelo primeiro clear (mascotes Void para as 20 primeiras forças), a Semana de Mudança de Visual Daeva (decoração com 50% de desconto, 9-30 set.) e o Daeva Pass 'Flower Bloomed at Night' (9 set. – 6 out.)." },
    ru: { alt: "Баннер гайда по сентябрьским событиям и Daeva Pass в Aion 2", caption: "Корейское обновление 9 сентября приносит три события: гонку первого клира (питомцы Void первым 20 силам), Неделю смены облика Daeva (декор −50 %, 9–30 сент.) и Daeva Pass «Flower Bloomed at Night» (9 сент. – 6 окт.)." },
    ko: { alt: "Aion 2 9월 이벤트·데바 패스 가이드 배너", caption: "9/9 한국 업데이트로 세 가지 이벤트: 슬픔의 설원 첫 클리어 레이스(상위 20혈맹에 보이드 펫), 데바 외형 변경 위크(9/9-9/30 장식 반값), 데바 패스 '밤에 핀 꽃'(9/9-10/6)." },
    "zh-hant": { alt: "Aion 2 9 月活動與 Daeva Pass 指南橫幅", caption: "9/9 韓服上線三大活動：Snowfield of Lament 首殺競速（前 20 團獲 Void 寵物）、Daeva 換裝週（9/9-9/30 裝飾半價）、Daeva Pass「夜綻之花」（9/9-10/6）。" },
  },
};

export const trendingSeptember9Article5: ContentEntry = {
  section: "guides",
  slug: "aion-2-september-events-daeva-pass-guide",
  schemaType: "Article",
  publishedAt: "2026-09-09",
  updatedAt: "2026-09-09",
  readingMinutes: 6,
  publication: publishedVerified,
  sources: [officialPatchSource, hubSource],
  heroImage: eHero,
  related: [
    { kind: "content", section: "guides", slug: "aion-2-daeva-pass-guide" },
    { kind: "content", section: "guides", slug: "aion-2-moonlit-oasis-daeva-pass-guide" },
    { kind: "content", section: "guides", slug: "aion-2-abyss-system-complete-guide" },
    { kind: "content", section: "guides", slug: "aion-2-early-game-free-gear-progression-guide" },
  ],
  translations: {
    en: articleCopy(guideLabels, "en", 6, {
      eyebrow: "EVENTS GUIDE",
      title: "Aion 2 September Events Guide: Snowfield of Lament First-Clear Race, Daeva Look Change Week, and the Flower Bloomed at Night Daeva Pass",
      description: "The September 9 update's events explained: the 'Be the First to Lift the Chalice' first-clear race with Void pets, Daeva Look Change Week with half-price decoration, and the 'Flower Bloomed at Night' Daeva Pass",
      intro: "The September 9 Korean update launches with three events running alongside the new raid: the 'Be the First to Lift the Chalice' first-clear race in Snowfield of Lament, the Daeva Look Change Week with half-price decoration, and a new Daeva Pass season, 'Flower Bloomed at Night'. Here is what each one offers and how to make the most of them.",
      sourceNote: "Based on the official Korean update notes of September 9, 2026 and the Aion2Hub translation of the same notes (both retrieved September 9, 2026). Dates use Korean service (KST) schedules; the global version launches October 5 with a modified Season 1.",
      keywords: ["Aion 2 first clear race event", "Aion 2 Daeva Look Change Week", "Aion 2 Daeva Pass Flower Bloomed at Night", "Aion 2 Void pet reward", "Aion 2 September events 2026"],
      sections: [
        section("chalice-race", "Be the First to Lift the Chalice: First-Clear Race", ["This event runs from the September 9 maintenance until the 20th force has cleared the new Snowfield of Lament Sanctuary. Placement is decided by the final boss Deltras's defeat time, and only force members present at that moment qualify.", "Rewards are cosmetic bragging rights: the 1st force gets the title 'The First to Break the Sword of Bitter Cold and Ice' plus the Golden Void pet, forces 2-5 get the Silver Void pet, and forces 6-20 get the Bronze Void pet. Payout timing is announced after clear data is checked, and rewards are claimable by mail for one month."]),
        section("look-change-week", "Daeva Look Change Week: Half-Price Decoration", ["From September 9 to September 30, decoration costs are halved — 200 Quna becomes 100 Quna per part, with unlimited changes during the period.", "If you have been sitting on Quna waiting for a good moment to re-skin your character, this two-week window is the cheapest time to do it."]),
        section("daeva-pass-overview", "Daeva Pass 'Flower Bloomed at Night': Overview", ["The new Daeva Pass season runs September 9 to October 6 (05:00), with rewards claimable until the October 7 maintenance. The Basic track costs 2,000,000 Kina (once per server); Premium costs 1,000 Quna plus 30,000 Soul Crystals (soul-bound), also once per server.", "The pass has 50 levels, with a weekly XP cap of 15,000 per character. After level 50, repeat rewards give 500 Soul Crystals on Basic and 3,000 on Premium, and levels can be bought at 50 Quna each."]),
        section("pass-xp-sources", "How to Earn Daeva Pass XP", ["Weekly XP sources per the patch notes: daily attendance 1,000; defeating 10 monsters 60; killing an opposing-faction player 100; Expedition/Transcendence clear 300; Sanctuary clear 700; Shugo Festival 500; successful gear enhancement 10; gear extraction 10.", "The level reward table repeats a 13-level cycle: odd levels give typed Soul Crystals (Cogni, Fera, Natura, Varian, Special) — 300 on Basic, 2,000 on Premium — even levels give plain Soul Crystal (700/3,000), and levels 11-13 (and 24-26, 37-39) give 3x Skin Chests (Weapon/Armor/Accessory, x10), with Splendent versions on Premium. Level 50 gives 1x Splendent Skin Chest (x10) on Basic, 3x on Premium."]),
        section("planning-notes", "Planning Notes", ["1. If you are in a competitive force with raid ambitions, the Chalice race is a single-window opportunity — schedule your Snowfield of Lament attempts early in the event; 2. The pass and the Look Change Week overlap, so a Premium pass plus a decoration pass is the efficient cosmetic season; 3. Weekly XP caps at 15,000 per character — spreading play across the week beats cramming; 4. Promotion items (Neo Ranger and Dark Police suits, Pinky Spin cosmetics) run September 9 to October 21 in the PURPLE store.", "For global players: these events belong to the Korean service. The global launch on October 5 ships a modified Season 1, so expect comparable launch events rather than this exact schedule."]),
      ],
    }),
    "zh-hans": articleCopy(guideLabels, "zh-hans", 6, {
      eyebrow: "活动指南",
      title: "Aion 2 9 月活动指南：Snowfield of Lament 首杀竞速、Daeva 换装周、夜绽之花 Daeva Pass",
      description: "9 月 9 日更新活动详解：「Be the First to Lift the Chalice」首杀竞速（Void 宠物）、Daeva 换装周（装饰半价）、「夜绽之花」Daeva Pass",
      intro: "9 月 9 日韩服更新随新副本同步上线三档活动：Snowfield of Lament 的「Be the First to Lift the Chalice」首杀竞速、装饰半价的 Daeva 换装周，以及新赛季 Daeva Pass「夜绽之花」。本指南说明各自奖励与最大化利用方式。",
      sourceNote: "基于 2026 年 9 月 9 日官方韩服更新说明及 Aion2Hub 的同一说明译文（均于 2026-09-09 抓取）。日期按韩服（KST）日程；全球版 10 月 5 日以改良版 Season 1 上线。",
      keywords: ["Aion 2 首杀竞速活动", "Aion 2 Daeva 换装周", "Aion 2 Daeva Pass 夜绽之花", "Aion 2 Void 宠物奖励", "Aion 2 2026年9月活动"],
      sections: [
        section("chalice-race", "Be the First to Lift the Chalice：首杀竞速", ["活动从 9 月 9 日维护后开始，直至第 20 支队伍通关新副本 Snowfield of Lament。排名由最终 Boss Deltras 的击杀时间决定，仅限当时在场的队伍成员参与评奖。", "奖励为外观向荣誉：第 1 名队伍获得称号「The First to Break the Sword of Bitter Cold and Ice」及黄金 Void 宠物，第 2-5 名获白银 Void 宠物，第 6-20 名获青铜 Void 宠物。发放时间在核对通关数据后公布，邮件领取有效期一个月。"]),
        section("look-change-week", "Daeva 换装周：装饰半价", ["9 月 9 日至 9 月 30 日，装饰费用减半——每部位从 200 Quna 降为 100 Quna，期间变更次数不限。", "如果你一直在等一个好时机给角色换外观，这两周是最便宜的窗口。"]),
        section("daeva-pass-overview", "Daeva Pass「夜绽之花」：总览", ["新赛季 Daeva Pass 于 9 月 9 日至 10 月 6 日 05:00 开放，奖励领取截止 10 月 7 日维护前。基础档 2,000,000 Kina（每服一次）；高级档 1,000 Quna 加 30,000 灵魂水晶（绑定），同样每服一次。", "通行证共 50 级，每角色每周经验上限 15,000。50 级后重复奖励：基础档每次 500 灵魂水晶、高级档 3,000，可花 50 Quna 购买等级。"]),
        section("pass-xp-sources", "如何获取 Daeva Pass 经验", ["补丁说明中的每周经验来源：每日签到 1,000；消灭 10 只怪物 60；击杀敌对阵营玩家 100；远征/超越副本通关 300；Sanctuary 通关 700；修格庆典 500；装备强化成功 10；装备提取 10。", "等级奖励表循环 13 级：奇数级给类型灵魂水晶（Cogni、Fera、Natura、Varian、Special）——基础档 300、高级档 2,000；偶数级给普通灵魂水晶（700/3,000）；11-13 级（及 24-26、37-39）给 3× 皮肤箱（武器/防具/饰品，x10），高级档为 Splendent 版。50 级给 1× Splendent 皮肤箱（x10，基础档）或 3×（高级档）。"]),
        section("planning-notes", "规划提示", ["1. 有竞速志向的强力队伍，圣杯竞速是一次性窗口——尽早安排 Snowfield of Lament 尝试；2. 通行证与换装周时间重叠，高级档通行证+装饰周是高效的外观赛季组合；3. 每周经验上限 15,000/角色——分散到整周游玩比集中冲刺更划算；4. 促销商品（Neo Ranger、Dark Police 套装、Pinky Spin 外观）9 月 9 日至 10 月 21 日在 PURPLE 商店上架。", "对全球玩家：这些活动属于韩服。全球版 10 月 5 日以改良版 Season 1 上线，届时会有对应的首发活动而非完全相同的日程。"]),
      ],
    }),
    fr: articleCopy(guideLabels, "fr", 6, {
      eyebrow: "GUIDE ÉVÉNEMENTS",
      title: "Guide des événements de septembre d'Aion 2 : course au premier clear, Semaine du changement d'apparence, Daeva Pass « Flower Bloomed at Night »",
      description: "Les événements du 9 septembre : la course « Be the First to Lift the Chalice » avec les pets Void, la Semaine du changement d'apparence à moitié prix, et le Daeva Pass « Flower Bloomed at Night »",
      intro: "La mise à jour coréenne du 9 septembre lance trois événements avec le nouveau raid : la course au premier clear « Be the First to Lift the Chalice » dans Snowfield of Lament, la Semaine du changement d'apparence à −50 %, et un nouveau Daeva Pass, « Flower Bloomed at Night ». Voici ce que chacun offre.",
      sourceNote: "Basé sur les notes de mise à jour officielles coréennes du 9 septembre 2026 et la traduction d'Aion2Hub (récupérées le 9 septembre 2026). Dates KST ; le global lance le 5 octobre avec une Saison 1 modifiée.",
      keywords: ["Aion 2 course premier clear", "Aion 2 Semaine changement d'apparence", "Aion 2 Daeva Pass Flower Bloomed at Night", "Aion 2 pet Void", "Aion 2 événements septembre 2026"],
      sections: [
        section("chalice-race", "Be the First to Lift the Chalice : course au premier clear", "Du 9 septembre jusqu'au 20e clear du Sanctuary Snowfield of Lament ; classement par temps de kill de Deltras, membres présents seulement. 1re force : titre + pet Void Or ; 2-5 : Void Argent ; 6-20 : Void Bronze. Distribution après vérification, courrier valable un mois."),
        section("look-change-week", "Semaine du changement d'apparence", "Du 9 au 30 septembre, décoration à moitié prix (200 → 100 Quna par partie, changements illimités). Le moment le moins cher pour refaire le look de son personnage."),
        section("daeva-pass-overview", "Daeva Pass « Flower Bloomed at Night »", "Du 9 septembre au 6 octobre (05:00), récompenses jusqu'à la maintenance du 7 octobre. Basic : 2 000 000 Kina (1×/serveur) ; Premium : 1 000 Quna + 30 000 cristaux d'âme (liés). 50 niveaux, plafond hebdo 15 000 XP/char ; après 50, répétable 500 (Basic) / 3 000 (Premium) cristaux, niveaux achetables à 50 Quna."),
        section("pass-xp-sources", "Gagner de l'XP de pass", "Sources : présence 1 000 ; 10 monstres 60 ; joueur adverse 100 ; expédition/transcendance 300 ; Sanctuary 700 ; Festival Shugo 500 ; amélioration d'équipement réussie 10 ; extraction 10. Table de récompenses cyclique sur 13 niveaux : impairs = cristaux typés (300/2 000), pairs = cristaux simples (700/3 000), 11-13 (24-26, 37-39) = 3× coffres de skins (Splendent en Premium) ; niveau 50 : coffre Splendent 1× (Basic) / 3× (Premium)."),
        section("planning-notes", "Notes de planification", "1. Force compétitive ? La course est une fenêtre unique — tentez Snowfield of Lament tôt ; 2. Le pass et la semaine look se chevauchent ; 3. Plafond 15 000/char/semaine — étalez le jeu ; 4. Promotions (Neo Ranger, Dark Police, Pinky Spin) du 9 septembre au 21 octobre dans la boutique PURPLE. Pour le global : événements coréens ; le lancement du 5 octobre aura ses propres événements."),
      ],
    }),
    de: articleCopy(guideLabels, "de", 6, {
      eyebrow: "EVENTS-LEITFADEN",
      title: "Aion 2 September-Events-Leitfaden: Erster-Clear-Rennen, Daeva-Look-Change-Week, Daeva Pass „Flower Bloomed at Night“",
      description: "Die Events vom 9. September erklärt: das Erster-Clear-Rennen „Be the First to Lift the Chalice“ mit Void-Begleitern, die Daeva-Look-Change-Week mit halbpreisiger Dekoration und der Daeva Pass „Flower Bloomed at Night“",
      intro: "Das koreanische Update vom 9. September startet mit drei Events neben dem neuen Raid: das Erster-Clear-Rennen „Be the First to Lift the Chalice“ in Snowfield of Lament, die Daeva-Look-Change-Week mit halbpreisiger Dekoration und eine neue Daeva-Pass-Saison, „Flower Bloomed at Night“. Hier ist, was jedes bietet.",
      sourceNote: "Basierend auf den offiziellen koreanischen Update-Notizen vom 9. September 2026 und der Aion2Hub-Übersetzung (abgerufen am 9. September 2026). KST-Zeiten; Global startet am 5. Oktober mit modifizierter Season 1.",
      keywords: ["Aion 2 Erster-Clear-Rennen", "Aion 2 Daeva-Look-Change-Week", "Aion 2 Daeva Pass Flower Bloomed at Night", "Aion 2 Void Begleiter", "Aion 2 September-Events 2026"],
      sections: [
        section("chalice-race", "Be the First to Lift the Chalice: Erster-Clear-Rennen", "Vom 9. September bis zum 20. Clear des Sanctuary Snowfield of Lament; Platzierung nach Killzeit von Deltras, nur anwesende Mitglieder. 1. Force: Titel + Golden Void; 2-5: Silver Void; 6-20: Bronze Void. Auszahlung nach Prüfung, Mail ein Monat."),
        section("look-change-week", "Daeva-Look-Change-Week", "9.-30. September: Dekoration halb so teuer (200 → 100 Quna pro Teil, unbegrenzte Änderungen). Die günstigste Zeit zum Umstylen."),
        section("daeva-pass-overview", "Daeva Pass „Flower Bloomed at Night“", "9. September bis 6. Oktober (05:00), Belohnungen bis zur Wartung am 7. Oktober. Basic: 2 000 000 Kina (1×/Server); Premium: 1 000 Quna + 30 000 Seelenkristalle (gebunden). 50 Stufen, Wochenlimit 15 000 XP/Char; nach 50: 500 (Basic) / 3 000 (Premium) Kristalle, Stufen für 50 Quna."),
        section("pass-xp-sources", "Wie du Pass-XP bekommst", "Quellen: Anwesenheit 1 000; 10 Monster 60; gegnerischer Spieler 100; Expedition/Transzendenz 300; Sanctuary 700; Shugo-Festival 500; erfolgreiche Verstärkung 10; Extraktion 10. Belohnungstabelle 13er-Zyklus: ungerade = typisierte Kristalle (300/2 000), gerade = einfache (700/3 000), 11-13 (24-26, 37-39) = 3× Skin-Truhen (Splendent in Premium); Stufe 50: Splendent-Truhe 1× (Basic) / 3× (Premium)."),
        section("planning-notes", "Planungsnotizen", "1. Wettbewerbsfähige Force? Das Rennen ist ein einmaliges Fenster — Snowfield of Lament früh angehen; 2. Pass und Look-Week überlappen; 3. Wochenlimit 15 000/Char — über die Woche verteilen; 4. Promotionen (Neo Ranger, Dark Police, Pinky Spin) vom 9. September bis 21. Oktober im PURPLE-Store. Für Global: koreanische Events; der Start am 5. Oktober bringt eigene Events."),
      ],
    }),
    es: articleCopy(guideLabels, "es", 6, {
      eyebrow: "GUÍA DE EVENTOS",
      title: "Guía de los eventos de septiembre de Aion 2: carrera por el primer clear, Semana de Cambio de Apariencia, Daeva Pass «Flower Bloomed at Night»",
      description: "Los eventos del 9 de septiembre: la carrera «Be the First to Lift the Chalice» con mascotas Void, la Semana de Cambio de Apariencia con decoración al 50 %, y el Daeva Pass «Flower Bloomed at Night»",
      intro: "La actualización coreana del 9 de septiembre lanza tres eventos junto al nuevo raid: la carrera por el primer clear «Be the First to Lift the Chalice» en Snowfield of Lament, la Semana de Cambio de Apariencia Daeva con decoración al 50 %, y una nueva temporada de Daeva Pass, «Flower Bloomed at Night». Esto es lo que ofrece cada uno.",
      sourceNote: "Basado en las notas de actualización oficiales coreanas del 9 de septiembre de 2026 y la traducción de Aion2Hub (recuperadas el 9 de septiembre de 2026). Fechas KST; el global lanza el 5 de octubre con Temporada 1 modificada.",
      keywords: ["Aion 2 carrera primer clear", "Aion 2 Semana Cambio de Apariencia", "Aion 2 Daeva Pass Flower Bloomed at Night", "Aion 2 mascota Void", "Aion 2 eventos septiembre 2026"],
      sections: [
        section("chalice-race", "Be the First to Lift the Chalice: carrera por el primer clear", "Del 9 de septiembre hasta el 20.º clear del Santuario Snowfield of Lament; puesto por tiempo de kill de Deltras, solo miembros presentes. 1.ª fuerza: título + Void Oro; 2-5: Void Plata; 6-20: Void Bronce. Pago tras revisión, correo válido un mes."),
        section("look-change-week", "Semana de Cambio de Apariencia", "Del 9 al 30 de septiembre, decoración a mitad de precio (200 → 100 Quna por parte, cambios ilimitados). El momento más barato para cambiar el look."),
        section("daeva-pass-overview", "Daeva Pass «Flower Bloomed at Night»", "Del 9 de septiembre al 6 de octubre (05:00), recompensas hasta el mantenimiento del 7 de octubre. Basic: 2 000 000 Kina (1×/servidor); Premium: 1 000 Quna + 30 000 cristales de alma (ligados). 50 niveles, tope semanal 15 000 XP/char; tras 50: 500 (Basic) / 3 000 (Premium) cristales, niveles a 50 Quna."),
        section("pass-xp-sources", "Cómo ganar XP del pass", "Fuentes: asistencia 1 000; 10 monstruos 60; jugador rival 100; expedición/trascendencia 300; Santuario 700; Festival Shugo 500; mejora de equipo exitosa 10; extracción 10. Tabla cíclica de 13 niveles: impares = cristales tipados (300/2 000), pares = simples (700/3 000), 11-13 (24-26, 37-39) = 3× cofres de skins (Splendent en Premium); nivel 50: cofre Splendent 1× (Basic) / 3× (Premium)."),
        section("planning-notes", "Notas de planificación", "1. ¿Fuerza competitiva? La carrera es una ventana única — intenta Snowfield of Lament pronto; 2. El pass y la semana look se solapan; 3. Tope 15 000/char/semana — distribuye el juego; 4. Promociones (Neo Ranger, Dark Police, Pinky Spin) del 9 de septiembre al 21 de octubre en la tienda PURPLE. Para el global: eventos coreanos; el lanzamiento del 5 de octubre traerá sus propios eventos."),
      ],
    }),
    ja: articleCopy(guideLabels, "ja", 6, {
      eyebrow: "イベントガイド",
      title: "Aion 2 9月イベントガイド：初クリアレース、デバ外見変更ウィーク、Daeva Pass「Flower Bloomed at Night」",
      description: "9月9日アップデートのイベント解説：「Be the First to Lift the Chalice」初クリアレース（Voidペット）、装飾半額のデバ外見変更ウィーク、「Flower Bloomed at Night」Daeva Pass",
      intro: "9月9日の韓国アップデートは新レイドと同時に3つのイベントを開始します：Snowfield of Lamentの「Be the First to Lift the Chalice」初クリアレース、装飾半額のデバ外見変更ウィーク、そして新シーズンDaeva Pass「Flower Bloomed at Night」。それぞれの報酬と活用法を解説します。",
      sourceNote: "2026年9月9日付公式韓国アップデートノートとAion2Hubの同一訳（いずれも2026-09-09取得）に基づきます。日程は韓国サービス(KST)基準。グローバルは10月5日に改良版シーズン1で開始します。",
      keywords: ["Aion 2 初クリアレース", "Aion 2 デバ外見変更ウィーク", "Aion 2 Daeva Pass Flower Bloomed at Night", "Aion 2 Voidペット", "Aion 2 9月イベント 2026"],
      sections: [
        section("chalice-race", "Be the First to Lift the Chalice：初クリアレース", "9月9日メンテ後から20部隊目のクリアまで。順位は最終ボスDeltrasの撃破時刻で決まり、その場にいた部隊メンバーのみが対象です。1位部隊に称号「The First to Break the Sword of Bitter Cold and Ice」＋ゴールドVoidペット、2-5位にシルバーVoid、6-20位にブロンズVoid。クリアデータ確認後に支給、メールで1か月間受け取り可能。"),
        section("look-change-week", "デバ外見変更ウィーク", "9月9日から9月30日まで装飾費が半額——1部位200クナ→100クナ、期間中変更回数無制限。キャラの見た目変更を検討中なら、この2週間が最も安いタイミングです。"),
        section("daeva-pass-overview", "Daeva Pass「Flower Bloomed at Night」概要", "シーズン期間は9月9日から10月6日05:00まで、報酬受け取りは10月7日メンテ前まで。Basicは2,000,000キナ（サーバーごと1回）、Premiumは1,000クナ＋ソウルクリスタル30,000個（バインド）で、こちらもサーバーごと1回です。", "パスは全50レベル、キャラクターごとの週間XP上限は15,000。50レベル以降は繰り返し報酬でBasic 500／Premium 3,000のソウルクリスタル、レベルは1つ50クナで購入可能です。"),
        section("pass-xp-sources", "パスXPの稼ぎ方", "週間XP源（パッチノートより）：出席1,000；モンスター10体討伐60；敵対陣営プレイヤー撃破100；遠征/超越クリア300；サンクチュアリクリア700；シュゴ祭り500；装備強化成功10；装備抽出10。", "報酬テーブルは13レベル周期：奇数レベルがタイプ別ソウルクリスタル（Cogni/Fera/Natura/Varian/Special、Basic 300／Premium 2,000）、偶数レベルが通常ソウルクリスタル（700/3,000）、11-13（24-26、37-39）が3×スキン宝箱（武器/防具/アクセサリー、x10、PremiumはSplendent版）。50レベルはSplendentスキン宝箱をBasic 1×／Premium 3×。"),
        section("planning-notes", "計画ノート", "1. 上位を狙う部隊ならレースは一度きりのチャンス——イベント序盤にSnowfield of Lamentへ挑戦を; 2. パスと外見変更ウィークは期間が重なるので、Premiumパス＋装飾週の組み合わせがお得; 3. 週間XP上限15,000/キャラ——週内に分散させる方が効率的; 4. プロモ品（Neo Ranger、Dark Police、Pinky Spin）は9月9日〜10月21日、PURPLEストアで販売。グローバル向け：これらのイベントは韓国サービス用。10月5日のローンチでは独自のイベントが想定されます。"),
      ],
    }),
    "pt-br": articleCopy(guideLabels, "pt-br", 6, {
      eyebrow: "GUIA DE EVENTOS",
      title: "Guia dos eventos de setembro do Aion 2: corrida pelo primeiro clear, Semana de Mudança de Visual, Daeva Pass 'Flower Bloomed at Night'",
      description: "Os eventos de 9 de setembro: a corrida 'Be the First to Lift the Chalice' com mascotes Void, a Semana de Mudança de Visual com decoração pela metade e o Daeva Pass 'Flower Bloomed at Night'",
      intro: "A atualização coreana de 9 de setembro lança três eventos junto com o novo raid: a corrida pelo primeiro clear 'Be the First to Lift the Chalice' em Snowfield of Lament, a Semana de Mudança de Visual Daeva com decoração pela metade e uma nova temporada de Daeva Pass, 'Flower Bloomed at Night'. Veja o que cada um oferece.",
      sourceNote: "Baseado nas notas de atualização oficiais coreanas de 9 de setembro de 2026 e na tradução da Aion2Hub (recuperadas em 9 de setembro de 2026). Datas KST; o global lança em 5 de outubro com Temporada 1 modificada.",
      keywords: ["Aion 2 corrida primeiro clear", "Aion 2 Semana Mudança de Visual", "Aion 2 Daeva Pass Flower Bloomed at Night", "Aion 2 mascote Void", "Aion 2 eventos setembro 2026"],
      sections: [
        section("chalice-race", "Be the First to Lift the Chalice: corrida pelo primeiro clear", "De 9 de setembro até o 20.º clear do Santuário Snowfield of Lament; posição pelo tempo de kill de Deltras, só membros presentes. 1.ª força: título + Void Ouro; 2-5: Void Prata; 6-20: Void Bronze. Pagamento após verificação, correio válido por um mês."),
        section("look-change-week", "Semana de Mudança de Visual", "De 9 a 30 de setembro, decoração pela metade (200 → 100 Quna por parte, mudanças ilimitadas). O momento mais barato para mudar o visual."),
        section("daeva-pass-overview", "Daeva Pass 'Flower Bloomed at Night'", "De 9 de setembro a 6 de outubro (05:00), recompensas até a manutenção de 7 de outubro. Basic: 2.000.000 Kina (1×/servidor); Premium: 1.000 Quna + 30.000 cristais de alma (ligados). 50 níveis, teto semanal 15.000 XP/char; após 50: 500 (Basic) / 3.000 (Premium) cristais, níveis a 50 Quna."),
        section("pass-xp-sources", "Como ganhar XP do pass", "Fontes: presença 1.000; 10 monstros 60; jogador rival 100; expedição/transcendência 300; Santuário 700; Festival Shugo 500; aprimoramento de equipamento bem-sucedido 10; extração 10. Tabela cíclica de 13 níveis: ímpares = cristais tipados (300/2.000), pares = simples (700/3.000), 11-13 (24-26, 37-39) = 3× baús de skins (Splendent no Premium); nível 50: baú Splendent 1× (Basic) / 3× (Premium)."),
        section("planning-notes", "Notas de planejamento", "1. Força competitiva? A corrida é uma janela única — tente Snowfield of Lament cedo; 2. O pass e a semana de visual se sobrepõem; 3. Teto 15.000/char/semana — distribua o jogo; 4. Promoções (Neo Ranger, Dark Police, Pinky Spin) de 9 de setembro a 21 de outubro na loja PURPLE. Para o global: eventos coreanos; o lançamento de 5 de outubro terá seus próprios eventos."),
      ],
    }),
    ru: articleCopy(guideLabels, "ru", 6, {
      eyebrow: "ГАЙД ПО СОБЫТИЯМ",
      title: "Гайд по сентябрьским событиям Aion 2: гонка первого клира, Неделя смены облика, Daeva Pass «Flower Bloomed at Night»",
      description: "События обновления 9 сентября: гонка «Be the First to Lift the Chalice» с питомцами Void, Неделя смены облика со скидкой 50 % на декор и Daeva Pass «Flower Bloomed at Night»",
      intro: "Корейское обновление 9 сентября запускает три события вместе с новым рейдом: гонку первого клира «Be the First to Lift the Chalice» в Snowfield of Lament, Неделю смены облика Daeva со скидкой на декор и новый сезон Daeva Pass «Flower Bloomed at Night». Вот что даёт каждое.",
      sourceNote: "На основе официальных корейских заметок об обновлении от 9 сентября 2026 г. и перевода Aion2Hub (получены 9 сентября 2026 г.). Время KST; глобал стартует 5 октября с модифицированным Сезоном 1.",
      keywords: ["Aion 2 гонка первого клира", "Aion 2 Неделя смены облика", "Aion 2 Daeva Pass Flower Bloomed at Night", "Aion 2 питомец Void", "Aion 2 события сентября 2026"],
      sections: [
        section("chalice-race", "Be the First to Lift the Chalice: гонка первого клира", "С 9 сентября до 20-го клира Святилища Snowfield of Lament; место по времени убийства Deltras, только присутствующие члены. 1-я сила: титул + Void Gold; 2–5: Void Silver; 6–20: Void Bronze. Выдача после проверки, почта — месяц."),
        section("look-change-week", "Неделя смены облика", "С 9 по 30 сентября декор вдвое дешевле (200 → 100 Quna за часть, без ограничений на изменения). Самое дешёвое время сменить образ."),
        section("daeva-pass-overview", "Daeva Pass «Flower Bloomed at Night»", "С 9 сентября по 6 октября (05:00), награды до обслуживания 7 октября. Basic: 2 000 000 Kina (1×/сервер); Premium: 1 000 Quna + 30 000 кристаллов душ (связанных). 50 уровней, недельный лимит 15 000 XP/персонаж; после 50: 500 (Basic) / 3 000 (Premium) кристаллов, уровни по 50 Quna."),
        section("pass-xp-sources", "Как получать XP пасса", "Источники: присутствие 1 000; 10 монстров 60; вражеский игрок 100; экспедиция/трансценденция 300; Святилище 700; Фестиваль Шуго 500; успешное улучшение 10; извлечение 10. Таблица — цикл из 13 уровней: нечётные = типизированные кристаллы (300/2 000), чётные = простые (700/3 000), 11–13 (24–26, 37–39) = 3× сундуки скинов (Splendent в Premium); уровень 50: сундук Splendent 1× (Basic) / 3× (Premium)."),
        section("planning-notes", "Заметки по планированию", "1. Конкурентной силе — гонка это разовый шанс: заходите в Snowfield of Lament рано; 2. Пасс и неделя облика перекрываются; 3. Лимит 15 000/персонаж/неделю — растягивайте игру; 4. Промо (Neo Ranger, Dark Police, Pinky Spin) — с 9 сентября по 21 октября в магазине PURPLE. Для глобала: события корейского сервиса; запуск 5 октября принесёт свои события."),
      ],
    }),
    ko: articleCopy(guideLabels, "ko", 6, {
      eyebrow: "이벤트 가이드",
      title: "아이온2 9월 이벤트 가이드: 첫 클리어 레이스, 데바 외형 변경 위크, Daeva Pass '밤에 핀 꽃'",
      description: "9월 9일 업데이트 이벤트 정리: 'Be the First to Lift the Chalice' 첫 클리어 레이스(보이드 펫), 장식 반값 데바 외형 변경 위크, '밤에 핀 꽃' Daeva Pass",
      intro: "9월 9일 한국 업데이트는 신규 레이드와 함께 세 가지 이벤트를 시작합니다: 슬픔의 설원의 'Be the First to Lift the Chalice' 첫 클리어 레이스, 장식비 반값 데바 외형 변경 위크, 그리고 새 시즌 Daeva Pass '밤에 핀 꽃'. 각각의 보상과 활용법을 정리했습니다.",
      sourceNote: "2026년 9월 9일자 공식 한국 업데이트 노트와 Aion2Hub의 동일 번역(모두 2026-09-09 확인)을 기반으로 했습니다. 일정은 한국 서비스(KST) 기준이며, 글로벌은 10월 5일 수정판 시즌 1로 시작합니다.",
      keywords: ["아이온2 첫 클리어 레이스", "아이온2 데바 외형 변경 위크", "아이온2 데바 패스 밤에 핀 꽃", "아이온2 보이드 펫", "아이온2 9월 이벤트 2026"],
      sections: [
        section("chalice-race", "Be the First to Lift the Chalice: 첫 클리어 레이스", "이벤트는 9월 9일 점검 후부터 20번째 혈맹이 신규 성역 슬픔의 설원을 클리어할 때까지 진행됩니다. 순위는 최종 보스 델트라스의 격파 시각으로 결정되며, 그 순간 혈맹에 있던 구성원만 대상입니다.", "보상은 외형적 명예입니다: 1위 혈맹에 칭호 'The First to Break the Sword of Bitter Cold and Ice'와 골드 보이드 펫, 2-5위에 실버 보이드 펫, 6-20위에 브론즈 보이드 펫. 클리어 데이터 확인 후 지급 시기가 공지되며, 우편으로 1개월간 수령 가능합니다."),
        section("look-change-week", "데바 외형 변경 위크: 장식 반값", "9월 9일부터 9월 30일까지 장식 비용이 절반으로 줄어듭니다——부위당 200쿠나 → 100쿠나, 기간 중 변경 횟수 제한 없음.", "쿠나를 아껴두고 캐릭터 외형 변경을 기다리고 있었다면, 이 2주가 가장 저렴한 시기입니다."),
        section("daeva-pass-overview", "Daeva Pass '밤에 핀 꽃': 개요", "새 시즌 데바 패스는 9월 9일부터 10월 6일 05:00까지, 보상 수령은 10월 7일 점검 전까지입니다. 기본 트랙은 2,000,000키나(서버당 1회), 프리미엄은 1,000쿠나 + 소울 크리스탈 30,000개(귀속)로 역시 서버당 1회입니다.", "패스는 총 50레벨이며, 캐릭터당 주간 XP 상한은 15,000입니다. 50레벨 이후 반복 보상은 기본 500 / 프리미엄 3,000개의 소울 크리스탈이고, 레벨은 1개당 50쿠나로 구매할 수 있습니다."),
        section("pass-xp-sources", "데바 패스 XP 획득법", "패치 노트 기준 주간 XP 획득처: 출석 1,000; 몬스터 10마리 처치 60; 적대 진영 플레이어 처치 100; 원정/초월 클리어 300; 성역 클리어 700; 슈고 페스티벌 500; 장비 강화 성공 10; 장비 추출 10.", "레벨 보상 테이블은 13레벨 주기로 반복됩니다: 홀수 레벨은 유형별 소울 크리스탈(Cogni·Fera·Natura·Varian·Special, 기본 300/프리미엄 2,000), 짝수 레벨은 일반 소울 크리스탈(700/3,000), 11-13레벨(및 24-26, 37-39)은 3× 스킨 상자(무기/방어구/악세서리, x10, 프리미엄은 스플렌던트 버전). 50레벨은 스플렌던트 스킨 상자를 기본 1개/프리미엄 3개 지급합니다."),
        section("planning-notes", "계획 노트", "1. 경쟁력 있는 혈맹이라면 성배 레이스는 일회성 기회——이벤트 초반에 슬픔의 설원 도전을 배치하세요; 2. 패스와 외형 변경 위크가 겹치므로 프리미엄 패스+장식 주간 조합이 효율적입니다; 3. 주간 XP 상한 15,000/캐릭터——주간에 분산 플레이가 집중보다 효율적; 4. 프로모션 상품(네오 레인저, 다크 폴리스, 핑키 스핀)은 9월 9일부터 10월 21일까지 PURPLE 스토어에서 판매됩니다.", "글로벌 플레이어에게: 이 이벤트들은 한국 서비스용입니다. 10월 5일 글로벌 출시는 수정판 시즌 1로 시작하므로, 동일한 일정이 아닌 자체 출시 이벤트가 준비될 전망입니다."),
      ],
    }),
    "zh-hant": articleCopy(guideLabels, "zh-hant", 6, {
      eyebrow: "活動指南",
      title: "Aion 2 9 月活動指南：Snowfield of Lament 首殺競速、Daeva 換裝週、夜綻之花 Daeva Pass",
      description: "9 月 9 日更新活動詳解：「Be the First to Lift the Chalice」首殺競速（Void 寵物）、Daeva 換裝週（裝飾半價）、「夜綻之花」Daeva Pass",
      intro: "9 月 9 日韓服更新隨新副本同步上線三檔活動：Snowfield of Lament 的「Be the First to Lift the Chalice」首殺競速、裝飾半價的 Daeva 換裝週，以及新賽季 Daeva Pass「夜綻之花」。本指南說明各自獎勵與最大化利用方式。",
      sourceNote: "基於 2026 年 9 月 9 日官方韓服更新說明及 Aion2Hub 的同一說明譯文（均於 2026-09-09 抓取）。日期按韓服（KST）日程；全球版 10 月 5 日以改良版 Season 1 上線。",
      keywords: ["Aion 2 首殺競速活動", "Aion 2 Daeva 換裝週", "Aion 2 Daeva Pass 夜綻之花", "Aion 2 Void 寵物獎勵", "Aion 2 2026年9月活動"],
      sections: [
        section("chalice-race", "Be the First to Lift the Chalice：首殺競速", ["活動從 9 月 9 日維護後開始，直至第 20 支隊伍通關新副本 Snowfield of Lament。排名由最終 Boss Deltras 的擊殺時間決定，僅限當時在場的隊伍成員參與評獎。", "獎勵為外觀向榮譽：第 1 名隊伍獲得稱號「The First to Break the Sword of Bitter Cold and Ice」及黃金 Void 寵物，第 2-5 名獲白銀 Void 寵物，第 6-20 名獲青銅 Void 寵物。發放時間在核對通關數據後公布，郵件領取有效期一個月。"]),
        section("look-change-week", "Daeva 換裝週：裝飾半價", ["9 月 9 日至 9 月 30 日，裝飾費用減半——每部位從 200 Quna 降為 100 Quna，期間變更次數不限。", "如果你一直在等一個好時機給角色換外觀，這兩週是最便宜的窗口。"]),
        section("daeva-pass-overview", "Daeva Pass「夜綻之花」：總覽", ["新賽季 Daeva Pass 於 9 月 9 日至 10 月 6 日 05:00 開放，獎勵領取截止 10 月 7 日維護前。基礎檔 2,000,000 Kina（每服一次）；高級檔 1,000 Quna 加 30,000 靈魂水晶（綁定），同樣每服一次。", "通行證共 50 級，每角色每週經驗上限 15,000。50 級後重複獎勵：基礎檔每次 500 靈魂水晶、高級檔 3,000，可花 50 Quna 購買等級。"]),
        section("pass-xp-sources", "如何獲取 Daeva Pass 經驗", ["補丁說明中的每週經驗來源：每日簽到 1,000；消滅 10 隻怪物 60；擊殺敵對陣營玩家 100；遠征/超越副本通關 300；Sanctuary 通關 700；修格慶典 500；裝備強化成功 10；裝備提取 10。", "等級獎勵表循環 13 級：奇數級給類型靈魂水晶（Cogni、Fera、Natura、Varian、Special）——基礎檔 300、高級檔 2,000；偶數級給普通靈魂水晶（700/3,000）；11-13 級（及 24-26、37-39）給 3× 皮膚箱（武器/防具/飾品，x10），高級檔為 Splendent 版。50 級給 1× Splendent 皮膚箱（x10，基礎檔）或 3×（高級檔）。"]),
        section("planning-notes", "規劃提示", ["1. 有競速志向的強力隊伍，聖杯競速是一次性窗口——盡早安排 Snowfield of Lament 嘗試；2. 通行證與換裝週時間重疊，高級檔通行證+裝飾週是高效的外觀賽季組合；3. 每週經驗上限 15,000/角色——分散到整週遊玩比集中衝刺更划算；4. 促銷商品（Neo Ranger、Dark Police 套裝、Pinky Spin 外觀）9 月 9 日至 10 月 21 日在 PURPLE 商店上架。", "對全球玩家：這些活動屬於韓服。全球版 10 月 5 日以改良版 Season 1 上線，屆時會有對應的首發活動而非完全相同的日程。"]),
      ],
    }),
  },
};
