import { articleCopy, localizations, newsLabels, publishedVerified, section } from "./trending-august-17-shared";
import type { ContentEntry, ContentHeroImage, ContentSource } from "./content-registry";

/* ARTICLE 1 — Gamescom lineup confirmation */

const gamescomLineupSource1: ContentSource = {
  id: "mmobomb-gamescom-lineup-2026-08-17",
  kind: "third-party", publisher: "MMOBomb",
  label: "NC Teases New Game Announcement For Gamescom",
  url: "https://www.mmobomb.com/news/nc-teases-new-game-announcement-gamescom",
  publishedAt: "2026-08-14",
  retrievedAt: "2026-08-17",
  verifiedAt: "2026-08-17",
  localizations: localizations({
    "zh-hans": "NC 在科隆展前预告新作发布",
    en: "NC Teases New Game Announcement For Gamescom",
    fr: "NC taquine une nouvelle annonce de jeu pour la Gamescom",
    de: "NC teasert neue Spielankündigung für die Gamescom",
    es: "NC adelanta un nuevo anuncio de juego para la Gamescom",
    ja: "NC、Gamescom で新作発表を予告",
    "pt-br": "NC provoca novo anúncio de jogo para a Gamescom",
    ru: "NC дразнит анонсом новой игры на Gamescom",
    ko: "NC, Gamescom에서 신작 발표 예고",
    "zh-hant": "NC 在科隆展前預告新作發布",
  }, "https://www.mmobomb.com/news/nc-teases-new-game-announcement-gamescom"),
};

const gamescomLineupSource2: ContentSource = {
  id: "tech-times-gamescom-2026-08-17",
  kind: "third-party", publisher: "Tech Times",
  label: "AION 2 Opens Western Early Access September 30 as NC Unveils Mystery Game",
  url: "https://www.techtimes.com/articles/2026/08/16/aion-2-opens-western-early-access-september-30-nc-unveils-mystery-game.htm",
  publishedAt: "2026-08-15",
  retrievedAt: "2026-08-17",
  verifiedAt: "2026-08-17",
  localizations: localizations({
    "zh-hans": "AION 2 西方服 9 月 30 日开启抢先体验，NC 公布神秘新作",
    en: "AION 2 Opens Western Early Access September 30 as NC Unveils Mystery Game",
    fr: "L'accès anticipé occidental d'AION 2 débute le 30 septembre, NC dévoile un jeu mystère",
    de: "AION 2 Western-Early-Access startet am 30. September, NC enthüllt Mystery-Spiel",
    es: "El acceso anticipado occidental de AION 2 comienza el 30 de septiembre mientras NC revela un juego misterioso",
    ja: "AION 2 西側早期アクセス9月30日開始、NCが謎の新作を発表",
    "pt-br": "Acesso antecipado ocidental de AION 2 começa em 30 de setembro com NC revelando jogo misterioso",
    ru: "Западный ранний доступ AION 2 начнётся 30 сентября, NC анонсирует загадочную игру",
    ko: "AION 2 서구권 얼리 액세스 9월 30일 시작, NC 미스터리 신작 발표",
    "zh-hant": "AION 2 西方服 9 月 30 日開啟搶先體驗，NC 公布神秘新作",
  }, "https://www.techtimes.com/articles/2026/08/16/aion-2-opens-western-early-access-september-30-nc-unveils-mystery-game.htm"),
};

const gamescomLineupSource3: ContentSource = {
  id: "herald-gamescom-lineup-2026-08-17",
  kind: "third-party", publisher: "Herald Business",
  label: "NCsoft to Unveil 'Aion 2,' 'Cinder City' and More at Gamescom 2026",
  url: "https://biz.heraldcorp.com/article/10833067",
  publishedAt: "2026-08-14",
  retrievedAt: "2026-08-17",
  verifiedAt: "2026-08-17",
  localizations: localizations({
    "zh-hans": "NCsoft 将在 2026 科隆游戏展公布《Aion 2》《Cinder City》等新作",
    en: "NCsoft to Unveil 'Aion 2,' 'Cinder City' and More at Gamescom 2026",
    fr: "NCsoft dévoilera 'Aion 2', 'Cinder City' et plus à la Gamescom 2026",
    de: "NCsoft enthüllt 'Aion 2', 'Cinder City' und mehr auf der Gamescom 2026",
    es: "NCsoft revelará 'Aion 2', 'Cinder City' y más en la Gamescom 2026",
    ja: "NCsoft、Gamescom 2026 で「Aion 2」「Cinder City」などを発表へ",
    "pt-br": "NCsoft vai revelar 'Aion 2', 'Cinder City' e mais na Gamescom 2026",
    ru: "NCsoft представит 'Aion 2', 'Cinder City' и другое на Gamescom 2026",
    ko: "NC소프트, Gamescom 2026에서 'Aion 2' 'Cinder City' 등 공개 예정",
    "zh-hant": "NCsoft 將在 2026 科隆遊戲展公布《Aion 2》《Cinder City》等新作",
  }, "https://biz.heraldcorp.com/article/10833067"),
};

const gamescomHero: ContentHeroImage = {
  src: "https://blogfiles.ncsoft.net/news/af7330da-4ff6-4b58-aece-400e6061a3be.jpg",
  width: 1100, height: 605,
  credit: "NC Corporation",
  sourceUrl: "https://aion2.plaync.com/ko-kr/board/notice",
  rights: "linked-official-media",
  translations: {
    "zh-hans": { alt: "NCSoft Gamescom 2026 阵容公告图", caption: "NC 官方配图；NCSoft 确认将在 2026 科隆游戏展展示三款全球新作。" },
    en: { alt: "NCSoft Gamescom 2026 lineup announcement image", caption: "Official NC artwork; NCSoft confirmed three new global titles for Gamescom 2026." },
    fr: { alt: "Image d'annonce de la line-up NCSoft Gamescom 2026", caption: "Visuel officiel NC ; NCSoft a confirmé trois nouveaux titres mondiaux pour la Gamescom 2026." },
    de: { alt: "NCSoft Gamescom 2026 Lineup-Ankündigungsbild", caption: "Offizielles NC-Artwork; NCSoft bestätigte drei neue globale Titel für die Gamescom 2026." },
    es: { alt: "Imagen de anuncio de la alineación de NCSoft en Gamescom 2026", caption: "Arte oficial de NC; NCSoft confirmó tres nuevos títulos globales para Gamescom 2026." },
    ja: { alt: "NCSoft Gamescom 2026 ラインナップ発表画像", caption: "NC公式アートワーク；NCSoft は Gamescom 2026 でグローバル新作3タイトルを発表予定です。" },
    "pt-br": { alt: "Imagem de anúncio do lineup da NCSoft na Gamescom 2026", caption: "Arte oficial da NC; a NCSoft confirmou três novos títulos globais para a Gamescom 2026." },
    ru: { alt: "Изображение анонса состава NCSoft на Gamescom 2026", caption: "Официальный арт NC; NCSoft подтвердила три новых глобальных проекта для Gamescom 2026." },
    ko: { alt: "NCSoft Gamescom 2026 라인업 공지 이미지", caption: "NC 공식 이미지입니다. NCSoft가 Gamescom 2026에서 글로벌 신작 3종을 공개한다고 확인했습니다." },
    "zh-hant": { alt: "NCSoft Gamescom 2026 陣容公告圖", caption: "NC 官方配圖；NCSoft 確認將在 2026 科隆遊戲展展示三款全球新作。" },
  },
};

export const trendingAugust17Article1: ContentEntry = {
  section: "news",
  slug: "gamescom-2026-ncsoft-lineup-project-bonfire",
  schemaType: "NewsArticle",
  publishedAt: "2026-08-17",
  updatedAt: "2026-08-17",
  readingMinutes: 5,
  publication: publishedVerified,
  sources: [gamescomLineupSource1, gamescomLineupSource2, gamescomLineupSource3],
  heroImage: gamescomHero,
  related: [
    { kind: "content", section: "news", slug: "aion-2-first-global-dev-stream-recap" },
    { kind: "content", section: "guides", slug: "aion-2-global-server-regions-guide" },
    { kind: "content", section: "news", slug: "global-release-september-2026" },
  ],
  translations: {
    en: articleCopy(newsLabels, "en", 5, {
      eyebrow: "GAMESCOM 2026",
      title: "NCSoft Confirms Gamescom 2026 Lineup: Aion 2, Cinder City & Mystery Project Bonfire World Premiere",
      description: "NCSoft will showcase three new global titles at Gamescom 2026 from August 26 in Cologne — Aion 2, the mystery game Cinder City, and Project Bonfire, which gets its world premiere at Opening Night Live.",
      intro: "NCSoft has officially confirmed its Gamescom 2026 lineup, and Aion 2 fans have every reason to pay attention. The Korean developer will bring three new global titles to Cologne — including the much-anticipated Project Bonfire, which will receive its world premiere at Opening Night Live. With Western early access for Aion 2 fast approaching on September 30, the show is expected to hold major launch news.",
      sourceNote: "Based on NCSoft's Gamescom 2026 participation announcements, MMOBomb's August 14 report, Herald Business' lineup coverage, and Tech Times reporting from August 15-16. All details confirmed by NCSoft's official statements.",
      keywords: ["Aion 2 Gamescom 2026", "NCSoft Gamescom lineup", "Project Bonfire premiere", "Cinder City", "Aion 2 early access September 30"],
      sections: [
        section("lineup", "NCSoft's Gamescom 2026 Confirmation", ["NCSoft has confirmed it will participate in Gamescom 2026, which opens in Cologne, Germany on August 26. The developer's booth will showcase three new global titles, signaling an aggressive push to expand beyond its established Korean market.", "Two of the three titles are already known: Aion 2 and the mystery title Cinder City. Reports from mid-August confirmed that 'Aion 2' and 'Cinder City' headline NCSoft's global lineup, with more information promised during the show."]),
        section("bonfire", "Project Bonfire: World Premiere at Opening Night Live", ["The third title, currently referred to only as 'Project Bonfire,' will receive its world premiere at Gamescom's Opening Night Live — the industry's marquee opening show. No genre, platform, or gameplay details have been confirmed yet, making it the biggest unknown of NCSoft's slate.", "For Aion 2 fans, the timing matters: a major new NCSoft title debuting right before Aion 2's global launch suggests the company is building momentum around its global portfolio in one concentrated week."]),
        section("aion2", "What This Means for Aion 2's Global Launch", ["Aion 2's Western early access opens September 30, 2026 — roughly five weeks after Gamescom. NCSoft has already used the August dev stream to detail customization, 8 classes, 5 server regions, and Founder's Packs, and the Gamescom week is the natural moment for launch-window announcements.", "Fans can reasonably watch for a concrete global release date for the free-to-play launch, new trailers, playable builds, or platform details (Steam and PURPLE) — though NCSoft has not confirmed any specific Aion 2 show-floor plans beyond its presence in the lineup."]),
        section("follow", "How to Follow the Announcements", ["Gamescom 2026 runs from August 26 in Cologne, with Opening Night Live airing on the evening before the show floor opens. Aion 2 players should follow NCSoft's official channels and Gamescom's broadcast to catch the Project Bonfire premiere and any Aion 2 reveals.", "Bookmark the AION2 KINA hub — we will summarize every Aion 2 announcement from Gamescom week as it lands, alongside launch-prep guidance for the September 30 early access."]),
      ],
    }),
    "zh-hans": articleCopy(newsLabels, "zh-hans", 5, {
      eyebrow: "2026 科隆游戏展",
      title: "NCSoft 确认 2026 科隆游戏展阵容：Aion 2、Cinder City 与神秘新作 Project Bonfire 世界首秀",
      description: "NCSoft 将在 8 月 26 日开幕的 2026 科隆游戏展上展示三款面向全球市场的新作——Aion 2、神秘新作 Cinder City，以及在开幕之夜现场（Opening Night Live）全球首秀的 Project Bonfire。",
      intro: "NCSoft 正式确认了 2026 科隆游戏展参展阵容，Aion 2 玩家有充分的理由关注。这家韩国开发商将携三款面向全球市场的新作亮相科隆——其中备受期待的 Project Bonfire 将在 Opening Night Live 上全球首秀。随着 Aion 2 西方服抢先体验（9 月 30 日）临近，业界普遍预期此次展会将公布重磅上线信息。",
      sourceNote: "基于 NCSoft 官方参展声明、MMOBomb 8 月 14 日报道、Herald Business 阵容报道以及 Tech Times 8 月 15-16 日报道。所有细节均经 NCSoft 官方公告确认。",
      keywords: ["Aion 2 科隆游戏展", "NCSoft 科隆阵容", "Project Bonfire 首秀", "Cinder City", "Aion 2 抢先体验 9月30日"],
      sections: [
        section("lineup", "NCSoft 确认 2026 科隆游戏展阵容", ["NCSoft 已确认将参加 2026 年 8 月 26 日开幕的科隆游戏展（Gamescom）。开发商展台将展示三款面向全球市场的新作，标志着其积极拓展韩国本土以外市场的战略意图。", "三款新作中两款已公开：Aion 2 与神秘新作 Cinder City。8 月中旬的多家报道确认，『Aion 2』与『Cinder City』位列 NCSoft 全球阵容前列，更多信息将在展会期间公布。"]),
        section("bonfire", "Project Bonfire：开幕之夜现场世界首秀", ["第三款新作目前仅以『Project Bonfire』代称，将在科隆游戏展开幕秀 Opening Night Live 上进行世界首秀。目前尚未确认其类型、平台或玩法细节，是 NCSoft 全部参展作品中最大的未知数。", "对 Aion 2 玩家而言，时机意味深长：一款重量级 NCSoft 新作恰在 Aion 2 全球上线前首秀，表明该公司正围绕全球产品组合在集中的一周内营造声势。"]),
        section("aion2", "对 Aion 2 全球上线的意义", ["Aion 2 西方服抢先体验将于 2026 年 9 月 30 日开启——距科隆游戏展约五周。NCSoft 已通过 8 月的开发者直播详述了自定义、8 职业、5 个服务器区域与创始人包，科隆周正是发布上线窗口信息的自然时机。", "玩家可以合理期待具体的免费游玩全球上线日期、新预告片、可玩版本或平台（Steam 与 PURPLE）细节——尽管 NCSoft 尚未确认除参展外任何针对 Aion 2 的现场活动计划。"]),
        section("follow", "如何跟进官方公告", ["2026 科隆游戏展于 8 月 26 日开幕，Opening Night Live 在展会现场开放前一晚播出。Aion 2 玩家应关注 NCSoft 官方渠道与 Gamescom 直播，捕捉 Project Bonfire 首秀及任何 Aion 2 相关内容。", "收藏 AION2 KINA 中心站——我们将在科隆周期间第一时间汇总每一项 Aion 2 公告，并同步提供 9 月 30 日抢先体验的上线准备指南。"]),
      ],
    }),
    ko: articleCopy(newsLabels, "ko", 5, {
      eyebrow: "게임스컴 2026",
      title: "NCSoft, Gamescom 2026 라인업 확정: Aion 2, Cinder City, 미스터리 신작 Project Bonfire 월드 프리미어",
      description: "NCSoft는 8월 26일 쾰른에서 개막하는 Gamescom 2026에서 글로벌 신작 3종을 선보입니다 — Aion 2, 미스터리 게임 Cinder City, 그리고 개막쇼 Opening Night Live에서 월드 프리미어되는 Project Bonfire.",
      intro: "NCSoft가 Gamescom 2026 참가 라인업을 공식 확정했습니다. 한국 개발사는 쾰른에서 글로벌 신작 3종을 선보이며, 그중 기대작 Project Bonfire는 Opening Night Live에서 월드 프리미어를 맞이합니다. Aion 2 서구권 얼리 액세스(9월 30일)가 다가오면서, 이번 쇼에서 출시 관련 주요 소식이 나올 것으로 예상됩니다.",
      sourceNote: "NCSoft 공식 참가 발표, MMOBomb 8월 14일 보도, Herald Business 라인업 보도, Tech Times 8월 15-16일 보도에 기반합니다. 모든 세부 사항은 NCSoft 공식 발표로 확인되었습니다.",
      keywords: ["Aion 2 게임스컴 2026", "NCSoft 게임스컴 라인업", "Project Bonfire 프리미어", "Cinder City", "Aion 2 얼리 액세스 9월 30일"],
      sections: [
        section("lineup", "NCSoft의 Gamescom 2026 라인업 확정", ["NCSoft는 2026년 8월 26일 독일 쾰른에서 개막하는 Gamescom 2026 참가를 확정했습니다. 부스에서는 글로벌 신작 3종을 공개하며, 한국 시장을 넘어 글로벌 확장을 위한 적극적인 행보를 보여줄 전망입니다.", "3종 중 2종은 이미 알려졌습니다: Aion 2와 미스터리 타이틀 Cinder City. 8월 중순 보도에 따르면 'Aion 2'와 'Cinder City'가 NCSoft 글로벌 라인업의 핵심이며, 쇼 기간 동안 더 많은 정보가 공개될 예정입니다."]),
        section("bonfire", "Project Bonfire: Opening Night Live 월드 프리미어", ["세 번째 타이틀은 현재 'Project Bonfire'로만 알려져 있으며, 게임스컴 개막쇼인 Opening Night Live에서 월드 프리미어를 맞이합니다. 장르, 플랫폼, 게임플레이 세부 사항은 아직 확인되지 않아 NCSoft 라인업 중 가장 큰 미스터리입니다.", "Aion 2 팬에게 중요한 점: Aion 2 글로벌 출시 직전에 대형 NCSoft 신작이 데뷔한다는 것은, 회사가 한 주에 글로벌 포트폴리오를 집중적으로 알릴 준비를 하고 있음을 시사합니다."]),
        section("aion2", "Aion 2 글로벌 출시에 미치는 의미", ["Aion 2 서구권 얼리 액세스는 2026년 9월 30일 시작됩니다 — 게임스컴 이후 약 5주 뒤입니다. NCSoft는 이미 8월 개발자 스트림에서 커스터마이징, 8개 클래스, 5개 서버 지역, 파운더스 팩을 상세히 공개했으며, 게임스컴 주가 출시 창구 발표의 자연스러운 시점입니다.", "팬들은 무료 플레이 정식 출시의 구체적인 날짜, 새 트레일러, 플레이 가능한 빌드, 또는 플랫폼(Steam 및 PURPLE) 세부 사항을 기대할 수 있습니다 — 다만 NCSoft는 라인업 참가 외에 Aion 2 관련 구체적인 현장 계획은 아직 확인하지 않았습니다."]),
        section("follow", "발표를 따라가는 방법", ["Gamescom 2026은 8월 26일 쾰른에서 개막하며, Opening Night Live는 전시장이 열리기 전날 저녁에 방송됩니다. Aion 2 플레이어는 NCSoft 공식 채널과 게임스컴 방송을 팔로우해 Project Bonfire 프리미어와 Aion 2 발표를 놓치지 마세요.", "AION2 KINA 허브를 즐겨찾기에 추가하세요 — 게임스컴 주간의 모든 Aion 2 발표를 가장 먼저 요약하고, 9월 30일 얼리 액세스 준비 가이드도 제공합니다."]),
      ],
    }),
    ja: articleCopy(newsLabels, "ja", 5, {
      eyebrow: "ゲームズコム2026",
      title: "NCSoft が Gamescom 2026 ラインナップ確定：Aion 2、Cinder City、ミステリー新作 Project Bonfire の世界初公開",
      description: "NCSoft は8月26日ケルンで開幕する Gamescom 2026 でグローバル新作3タイトルを披露します — Aion 2、ミステリーゲーム Cinder City、そしてオープニングナイトライブで世界初公開される Project Bonfire。",
      intro: "NCSoft が Gamescom 2026 のラインナップを正式に確定しました。ケルンでは3つのグローバル新作を披露し、その中でも注目の Project Bonfire はオープニングナイトライブで世界初公開されます。Aion 2 の西側早期アクセス（9月30日）が迫る中、このショーでの大型発表が期待されています。",
      sourceNote: "NCSoft の公式参加発表、MMOBomb 8月14日報道、Herald Business のラインナップ報道、Tech Times 8月15-16日報道に基づきます。すべての詳細は NCSoft 公式発表で確認済みです。",
      keywords: ["Aion 2 Gamescom 2026", "NCSoft Gamescom ラインナップ", "Project Bonfire 初公開", "Cinder City", "Aion 2 早期アクセス 9月30日"],
      sections: [
        section("lineup", "NCSoft の Gamescom 2026 ラインナップ確定", ["NCSoft は2026年8月26日にケルンで開幕する Gamescom 2026 への参加を確定しました。ブースではグローバル新作3タイトルを披露し、韓国市場を超えたグローバル展開への積極姿勢を示します。", "3タイトルのうち2つはすでに判明しています：Aion 2 とミステリー新作 Cinder City。8月中旬の報道では『Aion 2』『Cinder City』がラインナップの中心とされ、ショー期間中にさらなる情報が公開される見込みです。"]),
        section("bonfire", "Project Bonfire：オープニングナイトライブで世界初公開", ["3つ目のタイトルは現在『Project Bonfire』としてのみ知られ、Gamescom の幕開けを飾るオープニングナイトライブで世界初公開されます。ジャンル、プラットフォーム、ゲームプレイの詳細は未確認で、NCSoft のラインアップで最大の未知数です。", "Aion 2 ファンにとって重要なのはこのタイミングです：Aion 2 のグローバルローンチ直前に大型新作がデビューすることは、同社が1週間にグローバルポートフォリオを集中アピールする準備をしていることを示唆します。"]),
        section("aion2", "Aion 2 のグローバルローンチへの意味", ["Aion 2 の西側早期アクセスは2026年9月30日に開始されます — Gamescom から約5週間後です。NCSoft はすでに8月の開発者ストリームでカスタマイズ、8クラス、5サーバーリージョン、ファウンダーズパックを詳述しており、Gamescom 週はローンチウィンドウ発表の自然なタイミングです。", "ファンは無料プレイ正式リリースの具体的な日付、新トレーラー、プレイアブルビルド、またはプラットフォーム（Steam と PURPLE）の詳細を期待できます — ただし NCSoft は、ラインナップ参加以外の Aion 2 固有の現地プランは未確認です。"]),
        section("follow", "発表をフォローする方法", ["Gamescom 2026 は8月26日にケルンで開幕し、オープニングナイトライブは会場オープン前夜に放送されます。Aion 2 プレイヤーは NCSoft 公式チャンネルと Gamescom の放送をフォローして、Project Bonfire の初公開や Aion 2 の発表を見逃さないようにしましょう。", "AION2 KINA ハブをブックマークしてください — Gamescom 週の Aion 2 発表をすべてリアルタイムでまとめ、9月30日早期アクセス向けの準備ガイドも提供します。"]),
      ],
    }),
    fr: articleCopy(newsLabels, "fr", 5, {
      eyebrow: "GAMESCOM 2026",
      title: "NCSoft confirme sa line-up Gamescom 2026 : Aion 2, Cinder City et la première mondiale du mystérieux Project Bonfire",
      description: "NCSoft présentera trois nouveaux titres mondiaux à la Gamescom 2026 (à partir du 26 août à Cologne) : Aion 2, le jeu mystère Cinder City et Project Bonfire, dont la première mondiale aura lieu à l'Opening Night Live.",
      intro: "NCSoft a confirmé sa line-up Gamescom 2026, et les fans d'Aion 2 ont toutes les raisons d'être attentifs. Le studio coréen amènera trois nouveaux titres mondiaux à Cologne — dont l'anticipé Project Bonfire, qui sera présenté en première mondiale à l'Opening Night Live.",
      sourceNote: "Basé sur les annonces officielles de NCSoft, le rapport de MMOBomb du 14 août, la couverture de Herald Business et les reportages de Tech Times des 15-16 août.",
      keywords: ["Aion 2 Gamescom 2026", "line-up NCSoft Gamescom", "première Project Bonfire", "Cinder City", "accès anticipé Aion 2 30 septembre"],
      sections: [
        section("lineup", "La line-up Gamescom 2026 de NCSoft", ["NCSoft a confirmé sa participation à la Gamescom 2026, qui ouvre ses portes à Cologne le 26 août. Trois nouveaux titres mondiaux seront présentés sur le stand.", "Deux sont connus : Aion 2 et le jeu mystère Cinder City. D'autres informations sont promises pendant le salon."]),
        section("bonfire", "Project Bonfire : première mondiale à l'Opening Night Live", ["Le troisième titre, nommé 'Project Bonfire', recevra sa première mondiale à l'Opening Night Live. Aucun détail de genre, plateforme ou gameplay n'est confirmé.", "Le timing compte pour les fans d'Aion 2 : un grand nouveau titre NCSoft débute juste avant le lancement mondial d'Aion 2."]),
        section("aion2", "Ce que cela signifie pour le lancement mondial d'Aion 2", ["L'accès anticipé occidental d'Aion 2 ouvre le 30 septembre 2026, environ cinq semaines après la Gamescom. La semaine Gamescom est le moment naturel pour des annonces de fenêtre de lancement.", "Les fans peuvent surveiller une date de sortie mondiale concrète, de nouvelles bandes-annonces ou des détails de plateforme (Steam et PURPLE)."]),
        section("follow", "Comment suivre les annonces", ["La Gamescom 2026 se déroule du 26 août à Cologne, avec l'Opening Night Live la veille de l'ouverture. Suivez les chaînes officielles de NCSoft et la diffusion Gamescom.", "Ajoutez le hub AION2 KINA à vos favoris — nous résumerons chaque annonce Aion 2 de la semaine Gamescom."]),
      ],
    }),
    de: articleCopy(newsLabels, "de", 5, {
      eyebrow: "GAMESCOM 2026",
      title: "NCSoft bestätigt Gamescom-2026-Lineup: Aion 2, Cinder City und die Weltpremiere von Project Bonfire",
      description: "NCSoft wird auf der Gamescom 2026 (ab 26. August in Köln) drei neue globale Titel zeigen – Aion 2, das Mystery-Spiel Cinder City und Project Bonfire, dessen Weltpremiere in der Opening Night Live stattfindet.",
      intro: "NCSoft hat sein Gamescom-2026-Lineup offiziell bestätigt, und Aion-2-Fans haben allen Grund aufzupassen. Das koreanische Studio bringt drei neue globale Titel nach Köln – darunter das lang erwartete Project Bonfire mit Weltpremiere in der Opening Night Live.",
      sourceNote: "Basierend auf NCSofts offiziellen Ankündigungen, MMOBomb-Bericht vom 14. August, Herald-Business-Berichterstattung und Tech-Times-Reportagen vom 15.-16. August.",
      keywords: ["Aion 2 Gamescom 2026", "NCSoft Gamescom Lineup", "Project Bonfire Premiere", "Cinder City", "Aion 2 Early Access 30. September"],
      sections: [
        section("lineup", "NCSofts Gamescom-2026-Lineup", ["NCSoft hat die Teilnahme an der Gamescom 2026 bestätigt, die am 26. August in Köln beginnt. Am Stand werden drei neue globale Titel gezeigt.", "Zwei sind bekannt: Aion 2 und das Mystery-Spiel Cinder City. Weitere Informationen sind während der Messe versprochen."]),
        section("bonfire", "Project Bonfire: Weltpremiere in der Opening Night Live", ["Der dritte Titel, bisher nur als 'Project Bonfire' bekannt, feiert seine Weltpremiere in der Opening Night Live. Genre, Plattform und Gameplay sind noch offen.", "Das Timing ist für Aion-2-Fans bedeutsam: Ein großes neues NCSoft-Spiel debütiert direkt vor dem globalen Launch von Aion 2."]),
        section("aion2", "Bedeutung für Aion 2s globalen Launch", ["Der westliche Early Access von Aion 2 startet am 30. September 2026 – rund fünf Wochen nach der Gamescom. Die Gamescom-Woche ist der natürliche Moment für Launch-Fenster-Ankündigungen.", "Fans können auf ein konkretes Veröffentlichungsdatum, neue Trailer oder Plattformdetails (Steam und PURPLE) achten."]),
        section("follow", "So verfolgen Sie die Ankündigungen", ["Die Gamescom 2026 läuft ab dem 26. August in Köln, mit Opening Night Live am Vorabend. Folgen Sie NCSofts offiziellen Kanälen und dem Gamescom-Stream.", "Lesezeichen Sie sich den AION2-KINA-Hub – wir fassen jede Aion-2-Ankündigung der Gamescom-Woche zusammen."]),
      ],
    }),
    es: articleCopy(newsLabels, "es", 5, {
      eyebrow: "GAMESCOM 2026",
      title: "NCSoft confirma su alineación para Gamescom 2026: Aion 2, Cinder City y el estreno mundial del misterioso Project Bonfire",
      description: "NCSoft mostrará tres nuevos títulos globales en Gamescom 2026 (desde el 26 de agosto en Colonia): Aion 2, el juego misterio Cinder City y Project Bonfire, cuyo estreno mundial será en Opening Night Live.",
      intro: "NCSoft ha confirmado oficialmente su alineación para Gamescom 2026, y los fans de Aion 2 tienen razones de sobra para prestar atención. El estudio coreano llevará tres nuevos títulos globales a Colonia, incluido el esperado Project Bonfire, que tendrá su estreno mundial en Opening Night Live.",
      sourceNote: "Basado en los anuncios oficiales de NCSoft, el informe de MMOBomb del 14 de agosto, la cobertura de Herald Business y los reportajes de Tech Times del 15-16 de agosto.",
      keywords: ["Aion 2 Gamescom 2026", "alineación NCSoft Gamescom", "estreno Project Bonfire", "Cinder City", "acceso anticipado Aion 2 30 de septiembre"],
      sections: [
        section("lineup", "La alineación de NCSoft para Gamescom 2026", ["NCSoft ha confirmado su participación en Gamescom 2026, que abre el 26 de agosto en Colonia. Se mostrarán tres nuevos títulos globales.", "Dos son conocidos: Aion 2 y el juego misterio Cinder City. Se promete más información durante el evento."]),
        section("bonfire", "Project Bonfire: estreno mundial en Opening Night Live", ["El tercer título, llamado 'Project Bonfire', tendrá su estreno mundial en Opening Night Live. No se confirman detalles de género, plataforma o jugabilidad.", "El momento es clave para los fans de Aion 2: un gran nuevo título de NCSoft debuta justo antes del lanzamiento global de Aion 2."]),
        section("aion2", "Qué significa para el lanzamiento global de Aion 2", ["El acceso anticipado occidental de Aion 2 abre el 30 de septiembre de 2026, unas cinco semanas después de Gamescom. La semana Gamescom es el momento natural para anuncios de ventana de lanzamiento.", "Los fans pueden esperar una fecha de lanzamiento mundial concreta, nuevos tráileres o detalles de plataforma (Steam y PURPLE)."]),
        section("follow", "Cómo seguir los anuncios", ["Gamescom 2026 se celebra desde el 26 de agosto en Colonia, con Opening Night Live la víspera. Siga los canales oficiales de NCSoft y la transmisión de Gamescom.", "Marque el hub de AION2 KINA: resumiremos cada anuncio de Aion 2 de la semana Gamescom."]),
      ],
    }),
    "pt-br": articleCopy(newsLabels, "pt-br", 5, {
      eyebrow: "GAMESCOM 2026",
      title: "NCSoft confirma lineup da Gamescom 2026: Aion 2, Cinder City e estreia mundial do misterioso Project Bonfire",
      description: "A NCSoft mostrará três novos títulos globais na Gamescom 2026 (a partir de 26 de agosto em Colônia): Aion 2, o jogo misterioso Cinder City e Project Bonfire, com estreia mundial na Opening Night Live.",
      intro: "A NCSoft confirmou oficialmente seu lineup para a Gamescom 2026, e fãs de Aion 2 têm todos os motivos para prestar atenção. O estúdio coreano levará três novos títulos globais a Colônia, incluindo o aguardado Project Bonfire, que terá estreia mundial na Opening Night Live.",
      sourceNote: "Baseado nos anúncios oficiais da NCSoft, no relatório da MMOBomb de 14 de agosto, na cobertura da Herald Business e nas reportagens da Tech Times de 15-16 de agosto.",
      keywords: ["Aion 2 Gamescom 2026", "lineup NCSoft Gamescom", "estreia Project Bonfire", "Cinder City", "acesso antecipado Aion 2 30 de setembro"],
      sections: [
        section("lineup", "O lineup da NCSoft na Gamescom 2026", ["A NCSoft confirmou participação na Gamescom 2026, que abre em 26 de agosto em Colônia. Três novos títulos globais serão exibidos.", "Dois são conhecidos: Aion 2 e o jogo misterioso Cinder City. Mais informações são prometidas durante o evento."]),
        section("bonfire", "Project Bonfire: estreia mundial na Opening Night Live", ["O terceiro título, chamado 'Project Bonfire', terá estreia mundial na Opening Night Live. Nenhum detalhe de gênero, plataforma ou gameplay confirmado.", "O momento importa para fãs de Aion 2: um grande novo título da NCSoft estreia logo antes do lançamento global de Aion 2."]),
        section("aion2", "O que isso significa para o lançamento global de Aion 2", ["O acesso antecipado ocidental de Aion 2 abre em 30 de setembro de 2026, cerca de cinco semanas após a Gamescom. A semana da Gamescom é o momento natural para anúncios de janela de lançamento.", "Fãs podem esperar data de lançamento global concreta, novos trailers ou detalhes de plataforma (Steam e PURPLE)."]),
        section("follow", "Como acompanhar os anúncios", ["A Gamescom 2026 acontece a partir de 26 de agosto em Colônia, com Opening Night Live na véspera. Siga os canais oficiais da NCSoft e a transmissão da Gamescom.", "Marque o hub AION2 KINA: resumiremos cada anúncio de Aion 2 da semana Gamescom."]),
      ],
    }),
    ru: articleCopy(newsLabels, "ru", 5, {
      eyebrow: "GAMESCOM 2026",
      title: "NCSoft подтвердила состав Gamescom 2026: Aion 2, Cinder City и мировая премьера загадочной Project Bonfire",
      description: "NCSoft покажет три новых глобальных проекта на Gamescom 2026 (с 26 августа в Кёльне): Aion 2, загадочную Cinder City и Project Bonfire, чья мировая премьера состоится в Opening Night Live.",
      intro: "NCSoft официально подтвердила состав участников Gamescom 2026, и у фанатов Aion 2 есть все основания внимательно следить за событием. Корейская студия привезёт в Кёльн три новых глобальных проекта — включая ожидаемую Project Bonfire с мировой премьерой в Opening Night Live.",
      sourceNote: "На основе официальных анонсов NCSoft, отчёта MMOBomb от 14 августа, материалов Herald Business и репортажей Tech Times от 15-16 августа.",
      keywords: ["Aion 2 Gamescom 2026", "состав NCSoft Gamescom", "премьера Project Bonfire", "Cinder City", "ранний доступ Aion 2 30 сентября"],
      sections: [
        section("lineup", "Состав NCSoft на Gamescom 2026", ["NCSoft подтвердила участие в Gamescom 2026, которая открывается 26 августа в Кёльне. На стенде будут показаны три новых глобальных проекта.", "Два из них известны: Aion 2 и загадочная Cinder City. На выставке обещаны новые подробности."]),
        section("bonfire", "Project Bonfire: мировая премьера в Opening Night Live", ["Третий проект, известный как 'Project Bonfire', получит мировую премьеру в Opening Night Live. Жанр, платформы и геймплей пока не подтверждены.", "Время важно для фанатов Aion 2: крупный новый проект NCSoft дебютирует прямо перед глобальным запуском Aion 2."]),
        section("aion2", "Что это значит для глобального запуска Aion 2", ["Западный ранний доступ Aion 2 стартует 30 сентября 2026 года — примерно через пять недель после Gamescom. Неделя Gamescom — естественный момент для анонсов окна запуска.", "Фанаты могут ждать конкретную дату мирового релиза, новые трейлеры или детали платформ (Steam и PURPLE)."]),
        section("follow", "Как следить за анонсами", ["Gamescom 2026 пройдёт с 26 августа в Кёльне, Opening Night Live — накануне открытия. Следите за официальными каналами NCSoft и трансляцией Gamescom.", "Добавьте хаб AION2 KINA в закладки — мы соберём все анонсы Aion 2 за неделю Gamescom."]),
      ],
    }),
    "zh-hant": articleCopy(newsLabels, "zh-hant", 5, {
      eyebrow: "2026 科隆遊戲展",
      title: "NCSoft 確認 2026 科隆遊戲展陣容：Aion 2、Cinder City 與神秘新作 Project Bonfire 世界首秀",
      description: "NCSoft 將在 8 月 26 日開幕的 2026 科隆遊戲展上展示三款面向全球市場的新作——Aion 2、神秘新作 Cinder City，以及在開幕之夜現場（Opening Night Live）全球首秀的 Project Bonfire。",
      intro: "NCSoft 正式確認了 2026 科隆遊戲展參展陣容，Aion 2 玩家有充分的理由關注。這家韓國開發商將攜三款面向全球市場的新作亮相科隆——其中備受期待的 Project Bonfire 將在 Opening Night Live 上全球首秀。隨著 Aion 2 西方服搶先體驗（9 月 30 日）臨近，業界普遍預期此次展會將公布重磅上線資訊。",
      sourceNote: "基於 NCSoft 官方參展聲明、MMOBomb 8 月 14 日報導、Herald Business 陣容報導以及 Tech Times 8 月 15-16 日報導。所有細節均經 NCSoft 官方公告確認。",
      keywords: ["Aion 2 科隆遊戲展", "NCSoft 科隆陣容", "Project Bonfire 首秀", "Cinder City", "Aion 2 搶先體驗 9月30日"],
      sections: [
        section("lineup", "NCSoft 確認 2026 科隆遊戲展陣容", ["NCSoft 已確認將參加 2026 年 8 月 26 日開幕的科隆遊戲展（Gamescom）。開發商展台將展示三款面向全球市場的新作，標誌著其積極拓展韓國本土以外市場的戰略意圖。", "三款新作中兩款已公開：Aion 2 與神秘新作 Cinder City。8 月中的多家報導確認，《Aion 2》與《Cinder City》位列 NCSoft 全球陣容前列，更多資訊將在展會期間公布。"]),
        section("bonfire", "Project Bonfire：開幕之夜現場世界首秀", ["第三款新作目前僅以《Project Bonfire》代稱，將在科隆遊戲展開幕秀 Opening Night Live 上進行世界首秀。目前尚未確認其類型、平台或玩法細節，是 NCSoft 全部參展作品中最大的未知數。", "對 Aion 2 玩家而言，時機意味深長：一款重量級 NCSoft 新作恰在 Aion 2 全球上線前首秀，表明該公司正圍繞全球產品組合在集中的一週內營造聲勢。"]),
        section("aion2", "對 Aion 2 全球上線的意義", ["Aion 2 西方服搶先體驗將於 2026 年 9 月 30 日開啟——距科隆遊戲展約五週。NCSoft 已透過 8 月的開發者直播詳述了自訂、8 職業、5 個伺服器區域與創始人包，科隆週正是發布上線窗口資訊的自然時機。", "玩家可以合理期待具體的免費遊玩全球上線日期、新預告片、可玩版本或平台（Steam 與 PURPLE）細節——儘管 NCSoft 尚未確認除參展外任何針對 Aion 2 的現場活動計畫。"]),
        section("follow", "如何跟進官方公告", ["2026 科隆遊戲展於 8 月 26 日開幕，Opening Night Live 在展會現場開放前一晚播出。Aion 2 玩家應關注 NCSoft 官方管道與 Gamescom 直播，捕捉 Project Bonfire 首秀及任何 Aion 2 相關內容。", "收藏 AION2 KINA 中心站——我們將在科隆週期間第一時間彙總每一項 Aion 2 公告，並同步提供 9 月 30 日搶先體驗的上線準備指南。"]),
      ],
    }),
  },
};