import { articleCopy, localizations, guideLabels, publishedVerified, section } from "./trending-september-16-shared";
import type { ContentEntry, ContentHeroImage, ContentSource } from "./content-registry";

const classSource: ContentSource = {
  id: "nc-aion2-official-classes",
  kind: "official",
  publisher: "NC Corporation",
  label: "Aion 2 Official — Class System",
  url: "https://aion2.plaync.com/en-us/gameplay/",
  publishedAt: "2026-08-15",
  retrievedAt: "2026-09-16",
  verifiedAt: "2026-09-16",
  localizations: localizations({
    "zh-hans": "Aion 2 官方 — 职业系统", en: "Aion 2 Official — Class System",
    fr: "Aion 2 Officiel — Système de Classes", de: "Aion 2 Offiziell — Klassensystem",
    es: "Aion 2 Oficial — Sistema de Clases", ja: "Aion 2 公式 — クラスシステム",
    "pt-br": "Aion 2 Oficial — Sistema de Classes", ru: "Aion 2 Официальный — Система Классов",
    ko: "Aion 2 공식 — 클래스 시스템", "zh-hant": "Aion 2 官方 — 職業系統",
  }, "https://aion2.plaync.com/en-us/gameplay/"),
};

const classHero: ContentHeroImage = {
  src: "https://blogfiles.ncsoft.net/news/af7330da-4ff6-4b58-aece-400e6061a3be.jpg",
  width: 1200, height: 630,
  credit: "NC Corporation", sourceUrl: "https://aion2.plaync.com/en-us/", rights: "linked-official-media",
  translations: {
    "zh-hans": { alt: "Aion 2 转职指南横幅", caption: "Aion 2 转职机制完全指南——费用、限制、策略和注意事项。" },
    en: { alt: "Aion 2 Class Switching Guide Banner", caption: "Complete guide to Aion 2 class switching mechanics — costs, limitations, strategy, and considerations." },
    fr: { alt: "Bannière Guide Changement de Classe Aion 2", caption: "Guide complet des mécaniques de changement de classe dans Aion 2 — coûts, limites, stratégie." },
    de: { alt: "Aion 2 Klassenwechsel-Guide Banner", caption: "Kompletter Guide zum Klassenwechsel in Aion 2 — Kosten, Einschränkungen, Strategie." },
    es: { alt: "Banner Guía Cambio de Clase Aion 2", caption: "Guía completa de las mecánicas de cambio de clase en Aion 2 — costes, limitaciones, estrategia." },
    ja: { alt: "Aion 2 クラス切替ガイドバナー", caption: "Aion 2クラス切替メカニクス完全ガイド——コスト、制限、戦略。" },
    "pt-br": { alt: "Banner Guia Troca de Classe Aion 2", caption: "Guia completo das mecânicas de troca de classe no Aion 2 — custos, limitações, estratégia." },
    ru: { alt: "Баннер Гайд по Смене Класса Aion 2", caption: "Полное руководство по механике смены класса в Aion 2 — стоимость, ограничения, стратегия." },
    ko: { alt: "Aion 2 클래스 전환 가이드 배너", caption: "Aion 2 클래스 전환 메커니즘 완전 가이드 — 비용, 제한, 전략." },
    "zh-hant": { alt: "Aion 2 轉職指南橫幅", caption: "Aion 2 轉職機制完全指南——費用、限制、策略和注意事項。" },
  },
};

export const trendingSeptember16Article3: ContentEntry = {
  section: "guides",
  slug: "aion-2-class-switching-guide",
  schemaType: "Article",
  publishedAt: "2026-09-16",
  updatedAt: "2026-09-16",
  readingMinutes: 5,
  publication: publishedVerified,
  sources: [classSource],
  heroImage: classHero,
  related: [
    { kind: "content", section: "guides", slug: "aion-2-launch-classes-guide" },
    { kind: "content", section: "guides", slug: "aion-2-class-tier-list-guide" },
    { kind: "content", section: "guides", slug: "aion-2-trinity-roles-guide" },
    { kind: "content", section: "guides", slug: "aion-2-skill-preset-overhaul-guide" },
  ],
  translations: {
    en: articleCopy(guideLabels, "en", 5, {
      eyebrow: "CLASS SYSTEM",
      title: "Aion 2 Class Switching Guide: How to Change Class, Costs, Strategy, and What Carries Over",
      description: "Complete guide to Aion 2 class switching — learn the mechanics, costs, cooldowns, what transfers between classes, and when switching makes strategic sense.",
      intro: "Aion 2's class switching system lets you change your character's class without starting over. This guide covers everything you need to know about the switching mechanics, costs, limitations, and strategic considerations for making the most of this system.",
      sourceNote: "Based on NC's official class system documentation and Korean service mechanics as of September 2026.",
      keywords: ["Aion 2 class switching", "Aion 2 change class", "Aion 2 respec", "Aion 2 class transfer", "Aion 2 class switch cost"],
      sections: [
        section("switching-mechanics", "How Class Switching Works", ["Class switching in Aion 2 is available after completing the introductory quest chain at approximately level 10. You visit a Class Mastery NPC in any major city to initiate the switch. The process is instant — your character is immediately converted to the new class with all class-specific attributes recalculated.", "There are no class restrictions on switching — you can switch to any of the available classes regardless of your current class. However, some classes may require you to have completed specific introductory content before they become available as switch targets.", "The switching process preserves your character level, equipped gear, and inventory. What changes is your skill set, passive abilities, and class-specific resource system (mana, rage, energy, etc.)."]),
        section("costs-and-cooldowns", "Costs and Cooldowns", ["Each class switch costs a fixed amount of Kinah that scales with your level. At low levels (10-20), the cost is minimal — approximately 5,000-10,000 Kinah. At higher levels (40+), the cost increases to 50,000-100,000 Kinah per switch.", "After switching, there is a cooldown period of 7 days before you can switch again. This prevents rapid class-hopping and encourages players to commit to a class for a meaningful period. The cooldown is account-wide per character, not shared across your account.", "Your skill points are NOT refunded automatically when you switch. You will need to reallocate them manually using the skill reset option (which has its own separate cost). Plan your switch to include the skill reset cost in your budget."]),
        section("what-transfers", "What Carries Over When Switching", ["Your character level, experience progress, and equipped gear all carry over to the new class. However, gear that is class-specific (certain weapons or armor types) will be unequipped and returned to your inventory. You may need to acquire new gear suitable for your new class.", "Quest progress that is not class-specific continues normally. Class-specific quest chains will be reset — you will need to complete the new class's introductory quest chain to unlock class-specific content.", "Your Stigma slots and their unlock progress carry over, but the equipped Stigma skills are reset. You will need to re-equip Stigma skills appropriate for your new class. Skill presets you created for your old class remain saved but will not be usable until you switch back to that class."]),
        section("when-to-switch", "When to Switch Classes", ["The most common reason to switch is dissatisfaction with your current class's playstyle. If you find yourself not enjoying combat or feeling mismatched with your role, switching to a class that fits your preferences is a good investment.", "Meta shifts from balance patches can also make switching strategic. If your class falls significantly in the tier list after a patch, switching to a stronger class can improve your group content performance and PvP effectiveness.", "Some players switch to fill role shortages in their guild. If your guild needs a tank or healer and you have a DPS class, switching to fill that role benefits both you and your group. The ability to switch freely means you are never locked into a role you do not enjoy."]),
        section("switching-strategy", "Switching Strategy and Tips", ["Before committing to a switch, try the new class through the free trial system if available. Some events allow you to temporarily try classes before committing Kinah to a permanent switch. Use these opportunities to test your preferred build.", "Plan your switch around content timing. If a major dungeon or PvP season is starting, ensure your new class is geared and skilled up before diving in. Do not switch the day before a content release — give yourself time to relearn your rotation.", "Keep a Kinah reserve for the first switch. Between the switch cost, skill reset, and potential gear changes, the total expense can be 2-3x the base switch cost. Budget accordingly and avoid switching when your finances are tight."]),
      ],
    }),
    "zh-hans": articleCopy(guideLabels, "zh-hans", 5, {
      eyebrow: "职业系统",
      title: "Aion 2 转职指南：如何转职、费用、策略及继承内容",
      description: "Aion 2 转职完全指南——了解机制、费用、冷却时间、职业间继承内容和策略考量。",
      intro: "Aion 2 的转职系统让你可以更换角色职业而无需重新创建。本指南覆盖转职机制、费用、限制和策略考量的一切内容。",
      sourceNote: "基于 NC 官方职业系统文档和韩服机制（截至 2026 年 9 月）。",
      keywords: ["Aion 2 转职", "Aion 2 换职业", "Aion 2 洗点", "Aion 2 职业转换", "Aion 2 转职费用"],
      sections: [
        section("switching-mechanics", "转职如何运作", ["Aion 2 在完成约 10 级的入门任务链后可转职。前往任何主要城市的职业精通 NPC 发起转换。过程即时——角色立即转为新职业并重新计算职业属性。", "转职没有职业限制——可以转到任何可用职业。但某些职业可能需要完成特定入门内容才能作为转职目标。", "转换过程保留角色等级、装备和背包。变化的是技能组、被动属性和职业专属资源系统。"]),
        section("costs-and-cooldowns", "费用与冷却", ["每次转职花费固定 Kinah，随等级增长。低等级（10-20）费用约 5,000-10,000 Kinah。高等级（40+）增至 50,000-100,000 Kinah。", "转职后有 7 天冷却期才能再次转职。防止频繁切换并鼓励玩家投入一定时间。冷却按角色计算，不跨账号共享。", "转职时技能点不会自动退还。需要手动用技能重置选项重新分配（有额外费用）。预算时包含重置费用。"]),
        section("what-transfers", "转职继承内容", ["角色等级、经验进度和装备全部继承。但职业专属装备（某些武器或护甲类型）会卸下回到背包。可能需要获取新职业适用装备。", "非职业专属任务进度正常继续。职业专属任务链会重置——需完成新职业入门任务链解锁职业专属内容。", "烙印槽和解锁进度继承，但装备的烙印技能重置。需重新装备适合新职业的烙印技能。为旧职业创建的预设保留但不能使用，直到转回该职业。"]),
        section("when-to-switch", "何时转职", ["最常见原因是对当前职业玩法不满意。如果你发现自己不喜欢战斗或与角色不匹配，转到符合偏好的职业是不错的投资。", "平衡补丁的 meta 变化也可成为转职策略。如果职业在补丁后大幅下降，转到更强职业可提升团队和 PvP 表现。", "有些玩家转职填补公会角色短缺。如果公会需要坦克或治疗而你是 DPS，转职填补该角色对双方都有利。"]),
        section("switching-strategy", "转职策略与提示", ["在承诺转职前，通过免费试用系统尝试新职业。部分活动允许临时试用职业再花 Kinah 永久转职。利用这些机会测试偏好构建。", "围绕内容时间规划转职。如果大型副本或 PvP 赛季即将开始，确保新职业装备和技能到位后再投入。不要在内容发布前一天转职——给自己时间重新学习循环。", "保留首次转职的 Kinah 储备。加上转职费、技能重置和可能的装备更换，总费用可能是基础转职费的 2-3 倍。预算充足时再转职。"]),
      ],
    }),
    fr: articleCopy(guideLabels, "fr", 5, {
      eyebrow: "SYSTÈME DE CLASSES",
      title: "Guide Changement de Classe d'Aion 2 : Comment Changer, Coûts, Stratégie",
      description: "Guide complet du changement de classe dans Aion 2 — mécaniques, coûts, temps de recharge, ce qui est transféré et considérations stratégiques.",
      intro: "Le système de changement de classe d'Aion 2 vous permet de changer la classe de votre personnage sans recommencer.",
      sourceNote: "Basé sur la documentation officielle du système de classes de NC et les mécaniques du serveur coréen (septembre 2026).",
      keywords: ["Changement classe Aion 2", "Changer classe Aion 2", "Respec Aion 2"],
      sections: [
        section("switching-mechanics", "Comment Fonctionne le Changement", ["Le changement de classe est disponible après la chaîne de quêtes introductive au niveau 10 environ. Visitez un PNJ de Maîtrise de Classe pour initier le changement. Processus instantané.", "Aucune restriction de classe — vous pouvez changer vers n'importe quelle classe disponible.", "Le processus préserve votre niveau, équipement et inventaire. Ce qui change : compétences, passifs et système de ressources."]),
        section("costs-and-cooldowns", "Coûts et Temps de Recharge", ["Chaque changement coûte un montant fixe de Kinah qui évolue avec votre niveau. À bas niveaux : 5 000-10 000. À hauts niveaux : 50 000-100 000.", "Après le changement, 7 jours de temps de recharge avant de pouvoir changer à nouveau.", "Vos points de compétences ne sont PAS remboursés automatiquement. Vous devrez les réallouer manuellement."]),
        section("what-transfers", "Ce Qui est Conservé", ["Votre niveau, progression d'XP et équipement sont conservés. L'équipement spécifique à une classe sera déséquipé.", "La progression des quêtes non-spécifiques continue normalement. Les quêtes spécifiques à la classe sont réinitialisées.", "Vos slots de Stigma et leur progression sont conservés, mais les compétences Stigma équipées sont réinitialisées."]),
        section("when-to-switch", "Quand Changer de Classe", ["La raison la plus courante : l'insatisfaction avec le style de jeu de votre classe actuelle.", "Les changements de meta peuvent aussi rendre le changement stratégique.", "Certains joueurs changent pour combler des pénuries de rôles dans leur guilde."]),
        section("switching-strategy", "Stratégie et Conseils", ["Avant de vous engager, essayez la nouvelle classe via le système d'essai gratuit si disponible.", "Planifiez votre changement autour du timing des contenus.", "Gardez une réserve de Kinah pour le premier changement. Le coût total peut être 2-3x le coût de base."]),
      ],
    }),
    de: articleCopy(guideLabels, "de", 5, {
      eyebrow: "KLASSENSYSTEM",
      title: "Aion 2 Klassenwechsel-Guide: Wie Man Die Klasse Wechselt, Kosten, Strategie",
      description: "Kompletter Guide zum Klassenwechsel in Aion 2 — Mechaniken, Kosten, Cooldowns, Übertragung und strategische Überlegungen.",
      intro: "Das Klassenwechselsystem von Aion 2 ermöglicht es Ihnen, die Klasse Ihres Charakters zu ändern ohne neu anzufangen.",
      sourceNote: "Basierend auf NCs offizieller Klassensystem-Dokumentation und dem koreanischen Server (September 2026).",
      keywords: ["Aion 2 Klassenwechsel", "Aion 2 Klasse ändern", "Aion 2 Respec"],
      sections: [
        section("switching-mechanics", "Wie der Klassenwechsel Funktioniert", ["Klassenwechsel ist nach Abschluss der Einführungs-Questkette bei etwa Level 10 verfügbar. Besuchen Sie einen Klassenmeister-NPC.", "Keine Klassenbeschränkungen — Sie können zu jeder verfügbaren Klasse wechseln.", "Der Prozess bewahrt Level, Ausrüstung und Inventar."]),
        section("costs-and-cooldowns", "Kosten und Cooldowns", ["Jeder Wechsel kostet eine feste Menge Kinah die mit dem Level skaliert. Niedrige Level: 5.000-10.000. Hohe Level: 50.000-100.000.", "Nach dem Wechsel gibt es 7 Tage Cooldown.", "Fähigkeitspunkte werden NICHT automatisch erstattet."]),
        section("what-transfers", "Was Übernommen Wird", ["Level, EP-Fortschritt und Ausrüstung werden übernommen. Klassenspezifische Ausrüstung wird abgelegt.", "Nicht-klassenspezifische Questfortschritte werden normal fortgesetzt.", "Stigma-Slots werden übernommen, aber ausgerüstete Stigma-Fähigkeiten werden zurückgesetzt."]),
        section("when-to-switch", "Wann Die Klasse Wechseln", ["Häufigster Grund: Unzufriedenheit mit dem Spielstil der aktuellen Klasse.", "Meta-Veränderungen durch Balance-Patches können Wechsel strategisch machen.", "Manche Spieler wechseln um Rollen-Engpässe in ihrer Gilde zu füllen."]),
        section("switching-strategy", "Wechsel-Strategie und Tipps", ["Vor dem Wechsel testen Sie die neue Klasse durch das kostenlose Testsystem.", "Planen Sie Ihren Wechsel um das Content-Timing.", "Halten Sie eine Kinah-Reserve für den ersten Wechsel bereit."]),
      ],
    }),
    es: articleCopy(guideLabels, "es", 5, {
      eyebrow: "SISTEMA DE CLASES",
      title: "Guía de Cambio de Clase de Aion 2: Cómo Cambiar, Costes, Estrategia",
      description: "Guía completa del cambio de clase en Aion 2 — mecánicas, costes, tiempos de espera, qué se transfiere y consideraciones estratégicas.",
      intro: "El sistema de cambio de clase de Aion 2 te permite cambiar la clase de tu personaje sin empezar de nuevo.",
      sourceNote: "Basado en la documentación oficial del sistema de clases de NC (septiembre 2026).",
      keywords: ["Cambio clase Aion 2", "Cambiar clase Aion 2"],
      sections: [
        section("switching-mechanics", "Cómo Funciona el Cambio", ["El cambio está disponible tras completar la cadena introductoria al nivel 10.", "Sin restricciones de clase.", "El proceso conserva nivel, equipo e inventario."]),
        section("costs-and-cooldowns", "Costes y Tiempos de Espera", ["Cada cambio cuesta Kinah fijo escalado por nivel.", "7 días de espera después del cambio.", "Los puntos de habilidad NO se reembolsan automáticamente."]),
        section("what-transfers", "Qué Se Mantiene", ["Nivel, progreso de XP y equipo se mantienen.", "Las misiones no específicas continúan normalmente.", "Tus slots de Stigma se mantienen pero las habilidades equipadas se reinician."]),
        section("when-to-switch", "Cuándo Cambiar de Clase", ["Razón más común: insatisfacción con el estilo de juego.", "Cambios de meta por parches de balance.", "Llenar vacantes de rol en tu gremio."]),
        section("switching-strategy", "Estrategia y Consejos", ["Prueba la nueva clase antes de comprometerte.", "Planifica el cambio alrededor del timing de contenido.", "Guarda una reserva de Kinah."]),
      ],
    }),
    ja: articleCopy(guideLabels, "ja", 5, {
      eyebrow: "クラスシステム",
      title: "Aion 2 クラス切替ガイド：変更方法、コスト、戦略",
      description: "Aion 2のクラス切替完全ガイド——メカニクス、コスト、クールダウン、引き継ぎ内容、戦略的考慮事項。",
      intro: "Aion 2のクラス切替システムでキャラクターのクラスをやり直しなしで変更できます。",
      sourceNote: "NCの公式クラスシステム文書と韓国サーバーメカニクス（2026年9月時点）に基づいています。",
      keywords: ["Aion 2 クラス切替", "Aion 2 クラス変更"],
      sections: [
        section("switching-mechanics", "クラス切替の仕組み", ["クラス切替はレベル10頃の導入クエスト完了後に利用可能です。", "クラス制限なし——任意の利用可能クラスに切替可能。", "プロセスはレベル、装備、インベントリを保持します。"]),
        section("costs-and-cooldowns", "コストとクールダウン", ["各切替はレベルに応じてスケーリングする固定キナコストがかかります。", "切替後、再度切替できるまで7日間のクールダウン。", "スキルポイントは自動で払い戻されません。"]),
        section("what-transfers", "引き継ぎ内容", ["レベル、経験値進行、装備は引き継がれます。", "クラス固有でないクエスト進行は正常に継続。", "スティグマスロットは引き継がれますが、装備スキルはリセット。"]),
        section("when-to-switch", "いつ切替るか", ["最も一般的な理由：現在のクラスのプレイスタイルへの不満。", "バランスパッチによるメタ変化。", "ギルドのロール不足を埋めるため。"]),
        section("switching-strategy", "切替戦略とヒント", ["コミットする前に無料試用システムで新クラスを試してください。", "コンテンツタイミングに合わせて切替を計画。", "最初の切替用にキナを確保。"]),
      ],
    }),
    "pt-br": articleCopy(guideLabels, "pt-br", 5, {
      eyebrow: "SISTEMA DE CLASSES",
      title: "Guia de Troca de Classe do Aion 2: Como Trocar, Custos, Estratégia",
      description: "Guia completo da troca de classe no Aion 2 — mecânicas, custos, cooldowns, o que é transferido e considerações estratégicas.",
      intro: "O sistema de troca de classe do Aion 2 permite mudar a classe do seu personagem sem recomeçar.",
      sourceNote: "Baseado na documentação oficial do sistema de classes da NC (setembro 2026).",
      keywords: ["Troca classe Aion 2", "Mudar classe Aion 2"],
      sections: [
        section("switching-mechanics", "Como Funciona a Troca", ["A troca está disponível após completar a quest introdutória no nível 10.", "Sem restrições de classe.", "O processo preserva nível, equipamento e inventário."]),
        section("costs-and-cooldowns", "Custos e Cooldowns", ["Cada troca custa Kinah fixo escalado por nível.", "7 dias de cooldown após a troca.", "Pontos de habilidade NÃO são reembolsados automaticamente."]),
        section("what-transfers", "O que é Transferido", ["Nível, progresso de XP e equipamento são mantidos.", "Quests não específicas continuam normalmente.", "Slots de Stigma são mantidos mas habilidades equipadas são resetadas."]),
        section("when-to-switch", "Quando Trocar de Classe", ["Razão mais comum: insatisfação com o estilo de jogo.", "Mudanças de meta por patches de balance.", "Preencher faltas de role na guilda."]),
        section("switching-strategy", "Estratégia e Dicas", ["Teste a nova classe antes de se comprometer.", "Planeje a troca em torno do timing de conteúdo.", "Mantenha uma reserva de Kinah."]),
      ],
    }),
    ru: articleCopy(guideLabels, "ru", 5, {
      eyebrow: "СИСТЕМА КЛАССОВ",
      title: "Гайд по Смене Класса Aion 2: Как Сменить, Стоимость, Стратегия",
      description: "Полное руководство по смене класса в Aion 2 — механика, стоимость, кулдауны, что переносится и стратегические соображения.",
      intro: "Система смены класса Aion 2 позволяет изменить класс персонажа без начала заново.",
      sourceNote: "На основе официальной документации системы классов NC (сентябрь 2026).",
      keywords: ["Смена класса Aion 2", "Сменить класс Aion 2"],
      sections: [
        section("switching-mechanics", "Как Работает Смена", ["Смена доступна после завершения вводной цепочки квестов на уровне 10.", "Без ограничений по классам.", "Процесс сохраняет уровень, экипировку и инвентарь."]),
        section("costs-and-cooldowns", "Стоимость и Кулдауны", ["Каждая смена стоит фиксированную сумму Кина.", "7 дней кулдауна после смены.", "Очки навыков НЕ возвращаются автоматически."]),
        section("what-transfers", "Что Переносится", ["Уровень, прогресс опыта и экипировка переносятся.", "Не-классовые квесты продолжаются нормально.", "Слоты Стигмы переносятся, но экипированные навыки сбрасываются."]),
        section("when-to-switch", "Когда Менять Класс", ["Самая частая причина: недовольство стилем игры.", "Изменения меты от патчей баланса.", "Заполнение нехватки ролей в гильдии."]),
        section("switching-strategy", "Стратегия и Советы", ["Перед решением попробуйте новый класс через бесплатную систему.", "Планируйте смену вокруг тайминга контента.", "Держите резерв Кина."]),
      ],
    }),
    ko: articleCopy(guideLabels, "ko", 5, {
      eyebrow: "클래스 시스템",
      title: "Aion 2 클래스 전환 가이드: 변경 방법, 비용, 전략",
      description: "Aion 2 클래스 전환 완전 가이드 — 메커니즘, 비용, 쿨다운, 이전 내용, 전략적 고려사항.",
      intro: "Aion 2의 클래스 전환 시스템으로 캐릭터 클래스를 다시 시작하지 않고 변경할 수 있습니다.",
      sourceNote: "NC 공식 클래스 시스템 문서 기준 (2026년 9월).",
      keywords: ["Aion 2 클래스 전환", "Aion 2 클래스 변경"],
      sections: [
        section("switching-mechanics", "클래스 전환 작동 방식", ["클래스 전환은 약 10레벨 도입 퀘스트 완료 후 이용 가능합니다.", "클래스 제한 없음.", "프로세스는 레벨, 장비, 인벤토리를 보존합니다."]),
        section("costs-and-cooldowns", "비용 및 쿨다운", ["각 전환은 레벨에 따라 스케일링하는 고정 키나 비용이 듭니다.", "전환 후 7일 쿨다운.", "스킬 포인트는 자동 환불되지 않습니다."]),
        section("what-transfers", "이전되는 내용", ["레벨, 경험치 진행, 장비가 이전됩니다.", "비클래스 퀘스트 진행은 정상 계속.", "스티그마 슬롯은 이전되지만 장착 스킬은 리셋됩니다."]),
        section("when-to-switch", "언제 전환할 것인가", ["가장 흔한 이유: 현재 클래스 플레이스타일에 대한 불만.", "밸런스 패치로 인한 메타 변화.", "길드 역할 부족 채우기."]),
        section("switching-strategy", "전환 전략 및 팁", ["전환 전 무료 체험 시스템으로 새 클래스를 시도하세요.", "콘텐츠 타이밍에 맞춰 전환을 계획하세요.", "첫 전환을 위한 키나 예비금을 확보하세요."]),
      ],
    }),
    "zh-hant": articleCopy(guideLabels, "zh-hant", 5, {
      eyebrow: "職業系統",
      title: "Aion 2 轉職指南：如何轉職、費用、策略及繼承內容",
      description: "Aion 2 轉職完全指南——了解機制、費用、冷卻時間、職業間繼承內容和策略考量。",
      intro: "Aion 2 的轉職系統讓你可以更換角色職業而無需重新創建。",
      sourceNote: "基於 NC 官方職業系統文檔和韓服機制（截至 2026 年 9 月）。",
      keywords: ["Aion 2 轉職", "Aion 2 換職業"],
      sections: [
        section("switching-mechanics", "轉職如何運作", ["約 10 級完成入門任務鏈後可轉職。前往主要城市的職業精通 NPC 發起轉換。過程即時。", "轉職沒有職業限制——可以轉到任何可用職業。", "轉換保留角色等級、裝備和背包。變化的是技能組和被動屬性。"]),
        section("costs-and-cooldowns", "費用與冷卻", ["每次轉職花費固定 Kinah 隨等級增長。低等級約 5,000-10,000。高等級增至 50,000-100,000。", "轉職後有 7 天冷卻期。", "轉職時技能點不會自動退還。需手動重新分配。"]),
        section("what-transfers", "轉職繼承內容", ["角色等級、經驗進度和裝備全部繼承。職業專屬裝備會卸下。", "非職業專屬任務進度正常繼續。職業專屬任務鏈會重置。", "烙印槽繼承但裝備的烙印技能重置。"]),
        section("when-to-switch", "何時轉職", ["最常見原因是不喜歡當前職業玩法。", "平衡补丁的 meta 變化。", "填補公會角色短缺。"]),
        section("switching-strategy", "轉職策略與提示", ["轉職前通過免費試用系統嘗試新職業。", "圍繞內容時間規劃轉職。", "保留首次轉職的 Kinah 儲備。"]),
      ],
    }),
  },
};
