import { articleCopy, guideLabels, localizations, publishedVerified, section } from "./trending-september-2-shared";
import type { ContentEntry, ContentHeroImage, ContentSource } from "./content-registry";

/* ARTICLE 5 — Guide: Spacetime Rift Domination mechanics (from the Sept 2 KR update) */

const domSource1: ContentSource = {
  id: "ncsoft-kr-domination-2026-09-02",
  kind: "third-party", publisher: "NCSoft (via Aion2t)",
  label: "아이온2 9월 2일 업데이트 — 시공의 균열 지배전 (규칙과 일정)",
  url: "https://aion2t.com/news/42",
  publishedAt: "2026-09-02",
  retrievedAt: "2026-09-02",
  verifiedAt: "2026-09-02",
  localizations: localizations({
    "zh-hans": "Aion 2 9 月 2 日更新——时空裂隙·统治战（规则与日程）",
    en: "Aion 2 September 2 update — Spacetime Rift Domination (rules and schedule)",
    fr: "Mise à jour Aion 2 du 2 septembre — Domination des Failles (règles et horaires)",
    de: "Aion-2-Update vom 2. September — Spacetime-Rift-Domination (Regeln und Zeitplan)",
    es: "Actualización de Aion 2 del 2 de septiembre — Dominación de Fisuras (reglas y horarios)",
    ja: "Aion 2 9月2日アップデート — 時空の亀裂・支配戦（ルールと日程）",
    "pt-br": "Atualização de 2 de setembro do Aion 2 — Dominação de Fendas (regras e horários)",
    ru: "Обновление Aion 2 от 2 сентября — Доминация Разломов (правила и расписание)",
    ko: "아이온2 9월 2일 업데이트 — 시공의 균열 지배전(규칙과 일정)",
    "zh-hant": "Aion 2 9 月 2 日更新——時空裂隙·統治戰（規則與日程）",
  }, "https://aion2t.com/news/42"),
};

const domSource2: ContentSource = {
  id: "ncsoft-kr-update-original-dom-2026-09-02",
  kind: "third-party", publisher: "NCSOFT",
  label: "아이온2 업데이트 안내 (September 2, 2026, Korean official)",
  url: "https://aion2.plaync.com/ko-kr/board/update/list",
  publishedAt: "2026-09-02",
  retrievedAt: "2026-09-02",
  verifiedAt: "2026-09-02",
  localizations: localizations({
    "zh-hans": "Aion 2 更新公告（2026-09-02，韩服官方）",
    en: "Aion 2 update notes (September 2, 2026, KR official)",
    fr: "Notes de mise à jour d'Aion 2 (2 septembre 2026, officiel KR)",
    de: "Aion-2-Update-Hinweise (2. September 2026, KR offiziell)",
    es: "Notas de actualización de Aion 2 (2 de septiembre de 2026, oficial KR)",
    ja: "Aion 2 更新案内（2026年9月2日、KR公式）",
    "pt-br": "Notas de atualização do Aion 2 (2 de setembro de 2026, oficial KR)",
    ru: "Заметки об обновлении Aion 2 (2 сентября 2026, официально KR)",
    ko: "아이온2 업데이트 안내 (2026-09-02, KR 공식)",
    "zh-hant": "Aion 2 更新公告（2026-09-02，韓服官方）",
  }, "https://aion2.plaync.com/ko-kr/board/update/list"),
};

const domHero: ContentHeroImage = {
  src: "https://blogfiles.ncsoft.net/news/af7330da-4ff6-4b58-aece-400e6061a3be.jpg",
  width: 1100, height: 605,
  credit: "NC Corporation",
  sourceUrl: "https://aion2.plaync.com/ja-jp/board/notice/list",
  rights: "linked-official-media",
  translations: {
    "zh-hans": { alt: "Aion 2 时空裂隙·统治战指南配图", caption: "NC 官方配图；统治战为 9/2 上线的开放世界阵营战：周一/四/六 20:00、23:00，等级 50+、装备分 4,500+、战力 500.0k+、双区要塞扫荡 VI 级门槛，每周 3 枚事件钥匙。" },
    en: { alt: "Aion 2 Spacetime Rift Domination guide image", caption: "Official NC artwork; Domination is the open-world faction war added September 2: Mon/Thu/Sat 20:00 & 23:00, gates at level 50+, item level 4,500+, 500.0k Combat Power and tier-VI Stronghold Sweep in both zones, three Event Keys weekly." },
    fr: { alt: "Image du guide Domination des Failles d'Aion 2", caption: "Visuel officiel NC ; Domination est la guerre de factions ajoutée le 2 septembre : lun/jeu/sam 20:00 et 23:00, portes à niveau 50+, 4 500+ d'équipement, 500,0k de puissance et balayage VI dans les deux zones, trois clés par semaine." },
    de: { alt: "Bild zum Spacetime-Rift-Domination-Leitfaden von Aion 2", caption: "Offizielles NC-Artwork; Domination ist der am 2. September hinzugefügte Fraktionenkrieg: Mo/Do/Sa 20:00 & 23:00, Tore bei Level 50+, Ausrüstung 4.500+, 500,0k Kampfkraft und Festungs-Fegen VI in beiden Zonen, drei Schlüssel pro Woche." },
    es: { alt: "Imagen de la guía de Dominación de Fisuras de Aion 2", caption: "Arte oficial de NC; Dominación es la guerra de facciones añadida el 2 de septiembre: lun/jue/sáb 20:00 y 23:00, requisitos de nivel 50+, 4.500+ de equipo, 500,0k de poder y barrido VI en ambas zonas, tres claves semanales." },
    ja: { alt: "Aion 2 時空の亀裂・支配戦ガイド画像", caption: "NC公式アートワーク；支配戦は9月2日追加のオープンワールド陣営戦：月・木・土 20:00・23:00、レベル50+・装備4,500+・戦闘力500.0k+・両地域6段階掃討が扉、週3個のイベントキー。" },
    "pt-br": { alt: "Imagem do guia de Dominação de Fendas do Aion 2", caption: "Arte oficial da NC; Dominação é a guerra de facções adicionada em 2 de setembro: seg/qui/sáb 20:00 e 23:00, requisitos de nível 50+, 4.500+ de equipamento, 500,0k de poder e varredura VI nas duas zonas, três chaves semanais." },
    ru: { alt: "Изображение руководства по Доминации Разломов Aion 2", caption: "Официальный арт NC; Доминация — война фракций, добавленная 2 сентября: пн/чт/сб 20:00 и 23:00, порог уровня 50+, экипировки 4 500+, силы 500,0k и зачистки VI в обеих зонах, три ключа в неделю." },
    ko: { alt: "Aion 2 시공의 균열 지배전 가이드 이미지", caption: "NC 공식 이미지입니다. 지배전은 9월 2일 추가된 오픈월드 진영전: 월·목·토 20:00·23:00, 레벨 50+·장비 4,500+·전투력 500.0k+·양 지역 6단계 요새 쓸기 문턱, 주당 이벤트 키 3개." },
    "zh-hant": { alt: "Aion 2 時空裂隙·統治戰指南配圖", caption: "NC 官方配圖；統治戰為 9/2 上線的開放世界陣營戰：週一/四/六 20:00、23:00，等級 50+、裝備分 4,500+、戰力 500.0k+、雙區要塞掃蕩 VI 級門檻，每週 3 枚事件鑰匙。" },
  },
};

export const trendingSeptember2Article5: ContentEntry = {
  section: "guides",
  slug: "aion-2-spacetime-rift-domination-guide",
  schemaType: "Article",
  publishedAt: "2026-09-02",
  updatedAt: "2026-09-02",
  readingMinutes: 5,
  publication: publishedVerified,
  sources: [domSource1, domSource2],
  heroImage: domHero,
  related: [
    { kind: "content", section: "news", slug: "aion-2-kr-update-september-2-domination-revert" },
    { kind: "content", section: "guides", slug: "aion-2-great-rebalance-patch-guide" },
    { kind: "content", section: "news", slug: "aion-2-release-date-october-5-2026" },
    { kind: "content", section: "guides", slug: "aion-2-prelaunch-access-routes-guide" },
  ],
  translations: {
    en: articleCopy(guideLabels, "en", 5, {
      eyebrow: "DOMINATION MECHANICS",
      title: "Aion 2 Spacetime Rift Domination: Schedule, Entry Gates, Keys and How to Win",
      description: "Spacetime Rift Domination, the open-world faction war added in the September 2 KR update, runs Mon/Thu/Sat at 20:00 and 23:00 with hard gates (level 50+, item level 4,500+, 500.0k Combat Power, tier-VI Stronghold Sweep) and three weekly Event Keys. This guide breaks down every rule.",
      intro: "The September 2 Aion 2 update made the previously datamined open-world faction war official: Spacetime Rift Domination now has a schedule, a rulebook, and hard entry gates. Because this is the kind of endgame content global players will eventually meet, this guide walks through everything confirmed — when it runs, who can enter, how registration and the Event Key economy work, how stronghold capture and victory are decided, and what the rewards require.",
      sourceNote: "Based on NCSOFT's September 2 Korean update notes as covered by Aion2t, which links the original Korean post. This is a guide to the confirmed rules; the global build's own schedule at launch may differ.",
      keywords: ["Aion 2 Spacetime Rift Domination", "Aion 2 Domination schedule", "Aion 2 Event Key", "Aion 2 faction war guide", "Aion 2 Verteron Altgard PvP"],
      sections: [
        section("schedule", "Schedule and Rotation", ["Domination runs every Monday, Thursday and Saturday at 20:00 and 23:00 — the Spacetime Rift times — with the event active in either Verteron or Altgard.", "Attack and defence swap weekly: week 1 is Verteron with the Elyos defending; week 2 is Altgard with the Asmodians defending.", "Each event lasts about 25 minutes of combat after a 5-minute start window, and the portal stays open for 10 minutes for entry."]),
        section("entry-gates", "The Entry Gates (All Four Required)", ["Character level 50 or higher.", "Item level 4,500 or higher.", "Combat Power 500.0k or higher.", "Achievements: Verteron Stronghold Sweep VI and Altgard Stronghold Sweep VI — meaning every stronghold in both territories cleared. Each gate has its own refusal message, so you will know exactly which one you are missing."]),
        section("keys-and-registration", "Event Keys and Registration", ["Registration happens through the Domination notifier UI while holding at least one Event Key.", "Event Keys: three recharge automatically each week, and one is deducted when you receive the event reward. That weekly three-key cap is a hard ceiling on how often any player can farm the event.", "While the event is live, the [Join] button is only enabled in the defending side's territory, so positioning matters before registration closes."]),
        section("battle-rules", "Battle Rules and How to Win", ["Population: minimum 60 and maximum 200 characters per side. If either team is short, the event does not start.", "During Domination you cannot use Expedition, Transcendence, or Sanctuary content. S-PVP mode turns on when prep ends; only S-PVP characters fight each other, field monsters and normal-mode characters cannot be attacked, and field guards can still attack S-PVP characters.", "Five strongholds in the defending territory form one group, and one of three groups opens at random each event. A stronghold falls when all three monoliths are destroyed.", "Attackers win by taking 3 or more of the 5 strongholds; defenders win by still holding the majority when time runs out."]),
        section("rewards-and-tips", "Rewards and Practical Tips", ["Contribution is earned by destroying monoliths, killing stronghold guards, and killing enemy players. Only players who reach a minimum contribution are paid, and rewards follow the per-class contribution ranking.", "Idling gets you cut — stop contributing long enough and you are removed from the reward list; leave the area and a one-minute clock starts. Kills inside Domination do not count toward field achievements or the Spacetime Rift season kill counters.", "A Domination-only Kisk (attacking side only) holds more people than the Legion Kisk and is sold by the general merchant and Breeze Trading Company. Domination missions were added to the weekly/season server mission list — check them before joining so you earn toward the right objectives."]),
      ],
    }),
    "zh-hans": articleCopy(guideLabels, "zh-hans", 5, {
      eyebrow: "统治战机制",
      title: "Aion 2 时空裂隙·统治战：日程、入场门槛、钥匙与胜败规则",
      description: "9 月 2 日韩服更新上线的开放世界阵营战「时空裂隙·统治战」于周一/四/六 20:00、23:00 举行，硬性门槛（等级 50+、装备分 4,500+、战力 500.0k+、双区要塞扫荡 VI 级）加每周 3 枚事件钥匙。本指南拆解每条规则。",
      intro: "9 月 2 日 Aion 2 更新让此前数据挖掘的开放世界阵营战正式化：时空裂隙·统治战现带日程、规则书与硬入场门槛。这是全球玩家最终会遇到的终局内容，因此本指南覆盖已确认的一切——何时开、谁能进、注册与事件钥匙经济如何运作、要塞夺取与胜负如何判定、奖励需要什么。",
      sourceNote: "基于 NCsoft 2026 年 9 月 2 日韩服官方更新公告（Aion2t 整理并链接韩文原文）。本指南针对已确认规则；全球版上线时的自身日程或有不同。",
      keywords: ["Aion 2 时空裂隙统治战", "Aion 2 统治战日程", "Aion 2 事件钥匙", "Aion 2 阵营战指南", "Aion 2 维尔特伦阿尔特加德PvP"],
      sections: [
        section("schedule", "日程与轮换", ["统治战于每周一、周四、周六 20:00 与 23:00（时空裂隙时刻）在维尔特伦或阿尔特加德举行。", "攻防每周轮换：第一周维尔特伦、埃利奥斯防守；第二周阿尔特加德、阿斯莫迪安防守。", "每次事件在 5 分钟开场窗口后约 25 分钟战斗，传送门保持 10 分钟可入场。"]),
        section("entry-gates", "入场门槛（四项全需）", ["角色等级 50 或以上。", "装备分 4,500 或以上。", "战力 500.0k 或以上。", "成就：维尔特伦要塞扫荡 VI 与阿尔特加德要塞扫荡 VI——即两个区域所有要塞清过。每项门槛有各自的拒绝消息，你会清楚缺哪项。"]),
        section("keys-and-registration", "事件钥匙与注册", ["持有至少 1 枚事件钥匙时，通过统治战通知 UI 注册。", "事件钥匙：每周自动补充 3 枚，每次领取事件奖励消耗 1 枚。每周 3 枚上限是对玩家刷取次数的硬顶。", "事件进行时，[加入]按钮仅在防守方领土内启用——注册关闭前站位很重要。"]),
        section("battle-rules", "战斗规则与胜负", ["人口：每边最少 60、最多 200 人。任一侧人数不足则事件不开。", "期间不可使用远征、超越或圣域内容。准备结束后 S-PVP 模式开启；仅 S-PVP 角色互相攻击，野外怪物与普通模式角色不可被攻击，但野外守卫仍可攻击 S-PVP 角色。", "防守方领土 5 座要塞为一组，每次事件随机开启三组之一。要塞在三个方尖碑全部被毁时陷落。", "进攻方夺取 5 座中 3 座以上获胜；防守方在时间结束时仍占多数则获胜。"]),
        section("rewards-and-tips", "奖励与实用提示", ["贡献来自摧毁方尖碑、击杀要塞守卫与击杀敌方玩家。只有达到最低贡献的玩家获发奖励，且奖励按职业贡献排名发放。", "挂机会被除名——停止贡献足够久就从奖励名单移除；离开区域会启动 1 分钟倒计时。统治战内的击杀不计入野外成就或时空裂隙赛季击杀计数。", "统治战专用基斯克（仅进攻方）比军团基斯克容纳更多人，由普通商人与小精灵贸易公司出售。每周/赛季服务器任务列表新增统治战任务——加入前先查看，以便朝正确目标推进。"]),
      ],
    }),
    ko: articleCopy(guideLabels, "ko", 5, {
      eyebrow: "지배전 메커니즘",
      title: "아이온2 시공의 균열 지배전: 일정, 입장 문턱, 키와 승패 규칙",
      description: "9월 2일 KR 업데이트로 추가된 오픈월드 진영전 '시공의 균열 지배전'은 월·목·토 20:00·23:00에 열리며, 하드 문턱(레벨 50+, 장비 4,500+, 전투력 500.0k+, 양 지역 6단계 요새 쓸기)과 주 3개 이벤트 키가 있습니다. 본 가이드가 모든 규칙을 풀어냅니다.",
      intro: "9월 2일 업데이트로 데이터마이닝에서 알려졌던 오픈월드 진영전이 공식화됐습니다. 지배전은 일정·규칙·하드 입장 문턱을 갖췄습니다. 글로벌 플레이어가 결국 만나게 될 엔드게임 콘텐츠이므로, 확정된 내용을 전부 정리합니다.",
      sourceNote: "NCSOFT 9월 2일 한국 공식 업데이트 공지(Aion2t 정리·원문 링크) 기반. 글로벌 빌드의 출시 시 자체 일정은 다를 수 있습니다.",
      keywords: ["아이온2 시공의 균열 지배전", "아이온2 지배전 일정", "아이온2 이벤트 키", "아이온2 진영전 가이드", "아이온2 베르테론 알트가르트 PvP"],
      sections: [
        section("schedule", "일정과 순환", "지배전은 매주 월·목·토 20:00·23:00(균열 시간)에 베르테론 또는 알트가르트에서 열립니다. 공수는 주 단위로 교대합니다(1주 베르테론 엘리오스 수비, 2주 알트가르트 아스모디안 수비). 시작 창 5분 후 약 25분간 전투하며, 포털은 10분간 입장 가능합니다."),
        section("entry-gates", "입장 문턱(4개 모두 필요)", "레벨 50+, 장비 점수 4,500+, 전투력 500.0k+, 베르테론·알트가르트 요새 쓸기 VI 업적(양 지역 모든 요새 클리어). 각 문턱마다 별도 거절 메시지가 있어 무엇이 부족한지 정확히 알 수 있습니다."),
        section("keys-and-registration", "이벤트 키와 등록", "이벤트 키를 1개 이상 보유한 상태로 지배전 알리미 UI에서 등록합니다. 키는 주당 3개가 자동 충전되고 보상 수령마다 1개가 차감됩니다. 주 3개 상한이 파밍 횟수의 하드 캡입니다. 진행 중 [참가] 버튼은 수비 측 영토에서만 활성화됩니다."),
        section("battle-rules", "전투 규칙과 승패", "한쪽 최소 60·최대 200명. 부족하면 이벤트가 시작되지 않습니다. 진행 중 원정·초월·성역 사용 불가, S-PVP 모드로 참가자끼리만 전투(필드 몬스터·일반 캐릭터 공격 불가, 필드 경비병은 공격 가능). 수비 영토 5개 요새가 한 그룹이며 3개 그룹 중 하나가 무작위로 열립니다. 오벨리스크 3개 모두 파괴 시 요새 함락. 공격자는 5개 중 3개 이상 점령 시 승리, 수비자는 시간 종료 시 다수 보유 시 승리."),
        section("rewards-and-tips", "보상과 실용 팁", "기여도는 오벨리스크 파괴·요새 경비병 처치·적 플레이어 처치로 쌓입니다. 최소 기여에 도달한 플레이어만 보상을 받고, 보상은 직업별 기여 순위를 따릅니다. 놀면 제외되고, 지역을 벗어나면 1분 카운트다운이 시작됩니다. 지배전 내 처치는 필드 업적이나 균열 시즌 킬 카운터에 포함되지 않습니다. 지배전 전용 키스크(공격 측만)는 군단 키스크보다 많은 인원을 수용하며, 주간/시즌 서버 임무에 지배전 임무가 추가됐습니다."),
      ],
    }),
    ja: articleCopy(guideLabels, "ja", 5, {
      eyebrow: "支配戦メカニクス",
      title: "Aion 2 時空の亀裂・支配戦：日程・入場条件・キーと勝敗ルール",
      description: "9月2日KRアップデートで追加されたオープンワールド陣営戦『時空の亀裂・支配戦』は月・木・土 20:00・23:00に開催され、ハードな扉（レベル50+・装備4,500+・戦闘力500.0k+・両地域6段階掃討）と週3個のイベントキーがあります。本ガイドが全ルールを解説します。",
      intro: "9月2日のアップデートで、データマイニングで判明していたオープンワールド陣営戦が正式化しました。支配戦は日程・ルールブック・ハードな入場扉を備えています。グローバルプレイヤーがいつか出会うエンドゲームコンテンツなので、確認済みの内容を全て整理します。",
      sourceNote: "NCSOFT 9月2日韓国公式アップデート告知（Aion2t整理・原文リンク）に基づきます。グローバルビルドの開始時点での独自日程は異なる場合があります。",
      keywords: ["Aion 2 時空の亀裂・支配戦", "Aion 2 支配戦日程", "Aion 2 イベントキー", "Aion 2 陣営戦ガイド", "Aion 2 ベルテロン アルトガルト PvP"],
      sections: [
        section("schedule", "日程とローテーション", "支配戦は毎週月・木・土 20:00・23:00（亀裂時刻）にベルテロンまたはアルトガルトで開催されます。攻守は週ごとに交代（1週目ベルテロン・エリオス守備、2週目アルトガルト・アスモディアン守備）。開始ウィンドウ5分後から約25分の戦闘、ポータルは10分間入場可能です。"),
        section("entry-gates", "入場条件（4つ全て必要）", "レベル50以上、装備スコア4,500以上、戦闘力500.0k以上、ベルテロン・アルトガルト要塞掃討VIの達成（両地域の全要塞クリア）。各条件に専用の拒否メッセージがあり、不足が正確に分かります。"),
        section("keys-and-registration", "イベントキーと登録", "イベントキーを1個以上持った状態で支配戦通知UIから登録します。キーは週3個が自動補充され、報酬受領ごとに1個消費されます。週3個の上限がファーム回数のハードキャップです。進行中[参加]ボタンは守備側の領土でのみ有効です。"),
        section("battle-rules", "戦闘ルールと勝敗", "片側最低60・最大200人。不足なら開始しません。進行中は遠征・超越・聖域が使用不可、S-PVPモードで参加者同士のみ戦闘可（フィールドモンスター・通常キャラは攻撃不可、フィールド警備兵は攻撃可）。守備側領土5要塞が1グループで、3グループのうち1つがランダムに開放。オベリスク3つ全て破壊で要塞陥落。攻撃側は5つ中3つ以上で勝利、守備側は時間切れ時の多数保持で勝利です。"),
        section("rewards-and-tips", "報酬と実用のヒント", "貢献はオベリスク破壊・要塞警備兵撃破・敵プレイヤー撃破で蓄積。最低貢献に達した者のみ支払われ、報酬は職業別貢献ランキングに従います。放置で除名され、地域を離れると1分のカウントダウンが始まります。支配戦内のキルはフィールド実績や亀裂シーズンキルカウンターに含まれません。支配戦専用キスク（攻撃側のみ）は軍団キスクより収容人数が多く、週/シーズンサーバー任務に支配戦任務が追加されました。"),
      ],
    }),
    fr: articleCopy(guideLabels, "fr", 5, {
      eyebrow: "MÉCANIQUES DE DOMINATION",
      title: "Aion 2 Domination des Failles : horaires, portes d'entrée, clés et règles de victoire",
      description: "La Domination des Failles, guerre de factions ajoutée le 2 septembre, se déroule lun/jeu/sam à 20:00 et 23:00 avec des portes dures (niveau 50+, 4 500+ d'équipement, 500,0k de puissance, balayage VI) et trois clés par semaine. Ce guide détaille chaque règle.",
      intro: "La mise à jour du 2 septembre a officialisé la guerre de factions dataminée : la Domination des Failles a maintenant un calendrier, un règlement et des portes d'entrée dures. Guide complet des règles confirmées.",
      sourceNote: "Basé sur les notes coréennes officielles du 2 septembre 2026 (Aion2t). Le calendrier du build mondial au lancement peut différer.",
      keywords: ["Aion 2 Domination des Failles", "Aion 2 horaires Domination", "Aion 2 clé d'événement", "Aion 2 guide guerre de factions", "Aion 2 Verteron Altgard PvP"],
      sections: [
        section("schedule", "Horaires et rotation", "Chaque lundi, jeudi et samedi à 20:00 et 23:00 (heures des Failles), à Verteron ou Altgard. Rotation hebdomadaire attaque/défense (semaine 1 Verteron, Élyos défendent ; semaine 2 Altgard, Asmodiens défendent). ~25 min de combat après 5 min de démarrage, portail 10 min."),
        section("entry-gates", "Les quatre portes d'entrée", "Niveau 50+, score d'équipement 4 500+, puissance de combat 500,0k, et balayage des forteresses VI dans les deux zones. Chaque porte a son propre message de refus."),
        section("keys-and-registration", "Clés et inscription", "Inscription via l'UI avec au moins une clé d'événement. Trois clés rechargées par semaine, une déduite par récompense. Le bouton [Rejoindre] n'est actif que sur le territoire du défenseur."),
        section("battle-rules", "Règles et victoire", "60 à 200 personnages par camp. Pas d'expédition/transcendance/sanctuaire ; mode S-PVP entre participants. Cinq forteresses par groupe, un groupe sur trois s'ouvre au hasard ; chute à la destruction des trois obélisques. Attaquants gagnent à 3+/5, défenseurs par majorité."),
        section("rewards-and-tips", "Récompenses et conseils", "Contribution via obélisques, gardes et joueurs ennemis ; récompenses selon le classement par classe pour ceux atteignant le minimum. L'inaction exclut ; quitter la zone lance un compte à rebours d'une minute. Les kills en Domination ne comptent pas pour les exploits de terrain. Kisk Domination (attaquants uniquement) plus capacitaire ; missions Domination ajoutées aux missions hebdo/saison."),
      ],
    }),
    de: articleCopy(guideLabels, "de", 5, {
      eyebrow: "DOMINATION-MECHANIK",
      title: "Aion 2 Spacetime-Rift-Domination: Zeitplan, Eintrittshürden, Schlüssel und Siegregeln",
      description: "Die Spacetime-Rift-Domination, der am 2. September hinzugefügte Fraktionenkrieg, läuft Mo/Do/Sa um 20:00 und 23:00 mit harten Hürden (Level 50+, Ausrüstung 4.500+, 500,0k Kampfkraft, Fegen VI) und drei wöchentlichen Schlüsseln. Dieser Leitfaden erklärt jede Regel.",
      intro: "Das Update vom 2. September hat den zuvor gedataminten Fraktionenkrieg offiziell gemacht: Die Spacetime-Rift-Domination hat jetzt Zeitplan, Regelwerk und harte Eintrittshürden. Vollständiger Leitfaden zu den bestätigten Regeln.",
      sourceNote: "Basierend auf den offiziellen koreanischen Notizen vom 2. September 2026 (Aion2t). Der eigene Zeitplan des globalen Builds kann beim Start abweichen.",
      keywords: ["Aion 2 Spacetime-Rift-Domination", "Aion 2 Domination-Zeitplan", "Aion 2 Event-Schlüssel", "Aion 2 Fraktionen-Kriegs-Guide", "Aion 2 Verteron Altgard PvP"],
      sections: [
        section("schedule", "Zeitplan und Rotation", "Jeden Montag, Donnerstag und Samstag um 20:00 und 23:00 (Rift-Zeiten) in Verteron oder Altgard. Wöchentlicher Angriff/Verteidigungs-Wechsel (Woche 1 Verteron, Elyos verteidigen; Woche 2 Altgard, Asmodianer verteidigen). ~25 Min. Kampf nach 5 Min. Startfenster, Portal 10 Min."),
        section("entry-gates", "Die vier Eintrittshürden", "Level 50+, Ausrüstung 4.500+, Kampfkraft 500,0k und Festungs-Fegen VI in beiden Zonen. Jede Hürde hat eine eigene Ablehnungsmeldung."),
        section("keys-and-registration", "Schlüssel und Anmeldung", "Anmeldung über die UI mit mindestens einem Event-Schlüssel. Drei Schlüssel laden wöchentlich auf, einer wird pro Belohnung abgezogen. [Beitreten] ist nur im Territorium des Verteidigers aktiv."),
        section("battle-rules", "Kampfregeln und Sieg", "60 bis 200 Charaktere pro Seite. Keine Expedition/Transzendenz/Sanktuarium; S-PVP-Modus zwischen Teilnehmern. Fünf Festungen pro Gruppe, eine von drei öffnet zufällig; Eroberung bei Zerstörung aller drei Obelisken. Angreifer gewinnen bei 3+/5, Verteidiger durch Mehrheit."),
        section("rewards-and-tips", "Belohnungen und Tipps", "Beitrag durch Obelisken, Wachen und Feindspieler; Belohnung nach Klassen-Ranking für Mindestbeitrag. Inaktivität führt zur Streichung; Verlassen der Zone startet eine 1-Minuten-Uhr. Domination-Kills zählen nicht für Feld-Erfolge. Domination-Kisk (nur Angreifer) fasst mehr; Domination-Missionen in den Wochen-/Saison-Missionen."),
      ],
    }),
    es: articleCopy(guideLabels, "es", 5, {
      eyebrow: "MECÁNICAS DE DOMINACIÓN",
      title: "Aion 2 Dominación de Fisuras: horarios, requisitos, claves y reglas de victoria",
      description: "La Dominación de Fisuras, guerra de facciones añadida el 2 de septiembre, se celebra lun/jue/sáb a las 20:00 y 23:00 con requisitos duros (nivel 50+, 4.500+ de equipo, 500,0k de poder, barrido VI) y tres claves semanales. Esta guía detalla cada regla.",
      intro: "La actualización del 2 de septiembre oficializó la guerra de facciones extraída: la Dominación de Fisuras ahora tiene calendario, reglamento y requisitos duros. Guía completa de las reglas confirmadas.",
      sourceNote: "Basado en las notas oficiales coreanas del 2 de septiembre de 2026 (Aion2t). El calendario propio del build global puede diferir.",
      keywords: ["Aion 2 Dominación de Fisuras", "Aion 2 horarios Dominación", "Aion 2 clave de evento", "Aion 2 guía guerra de facciones", "Aion 2 Verteron Altgard PvP"],
      sections: [
        section("schedule", "Horarios y rotación", "Cada lunes, jueves y sábado a las 20:00 y 23:00 (horas de Fisuras), en Verteron o Altgard. Rotación semanal ataque/defensa (semana 1 Verteron, Elyos defienden; semana 2 Altgard, Asmodianos defienden). ~25 min de combate tras 5 min de inicio, portal 10 min."),
        section("entry-gates", "Los cuatro requisitos", "Nivel 50+, puntuación de equipo 4.500+, poder de combate 500,0k y barrido de fortalezas VI en ambas zonas. Cada requisito tiene su propio mensaje de rechazo."),
        section("keys-and-registration", "Claves e inscripción", "Inscripción vía UI con al menos una clave de evento. Tres claves recargadas por semana, una por recompensa. [Unirse] solo activo en territorio del defensor."),
        section("battle-rules", "Reglas y victoria", "60 a 200 personajes por bando. Sin expedición/trascendencia/santuario; modo S-PVP entre participantes. Cinco fortalezas por grupo, uno de tres se abre al azar; caída con tres obeliscos destruidos. Atacantes ganan a 3+/5, defensores por mayoría."),
        section("rewards-and-tips", "Recompensas y consejos", "Contribución con obeliscos, guardias y enemigos; recompensas por rango de clase para quienes alcanzan el mínimo. La inactividad excluye; salir de la zona inicia un contador de un minuto. Los kills en Dominación no cuentan para logros de campo. Kisk de Dominación (solo atacantes) con más capacidad; misiones de Dominación añadidas."),
      ],
    }),
    "pt-br": articleCopy(guideLabels, "pt-br", 5, {
      eyebrow: "MECÂNICAS DE DOMINAÇÃO",
      title: "Aion 2 Dominação de Fendas: horários, requisitos, chaves e regras de vitória",
      description: "A Dominação de Fendas, guerra de facções adicionada em 2 de setembro, ocorre seg/qui/sáb às 20:00 e 23:00 com requisitos rígidos (nível 50+, 4.500+ de equipamento, 500,0k de poder, varredura VI) e três chaves semanais. Este guia detalha cada regra.",
      intro: "A atualização de 2 de setembro oficializou a guerra de facções vazada: a Dominação de Fendas agora tem calendário, regulamento e requisitos rígidos. Guia completo das regras confirmadas.",
      sourceNote: "Com base nas notas oficiais coreanas de 2 de setembro de 2026 (Aion2t). O calendário próprio do build global pode diferir.",
      keywords: ["Aion 2 Dominação de Fendas", "Aion 2 horários Dominação", "Aion 2 chave de evento", "Aion 2 guia guerra de facções", "Aion 2 Verteron Altgard PvP"],
      sections: [
        section("schedule", "Horários e rotação", "Toda segunda, quinta e sábado às 20:00 e 23:00 (horários de Fendas), em Verteron ou Altgard. Rotação semanal ataque/defesa (semana 1 Verteron, Elyos defendem; semana 2 Altgard, Asmodianos defendem). ~25 min de combate após 5 min de início, portal 10 min."),
        section("entry-gates", "Os quatro requisitos", "Nível 50+, pontuação de equipamento 4.500+, poder de combate 500,0k e varredura de fortalezas VI nas duas zonas. Cada requisito tem sua própria mensagem de recusa."),
        section("keys-and-registration", "Chaves e inscrição", "Inscrição via UI com pelo menos uma chave de evento. Três chaves recarregadas por semana, uma por recompensa. [Entrar] só ativo no território do defensor."),
        section("battle-rules", "Regras e vitória", "60 a 200 personagens por lado. Sem expedição/transcendência/santuário; modo S-PVP entre participantes. Cinco fortalezas por grupo, um de três abre ao acaso; queda com três obeliscos destruídos. Atacantes vencem a 3+/5, defensores por maioria."),
        section("rewards-and-tips", "Recompensas e dicas", "Contribuição com obeliscos, guardas e inimigos; recompensas por ranking de classe para quem atinge o mínimo. Inatividade exclui; sair da zona inicia contador de um minuto. Kills na Dominação não contam para conquistas de campo. Kisk de Dominação (só atacantes) com mais capacidade; missões de Dominação adicionadas."),
      ],
    }),
    ru: articleCopy(guideLabels, "ru", 5, {
      eyebrow: "МЕХАНИКА ДОМИНАЦИИ",
      title: "Aion 2 Доминация Разломов: расписание, требования, ключи и правила победы",
      description: "Доминация Разломов, война фракций, добавленная 2 сентября, проходит пн/чт/сб в 20:00 и 23:00 с жёсткими требованиями (уровень 50+, экипировка 4 500+, сила 500,0k, зачистка VI) и тремя еженедельными ключами. Это руководство разбирает каждое правило.",
      intro: "Обновление от 2 сентября официально оформило слитую войну фракций: у Доминации Разломов теперь есть расписание, регламент и жёсткие требования. Полное руководство по подтверждённым правилам.",
      sourceNote: "На основе официальных корейских заметок от 2 сентября 2026 (Aion2t). Собственное расписание глобальной сборки может отличаться.",
      keywords: ["Aion 2 Доминация Разломов", "Aion 2 расписание Доминации", "Aion 2 ключ события", "Aion 2 гайд войны фракций", "Aion 2 Вертерон Альтгард PvP"],
      sections: [
        section("schedule", "Расписание и ротация", "Каждый понедельник, четверг и субботу в 20:00 и 23:00 (время Разломов) в Вертероне или Альтгарде. Еженедельная ротация атаки/обороны (неделя 1 Вертерон, Элиос защищают; неделя 2 Альтгард, Асмодиане защищают). ~25 минут боя после 5-минутного окна, портал 10 минут."),
        section("entry-gates", "Четыре требования", "Уровень 50+, экипировка 4 500+, сила 500,0k и зачистка крепостей VI в обеих зонах. У каждого требования свой отказ."),
        section("keys-and-registration", "Ключи и регистрация", "Регистрация через UI минимум с одним ключом события. Три ключа пополняются еженедельно, один списывается за награду. [Присоединиться] активно только на территории защитника."),
        section("battle-rules", "Правила и победа", "От 60 до 200 персонажей на сторону. Без экспедиции/трансценденции/святилища; режим S-PVP между участниками. Пять крепостей в группе, одна из трёх открывается случайно; падение при разрушении трёх обелисков. Атакующие побеждают при 3+/5, защитники — большинством."),
        section("rewards-and-tips", "Награды и советы", "Вклад за обелиски, стражей и врагов; награды по классовому рейтингу тем, кто достиг минимума. Бездействие исключает; выход из зоны запускает минуту. Убийства в Доминации не считаются в полевые достижения. Киск Доминации (только атакующие) вмещает больше; добавлены миссии Доминации."),
      ],
    }),
    "zh-hant": articleCopy(guideLabels, "zh-hant", 5, {
      eyebrow: "統治戰機制",
      title: "Aion 2 時空裂隙·統治戰：日程、入場門檻、鑰匙與勝敗規則",
      description: "9 月 2 日韓服更新上線的開放世界陣營戰「時空裂隙·統治戰」於週一/四/六 20:00、23:00 舉行，硬性門檻（等級 50+、裝備分 4,500+、戰力 500.0k+、雙區要塞掃蕩 VI 級）加每週 3 枚事件鑰匙。本指南拆解每條規則。",
      intro: "9 月 2 日 Aion 2 更新讓此前數據挖掘的開放世界陣營戰正式化：時空裂隙·統治戰現帶日程、規則書與硬入場門檻。這是全球玩家最終會遇到的終局內容，因此本指南覆蓋已確認的一切。",
      sourceNote: "基於 NCsoft 2026 年 9 月 2 日韓服官方更新公告（Aion2t 整理並連結韓文原文）。本指南針對已確認規則；全球版上線時的自身日程或有不同。",
      keywords: ["Aion 2 時空裂隙統治戰", "Aion 2 統治戰日程", "Aion 2 事件鑰匙", "Aion 2 陣營戰指南", "Aion 2 維爾特倫阿爾特加德PvP"],
      sections: [
        section("schedule", "日程與輪換", ["統治戰於每週一、週四、週六 20:00 與 23:00（時空裂隙時刻）在維爾特倫或阿爾特加德舉行。攻防每週輪換：第一週維爾特倫、埃利奧斯防守；第二週阿爾特加德、阿斯莫迪安防守。每次事件在 5 分鐘開場窗口後約 25 分鐘戰鬥，傳送門保持 10 分鐘可入場。"]),
        section("entry-gates", "入場門檻（四項全需）", ["角色等級 50 或以上；裝備分 4,500 或以上；戰力 500.0k 或以上；成就：維爾特倫要塞掃蕩 VI 與阿爾特加德要塞掃蕩 VI——即兩個區域所有要塞清過。每項門檻有各自的拒絕訊息。"]),
        section("keys-and-registration", "事件鑰匙與註冊", ["持有至少 1 枚事件鑰匙時，透過統治戰通知 UI 註冊。事件鑰匙：每週自動補充 3 枚，每次領取事件獎勵消耗 1 枚。事件進行時，[加入]按鈕僅在防守方領土內啟用。"]),
        section("battle-rules", "戰鬥規則與勝負", ["人口：每邊最少 60、最多 200 人。任一側人數不足則事件不開。期間不可使用遠征、超越或聖域內容；準備結束後 S-PVP 模式開啟，僅 S-PVP 角色互相攻擊。防守方領土 5 座要塞為一組，每次事件隨機開啟三組之一。要塞在三個方尖碑全部被毀時陷落。進攻方奪取 5 座中 3 座以上獲勝；防守方在時間結束時仍佔多數則獲勝。"]),
        section("rewards-and-tips", "獎勵與實用提示", ["貢獻來自摧毀方尖碑、擊殺要塞守衛與擊殺敵方玩家。只有達到最低貢獻的玩家獲發獎勵，且獎勵按職業貢獻排名發放。掛機會被除名；離開區域會啟動 1 分鐘倒數。統治戰內的擊殺不計入野外成就或時空裂隙賽季擊殺計數。統治戰專用基斯克（僅進攻方）比軍團基斯克容納更多人。每週/賽季伺服器任務新增統治戰任務——加入前先查看。"]),
      ],
    }),
  },
};