import { articleCopy, guideLabels, localizations, publishedVerified, section } from "./trending-september-9-shared";
import type { ContentEntry, ContentHeroImage, ContentSource } from "./content-registry";

/* ARTICLE 3 — Seal system guide: new equipment slot added Sept 9 (KR), how to obtain and upgrade seals */

const invenSource: ContentSource = {
  id: "inven-aion2-snowfield-preview-2026-09-08",
  kind: "third-party",
  publisher: "Inven Global",
  label: "Aion 2 Unveils New Raid Content 'Snowfield of Grief' (Seal slot details)",
  url: "https://www.invenglobal.com/articles/25688/aion-2-unveils-new-raid-content-snowfield-of-grief",
  publishedAt: "2026-09-08",
  retrievedAt: "2026-09-09",
  verifiedAt: "2026-09-09",
  localizations: localizations({
    "zh-hans": "Aion 2 公布新团队副本「Snowfield of Grief」（印章栏详情）",
    en: "Aion 2 Unveils New Raid Content 'Snowfield of Grief' (Seal slot details)",
    fr: "Aion 2 dévoile le raid « Snowfield of Grief » (détails de l'emplacement Sceau)",
    de: "Aion 2 enthüllt Raid „Snowfield of Grief“ (Details zum Seal-Platz)",
    es: "Aion 2 desvela el raid «Snowfield of Grief» (detalles de la ranura de Sello)",
    ja: "Aion 2 新レイド「Snowfield of Grief」公開（シール枠の詳細）",
    "pt-br": "Aion 2 revela o raid 'Snowfield of Grief' (detalhes do slot de Selo)",
    ru: "Aion 2 анонсирует рейд «Snowfield of Grief» (детали слота Печати)",
    ko: "아이온2 신규 레이드 '슬픔의 설원' 공개 (인장 칸 상세)",
    "zh-hant": "Aion 2 公布新團隊副本「Snowfield of Grief」（印章欄詳情）",
  }, "https://www.invenglobal.com/articles/25688/aion-2-unveils-new-raid-content-snowfield-of-grief"),
};

const officialPatchSource: ContentSource = {
  id: "aion2-official-update-2026-09-09",
  kind: "official",
  publisher: "NC Corporation",
  label: "AION 2 Update Notes — September 9, 2026 (Seal slot, crafting)",
  url: "https://aion2.plaync.com/ko-kr/board/update/view?articleId=6aa062386b722c561dc6a46c",
  publishedAt: "2026-09-09",
  retrievedAt: "2026-09-09",
  verifiedAt: "2026-09-09",
  localizations: localizations({
    "zh-hans": "AION 2 更新说明——2026-09-09（印章栏、制作）",
    en: "AION 2 Update Notes — September 9, 2026 (Seal slot, crafting)",
    fr: "Notes de mise à jour AION 2 — 9 septembre 2026 (emplacement Sceau, artisanat)",
    de: "AION-2-Update-Notizen — 9. September 2026 (Seal-Platz, Handwerk)",
    es: "Notas de actualización de AION 2 — 9 de septiembre de 2026 (ranura de Sello, artesanía)",
    ja: "AION 2 アップデートノート——2026-09-09（シール枠、製作）",
    "pt-br": "Notas de atualização do AION 2 — 9 de setembro de 2026 (slot de Selo, artesanato)",
    ru: "Заметки об обновлении AION 2 — 9 сентября 2026 (слот Печати, ремесло)",
    ko: "AION 2 업데이트 노트 — 2026-09-09 (인장 칸, 제작)",
    "zh-hant": "AION 2 更新說明——2026-09-09（印章欄、製作）",
  }, "https://aion2.plaync.com/ko-kr/board/update/view?articleId=6aa062386b722c561dc6a46c"),
};

const sealHero: ContentHeroImage = {
  src: "https://blogfiles.ncsoft.net/news/af7330da-4ff6-4b58-aece-400e6061a3be.jpg",
  width: 1200, height: 630,
  credit: "NC Corporation",
  sourceUrl: "https://aion2.plaync.com/en-us/",
  rights: "linked-official-media",
  translations: {
    "zh-hans": { alt: "Aion 2 印章系统指南横幅", caption: "9/9 韩服更新新增「印章」装备栏：可从 Easy 难度副本获得「Deltras's Seal（Unique）」，经传承制作升 Heroic，Fabled 级可手工制作，突破选项提升武器伤害增幅。" },
    en: { alt: "Aion 2 Seal system guide banner", caption: "The September 9 Korean update adds a new Seal equipment slot: Deltras's Seal (Unique) drops from Easy difficulty and can be upgraded to Heroic via Succession Crafting, Fabled seals come from Handicrafting, and the Breakthrough option boosts Weapon Damage Amplification." },
    fr: { alt: "Bannière du guide du système Sceau d'Aion 2", caption: "La mise à jour coréenne du 9 septembre ajoute un emplacement Sceau : Deltras's Seal (Unique) dès Easy, Heroic par artisanat de succession, Fabled par l'artisanat, Breakthrough améliore l'amplification des dégâts d'arme." },
    de: { alt: "Banner zum Seal-System-Leitfaden von Aion 2", caption: "Das koreanische Update vom 9. September fügt einen Seal-Platz hinzu: Deltras's Seal (Unique) ab Easy, Heroic per Succession Crafting, Fabled per Handwerk, Breakthrough verstärkt die Waffenschadens-Verstärkung." },
    es: { alt: "Banner de la guía del sistema de Sello de Aion 2", caption: "La actualización coreana del 9 de septiembre añade una ranura de Sello: Deltras's Seal (Unique) desde Easy, Heroic por artesanía de sucesión, Fabled por artesanía, Breakthrough aumenta la amplificación de daño de arma." },
    ja: { alt: "Aion 2 シールシステムガイドバナー", caption: "9/9韓国アップデートで新装備枠「シール」追加：Easyから「Deltras's Seal（Unique）」、継承制作でHeroicへ、Fabledは手工芸、ブレークスルーで武器ダメージ増幅アップ。" },
    "pt-br": { alt: "Banner do guia do sistema de Selo do Aion 2", caption: "A atualização coreana de 9 de setembro adiciona um slot de Selo: Deltras's Seal (Unique) desde Easy, Heroic via artesanato de sucessão, Fabled por artesanato, Breakthrough aumenta a amplificação de dano de arma." },
    ru: { alt: "Баннер гайда по системе Печатей Aion 2", caption: "Корейское обновление 9 сентября добавляет слот Печати: Deltras's Seal (Unique) с Easy, Heroic через наследование, Fabled ремеслом, Breakthrough усиливает урон оружия." },
    ko: { alt: "Aion 2 인장 시스템 가이드 배너", caption: "9/9 한국 업데이트로 신규 장비 칸 '인장' 추가: Easy부터 '델트라스의 인장(Unique)', 계승 제작으로 Heroic 승급, Fabled는 수공예, 브레이크스루는 무기 피해 증폭 상승." },
    "zh-hant": { alt: "Aion 2 印章系統指南橫幅", caption: "9/9 韓服更新新增「印章」裝備欄：可從 Easy 難度副本獲得「Deltras's Seal（Unique）」，經傳承製作升 Heroic，Fabled 級可手工製作，突破選項提升武器傷害增幅。" },
  },
};

export const trendingSeptember9Article3: ContentEntry = {
  section: "guides",
  slug: "aion-2-seal-system-guide",
  schemaType: "Article",
  publishedAt: "2026-09-09",
  updatedAt: "2026-09-09",
  readingMinutes: 5,
  publication: publishedVerified,
  sources: [invenSource, officialPatchSource],
  heroImage: sealHero,
  related: [
    { kind: "content", section: "guides", slug: "aion-2-endgame-gear-guide" },
    { kind: "content", section: "guides", slug: "aion-2-gear-enhancement-guide" },
    { kind: "content", section: "guides", slug: "aion-2-abyss-system-complete-guide" },
    { kind: "content", section: "guides", slug: "aion-2-trials-raids-guide" },
  ],
  translations: {
    en: articleCopy(guideLabels, "en", 5, {
      eyebrow: "SEAL GUIDE",
      title: "Aion 2 Seal System Guide: New Equipment Slot, How to Get and Upgrade Seals",
      description: "The September 9 update adds a Seal equipment slot: get Deltras's Seal (Unique) from the Snowfield of Grief raid on Easy, upgrade to Heroic via Succession Crafting, and craft Fabled seals with Handicrafting",
      intro: "The September 9 Korean update introduces a new equipment slot: Seal. This guide explains what seals do, where the Deltras's Seal accessory comes from, how to upgrade it, and the crafting routes that feed the new slot.",
      sourceNote: "Based on the official Korean update notes of September 9, 2026 and Inven Global's September 8, 2026 preview report (both retrieved September 9, 2026). Applies to the Korean service; the global version launches October 5 with a modified Season 1 and will receive this system later.",
      keywords: ["Aion 2 Seal system", "Aion 2 Deltras's Seal Unique", "Aion 2 Seal slot equipment", "Aion 2 Succession Crafting seal upgrade", "Aion 2 Handicrafting Fabled seal"],
      sections: [
        section("what-is-seal", "What the Seal Slot Is", ["The September 9 patch adds a new equipment slot named 'Seal' to the character sheet, sitting alongside the weapon, guarder, armor, and accessory slots introduced earlier in Chapter 1.", "The showcase accessory for the system is 'Deltras's Seal (Unique)', named after the new raid's final boss — it can be obtained starting from Easy difficulty in Snowfield of Grief."]),
        section("how-to-obtain", "How to Obtain Seals", ["There are two routes in the patch notes: crafting, and material-converting the equipment change vouchers obtained from the Snowfield of Lament Sanctuary together with Kina.", "For players who focus on the new raid, the voucher route is the direct path: run the Sanctuary, collect equipment change vouchers, and convert them with Kina to produce seals."]),
        section("upgrade-path", "Upgrade Path: Unique to Heroic", ["Unique-grade seals obtained in Snowfield of Grief can be upgraded to Heroic grade through Succession Crafting — the same inheritance-crafting system used for weapons and armor.", "Fabled-grade seals are created via Handicrafting, giving the crafting community a route into the new slot without raiding."]),
        section("breakthrough", "The Breakthrough Option", ["The key combat stat on seals is the Breakthrough option, which increases Weapon Damage Amplification.", "That makes the seal slot a direct damage multiplier for PvE and PvP alike — worth factoring into your endgame damage calculations alongside the Abyss set effects that were reworked in the same patch."]),
        section("practical-notes", "Practical Notes After the Update", ["One side effect in the patch notes: because the Seal slot changes how accessory details work, NPC-shop quick-sell registration and server/character storage quick-registration accessory detail settings are reset after the update — re-check them in the settings UI.", "The slot arrives with the Snowfield of Grief raid and the new Tier 4 gear, so plan your Kina and crafting materials accordingly if you are chasing the Korean endgame."]),
      ],
    }),
    "zh-hans": articleCopy(guideLabels, "zh-hans", 5, {
      eyebrow: "印章指南",
      title: "Aion 2 印章系统指南：新装备栏、获取与升级途径",
      description: "9 月 9 日更新新增「印章」装备栏：Snowfield of Grief 副本 Easy 难度获得「Deltras's Seal（Unique）」、传承制作升 Heroic、手工制作 Fabled 印章",
      intro: "9 月 9 日韩服更新引入新的装备栏：印章。本指南说明印章的作用、Deltras's Seal 饰品的来源、升级路径，以及供给该新栏位的制作途径。",
      sourceNote: "基于 2026 年 9 月 9 日官方韩服更新说明与 Inven Global 2026 年 9 月 8 日预览报道（均于 2026-09-09 抓取）。适用于韩服；全球版 10 月 5 日以改良版 Season 1 上线，此系统后续才会到达。",
      keywords: ["Aion 2 印章系统", "Aion 2 Deltras's Seal Unique", "Aion 2 印章装备栏", "Aion 2 传承制作 印章升级", "Aion 2 手工制作 Fabled 印章"],
      sections: [
        section("what-is-seal", "印章栏是什么", ["9 月 9 日补丁在角色面板新增名为「印章」的装备栏，与 Chapter 1 早前引入的武器、守护者、防具与饰品栏并列。", "该系统的代表饰品是「Deltras's Seal（Unique）」——以新副本最终 Boss 命名，可从 Snowfield of Grief 的 Easy 难度起获得。"]),
        section("how-to-obtain", "如何获取印章", ["补丁说明中有两条途径：制作；以及将 Snowfield of Lament 副本获得的装备更换券与 Kina 一起进行材料转换。", "主刷新副本的玩家走兑换券路线最直接：打副本、收集装备更换券、与 Kina 一起转换出印章。"]),
        section("upgrade-path", "升级路径：Unique 升 Heroic", ["Snowfield of Grief 中获得的 Unique 印章可经传承制作升级为 Heroic 级——与武器/防具使用的传承制作是同一系统。", "Fabled 级印章通过手工制作产出，为制作玩家提供不依赖副本的入坑途径。"]),
        section("breakthrough", "突破选项", ["印章的关键战斗属性是突破选项，可提升武器伤害增幅。", "这意味着印章栏是直接的伤害倍率来源，PvE 与 PvP 都适用——规划终局伤害时应与同一补丁重做的深渊套装效果一并考虑。"]),
        section("practical-notes", "更新后的实用提示", ["补丁说明中的一个副作用：由于印章栏改变了饰品详情逻辑，更新后 NPC 商店快速出售登记与服务器/角色仓库快捷登记中的饰品详情设置会被重置——记得在设置界面重新勾选。", "该栏位与 Snowfield of Grief 副本及新 Tier 4 装备一同到来，如果你在追韩服终局，请相应规划 Kina 与制作材料。"]),
      ],
    }),
    fr: articleCopy(guideLabels, "fr", 5, {
      eyebrow: "GUIDE SCEAU",
      title: "Guide du système Sceau d'Aion 2 : nouvel emplacement, obtention et amélioration",
      description: "La mise à jour du 9 septembre ajoute un emplacement Sceau : Deltras's Seal (Unique) au raid Snowfield of Grief dès Easy, Heroic par artisanat de succession, Sceaux Fabled à l'artisanat",
      intro: "La mise à jour coréenne du 9 septembre introduit un nouvel emplacement d'équipement : Sceau. Ce guide explique le rôle des sceaux, l'origine de l'accessoire Deltras's Seal, l'amélioration et les voies d'artisanat.",
      sourceNote: "Basé sur les notes de mise à jour officielles coréennes du 9 septembre 2026 et le rapport de preview d'Inven Global du 8 septembre 2026 (récupérés le 9 septembre 2026).",
      keywords: ["Aion 2 système Sceau", "Aion 2 Deltras's Seal Unique", "Aion 2 emplacement Sceau équipement", "Aion 2 artisanat de succession sceau", "Aion 2 artisanat Sceau Fabled"],
      sections: [
        section("what-is-seal", "L'emplacement Sceau", "Le patch du 9 septembre ajoute un emplacement « Sceau » à la fiche du personnage, aux côtés des armes, gardes, armures et accessoires du Chapitre 1. L'accessoire phare : « Deltras's Seal (Unique) », dès Easy dans Snowfield of Grief."),
        section("how-to-obtain", "Comment obtenir des sceaux", "Deux voies : l'artisanat, et la conversion matérielle des bons d'échange d'équipement du Sanctuary Snowfield of Lament avec du Kina. La voie des bons est la plus directe pour les joueurs du raid."),
        section("upgrade-path", "Amélioration : Unique → Heroic", "Les sceaux Unique de Snowfield of Grief passent en Heroic par artisanat de succession (même système que les armes/armures). Les sceaux Fabled se créent par l'artisanat classique."),
        section("breakthrough", "L'option Breakthrough", "La stat clé : Breakthrough, qui augmente l'amplification des dégâts d'arme — un multiplicateur direct en PvE comme en PvP, à combiner avec les effets de sets Abyss révisés."),
        section("practical-notes", "Notes pratiques", "Effet secondaire : les réglages de détail des accessoires (vente rapide en boutique NPC, enregistrement rapide au stockage) sont réinitialisés après la mise à jour — à revérifier. L'emplacement arrive avec le raid et le Tier 4 : planifiez Kina et matériaux."),
      ],
    }),
    de: articleCopy(guideLabels, "de", 5, {
      eyebrow: "SEAL-LEITFADEN",
      title: "Leitfaden zum Seal-System von Aion 2: neuer Ausrüstungsplatz, Beschaffung und Aufwertung",
      description: "Das Update vom 9. September fügt einen Seal-Platz hinzu: Deltras's Seal (Unique) ab Easy im Raid Snowfield of Grief, Heroic per Succession Crafting, Fabled-Siegel per Handwerk",
      intro: "Das koreanische Update vom 9. September führt einen neuen Ausrüstungsplatz ein: Seal. Dieser Leitfaden erklärt, was Siegel tun, woher Deltras's Seal kommt, wie man es aufwertet und welche Handwerkswege den neuen Platz speisen.",
      sourceNote: "Basierend auf den offiziellen koreanischen Update-Notizen vom 9. September 2026 und dem Inven-Global-Preview vom 8. September 2026 (abgerufen am 9. September 2026).",
      keywords: ["Aion 2 Seal-System", "Aion 2 Deltras's Seal Unique", "Aion 2 Seal Platz Ausrüstung", "Aion 2 Succession Crafting Siegel", "Aion 2 Handwerk Fabled Siegel"],
      sections: [
        section("what-is-seal", "Der Seal-Platz", "Das Update vom 9. September fügt einen Platz namens „Seal“ hinzu, neben Waffe, Guarder, Rüstung und Accessoires aus Kapitel 1. Das Aushängeschild: „Deltras's Seal (Unique)“, ab Easy in Snowfield of Grief."),
        section("how-to-obtain", "Wie man Siegel bekommt", "Zwei Wege: Handwerk und Material-Umwandlung der Ausrüstungswechsel-Gutscheine aus dem Sanctuary Snowfield of Lament zusammen mit Kina. Der Gutscheinweg ist für Raid-Spieler der direkte."),
        section("upgrade-path", "Aufwertung: Unique → Heroic", "Unique-Siegel aus Snowfield of Grief gehen per Succession Crafting auf Heroic (dasselbe System wie Waffen/Rüstung). Fabled-Siegel entstehen per Handwerk."),
        section("breakthrough", "Die Breakthrough-Option", "Die Schlüssel-Stat: Breakthrough erhöht die Waffenschadens-Verstärkung — ein direkter Multiplikator in PvE und PvP, zu kombinieren mit den überarbeiteten Abyss-Seteffekten."),
        section("practical-notes", "Praktische Hinweise", "Nebeneffekt: Die Detail-Einstellungen für Accessoires (NPC-Schnellverkauf, Schnellregistrierung im Lager) werden nach dem Update zurückgesetzt — neu prüfen. Der Platz kommt mit Raid und Tier 4: Kina und Materialien einplanen."),
      ],
    }),
    es: articleCopy(guideLabels, "es", 5, {
      eyebrow: "GUÍA DE SELLO",
      title: "Guía del sistema de Sello de Aion 2: nueva ranura, obtención y mejora",
      description: "La actualización del 9 de septiembre añade una ranura de Sello: Deltras's Seal (Unique) en el raid Snowfield of Grief desde Easy, Heroic por artesanía de sucesión, Sellos Fabled por artesanía",
      intro: "La actualización coreana del 9 de septiembre introduce una nueva ranura de equipo: Sello. Esta guía explica qué hacen los sellos, de dónde viene el accesorio Deltras's Seal, cómo mejorarlo y las rutas de artesanía.",
      sourceNote: "Basado en las notas de actualización oficiales coreanas del 9 de septiembre de 2026 y el informe de preview de Inven Global del 8 de septiembre de 2026 (recuperados el 9 de septiembre de 2026).",
      keywords: ["Aion 2 sistema de Sello", "Aion 2 Deltras's Seal Unique", "Aion 2 ranura de Sello equipo", "Aion 2 artesanía de sucesión sello", "Aion 2 artesanía Sello Fabled"],
      sections: [
        section("what-is-seal", "La ranura de Sello", "El parche del 9 de septiembre añade una ranura «Sello» a la ficha del personaje, junto a armas, guardas, armaduras y accesorios del Capítulo 1. El accesorio estrella: «Deltras's Seal (Unique)», desde Easy en Snowfield of Grief."),
        section("how-to-obtain", "Cómo obtener sellos", "Dos vías: artesanía, y conversión material de los vales de cambio de equipo del Santuario Snowfield of Lament con Kina. La vía de vales es la directa para jugadores del raid."),
        section("upgrade-path", "Mejora: Unique → Heroic", "Los sellos Unique de Snowfield of Grief suben a Heroic por artesanía de sucesión (mismo sistema que armas/armaduras). Los sellos Fabled se crean por artesanía."),
        section("breakthrough", "La opción Breakthrough", "La stat clave: Breakthrough, que aumenta la amplificación de daño de arma — un multiplicador directo en PvE y PvP, a combinar con los efectos de sets Abyss reformados."),
        section("practical-notes", "Notas prácticas", "Efecto secundario: los ajustes de detalle de accesorios (venta rápida en tienda NPC, registro rápido en almacén) se reinician tras la actualización — revísalos. La ranura llega con el raid y el Tier 4: planifica Kina y materiales."),
      ],
    }),
    ja: articleCopy(guideLabels, "ja", 5, {
      eyebrow: "シールガイド",
      title: "Aion 2 シールシステムガイド：新装備枠、入手・強化方法",
      description: "9月9日アップデートで新装備枠「シール」追加：Snowfield of GriefのEasyから「Deltras's Seal（Unique）」、継承制作でHeroic、Fabledは手工芸で製作",
      intro: "9月9日の韓国アップデートで新しい装備枠「シール」が導入されました。このガイドではシールの役割、Deltras's Sealアクセサリーの入手先、強化方法、そして新枠を支える製作ルートを解説します。",
      sourceNote: "2026年9月9日付公式韓国アップデートノートとInven Global 2026年9月8日付プレビュー（いずれも2026-09-09取得）に基づきます。",
      keywords: ["Aion 2 シールシステム", "Aion 2 Deltras's Seal Unique", "Aion 2 シール 装備枠", "Aion 2 継承制作 シール 強化", "Aion 2 手工芸 Fabled シール"],
      sections: [
        section("what-is-seal", "シール枠とは", "9月9日のパッチでキャラクターシートに「シール」という新装備枠が追加されました。武器・ガーダー・防具・アクセサリー（Chapter 1で実装済み）と並びます。目玉アクセサリーは新レイドのラスボスにちなんだ「Deltras's Seal（Unique）」で、Snowfield of GriefのEasyから入手可能です。"),
        section("how-to-obtain", "シールの入手方法", "パッチノートに記載されたルートは2つ：製作、そしてSnowfield of Lamentサンクチュアリで得られる装備変更券をKinaと合わせて素材変換する方法です。レイドを周回するプレイヤーは券ルートが直接的です。"),
        section("upgrade-path", "強化：Unique → Heroic", "Snowfield of Griefで入手したUniqueシールは、武器・防具と同じ継承制作でHeroicへ昇格できます。Fabled級シールは手工芸で製作でき、レイドなしでも新枠にアプローチできます。"),
        section("breakthrough", "ブレークスルーオプション", "シールの重要ステータスはブレークスルーで、武器ダメージ増幅を上昇させます。PvE・PvP共通の直接的なダメージ乗算要素であり、同じパッチで改修されたアビスセット効果と合わせて検討しましょう。"),
        section("practical-notes", "アップデート後の注意", "パッチノートの副作用として、シール枠追加に伴いアクセサリー詳細設定（NPCショップクイックセール登録、サーバー/キャラ倉庫クイック登録）がリセットされます——設定UIで再確認を。新レイドとTier 4と同時に実装されるため、Kinaと素材の計画を立てましょう。"),
      ],
    }),
    "pt-br": articleCopy(guideLabels, "pt-br", 5, {
      eyebrow: "GUIA DE SELO",
      title: "Guia do sistema de Selo do Aion 2: novo slot, obtenção e melhoria",
      description: "A atualização de 9 de setembro adiciona um slot de Selo: Deltras's Seal (Unique) no raid Snowfield of Grief desde Easy, Heroic via artesanato de sucessão, Selos Fabled por artesanato",
      intro: "A atualização coreana de 9 de setembro introduz um novo slot de equipamento: Selo. Este guia explica o que os selos fazem, de onde vem o acessório Deltras's Seal, como melhorá-lo e as rotas de artesanato.",
      sourceNote: "Baseado nas notas de atualização oficiais coreanas de 9 de setembro de 2026 e no relatório de preview da Inven Global de 8 de setembro de 2026 (recuperados em 9 de setembro de 2026).",
      keywords: ["Aion 2 sistema de Selo", "Aion 2 Deltras's Seal Unique", "Aion 2 slot de Selo equipamento", "Aion 2 artesanato de sucessão selo", "Aion 2 artesanato Selo Fabled"],
      sections: [
        section("what-is-seal", "O slot de Selo", "O patch de 9 de setembro adiciona um slot 'Selo' à ficha do personagem, ao lado de armas, guardas, armaduras e acessórios do Capítulo 1. O acessório de destaque: 'Deltras's Seal (Unique)', desde Easy em Snowfield of Grief."),
        section("how-to-obtain", "Como obter selos", "Duas vias: artesanato e conversão material dos vales de troca de equipamento do Santuário Snowfield of Lament com Kina. A via de vales é a direta para jogadores do raid."),
        section("upgrade-path", "Melhoria: Unique → Heroic", "Selos Unique de Snowfield of Grief sobem para Heroic via artesanato de sucessão (mesmo sistema de armas/armaduras). Selos Fabled são criados por artesanato."),
        section("breakthrough", "A opção Breakthrough", "A stat-chave: Breakthrough, que aumenta a amplificação de dano de arma — um multiplicador direto em PvE e PvP, a combinar com os efeitos de sets Abyss reformados."),
        section("practical-notes", "Notas práticas", "Efeito colateral: os ajustes de detalhe de acessórios (venda rápida na loja NPC, registro rápido no armazém) são resetados após a atualização — revise-os. O slot chega com o raid e o Tier 4: planeje Kina e materiais."),
      ],
    }),
    ru: articleCopy(guideLabels, "ru", 5, {
      eyebrow: "ГАЙД ПО ПЕЧАТЯМ",
      title: "Гайд по системе Печатей Aion 2: новый слот, получение и улучшение",
      description: "Обновление 9 сентября добавляет слот Печати: Deltras's Seal (Unique) в рейде Snowfield of Grief с Easy, Heroic через наследование, Fabled-печати ремеслом",
      intro: "Корейское обновление 9 сентября вводит новый слот экипировки: Печать. Гайд объясняет, что делают печати, откуда берётся аксессуар Deltras's Seal, как его улучшать и какие ремесленные пути кормят новый слот.",
      sourceNote: "На основе официальных корейских заметок об обновлении от 9 сентября 2026 г. и превью Inven Global от 8 сентября 2026 г. (получены 9 сентября 2026 г.).",
      keywords: ["Aion 2 система Печатей", "Aion 2 Deltras's Seal Unique", "Aion 2 слот Печати экипировка", "Aion 2 наследование печать", "Aion 2 ремесло Fabled печать"],
      sections: [
        section("what-is-seal", "Слот Печати", "Патч 9 сентября добавляет слот «Печать» в лист персонажа, рядом с оружием, гардами, бронёй и аксессуарами Главы 1. Флагман системы — «Deltras's Seal (Unique)», доступный с Easy в Snowfield of Grief."),
        section("how-to-obtain", "Как получить печати", "Два пути: ремесло и материальная конвертация ваучеров смены экипировки из Святилища Snowfield of Lament вместе с Kina. Ваучерный путь — самый прямой для рейд-игроков."),
        section("upgrade-path", "Улучшение: Unique → Heroic", "Unique-печати из Snowfield of Grief улучшаются до Heroic через наследование (та же система, что для оружия/брони). Fabled-печати создаются ремеслом."),
        section("breakthrough", "Опция Breakthrough", "Ключевая характеристика: Breakthrough повышает усиление урона оружия — прямой множитель и в PvE, и в PvP, который стоит комбинировать с переработанными сетами Бездны."),
        section("practical-notes", "Практические заметки", "Побочный эффект: настройки деталей аксессуаров (быстрая продажа в NPC-магазине, быстрая регистрация на складе) сбрасываются после обновления — перепроверьте. Слот выходит с рейдом и Tier 4: планируйте Kina и материалы."),
      ],
    }),
    ko: articleCopy(guideLabels, "ko", 5, {
      eyebrow: "인장 가이드",
      title: "아이온2 인장 시스템 가이드: 신규 장비 칸, 획득·승급 방법",
      description: "9월 9일 업데이트로 신규 장비 칸 '인장' 추가: 슬픔의 설원 Easy부터 '델트라스의 인장(Unique)', 계승 제작으로 Heroic, Fabled는 수공예로 제작",
      intro: "9월 9일 한국 업데이트로 새로운 장비 칸 '인장'이 도입됐습니다. 이 가이드는 인장의 역할, 델트라스의 인장 액세서리 획득처, 승급 방법, 그리고 새 칸을 채우는 제작 루트를 설명합니다.",
      sourceNote: "2026년 9월 9일자 공식 한국 업데이트 노트와 Inven Global 2026년 9월 8일자 프리뷰 보도(모두 2026-09-09 확인)를 기반으로 했습니다.",
      keywords: ["아이온2 인장 시스템", "아이온2 델트라스의 인장 Unique", "아이온2 인장 장비 칸", "아이온2 계승 제작 인장 승급", "아이온2 수공예 Fabled 인장"],
      sections: [
        section("what-is-seal", "인장 칸이란", "9월 9일 패치로 캐릭터 시트에 '인장'이라는 새 장비 칸이 추가됩니다. Chapter 1에서 이미 도입된 무기·가더·방어구·액세서리 칸과 나란히 자리합니다.", "시스템의 대표 액세서리는 신규 레이드 최종 보스의 이름을 딴 '델트라스의 인장(Unique)'으로, 슬픔의 설원 Easy 난이도부터 획득할 수 있습니다."),
        section("how-to-obtain", "인장 획득 방법", "패치 노트에는 두 가지 경로가 있습니다: 제작, 그리고 슬픔의 설원 성역에서 얻는 장비 교환권을 키나와 함께 재료 변환하는 방법입니다.", "신규 레이드를 주력으로 하는 플레이어라면 교환권 루트가 가장 직접적입니다: 성역을 돌아 장비 교환권을 모으고 키나와 함께 변환해 인장을 생산합니다."),
        section("upgrade-path", "승급: Unique → Heroic", "슬픔의 설원에서 얻은 Unique 인장은 무기·방어구와 동일한 계승 제작 시스템으로 Heroic 등급까지 승급할 수 있습니다.", "Fabled 등급 인장은 수공예로 제작할 수 있어, 레이드를 돌지 않아도 새 칸에 접근하는 길을 만들어 줍니다."),
        section("breakthrough", "브레이크스루 옵션", "인장의 핵심 전투 스탯은 브레이크스루로, 무기 피해 증폭을 올려줍니다.", "즉 인장 칸은 PvE·PvP 공통의 직접적인 피해 배율 요소이며, 같은 패치에서 개편된 아비스 세트 효과와 함께 엔드게임 딜 계산에 반영해야 합니다."),
        section("practical-notes", "업데이트 후 실전 노트", "패치 노트에 명시된 부작용이 하나 있습니다: 인장 칸 추가로 액세서리 상세 설정이 바뀌어, NPC 상점 퀵셀 등록과 서버/캐릭터 창고 퀵 등록의 액세서리 상세 설정이 초기화됩니다——설정 UI에서 다시 체크하세요.", "인장 칸은 슬픔의 설원 레이드와 신규 Tier 4 장비와 함께 옵니다. 한국 서버 엔드게임을 노린다면 키나와 제작 재료 계획을 세워 두세요."),
      ],
    }),
    "zh-hant": articleCopy(guideLabels, "zh-hant", 5, {
      eyebrow: "印章指南",
      title: "Aion 2 印章系統指南：新裝備欄、獲取與升級途徑",
      description: "9 月 9 日更新新增「印章」裝備欄：Snowfield of Grief 副本 Easy 難度獲得「Deltras's Seal（Unique）」、傳承製作升 Heroic、手工製作 Fabled 印章",
      intro: "9 月 9 日韓服更新引入新的裝備欄：印章。本指南說明印章的作用、Deltras's Seal 飾品的來源、升級路徑，以及供給該新欄位的製作途徑。",
      sourceNote: "基於 2026 年 9 月 9 日官方韓服更新說明與 Inven Global 2026 年 9 月 8 日預覽報導（均於 2026-09-09 抓取）。適用於韓服；全球版 10 月 5 日以改良版 Season 1 上線，此系統後續才會到達。",
      keywords: ["Aion 2 印章系統", "Aion 2 Deltras's Seal Unique", "Aion 2 印章裝備欄", "Aion 2 傳承製作 印章升級", "Aion 2 手工製作 Fabled 印章"],
      sections: [
        section("what-is-seal", "印章欄是什麼", ["9 月 9 日補丁在角色面板新增名為「印章」的裝備欄，與 Chapter 1 早前引入的武器、守護者、防具與飾品欄並列。", "該系統的代表飾品是「Deltras's Seal（Unique）」——以新副本最終 Boss 命名，可從 Snowfield of Grief 的 Easy 難度起獲得。"]),
        section("how-to-obtain", "如何獲取印章", ["補丁說明中有兩條途徑：製作；以及將 Snowfield of Lament 副本獲得的裝備更換券與 Kina 一起進行材料轉換。", "主刷新副本的玩家走兌換券路線最直接：打副本、收集裝備更換券、與 Kina 一起轉換出印章。"]),
        section("upgrade-path", "升級路徑：Unique 升 Heroic", ["Snowfield of Grief 中獲得的 Unique 印章可經傳承製作升級為 Heroic 級——與武器/防具使用的傳承製作是同一系統。", "Fabled 級印章透過手工製作產出，為製作玩家提供不依賴副本的入坑途徑。"]),
        section("breakthrough", "突破選項", ["印章的關鍵戰鬥屬性是突破選項，可提升武器傷害增幅。", "這意味著印章欄是直接的傷害倍率來源，PvE 與 PvP 都適用——規劃終局傷害時應與同一補丁重做的深淵套裝效果一併考慮。"]),
        section("practical-notes", "更新後的實用提示", ["補丁說明中的一個副作用：由於印章欄改變了飾品詳情邏輯，更新後 NPC 商店快速出售登記與伺服器/角色倉庫快捷登記中的飾品詳情設定會被重置——記得在設定介面重新勾選。", "該欄位與 Snowfield of Grief 副本及新 Tier 4 裝備一同到來，如果你在追韓服終局，請相應規劃 Kina 與製作材料。"]),
      ],
    }),
  },
};
