import { articleCopy, guideLabels, localizations, publishedVerified, section } from "./trending-august-29-shared";
import type { ContentEntry, ContentHeroImage, ContentSource } from "./content-registry";

/* ARTICLE 3 — Moonlit Oasis Daeva Pass (Aug 26 update season) */

const dpSource1: ContentSource = {
  id: "aion2t-aug26-update-2026-08-29",
  kind: "third-party", publisher: "AION2T",
  label: "AION 2 — August 26, 2026 Update Notes: The Great Rebalance, Server Transfers and Bound Kina",
  url: "https://aion2t.com/news/40",
  publishedAt: "2026-08-26",
  retrievedAt: "2026-08-28",
  verifiedAt: "2026-08-28",
  localizations: localizations({
    "zh-hans": "Aion 2——2026 年 8 月 26 日更新说明：大平衡、服务器转移与绑定基纳",
    en: "AION 2 — August 26, 2026 Update Notes: The Great Rebalance, Server Transfers and Bound Kina",
    fr: "Aion 2 — Notes de mise à jour du 26 août 2026 : Grand rééquilibrage, transferts de serveur et Kina liée",
    de: "Aion 2 — Update-Notizen vom 26. August 2026: Great Rebalance, Servertransfers und gebundenes Kina",
    es: "Aion 2 — Notas de la actualización del 26 de agosto de 2026: Gran rebalanceo, transferencias de servidor y Kina vinculada",
    ja: "Aion 2 — 2026年8月26日アップデートノート：グレートリバランス、サーバー移行、バインドキナ",
    "pt-br": "Aion 2 — Notas da atualização de 26 de agosto de 2026: Grande reequilíbrio, transferências de servidor e Kina vinculada",
    ru: "Aion 2 — Примечания к обновлению от 26 августа 2026: Великий ребаланс, переносы серверов и связанная Кина",
    ko: "Aion 2 — 2026년 8월 26일 업데이트 노트: 그레이트 리밸런스, 서버 이전, 귀속 키나",
    "zh-hant": "Aion 2——2026 年 8 月 26 日更新說明：大平衡、伺服器轉移與綁定金納",
  }, "https://aion2t.com/news/40"),
};

const dpSource2: ContentSource = {
  id: "nc-official-notice-2026-08-29",
  kind: "official", publisher: "NC",
  label: "AION 2 Official Website — Notices & Events",
  url: "https://aion2.plaync.com/ko-kr/board/notice",
  publishedAt: "2026-08-26",
  retrievedAt: "2026-08-28",
  verifiedAt: "2026-08-28",
  localizations: localizations({
    "zh-hans": "AION 2 官方网站——公告与活动",
    en: "AION 2 Official Website — Notices & Events",
    fr: "Site officiel AION 2 — annonces et événements",
    de: "AION 2 Offizielle Website — Ankündigungen & Events",
    es: "Sitio web oficial de AION 2 — avisos y eventos",
    ja: "AION 2 公式サイト — お知らせ＆イベント",
    "pt-br": "Site oficial do AION 2 — avisos e eventos",
    ru: "Официальный сайт AION 2 — объявления и события",
    ko: "Aion 2 공식 사이트 — 공지 및 이벤트",
    "zh-hant": "AION 2 官方網站——公告與活動",
  }, "https://aion2.plaync.com/ko-kr/board/notice"),
};

const dpHero: ContentHeroImage = {
  src: "https://blogfiles.ncsoft.net/news/af7330da-4ff6-4b58-aece-400e6061a3be.jpg",
  width: 1100, height: 605,
  credit: "NC Corporation",
  sourceUrl: "https://aion2.plaync.com/ko-kr/board/notice",
  rights: "linked-official-media",
  translations: {
    "zh-hans": { alt: "Aion 2 月影绿洲 Daeva Pass 指南配图", caption: "NC 官方配图；8 月 26 日更新上线『月影绿洲』Daeva Pass 赛季，售卖至 9 月 22 日 05:00，任务与奖励领取至 9 月 23 日维护前。" },
    en: { alt: "Aion 2 Moonlit Oasis Daeva Pass guide image", caption: "Official NC artwork; the August 26 update opened the 'Moonlit Oasis' Daeva Pass season, on sale until September 22, 05:00, with missions and rewards claimable until the September 23 maintenance." },
    fr: { alt: "Image du guide du Passe de Daeva Moonlit Oasis d'Aion 2", caption: "Visuel officiel NC ; la mise à jour du 26 août ouvre la saison du Passe de Daeva « Moonlit Oasis », en vente jusqu'au 22 septembre 05:00." },
    de: { alt: "Bild zum Moonlit-Oasis-Daeva-Pass-Guide für Aion 2", caption: "Offizielles NC-Artwork; das Update vom 26. August eröffnet die Daeva-Pass-Saison „Moonlit Oasis“ (Verkauf bis 22. September 05:00)." },
    es: { alt: "Imagen de la guía del Pase de Daeva Moonlit Oasis de Aion 2", caption: "Arte oficial de NC; la actualización del 26 de agosto abre la temporada «Moonlit Oasis» del Pase de Daeva, a la venta hasta el 22 de septiembre a las 05:00." },
    ja: { alt: "Aion 2 ムーンリットオアシス デイバパス ガイド画像", caption: "NC公式アートワーク；8月26日のアップデートで「ムーンリットオアシス」デイバパスシーズンが始まり、9月22日05:00まで販売です。" },
    "pt-br": { alt: "Imagem do guia do Daeva Pass Moonlit Oasis do Aion 2", caption: "Arte oficial da NC; a atualização de 26 de agosto abre a temporada «Moonlit Oasis» do Daeva Pass, à venda até 22 de setembro às 05:00." },
    ru: { alt: "Изображение гайда по Daeva Pass «Лунный оазис» в Aion 2", caption: "Официальный арт NC; обновление от 26 августа открывает сезон Daeva Pass «Лунный оазис» — продажа до 22 сентября 05:00." },
    ko: { alt: "Aion 2 문릿 오아시스 데이바 패스 가이드 이미지", caption: "NC 공식 이미지입니다. 8월 26일 업데이트로 '문릿 오아시스' 데이바 패스 시즌이 열렸으며 9월 22일 05:00까지 판매됩니다." },
    "zh-hant": { alt: "Aion 2 月影綠洲 Daeva Pass 指南配圖", caption: "NC 官方配圖；8 月 26 日更新上線『月影綠洲』Daeva Pass 賽季，販售至 9 月 22 日 05:00，任務與獎勵領取至 9 月 23 日維護前。" },
  },
};

export const trendingAugust29Article3: ContentEntry = {
  section: "guides",
  slug: "aion-2-moonlit-oasis-daeva-pass-guide",
  schemaType: "Article",
  publishedAt: "2026-08-28",
  updatedAt: "2026-08-28",
  readingMinutes: 5,
  publication: publishedVerified,
  sources: [dpSource1, dpSource2],
  heroImage: dpHero,
  related: [
    { kind: "content", section: "guides", slug: "aion-2-daeva-pass-guide" },
    { kind: "content", section: "news", slug: "aion-2-founders-packs-30-day-membership" },
    { kind: "content", section: "guides", slug: "aion-2-great-rebalance-patch-guide" },
    { kind: "content", section: "guides", slug: "aion-2-brokerage-market-guide" },
  ],
  translations: {
    en: articleCopy(guideLabels, "en", 5, {
      eyebrow: "DAEVA PASS — NEW SEASON",
      title: "Moonlit Oasis Daeva Pass Guide: Rewards, EXP Rules & Dates",
      description: "The August 26 update opened the 'Moonlit Oasis' Daeva Pass season for the Korean/Taiwanese version — on sale until September 22. Here are the prices, the 50-level reward track, weekly EXP caps, and the Premium coin bonuses.",
      intro: "The August 26 'Great Rebalance' update also rolled in a new Daeva Pass season — 'Moonlit Oasis' — for the Korean/Taiwanese live version. Running from the August 26 maintenance to September 22, it pairs a 50-level reward track with a strict weekly EXP cap and both a Kina-priced Basic pass and a Quna-priced Premium pass. This guide lays out the exact prices, dates, reward structure and EXP rules so you can decide whether the season is worth your Kina or Quna.",
      sourceNote: "Based on AION2T's full breakdown of the August 26, 2026 update notes, cross-checked against NC's official notice board. These are the live Korean/Taiwanese version numbers; the global Daeva Pass at launch may differ.",
      keywords: ["Aion 2 Moonlit Oasis Daeva Pass", "Aion 2 Daeva Pass season", "Aion 2 Daeva Pass rewards", "Aion 2 pass September 2026", "Aion 2 Daeva Pass premium"],
      sections: [
        section("dates", "Season Dates & Products", ["The season opened with the August 26 maintenance and the two passes go on sale until September 22, 05:00. Missions and rewards remain claimable until just before the September 23 maintenance — so there is a short grace period after the sale ends.", "Moonlit Oasis (Basic) costs 2,000,000 Kina and can be bought once per character. Moonlit Oasis (Premium) costs 1,000 Quna and includes 10 Odyle Energy (Bound) on top of the pass itself — once per character.", "Both are tied to the live KR/TW version; global launch mechanics for a Daeva Pass equivalent have not been announced yet."]),
        section("reward-track", "The 50-Level Reward Track", ["The track runs to level 50, with a reward granted at every level, and EXP earned beyond 50 converts into repeat rewards instead: Battle Enhance Scroll (Bound) x3 on Basic, or Odyle Energy (Bound) x1 on Premium per repeat.", "If you need levels fast, they can be purchased outright at 50 Quna per level — a convenience option for late-season catch-up.", "Premium also pays 1,500 Daeva Pass Shop Coin: Chapter 1 at levels 2, 7, 12, 17, 22, 27, 32, 37, 42 and 47 — 15,000 coins over the full track."]),
        section("exp-rules", "Weekly EXP Cap & Sources", ["There is a hard cap of 15,000 XP per character per week, which defines how fast anyone can realistically progress — plan for roughly a level-and-a-half of pure progression per week under the cap.", "The fastest sources: 300 XP per Expedition or Transcendence clear and 700 XP per Sanctuary clear, versus 50 XP per 10 monsters, 100 XP per enemy-faction player kill, 30 XP per gathering action and 20 XP per crafting action.", "Lighter background sources include 10 XP per enchant, 10 XP per extraction and 20 XP per soul binding — progress that accrues while you play normally."]),
        section("kina-context", "Pass & the Bound-Kina Update", ["The season launches alongside the new Bound Kina system in six dungeon modes — Kina earned in Fire Temple, Ferocious Horn Den, Dying Dramata's Nest, Cradle of Nihility, Submerged Life Temple and Abyssal Forge: Ludra now stays account-bound and cannot be traded.", "If you were planning to fund a Premium pass by selling dungeon Kina, that route is now closed: bound Kina can't leave your account, so buying the pass comes from unbound income or Quna directly.", "The brokerage market guide covers what still moves between players after the change."]),
        section("takeaway", "Worth It?", ["For players who expect to clear Expeditions/Sanctuary content weekly, the Basic pass is essentially pure upside: 2M Kina for a 50-level reward track that refunds itself in materials and scrolls.", "Premium is the pick for players who want the 15,000 Shop Coins and the Odyle Energy accelerant — but at 1,000 Quna it only makes sense if you were already spending on the shop this month.", "For everyone else, the generic Daeva Pass guide explains how the system works across seasons, and the global version may simplify or change these numbers before launch."]),
      ],
    }),
    "zh-hans": articleCopy(guideLabels, "zh-hans", 5, {
      eyebrow: "DAEVA PASS——新赛季",
      title: "月影绿洲 Daeva Pass 指南：奖励、经验规则与日期",
      description: "8 月 26 日更新为韩/台版上线『月影绿洲』Daeva Pass 赛季——售卖至 9 月 22 日。以下为价格、50 级奖励路线、每周经验上限与高级版代币加成。",
      intro: "8 月 26 日『大平衡』更新同时为韩/台线上版带来新 Daeva Pass 赛季——『月影绿洲』。赛季自 8 月 26 日维护后持续至 9 月 22 日，采用 50 级奖励路线、严格周经验上限，并提供基纳购买的普通版与 Quna 购买的豪华版。本指南列出准确价格、日期、奖励结构与经验规则，帮助你判断本赛季是否值得投入。",
      sourceNote: "基于 AION2T 对 2026 年 8 月 26 日更新说明的完整拆解，并与 NC 官方公告板交叉核对。以上为韩/台线上版数字；全球版上线时的 Daeva Pass 可能不同。",
      keywords: ["Aion 2 月影绿洲 Daeva Pass", "Aion 2 Daeva Pass 赛季", "Aion 2 Daeva Pass 奖励", "Aion 2 9月通行证", "Aion 2 Daeva Pass 豪华版"],
      sections: [
        section("dates", "赛季日期与商品", ["赛季随 8 月 26 日维护开启，两款通行证售卖至 9 月 22 日 05:00；任务与奖励领取持续至 9 月 23 日维护前——售卖结束后有短暂宽限期。", "月影绿洲（普通版）：2,000,000 基纳，每角色一次；月影绿洲（豪华版）：1,000 Quna，额外含 10 个绑定奥德能量，每角色一次。", "两者均绑定韩/台线上版；全球版的 Daeva Pass 机制尚未公布。"]),
        section("reward-track", "50 级奖励路线", ["路线最高 50 级，每级发放奖励；超过 50 级的经验转为循环奖励：普通版每次 绑定战斗强化卷轴 ×3，豪华版每次 绑定奥德能量 ×1。", "需要快速升级可直购：每级 50 Quna。", "豪华版另在 2/7/12/17/22/27/32/37/42/47 级各发 1,500 第 1 章 Daeva Pass 商店币——全路线共 15,000。"]),
        section("exp-rules", "每周经验上限与来源", ["硬上限 15,000 经验/角色/周，决定实际推进速度——上限内每周约合一级半进度。", "最快来源：远征/超越通关 300 经验、圣所通关 700 经验；对比每 10 只怪 50、敌对阵营击杀 100、采集 30、制作 20。", "轻度后台来源：强化 10、提取 10、灵魂绑定 20——正常游玩自然累积。"]),
        section("kina-context", "通行证与绑定基纳更新", ["本赛季与六副本绑定基纳系统同步上线——炎之神殿、凶兽角巢、垂死德拉玛塔之巢、虚无摇篮、水下生命神殿、深渊锻造炉：卢德拉产出的基纳将绑定账户不可交易。", "若曾打算靠卖副本基纳充豪华版，此路已断：绑定基纳无法离开账户，购买通行证只能来自非绑定收入或直接 Quna。", "拍卖行市指南覆盖变更后玩家间仍可流通的物品。"]),
        section("takeaway", "值得吗？", ["每周稳定清远征/圣所内容的玩家，普通版几乎是纯收益：2M 基纳换 50 级奖励路线，材料与卷轴即可回本。", "豪华版适合想要 15,000 商店币与奥德能量加速剂的玩家——但 1,000 Quna 仅在本月本就打算充值时划算。", "其余玩家可参考通用 Daeva Pass 指南了解跨赛季机制；全球版可能在上线前简化或调整上述数字。"]),
      ],
    }),
    ko: articleCopy(guideLabels, "ko", 5, {
      eyebrow: "데이바 패스 — 신규 시즌",
      title: "문릿 오아시스 데이바 패스 가이드: 보상, 경험치 규칙, 날짜",
      description: "8월 26일 업데이트로 한/대만 버전에 '문릿 오아시스' 데이바 패스 시즌이 열렸습니다 — 9월 22일까지 판매. 가격, 50레벨 보상 트랙, 주간 경험치 상한, 프리미엄 코인 보너스를 정리합니다.",
      intro: "8월 26일 '그레이트 리밸런스' 업데이트와 함께 한/대만 라이브 버전에 새 데이바 패스 시즌 '문릿 오아시스'가 등장했습니다. 8월 26일 점검부터 9월 22일까지, 50레벨 보상 트랙과 엄격한 주간 경험치 상한, 키나 기본 팩과 Quna 프리미엄 팩으로 구성됩니다.",
      sourceNote: "AION2T의 2026년 8월 26일 업데이트 노트 전문 분석과 NC 공식 공지 교차 확인 기반. 한/대만 라이브 수치이며 글로벌 출시판은 다를 수 있습니다.",
      keywords: ["Aion 2 문릿 오아시스 데이바 패스", "Aion 2 데이바 패스 시즌", "Aion 2 데이바 패스 보상", "Aion 2 9월 패스", "Aion 2 데이바 패스 프리미엄"],
      sections: [
        section("dates", "시즌 기간과 상품", "8월 26일 점검과 함께 시작, 두 팩 모두 9월 22일 05:00까지 판매. 미션과 보상 수령은 9월 23일 점검 직전까지. 기본팩 200만 키나(캐릭터당 1회), 프리미엄팩 1,000 Quna(귀속 오딜 에너지 10개 포함)."),
        section("reward-track", "50레벨 보상 트랙", "매 레벨 보상, 50레벨 초과 경험치는 반복 보상으로 전환(기본 3회 전투 강화 두루마리, 프리미엄 귀속 오딜 에너지 1개). 레벨 직구 50 Quna. 프리미엄은 2/7/12/17/22/27/32/37/42/47레벨에서 1,500 코인씩 총 15,000 코인 지급."),
        section("exp-rules", "주간 경험치 상한과 원천", "캐릭터당 주 15,000 XP 상한. 원정/초월 클리어 300, 성역 클리어 700, 몬스터 10마리 50, 적 진영 처치 100, 채집 30, 제작 20, 인챈트 10, 추출 10, 영혼 결속 20."),
        section("kina-context", "패스와 귀속 키나 업데이트", "6개 던전 모드의 귀속 키나 시스템(불의 사원, 사나운 뿔 소굴, 드라마타 둥지, 허무의 요람, 수중 생명 사원, 심연 대장간: 루드라)이 동시에 시작됐습니다. 귀속 키나로는 프리미엄 팩을 살 수 없습니다."),
        section("takeaway", "가치 판단", "주간 원정/성역 클리어러에게 기본 팩은 사실상 무조건 이득. 15,000 코인과 오딜 에너지를 원하면 프리미엄. 글로벌판은 숫자가 달라질 수 있습니다."),
      ],
    }),
    ja: articleCopy(guideLabels, "ja", 5, {
      eyebrow: "デイバパス — 新シーズン",
      title: "ムーンリットオアシス デイバパスガイド：報酬、EXPルール、日程",
      description: "8月26日のアップデートで韓/台湾版に『ムーンリットオアシス』デイバパスシーズンが開幕しました（9月22日まで販売）。価格、50レベル報酬、週間EXP上限、プレミアムコインボーナスを整理します。",
      intro: "8月26日の『グレートリバランス』アップデートとともに、韓/台湾ライブ版に新デイバパスシーズン『ムーンリットオアシス』が登場しました。8月26日メンテから9月22日まで、50レベル報酬トラック、厳格な週間EXP上限、キナ基本パックとQunaプレミアムパックで構成されます。",
      sourceNote: "AION2T の2026年8月26日アップデートノート詳細分析と NC 公式告知の照合に基づきます。韓/台湾ライブの数値であり、グローバル版では異なる可能性があります。",
      keywords: ["Aion 2 ムーンリットオアシス デイバパス", "Aion 2 デイバパス シーズン", "Aion 2 デイバパス 報酬", "Aion 2 9月パス", "Aion 2 デイバパス プレミアム"],
      sections: [
        section("dates", "シーズン日程と商品", "8月26日メンテから開始、両パックとも9月22日05:00まで販売。ミッションと報酬受領は9月23日メンテ直前まで。基本パック200万キナ（キャラごと1回）、プレミアム1,000 Quna（帰属オディルエナジー 10個付き）。"),
        section("reward-track", "50レベル報酬トラック", "毎レベル報酬。50超の経験値は繰り返し報酬（基本：戦闘強化スクロール（帰属）×3、プレミアム：オディルエナジー（帰属）×1）。レベル直購入50 Quna。プレミアムは2/7/12/17/22/27/32/37/42/47レベルで各1,500コイン、計15,000。"),
        section("exp-rules", "週間EXP上限と獲得源", "キャラごと週15,000 XPが上限。遠征/超越クリア300、聖域クリア700、モンスター10体50、敵陣営キル100、採集30、製作20、エンチャント10、抽出10、ソウルバインド20。"),
        section("kina-context", "パスと帰属キナ更新", "6ダンジョンモードの帰属キナ（火の神殿、猛々しい角の巣、ドラマタの巣、虚無の揺籃、水没生命神殿、深淵鍛冶場：ルドラ）が同時開始。帰属キナでプレミアム購入は不可。"),
        section("takeaway", "価値判断", "週間で遠征/聖域を回す人は基本パックはほぼ確実に得。15,000コインと加速材が欲しいならプレミアム。グローバル版は数字が変わる可能性があります。"),
      ],
    }),
    fr: articleCopy(guideLabels, "fr", 5, {
      eyebrow: "PASSE DE DAEVA — NOUVELLE SAISON",
      title: "Guide du Passe de Daeva Moonlit Oasis : récompenses, règles d'EXP et dates",
      description: "La mise à jour du 26 août a ouvert la saison « Moonlit Oasis » du Passe de Daeva pour la version coréenne/taiwanaise — en vente jusqu'au 22 septembre. Prix, piste de 50 niveaux, plafonds d'EXP hebdo.",
      intro: "La mise à jour « Grand rééquilibrage » du 26 août a aussi ajouté une nouvelle saison de Passe de Daeva — « Moonlit Oasis » — sur la version KR/TW. Du 26 août au 22 septembre, avec une piste de 50 niveaux, un plafond hebdo strict et deux passes : Basic en Kina, Premium en Quna.",
      sourceNote: "Basé sur l'analyse complète d'AION2T des notes du 26 août 2026, croisée avec le tableau d'annonces NC. Chiffres de la version KR/TW ; la version globale peut différer.",
      keywords: ["Aion 2 Moonlit Oasis Passe de Daeva", "Aion 2 saison passe", "Aion 2 récompenses passe", "Aion 2 passe septembre 2026"],
      sections: [
        section("dates", "Dates et produits", "Du 26 août au 22 septembre 05:00 (missions jusqu'à la maintenance du 23 septembre). Basic : 2 000 000 Kina (1x/perso). Premium : 1 000 Quna + 10 Énergie d'Odyle (liée)."),
        section("reward-track", "Piste de 50 niveaux", "Une récompense par niveau ; au-delà de 50, récompenses répétées (Parchemin de renforcement ×3 / Odyle ×1). Niveaux achetables à 50 Quna. Premium : 1 500 pièces boutique aux niveaux 2-47 (15 000 au total)."),
        section("exp-rules", "Plafonds et sources d'EXP", "15 000 EXP/semaine maximum par personnage. Sources : 300 en expédition/transcendance, 700 en sanctuaire, 50/10 monstres, 100 kill faction adverse, 30 récolte, 20 artisanat."),
        section("kina-context", "Passe et Kina liée", "Le passe sort avec la Kina liée de six donjons — la Kina de ces modes ne peut plus être revendue ; impossible de financer le Premium en vendant de la Kina de donjon."),
        section("takeaway", "Ça vaut le coup ?", "Le Basic est quasi tout bénéfice pour les joueurs qui font des expéditions chaque semaine. Premium pour les 15 000 coins et l'Ostyle. La version globale peut changer ces chiffres."),
      ],
    }),
    de: articleCopy(guideLabels, "de", 5, {
      eyebrow: "DAEVA PASS — NEUE SAISON",
      title: "Moonlit-Oasis-Daeva-Pass-Guide: Belohnungen, EXP-Regeln & Termine",
      description: "Das Update vom 26. August eröffnete die Daeva-Pass-Saison „Moonlit Oasis“ für die koreanische/taiwanesische Version — Verkauf bis 22. September. Preise, 50-Stufen-Belohnungsbahn, wöchentliches EXP-Limit.",
      intro: "Das „Great Rebalance“-Update vom 26. August brachte auch eine neue Daeva-Pass-Saison — „Moonlit Oasis“ — für KR/TW. Vom 26. August bis 22. September, mit 50-Stufen-Bahn, striktem Wochenlimit und Basic- (Kina) bzw. Premium-Pass (Quna).",
      sourceNote: "Basierend auf AION2Ts Analyse der Update-Notizen vom 26. August 2026, abgeglichen mit den NC-Ankündigungen. KR/TW-Werte; die globale Version kann abweichen.",
      keywords: ["Aion 2 Moonlit Oasis Daeva Pass", "Aion 2 Daeva-Pass-Saison", "Aion 2 Daeva-Pass-Belohnungen", "Aion 2 Pass September 2026"],
      sections: [
        section("dates", "Termine & Produkte", "Vom 26. August bis 22. September 05:00 (Missionen bis zur Wartung am 23. September). Basic: 2.000.000 Kina (1x/Charakter). Premium: 1.000 Quna + 10 Odyle-Energie (gebunden)."),
        section("reward-track", "50-Stufen-Bahn", "Belohnung pro Stufe; über 50 hinaus Wiederholungsbelohnungen (Kampfverstärkungsrolle ×3 / Odyle ×1). Stufen kaufbar für 50 Quna. Premium: 1.500 Shop-Coins auf den Stufen 2-47 (15.000 gesamt)."),
        section("exp-rules", "EXP-Limit & Quellen", "Max. 15.000 EXP/Woche pro Charakter. Quellen: 300 Expedition/Transzendenz, 700 Heiligtum, 50/10 Monster, 100 feindliche Fraktions-Kills, 30 Sammeln, 20 Handwerk."),
        section("kina-context", "Pass & gebundenes Kina", "Der Pass startet mit dem gebundenen Kina aus sechs Dungeons — dieses Kina kann nicht mehr gehandelt werden; ein Verkauf zum Finanzieren des Premium-Passes entfällt."),
        section("takeaway", "Lohnt sich das?", "Basic ist für wöchentliche Expeditions-Spieler praktisch reiner Gewinn. Premium für 15.000 Coins und Odyle-Boost. Die globale Version kann die Zahlen ändern."),
      ],
    }),
    es: articleCopy(guideLabels, "es", 5, {
      eyebrow: "PASE DE DAEVA — NUEVA TEMPORADA",
      title: "Guía del Pase de Daeva Moonlit Oasis: recompensas, reglas de EXP y fechas",
      description: "La actualización del 26 de agosto abrió la temporada «Moonlit Oasis» del Pase de Daeva para la versión coreana/taiwanesa — a la venta hasta el 22 de septiembre. Precios, pista de 50 niveles, límites semanales de EXP.",
      intro: "La actualización del «Gran rebalanceo» del 26 de agosto también trajo una nueva temporada del Pase de Daeva — «Moonlit Oasis» — para la versión KO/TW. Del 26 de agosto al 22 de septiembre, con pista de 50 niveles, tope semanal estricto y pases Basic (Kina) y Premium (Quna).",
      sourceNote: "Basado en el análisis completo de AION2T de las notas del 26 de agosto de 2026 y el tablón oficial de NC. Valores KO/TW; la versión global puede diferir.",
      keywords: ["Aion 2 Moonlit Oasis Pase de Daeva", "Aion 2 temporada del pase", "Aion 2 recompensas pase", "Aion 2 pase septiembre 2026"],
      sections: [
        section("dates", "Fechas y productos", "Del 26 de agosto al 22 de septiembre 05:00 (misiones hasta el mantenimiento del 23). Básico: 2.000.000 Kina (1x/personaje). Premium: 1.000 Quna + 10 Energía Odyle (vinculada)."),
        section("reward-track", "Pista de 50 niveles", "Recompensa por nivel; más allá de 50, recompensas repetidas (Pergamino de refuerzo ×3 / Odyle ×1). Niveles comprables a 50 Quna. Premium: 1.500 monedas en niveles 2-47 (15.000 en total)."),
        section("exp-rules", "Límites y fuentes de EXP", "Máx. 15.000 EXP/semana por personaje. Fuentes: 300 expedición/trascendencia, 700 santuario, 50/10 monstruos, 100 kill de facción enemiga, 30 recolección, 20 artesanía."),
        section("kina-context", "Pase y Kina vinculada", "El pase llega con la Kina vinculada de seis mazmorras — esa Kina ya no puede venderse; financiar el Premium vendiendo Kina queda descartado."),
        section("takeaway", "¿Merece la pena?", "El Básico es casi todo ganancia para jugadores de expediciones semanales. Premium para las 15.000 monedas y el impulso de Odyle. La versión global puede cambiar las cifras."),
      ],
    }),
    "pt-br": articleCopy(guideLabels, "pt-br", 5, {
      eyebrow: "PASSE DE DAEVA — NOVA TEMPORADA",
      title: "Guia do Daeva Pass Moonlit Oasis: recompensas, regras de EXP e datas",
      description: "A atualização de 26 de agosto abriu a temporada «Moonlit Oasis» do Daeva Pass para a versão coreana/taiwanesa — à venda até 22 de setembro. Preços, trilha de 50 níveis, limites semanais de EXP.",
      intro: "A atualização do «Grande reequilíbrio» de 26 de agosto também trouxe uma nova temporada do Daeva Pass — «Moonlit Oasis» — para a versão KO/TW. De 26 de agosto a 22 de setembro, com trilha de 50 níveis, teto semanal estrito e passes Básico (Kina) e Premium (Quna).",
      sourceNote: "Com base na análise completa da AION2T das notas de 26 de agosto de 2026 e no quadro de avisos da NC. Valores KO/TW; a versão global pode diferir.",
      keywords: ["Aion 2 Moonlit Oasis Daeva Pass", "Aion 2 temporada do passe", "Aion 2 recompensas do passe", "Aion 2 passe setembro 2026"],
      sections: [
        section("dates", "Datas e produtos", "De 26 de agosto a 22 de setembro às 05:00 (missões até a manutenção do dia 23). Básico: 2.000.000 Kina (1x/personagem). Premium: 1.000 Quna + 10 Energia Odyle (vinculada)."),
        section("reward-track", "Trilha de 50 níveis", "Recompensa por nível; acima de 50, recompensas repetidas (Pergaminho de reforço ×3 / Odyle ×1). Níveis compráveis a 50 Quna. Premium: 1.500 moedas nos níveis 2-47 (15.000 no total)."),
        section("exp-rules", "Limites e fontes de EXP", "Máx. 15.000 EXP/semana por personagem. Fontes: 300 expedição/transcendência, 700 santuário, 50/10 monstros, 100 kill de facção inimiga, 30 coleta, 20 artesanato."),
        section("kina-context", "Passe e Kina vinculada", "O passe chega com a Kina vinculada de seis masmorras — essa Kina não pode mais ser vendida; financiar o Premium vendendo Kina fica descartado."),
        section("takeaway", "Vale a pena?", "O Básico é quase tudo ganho para jogadores de expedições semanais. Premium para as 15.000 moedas e o impulso de Odyle. A versão global pode mudar os números."),
      ],
    }),
    ru: articleCopy(guideLabels, "ru", 5, {
      eyebrow: "DAEVA PASS — НОВЫЙ СЕЗОН",
      title: "Гайд по Daeva Pass «Лунный оазис»: награды, правила опыта и даты",
      description: "Обновление от 26 августа открыло сезон «Лунный оазис» Daeva Pass для корейской/тайваньской версии — продажа до 22 сентября. Цены, дорога 50 уровней, недельные лимиты опыта.",
      intro: "Обновление «Великий ребаланс» от 26 августа также принесло новый сезон Daeva Pass — «Лунный оазис» — для версии KO/TW. С 26 августа по 22 сентября: дорога 50 уровней, строгий недельный лимит, базовый пас за Кину и премиум за Quna.",
      sourceNote: "На основе полного разбора AION2T примечаний от 26 августа 2026 и официальной доски NC. Значения KO/TW; глобальная версия может отличаться.",
      keywords: ["Aion 2 Лунный оазис Daeva Pass", "Aion 2 сезон Daeva Pass", "Aion 2 награды Daeva Pass", "Aion 2 пас сентябрь 2026"],
      sections: [
        section("dates", "Даты и товары", "С 26 августа до 22 сентября 05:00 (миссии до обслуживания 23-го). Базовый: 2 000 000 Кины (1x/персонаж). Премиум: 1 000 Quna + 10 Энергия Одиля (связанная)."),
        section("reward-track", "Дорога 50 уровней", "Награда за каждый уровень; сверх 50 — повторные награды (Свиток усиления ×3 / Одиль ×1). Уровни покупаются по 50 Quna. Премиум: 1 500 монет на уровнях 2–47 (15 000 всего)."),
        section("exp-rules", "Лимиты и источники опыта", "Макс. 15 000 опыта/неделю на персонажа. Источники: 300 экспедиция/трансцендентность, 700 святилище, 50/10 монстров, 100 убийство вражеской фракции, 30 сбор, 20 крафт."),
        section("kina-context", "Пас и связанная Кина", "Пас выходит вместе со связанной Киной из шести данжей — эту Кину нельзя продавать; финансировать премиум продажей Кины больше нельзя."),
        section("takeaway", "Стоит ли?", "Базовый пас почти чистый выигрыш для игроков еженедельных экспедиций. Премиум — ради 15 000 монет и ускорения Одиля. Глобальная версия может изменить цифры."),
      ],
    }),
    "zh-hant": articleCopy(guideLabels, "zh-hant", 5, {
      eyebrow: "DAEVA PASS——新賽季",
      title: "月影綠洲 Daeva Pass 指南：獎勵、經驗規則與日期",
      description: "8 月 26 日更新為韓/台版上線『月影綠洲』Daeva Pass 賽季——販售至 9 月 22 日。以下為價格、50 級獎勵路線、每週經驗上限與豪華版代幣加成。",
      intro: "8 月 26 日『大平衡』更新同時為韓/台線上版帶來新 Daeva Pass 賽季——『月影綠洲』。賽季自 8 月 26 日維護後持續至 9 月 22 日，採用 50 級獎勵路線、嚴格週經驗上限，並提供基納購買的普通版與 Quna 購買的豪華版。本指南列出準確價格、日期、獎勵結構與經驗規則，幫助你判斷本賽季是否值得投入。",
      sourceNote: "基於 AION2T 對 2026 年 8 月 26 日更新說明的完整拆解，並與 NC 官方公告板交叉核對。以上為韓/台線上版數字；全球版上線時的 Daeva Pass 可能不同。",
      keywords: ["Aion 2 月影綠洲 Daeva Pass", "Aion 2 Daeva Pass 賽季", "Aion 2 Daeva Pass 獎勵", "Aion 2 9月通行證", "Aion 2 Daeva Pass 豪華版"],
      sections: [
        section("dates", "賽季日期與商品", ["賽季隨 8 月 26 日維護開啟，兩款通行證販售至 9 月 22 日 05:00；任務與獎勵領取持續至 9 月 23 日維護前——販售結束後有短暫寬限期。", "月影綠洲（普通版）：2,000,000 基納，每角色一次；月影綠洲（豪華版）：1,000 Quna，額外含 10 個綁定奧德能量，每角色一次。", "兩者均綁定韓/台線上版；全球版的 Daeva Pass 機制尚未公布。"]),
        section("reward-track", "50 級獎勵路線", ["路線最高 50 級，每級發放獎勵；超過 50 級的經驗轉為循環獎勵：普通版每次 綁定戰鬥強化卷軸 ×3，豪華版每次 綁定奧德能量 ×1。", "需要快速升級可直購：每級 50 Quna。", "豪華版另在 2/7/12/17/22/27/32/37/42/47 級各發 1,500 第 1 章 Daeva Pass 商店幣——全路線共 15,000。"]),
        section("exp-rules", "每週經驗上限與來源", ["硬上限 15,000 經驗/角色/週，決定實際推進速度——上限內每週約合一級半進度。", "最快來源：遠征/超越通關 300 經驗、聖所通關 700 經驗；對比每 10 隻怪 50、敵對陣營擊殺 100、採集 30、製作 20。", "輕度後台來源：強化 10、提取 10、靈魂綁定 20——正常遊玩自然累積。"]),
        section("kina-context", "通行證與綁定基納更新", ["本賽季與六副本綁定基納系統同步上線——炎之神殿、凶獸角巢、垂死德拉瑪塔之巢、虛無搖籃、水下生命神殿、深淵鍛造爐：盧德拉產出的基納將綁定帳戶不可交易。", "若曾打算靠賣副本基納充豪華版，此路已斷：綁定基納無法離開帳戶，購買通行證只能來自非綁定收入或直接 Quna。", "拍賣行市指南涵蓋變更後玩家間仍可流通的物品。"]),
        section("takeaway", "值得嗎？", ["每週穩定清遠征/聖所內容的玩家，普通版幾乎是純收益：2M 基納換 50 級獎勵路線，材料與卷軸即可回本。", "豪華版適合想要 15,000 商店幣與奧德能量加速劑的玩家——但 1,000 Quna 僅在本月本就打算儲值時划算。", "其餘玩家可參考通用 Daeva Pass 指南了解跨賽季機制；全球版可能在上線前簡化或調整上述數字。"]),
      ],
    }),
  },
};