import { articleCopy, localizations, newsLabels, publishedVerified, section } from "./trending-september-1-shared";
import type { ContentEntry, ContentHeroImage, ContentSource } from "./content-registry";

/* ARTICLE 2 — Korean press: NC hits an all-time-high first-half 2026 PC revenue, Aion 2 a key driver */

const revSource1: ContentSource = {
  id: "chosunbiz-nc-h1-record-2026-08-27",
  kind: "third-party", publisher: "Chosunbiz",
  label: "‘아이온2·리니지 클래식’ 효과…엔씨, 상반기 PC 매출 사상 최대",
  url: "https://news.google.com/rss/search?q=%22%EC%83%81%EB%B0%98%EA%B8%B0%20PC%20%EB%A7%A4%EC%B6%9C%22%20%EC%97%94%EC%94%A8&hl=ko&gl=KR&ceid=KR:ko",
  publishedAt: "2026-08-27",
  retrievedAt: "2026-09-01",
  verifiedAt: "2026-09-01",
  localizations: localizations({
    "zh-hans": "「Aion 2 · Lineage Classic 效应」……NC，上半年 PC 营收史上最高",
    en: "“Aion 2 · Lineage Classic effect”… NC posts all-time-high first-half PC revenue",
    fr: "« Effet Aion 2 et Lineage Classic »… record de revenus PC au premier semestre chez NC",
    de: "„Aion-2-/Lineage-Classic-Effekt“… NC meldet Rekord-PC-Umsatz im ersten Halbjahr",
    es: "«Efecto Aion 2 y Lineage Classic»… NC marca récord de ingresos de PC en el primer semestre",
    ja: "「アイオン2・リネージュクラシック効果」…NC、上半期PC売上は史上最高",
    "pt-br": "«Efeito Aion 2 e Lineage Classic»… NC registra receita recorde de PC no primeiro semestre",
    ru: "«Эффект Aion 2 и Lineage Classic»… NC фиксирует рекордную выручку на ПК за полугодие",
    ko: "‘아이온2·리니지 클래식’ 효과…엔씨, 상반기 PC 매출 사상 최대",
    "zh-hant": "「Aion 2 · Lineage Classic 效應」……NC，上半年 PC 營收史上最高",
  }, "https://biz.chosun.com/it-science/ict/"),
};

const revSource2: ContentSource = {
  id: "techm-kim-taekjin-decision-2026-08-28",
  kind: "third-party", publisher: "techm",
  label: "AAA급 PC 신작으로 승부수...김택진의 결단, 엔씨 반등 이끌었다",
  url: "https://news.google.com/rss/search?q=AAA%EA%B8%89%20PC%20%EC%8B%A0%EC%9E%91%20%EA%B9%80%ED%83%9D%EC%A7%84&hl=ko&gl=KR&ceid=KR:ko",
  publishedAt: "2026-08-28",
  retrievedAt: "2026-09-01",
  verifiedAt: "2026-09-01",
  localizations: localizations({
    "zh-hans": "以 AAA 级 PC 新作押注……金泽辰的决断带领 NC 反弹",
    en: "Betting on AAA PC titles… Kim Taek-jin's decision led NC's rebound",
    fr: "Parier sur des titres PC AAA… la décision de Kim Taek-jin a mené le rebond de NC",
    de: "AAA-PC-Neuheiten als Trumpf… Kim Taek-jins Entscheidung trug NCs Erholung",
    es: "Apuesta por títulos AAA de PC… la decisión de Kim Taek-jin impulsó el repunte de NC",
    ja: "AAA級PC新作で勝負…김택진の決断がNCの反転を導いた",
    "pt-br": "Aposta em títulos AAA de PC… a decisão de Kim Taek-jin guiou a recuperação da NC",
    ru: "Ставка на ААА-новинки для ПК… решение Ким Тхэкджина привело NC к развороту",
    ko: "AAA급 PC 신작으로 승부수...김택진의 결단, 엔씨 반등 이끌었다",
    "zh-hant": "以 AAA 級 PC 新作下注……金澤辰的決斷帶領 NC 反彈",
  }, "https://www.techm.kr/news/"),
};

const revHero: ContentHeroImage = {
  src: "https://blogfiles.ncsoft.net/news/af7330da-4ff6-4b58-aece-400e6061a3be.jpg",
  width: 1100, height: 605,
  credit: "NC Corporation",
  sourceUrl: "https://aion2.plaync.com/ja-jp/board/notice/list",
  rights: "linked-official-media",
  translations: {
    "zh-hans": { alt: "NC 上半年 PC 营收新闻配图", caption: "NC 官方配图；韩媒制媒称 NC 上半年 PC 营收创史上最高，Aion 2 与《天堂经典》为两大驱动力。" },
    en: { alt: "NC first-half PC revenue news image", caption: "Official NC artwork; Korean press reports NC posted its highest-ever first-half PC revenue, with Aion 2 and Lineage Classic as the two main drivers." },
    fr: { alt: "Image des revenus PC semestriels de NC", caption: "Visuel officiel NC ; la presse coréenne rapporte un record de revenus PC semestriels chez NC, porté par Aion 2 et Lineage Classic." },
    de: { alt: "Bild zu NCs PC-Halbjahresumsatz", caption: "Offizielles NC-Artwork; die koreanische Presse berichtet von NCs Rekord-PC-Halbjahresumsatz, getragen von Aion 2 und Lineage Classic." },
    es: { alt: "Imagen de ingresos semestrales de PC de NC", caption: "Arte oficial de NC; la prensa coreana reporta un récord de ingresos de PC semestrales en NC, impulsado por Aion 2 y Lineage Classic." },
    ja: { alt: "NC上半期PC売上ニュース画像", caption: "NC公式アートワーク；韓国報道はNCの上半期PC売上が史上最高となり、アイオン2とリネージュクラシックが2大牽引役とした。" },
    "pt-br": { alt: "Imagem da receita semestral de PC da NC", caption: "Arte oficial da NC; a imprensa coreana reporta receita recorde de PC no semestre, impulsionada por Aion 2 e Lineage Classic." },
    ru: { alt: "Изображение полугодовой выручки NC на ПК", caption: "Официальный арт NC; корейская пресса сообщает о рекордной полугодовой ПК-выручке NC, драйверы — Aion 2 и Lineage Classic." },
    ko: { alt: "NC 상반기 PC 매출 뉴스 이미지", caption: "NC 공식 이미지입니다. 한국 언론은 NC의 상반기 PC 매출이 사상 최대를 기록했고 아이온2와 리니지 클래식이 두 축이었다고 보도합니다." },
    "zh-hant": { alt: "NC 上半年 PC 營收新聞配圖", caption: "NC 官方配圖；韓媒稱 NC 上半年 PC 營收創史上最高，Aion 2 與《天堂經典》為兩大驅動力。" },
  },
};

export const trendingSeptember1Article2: ContentEntry = {
  section: "news",
  slug: "aion-2-ncsoft-h1-record-pc-revenue",
  schemaType: "NewsArticle",
  publishedAt: "2026-09-01",
  updatedAt: "2026-09-01",
  readingMinutes: 5,
  publication: publishedVerified,
  sources: [revSource1, revSource2],
  heroImage: revHero,
  related: [
    { kind: "content", section: "news", slug: "aion-2-gamescom-2026-preview-impressions" },
    { kind: "content", section: "news", slug: "aion-2-release-date-october-5-2026" },
    { kind: "content", section: "news", slug: "aion-2-ncsoft-global-strategy-korea-playbook" },
    { kind: "content", section: "guides", slug: "aion-2-monetization-f2p-cosmetics-guide" },
  ],
  translations: {
    en: articleCopy(newsLabels, "en", 5, {
      eyebrow: "NC BUSINESS LINE",
      title: "NC Posts All-Time-High First-Half PC Revenue: Aion 2 Named a Key Driver",
      description: "Korean business press reports NC hit its highest-ever first-half PC revenue, with Aion 2 and Lineage Classic credited as the main drivers (Chosunbiz, August 27). This rounds out the picture ahead of Aion 2's October 5 global launch.",
      intro: "The business story around Aion 2's global launch keeps building. On August 27, Chosunbiz reported that NC posted its highest-ever first-half PC revenue, with the headline crediting “Aion 2 and Lineage Classic” — and a day later techm framed the same momentum around chairman Kim Taek-jin's bet on AAA PC titles. This report summarizes what those headlines say, what they don't, and how it fits the October 5 launch.",
      sourceNote: "Based on headline-verified Korean business press reporting: Chosunbiz (August 27, “’Aion 2·Lineage Classic’ effect…NC, highest-ever first-half PC revenue”) and techm (August 28, “Betting on AAA PC titles…Kim Taek-jin's decision led NC's rebound”). Article bodies were not re-fetched; figures cited here are limited to what was previously verified on this site.",
      keywords: ["NC first half 2026 revenue", "NC PC revenue record", "Aion 2 revenue driver", "NCsoft Kim Taek-jin", "Aion 2 business"],
      sections: [
        section("what-press-says", "What the Korean Press Reported", ["On August 27, Chosunbiz's headline stated that NC's first-half 2026 PC revenue reached an all-time high, attributing the result to “Aion 2 and Lineage Classic”. The outlet's reporting sits in the business section — a financial-sheet claim, not a marketing blurb.", "On August 28, techm followed with “Betting on AAA PC titles… Kim Taek-jin's decision led NC's rebound”, attaching the momentum to the chairman's strategic shift toward premium PC games — a direct reference to the same title pipeline that ends with Aion 2's global launch.", "Neither headline gives figures we can quote as verified data beyond what this site already carried; treat the specific revenue numbers with that caution."]),
        section("what-we-already-verified", "What This Site Already Verified", ["In our August 27 batch, this site documented NC's Q1 2026 results: PC game revenue up roughly 210% year-over-year to about $223 million, following Aion 2's Korean and Taiwanese release in November 2025.", "Those Q1 numbers are the verified backdrop for the H1 record headline. The direction of travel — Aion 2 and Lineage Classic driving PC revenue to record levels — is consistent between the two.", "If you arrive here looking for the exact H1 figure, the honest answer is that the verified number remains the Q1 one; the H1 total was reported by Chosunbiz but not re-verified by this site."]),
        section("why-it-matters", "Why It Matters for Aion 2 Players", ["Revenue records matter to players for one practical reason: they fund the live-service roadmap. Aion 2's global build ships with features the Korean service refined — the Great Rebalance, server transfers, bound-Kina economy tools — because the service is self-sustaining.", "The corporation behind the global launch is not in a retrenchment posture: press framing points to increasing PC investment rather than cutting it, which reduces the risk of a delayed or resource-starved global operation.", "It also gives context for the October 5 date: NC is treating the global expansion as the next growth leg, not a side project — the same framing our earlier Korea-playbook report described."]),
        section("caveats", "The Caveats to Keep in Mind", ["Headline evidence is directional, not audited. First-half results usually include Q2, and mobile plus licensing revenue sit outside the “PC revenue” figure the headline emphasizes.", "The Chosunbiz and techm pieces are business-press coverage of public statements; until NC publishes its own first-half disclosure, exact totals belong to the company's official reporting.", "Finally, the global launch itself is a separate risk vector: a record Korean PC business does not guarantee overseas success — the October 5 launch still depends on the LST, server quality, and the free-to-play economy holding up at scale."]),
        section("takeaway", "The Takeaway", ["The Korean press line is clear: Aion 2 sits at the center of NC's strongest PC revenue period on record, and the company is betting on AAA PC titles going forward.", "For players, the practical read is that the live service is funded and the global launch is positioned as a growth priority. Whether that converts into a smooth October 5 is a test the Launch Scale Test on September 17–18 exists to answer.", "Watch NC's own first-half disclosure for the audited totals; until then, treat the record as press-reported rather than company-confirmed."]),
      ],
    }),
    "zh-hans": articleCopy(newsLabels, "zh-hans", 5, {
      eyebrow: "NC 业绩线",
      title: "NC 上半年 PC 营收创史上最高：Aion 2 被点名为主引擎",
      description: "韩媒报道 NC 上半年 PC 营收创历史最高，Aion 2 与《天堂经典》被列为主引擎（Chosunbiz，8/27）。这幅图景为 Aion 2 的 10 月 5 日全球上线补齐了商业背景。",
      intro: "围绕 Aion 2 全球上线的商业故事仍在累积。8 月 27 日 Chosunbiz 报道 NC 上半年 PC 营收创史上最高，标题点名「Aion 2 与《天堂经典》」；一天后 techm 以同一动能报道会长金泽辰对 AAA 级 PC 新作的押注。本文汇总这些标题说了什么、没说什么，以及它与 10 月 5 日上线的关系。",
      sourceNote: "基于标题级核实的韩媒报道：Chosunbiz（8/27「'아이온2·리니지 클래식' 효과…엔씨, 상반기 PC 매출 사상 최대」）与 techm（8/28「AAA급 PC 신작으로 승수부...김택진의 결단, 엔씨 반등 이끌었다」）。正文未重新抓取；本站引用数字限于此前已核实部分。",
      keywords: ["NC 上半年营收", "NC PC 营收纪录", "Aion 2 营收引擎", "NCSOFT 金泽辰", "Aion 2 业绩"],
      sections: [
        section("what-press-says", "韩媒报道了什么", ["8 月 27 日 Chosunbiz 标题称 NC 2026 上半年 PC 营收达史上最高，并将其归于「Aion 2 与《天堂经典》」。该报道在财经版——这是财报声明，不是营销文案。", "8 月 28 日 techm 跟进：「以 AAA 级 PC 新作下注……金泽辰的决断带领 NC 反弹」，把动能归于会长转向高端 PC 游戏的战略——这一产品管线以 Aion 2 全球上线收尾。", "两个标题都没有给出本站可引用的已核实数字；对具体营收金额请保留上述谨慎。"]),
        section("what-we-already-verified", "本站已核实的内容", ["在 8/27 批中，本站记录了 NC 2026 年 Q1 业绩：PC 游戏收入同比增长约 210%（约 2.23 亿美元），Aion 2 于 2025 年 11 月在韩国与台湾上线。", "Q1 数字是 H1 纪录标题的已核实背景。方向一致：Aion 2 与《天堂经典》把 PC 收入推向历史高位。", "若你来找 H1 精确数字：诚实地说，本站已核实的仍是 Q1；H1 总额由 Chosunbiz 报道，但本站未复核。"]),
        section("why-it-matters", "对玩家为何重要", ["营收纪录对玩家有一个实际意义：它支撑长线运营路线图。Aion 2 全球版带着韩服打磨过的系统（大重做、服务器转移、绑定 Kina 经济工具）上线，正因为服务可以自我造血。", "幕后的公司不是收缩姿态：媒体报道指向加大 PC 投入而非削减，这降低了全球运营延迟或缺资源的风险。", "它也为 10 月 5 日提供背景：NC 把全球扩展当作下一增长腿，而非副业——这与我们此前韩厂新剧本报告的说法一致。"]),
        section("caveats", "需要保留的注意点", ["标题证据是方向性的，不是审计结论。上半年通常含 Q2；移动与授权收入在“PC 营收”口径之外。", "Chosunbiz 与 techm 是对公开声明的财经报道；在 NC 发布自己的官方披露前，精确总额以公司正式报告为准。", "最后，全球上线本身是独立风险：韩服 PC 业务的纪录不保证海外成功——10 月 5 日仍取决于 LST、服务器质量与免费经济在大规模下的表现。"]),
        section("takeaway", "结论", ["韩媒口径清晰：Aion 2 处在 NC 史上最强 PC 营收期的中心，公司正押注 AAA 级 PC 新作。", "对玩家，务实的读法是：长线服务有资金支撑，全球上线被定位为增长优先项。它能否转化为顺畅的 10 月 5 日，正是 9 月 17–18 日 Launch Scale Test 要回答的问题。", "等 NC 自己的上半年披露看审计后的总额；在那之前，请把纪录视为媒体报道而非公司确认。"]),
      ],
    }),
    ko: articleCopy(newsLabels, "ko", 5, {
      eyebrow: "NC 실적 라인",
      title: "NC 상반기 PC 매출 사상 최대: 아이온2가 핵심 동력으로 지목",
      description: "한국 언론은 NC의 상반기 PC 매출이 사상 최대를 기록했으며 아이온2와 리니지 클래식이 주력이라고 보도했습니다(조선비즈, 8/27). 아이온2의 10월 5일 글로벌 출시를 앞둔 배경입니다.",
      intro: "아이온2 글로벌 출시를 둘러싼 비즈니스 스토리가 계속 쌓이고 있습니다. 본 기사는 조선비즈(8/27)와 techm(8/28)의 제목 수준 보도를 요약하고, 10월 5일 출시와 어떻게 맞물리는지 정리합니다.",
      sourceNote: "제목 수준으로 검증된 한국 언론 보도 기반: 조선비즈(8/27)와 techm(8/28). 본문 재확인은 하지 않았으며, 인용 수치는 이 사이트가 이전에 검증한 범위로 한정합니다.",
      keywords: ["NC 상반기 매출", "NC PC 매출 기록", "아이온2 매출 동력", "엔씨소프트 김택진", "아이온2 실적"],
      sections: [
        section("what-press-says", "한국 언론이 보도한 것", "8월 27일 조선비즈 제목은 NC의 2026년 상반기 PC 매출이 사상 최대라고 밝히며 '아이온2와 리니지 클래식'을 원인으로 꼽았습니다. 8월 28일 techm은 'AAA급 PC 신작으로 승부수...김택진의 결단'으로 같은 흐름을 다뤘습니다. 두 제목 모두 이 사이트가 인용할 검증된 수치를 주지는 않습니다."),
        section("what-we-already-verified", "이 사이트가 이미 검증한 내용", "8/27 배치에서 NC 2026년 1분기 실적을 기록했습니다: PC 게임 매출 전년 대비 약 210% 증가(약 2.23억 달러), 2025년 11월 한국·대만 출시 이후. H1 기록 제목의 배경은 이 수치이며, 방향성은 일치합니다. H1 정확한 총액은 조선비즈가 보도했지만 이 사이트는 재검증하지 않았습니다."),
        section("why-it-matters", "플레이어에게 중요한 이유", "매출 기록은 라이브 운영 로드맵을 뒷받침합니다. 글로벌 빌드는 대규모 리밸런스, 서버 이전, 바운드 키나 경제 도구 등 한국 서비스에서 다듬은 시스템을 실어 옵니다. NC는 글로벌 확장을 부업이 아닌 다음 성장 축으로 보고 있으며, 이는 월드롤 전반의 기조와 같습니다."),
        section("caveats", "유의할 점", "제목 증거는 방향성일 뿐 감사된 결론이 아닙니다. 모바일·라이선스 수익은 'PC 매출' 밖입니다. NC가 공식 상반기 실적을 공개하기 전까지 정확한 총액은 회사 공시 기준입니다. 글로벌 출시 자체는 별개의 리스크입니다."),
        section("takeaway", "결론", "한국 언론 구도는 명확합니다: 아이온2는 NC 사상 최대 PC 매출기의 중심이며, 회사는 AAA급 PC 신작을 밀고 있습니다. 10월 5일로 이어지느냐는 9월 17–18일 LST가 답할 문제입니다."),
      ],
    }),
    ja: articleCopy(newsLabels, "ja", 5, {
      eyebrow: "NC業績ライン",
      title: "NC上半期PC売上は史上最高：アイオン2が主役に指名",
      description: "韓国報道はNCの上半期PC売上が史上最高となり、アイオン2とリネージュクラシックが主因と報じました（チョスンビズ、8/27）。10月5日のグローバル発売を前にした背景です。",
      intro: "アイオン2のグローバル発売を巡るビジネスストーリーが積み上がっています。本記事はチョスンビズ（8/27）とtechm（8/28）の見出しレベル報道を要約し、10月5日の発売との関係を整理します。",
      sourceNote: "見出しレベルで検証した韓国報道に基づきます：チョスンビズ（8/27）とtechm（8/28）。本文は再取得しておらず、引用数値はこのサイトが既に検証した範囲に限ります。",
      keywords: ["NC 上半期売上", "NC PC売上記録", "アイオン2 売上牽引", "NCSOFT 金澤辰", "アイオン2 業績"],
      sections: [
        section("what-press-says", "韓国報道が伝えたこと", "8月27日、チョスンビズの見出しはNCの2026年上半期PC売上が史上最高とし、『アイオン2とリネージュクラシック』を要因に挙げました。8月28日のtechmは「AAA級PC新作で勝負…金澤辰の決断」と同一の流れを扱いました。どちらの見出しも、当サイトが引用できる検証済み数値は与えません。"),
        section("what-we-already-verified", "このサイトが既に検証した内容", "8/27バッチでNCの2026年第1四半期実績を記録しました：PCゲーム売上は前年比約210%増（約2.23億ドル）。H1記録見出しの背景はこの数値で、方向性は一致します。H1の正確な総額はチョスンビズが報じましたが、当サイトは再検証していません。"),
        section("why-it-matters", "プレイヤーにとっての重要性", "売上記録はライブ運営のロードマップを支えます。グローバル版は大規模リバランス、サーバー移転、バインド・キナ経済ツールなど韓国サービスで磨いたシステムを載せてきます。NCはグローバル拡大を副業ではなく次の成長軸と見ており、これは同社の全体方針と一致します。"),
        section("caveats", "留保事項", "見出し証拠は方向性であり監査結論ではありません。モバイル・ライセンス収益は「PC売上」の外です。NCが公式の上期開示を行うまで、正確な総額は会社発表基準です。"),
        section("takeaway", "結論", "韓国報道の構図は明確です：アイオン2はNC史上最大のPC売上期の中心であり、会社はAAA級PC新作を押しています。10月5日に繋がるかは、9月17–18日のLSTが答える問題です。"),
      ],
    }),
    fr: articleCopy(newsLabels, "fr", 5, {
      eyebrow: "LIGNE MÉTIER NC",
      title: "NC bat son record de revenus PC semestriels : Aion 2 cité comme moteur",
      description: "La presse coréenne rapporte un record de revenus PC semestriels chez NC, porté par Aion 2 et Lineage Classic (Chosunbiz, 27 août). Le décor du lancement mondial d'Aion 2 le 5 octobre.",
      intro: "L'histoire d'entreprise autour du lancement mondial d'Aion 2 se renforce. Chosunbiz (27 août) rapporte un record de revenus PC semestriels attribué à « Aion 2 et Lineage Classic » ; techm (28 août) parle de la même dynamique via la décision de Kim Taek-jin de miser sur le PC AAA. Voici ce que disent ces titres, et leur rapport au 5 octobre.",
      sourceNote: "Basé sur des titres vérifiés de presse coréenne : Chosunbiz (27 août) et techm (28 août). Les corps d'articles n'ont pas été ré-extraits ; les chiffres cités se limitent à ceux déjà vérifiés sur ce site.",
      keywords: ["NC revenus semestriels 2026", "recette PC record NC", "Aion 2 moteur de recette", "NCsoft Kim Taek-jin", "Aion 2 métier"],
      sections: [
        section("what-press-says", "Ce que dit la presse coréenne", "Le 27 août, Chosunbiz titre sur un record de revenus PC semestriels 2026 chez NC, attribué à « Aion 2 et Lineage Classic ». Le 28 août, techm suit avec « miser sur le PC AAA… la décision de Kim Taek-jin ». Aucun chiffre vérifiable n'est donné par les seuls titres."),
        section("what-we-already-verified", "Ce que ce site a déjà vérifié", "Dans le lot du 27 août, ce site a documenté le T1 2026 de NC : revenus PC en hausse d'environ 210 % sur un an (≈223 M$). C'est l'arrière-plan vérifié du record S1. Le total S1 exact a été rapporté par Chosunbiz mais non re-vérifié ici."),
        section("why-it-matters", "Pourquoi c'est important", "Un record finance la feuille de route du live-service : la build globale embarque les systèmes rodés en Corée (grand rééquilibrage, transferts de serveurs, économie Kina liée). NC traite l'expansion globale comme une prochaine jambe de croissance, pas un projet secondaire."),
        section("caveats", "Précautions", "Les titres sont directionnels, pas audités. Le mobile et les licences sont hors du périmètre « PC ». En attendant la divulgation officielle, le total appartient au rapport de la société."),
        section("takeaway", "Conclusion", "La ligne de la presse coréenne est nette : Aion 2 est au centre de la plus forte période de revenus PC de NC et la société parie sur le PC AAA. La conversion en un 5 octobre fluide reste le test du LST des 17–18 septembre."),
      ],
    }),
    de: articleCopy(newsLabels, "de", 5, {
      eyebrow: "NC GESCHÄFTSLINIE",
      title: "NC meldet Rekord-PC-Umsatz im ersten Halbjahr: Aion 2 als zentraler Treiber",
      description: "Die koreanische Wirtschaftspresse berichtet über NCs höchsten je verzeichneten PC-Halbjahresumsatz, getragen von Aion 2 und Lineage Classic (Chosunbiz, 27. August). Der Hintergrund zum globalen Start am 5. Oktober.",
      intro: "Die Unternehmensgeschichte um Aion 2s globalen Start wächst weiter. Chosunbiz (27.8.) meldet einen Rekord-PC-Halbjahresumsatz mit Verweis auf Aion 2 und Lineage Classic; techm (28.8.) führt dieselbe Dynamik auf Kim Taek-jins AAA-PC-Wette zurück. Diese Titel und ihre Bedeutung für den 5. Oktober.",
      sourceNote: "Basierend auf titelgeprüfter koreanischer Wirtschaftspresse: Chosunbiz (27.8.) und techm (28.8.). Artikeltexte wurden nicht erneut abgerufen; zitierte Zahlen beschränken sich auf hier bereits Verifiziertes.",
      keywords: ["NC Halbjahresumsatz 2026", "NC PC-Umsatzrekord", "Aion 2 Umsatztreiber", "NCsoft Kim Taek-jin", "Aion 2 Geschäft"],
      sections: [
        section("what-press-says", "Was die koreanische Presse berichtet", "Chosunbiz meldet am 27.8. einen Allzeithoch-PC-Halbjahresumsatz bei NC, zurückgeführt auf Aion 2 und Lineage Classic. techm folgt am 28.8. mit «AAA-PC-Wette… Kim Taek-jins Entscheidung». Die Titel allein liefern keine verifizierbaren Zahlen."),
        section("what-we-already-verified", "Was hier bereits verifiziert ist", "Im 27.8.-Los dokumentierte die Site NCs Q1 2026: PC-Umsatz ca. +210 % im Jahresvergleich (≈223 M$). Dies ist der verifizierte Hintergrund des Halbjahresrekords. Die genaue S1-Gesamtsumme wurde von Chosunbiz berichtet, hier aber nicht nachgeprüft."),
        section("why-it-matters", "Warum es für Spieler zählt", "Ein Rekord finanziert die Live-Service-Roadmap: Die globale Build bringt die in Korea ausgereiften Systeme mit (großes Rebalancing, Servertransfers, gebundene-Kina-Ökonomie). NC behandelt die Global-Expansion als nächste Wachstumsstufe, nicht als Nebenprojekt."),
        section("caveats", "Vorsichtsnotizen", "Titelbelege sind richtungsweisend, nicht geprüft. Mobile und Lizenzen liegen außerhalb der «PC-Umsatz»-Klammer. Bis zur offiziellen Offenlegung gilt der Unternehmensbericht."),
        section("takeaway", "Fazit", "Die koreanische Presse zeichnet ein klares Bild: Aion 2 steht im Zentrum der stärksten PC-Umsatzperiode von NC, und das Unternehmen setzt auf AAA-PC. Ob daraus ein reibungsloser 5. Oktober wird, entscheidet der LST am 17.–18. September."),
      ],
    }),
    es: articleCopy(newsLabels, "es", 5, {
      eyebrow: "LÍNEA DE NEGOCIO NC",
      title: "NC marca récord de ingresos de PC semestrales: Aion 2 citado como motor",
      description: "La prensa coreana reporta un récord de ingresos de PC semestrales en NC, impulsado por Aion 2 y Lineage Classic (Chosunbiz, 27 de agosto). El telón de fondo del lanzamiento mundial del 5 de octubre.",
      intro: "La historia empresarial en torno al lanzamiento mundial de Aion 2 sigue creciendo. Chosunbiz (27/8) reporta un récord de ingresos de PC semestrales atribuido a «Aion 2 y Lineage Classic»; techm (28/8) habla de la misma dinámica por la decisión de Kim Taek-jin de apostar por el PC AAA. Qué dicen estos titulares y su relación con el 5 de octubre.",
      sourceNote: "Basado en titulares verificados de la prensa coreana: Chosunbiz (27/8) y techm (28/8). Los cuerpos no se re-extrajeron; las cifras citadas se limitan a lo ya verificado en este sitio.",
      keywords: ["NC ingresos semestrales 2026", "récord ingresos PC NC", "Aion 2 motor de ingresos", "NCsoft Kim Taek-jin", "Aion 2 negocio"],
      sections: [
        section("what-press-says", "Qué reporta la prensa coreana", "El 27/8, Chosunbiz titula sobre un récord de ingresos de PC semestrales en NC, atribuido a «Aion 2 y Lineage Classic». El 28/8, techm sigue con «apuesta por PC AAA… la decisión de Kim Taek-jin». Los titulares por sí solos no dan cifras verificables."),
        section("what-we-already-verified", "Lo que este sitio ya verificó", "En el lote del 27/8, este sitio documentó el Q1 2026 de NC: ingresos de PC +210 % interanual (≈223 M$). Ese es el telón de fondo verificado del récord. El total exacto del S1 fue reportado por Chosunbiz, no re-verificado aquí."),
        section("why-it-matters", "Por qué importa a los jugadores", "Un récord financia la hoja de ruta del live-service: la build global trae los sistemas pulidos en Corea (gran rebalanceo, transferencias de servidor, economía de Kina ligada). NC trata la expansión global como una pata de crecimiento, no un proyecto secundario."),
        section("caveats", "Precauciones", "Los titulares son direccionales, no auditados. Móvil y licencias quedan fuera del perímetro «PC». Hasta la divulgación oficial, el total pertenece al informe de la compañía."),
        section("takeaway", "Conclusión", "La línea de la prensa coreana es clara: Aion 2 está en el centro del mayor periodo de ingresos de PC de NC y la empresa apuesta por el PC AAA. Convertirlo en un 5 de octubre fluido es la prueba del LST del 17–18 de septiembre."),
      ],
    }),
    "pt-br": articleCopy(newsLabels, "pt-br", 5, {
      eyebrow: "LINHA DE NEGÓCIOS NC",
      title: "NC registra receita recorde de PC no semestre: Aion 2 citado como motor",
      description: "A imprensa coreana reporta receita recorde de PC semestral na NC, impulsionada por Aion 2 e Lineage Classic (Chosunbiz, 27 de agosto). O pano de fundo do lançamento global de 5 de outubro.",
      intro: "A história empresarial em torno do lançamento global do Aion 2 continua crescendo. A Chosunbiz (27/8) reporta receita recorde de PC semestral, atribuída a «Aion 2 e Lineage Classic»; a techm (28/8) fala da mesma dinâmica pela decisão de Kim Taek-jin de apostar no PC AAA. O que esses títulos dizem e a relação com 5 de outubro.",
      sourceNote: "Baseado em títulos verificados da imprensa coreana: Chosunbiz (27/8) e techm (28/8). Os corpos não foram re-extraídos; os números citados limitam-se ao já verificado neste site.",
      keywords: ["NC receita semestral 2026", "recorde receita PC NC", "Aion 2 motor de receita", "NCsoft Kim Taek-jin", "Aion 2 negócios"],
      sections: [
        section("what-press-says", "O que a imprensa coreana reportou", "No dia 27/8, a Chosunbiz noticia receita recorde de PC semestral na NC, atribuída a «Aion 2 e Lineage Classic». No dia 28/8, a techm segue com «aposta em PC AAA… a decisão de Kim Taek-jin». Os títulos sozinhos não fornecem números verificáveis."),
        section("what-we-already-verified", "O que este site já verificou", "No lote de 27/8, este site documentou o Q1 2026 da NC: receita de PC +210 % na comparação anual (≈US$ 223 mi). Esse é o pano de fundo verificado do recorde. O total exato do S1 foi reportado pela Chosunbiz, não re-verificado aqui."),
        section("why-it-matters", "Por que importa aos jogadores", "Um recorde financia o roteiro do live-service: a build global traz os sistemas refinados na Coreia (grande rebalanceamento, transferências de servidor, economia de Kina vinculada). A NC trata a expansão global como uma perna de crescimento, não um projeto secundário."),
        section("caveats", "Ressalvas", "Os títulos são direcionais, não auditados. Móvel e licenças ficam fora do perímetro «PC». Até a divulgação oficial, o total pertence ao relatório da empresa."),
        section("takeaway", "Conclusão", "A linha da imprensa coreana é clara: o Aion 2 está no centro do maior período de receita de PC da NC e a empresa aposta no PC AAA. Converter isso num 5 de outubro tranquilo é o teste do LST de 17–18 de setembro."),
      ],
    }),
    ru: articleCopy(newsLabels, "ru", 5, {
      eyebrow: "БИЗНЕС-ЛИНИЯ NC",
      title: "NC фиксирует рекордную полугодовую ПК-выручку: Aion 2 назван драйвером",
      description: "Корейская деловая пресса сообщает о рекордной полугодовой ПК-выручке NC, драйверы — Aion 2 и Lineage Classic (Chosunbiz, 27 августа). Фон для мирового запуска Aion 2 5 октября.",
      intro: "Деловая история вокруг мирового запуска Aion 2 набирает обороты. Chosunbiz (27/8) сообщает о рекордной полугодовой ПК-выручке, приписывая её «Aion 2 и Lineage Classic»; techm (28/8) пишет о той же динамике через ставку Ким Тхэкджина на ПК-ААА. Что говорят эти заголовки и как это связано с 5 октября.",
      sourceNote: "Основано на проверенных заголовках корейской деловой прессы: Chosunbiz (27/8) и techm (28/8). Тексты статей повторно не извлекались; цитируемые цифры ограничены уже проверенными на этом сайте.",
      keywords: ["NC полугодовая выручка 2026", "рекорд ПК-выручки NC", "Aion 2 драйвер выручки", "NCsoft Ким Тхэкджин", "Aion 2 бизнес"],
      sections: [
        section("what-press-says", "О чём сообщила корейская пресса", "27/8 Chosunbiz пишет о рекордной полугодовой ПК-выручке NC, приписывая её «Aion 2 и Lineage Classic». 28/8 techm продолжает: «ставка на ПК-ААА… решение Ким Тхэкджина». Сами заголовки не дают проверяемых цифр."),
        section("what-we-already-verified", "Что уже проверено на этом сайте", "В лоте 27/8 сайт задокументировал Q1 2026 NC: ПК-выручка +210 % в годовом сравнении (≈223 млн $). Это проверенный фон рекорда. Точный итог S1 был опубликован Chosunbiz, но здесь не перепроверялся."),
        section("why-it-matters", "Почему это важно игрокам", "Рекорд финансирует дорожную карту live-service: глобальная сборка несёт системы, отточенные в Корее (большой ребаланс, переносы серверов, экономика связанной кинь). NC трактует глобальную экспансию как следующую ветвь роста, а не побочный проект."),
        section("caveats", "Оговорки", "Заголовки направленны, но не аудированы. Мобильные и лицензионные доходы вне рамок «ПК-выручки». До официального раскрытия итог принадлежит отчёту компании."),
        section("takeaway", "Вывод", "Контур корейской прессы ясен: Aion 2 — в центре сильнейшего ПК-периода NC, и компания ставит на ПК-ААА. Превращение этого в гладкий 5 октября — задача стресс-теста 17–18 сентября."),
      ],
    }),
    "zh-hant": articleCopy(newsLabels, "zh-hant", 5, {
      eyebrow: "NC 業績線",
      title: "NC 上半年 PC 營收創史上最高：Aion 2 被點名為主引擎",
      description: "韓媒報導 NC 上半年 PC 營收創歷史最高，Aion 2 與《天堂經典》被列為主引擎（Chosunbiz，8/27）。這幅圖景為 Aion 2 的 10 月 5 日全球上線補齊了商業背景。",
      intro: "圍繞 Aion 2 全球上線的商業故事仍在累積。8 月 27 日 Chosunbiz 報導 NC 上半年 PC 營收創史上最高，標題點名「Aion 2 與《天堂經典》」；一天後 techm 以同一動能報導會長金澤辰對 AAA 級 PC 新作的押注。本文彙總這些標題說了什麼、沒說什麼。",
      sourceNote: "基於標題級核實的韓媒報導：Chosunbiz（8/27）與 techm（8/28）。正文未重新抓取；本站引用數字限於此前已核實部分。",
      keywords: ["NC 上半年營收", "NC PC 營收紀錄", "Aion 2 營收引擎", "NCSOFT 金澤辰", "Aion 2 業績"],
      sections: [
        section("what-press-says", "韓媒報導了什麼", ["8 月 27 日 Chosunbiz 標題稱 NC 2026 上半年 PC 營收達史上最高，並歸於「Aion 2 與《天堂經典》」。8 月 28 日 techm 跟進：「以 AAA 級 PC 新作下注……金澤辰的決斷帶領 NC 反彈」。兩個標題都未給出本站可引用的已核實數字。"]),
        section("what-we-already-verified", "本站已核實的內容", ["在 8/27 批中，本站記錄了 NC 2026 Q1 業績：PC 遊戲收入同比增長約 210%（約 2.23 億美元）。Q1 數字是 H1 紀錄標題的已核實背景；H1 總額由 Chosunbiz 報導，但本站未複核。"]),
        section("why-it-matters", "對玩家為何重要", ["營收紀錄支撐長線營運路線圖：全球版帶著韓服打磨過的系統上線。NC 把全球擴展當作下一增長腿，而非副業——與本站韓廠新劇本報告一致。"]),
        section("caveats", "需要保留的注意點", ["標題證據是方向性的，不是審計結論；移動與授權收入在「PC 營收」口徑之外。NC 發布官方披露前，精確總額以公司正式報告為準。全球上線本身是獨立風險。"]),
        section("takeaway", "結論", ["韓媒口徑清晰：Aion 2 處在 NC 史上最強 PC 營收期的中心。它能否轉化為順暢的 10 月 5 日，正是 9 月 17–18 日 LST 要回答的問題。"]),
      ],
    }),
  },
};