import { articleCopy, guideLabels, localizations, publishedVerified, section } from "./trending-september-10-shared";
import type { ContentEntry, ContentHeroImage, ContentSource } from "./content-registry";

/* ARTICLE 2 — Snowfield of Sorrow farming guide: entry item levels, drops, Hard rewards */

const ncOfficialSource: ContentSource = {
  id: "nc-official-a2-update-2026-09-09",
  kind: "official",
  publisher: "NC Corporation",
  label: "NC's AION 2: New Sanctuary 'Snowfield of Sorrow' Update (Press Release)",
  url: "https://about.ncsoft.com/news/article/A2_update_20260909",
  publishedAt: "2026-09-09",
  retrievedAt: "2026-09-10",
  verifiedAt: "2026-09-10",
  localizations: localizations({
    "zh-hans": "NC 的 AION 2：新 Sanctuary「Snowfield of Sorrow」更新（新闻稿）",
    en: "NC's AION 2: New Sanctuary 'Snowfield of Sorrow' Update (Press Release)",
    fr: "AION 2 de NC : mise à jour du Sanctuary « Snowfield of Sorrow » (communiqué)",
    de: "NCs AION 2: Update „Snowfield of Sorrow“ (Pressemitteilung)",
    es: "AION 2 de NC: actualización del Santuario «Snowfield of Sorrow» (nota de prensa)",
    ja: "NCのAION 2：新サンクチュアリ「Snowfield of Sorrow」アップデート（プレスリリース）",
    "pt-br": "AION 2 da NC: atualização do Santuário 'Snowfield of Sorrow' (comunicado)",
    ru: "AION 2 от NC: обновление Святилища «Snowfield of Sorrow» (пресс-релиз)",
    ko: "엔씨 AION 2: 신규 성역 '비탄의 설원' 업데이트 (보도자료)",
    "zh-hant": "NC 的 AION 2：新 Sanctuary「Snowfield of Sorrow」更新（新聞稿）",
  }, "https://about.ncsoft.com/news/article/A2_update_20260909"),
};

const invenSource: ContentSource = {
  id: "inven-snowfield-sorrow-25730-2026-09-08",
  kind: "third-party",
  publisher: "Inven Global",
  label: "'Aion 2' Adds Highest-Difficulty Sanctuary 'Snowfield of Sorrow'",
  url: "https://www.invenglobal.com/articles/25730/aion-2-adds-highest-difficulty-sanctuary-snowfield-of-sorrow",
  publishedAt: "2026-09-08",
  retrievedAt: "2026-09-10",
  verifiedAt: "2026-09-10",
  localizations: localizations({
    "zh-hans": "『Aion 2』新增最高难度 Sanctuary『Snowfield of Sorrow』",
    en: "'Aion 2' Adds Highest-Difficulty Sanctuary 'Snowfield of Sorrow'",
    fr: "« Aion 2 » ajoute le Sanctuary « Snowfield of Sorrow » de plus haute difficulté",
    de: "„Aion 2“ fügt Sanctuary „Snowfield of Sorrow“ mit höchster Schwierigkeit hinzu",
    es: "«Aion 2» añade el Santuario «Snowfield of Sorrow» de máxima dificultad",
    ja: "『Aion 2』に最高難度サンクチュアリ「Snowfield of Sorrow」追加",
    "pt-br": "'Aion 2' adiciona o Santuário 'Snowfield of Sorrow' de maior dificuldade",
    ru: "«Aion 2» добавляет Святилище «Snowfield of Sorrow» высшей сложности",
    ko: "'아이온2' 최고 난도 성역 '비탄의 설원' 추가",
    "zh-hant": "『Aion 2』新增最高難度 Sanctuary『Snowfield of Sorrow』",
  }, "https://www.invenglobal.com/articles/25730/aion-2-adds-highest-difficulty-sanctuary-snowfield-of-sorrow"),
};

const fHero: ContentHeroImage = {
  src: "https://blogfiles.ncsoft.net/news/af7330da-4ff6-4b58-aece-400e6061a3be.jpg",
  width: 1200, height: 630,
  credit: "NC Corporation",
  sourceUrl: "https://aion2.plaync.com/en-us/",
  rights: "linked-official-media",
  translations: {
    "zh-hans": { alt: "Aion 2 Snowfield of Sorrow 刷取指南横幅", caption: "新 Sanctuary「Snowfield of Sorrow」入场装分 5,800（Easy）/6,000（Normal）/6,200（Hard）；掉落 Deltras's Seal、[True] 武器能量与 Liberated White Night 武器/守护者，Hard 可获英雄级武器。" },
    en: { alt: "Aion 2 Snowfield of Sorrow farming guide banner", caption: "The new Sanctuary 'Snowfield of Sorrow' requires item level 5,800 (Easy) / 6,000 (Normal) / 6,200 (Hard) and drops Deltras's Seal, [True] weapon energy, and Liberated White Night weapons and guarders — with hero-grade weapons on Hard." },
    fr: { alt: "Bannière du guide de farm de Snowfield of Sorrow d'Aion 2", caption: "Le Sanctuary « Snowfield of Sorrow » exige un niveau d'équipement de 5 800 (Easy) / 6 000 (Normal) / 6 200 (Hard) et droppe Deltras's Seal, l'énergie d'armes [True] et les armes et gardes Liberated White Night — armes de rang héros en Hard." },
    de: { alt: "Banner zum Farming-Leitfaden von Snowfield of Sorrow in Aion 2", caption: "Das Sanctuary „Snowfield of Sorrow“ verlangt Itemlevel 5 800 (Easy) / 6 000 (Normal) / 6 200 (Hard) und droppt Deltras's Seal, [True]-Waffenenergie sowie Liberated-White-Night-Waffen und -Garder — Helden-Waffen auf Hard." },
    es: { alt: "Banner de la guía de farmeo de Snowfield of Sorrow de Aion 2", caption: "El Santuario «Snowfield of Sorrow» exige nivel de equipo 5 800 (Easy) / 6 000 (Normal) / 6 200 (Hard) y suelta Deltras's Seal, energía de armas [True] y armas y guardas Liberated White Night — armas de grado héroe en Hard." },
    ja: { alt: "Aion 2 Snowfield of Sorrow ファーミングガイドバナー", caption: "新サンクチュアリ「Snowfield of Sorrow」は装備スコア5,800（Easy）/6,000（Normal）/6,200（Hard）が入場条件。Deltras's Seal、[True]武器エネルギー、Liberated White Night武器・ガーダーがドロップし、Hardでは英雄級武器も。" },
    "pt-br": { alt: "Banner do guia de farm de Snowfield of Sorrow do Aion 2", caption: "O Santuário 'Snowfield of Sorrow' exige nível de item 5.800 (Easy) / 6.000 (Normal) / 6.200 (Hard) e dropa Deltras's Seal, energia de armas [True] e armas e guardas Liberated White Night — armas de grau herói no Hard." },
    ru: { alt: "Баннер гайда по фарму Snowfield of Sorrow в Aion 2", caption: "Святилище «Snowfield of Sorrow» требует уровень предметов 5 800 (Easy) / 6 000 (Normal) / 6 200 (Hard) и роняет Deltras's Seal, энергию оружия [True] и оружие с гардами Liberated White Night — геройское оружие на Hard." },
    ko: { alt: "Aion 2 비탄의 설원 파밍 가이드 배너", caption: "신규 성역 '비탄의 설원' 입장 장비 점수는 쉬움 5,800 / 보통 6,000 / 어려움 6,200이며, 델트라스의 인장·[진] 무기 기운·해방된 백야의 무기/가더가 드롭되고 어려움에서는 영웅 등급 무기까지 획득할 수 있습니다." },
    "zh-hant": { alt: "Aion 2 Snowfield of Sorrow 刷取指南橫幅", caption: "新 Sanctuary「Snowfield of Sorrow」入場裝分 5,800（Easy）/6,000（Normal）/6,200（Hard）；掉落 Deltras's Seal、[True] 武器能量與 Liberated White Night 武器/守護者，Hard 可獲英雄級武器。" },
  },
};

export const trendingSeptember10Article2: ContentEntry = {
  section: "guides",
  slug: "aion-2-snowfield-of-sorrow-farming-guide",
  schemaType: "Article",
  publishedAt: "2026-09-10",
  updatedAt: "2026-09-10",
  readingMinutes: 6,
  publication: publishedVerified,
  sources: [ncOfficialSource, invenSource],
  heroImage: fHero,
  related: [
    { kind: "content", section: "news", slug: "aion-2-snowfield-of-grief-sanctuary-raid" },
    { kind: "content", section: "guides", slug: "aion-2-seal-system-guide" },
    { kind: "content", section: "guides", slug: "aion-2-true-dragon-lord-gear-guide" },
    { kind: "content", section: "guides", slug: "aion-2-endgame-gear-guide" },
  ],
  translations: {
    en: articleCopy(guideLabels, "en", 6, {
      eyebrow: "FARMING GUIDE",
      title: "Snowfield of Sorrow Farming Guide: Entry Item Levels, Drops, and Hard-Difficulty Rewards",
      description: "How to farm the new Sanctuary 'Snowfield of Sorrow': item level 5,800/6,000/6,200 entry by difficulty, the Storm Legion Commander Deltras fight, and the drops from Deltras's Seal to [True] weapon energy and Liberated White Night gear",
      intro: "The new Snowfield of Sorrow Sanctuary is the highest PvE content bar in Aion 2 so far. This guide covers the entry item levels by difficulty, what the raid drops — from Deltras's Seal to [True] weapon energy and Liberated White Night gear — and how Hard difficulty rewards feed the crafted Tier 4 progression.",
      sourceNote: "Based on NCsoft's official September 9, 2026 press release and Inven Global's September 8, 2026 report (both retrieved September 10, 2026). Applies to the Korean service; the global version launches October 5 with a modified Season 1.",
      keywords: ["Aion 2 Snowfield of Sorrow farming", "Aion 2 item level 5800 6200 entry", "Aion 2 Deltras's Seal drop", "Aion 2 Liberated White Night weapons", "Aion 2 Hard hero grade weapons"],
      sections: [
        section("entry-requirements", "Entry Item Levels by Difficulty", ["The Sanctuary scales its entry requirement: item level 5,800 for Easy, 6,000 for Normal, and 6,200 for Hard. The difficulty also governs which rewards you can expect.", "For context, the 4,800+ bar on the upcoming Temple of Fire trial is lower — Snowfield of Sorrow is the current endgame ceiling, so plan your gearing path accordingly before your first run."]),
        section("the-boss", "Storm Legion Commander Deltras", ["The raid's final boss is 'Storm Legion Commander Deltras', a mechanics-driven fight that rewards immediate reactions over memorized rotations — the same design direction NCsoft emphasized when the raid was previewed.", "On Hard, the kill feeds the first-clear race: the first 20 forces receive the Void pet set and title, and the 1st-3rd clears are enshrined in the Hall of Fame."]),
        section("the-drops", "What the Raid Drops", ["Official rewards from the update: 'Deltras's Seal', 'Runaway Fear's Energy: [True] weapons', and 'Liberated White Night' weapons and guarders.", "Deltras's Seal is the showcase accessory that fills the new Seal equipment slot added in the same update, and Liberated White Night is the Tier 4 gear line that feeds the crafted [True] Genesis / Nemesis Dragon Lord equipment through material conversion."]),
        section("hard-rewards", "Hard Rewards: Hero-Grade Weapons", ["Hard difficulty adds hero-grade (Heroic) weapons to the reward table — the top crafted tier for the Korean service.", "That makes Hard the key repeatable source for endgame weapon progression: run it for Liberated White Night and [True] weapon energy, convert surplus into crafting materials, and complete your Tier 4 pieces."]),
        section("farming-strategy", "Farming Strategy Notes", ["1. Hit the item-level gates in order: 5,800 → 6,000 → 6,200; 2. Farm the highest difficulty your group can clear reliably — Normal is the safe middle ground for most groups; 3. Convert surplus Liberated White Night drops into [True] crafting materials instead of letting them sit; 4. Track the Seal slot upgrades — Deltras's Seal (Unique) upgrades to Heroic via Succession Crafting; 5. If you are racing for the Bronze/Silver Void pets, schedule attempts while the first-clear event is still open (first 20 Hard clears).", "For global players: the Korean service is running this content now. Expect the same raid structure in the global content pipeline after the October 5 launch of a modified Season 1."]),
      ],
    }),
    "zh-hans": articleCopy(guideLabels, "zh-hans", 6, {
      eyebrow: "刷取指南",
      title: "Snowfield of Sorrow 刷取指南：入场装分、掉落与 Hard 奖励",
      description: "如何刷新 Sanctuary「Snowfield of Sorrow」：按难度的 5,800/6,000/6,200 入场装分、风暴军团团长 Deltras 战，以及从 Deltras's Seal 到 [True] 武器能量与 Liberated White Night 装备的掉落",
      intro: "新的 Snowfield of Sorrow Sanctuary 是目前 Aion 2 中 PvE 内容门槛最高的副本。本指南说明各难度的入场装分、副本掉落——从 Deltras's Seal 到 [True] 武器能量与 Liberated White Night 装备——以及 Hard 奖励如何支撑制作 Tier 4 成长线。",
      sourceNote: "基于 NCsoft 官方 2026 年 9 月 9 日新闻稿与 Inven Global 2026 年 9 月 8 日报道（均于 2026-09-10 抓取）。适用于韩服；全球版 10 月 5 日以改良版 Season 1 上线。",
      keywords: ["Aion 2 Snowfield of Sorrow 刷取", "Aion 2 入场装分 5800 6200", "Aion 2 Deltras's Seal 掉落", "Aion 2 Liberated White Night 武器", "Aion 2 Hard 英雄级武器"],
      sections: [
        section("entry-requirements", "按难度的入场装分", ["副本按难度分级入场要求：Easy 装分 5,800、Normal 6,000、Hard 6,200。难度也决定你能期待什么奖励。", "参照：即将到来的 Temple of Fire 试炼门槛是 4,800+——比它更高。Snowfield of Sorrow 是当前终局天花板，首次进入前请先规划好装备路线。"]),
        section("the-boss", "风暴军团团长 Deltras", ["副本最终 Boss 是「폭풍의 레기온 단장 델트라스」（风暴军团团长 Deltras）——一场奖励即时反应而非背板的机制战，与预告时 NCsoft 强调的设计方向一致。", "Hard 击杀进入首杀竞速：前 20 支队伍获得 Void 宠物套装与称号，1-3 名刻入名人堂。"]),
        section("the-drops", "副本掉落", ["官方公布的本轮奖励：「Deltras's Seal」「폭주한 공포의 기운: [진] 무기」（狂暴恐惧之气: [True] 武器）与「Liberated White Night」武器与守护者。", "Deltras's Seal 是填充同次更新新增「印章」装备栏的代表饰品；Liberated White Night 是 Tier 4 装备线，经材料转换为 [True] 创世/灭绝龙神制作材料。"]),
        section("hard-rewards", "Hard 奖励：英雄级武器", ["Hard 难度在奖励表中加入英雄级（Heroic）武器——韩服当前最高制作阶。", "这让 Hard 成为终局武器成长的关键可重复来源：刷 Liberated White Night 与 [True] 武器能量，把多余部分转换为制作材料，补齐 Tier 4 部件。"]),
        section("farming-strategy", "刷取策略要点", ["1. 按顺序突破装分门槛：5,800 → 6,000 → 6,200；2. 刷你们队伍能稳定通关的最高难度——Normal 是多数队伍的稳妥中间档；3. 多余的 Liberated White Night 掉落转换为 [True] 制作材料，别让它闲置；4. 跟进印章栏升级——Deltras's Seal（Unique）可经传承制作升 Heroic；5. 若在争青铜/白银 Void，请在首杀活动（前 20 个 Hard 通关）窗口内尽早安排。", "对全球玩家：韩服现在正在运行该内容。全球版 10 月 5 日以改良版 Season 1 上线后，同一副本结构将进入全球内容管线。"]),
      ],
    }),
    fr: articleCopy(guideLabels, "fr", 6, {
      eyebrow: "GUIDE DE FARM",
      title: "Guide de farm de Snowfield of Sorrow : niveaux d'entrée, drops et récompenses Hard",
      description: "Comment farmer le Sanctuary « Snowfield of Sorrow » : entrée à 5 800/6 000/6 200 selon la difficulté, le combat contre le Commandant Deltras, et les drops de Deltras's Seal aux armes [True] et à l'équipement Liberated White Night",
      intro: "Le Sanctuary Snowfield of Sorrow est le contenu PvE le plus exigeant d'Aion 2 à ce jour. Ce guide couvre les niveaux d'entrée, les drops — de Deltras's Seal aux armes [True] et au Liberated White Night — et comment le Hard alimente la progression Tier 4.",
      sourceNote: "Basé sur le communiqué officiel de NCsoft du 9 septembre 2026 et le rapport d'Inven Global du 8 septembre 2026 (récupérés le 10 septembre 2026).",
      keywords: ["Aion 2 farm Snowfield of Sorrow", "Aion 2 niveau d'équipement 5800 6200", "Aion 2 drop Deltras's Seal", "Aion 2 armes Liberated White Night", "Aion 2 armes héros Hard"],
      sections: [
        section("entry-requirements", "Niveaux d'entrée par difficulté", "Entrée : 5 800 (Easy), 6 000 (Normal), 6 200 (Hard). À titre de référence, le prochain Trial « Temple of Fire » demande 4 800+ — Snowfield of Sorrow est le plafond d'endgame actuel."),
        section("the-boss", "Le Commandant de légion Deltras", "Boss final : « Commandant de légion de la Tempête Deltras », un combat de mécaniques récompensant les réactions immédiates. En Hard, le kill alimente la course au premier clear (20 forces, pets Void) et le Hall of Fame."),
        section("the-drops", "Les drops", "Récompenses officielles : « Deltras's Seal », « Énergie de la peur déchaînée : armes [True] », armes et gardes « Liberated White Night ». Le Sceau remplit le nouvel emplacement Sceau ; Liberated White Night alimente l'équipement Tier 4 [True] par conversion."),
        section("hard-rewards", "Récompenses Hard : armes héros", "Le Hard ajoute des armes de grade héroïque — le plus haut rang fabriqué. C'est la source répétable clé de la progression d'armes d'endgame."),
        section("farming-strategy", "Notes de stratégie", "1. Franchissez les paliers (5 800 → 6 000 → 6 200) ; 2. Farmez la difficulté la plus haute gérable (Normal en compromis sûr) ; 3. Convertissez l'excédent en matériaux [True] ; 4. Suivez l'emplacement Sceau (Unique → Heroic) ; 5. La course est ouverte (20 premiers Hard). Pour le global : même structure dans le pipeline après le 5 octobre."),
      ],
    }),
    de: articleCopy(guideLabels, "de", 6, {
      eyebrow: "FARMING-LEITFADEN",
      title: "Farming-Leitfaden für Snowfield of Sorrow: Einstiegs-Itemlevel, Drops und Hard-Belohnungen",
      description: "So farmst du das Sanctuary „Snowfield of Sorrow“: Itemlevel 5 800/6 000/6 200 nach Schwierigkeit, der Kampf gegen Legion Commander Deltras und die Drops von Deltras's Seal bis zu [True]-Waffenenergie und Liberated-White-Night-Ausrüstung",
      intro: "Das Sanctuary Snowfield of Sorrow ist die höchste PvE-Hürde von Aion 2. Dieser Leitfaden deckt die Einstiegs-Itemlevel, die Drops — von Deltras's Seal bis zu [True]-Waffenenergie und Liberated White Night — und die Hard-Belohnungen ab.",
      sourceNote: "Basierend auf der offiziellen NCsoft-Pressemitteilung vom 9. September 2026 und dem Inven-Global-Bericht vom 8. September 2026 (abgerufen am 10. September 2026).",
      keywords: ["Aion 2 Farming Snowfield of Sorrow", "Aion 2 Itemlevel 5800 6200", "Aion 2 Deltras's Seal Drop", "Aion 2 Liberated White Night Waffen", "Aion 2 Helden-Waffen Hard"],
      sections: [
        section("entry-requirements", "Einstiegs-Itemlevel nach Schwierigkeit", "Eintritt: 5 800 (Easy), 6 000 (Normal), 6 200 (Hard). Zum Vergleich: Das kommende Trial „Temple of Fire“ verlangt 4 800+ — Snowfield of Sorrow ist die aktuelle Endgame-Decke."),
        section("the-boss", "Legion Commander Deltras", "Endboss: „Sturmlegions-Kommandant Deltras“ — ein Mechanik-Kampf, der sofortige Reaktionen belohnt. Auf Hard speist der Kill das Erster-Clear-Rennen (20 Forces, Void-Begleiter) und die Hall of Fame."),
        section("the-drops", "Die Drops", "Offizielle Belohnungen: „Deltras's Seal“, „Energie der entfesselten Angst: [True]-Waffen“, Liberated-White-Night-Waffen und -Garder. Das Seal füllt den neuen Seal-Platz; Liberated White Night speist Tier-4-[True]-Ausrüstung."),
        section("hard-rewards", "Hard-Belohnungen: Helden-Waffen", "Hard fügt Waffen von Helden-Rang hinzu — die höchste gefertigte Stufe. Die wichtigste wiederholbare Quelle für die Endgame-Waffenprogression."),
        section("farming-strategy", "Strategie-Notizen", "1. Stufen erklimmen (5 800 → 6 000 → 6 200); 2. Höchste machbare Stufe farmen (Normal als sicherer Mittelweg); 3. Überschuss in [True]-Materialien umwandeln; 4. Seal-Platz upgraden (Unique → Heroic); 5. Rennen läuft (erste 20 Hard). Für Global: gleiche Struktur nach dem 5. Oktober."),
      ],
    }),
    es: articleCopy(guideLabels, "es", 6, {
      eyebrow: "GUÍA DE FARM",
      title: "Guía de farmeo de Snowfield of Sorrow: niveles de entrada, drops y recompensas Hard",
      description: "Cómo farmear el Santuario «Snowfield of Sorrow»: entrada a 5 800/6 000/6 200 según dificultad, la pelea contra el Comandante Deltras y los drops del Deltras's Seal a las armas [True] y el equipo Liberated White Night",
      intro: "El Santuario Snowfield of Sorrow es el contenido PvE más exigente de Aion 2 hasta ahora. Esta guía cubre los niveles de entrada, los drops — del Deltras's Seal a las armas [True] y Liberated White Night — y cómo el Hard alimenta la progresión Tier 4.",
      sourceNote: "Basado en la nota de prensa oficial de NCsoft del 9 de septiembre de 2026 y el informe de Inven Global del 8 de septiembre de 2026 (recuperados el 10 de septiembre de 2026).",
      keywords: ["Aion 2 farm Snowfield of Sorrow", "Aion 2 nivel de equipo 5800 6200", "Aion 2 drop Deltras's Seal", "Aion 2 armas Liberated White Night", "Aion 2 armas héroe Hard"],
      sections: [
        section("entry-requirements", "Niveles de entrada por dificultad", "Entrada: 5 800 (Easy), 6 000 (Normal), 6 200 (Hard). Como referencia, el próximo Trial «Temple of Fire» pide 4 800+ — Snowfield of Sorrow es el techo actual del endgame."),
        section("the-boss", "Comandante de legión Deltras", "Jefe final: «Comandante de la Legión de la Tormenta Deltras», una pelea de mecánicas que premia reacciones inmediatas. En Hard, el kill alimenta la carrera del primer clear (20 fuerzas, mascotas Void) y el Salón de la Fama."),
        section("the-drops", "Los drops", "Recompensas oficiales: «Deltras's Seal», «Energía del miedo desatado: armas [True]», armas y guardas «Liberated White Night». El Sello llena la nueva ranura de Sello; Liberated White Night alimenta el equipo Tier 4 [True] por conversión."),
        section("hard-rewards", "Recompensas Hard: armas héroe", "El Hard añade armas de grado héroe — el rango fabricado más alto. Es la fuente repetible clave de la progresión de armas del endgame."),
        section("farming-strategy", "Notas de estrategia", "1. Sube los escalones (5 800 → 6 000 → 6 200); 2. Farmea la dificultad más alta viable (Normal como punto medio seguro); 3. Convierte el excedente en materiales [True]; 4. Sigue la ranura de Sello (Unique → Heroic); 5. La carrera sigue abierta (primeros 20 Hard). Para el global: misma estructura tras el 5 de octubre."),
      ],
    }),
    ja: articleCopy(guideLabels, "ja", 6, {
      eyebrow: "ファーミングガイド",
      title: "Snowfield of Sorrow ファーミングガイド：入場条件、ドロップ、Hard報酬",
      description: "新サンクチュアリ「Snowfield of Sorrow」のファーミング方法：難易度別5,800/6,000/6,200の入場条件、嵐のレギオン団長Deltras戦、Deltras's Sealから[True]武器エネルギー・Liberated White Night装備までのドロップ",
      intro: "新サンクチュアリ「Snowfield of Sorrow」は現時点でAion 2のPvE最高難度です。本ガイドは難易度別の入場条件、ドロップ（Deltras's Sealから[True]武器エネルギー、Liberated White Night装備まで）、そしてHard報酬が制作Tier 4成長をどう支えるかを解説します。",
      sourceNote: "NC公式2026年9月9日付プレスリリースとInven Global 2026年9月8日付報道（いずれも2026-09-10取得）に基づきます。",
      keywords: ["Aion 2 Snowfield of Sorrow ファーミング", "Aion 2 入場条件 5800 6200", "Aion 2 Deltras's Seal ドロップ", "Aion 2 Liberated White Night 武器", "Aion 2 Hard 英雄級武器"],
      sections: [
        section("entry-requirements", "難易度別の入場条件", "入場条件は難易度別：Easy 5,800、Normal 6,000、Hard 6,200。参考までに、次の試練「Temple of Fire」は4,800+——Snowfield of Sorrowは現行エンドゲームの上限です。"),
        section("the-boss", "嵐のレギオン団長 Deltras", "最終ボスは「嵐のレギオン団長デルトラス」——即時反応を重視したメカニクス戦で、プレビュー時にNCが強調した設計と一致します。Hardクリアは初クリアレース（先着20部隊、Voidペット）と栄誉の殿堂に食い込みます。"),
        section("the-drops", "ドロップ内容", "公式報酬：「Deltras's Seal」「暴走した恐怖の気配: [진]武器」「Liberated White Night」武器・ガーダー。シールは同時実装の新装備枠「シール」を満たし、Liberated White NightはTier 4 [True]装備の素材変換に使われます。"),
        section("hard-rewards", "Hard報酬：英雄級武器", "Hardは英雄級（Heroic）武器を報酬テーブルに追加——韓国サービス最高の制作階級。エンドゲーム武器成長の要となる反復可能な供給源です。"),
        section("farming-strategy", "ファーミング戦略", "1. 段階的に突破（5,800→6,000→6,200）; 2. 安定クリア可能な最高難度を周回（Normalが安全な中間点）; 3. 余剰のLiberated White Nightを[True]素材に変換; 4. シール枠の昇級（Unique→Heroic）を追う; 5. レース（先着20Hard）が開いているうちに挑戦を。グローバルは10月5日以降、同じ構造で提供されます。"),
      ],
    }),
    "pt-br": articleCopy(guideLabels, "pt-br", 6, {
      eyebrow: "GUIA DE FARM",
      title: "Guia de farm de Snowfield of Sorrow: níveis de entrada, drops e recompensas do Hard",
      description: "Como farmar o Santuário 'Snowfield of Sorrow': entrada a 5.800/6.000/6.200 por dificuldade, a luta contra o Comandante Deltras e os drops do Deltras's Seal às armas [True] e ao equipamento Liberated White Night",
      intro: "O Santuário Snowfield of Sorrow é o conteúdo PvE mais exigente do Aion 2 até agora. Este guia cobre os níveis de entrada, os drops — do Deltras's Seal às armas [True] e Liberated White Night — e como o Hard alimenta a progressão Tier 4.",
      sourceNote: "Baseado no comunicado oficial da NCsoft de 9 de setembro de 2026 e no relatório da Inven Global de 8 de setembro de 2026 (recuperados em 10 de setembro de 2026).",
      keywords: ["Aion 2 farm Snowfield of Sorrow", "Aion 2 nível de item 5800 6200", "Aion 2 drop Deltras's Seal", "Aion 2 armas Liberated White Night", "Aion 2 armas herói Hard"],
      sections: [
        section("entry-requirements", "Níveis de entrada por dificuldade", "Entrada: 5.800 (Easy), 6.000 (Normal), 6.200 (Hard). Para referência, o próximo Trial 'Temple of Fire' pede 4.800+ — Snowfield of Sorrow é o teto atual do endgame."),
        section("the-boss", "Comandante de legião Deltras", "Chefe final: 'Comandante da Legião da Tempestade Deltras', uma luta de mecânicas que premia reações imediatas. No Hard, o kill alimenta a corrida do primeiro clear (20 forças, mascotes Void) e o Hall da Fama."),
        section("the-drops", "Os drops", "Recompensas oficiais: 'Deltras's Seal', 'Energia do medo descontrolado: armas [True]', armas e guardas 'Liberated White Night'. O Selo preenche o novo slot de Selo; Liberated White Night alimenta o equipamento Tier 4 [True] por conversão."),
        section("hard-rewards", "Recompensas do Hard: armas herói", "O Hard adiciona armas de grau herói — o maior grau fabricado. É a fonte repetível-chave da progressão de armas do endgame."),
        section("farming-strategy", "Notas de estratégia", "1. Suba os degraus (5.800 → 6.000 → 6.200); 2. Farme a dificuldade mais alta viável (Normal como meio-termo seguro); 3. Converta o excedente em materiais [True]; 4. Acompanhe o slot de Selo (Unique → Heroic); 5. A corrida segue aberta (primeiros 20 Hard). Para o global: mesma estrutura após 5 de outubro."),
      ],
    }),
    ru: articleCopy(guideLabels, "ru", 6, {
      eyebrow: "ГАЙД ПО ФАРМУ",
      title: "Гайд по фарму Snowfield of Sorrow: уровни входа, дропы и награды Hard",
      description: "Как фармить Святилище «Snowfield of Sorrow»: вход 5 800/6 000/6 200 по сложности, бой с Легион-командиром Deltras и дропы от Deltras's Seal до энергии оружия [True] и экипировки Liberated White Night",
      intro: "Святилище Snowfield of Sorrow — самая высокая PvE-планка Aion 2 на данный момент. Гайд охватывает уровни входа, дропы — от Deltras's Seal до энергии оружия [True] и Liberated White Night — и то, как Hard питает крафтовую прогрессию Tier 4.",
      sourceNote: "На основе официального пресс-релиза NCsoft от 9 сентября 2026 г. и отчёта Inven Global от 8 сентября 2026 г. (получены 10 сентября 2026 г.).",
      keywords: ["Aion 2 фарм Snowfield of Sorrow", "Aion 2 уровень предметов 5800 6200", "Aion 2 дроп Deltras's Seal", "Aion 2 оружие Liberated White Night", "Aion 2 геройское оружие Hard"],
      sections: [
        section("entry-requirements", "Уровни входа по сложности", "Вход: 5 800 (Easy), 6 000 (Normal), 6 200 (Hard). Для справки, следующее Испытание «Temple of Fire» требует 4 800+ — Snowfield of Sorrow сейчас потолок эндгейма."),
        section("the-boss", "Легион-командир Deltras", "Финальный босс: «Штормовой Легион-командир Deltras» — механик-бой, поощряющий мгновенные реакции. На Hard клир кормит гонку первого клира (20 сил, питомцы Void) и Зал славы."),
        section("the-drops", "Дропы", "Официальные награды: «Deltras's Seal», «Энергия безудержного страха: оружие [True]», оружие и гарды «Liberated White Night». Печать заполняет новый слот Печати; Liberated White Night питает экипировку Tier 4 [True] конвертацией."),
        section("hard-rewards", "Награды Hard: геройское оружие", "Hard добавляет оружие геройского ранга — высочайший крафтовый ранг. Ключевой повторяемый источник прогрессии оружия эндгейма."),
        section("farming-strategy", "Заметки по фарму", "1. Проходите ступени (5 800 → 6 000 → 6 200); 2. Фармите максимальную проходимую сложность (Normal — безопасная середина); 3. Конвертируйте излишки в материалы [True]; 4. Прокачивайте слот Печати (Unique → Heroic); 5. Гонка открыта (первые 20 на Hard). Для глобала: та же структура после 5 октября."),
      ],
    }),
    ko: articleCopy(guideLabels, "ko", 6, {
      eyebrow: "파밍 가이드",
      title: "비탄의 설원 파밍 가이드: 입장 조건, 드랍, 어려움 보상",
      description: "신규 성역 '비탄의 설원' 파밍 방법: 난이도별 5,800/6,000/6,200 입장 장비 점수, 폭풍의 레기온 단장 델트라스전, 델트라스의 인장부터 [진] 무기 기운·해방된 백야 장비까지의 드랍 정리",
      intro: "신규 성역 '비탄의 설원'은 현재 Aion 2의 PvE 최고 난이도 콘텐츠입니다. 이 가이드는 난이도별 입장 장비 점수, 레이드 드랍——델트라스의 인장부터 [진] 무기 기운, 해방된 백야 장비까지——그리고 어려움 보상이 제작 Tier 4 성장을 어떻게 받쳐주는지 설명합니다.",
      sourceNote: "NC 공식 2026년 9월 9일자 보도자료와 Inven Global 2026년 9월 8일자 보도(모두 2026-09-10 확인)를 기반으로 했습니다.",
      keywords: ["아이온2 비탄의 설원 파밍", "아이온2 입장 장비점수 5800 6200", "아이온2 델트라스의 인장 드랍", "아이온2 해방된 백야 무기", "아이온2 어려움 영웅 등급 무기"],
      sections: [
        section("entry-requirements", "난이도별 입장 장비 점수", "입장 요건은 난이도별로 다릅니다: 쉬움 5,800 / 보통 6,000 / 어려움 6,200. 참고로 다음 시련 '불의 사원'은 4,800+——비탄의 설원이 현재 엔드게임의 최상위 문턱입니다."),
        section("the-boss", "폭풍의 레기온 단장 델트라스", "레이드 최종 보스는 '폭풍의 레기온 단장 델트라스'입니다——암기식 로테이션보다 즉각적인 반응을 요구하는 메커닉 중심 전투로, 프리뷰 때 NC가 강조한 설계 방향과 일치합니다.", "어려움 격파는 첫 클리어 레이스로 이어집니다: 선착 20개 포스에 보이드 펫 세트와 칭호, 1~3위는 명예의 전당에 새겨집니다."),
        section("the-drops", "레이드 드랍", "업데이트 공식 보상: '델트라스의 인장', '폭주한 공포의 기운: [진] 무기', '해방된 백야의 무기·가더'.", "델트라스의 인장은 같은 업데이트에서 추가된 신규 장비 칸 '인장'을 채우는 대표 액세서리이고, 해방된 백야는 재료 변환을 통해 [True] 창세/멸절 드래곤 로드 제작을 받쳐주는 Tier 4 장비 라인입니다."),
        section("hard-rewards", "어려움 보상: 영웅 등급 무기", "어려움 난이도는 영웅(Heroic) 등급 무기를 보상 테이블에 추가합니다——한국 서버 최고 제작 등급입니다.", "즉 어려움은 엔드게임 무기 성장의 핵심 반복 수급처: 해방된 백야와 [진] 무기 기운을 모으고, 잉여분을 제작 재료로 변환해 Tier 4 부위를 완성합니다."),
        section("farming-strategy", "파밍 전략 요점", "1. 장비 점수 문턱을 순서대로 돌파(5,800→6,000→6,200); 2. 공대가 안정적으로 클리어 가능한 최고 난이도를 반복(보통이 안전한 중간 지점); 3. 잉여 해방된 백야 드랍은 [True] 제작 재료로 변환해 방치하지 말 것; 4. 인장 칸 성장을 챙길 것(델트라스의 인장 Unique→계승 제작으로 Heroic); 5. 구릿빛/은빛 보이드를 노린다면 첫 클리어 이벤트(선착 20 Hard)가 끝나기 전에 도전을 서두르세요.", "글로벌 플레이어에게: 한국 서버가 현재 이 콘텐츠를 운영 중입니다. 10월 5일 수정판 시즌 1 출시 이후 같은 구조가 글로벌 콘텐츠 파이프라인에 들어올 예정입니다."),
      ],
    }),
    "zh-hant": articleCopy(guideLabels, "zh-hant", 6, {
      eyebrow: "刷取指南",
      title: "Snowfield of Sorrow 刷取指南：入場裝分、掉落與 Hard 獎勵",
      description: "如何刷新 Sanctuary「Snowfield of Sorrow」：按難度的 5,800/6,000/6,200 入場裝分、風暴軍團團長 Deltras 戰，以及從 Deltras's Seal 到 [True] 武器能量與 Liberated White Night 裝備的掉落",
      intro: "新的 Snowfield of Sorrow Sanctuary 是目前 Aion 2 中 PvE 內容門檻最高的副本。本指南說明各難度的入場裝分、副本掉落——從 Deltras's Seal 到 [True] 武器能量與 Liberated White Night 裝備——以及 Hard 獎勵如何支撐製作 Tier 4 成長線。",
      sourceNote: "基於 NCsoft 官方 2026 年 9 月 9 日新聞稿與 Inven Global 2026 年 9 月 8 日報導（均於 2026-09-10 抓取）。適用於韓服；全球版 10 月 5 日以改良版 Season 1 上線。",
      keywords: ["Aion 2 Snowfield of Sorrow 刷取", "Aion 2 入場裝分 5800 6200", "Aion 2 Deltras's Seal 掉落", "Aion 2 Liberated White Night 武器", "Aion 2 Hard 英雄級武器"],
      sections: [
        section("entry-requirements", "按難度的入場裝分", ["副本按難度分級入場要求：Easy 裝分 5,800、Normal 6,000、Hard 6,200。難度也決定你能期待什麼獎勵。", "參照：即將到來的 Temple of Fire 試煉門檻是 4,800+——比它更高。Snowfield of Sorrow 是當前終局天花板，首次進入前請先規劃好裝備路線。"]),
        section("the-boss", "風暴軍團團長 Deltras", ["副本最終 Boss 是「폭풍의 레기온 단장 델트라스」（風暴軍團團長 Deltras）——一場獎勵即時反應而非背板的機制戰，與預告時 NCsoft 強調的設計方向一致。", "Hard 擊殺進入首殺競速：前 20 支隊伍獲得 Void 寵物套裝與稱號，1-3 名刻入名人堂。"]),
        section("the-drops", "副本掉落", ["官方公布的本輪獎勵：「Deltras's Seal」「폭주한 공포의 기운: [진] 무기」（狂暴恐懼之氣: [True] 武器）與「Liberated White Night」武器與守護者。", "Deltras's Seal 是填充同次更新新增「印章」裝備欄的代表飾品；Liberated White Night 是 Tier 4 裝備線，經材料轉換為 [True] 創世/滅絕龍神製作材料。"]),
        section("hard-rewards", "Hard 獎勵：英雄級武器", ["Hard 難度在獎勵表中加入英雄級（Heroic）武器——韓服當前最高製作階。", "這讓 Hard 成為終局武器成長的關鍵可重複來源：刷 Liberated White Night 與 [True] 武器能量，把多餘部分轉換為製作材料，補齊 Tier 4 部件。"]),
        section("farming-strategy", "刷取策略要點", ["1. 按順序突破裝分門檻：5,800 → 6,000 → 6,200；2. 刷你們隊伍能穩定通關的最高難度——Normal 是多數隊伍的穩妥中間檔；3. 多餘的 Liberated White Night 掉落轉換為 [True] 製作材料，別讓它閒置；4. 跟進印章欄升級——Deltras's Seal（Unique）可經傳承製作升 Heroic；5. 若在爭青銅/白銀 Void，請在首殺活動（前 20 個 Hard 通關）窗口內盡早安排。", "對全球玩家：韓服現在正在運行該內容。全球版 10 月 5 日以改良版 Season 1 上線後，同一副本結構將進入全球內容管線。"]),
      ],
    }),
  },
};
