import { articleCopy, localizations, guideLabels, publishedVerified, section } from "./trending-september-14-shared";
import type { ContentEntry, ContentHeroImage, ContentSource } from "./content-registry";

/* ARTICLE 4 — Aion 2 item level progression roadmap */

const ilvlSource: ContentSource = {
  id: "aion2-official-abyss-schedule-2026-07-31",
  kind: "official",
  publisher: "NC Corporation",
  label: "AION 2 Abyss Schedules and Equipment Progression",
  url: "https://tw.ncsoft.com/aion2/board/update/view?articleId=6a31a438754f8e55c506f818",
  publishedAt: "2026-07-31",
  retrievedAt: "2026-09-14",
  verifiedAt: "2026-09-14",
  localizations: localizations({
    "zh-hans": "AION 2 深渊时间表与装备进阶",
    en: "AION 2 Abyss Schedules and Equipment Progression",
    fr: "AION 2 : planification de l'Abysse et progression des équipements",
    de: "AION 2 Abyss-Zeiten und Ausrüstungs-Progression",
    es: "AION 2: horarios del Abismo y progresión de equipo",
    ja: "AION 2 深淵スケジュールと装備進行",
    "pt-br": "AION 2: horários do Abismo e progressão de equipamento",
    ru: "AION 2: расписание Бездны和 прогресс снаряжения",
    ko: "AION2 어비스 시간표 및 장비 진행",
    "zh-hant": "AION 2 深淵時間表與裝備進階",
  }, "https://tw.ncsoft.com/aion2/board/update/view?articleId=6a31a438754f8e55c506f818"),
};

const ilvlHero: ContentHeroImage = {
  src: "https://blogfiles.ncsoft.net/news/af7330da-4ff6-4b58-aece-400e6061a3be.jpg",
  width: 1200, height: 630,
  credit: "NC Corporation",
  sourceUrl: "https://aion2.plaync.com/en-us/",
  rights: "linked-official-media",
  translations: {
    "zh-hans": { alt: "Aion 2 装备等级进阶路线图横幅", caption: "Aion 2 的装备等级系统从 4,000 到 7,000+——从新手装备到终局武器，每个等级段对应特定的内容和系统。" },
    en: { alt: "Aion 2 item level progression roadmap banner", caption: "Aion 2's item level system spans from 4,000 to 7,000+ — from starter gear to end-game weapons, each range corresponds to specific content and systems." },
    fr: { alt: "Bannière de la roadmap des niveaux d'équipement d'Aion 2", caption: "Le système de niveaux d'équipement d'Aion 2 va de 4 000 à 7 000+ — de l'équipement de départ aux armes de fin de partie." },
    de: { alt: "Banner zur Ausrüstungs-Level-Roadmap von Aion 2", caption: "Das Ausrüstungs-Levelsystem von Aion 2 reicht von 4 000 bis 7 000+ — von Einsteiger-Ausrüstung bis Endgame-Waffen." },
    es: { alt: "Banner de la hoja de ruta de niveles de equipo de Aion 2", caption: "El sistema de niveles de equipo de Aion 2 va de 4 000 a 7 000+ — desde el equipo inicial hasta las armas de final de partida." },
    ja: { alt: "Aion 2 装備レベル進行ロードマップバナー", caption: "Aion 2の装備レベルシステムは4,000から7,000+——初心者装備から終局武器まで、各範囲が特定のコンテンツとシステムに対応します。" },
    "pt-br": { alt: "Banner da roadmap de níveis de equipamento do Aion 2", caption: "O sistema de níveis de equipamento do Aion 2 vai de 4 000 a 7 000+ — desde o equipamento inicial até as armas de fim de jogo." },
    ru: { alt: "Баннер дорожной карты уровней снаряжения Aion 2", caption: "Система уровней снаряжения Aion 2 охватывает от 4 000 до 7 000+ — от стартового снаряжения до эндгейм-оружия." },
    ko: { alt: "Aion 2 장비 레벨 진행 로드맵 배너", caption: "Aion 2의 장비 레벨 시스템은 4,000에서 7,000+까지——입문 장비에서 후반 무기까지, 각 구간이 특정 콘텐츠와 시스템에 대응합니다." },
    "zh-hant": { alt: "Aion 2 裝備等級進階路線圖橫幅", caption: "Aion 2 的裝備等級系統從 4,000 到 7,000+——從新手裝備到終局武器，每個等級段對應特定的內容和系統。" },
  },
};

export const trendingSeptember14Article4: ContentEntry = {
  section: "guides",
  slug: "aion-2-item-level-progression-roadmap",
  schemaType: "Article",
  publishedAt: "2026-09-14",
  updatedAt: "2026-09-14",
  readingMinutes: 7,
  publication: publishedVerified,
  sources: [ilvlSource],
  heroImage: ilvlHero,
  related: [
    { kind: "content", section: "guides", slug: "aion-2-snowfield-of-sorrow-farming-guide" },
    { kind: "content", section: "guides", slug: "equipment-tuning" },
    { kind: "content", section: "guides", slug: "aion-2-enhancement-system-strategy-guide" },
    { kind: "content", section: "guides", slug: "aion-2-crafting-weapons-standard-progression" },
  ],
  translations: {
    en: articleCopy(guideLabels, "en", 7, {
      eyebrow: "PROGRESSION",
      title: "Aion 2 Item Level Progression Roadmap: From Starter Gear to End-Game Weapons",
      description: "A complete guide to Aion 2's item level system — how item levels work, what each range unlocks, and which content is required to reach each tier from 4,000 to 7,000+",
      intro: "Understanding Aion 2's item level system is essential for planning your progression. Item levels are not just cosmetic labels — they determine your access to content, your combat effectiveness, and your ability to compete in end-game systems like Snowfield of Sorrow and Abyss dungeons.",
      sourceNote: "Based on NCsoft's official Abyss schedule documentation and the Korean service item level system as of September 2026. Global values may be adjusted for the modified Season 1.",
      keywords: ["Aion 2 item level progression", "Aion 2 gear level guide", "Aion 2 equipment progression", "Aion 2 end-game item level", "Aion 2 Snowfield of Sorrow item level"],
      sections: [
        section("item-level-basics", "How Item Levels Work in Aion 2", ["Every piece of equipment in Aion 2 has an item level (iLvl) that determines its power. iLvl is the primary stat that gates content — you need minimum iLvl to enter dungeons, raids, and PvP instances. iLvl scales with character level and the source of the equipment.", "Item levels range from approximately 4,000 (starter gear) to 7,000+ (end-game raid gear). Each iLvl increase represents roughly 1-2% more power, but the content gate is the real restriction."]),
        section("early-game", "4,000–5,000: Early Game Progression", ["Starter equipment (4,000–4,500) comes from early quests and training areas. By 4,500 you can tackle basic dungeons and expedition content. 5,000 iLvl gear comes from mid-tier dungeons and Transcendence content.", "The early game is designed for fast progression — most players should reach 5,000 iLvl within the first few hours. Focus on completing main quests and clearing basic dungeons to build up your equipment."]),
        section("mid-game", "5,000–6,000: Mid-Game Push", ["5,000–5,500 iLvl is where most players spend the majority of their early progression time. Transcendence dungeons, Expedition content, and crafting provide the bulk of equipment in this range. Enhancement (covered in a separate guide) adds + bonuses on top of base iLvl.", "5,500–6,000 iLvl requires more dedicated play — organized dungeons, crafting with higher-tier materials, and consistent enhancement. The modified Season 1 for global will extend this range with longer progression curves."]),
        section("end-game", "6,000–7,000+: End-Game Content", ["6,000–6,200 iLvl is the threshold for Snowfield of Sorrow (Easy: 5,800, Normal: 6,000, Hard: 6,200) and high-tier Abyss content. Reaching 6,000 requires consistent dungeon clears, enhancement, and possibly crafting with top-tier materials.", "7,000+ iLvl is the theoretical end-game ceiling for raid gear. Not all players will reach this range — it requires top-tier dungeon participation, consistent enhancement at high levels, and access to the rarest crafting materials."]),
        section("progression-tips", "Progression Tips for Global Players", ["Prioritize enhancement early. A 5,000 iLvl weapon enhanced to +10 is more powerful than a 5,500 iLvl weapon at +0. Enhancement is the most cost-effective way to increase your combat power in the mid-game.", "Don't neglect crafting. Standard-route weapons are competitive with dungeon drops and provide a viable alternative for players who cannot consistently clear high-tier content.", "Track your iLvl gap to the next content gate. If you're close (within 100–200 iLvl), prioritize that content. If you're far, focus on the current accessible content and enhancement."]),
      ],
    }),
    "zh-hans": articleCopy(guideLabels, "zh-hans", 7, {
      eyebrow: "进阶",
      title: "Aion 2 装备等级进阶路线图：从新手装备到终局武器",
      description: "Aion 2 装备等级系统全面攻略——装备等级如何运作，每个范围解锁什么，以及从 4,000 到 7,000+ 每个等级段需要哪些内容",
      intro: "理解 Aion 2 的装备等级系统对规划进阶至关重要。装备等级不是纯粹的标签——它们决定你的内容访问权限、战斗效果和参与终局系统的能力。",
      sourceNote: "基于 NCsoft 官方深渊时间表文档与 2026 年 9 月韩服装备等级系统。全球数值可能因改良版 Season 1 而调整。",
      keywords: ["Aion 2 装备等级进阶", "Aion 2 装备等级攻略", "Aion 2 装备进阶", "Aion 2 终局装备等级", "Aion 2 Snowfield of Sorrow 装备等级"],
      sections: [
        section("item-level-basics", "Aion 2 装备等级如何运作", ["Aion 2 中的每件装备都有一个装备等级（iLvl），决定其强度。iLvl 是内容关卡的主要属性——你需要最低 iLvl 才能进入副本、副本和 PvP 实例。iLvl 随角色等级和装备来源缩放。", "装备等级范围约为 4,000（新手装备）到 7,000+（终局副本装备）。每 100 iLvl 提升约等于 1-2% 的额外强度，但内容关卡才是真正的限制。"]),
        section("early-game", "4,000–5,000：前期进阶", ["新手装备（4,000–4,500）来自早期任务和训练区。达到 4,500 你可以挑战基础副本和远征内容。5,000 iLvl 装备来自中端副本和超越内容。", "前期设计为快速进阶——大多数玩家应在数小时内达到 5,000 iLvl。专注于完成主线任务和清理基础副本来积累装备。"]),
        section("mid-game", "5,000–6,000：中期推进", ["5,000–5,500 iLvl 是大多数玩家前期进阶时间的集中区。超越副本、远征内容和制作提供了这一范围的大部分装备。强化（在另一篇攻略中详述）在基础 iLvl 之上添加 + 加成。", "5,500–6,000 iLvl 需要更专注的游玩——有组织的副本、更高等级材料制作和持续强化。全球改良版 Season 1 将通过更长的进度曲线扩展这一范围。"]),
        section("end-game", "6,000–7,000+：终局内容", ["6,000–6,200 iLvl 是 Snowfield of Sorrow（简单：5,800，普通：6,000，困难：6,200）和高层深渊内容的门槛。达到 6,000 需要持续的副本通关、强化以及可能的顶级材料制作。", "7,000+ iLvl 是副本装备的理论终局上限。并非所有玩家都能达到这一范围——它需要顶级副本参与、高等级持续强化以及稀有制作材料的获取。"]),
        section("progression-tips", "对全球玩家的进阶建议", ["优先早期强化。5,000 iLvl +10 的武器比 5,500 iLvl +0 的武器更强。在中期，强化是最具成本效益的战斗力量提升方式。", "不要忽视制作。标准途径武器与副本掉落有竞争力，为无法持续通关高端内容的玩家提供了可行的替代方案。", "追踪你与下一个内容关卡的 iLvl 差距。如果差距在 100–200 iLvl 以内，优先该内容。如果差距较大，专注于当前可访问的内容和强化。"]),
      ],
    }),
    fr: articleCopy(guideLabels, "fr", 7, {
      eyebrow: "PROGRESSION",
      title: "Aion 2 Progression des Niveaux d'Équipement : du Départ au Fin de Partie",
      description: "Un guide complet du système de niveaux d'équipement d'Aion 2 — fonctionnement, seuils de contenu et progression de 4 000 à 7 000+",
      intro: "Comprendre le système de niveaux d'équipement d'Aion 2 est essentiel pour planifier votre progression. Les niveaux d'équipement déterminent votre accès aux contenus et votre efficacité en combat.",
      sourceNote: "Basé sur la documentation officielle de NCsoft et le système coréen de septembre 2026. Les valeurs globales peuvent être ajustées.",
      keywords: ["Aion 2 progression niveaux équipement", "guide niveaux équipement Aion 2", "Aion 2 end-game item level"],
      sections: [
        section("item-level-basics", "Fonctionnement des Niveaux d'Équipement", ["Chaque équipement a un niveau d'équipement (iLvl) qui détermine sa puissance. L'iLvl contrôle l'accès au contenu."]),
        section("early-game", "4 000–5 000 : Début de Partie", ["L'équipement de départ (4 000–4 500) provient des premières quêtes. Le iLvl 5 000 provient des donjons intermédiaires."]),
        section("mid-game", "5 000–6 000 : Milieu de Partie", ["C'est là que la plupart des joueurs passent le plus de temps. L'amélioration ajoute des bonus au-delà du iLvl de base."]),
        section("end-game", "6 000–7 000+ : Fin de Partie", ["6 000–6 200 est le seuil pour Snowfield of Sorrow. 7 000+ est la limite théorique du raid."]),
        section("progression-tips", "Conseils de Progression", ["Priorisez l'amélioration tôt. Un arme 5 000 +10 surpasse une arme 5 500 +0."]),
      ],
    }),
    de: articleCopy(guideLabels, "de", 7, {
      eyebrow: "PROGRESSION",
      title: "Aion 2 Ausrüstungs-Level Progression: vom Start bis zum Endgame",
      description: "Ein umfassender Guide zum Ausrüstungs-Level-System von Aion 2 — von 4 000 bis 7 000+",
      intro: "Das Ausrüstungs-Level-System von Aion 2 zu verstehen ist entscheidend für die Planung Ihrer Fortschritte.",
      sourceNote: "Basierend auf NCsoft-Dokumentation und dem koreanischen System von September 2026.",
      keywords: ["Aion 2 Ausrüstungs-Level Fortschritt", "Aion 2 Gear Level Guide", "Aion 2 Endgame Ausrüstung"],
      sections: [
        section("item-level-basics", "Funktionsweise der Ausrüstungs-Levels", ["Jedes Ausrüstungsstück hat ein Ausrüstungs-Level (iLvl), das seine Stärke bestimmt."]),
        section("early-game", "4 000–5 000: Früh-Spiel", ["Anfangs-Ausrüstung (4 000–4 500) stammt aus frühen Quests. 5 000 iLvl aus mittleren Dungeons."]),
        section("mid-game", "5 000–6 000: Mittel-Spiel", ["Hier verbringen die meisten Spieler die meiste Zeit. Erweiterung fügt Boni hinzu."]),
        section("end-game", "6 000–7 000+: Endgame", ["6 000–6 200 ist die Schwelle für Snowfield of Sorrow. 7 000+ ist die Raid-Obergrenze."]),
        section("progression-tips", "Fortschritts-Tipps", ["Priorisieren Sie früh die Erweiterung. Ein 5 000 iLvl +10-Waffen übertrifft 5 500 iLvl +0."]),
      ],
    }),
    es: articleCopy(guideLabels, "es", 7, {
      eyebrow: "PROGRESIÓN",
      title: "Aion 2 Hoja de Ruta de Niveles de Equipo: del Inicio al Final de Partida",
      description: "Una guía completa del sistema de niveles de equipo de Aion 2 — de 4 000 a 7 000+",
      intro: "Entender el sistema de niveles de equipo de Aion 2 es esencial para planificar tu progreso.",
      sourceNote: "Basado en la documentación oficial de NCsoft y el sistema coreano de septiembre de 2026.",
      keywords: ["Aion 2 progreso niveles equipo", "guía niveles equipo Aion 2", "Aion 2 end-game item level"],
      sections: [
        section("item-level-basics", "Cómo Funcionan los Niveles de Equipo", ["Cada equipo tiene un nivel de equipo (iLvl) que determina su potencia. El iLvl controla el acceso al contenido."]),
        section("early-game", "4 000–5 000: Inicio", ["El equipo inicial (4 000–4 500) proviene de las primeras misiones. 5 000 iLvl de mazmorras intermedias."]),
        section("mid-game", "5 000–6 000: Mitad de Partida", ["Aquí pasan la mayoría de los jugadores su tiempo. La mejora añade bonificaciones."]),
        section("end-game", "6 000–7 000+: Final de Partida", ["6 000–6 200 es el umbral para Snowfield of Sorrow. 7 000+ es el límite de raid."]),
        section("progression-tips", "Consejos de Progreso", ["Prioriza la mejora temprano. Un arma 5 000 +10 supera una 5 500 +0."]),
      ],
    }),
    ja: articleCopy(guideLabels, "ja", 7, {
      eyebrow: "進行",
      title: "Aion 2 装備レベル進行ロードマップ：初心者装備から終局武器まで",
      description: "Aion 2の装備レベルシステム完全ガイド——4,000から7,000+までの各段階の解説",
      intro: "Aion 2の装備レベルシステムを理解することは、進行を計画する上で不可欠です。装備レベルはコンテンツへのアクセスと戦闘効率を決定します。",
      sourceNote: "NCsoftの公式ドキュメントと2026年9月の韓国サーバーシステムに基づきます。",
      keywords: ["Aion 2 装備レベル進行", "Aion 2 ギアレベルガイド", "Aion 2 エンドゲーム装備"],
      sections: [
        section("item-level-basics", "装備レベルの仕組み", ["各装備にはiLvl（装備レベル）があり、その強さを決定します。iLvlはコンテンツへのアクセスを制御します。"]),
        section("early-game", "4,000–5,000：序盤", ["初心者装備（4,000–4,500）は初期クエストから。5,000 iLvlは中級ダンジョンから。"]),
        section("mid-game", "5,000–6,000：中盤", ["多くのプレイヤーがここで時間を使います。強化がiLvlベースのボーナスを追加します。"]),
        section("end-game", "6,000–7,000+：終盤", ["6,000–6,200はSnowfield of Sorrowの閾値。7,000+はレイドの理論上限です。"]),
        section("progression-tips", "進行のヒント", ["早期に強化を優先。5,000 iLvl +10の武器は5,500 iLvl +0より強いです。"]),
      ],
    }),
    "pt-br": articleCopy(guideLabels, "pt-br", 7, {
      eyebrow: "PROGRESSÃO",
      title: "Aion 2 Roadmap de Níveis de Equipamento: do Início ao Fim de Jogo",
      description: "Um guia completo do sistema de níveis de equipamento do Aion 2 — de 4 000 a 7 000+",
      intro: "Entender o sistema de níveis de equipamento do Aion 2 é essencial para planejar seu progresso.",
      sourceNote: "Baseado na documentação oficial da NCsoft e no sistema coreano de setembro de 2026.",
      keywords: ["Aion 2 progresso níveis equipamento", "guia níveis equipamento Aion 2", "Aion 2 end-game item level"],
      sections: [
        section("item-level-basics", "Como os Níveis de Equipamento Funcionam", ["Cada equipamento tem um nível de equipamento (iLvl) que determina sua potência. O iLvl controla o acesso ao conteúdo."]),
        section("early-game", "4 000–5 000: Início", ["O equipamento inicial (4 000–4 500) vem das primeiras missões. 5 000 iLvl de masmorras intermediárias."]),
        section("mid-game", "5 000–6 000: Meio de Jogo", ["Aqui é onde a maioria dos jogadores passa mais tempo. Melhorias adicionam bônus."]),
        section("end-game", "6 000–7 000+: Fim de Jogo", ["6 000–6 200 é o limiar para Snowfield of Sorrow. 7 000+ é o limite de raid."]),
        section("progression-tips", "Dicas de Progresso", ["Priorize melhorias cedo. Uma arma 5 000 +10 supera uma 5 500 +0."]),
      ],
    }),
    ru: articleCopy(guideLabels, "ru", 7, {
      eyebrow: "ПРОГРЕСС",
      title: "Aion 2 Дорожная Карта Уровней Снаряжения: от Старта до Эндгейма",
      description: "Полное руководство по системе уровней снаряжения в Aion 2 — от 4 000 до 7 000+",
      intro: "Понимание системы уровней снаряжения в Aion 2 необходимо для планирования прогресса. Уровни снаряжения определяют доступ к контенту и эффективность в бою.",
      sourceNote: "На основе официальной документации NCsoft и корейской системы сентября 2026 г. Глобальные значения могут быть скорректированы.",
      keywords: ["Aion 2 прогресс уровней снаряжения", "руководство уровнем снаряжения Aion 2", "Aion 2 end-game item level"],
      sections: [
        section("item-level-basics", "Как Работают Уровни Снаряжения", ["Каждый предмет имеет уровень снаряжения (iLvl), определяющий его мощь. iLvl контролирует доступ к контенту."]),
        section("early-game", "4 000–5 000: Ранняя Игра", ["Стартовое снаряжение (4 000–4 500) из первых квестов. 5 000 iLvl из средних данжей."]),
        section("mid-game", "5 000–6 000: Средняя Игра", ["Большинство игроков проводит здесь больше всего времени. Улучшение добавляет бонусы."]),
        section("end-game", "6 000–7 000+: Эндгейм", ["6 000–6 200 — порог для Snowfield of Sorrow. 7 000+ — теоретический предел рейдов."]),
        section("progression-tips", "Советы по Прогрессу", ["Приоритизируйте улучшение рано. Оружие 5 000 iLvl +10 сильнее 5 500 iLvl +0."]),
      ],
    }),
    ko: articleCopy(guideLabels, "ko", 7, {
      eyebrow: "진행",
      title: "Aion 2 장비 레벨 진행 로드맵: 입문 장비에서 후반 무기까지",
      description: "Aion 2의 장비 레벨 시스템 완전 가이드 — 4,000에서 7,000+까지",
      intro: "Aion 2의 장비 레벨 시스템을 이해하는 것은 진행을 계획하는 데 필수적입니다. 장비 레벨은 콘텐츠 접근 권한과 전투 효율을 결정합니다.",
      sourceNote: "NCsoft 공식 문서 및 2026년 9월 한국 서버 시스템에 기반합니다.",
      keywords: ["Aion 2 장비 레벨 진행", "Aion 2 기어 레벨 가이드", "Aion 2 엔드게임 장비"],
      sections: [
        section("item-level-basics", "장비 레벨 작동 방식", ["각 장비에는 장비 레벨(iLvl)이 있어 그 강도를 결정합니다. iLvl은 콘텐츠 접근을 제어합니다."]),
        section("early-game", "4,000–5,000: 초반", ["입문 장비(4,000–4,500)는 초기 퀘스트에서. 5,000 iLvl은 중급 던전에서."]),
        section("mid-game", "5,000–6,000: 중반", ["대부분의 플레이어가 여기서 가장 많은 시간을 보냅니다. 강화가 보너스를 추가합니다."]),
        section("end-game", "6,000–7,000+: 후반", ["6,000–6,200은 Snowfield of Sorrow의 임계값. 7,000+은 레이드의 이론 한계입니다."]),
        section("progression-tips", "진행 팁", ["조기에 강화를 우선하세요. 5,000 iLvl +10 무기는 5,500 iLvl +0보다 강합니다."]),
      ],
    }),
    "zh-hant": articleCopy(guideLabels, "zh-hant", 7, {
      eyebrow: "進階",
      title: "Aion 2 裝備等級進階路線圖：從新手裝備到終局武器",
      description: "Aion 2 裝具等級系統全面攻略——裝具等級如何運作，每個範圍解鎖什麼，以及從 4,000 到 7,000+ 每個等級段需要哪些內容",
      intro: "理解 Aion 2 的裝具等級系統對規劃進階至關重要。裝具等級不是純粹的標籤——它們決定你的內容訪問權限、戰鬥效果和參與終局系統的能力。",
      sourceNote: "基於 NCsoft 官方深淵時間表文件與 2026 年 9 月韓服裝具等級系統。全球數值可能因改良版 Season 1 而調整。",
      keywords: ["Aion 2 裝具等級進階", "Aion 2 裝具等級攻略", "Aion 2 裝具進階", "Aion 2 終局裝具等級", "Aion 2 Snowfield of Sorrow 裝具等級"],
      sections: [
        section("item-level-basics", "Aion 2 裝具等級如何運作", ["Aion 2 中的每件裝備都有一個裝具等級（iLvl），決定其強度。iLvl 是內容關卡的屬性——你需要最低 iLvl 才能進入副本、副本和 PvP 實例。iLvl 隨角色等級和裝備來源縮放。", "裝具等級範圍約為 4,000（新手裝備）到 7,000+（終局副本裝備）。每 100 iLvl 提升約等於 1-2% 的額外強度，但內容關卡才是真正的限制。"]),
        section("early-game", "4,000–5,000：前期進階", ["新手裝備（4,000–4,500）來自早期任務和訓練區。達到 4,500 你可以挑戰基礎副本和遠征內容。5,000 iLvl 裝備來自中端副本和超越內容。", "前期設計為快速進階——大多數玩家應在數小時內達到 5,000 iLvl。專注於完成主線任務和清理基礎副本來積累裝備。"]),
        section("mid-game", "5,000–6,000：中期推進", ["5,000–5,500 iLvl 是大多數玩家前期進階時間的集中區。超越副本、遠征內容和製作提供了這一範圍的大部分裝備。強化（在另一篇攻略中詳述）在基礎 iLvl 之上添加 + 加成。", "5,500–6,000 iLvl 需要更專注的遊玩——有組織的副本、更高等級材料製作和持續強化。全球改良版 Season 1 將通過更長的進度曲線擴展這一範圍。"]),
        section("end-game", "6,000–7,000+：終局內容", ["6,000–6,200 iLvl 是 Snowfield of Sorrow（簡單：5,800，普通：6,000，困難：6,200）和高層深淵內容的門檻。達到 6,000 需要持續的副本通關、強化以及可能的頂級材料製作。", "7,000+ iLvl 是副本裝備的理論終局上限。並非所有玩家都能達到這一範圍——它需要頂級副本參與、高等級持續強化以及稀有製作材料的獲取。"]),
        section("progression-tips", "對全球玩家的進階建議", ["優先早期強化。5,000 iLvl +10 的武器比 5,500 iLvl +0 的武器更強。在中期，強化是最具成本效益的戰鬥力量提升方式。", "不要忽視製作。標準途徑武器與副本掉落有競爭力，為無法持續通關高端內容的玩家提供了可行的替代方案。", "追蹤你與下一個內容關卡的 iLvl 差距。如果差距在 100–200 iLvl 以內，優先該內容。如果差距較大，專注於當前可訪問的內容和強化。"]),
      ],
    }),
  },
};
