import { articleCopy, guideLabels, localizations, publishedVerified, section } from "./trending-august-28-shared";
import type { ContentEntry, ContentHeroImage, ContentSource } from "./content-registry";

/* ARTICLE 2 — 'The Great Rebalance' patch (Aug 26): every class change */

const grSource1: ContentSource = {
  id: "aion2t-rebalance-2026-08-28",
  kind: "third-party", publisher: "AION2T",
  label: "Aion 2 — August 26, 2026 Update Notes: The Great Rebalance, Server Transfers and Bound Kina",
  url: "https://aion2t.com/news/40",
  publishedAt: "2026-08-26",
  retrievedAt: "2026-08-27",
  verifiedAt: "2026-08-27",
  localizations: localizations({
    "zh-hans": "Aion 2 —— 2026 年 8 月 26 日更新说明：大平衡、服务器转移与绑定基纳",
    en: "Aion 2 — August 26, 2026 Update Notes: The Great Rebalance, Server Transfers and Bound Kina",
    fr: "Aion 2 — Notes de mise à jour du 26 août 2026 : Grande rééquilibrage, transferts de serveur et Kina liée",
    de: "Aion 2 — Update-Notes vom 26. August 2026: Great Rebalance, Servertransfers und gebundenes Kina",
    es: "Aion 2 — Notas de actualización del 26 de agosto de 2026: Gran rebalanceo, transferencias de servidor y Kina vinculada",
    ja: "Aion 2 — 2026年8月26日アップデートノート：グレートリバランス、サーバー移行、バインドキナ",
    "pt-br": "Aion 2 — Notas de atualização de 26 de agosto de 2026: Grande reequilíbrio, transferências de servidor e Kina vinculada",
    ru: "Aion 2 — Примечания к обновлению от 26 августа 2026: Великий ребаланс, переносы серверов и связанная Кина",
    ko: "Aion 2 — 2026년 8월 26일 업데이트 노트: 그레이트 리밸런스, 서버 이전, 귀속 키나",
    "zh-hant": "Aion 2 —— 2026 年 8 月 26 日更新說明：大平衡、伺服器轉移與綁定金納",
  }, "https://aion2t.com/news/40"),
};

const grSource2: ContentSource = {
  id: "nc-official-rebalance-2026-08-28",
  kind: "official", publisher: "NC",
  label: "AION 2 Official Website — Patch Notes",
  url: "https://aion2.plaync.com/ko-kr/board/notice",
  publishedAt: "2026-08-26",
  retrievedAt: "2026-08-27",
  verifiedAt: "2026-08-27",
  localizations: localizations({
    "zh-hans": "AION 2 官方网站——更新说明",
    en: "AION 2 Official Website — Patch Notes",
    fr: "Site officiel AION 2 — notes de mise à jour",
    de: "AION 2 Offizielle Website — Patch-Notes",
    es: "Sitio web oficial de AION 2 — notas de actualización",
    ja: "AION 2 公式サイト — パッチノート",
    "pt-br": "Site oficial do AION 2 — notas de atualização",
    ru: "Официальный сайт AION 2 — патчноуты",
    ko: "AION 2 공식 사이트 — 패치 노트",
    "zh-hant": "AION 2 官方網站——更新說明",
  }, "https://aion2.plaync.com/ko-kr/board/notice"),
};

const grHero: ContentHeroImage = {
  src: "https://blogfiles.ncsoft.net/news/af7330da-4ff6-4b58-aece-400e6061a3be.jpg",
  width: 1100, height: 605,
  credit: "NC Corporation",
  sourceUrl: "https://aion2.plaync.com/ko-kr/board/notice",
  rights: "linked-official-media",
  translations: {
    "zh-hans": { alt: "Aion 2 大平衡补丁指南配图", caption: "NC 官方配图；8 月 26 日『大平衡』补丁上线韩/台服，重做圣骑士与吟游、重构 DPS 取消逻辑。" },
    en: { alt: "Aion 2 Great Rebalance patch guide image", caption: "Official NC artwork; the August 26 'Great Rebalance' shipped to the Korean/Taiwanese service, reworking Templar and Chanter and reworking DPS cancel logic." },
    fr: { alt: "Image du guide du patch Grande rééquilibrage d'Aion 2", caption: "Visuel officiel NC ; le « Great Rebalance » du 26 août est sorti sur le service coréen/taiwanais." },
    de: { alt: "Bild zum Guide zum Aion-2-Great-Rebalance-Patch", caption: "Offizielles NC-Artwork; der „Great Rebalance“ vom 26. August kam zum koreanischen/taiwanesischen Dienst." },
    es: { alt: "Imagen de la guía del parche Gran rebalanceo de Aion 2", caption: "Arte oficial de NC; el «Gran rebalanceo» del 26 de agosto llegó al servicio coreano/taiwanés." },
    ja: { alt: "Aion 2 グレートリバランスパッチガイド画像", caption: "NC公式アートワーク；8月26日の「グレートリバランス」が韓国・台湾サービスに配信されました。" },
    "pt-br": { alt: "Imagem do guia do patch Grande reequilíbrio de Aion 2", caption: "Arte oficial da NC; o «Grande reequilíbrio» de 26 de agosto chegou ao serviço coreano/taiwanês." },
    ru: { alt: "Изображение гайда по патчу «Великий ребаланс» в Aion 2", caption: "Официальный арт NC; «Великий ребаланс» от 26 августа вышел на корейско-тайваньском сервисе." },
    ko: { alt: "Aion 2 그레이트 리밸런스 패치 가이드 이미지", caption: "NC 공식 이미지입니다. 8월 26일 '그레이트 리밸런스'가 한국·대만 서버에 적용됐습니다." },
    "zh-hant": { alt: "Aion 2 大平衡修補程式指南配圖", caption: "NC 官方配圖；8 月 26 日『大平衡』修補程式上線韓/台服，重做聖騎士與吟遊、重構 DPS 取消邏輯。" },
  },
};

export const trendingAugust28Article2: ContentEntry = {
  section: "guides",
  slug: "aion-2-great-rebalance-patch-guide",
  schemaType: "Article",
  publishedAt: "2026-08-27",
  updatedAt: "2026-08-27",
  readingMinutes: 6,
  publication: publishedVerified,
  sources: [grSource1, grSource2],
  heroImage: grHero,
  related: [
    { kind: "content", section: "guides", slug: "post-patch-class-tier-list-august-2026" },
    { kind: "content", section: "guides", slug: "class-selection-pve-pvp-guide-global" },
    { kind: "content", section: "guides", slug: "aion-2-global-version-changes-guide" },
  ],
  translations: {
    en: articleCopy(guideLabels, "en", 6, {
      eyebrow: "BALANCE PATCH",
      title: "Aion 2 'The Great Rebalance' Patch (Aug 26): Every Class Change",
      description: "The August 26 'Great Rebalance' is the biggest class patch since launch: minimum cancel time on all skills, reworked Templar and Chanter, halved party synergies, and more. Here is every change and what it means for the meta.",
      intro: "On August 26, the Korean/Taiwanese service received 'The Great Rebalance' — the largest class patch since Aion 2's launch. It changes how animation-cancelling works, reworks Templar and Chanter, trims group synergies, and adjusts shields, lifesteal, theostones, and dispel. This guide breaks down every confirmed change and what it signals for players, including how it previews the global version's tuning.",
      sourceNote: "Based on AION2T's August 26 update notes and NC's official patch notes for the Korean/Taiwanese service. The 'Great Rebalance' applies to the Asian service; the global version may receive adjusted tuning at or after its October 5 launch.",
      keywords: ["Aion 2 Great Rebalance", "Aion 2 balance patch", "Aion 2 class changes August 2026", "Aion 2 Templar rework", "Aion 2 animation cancel"],
      sections: [
        section("overview", "Overview: The Big Picture", ["The headline change is that all skills now apply a minimum cancel time. In practice this means animation-cancelling DPS no longer depends on gear speed and network latency — the same rotation does the same damage for everyone on the same gear, removing the 'script-cancel' advantage high-ping or high-gear players had.", "Across the board, all nine classes received PvE damage increases, with damage caps lowered and damage floors raised. That is a flattening pass: weaker outputs got pulled up, top-end burst got pulled in, narrowing the gap between good and optimal rotations.", "It is deliberately a 'rebalance' rather than a nerf wave — the patch reads as an attempt to standardize output and make class power less dependent on execution exploits, while keeping every class viable."]),
        section("templar-chanter", "Templar & Chanter Rework", ["Templar and Chanter got the most surgery. Judgment and Dark Crush are no longer passive stun-penalty skills triggered by taking damage; they now trigger from the class's own rotation, giving players active control over these tools instead of a reactionary proc.", "Punishment becomes a 20-meter projectile, improving Templar's reach in PvE and PvP engagements where gap-closing is awkward. Spinning Strike's mana cost drops from 250 to 100 MP and its cooldown is halved, smoothing the class's sustain in extended fights.", "Both classes also lost roughly half of their party-synergy passives (alongside Gladiator and Cleric), a coordinated cut that trims how much group power these support-leaning classes passively hand out."]),
        section("other-classes", "Other Class & System Adjustments", ["Beyond the two reworks, four classes had their primary-skill lifesteal reduced, curbing self-sustain in prolonged combat. All fixed-value shields were converted to HP-percentage shields, making them scale with gear and stay relevant later.", "Theostones received a built-in cooldown, preventing back-to-back theostone bursts, and dispel no longer clears potion buffs — a meaningful change for both PvE and PvP where cleanse timing was a core skill.", "Abyss armor set bonuses were buffed: at 12 pieces the bonus rises from 20% to 40%, reinforcing the end-game PvPvE gearing path."]),
        section("economy", "Economy & New Features in the Patch", ["The patch also introduced Bound Kina: kinah that drops from six dungeon modes is now bound to the character, an anti-economy-inflation measure that limits how freely farmed kinah can be sold on the broker. This complements the earlier Quna-to-Kinah exchange limits.", "Server Transfers arrived as a limited feature (one week, 1,000 Quna base + 200 per character, active only 20:00-24:00) — covered in detail in our server transfer guide.", "A new Daeva Pass, 'Moonlit Oasis', runs until September 22, refreshing the seasonal battle pass track with the usual cosmetics and resources."]),
        section("global", "What It Means for Global Players", ["The 'Great Rebalance' is an Asian-service patch, but it matters to global players for two reasons: it previews the tuning philosophy NC applies to class balance, and the global version is explicitly adjusted from Korean/Taiwanese feedback.", "Expect the global October 5 launch to ship with a class balance baseline informed by this patch — either the same rebalance or a version tuned further. Watch for global patch notes closer to launch to confirm which classes receive which changes.", "For meta-watchers, the practical takeaway: animation-cancel execution is being normalized, group-synergy stacking is being trimmed, and survivability (shields, lifesteal, cleanse) is being re-centered — plan your class and build choices with those trends in mind."]),
      ],
    }),
    "zh-hans": articleCopy(guideLabels, "zh-hans", 6, {
      eyebrow: "平衡补丁",
      title: "Aion 2『大平衡』补丁（8月26日）：全部职业改动",
      description: "8 月 26 日『大平衡』是上线以来最大的职业补丁：全技能最低取消时间、重做圣骑士与吟游、协同被动减半等。以下为全部改动与对版本的意义。",
      intro: "8 月 26 日，韩/台服迎来『大平衡』——Aion 2 上线以来最大的职业补丁。它改变动画取消机制、重做圣骑士与吟游、削减团队协同、调整护盾/吸血/神石/驱散。本指南逐一解读已确认改动及其对玩家（包括全球版调校预览）的意义。",
      sourceNote: "基于 AION2T 8 月 26 日更新说明与 NC 官方韩/台服更新说明。『大平衡』适用于亚服；全球版可能在 10 月 5 日上线时采用调整后的版本。",
      keywords: ["Aion 2 大平衡", "Aion 2 平衡补丁", "Aion 2 职业改动 2026年8月", "Aion 2 圣骑士重做", "Aion 2 动画取消"],
      sections: [
        section("overview", "总览：大局", ["核心变化：所有技能现在都有最低取消时间——动画取消的 DPS 不再取决于装备攻速与网络延迟，同样装备下输出拉平，消除了高延迟/高配置玩家的脚本取消优势。", "九个职业 PvE 伤害全部提升，上限下调、下限上调，压缩好循环与最佳循环的差距。", "这是『再平衡』而非削弱浪潮——标准化输出、让职业强度少依赖操作漏洞。"]),
        section("templar-chanter", "圣骑士与吟游重做", ["Judgment 与 Dark Crush 不再是被动受击惩罚技，改由职业自身循环触发，玩家获得主动控制。", "Punishment 变为 20m 投射物；Spinning Strike 蓝耗 250→100、冷却减半。", "两者与角斗士、治愈协同被动约减半，削减支援型职业被动赋予的团队强度。"]),
        section("other-classes", "其他职业与系统调整", ["四个职业主技能吸血削减；所有固定护盾改为 HP 百分比护盾，随装备成长。", "神石加入内置冷却；驱散不再清除药水增益。", "深渊套装 12 件加成 20%→40%，强化终局 PvPvE 装备路线。"]),
        section("economy", "经济与新功能", ["引入绑定基纳：六个副本模式掉落的基纳绑定角色，限制刷金出售，呼应此前 Quna 兑换限制。", "服务器转移作为限时功能（一周、1000 Quna 基础 + 每角色 200、仅 20:00-24:00），详见服务器转移指南。", "新 Daeva Pass『Moonlit Oasis』持续至 9 月 22 日。"]),
        section("global", "对全球玩家的意义", ["这是亚服补丁，但对全球玩家重要：它预览 NC 的职业平衡理念，且全球版明确根据韩/台反馈调整。", "预计 10 月 5 日全球上线会以本补丁为平衡基线。", "实操要点：动画取消执行被标准化、团队协同叠加被削减、生存（护盾/吸血/净化）被重新居中——据此规划职业与构筑。"]),
      ],
    }),
    ko: articleCopy(guideLabels, "ko", 6, {
      eyebrow: "밸런스 패치",
      title: "Aion 2 '그레이트 리밸런스' 패치 (8월 26일): 전체 클래스 변경점",
      description: "8월 26일 '그레이트 리밸런스'는 출시 이후 최대 클래스 패치입니다: 모든 스킬 최소 취소 시간, 템플러·챈터 리워크, 파티 시너지 절반 감소 등. 모든 변경점과 메타 의미를 다룹니다.",
      intro: "8월 26일 한국·대만 서버에 '그레이트 리밸런스'가 적용됐습니다 — 출시 이후 최대 클래스 패치입니다. 애니메이션 캔슬 방식 변경, 템플러·챈터 리워크, 그룹 시너지 축소, 방패·흡혈·테오스톤·디스펠 조정. 모든 확정 변경점을 정리합니다.",
      sourceNote: "AION2T의 8월 26일 업데이트 노트와 NC 공식 한/대만 패치 노트 기반. 글로벌 버전은 10월 5일 출시 시 조정된 버전일 수 있습니다.",
      keywords: ["Aion 2 그레이트 리밸런스", "Aion 2 밸런스 패치", "Aion 2 클래스 변경 2026년 8월", "Aion 2 템플러 리워크", "Aion 2 애니메이션 캔슬"],
      sections: [
        section("overview", "개요", "모든 스킬에 최소 취소 시간 적용 — 애니메이션 캔슬 DPS가 장비 공속·네트워크에 의존하지 않게 됐습니다. 9개 클래스 PvE 데미지 상한 하향·하한 상향으로 격차 축소. '리밸런스'지 너프가 아닙니다."),
        section("templar-chanter", "템플러 & 챈터 리워크", "Judgment/Dark Crush가 피격 패시브가 아닌 자체 순환에서 발동. Punishment 20m 투사체, Spinning Strike MP 250→100·쿨 절반. 파티 시너지 절반 감소."),
        section("other-classes", "기타 클래스·시스템", "4개 클래스 흡혈 감소, 고정 방패 → HP% 방패, 테오스톤 내부 쿨, 디스펠이 물약 버프를 지우지 않음. 심연 세트 12피스 20%→40%."),
        section("economy", "경제 & 신규 기능", "귀속 키나 도입(6개 던전 모드 드랍 귀속), 서버 이전(1주·1000 큐나+캐릭터당 200·20:00-24:00), 신규 대에바 패스 '문릿 오아시스'(9월 22일까지)."),
        section("global", "글로벌 플레이어 의미", "아시아 서버 패치지만 NC의 밸런스 철학을 보여주고, 글로벌은 한/대만 피드백 기반으로 조정됩니다. 10월 5일 출시 빌드에 반영될 가능성이 높습니다."),
      ],
    }),
    ja: articleCopy(guideLabels, "ja", 6, {
      eyebrow: "バランスパッチ",
      title: "Aion 2『グレートリバランス』パッチ（8月26日）：全クラス変更点",
      description: "8月26日の『グレートリバランス』はリリース以来最大のクラスパッチ：全スキル最低キャンセル時間、テンプラー・チャンター再設計、パーティ相乗効果半減など。全変更点とメタへの影響を解説します。",
      intro: "8月26日、韓国・台湾サーバーに『グレートリバランス』が配信されました。アニメーションキャンセルの変更、テンプラー・チャンター再設計、グループシナジー削減、シールド・吸血・テオストーン・ディスペル調整。確定済みの変更点を整理します。",
      sourceNote: "AION2T の8月26日アップデートノートと NC 公式の韓国・台湾パッチノートに基づきます。グローバル版は10月5日時点で調整版になる可能性があります。",
      keywords: ["Aion 2 グレートリバランス", "Aion 2 バランスパッチ", "Aion 2 クラス変更 2026年8月", "Aion 2 テンプラー再設計", "Aion 2 アニメーションキャンセル"],
      sections: [
        section("overview", "概要", "全スキルに最低キャンセル時間を適用 — アニメーションキャンセルDPSが装備速度・回線に依存しなくなりました。9クラスのPvEダメージは上限低下・下限上昇で格差縮小。"),
        section("templar-chanter", "テンプラー＆チャンター再設計", "Judgment/Dark Crush が被弾パッシブから自循環で発動へ。Punishment 20m 投射物、Spinning Strike MP 250→100・CD半減。パーティ相乗効果約半減。"),
        section("other-classes", "他クラス・システム", "4クラスの主スキル吸血削減、固定シールド→HP%化、テオストーン内部CD、ディスペルが薬バフを解除しない。深淵セット12部位 20%→40%。"),
        section("economy", "経済＆新機能", "バインドキナ導入（6ダンジョンモード）、サーバー移行（1週間・1000キナ+キャラ200・20:00-24:00）、新デーバパス『ムーンリットオアシス』（9月22日まで）。"),
        section("global", "グローバルへの意味", "アジアサーバーパッチですが NC のバランス哲学を示し、グローバルは韓国・台湾フィードバック基盤で調整されます。10月5日ビルドに反映される可能性が高いです。"),
      ],
    }),
    fr: articleCopy(guideLabels, "fr", 6, {
      eyebrow: "PATCH D'ÉQUILIBRAGE",
      title: "Patch « Great Rebalance » d'Aion 2 (26 août) : tous les changements de classes",
      description: "Le « Great Rebalance » du 26 août est le plus gros patch de classes depuis le lancement : temps d'annulation minimum, refonte du Templier et du Chanter, synergies réduites. Tous les changements.",
      intro: "Le 26 août, le service coréen/taiwanais a reçu le « Great Rebalance », le plus gros patch de classes depuis le lancement d'Aion 2. Il modifie l'annulation d'animation, refond Templier et Chanter, réduit les synergies de groupe et ajuste boucliers, vol de vie, théostones et dissipation.",
      sourceNote: "Basé sur les notes du 26 août d'AION2T et les patch notes officiels NC. Le patch concerne le service asiatique ; la version mondiale peut recevoir un rééquilibrage ajusté.",
      keywords: ["Aion 2 Great Rebalance", "Aion 2 patch d'équilibrage", "Aion 2 changements de classes", "Aion 2 refonte Templier"],
      sections: [
        section("overview", "Vue d'ensemble", "Tous les sorts appliquent un temps d'annulation minimum : le DPS par annulation d'animation ne dépend plus du stuff ni du ping. Neuf classes reçoivent un boost PvE (plafonds abaissés, planchers relevés)."),
        section("templar-chanter", "Refonte Templier & Chanter", "Judgment et Dark Crush se déclenchent désormais depuis la rotation, Punishment devient un projectile 20 m, Spinning Strike passe à 100 MP avec CD réduit. Synergies de groupe réduites de moitié."),
        section("other-classes", "Autres classes et systèmes", "Vol de vie réduit sur 4 classes, boucliers fixes → %PV, théostones avec CD interne, dissipation ne purge plus les buffs de potions. Bonus de set Abyss 12 pièces 20%→40%."),
        section("economy", "Économie et nouveautés", "Kina liée (6 modes de donjon), transferts de serveur (1 semaine, 1 000 Quna + 200/caractère, 20h-24h), nouveau Daeva Pass « Moonlit Oasis » jusqu'au 22 septembre."),
        section("global", "Pour la version mondiale", "Patch asiatique mais il préfigure la philosophie d'équilibrage de NC ; la sortie mondiale du 5 octobre devrait s'en inspirer."),
      ],
    }),
    de: articleCopy(guideLabels, "de", 6, {
      eyebrow: "BALANCE-PATCH",
      title: "Aion-2-„Great-Rebalance“-Patch (26. August): alle Klassenänderungen",
      description: "Der „Great Rebalance“ vom 26. August ist der größte Klassen-Patch seit Launch: minimale Abbruchzeit, Rework von Templer und Chanter, halbierte Synergien. Alle Änderungen.",
      intro: "Am 26. August erhielt der koreanische/taiwanesische Dienst den „Great Rebalance“ – den größten Klassen-Patch seit dem Launch von Aion 2. Er ändert Animation-Cancel, überarbeitet Templer und Chanter, kürzt Gruppensynergien und passt Schilde, Lebensraub, Theostones und Dispel an.",
      sourceNote: "Basierend auf den Notizen vom 26. August von AION2T und den offiziellen NC-Patch-Notes. Patch betrifft den asiatischen Dienst; die globale Version kann angepasstes Tuning erhalten.",
      keywords: ["Aion 2 Great Rebalance", "Aion 2 Balance-Patch", "Aion 2 Klassenänderungen", "Aion 2 Templer-Rework"],
      sections: [
        section("overview", "Überblick", "Alle Skills haben jetzt eine minimale Abbruchzeit: Animation-Cancel-DPS hängt nicht mehr von Ausrüstung und Ping ab. Neun Klassen erhalten PvE-Schub (Obergrenzen gesenkt, Untergrenzen angehoben)."),
        section("templar-chanter", "Templer & Chanter-Rework", "Judgment und Dark Crush lösen aus der eigenen Rotation aus, Punishment wird 20-m-Projektil, Spinning Strike auf 100 MP mit halbem CD. Gruppensynergien halbiert."),
        section("other-classes", "Andere Klassen & Systeme", "Lebensraub auf 4 Klassen reduziert, feste Schilde → %HP, Theostones mit internem CD, Dispel entfernt keine Trank-Buffs. Abyss-Set 12 Teile 20%→40%."),
        section("economy", "Wirtschaft & Neues", "Gebundenes Kina (6 Dungeon-Modi), Servertransfer (1 Woche, 1000 Quna + 200/Charakter, 20-24 Uhr), neuer Daeva Pass „Moonlit Oasis“ bis 22. September."),
        section("global", "Für die globale Version", "Asien-Patch, zeigt aber NCs Balance-Philosophie; der globale Start am 5. Oktober dürfte sich daran orientieren."),
      ],
    }),
    es: articleCopy(guideLabels, "es", 6, {
      eyebrow: "PARCHE DE EQUILIBRIO",
      title: "Parche «Gran rebalanceo» de Aion 2 (26 de agosto): todos los cambios de clase",
      description: "El «Gran rebalanceo» del 26 de agosto es el mayor parche de clases desde el lanzamiento: tiempo de cancelación mínimo, rework de Templario y Chanter, sinergias reducidas. Todos los cambios.",
      intro: "El 26 de agosto, el servicio coreano/taiwanés recibió el «Gran rebalanceo», el mayor parche de clases desde el lanzamiento de Aion 2. Cambia la cancelación de animación, rehace Templario y Chanter, recorta sinergias de grupo y ajusta escudos, robo de vida, theostones y disipación.",
      sourceNote: "Basado en las notas del 26 de agosto de AION2T y los patch notes oficiales de NC. El parche es para el servicio asiático; la versión global puede recibir un ajuste adaptado.",
      keywords: ["Aion 2 Gran rebalanceo", "Aion 2 parche de equilibrio", "Aion 2 cambios de clase", "Aion 2 rework Templario"],
      sections: [
        section("overview", "Resumen", "Todos los hechizos aplican un tiempo de cancelación mínimo: el DPS por cancelación de animación ya no depende del equipo ni del ping. Nueve clases reciben boost PvE (techos bajados, suelos subidos)."),
        section("templar-chanter", "Rework de Templario y Chanter", "Judgment y Dark Crush se disparan desde la propia rotación, Punishment pasa a proyectil de 20 m, Spinning Strike a 100 MP con CD reducido. Sinergias de grupo reducidas a la mitad."),
        section("other-classes", "Otras clases y sistemas", "Robo de vida reducido en 4 clases, escudos fijos → %PV, theostones con CD interno, disipación ya no limpia buffs de pociones. Bonus de set Abyss 12 piezas 20%→40%."),
        section("economy", "Economía y novedades", "Kina vinculada (6 modos de mazmorra), transferencias de servidor (1 semana, 1000 Quna + 200/personaje, 20-24 h), nuevo Daeva Pass «Moonlit Oasis» hasta el 22 de septiembre."),
        section("global", "Para la versión global", "Parche asiático pero prefigura la filosofía de equilibrio de NC; el lanzamiento global del 5 de octubre debería inspirarse en él."),
      ],
    }),
    "pt-br": articleCopy(guideLabels, "pt-br", 6, {
      eyebrow: "PATCH DE EQUILÍBRIO",
      title: "Patch «Grande reequilíbrio» de Aion 2 (26 de agosto): todas as mudanças de classe",
      description: "O «Grande reequilíbrio» de 26 de agosto é o maior patch de classes desde o lançamento: tempo de cancelamento mínimo, rework de Templário e Chanter, sinergias reduzidas. Todas as mudanças.",
      intro: "Em 26 de agosto, o serviço coreano/taiwanês recebeu o «Grande reequilíbrio», o maior patch de classes desde o lançamento de Aion 2. Ele muda o cancelamento de animação, refaz Templário e Chanter, corta sinergias de grupo e ajusta escudos, roubo de vida, theostones e dissipação.",
      sourceNote: "Baseado nas notas de 26 de agosto da AION2T e nos patch notes oficiais da NC. O patch é para o serviço asiático; a versão global pode receber ajuste adaptado.",
      keywords: ["Aion 2 Grande reequilíbrio", "Aion 2 patch de equilíbrio", "Aion 2 mudanças de classe", "Aion 2 rework Templário"],
      sections: [
        section("overview", "Visão geral", "Todos os feitiços aplicam tempo de cancelamento mínimo: o DPS por cancelamento de animação não depende mais de equipamento nem de ping. Nove classes recebem boost PvE (tetos menores, pisos maiores)."),
        section("templar-chanter", "Rework de Templário e Chanter", "Judgment e Dark Crush passam a disparar da própria rotação, Punishment vira projétil de 20 m, Spinning Strike vai a 100 MP com CD reduzido. Sinergias de grupo reduzidas pela metade."),
        section("other-classes", "Outras classes e sistemas", "Roubo de vida reduzido em 4 classes, escudos fixos → %PV, theostones com CD interno, dissipação não limpa mais buffs de poção. Bônus de set Abyss 12 peças 20%→40%."),
        section("economy", "Economia e novidades", "Kina vinculada (6 modos de masmorra), transferências de servidor (1 semana, 1000 Quna + 200/personagem, 20h-24h), novo Daeva Pass «Moonlit Oasis» até 22 de setembro."),
        section("global", "Para a versão global", "Patch asiático mas prenuncia a filosofia de equilíbrio da NC; o lançamento global de 5 de outubro deve se inspirar nele."),
      ],
    }),
    ru: articleCopy(guideLabels, "ru", 6, {
      eyebrow: "ПАТЧ БАЛАНСА",
      title: "Патч «Великий ребаланс» Aion 2 (26 августа): все изменения классов",
      description: "«Великий ребаланс» от 26 августа — крупнейший патч классов с запуска: минимальное время отмены, реворк Тамплиера и Чантера, урезанные синергии. Все изменения.",
      intro: "26 августа корейско-тайваньский сервис получил «Великий ребаланс» — крупнейший патч классов с запуска Aion 2. Он меняет отмену анимации, переделывает Тамплиера и Чантера, сокращает групповые синергии и корректирует щиты, вампиризм, теостоуны и развеивание.",
      sourceNote: "На основе заметок AION2T от 26 августа и официальных патчноутов NC. Патч для азиатского сервиса; глобальная версия может получить адаптированную настройку.",
      keywords: ["Aion 2 Великий ребаланс", "Aion 2 патч баланса", "Aion 2 изменения классов", "Aion 2 реворк Тамплиера"],
      sections: [
        section("overview", "Обзор", "Все скиллы получили минимальное время отмены: DPS от отмены анимации больше не зависит от шмота и пинга. Девять классов получают буст PvE (потолки ниже, полы выше)."),
        section("templar-chanter", "Реворк Тамплиера и Чантера", "Judgment и Dark Crush срабатывают из собственной ротации, Punishment становится 20-м снарядом, Spinning Strike до 100 MP с половинным КД. Групповые синергии вдвое меньше."),
        section("other-classes", "Другие классы и системы", "Вампиризм урезан на 4 классах, фикс-щиты → %HP, у теостоунов внутренний КД, развеивание больше не снимает бафы зелий. Сет Абисс 12 предметов 20%→40%."),
        section("economy", "Экономика и новое", "Связанная Кина (6 режимов данжа), перенос серверов (неделя, 1000 Кина + 200/персонаж, 20:00-24:00), новый Daeva Pass «Moonlit Oasis» до 22 сентября."),
        section("global", "Для глобальной версии", "Азиатский патч, но показывает философию баланса NC; глобальный запуск 5 октября, вероятно, опирается на него."),
      ],
    }),
    "zh-hant": articleCopy(guideLabels, "zh-hant", 6, {
      eyebrow: "平衡修補程式",
      title: "Aion 2『大平衡』修補程式（8月26日）：全部職業改動",
      description: "8 月 26 日『大平衡』是上線以來最大的職業修補程式：全技能最低取消時間、重做聖騎士與吟遊、協同被動減半等。以下為全部改動與對版本（含全球版調校預覽）的意義。",
      intro: "8 月 26 日，韓/台服迎來『大平衡』——Aion 2 上線以來最大的職業修補程式。它改變動畫取消機制、重做聖騎士與吟遊、削減團隊協同、調整護盾/吸血/神石/驅散。本指南逐一解讀已確認改動及其對玩家的意義。",
      sourceNote: "基於 AION2T 8 月 26 日更新說明與 NC 官方韓/台服更新說明。『大平衡』適用於亞服；全球版可能在 10 月 5 日上線時採用調整後的版本。",
      keywords: ["Aion 2 大平衡", "Aion 2 平衡修補程式", "Aion 2 職業改動 2026年8月", "Aion 2 聖騎士重做", "Aion 2 動畫取消"],
      sections: [
        section("overview", "總覽：大局", ["核心變化：所有技能現在都有最低取消時間——動畫取消的 DPS 不再取決於裝備攻速與網路延遲，同樣裝備下輸出拉平。", "九個職業 PvE 傷害全部提升，上限下調、下限上調。", "這是『再平衡』而非削弱浪潮。"]),
        section("templar-chanter", "聖騎士與吟遊重做", ["Judgment 與 Dark Crush 不再是被動受擊懲罰技，改由職業自身循環觸發。", "Punishment 變為 20m 投射物；Spinning Strike 藍耗 250→100、冷卻減半。", "兩者與角鬥士、治癒協同被動約減半。"]),
        section("other-classes", "其他職業與系統調整", ["四個職業主技能吸血削減；所有固定護盾改為 HP 百分比護盾。", "神石加入內建冷卻；驅散不再清除藥水增益。", "深淵套裝 12 件加成 20%→40%。"]),
        section("economy", "經濟與新功能", ["引入綁定金納：六個副本模式掉落的金納綁定角色。", "伺服器轉移作為限時功能（一週、1000 金納基礎 + 每角色 200、僅 20:00-24:00）。", "新 Daeva Pass『Moonlit Oasis』持續至 9 月 22 日。"]),
        section("global", "對全球玩家的意義", ["這是亞服修補程式，但預覽 NC 的職業平衡理念，且全球版明確根據韓/台回饋調整。", "預計 10 月 5 日全球上線會以本修補程式為平衡基線。", "實作要點：動畫取消執行被標準化、團隊協同疊加被削減、生存被重新居中。"]),
      ],
    }),
  },
};