import { articleCopy, guideLabels, localizations, publishedVerified, section } from "./trending-august-30-shared";
import type { ContentEntry, ContentHeroImage, ContentSource } from "./content-registry";

/* ARTICLE 3 — Monetization: F2P, cosmetics-first, optional membership, no-P2W stance */

const mtSource1: ContentSource = {
  id: "inthegame-gamescom-preview-2026-08-30-c",
  kind: "third-party", publisher: "intheGame",
  label: "Preview | AION 2 op Gamescom 2026 (monetization & dev stance)",
  url: "https://inthegame.nl/2026/08/29/preview-aion-2-op-gamescom-2026/",
  publishedAt: "2026-08-29",
  retrievedAt: "2026-08-29",
  verifiedAt: "2026-08-29",
  localizations: localizations({
    "zh-hans": "前瞻 | Gamescom 2026 的 Aion 2（变现与开发者立场）",
    en: "Preview | AION 2 op Gamescom 2026 (monetization & dev stance)",
    fr: "Aperçu | AION 2 au Gamescom 2026 (monétisation et position des devs)",
    de: "Vorschau | AION 2 auf der Gamescom 2026 (Monetarisierung & Dev-Position)",
    es: "Impresión | AION 2 en Gamescom 2026 (monetización y postura de los devs)",
    ja: "プレビュー | Gamescom 2026 の Aion 2（収益化と開発陣の立場）",
    "pt-br": "Impressão | AION 2 na Gamescom 2026 (monetização e postura dos devs)",
    ru: "Превью | Aion 2 на Gamescom 2026 (монетизация и позиция разработчиков)",
    ko: "프리뷰 | Gamescom 2026의 Aion 2 (수익화·개발진 입장)",
    "zh-hant": "前瞻 | Gamescom 2026 的 Aion 2（變現與開發者立場）",
  }, "https://inthegame.nl/2026/08/29/preview-aion-2-op-gamescom-2026/"),
};

const mtSource2: ContentSource = {
  id: "steam-founders-showcase-2026-08-30",
  kind: "third-party", publisher: "Steam",
  label: "AION 2 — Founder's Pack Content Showcase",
  url: "https://steamcommunity.com/games/3393110/announcements/detail/1839041357024448",
  publishedAt: "2026-07-22",
  retrievedAt: "2026-08-29",
  verifiedAt: "2026-08-29",
  localizations: localizations({
    "zh-hans": "AION 2——创始人包内容展示",
    en: "AION 2 — Founder's Pack Content Showcase",
    fr: "Aion 2 — Présentation du contenu des packs Fondateur",
    de: "Aion 2 — Founder's-Pack-Inhalte im Überblick",
    es: "Aion 2 — Presentación del contenido de los packs de fundador",
    ja: "Aion 2 — ファウンダーズパック内容紹介",
    "pt-br": "Aion 2 — Apresentação do conteúdo dos packs de fundador",
    ru: "Aion 2 — Обзор наборов основателя",
    ko: "Aion 2 — 파운더스 팩 콘텐츠 소개",
    "zh-hant": "AION 2——創始人包內容展示",
  }, "https://steamcommunity.com/games/3393110/announcements/detail/1839041357024448"),
};

const mtHero: ContentHeroImage = {
  src: "https://blogfiles.ncsoft.net/news/af7330da-4ff6-4b58-aece-400e6061a3be.jpg",
  width: 1100, height: 605,
  credit: "NC Corporation",
  sourceUrl: "https://aion2.plaync.com/ja-jp/board/notice/list",
  rights: "linked-official-media",
  translations: {
    "zh-hans": { alt: "Aion 2 变现模式指南配图", caption: "NC 官方配图；Gamescom 2026 开发者问答确认 Aion 2 免费游玩、以外观为主变现，并提供带月度好物的可选订阅。" },
    en: { alt: "Aion 2 monetization guide image", caption: "Official NC artwork; the Gamescom 2026 developer Q&A confirmed Aion 2 is free-to-play with cosmetics-first monetization and an optional membership offering monthly goodies." },
    fr: { alt: "Image du guide de monétisation d'Aion 2", caption: "Visuel officiel NC ; le Q&A Gamescom 2026 confirme un modèle free-to-play axé cosmétiques et un abonnement optionnel." },
    de: { alt: "Bild zum Aion-2-Monetarisierungsguide", caption: "Offizielles NC-Artwork; das Gamescom-2026-Q&A bestätigt Free-to-play, Kosmetik-Monetarisierung und eine optionale Mitgliedschaft." },
    es: { alt: "Imagen de la guía de monetización de Aion 2", caption: "Arte oficial de NC; el Q&A de Gamescom 2026 confirma free-to-play, monetización cosmética y suscripción opcional." },
    ja: { alt: "Aion 2 収益化ガイド画像", caption: "NC公式アートワーク；Gamescom 2026 の開発者Q&Aは、基本プレイ無料・コスメ中心の収益化・月間特典付き任意サブスクを確認しました。" },
    "pt-br": { alt: "Imagem do guia de monetização do Aion 2", caption: "Arte oficial da NC; o Q&A da Gamescom 2026 confirma free-to-play, monetização cosmética e assinatura opcional." },
    ru: { alt: "Изображение гайда по монетизации Aion 2", caption: "Официальный арт NC; Q&A Gamescom 2026 подтверждает free-to-play, косметическую монетизацию и опциональную подписку." },
    ko: { alt: "Aion 2 수익화 가이드 이미지", caption: "NC 공식 이미지입니다. Gamescom 2026 개발자 Q&A는 기본 무료·코스메틱 중심 수익화·월간 혜택의 선택 구독을 확인했습니다." },
    "zh-hant": { alt: "Aion 2 變現模式指南配圖", caption: "NC 官方配圖；Gamescom 2026 開發者問答確認 Aion 2 免費遊玩、以外觀為主變現，並提供帶月度好物的可選訂閱。" },
  },
};

export const trendingAugust30Article3: ContentEntry = {
  section: "guides",
  slug: "aion-2-monetization-f2p-cosmetics-guide",
  schemaType: "Article",
  publishedAt: "2026-08-29",
  updatedAt: "2026-08-29",
  readingMinutes: 4,
  publication: publishedVerified,
  sources: [mtSource1, mtSource2],
  heroImage: mtHero,
  related: [
    { kind: "content", section: "news", slug: "aion-2-founders-packs-30-day-membership" },
    { kind: "content", section: "guides", slug: "aion-2-brokerage-market-guide" },
    { kind: "content", section: "guides", slug: "aion-2-great-rebalance-patch-guide" },
    { kind: "content", section: "guides", slug: "aion-2-cross-platform-guide" },
  ],
  translations: {
    en: articleCopy(guideLabels, "en", 4, {
      eyebrow: "ECONOMY & MONETIZATION",
      title: "Aion 2 Monetization Guide: Free-to-Play, Cosmetics-First & Optional Membership",
      description: "The Gamescom 2026 developer Q&A laid out how Aion 2 makes money: free-to-play, cosmetics-led monetization, an optional subscription with monthly goodies, and many skins unlockable in-game. Here is the full picture.",
      intro: "Aion 2's monetization was one of the most asked-about topics heading into launch, and the Gamescom 2026 developer Q&A gave the clearest answer yet: the game is free-to-play, monetization is primarily cosmetics, an optional subscription adds monthly goodies, and a large share of mount skins and outfits are unlockable purely through in-game content. This guide assembles what has been confirmed and what it means for how you spend (or don't spend).",
      sourceNote: "Based on intheGame's Gamescom 2026 developer Q&A (August 29, 2026) and the official Steam Founder's Pack content showcase, with membership context from the Aion 2 Japan official site.",
      keywords: ["Aion 2 monetization", "Aion 2 free to play", "Aion 2 cosmetics", "Aion 2 subscription", "Aion 2 pay to win"],
      sections: [
        section("model", "The Confirmed Model", ["Free-to-play is the base, confirmed again at Gamescom: no box price on the October 5 PC launch via Steam and PURPLE.", "Monetization is primarily cosmetics — the shop sells looks, not power, per the developers' framing.", "An optional subscription model adds monthly goodies on top of the free base; the 30-day membership is already bundled into Founder's Packs, so early access buyers get a first taste of it."]),
        section("in-game-unlocks", "Skins You Don't Pay For", ["A significant share of mount skins and outfits are unlockable purely through in-game content, not just the shop — so the paid store is not the only path to good-looking characters and mounts.", "This is consistent with Aion 2's exploration and anti-daily design: cosmetic rewards double as discovery rewards.", "Expect the exact split between shop and in-game cosmetics to be detailed closer to launch or during the September 17–18 launch scale test."]),
        section("p2w", "The Pay-to-Win Question", ["The write-up's biggest hope was that Aion 2 stays away from pay-to-win — in the author's view the single factor deciding whether it becomes a lasting game.", "Nothing in the Q&A indicates power being sold; vertical progression (levels and gear) was described as earned through content.", "The bound-Kina update in the Korean/Taiwanese live version already leans anti-RMT; global monetization may mirror that direction."]),
        section("what-it-means", "What It Means For You", ["Budget-wise, the realistic question is whether the optional membership is worth it for you — the monthly goodies it adds determine that, and Founder's Pack buyers can evaluate it during their 5-day early access.", "If cosmetics can be earned in-game, the shop becomes a convenience for impatient collectors rather than a requirement.", "Revisit this guide as NC details membership benefits and the shop lineup before launch."]),
      ],
    }),
    "zh-hans": articleCopy(guideLabels, "zh-hans", 4, {
      eyebrow: "经济与变现",
      title: "Aion 2 变现指南：免费游玩、外观优先与可选订阅",
      description: "Gamescom 2026 开发者问答阐明 Aion 2 的赚钱方式：免费游玩、以外观为主变现、带月度好物的可选订阅，且许多皮肤可在游戏内解锁。以下为完整图景。",
      intro: "Aion 2 的变现是上线前被问得最多的话题之一，Gamescom 2026 开发者问答给出了迄今最清晰的答案：游戏免费游玩，变现以外观为主，可选订阅补充月度好物，大量坐骑皮肤与外观可纯靠游戏内内容解锁。本指南汇总已确认信息及对你的花费（或不花费）意味着什么。",
      sourceNote: "基于 intheGame 的 Gamescom 2026 开发者问答（2026-08-29）与官方 Steam 创始人包内容展示，会员背景以 Aion 2 日本官网为准。",
      keywords: ["Aion 2 变现", "Aion 2 免费游玩", "Aion 2 外观", "Aion 2 订阅", "Aion 2 付费取胜"],
      sections: [
        section("model", "已确认的模型", ["免费游玩为基础，Gamescom 再次确认：10 月 5 日 PC 上线（Steam 与 PURPLE）无买断价。", "变现以外观为主——按开发方表述，商店卖的是外观而非强度。", "可选订阅在免费基础上补充月度好物；30 天会员已并入创始人包——抢先体验买家可先尝鲜。"]),
        section("in-game-unlocks", "无需付费的皮肤", ["相当一部分坐骑皮肤与外观可纯靠游戏内内容解锁——商店不是变好看的唯一路径。", "这与探索与反日常设计一致：外观奖励兼作发现奖励。", "商店与游戏内外观的确切比例预计在临近上线或 9 月 17-18 日上线规模测试时公布。"]),
        section("p2w", "付费取胜之问", ["报道最大的期望是 Aion 2 远离付费取胜——作者认为是决定它能否成为长寿游戏的唯一因素。", "问答中没有任何出售强度的迹象；垂直养成（等级与装备）被描述为通过内容获取。", "韩/台线上版的绑定基纳更新已倾向反 RMT；全球版变现可能镜像该方向。"]),
        section("what-it-means", "对你的意义", ["预算角度，现实问题是可选订阅是否值得——月度好物决定这点，创始人包买家可在 5 天抢先体验中评估。", "若外观可在游戏内获得，商店只是心急收藏者的便利而非必需。", "NC 上线前公布会员权益与商店清单后，请回访本指南。"]),
      ],
    }),
    ko: articleCopy(guideLabels, "ko", 4, {
      eyebrow: "경제와 수익화",
      title: "Aion 2 수익화 가이드: 기본 무료·코스메틱 중심·선택 구독",
      description: "Gamescom 2026 개발자 Q&A가 Aion 2의 수익화 방식을 밝혔습니다: 기본 무료, 코스메틱 중심, 월간 혜택의 선택 구독, 많은 스킨은 게임 내 해금. 전체 그림을 정리합니다.",
      intro: "게임은 기본 무료이고 수익화는 주로 코스메틱이며, 선택 구독이 월간 혜택을 더하고, 상당수의 탈것 스킨과 외형이 게임 내 콘텐츠로만 해금됩니다. 파운더스 팩에는 30일 멤버십이 포함됩니다.",
      sourceNote: "intheGame의 Gamescom 2026 개발자 Q&A(2026-08-29)와 공식 Steam 파운더스 팩 콘텐츠 소개, Aion 2 일본 공식 사이트의 멤버십 배경 기반.",
      keywords: ["Aion 2 수익화", "Aion 2 기본 무료", "Aion 2 코스메틱", "Aion 2 구독", "Aion 2 P2W"],
      sections: [
        section("model", "확인된 모델", "10월 5일 PC 출시(Steam/PURPLE)는 기본 무료. 수익화는 코스메틱 중심으로 '힘'이 아닌 '외모'를 판매. 선택 구독이 월간 혜택을 제공하며 30일 멤버십이 파운더스 팩에 포함."),
        section("in-game-unlocks", "돈 내지 않아도 되는 스킨", "상당수의 탈것 스킨·외형이 게임 내 콘텐츠로만 해금됩니다. 상점은 '예쁘게' 만드는 유일한 길이 아닙니다. 상점과 인게임 코스메틱의 정확한 비율은 LST(9/17~18) 전후에 공개될 전망."),
        section("p2w", "P2W 논쟁", "기사가 가장 바라는 점은 P2W 회피입니다. Q&A에서 힘을 판다는 신호는 없으며, 수직 성장은 콘텐츠로 얻는 것으로 설명됐습니다. 한/대만의 귀속 키나 업데이트도 반-RMT 방향입니다."),
        section("what-it-means", "의미", "선택 구독이 본인에게 가치 있는지가 실질 질문입니다. 인게임 해금이 많다면 상점은 필수가 아닌 편의입니다. 출시 전 멤버십 혜택 공개 후 업데이트하겠습니다."),
      ],
    }),
    ja: articleCopy(guideLabels, "ja", 4, {
      eyebrow: "経済と収益化",
      title: "Aion 2 収益化ガイド：基本無料・コスメ中心・任意サブスク",
      description: "Gamescom 2026 の開発者Q&Aが Aion 2 の収益化を明かしました：基本無料、コスメ中心、月間特典の任意サブスク、多くのスキンはゲーム内で解放。全体像をまとめます。",
      intro: "ゲームは基本無料で、収益化は主にコスメ。任意サブスクが月間特典を加え、多くのマウントスキンと外観がゲーム内コンテンツだけで解放されます。ファウンダーズパックには30日メンバーシップが含まれます。",
      sourceNote: "intheGame の Gamescom 2026 開発者Q&A（2026-08-29）と公式 Steam ファウンダーズパック紹介、日本公式サイトのメンバーシップ背景に基づきます。",
      keywords: ["Aion 2 収益化", "Aion 2 基本無料", "Aion 2 コスメ", "Aion 2 サブスク", "Aion 2 課金勝利"],
      sections: [
        section("model", "確認されたモデル", "10月5日のPC発売（Steam/PURPLE）は基本無料。収益化はコスメ中心で「見た目」を売る。任意サブスクが月間特典を提供し、30日メンバーシップがファウンダーズパックに含まれます。"),
        section("in-game-unlocks", "課金不要のスキン", "多くのマウントスキン・外観がゲーム内コンテンツだけで解放されます。ショップは見た目を良くする唯一の道ではありません。比率の詳細はLST（9/17〜18）前後に公開される見込みです。"),
        section("p2w", "課金勝利の論点", "記事が最も望むのはP2W回避です。Q&Aに強さの販売を示すものはなく、垂直成長はコンテンツで得ると説明されました。韓/台湾の帰属キナ更新も反RMT方向です。"),
        section("what-it-means", "意味", "任意サブスクが自分にとって価値があるかが実質的な問いです。インゲーム解放が多いならショップは必須ではなく利便性です。発売前の特典公開後に更新します。"),
      ],
    }),
    fr: articleCopy(guideLabels, "fr", 4, {
      eyebrow: "ÉCONOMIE & MONÉTISATION",
      title: "Guide de monétisation d'Aion 2 : free-to-play, cosmétiques et abonnement optionnel",
      description: "Le Q&A développeurs de Gamescom 2026 a détaillé la monétisation : free-to-play, cosmétiques, abonnement optionnel avec avantages mensuels, et beaucoup de skins déblocables en jeu.",
      intro: "Le Q&A développeurs de Gamescom 2026 a donné la réponse la plus claire à ce jour : free-to-play, monétisation principalement cosmétique, abonnement optionnel, et beaucoup de skins de montures/tenues déblocables en jeu.",
      sourceNote: "Basé sur le Q&A Gamescom 2026 d'intheGame (29 août 2026) et la présentation officielle Steam des packs Fondateur.",
      keywords: ["Aion 2 monétisation", "Aion 2 free to play", "Aion 2 cosmétiques", "Aion 2 abonnement"],
      sections: [
        section("model", "Le modèle confirmé", "Free-to-play, sortie PC le 5 octobre sans prix de boîte. Monétisation surtout cosmétique ; abonnement optionnel avec avantages mensuels ; 30 jours de membre inclus dans les packs Fondateur."),
        section("in-game-unlocks", "Skins sans payer", "Une grande part des skins est déblocable en jeu. Le shop n'est pas le seul chemin. Ratio exact à venir au LST des 17-18 septembre."),
        section("p2w", "La question pay-to-win", "L'espoir central de l'article : pas de P2W. Rien dans le Q&A ne vend de la puissance ; progression verticale gagnée par le contenu. La Kina liée en KR/TW penche déjà anti-RMT."),
        section("what-it-means", "Ce que ça change pour vous", "Question budgétaire : l'abonnement vaut-il ses avantages mensuels ? Les skins en jeu réduisent la pression de la boutique."),
      ],
    }),
    de: articleCopy(guideLabels, "de", 4, {
      eyebrow: "WIRTSCHAFT & MONETARISIERUNG",
      title: "Aion-2-Monetarisierungsguide: Free-to-play, Kosmetik & optionale Mitgliedschaft",
      description: "Das Gamescom-2026-Dev-Q&A legte die Monetarisierung dar: Free-to-play, Kosmetik-ledig, optionale Mitgliedschaft mit Monatsvorteilen, viele Skins im Spiel freischaltbar.",
      intro: "Das Gamescom-2026-Dev-Q&A gab die klarste Antwort: Free-to-play, hauptsächlich kosmetische Monetarisierung, optionale Mitgliedschaft, viele Mount-Skins/Outfits rein im Spiel freischaltbar.",
      sourceNote: "Basierend auf dem Gamescom-2026-Q&A von intheGame (29. August 2026) und der offiziellen Steam-Founder's-Pack-Vorstellung.",
      keywords: ["Aion 2 Monetarisierung", "Aion 2 Free to play", "Aion 2 Kosmetik", "Aion 2 Mitgliedschaft"],
      sections: [
        section("model", "Das bestätigte Modell", "Free-to-play, PC-Start am 5. Oktober ohne Kaufpreis. Monetarisierung vor allem kosmetisch; optionale Mitgliedschaft mit Monatsvorteilen; 30 Tage Mitgliedschaft in Founder's Packs enthalten."),
        section("in-game-unlocks", "Skins ohne Bezahlung", "Ein großer Teil der Skins ist im Spiel freischaltbar. Der Shop ist nicht der einzige Weg. Genaue Aufteilung beim LST (17.–18. September) erwartet."),
        section("p2w", "Die Pay-to-Win-Frage", "Größte Hoffnung: kein P2W. Nichts im Q&A verkauft Macht; vertikale Progression wird durch Inhalte verdient. Gebundenes Kina in KR/TW deutet anti-RMT."),
        section("what-it-means", "Was es für dich heißt", "Budgetfrage: lohnt die optionale Mitgliedschaft? In-Game-Skins nehmen den Druck aus dem Shop."),
      ],
    }),
    es: articleCopy(guideLabels, "es", 4, {
      eyebrow: "ECONOMÍA Y MONETIZACIÓN",
      title: "Guía de monetización de Aion 2: free-to-play, cosméticos y suscripción opcional",
      description: "El Q&A de desarrolladores de Gamescom 2026 detalló la monetización: free-to-play, cosméticos, suscripción opcional con ventajas mensuales y muchos skins desbloqueables en el juego.",
      intro: "El Q&A de desarrolladores de Gamescom 2026 dio la respuesta más clara: free-to-play, monetización principalmente cosmética, suscripción opcional y muchos skins de monturas/atuendos desbloqueables en el juego.",
      sourceNote: "Basado en el Q&A de Gamescom 2026 de intheGame (29 de agosto de 2026) y la presentación oficial de Steam de los packs de fundador.",
      keywords: ["Aion 2 monetización", "Aion 2 free to play", "Aion 2 cosméticos", "Aion 2 suscripción"],
      sections: [
        section("model", "El modelo confirmado", "Free-to-play, lanzamiento en PC el 5 de octubre sin precio de caja. Monetización sobre todo cosmética; suscripción opcional con ventajas mensuales; 30 días de membresía incluidos en los packs de fundador."),
        section("in-game-unlocks", "Skins sin pagar", "Gran parte de los skins se desbloquea en el juego. La tienda no es el único camino. Reparto exacto esperado en el LST del 17-18 de septiembre."),
        section("p2w", "La cuestión pay-to-win", "Mayor esperanza: sin P2W. Nada en el Q&A vende poder; la progresión vertical se gana con contenido. La Kina vinculada en KO/TW apunta anti-RMT."),
        section("what-it-means", "Qué significa para ti", "Cuestión presupuestaria: ¿vale la suscripción opcional? Los skins en el juego quitan presión a la tienda."),
      ],
    }),
    "pt-br": articleCopy(guideLabels, "pt-br", 4, {
      eyebrow: "ECONOMIA E MONETIZAÇÃO",
      title: "Guia de monetização do Aion 2: free-to-play, cosméticos e assinatura opcional",
      description: "O Q&A com desenvolvedores da Gamescom 2026 detalhou a monetização: free-to-play, cosméticos, assinatura opcional com vantagens mensais e muitos visuais desbloqueáveis no jogo.",
      intro: "O Q&A com desenvolvedores da Gamescom 2026 deu a resposta mais clara: free-to-play, monetização principalmente cosmética, assinatura opcional e muitos visuais de montarias/roupas desbloqueáveis no jogo.",
      sourceNote: "Com base no Q&A da Gamescom 2026 da intheGame (29 de agosto de 2026) e na apresentação oficial da Steam dos packs de fundador.",
      keywords: ["Aion 2 monetização", "Aion 2 free to play", "Aion 2 cosméticos", "Aion 2 assinatura"],
      sections: [
        section("model", "O modelo confirmado", "Free-to-play, lançamento no PC em 5 de outubro sem preço de caixa. Monetização sobretudo cosmética; assinatura opcional com vantagens mensais; 30 dias de assinatura incluídos nos packs de fundador."),
        section("in-game-unlocks", "Visuais sem pagar", "Grande parte dos visuais é desbloqueável no jogo. A loja não é o único caminho. Divisão exata esperada no LST de 17-18 de setembro."),
        section("p2w", "A questão pay-to-win", "Maior esperança: sem P2W. Nada no Q&A vende poder; a progressão vertical se ganha com conteúdo. A Kina vinculada em KO/TW aponta anti-RMT."),
        section("what-it-means", "O que significa para você", "Questão orçamentária: vale a assinatura opcional? Visuais no jogo tiram pressão da loja."),
      ],
    }),
    ru: articleCopy(guideLabels, "ru", 4, {
      eyebrow: "ЭКОНОМИКА И МОНЕТИЗАЦИЯ",
      title: "Гайд по монетизации Aion 2: free-to-play, косметика и опциональная подписка",
      description: "Q&A разработчиков Gamescom 2026 раскрыл монетизацию: free-to-play, косметика, опциональная подписка с месячными бонусами и много скинов, открываемых в игре.",
      intro: "Q&A разработчиков Gamescom 2026 дало самый ясный ответ: free-to-play, монетизация в основном косметическая, опциональная подписка и много скинов маунтов/нарядов, открываемых в игре.",
      sourceNote: "На основе Q&A Gamescom 2026 от intheGame (29 августа 2026) и официальной презентации Steam наборов основателя.",
      keywords: ["Aion 2 монетизация", "Aion 2 free to play", "Aion 2 косметика", "Aion 2 подписка"],
      sections: [
        section("model", "Подтверждённая модель", "Free-to-play, запуск на ПК 5 октября без цены коробки. Монетизация в основном косметическая; опциональная подписка с месячными бонусами; 30 дней членства в наборах основателя."),
        section("in-game-unlocks", "Скины без оплаты", "Большая часть скинов открывается в игре. Магазин — не единственный путь. Точное разделение ожидается на LST 17–18 сентября."),
        section("p2w", "Вопрос pay-to-win", "Главная надежда: без P2W. В Q&A нет продажи силы; вертикальный прогресс зарабатывается контентом. Связанная Кина в KO/TW указывает на анти-RMT."),
        section("what-it-means", "Что это значит для вас", "Бюджетный вопрос: стоит ли опциональная подписка? Скины в игре снимают давление магазина."),
      ],
    }),
    "zh-hant": articleCopy(guideLabels, "zh-hant", 4, {
      eyebrow: "經濟與變現",
      title: "Aion 2 變現指南：免費遊玩、外觀優先與可選訂閱",
      description: "Gamescom 2026 開發者問答闡明 Aion 2 的賺錢方式：免費遊玩、以外觀為主變現、帶月度好物的可選訂閱，且許多皮膚可在遊戲內解鎖。以下為完整圖景。",
      intro: "Aion 2 的變現是上線前被問得最多的話題之一，Gamescom 2026 開發者問答給出了迄今最清晰的答案：遊戲免費遊玩，變現以外觀為主，可選訂閱補充月度好物，大量坐騎皮膚與外觀可純靠遊戲內內容解鎖。本指南彙總已確認資訊及對你的花費（或不花費）意味著什麼。",
      sourceNote: "基於 intheGame 的 Gamescom 2026 開發者問答（2026-08-29）與官方 Steam 創始人包內容展示，會員背景以 Aion 2 日本官網為準。",
      keywords: ["Aion 2 變現", "Aion 2 免費遊玩", "Aion 2 外觀", "Aion 2 訂閱", "Aion 2 付費取勝"],
      sections: [
        section("model", "已確認的模型", ["免費遊玩為基礎，Gamescom 再次確認：10 月 5 日 PC 上線（Steam 與 PURPLE）無買斷價。", "變現以外觀為主——按開發方表述，商店賣的是外觀而非強度。", "可選訂閱在免費基礎上補充月度好物；30 天會員已併入創始人包——搶先體驗買家可先嚐鮮。"]),
        section("in-game-unlocks", "無需付費的皮膚", ["相當一部分坐騎皮膚與外觀可純靠遊戲內內容解鎖——商店不是變好看的唯一路徑。", "這與探索與反日常設計一致：外觀獎勵兼作發現獎勵。", "商店與遊戲內外觀的確切比例預計在臨近上線或 9 月 17-18 日上線規模測試時公布。"]),
        section("p2w", "付費取勝之問", ["報導最大的期望是 Aion 2 遠離付費取勝——作者認為是決定它能否成為長壽遊戲的唯一因素。", "問答中沒有任何出售強度的跡象；垂直養成（等級與裝備）被描述為透過內容獲取。", "韓/台線上版的綁定金納更新已傾向反 RMT；全球版變現可能鏡像該方向。"]),
        section("what-it-means", "對你的意義", ["預算角度，現實問題是可選訂閱是否值得——月度好物決定這點，創始人包買家可在 5 天搶先體驗中評估。", "若外觀可在遊戲內獲得，商店只是心急收藏者的便利而非必需。", "NC 上線前公布會員權益與商店清單後，請回訪本指南。"]),
      ],
    }),
  },
};