import { articleCopy, guideLabels, localizations, publishedVerified, section } from "./trending-september-8-shared";
import type { ContentEntry, ContentHeroImage, ContentSource } from "./content-registry";

/* ARTICLE 4 — Aion 2 global build QoL guide: no daily/weekly gates, smoothed progression, PvP optional, global livestreams */

const wfSource: ContentSource = {
  id: "wccftech-aion2-qa-2026-09-07",
  kind: "third-party",
  publisher: "Wccftech",
  label: "Aion 2 Q&A: Developers Discuss QoL, No Daily/Weekly Gates, and PvP Direction",
  url: "https://wccftech.com/aion-2-qa-dlss-5-console-cross-play/",
  publishedAt: "2026-09-07",
  retrievedAt: "2026-09-08",
  verifiedAt: "2026-09-08",
  localizations: localizations({
    "zh-hans": "Aion 2 Q&A：开发者谈 QoL、无日常/周常门槛与 PvP 方向",
    en: "Aion 2 Q&A: Developers Discuss QoL, No Daily/Weekly Gates, and PvP Direction",
    fr: "Aion 2 Q&R : les développeurs parlent QoL, absence de seuils quotidiens/hebdomadaires et direction PvP",
    de: "Aion 2 Q&A: Entwickler über QoL, keine Tages-/Wochen-Gates und PvP-Richtung",
    es: "Aion 2 Preguntas y respuestas: los desarrolladores hablan de QoL, sin límites diarios/semanales y la dirección PvP",
    ja: "Aion 2 Q&A：開発者がQoL・デイリー/ウィークリー制限なし・PvPの方針を語る",
    "pt-br": "Aion 2 Q&A: desenvolvedores falam sobre QoL, sem limites diários/semanais e direção do PvP",
    ru: "Aion 2 Q&A: разработчики о QoL, отсутствии ежедневных/еженедельных ограничений и направлении PvP",
    ko: "아이온2 Q&A: 개발진이 QoL·일일/주간 게이트 없음·PvP 방향을 설명",
    "zh-hant": "Aion 2 Q&A：開發者談 QoL、無日常/週常門檻與 PvP 方向",
  }, "https://wccftech.com/aion-2-qa-dlss-5-console-cross-play/"),
};

const steamSource: ContentSource = {
  id: "aion2-steam-store-2026-09-08",
  kind: "platform",
  publisher: "Steam",
  label: "AION 2 on Steam (Free to Play, Oct 5 2026)",
  url: "https://store.steampowered.com/app/3393110/AION_2/",
  publishedAt: "2026-08-26",
  retrievedAt: "2026-09-08",
  verifiedAt: "2026-09-08",
  localizations: localizations({
    "zh-hans": "Steam 上的 AION 2（免费游玩，2026-10-05）",
    en: "AION 2 on Steam (Free to Play, Oct 5 2026)",
    fr: "AION 2 sur Steam (free-to-play, 5 oct. 2026)",
    de: "AION 2 auf Steam (Free to Play, 5. Okt. 2026)",
    es: "AION 2 en Steam (gratuito, 5 oct 2026)",
    ja: "SteamのAION 2（基本無料、2026-10-05）",
    "pt-br": "AION 2 na Steam (gratuito, 5 out 2026)",
    ru: "AION 2 в Steam (бесплатная, 05.10.2026)",
    ko: "Steam의 AION 2 (부분 유료, 2026-10-05)",
    "zh-hant": "Steam 上的 AION 2（免費遊玩，2026-10-05）",
  }, "https://store.steampowered.com/app/3393110/AION_2/"),
};

const qolHero: ContentHeroImage = {
  src: "https://blogfiles.ncsoft.net/news/af7330da-4ff6-4b58-aece-400e6061a3be.jpg",
  width: 1200, height: 630,
  credit: "NC Corporation",
  sourceUrl: "https://aion2.plaync.com/en-us/",
  rights: "linked-official-media",
  translations: {
    "zh-hans": { alt: "Aion 2 全球版 QoL 指南横幅", caption: "开发团队确认全球版无日常/周常内容门槛、物品成长曲线已平滑化、PvP 改为可选，全球团队将定期直播听取反馈。" },
    en: { alt: "Aion 2 global QoL guide banner", caption: "The developers confirmed the global build has no daily/weekly content gates, smoothed item progression, optional PvP, and a global team that will livestream to hear player feedback." },
    fr: { alt: "Bannière du guide QoL global d'Aion 2", caption: "Les développeurs confirment : pas de seuils quotidiens/hebdomadaires, progression d'objets lissée, PvP optionnel, et une équipe globale qui diffusera en direct." },
    de: { alt: "Banner zum globalen QoL-Leitfaden von Aion 2", caption: "Die Entwickler bestätigen: keine Tages-/Wochen-Gates, geglättete Item-Progression, optionales PvP und ein globales Team mit regelmäßigen Livestreams." },
    es: { alt: "Banner de la guía QoL global de Aion 2", caption: "Los desarrolladores confirman: sin límites diarios/semanales, progresión de objetos suavizada, PvP opcional y un equipo global que hará livestreams." },
    ja: { alt: "Aion 2 グローバル版QoLガイドバナー", caption: "開発陣が確認：デイリー/ウィークリーのコンテンツ制限なし、アイテム成長のスムーズ化、PvPは任意参加、グローバルチームがライブ配信でフィードバックを収集。" },
    "pt-br": { alt: "Banner do guia de QoL global do Aion 2", caption: "Os desenvolvedores confirmam: sem limites diários/semanais, progressão de itens suavizada, PvP opcional e equipe global com livestreams." },
    ru: { alt: "Баннер гайда по QoL глобальной версии Aion 2", caption: "Разработчики подтверждают: без ежедневных/еженедельных ограничений, сглаженная прокачка предметов, необязательный PvP и глобальная команда с регулярными стримами." },
    ko: { alt: "Aion 2 글로벌 QoL 가이드 배너", caption: "개발진이 확인: 일일/주간 콘텐츠 게이트 없음, 아이템 성장 곡선의 유연화, PvP는 선택 참여, 피드백을 듣는 글로벌 라이브스트림 운영." },
    "zh-hant": { alt: "Aion 2 全球版 QoL 指南橫幅", caption: "開發團隊確認全球版無日常/週常內容門檻、物品成長曲線已平滑化、PvP 改為可選，全球團隊將定期直播聽取回饋。" },
  },
};

export const trendingSeptember8Article4: ContentEntry = {
  section: "guides",
  slug: "aion-2-global-qol-no-daily-gates-guide",
  schemaType: "Article",
  publishedAt: "2026-09-08",
  updatedAt: "2026-09-08",
  readingMinutes: 6,
  publication: publishedVerified,
  sources: [wfSource, steamSource],
  heroImage: qolHero,
  related: [
    { kind: "content", section: "guides", slug: "aion-2-no-autoplay-anti-grind-design-guide" },
    { kind: "content", section: "guides", slug: "aion-2-endgame-progression-roadmap" },
    { kind: "content", section: "guides", slug: "aion-2-global-version-changes-guide" },
    { kind: "content", section: "guides", slug: "aion-2-great-rebalance-patch-guide" },
  ],
  translations: {
    en: articleCopy(guideLabels, "en", 6, {
      eyebrow: "QOL GUIDE",
      title: "Aion 2 Global Build QoL Guide: No Daily or Weekly Gates, Smoothed Progression, PvP Optional",
      description: "What the developers confirmed about the global build's quality of life: no daily or weekly content gates, smoothed item progression, PvP as a choice, and regular global livestreams",
      intro: "In the September 7 Gamescom interview, the Aion 2 team spelled out how player feedback reshaped the global build: item progression was smoothed, quality-of-life features were added, daily and weekly content gates were removed, and PvP is being repositioned as optional — with a global team that plans to livestream regularly to keep listening.",
      sourceNote: "Based on Wccftech's September 7, 2026 interview with the Aion 2 team (Namjoon Kim and Andrew Long), cross-checked with the official Steam store page (retrieved September 8, 2026).",
      keywords: ["Aion 2 no daily weekly gates", "Aion 2 QoL global build", "Aion 2 smoothed item progression", "Aion 2 PvP optional", "Aion 2 global dev livestream"],
      sections: [
        section("no-content-gates", "No Daily or Weekly Content Gates", ["The most concrete QoL promise came from Namjoon Kim: 'We tried to minimize daily and weekly content. What I mean is that there's no daily or weekly content gate. You can come to the game whenever you want and enjoy however much of it you want.'", "That is a notable departure from the Korean service's early rhythm — and a direct answer to the 'second job' complaint that plagues many MMOs. Practically, it means no forced daily quest stack or weekly raid checklist you must complete to stay competitive."]),
        section("smoothed-progression", "Smoothed Item Progression", ["Kim described the first change since the Korean launch: item progression initially 'felt somewhat disconnected, a big chunk of progression, then another big chunk.' The team smoothed the connection 'so nothing is lost in the progression you've accumulated through to the end.'", "For players, this means gear upgrades should feel continuous rather than stair-stepped — relevant when planning the endgame path covered in the site's endgame progression roadmap."]),
        section("pvp-optional-direction", "PvP Becomes a Choice, Not a Requirement", ["On the PvP-versus-PvE question, Kim said the same trend seen in the West also exists in Korea: 'there are many more players who are PvE-oriented than PvP-oriented.'", "The team 'made the decision to minimise forcing people into PvP who don't want it. People can make a choice. If you want to participate, you can. If you don't, you don't have to.' That direction is confirmed going forward — a meaningful signal for players who were worried the faction war would be mandatory."]),
        section("global-livestreams", "The Global Team Will Livestream", ["Andrew Long described the global operation's feedback loop: 'One of the things the Korean team is really great at is weekly live streams where they listen to their players directly. The global team will emulate that model, so we'll be streaming and interacting with players.'", "Expect regular livestreams around launch — the September 17-18 Launch Scale Test is the first public checkpoint where feedback will be gathered."]),
        section("launch-checklist", "How to Use This Before October 5", ["1. Reassess time commitment: without daily/weekly gates, an irregular play schedule is viable — you are not punished for missing a reset; 2. Choose content by mood: PvE dungeons, Abyss PvP, or life skills are all legitimate paths and none are mandatory; 3. Use the LST on September 17-18 to test how the smoothed progression feels at low level; 4. Watch the global team's livestreams for the first live roadmap details; 5. If you quit a previous MMO over forced dailies, this design is worth a second look."]),
      ],
    }),
    "zh-hans": articleCopy(guideLabels, "zh-hans", 6, {
      eyebrow: "QoL 指南",
      title: "Aion 2 全球版 QoL 指南：无日常/周常门槛、成长曲线平滑、PvP 可选",
      description: "开发者确认的全球版品质优化内容：无日常/周常内容门槛、物品成长平滑化、PvP 变为选择、全球团队定期直播",
      intro: "在 9 月 7 日 Gamescom 专访中，Aion 2 团队阐述了玩家反馈如何重塑全球版：物品成长曲线平滑化、加入大量 QoL 功能、移除日常/周常内容门槛、PvP 改为可选——并有计划定期直播持续听取反馈的全球团队。",
      sourceNote: "基于 Wccftech 2026 年 9 月 7 日对 Aion 2 开发团队（金南俊与 Andrew Long）的专访，并与官方 Steam 商店页（2026-09-08 抓取）交叉核对。",
      keywords: ["Aion 2 无日常周常门槛", "Aion 2 全球版 QoL", "Aion 2 物品成长平滑", "Aion 2 PvP 可选", "Aion 2 全球开发者直播"],
      sections: [
        section("no-content-gates", "无日常/周常内容门槛", ["最具体的 QoL 承诺来自金南俊：「我们尽量精简日常与周常内容。我的意思是，没有日常或周常内容门槛。你想什么时候来都行，想玩多少就玩多少。」", "这是对韩服早期节奏的显著改变——也是对那些把 MMO 玩成「第二份工作」的抱怨的直接回应。实际意味着没有必须完成的日常任务堆或周常副本清单来维持竞争力。"]),
        section("smoothed-progression", "物品成长曲线平滑化", ["金南俊描述了韩服上线以来的第一项改动：物品成长最初「感觉断断续续，一大块成长，然后又一 大块」。团队将衔接处做平滑，「让你积累的成长在到达终点前不会丢失」。", "对玩家而言，装备升级应该连续而非阶梯式——规划终局路线时（见本站终局成长路线图）这点很相关。"]),
        section("pvp-optional-direction", "PvP 变为选择而非义务", ["关于 PvP 与 PvE 之争，金南俊表示西方出现的趋势在韩国同样存在：「PvE 向玩家比 PvP 向玩家多得多。」", "团队「决定尽量减少把不想打 PvP 的人推入 PvP。玩家可以做选择：想参与就参与，不想就不必。」该方向已确认将延续——对担心阵营战是强制内容的玩家是有意义的信号。"]),
        section("global-livestreams", "全球团队将直播", ["Andrew Long 描述了全球运营的反馈闭环：「韩国团队最擅长的事情之一就是每周直播直接听取玩家意见。全球团队将效仿这一模式，我们会直播并与玩家互动。」", "预计上线前后会有定期直播——9 月 17-18 日规模测试是首个公开收集反馈的检查点。"]),
        section("launch-checklist", "10 月 5 日前如何利用", ["1. 重新评估投入时间：没有日常/周常门槛，不规律的游玩节奏也可行——错过刷新不会受罚；2. 按心情选内容：PvE 副本、深渊 PvP 或生活技能都是正当路线，无一强制；3. 用 9 月 17-18 日 LST 测试低等级时平滑成长的实际手感；4. 关注全球团队直播，第一时间了解上线路线详情；5. 如果你曾因强制日常离开某款 MMO，这个设计值得再看一眼。"]),
      ],
    }),
    fr: articleCopy(guideLabels, "fr", 6, {
      eyebrow: "GUIDE QOL",
      title: "Guide QoL de la version globale d'Aion 2 : pas de seuils quotidiens/hebdomadaires, progression lissée, PvP optionnel",
      description: "Ce que les développeurs ont confirmé pour la version globale : pas de seuils quotidiens/hebdomadaires, progression d'objets lissée, PvP au choix, livestreams réguliers",
      intro: "Dans l'entretien du 7 septembre à la Gamescom, l'équipe d'Aion 2 a expliqué comment les retours des joueurs ont remodelé la version globale : progression d'objets lissée, fonctionnalités QoL ajoutées, seuils quotidiens/hebdomadaires supprimés, PvP repositionné en option — avec une équipe globale qui diffusera régulièrement.",
      sourceNote: "Basé sur l'entretien de Wccftech du 7 septembre 2026 avec l'équipe Aion 2 (Namjoon Kim et Andrew Long), recoupé avec la page Steam officielle (récupérée le 8 septembre 2026).",
      keywords: ["Aion 2 pas de seuils journaliers", "Aion 2 QoL version globale", "Aion 2 progression d'objets lissée", "Aion 2 PvP optionnel", "Aion 2 livestreams développeurs"],
      sections: [
        section("no-content-gates", "Pas de seuils quotidiens ou hebdomadaires", "Namjoon Kim : « Nous avons minimisé le contenu quotidien et hebdomadaire : il n'y a pas de seuil quotidien ou hebdomadaire. Venez quand vous voulez, jouez autant que vous voulez. » Un écart notable avec le rythme coréen initial — pas de pile de quêtes quotidiennes obligatoires."),
        section("smoothed-progression", "Progression d'objets lissée", "Kim : la progression « semblait déconnectée, un gros bloc, puis un autre » ; l'équipe a lissé la connexion « pour que rien ne soit perdu » — les montées d'équipement devraient être continues plutôt qu'en escalier."),
        section("pvp-optional-direction", "PvP : un choix, pas une obligation", "Kim : « plus de joueurs sont PvE que PvP, même en Corée » ; l'équipe « minimise le fait de forcer les gens vers le PvP. On peut choisir. » Direction confirmée pour l'avenir."),
        section("global-livestreams", "L'équipe globale diffusera", "Andrew Long : « L'équipe coréenne excelle dans les streams hebdomadaires où elle écoute les joueurs. L'équipe globale imitera ce modèle. » Attendez-vous à des streams réguliers autour du lancement."),
        section("launch-checklist", "Comment l'utiliser avant le 5 octobre", "1. Un planning irrégulier est viable sans seuils ; 2. Choisissez le contenu par envie (PvE, Abysse, métiers) ; 3. Testez la progression lissée au LST 17-18 septembre ; 4. Suivez les streams de l'équipe globale ; 5. Si vous avez quitté un MMO à cause des quotidiennes, ce design mérite un second regard."),
      ],
    }),
    de: articleCopy(guideLabels, "de", 6, {
      eyebrow: "QOL-LEITFADEN",
      title: "QoL-Leitfaden für die globale Version von Aion 2: keine Tages-/Wochen-Gates, geglättete Progression, PvP optional",
      description: "Was die Entwickler für die globale Version bestätigt haben: keine Tages-/Wochen-Gates, geglättete Item-Progression, PvP als Wahl, regelmäßige Livestreams",
      intro: "Im Gamescom-Interview vom 7. September erklärte das Aion-2-Team, wie Spieler-Feedback die globale Version geformt hat: geglättete Item-Progression, mehr QoL, keine Tages-/Wochen-Gates, und PvP wird als optional neu positioniert — mit einem globalen Team, das regelmäßig streamen will.",
      sourceNote: "Basierend auf dem Wccftech-Interview vom 7. September 2026 mit dem Aion-2-Team (Namjoon Kim und Andrew Long), abgeglichen mit der offiziellen Steam-Seite (abgerufen am 8. September 2026).",
      keywords: ["Aion 2 keine Tages Wochen Gates", "Aion 2 QoL globale Version", "Aion 2 geglättete Item-Progression", "Aion 2 PvP optional", "Aion 2 globale Livestreams"],
      sections: [
        section("no-content-gates", "Keine Tages- oder Wochen-Gates", "Namjoon Kim: „Wir haben tägliche und wöchentliche Inhalte minimiert — es gibt kein Tages- oder Wochen-Gate. Komm, wann du willst, spiel, wie viel du willst.“ Ein deutlicher Bruch mit dem frühen koreanischen Rhythmus; keine Pflicht-Dailies, um konkurrenzfähig zu bleiben."),
        section("smoothed-progression", "Geglättete Item-Progression", "Kim: Die Progression „fühlte sich abgehackt an, ein großer Block, dann ein weiterer“; das Team glättete die Verbindung, „damit nichts verloren geht“ — Ausrüstung sollte kontinuierlich statt treppenförmig wirken."),
        section("pvp-optional-direction", "PvP wird zur Wahl", "Kim: „Auch in Korea gibt es mehr PvE- als PvP-Spieler“; das Team „minimiert, Leute in PvP zu zwingen. Man kann wählen.“ Diese Richtung gilt auch künftig."),
        section("global-livestreams", "Das globale Team streamt", "Andrew Long: „Das koreanische Team ist großartig in wöchentlichen Streams, in denen es Spieler direkt hört. Das globale Team wird dieses Modell übernehmen.“ Rechne mit regelmäßigen Streams rund um den Launch."),
        section("launch-checklist", "So nutzt du das vor dem 5. Oktober", "1. Unregelmäßiges Spielen ist ohne Gates tragfähig; 2. Inhalt nach Laune wählen (PvE, Abyss, Berufe); 3. LST 17.-18. September zum Testen der geglätteten Progression nutzen; 4. Globale Livestreams für die ersten Roadmap-Details; 5. Wer wegen Pflicht-Dailies ein MMO verließ, sollte sich dieses Design ansehen."),
      ],
    }),
    es: articleCopy(guideLabels, "es", 6, {
      eyebrow: "GUÍA QOL",
      title: "Guía QoL de la versión global de Aion 2: sin límites diarios/semanales, progresión suavizada, PvP opcional",
      description: "Lo que confirmaron los desarrolladores para la versión global: sin límites diarios/semanales, progresión de objetos suavizada, PvP como elección y livestreams regulares",
      intro: "En la entrevista del 7 de septiembre en Gamescom, el equipo de Aion 2 explicó cómo los comentarios de los jugadores reformaron la versión global: progresión de objetos suavizada, funciones QoL añadidas, límites diarios/semanales eliminados y PvP reposicionado como opcional — con un equipo global que planea transmitir regularmente.",
      sourceNote: "Basado en la entrevista de Wccftech del 7 de septiembre de 2026 con el equipo de Aion 2 (Namjoon Kim y Andrew Long), cotejado con la página oficial de Steam (recuperada el 8 de septiembre de 2026).",
      keywords: ["Aion 2 sin límites diarios semanales", "Aion 2 QoL versión global", "Aion 2 progresión de objetos suavizada", "Aion 2 PvP opcional", "Aion 2 livestreams desarrolladores"],
      sections: [
        section("no-content-gates", "Sin límites diarios o semanales", "Namjoon Kim: «Minimizamos el contenido diario y semanal: no hay límite diario o semanal. Ven cuando quieras, juega cuanto quieras.» Un cambio notable frente al ritmo coreano inicial — sin pila de diarias obligatorias."),
        section("smoothed-progression", "Progresión de objetos suavizada", "Kim: la progresión «se sentía desconectada, un gran bloque y luego otro»; el equipo suavizó la conexión «para que nada se pierda» — las mejoras deberían sentirse continuas, no escalonadas."),
        section("pvp-optional-direction", "PvP: una elección, no una obligación", "Kim: «hay más jugadores PvE que PvP, incluso en Corea»; el equipo «minimiza forzar a la gente al PvP. Puedes elegir.» Dirección confirmada a futuro."),
        section("global-livestreams", "El equipo global transmitirá", "Andrew Long: «El equipo coreano es muy bueno en streams semanales donde escucha a los jugadores. El equipo global imitará ese modelo.» Espera streams regulares alrededor del lanzamiento."),
        section("launch-checklist", "Cómo usarlo antes del 5 de octubre", "1. Un horario irregular es viable sin límites; 2. Elige contenido por preferencia (PvE, Abismo, oficios); 3. Prueba la progresión suavizada en el LST 17-18 de septiembre; 4. Sigue los streams del equipo global; 5. Si dejaste un MMO por las diarias obligatorias, este diseño merece una segunda mirada."),
      ],
    }),
    ja: articleCopy(guideLabels, "ja", 6, {
      eyebrow: "QoLガイド",
      title: "Aion 2 グローバル版QoLガイド：デイリー/ウィークリー制限なし、成長曲線の平滑化、PvPは任意参加",
      description: "開発陣が確認したグローバル版のQoL内容：デイリー/ウィークリーのコンテンツ制限なし、アイテム成長の平滑化、PvPは選択制、定期ライブ配信",
      intro: "9月7日のGamescomインタビューでAion 2チームは、プレイヤーからのフィードバックがグローバル版をどう変えたかを説明しました：アイテム成長の平滑化、多数のQoL機能、デイリー/ウィークリー制限の撤廃、PvPを任意参加に——そして定期配信で意見を聞き続けるグローバルチームも明らかに。",
      sourceNote: "Wccftech 2026年9月7日付インタビュー（Aion 2チーム：김남준・Andrew Long）に基づき、公式Steamストアページ（2026-09-08取得）と照合。",
      keywords: ["Aion 2 デイリー ウィークリー なし", "Aion 2 グローバル QoL", "Aion 2 アイテム成長 平滑化", "Aion 2 PvP 任意参加", "Aion 2 開発ライブ配信"],
      sections: [
        section("no-content-gates", "デイリー/ウィークリー制限なし", "最も具体的なQoLの約束は김남준氏の言葉です：「デイリー・ウィークリーのコンテンツを最小化しました。つまりデイリー/ウィークリーのゲートはありません。好きなときに来て、好きなだけ遊べます。」韓国サービス初期のリズムからの明確な転換です。"),
        section("smoothed-progression", "アイテム成長の平滑化", "김남준氏：成長は当初「断片的に感じられた——大きな塊、そしてまた塊」。チームは「蓄積した成長が最後まで失われないよう」つなぎ目を滑らかにしました。"),
        section("pvp-optional-direction", "PvPは選択制へ", "김남준氏：「韓国でもPvPよりPvE志向のプレイヤーの方が多い」——チームは「望まない人をPvPに強制するのを最小化。参加したければ参加、したくなければ不要。」今後もこの方針です。"),
        section("global-livestreams", "グローバルチームが配信", "Andrew Long氏：「韓国チームの強みは毎週のライブ配信でプレイヤーの声を直接聞くこと。グローバルチームもこのモデルを踏襲し、配信で交流します。」ローンチ前後に定期配信が期待できます。"),
        section("launch-checklist", "10月5日までの活用法", "1. ゲートがないので不規則なプレイでも成立——リセットを逃しても罰せられません；2. 気分でコンテンツを選ぶ（PvE、アビス、生活スキル）——どれも必須ではない；3. 9月17-18日のLSTで低レベル帯の成長感を体感；4. グローバル配信で最初のロードマップ情報をチェック；5. 強制デイリーでMMOを離れた人こそ注目の設計です。"),
      ],
    }),
    "pt-br": articleCopy(guideLabels, "pt-br", 6, {
      eyebrow: "GUIA DE QOL",
      title: "Guia de QoL da versão global do Aion 2: sem limites diários/semanais, progressão suavizada, PvP opcional",
      description: "O que os desenvolvedores confirmaram para a versão global: sem limites diários/semanais, progressão de itens suavizada, PvP como escolha e livestreams regulares",
      intro: "Na entrevista de 7 de setembro na Gamescom, a equipe do Aion 2 explicou como o feedback dos jogadores reformulou a versão global: progressão de itens suavizada, recursos de QoL adicionados, limites diários/semanais removidos e PvP reposicionado como opcional — com uma equipe global que planeja fazer livestreams regularmente.",
      sourceNote: "Baseado na entrevista da Wccftech de 7 de setembro de 2026 com a equipe do Aion 2 (Namjoon Kim e Andrew Long), cruzado com a página oficial da Steam (acessada em 8 de setembro de 2026).",
      keywords: ["Aion 2 sem limites diários semanais", "Aion 2 QoL versão global", "Aion 2 progressão de itens suavizada", "Aion 2 PvP opcional", "Aion 2 livestreams desenvolvedores"],
      sections: [
        section("no-content-gates", "Sem limites diários ou semanais", "Namjoon Kim: «Minimizamos o conteúdo diário e semanal: não há limite diário ou semanal. Venha quando quiser, jogue o quanto quiser.» Uma mudança notável ante o ritmo coreano inicial — sem pilha de dailies obrigatórias."),
        section("smoothed-progression", "Progressão de itens suavizada", "Kim: a progressão «parecia desconectada, um grande bloco e depois outro»; a equipe suavizou a conexão «para que nada se perca» — upgrades devem parecer contínuos, não em degraus."),
        section("pvp-optional-direction", "PvP: uma escolha, não uma obrigação", "Kim: «há mais jogadores PvE do que PvP, até na Coreia»; a equipe «minimiza forçar as pessoas ao PvP. Você pode escolher.» Direção confirmada para o futuro."),
        section("global-livestreams", "A equipe global vai transmitir", "Andrew Long: «O time coreano é ótimo em livestreams semanais onde escuta os jogadores. A equipe global vai imitar esse modelo.» Espere streams regulares em torno do lançamento."),
        section("launch-checklist", "Como usar antes de 5 de outubro", "1. Um horário irregular é viável sem limites; 2. Escolha conteúdo por preferência (PvE, Abismo, ofícios); 3. Teste a progressão suavizada no LST 17-18 de setembro; 4. Acompanhe os livestreams da equipe global; 5. Se você deixou um MMO por causa de dailies obrigatórias, este design merece uma segunda olhada."),
      ],
    }),
    ru: articleCopy(guideLabels, "ru", 6, {
      eyebrow: "ГАЙД ПО QOL",
      title: "Гайд по QoL глобальной версии Aion 2: без ежедневных/еженедельных ограничений, сглаженная прокачка, необязательный PvP",
      description: "Что разработчики подтвердили для глобальной версии: без ежедневных/еженедельных ограничений, сглаженная прокачка предметов, PvP по выбору, регулярные стримы",
      intro: "В интервью 7 сентября на Gamescom команда Aion 2 объяснила, как отзывы игроков изменили глобальную версию: сглаженная прокачка предметов, добавлены функции QoL, убраны ежедневные/еженедельные ограничения, а PvP переводится в разряд опционального — плюс глобальная команда планирует регулярно стримить.",
      sourceNote: "На основе интервью Wccftech от 7 сентября 2026 г. с командой Aion 2 (Намджун Ким и Эндрю Лонг), сверено с официальной страницей Steam (получена 8 сентября 2026 г.).",
      keywords: ["Aion 2 без ежедневных еженедельных", "Aion 2 QoL глобальная версия", "Aion 2 сглаженная прокачка", "Aion 2 PvP необязательный", "Aion 2 стримы разработчиков"],
      sections: [
        section("no-content-gates", "Без ежедневных или еженедельных ограничений", "Намджун Ким: «Мы минимизировали ежедневный и еженедельный контент: нет ежедневного или еженедельного гейта. Приходите, когда хотите, играйте сколько хотите». Заметный разрыв с ранним корейским ритмом — никаких обязательных дейликов."),
        section("smoothed-progression", "Сглаженная прокачка предметов", "Ким: прокачка «ощущалась отрывистой — большой блок, потом ещё один»; команда сгладила переходы, «чтобы ничего не терялось» — апгрейды должны ощущаться непрерывными."),
        section("pvp-optional-direction", "PvP: выбор, а не обязанность", "Ким: «PvE-игроков больше, чем PvP, даже в Корее»; команда «минимизирует принуждение к PvP. Можно выбирать». Направление подтверждено на будущее."),
        section("global-livestreams", "Глобальная команда будет стримить", "Эндрю Лонг: «Корейская команда сильна в еженедельных стримах, где напрямую слушает игроков. Глобальная команда повторит эту модель». Ждите регулярных стримов вокруг запуска."),
        section("launch-checklist", "Как использовать до 5 октября", "1. Без гейтов возможен нерегулярный график — пропуск ресета не наказывается; 2. Выбирайте контент по настроению (PvE, Бездна, профессии); 3. Протестируйте сглаженную прокачку в LST 17–18 сентября; 4. Смотрите стримы глобальной команды; 5. Если вы ушли из MMO из-за обязательных дейликов, этот дизайн стоит второго взгляда."),
      ],
    }),
    ko: articleCopy(guideLabels, "ko", 6, {
      eyebrow: "QoL 가이드",
      title: "아이온2 글로벌 QoL 가이드: 일일/주간 게이트 없음, 성장 곡선의 유연화, PvP는 선택 참여",
      description: "개발진이 확인한 글로벌 버전의 QoL 내용: 일일/주간 콘텐츠 게이트 없음, 아이템 성장의 유연화, PvP는 선택제, 정기 라이브 방송",
      intro: "9월 7일 Gamescom 인터뷰에서 아이온2 팀은 플레이어 피드백이 글로벌 버전을 어떻게 바꿨는지 설명했습니다: 아이템 성장 곡선의 유연화, 다수의 QoL 기능 추가, 일일/주간 게이트 철폐, PvP를 선택제로——그리고 정기 방송으로 의견을 계속 듣겠다는 글로벌 팀도 확인됐습니다.",
      sourceNote: "Wccftech 2026년 9월 7일 인터뷰(아이온2 팀: 김남준·Andrew Long)를 기반으로, 공식 Steam 스토어 페이지(2026-09-08 확인)와 교차 검증했습니다.",
      keywords: ["아이온2 일일 주간 게이트 없음", "아이온2 글로벌 QoL", "아이온2 아이템 성장 유연화", "아이온2 PvP 선택", "아이온2 개발진 라이브 방송"],
      sections: [
        section("no-content-gates", "일일/주간 콘텐츠 게이트 없음", "가장 구체적인 QoL 약속은 김남준 디렉터의 발언입니다: \"일일·주간 콘텐츠를 최소화했습니다. 즉 일일/주간 게이트가 없습니다. 원할 때 와서, 원하는 만큼 즐기면 됩니다.\" 한국 서비스 초기 리듬과의 확실한 단절이며, '제2의 직장'식 강제 일퀘 스택이 사라졌다는 뜻입니다."),
        section("smoothed-progression", "아이템 성장의 유연화", "김남준 디렉터: 성장이 처음에는 \"단절된 느낌——큰 덩어리, 그리고 또 덩어리\"였는데, 팀이 \"끝까지 쌓은 성장이 유실되지 않도록\" 연결을 매끄럽게 만들었습니다. 장비 강화가 계단식이 아니라 연속적으로 느껴지도록 한 것입니다."),
        section("pvp-optional-direction", "PvP는 선택이지 의무가 아님", "김남준 디렉터: \"한국에서도 PvP보다 PvE 지향 플레이어가 훨씬 많습니다\"——팀은 \"원하지 않는 사람을 PvP로 몰아넣는 것을 최소화했습니다. 참여하고 싶으면 하고, 싫으면 안 해도 됩니다.\" 이 방향은 앞으로도 유지됩니다."),
        section("global-livestreams", "글로벌 팀이 라이브 방송", "Andrew Long: \"한국 팀의 강점 중 하나는 매주 라이브 방송으로 플레이어 의견을 직접 듣는 것입니다. 글로벌 팀도 이 모델을 따를 것입니다.\" 출시 전후로 정기 방송이 이어질 전망입니다."),
        section("launch-checklist", "10월 5일 전 활용법", "1. 게이트가 없으니 불규칙한 플레이도 성립——리셋을 놓쳐도 불이익 없음; 2. 기분에 따라 콘텐츠 선택(PvE 던전, 아비스 PvP, 생활 스킬)——어느 것도 필수 아님; 3. 9월 17-18일 LST에서 저레벨 성장감을 직접 테스트; 4. 글로벌 팀 라이브 방송으로 첫 로드맵 정보 확인; 5. 강제 일퀘 때문에 MMO를 떠났다면, 이 설계는 다시 볼 가치가 있습니다."),
      ],
    }),
    "zh-hant": articleCopy(guideLabels, "zh-hant", 6, {
      eyebrow: "QoL 指南",
      title: "Aion 2 全球版 QoL 指南：無日常/週常門檻、成長曲線平滑、PvP 可選",
      description: "開發者確認的全球版品質優化內容：無日常/週常內容門檻、物品成長平滑化、PvP 變為選擇、全球團隊定期直播",
      intro: "在 9 月 7 日 Gamescom 專訪中，Aion 2 團隊闡述了玩家回饋如何重塑全球版：物品成長曲線平滑化、加入大量 QoL 功能、移除日常/週常內容門檻、PvP 改為可選——並有計畫定期直播持續聽取回饋的全球團隊。",
      sourceNote: "基於 Wccftech 2026 年 9 月 7 日對 Aion 2 開發團隊（金南俊與 Andrew Long）的專訪，並與官方 Steam 商店頁（2026-09-08 抓取）交叉核對。",
      keywords: ["Aion 2 無日常週常門檻", "Aion 2 全球版 QoL", "Aion 2 物品成長平滑", "Aion 2 PvP 可選", "Aion 2 全球開發者直播"],
      sections: [
        section("no-content-gates", "無日常/週常內容門檻", ["最具體的 QoL 承諾來自金南俊：「我們盡量精簡日常與週常內容。我的意思是，沒有日常或週常內容門檻。你想什麼時候來都行，想玩多少就玩多少。」", "這是對韓服早期節奏的顯著改變——也是對那些把 MMO 玩成「第二份工作」的抱怨的直接回應。實際意味著沒有必須完成的日常任務堆或週常副本清單來維持競爭力。"]),
        section("smoothed-progression", "物品成長曲線平滑化", ["金南俊描述了韓服上線以來的第一項改動：物品成長最初「感覺斷斷續續，一大塊成長，然後又一大塊」。團隊將銜接處做平滑，「讓你累積的成長在到達終點前不會丟失」。", "對玩家而言，裝備升級應該連續而非階梯式——規劃終局路線時（見本站終局成長路線圖）這點很相關。"]),
        section("pvp-optional-direction", "PvP 變為選擇而非義務", ["關於 PvP 與 PvE 之爭，金南俊表示西方出現的趨勢在韓國同樣存在：「PvE 向玩家比 PvP 向玩家多得多。」", "團隊「決定盡量減少把不想打 PvP 的人推入 PvP。玩家可以做選擇：想參與就參與，不想就不必。」該方向已確認將延續——對擔心陣營戰是強制內容的玩家是有意義的訊號。"]),
        section("global-livestreams", "全球團隊將直播", ["Andrew Long 描述了全球營運的回饋閉環：「韓國團隊最擅長的事情之一就是每週直播直接聽取玩家意見。全球團隊將效仿這一模式，我們會直播並與玩家互動。」", "預計上線前後會有定期直播——9 月 17-18 日規模測試是首個公開收集回饋的檢查點。"]),
        section("launch-checklist", "10 月 5 日前如何利用", ["1. 重新評估投入時間：沒有日常/週常門檻，不規律的遊玩節奏也可行——錯過刷新不會受罰；2. 按心情選內容：PvE 副本、深淵 PvP 或生活技能都是正當路線，無一強制；3. 用 9 月 17-18 日 LST 測試低等級時平滑成長的實際手感；4. 關注全球團隊直播，第一時間了解上線路線詳情；5. 如果你曾因強制日常離開某款 MMO，這個設計值得再看一眼。"]),
      ],
    }),
  },
};
