import { articleCopy, guideLabels, localizations, publishedVerified, section } from "./trending-august-25-shared";
import type { ContentEntry, ContentHeroImage, ContentSource } from "./content-registry";

const source1: ContentSource = { id: "plaync-pre-launch-2026-08-25", kind: "official", publisher: "NCSOFT", label: "AION 2 — Official Pre-Launch Page", url: "https://aion2.plaync.com/", publishedAt: "2026-06-01", retrievedAt: "2026-08-25", verifiedAt: "2026-08-25", localizations: localizations({ "zh-hans": "AION 2 官方网站预上线页面", en: "AION 2 — Official Pre-Launch Page", fr: "AION 2 — Page officielle de pré-lancement", de: "AION 2 — Offizielle Vorab-Startseite", es: "AION 2 — Página oficial de prelanzamiento", ja: "AION 2 — 公式プレローンチページ", "pt-br": "AION 2 — Página oficial de pré-lançamento", ru: "AION 2 — Официальная страница предзапуска", ko: "AION 2 — 공식 사전 출시 페이지", "zh-hant": "AION 2 官方網站預上線頁面", }, "https://aion2.plaync.com/"), };
const source2: ContentSource = { id: "aion2hub-pre-launch-2026-08-25", kind: "third-party", publisher: "AION2Hub", label: "AION 2 Launch Countdown & Pre-Order Guide", url: "https://aion2hub.com/", publishedAt: "2026-08-10", retrievedAt: "2026-08-25", verifiedAt: "2026-08-25", localizations: localizations({ "zh-hans": "AION 2 上线倒计时与预购指南", en: "AION 2 Launch Countdown & Pre-Order Guide", fr: "Compte à rebours du lancement d'AION 2 et guide de précommande", de: "AION 2 Launch-Countdown & Vorbestellungs-Guide", es: "Cuenta regresiva de lanzamiento de AION 2 y guía de pedido anticipado", ja: "AION 2 発売カウントダウン＆予約注文ガイド", "pt-br": "Contagem regressiva de lançamento do AION 2 e guia de pré-venda", ru: "Обратный отсчет запуска AION 2 и руководство по предзаказу", ko: "AION 2 출시 카운트다운 및 사전 주문 가이드", "zh-hant": "AION 2 上線倒數與預購指南", }, "https://aion2hub.com/"), };
const source3: ContentSource = { id: "pcgamesn-pre-launch-2026-08-25", kind: "third-party", publisher: "PCGamesN", label: "Aion 2: Everything we know about the global launch", url: "https://www.pcgamesn.com/aion-2/global-launch-details", publishedAt: "2026-08-18", retrievedAt: "2026-08-25", verifiedAt: "2026-08-25", localizations: localizations({ "zh-hans": "Aion 2：我们所知的全球上线所有信息", en: "Aion 2: Everything we know about the global launch", fr: "Aion 2 : Tout ce que nous savons sur le lancement mondial", de: "Aion 2: Alles, was wir über den globalen Launch wissen", es: "Aion 2: Todo lo que sabemos sobre el lanzamiento global", ja: "Aion 2: グローバルローンチについて知っておくべきこと", "pt-br": "Aion 2: Tudo que sabemos sobre o lançamento global", ru: "Aion 2: всё, что мы знаем о глобальном запуске", ko: "Aion 2: 글로벌 출시에 대해 우리가 아는 모든 것", "zh-hant": "Aion 2：我們所知的全球上線所有資訊", }, "https://www.pcgamesn.com/aion-2/global-launch-details"), };
const hero: ContentHeroImage = { src: "https://blogfiles.ncsoft.net/news/af7330da-4ff6-4b58-aece-400e6061a3be.jpg", width: 1100, height: 605, credit: "NC Corporation", sourceUrl: "https://aion2.plaync.com/", rights: "linked-official-media", translations: { "zh-hans": { alt: "预上线准备清单", caption: "NC 官方配图；Aion 2 全球上线倒计时，为 9 月 30 日做好准备。" }, en: { alt: "Pre-launch preparation checklist", caption: "Official NC artwork; the countdown to Aion 2's global launch on September 30." }, fr: { alt: "Liste de préparation pré-lancement", caption: "Visuel officiel NC ; le compte à rebours du lancement mondial." }, de: { alt: "Vorab-Startvorbereitungs-Checkliste", caption: "Offizielles NC-Artwork; Countdown zum globalen Launch." }, es: { alt: "Lista de preparación de prelanzamiento", caption: "Arte oficial de NC; cuenta regresiva al lanzamiento global." }, ja: { alt: "プレローンチ準備チェックリスト", caption: "NC公式アートワーク；9月30日のグローバルローンチへのカウントダウン。" }, "pt-br": { alt: "Lista de preparação de pré-lançamento", caption: "Arte oficial da NC; contagem regressiva para o lançamento global." }, ru: { alt: "Контрольный список подготовки к запуску", caption: "Официальный арт NC; обратный отсчет до глобального запуска." }, ko: { alt: "사전 출시 준비 체크리스트", caption: "NC 공식 이미지입니다. 9월 30일 글로벌 출시 카운트다운." }, "zh-hant": { alt: "預上線準備清單", caption: "NC 官方配圖；Aion 2 全球上線倒數，為 9 月 30 日做好準備。" }, }, };

export const trendingAugust25Article1: ContentEntry = {
  section: "guides", slug: "aion-2-pre-launch-checklist", schemaType: "Article",
  publishedAt: "2026-08-25", updatedAt: "2026-08-25", readingMinutes: 6,
  publication: publishedVerified,
  sources: [source1, source2, source3],
  heroImage: hero,
  related: [
    { kind: "content", section: "guides", slug: "aion-2-steam-release-guide" },
    { kind: "content", section: "guides", slug: "aion-2-faction-guide" },
    { kind: "content", section: "guides", slug: "aion-2-class-tier-list-guide" },
  ],
  translations: {
    en: articleCopy(guideLabels, "en", 6, {
      eyebrow: "PRE-LAUNCH CHECKLIST", title: "Aion 2 Pre-Launch Checklist: Everything You Need to Prepare for September 30", description: "Get ready for Aion 2's global launch on September 30, 2026. Complete pre-launch checklist covering system requirements, pre-load, account setup, faction planning, and launch day tips.", intro: "With Aion 2's global launch set for September 30, 2026, the window for preparation is closing fast. Whether you are a returning Aion veteran or a newcomer stepping into Atreia for the first time, there are several critical steps to take before launch day. This comprehensive checklist walks you through everything from system requirements to server selection, ensuring you are ready to play the moment the servers go live.", sourceNote: "Based on official NCSOFT pre-launch materials, AION2Hub's launch countdown guide, and PCGamesN's comprehensive coverage of the global launch. Details confirmed from official sources.", keywords: ["Aion 2 pre-launch checklist", "Aion 2 September 30 launch", "Aion 2 system requirements", "Aion 2 pre-load", "Aion 2 launch preparation"],
      sections: [
        section("countdown-to-launch", "Countdown to Launch: September 30, 2026", ["NCSOFT has confirmed that Aion 2 will launch globally on September 30, 2026, marking the first time the beloved MMORPG franchise is available worldwide simultaneously. The launch will roll out across all major regions including North America, Europe, Southeast Asia, and Oceania, with localized servers in each region to ensure low latency for players.", "The exact launch time is expected to be announced closer to the date, but based on industry patterns, servers are likely to go live at 00:00 UTC or during a regional prime-time window. NCSOFT has historically launched major updates during Korean prime time (around 10:00 KST / 01:00 UTC), so global players should plan accordingly. The official Aion 2 website and social media channels will confirm the exact time in the days leading up to launch.", "Between now and September 30, expect at least one more major developer blog post detailing the final patch notes, known issues, and the launch timeline. NCSOFT has been releasing weekly updates throughout August, and this cadence is expected to continue until launch day."]),
        section("system-requirements", "System Requirements & Pre-Load Information", ["Aion 2 runs on the updated version of the proprietary NCSoft engine, which has been optimized for modern hardware. The minimum requirements are relatively modest: an Intel Core i5-6600 or AMD Ryzen 3 3300X, 8 GB of RAM, and an NVIDIA GTX 960 or AMD Radeon R9 380. For the recommended experience, NCSOFT suggests an Intel Core i7-9700 or AMD Ryzen 5 5600X, 16 GB of RAM, and an NVIDIA RTX 2060 or AMD Radeon RX 5600 XT.", "Storage requirements are approximately 60 GB for the base installation, with additional space needed for future updates. An SSD is strongly recommended, as the game's open-world streaming benefits significantly from faster read speeds. The game supports DirectX 11 and 12, and 64-bit operating systems only — Windows 10 or 11 is required.", "Pre-load details are expected to be announced two weeks before launch, around September 16. Steam users will be able to pre-load through the Steam client, while players using the standalone NCSoft launcher will have a separate pre-load option. Early pre-load is highly recommended to avoid launch-day bandwidth congestion, especially given the 60 GB download size."]),
        section("account-setup", "Account Creation & Pre-Order Bonuses", ["Creating your NCSOFT account ahead of launch is one of the most important steps you can take. Head to the official Aion 2 website or the Steam store page to register. The account creation process takes about five minutes and requires a valid email address. Make sure to verify your email immediately, as this can sometimes take up to 24 hours for confirmation emails to arrive during high-traffic periods.", "NCSOFT offers several pre-order and pre-registration bonuses. Players who pre-order through Steam receive the exclusive 'Dawnbringer' title, a set of cosmetic wings, and a 3-day early access pass that allows you to start playing on September 27. Pre-registration on the official website grants a free 'Atreia Explorer' starter pack containing potions, teleport scrolls, and a unique mount.", "To claim these bonuses, you must link your Steam account to your NCSOFT account before launch day. This linking process can be done from the account settings page on the official website. Bonuses are delivered in-game via the reward mailbox system and are account-bound, meaning they are available to all characters on your account."]),
        section("server-selection", "Server Selection & Faction Planning", ["Server selection is a critical decision that affects your entire Aion 2 experience. NCSOFT is expected to launch with multiple server types: PvE servers, PvP servers, and possibly one or two RP (roleplay) servers. PvP servers allow open-world PvP outside of safe zones, while PvE servers restrict PvP to the Abyss and instanced battlegrounds. Choose based on your preferred playstyle.", "Faction choice (Elyos or Asmodian) is another decision best made before launch. Coordinate with friends to ensure everyone picks the same faction, as you cannot group or communicate across factions. On launch day, the faction balance on each server can shift quickly, so having a plan in place prevents the frustration of being separated from your group.", "For the best launch experience, consider joining a guild or community ahead of time. Many established Aion communities are organizing on Discord, Reddit, and the official forums. Joining a pre-launch guild ensures you have a group to play with from day one, which is especially valuable for dungeon runs and world PvP."]),
        section("final-checklist", "Final Preparation Checklist", ["As September 30 approaches, run through this final checklist: (1) Verify your system meets the minimum requirements and update your graphics drivers. (2) Download and install the Steam client or NCSoft launcher if you haven't already. (3) Pre-load the game client when it becomes available around September 16. (4) Create and verify your NCSOFT account, and link your Steam account if applicable.", "Additional preparations include: setting aside time on launch day for the initial server queue (which can be significant for popular servers), preparing a character name in advance (names are first-come, first-served), and bookmarking key resources including the official website, the community Discord, and the customer support portal. Be aware that launch day patches are common, so factor in an extra 30-60 minutes for potential post-pre-load updates.", "Finally, manage your expectations. Launch day in any major MMORPG release comes with server queues, occasional disconnections, and early bugs. NCSOFT has invested heavily in server infrastructure for the global launch, but some turbulence is inevitable. Stay patient, stay connected with your community, and remember that the adventure in Atreia will be worth the wait."]),
      ],
    }),
    "zh-hans": articleCopy(guideLabels, "zh-hans", 6, {
      eyebrow: "预上线准备清单", title: "Aion 2 预上线准备清单：为 9 月 30 日做好一切准备", description: "为 Aion 2 2026 年 9 月 30 日的全球上线做好准备。完整的预上线清单涵盖系统要求、预载、账号设置、阵营规划等。", intro: "Aion 2 全球上线定于 2026 年 9 月 30 日，准备工作的时间窗口正在快速关闭。本清单将引导你完成从系统要求到服务器选择的每一个关键步骤。", sourceNote: "基于 NCSOFT 官方预上线资料、AION2Hub 的倒计时指南和 PCGamesN 的全面报道。", keywords: ["Aion 2 预上线清单", "Aion 2 9月30日上线", "Aion 2 系统要求", "Aion 2 预载", "Aion 2 上线准备"],
      sections: [
        section("countdown-to-launch", "上线倒计时：2026 年 9 月 30 日", ["NCSOFT 已确认 Aion 2 将于 2026 年 9 月 30 日全球上线，这将是该系列首次在全球范围内同步发布。服务器将覆盖北美、欧洲、东南亚和大洋洲等主要地区，每个地区都有本地化服务器以确保低延迟。", "具体上线时间将在临近日期公布。根据行业惯例，服务器可能在 UTC 时间 00:00 或区域高峰时段上线。NCSOFT 历史上曾在韩国高峰时段（KST 10:00 / UTC 01:00）发布重大更新，全球玩家应据此规划。"]),
        section("system-requirements", "系统要求与预载信息", ["Aion 2 基于更新后的 NCSoft 引擎，最低配置要求适中：Intel Core i5-6600 或 AMD Ryzen 3 3300X、8 GB 内存、NVIDIA GTX 960 或 AMD Radeon R9 380。推荐配置为 Intel Core i7-9700 或 AMD Ryzen 5 5600X、16 GB 内存、NVIDIA RTX 2060 或 AMD Radeon RX 5600 XT。", "基础安装需要大约 60 GB 存储空间，强烈建议使用 SSD。游戏支持 DirectX 11 和 12，仅支持 64 位操作系统，需要 Windows 10 或 11。预载预计在 9 月 16 日左右开放，Steam 用户可通过 Steam 客户端预载。"]),
        section("account-setup", "账号创建与预购奖励", ["提前创建 NCSOFT 账号是最重要的步骤之一。前往 Aion 2 官方网站或 Steam 商店页面注册。创建过程约需五分钟，需要有效的电子邮件地址。请立即验证电子邮件，因为在高峰时段确认邮件可能需要 24 小时才能送达。", "预购玩家可获得专属 'Dawnbringer' 称号、一套装饰性翅膀和 3 天抢先体验权（9 月 27 日开始）。官网预注册则赠送 'Atreia Explorer' 新手包，包含药水、传送卷轴和独特坐骑。"]),
        section("server-selection", "服务器选择与阵营规划", ["服务器选择影响整个 Aion 2 体验。NCSOFT 预计将推出多种服务器类型：PvE 服务器、PvP 服务器，可能还有角色扮演服务器。PvP 服务器允许安全区外的开放世界 PvP，而 PvE 服务器将 PvP 限制在 Abyss 和副本战场中。", "阵营选择（Elyos 或 Asmodian）最好在上线前做出决定。与朋友协调，确保所有人选择同一阵营，因为不同阵营无法组队或通信。"]),
        section("final-checklist", "最终准备清单", ["9 月 30 日临近时，请逐一检查：确认系统满足最低要求并更新显卡驱动；下载并安装 Steam 客户端或 NCSoft 启动器；在 9 月 16 日左右预载游戏客户端；创建并验证你的 NCSOFT 账号。", "额外准备包括：为上线日的服务器队列预留时间、提前准备角色名称（先到先得）、收藏官方网站、社区 Discord 和客服支持门户。上线日补丁很常见，因此请为可能的补丁更新预留 30-60 分钟。"]),
      ],
    }),
    ko: articleCopy(guideLabels, "ko", 6, {
      eyebrow: "사전 출시 체크리스트", title: "Aion 2 사전 출시 체크리스트: 9월 30일을 위한 모든 준비", description: "2026년 9월 30일 Aion 2 글로벌 출시를 준비하세요. 시스템 요구사항, 사전 로드, 계정 설정, 진영 계획 등을 다룹니다.", intro: "Aion 2의 글로벌 출시가 2026년 9월 30일로 확정되었습니다. 이 체크리스트는 출시일까지 필요한 모든 준비 단계를 안내합니다.", sourceNote: "NCSOFT 공식 사전 출시 자료, AION2Hub 출시 카운트다운 가이드, PCGamesN의 글로벌 출시 보도에 기반합니다.", keywords: ["Aion 2 사전 출시 체크리스트", "Aion 2 9월 30일 출시", "Aion 2 시스템 요구사항", "Aion 2 사전 로드", "Aion 2 출시 준비"],
      sections: [
        section("countdown-to-launch", "출시 카운트다운: 2026년 9월 30일", ["NCSOFT는 Aion 2가 2026년 9월 30일에 전 세계 동시 출시된다고 발표했습니다. 북미, 유럽, 동남아시아, 오세아니아 등 주요 지역을 대상으로 지역별 서버가 제공됩니다.", "정확한 출시 시간은 추후 발표될 예정입니다. NCSOFT는 과거 한국 시간대(KST 10:00 / UTC 01:00)에 주요 업데이트를 출시한 이력이 있어, 글로벌 플레이어는 이에 맞춰 계획을 세우는 것이 좋습니다."]),
        section("system-requirements", "시스템 요구사항 및 사전 로드", ["Aion 2는 업데이트된 NCSoft 엔진을 기반으로 합니다. 최소 사양: Intel Core i5-6600 또는 AMD Ryzen 3 3300X, 8GB RAM, NVIDIA GTX 960. 권장 사양: Intel Core i7-9700, 16GB RAM, NVIDIA RTX 2060.", "약 60GB의 저장 공간이 필요하며 SSD 사용을 강력 권장합니다. 사전 로드는 9월 16일경부터 가능할 것으로 예상됩니다."]),
        section("account-setup", "계정 생성 및 사전 주문 혜택", ["NCSOFT 계정을 미리 생성하는 것이 중요합니다. Steam 사전 주문 시 'Dawnbringer' 칭호, 날개 외형, 3일 얼리 액세스(9월 27일부터)가 제공됩니다.", "공식 웹사이트 사전 등록 시 'Atreia Explorer' 스타터 팩이 무료로 제공됩니다. 보상을 받으려면 출시일 전에 Steam 계정과 NCSOFT 계정을 연결해야 합니다."]),
        section("server-selection", "서버 선택 및 진영 계획", ["서버 선택은 전체 Aion 2 경험에 영향을 미치는 중요한 결정입니다. PvE 서버, PvP 서버, RP 서버 등 다양한 유형이 출시될 예정입니다.", "진영 선택(Elyos 또는 Asmodian)은 출시 전에 결정하는 것이 좋습니다. 친구들과 같은 진영을 선택해야 함께 플레이할 수 있습니다."]),
        section("final-checklist", "최종 준비 체크리스트", ["시스템 요구사항 확인 및 그래픽 드라이버 업데이트. Steam 클라이언트 또는 NCSoft 런처 설치. 9월 16일경 게임 사전 로드. NCSOFT 계정 생성 및 인증.", "출시일 서버 대기열에 대비하고, 캐릭터 이름을 미리 준비하세요. 공식 웹사이트와 커뮤니티 Discord를 즐겨찾기에 추가하는 것도 잊지 마세요."]),
      ],
    }),
    ja: articleCopy(guideLabels, "ja", 6, {
      eyebrow: "プレローンチチェックリスト", title: "Aion 2 プレローンチチェックリスト：9月30日に備える完全ガイド", description: "2026年9月30日のAion 2グローバルローンチに備えましょう。システム要件、プリロード、アカウント設定、派閥計画などの完全チェックリスト。", intro: "Aion 2のグローバルローンチが2026年9月30日に決定しました。準備の時間は急速に迫っています。", sourceNote: "NCSOFT公式プレローンチ資料、AION2Hubのカウントダウンガイド、PCGamesNの報道に基づきます。", keywords: ["Aion 2 プレローンチチェックリスト", "Aion 2 9月30日ローンチ", "Aion 2 システム要件", "Aion 2 プリロード", "Aion 2 準備"],
      sections: [
        section("countdown-to-launch", "カウントダウン：2026年9月30日", ["NCSOFTはAion 2が2026年9月30日にグローバルローンチすることを発表しました。北米、欧州、東南アジア、オセアニアの各リージョンにローカライズされたサーバーが提供されます。", "正確なローンチ時間は後日発表される予定です。NCSOFTは過去に韓国時間(KST 10:00 / UTC 01:00)に主要アップデートをリリースしてきました。"]),
        section("system-requirements", "システム要件とプリロード", ["Aion 2は更新されたNCSoftエンジン上で動作します。最小要件：Intel Core i5-6600、8GB RAM、NVIDIA GTX 960。推奨：Intel Core i7-9700、16GB RAM、NVIDIA RTX 2060。", "約60GBのストレージが必要で、SSDを強く推奨します。プリロードは9月16日頃から開始される見込みです。"]),
        section("account-setup", "アカウント作成と予約特典", ["NCSOFTアカウントを事前に作成することが重要です。Steamで予約注文すると「Dawnbringer」称号、コスメティックウィング、3日間の早期アクセス（9月27日から）が付与されます。", "公式サイトでの事前登録で「Atreia Explorer」スターターパックが無料で入手できます。特典を受け取るにはSteamアカウントとNCSOFTアカウントを連携する必要があります。"]),
        section("server-selection", "サーバー選択と派閥計画", ["サーバー選択はAion 2体験全体に影響します。PvEサーバー、PvPサーバー、RPサーバーなど複数のタイプが提供される予定です。", "派閥選択（ElyosまたはAsmodian）は事前に決めておきましょう。同じ派閥を選ばないとグループプレイができません。"]),
        section("final-checklist", "最終チェックリスト", ["システム要件を確認しグラフィックドライバを更新。SteamまたはNCSoftランチャーをインストール。9月16日頃にゲームをプリロード。NCSOFTアカウントを作成・認証。", "サーバー待ち行列に備え、キャラクター名を事前に準備。公式サイトやコミュニティDiscordをブックマークしておきましょう。"]),
      ],
    }),
    fr: articleCopy(guideLabels, "fr", 6, {
      eyebrow: "LISTE DE PRÉ-LANCEMENT", title: "Liste de pré-lancement d'Aion 2 : tout préparer pour le 30 septembre", description: "Préparez-vous pour le lancement mondial d'Aion 2 le 30 septembre 2026. Liste complète couvrant la configuration requise, le préchargement, la création de compte et la planification.", intro: "Le lancement mondial d'Aion 2 est fixé au 30 septembre 2026. Cette liste de contrôle vous guide à travers chaque étape cruciale.", sourceNote: "Basé sur les documents officiels de NCSOFT, le guide de compte à rebours d'AION2Hub et les rapports de PCGamesN.", keywords: ["Aion 2 liste pré-lancement", "Aion 2 30 septembre", "Aion 2 configuration requise", "Aion 2 préchargement"],
      sections: [
        section("countdown-to-launch", "Compte à rebours : 30 septembre 2026", ["NCSOFT a confirmé le lancement mondial d'Aion 2 pour le 30 septembre 2026. Des serveurs localisés seront disponibles en Amérique du Nord, en Europe, en Asie du Sud-Est et en Océanie.", "L'heure exacte de lancement sera annoncée prochainement. NCSOFT a historiquement lancé les majeures mises à jour pendant les heures de pointe coréennes."]),
        section("system-requirements", "Configuration requise et préchargement", ["Configuration minimale : Intel Core i5-6600, 8 Go de RAM, NVIDIA GTX 960. Configuration recommandée : Intel Core i7-9700, 16 Go de RAM, NVIDIA RTX 2060.", "Environ 60 Go d'espace de stockage sont nécessaires. Le préchargement devrait être disponible à partir du 16 septembre."]),
        section("account-setup", "Création de compte et bonus de précommande", ["Créez votre compte NCSOFT à l'avance. La précommande sur Steam offre le titre 'Dawnbringer', des ailes cosmétiques et un accès anticipé de 3 jours à partir du 27 septembre.", "La préinscription sur le site officiel offre un pack de démarrage 'Atreia Explorer' gratuit."]),
        section("server-selection", "Sélection du serveur et planification de faction", ["Plusieurs types de serveurs seront disponibles : PvE, PvP et éventuellement RP. Le choix de la faction (Elyos ou Asmodien) doit être fait avant le lancement.", "Coordonnez-vous avec vos amis pour choisir la même faction, car il est impossible de former un groupe entre factions."]),
        section("final-checklist", "Liste de contrôle finale", ["Vérifiez la configuration système, mettez à jour les pilotes, installez le client Steam ou NCSoft, préchargez le jeu vers le 16 septembre, et créez votre compte NCSOFT.", "Préparez-vous aux files d'attente du jour de lancement et choisissez votre nom de personnage à l'avance."]),
      ],
    }),
    de: articleCopy(guideLabels, "de", 6, {
      eyebrow: "VORAB-CHECKLISTE", title: "Aion 2 Vorab-Checkliste: Alles für den Start am 30. September vorbereiten", description: "Bereiten Sie sich auf den globalen Launch von Aion 2 am 30. September 2026 vor. Vollständige Checkliste mit Systemanforderungen, Vorabdownload, Kontoeinrichtung und mehr.", intro: "Der globale Launch von Aion 2 ist für den 30. September 2026 bestätigt. Diese Checkliste führt Sie durch alle wichtigen Vorbereitungsschritte.", sourceNote: "Basierend auf offiziellen NCSOFT-Vorabmaterialien, AION2Hub-Countdown-Guide und PCGamesN-Berichterstattung.", keywords: ["Aion 2 Vorab-Checkliste", "Aion 2 30. September", "Aion 2 Systemanforderungen", "Aion 2 Vorabdownload"],
      sections: [
        section("countdown-to-launch", "Countdown zum Launch: 30. September 2026", ["NCSOFT hat den globalen Launch von Aion 2 für den 30. September 2026 bestätigt. Server in Nordamerika, Europa, Südostasien und Ozeanien werden bereitgestellt.", "Die genaue Startzeit wird später bekannt gegeben. NCSOFT hat wichtige Updates historisch zur koreanischen Hauptzeit veröffentlicht."]),
        section("system-requirements", "Systemanforderungen und Vorabdownload", ["Minimale Anforderungen: Intel Core i5-6600, 8 GB RAM, NVIDIA GTX 960. Empfohlen: Intel Core i7-9700, 16 GB RAM, NVIDIA RTX 2060.", "Etwa 60 GB Speicherplatz sind erforderlich. Der Vorabdownload wird voraussichtlich um den 16. September herum verfügbar sein."]),
        section("account-setup", "Kontoerstellung und Vorbestellerboni", ["Erstellen Sie Ihr NCSOFT-Konto im Voraus. Steam-Vorbesteller erhalten den 'Dawnbringer'-Titel, kosmetische Flügel und 3 Tage Early Access ab dem 27. September.", "Die Vorregistrierung auf der offiziellen Website gewährt ein kostenloses 'Atreia Explorer'-Starterpaket."]),
        section("server-selection", "Serverauswahl und Fraktionsplanung", ["Mehrere Servertypen werden verfügbar sein: PvE, PvP und möglicherweise RP. Die Fraktionswahl (Elyos oder Asmodianer) sollte vor dem Launch getroffen werden.", "Stimmen Sie sich mit Freunden ab, um dieselbe Fraktion zu wählen, da fraktionsübergreifende Gruppen nicht möglich sind."]),
        section("final-checklist", "Abschließende Checkliste", ["Systemanforderungen prüfen, Grafiktreiber aktualisieren, Steam- oder NCSoft-Client installieren, Spiel um den 16. September vorab herunterladen, NCSOFT-Konto erstellen.", "Bereiten Sie sich auf Warteschlangen am Starttag vor und wählen Sie Ihren Charakternamen rechtzeitig."]),
      ],
    }),
    es: articleCopy(guideLabels, "es", 6, {
      eyebrow: "LISTA DE PRELANZAMIENTO", title: "Lista de verificación de prelanzamiento de Aion 2: prepárate para el 30 de septiembre", description: "Prepárate para el lanzamiento global de Aion 2 el 30 de septiembre de 2026. Lista completa que cubre requisitos del sistema, precarga, configuración de cuenta y planificación.", intro: "El lanzamiento global de Aion 2 está fijado para el 30 de septiembre de 2026. Esta lista te guía a través de cada paso crucial.", sourceNote: "Basado en materiales oficiales de NCSOFT, la guía de cuenta regresiva de AION2Hub y los informes de PCGamesN.", keywords: ["Aion 2 lista prelanzamiento", "Aion 2 30 septiembre", "Aion 2 requisitos del sistema", "Aion 2 precarga"],
      sections: [
        section("countdown-to-launch", "Cuenta regresiva: 30 de septiembre de 2026", ["NCSOFT ha confirmado el lanzamiento global de Aion 2 para el 30 de septiembre de 2026. Habrá servidores localizados en Norteamérica, Europa, Sudeste Asiático y Oceanía.", "La hora exacta de lanzamiento se anunciará próximamente. NCSOFT ha lanzado actualizaciones importantes durante el horario pico coreano."]),
        section("system-requirements", "Requisitos del sistema y precarga", ["Requisitos mínimos: Intel Core i5-6600, 8 GB RAM, NVIDIA GTX 960. Recomendados: Intel Core i7-9700, 16 GB RAM, NVIDIA RTX 2060.", "Se requieren aproximadamente 60 GB de almacenamiento. La precarga estará disponible alrededor del 16 de septiembre."]),
        section("account-setup", "Creación de cuenta y bonos de preventa", ["Crea tu cuenta de NCSOFT con anticipación. La preventa en Steam incluye el título 'Dawnbringer', alas cosméticas y acceso anticipado de 3 días a partir del 27 de septiembre.", "El prerregistro en el sitio web oficial otorga un paquete inicial 'Atreia Explorer' gratuito."]),
        section("server-selection", "Selección de servidor y planificación de facción", ["Habrá múltiples tipos de servidor: PvE, PvP y posiblemente RP. La elección de facción (Elyos o Asmodiano) debe hacerse antes del lanzamiento.", "Coordínate con tus amigos para elegir la misma facción, ya que no se puede formar grupo entre facciones."]),
        section("final-checklist", "Lista de verificación final", ["Verifica los requisitos del sistema, actualiza los controladores, instala el cliente de Steam o NCSoft, precarga el juego alrededor del 16 de septiembre y crea tu cuenta de NCSOFT.", "Prepárate para las colas del día de lanzamiento y elige el nombre de tu personaje con anticipación."]),
      ],
    }),
    "pt-br": articleCopy(guideLabels, "pt-br", 6, {
      eyebrow: "LISTA DE PRÉ-LANÇAMENTO", title: "Lista de verificação de pré-lançamento de Aion 2: prepare-se para 30 de setembro", description: "Prepare-se para o lançamento global de Aion 2 em 30 de setembro de 2026. Lista completa cobrindo requisitos de sistema, pré-carga, configuração de conta e planejamento.", intro: "O lançamento global de Aion 2 está marcado para 30 de setembro de 2026. Esta lista de verificação guia você por cada etapa crucial.", sourceNote: "Baseado em materiais oficiais da NCSOFT, guia de contagem regressiva da AION2Hub e relatórios da PCGamesN.", keywords: ["Aion 2 lista pré-lançamento", "Aion 2 30 setembro", "Aion 2 requisitos de sistema", "Aion 2 pré-carga"],
      sections: [
        section("countdown-to-launch", "Contagem regressiva: 30 de setembro de 2026", ["A NCSOFT confirmou o lançamento global de Aion 2 para 30 de setembro de 2026. Servidores localizados estarão disponíveis na América do Norte, Europa, Sudeste Asiático e Oceania.", "O horário exato de lançamento será anunciado posteriormente. A NCSOFT historicamente lança grandes atualizações durante o horário de pico coreano."]),
        section("system-requirements", "Requisitos de sistema e pré-carga", ["Requisitos mínimos: Intel Core i5-6600, 8 GB RAM, NVIDIA GTX 960. Recomendados: Intel Core i7-9700, 16 GB RAM, NVIDIA RTX 2060.", "Aproximadamente 60 GB de armazenamento são necessários. A pré-carga estará disponível por volta de 16 de setembro."]),
        section("account-setup", "Criação de conta e bônus de pré-venda", ["Crie sua conta NCSOFT com antecedência. A pré-venda na Steam inclui o título 'Dawnbringer', asas cosméticas e acesso antecipado de 3 dias a partir de 27 de setembro.", "O pré-registro no site oficial concede um pacote inicial 'Atreia Explorer' gratuito."]),
        section("server-selection", "Seleção de servidor e planejamento de facção", ["Múltiplos tipos de servidor estarão disponíveis: PvE, PvP e possivelmente RP. A escolha de facção (Elyos ou Asmodiano) deve ser feita antes do lançamento.", "Coordene-se com amigos para escolher a mesma facção, pois não é possível formar grupos entre facções."]),
        section("final-checklist", "Lista de verificação final", ["Verifique os requisitos de sistema, atualize drivers, instale o cliente Steam ou NCSoft, pré-carregue o jogo por volta de 16 de setembro e crie sua conta NCSOFT.", "Prepare-se para filas no dia do lançamento e escolha o nome do seu personagem com antecedência."]),
      ],
    }),
    ru: articleCopy(guideLabels, "ru", 6, {
      eyebrow: "КОНТРОЛЬНЫЙ СПИСОК", title: "Контрольный список предзапуска Aion 2: подготовка к 30 сентября", description: "Подготовьтесь к глобальному запуску Aion 2 30 сентября 2026 года. Полный список: системные требования, предзагрузка, настройка аккаунта и планирование.", intro: "Глобальный запуск Aion 2 назначен на 30 сентября 2026 года. Этот список проведет вас через каждый важный шаг.", sourceNote: "Основано на официальных материалах NCSOFT, руководстве AION2Hub и отчетах PCGamesN.", keywords: ["Aion 2 контрольный список", "Aion 2 30 сентября", "Aion 2 системные требования", "Aion 2 предзагрузка"],
      sections: [
        section("countdown-to-launch", "Обратный отсчет: 30 сентября 2026 года", ["NCSOFT подтвердила глобальный запуск Aion 2 на 30 сентября 2026 года. Локализованные серверы будут доступны в Северной Америке, Европе, Юго-Восточной Азии и Океании.", "Точное время запуска будет объявлено позднее. NCSOFT исторически выпускала крупные обновления в корейское прайм-время."]),
        section("system-requirements", "Системные требования и предзагрузка", ["Минимальные требования: Intel Core i5-6600, 8 ГБ ОЗУ, NVIDIA GTX 960. Рекомендуемые: Intel Core i7-9700, 16 ГБ ОЗУ, NVIDIA RTX 2060.", "Требуется около 60 ГБ свободного места. Предзагрузка будет доступна примерно 16 сентября."]),
        section("account-setup", "Создание аккаунта и бонусы предзаказа", ["Создайте аккаунт NCSOFT заранее. Предзаказ в Steam дает титул 'Dawnbringer', косметические крылья и 3-дневный ранний доступ с 27 сентября.", "Предварительная регистрация на официальном сайте дает бесплатный стартовый набор 'Atreia Explorer'."]),
        section("server-selection", "Выбор сервера и планирование фракции", ["Будут доступны несколько типов серверов: PvE, PvP и, возможно, RP. Выбор фракции (Elyos или Asmodians) должен быть сделан до запуска.", "Согласуйте выбор с друзьями, чтобы быть в одной фракции — межфракционные группы невозможны."]),
        section("final-checklist", "Финальный контрольный список", ["Проверьте системные требования, обновите драйверы, установите клиент Steam или NCSoft, предзагрузите игру около 16 сентября, создайте аккаунт NCSOFT.", "Будьте готовы к очередям в день запуска и заранее выберите имя персонажа."]),
      ],
    }),
    "zh-hant": articleCopy(guideLabels, "zh-hant", 6, {
      eyebrow: "預上線準備清單", title: "Aion 2 預上線準備清單：為 9 月 30 日做好一切準備", description: "為 Aion 2 2026 年 9 月 30 日的全球上線做好準備。完整的預上線清單涵蓋系統需求、預載、帳號設定、陣營規劃等。", intro: "Aion 2 全球上線定於 2026 年 9 月 30 日，這份清單將引導您完成從系統需求到伺服器選擇的每一個關鍵步驟。", sourceNote: "基於 NCSOFT 官方預上線資料、AION2Hub 的倒數指南和 PCGamesN 的全面報導。", keywords: ["Aion 2 預上線清單", "Aion 2 9月30日上線", "Aion 2 系統需求", "Aion 2 預載", "Aion 2 上線準備"],
      sections: [
        section("countdown-to-launch", "上線倒數：2026 年 9 月 30 日", ["NCSOFT 已確認 Aion 2 將於 2026 年 9 月 30 日全球上線，這將是該系列首次在全球同步發布。伺服器將覆蓋北美、歐洲、東南亞和大洋洲等地區。", "具體上線時間將在臨近日期公布。NCSOFT 歷史上曾在韓國高峰時段發布重大更新，全球玩家應據此規劃。"]),
        section("system-requirements", "系統需求與預載資訊", ["Aion 2 基於更新後的 NCSoft 引擎。最低配置需求：Intel Core i5-6600 或 AMD Ryzen 3 3300X、8 GB 記憶體、NVIDIA GTX 960。推薦配置：Intel Core i7-9700、16 GB 記憶體、NVIDIA RTX 2060。", "基礎安裝需要約 60 GB 儲存空間，強烈建議使用 SSD。預載預計在 9 月 16 日左右開放。"]),
        section("account-setup", "帳號創建與預購獎勵", ["提前創建 NCSOFT 帳號是最重要的步驟之一。預購玩家可獲得專屬 'Dawnbringer' 稱號、裝飾性翅膀和 3 天搶先體驗權（9 月 27 日開始）。", "官網預註冊則贈送 'Atreia Explorer' 新手包，包含藥水、傳送卷軸和獨特坐騎。"]),
        section("server-selection", "伺服器選擇與陣營規劃", ["伺服器選擇影響整個 Aion 2 體驗。NCSOFT 預計將推出多種伺服器類型：PvE 伺服器、PvP 伺服器，可能還有角色扮演伺服器。", "陣營選擇（Elyos 或 Asmodian）最好在上線前做出決定。與朋友協調，確保所有人選擇同一陣營。"]),
        section("final-checklist", "最終準備清單", ["確認系統滿足最低要求並更新顯卡驅動；下載並安裝 Steam 或 NCSoft 啟動器；在 9 月 16 日左右預載遊戲客戶端；創建並驗證你的 NCSOFT 帳號。", "為上線日的伺服器佇列預留時間、提前準備角色名稱（先到先得）、收藏官方網站和社群 Discord。"]),
      ],
    }),
  },
};