import {
  articleCopy,
  localizations,
  guideLabels,
  publishedVerified,
  section,
} from "./trending-september-5-shared";
import type { ContentSource, ContentHeroImage } from "./content-registry";

const officialCraftingSource: ContentSource = {
  id: "ncsoft-crafting-guide",
  kind: "official",
  publisher: "NCSoft",
  label: "AION 2 Official Guide — Crafting & Life Skills",
  url: "https://aion2.plaync.com/en-us/game/guide/crafting",
  publishedAt: "2026-08-20",
  retrievedAt: "2026-09-05",
  verifiedAt: "2026-09-05",
  localizations: localizations(
    {
      "zh-hans": "AION 2 官方指南 — 制作与生活技能", en: "AION 2 Official Guide — Crafting & Life Skills", fr: "Guide officiel d'AION 2 — Artisanat et compétences de vie",
      de: "AION 2 Offizieller Leitfaden — Handwerk und Lebensfähigkeiten", es: "Guía oficial de AION 2 — Artesanía y habilidades de vida", ja: "AION 2 公式ガイド — 製作と生活スキル",
      "pt-br": "Guia oficial do AION 2 — Fabricação e habilidades de vida", ru: "Официальное руководство AION 2 — Ремесло и жизненные навыки", ko: "AION 2 공식 가이드 — 제작 및 생활 스킬", "zh-hant": "AION 2 官方指南 — 製作與生活技能",
    },
    "https://aion2.plaync.com/en-us/game/guide/crafting",
  ),
};

const communityCraftSource: ContentSource = {
  id: "aion2t-crafting-profit-guide",
  kind: "third-party",
  publisher: "AION2T",
  label: "AION 2 Crafting Economy: How to Profit from Life Skills",
  url: "https://aion2t.com/guides/crafting-profit-guide/",
  publishedAt: "2026-09-02",
  retrievedAt: "2026-09-05",
  verifiedAt: "2026-09-05",
  localizations: localizations(
    {
      "zh-hans": "AION 2 制作经济：如何从生活技能中获利", en: "AION 2 Crafting Economy: How to Profit from Life Skills", fr: "Économie d'artisanat d'AION 2 : Comment profiter des compétences de vie",
      de: "AION 2 Handwerkswirtschaft: Wie man mit Lebensfähigkeiten profitiert", es: "Economía de artesanía de AION 2: Cómo beneficiarse de las habilidades de vida", ja: "AION 2 製作経済：生活スキルで利益を得る方法",
      "pt-br": "Economia de fabricação do AION 2: Como lucrar com habilidades de vida", ru: "Экономика ремесла AION 2: Как извлечь выгоду из жизненных навыков", ko: "AION 2 제작 경제: 생활 스킬로 수익을 얻는 방법", "zh-hant": "AION 2 製作經濟：如何從生活技能中獲利",
    },
    "https://aion2t.com/guides/crafting-profit-guide/",
  ),
};

const hero: ContentHeroImage = {
  src: "https://blogfiles.ncsoft.net/news/af7330da-4ff6-4b58-aece-400e6061a3be.jpg",
  width: 1200, height: 630, credit: "NC Corporation",
  sourceUrl: "https://aion2.plaync.com/en-us/game/guide/crafting",
  rights: "linked-official-media",
  translations: {
    "zh-hans": { alt: "AION 2 制作与生活技能指南", caption: "完整制作系统与生活技能深度解析。" },
    en: { alt: "AION 2 Crafting and Life Skills Guide", caption: "Complete crafting system and life skills deep dive." },
    fr: { alt: "Guide d'artisanat et compétences de vie d'AION 2", caption: "Analyse complète du système d'artisanat et des compétences de vie." },
    de: { alt: "AION 2 Handwerks- und Lebensfähigkeiten-Leitfaden", caption: "Vollständige Analyse des Handwerksystems." },
    es: { alt: "Guía de artesanía y habilidades de vida de AION 2", caption: "Análisis completo del sistema de artesanía." },
    ja: { alt: "AION 2 製作・生活スキルガイド", caption: "製作システムと生活スキルの完全解析。" },
    "pt-br": { alt: "Guia de fabricação e habilidades de vida do AION 2", caption: "Análise completa do sistema de fabricação." },
    ru: { alt: "Руководство по ремеслу и жизненным навыкам AION 2", caption: "Полный анализ системы ремесла." },
    ko: { alt: "AION 2 제작 및 생활 스킬 가이드", caption: "제작 시스템과 생활 스킬 완전 분석." },
    "zh-hant": { alt: "AION 2 製作與生活技能指南", caption: "完整製作系統與生活技能深度解析。" },
  },
};

export const trendingSeptember5Article3 = {
  section: "guides" as const,
  slug: "aion-2-crafting-life-skills-complete-guide",
  schemaType: "Article" as const,
  publishedAt: "2026-09-05", updatedAt: "2026-09-05",
  readingMinutes: 10,
  publication: publishedVerified,
  sources: [officialCraftingSource, communityCraftSource],
  heroImage: hero,
  related: [
    { kind: "content" as const, section: "guides" as const, slug: "aion-2-endgame-progression-roadmap" },
    { kind: "content" as const, section: "guides" as const, slug: "aion-2-solo-leveling-guide-40-cap" },
    { kind: "content" as const, section: "guides" as const, slug: "aion-2-mounts-movement-travel-guide" },
  ],
  translations: {
    "zh-hans": articleCopy(guideLabels, "zh-hans", 10, {
      eyebrow: "制作指南",
      title: "AION 2 制作与生活技能完整指南：从入门到赚钱",
      description: "全面解析AION 2的制作系统：6大制作专业、4大采集专业、材料获取、装备制作流程、以及如何通过制作系统赚取金币",
      intro: "AION 2 的制作系统是游戏经济的核心。本文将全面解析制作专业的选择、升级路线、以及赚钱策略，帮助你在游戏中建立稳定的收入来源。",
      keywords: ["AION 2 制作", "AION 2 生活技能", "AION 2 赚钱", "AION 2 采集", "AION 2 制作专业"],
      sourceNote: "基于 NCSoft 官方制作指南和 AION2T 制作经济攻略（2026-09-02）整理。",
      sections: [
        section("crafting-professions-overview", "制作专业概览", "AION 2 有 6 大制作专业：武器锻造（近战武器）、盔甲锻造（板甲）、裁缝（布甲/皮甲）、炼金术（药水/卷轴）、烹饪（食物BUFF）、工艺（饰品/宝石）。每个角色最多同时学习 2 个制作专业。升级制作专业需要消耗材料和金币，建议先确定目标产品再选择专业。"),
        section("gathering-professions", "采集专业", "4 大采集专业与制作专业配套：采矿（配合锻造）、采伐（配合工艺）、采集（配合炼金/烹饪）、狩猎（配合裁缝）。每个角色可同时拥有 3 个采集专业。采集点在世界地图上有固定刷新位置，高级材料需要更高的采集等级。竞争热门采集点是早期常见问题——建议错峰采集或选择冷门但高价值的材料。"),
        section("leveling-crafting", "制作专业升级路线", "制作专业从 1 级开始，最高 50 级。每级通过制作物品获得经验。建议升级路线：1-10 级制作灰色物品（最低材料消耗）；10-30 级制作绿色物品（可出售给 NPC）；30-40 级制作蓝色物品（拍卖行有需求）；40-50 级制作紫色/金色物品（高利润但材料昂贵）。每个整数等级（10/20/30/40/50）需要完成职业任务才能继续升级。"),
        section("profit-strategies", "赚钱策略", "最赚钱的制作路线：烹饪（食物BUFF消耗量大，稳定需求）和炼金术（药水是副本刚需）。中级赚钱：制作蓝色装备出售给练级中的玩家。高级赚钱：50级工艺制作传说宝石——利润高但材料成本也高。每日任务奖励的'制作加速券'可以显著降低升级成本。"),
        section("beginner-tips", "新手建议", "1. 先确定你要制作的最终产品，再选择专业——不要盲目升级；2. 烹饪+采集是最佳新手组合——材料便宜、需求稳定；3. 在拍卖行观察价格趋势——了解什么物品有利可图；4. 利用每日采集任务——它们提供免费材料和经验；5. 加入公会——公会制作加成可以节省 10-15% 材料消耗。", ),
      ],
    }),
    en: articleCopy(guideLabels, "en", 10, {
      eyebrow: "CRAFTING GUIDE",
      title: "AION 2 Crafting and Life Skills Complete Guide: From Beginner to Profiting",
      description: "Full analysis of AION 2's crafting system: 6 crafting professions, 4 gathering professions, material acquisition, equipment crafting process, and how to earn gold through crafting",
      intro: "AION 2's crafting system is the core of the game economy. This article fully analyzes crafting profession choices, leveling routes, and money-making strategies to help you build a stable income source.",
      keywords: ["AION 2 crafting", "AION 2 life skills", "AION 2 gold making", "AION 2 gathering", "AION 2 crafting professions"],
      sourceNote: "Based on NCSoft's official crafting guide and AION2T crafting economy guide (September 2, 2026).",
      sections: [
        section("crafting-professions-overview", "Crafting Professions Overview", "AION 2 has 6 crafting professions: Weaponsmithing (melee weapons), Armorsmithing (plate armor), Tailoring (cloth/leather armor), Alchemy (potions/scrolls), Cooking (food BUFFs), Handicraft (accessories/gems). Each character can learn up to 2 crafting professions simultaneously. Leveling crafting requires materials and gold — decide your target product before choosing."),
        section("gathering-professions", "Gathering Professions", "4 gathering professions pair with crafting: Mining (for smithing), Logging (for handicraft), Gathering (for alchemy/cooking), Skinning (for tailoring). Each character can have 3 gathering professions. Gathering nodes have fixed respawn locations on the world map; higher-tier materials require higher gathering levels. Competing for popular nodes is a common early issue — try off-peak hours or choose less popular but high-value materials."),
        section("leveling-crafting", "Crafting Leveling Route", "Crafting starts at level 1, max 50. Gain XP by crafting items. Recommended route: Levels 1-10 craft grey items (lowest material cost); 10-30 craft green items (sellable to NPC); 30-40 craft blue items (auction house demand); 40-50 craft purple/gold items (high profit but expensive materials). Each milestone level (10/20/30/40/50) requires a profession quest to continue."),
        section("profit-strategies", "Profit Strategies", "Most profitable routes: Cooking (food BUFFs have high, stable demand) and Alchemy (potions are dungeon essentials). Mid-tier profit: craft blue gear for leveling players. High-tier profit: level 50 Handicraft legendary gems — high profit but expensive materials. Daily quest 'Crafting Acceleration Coupons' significantly reduce leveling costs."),
        section("beginner-tips", "Beginner Tips", "1. Decide your end product first, then choose professions — don't level blindly; 2. Cooking + Gathering is the best beginner combo — cheap materials, stable demand; 3. Watch auction house price trends — understand what's profitable; 4. Use daily gathering quests — free materials and XP; 5. Join a guild — guild crafting bonuses save 10-15% material costs."),
      ],
    }),
    fr: articleCopy(guideLabels, "fr", 10, {
      eyebrow: "GUIDE D'ARTISANAT",
      title: "Guide complet d'artisanat et compétences de vie d'AION 2 : Du débutant au profitable",
      description: "Analyse complète du système d'artisanat : 6 professions, 4 compétences de collecte, acquisition de matériaux",
      intro: "Le système d'artisanat d'AION 2 est au cœur de l'économie du jeu.",
      keywords: ["Artisanat AION 2", "Compétences de vie AION 2", "Or AION 2", "Collecte AION 2", "Professions AION 2"],
      sourceNote: "Basé sur le guide officiel NCSoft et le guide économique d'AION2T (2 septembre 2026).",
      sections: [
        section("crafting-professions-overview", "Aperçu des professions d'artisanat", "6 professions : Forge d'armes, Forge d'armures, Couture, Alchimie, Cuisine, Artisanat. 2 max par personnage."),
        section("gathering-professions", "Compétences de collecte", "4 compétences : Minage, Bûcheronnage, Cueilleté, Dépeçage. 3 max par personnage."),
        section("leveling-crafting", "Route de montée d'artisanat", "Niveau 1 à 50. Objets gris 1-10, verts 10-30, bleus 30-40, violets/or 40-50."),
        section("profit-strategies", "Stratégies de profit", "Cuisine (BUFFs alimentaires) et Alchimie (potions) sont les plus rentables."),
        section("beginner-tips", "Conseils débutants", "1. Choisir le produit final d'abord ; 2. Cuisine + Collecte = meilleur combo débutant ; 3. Observer l'hôtel des ventes ; 4. Quêtes quotidiennes ; 5. Rejoindre une guilde."),
      ],
    }),
    de: articleCopy(guideLabels, "de", 10, {
      eyebrow: "HANDWERKSLEITFADEN",
      title: "AION 2 Handwerk und Lebensfähigkeiten Kompletter Leitfaden: Vom Anfänger zum Profit",
      description: "Vollständige Analyse des Handwerksystems: 6 Berufe, 4 Sammelberufe, Materialbeschaffung",
      intro: "Das Handwerksystem von AION 2 ist das Kernstück der Spielwirtschaft.",
      keywords: ["Handwerk AION 2", "Lebensfähigkeiten AION 2", "Gold AION 2", "Sammeln AION 2", "Berufe AION 2"],
      sourceNote: "Basierend auf NCSofts offiziellem Handwerksleitfaden und AION2T-Wirtschaftsleitfaden (2. September 2026).",
      sections: [
        section("crafting-professions-overview", "Handwerksberufe Überblick", "6 Berufe: Waffenschmied, Rüstungsschmied, Schneider, Alchemie, Kochkunst, Kunsthandwerk. Max 2 pro Charakter."),
        section("gathering-professions", "Sammelberufe", "4 Berufe: Bergbau, Holzfäller, Kräutersammeln, Kürschnerei. Max 3 pro Charakter."),
        section("leveling-crafting", "Handwerk-Levelroute", "Stufe 1-50. Grau 1-10, Grün 10-30, Blau 30-40, Lila/Gold 40-50."),
        section("profit-strategies", "Gewinnstrategien", "Kochen (Food-BUFFs) und Alchemie (Tränke) sind am profitabelsten."),
        section("beginner-tips", "Anfängertipps", "1. Endprodukt zuerst wählen; 2. Kochen + Sammeln = bestes Anfänger-Combo; 3. Auktionshaus beobachten; 4. Tägliche Quests; 5. Gilde beitreten."),
      ],
    }),
    es: articleCopy(guideLabels, "es", 10, {
      eyebrow: "GUÍA DE ARTESANÍA",
      title: "Guía completa de artesanía y habilidades de vida de AION 2: De principiante a rentable",
      description: "Análisis completo del sistema de artesanía: 6 profesiones, 4 de recolección, adquisición de materiales",
      intro: "El sistema de artesanía de AION 2 es el núcleo de la economía del juego.",
      keywords: ["Artesanía AION 2", "Habilidades de vida AION 2", "Oro AION 2", "Recolección AION 2", "Profesiones AION 2"],
      sourceNote: "Basado en la guía oficial de NCSoft y la guía económica de AION2T (2 de septiembre de 2026).",
      sections: [
        section("crafting-professions-overview", "Descripción de profesiones de artesanía", "6 profesiones: Herrería de armas, Herrería de armaduras, Sastrería, Alquimia, Cocina, Artesanía. Máx 2 por personaje."),
        section("gathering-professions", "Profesiones de recolección", "4 profesiones: Minería, Leñador, Recolección, Pellejería. Máx 3 por personaje."),
        section("leveling-crafting", "Ruta de subida de artesanía", "Nivel 1-50. Gris 1-10, verde 10-30, azul 30-40, púrpura/oro 40-50."),
        section("profit-strategies", "Estrategias de beneficio", "Cocina (BUFFs de comida) y Alquimia (pociones) son las más rentables."),
        section("beginner-tips", "Consejos para principiantes", "1. Elegir producto final primero; 2. Cocina + Recolección = mejor combo principiante; 3. Observar casa de subastas; 4. Misiones diarias; 5. Unirse a hermandad."),
      ],
    }),
    ja: articleCopy(guideLabels, "ja", 10, {
      eyebrow: "製作ガイド",
      title: "AION 2 製作・生活スキル完全ガイド：初心者から収益化まで",
      description: "製作システムの完全分析：6大製作専門、4大採取専門、材料取得",
      intro: "AION 2の製作システムはゲーム経済の核心です。",
      keywords: ["AION 2 製作", "AION 2 生活スキル", "AION 2 ゴールド", "AION 2 採取", "AION 2 製作専門"],
      sourceNote: "NCSoft公式製作ガイドおよびAION2T製作経済ガイド（2026年9月2日）に基づく。",
      sections: [
        section("crafting-professions-overview", "製作専門概要", "6専門：武器鍛造、鎧鍛造、裁縫、錬金術、調理、工芸。キャラクターごとに最大2つ。"),
        section("gathering-professions", "採取専門", "4専門：採鉱、伐採、採集、狩猟。キャラクターごとに最大3つ。"),
        section("leveling-crafting", "製作レベルルート", "レベル1-50。灰色1-10、緑10-30、青30-40、紫/金40-50。"),
        section("profit-strategies", "収益戦略", "調理（食物BUFF）と錬金術（ポーション）が最も収益性が高い。"),
        section("beginner-tips", "初心者ヒント", "1. 最終製品を先に決定；2. 調理+採集=最適な初心者コンビ；3. オークションハウスを監視；4. 日次クエスト；5. ギルドに参加。"),
      ],
    }),
    "pt-br": articleCopy(guideLabels, "pt-br", 10, {
      eyebrow: "GUIA DE FABRICAÇÃO",
      title: "Guia completo de fabricação e habilidades de vida do AION 2: De iniciante a lucrativo",
      description: "Análise completa do sistema de fabricação: 6 profissões, 4 de coleta, aquisição de materiais",
      intro: "O sistema de fabricação do AION 2 é o núcleo da economia do jogo.",
      keywords: ["Fabricação AION 2", "Habilidades de vida AION 2", "Ouro AION 2", "Coleta AION 2", "Profissões AION 2"],
      sourceNote: "Baseado no guia oficial da NCSoft e guia econômico do AION2T (2 de setembro de 2026).",
      sections: [
        section("crafting-professions-overview", "Visão geral das profissões de fabricação", "6 profissões: Forja de armas, Forja de armaduras, Alfaiataria, Alquimia, Culinária, Artesanato. Máx 2 por personagem."),
        section("gathering-professions", "Profissões de coleta", "4 profissões: Mineração, Lenhador, Coleta, Esfolamento. Máx 3 por personagem."),
        section("leveling-crafting", "Rota de subida de fabricação", "Nível 1-50. Cinza 1-10, verde 10-30, azul 30-40, roxo/ouro 40-50."),
        section("profit-strategies", "Estratégias de lucro", "Culinária (BUFFs de comida) e Alquimia (poções) são as mais lucrativas."),
        section("beginner-tips", "Dicas para iniciantes", "1. Escolher produto final primeiro; 2. Culinária + Coleta = melhor combo iniciante; 3. Observar casa de leilões; 4. Missões diárias; 5. Entrar em guilda."),
      ],
    }),
    ru: articleCopy(guideLabels, "ru", 10, {
      eyebrow: "РУКОВОДСТВО ПО РЕМЕСЛУ",
      title: "Полное руководство по ремеслу и жизненным навыкам AION 2: От новичка до прибыльного",
      description: "Полный анализ системы ремесла: 6 профессий, 4 собирающих, получение материалов",
      intro: "Система ремесла AION 2 — ядро игровой экономики.",
      keywords: ["Ремесло AION 2", "Жизненные навыки AION 2", "Золото AION 2", "Сбор AION 2", "Профессии AION 2"],
      sourceNote: "На основе официального руководства NCSoft и экономического руководства AION2T (2 сентября 2026 г.).",
      sections: [
        section("crafting-professions-overview", "Обзор ремесленных профессий", "6 профессий: Оружейник, Бронник, Портной, Алхимия, Кулинария, Ремесло. Макс 2 на персонажа."),
        section("gathering-professions", "Собирающие профессии", "4 профессии: Горное дело, Лесоруб, Травник, Снятие шкур. Макс 3 на персонажа."),
        section("leveling-crafting", "Маршрут прокачки ремесла", "Уровень 1-50. Серые 1-10, зелёные 10-30, синие 30-40, фиолетовые/золотые 40-50."),
        section("profit-strategies", "Стратегии прибыли", "Кулинария (баффы еды) и Алхимия (зелья) — самые прибыльные."),
        section("beginner-tips", "Советы новичкам", "1. Сначала выбрать конечный продукт; 2. Кулинария + Сбор = лучшее комбо новичка; 3. Следить за аукционом; 4. Ежедневные квесты; 5. Вступить в гильдию."),
      ],
    }),
    ko: articleCopy(guideLabels, "ko", 10, {
      eyebrow: "제작 가이드",
      title: "AION 2 제작 및 생활 스킬 완전 가이드: 초보자부터 수익화까지",
      description: "제작 시스템의 완전한 분석: 6대 제작 전문, 4대 채집 전문, 재료 획득",
      intro: "AION 2의 제작 시스템은 게임 경제의 핵심입니다.",
      keywords: ["AION 2 제작", "AION 2 생활 스킬", "AION 2 골드", "AION 2 채집", "AION 2 제작 전문"],
      sourceNote: "NCSoft 공식 제작 가이드 및 AION2T 제작 경제 가이드(2026-09-02) 기반.",
      sections: [
        section("crafting-professions-overview", "제작 전문 개요", "6대 전문: 무기 단조, 갑옷 단조, 재봉, 연금술, 조리, 공예. 캐릭터당 최대 2개."),
        section("gathering-professions", "채집 전문", "4대 전문: 채광, 벌목, 채집, 수렵. 캐릭터당 최대 3개."),
        section("leveling-crafting", "제작 레벨 루트", "레벨 1-50. 회색 1-10, 녹색 10-30, 청색 30-40, 보라/금 40-50."),
        section("profit-strategies", "수익 전략", "조리(음식 버프)와 연금술(포션)이 가장 수익성이 높습니다."),
        section("beginner-tips", "초보자 팁", "1. 최종 제품 먼저 결정; 2. 조리+채집=최적 초보자 조합; 3. 경매장 주시; 4. 일일 퀘스트; 5. 길드 가입."),
      ],
    }),
    "zh-hant": articleCopy(guideLabels, "zh-hant", 10, {
      eyebrow: "製作指南",
      title: "AION 2 製作與生活技能完整指南：從入門到賺錢",
      description: "全面解析AION 2的製作系統：6大製作專業、4大採集專業、材料獲取、裝備製作流程、以及如何通過製作系統賺取金幣",
      intro: "AION 2 的製作系統是遊戲經濟的核心。本文將全面解析製作專業的選擇、升級路線、以及賺錢策略，幫助你在遊戲中建立穩定的收入來源。",
      keywords: ["AION 2 製作", "AION 2 生活技能", "AION 2 賺錢", "AION 2 採集", "AION 2 製作專業"],
      sourceNote: "基於 NCSoft 官方製作指南和 AION2T 製作經濟攻略（2026-09-02）整理。",
      sections: [
        section("crafting-professions-overview", "製作專業概覽", "AION 2 有 6 大製作專業：武器鍛造（近戰武器）、盔甲鍛造（板甲）、裁縫（布甲/皮甲）、煉金術（藥水/卷軸）、烹飪（食物BUFF）、工藝（飾品/寶石）。每個角色最多同時學習 2 個製作專業。升級製作專業需要消耗材料和金幣，建議先確定目標產品再選擇專業。"),
        section("gathering-professions", "採集專業", "4 大採集專業與製作專業配套：採礦（配合鍛造）、採伐（配合工藝）、採集（配合煉金/烹飪）、狩獵（配合裁縫）。每個角色可同時擁有 3 個採集專業。採集點在世界地圖上有固定刷新位置，高級材料需要更高的採集等級。競爭熱門採集點是早期常見問題——建議錯峰採集或選擇冷门但高價值的材料。"),
        section("leveling-crafting", "製作專業升級路線", "製作專業從 1 級開始，最高 50 級。每級通過製作物品獲得經驗。建議升級路線：1-10 級製作灰色物品（最低材料消耗）；10-30 級製作綠色物品（可出售給 NPC）；30-40 級製作藍色物品（拍賣行有需求）；40-50 級製作紫色/金色物品（高利潤但材料昂貴）。每個整數等級（10/20/30/40/50）需要完成職業任務才能繼續升級。"),
        section("profit-strategies", "賺錢策略", "最賺錢的製作路線：烹飪（食物BUFF消耗量大，穩定需求）和煉金術（藥水是副本剛需）。中級賺錢：製作藍色裝備出售給練級中的玩家。高級賺錢：50級工藝製作傳說寶石——利潤高但材料成本也高。每日任務獎勵的'製作加速券'可以顯著降低升級成本。"),
        section("beginner-tips", "新手建議", "1. 先確定你要製作的最終產品，再選擇專業——不要盲目升級；2. 烹飪+採集是最佳新手組合——材料便宜、需求穩定；3. 在拍賣行觀察價格趨勢——了解什麼物品有利可圖；4. 利用每日採集任務——它們提供免費材料和經驗；5. 加入公會——公會製作加成可以節省 10-15% 材料消耗。"),
      ],
    }),
  },
};
