import {
  articleCopy,
  localizations,
  guideLabels,
  publishedVerified,
  section,
} from "./trending-september-5-shared";
import type { ContentSource, ContentHeroImage } from "./content-registry";

const officialEndgameSource: ContentSource = {
  id: "ncsoft-endgame-guide",
  kind: "official",
  publisher: "NCSoft",
  label: "AION 2 Official Guide — Endgame Content",
  url: "https://aion2.plaync.com/en-us/game/guide/abyss",
  publishedAt: "2026-08-20",
  retrievedAt: "2026-09-05",
  verifiedAt: "2026-09-05",
  localizations: localizations(
    {
      "zh-hans": "AION 2 官方指南 — 满级内容", en: "AION 2 Official Guide — Endgame Content", fr: "Guide officiel d'AION 2 — Contenu fin de jeu",
      de: "AION 2 Offizieller Leitfaden — Endgame-Inhalte", es: "Guía oficial de AION 2 — Contenido endgame", ja: "AION 2 公式ガイド — エンドゲームコンテンツ",
      "pt-br": "Guia oficial do AION 2 — Conteúdo endgame", ru: "Официальное руководство AION 2 — Эндшпиль", ko: "AION 2 공식 가이드 — 엔드게임 콘텐츠", "zh-hant": "AION 2 官方指南 — 滿級內容",
    },
    "https://aion2.plaync.com/en-us/game/guide/abyss",
  ),
};

const communityEndgameSource: ContentSource = {
  id: "aion2hub-endgame-roadmap",
  kind: "third-party",
  publisher: "AION2Hub",
  label: "AION 2 Endgame Roadmap: What to Do After Level 40",
  url: "https://aion2hub.com/guides/endgame-roadmap/",
  publishedAt: "2026-09-04",
  retrievedAt: "2026-09-05",
  verifiedAt: "2026-09-05",
  localizations: localizations(
    {
      "zh-hans": "AION 2 满级后路线图：40级后做什么", en: "AION 2 Endgame Roadmap: What to Do After Level 40", fr: "Feuille de route endgame d'AION 2 : Que faire après le niveau 40",
      de: "AION 2 Endgame-Fahrplan: Was nach Stufe 40 tun", es: "Hoja de ruta endgame de AION 2: Qué hacer después del nivel 40", ja: "AION 2 エンドゲームロードマップ：レベル40後にすること",
      "pt-br": "Roteiro endgame do AION 2: O que fazer após o nível 40", ru: "Дорожная карта эндшпиля AION 2: Что делать после 40 уровня", ko: "AION 2 엔드게임 로드맵: 40레벨 이후 할 일", "zh-hant": "AION 2 滿級後路線圖：40級後做什麼",
    },
    "https://aion2hub.com/guides/endgame-roadmap/",
  ),
};

const hero: ContentHeroImage = {
  src: "https://blogfiles.ncsoft.net/news/af7330da-4ff6-4b58-aece-400e6061a3be.jpg",
  width: 1200, height: 630, credit: "NC Corporation",
  sourceUrl: "https://aion2.plaync.com/en-us/game/guide/abyss",
  rights: "linked-official-media",
  translations: {
    "zh-hans": { alt: "AION 2 满级后进度路线图", caption: "40级后的完整进度路线：深渊、副本、PVP。" },
    en: { alt: "AION 2 Endgame Progression Roadmap", caption: "Complete post-40 progression: Abyss, dungeons, PVP." },
    fr: { alt: "Feuille de route endgame d'AION 2", caption: "Progression post-40 complète : Abysses, donjons, PVP." },
    de: { alt: "AION 2 Endgame-Fortschrittsfahrplan", caption: "Vollständiger Fortschritt nach 40: Abgrund, Dungeons, PVP." },
    es: { alt: "Hoja de ruta endgame de AION 2", caption: "Progresión post-40 completa: Abismo, mazmorras, PVP." },
    ja: { alt: "AION 2 エンドゲーム進行ロードマップ", caption: "40以降の完全進行：深淵、ダンジョン、PVP。" },
    "pt-br": { alt: "Roteiro de progressão endgame do AION 2", caption: "Progressão pós-40 completa: Abismo, masmorras, PVP." },
    ru: { alt: "Дорожная карта прогресса эндшпиля AION 2", caption: "Полный прогресс после 40: Бездна, подземелья, PVP." },
    ko: { alt: "AION 2 엔드게임 진행 로드맵", caption: "40레벨 이후 완전한 진행: 심연, 던전, PVP." },
    "zh-hant": { alt: "AION 2 滿級後進度路線圖", caption: "40級後的完整進度路線：深淵、副本、PVP。" },
  },
};

export const trendingSeptember5Article4 = {
  section: "guides" as const,
  slug: "aion-2-endgame-progression-roadmap",
  schemaType: "Article" as const,
  publishedAt: "2026-09-05", updatedAt: "2026-09-05",
  readingMinutes: 11,
  publication: publishedVerified,
  sources: [officialEndgameSource, communityEndgameSource],
  heroImage: hero,
  related: [
    { kind: "content" as const, section: "guides" as const, slug: "aion-2-abyss-system-complete-guide" },
    { kind: "content" as const, section: "guides" as const, slug: "aion-2-crafting-life-skills-complete-guide" },
    { kind: "content" as const, section: "guides" as const, slug: "aion-2-solo-leveling-guide-40-cap" },
  ],
  translations: {
    "zh-hans": articleCopy(guideLabels, "zh-hans", 11, {
      eyebrow: "满级指南",
      title: "AION 2 满级后完整进度路线图：40级之后做什么",
      description: "从40级满级到真正毕业：深渊PVP入门、传说副本攻略、装备获取路线、公会战争参与、以及每日/每周必做清单",
      intro: "达到40级只是AION 2的开始。满级后有大量内容等待探索：深渊PVP、高级副本、装备进阶、公会战等。本文将为你规划一条清晰的满级后进度路线。",
      keywords: ["AION 2 满级", "AION 2 满级后", "AION 2 深渊", "AION 2 传说装备", "AION 2 每日任务"],
      sourceNote: "基于 NCSoft 官方满级指南和 AION2Hub 满级路线图（2026-09-04）整理。",
      sections: [
        section("first-week-priorities", "满级第一周优先事项", "1. 完成满级主线任务链——奖励首套蓝色装备；2. 加入活跃公会——公会技能加成对满级内容至关重要；3. 开始深渊PVP入门——先在低层区域熟悉机制；4. 每日深渊任务不可错过——提供AP和装备材料；5. 了解副本时间表——高级副本有固定开放时间。"),
        section("abyss-pvp-entry", "深渊PVP入门", "深渊是AION 2的核心PVP系统。入门建议：从下层Reshanta开始，这里的敌人等级较低；先观察再参战——学习种族间的战术配合；加入公会PVP团队——团队协作远比个人技术重要；每天至少参加一次要塞攻城战——即使失败也有AP奖励。深渊点数（AP）用于购买PVP专属装备和解锁种族等级。"),
        section("dungeon-progression", "副本进度路线", "满级副本分三个层级：普通（蓝色装备掉落）、英雄（紫色装备掉落）、传说（金色装备掉落）。建议顺序：先刷普通副本满蓝色装备→英雄副本刷紫色→传说副本需要组队配合。传说副本每周有次数限制，优先完成收益最高的Boss。副本中的掉落可以交易——与公会成员协调分配。"),
        section("gear-progression", "装备获取与进阶", "满级装备进阶路线：蓝色→紫色→金色→传说。每个阶段需要：更好的基础装备+强化材料+金币。强化有失败概率——使用保护卷轴可以降低损失。传说装备需要深渊Boss掉落的材料——这是PVP和PVE交汇的地方。制作专业也可以生产紫色装备——是装备来源的补充。"),
        section("daily-weekly-checklist", "每日/每周必做清单", "每日：深渊日常任务（AP+材料）、3次英雄副本（紫色装备）、公会捐献（公会技能经验）、采集专业日常（制作材料）。每周：传说副本（金色装备材料）、要塞攻城战（2次）、深渊Boss讨伐（传说材料）、竞技场赛季奖励（PVP装备）。每月：赛季PVP排名奖励、限时活动副本。", ),
      ],
    }),
    en: articleCopy(guideLabels, "en", 11, {
      eyebrow: "ENDGAME GUIDE",
      title: "AION 2 Endgame Progression Complete Roadmap: What to Do After Level 40",
      description: "From level 40 cap to truly graduated: Abyss PVP introduction, legendary dungeon攻略, gear acquisition route, guild war participation, and daily/weekly must-do checklist",
      intro: "Reaching level 40 is just the beginning of AION 2. After the cap, there's a wealth of content: Abyss PVP, high-tier dungeons, gear progression, guild wars, and more. This article plans a clear post-cap progression route for you.",
      keywords: ["AION 2 endgame", "AION 2 after 40", "AION 2 Abyss", "AION 2 legendary gear", "AION 2 daily quests"],
      sourceNote: "Based on NCSoft's official endgame guide and AION2Hub endgame roadmap (September 4, 2026).",
      sections: [
        section("first-week-priorities", "First Week Priorities at Cap", "1. Complete the endgame main quest chain — rewards first blue gear set; 2. Join an active guild — guild skill bonuses are crucial for endgame content; 3. Start Abyss PVP introduction — begin in lower-tier zones to learn mechanics; 4. Daily Abyss quests are must-dos — provide AP and gear materials; 5. Learn dungeon schedules — high-tier dungeons have fixed open times."),
        section("abyss-pvp-entry", "Abyss PVP Introduction", "The Abyss is AION 2's core PVP system. Getting started: begin in Lower Reshanta where enemies are lower level; observe before engaging — learn inter-race tactical coordination; join guild PVP teams — teamwork matters far more than individual skill; participate in at least one fortress siege daily — even losses give AP rewards. Abyss Points (AP) purchase PVP-exclusive gear and unlock racial ranks."),
        section("dungeon-progression", "Dungeon Progression Route", "Endgame dungeons have three tiers: Normal (blue gear drops), Heroic (purple gear drops), Legendary (gold gear drops). Recommended order: farm Normal for full blue gear → Heroic for purple → Legendary requires team coordination. Legendary dungeons have weekly limits — prioritize highest-value Bosses. Dungeon drops are tradeable — coordinate distribution with guildmates."),
        section("gear-progression", "Gear Acquisition and Progression", "Endgame gear progression: Blue → Purple → Gold → Legendary. Each stage needs: better base gear + enhancement materials + gold. Enhancement has failure chance — use protection scrolls to reduce losses. Legendary gear requires materials from Abyss Boss drops — where PVP and PVE intersect. Crafting professions can also produce purple gear — a supplementary gear source."),
        section("daily-weekly-checklist", "Daily/Weekly Must-Do Checklist", "Daily: Abyss daily quests (AP + materials), 3 Heroic dungeons (purple gear), guild donations (guild skill XP), gathering profession dailies (crafting materials). Weekly: Legendary dungeons (gold gear materials), fortress sieges (2x), Abyss Boss hunts (legendary materials), arena season rewards (PVP gear). Monthly: seasonal PVP rank rewards, limited-time event dungeons."),
      ],
    }),
    fr: articleCopy(guideLabels, "fr", 11, {
      eyebrow: "GUIDE ENDGAME",
      title: "Feuille de route complète de progression endgame d'AION 2 : Que faire après le niveau 40",
      description: "Du niveau 40 à la graduation : introduction PVP des Abysses, donjons légendaires, équipement, guerres de guilde",
      intro: "Atteindre le niveau 40 n'est que le début d'AION 2.",
      keywords: ["Endgame AION 2", "AION 2 après 40", "AION 2 Abysses", "Équipement légendaire AION 2", "Quêtes quotidiennes AION 2"],
      sourceNote: "Basé sur le guide officiel NCSoft et la feuille de route endgame d'AION2Hub (4 septembre 2026).",
      sections: [
        section("first-week-priorities", "Priorités de la première semaine", "1. Quêtes principales endgame — première set bleue ; 2. Guilde active ; 3. Introduction PVP Abysses ; 4. Quêtes quotidiennes Abysses ; 5. Horaires de donjons."),
        section("abyss-pvp-entry", "Introduction PVP des Abysses", "Commencez dans la Reshanta inférieure. Observez avant d'engager. Rejoignez les équipes PVP de guilde. Participer aux sièges quotidiens."),
        section("dungeon-progression", "Progression des donjons", "Trois niveaux : Normal (bleu), Héroïque (violet), Légendaire (or). Farm Normal → Héroïque → Légendaire en équipe."),
        section("gear-progression", "Progression d'équipement", "Bleu → Violet → Or → Légendaire. Amélioration avec risque d'échec — utiliser des parchemins de protection."),
        section("daily-weekly-checklist", "Checklist quotidienne/hebdomadaire", "Quotidien : quêtes Abysses, 3 donjons héroïques, dons de guilde, collecte. Hebdomadaire : donjons légendaires, sièges, boss, arène. Mensuel : récompenses de saison."),
      ],
    }),
    de: articleCopy(guideLabels, "de", 11, {
      eyebrow: "ENDGAME-LEITFADEN",
      title: "AION 2 Endgame-Fortschrittsfahrplan: Was nach Stufe 40 tun",
      description: "Von Stufe 40 bis zum Abschluss: Abgrund-PVP, legendäre Dungeons, Ausrüstung, Gildenkriege",
      intro: "Stufe 40 ist erst der Anfang von AION 2.",
      keywords: ["Endgame AION 2", "AION 2 nach 40", "AION 2 Abgrund", "Legendäre Ausrüstung AION 2", "Tägliche Quests AION 2"],
      sourceNote: "Basierend auf NCSofts offiziellem Endgame-Leitfaden und AION2Hub-Fahrplan (4. September 2026).",
      sections: [
        section("first-week-priorities", "Prioritäten der ersten Woche", "1. Endgame-Hauptquests — erstes blaues Set; 2. Aktive Gilde; 3. Abgrund-PVP-Einführung; 4. Tägliche Abgrund-Quests; 5. Dungeon-Zeitpläne."),
        section("abyss-pvp-entry", "Abgrund-PVP-Einführung", "In Unterer Reshanta beginnen. Beobachten vor dem Angriff. Gilden-PVP-Teams beitreten. Tägliche Belagerungen."),
        section("dungeon-progression", "Dungeon-Fortschritt", "Drei Stufen: Normal (blau), Heroisch (lila), Legendär (gold). Normal farmen → Heroisch → Legendär im Team."),
        section("gear-progression", "Ausrüstungsfortschritt", "Blau → Lila → Gold → Legendär. Verbesserung mit Fehlerrisiko — Schutzschriften verwenden."),
        section("daily-weekly-checklist", "Tägliche/Wöchentliche Checkliste", "Täglich: Abgrund-Quests, 3 heroische Dungeons, Gildenspenden, Sammeln. Wöchentlich: Legendäre Dungeons, Belagerungen, Bosse, Arena. Monatlich: Saisonbelohnungen."),
      ],
    }),
    es: articleCopy(guideLabels, "es", 11, {
      eyebrow: "GUÍA ENDGAME",
      title: "Hoja de ruta completa de progresión endgame de AION 2: Qué hacer después del nivel 40",
      description: "Del nivel 40 a la graduación: PVP del Abismo, mazmorras legendarias, equipo, guerras de hermandad",
      intro: "Alcanzar el nivel 40 es solo el comienzo de AION 2.",
      keywords: ["Endgame AION 2", "AION 2 después de 40", "AION 2 Abismo", "Equipo legendario AION 2", "Misiones diarias AION 2"],
      sourceNote: "Basado en la guía oficial de NCSoft y la hoja de ruta endgame de AION2Hub (4 de septiembre de 2026).",
      sections: [
        section("first-week-priorities", "Prioridades de la primera semana", "1. Misiones principales endgame — primer set azul; 2. Hermandad activa; 3. Introducción PVP Abismo; 4. Misiones diarias Abismo; 5. Horarios de mazmorras."),
        section("abyss-pvp-entry", "Introducción PVP del Abismo", "Comenzar en Reshanta inferior. Observar antes de atacar. Unirse a equipos PVP de hermandad. Asedios diarios."),
        section("dungeon-progression", "Progresión de mazmorras", "Tres niveles: Normal (azul), Heroico (púrpura), Legendario (oro). Farmear Normal → Heroico → Legendario en equipo."),
        section("gear-progression", "Progresión de equipo", "Azul → Púrpura → Oro → Legendario. Mejora con riesgo de fallo — usar pergaminos de protección."),
        section("daily-weekly-checklist", "Lista diaria/semanal", "Diario: misiones Abismo, 3 mazmorras heroicas, donaciones de hermandad, recolección. Semanal: mazmorras legendarias, asedios, jefes, arena. Mensual: recompensas de temporada."),
      ],
    }),
    ja: articleCopy(guideLabels, "ja", 11, {
      eyebrow: "エンドゲームガイド",
      title: "AION 2 エンドゲーム進行完全ロードマップ：レベル40後にすること",
      description: "レベル40から卒業まで：深淵PVP入門、伝説ダンジョン、装備取得ルート、ギルド戦争",
      intro: "レベル40到達はAION 2の始まりに過ぎません。",
      keywords: ["AION 2 エンドゲーム", "AION 2 40後", "AION 2 深淵", "AION 2 伝説装備", "AION 2 日次クエスト"],
      sourceNote: "NCSoft公式エンドゲームガイドおよびAION2Hubエンドゲームロードマップ（2026年9月4日）に基づく。",
      sections: [
        section("first-week-priorities", "1週目の優先事項", "1. エンドゲームメインクエスト — 最初の青セット；2. 活発なギルド；3. 深淵PVP入門；4. 日次深淵クエスト；5. ダンジョン时间表。"),
        section("abyss-pvp-entry", "深淵PVP入門", "下層Reshantaから開始。攻撃前に観察。ギルドPVPチームに参加。毎日の包囲戦。"),
        section("dungeon-progression", "ダンジョン進行", "3段階：通常（青）、英雄（紫）、伝説（金）。通常ファーム→英雄→伝説をチームで。"),
        section("gear-progression", "装備進行", "青→紫→金→伝説。強化は失敗リスクあり — 保護スクロールを使用。"),
        section("daily-weekly-checklist", "日次/週次チェックリスト", "日次：深淵クエスト、英雄ダンジョン3回、ギルド寄付、採集。週次：伝説ダンジョン、包囲戦、ボス、アリーナ。月次：シーズン報酬。"),
      ],
    }),
    "pt-br": articleCopy(guideLabels, "pt-br", 11, {
      eyebrow: "GUIA ENDGAME",
      title: "Roteiro completo de progressão endgame do AION 2: O que fazer após o nível 40",
      description: "Do nível 40 à formatura: PVP do Abismo, masmorras lendárias, equipamento, guerras de guilda",
      intro: "Atingir o nível 40 é apenas o começo do AION 2.",
      keywords: ["Endgame AION 2", "AION 2 após 40", "AION 2 Abismo", "Equipamento lendário AION 2", "Missões diárias AION 2"],
      sourceNote: "Baseado no guia oficial da NCSoft e roteiro endgame do AION2Hub (4 de setembro de 2026).",
      sections: [
        section("first-week-priorities", "Prioridades da primeira semana", "1. Missões principais endgame — primeiro set azul; 2. Guilda ativa; 3. Introdução PVP Abismo; 4. Missões diárias Abismo; 5. Horários de masmorras."),
        section("abyss-pvp-entry", "Introdução PVP do Abismo", "Começar na Reshanta inferior. Observar antes de atacar. Entrar em equipes PVP de guilda. Cercos diários."),
        section("dungeon-progression", "Progressão de masmorras", "Três níveis: Normal (azul), Heroico (roxo), Lendário (ouro). Farmear Normal → Heroico → Lendário em equipe."),
        section("gear-progression", "Progressão de equipamento", "Azul → Roxo → Ouro → Lendário. Melhoria com risco de falha — usar pergaminhos de proteção."),
        section("daily-weekly-checklist", "Lista diária/semanal", "Diário: missões Abismo, 3 masmorras heroicas, doações de guilda, coleta. Semanal: masmorras lendárias, cercos, chefes, arena. Mensal: recompensas de temporada."),
      ],
    }),
    ru: articleCopy(guideLabels, "ru", 11, {
      eyebrow: "РУКОВОДСТВО ПО ЭНДШПИЛЮ",
      title: "Полная дорожная карта прогресса эндшпиля AION 2: Что делать после 40 уровня",
      description: "От 40 уровня до завершения: введение в PVP Бездны, легендарные подземелья, получение снаряжения, гильдейские войны",
      intro: "Достижение 40 уровня — это только начало AION 2.",
      keywords: ["Эндшпиль AION 2", "AION 2 после 40", "AION 2 Бездна", "Легендарное снаряжение AION 2", "Ежедневные квесты AION 2"],
      sourceNote: "На основе официального руководства NCSoft и дорожной карты эндшпиля AION2Hub (4 сентября 2026 г.).",
      sections: [
        section("first-week-priorities", "Приоритеты первой недели", "1. Основные квесты эндшпиля — первый синий набор; 2. Активная гильдия; 3. Введение в PVP Бездны; 4. Ежедневные квесты Бездны; 5. Расписания подземелий."),
        section("abyss-pvp-entry", "Введение в PVP Бездны", "Начать в Нижней Рещанте. Наблюдать перед атакой. Присоединиться к PVP-командам гильдии. Ежедневные осады."),
        section("dungeon-progression", "Прогресс подземелий", "Три уровня: Обычные (синие), Героические (фиолетовые), Легендарные (золотые). Фармить Обычные → Героические → Легендарные в команде."),
        section("gear-progression", "Прогресс снаряжения", "Синее → Фиолетовое → Золотое → Легендарное. Улучшение с риском неудачи — использовать свитки защиты."),
        section("daily-weekly-checklist", "Ежедневный/еженедельный чеклист", "Ежедневно: квесты Бездны, 3 героических подземелья, пожертвования гильдии, сбор. Еженедельно: легендарные подземелья, осады, боссы, арена. Ежемесячно: сезонные награды."),
      ],
    }),
    ko: articleCopy(guideLabels, "ko", 11, {
      eyebrow: "엔드게임 가이드",
      title: "AION 2 엔드게임 진행 완전 로드맵: 40레벨 이후 할 일",
      description: "40레벨부터 졸업까지: 심연 PVP 입문, 전설 던전, 장비 획득 루트, 길드 전쟁 참여, 일일/주간 필수 체크리스트",
      intro: "40레벨 도달은 AION 2의 시작에 불과합니다. 만레 이후에는 심연 PVP, 고급 던전, 장비 강화, 길드전 등 방대한 콘텐츠가 기다리고 있습니다.",
      keywords: ["AION 2 엔드게임", "AION 2 만레 이후", "AION 2 심연", "AION 2 전설 장비", "AION 2 일일 퀘스트"],
      sourceNote: "NCSoft 공식 엔드게임 가이드 및 AION2Hub 엔드게임 로드맵(2026-09-04) 기반.",
      sections: [
        section("first-week-priorities", "만레 첫 주 우선사항", "1. 엔드게임 메인 퀘스트 체인 — 첫 파랑 장비 세트; 2. 활성 길드 가입 — 길드 스킬 보너스가 엔드게임에 필수; 3. 심연 PVP 입문 — 하층 구역에서 먼저 메커닉 익히기; 4. 일일 심연 퀘스트 필수 — AP와 장비 재료 제공; 5. 던전 시간표 확인 — 고급 던전은 정해진 시간에 열림."),
        section("abyss-pvp-entry", "심연 PVP 입문", "심연은 AION 2의 핵심 PVP 시스템입니다. 하층 레샨타에서 시작하면 적 레벨이 낮습니다. 참전 전에 관찰하며 종족 간 전술 협동을 배우세요. 길드 PVP 팀에 가입하면 개인 기량보다 팀워크가 훨씬 중요합니다. 매일 최소 1번 요새 공성전에 참여 — 패배해도 AP 보상이 있습니다."),
        section("dungeon-progression", "던전 진행 루트", "만레 던전은 3단계: 일반(파랑), 영웅(보라), 전설(금). 순서: 일반에서 파랑 장비 풀파밍 → 영웅에서 보라 → 전설은 팀 협력 필요. 전설 던전은 주간 횟수 제한 — 가장 수익 높은 보스 우선. 던전 드롭은 거래 가능 — 길드원과 배분 조율."),
        section("gear-progression", "장비 획득과 강화", "만레 장비 강화 루트: 파랑→보라→금→전설. 각 단계마다 필요한 것: 더 좋은 기본 장비 + 강화 재료 + 골드. 강화는 실패 확률 있음 — 보호 두루마리로 손실 감소. 전설 장비는 심연 보스 드롭 재료가 필요 — PVP와 PVE가 교차하는 지점. 제작 전문으로도 보라 장비 생산 가능."),
        section("daily-weekly-checklist", "일일/주간 필수 체크리스트", "일일: 심연 일일 퀘스트(AP+재료), 영웅 던전 3회(보라 장비), 길드 기부(길드 스킬 경험치), 채집 전문 일일(제작 재료). 주간: 전설 던전(금 장비 재료), 요새 공성전(2회), 심연 보스 토벌(전설 재료), 아레나 시즌 보상(PVP 장비). 월간: 시즌 PVP 랭킹 보상, 기간한정 이벤트 던전."),
      ],
    }),
    "zh-hant": articleCopy(guideLabels, "zh-hant", 11, {
      eyebrow: "滿級指南",
      title: "AION 2 滿級後完整進度路線圖：40級之後做什麼",
      description: "從40級滿級到真正畢業：深淵PVP入門、傳說副本攻略、裝備獲取路線、公會戰爭參與、以及每日/每週必做清單",
      intro: "達到40級只是AION 2的開始。滿級後有大量內容等待探索：深淵PVP、高級副本、裝備進階、公會戰等。本文將為你規劃一條清晰的滿級後進度路線。",
      keywords: ["AION 2 滿級", "AION 2 滿級後", "AION 2 深淵", "AION 2 傳說裝備", "AION 2 每日任務"],
      sourceNote: "基於 NCSoft 官方滿級指南和 AION2Hub 滿級路線圖（2026-09-04）整理。",
      sections: [
        section("first-week-priorities", "滿級第一週優先事項", "1. 完成滿級主線任務鏈——獎勵首套藍色裝備；2. 加入活躍公會——公會技能加成對滿級內容至關重要；3. 開始深淵PVP入門——先在下層區域熟悉機制；4. 每日深淵任務不可錯過——提供AP和裝備材料；5. 了解副本時間表——高級副本有固定開放時間。"),
        section("abyss-pvp-entry", "深淵PVP入門", "深淵是AION 2的核心PVP系統。入門建議：從下層Reshanta開始，這裡的敵人等級較低；先觀察再參戰——學習種族間的戰術配合；加入公會PVP團隊——團隊協作遠比個人技術重要；每天至少參加一次要塞攻城戰——即使失敗也有AP獎勵。深淵點數（AP）用於購買PVP專屬裝備和解鎖種族等級。"),
        section("dungeon-progression", "副本進度路線", "滿級副本分三個層級：普通（藍色裝備掉落）、英雄（紫色裝備掉落）、傳說（金色裝備掉落）。建議順序：先刷普通副本滿藍色裝備→英雄副本刷紫色→傳說副本需要組隊配合。傳說副本每週有次數限制，優先完成收益最高的Boss。副本中的掉落可以交易——與公會成員協調分配。"),
        section("gear-progression", "裝備獲取與進階", "滿級裝備進階路線：藍色→紫色→金色→傳說。每個階段需要：更好的基礎裝備+強化材料+金幣。強化有失敗機率——使用保護卷軸可以降低損失。傳說裝備需要深淵Boss掉落的材料——這是PVP和PVE交匯的地方。製作專業也可以生產紫色裝備——是裝備來源的補充。"),
        section("daily-weekly-checklist", "每日/每週必做清單", "每日：深淵日常任務（AP+材料）、3次英雄副本（紫色裝備）、公會捐獻（公會技能經驗）、採集專業日常（製作材料）。每週：傳說副本（金色裝備材料）、要塞攻城戰（2次）、深淵Boss討伐（傳說材料）、競技場賽季獎勵（PVP裝備）。每月：賽季PVP排名獎勵、限時活動副本。"),
      ],
    }),
  },
};
