import { articleCopy, localizations, guideLabels, publishedVerified, section } from "./trending-september-16-shared";
import type { ContentEntry, ContentHeroImage, ContentSource } from "./content-registry";

const roadmapSource: ContentSource = {
  id: "nc-aion2-official-roadmap",
  kind: "official",
  publisher: "NC Corporation",
  label: "Aion 2 Official — Gameplay Overview",
  url: "https://aion2.plaync.com/en-us/gameplay/",
  publishedAt: "2026-08-15",
  retrievedAt: "2026-09-16",
  verifiedAt: "2026-09-16",
  localizations: localizations({
    "zh-hans": "Aion 2 官方 — 游戏概览", en: "Aion 2 Official — Gameplay Overview",
    fr: "Aion 2 Officiel — Aperçu du Gameplay", de: "Aion 2 Offiziell — Gameplay-Übersicht",
    es: "Aion 2 Oficial — Resumen de Jugabilidad", ja: "Aion 2 公式 — ゲームプレイ概要",
    "pt-br": "Aion 2 Oficial — Visão Geral do Gameplay", ru: "Aion 2 Официальный — Обзор Геймплея",
    ko: "Aion 2 공식 — 게임플레이 개요", "zh-hant": "Aion 2 官方 — 遊戲概覽",
  }, "https://aion2.plaync.com/en-us/gameplay/"),
};

const roadmapHero: ContentHeroImage = {
  src: "https://blogfiles.ncsoft.net/news/af7330da-4ff6-4b58-aece-400e6061a3be.jpg",
  width: 1200, height: 630,
  credit: "NC Corporation", sourceUrl: "https://aion2.plaync.com/en-us/", rights: "linked-official-media",
  translations: {
    "zh-hans": { alt: "Aion 2 首周路线攻略横幅", caption: "Aion 2 新人前 7 天路线规划——每天的关键目标、装备优先级和常见错误。" },
    en: { alt: "Aion 2 First Week Roadmap Banner", caption: "Aion 2 new player 7-day progression roadmap — daily milestones, gear priorities, and common mistakes to avoid." },
    fr: { alt: "Bannière Feuille de Route Première Semaine Aion 2", caption: "Feuille de route 7 jours pour nouveaux joueurs Aion 2 — étapes quotidiennes, priorités d'équipement et erreurs courantes." },
    de: { alt: "Aion 2 Erste Woche Roadmap Banner", caption: "Aion 2 7-Tage Roadmap für neue Spieler — tägliche Meilensteine, Ausrüstungsprioritäten und häufige Fehler." },
    es: { alt: "Banner Hoja de Ruta Primera Semana Aion 2", caption: "Hoja de ruta de 7 días para nuevos jugadores de Aion 2 — hitos diarios, prioridades de equipo y errores comunes." },
    ja: { alt: "Aion 2 初週ロードマップバナー", caption: "Aion 2 新規プレイヤー7日進行ロードマップ — 日次目標、装備優先度、よくある間違い。" },
    "pt-br": { alt: "Banner Roteiro Primeira Semana Aion 2", caption: "Roteiro de 7 dias para novos jogadores do Aion 2 — marcos diários, prioridades de equipamento e erros comuns." },
    ru: { alt: "Баннер Дорожная Карта Первой Недели Aion 2", caption: "Дорожная карта на 7 дней для новых игроков Aion 2 — ежедневные цели, приоритеты экипировки и типичные ошибки." },
    ko: { alt: "Aion 2 첫 주 로드맵 배너", caption: "Aion 2 신규 플레이어 7일 진행 로드맵 — 일일 목표, 장비 우선순위, 흔한 실수." },
    "zh-hant": { alt: "Aion 2 首週路線攻略橫幅", caption: "Aion 2 新人前 7 天路線規劃——每天的關鍵目標、裝備優先級和常見錯誤。" },
  },
};

export const trendingSeptember16Article2: ContentEntry = {
  section: "guides",
  slug: "aion-2-first-week-roadmap-guide",
  schemaType: "Article",
  publishedAt: "2026-09-16",
  updatedAt: "2026-09-16",
  readingMinutes: 7,
  publication: publishedVerified,
  sources: [roadmapSource],
  heroImage: roadmapHero,
  related: [
    { kind: "content", section: "guides", slug: "aion-2-leveling-guide-1-50" },
    { kind: "content", section: "guides", slug: "aion-2-daily-weekly-routine-guide" },
    { kind: "content", section: "guides", slug: "aion-2-questing-leveling-guide" },
    { kind: "content", section: "guides", slug: "aion-2-early-game-free-gear-progression-guide" },
  ],
  translations: {
    en: articleCopy(guideLabels, "en", 7, {
      eyebrow: "NEW PLAYERS",
      title: "Aion 2 First Week Roadmap: Your 7-Day Progression Plan from Character Creation to Endgame Prep",
      description: "A structured 7-day roadmap for Aion 2 new players. Follow this day-by-day plan to maximize your early progression, avoid common mistakes, and reach endgame-ready status efficiently.",
      intro: "The first week in Aion 2 sets the foundation for your entire progression. This roadmap breaks down each day into achievable milestones, helping you balance questing, exploration, combat skill development, and social connections without burning out or wasting resources.",
      sourceNote: "Based on NC's official gameplay guides and the Korean service progression system as of September 2026. Global launch timing and content availability may differ.",
      keywords: ["Aion 2 first week guide", "Aion 2 new player roadmap", "Aion 2 7 day guide", "Aion 2 beginner progression", "Aion 2 early game guide"],
      sections: [
        section("day-1-3", "Days 1-3: Building Your Foundation", ["Day 1 focuses on class selection and the introductory quest chain. Take your time choosing a class — watch the skill preview videos and consider your preferred playstyle rather than rushing into a meta pick. Complete the tutorial zone thoroughly; it teaches core combat mechanics that you will rely on throughout the game.", "Days 2-3 cover the first major zone and unlock the core progression systems. You will reach approximately level 15-18 by the end of Day 3, unlock your first Stigma slots, and gain access to the first dungeon. Prioritize main story quests over side content during this phase — the XP efficiency is significantly better.", "Focus on learning your class rotation before worrying about optimization. Practice your basic skill combo on normal mobs, learn to dodge telegraphed attacks, and understand your role in group content. The combat system rewards active play, so building muscle memory early pays dividends later."]),
        section("day-4-5", "Days 4-5: Expanding Your Horizons", ["Day 4 is when you should join a guild and start exploring group content. Aion 2's dungeon system becomes available around this point, and having a consistent group makes the experience much smoother. Look for guilds that match your playstyle and schedule — active guilds provide significant XP bonuses and market access.", "Day 5 covers unlocking key secondary systems: crafting basics, the brokerage market, and your first skill preset swap. Experiment with different skill combinations to find what works for your preferred content. The skill preset system is one of Aion 2's most powerful features — use it to adapt to different situations.", "By the end of Day 5, you should be around level 25-28. At this point, start thinking about your gear upgrade path. Save your enhancement materials for your primary weapon first — weapon upgrades have the largest impact on damage output."]),
        section("day-6-7", "Days 6-7: Optimization and Social Integration", ["Day 6 focuses on gear optimization and PvP introduction. Try your first Battleground match to understand the PvP meta, even if you plan to focus on PvE. Understanding PvP mechanics helps in all combat situations. Also begin your daily routine — establish which dailies and weeklies are worth your time.", "Day 7 is about consolidating your progress and planning ahead. Review your skill presets, ensure your gear enhancement is on track, and connect with your guild for upcoming group content. Set goals for week 2: specific dungeons, PvP rank targets, or crafting milestones.", "The weekend is also a good time to explore the player economy. Check brokerage prices for your crafting materials, identify profitable gathering routes, and consider investing in useful consumables for the week ahead."]),
        section("gear-priorities", "Gear Priority Order: What to Upgrade First", ["Your weapon is always the first priority. Weapon upgrades directly increase your damage output, which affects everything from questing speed to dungeon performance. Upgrade your weapon as soon as you can afford it, and do not waste materials on armor until your weapon is current.", "Armor upgrades come second, but focus on pieces that complement your role. Tanks should prioritize defense stats, DPS classes should look for attack power, and healers should focus on healing amplification. Do not chase perfect stats on early gear — you will replace it quickly.", "Accessories and cosmetics are lowest priority. Accessories provide small stat bonuses that become meaningful only at higher levels. Cosmetics are purely aesthetic and can be acquired gradually. Focus your Kinah on functional upgrades during the first week."]),
        section("common-mistakes", "Common First Week Mistakes to Avoid", ["Do not rush to max level without learning your class. Many new players skip tutorials and story content to reach endgame quickly, but endgame content requires competent play. A well-played lower-level character outperforms a rushed max-level player who does not understand their skills.", "Do not spend Kinah on cosmetic items during your first week. The temptation to customize your character is strong, but functional upgrades — weapon enhancement, skill unlocks, crafting materials — provide far more value in the early game.", "Do not ignore the social systems. Aion 2 is a social MMO, and guild membership provides significant benefits including XP bonuses, group finding, and market access. Players who skip guild joining in the first week fall behind those who integrate socially from the start."]),
      ],
    }),
    "zh-hans": articleCopy(guideLabels, "zh-hans", 7, {
      eyebrow: "新手",
      title: "Aion 2 首周路线：从角色创建到后期准备的 7 天进阶规划",
      description: "为 Aion 2 新玩家设计的结构化 7 天路线图。按此逐日计划最大化早期进阶、避免常见错误并高效达到后期就绪状态。",
      intro: "Aion 2 的第一周为整个进阶奠定基础。本路线将每天分解为可实现的目标，帮助你平衡任务、探索、战斗技巧发展和社交联系，避免疲劳或浪费资源。",
      sourceNote: "基于 NC 官方攻略指南和韩服进阶系统（截至 2026 年 9 月）。全球版时间和内容可能有差异。",
      keywords: ["Aion 2 首周攻略", "Aion 2 新手路线", "Aion 2 7天攻略", "Aion 2 新手进阶", "Aion 2 前期攻略"],
      sections: [
        section("day-1-3", "第 1-3 天：建立基础", ["第 1 天重点是职业选择和入门任务链。花时间选择职业——观看技能预览视频，考虑你偏好的玩法而非追求 meta。彻底完成教程区域；它教授核心战斗机制，贯穿整个游戏。", "第 2-3 天覆盖第一个主要区域并解锁核心进阶系统。到第 3 天结束约达到 15-18 级，解锁第一组烙印槽，并获得第一个副本入口。此阶段优先主线任务而非支线——经验效率明显更高。", "在担心优化之前先学会你的职业循环。在普通怪物上练习基础技能连招，学会躲避预告攻击，理解你在团队内容中的角色。战斗系统奖励主动操作，早期建立肌肉记忆后期收益巨大。"]),
        section("day-4-5", "第 4-5 天：拓展视野", ["第 4 天应该加入公会并开始探索团队内容。Aion 2 的副本系统大约在此时开放，稳定的团队让体验更顺畅。寻找符合你玩法和时间的公会——活跃公会提供显著经验加成和市场渠道。", "第 5 天覆盖解锁关键次要系统：制作基础、交易所和第一次技能预设切换。尝试不同技能组合找到适合你偏好内容的方式。技能预设系统是 Aion 2 最强大的功能之一——用它适应不同情况。", "到第 5 天结束应在 25-28 级左右。此时开始考虑装备升级路线。将强化材料优先用于主武器——武器升级对伤害输出影响最大。"]),
        section("day-6-7", "第 6-7 天：优化与社交整合", ["第 6 天聚焦装备优化和 PvP 入门。参加第一次战场对局了解 PvP meta，即使你计划专注 PvE。理解 PvP 机制对所有战斗情况都有帮助。同时开始你的日常流程——确定哪些日常和周常值得投入时间。", "第 7 天是巩固进度和规划未来。回顾你的技能预设，确保装备强化在正轨上，联系公会准备即将到来的团队内容。设定第 2 周目标：特定副本、PvP 段位目标或制作里程碑。", "周末也是探索玩家经济的好时机。查看交易所材料价格，识别有利可图的采集路线，考虑投资下周有用的消耗品。"]),
        section("gear-priorities", "装备优先顺序：先升级什么", ["武器始终是第一优先。武器升级直接增加伤害输出，影响从任务速度到副本表现的方方面面。能负担得起就立刻升级武器，武器没跟上之前不要将材料浪费在护甲上。", "护甲升级其次，但聚焦符合你角色的部件。坦克优先防御属性，DPS 职业寻找攻击力，治疗聚焦治疗增幅。不要在早期装备上追求完美属性——你会很快替换它们。", "饰品和外观最低优先。饰品提供的小属性加成只在高等级才有意义。外观纯装饰，可以慢慢获取。第一周将 Kinah 聚焦在功能性升级上。"]),
        section("common-mistakes", "应避免的常见首周错误", ["不要在学习职业之前就急着满级。许多新玩家跳过教程和故事内容快速冲到后期，但后期内容需要熟练的操作。一个操作良好的低级角色胜过不理解技能的急躁满级玩家。", "第一周不要在外观物品上花 Kinah。定制角色的诱惑很强，但功能性升级——武器强化、技能解锁、制作材料——在早期提供的价值远超外观。", "不要忽视社交系统。Aion 2 是社交 MMO，公会成员资格提供显著福利包括经验加成、组队和市场渠道。第一周跳过公会的玩家会落后于从一开始就社交整合的玩家。"]),
      ],
    }),
    fr: articleCopy(guideLabels, "fr", 7, {
      eyebrow: "NOUVEAUX JOUEURS",
      title: "Feuille de Route Première Semaine d'Aion 2 : Votre Plan de Progression en 7 Jours",
      description: "Feuille de route structurée en 7 jours pour les nouveaux joueurs d'Aion 2. Suivez ce plan jour par jour pour maximiser votre progression initiale.",
      intro: "La première semaine dans Aion 2 pose les fondations de toute votre progression. Cette feuille de route décompose chaque jour en objectifs réalisables.",
      sourceNote: "Basé sur les guides gameplay officiels de NC et le système de progression du serveur coréen (septembre 2026).",
      keywords: ["Guide première semaine Aion 2", "Roadmap nouveau joueur Aion 2", "Guide 7 jours Aion 2", "Progression débutant Aion 2"],
      sections: [
        section("day-1-3", "Jours 1-3 : Construire Vos Fondations", ["Le Jour 1 se concentre sur le choix de classe et la chaîne de quêtes introductive. Prenez votre temps pour choisir une classe — regardez les vidéos d'aperçu des compétences.", "Les Jours 2-3 couvrent la première zone majeure et le déblocage des systèmes de progression fondamentaux. Vous atteindrez environ le niveau 15-18 à la fin du Jour 3.", "Concentrez-vous sur l'apprentissage de votre rotation de classe avant de vous soucier de l'optimisation."]),
        section("day-4-5", "Jours 4-5 : Élargir Vos Horizons", ["Le Jour 4 est le moment de rejoindre une guilde et de commencer à explorer le contenu de groupe. Rejoignez des guildes qui correspondent à votre style de jeu.", "Le Jour 5 couvre le déblocage des systèmes secondaires clés : bases de l'artisanat, marché de courtage et premier changement de preset de compétences.", "À la fin du Jour 5, vous devriez être environ niveau 25-28. Commencez à penser à votre chemin d'amélioration d'équipement."]),
        section("day-6-7", "Jours 6-7 : Optimisation et Intégration Sociale", ["Le Jour 6 se concentre sur l'optimisation d'équipement et l'introduction au PvP. Essayez votre premier match de Champ de Bataille.", "Le Jour 7 consolide votre progression et planifie l'avenir. Révisez vos presets de compétences, assurez-vous que votre amélioration d'équipement est en bonne voie.", "Le week-end est aussi un bon moment pour explorer l'économie des joueurs."]),
        section("gear-priorities", "Ordre de Priorité d'Équipement", ["Votre arme est toujours la première priorité. Les améliorations d'arme augmentent directement vos dégâts.", "Les améliorations d'armure viennent en second, mais concentrez-vous sur les pièces qui complètent votre rôle.", "Les accessoires et cosmétiques sont la priorité la plus basse. Concentrez votre Kinah sur les améliorations fonctionnelles."]),
        section("common-mistakes", "Erreurs Courantes de la Première Semaine", ["Ne vous précipitez pas au niveau max sans apprendre votre classe. Un personnage de bas niveau bien joué surpasse un joueur max level pressé qui ne comprend pas ses compétences.", "Ne dépensez pas de Kinah en cosmétiques durant la première semaine. Les améliorations fonctionnelles fournissent beaucoup plus de valeur.", "N'ignorez pas les systèmes sociaux. L'adhésion à une guilde fournit des bonus d'XP significatifs et un accès au marché."]),
      ],
    }),
    de: articleCopy(guideLabels, "de", 7, {
      eyebrow: "NEUE SPIELER",
      title: "Aion 2 Erste Woche Roadmap: Ihr 7-Tage Fortschrittsplan",
      description: "Strukturierter 7-Tage Roadmap für Aion 2 Neuspieler. Folgen Sie diesem Tagesplan um Ihre frühe Progression zu maximieren.",
      intro: "Die erste Woche in Aion 2 legt das Fundament für Ihre gesamte Progression.",
      sourceNote: "Basierend auf NCs offiziellen Gameplay-Guides und dem koreanischen Server (September 2026).",
      keywords: ["Aion 2 erste Woche Guide", "Aion 2 Neuspieler Roadmap", "Aion 2 7 Tage Guide"],
      sections: [
        section("day-1-3", "Tag 1-3: Grundlagen Aufbauen", ["Tag 1 konzentriert sich auf Klassenwahl und die Einführungs-Questkette. Nehmen Sie sich Zeit bei der Klassenwahl.", "Tag 2-3 deckt die erste Hauptzone ab und schaltet Kern-Fortschrittssysteme frei. Sie erreichen etwa Level 15-18 am Ende von Tag 3.", "Konzentrieren Sie sich darauf, Ihre Klassen-Rotation zu lernen bevor Sie sich um Optimierung kümmern."]),
        section("day-4-5", "Tag 4-5: Horizonte Erweitern", ["Tag 4 sollten Sie einer Gilde beitreten und Gruppeninhalte erkunden.", "Tag 5 deckt das Freischalten wichtiger Sekundärsysteme ab: Handwerksgrundlagen, Börsenmarkt und erster Skill-Preset-Tausch.", "Am Ende von Tag 5 sollten Sie etwa Level 25-28 sein."]),
        section("day-6-7", "Tag 6-7: Optimierung und Soziale Integration", ["Tag 6 konzentriert sich auf Ausrüstungsoptimierung und PvP-Einführung.", "Tag 7 konsolidiert Ihren Fortschritt und plant voraus.", "Das Wochenende ist auch eine gute Zeit, um die Spielerwirtschaft zu erkunden."]),
        section("gear-priorities", "Ausrüstungspriorität", ["Ihre Waffe hat immer erste Priorität. Waffen-Upgrades erhöhen direkt Ihren Schaden.", "Rüstungs-Upgrades kommen zweitens.", "Accessoires und Kosmetika haben niedrigste Priorität."]),
        section("common-mistakes", "Häufige Fehler der Ersten Woche", ["Übereilen Sie nicht zum Max-Level ohne Ihre Klasse zu lernen.", "Geben Sie in der ersten Woche kein Kinah für Kosmetika aus.", "Ignorieren Sie nicht die sozialen Systeme."]),
      ],
    }),
    es: articleCopy(guideLabels, "es", 7, {
      eyebrow: "NUEVOS JUGADORES",
      title: "Hoja de Ruta Primera Semana de Aion 2: Tu Plan de Progresión de 7 Días",
      description: "Hoja de ruta estructurada de 7 días para nuevos jugadores de Aion 2. Sigue este plan día a día para maximizar tu progresión inicial.",
      intro: "La primera semana en Aion 2 establece los cimientos de toda tu progresión.",
      sourceNote: "Basado en las guías oficiales de gameplay de NC y el servidor coreano (septiembre 2026).",
      keywords: ["Guía primera semana Aion 2", "Roadmap nuevo jugador Aion 2", "Guía 7 días Aion 2"],
      sections: [
        section("day-1-3", "Días 1-3: Construyendo Tu Base", ["El Día 1 se centra en la selección de clase y la cadena de misiones introductoria.", "Los Días 2-3 cubren la primera zona principal y desbloquean los sistemas de progresión centrales. Alcanzarás aproximadamente nivel 15-18 al final del Día 3.", "Enfócate en aprender tu rotación de clase antes de preocuparte por la optimización."]),
        section("day-4-5", "Días 4-5: Expandiendo Horizontes", ["El Día 4 deberías unirte a un gremio y empezar a explorar contenido en grupo.", "El Día 5 cubre el desbloqueo de sistemas secundarios clave.", "Al final del Día 5 deberías estar alrededor de nivel 25-28."]),
        section("day-6-7", "Días 6-7: Optimización e Integración Social", ["El Día 6 se enfoca en optimización de equipo e introducción al PvP.", "El Día 7 consolida tu progreso y planifica adelante.", "El fin de semana también es buen momento para explorar la economía de jugadores."]),
        section("gear-priorities", "Orden de Prioridad de Equipo", ["Tu arma es siempre la primera prioridad.", "Las mejoras de armadura van en segundo lugar.", "Los accesorios y cosméticos son la prioridad más baja."]),
        section("common-mistakes", "Errores Comunes de la Primera Semana", ["No te apresures al nivel máximo sin aprender tu clase.", "No gastes Kinah en cosméticos durante la primera semana.", "No ignores los sistemas sociales."]),
      ],
    }),
    ja: articleCopy(guideLabels, "ja", 7, {
      eyebrow: "新規プレイヤー",
      title: "Aion 2 初週ロードマップ：キャラクター作成からエンドゲーム準備までの7日間進行プラン",
      description: "Aion 2新規プレイヤー向けの構造化された7日間ロードマップ。日ごとの計画に従って初期進行を最大化しましょう。",
      intro: "Aion 2の最初の1週間は、あなたの進行全体の基盤を築きます。",
      sourceNote: "NCの公式ゲームプレイガイドと韓国サーバーの進行システムに基づいています（2026年9月時点）。",
      keywords: ["Aion 2 初週ガイド", "Aion 2 新規プレイヤーロードマップ", "Aion 2 7日ガイド"],
      sections: [
        section("day-1-3", "1-3日目：基盤の構築", ["1日目はクラス選択と導入クエストチェーンに集中します。クラス選択に時間をかけてください。", "2-3日目は最初の主要ゾーンをカバーし、コア進行システムを解放します。3日目終了時点で約レベル15-18に到達します。", "最適化を心配する前にクラスローテーションを学ぶことに集中してください。"]),
        section("day-4-5", "4-5日目：視野の拡大", ["4日目はギルドに参加し、グループコンテンツを探索し始めるべきです。", "5日目は重要な二次システムの解放をカバーします：製作の基本、ブローカレッジ、最初のスキルプリセット変更。", "5日目終了時点で約レベル25-28のはずです。"]),
        section("day-6-7", "6-7日目：最適化と社会統合", ["6日目は装備最適化とPvP入門に焦点を当てます。", "7日目は進行を統合し、先を計画します。", "週末はプレイヤー経済を探索する良いタイミングです。"]),
        section("gear-priorities", "装備優先順位", ["武器が常に最優先です。武器アップグレードは直接ダメージ出力を増加させます。", "防具アップグレードが2番目です。", "アクセサリーとコスメティックは最下位優先です。"]),
        section("common-mistakes", "よくある初週の間違い", ["クラスを学ばずにマックスレベルを急がないでください。", "最初の週にコスメティックアイテムにKinahを使わないでください。", "ソーシャルシステムを無視しないでください。"]),
      ],
    }),
    "pt-br": articleCopy(guideLabels, "pt-br", 7, {
      eyebrow: "NOVOS JOGADORES",
      title: "Roteiro da Primeira Semana do Aion 2: Seu Plano de Progressão de 7 Dias",
      description: "Roteiro estruturado de 7 dias para novos jogadores do Aion 2. Siga este plano dia a dia para maximizar sua progressão inicial.",
      intro: "A primeira semana no Aion 2 estabelece a fundação para toda sua progressão.",
      sourceNote: "Baseado nos guias oficiais de gameplay da NC e no servidor coreano (setembro 2026).",
      keywords: ["Guia primeira semana Aion 2", "Roteiro novo jogador Aion 2", "Guia 7 dias Aion 2"],
      sections: [
        section("day-1-3", "Dias 1-3: Construindo Sua Base", ["O Dia 1 foca na seleção de classe e na cadeia de quests introdutória.", "Os Dias 2-3 cobrem a primeira zona principal e desbloqueiam os sistemas centrais de progressão.", "Foque em aprender sua rotação de classe antes de se preocupar com otimização."]),
        section("day-4-5", "Dias 4-5: Expandindo Horizontes", ["O Dia 4 é quando você deve entrar em uma guilda e começar a explorar conteúdo em grupo.", "O Dia 5 cobre o desbloqueio de sistemas secundários chave.", "Ao final do Dia 5, você deve estar por volta do nível 25-28."]),
        section("day-6-7", "Dias 6-7: Otimização e Integração Social", ["O Dia 6 foca em otimização de equipamento e introdução ao PvP.", "O Dia 7 consolida seu progresso e planeja adiante.", "O fim de semana também é bom para explorar a economia de jogadores."]),
        section("gear-priorities", "Ordem de Prioridade de Equipamento", ["Sua arma é sempre a primeira prioridade.", "Melhorias de armadura vêm em segundo.", "Acessórios e cosméticos são a prioridade mais baixa."]),
        section("common-mistakes", "Erros Comuns da Primeira Semana", ["Não corra para o nível máximo sem aprender sua classe.", "Não gaste Kinah em cosméticos na primeira semana.", "Não ignore os sistemas sociais."]),
      ],
    }),
    ru: articleCopy(guideLabels, "ru", 7, {
      eyebrow: "НОВЫЕ ИГРОКИ",
      title: "Дорожная Карта Первой Недели Aion 2: Ваш 7-Дневный План Прогрессии",
      description: "Структурированная дорожная карта на 7 дней для новых игроков Aion 2. Следуйте этому плану для максимизации начальной прогрессии.",
      intro: "Первая неделя в Aion 2 закладывает фундамент всей вашей прогрессии.",
      sourceNote: "На основе официальных гайдов NC и корейского сервера (сентябрь 2026).",
      keywords: ["Гайд первая неделя Aion 2", "Дорожная карта новый игрок Aion 2"],
      sections: [
        section("day-1-3", "Дни 1-3: Создание Основы", ["День 1 фокусируется на выборе класса и вводной цепочке квестов.", "Дни 2-3 охватывают первую основную зону и разблокируют ключевые системы прогрессии.", "Сосредоточьтесь на изучении ротации класса прежде чем беспокоиться об оптимизации."]),
        section("day-4-5", "Дни 4-5: Расширение Горизонтов", ["День 4 — время вступить в гильдию и начать исследовать групповой контент.", "День 5 охватывает разблокировку ключевых вторичных систем.", "К концу Дня 5 вы должны быть примерно 25-28 уровня."]),
        section("day-6-7", "Дни 6-7: Оптимизация и Социальная Интеграция", ["День 6 фокусируется на оптимизации экипировки и введении в PvP.", "День 7 консолидирует ваш прогресс и планирует вперёд.", "Выходные — хорошее время для исследования экономики игроков."]),
        section("gear-priorities", "Порядок Приоритета Экипировки", ["Ваше оружие всегда в первом приоритете.", "Улучшения брони идут вторыми.", "Аксессуары и косметика — lowest priority."]),
        section("common-mistakes", "Типичные Ошибки Первой Недели", ["Не спешите к макс. уровню не изучив класс.", "Не тратьте Кина на косметику в первую неделю.", "Не игнорируйте социальные системы."]),
      ],
    }),
    ko: articleCopy(guideLabels, "ko", 7, {
      eyebrow: "신규 플레이어",
      title: "Aion 2 첫 주 로드맵: 캐릭터 생성부터 엔드게임 준비까지 7일 진행 계획",
      description: "Aion 2 신규 플레이어를 위한 구조화된 7일 로드맵. 일별 계획에 따라 초기 진행을 극대화하세요.",
      intro: "Aion 2의 첫 주 전체 진행의 기반을 마련합니다.",
      sourceNote: "NC의 공식 게임플레이 가이드와 한국 서버 진행 시스템 기준 (2026년 9월).",
      keywords: ["Aion 2 첫주 가이드", "Aion 2 신규 플레이어 로드맵", "Aion 2 7일 가이드"],
      sections: [
        section("day-1-3", "1-3일차: 기반 구축", ["1일차는 클래스 선택과 도입 퀘스트 체인에 집중합니다.", "2-3일차는 첫 번째 주요 존을 커버하고 핵심 진행 시스템을 해금합니다. 3일차 종료 시 약 15-18레벨에 도달합니다.", "최적화를 걱정하기 전에 클래스 로테이션을 배우는 데 집중하세요."]),
        section("day-4-5", "4-5일차: 지평 확장", ["4일차는 길드에 가입하고 그룹 콘텐츠를 탐험해야 합니다.", "5일차는 핵심 보조 시스템 해금을 다룹니다: 제작 기본, 브로커리지 시장, 첫 스킬 프리셋 교체.", "5일차 종료 시 약 25-28레벨이어야 합니다."]),
        section("day-6-7", "6-7일차: 최적화와 소셜 통합", ["6일차는 장비 최적화와 PvP 입문에 집중합니다.", "7일차는 진행을 통합하고 앞을 계획합니다.", "주말은 플레이어 경제를 탐험하기 좋은 시간입니다."]),
        section("gear-priorities", "장비 우선순위", ["무기가 항상 최우선입니다. 무기 업그레이드는 직접적으로 데미지 출력을 증가시킵니다.", "방어구 업그레이드가 두 번째입니다.", "액세서리와 코스메틱은 최하위 우선순위입니다."]),
        section("common-mistakes", "흔한 첫 주 실수", ["클래스를 배우지 않고 맥스 레벨을 서두르지 마세요.", "첫 주에 코스메틱 아이템에 키나를 쓰지 마세요.", "소셜 시스템을 무시하지 마세요."]),
      ],
    }),
    "zh-hant": articleCopy(guideLabels, "zh-hant", 7, {
      eyebrow: "新手",
      title: "Aion 2 首週路線：從角色創建到後期準備的 7 天進階規劃",
      description: "為 Aion 2 新玩家設計的結構化 7 天路線圖。按此逐日計劃最大化早期進階、避免常見錯誤。",
      intro: "Aion 2 的第一週為整個進階奠定基礎。本路線將每天分解為可實現的目標。",
      sourceNote: "基於 NC 官方攻略指南和韓服進階系統（截至 2026 年 9 月）。",
      keywords: ["Aion 2 首週攻略", "Aion 2 新手路線", "Aion 2 7天攻略"],
      sections: [
        section("day-1-3", "第 1-3 天：建立基礎", ["第 1 天重點是職業選擇和入門任務鏈。花時間選擇職業。", "第 2-3 天覆蓋第一個主要區域並解鎖核心進階系統。到第 3 天結束約達到 15-18 級。", "在擔心優化之前先學會你的職業循環。"]),
        section("day-4-5", "第 4-5 天：拓展視野", ["第 4 天應該加入公會並開始探索團隊內容。", "第 5 天覆蓋解鎖關鍵次要系統：製作基礎、交易所和第一次技能預設切換。", "到第 5 天結束應在 25-28 級左右。"]),
        section("day-6-7", "第 6-7 天：優化與社交整合", ["第 6 天聚焦裝備優化和 PvP 入門。", "第 7 天是鞏固進度和規劃未來。", "週末也是探索玩家經濟的好時機。"]),
        section("gear-priorities", "裝備優先順序：先升級什麼", ["武器始終是第一優先。", "護甲升級其次。", "飾品和外觀最低優先。"]),
        section("common-mistakes", "應避免的常見首周錯誤", ["不要在學習職業之前就急著滿級。", "第一周不要在外觀物品上花 Kinah。", "不要忽視社交系統。"]),
      ],
    }),
  },
};
