import { articleCopy, localizations, guideLabels, publishedVerified, section } from "./trending-september-7-shared";
import type { ContentSource, ContentHeroImage } from "./content-registry";

/* ARTICLE 4 — Solo dungeon boss-mechanics training guide (newly detailed at Gamescom, September 6 report) */

const sdSource1: ContentSource = {
  id: "guided-news-solo-dungeons-2026-09-06",
  kind: "third-party",
  publisher: "Guided News",
  label: "AION 2: NC will beim westlichen Release vieles besser machen (solo dungeons, dungeons & raids section)",
  url: "https://guided.news/en/opinion/aion-2-nc-wants-to-do-a-lot-better-with-the-western-release/",
  publishedAt: "2026-09-06",
  retrievedAt: "2026-09-07",
  verifiedAt: "2026-09-07",
  localizations: localizations({
    "zh-hans": "AION 2：NC 要让西区发行做得更好（单人副本/副本与团队章节）",
    en: "AION 2: NC wants to do a lot better with the western release (solo dungeons, dungeons & raids section)",
    fr: "AION 2 : NC veut faire mieux à l'Ouest (section donjons solo, donjons et raids)",
    de: "AION 2: NC will es im Westen besser machen (Abschnitt Solo-Dungeons, Dungeons & Raids)",
    es: "AION 2: NC quiere hacerlo mejor en Occidente (sección de mazmorras en solitario, mazmorras y raides)",
    ja: "AION 2：NCは西側でより良くしたい（ソロダンジョン/ダンジョン・レイド節）",
    "pt-br": "AION 2: a NC quer fazer melhor no Ocidente (seção de masmorras solo, masmorras e raides)",
    ru: "AION 2: NC хочет сделать лучше на Западе (раздел соло-подземелий и рейдов)",
    ko: "AION 2: NC, 서구에서 더 잘 하고 싶다 (솔로 던전/던전·레이드 섹션)",
    "zh-hant": "AION 2：NC 要讓西區做得更好（單人副本/副本與團隊章節）",
  }, "https://guided.news/en/opinion/aion-2-nc-wants-to-do-a-lot-better-with-the-western-release/"),
};

const sdSource2: ContentSource = {
  id: "aion2-official-teaser-2026-09-07",
  kind: "official",
  publisher: "NCSoft",
  label: "AION 2 Official Site — Game Overview",
  url: "https://aion2.plaync.com/en-us/",
  publishedAt: "2026-08-25",
  retrievedAt: "2026-09-07",
  verifiedAt: "2026-09-07",
  localizations: localizations({
    "zh-hans": "AION 2 官网——游戏总览",
    en: "AION 2 Official Site — Game Overview",
    fr: "Site officiel d'AION 2 — Présentation du jeu",
    de: "AION 2 Offizielle Website — Spielübersicht",
    es: "Sitio oficial de AION 2 — Resumen del juego",
    ja: "AION 2 公式サイト——ゲーム概要",
    "pt-br": "Site oficial do AION 2 — Visão geral do jogo",
    ru: "Официальный сайт AION 2 — Обзор игры",
    ko: "AION 2 공식 사이트 — 게임 개요",
    "zh-hant": "AION 2 官網——遊戲總覽",
  }, "https://aion2.plaync.com/en-us/"),
};

const sdHero: ContentHeroImage = {
  src: "https://blogfiles.ncsoft.net/news/af7330da-4ff6-4b58-aece-400e6061a3be.jpg",
  width: 1200, height: 630,
  credit: "NC Corporation",
  sourceUrl: "https://aion2.plaync.com/en-us/",
  rights: "linked-official-media",
  translations: {
    "zh-hans": { alt: "Aion 2 单人副本机制训练指南横幅", caption: "单人副本让你单独面对 Boss，练习读招、走位与机制——为团队内容做好准备。" },
    en: { alt: "Aion 2 solo dungeon mechanics training guide banner", caption: "Solo dungeons pit you and a boss alone — the place to learn attack reading, dodging, and mechanics before group content." },
    fr: { alt: "Bannière du guide d'entraînement aux donjons solo d'AION 2", caption: "Les donjons solo vous opposent à un boss — l'endroit pour apprendre à lire les attaques, esquiver et maîtriser les mécaniques." },
    de: { alt: "Banner zum Solo-Dungeon-Mechanik-Training in Aion 2", caption: "Solo-Dungeons stellen dich allein einem Boss gegenüber — der Ort für Angriffslesen, Ausweichen und Mechaniken vor Gruppencontent." },
    es: { alt: "Banner de la guía de entrenamiento en mazmorras en solitario de AION 2", caption: "Las mazmorras en solitario te enfrentan a un jefe — el lugar para aprender a leer ataques, esquivar y dominar mecánicas." },
    ja: { alt: "Aion 2 ソロダンジョン機構トレーニングガイドバナー", caption: "ソロダンジョンはボスと1対1——攻撃の読み、回避、メカニクスを学ぶ場です。" },
    "pt-br": { alt: "Banner do guia de treino em masmorras solo do AION 2", caption: "As masmorras solo colocam você contra um chefe — o lugar para aprender a ler ataques, esquivar e dominar mecânicas." },
    ru: { alt: "Баннер гайда по тренировке механик в соло-подземельях AION 2", caption: "Соло-подземелья ставят вас один на один с боссом — место для чтения атак, уклонения и изучения механик." },
    ko: { alt: "Aion 2 솔로 던전 메커니즘 훈련 가이드 배너", caption: "솔로 던전은 보스와 1대1로 맞서는 곳——공격 읽기, 회피, 메커니즘 학습의 장입니다." },
    "zh-hant": { alt: "Aion 2 單人副本機制訓練指南橫幅", caption: "單人副本讓你單獨面對 Boss，練習讀招、走位與機制——為團隊內容做好準備。" },
  },
};

export const trendingSeptember7Article4: ContentEntry = {
  section: "guides",
  slug: "aion-2-solo-dungeon-boss-mechanics-guide",
  schemaType: "Article",
  publishedAt: "2026-09-07",
  updatedAt: "2026-09-07",
  readingMinutes: 6,
  publication: publishedVerified,
  sources: [sdSource1, sdSource2],
  heroImage: sdHero,
  related: [
    { kind: "content", section: "guides", slug: "aion-2-dungeon-guide" },
    { kind: "content", section: "guides", slug: "aion-2-solo-player-guide" },
    { kind: "content", section: "guides", slug: "aion-2-trials-raids-guide" },
  ],
  translations: {
    en: articleCopy(guideLabels, "en", 6, {
      eyebrow: "SOLO DUNGEON GUIDE",
      title: "Aion 2 Solo Dungeons: Training Grounds for Boss Mechanics Before You Group Up",
      description: "How Aion 2's solo dungeons work as boss-mechanic trainers: reading attack telegraphs, avoiding red zones, class mastery, wing gliding inside instances, and the path to 4-player dungeons and 8-player raids",
      intro: "Aion 2's solo dungeons are designed so you and a boss face each other alone. Instead of learning mechanics on a four-player run, you practice reading attacks, positioning, and dodging by yourself — then carry that mastery into group content. This guide breaks down how it works and how to use it before launch.",
      keywords: ["Aion 2 solo dungeon boss mechanics", "Aion 2 how to dodge boss attacks", "Aion 2 learn dungeon mechanics solo", "Aion 2 solo to dungeon progression", "Aion 2 wing gliding dodge instances"],
      sourceNote: "Based on Guided News' September 6 report of its Gamescom appointment with NCsoft (solo dungeons, dungeons & raids details), cross-checked with the official AION 2 site (retrieved September 7, 2026).",
      sections: [
        section("what-solo-dungeons-are", "What Aion 2's Solo Dungeons Are", ["According to the September 6 Gamescom report, solo dungeons are small instances where it is basically just you and one boss. Their stated purpose: learn to read attacks correctly, dodge, and understand the enemy's mechanics.", "They double as class training — instead of surprising four other players with your handling of a boss, you internalize the basics alone first. They are not a tutorial-only feature: successful fights pay out rewards and contribute to character progression."]),
        section("reading-and-dodging", "Reading Attacks and Avoiding the Red Zones", ["Aion 2's combat is faster and more action-oriented than the original, with timing, positioning, and reactions emphasized by the developers during the briefing.", "The solo bosses teach exactly that language: attack wind-ups become readable tells, ground/red zones demand movement, and your reaction window is where the mechanic lives. Practice here converts directly to survival in 4-player dungeons."]),
        section("class-mastery", "Class Mastery Before Group Content", ["Solo runs let you map your kit to boss behavior — cooldown timing, when to hold defensive skills, which abilities to kite with — without group pressure.", "The report says group content emphasizes movement, communication, and player synergy; solo dungeons are where the movement half of that equation gets trained."]),
        section("wings-inside-instances", "Wings Inside Instances: Glide, Don't Free-Fly", ["An important instance-specific rule from the same report: you cannot fly freely inside dungeons, but your wings remain relevant — certain gliding or hovering moves can still be used, for example to evade attacks.", "Plan for a toolset of ground movement plus short glide bursts rather than full flight when entering instances."]),
        section("solo-to-group-path", "From Solo to 4-Player Dungeons to 8-Player Raids", ["The progression described at Gamescom runs: solo dungeons → 4-player dungeons → 8-player raids, where groups can temporarily split to handle different tasks or bosses before regrouping for the main opponent.", "Concrete plan for launch week: clear each solo dungeon's mechanics first, use them to qualify your class for 4-player content, and only then queue for raids — this mirrors the free-gear path in our early-game guide and the trials/raids overview."]),
      ],
    }),
    "zh-hans": articleCopy(guideLabels, "zh-hans", 6, {
      eyebrow: "单人副本攻略",
      title: "Aion 2 单人副本：组队前练习 Boss 机制的训练场",
      description: "Aion 2 单人副本如何充当 Boss 机制训练场：读招、躲红区、职业精通、副本内滑翔闪避，以及通往四人副本与八人团队的路径",
      intro: "Aion 2 的单人副本设计让你与 Boss 一对一。与其在四人本里现学机制，不如先独自练习读招、站位与闪避——再把这份熟练带进团队内容。本攻略详解其机制与上线前如何利用。",
      sourceNote: "基于 Guided News 9 月 6 日 Gamescom 约谈报道（单人副本/副本与团队细节），并与 AION 2 官网（2026-09-07 抓取）交叉核对。",
      keywords: ["Aion 2 单人副本 Boss机制", "Aion 2 躲避Boss攻击", "Aion 2 单人学习副本机制", "Aion 2 单人到副本进度", "Aion 2 翅膀滑翔闪避"],
      sections: [
        section("what-solo-dungeons-are", "Aion 2 单人副本是什么", ["据 9 月 6 日 Gamescom 报道，单人副本是小型场景，基本只有你与一个 Boss。官方表述的目的：学会正确读取攻击、闪避并理解敌人机制。", "它同时充当职业训练——与其在四人本中给队友添麻烦，不如先一个人掌握基础。它不只是教程：成功战斗会发放奖励并推进角色成长。"]),
        section("reading-and-dodging", "读招与躲避红区", ["Aion 2 的战斗比初代更快、更动作向，开发者在简报中强调时机、站位与反应。", "单人 Boss 教的就是这套语言：起手动作成为可读前摇、地面红区逼你走位、机制就藏在反应窗口里。在这里练出的能力可直接保命于四人本。"]),
        section("class-mastery", "进团队前的职业精通", ["单刷让你把技能组与 Boss 行为对应起来——冷却时机、何时留防御技、用哪些技能风筝——没有组队压力。", "报道称团队内容强调移动、交流与配合；单人副本正是训练其中「移动」一半的场所。"]),
        section("wings-inside-instances", "副本内的翅膀：滑翔而非自由飞行", ["同一报道中的重要规则：副本内不能自由飞行，但翅膀仍有用——特定滑翔/悬停动作仍可使用，例如用来闪避攻击。", "进副本前规划一套「地面移动+短距滑翔」的组合，而非依赖完整飞行。"]),
        section("solo-to-group-path", "从单人→四人→八人的路径", ["Gamescom 描述的顺序：单人副本→四人副本→八人团队；团队中队伍可临时拆分处理不同任务/Boss，再汇合打主目标。", "上线周的具体计划：先逐个掌握单人副本机制→用它验证职业适配四人内容→再进团队。这与本站前期免费装备指南和试炼/团队副本概览互相印证。"]),
      ],
    }),
    fr: articleCopy(guideLabels, "fr", 6, {
      eyebrow: "GUIDE DONJON SOLO",
      title: "Donjons solo d'Aion 2 : un terrain d'entraînement aux mécaniques de boss avant le groupe",
      description: "Comment les donjons solo d'Aion 2 servent d'entraînement : lire les attaques, éviter les zones, maîtrise de classe, vol plané en instance, chemin vers les donjons à 4 et raids à 8",
      intro: "Les donjons solo d'Aion 2 vous mettent seul face à un boss. Au lieu d'apprendre en groupe, vous pratiquez la lecture des attaques, le positionnement et l'esquive — puis portez cette maîtrise en contenu de groupe.",
      sourceNote: "Basé sur le rapport de Guided News du 6 septembre (donjons solo, donjons et raids), recoupé avec le site officiel d'AION 2 (7 septembre 2026).",
      keywords: ["Aion 2 donjon solo mécaniques", "Aion 2 esquiver attaques boss", "Aion 2 apprendre mécaniques seul", "Aion 2 progression solo donjon", "Aion 2 vol plané instance"],
      sections: [
        section("what-solo-dungeons-are", "Ce que sont les donjons solo", "De petites instances où vous seul affrontez un boss, pour apprendre à lire les attaques, esquiver et comprendre les mécaniques ; pas seulement un tutoriel — récompenses et progression."),
        section("reading-and-dodging", "Lire et esquiver", "Le combat est plus rapide et orienté action ; timing, positionnement et réactions importent — les bosses solo enseignent la lecture des télégraphes et des zones au sol."),
        section("class-mastery", "Maîtrise de classe avant le groupe", "Le solo permet de caler votre kit sur le comportement du boss sans pression ; le contenu de groupe exige mouvement, communication et synergie."),
        section("wings-inside-instances", "Ailes en instance : planer", "Pas de vol libre dans les donjons, mais des mouvements de plané/survol restent possibles pour esquiver — prévoyez un kit sol + glissades."),
        section("solo-to-group-path", "Du solo au groupe", "Progression : solo → donjons à 4 → raids à 8 (scission temporaire pour plusieurs boss, puis regroupement) ; maîtrisez le solo avant de passer au groupe."),
      ],
    }),
    de: articleCopy(guideLabels, "de", 6, {
      eyebrow: "SOLO-DUNGEON-GUIDE",
      title: "Aion 2 Solo-Dungeons: Trainingsplatz für Boss-Mechaniken vor der Gruppe",
      description: "Wie Aion-2-Solo-Dungeons als Mechanik-Trainer dienen: Angriffe lesen, Zonen meiden, Klassenmeisterung, Gleiten in Instanzen, Weg zu 4er-Dungeons und 8er-Raids",
      intro: "Aion-2-Solo-Dungeons stellen dich allein einem Boss gegenüber. Statt Mechaniken in der Gruppe zu lernen, übst du Lesen, Positionierung und Ausweichen allein — und trägst diese Meisterschaft in den Gruppencontent.",
      sourceNote: "Basierend auf dem Guided-News-Bericht vom 6. September (Solo-Dungeons, Dungeons & Raids), abgeglichen mit der offiziellen AION-2-Seite (7. September 2026).",
      keywords: ["Aion 2 Solo-Dungeon Mechaniken", "Aion 2 Bossangriffe ausweichen", "Aion 2 Mechaniken solo lernen", "Aion 2 Solo-zu-Dungeon-Fortschritt", "Aion 2 Gleiten Instanz"],
      sections: [
        section("what-solo-dungeons-are", "Was Solo-Dungeons sind", "Kleine Instanzen mit nur dir und einem Boss, um Angriffe zu lesen, auszuweichen und Mechaniken zu verstehen; kein reines Tutorial — Belohnungen und Fortschritt."),
        section("reading-and-dodging", "Lesen und Ausweichen", "Der Kampf ist schneller und actionorientierter; Timing, Positionierung und Reaktion zählen — Solo-Bosse lehren genau das Lesen von Telegraphen und Boden-Zonen."),
        section("class-mastery", "Klassenmeisterung vor der Gruppe", "Solo erlaubt es, dein Kit ohne Druck auf das Bossverhalten abzustimmen; Gruppencontent betont Bewegung, Kommunikation und Synergie."),
        section("wings-inside-instances", "Flügel in Instanzen: Gleiten", "Kein freies Fliegen in Dungeons, aber Gleit-/Schwebebewegungen zum Ausweichen möglich — Boden-Kit plus kurze Gleiter einplanen."),
        section("solo-to-group-path", "Vom Solo zur Gruppe", "Progression: Solo → 4er-Dungeons → 8er-Raids (zeitweise Aufteilung, dann Wieder-Vereinigung) ; erst Solo-Mechaniken beherrschen, dann Gruppe."),
      ],
    }),
    es: articleCopy(guideLabels, "es", 6, {
      eyebrow: "GUÍA MAZMORRA SOLO",
      title: "Mazmorras en solitario de Aion 2: campos de entrenamiento de mecánicas de jefe antes del grupo",
      description: "Cómo las mazmorras en solitario entrenan mecánicas de jefe: leer ataques, esquivar zonas, maestría de clase, planeo en instancias, camino a mazmorras de 4 y raides de 8",
      intro: "Las mazmorras en solitario de Aion 2 te enfrentan a un jefe a solas. En lugar de aprender en grupo, practicas lectura de ataques, posicionamiento y esquiva — y llevas esa maestría al contenido de grupo.",
      sourceNote: "Basado en el informe de Guided News del 6 de septiembre (mazmorras solo, mazmorras y raides), cotejado con el sitio oficial de AION 2 (7 de septiembre de 2026).",
      keywords: ["Aion 2 mazmorra solo mecánicas", "Aion 2 esquivar ataques jefe", "Aion 2 aprender mecánicas solo", "Aion 2 progresión solo mazmorra", "Aion 2 planeo instancia"],
      sections: [
        section("what-solo-dungeons-are", "Qué son las mazmorras solo", "Pequeñas instancias con solo tú y un jefe, para aprender a leer ataques, esquivar y entender mecánicas; no solo tutorial — recompensas y progresión."),
        section("reading-and-dodging", "Leer y esquivar", "El combate es más rápido y orientado a la acción; timing, posicionamiento y reacciones cuentan — los jefes solo enseñan a leer telegrafías y zonas del suelo."),
        section("class-mastery", "Maestría de clase antes del grupo", "El solo permite ajustar tu kit al comportamiento del jefe sin presión; el contenido de grupo exige movimiento, comunicación y sinergia."),
        section("wings-inside-instances", "Alas en instancias: planear", "Sin vuelo libre en mazmorras, pero con planeo/suspensión para esquivar — planifica kit terrestre más planeos cortos."),
        section("solo-to-group-path", "Del solo al grupo", "Progresión: solo → mazmorras de 4 → raides de 8 (división temporal, luego reagrupación) ; domina lo solo antes de entrar en grupo."),
      ],
    }),
    ja: articleCopy(guideLabels, "ja", 6, {
      eyebrow: "ソロダンジョンガイド",
      title: "Aion 2ソロダンジョン：グループ前にBossメカニクスを学ぶ訓練場",
      description: "ソロダンジョンがBossメカニクス訓練場になる仕組み：攻撃の読み、回避、クラス熟練、インスタンス内グライド、4人ダンジョン/8人レイドへの道",
      intro: "Aion 2のソロダンジョンは、あなたとBossだけの対決です。グループで学ぶ代わりに、攻撃の読み、立ち位置、回避を独りで練習し——その熟練をグループコンテンツに持ち込みます。",
      sourceNote: "Guided News 9月6日付Gamescom取材報道（ソロダンジョン/ダンジョン・レイド節）に基づき、AION 2公式サイト（2026-09-07取得）と照合。",
      keywords: ["Aion 2 ソロダンジョン ボス機構", "Aion 2 ボス攻撃回避", "Aion 2 机制を一人で学ぶ", "Aion 2 ソロからダンジョン", "Aion 2 インスタンス内グライド"],
      sections: [
        section("what-solo-dungeons-are", "ソロダンジョンとは", "あなたとBossだけの小規模インスタンス。攻撃の読み、回避、メカニクス理解のための場で、単なるチュートリアルではなく報酬と成長があります。"),
        section("reading-and-dodging", "読みと回避", "戦闘は初代より高速でアクション寄り——タイミング、立ち位置、反応が重視され、ソロBossがその言語を教えてくれます。"),
        section("class-mastery", "グループ前のクラス熟練", "ソロで自分のスキルセットをBoss挙動に合わせられます（クールタイム、防御技の温存、キッティング）。グループは移動・会話・シナジー重視。"),
        section("wings-inside-instances", "インスタンス内の翼：滑空", "ダンジョン内の自由飛行は不可ですが、回避用のグライド/ホバー動作は可能——地上移動＋短い滑空の組み合わせを。"),
        section("solo-to-group-path", "ソロからグループへの道", "進行：ソロ→4人ダンジョン→8人レイド（一時分隊→合流）。まずソロの機構をマスターしてからグループへ。"),
      ],
    }),
    "pt-br": articleCopy(guideLabels, "pt-br", 6, {
      eyebrow: "GUIA MASMORRA SOLO",
      title: "Masmorras solo do Aion 2: campos de treino de mecânicas de chefe antes do grupo",
      description: "Como as masmorras solo treinam mecânicas de chefe: ler ataques, evitar áreas, maestria de classe, planagem em instâncias, caminho para masmorras de 4 e raides de 8",
      intro: "As masmorras solo do Aion 2 colocam você sozinho contra um chefe. Em vez de aprender em grupo, você pratica leitura de ataques, posicionamento e esquiva — e leva essa maestria ao conteúdo de grupo.",
      sourceNote: "Baseado no relato da Guided News de 6 de setembro (masmorras solo, masmorras e raides), cruzado com o site oficial do AION 2 (7 de setembro de 2026).",
      keywords: ["Aion 2 masmorra solo mecânicas", "Aion 2 esquivar ataques chefe", "Aion 2 aprender mecânicas solo", "Aion 2 progressão solo masmorra", "Aion 2 planagem instância"],
      sections: [
        section("what-solo-dungeons-are", "O que são as masmorras solo", "Pequenas instâncias com só você e um chefe, para aprender a ler ataques, esquivar e entender mecânicas; não é só tutorial — recompensas e progressão."),
        section("reading-and-dodging", "Ler e esquivar", "O combate é mais rápido e orientado à ação; timing, posicionamento e reações contam — os chefes solo ensinam a ler telégrafos e áreas no chão."),
        section("class-mastery", "Maestria de classe antes do grupo", "O solo permite ajustar seu kit ao comportamento do chefe sem pressão; conteúdo de grupo exige movimento, comunicação e sinergia."),
        section("wings-inside-instances", "Asas em instâncias: planar", "Sem voo livre em masmorras, mas é possível planar/suspender para esquivar — planeje kit terrestre mais planagens curtas."),
        section("solo-to-group-path", "Do solo ao grupo", "Progressão: solo → masmorras de 4 → raides de 8 (divisão temporária, depois reagrupamento); domine o solo antes do grupo."),
      ],
    }),
    ru: articleCopy(guideLabels, "ru", 6, {
      eyebrow: "ГАЙД ПО СОЛО-ПОДЗЕМЕЛЬЯМ",
      title: "Соло-подземелья Aion 2: полигон для механик боссов перед группой",
      description: "Как соло-подземелья тренируют чтение атак, уклонение, мастерство класса, скольжение в инстансах и путь к подземельям на 4 и рейдам на 8",
      intro: "Соло-подземелья Aion 2 ставят вас один на один с боссом. Вместо учёбы в группе вы практикуете чтение атак, позиционирование и уклонение — и переносите мастерство в групповой контент.",
      sourceNote: "На основе отчёта Guided News от 6 сентября (соло-подземелья, подземелья и рейды), сверено с официальным сайтом AION 2 (7 сентября 2026 г.).",
      keywords: ["Aion 2 соло-подземелья механики", "Aion 2 уклонение от атак босса", "Aion 2 учить механики соло", "Aion 2 прогресс соло в данж", "Aion 2 скольжение инстанс"],
      sections: [
        section("what-solo-dungeons-are", "Что такое соло-подземелья", "Небольшие инстансы, где только вы и босс: учиться читать атаки, уклоняться и понимать механики; не просто туториал — награды и прокачка."),
        section("reading-and-dodging", "Читать и уклоняться", "Бой быстрее и более экшен-ориентирован; тайминг, позиция и реакции важны — соло-боссы учат именно этому языку."),
        section("class-mastery", "Мастерство класса перед группой", "Соло позволяет подогнать набор умений под поведение босса без давления; группа требует движения, связи и синергии."),
        section("wings-inside-instances", "Крылья в инстансах: планирование", "Полёт в подземельях недоступен, но скольжение/зависание для уклонения работает — планируйте наземный набор + короткие глиссы."),
        section("solo-to-group-path", "От соло к группе", "Прогрессия: соло → подземелья на 4 → рейды на 8 (временное разделение, затем встреча) ; освойте соло перед группой."),
      ],
    }),
    ko: articleCopy(guideLabels, "ko", 6, {
      eyebrow: "솔로 던전 가이드",
      title: "아이온2 솔로 던전: 파티 전에 보스 메커니즘을 익히는 훈련장",
      description: "솔로 던전이 보스 메커니즘 훈련장이 되는 방법: 공격 읽기, 회피, 클래스 숙련, 인스턴스 내 글라이드, 4인 던전/8인 레이드로 가는 길",
      intro: "아이온2의 솔로 던전은 나와 보스만 마주하는 공간입니다. 파티에서 배우는 대신, 공격 읽기와 위치 잡기, 회피를 혼자 연습하고——그 숙련도를 그룹 콘텐츠로 가져갑니다.",
      sourceNote: "Guided News 9월 6일자 Gamescom 미팅 보도(솔로 던전/던전·레이드 절)에 기반하여, AION 2 공식 사이트(2026-09-07 확인)와 교차 확인했습니다.",
      keywords: ["아이온2 솔로 던전 보스 메커니즘", "아이온2 보스 공격 회피", "아이온2 메커니즘 혼자 배우기", "아이온2 솔로에서 던전으로", "아이온2 인스턴스 글라이드"],
      sections: [
        section("what-solo-dungeons-are", "솔로 던전이란", "나와 보스만 있는 소규모 인스턴스. 공격 읽기, 회피, 메커니즘 이해를 위한 공간이며, 단순 튜토리얼이 아니라 보상과 성장이 있습니다."),
        section("reading-and-dodging", "읽기와 회피", "전투는 원작보다 빠르고 액션 지향적입니다——타이밍·위치·반응이 중요하며, 솔로 보스가 그 언어를 가르쳐 줍니다."),
        section("class-mastery", "파티 전 클래스 숙련", "솔로는 압박 없이 내 스킬셋을 보스 행동에 맞추게 합니다(쿨타임, 방어기 아끼기, 키팅). 그룹 콘텐츠는 이동·소통·시너지가 핵심."),
        section("wings-inside-instances", "인스턴스 속 날개: 글라이드", "던전 내 자유 비행은 불가하지만, 회피용 글라이드/호버는 가능합니다——지상 이동 + 짧은 활강 조합을 준비하세요."),
        section("solo-to-group-path", "솔로에서 그룹으로 가는 길", "진행: 솔로→4인 던전→8인 레이드(임시 분대 후 합류). 먼저 솔로의 메커니즘을 마스터한 뒤 그룹으로."),
      ],
    }),
    "zh-hant": articleCopy(guideLabels, "zh-hant", 6, {
      eyebrow: "單人副本攻略",
      title: "Aion 2 單人副本：組隊前練習 Boss 機制的訓練場",
      description: "Aion 2 單人副本如何充當 Boss 機制訓練場：讀招、躲紅區、職業精通、副本內滑翔閃避，以及通往四人副本與八人團隊的路徑",
      intro: "Aion 2 的單人副本設計讓你與 Boss 一對一。與其在四人本裡現學機制，不如先獨自練習讀招、站位與閃避——再把這份熟練帶進團隊內容。本攻略詳解其機制與上線前如何利用。",
      sourceNote: "基於 Guided News 9 月 6 日 Gamescom 約談報導（單人副本/副本與團隊細節），並與 AION 2 官網（2026-09-07 抓取）交叉核對。",
      keywords: ["Aion 2 單人副本 Boss機制", "Aion 2 躲避Boss攻擊", "Aion 2 單人學習副本機制", "Aion 2 單人到副本進度", "Aion 2 翅膀滑翔閃避"],
      sections: [
        section("what-solo-dungeons-are", "Aion 2 單人副本是什麼", ["據 9 月 6 日 Gamescom 報導，單人副本是小型場景，基本只有你與一個 Boss。官方表述的目的：學會正確讀取攻擊、閃避並理解敵人機制。", "它同時充當職業訓練——與其讓隊友在四人本裡受苦，不如先一個人掌握基礎。它不只是教學：成功戰鬥會發放獎勵並推進角色成長。"]),
        section("reading-and-dodging", "讀招與躲避紅區", ["Aion 2 的戰鬥比初代更快、更動作向，開發者在簡報中強調時機、站位與反應。", "單人 Boss 教的就是這套語言：起手動作成為可讀前搖、地面紅區逼你走位、機制就藏在反應窗口裡。在這裡練出的能力可直接保命於四人本。"]),
        section("class-mastery", "進團隊前的職業精通", ["單刷讓你把技能組與 Boss 行為對應起來——冷卻時機、何時留防禦技、用哪些技能風箏——沒有組隊壓力。", "報導稱團隊內容強調移動、交流與配合；單人副本正是訓練其中「移動」一半的場所。"]),
        section("wings-inside-instances", "副本內的翅膀：滑翔而非自由飛行", ["同一報導中的重要規則：副本內不能自由飛行，但翅膀仍有用——特定滑翔/懸停動作仍可使用，例如用來閃避攻擊。", "進副本前規劃一套「地面移動+短距滑翔」的組合，而非依賴完整飛行。"]),
        section("solo-to-group-path", "從單人→四人→八人的路徑", ["Gamescom 描述的順序：單人副本→四人副本→八人團隊；團隊中隊伍可臨時拆分處理不同任務/Boss，再匯合打主目標。", "上線周的具體計畫：先逐個掌握單人副本機制→用它驗證職業適配四人內容→再進團隊。這與本站前期免費裝備指南和試煉/團隊副本概覽互相印證。"]),
      ],
    }),
  },
};