import { articleCopy, localizations, newsLabels, publishedVerified, section } from "./trending-september-8-shared";
import type { ContentEntry, ContentHeroImage, ContentSource } from "./content-registry";

/* ARTICLE 1 — Aion 2 console version confirmed; cross-play with PC likely not supported; global remains PC-only (no mobile plans) */

const wfSource: ContentSource = {
  id: "wccftech-aion2-qa-2026-09-07",
  kind: "third-party",
  publisher: "Wccftech",
  label: "Aion 2 Q&A: NVIDIA DLSS 5 Confirmed in the Works; Console Launch Is Coming, but Cross-Play Likely Isn't",
  url: "https://wccftech.com/aion-2-qa-dlss-5-console-cross-play/",
  publishedAt: "2026-09-07",
  retrievedAt: "2026-09-08",
  verifiedAt: "2026-09-08",
  localizations: localizations({
    "zh-hans": "Aion 2 Q&A：DLSS 5 确认开发中；主机版将至，但跨平台大概率不支持",
    en: "Aion 2 Q&A: NVIDIA DLSS 5 Confirmed in the Works; Console Launch Is Coming, but Cross-Play Likely Isn't",
    fr: "Aion 2 Q&R : DLSS 5 confirmé, lancement console à venir, mais le cross-play probablement pas",
    de: "Aion 2 Q&A: DLSS 5 bestätigt, Konsolen-Launch kommt, Cross-Play wohl nicht",
    es: "Aion 2 Preguntas y respuestas: DLSS 5 confirmado, lanzamiento de consola en camino, pero el cross-play probablemente no",
    ja: "Aion 2 Q&A：DLSS 5 開発中を確認、コンソール版準備中、クロスプレイはおそらく非対応",
    "pt-br": "Aion 2 Q&A: DLSS 5 confirmado, lançamento para consoles a caminho, mas cross-play provavelmente não",
    ru: "Aion 2 Q&A: DLSS 5 подтверждён, консольный запуск готовится, кросс-плей вряд ли будет",
    ko: "아이온2 Q&A: DLSS 5 개발 중 확인, 콘솔 출시 준비 중, 크로스플레이는 아마 미지원",
    "zh-hant": "Aion 2 Q&A：DLSS 5 確認開發中；主機版將至，但跨平台大概率不支援",
  }, "https://wccftech.com/aion-2-qa-dlss-5-console-cross-play/"),
};

const steamSource: ContentSource = {
  id: "aion2-steam-store-2026-09-08",
  kind: "platform",
  publisher: "Steam",
  label: "AION 2 on Steam (Free to Play, Oct 5 2026)",
  url: "https://store.steampowered.com/app/3393110/AION_2/",
  publishedAt: "2026-08-26",
  retrievedAt: "2026-09-08",
  verifiedAt: "2026-09-08",
  localizations: localizations({
    "zh-hans": "Steam 上的 AION 2（免费游玩，2026-10-05）",
    en: "AION 2 on Steam (Free to Play, Oct 5 2026)",
    fr: "AION 2 sur Steam (free-to-play, 5 oct. 2026)",
    de: "AION 2 auf Steam (Free to Play, 5. Okt. 2026)",
    es: "AION 2 en Steam (gratuito, 5 oct 2026)",
    ja: "SteamのAION 2（基本無料、2026-10-05）",
    "pt-br": "AION 2 na Steam (gratuito, 5 out 2026)",
    ru: "AION 2 в Steam (бесплатная, 05.10.2026)",
    ko: "Steam의 AION 2 (부분 유료, 2026-10-05)",
    "zh-hant": "Steam 上的 AION 2（免費遊玩，2026-10-05）",
  }, "https://store.steampowered.com/app/3393110/AION_2/"),
};

const cHero: ContentHeroImage = {
  src: "https://blogfiles.ncsoft.net/news/af7330da-4ff6-4b58-aece-400e6061a3be.jpg",
  width: 1200, height: 630,
  credit: "NC Corporation",
  sourceUrl: "https://aion2.plaync.com/en-us/",
  rights: "linked-official-media",
  translations: {
    "zh-hans": { alt: "Aion 2 主机版路线新闻横幅", caption: "NC 在 Gamescom 专访中确认主机版正在筹备：全球首发优先，跨平台大概率与 PC 分开运营，全球版无移动端计划。" },
    en: { alt: "Aion 2 console roadmap news banner", caption: "In a Gamescom interview, NC confirmed a console version is in preparation after the global launch, with cross-play likely run as a separate operation, and no mobile plans for the global build." },
    fr: { alt: "Bannière d'actualité route console d'Aion 2", caption: "Lors d'un entretien Gamescom, NC a confirmé préparer une version console après le lancement global, un cross-play probablement séparé, et aucun projet mobile." },
    de: { alt: "News-Banner zur Konsolen-Roadmap von Aion 2", caption: "In einem Gamescom-Interview bestätigte NC, dass eine Konsolenversion nach dem globalen Launch vorbereitet wird, Cross-Play voraussichtlich getrennt, und keine Mobile-Pläne." },
    es: { alt: "Banner de noticias sobre la hoja de ruta de consola de Aion 2", caption: "En una entrevista en Gamescom, NC confirmó que prepara una versión de consola tras el lanzamiento global, con cross-play probablemente separado y sin planes móviles." },
    ja: { alt: "Aion 2 コンソール版ロードマップニュースバナー", caption: "GamescomインタビューでNCはコンソール版の準備を確認：グローバル先行、クロスプレイはおそらく分離運営、モバイル計画なし。" },
    "pt-br": { alt: "Banner de notícias do roadmap de console do Aion 2", caption: "Em entrevista na Gamescom, a NC confirmou que prepara uma versão de console após o lançamento global, com cross-play provavelmente separado e sem planos mobile." },
    ru: { alt: "Баннер новостей о консольной дорожной карте Aion 2", caption: "В интервью на Gamescom NC подтвердила подготовку консольной версии после глобального запуска, кросс-плей, вероятно, раздельный, без мобильных планов." },
    ko: { alt: "Aion 2 콘솔 로드맵 뉴스 배너", caption: "Gamescom 인터뷰에서 NC가 콘솔 버전 준비를 확인: 글로벌 출시 우선, 크로스플레이는 아마 분리 운영, 모바일 계획 없음." },
    "zh-hant": { alt: "Aion 2 主機版路線新聞橫幅", caption: "NC 在 Gamescom 專訪中確認主機版正在籌備：全球首發優先，跨平台大概率與 PC 分開營運，全球版無行動端計畫。" },
  },
};

export const trendingSeptember8Article1: ContentEntry = {
  section: "news",
  slug: "aion-2-console-version-cross-play-roadmap",
  schemaType: "NewsArticle",
  publishedAt: "2026-09-08",
  updatedAt: "2026-09-08",
  readingMinutes: 6,
  publication: publishedVerified,
  sources: [wfSource, steamSource],
  heroImage: cHero,
  related: [
    { kind: "content", section: "news", slug: "aion-2-release-date-october-5-2026" },
    { kind: "content", section: "news", slug: "aion-2-steam-store-countdown-four-weeks" },
    { kind: "content", section: "guides", slug: "aion-2-prelaunch-access-routes-guide" },
    { kind: "content", section: "guides", slug: "aion-2-launch-scale-test-preparation-guide" },
  ],
  translations: {
    en: articleCopy(newsLabels, "en", 6, {
      eyebrow: "PLATFORM ROADMAP",
      title: "Aion 2 Console Version Confirmed: Cross-Play With PC Unlikely; Global Stays PC-Only for Now",
      description: "NCsoft confirms a console version of Aion 2 is in preparation after the October 5 global launch, cross-play will likely be a separate operation, and there are no mobile plans for the global build",
      intro: "In a September 7 interview following a Gamescom presentation, NCsoft confirmed for the first time that a console version of Aion 2 is in preparation — but the global launch stays PC-only, cross-play between PC and console will likely not be supported, and no mobile version is planned.",
      sourceNote: "Based on Wccftech's September 7, 2026 interview with the Aion 2 team (Namjoon Kim, Merv Lee Kwai, Andrew Long) at Gamescom, cross-checked with the official Steam store page (retrieved September 8, 2026).",
      keywords: ["Aion 2 console version", "Aion 2 cross-play PC console", "Aion 2 mobile version no plans", "Aion 2 global launch PC only", "Aion 2 platforms roadmap"],
      sections: [
        section("console-confirmed", "A Console Version Is Confirmed — After the Global Launch", ["Asked about a potential console release, Aion 2's Namjoon Kim answered directly: 'As a matter of fact, we're preparing a console launch as well. But our priority is the global launch first, and console support will follow after that.'", "That is the first explicit confirmation that a console version exists in the roadmap. No platforms were named, and no window was given beyond 'after' the PC global launch."]),
        section("cross-play-likely-separate", "Cross-Play With PC: Likely a Separate Operation", ["On cross-play between PC and console, Kim said the team has not made a clear decision, 'but we think that for now cross-play probably won't be supported between PC and console, because the usage and the gameplay are different, and the timing of the launch is different for PC and console.'", "He added that it is not confirmed yet, 'but for now we think it's probably going to be a separate operation' — the working assumption is separate servers rather than shared queues."]),
        section("no-mobile-pc-only", "No Mobile Version; Global Is PC-Only for Launch", ["The global build ships on PC only — Steam and NC's own PURPLE launcher. Asked about mobile, Merv Lee Kwai was blunt: 'Sadly, there are no plans for the mobile version.'", "That differs from some Asian-market expectations, but matches the 'PC-native' positioning NC has repeated for the global release."]),
        section("controllers", "Controllers Are Supported on PC", ["PC players who prefer a gamepad are covered: asked whether the game will support controllers, Merv Lee Kwai answered 'Absolutely, controllers are supported.'", "Aerial combat and double-jump flight are core to Aion 2's feel, so controller support is a meaningful confirmation for PC players who want the console-style input."]),
        section("launch-timeline", "What the Timeline Looks Like", ["The pieces around the console news are unchanged: the free Launch Scale Test runs September 17-18 via Steam, Founder's Pack owners get advance access from September 30, and the free-to-play global launch is set for October 5.", "With the game's first season launching on PC and cross-play looking separate, console players should plan on waiting until the PC version is established — NC has not shared a console timing estimate."]),
      ],
    }),
    "zh-hans": articleCopy(newsLabels, "zh-hans", 6, {
      eyebrow: "平台路线",
      title: "Aion 2 主机版确认：与 PC 跨平台大概率不支持；全球版现阶段仅 PC",
      description: "NCsoft 确认 Aion 2 主机版正在筹备（紧随 10 月 5 日全球首发之后）；跨平台大概率分开运营；全球版无移动端计划",
      intro: "在 9 月 7 日 Gamescom 发布会后的专访中，NCsoft 首次明确确认 Aion 2 主机版正在筹备——但全球首发仍仅限 PC，PC 与主机跨平台大概率不支持，且无移动端计划。",
      sourceNote: "基于 Wccftech 2026 年 9 月 7 日在 Gamescom 对 Aion 2 开发团队（金南俊、Merv Lee Kwai、Andrew Long）的专访，并与官方 Steam 商店页（2026-09-08 抓取）交叉核对。",
      keywords: ["Aion 2 主机版", "Aion 2 PC 主机跨平台", "Aion 2 移动版 无计划", "Aion 2 全球首发 仅 PC", "Aion 2 平台路线"],
      sections: [
        section("console-confirmed", "主机版确认——紧随全球首发", ["被问及潜在的主机版时，Aion 2 的金南俊直接回答：「事实上，我们也在筹备主机版。但我们的优先级是先做好全球首发，主机支持会在其后跟进。」", "这是官方首次明确主机版在路线图中。未公布具体平台，时间窗口也只有「PC 全球首发之后」。"]),
        section("cross-play-likely-separate", "与 PC 跨平台：大概率分开运营", ["关于 PC 与主机跨平台，金南俊表示团队尚未做最终决定，「但目前我们认为 PC 与主机之间大概率不会支持跨平台，因为使用方式与玩法不同，且 PC 与主机的上线时间也不同。」", "他补充说此事尚未确认，「但目前的倾向是分开运营」——默认假设是独立服务器而非共享队列。"]),
        section("no-mobile-pc-only", "无移动版；全球版首发仅 PC", ["全球版只在 PC 上架——Steam 与 NC 自家的 PURPLE 启动器。被问及移动端时，Merv Lee Kwai 直言：「很遗憾，没有移动版计划。」", "这与部分亚洲市场预期不同，但符合 NC 反复强调的全球版「PC 原生」定位。"]),
        section("controllers", "PC 支持手柄", ["喜欢手柄的 PC 玩家有福了：被问及游戏是否支持手柄时，Merv Lee Kwai 回答「当然，支持手柄。」", "空中战斗与二段跳飞行是 Aion 2 的核心体验，因此手柄支持对想用手柄输入的 PC 玩家是有意义的确认。"]),
        section("launch-timeline", "时间线一览", ["主机版新闻之外的节点不变：免费规模测试 9 月 17-18 日经 Steam 进行，创始人包持有者 9 月 30 日起抢先体验，免费制全球首发定于 10 月 5 日。", "首个赛季将在 PC 上线且跨平台大概率分开，主机玩家应做好等 PC 版站稳后再说——NC 尚未给出主机版时间估计。"]),
      ],
    }),
    fr: articleCopy(newsLabels, "fr", 6, {
      eyebrow: "ROADMAP PLATEFORMES",
      title: "Version console d'Aion 2 confirmée : le cross-play avec PC probablement non, le global reste PC pour l'instant",
      description: "NCsoft confirme préparer une version console d'Aion 2 après le lancement global du 5 octobre ; cross-play probablement séparé ; aucun projet mobile",
      intro: "Lors d'un entretien du 7 septembre après une présentation Gamescom, NCsoft a confirmé pour la première fois préparer une version console d'Aion 2 — mais le lancement global reste PC uniquement, le cross-play PC/console ne sera probablement pas supporté, et aucun projet mobile n'est prévu.",
      sourceNote: "Basé sur l'entretien de Wccftech du 7 septembre 2026 avec l'équipe Aion 2 (Namjoon Kim, Merv Lee Kwai, Andrew Long) à la Gamescom, recoupé avec la page Steam officielle (récupérée le 8 septembre 2026).",
      keywords: ["Aion 2 version console", "Aion 2 cross-play PC console", "Aion 2 mobile pas prévu", "Aion 2 lancement global PC", "Aion 2 plateformes roadmap"],
      sections: [
        section("console-confirmed", "Une version console confirmée — après le lancement global", "Interrogé, Namjoon Kim a répondu : « En fait, nous préparons aussi un lancement console. Mais notre priorité est d'abord le lancement global ; le support console suivra. » C'est la première confirmation explicite ; aucune plateforme ni fenêtre n'a été donnée."),
        section("cross-play-likely-separate", "Cross-play avec PC : probablement une opération séparée", "Kim : « pas encore de décision claire, mais pour l'instant le cross-play ne sera probablement pas supporté entre PC et console, car l'usage, le gameplay et le calendrier diffèrent. » Hypothèse de travail : serveurs séparés plutôt que files partagées."),
        section("no-mobile-pc-only", "Pas de version mobile ; le global est PC uniquement", "La version globale sort sur PC uniquement — Steam et le lanceur PURPLE. Merv Lee Kwai : « Malheureusement, aucun projet de version mobile. » Conforme au positionnement « PC-native » répété par NC."),
        section("controllers", "Les manettes sont supportées sur PC", "« Absolument, les manettes sont supportées », a répondu Merv Lee Kwai. Le combat aérien et le double saut étant centraux, c'est une confirmation utile pour les joueurs PC."),
        section("launch-timeline", "Le calendrier", "LST gratuit 17-18 septembre via Steam ; accès anticipé des Founder's Pack le 30 septembre ; lancement free-to-play le 5 octobre. Les joueurs console devront attendre que la version PC soit établie — aucun calendrier console annoncé."),
      ],
    }),
    de: articleCopy(newsLabels, "de", 6, {
      eyebrow: "PLATTFORM-ROADMAP",
      title: "Aion 2 Konsolenversion bestätigt: Cross-Play mit PC wohl nicht, Global bleibt vorerst PC-only",
      description: "NCsoft bestätigt, eine Konsolenversion von Aion 2 nach dem Global-Launch am 5. Oktober vorzubereiten; Cross-Play voraussichtlich getrennt; keine Mobile-Pläne",
      intro: "In einem Interview vom 7. September nach einer Gamescom-Präsentation bestätigte NCsoft erstmals, dass eine Konsolenversion von Aion 2 vorbereitet wird — der globale Start bleibt aber PC-only, Cross-Play zwischen PC und Konsole wird voraussichtlich nicht unterstützt, und eine Mobile-Version ist nicht geplant.",
      sourceNote: "Basierend auf dem Wccftech-Interview vom 7. September 2026 mit dem Aion-2-Team (Namjoon Kim, Merv Lee Kwai, Andrew Long) auf der Gamescom, abgeglichen mit der offiziellen Steam-Seite (abgerufen am 8. September 2026).",
      keywords: ["Aion 2 Konsolenversion", "Aion 2 Cross-Play PC Konsole", "Aion 2 Mobile keine Pläne", "Aion 2 Global-Launch PC only", "Aion 2 Plattform-Roadmap"],
      sections: [
        section("console-confirmed", "Konsolenversion bestätigt — nach dem Global-Launch", "Namjoon Kim: „Tatsächlich bereiten wir auch einen Konsolen-Launch vor. Aber unsere Priorität ist zuerst der Global-Launch; Konsolen-Support folgt danach.“ Erste explizite Bestätigung; keine Plattformen oder Zeitfenster genannt."),
        section("cross-play-likely-separate", "Cross-Play mit PC: voraussichtlich getrennt", "Kim: „noch keine klare Entscheidung, aber wir glauben, dass Cross-Play zwischen PC und Konsole vorerst wohl nicht unterstützt wird, da Nutzung, Gameplay und Startzeitpunkt unterschiedlich sind.“ Arbeitsannahme: getrennte Server."),
        section("no-mobile-pc-only", "Keine Mobile-Version; Global ist PC-only", "Die globale Version erscheint nur auf PC — Steam und der PURPLE-Launcher. Merv Lee Kwai: „Leider gibt es keine Pläne für eine Mobile-Version.“ Passt zur PC-nativen Positionierung."),
        section("controllers", "Controller werden unterstützt", "„Absolut, Controller werden unterstützt“, so Merv Lee Kwai. Angesichts des Luftkampfs und des Doppelsprungs eine wichtige Bestätigung für PC-Spieler."),
        section("launch-timeline", "Der Zeitplan", "Kostenloser LST 17.-18. September via Steam; Founder's-Pack-Frühzugang ab 30. September; Free-to-Play-Launch am 5. Oktober. Konsolenspieler müssen warten, bis die PC-Version etabliert ist."),
      ],
    }),
    es: articleCopy(newsLabels, "es", 6, {
      eyebrow: "HOJA DE RUTA DE PLATAFORMAS",
      title: "Versión de consola de Aion 2 confirmada: el cross-play con PC probablemente no; el lanzamiento global sigue siendo solo PC",
      description: "NCsoft confirma que prepara una versión de consola de Aion 2 tras el lanzamiento global del 5 de octubre; el cross-play probablemente será una operación separada; sin planes móviles",
      intro: "En una entrevista del 7 de septiembre tras una presentación en Gamescom, NCsoft confirmó por primera vez que prepara una versión de consola de Aion 2 — pero el lanzamiento global sigue siendo solo PC, el cross-play entre PC y consola probablemente no se soportará, y no hay planes móviles.",
      sourceNote: "Basado en la entrevista de Wccftech del 7 de septiembre de 2026 con el equipo de Aion 2 (Namjoon Kim, Merv Lee Kwai, Andrew Long) en Gamescom, cotejado con la página oficial de Steam (recuperada el 8 de septiembre de 2026).",
      keywords: ["Aion 2 versión consola", "Aion 2 cross-play PC consola", "Aion 2 móvil sin planes", "Aion 2 lanzamiento global solo PC", "Aion 2 plataformas hoja de ruta"],
      sections: [
        section("console-confirmed", "Una versión de consola confirmada — tras el lanzamiento global", "Namjoon Kim respondió: «De hecho, estamos preparando un lanzamiento de consola también. Pero nuestra prioridad es primero el lanzamiento global; el soporte de consola seguirá después.» Primera confirmación explícita; sin plataformas ni fechas."),
        section("cross-play-likely-separate", "Cross-play con PC: probablemente una operación separada", "Kim: «aún no hay decisión clara, pero por ahora el cross-play probablemente no se soporte entre PC y consola, porque el uso, el gameplay y el calendario son diferentes.» Supuesto de trabajo: servidores separados."),
        section("no-mobile-pc-only", "Sin versión móvil; el global es solo PC", "La versión global sale solo en PC — Steam y el launcher PURPLE. Merv Lee Kwai: «Lamentablemente, no hay planes para la versión móvil.» Coherente con el posicionamiento PC-nativo."),
        section("controllers", "Se soportan mandos en PC", "«Absolutamente, los mandos están soportados», respondió Merv Lee Kwai. Dado el combate aéreo y el doble salto, es una confirmación importante para jugadores de PC."),
        section("launch-timeline", "El calendario", "LST gratuito 17-18 de septiembre vía Steam; acceso anticipado de Founder's Pack el 30 de septiembre; lanzamiento free-to-play el 5 de octubre. Los jugadores de consola deberán esperar a que la versión PC esté asentada."),
      ],
    }),
    ja: articleCopy(newsLabels, "ja", 6, {
      eyebrow: "プラットフォームロードマップ",
      title: "Aion 2 コンソール版が正式に準備中：PCとのクロスプレイはおそらく非対応、グローバルは当面PCのみ",
      description: "NCが10月5日のグローバルローンチ後にコンソール版を準備中と確認；クロスプレイはおそらく分離運営；モバイル版の計画なし",
      intro: "9月7日、Gamescomプレゼン後のインタビューでNCは初めてAion 2のコンソール版準備を明言——ただしグローバルローンチは当面PCのみ、PCとコンソールのクロスプレイはおそらく非対応、モバイル版の計画もありません。",
      sourceNote: "Wccftech 2026年9月7日付Gamescomインタビュー（Aion 2チーム：김남준・Merv Lee Kwai・Andrew Long）に基づき、公式Steamストアページ（2026-09-08取得）と照合。",
      keywords: ["Aion 2 コンソール版", "Aion 2 クロスプレイ PC コンソール", "Aion 2 モバイル 計画なし", "Aion 2 グローバル PCのみ", "Aion 2 プラットフォーム ロードマップ"],
      sections: [
        section("console-confirmed", "コンソール版が確定——グローバル後に", "김남준氏：「実はコンソール版も準備しています。ただ優先はまずグローバルローンチで、コンソール対応はその後です。」初の明言。プラットフォーム名・時期は未公表。"),
        section("cross-play-likely-separate", "PCとのクロスプレイ：おそらく分離", "김남준氏：「明確な決定はまだですが、現時点ではPCとコンソールのクロスプレイはおそらく非対応になるでしょう。利用方法・ゲームプレイ・リリース時期が異なるからです。」作業仮説は別サーバー運営。"),
        section("no-mobile-pc-only", "モバイル版なし；グローバルはPCのみ", "グローバル版はPCのみ——Steamと自社ランチャーPURPLE。Merv Lee Kwai氏：「残念ながらモバイル版の計画はありません。」PCネイティブという位置づけと一致。"),
        section("controllers", "PCでコントローラー対応", "「もちろん、コントローラー対応です」とMerv Lee Kwai氏。空中戦と二段ジャンプが核のAion 2では、PCプレイヤーにとって重要な確認です。"),
        section("launch-timeline", "タイムライン", "無料LSTは9月17-18日（Steam）、ファウンダーズパック先行は9月30日から、F2Pローンチは10月5日。コンソール版の時期は未定で、PC版が軌道に乗るのを待つ形です。"),
      ],
    }),
    "pt-br": articleCopy(newsLabels, "pt-br", 6, {
      eyebrow: "ROADMAP DE PLATAFORMAS",
      title: "Versão de console do Aion 2 confirmada: cross-play com PC provavelmente não; global continua só PC por enquanto",
      description: "NCsoft confirma que prepara uma versão de console do Aion 2 após o lançamento global de 5 de outubro; cross-play provavelmente separado; sem planos mobile",
      intro: "Em entrevista de 7 de setembro após uma apresentação na Gamescom, a NCsoft confirmou pela primeira vez que prepara uma versão de console do Aion 2 — mas o lançamento global continua só PC, o cross-play entre PC e console provavelmente não será suportado, e não há planos mobile.",
      sourceNote: "Baseado na entrevista da Wccftech de 7 de setembro de 2026 com a equipe do Aion 2 (Namjoon Kim, Merv Lee Kwai, Andrew Long) na Gamescom, cruzado com a página oficial da Steam (acessada em 8 de setembro de 2026).",
      keywords: ["Aion 2 versão console", "Aion 2 cross-play PC console", "Aion 2 mobile sem planos", "Aion 2 lançamento global só PC", "Aion 2 plataformas roadmap"],
      sections: [
        section("console-confirmed", "Uma versão de console confirmada — após o lançamento global", "Namjoon Kim respondeu: «Na verdade, estamos preparando um lançamento de console também. Mas nossa prioridade é primeiro o lançamento global; o suporte a console virá depois.» Primeira confirmação explícita; sem plataformas ou prazos."),
        section("cross-play-likely-separate", "Cross-play com PC: provavelmente uma operação separada", "Kim: «ainda não decidimos, mas por enquanto o cross-play provavelmente não será suportado entre PC e console, porque o uso, o gameplay e o calendário são diferentes.» Premissa de trabalho: servidores separados."),
        section("no-mobile-pc-only", "Sem versão mobile; o global é só PC", "A versão global sai só no PC — Steam e o launcher PURPLE. Merv Lee Kwai: «Infelizmente, não há planos para a versão mobile.» Coerente com o posicionamento PC-nativo."),
        section("controllers", "Controles são suportados no PC", "«Absolutamente, controles são suportados», respondeu Merv Lee Kwai. Com o combate aéreo e o double jump no centro, é uma confirmação relevante para jogadores de PC."),
        section("launch-timeline", "O calendário", "LST gratuito 17-18 de setembro via Steam; acesso antecipado dos Founder's Pack em 30 de setembro; lançamento free-to-play em 5 de outubro. Jogadores de console devem esperar a versão PC se estabelecer."),
      ],
    }),
    ru: articleCopy(newsLabels, "ru", 6, {
      eyebrow: "ПЛАТФОРМЕННАЯ ДОРОЖНАЯ КАРТА",
      title: "Консольная версия Aion 2 подтверждена: кросс-плей с ПК вряд ли будет, глобальный запуск пока только на ПК",
      description: "NCsoft подтверждает подготовку консольной версии Aion 2 после глобального запуска 5 октября; кросс-плей, вероятно, раздельный; мобильных планов нет",
      intro: "В интервью 7 сентября после презентации на Gamescom NCsoft впервые подтвердила подготовку консольной версии Aion 2 — но глобальный запуск остаётся только на ПК, кросс-плей между ПК и консолями, скорее всего, не будет поддерживаться, а мобильной версии не планируется.",
      sourceNote: "На основе интервью Wccftech от 7 сентября 2026 г. с командой Aion 2 (Намджун Ким, Мерв Ли Квай, Эндрю Лонг) на Gamescom, сверено с официальной страницей Steam (получена 8 сентября 2026 г.).",
      keywords: ["Aion 2 консольная версия", "Aion 2 кросс-плей ПК консоль", "Aion 2 мобильная версия нет", "Aion 2 глобальный запуск только ПК", "Aion 2 платформы дорожная карта"],
      sections: [
        section("console-confirmed", "Консольная версия подтверждена — после глобального запуска", "Намджун Ким ответил: «Вообще-то мы готовим и консольный запуск. Но наш приоритет — сначала глобальный запуск; поддержка консолей последует за ним». Первое явное подтверждение; платформы и сроки не названы."),
        section("cross-play-likely-separate", "Кросс-плей с ПК: вероятно, раздельная операция", "Ким: «окончательного решения нет, но пока кросс-плей между ПК и консолями, скорее всего, не будет поддерживаться, потому что использование, геймплей и сроки запуска разные». Рабочая гипотеза — отдельные серверы."),
        section("no-mobile-pc-only", "Мобильной версии нет; глобально только ПК", "Глобальная версия выходит только на ПК — Steam и собственный лаунчер PURPLE. Мерв Ли Квай: «К сожалению, планов на мобильную версию нет». Соответствует позиционированию «PC-native»."),
        section("controllers", "Геймпады поддерживаются на ПК", "«Безусловно, геймпады поддерживаются», — ответил Мерв Ли Квай. Учитывая воздушный бой и двойной прыжок, это важное подтверждение для ПК-игроков."),
        section("launch-timeline", "График", "Бесплатный LST 17–18 сентября через Steam; ранний доступ для владельцев Founder's Pack с 30 сентября; бесплатный запуск 5 октября. Консольным игрокам придётся подождать, пока ПК-версия встанет на ноги."),
      ],
    }),
    ko: articleCopy(newsLabels, "ko", 6, {
      eyebrow: "플랫폼 로드맵",
      title: "아이온2 콘솔 버전 공식 준비 중: PC와 크로스플레이는 아마 미지원, 글로벌은 당분간 PC 전용",
      description: "NC가 10월 5일 글로벌 출시 이후 콘솔 버전을 준비 중이라고 확인; 크로스플레이는 아마 분리 운영; 모바일 계획 없음",
      intro: "9월 7일 Gamescom 프레젠테이션 후 인터뷰에서 NC가 처음으로 아이온2 콘솔 버전 준비를 공식 확인했습니다——하지만 글로벌 출시는 당분간 PC 전용, PC-콘솔 크로스플레이는 아마 미지원, 모바일 계획도 없습니다.",
      sourceNote: "Wccftech 2026년 9월 7일 Gamescom 인터뷰(아이온2 팀: 김남준·Merv Lee Kwai·Andrew Long)를 기반으로, 공식 Steam 스토어 페이지(2026-09-08 확인)와 교차 검증했습니다.",
      keywords: ["아이온2 콘솔 버전", "아이온2 크로스플레이 PC 콘솔", "아이온2 모바일 계획 없음", "아이온2 글로벌 PC 전용", "아이온2 플랫폼 로드맵"],
      sections: [
        section("console-confirmed", "콘솔 버전 확정——글로벌 이후", "김남준 디렉터가 직접 답했습니다: \"사실 콘솔 출시도 준비하고 있습니다. 다만 우선순위는 글로벌 출시가 먼저이고, 콘솔 지원은 그 뒤를 따릅니다.\" 콘솔 버전 로드맵 존재를 처음으로 공식 확인한 발언이며, 플랫폼과 시기는 미공개입니다."),
        section("cross-play-likely-separate", "PC와 크로스플레이: 아마 분리 운영", "김남준 디렉터: \"아직 명확한 결정은 없지만, 현재로선 PC와 콘솔 간 크로스플레이는 아마 지원되지 않을 것입니다. 사용 방식과 게임플레이, 출시 시점이 다르기 때문입니다.\" 작업 가정은 별도 서버 운영입니다."),
        section("no-mobile-pc-only", "모바일 없음; 글로벌은 PC 전용", "글로벌 빌드는 PC 전용으로 출시됩니다——Steam과 자체 런처 PURPLE. Merv Lee Kwai: \"아쉽게도 모바일 버전 계획은 없습니다.\" NC가 강조해온 'PC 네이티브' 포지셔닝과 일치합니다."),
        section("controllers", "PC에서 컨트롤러 지원", "\"물론, 컨트롤러를 지원합니다\"——Merv Lee Kwai의 답변입니다. 공중전과 이단 점프 비행이 핵심인 아이온2에서, 게임패드를 선호하는 PC 유저에게 의미 있는 확인입니다."),
        section("launch-timeline", "일정 정리", "무료 규모 테스트(LST)는 9월 17-18일 Steam으로 진행, 파운더스 팩 소지자는 9월 30일부터 조기 접속, F2P 글로벌 출시는 10월 5일입니다. 콘솔은 PC 버전이 자리 잡은 뒤가 될 전망이며, NC는 아직 시기를 밝히지 않았습니다."),
      ],
    }),
    "zh-hant": articleCopy(newsLabels, "zh-hant", 6, {
      eyebrow: "平台路線",
      title: "Aion 2 主機版確認：與 PC 跨平台大概率不支援；全球版現階段僅 PC",
      description: "NCsoft 確認 Aion 2 主機版正在籌備（緊隨 10 月 5 日全球首發之後）；跨平台大概率分開營運；全球版無行動端計畫",
      intro: "在 9 月 7 日 Gamescom 發表會後的專訪中，NCsoft 首次明確確認 Aion 2 主機版正在籌備——但全球首發仍僅限 PC，PC 與主機跨平台大概率不支援，且無行動端計畫。",
      sourceNote: "基於 Wccftech 2026 年 9 月 7 日在 Gamescom 對 Aion 2 開發團隊（金南俊、Merv Lee Kwai、Andrew Long）的專訪，並與官方 Steam 商店頁（2026-09-08 抓取）交叉核對。",
      keywords: ["Aion 2 主機版", "Aion 2 PC 主機跨平台", "Aion 2 行動版 無計畫", "Aion 2 全球首發 僅 PC", "Aion 2 平台路線"],
      sections: [
        section("console-confirmed", "主機版確認——緊隨全球首發", ["被問及潛在主機版時，Aion 2 的金南俊直接回答：「事實上，我們也在籌備主機版。但我們的優先級是先做好全球首發，主機支援會在其後跟進。」", "這是官方首次明確主機版在路線圖中。未公布具體平台，時間窗口也只有「PC 全球首發之後」。"]),
        section("cross-play-likely-separate", "與 PC 跨平台：大概率分開營運", ["關於 PC 與主機跨平台，金南俊表示團隊尚未做最終決定，「但目前我們認為 PC 與主機之間大概率不會支援跨平台，因為使用方式與玩法不同，且 PC 與主機的上線時間也不同。」", "他補充說此事尚未確認，「但目前傾向是分開營運」——預設假設是獨立伺服器而非共享佇列。"]),
        section("no-mobile-pc-only", "無行動版；全球版首發僅 PC", ["全球版只在 PC 上架——Steam 與 NC 自家的 PURPLE 啟動器。被問及行動端時，Merv Lee Kwai 直言：「很遺憾，沒有行動版計畫。」", "這與部分亞洲市場預期不同，但符合 NC 反覆強調的全球版「PC 原生」定位。"]),
        section("controllers", "PC 支援手把", ["喜歡手把的 PC 玩家有福了：被問及遊戲是否支援手把時，Merv Lee Kwai 回答「當然，支援手把。」", "空中戰鬥與二段跳飛行是 Aion 2 的核心體驗，因此手把支援對想用手把輸入的 PC 玩家是有意義的確認。"]),
        section("launch-timeline", "時間線一覽", ["主機版新聞之外的節點不變：免費規模測試 9 月 17-18 日經 Steam 進行，創辦人包持有者 9 月 30 日起搶先體驗，免費制全球首發定於 10 月 5 日。", "首個賽季將在 PC 上線且跨平台大概率分開，主機玩家應做好等 PC 版站穩再說——NC 尚未給出主機版時間估計。"]),
      ],
    }),
  },
};
