import { articleCopy, guideLabels, localizations, publishedVerified, section } from "./trending-september-12-shared";
import type { ContentEntry, ContentHeroImage, ContentSource } from "./content-registry";

/* ARTICLE 5 — Will the global launch repeat the Korean balance complaints? FAQ on the modified Season 1 and the revenue-risk debate */

const newsquestSource: ContentSource = {
  id: "newsquest-aion2-global-revenue-risk-2026-09-10",
  kind: "third-party",
  publisher: "Newsquest (뉴스퀘스트)",
  label: "User Complaints Become Results... As Aion 2 Stumbles, Warning Lights for NC's Global Revenue",
  url: "https://www.newsquest.co.kr/news/articleView.html?idxno=300674",
  publishedAt: "2026-09-10",
  retrievedAt: "2026-09-12",
  verifiedAt: "2026-09-12",
  localizations: localizations({
    "zh-hans": "用户不满成为业绩…Aion 2 步履蹒跚，NC 全球营收亮起警示灯",
    en: "User Complaints Become Results... As Aion 2 Stumbles, Warning Lights for NC's Global Revenue",
    fr: "Les plaintes des joueurs deviennent des résultats… Aion 2 trébuche, NC voit ses revenus globaux clignoter",
    de: "Nutzerbeschwerden werden zu Zahlen… Aion 2 stolpert, NCs globale Einnahmen warnen",
    es: "Las quejas de los usuarios se vuelven resultados… Aion 2 tropieza y las alarmas se encienden para los ingresos globales de NC",
    ja: "ユーザー不満が業績に…Aion 2 がつまずき、NCのグローバル売上に警告灯",
    "pt-br": "Reclamações de usuários viram resultados... Aion 2 tropeça e os alarmes acendem para a receita global da NC",
    ru: "Недовольство игроков становится результатами… Aion 2 спотыкается, у NC загораются огни тревоги по глобальной выручке",
    ko: "유저 불만이 실적으로…'아이온2' 삐걱대자 NC 글로벌 매출에도 경고등",
    "zh-hant": "使用者不滿成為業績…Aion 2 步履蹣跚，NC 全球營收亮起警示燈",
  }, "https://www.newsquest.co.kr/news/articleView.html?idxno=300674"),
};

const wfSource: ContentSource = {
  id: "wccftech-aion2-qa-2026-09-07",
  kind: "third-party",
  publisher: "Wccftech",
  label: "Aion 2 Q&A: NVIDIA DLSS 5 Confirmed in the Works; Console Launch Is Coming, but Cross-Play Likely Isn't",
  url: "https://wccftech.com/aion-2-qa-dlss-5-console-cross-play/",
  publishedAt: "2026-09-07",
  retrievedAt: "2026-09-12",
  verifiedAt: "2026-09-12",
  localizations: localizations({
    "zh-hans": "Aion 2 Q&A：DLSS 5 确认开发中；主机版将至，但跨平台大概率不支持",
    en: "Aion 2 Q&A: NVIDIA DLSS 5 Confirmed in the Works; Console Launch Is Coming, but Cross-Play Likely Isn't",
    fr: "Aion 2 Q&R : DLSS 5 confirmé, lancement console à venir, mais le cross-play probablement pas",
    de: "Aion 2 Q&A: DLSS 5 bestätigt, Konsolen-Launch kommt, Cross-Play wohl nicht",
    es: "Aion 2 Preguntas y respuestas: DLSS 5 confirmado, lanzamiento de consola en camino, pero el cross-play probablemente no",
    ja: "Aion 2 Q&A：DLSS 5 開発中を確認、コンソール版準備中、クロスプレイはおそらく非対応",
    "pt-br": "Aion 2 Q&A: DLSS 5 confirmado, lançamento para consoles a caminho, mas cross-play provavelmente não",
    ru: "Aion 2 Q&A: DLSS 5 подтверждён, консольный запуск готовится, кросс-плей вряд ли будет",
    ko: "아이온2 Q&A: DLSS 5 개발 중 확인, 콘솔 출시 준비 중, 크로스플레이는 아마 미지원",
    "zh-hant": "Aion 2 Q&A：DLSS 5 確認開發中；主機版將至，但跨平台大概率不支援",
  }, "https://wccftech.com/aion-2-qa-dlss-5-console-cross-play/"),
};

const bHero: ContentHeroImage = {
  src: "https://blogfiles.ncsoft.net/news/af7330da-4ff6-4b58-aece-400e6061a3be.jpg",
  width: 1200, height: 630,
  credit: "NC Corporation",
  sourceUrl: "https://aion2.plaync.com/en-us/",
  rights: "linked-official-media",
  translations: {
    "zh-hans": { alt: "Aion 2 全球版平衡风险 FAQ 横幅", caption: "分析师担心韩服平衡不满导致的收入下滑会在 10/5 全球版重演；本文梳理：改良版 Season 1 的 QoL/平衡改动（无门槛/成长平滑/PvP 可选）、$15 会员模型与减负设计如何直接回应这一担忧。" },
    en: { alt: "Aion 2 global launch balance-risk FAQ banner", caption: "Analysts worry Aion 2's Korea balance-complaint revenue decline could repeat globally after October 5. This FAQ walks through how the modified Season 1 — no gates, smoothed progression, optional PvP, the $15 membership — directly answers that concern." },
    fr: { alt: "Bannière FAQ du risque d'équilibrage du lancement global d'Aion 2", caption: "Les analystes craignent que le déclin coréen lié aux plaintes d'équilibrage ne se répète après le 5 octobre. Cette FAQ montre comment la Saison 1 modifiée — sans seuils, progression lissée, PvP optionnel, adhésion à 15 $ — répond à cette inquiétude." },
    de: { alt: "Banner der FAQ zum Balance-Risiko des Global-Starts von Aion 2", caption: "Analysten befürchten, dass sich der koreanische Balance-Beschwerde-Umsatzrückgang nach dem 5. Oktober global wiederholt. Diese FAQ zeigt, wie die modifizierte Season 1 — keine Gates, geglättete Progression, optionales PvP, die 15-$-Membership — dem direkt begegnet." },
    es: { alt: "Banner de preguntas frecuentes sobre el riesgo de equilibrio del lanzamiento global de Aion 2", caption: "Los analistas temen que el declive coreano por quejas de equilibrio se repita tras el 5 de octubre. Esta FAQ muestra cómo la Temporada 1 modificada — sin límites, progresión suavizada, PvP opcional, membresía de $15 — responde directamente." },
    ja: { alt: "Aion 2 グローバルローンチ バランスリスクFAQバナー", caption: "アナリストは韓国のバランス不満による売上低下が10月5日以降グローバルでも繰り返される懸念を表明。本FAQは改良版シーズン1——ゲートなし、成長の平滑化、PvP任意、15ドルメンバーシップ——がその懸念にどう直接応えるかを整理します。" },
    "pt-br": { alt: "Banner de FAQ do risco de equilíbrio do lançamento global do Aion 2", caption: "Analistas temem que o declínio coreano por reclamações de equilíbrio se repita após 5 de outubro. Este FAQ mostra como a Temporada 1 modificada — sem limites, progressão suavizada, PvP opcional, associação de US$ 15 — responde diretamente." },
    ru: { alt: "Баннер FAQ о риске баланса глобального запуска Aion 2", caption: "Аналитики опасаются, что корейский спад из-за жалоб на баланс повторится после 5 октября. Этот FAQ показывает, как модифицированный Сезон 1 — без гейтов, сглаженная прокачка, необязательный PvP, подписка $15 — прямо отвечает на это." },
    ko: { alt: "Aion 2 글로벌 출시 밸런스 리스크 FAQ 배너", caption: "애널리스트들은 한국의 밸런스 불만 매출 하락이 10/5 이후 글로벌에서도 반복될 수 있다고 우려합니다. 이 FAQ는 수정판 시즌 1——게이트 없음, 성장의 유연화, PvP 선택, $15 멤버십——이 그 우려에 어떻게 직접 답하는지 정리합니다." },
    "zh-hant": { alt: "Aion 2 全球版平衡風險 FAQ 橫幅", caption: "分析師擔心韓服平衡不滿導致的收入下滑會在 10/5 全球版重演；本文梳理：改良版 Season 1 的 QoL/平衡改動（無門檻/成長平滑/PvP 可選）、$15 會員模型與減負設計如何直接回應這一擔憂。" },
  },
};

export const trendingSeptember12Article5: ContentEntry = {
  section: "guides",
  slug: "aion-2-global-launch-balance-risk-faq",
  schemaType: "Article",
  publishedAt: "2026-09-12",
  updatedAt: "2026-09-12",
  readingMinutes: 6,
  publication: publishedVerified,
  sources: [newsquestSource, wfSource],
  heroImage: bHero,
  related: [
    { kind: "content", section: "news", slug: "aion-2-global-launch-revenue-risk-analysis" },
    { kind: "content", section: "guides", slug: "aion-2-global-qol-no-daily-gates-guide" },
    { kind: "content", section: "guides", slug: "aion-2-global-version-changes-guide" },
    { kind: "content", section: "news", slug: "aion-2-global-launch-content-model-season-1" },
  ],
  translations: {
    en: articleCopy(guideLabels, "en", 6, {
      eyebrow: "LAUNCH FAQ",
      title: "Will Aion 2's Global Launch Repeat the Korean Balance Complaints? A FAQ on the Modified Season 1 and the Revenue-Risk Debate",
      description: "Analysts flagged the risk that Aion 2's Korea/Taiwan revenue decline — driven by balance dissatisfaction — repeats globally after October 5. This FAQ walks through what the modified Season 1 actually changes and whether the global build addresses the complaint patterns",
      intro: "A September 10 analyst note cut NCsoft's target price partly because Aion 2's Korea/Taiwan revenue is declining faster than expected on growing balance dissatisfaction — and warned the pattern could repeat after the October 5 global launch. This FAQ breaks down what the modified Season 1 actually changes, and how much of the analyst concern it addresses.",
      sourceNote: "Based on Newsquest's September 10, 2026 report of Kiwoom Securities' analysis and Wccftech's September 7, 2026 interview with the Aion 2 team (both retrieved September 12, 2026).",
      keywords: ["Aion 2 global launch balance complaints FAQ", "Aion 2 modified Season 1 changes", "Aion 2 revenue decline repeat global", "Aion 2 QoL balance improvements", "Aion 2 global launch risk FAQ"],
      sections: [
        section("will-it-repeat", "Will the Korean Decline Pattern Repeat Globally?", ["Analysts are applying the Korea/Taiwan revenue-decline pattern to next year's global estimates by analogy — a risk flag, not a forecast. The global build has not launched, so the pattern is an assumption about revenue persistence, not a statement about the game itself.", "The mitigating argument is structural: the global build is not a port of Korea's current state. It ships a modified Season 1 with the quality-of-life and balance improvements that the Korean service accumulated, which is exactly the layer the complaints target."]),
        section("what-changes", "What the Modified Season 1 Actually Changes", ["Per the September 7 developer interview: the global build launches with the same Season 1 Korea and Taiwan started with, but modified — including the QoL and balance improvements — and item progression was smoothed so nothing in your accumulated progression is lost.", "That is a direct answer to the 'stair-stepped progression' complaint pattern that analysts cite: gear upgrades are meant to feel continuous, not like disconnected big chunks."]),
        section("no-gates-pvp", "No Daily/Weekly Gates and Optional PvP", ["The same interview confirmed the global build has no daily or weekly content gates — you can come and play whenever and however much you want — and that PvP is being repositioned as a choice rather than a requirement.", "Both address the fatigue and forced-PvP complaints that typically drive churn in Korean MMOs, and both are the specific mechanics that the analyst note's 'balance dissatisfaction' framing tends to reference."]),
        section("monetization-context", "The Monetization Context: One $15 Membership", ["The global economy consolidates the dual subscription into a single $15/month membership, with Founder's Packs bundling 30 days. Trade and convenience sit behind the membership; dungeons, raids, and PvP are not gated by it.", "Transparent pricing and a single subscription tier are the kind of monetization clarity that mitigates the 'pay-to-progress' perception risks — though the real test is how the crafted Tier 4 economy lands in the global market."]),
        section("what-to-watch", "What to Watch After October 5", ["1. Whether the modified Season 1's QoL layer keeps early retention above the Korean curve; 2. Whether the Seal and crafted-gear economy avoids the whale-vs-free perception gap; 3. Whether the piloting/macro enforcement holds in the global raid scene (the first Korean crackdown was a strong signal); 4. Whether the ~3-month season cadence behind Korea keeps content flowing faster than complaints accumulate.", "For players, the takeaway is practical: the global build is the improved version of the exact systems the analysts worry about — the risk debate is about economics, and the game's own QoL layer is the counterargument."]),
      ],
    }),
    "zh-hans": articleCopy(guideLabels, "zh-hans", 6, {
      eyebrow: "首发 FAQ",
      title: "Aion 2 全球版会重演韩服平衡不满吗？改良版 Season 1 与营收风险之争 FAQ",
      description: "分析师提示：由平衡不满驱动的 Aion 2 韩服/台服收入下滑可能在 10 月 5 日全球版重演。本文梳理改良版 Season 1 实际改了什么，以及全球版在多大程度上回应了不满模式",
      intro: "9 月 10 日分析师下调 NCsoft 目标价的部分理由：Aion 2 韩服/台服收入因日益增长的平衡不满而下滑快于预期——并警告该模式可能在 10 月 5 日全球首发后重演。本 FAQ 拆解改良版 Season 1 实际改了什么，以及它在多大程度上回应了分析师的担忧。",
      sourceNote: "基于 뉴스퀘스트（Newsquest）2026 年 9 月 10 日对 Kiwoom 证券分析的报道，与 Wccftech 2026 年 9 月 7 日对 Aion 2 开发团队的专访（均于 2026-09-12 抓取）。",
      keywords: ["Aion 2 全球版 平衡不满 FAQ", "Aion 2 改良版 Season 1 改动", "Aion 2 收入下滑 全球重演", "Aion 2 QoL 平衡改进", "Aion 2 全球首发 风险 FAQ"],
      sections: [
        section("will-it-repeat", "韩服下滑模式会在全球重演吗？", ["分析师正把韩服/台服收入下滑模式类推到明年的全球预估——这是风险提示而非预测。全球版尚未上线，该模式只是对收入持续性的假设，并非对游戏本身的论断。", "缓解论点具有结构性：全球版不是韩服现况的直接移植。它以改良版 Season 1 上线，搭载韩服积累的 QoL 与平衡改进——这恰恰是不满所指向的层面。"]),
        section("what-changes", "改良版 Season 1 实际改了什么", ["据 9 月 7 日开发者专访：全球版以韩服/台服最初上线的同一 Season 1 开始，但为改良版——包含 QoL 与平衡改进——且物品成长已平滑化，你积累的成长不会丢失。", "这是对分析师所引「阶梯式成长」不满模式的直接回应：装备升级应感觉连续，而非互不相连的大块。"]),
        section("no-gates-pvp", "无日常/周常门槛与可选 PvP", ["同一专访确认全球版无日常/周常内容门槛——想什么时候来都行、想玩多少玩多少——且 PvP 被重新定位为选择而非义务。", "两者都回应了通常导致韩式 MMO 流失的疲劳与强制 PvP 抱怨，也正是指分析师「平衡不满」框架的机制。"]),
        section("monetization-context", "变现语境：$15 单一会员", ["全球经济把双订阅整合为每月 $15 单一会员，创始人包附带 30 天。交易与便利在会员之后，副本、团队与 PvP 不受其门槛限制。", "透明的定价与单一订阅档是缓解「氪金变强」感知风险的那类变现清晰度——不过真正的考验是制作 Tier 4 经济在全球市场的落地方式。"]),
        section("what-to-watch", "10 月 5 日后观察什么", ["1. 改良版 Season 1 的 QoL 层能否让早期留存高于韩服曲线；2. 印章与制作装备经济能否避免「氪佬 vs 免费」感知鸿沟；3. 代练/宏执法能否在全球副本场景维持（韩服首轮打击是强信号）；4. 落后韩服约三个月的赛季节奏能否让内容流动快于不满积累。", "对玩家的实用结论：全球版正是分析师所担忧的那些系统的改进版——风险之争关乎经济，而游戏自身的 QoL 层就是反方论据。"]),
      ],
    }),
    fr: articleCopy(guideLabels, "fr", 5, {
      eyebrow: "FAQ LANCEMENT",
      title: "Le lancement global d'Aion 2 répétera-t-il les plaintes coréennes d'équilibrage ? FAQ sur la Saison 1 modifiée",
      description: "Les analystes ont signalé le risque que le déclin coréen/taiwanais — insatisfaction d'équilibrage — se répète après le 5 octobre. Cette FAQ détaille ce que la Saison 1 modifiée change réellement",
      intro: "Une note du 10 septembre a abaissé l'objectif de NCsoft, notamment parce que le déclin coréen/taiwanais d'Aion 2 est plus rapide que prévu — et a averti que le schéma pourrait se répéter après le 5 octobre. Cette FAQ décompose les changements réels de la Saison 1 modifiée.",
      sourceNote: "Basé sur le rapport de Newsquest du 10 septembre 2026 (analyse Kiwoom) et l'entretien de Wccftech du 7 septembre 2026 (récupérés le 12 septembre 2026).",
      keywords: ["Aion 2 plaintes d'équilibrage global FAQ", "Aion 2 Saison 1 modifiée changements", "Aion 2 répétition déclin global", "Aion 2 améliorations QoL équilibrage", "Aion 2 risque lancement global FAQ"],
      sections: [
        section("will-it-repeat", "Le schéma coréen se répétera-t-il ?", "Le schéma KR/TW est appliqué par analogie aux estimations 2027 — un drapeau de risque, pas une prévision. Le global n'a pas lancé : c'est une hypothèse de persistance, pas un jugement sur le jeu. Argument structurel : le global n'est pas un port de l'état coréen — Saison 1 modifiée avec les QoL/balance accumulés."),
        section("what-changes", "Ce que change la Saison 1 modifiée", "Selon l'interview du 7 septembre : même Season 1 que Corée/Taiwan au départ, mais modifiée (QoL + équilibrage), progression d'objets lissée « pour que rien ne soit perdu » — réponse directe au pattern « progression en escalier »."),
        section("no-gates-pvp", "Sans seuils et PvP optionnel", "Pas de seuils quotidiens/hebdomadaires ; PvP repositionné comme choix. Les deux répondent à la fatigue et au PvP forcé — les mécaniques derrière l'« insatisfaction d'équilibrage » des analystes."),
        section("monetization-context", "Contexte monétisation", "Abonnement unique à 15 $/mois, Founder's Packs avec 30 jours ; commerce et commodités derrière la membership, pas les donjons/raids/PvP. La clarté atténue le risque de perception pay-to-progress ; le test réel est l'économie Tier 4."),
        section("what-to-watch", "À surveiller après le 5 octobre", "1. Rétention au-dessus de la courbe coréenne ; 2. Économie Sceau/Tier 4 sans fossé whale-vs-free ; 3. Maintien de l'application pilotage/macros ; 4. Cadence saisonnière plus rapide que l'accumulation des plaintes. Pour les joueurs : le global est la version améliorée des systèmes que les analystes craignent."),
      ],
    }),
    de: articleCopy(guideLabels, "de", 5, {
      eyebrow: "LAUNCH-FAQ",
      title: "Wiederholt der Global-Start von Aion 2 die koreanischen Balance-Beschwerden? FAQ zur modifizierten Season 1",
      description: "Analysten haben das Risiko signalisiert, dass sich der Korea/Taiwan-Umsatzrückgang — Balance-Unzufriedenheit — nach dem 5. Oktober global wiederholt. Diese FAQ zeigt, was die modifizierte Season 1 wirklich ändert",
      intro: "Eine Analystennotiz vom 10. September senkte das NCsoft-Kursziel, weil der Korea/Taiwan-Umsatzrückgang von Aion 2 schneller läuft als erwartet — und warnte, das Muster könnte sich nach dem 5. Oktober wiederholen. Diese FAQ zerlegt, was die modifizierte Season 1 wirklich ändert.",
      sourceNote: "Basierend auf dem Newsquest-Bericht vom 10. September 2026 (Kiwoom-Analyse) und dem Wccftech-Interview vom 7. September 2026 (abgerufen am 12. September 2026).",
      keywords: ["Aion 2 Balance-Beschwerden Global FAQ", "Aion 2 modifizierte Season 1 Änderungen", "Aion 2 Wiederholung Rückgang Global", "Aion 2 QoL Balance-Verbesserungen", "Aion 2 Risiko Global-Start FAQ"],
      sections: [
        section("will-it-repeat", "Wiederholt sich das koreanische Muster?", "Das KR/TW-Muster wird analog auf 2027 übertragen — eine Risikofahne, keine Prognose. Global hat noch nicht gestartet. Strukturelles Gegenargument: Global ist kein Port des koreanischen Stands — modifizierte Season 1 mit den angesammelten QoL/Balance-Verbesserungen."),
        section("what-changes", "Was die modifizierte Season 1 ändert", "Laut Interview vom 7. September: dieselbe Season 1 wie Korea/Taiwan zu Beginn, aber modifiziert (QoL + Balance), geglättete Item-Progression „damit nichts verloren geht“ — direkte Antwort auf das Stufen-Progression-Muster."),
        section("no-gates-pvp", "Keine Gates und optionales PvP", "Keine Tages-/Wochen-Gates; PvP als Wahl neu positioniert. Beide adressieren Fatigue und erzwungenes PvP — die Mechaniken hinter der „Balance-Unzufriedenheit“ der Analysten."),
        section("monetization-context", "Monetarisierungskontext", "Eine Membership für 15 $/Monat, Founder's Packs mit 30 Tagen; Handel und Komfort hinter der Membership, nicht Dungeons/Raids/PvP. Klarheit mindert Pay-to-Progress-Wahrnehmung; der echte Test ist die Tier-4-Wirtschaft."),
        section("what-to-watch", "Beobachten nach dem 5. Oktober", "1. Retention über der koreanischen Kurve ; 2. Seal-/Tier-4-Wirtschaft ohne Whale-vs-Free-Graben ; 3. Hält die Piloten-/Makro-Durchsetzung ; 4. Saison-Kadenz schneller als Beschwerde-Akkumulation. Für Spieler: Global ist die verbesserte Version der Systeme, die Analysten fürchten."),
      ],
    }),
    es: articleCopy(guideLabels, "es", 5, {
      eyebrow: "FAQ DE LANZAMIENTO",
      title: "¿El lanzamiento global de Aion 2 repetirá las quejas coreanas de equilibrio? FAQ sobre la Temporada 1 modificada",
      description: "Los analistas señalaron el riesgo de que el declive Corea/Taiwán — insatisfacción de equilibrio — se repita tras el 5 de octubre. Esta FAQ detalla qué cambia realmente la Temporada 1 modificada",
      intro: "Una nota del 10 de septiembre recortó el objetivo de NCsoft, en parte porque el declive coreano/taiwanés de Aion 2 es más rápido de lo previsto — y advirtió que el patrón podría repetirse tras el 5 de octubre. Esta FAQ desglosa qué cambia realmente la Temporada 1 modificada.",
      sourceNote: "Basado en el informe de Newsquest del 10 de septiembre de 2026 (análisis de Kiwoom) y la entrevista de Wccftech del 7 de septiembre de 2026 (recuperados el 12 de septiembre de 2026).",
      keywords: ["Aion 2 quejas de equilibrio global FAQ", "Aion 2 Temporada 1 modificada cambios", "Aion 2 repetición declive global", "Aion 2 mejoras QoL equilibrio", "Aion 2 riesgo lanzamiento global FAQ"],
      sections: [
        section("will-it-repeat", "¿Se repetirá el patrón coreano?", "El patrón KR/TW se aplica por analogía a 2027 — una bandera de riesgo, no una previsión. El global no ha lanzado. Argumento estructural: el global no es un port del estado coreano — Temporada 1 modificada con las QoL/balance acumulados."),
        section("what-changes", "Qué cambia la Temporada 1 modificada", "Según la entrevista del 7 de septiembre: la misma Temporada 1 de Corea/Taiwán al inicio, pero modificada (QoL + equilibrio), progresión de objetos suavizada «para que nada se pierda» — respuesta directa al patrón de progresión en escalón."),
        section("no-gates-pvp", "Sin límites y PvP opcional", "Sin límites diarios/semanales; PvP reposicionado como elección. Ambos atienden la fatiga y el PvP forzado — las mecánicas tras la «insatisfacción de equilibrio» de los analistas."),
        section("monetization-context", "Contexto de monetización", "Membresía única de $15/mes, Founder's Packs con 30 días; comercio y comodidades tras la membresía, no mazmorras/raids/PvP. La claridad mitiga el riesgo de percepción pay-to-progress; la prueba real es la economía Tier 4."),
        section("what-to-watch", "Qué observar tras el 5 de octubre", "1. Retención sobre la curva coreana; 2. Economía Sello/Tier 4 sin brecha whale-vs-free; 3. Que se mantenga la aplicación pilotaje/macros; 4. Cadencia estacional más rápida que la acumulación de quejas. Para jugadores: el global es la versión mejorada de los sistemas que los analistas temen."),
      ],
    }),
    ja: articleCopy(guideLabels, "ja", 5, {
      eyebrow: "ローンチFAQ",
      title: "Aion 2 グローバルは韓国のバランス不満を繰り返すか？改良版シーズン1と売上リスク論争のFAQ",
      description: "アナリストは韓国・台湾の売上低下——バランス不満——が10月5日以降グローバルでも繰り返されるリスクを警告。本FAQは改良版シーズン1が実際に何を変えるかを整理します",
      intro: "9月10日のアナリストノートはNC目標株価を引き下げましたが、その理由の一つがAion 2の韓国・台湾売上がバランス不満の高まりで想定より速く低下していること——そして10月5日以降も同じパターンが繰り返される恐れ。本FAQは改良版シーズン1が実際に何を変えるかを分解します。",
      sourceNote: "ニュースクエスト2026年9月10日付（Kiwoom証券分析）とWccftech 2026年9月7日付インタビュー（いずれも2026-09-12取得）に基づきます。",
      keywords: ["Aion 2 グローバル バランス不満 FAQ", "Aion 2 改良版シーズン1 変更", "Aion 2 売上低下 再現 グローバル", "Aion 2 QoL バランス改善", "Aion 2 グローバルローンチ リスク FAQ"],
      sections: [
        section("will-it-repeat", "韓国の低下パターンはグローバルで繰り返されるか", "アナリストはKR/TWの売上低下パターンを来年のグローバル予想に「準用」しています——リスクフラグであって予測ではありません。グローバルはまだ未ローンチで、これは収益持続性への仮定です。構造的な反論：グローバルは韓国の現状の移植ではなく、蓄積されたQoL・バランス改善を載せた改良版シーズン1で始まります。"),
        section("what-changes", "改良版シーズン1が実際に変えること", "9月7日の開発者インタビューによれば：韓国・台湾が最初に始めた同じシーズン1で開始しますが、QoL・バランス改善を含む改良版で、アイテム成長も「蓄積した成長が失われないよう」平滑化されています。アナリストが挙げる「階段状成長」不満への直接の回答です。"),
        section("no-gates-pvp", "デイリー/ウィークリーなしとPvP任意", "同じインタビューで、日次/週次コンテンツゲートなし（好きなときに好きなだけ）、PvPは選択として再定位——が確認されています。韓国MMOの離脱要因である疲労と強制PvPへの対処であり、アナリストの「バランス不満」の枠組みが指す具体的なメカニクスです。"),
        section("monetization-context", "マネタイズの文脈：月15ドルの単一メンバーシップ", "グローバル経済は二重サブスクを月$15の単一メンバーシップに統合し、ファウンダーズパックに30日分を含めます。取引と便利機能はメンバーシップの後ろ、ダンジョン・レイド・PvPはゲートされません。透明な価格と単一課金は「課金で強くなる」という認識リスクを和らげます——本当の試練は制作Tier 4経済のグローバルでの着地です。"),
        section("what-to-watch", "10月5日以降の注視点", "1. 改良版のQoL層が初期リテンションを韓国より高く保てるか; 2. シール・制作装備経済が課金層vs無課金の溝を作らないか; 3. 代行・マクロ取締がグローバルのレイドでも維持されるか（韓国の初の取締は強いシグナル）; 4. 約3カ月のシーズン間隔でコンテンツ供給が不満蓄積より速いか。プレイヤーへの実用的結論：グローバルはアナリストが懸念するシステムの改善版であり、ゲーム自身のQoL層が反論です。"),
      ],
    }),
    "pt-br": articleCopy(guideLabels, "pt-br", 5, {
      eyebrow: "FAQ DE LANÇAMENTO",
      title: "O lançamento global do Aion 2 repetirá as reclamações coreanas de equilíbrio? FAQ sobre a Temporada 1 modificada",
      description: "Analistas sinalizaram o risco de que a queda Coreia/Taiwan — insatisfação de equilíbrio — se repita após 5 de outubro. Este FAQ detalha o que a Temporada 1 modificada realmente muda",
      intro: "Uma nota de 10 de setembro cortou o alvo da NCsoft, em parte porque a queda coreana/taiwanesa do Aion 2 é mais rápida que o previsto — e alertou que o padrão pode se repetir após 5 de outubro. Este FAQ decompõe o que a Temporada 1 modificada realmente muda.",
      sourceNote: "Baseado no relatório da Newsquest de 10 de setembro de 2026 (análise da Kiwoom) e na entrevista da Wccftech de 7 de setembro de 2026 (recuperados em 12 de setembro de 2026).",
      keywords: ["Aion 2 reclamações de equilíbrio global FAQ", "Aion 2 Temporada 1 modificada mudanças", "Aion 2 repetição queda global", "Aion 2 melhorias QoL equilíbrio", "Aion 2 risco lançamento global FAQ"],
      sections: [
        section("will-it-repeat", "O padrão coreano se repetirá?", "O padrão KR/TW é aplicado por analogia a 2027 — uma bandeira de risco, não uma previsão. O global não lançou. Argumento estrutural: o global não é um port do estado coreano — Temporada 1 modificada com as QoL/equilíbrio acumuladas."),
        section("what-changes", "O que a Temporada 1 modificada muda", "Segundo a entrevista de 7 de setembro: a mesma Temporada 1 de Coreia/Taiwan no início, mas modificada (QoL + equilíbrio), progressão de itens suavizada «para que nada se perca» — resposta direta ao padrão de progressão em degraus."),
        section("no-gates-pvp", "Sem limites e PvP opcional", "Sem limites diários/semanais; PvP reposicionado como escolha. Ambos atendem a fadiga e o PvP forçado — as mecânicas por trás da «insatisfação de equilíbrio» dos analistas."),
        section("monetization-context", "Contexto de monetização", "Associação única de US$ 15/mês, Founder's Packs com 30 dias; comércio e conveniências atrás da associação, não masmorras/raids/PvP. A clareza mitiga o risco de percepção pay-to-progress; o teste real é a economia Tier 4."),
        section("what-to-watch", "O que observar após 5 de outubro", "1. Retenção acima da curva coreana; 2. Economia de Selo/Tier 4 sem abismo whale-vs-free; 3. Manutenção da aplicação de pilotagem/macros; 4. Cadência sazonal mais rápida que o acúmulo de reclamações. Para jogadores: o global é a versão melhorada dos sistemas que os analistas temem."),
      ],
    }),
    ru: articleCopy(guideLabels, "ru", 5, {
      eyebrow: "FAQ ЗАПУСКА",
      title: "Повторит ли глобальный запуск Aion 2 корейские жалобы на баланс? FAQ о модифицированном Сезоне 1",
      description: "Аналитики сигнализировали о риске повторения спада Кореи/Тайваня — недовольство балансом — после 5 октября. Этот FAQ разбирает, что реально меняет модифицированный Сезон 1",
      intro: "Заметка от 10 сентября снизила целевую цену NCsoft отчасти из-за более быстрого, чем ожидалось, спада выручки Aion 2 в Корее/Тайване — и предупредила, что паттерн может повториться после 5 октября. Этот FAQ разбирает реальные изменения модифицированного Сезона 1.",
      sourceNote: "На основе отчёта Newsquest от 10 сентября 2026 г. (анализ Kiwoom) и интервью Wccftech от 7 сентября 2026 г. (получены 12 сентября 2026 г.).",
      keywords: ["Aion 2 жалобы на баланс глобал FAQ", "Aion 2 модифицированный Сезон 1 изменения", "Aion 2 повторение спада глобал", "Aion 2 улучшения QoL баланса", "Aion 2 риск глобального запуска FAQ"],
      sections: [
        section("will-it-repeat", "Повторится ли корейский паттерн?", "Паттерн KR/TW переносится по аналогии на 2027-й — флаг риска, не прогноз. Глобал ещё не запущен. Структурный аргумент: глобал — не порт корейского состояния; модифицированный Сезон 1 с накопленными QoL/балансом."),
        section("what-changes", "Что меняет модифицированный Сезон 1", "По интервью от 7 сентября: тот же Сезон 1, что у Кореи/Тайваня в начале, но модифицированный (QoL + баланс), сглаженная прокачка «чтобы ничего не терялось» — прямой ответ на паттерн «ступенчатой прокачки»."),
        section("no-gates-pvp", "Без гейтов и необязательный PvP", "Нет ежедневных/еженедельных гейтов; PvP перепозиционирован как выбор. Оба отвечают на усталость и принудительный PvP — механики за «недовольством балансом» аналитиков."),
        section("monetization-context", "Контекст монетизации", "Единая подписка $15/мес, Founder's Packs с 30 днями; торговля и удобства за подпиской, не данжи/рейды/PvP. Прозрачность смягчает риск восприятия pay-to-progress; настоящий тест — экономика Tier 4."),
        section("what-to-watch", "Что наблюдать после 5 октября", "1. Ретенция выше корейской кривой; 2. Экономика Печати/Tier 4 без пропасти кит-против-фри; 3. Удержание мер по пилотингу/макросам; 4. Сезонный темп быстрее накопления жалоб. Для игроков: глобал — улучшенная версия систем, которых боятся аналитики."),
      ],
    }),
    ko: articleCopy(guideLabels, "ko", 5, {
      eyebrow: "출시 FAQ",
      title: "아이온2 글로벌은 한국의 밸런스 불만을 반복할까? 수정판 시즌 1과 매출 리스크 논쟁 FAQ",
      description: "애널리스트들은 한국·대만 매출 하락——밸런스 불만——이 10월 5일 이후 글로벌에서도 반복될 리스크를 경고했습니다. 이 FAQ는 수정판 시즌 1이 실제로 무엇을 바꾸는지 정리합니다",
      intro: "9월 10일자 증권사 리포트가 NC 목표주가를 내린 이유 중 하나는 아이온2의 한국·대만 매출이 밸런스 불만 증가로 예상보다 가파르게 하락한다는 것——그리고 10월 5일 글로벌 출시 이후에도 같은 패턴이 반복될 수 있다는 경고였습니다. 이 FAQ는 수정판 시즌 1이 실제로 무엇을 바꾸는지 분해합니다.",
      sourceNote: "뉴스퀘스트 2026년 9월 10일자(키움증권 분석)와 Wccftech 2026년 9월 7일자 인터뷰(모두 2026-09-12 확인)를 기반으로 했습니다.",
      keywords: ["아이온2 글로벌 밸런스 불만 FAQ", "아이온2 수정판 시즌 1 변경", "아이온2 매출 하락 글로벌 재현", "아이온2 QoL 밸런스 개선", "아이온2 글로벌 출시 리스크 FAQ"],
      sections: [
        section("will-it-repeat", "한국의 하락 패턴이 글로벌에서 반복될까", "애널리스트들은 한국·대만 매출 하락 패턴을 내년 글로벌 추정치에 '준용'하고 있습니다——리스크 경고이지 예측은 아닙니다. 글로벌은 아직 출시 전이라, 이 패턴은 매출 지속성에 대한 가정이지 게임 자체에 대한 판단이 아닙니다.", "완충 논거는 구조적입니다: 글로벌 빌드는 한국 서버 현황의 직역이 아닙니다. 한국이 쌓아온 QoL·밸런스 개선을 포함한 수정판 시즌 1로 출시되며, 이는 불만이 겨냥하는 바로 그 층입니다."),
        section("what-changes", "수정판 시즌 1이 실제로 바꾸는 것", "9월 7일 개발자 인터뷰에 따르면: 한국·대만이 처음 시작한 동일한 시즌 1로 출시하되, QoL·밸런스 개선을 포함한 수정판이며, 아이템 성장도 '쌓아온 성장이 유실되지 않도록' 유연화됐습니다.", "애널리스트가 인용하는 '계단식 성장' 불만 패턴에 대한 직접적인 답변입니다: 장비 강화가 단절된 큰 덩어리가 아니라 연속적으로 느껴지도록 한 것입니다."),
        section("no-gates-pvp", "일일/주간 게이트 없음과 PvP 선택", "같은 인터뷰에서 글로벌 빌드에 일일/주간 콘텐츠 게이트가 없다는 것(원할 때 와서 원하는 만큼)과, PvP가 선택으로 재정의된다는 것이 확인됐습니다.", "둘 다 한국형 MMORPG의 이탈 요인인 피로도와 강제 PvP 불만에 대응하며, 증권사 '밸런스 불만' 프레임이 가리키는 구체적 메커니즘입니다."),
        section("monetization-context", "과금 구조 맥락: 월 $15 단일 멤버십", "글로벌 경제는 이중 구독을 월 $15 단일 멤버십으로 통합하고 파운더스 팩에 30일을 포함합니다. 거래와 편의 기능이 멤버십 뒤에 있고, 던전·레이드·PvP는 멤버십으로 막히지 않습니다.", "투명한 가격과 단일 구독 등급은 '과금으로 강해지는 것'이라는 인식 리스크를 줄이는 종류의 명확성입니다——진짜 시험대는 제작 Tier 4 경제가 글로벌 시장에서 어떻게 자리 잡는지입니다."),
        section("what-to-watch", "10월 5일 이후 지켜볼 것", "1. 수정판 시즌 1의 QoL 층이 초기 리텐션을 한국보다 높게 유지하는가; 2. 인장·제작 장비 경제가 과금층 vs 무과금의 인식 격차를 만들지 않는가; 3. 대리·매크로 단속이 글로벌 레이드에서도 유지되는가(한국의 첫 단속은 강한 신호); 4. 한국보다 약 3개월 늦은 시즌 주기가 불만 축적보다 빠르게 콘텐츠를 공급하는가.", "플레이어에게 실용적인 결론: 글로벌은 애널리스트가 우려하는 시스템의 개선판입니다——리스크 논쟁은 경제학에 관한 것이고, 게임 자체의 QoL 층이 반박 논거입니다."),
      ],
    }),
    "zh-hant": articleCopy(guideLabels, "zh-hant", 5, {
      eyebrow: "首發 FAQ",
      title: "Aion 2 全球版會重演韓服平衡不滿嗎？改良版 Season 1 與營收風險之爭 FAQ",
      description: "分析師提示：由平衡不滿驅動的 Aion 2 韓服/台服收入下滑可能在 10 月 5 日全球版重演。本文梳理改良版 Season 1 實際改了什么，以及全球版在多大程度上回應了不滿模式",
      intro: "9 月 10 日分析師下調 NCsoft 目標價的部分理由：Aion 2 韓服/台服收入因日益增長的平衡不滿而下滑快於預期——並警告該模式可能在 10 月 5 日全球首發後重演。本 FAQ 拆解改良版 Season 1 實際改了什么，以及它在多大程度上回應了分析師的擔憂。",
      sourceNote: "基於 뉴스퀘스트（Newsquest）2026 年 9 月 10 日對 Kiwoom 證券分析的報導，與 Wccftech 2026 年 9 月 7 日對 Aion 2 開發團隊的專訪（均於 2026-09-12 抓取）。",
      keywords: ["Aion 2 全球版 平衡不滿 FAQ", "Aion 2 改良版 Season 1 改動", "Aion 2 收入下滑 全球重演", "Aion 2 QoL 平衡改進", "Aion 2 全球首發 風險 FAQ"],
      sections: [
        section("will-it-repeat", "韓服下滑模式會在全球重演嗎？", ["分析師正把韓服/台服收入下滑模式類推到明年的全球預估——這是風險提示而非預測。全球版尚未上線，該模式只是對收入持續性的假設，並非對遊戲本身的論斷。", "緩解論點具有結構性：全球版不是韓服現況的直接移植。它以改良版 Season 1 上線，搭載韓服累積的 QoL 與平衡改進——這恰恰是不滿所指的層面。"]),
        section("what-changes", "改良版 Season 1 實際改了什么", ["據 9 月 7 日開發者專訪：全球版以韓服/台服最初上線的同一 Season 1 開始，但為改良版——包含 QoL 與平衡改進——且物品成長已平滑化，你累積的成長不會丟失。", "這是對分析師所引「階梯式成長」不滿模式的直接回應：裝備升級應感覺連續，而非互不相連的大塊。"]),
        section("no-gates-pvp", "無日常/週常門檻與可選 PvP", ["同一專訪確認全球版無日常/週常內容門檻——想什麼時候來都行、想玩多少就玩多少——且 PvP 被重新定位為選擇而非義務。", "兩者都回應了通常導致韓式 MMO 流失的疲勞與強制 PvP 抱怨，也正是指分析師「平衡不滿」框架的機制。"]),
        section("monetization-context", "變現語境：$15 單一會員", ["全球經濟把雙訂閱整合為每月 $15 單一會員，創辦人包附帶 30 天。交易與便利在會員之後，副本、團隊與 PvP 不受其門檻限制。", "透明的定價與單一訂閱檔是緩解「課金變強」感知風險的那類變現清晰度——不過真正的考驗是製作 Tier 4 經濟在全球市場的落地方式。"]),
        section("what-to-watch", "10 月 5 日後觀察什麼", ["1. 改良版 Season 1 的 QoL 層能否讓早期留存高於韓服曲線；2. 印章與製作裝備經濟能否避免「課佬 vs 免費」感知鴻溝；3. 代練/巨集執法能否在全球副本場景維持（韓服首輪打擊是強訊號）；4. 落後韓服約三個月的賽季節奏能否讓內容流動快於不滿累積。", "對玩家的實用結論：全球版正是分析師所擔憂的那些系統的改進版——風險之爭關乎經濟，而遊戲自身的 QoL 層就是反方論據。"]),
      ],
    }),
  },
};