import { articleCopy, localizations, guideLabels, publishedVerified, section } from "./trending-september-16-shared";
import type { ContentEntry, ContentHeroImage, ContentSource } from "./content-registry";

const transitionSource: ContentSource = {
  id: "nc-aion2-official-transition",
  kind: "official",
  publisher: "NC Corporation",
  label: "Aion 2 Official — Returning Player Guide",
  url: "https://aion2.plaync.com/en-us/",
  publishedAt: "2026-08-15",
  retrievedAt: "2026-09-16",
  verifiedAt: "2026-09-16",
  localizations: localizations({
    "zh-hans": "Aion 2 官方 — 回归玩家指南",
    en: "Aion 2 Official — Returning Player Guide",
    fr: "Aion 2 Officiel — Guide du joueur de retour",
    de: "Aion 2 Offiziell — Rückkehrer-Leitfaden",
    es: "Aion 2 Oficial — Guía del jugador que regresa",
    ja: "Aion 2 公式 — リターナーガイド",
    "pt-br": "Aion 2 Oficial — Guia do Jogador Retornando",
    ru: "Aion 2 Официальный — Гайд для возвращающихся",
    ko: "Aion 2 공식 — 복귀 플레이어 가이드",
    "zh-hant": "Aion 2 官方 — 回歸玩家指南",
  }, "https://aion2.plaync.com/en-us/"),
};

const transitionHero: ContentHeroImage = {
  src: "https://blogfiles.ncsoft.net/news/af7330da-4ff6-4b58-aece-400e6061a3be.jpg",
  width: 1200, height: 630,
  credit: "NC Corporation",
  sourceUrl: "https://aion2.plaync.com/en-us/",
  rights: "linked-official-media",
  translations: {
    "zh-hans": { alt: "Aion 2 老玩家回归攻略横幅", caption: "从 Aion 1 回归 Aion 2 的完整指南——系统差异、进阶变化和老玩家必备知识。" },
    en: { alt: "Aion 2 Transition Guide Banner", caption: "Complete guide for returning from Aion 1 to Aion 2 — system differences, progression changes, and veteran essentials." },
    fr: { alt: "Bannière du guide de transition Aion 2", caption: "Guide complet pour revenir d'Aion 1 à Aion 2 — différences système, changements de progression et essentiels vétérans." },
    de: { alt: "Aion 2 Umstiegs-Guide Banner", caption: "Kompletter Leitfaden für die Rückkehr von Aion 1 zu Aion 2 — Systemunterschiede, Fortschrittsänderungen und Veteranen-Essentials." },
    es: { alt: "Banner de la guía de transición de Aion 2", caption: "Guía completa para volver de Aion 1 a Aion 2 — diferencias del sistema, cambios de progresión y esenciales para veteranos." },
    ja: { alt: "Aion 2 移行ガイドバナー", caption: "Aion 1からAion 2への復帰完全ガイド——システム差異、進捗変化、ベテラン必备情報。" },
    "pt-br": { alt: "Banner do guia de transição do Aion 2", caption: "Guia completo para retornar do Aion 1 ao Aion 2 — diferenças de sistema, mudanças de progressão e essenciais para veteranos." },
    ru: { alt: "Баннер гайда по переходу Aion 2", caption: "Полное руководство по возвращению из Aion 1 в Aion 2 — различия систем, изменения прогрессии и необходимое для ветеранов." },
    ko: { alt: "Aion 2 전환 가이드 배너", caption: "Aion 1에서 Aion 2로 복귀하는 완전 가이드 — 시스템 차이, 진행 변화, 베테랑 필수 정보." },
    "zh-hant": { alt: "Aion 2 老玩家回歸攻略橫幅", caption: "從 Aion 1 回歸 Aion 2 的完整指南——系統差異、進階變化和老玩家必備知識。" },
  },
};

export const trendingSeptember16Article1: ContentEntry = {
  section: "guides",
  slug: "aion-2-aion-1-to-aion-2-transition-guide",
  schemaType: "Article",
  publishedAt: "2026-09-16",
  updatedAt: "2026-09-16",
  readingMinutes: 6,
  publication: publishedVerified,
  sources: [transitionSource],
  heroImage: transitionHero,
  related: [
    { kind: "content", section: "guides", slug: "aion-2-launch-classes-guide" },
    { kind: "content", section: "guides", slug: "aion-2-leveling-guide-1-50" },
    { kind: "content", section: "guides", slug: "aion-2-endgame-path-guide" },
    { kind: "content", section: "guides", slug: "aion-2-skill-system-deep-dive" },
  ],
  translations: {
    en: articleCopy(guideLabels, "en", 6, {
      eyebrow: "RETURNING PLAYERS",
      title: "Aion 1 to Aion 2 Transition Guide: Everything Veterans Need to Know",
      description: "Complete transition guide for Aion 1 veterans moving to Aion 2. Learn what changed in combat, classes, economy, and progression — and how your experience gives you an edge.",
      intro: "Aion 2 is not a simple sequel — it is a ground-up rebuild on Unreal Engine 5 with a new action combat system, a streamlined class roster, and a reworked progression model. For Aion 1 veterans, this guide covers every major system change so you can leverage your experience efficiently from day one.",
      sourceNote: "Based on NC's official gameplay pages and the Korean service as of September 2026. Global launch adjustments may apply.",
      keywords: ["Aion 1 to Aion 2", "Aion 2 transition guide", "Aion 2 for veterans", "Aion 2 vs Aion 1", "Aion 2 returning players"],
      sections: [
        section("what-changed", "Key Differences Between Aion 1 and Aion 2", ["Aion 2 runs on Unreal Engine 5, replacing the proprietary Aion engine. This means dramatically improved graphics, real-time lighting, and larger draw distances. The world of Atreia has been rebuilt from scratch with seamless zone transitions — no more loading screens between major areas.", "The class system has been streamlined from Aion 1's 12+ classes down to 6 starter classes at launch, with each class offering deeper customization through the Stigma and skill preset systems rather than class proliferation. If you played Sorcerer in Aion 1, expect Arcanist to feel familiar but with entirely new mechanics.", "Combat has shifted from tab-target to action-based. Positioning, dodging, and timing matter far more than in Aion 1's auto-attack-centric system. The flight system has also been reworked — it is now integrated into combat rather than being a separate mode."]),
        section("account-progression", "Account and Progression: What Carries Over", ["Nothing carries over from Aion 1 to Aion 2. This is a completely fresh start — new characters, new servers, new economy. However, your knowledge of Aion's world, quest patterns, and dungeon layouts transfers directly.", "Server selection for global launch follows the same regional model: NA, EU, JP, SA. Korean and Taiwanese servers remain separate. Choose your server based on community size and language preference, just as you would have in Aion 1.", "Veterans have a significant advantage in early-game efficiency. You already know optimal questing routes, dungeon mechanics, and class synergies. The leveling curve is different, but your map knowledge and system familiarity will put you ahead of brand-new players."]),
        section("combat-evolution", "Combat System Evolution", ["Aion 1's tab-target combat is gone. Aion 2 uses a full action combat system similar to Aion 1's class-specific mechanics but applied universally. Every skill requires manual aiming, and positional attacks (back attacks, flanking) deal bonus damage.", "The skill system uses a Stigma slot model where you equip a limited number of skills and swap them via presets. This replaces Aion 1's massive skill list approach. You will have fewer skills active at once, but each one matters more in rotation.", "Flight in Aion 2 is integrated into combat rather than being a toggle mode. You can use aerial skills while flying, and the wing system has progression tiers that affect flight duration and aerial combat effectiveness. This is a major shift from Aion 1's separate flight mode."]),
        section("economy-differences", "Economy and Progression Differences", ["The Kinah economy in Aion 2 follows a similar player-driven market model, but the brokerage system has been updated with new filtering, price history, and cross-server listing features. Crafting has been restructured into distinct profession chains with less overlap than Aion 1.", "Gear progression is more streamlined. Instead of Aion 1's complex enchantment and manastone system, Aion 2 uses a simplified enhancement system with clearer upgrade tiers and reduced failure penalties. Endgame gear still requires significant grinding through trials and raids.", "The Daeva Pass (membership) model remains similar to Aion 1's premium system, offering quality-of-life perks and cosmetic benefits. Free-to-play is fully viable for core content, but membership accelerates progression through additional inventory, teleportation discounts, and exclusive cosmetics."]),
        section("veteran-tips", "Tips for Veteran Players", ["Do not rush to endgame. Aion 2's modified progression curve is designed for players to explore content at a measured pace. Use your veteran knowledge to optimize, not to skip. The story content and zone exploration have been significantly expanded.", "Experiment with the skill preset system early. Unlike Aion 1's permanent skill unlocks, Aion 2's preset system lets you swap builds for different content. Find your preferred playstyle before committing to endgame optimization.", "Join a guild on day one. Aion 2's endgame content — trials, Abyss PvP, siege warfare — requires coordinated groups. Your veteran experience makes you a valuable recruit, and guild connections will accelerate your progression through group content and market access."]),
      ],
    }),
    "zh-hans": articleCopy(guideLabels, "zh-hans", 6, {
      eyebrow: "回归玩家",
      title: "Aion 1 到 Aion 2 过渡指南：老玩家必备知识",
      description: "Aion 1 老玩家转向 Aion 2 的完整过渡指南。了解战斗、职业、经济和进阶的所有变化——以及如何利用你的经验获得优势。",
      intro: "Aion 2 不是简单的续作——它是基于虚幻引擎 5 的全面重建，采用全新动作战斗系统、精简的职业阵容和重做的进阶模型。本指南覆盖每个主要系统变化，帮助老玩家从第一天起高效利用经验。",
      sourceNote: "基于 NC 官方游戏页面和韩服（截至 2026 年 9 月）。全球版可能有调整。",
      keywords: ["Aion 1 到 Aion 2", "Aion 2 过渡指南", "Aion 2 老玩家", "Aion 2 与 Aion 1", "Aion 2 回归玩家"],
      sections: [
        section("what-changed", "Aion 1 与 Aion 2 的关键差异", ["Aion 2 运行在虚幻引擎 5 上，取代了 Aion 的专有引擎。画面大幅提升，实时光照和更远的渲染距离。亚特雷亚世界从零重建，区域无缝过渡——主要区域之间不再有加载画面。", "职业系统从 Aion 1 的 12+ 职业精简到上线时 6 个起始职业，每个职业通过烙印和技能预设系统提供更深度的自定义，而非职业堆叠。如果你在 Aion 1 玩的是魔术师，可以期待奥术师感觉熟悉但机制完全不同。", "战斗从锁定目标转向动作制。走位、闪避和时机比 Aion 1 的自动攻击系统重要得多。飞行系统也重做了——现在整合进战斗而非独立模式。"]),
        section("account-progression", "账号与进阶：什么能继承", ["Aion 1 到 Aion 2 没有任何数据继承。这是全新开始——新角色、新服务器、新经济。但你对 Aion 世界、任务模式和副本布局的知识直接转移。", "全球版服务器选择沿用区域模型：北美、欧洲、日本、南美。韩服和台服独立。根据社区规模和语言偏好选择服务器，和 Aion 1 一样。", "老玩家在早期效率上有显著优势。你已经知道最优任务路线、副本机制和职业配合。升级曲线不同，但地图知识和系统熟悉度会让你领先全新玩家。"]),
        section("combat-evolution", "战斗系统演变", ["Aion 1 的锁定目标战斗消失了。Aion 2 使用全面动作战斗系统，类似 Aion 1 的职业专属机制但普遍应用。每个技能需要手动瞄准，位置攻击（背刺、侧翼）有额外伤害。", "技能系统使用烙印槽模型，装备有限技能并通过预设切换。取代了 Aion 1 的庞大技能列表方式。同时激活的技能更少，但每个技能在循环中更重要。", "Aion 2 的飞行整合进战斗而非切换模式。飞行中可以使用空中技能，翅膀系统有进阶等级影响飞行时间和空中战斗效果。这是与 Aion 1 独立飞行模式的重大转变。"]),
        section("economy-differences", "经济与进阶差异", ["Aion 2 的 Kinah 经济沿用类似的玩家驱动市场模型，但交易所系统更新了新的过滤、价格历史和跨服挂牌功能。制作被重构为不同的专业链，重叠比 Aion 1 更少。", "装备进阶更精简。不再是 Aion 1 复杂的附魔和魔石系统，Aion 2 使用简化的强化系统，有更清晰的升级等级和降低的失败惩罚。后期装备仍需通过试炼和团队副本大量刷取。", "Daeva Pass（会员）模式与 Aion 1 的高级系统类似，提供生活质量和外观福利。免费游玩核心内容完全可行，但会员通过额外背包、传送折扣和独占外观加速进阶。"]),
        section("veteran-tips", "老玩家建议", ["不要急着冲到后期。Aion 2 的改良进阶曲线是为让玩家按节奏探索内容设计的。利用老玩家知识优化，而不是跳过。故事内容和区域探索大幅扩展了。", "尽早尝试技能预设系统。不同于 Aion 1 的永久技能解锁，Aion 2 的预设系统让你切换不同内容的构建。在投入后期优化前找到你的偏好玩法。", "第一天就加入公会。Aion 2 的后期内容——试炼、深渊 PvP、攻城战——需要协调团队。你的老玩家经验让你成为有价值的招募对象，公会联系将通过团队内容和市场渠道加速你的进阶。"]),
      ],
    }),
    fr: articleCopy(guideLabels, "fr", 6, {
      eyebrow: "JOUEURS DE RETOUR",
      title: "Guide de Transition d'Aion 1 à Aion 2 : Tout Ce que les Vétérans Doivent Savoir",
      description: "Guide de transition complet pour les vétérans d'Aion 1 passant à Aion 2. Découvrez ce qui a changé en combat, classes, économie et progression.",
      intro: "Aion 2 n'est pas une simple suite — c'est une reconstruction complète sur Unreal Engine 5 avec un nouveau système de combat action, un roster de classes simplifié et un modèle de progression retravaillé.",
      sourceNote: "Basé sur les pages gameplay officielles de NC et le serveur coréen (septembre 2026). Des ajustements pour le lancement mondial peuvent s'appliquer.",
      keywords: ["Aion 1 vers Aion 2", "Guide transition Aion 2", "Aion 2 pour vétérans", "Aion 2 vs Aion 1", "Aion 2 joueurs revenants"],
      sections: [
        section("what-changed", "Différences Clés Entre Aion 1 et Aion 2", ["Aion 2 tourne sur Unreal Engine 5, remplaçant le moteur propriétaire d'Aion. Graphismes considérablement améliorés, éclairage temps réel et distances de rendu plus grandes. Le monde d'Atreia a été reconstruit avec des transitions de zone fluides — plus d'écrans de chargement entre les zones principales.", "Le système de classes a été rationalisé de 12+ classes d'Aion 1 à 6 classes de lancement, chaque classe offrant une personnalisation plus profonde via les systèmes de Stigma et de préréglages de compétences plutôt que la prolifération de classes.", "Le combat est passé du tab-target à l'action. Le positionnement, l'esquive et le timing comptent beaucoup plus que dans le système centré sur l'auto-attaque d'Aion 1. Le système de vol a également été retravaillé — il est maintenant intégré au combat."]),
        section("account-progression", "Compte et Progression : Ce Qui est Conservé", ["Rien ne passe d'Aion 1 à Aion 2. C'est un départ complètement nouveau — nouveaux personnages, nouveaux serveurs, nouvelle économie. Cependant, votre connaissance du monde d'Aion se transfère directement.", "La sélection de serveur suit le même modèle régional : NA, EU, JP, SA. Les serveurs coréen et taïwanais restent séparés. Choisissez votre serveur selon la taille de la communauté et la préférence linguistique.", "Les vétérans ont un avantage significatif en efficacité early-game. Vous connaissez déjà les routes de quêtes optimales, les mécaniques de donjon et les synergies de classes."]),
        section("combat-evolution", "Évolution du Système de Combat", ["Le combat tab-target d'Aion 1 a disparu. Aion 2 utilise un système de combat action complet. Chaque compétence nécessite un visée manuelle, et les attaques positionnelles (dos, flanc) infligent des bonus.", "Le système de compétences utilise un modèle de slots de Stigma où vous équipez un nombre limité de compétences et les changez via des préréglages. Vous aurez moins de compétences actives, mais chacune compte davantage.", "Le vol dans Aion 2 est intégré au combat plutôt qu'un mode bascule. Vous pouvez utiliser des compétences aériennes en volant, et le système d'ailes a des niveaux de progression qui affectent la durée de vol et l'efficacité du combat aérien."]),
        section("economy-differences", "Différences d'Économie et de Progression", ["L'économie Kinah d'Aion 2 suit un modèle de marché joueur similaire, mais le système de courtage a été mis à jour avec de nouveaux filtres, l'historique des prix et les listings inter-serveurs.", "La progression d'équipement est plus rationalisée. Au lieu du système complexe d'enchantement et de manastones d'Aion 1, Aion 2 utilise un système d'amélioration simplifié avec des niveaux plus clairs et des pénalités d'échec réduites.", "Le modèle Daeva Pass reste similaire au système premium d'Aion 1, offrant des avantages QoL et cosmétiques. Le free-to-play est viable pour le contenu principal."]),
        section("veteran-tips", "Conseils pour les Vétérans", ["Ne vous précipitez pas vers l'endgame. La courbe de progression modifiée d'Aion 2 est conçue pour explorer le contenu à un rythme mesuré. Utilisez vos connaissances pour optimiser, pas pour sauter.", "Expérimentez le système de préréglages tôt. Contrairement aux déblocages permanents d'Aion 1, Aion 2 vous permet de changer de build pour différents contenus.", "Rejoignez une guilde dès le premier jour. Le contenu endgame d'Aion 2 — raids, PvP d'Abyss, guerres de siège — nécessite des groupes coordonnés. Votre expérience de vétéran vous rend précieux."]),
      ],
    }),
    de: articleCopy(guideLabels, "de", 6, {
      eyebrow: "RÜCKKEHRER",
      title: "Aion 1 zu Aion 2 Umstiegs-Guide: Alles was Veteranen Wissen Müssen",
      description: "Kompletter Umstiegs-Guide für Aion 1-Veteranen, die zu Aion 2 wechseln. Erfahren Sie, was sich in Kampf, Klassen, Wirtschaft und Fortschritt geändert hat.",
      intro: "Aion 2 ist keine einfache Fortsetzung — es ist ein vollständiger Neuaufbau auf Unreal Engine 5 mit einem neuen Action-Kampfsystem, einem optimierten Klassen-Repertoire und einem überarbeiteten Fortschrittsmodell.",
      sourceNote: "Basierend auf NCs offiziellen Gameplay-Seiten und dem koreanischen Server (September 2026). Globale Launch-Anpassungen können gelten.",
      keywords: ["Aion 1 zu Aion 2", "Aion 2 Umstiegs-Guide", "Aion 2 für Veteranen", "Aion 2 vs Aion 1", "Aion 2 zurückkehrende Spieler"],
      sections: [
        section("what-changed", "Wichtige Unterschiede Zwischen Aion 1 und Aion 2", ["Aion 2 läuft auf Unreal Engine 5 und ersetzt die proprietäre Aion-Engine. Deutlich verbesserte Grafik, Echtzeit-Beleuchtung und größere Sichtweiten. Die Welt von Atreia wurde neu aufgebaut mit nahtlosen Zonenübergängen — keine Ladebildschirme mehr zwischen Hauptgebieten.", "Das Klassensystem wurde von 12+ Klassen aus Aion 1 auf 6 Starterklassen zum Launch reduziert, wobei jede Klasse tiefere Anpassung durch Stigma- und Skill-Preset-Systeme bietet.", "Der Kampf hat sich von Tab-Target zu Action-basiert gewandelt. Positionierung, Ausweichen und Timing sind viel wichtiger als in Aion 1s Auto-Attack-System. Das Flugsystem wurde ebenfalls überarbeitet — es ist jetzt in den Kampf integriert."]),
        section("account-progression", "Konto und Fortschritt: Was Übernommen Wird", ["Nichts wird von Aion 1 nach Aion 2 übertragen. Dies ist ein komplett neuer Start — neue Charaktere, neue Server, neue Wirtschaft. Allerdings transferiert sich Ihr Wissen über Aions Welt direkt.", "Die Serverauswahl folgt dem gleichen regionalen Modell: NA, EU, JP, SA. Koreanische und taiwanesische Server bleiben separat.", "Veteranen haben einen signifikanten Vorteil in der Early-Game-Effizienz. Sie kennen bereits optimale Quest-Routen, Dungeon-Mechaniken und Klassen-Synergien."]),
        section("combat-evolution", "Entwicklung des Kampfsystems", ["Aion 1s Tab-Target-Kampf ist verschwunden. Aion 2 verwendet ein vollständiges Action-Kampfsystem. Jede Fähigkeit erfordert manuelles Zielen, und Positionsangriffe verursachen Bonusschaden.", "Das Skill-System verwendet ein Stigma-Slot-Modell. Sie werden weniger aktive Fähigkeiten haben, aber jede zählt mehr in der Rotation.", "Flug in Aion 2 ist in den Kampf integriert statt ein Umschaltmodus. Sie können Luftfähigkeiten im Flug nutzen, und das Flügelsystem hat Fortschrittsstufen."]),
        section("economy-differences", "Wirtschafts- und Fortschrittsunterschiede", ["Die Kinah-Wirtschaft in Aion 2 folgt einem ähnlichen spielergetriebenen Marktmodell, aber das Börsensystem wurde mit neuen Filtern, Preisverlauf und serverübergreifenden Listings aktualisiert.", "Ausrüstungsfortschritt ist optimierter. Statt Aion 1s komplexem Verzauberungs- und Manastone-System verwendet Aion 2 ein vereinfachtes Verbesserungs-System.", "Das Daeva Pass-Modell bleibt ähnlich zu Aion 1s Premium-System mit QoL-Vorteilen und kosmetischen Benefits."]),
        section("veteran-tips", "Tipps für Veteranenspieler", ["Überstürzen Sie nicht zum Endgame. Aion 2s modifizierte Fortschrittskurve ist für gemessenes Erkunden konzipiert.", "Experimentieren Sie früh mit dem Skill-Preset-System. Im Gegensatz zu Aion 1s permanenten Freischaltungen können Sie Builds für verschiedene Inhalte wechseln.", "Treten Sie am ersten Tag einer Gilde bei. Aion 2s Endgame-Inhalte — Prüfungen, Abyss-PvP, Belagerungen — erfordern koordinierte Gruppen."]),
      ],
    }),
    es: articleCopy(guideLabels, "es", 6, {
      eyebrow: "JUGADORES QUE REGRESAN",
      title: "Guía de Transición de Aion 1 a Aion 2: Todo lo que los Veteranos Necesitan Saber",
      description: "Guía de transición completa para veteranos de Aion 1 que pasan a Aion 2. Aprende qué cambió en combate, clases, economía y progresión.",
      intro: "Aion 2 no es una secuela simple — es una reconstrucción completa en Unreal Engine 5 con un nuevo sistema de combate de acción, un elenco de clases optimizado y un modelo de progresión renovado.",
      sourceNote: "Basado en las páginas de gameplay oficiales de NC y el servidor coreano (septiembre 2026). Pueden aplicar ajustes para el lanzamiento global.",
      keywords: ["Aion 1 a Aion 2", "Guía transición Aion 2", "Aion 2 para veteranos", "Aion 2 vs Aion 1", "Aion 2 jugadores que regresan"],
      sections: [
        section("what-changed", "Diferencias Clave Entre Aion 1 y Aion 2", ["Aion 2 funciona con Unreal Engine 5, reemplazando el motor propietario de Aion. Gráficos dramáticamente mejorados, iluminación en tiempo real y mayores distancias de renderizado. El mundo de Atreia ha sido reconstruido con transiciones de zona fluidas.", "El sistema de clases se ha optimizado de 12+ clases de Aion 1 a 6 clases iniciales en el lanzamiento, cada clase ofreciendo personalización más profunda a través de los sistemas de Stigma y presets de habilidades.", "El combate ha cambiado de tab-target a acción. El posicionamiento, la esquiva y el timing importan mucho más que en el sistema de Aion 1."]),
        section("account-progression", "Cuenta y Progresión: Qué Se Mantiene", ["Nada se transfiere de Aion 1 a Aion 2. Este es un comienzo completamente nuevo. Sin embargo, tu conocimiento del mundo de Aion se transfiere directamente.", "La selección de servidor sigue el mismo modelo regional: NA, EU, JP, SA. Los servidores coreano y taiwanés permanecen separados.", "Los veteranos tienen una ventaja significativa en eficiencia early-game. Ya conoces rutas de misiones óptimas, mecánicas de mazmorras y sinergias de clases."]),
        section("combat-evolution", "Evolución del Sistema de Combate", ["El combate tab-target de Aion 1 ha desaparecido. Aion 2 usa un sistema de combate de acción completo. Cada habilidad requiere apuntado manual.", "El sistema de habilidades usa un modelo de slots de Stigma. Tendrás menos habilidades activas, pero cada una importa más en la rotación.", "El vuelo en Aion 2 está integrado en el combate en lugar de ser un modo separado."]),
        section("economy-differences", "Diferencias de Economía y Progresión", ["La economía Kinah de Aion 2 sigue un modelo de mercado similar, pero el sistema de corretaje se ha actualizado con nuevos filtros e historial de precios.", "La progresión de equipo es más optimizada. En lugar del complejo sistema de encantamiento de Aion 1, Aion 2 usa un sistema de mejora simplificado.", "El modelo Daeva Pass permanece similar al sistema premium de Aion 1."]),
        section("veteran-tips", "Consejos para Jugadores Veteranos", ["No te apresures al endgame. La curva de progresión de Aion 2 está diseñada para explorar contenido a un ritmo medido.", "Experimenta con el sistema de presets de habilidades temprano. A diferencia de los desbloqueos permanentes de Aion 1, puedes cambiar builds.", "Únete a un gremio desde el primer día. El contenido endgame de Aion 2 requiere grupos coordinados."]),
      ],
    }),
    ja: articleCopy(guideLabels, "ja", 6, {
      eyebrow: "リターナー",
      title: "Aion 1からAion 2への移行ガイド：ベテランが知るべき全て",
      description: "Aion 1からAion 2へ移行するベテラン向け完全ガイド。戦闘、クラス、経済、進捗システムの変化を学びましょう。",
      intro: "Aion 2はシンプルな続編ではありません——Unreal Engine 5での全面再構築で、新しいアクション戦闘システム、最適化されたクラスラインナップ、改訂された進捗モデルを搭載しています。",
      sourceNote: "NC公式ゲームページと韓国情報（2026年9月時点）に基づいています。グローバル版の調整が適用される場合があります。",
      keywords: ["Aion 1からAion 2", "Aion 2 移行ガイド", "Aion 2 ベテラン向け", "Aion 2 vs Aion 1", "Aion 2 リターナー"],
      sections: [
        section("what-changed", "Aion 1とAion 2の主な違い", ["Aion 2はUnreal Engine 5で動作し、Aionの独自エンジンを置き換えました。グラフィックが大幅に向上し、リアルタイムライティングとより長い描画距離を実現。アトレイアの世界はゼロから再構築され、シームレスなゾーン遷移——主要エリア間のローディング画面はなくなりました。", "クラスシステムはAion 1の12以上からローンチ時に6スタータークラスに整理され、各クラスはスティグマとスキルプリセットシステムを通じてより深いカスタマイズを提供します。", "戦闘はタブターゲットからアクションベースに移行。ポジショニング、回避、タイミングがAion 1のオートアタック中心システムよりもはるかに重要です。"]),
        section("account-progression", "アカウントと進捗：引き継ぎについて", ["Aion 1からAion 2へ引き継がれるデータはありません。完全に新しいスタートです。ただし、Aionの世界、クエストパターン、ダンジョンレイアウトの知識はそのまま転移します。", "サーバー選択は同じリージョナルモデルに従います：NA、EU、JP、SA。韓国と台湾サーバーは引き続き分離されています。", "ベテランは序盤の効率に大きな優位性があります。最適なクエストルート、ダンジョンギミック、クラスシナジーを既に知っています。"]),
        section("combat-evolution", "戦闘システムの進化", ["Aion 1のタブターゲット戦闘はなくなりました。Aion 2はフルアクション戦闘システムを使用します。全スキルに手動エイミングが必要で、位置取り攻撃がボーナスダメージを与えます。", "スキルシステムはスティグマスロットモデルを使用します。同時にアクティブなスキルは少なくなりますが、ローテーションで各スキルがより重要になります。", "Aion 2の飛行は戦闘に統合されています。飛行中に空中スキルを使用でき、ウィングシステムに飛行時間と空中戦闘効果に影響する進捗ティアがあります。"]),
        section("economy-differences", "経済と進捗の違い", ["Aion 2のキnah経済は同様のプレイヤードリブン市場モデルに従いますが、ブローカレッジシステムは新しいフィルタリング、価格履歴、クロスサーバーリスティングで更新されました。", "装備進捗はより最適化されています。Aion 1の複雑なエンチャントとマナストーンシステムの代わりに、Aion 2はより明確なアップグレードティアと減少した失敗ペナルティを持つ簡素化された強化システムを使用します。", "ダエヴァパスモデルはAion 1のプレミアムシステムと類似しており、QoL特典とコスメティックを提供します。"]),
        section("veteran-tips", "ベテラン向けヒント", ["エンドゲームを急がないでください。Aion 2の修正された進捗曲線はコンテンツを計画的に探索するように設計されています。", "早めにスキルプリセットシステムを試してください。Aion 1の永続アンロックとは異なり、異なるコンテンツ用にビルドを切り替えられます。", "初日からギルドに参加してください。Aion 2のエンドゲームコンテンツ——試練、アビースPvP、攻城戦——には協調グループが必要です。"]),
      ],
    }),
    "pt-br": articleCopy(guideLabels, "pt-br", 6, {
      eyebrow: "JOGADORES RETORNANDO",
      title: "Guia de Transição do Aion 1 para Aion 2: Tudo que Veteranos Precisam Saber",
      description: "Guia completo de transição para veteranos do Aion 1 migrando para Aion 2. Saiba o que mudou em combate, classes, economia e progressão.",
      intro: "Aion 2 não é uma sequência simples — é uma reconstrução completa no Unreal Engine 5 com novo sistema de combate action, elenco de classes otimizado e modelo de progressão reformulado.",
      sourceNote: "Baseado nas páginas oficiais de gameplay da NC e no servidor coreano (setembro 2026). Ajustes de lançamento global podem se aplicar.",
      keywords: ["Aion 1 para Aion 2", "Guia transição Aion 2", "Aion 2 para veteranos", "Aion 2 vs Aion 1", "Aion 2 jogadores retornando"],
      sections: [
        section("what-changed", "Diferenças Principais Entre Aion 1 e Aion 2", ["Aion 2 roda no Unreal Engine 5, substituindo o motor proprietário do Aion. Gráficos drasticamente melhorados, iluminação em tempo real e maiores distâncias de renderização.", "O sistema de classes foi otimizado de 12+ classes do Aion 1 para 6 classes iniciais no lançamento, cada classe oferecendo personalização mais profunda através dos sistemas de Stigma e presets de habilidades.", "O combate mudou de tab-target para action-based. Posicionamento, esquiva e timing importam muito mais."]),
        section("account-progression", "Conta e Progressão: O que é Mantido", ["Nada é transferido do Aion 1 para Aion 2. Este é um começo completamente novo. Porém, seu conhecimento do mundo se transfere diretamente.", "A seleção de servidor segue o mesmo modelo regional: NA, EU, JP, SA.", "Veteranos têm vantagem significativa em eficiência early-game."]),
        section("combat-evolution", "Evolução do Sistema de Combate", ["O combate tab-target do Aion 1 desapareceu. Aion 2 usa um sistema de combate action completo.", "O sistema de habilidades usa um modelo de slots de Stigma. Menos habilidades ativas, mas cada uma conta mais na rotação.", "O voo no Aion 2 é integrado ao combate."]),
        section("economy-differences", "Diferenças de Economia e Progressão", ["A economia Kinah do Aion 2 segue um modelo similar, mas o sistema de corretagem foi atualizado.", "A progressão de装备 é mais otimizada. Em vez do complexo sistema de encantamento do Aion 1, Aion 2 usa um sistema de aprimoramento simplificado.", "O modelo Daeva Pass permanece similar ao sistema premium do Aion 1."]),
        section("veteran-tips", "Dicas para Jogadores Veteranos", ["Não corra para o endgame. A curva de progressão do Aion 2 é projetada para explorar conteúdo em ritmo moderado.", "Experimente o sistema de presets de habilidades cedo.", "Junte-se a uma guilda no primeiro dia. O conteúdo endgame requer grupos coordenados."]),
      ],
    }),
    ru: articleCopy(guideLabels, "ru", 6, {
      eyebrow: "ВОЗВРАЩАЮЩИЕСЯ",
      title: "Гайд по Переходу из Aion 1 в Aion 2: Всё что Нужно Знать Ветеранам",
      description: "Полный гайд по переходу для ветеранов Aion 1, переходящих в Aion 2. Узнайте что изменилось в бою, классах, экономике и прогрессии.",
      intro: "Aion 2 — не простое продолжение, а полная перестройка на Unreal Engine 5 с новой экшн-боевой системой, оптимизированным набором классов и переработанной моделью прогрессии.",
      sourceNote: "На основе официальных страниц геймплея NC и корейского сервера (сентябрь 2026). Могут применятьсяadjustments глобального запуска.",
      keywords: ["Aion 1 в Aion 2", "Гайд переход Aion 2", "Aion 2 для ветеранов", "Aion 2 vs Aion 1", "Aion 2 возвращающиеся"],
      sections: [
        section("what-changed", "Ключевые Различия Между Aion 1 и Aion 2", ["Aion 2 работает на Unreal Engine 5, заменяя проприетарный движок Aion. Значительно улучшенная графика, освещение реального времени и большие дистанции отрисовки.", "Система классов оптимизирована с 12+ классов Aion 1 до 6 стартовых классов на запуске, каждый класс предлагает более глубокую кастомизацию через системы Стигмы и пресетов навыков.", "Бой перешёл от таб-таргета к экшн-системе. Позиционирование, уклонение и тайминг важнее."]),
        section("account-progression", "Аккаунт и Прогрессия: Что Переносится", ["Ничто не переносится из Aion 1 в Aion 2. Это полностью новое начало. Однако ваши знания мира переносятся напрямую.", "Выбор сервера следует той же региональной модели: NA, EU, JP, SA.", "Ветераны имеют значительное преимущество в эффективности early-game."]),
        section("combat-evolution", "Эволюция Боевой Системы", ["Таб-таргет бой Aion 1 исчез. Aion 2 использует полную экшн-боевую систему.", "Система навыков использует модель слотов Стигмы. Меньше активных навыков, но каждый важнее в ротации.", "Полёт в Aion 2 интегрирован в бой."]),
        section("economy-differences", "Различия Экономики и Прогрессии", ["Экономика Кина в Aion 2 следует схожей модели, но система брокера обновлена.", "Прогрессия экипировки более оптимизирована. Вместо сложной системы зачарования Aion 1, Aion 2 использует упрощённую систему улучшения.", "Модель Daeva Pass остаётся схожей с премиум-системой Aion 1."]),
        section("veteran-tips", "Советы Ветеранам", ["Не спешите в эндшпиль. Кривая прогрессии Aion 2 рассчитана на размеренное исследование.", "Рано попробуйте систему пресетов навыков.", "Вступите в гильдию с первого дня. Эндшпиль-контент требует скоординированных групп."]),
      ],
    }),
    ko: articleCopy(guideLabels, "ko", 6, {
      eyebrow: "복귀 플레이어",
      title: "Aion 1에서 Aion 2 전환 가이드: 베테랑이 알아야 할 모든 것",
      description: "Aion 1에서 Aion 2로 전환하는 베테랑을 위한 완전 전환 가이드. 전투, 클래스, 경제, 진행 시스템의 변화를 확인하세요.",
      intro: "Aion 2는 단순한 속편이 아닙니다 — Unreal Engine 5에서의 전면 재구축으로, 새로운 액션 전투 시스템, 최적화된 클래스 라인업, 개편된 진행 모델을 탑재하고 있습니다.",
      sourceNote: "NC 공식 게임플레이 페이지와 한국 서버 기준 (2026년 9월). 글로벌 런칭 조정이 적용될 수 있습니다.",
      keywords: ["Aion 1에서 Aion 2", "Aion 2 전환 가이드", "Aion 2 베테랑", "Aion 2 vs Aion 1", "Aion 2 복귀 플레이어"],
      sections: [
        section("what-changed", "Aion 1과 Aion 2의 주요 차이점", ["Aion 2는 Unreal Engine 5에서 구동되며 Aion의 독자 엔진을 대체합니다. 그래픽이 대폭 개선되었고, 실시간 라이팅과 더 먼 렌더링 거리를 제공합니다.", "클래스 시스템은 Aion 1의 12개 이상에서 론치 시 6개 스타터 클래스로 정리되었으며, 각 클래스는 스티그마와 스킬 프리셋 시스템을 통해 더 깊은 커스터마이징을 제공합니다.", "전투는 탭 타겟에서 액션 기반으로 전환되었습니다. 포지셔닝, 회피, 타이밍이 훨씬 중요합니다."]),
        section("account-progression", "계정 및 진행: 이전되는 것", ["Aion 1에서 Aion 2로 이전되는 데이터는 없습니다. 완전히 새로운 시작입니다. 다만 Aion 세계에 대한 지식은 직접 이전됩니다.", "서버 선택은 동일한 지역 모델을 따릅니다: NA, EU, JP, SA.", "베테랑은 초반 효율에서 상당한 이점이 있습니다."]),
        section("combat-evolution", "전투 시스템의 진화", ["Aion 1의 탭 타겟 전투는 사라졌습니다. Aion 2는 풀 액션 전투 시스템을 사용합니다.", "스킬 시스템은 스티그마 슬롯 모델을 사용합니다. 활성 스킬은 적지만 로테이션에서 각 스킬이 더 중요합니다.", "Aion 2의 비행은 전투에 통합되어 있습니다."]),
        section("economy-differences", "경제 및 진행 차이", ["Aion 2의 키나 경제는 유사한 모델을 따르지만 브로커리지 시스템이 업데이트되었습니다.", "장비 진행이 더 최적화되었습니다. Aion 1의 복잡한 마법부여 시스템 대신 간소화된 강화 시스템을 사용합니다.", "Daeva Pass 모델은 Aion 1의 프리미엄 시스템과 유사합니다."]),
        section("veteran-tips", "베테랑 팁", ["엔드게임을 서두르지 마세요. Aion 2의 수정된 진행 곡선은 콘텐츠를 측정된 속도로 탐색하도록 설계되었습니다.", "스티그마 프리셋 시스템을 일찍 실험하세요.", "첫날부터 길드에 가입하세요. 엔드게임 콘텐츠는 조율된 그룹이 필요합니다."]),
      ],
    }),
    "zh-hant": articleCopy(guideLabels, "zh-hant", 6, {
      eyebrow: "回歸玩家",
      title: "Aion 1 到 Aion 2 過渡指南：老玩家必備知識",
      description: "Aion 1 老玩家轉向 Aion 2 的完整過渡指南。了解戰鬥、職業、經濟和進階的所有變化。",
      intro: "Aion 2 不是簡單的續作——它是基於虛幻引擎 5 的全面重建，採用全新動作戰鬥系統、精簡的職業陣容和重做的進階模型。",
      sourceNote: "基於 NC 官方遊戲頁面和韓服（截至 2026 年 9 月）。全球版可能有調整。",
      keywords: ["Aion 1 到 Aion 2", "Aion 2 過渡指南", "Aion 2 老玩家", "Aion 2 與 Aion 1", "Aion 2 回歸玩家"],
      sections: [
        section("what-changed", "Aion 1 與 Aion 2 的關鍵差異", ["Aion 2 運行在虛幻引擎 5 上，取代了 Aion 的專有引擎。畫面大幅提升，實時光照和更遠的渲染距離。亞特雷亞世界從零重建，區域無縫過渡。", "職業系統從 Aion 1 的 12+ 職業精簡到上線時 6 個起始職業，每個職業通過烙印和技能預設系統提供更深度自定義。", "戰鬥從鎖定目標轉向動作制。走位、閃避和時機比 Aion 1 重要得多。飛行系統也重做——整合進戰鬥而非獨立模式。"]),
        section("account-progression", "帳號與進階：什麼能繼承", ["Aion 1 到 Aion 2 沒有任何數據繼承。這是全新開始。但你對 Aion 世界的知識直接轉移。", "全球版服務器選擇沿用區域模型：北美、歐洲、日本、南美。韓服和台服獨立。", "老玩家在早期效率上有顯著優勢。你已經知道最優任務路線、副本機制和職業配合。"]),
        section("combat-evolution", "戰鬥系統演變", ["Aion 1 的鎖定目標戰鬥消失了。Aion 2 使用全面動作戰鬥系統。每個技能需要手動瞄準，位置攻擊有額外傷害。", "技能系統使用烙印槽模型。同時激活的技能更少，但每個技能在循環中更重要。", "Aion 2 的飛行整合進戰鬥而非切換模式。飛行中可以使用空中技能，翅膀系統有進階等級。"]),
        section("economy-differences", "經濟與進階差異", ["Aion 2 的 Kinah 經濟沿用類似的玩家驅動市場模型，但交易所系統更新了新的過濾和價格歷史功能。", "裝備進階更精簡。Aion 2 使用簡化的強化系統，有更清晰的升級等級。", "Daeva Pass 模式與 Aion 1 的高級系統類似，提供生活質量和外觀福利。"]),
        section("veteran-tips", "老玩家建議", ["不要急著衝到後期。Aion 2 的改良進階曲線是為讓玩家按節奏探索內容設計的。", "盡早嘗試技能預設系統。不同於 Aion 1 的永久技能解鎖，Aion 2 的預設系統讓你切換不同內容的構建。", "第一天就加入公會。Aion 2 的後期內容需要協調團隊。你的老玩家經驗讓你成為有價值的招募對象。"]),
      ],
    }),
  },
};
