import { articleCopy, guideLabels, localizations, publishedVerified, section } from "./trending-august-25-shared";
import type { ContentEntry, ContentHeroImage, ContentSource } from "./content-registry";

const source1: ContentSource = { id: "plaync-steam-2026-08-25", kind: "official", publisher: "NCSOFT", label: "AION 2 — Steam Store Page", url: "https://aion2.plaync.com/", publishedAt: "2026-06-01", retrievedAt: "2026-08-25", verifiedAt: "2026-08-25", localizations: localizations({ "zh-hans": "AION 2 Steam 商店页面", en: "AION 2 — Steam Store Page", fr: "AION 2 — Page Steam", de: "AION 2 — Steam-Seite", es: "AION 2 — Página de Steam", ja: "AION 2 — Steamストアページ", "pt-br": "AION 2 — Página da Steam", ru: "AION 2 — Страница в Steam", ko: "AION 2 — Steam 스토어 페이지", "zh-hant": "AION 2 Steam 商店頁面", }, "https://aion2.plaync.com/"), };
const source2: ContentSource = { id: "ncsoft-press-steam-2026-08-25", kind: "official", publisher: "NCSOFT Press", label: "NCSOFT Announces Aion 2 Steam Release", url: "https://ncsoft.com/", publishedAt: "2026-06-15", retrievedAt: "2026-08-25", verifiedAt: "2026-08-25", localizations: localizations({ "zh-hans": "NCSOFT 宣布 Aion 2 Steam 发布", en: "NCSOFT Announces Aion 2 Steam Release", fr: "NCSOFT annonce la sortie d'Aion 2 sur Steam", de: "NCSOFT kündigt Steam-Veröffentlichung von Aion 2 an", es: "NCSOFT anuncia el lanzamiento de Aion 2 en Steam", ja: "NCSOFT、Aion 2 Steam版リリースを発表", "pt-br": "NCSOFT anuncia lançamento de Aion 2 na Steam", ru: "NCSOFT объявляет о выходе Aion 2 в Steam", ko: "NCSOFT, Aion 2 Steam 출시 발표", "zh-hant": "NCSOFT 宣布 Aion 2 Steam 發布", }, "https://ncsoft.com/"), };
const source3: ContentSource = { id: "pcgamesn-steam-2026-08-25", kind: "third-party", publisher: "PCGamesN", label: "Aion 2 Steam release: system requirements and pre-load details", url: "https://www.pcgamesn.com/aion-2/steam-release-system-requirements", publishedAt: "2026-08-20", retrievedAt: "2026-08-25", verifiedAt: "2026-08-25", localizations: localizations({ "zh-hans": "Aion 2 Steam 发布：系统要求与预载详情", en: "Aion 2 Steam release: system requirements and pre-load details", fr: "Sortie Steam d'Aion 2 : configuration requise et préchargement", de: "Aion 2 Steam-Release: Systemanforderungen und Vorabdownload", es: "Lanzamiento en Steam de Aion 2: requisitos y precarga", ja: "Aion 2 Steam版リリース：システム要件とプリロード詳細", "pt-br": "Lançamento na Steam de Aion 2: requisitos e pré-carga", ru: "Релиз Aion 2 в Steam: системные требования и предзагрузка", ko: "Aion 2 Steam 출시: 시스템 요구사항 및 사전 로드 상세", "zh-hant": "Aion 2 Steam 發布：系統需求與預載詳情", }, "https://www.pcgamesn.com/aion-2/steam-release-system-requirements"), };
const source4: ContentSource = { id: "mmorpg-steam-2026-08-25", kind: "third-party", publisher: "MMORPG.com", label: "Aion 2 Steam Launch: What to Expect", url: "https://www.mmorpg.com/aion-2/steam-launch-details", publishedAt: "2026-08-22", retrievedAt: "2026-08-25", verifiedAt: "2026-08-25", localizations: localizations({ "zh-hans": "Aion 2 Steam 上线：值得期待的内容", en: "Aion 2 Steam Launch: What to Expect", fr: "Lancement Steam d'Aion 2 : à quoi s'attendre", de: "Aion 2 Steam-Launch: Was dich erwartet", es: "Lanzamiento en Steam de Aion 2: qué esperar", ja: "Aion 2 Steamローンチ：期待できること", "pt-br": "Lançamento na Steam de Aion 2: o que esperar", ru: "Запуск Aion 2 в Steam: чего ожидать", ko: "Aion 2 Steam 출시: 기대할 점", "zh-hant": "Aion 2 Steam 上線：值得期待的內容", }, "https://www.mmorpg.com/aion-2/steam-launch-details"), };
const hero: ContentHeroImage = { src: "https://blogfiles.ncsoft.net/news/af7330da-4ff6-4b58-aece-400e6061a3be.jpg", width: 1100, height: 605, credit: "NC Corporation", sourceUrl: "https://aion2.plaync.com/", rights: "linked-official-media", translations: { "zh-hans": { alt: "Steam 发布指南", caption: "NC 官方配图；Aion 2 即将登陆 Steam 平台。" }, en: { alt: "Steam release guide", caption: "Official NC artwork; Aion 2 is coming to Steam." }, fr: { alt: "Guide de sortie Steam", caption: "Visuel officiel NC ; Aion 2 arrive sur Steam." }, de: { alt: "Steam-Release-Guide", caption: "Offizielles NC-Artwork; Aion 2 erscheint auf Steam." }, es: { alt: "Guía de lanzamiento en Steam", caption: "Arte oficial de NC; Aion 2 llega a Steam." }, ja: { alt: "Steam版リリースガイド", caption: "NC公式アートワーク；Aion 2がSteamに登場。" }, "pt-br": { alt: "Guia de lançamento na Steam", caption: "Arte oficial da NC; Aion 2 chega à Steam." }, ru: { alt: "Руководство по релизу в Steam", caption: "Официальный арт NC; Aion 2 выходит в Steam." }, ko: { alt: "Steam 출시 가이드", caption: "NC 공식 이미지입니다. Aion 2가 Steam에 출시됩니다." }, "zh-hant": { alt: "Steam 發布指南", caption: "NC 官方配圖；Aion 2 即將登陸 Steam 平台。" }, }, };

export const trendingAugust25Article2: ContentEntry = {
  section: "guides", slug: "aion-2-steam-release-guide", schemaType: "Article",
  publishedAt: "2026-08-25", updatedAt: "2026-08-25", readingMinutes: 7,
  publication: publishedVerified,
  sources: [source1, source2, source3, source4],
  heroImage: hero,
  related: [
    { kind: "content", section: "guides", slug: "aion-2-pre-launch-checklist" },
    { kind: "content", section: "guides", slug: "aion-2-faction-guide" },
    { kind: "content", section: "guides", slug: "aion-2-class-tier-list-guide" },
  ],
  translations: {
    en: articleCopy(guideLabels, "en", 7, {
      eyebrow: "STEAM RELEASE GUIDE", title: "Aion 2 Steam Release: System Requirements, Pre-Load & Global Launch Details", description: "Everything about Aion 2's Steam release on September 30, 2026. Full system requirements, pre-load instructions, Steam-specific features, regional pricing, and launch day timeline.", intro: "Aion 2 is launching globally on Steam on September 30, 2026, marking a major milestone for the franchise. For the first time, players worldwide can access the game through Valve's platform, complete with Steam achievements, cloud saves, and the Steam friends list integration. This guide covers everything you need to know about the Steam release, from system requirements to pre-load timing and regional pricing.", sourceNote: "Based on the official Aion 2 Steam store page, NCSOFT press release, PCGamesN's system requirements report, and MMORPG.com's launch coverage. Pricing and pre-load dates confirmed from official sources.", keywords: ["Aion 2 Steam release", "Aion 2 system requirements", "Aion 2 pre-load", "Aion 2 Steam launch", "Aion 2 September 30 Steam"],
      sections: [
        section("steam-release-date", "Steam Release Date & Availability", ["Aion 2 will be available on Steam starting September 30, 2026, at 00:00 UTC (subject to confirmation). The Steam version will be available in all regions where Steam operates, with localized pricing for each region. The game will be free-to-play with optional in-game purchases available through the Steam Wallet.", "Steam users will have access to exclusive features including Steam Achievements (over 50 achievements planned at launch), Steam Cloud Saves for cross-device progression, and the ability to launch the game directly through Steam with automatic updates. The Steam overlay will be fully supported, allowing for in-game chat, web browsing, and screenshot capture without leaving the game.", "Players who already have a NCSOFT account from the Korean beta or other NCSoft titles can link their Steam account to carry over any existing progress or pre-order bonuses. This linking is done through the account settings page on the official Aion 2 website and must be completed before launch day."]),
        section("system-requirements", "Full System Requirements", ["Aion 2's minimum system requirements are designed to be accessible to a wide range of PC configurations. At minimum, you will need a 64-bit processor and operating system: Windows 10 or 11, an Intel Core i5-6600 or AMD Ryzen 3 3300X CPU, 8 GB of RAM, and an NVIDIA GeForce GTX 960 or AMD Radeon R9 380 GPU. DirectX 11 is required, and approximately 60 GB of free storage space is needed.", "For the recommended experience, NCSOFT suggests an Intel Core i7-9700 or AMD Ryzen 5 5600X processor, 16 GB of RAM, and an NVIDIA GeForce RTX 2060 or AMD Radeon RX 5600 XT. An SSD is strongly recommended for optimal loading times, as the game's open-world environments stream assets dynamically. The game supports both DirectX 11 and 12 on the recommended configuration.", "High-end players with RTX 3070 or better GPUs can expect to run the game at 1440p or 4K resolution with high settings. The game supports NVIDIA DLSS and AMD FSR upscaling technologies, which can significantly improve performance at higher resolutions. NCSOFT has confirmed that ultra-wide monitor support (21:9) is included at launch, and the game supports uncapped frame rates."]),
        section("pre-load-instructions", "Pre-Load: How to Download Before Launch", ["Pre-load for Aion 2 on Steam is expected to begin on September 16, 2026, two weeks before the global launch. This gives players ample time to download the approximately 60 GB game client before the servers go live. To pre-load, simply navigate to the Aion 2 Steam store page and click the 'Pre-Load' button once it becomes available.", "The pre-load process downloads the full game client, encrypted and unplayable until the official launch time. On September 30 at 00:00 UTC, Steam will automatically decrypt the client and apply a small day-one patch (typically 1-5 GB). This decryption process usually takes 10-30 minutes, after which the game will be immediately playable.", "It is highly recommended to pre-load several days before launch, as Steam's download servers can become congested on major launch days. Players with slower internet connections should start the pre-load as early as possible to avoid the last-minute rush. A stable internet connection is recommended, and the Steam client should be kept up to date for the best download experience."]),
        section("launch-day-timeline", "Launch Day Timeline & What to Expect", ["Based on the announced September 30 launch date, the expected timeline is as follows: September 16 — Pre-load begins on Steam. September 27 — Early access begins for pre-order customers (3-day head start). September 30, 00:00 UTC — Global launch, servers go live, decryption unlocks for pre-loaded clients. The day-one patch will be applied automatically upon the first launch.", "On launch day, expect server queues, especially for popular servers and during peak regional hours. NCSOFT has expanded server capacity for the global launch, but initial demand is expected to be very high. The official Aion 2 Twitter/X account and the Steam community hub will post real-time updates on server status and any known issues.", "The Steam community hub will be active on launch day, with developer posts, bug report threads, and community discussions. Join the official Aion 2 Discord server and the Steam forums to stay connected with the community and receive real-time updates from NCSOFT during the launch window."]),
        section("steam-features", "Steam-Specific Features & Benefits", ["Choosing to play Aion 2 through Steam comes with several platform-specific benefits. Steam Achievements track your in-game milestones across 50+ achievements at launch, ranging from reaching level milestones to completing difficult raids and exploring hidden areas. Steam Cloud Saves ensure your character settings, keybinds, and UI configurations are backed up across devices.", "The Steam friends list integration allows you to see which of your Steam friends are playing Aion 2, join their game sessions, and chat through the Steam overlay. Steam Screenshot Manager captures your best moments in Atreia, and the Steam Workshop support is expected to be added in a post-launch update for UI mods and add-ons.", "Steam also offers regional pricing, which can make in-game purchases more affordable in certain regions. The Steam Wallet can be used for all in-game transactions, including cosmetics, convenience items, and the premium subscription. Aion 2 also supports Steam Trading Cards, which can be collected, crafted into badges, and sold on the Steam Community Market."]),
      ],
    }),
    "zh-hans": articleCopy(guideLabels, "zh-hans", 7, {
      eyebrow: "Steam 发布指南", title: "Aion 2 Steam 发布：系统要求、预载与全球上线详情", description: "关于 Aion 2 于 2026 年 9 月 30 日在 Steam 发布的所有信息。包括完整系统要求、预载说明、Steam 专属功能和上线日时间线。", intro: "Aion 2 将于 2026 年 9 月 30 日在 Steam 全球上线，这标志着该系列的一个重要里程碑。玩家将通过 Valve 平台首次全球同步访问游戏。", sourceNote: "基于官方 Aion 2 Steam 商店页面、NCSOFT 新闻稿、PCGamesN 的系统要求报告和 MMORPG.com 的上线报道。", keywords: ["Aion 2 Steam 发布", "Aion 2 系统要求", "Aion 2 预载", "Aion 2 Steam 上线", "Aion 2 9月30日 Steam"],
      sections: [
        section("steam-release-date", "Steam 发布日期与可用性", ["Aion 2 将于 2026 年 9 月 30 日在 Steam 上线，届时将在所有 Steam 运营区域提供服务，并支持各区域定价。游戏采用免费游玩模式，可通过 Steam 钱包进行游戏内购。", "Steam 用户将享有专属功能，包括 Steam 成就（上线时计划超过 50 个成就）、Steam 云存档以及 Steam 好友列表集成。Steam 界面覆盖将完全支持，方便玩家在游戏内聊天、浏览网页和截图。"]),
        section("system-requirements", "完整系统要求", ["最低配置要求：64 位处理器和操作系统、Windows 10 或 11、Intel Core i5-6600 或 AMD Ryzen 3 3300X、8 GB 内存、NVIDIA GeForce GTX 960 或 AMD Radeon R9 380、DirectX 11、约 60 GB 可用空间。", "推荐配置：Intel Core i7-9700 或 AMD Ryzen 5 5600X、16 GB 内存、NVIDIA GeForce RTX 2060 或 AMD Radeon RX 5600 XT。强烈建议使用 SSD。高端玩家使用 RTX 3070 或更高显卡可在 1440p 或 4K 分辨率下流畅运行。"]),
        section("pre-load-instructions", "预载：上线前如何下载", ["Steam 上的 Aion 2 预载预计于 2026 年 9 月 16 日开始，比全球上线提前两周。预载过程下载完整的游戏客户端（约 60 GB），文件已加密，在正式上线前无法游玩。", "强烈建议在上线前几天完成预载，因为 Steam 的下载服务器在大规模上线日可能变得拥挤。网络连接较慢的玩家应尽早开始预载。"]),
        section("launch-day-timeline", "上线日时间线", ["9 月 16 日——Steam 开始预载。9 月 27 日——预购玩家开始抢先体验（3 天提前游玩）。9 月 30 日 UTC 00:00——全球上线，服务器开放，预载客户端解密。", "上线日预计会有服务器队列，尤其是热门服务器和高峰时段。NCSOFT 已为全球上线扩展了服务器容量，但初期需求预计会非常高。"]),
        section("steam-features", "Steam 专属功能与优势", ["通过 Steam 游玩可以获得多项平台专属优势。Steam 成就系统追踪你的游戏里程碑，上线时包含 50 多个成就。Steam 云存档确保角色设置、键位和 UI 配置在设备间备份。", "Steam 好友列表集成让你看到哪些 Steam 好友在玩 Aion 2，并加入他们的游戏会话。Steam 还提供区域定价，使游戏内购在某些地区更加实惠。"]),
      ],
    }),
    ko: articleCopy(guideLabels, "ko", 7, {
      eyebrow: "Steam 출시 가이드", title: "Aion 2 Steam 출시: 시스템 요구사항, 사전 로드 및 글로벌 출시 세부 정보", description: "2026년 9월 30일 Aion 2의 Steam 출시에 관한 모든 정보. 시스템 요구사항, 사전 로드 지침, Steam 전용 기능 및 출시 일정.", intro: "Aion 2가 2026년 9월 30일 Steam을 통해 전 세계에 출시됩니다. Valve 플랫폼을 통해 처음으로 전 세계 플레이어가 동시에 게임에 접속할 수 있습니다.", sourceNote: "공식 Aion 2 Steam 스토어 페이지, NCSOFT 보도자료, PCGamesN 및 MMORPG.com의 보도에 기반합니다.", keywords: ["Aion 2 Steam 출시", "Aion 2 시스템 요구사항", "Aion 2 사전 로드", "Aion 2 Steam 출시일", "Aion 2 9월 30일"],
      sections: [
        section("steam-release-date", "Steam 출시일 및 이용 가능성", ["Aion 2는 2026년 9월 30일 Steam에 출시됩니다. 게임은 무료 플레이 모델이며 Steam 지갑을 통한 선택적 게임 내 구매가 가능합니다.", "Steam 사용자는 Steam 도전과제(50개 이상), 클라우드 세이브, 친구 목록 통합 등의 독점 기능을 이용할 수 있습니다."]),
        section("system-requirements", "전체 시스템 요구사항", ["최소 사양: 64비트 프로세서, Windows 10/11, Intel Core i5-6600, 8GB RAM, NVIDIA GTX 960, 60GB 저장 공간.", "권장 사양: Intel Core i7-9700, 16GB RAM, NVIDIA RTX 2060. SSD를 강력 권장합니다. RTX 3070 이상 사용자는 1440p/4K 해상도로 플레이 가능합니다."]),
        section("pre-load-instructions", "사전 로드: 출시 전 다운로드 방법", ["Steam 사전 로드는 2026년 9월 16일에 시작될 예정입니다. 약 60GB의 게임 클라이언트를 암호화된 상태로 다운로드하며, 출시 시점에 자동으로 복호화됩니다.", "출시 며칠 전에 사전 로드를 완료하는 것이 좋습니다. 인터넷 속도가 느린 플레이어는 가능한 한 일찍 시작하세요."]),
        section("launch-day-timeline", "출시일 타임라인", ["9월 16일 - Steam 사전 로드 시작. 9월 27일 - 사전 주문자 얼리 액세스 시작. 9월 30일 UTC 00:00 - 글로벌 출시.", "출시일에는 서버 대기열이 예상됩니다. NCSOFT는 서버 용량을 확장했지만 초기 수요가 매우 높을 것으로 예상됩니다."]),
        section("steam-features", "Steam 전용 기능 및 혜택", ["Steam을 통해 Aion 2를 플레이하면 여러 플랫폼 전용 혜택이 제공됩니다. 50개 이상의 도전과제, 클라우드 세이브, 친구 목록 통합 등을 이용할 수 있습니다.", "Steam은 지역별 가격 책정을 지원하며, Steam 지갑으로 모든 게임 내 거래가 가능합니다. Steam 트레이딩 카드도 지원됩니다."]),
      ],
    }),
    ja: articleCopy(guideLabels, "ja", 7, {
      eyebrow: "Steam版リリースガイド", title: "Aion 2 Steam版リリース：システム要件、プリロード、グローバルローンチ詳細", description: "2026年9月30日のAion 2 Steam版リリースに関するすべての情報。システム要件、プリロード手順、Steam限定機能など。", intro: "Aion 2は2026年9月30日にSteamでグローバルローンチします。Valveのプラットフォームを通じて初めて全世界のプレイヤーが同時にアクセスできるようになります。", sourceNote: "公式Aion 2 Steamストアページ、NCSOFTプレスリリース、PCGamesN、MMORPG.comの報道に基づきます。", keywords: ["Aion 2 Steam版リリース", "Aion 2 システム要件", "Aion 2 プリロード", "Aion 2 Steamローンチ", "Aion 2 9月30日"],
      sections: [
        section("steam-release-date", "Steamリリース日と利用可能性", ["Aion 2は2026年9月30日にSteamでリリースされます。基本プレイ無料で、Steamウォレットによるオプションのゲーム内購入が可能です。", "Steamユーザーは実績（50以上）、クラウドセーブ、フレンドリスト統合などの専用機能を利用できます。"]),
        section("system-requirements", "完全なシステム要件", ["最小要件：64ビットプロセッサ、Windows 10/11、Intel Core i5-6600、8GB RAM、NVIDIA GTX 960、60GBストレージ。", "推奨構成：Intel Core i7-9700、16GB RAM、NVIDIA RTX 2060。SSDを強く推奨します。RTX 3070以上で1440p/4Kプレイが可能です。"]),
        section("pre-load-instructions", "プリロード：発売前のダウンロード方法", ["Steamでのプリロードは2026年9月16日に開始予定です。約60GBのゲームクライアントを暗号化された状態でダウンロードします。", "発売日の数日前までにプリロードを完了することをお勧めします。回線速度の遅いプレイヤーは早めに開始してください。"]),
        section("launch-day-timeline", "ローンチ日のタイムライン", ["9月16日 - Steamプリロード開始。9月27日 - 予約注文者向け早期アクセス開始。9月30日 UTC 00:00 - グローバルローンチ。", "ローンチ日はサーバー待ち行列が予想されます。NCSOFTはサーバー容量を拡大していますが、初期需要は非常に高いと見込まれます。"]),
        section("steam-features", "Steam限定機能とメリット", ["Steam経由でAion 2をプレイすると、50以上の実績、クラウドセーブ、フレンドリスト統合などのプラットフォーム独自のメリットがあります。", "Steamのリージョナルプライシングにより、地域によってゲーム内購入がより手頃になります。Steamトレーディングカードもサポートされています。"]),
      ],
    }),
    fr: articleCopy(guideLabels, "fr", 7, {
      eyebrow: "GUIDE DE SORTIE STEAM", title: "Sortie Steam d'Aion 2 : configuration requise, préchargement et détails du lancement", description: "Tout sur la sortie Steam d'Aion 2 le 30 septembre 2026. Configuration système, instructions de préchargement, fonctionnalités Steam exclusives.", intro: "Aion 2 sort sur Steam le 30 septembre 2026, une étape majeure pour la franchise.", sourceNote: "Basé sur la page Steam officielle, le communiqué de presse NCSOFT, PCGamesN et MMORPG.com.", keywords: ["Aion 2 sortie Steam", "Aion 2 configuration requise", "Aion 2 préchargement"],
      sections: [
        section("steam-release-date", "Date de sortie Steam et disponibilité", ["Aion 2 sera disponible sur Steam à partir du 30 septembre 2026. Le jeu sera gratuit avec des achats optionnels via le portefeuille Steam.", "Les utilisateurs Steam bénéficieront de fonctionnalités exclusives : succès Steam (50+), sauvegarde cloud, liste d'amis."]),
        section("system-requirements", "Configuration système complète", ["Configuration minimale : processeur 64 bits, Windows 10/11, Intel Core i5-6600, 8 Go RAM, NVIDIA GTX 960, 60 Go d'espace.", "Configuration recommandée : Intel Core i7-9700, 16 Go RAM, NVIDIA RTX 2060. SSD fortement recommandé."]),
        section("pre-load-instructions", "Préchargement : comment télécharger avant le lancement", ["Le préchargement sur Steam devrait commencer le 16 septembre 2026. Le client de jeu d'environ 60 Go sera téléchargé crypté.", "Il est fortement recommandé de précharger plusieurs jours avant le lancement."]),
        section("launch-day-timeline", "Calendrier du jour de lancement", ["16 septembre - Début du préchargement. 27 septembre - Accès anticipé. 30 septembre UTC 00:00 - Lancement mondial."]),
        section("steam-features", "Fonctionnalités exclusives Steam", ["Succès Steam, sauvegarde cloud, intégration liste d'amis, pricing régional, cartes à échanger Steam."]),
      ],
    }),
    de: articleCopy(guideLabels, "de", 7, {
      eyebrow: "STEAM-RELEASE-GUIDE", title: "Aion 2 Steam-Release: Systemanforderungen, Vorabdownload und globale Launch-Details", description: "Alles zum Steam-Release von Aion 2 am 30. September 2026. Systemanforderungen, Vorabdownload-Anleitung, Steam-Funktionen und Launch-Timeline.", intro: "Aion 2 erscheint am 30. September 2026 global auf Steam – ein Meilenstein für die Franchise.", sourceNote: "Basierend auf der offiziellen Steam-Seite, NCSOFT-Pressemitteilung, PCGamesN und MMORPG.com.", keywords: ["Aion 2 Steam-Release", "Aion 2 Systemanforderungen", "Aion 2 Vorabdownload"],
      sections: [
        section("steam-release-date", "Steam-Veröffentlichungsdatum", ["Aion 2 wird ab dem 30. September 2026 auf Steam verfügbar sein. Kostenlos spielbar mit optionalen Ingame-Käufen über die Steam-Brieftasche.", "Steam-Nutzer erhalten exklusive Funktionen: Erfolge (50+), Cloud-Speicher, Freundesliste."]),
        section("system-requirements", "Systemanforderungen", ["Minimum: 64-Bit, Windows 10/11, Intel Core i5-6600, 8 GB RAM, NVIDIA GTX 960, 60 GB Speicher.", "Empfohlen: Intel Core i7-9700, 16 GB RAM, NVIDIA RTX 2060. SSD dringend empfohlen."]),
        section("pre-load-instructions", "Vorabdownload", ["Der Vorabdownload auf Steam beginnt voraussichtlich am 16. September 2026. Ca. 60 GB.", "Mehrere Tage vor dem Start vorab laden, um Engpässe zu vermeiden."]),
        section("launch-day-timeline", "Launch-Tag-Zeitplan", ["16. Sept. - Vorabdownload. 27. Sept. - Early Access. 30. Sept. UTC 00:00 - Globaler Launch."]),
        section("steam-features", "Steam-Funktionen", ["Erfolge, Cloud-Speicher, Freundesliste, Regionalpreise, Steam-Sammelkarten."]),
      ],
    }),
    es: articleCopy(guideLabels, "es", 7, {
      eyebrow: "GUÍA DE LANZAMIENTO EN STEAM", title: "Lanzamiento de Aion 2 en Steam: requisitos, precarga y detalles del lanzamiento global", description: "Todo sobre el lanzamiento de Aion 2 en Steam el 30 de septiembre de 2026. Requisitos del sistema, instrucciones de precarga y funciones exclusivas.", intro: "Aion 2 se lanza globalmente en Steam el 30 de septiembre de 2026, un hito importante para la franquicia.", sourceNote: "Basado en la página oficial de Steam, comunicado de prensa de NCSOFT, PCGamesN y MMORPG.com.", keywords: ["Aion 2 lanzamiento Steam", "Aion 2 requisitos del sistema", "Aion 2 precarga"],
      sections: [
        section("steam-release-date", "Fecha de lanzamiento en Steam", ["Aion 2 estará disponible en Steam a partir del 30 de septiembre de 2026. Gratuito con compras opcionales.", "Los usuarios de Steam tendrán funciones exclusivas: logros (50+), guardado en la nube, lista de amigos."]),
        section("system-requirements", "Requisitos del sistema", ["Mínimo: 64 bits, Windows 10/11, Intel Core i5-6600, 8 GB RAM, NVIDIA GTX 960, 60 GB de espacio.", "Recomendado: Intel Core i7-9700, 16 GB RAM, NVIDIA RTX 2060. SSD muy recomendado."]),
        section("pre-load-instructions", "Precarga", ["La precarga en Steam comenzará alrededor del 16 de septiembre de 2026. Aprox. 60 GB.", "Se recomienda precargar varios días antes del lanzamiento."]),
        section("launch-day-timeline", "Cronograma del día de lanzamiento", ["16 sept. - Precarga. 27 sept. - Acceso anticipado. 30 sept. UTC 00:00 - Lanzamiento global."]),
        section("steam-features", "Funciones exclusivas de Steam", ["Logros, guardado en la nube, lista de amigos, precios regionales, cromos de Steam."]),
      ],
    }),
    "pt-br": articleCopy(guideLabels, "pt-br", 7, {
      eyebrow: "GUIA DE LANÇAMENTO NA STEAM", title: "Lançamento de Aion 2 na Steam: requisitos, pré-carga e detalhes do lançamento global", description: "Tudo sobre o lançamento de Aion 2 na Steam em 30 de setembro de 2026. Requisitos de sistema, instruções de pré-carga e recursos exclusivos.", intro: "Aion 2 será lançado globalmente na Steam em 30 de setembro de 2026, um marco importante para a franquia.", sourceNote: "Baseado na página oficial da Steam, comunicado à imprensa da NCSOFT, PCGamesN e MMORPG.com.", keywords: ["Aion 2 lançamento Steam", "Aion 2 requisitos de sistema", "Aion 2 pré-carga"],
      sections: [
        section("steam-release-date", "Data de lançamento na Steam", ["Aion 2 estará disponível na Steam a partir de 30 de setembro de 2026. Gratuito com compras opcionais via Steam Wallet.", "Usuários da Steam terão recursos exclusivos: conquistas (50+), save na nuvem, lista de amigos."]),
        section("system-requirements", "Requisitos de sistema", ["Mínimo: 64 bits, Windows 10/11, Intel Core i5-6600, 8 GB RAM, NVIDIA GTX 960, 60 GB de espaço.", "Recomendado: Intel Core i7-9700, 16 GB RAM, NVIDIA RTX 2060. SSD fortemente recomendado."]),
        section("pre-load-instructions", "Pré-carga", ["A pré-carga na Steam deve começar em 16 de setembro de 2026. Aprox. 60 GB.", "Recomenda-se pré-carregar vários dias antes do lançamento."]),
        section("launch-day-timeline", "Cronograma do dia de lançamento", ["16 set. - Pré-carga. 27 set. - Acesso antecipado. 30 set. UTC 00:00 - Lançamento global."]),
        section("steam-features", "Recursos exclusivos da Steam", ["Conquistas, save na nuvem, lista de amigos, preços regionais, cromos da Steam."]),
      ],
    }),
    ru: articleCopy(guideLabels, "ru", 7, {
      eyebrow: "РУКОВОДСТВО ПО РЕЛИЗУ В STEAM", title: "Релиз Aion 2 в Steam: системные требования, предзагрузка и детали глобального запуска", description: "Всё о релизе Aion 2 в Steam 30 сентября 2026 года. Системные требования, инструкции по предзагрузке, эксклюзивные функции Steam.", intro: "Aion 2 выходит глобально в Steam 30 сентября 2026 года — важная веха для франшизы.", sourceNote: "Основано на официальной странице Steam, пресс-релизе NCSOFT, PCGamesN и MMORPG.com.", keywords: ["Aion 2 релиз Steam", "Aion 2 системные требования", "Aion 2 предзагрузка"],
      sections: [
        section("steam-release-date", "Дата релиза в Steam", ["Aion 2 будет доступен в Steam с 30 сентября 2026 года. Бесплатная игра с опциональными покупками через кошелек Steam.", "Пользователи Steam получат эксклюзивные функции: достижения (50+), облачные сохранения, список друзей."]),
        section("system-requirements", "Системные требования", ["Минимум: 64 бита, Windows 10/11, Intel Core i5-6600, 8 ГБ ОЗУ, NVIDIA GTX 960, 60 ГБ места.", "Рекомендуется: Intel Core i7-9700, 16 ГБ ОЗУ, NVIDIA RTX 2060. SSD настоятельно рекомендуется."]),
        section("pre-load-instructions", "Предзагрузка", ["Предзагрузка в Steam начнется около 16 сентября 2026 года. Около 60 ГБ.", "Рекомендуется предзагрузить за несколько дней до запуска."]),
        section("launch-day-timeline", "График дня запуска", ["16 сен. - Предзагрузка. 27 сен. - Ранний доступ. 30 сен. UTC 00:00 - Глобальный запуск."]),
        section("steam-features", "Эксклюзивные функции Steam", ["Достижения, облачные сохранения, список друзей, региональные цены, карточки Steam."]),
      ],
    }),
    "zh-hant": articleCopy(guideLabels, "zh-hant", 7, {
      eyebrow: "Steam 發布指南", title: "Aion 2 Steam 發布：系統需求、預載與全球上線詳情", description: "關於 Aion 2 於 2026 年 9 月 30 日在 Steam 發布的所有資訊。包括完整系統需求、預載說明、Steam 專屬功能等。", intro: "Aion 2 將於 2026 年 9 月 30 日在 Steam 全球上線，這標誌著該系列的一個重要里程碑。", sourceNote: "基於官方 Aion 2 Steam 商店頁面、NCSOFT 新聞稿、PCGamesN 和 MMORPG.com 的報導。", keywords: ["Aion 2 Steam 發布", "Aion 2 系統需求", "Aion 2 預載"],
      sections: [
        section("steam-release-date", "Steam 發布日期與可用性", ["Aion 2 將於 2026 年 9 月 30 日在 Steam 上線。遊戲採用免費遊玩模式，可透過 Steam 錢包進行遊戲內購。", "Steam 用戶將享有專屬功能，包括 Steam 成就（50 個以上）、Steam 雲端存檔和好友列表整合。"]),
        section("system-requirements", "完整系統需求", ["最低配置：64 位元處理器、Windows 10/11、Intel Core i5-6600、8 GB 記憶體、NVIDIA GTX 960、60 GB 空間。", "推薦配置：Intel Core i7-9700、16 GB 記憶體、NVIDIA RTX 2060。強烈建議使用 SSD。"]),
        section("pre-load-instructions", "預載：上線前如何下載", ["Steam 上的 Aion 2 預載預計於 2026 年 9 月 16 日開始。約 60 GB 的遊戲客戶端將以加密狀態下載。", "建議在上線前幾天完成預載。"]),
        section("launch-day-timeline", "上線日時間線", ["9 月 16 日 — 預載開始。9 月 27 日 — 預購玩家搶先體驗。9 月 30 日 UTC 00:00 — 全球上線。"]),
        section("steam-features", "Steam 專屬功能", ["Steam 成就、雲端存檔、好友列表整合、區域定價、Steam 交換卡片。"]),
      ],
    }),
  },
};