import { articleCopy, guideLabels, localizations, publishedVerified, section } from "./trending-august-30-shared";
import type { ContentEntry, ContentHeroImage, ContentSource } from "./content-registry";

/* ARTICLE 2 — Underwater exploration: a new layer of the seamless world */

const uwSource1: ContentSource = {
  id: "inthegame-gamescom-preview-2026-08-30-b",
  kind: "third-party", publisher: "intheGame",
  label: "Preview | AION 2 op Gamescom 2026 (underwater & world traversal details)",
  url: "https://inthegame.nl/2026/08/29/preview-aion-2-op-gamescom-2026/",
  publishedAt: "2026-08-29",
  retrievedAt: "2026-08-29",
  verifiedAt: "2026-08-29",
  localizations: localizations({
    "zh-hans": "前瞻 | Gamescom 2026 的 Aion 2（水下与世界移动细节）",
    en: "Preview | AION 2 op Gamescom 2026 (underwater & world traversal details)",
    fr: "Aperçu | AION 2 au Gamescom 2026 (détails sous-marins et déplacement)",
    de: "Vorschau | AION 2 auf der Gamescom 2026 (Unterwasser- und Fortbewegungsdetails)",
    es: "Impresión | AION 2 en Gamescom 2026 (detalles submarinos y de movimiento)",
    ja: "プレビュー | Gamescom 2026 の Aion 2（水中と移動の詳細）",
    "pt-br": "Impressão | AION 2 na Gamescom 2026 (detalhes subaquáticos e de movimentação)",
    ru: "Превью | Aion 2 на Gamescom 2026 (подводные и навигационные детали)",
    ko: "프리뷰 | Gamescom 2026의 Aion 2 (수중·이동 세부)",
    "zh-hant": "前瞻 | Gamescom 2026 的 Aion 2（水下與世界移動細節）",
  }, "https://inthegame.nl/2026/08/29/preview-aion-2-op-gamescom-2026/"),
};

const uwSource2: ContentSource = {
  id: "nc-jp-official-live-2026-08-30-b",
  kind: "official", publisher: "NC",
  label: "AION 2 Official Site (Japan) — World & Expeditions Overview",
  url: "https://aion2.ncsoft.jp/ja/contents",
  publishedAt: "2026-08-28",
  retrievedAt: "2026-08-29",
  verifiedAt: "2026-08-29",
  localizations: localizations({
    "zh-hans": "AION 2 官方网站（日本）——世界与远征概览",
    en: "AION 2 Official Site (Japan) — World & Expeditions Overview",
    fr: "Site officiel AION 2 (Japon) — aperçu du monde et des expéditions",
    de: "AION 2 Offizielle Website (Japan) — Welt- & Expeditions-Überblick",
    es: "Sitio oficial de AION 2 (Japón) — visión del mundo y expediciones",
    ja: "AION 2 公式サイト（日本）— 世界と遠征の概要",
    "pt-br": "Site oficial do AION 2 (Japão) — visão geral do mundo e expedições",
    ru: "Официальный сайт AION 2 (Япония) — обзор мира и экспедиций",
    ko: "Aion 2 공식 사이트 (일본) — 세계·원정 개요",
    "zh-hant": "AION 2 官方網站（日本）——世界與遠征概覽",
  }, "https://aion2.ncsoft.jp/ja/contents"),
};

const uwHero: ContentHeroImage = {
  src: "https://blogfiles.ncsoft.net/news/af7330da-4ff6-4b58-aece-400e6061a3be.jpg",
  width: 1100, height: 605,
  credit: "NC Corporation",
  sourceUrl: "https://aion2.plaync.com/ja-jp/board/notice/list",
  rights: "linked-official-media",
  translations: {
    "zh-hans": { alt: "Aion 2 水下探索指南配图", caption: "NC 官方配图；Gamescom 2026 前瞻确认 Aion 2 的无缝世界在海面之下继续延伸，玩家可潜水探索水下区域。" },
    en: { alt: "Aion 2 underwater exploration guide image", caption: "Official NC artwork; the Gamescom 2026 preview confirmed Aion 2's seamless world continues below the water surface, letting players dive and explore." },
    fr: { alt: "Image du guide d'exploration sous-marine d'Aion 2", caption: "Visuel officiel NC ; l'aperçu Gamescom 2026 confirme que le monde seamless d'Aion 2 continue sous la surface, avec exploration en plongée." },
    de: { alt: "Bild zum Aion-2-Unterwasser-Erkundungsguide", caption: "Offizielles NC-Artwork; die Gamescom-2026-Vorschau bestätigt, dass Aion 2s Seamless-World unter der Wasseroberfläche weitergeht." },
    es: { alt: "Imagen de la guía de exploración submarina de Aion 2", caption: "Arte oficial de NC; el avance de Gamescom 2026 confirma que el mundo seamless de Aion 2 continúa bajo la superficie." },
    ja: { alt: "Aion 2 水中探索ガイド画像", caption: "NC公式アートワーク；Gamescom 2026 プレビューは Aion 2 のシームレスな世界が水面下にも続き、潜水して探索できることを確認しました。" },
    "pt-br": { alt: "Imagem do guia de exploração subaquática do Aion 2", caption: "Arte oficial da NC; a impressão da Gamescom 2026 confirma que o mundo seamless do Aion 2 continua abaixo da superfície." },
    ru: { alt: "Изображение гайда по подводному исследованию Aion 2", caption: "Официальный арт NC; превью Gamescom 2026 подтверждает, что бесшовный мир Aion 2 продолжается под водой." },
    ko: { alt: "Aion 2 수중 탐험 가이드 이미지", caption: "NC 공식 이미지입니다. Gamescom 2026 프리뷰는 Aion 2의 무니팅 세계가 수면 아래로 이어져 잠수 탐험이 가능함을 확인했습니다." },
    "zh-hant": { alt: "Aion 2 水下探索指南配圖", caption: "NC 官方配圖；Gamescom 2026 前瞻確認 Aion 2 的無縫世界在海面之下繼續延伸，玩家可潛水探索水下區域。" },
  },
};

export const trendingAugust30Article2: ContentEntry = {
  section: "guides",
  slug: "aion-2-underwater-exploration-guide",
  schemaType: "Article",
  publishedAt: "2026-08-29",
  updatedAt: "2026-08-29",
  readingMinutes: 4,
  publication: publishedVerified,
  sources: [uwSource1, uwSource2],
  heroImage: uwHero,
  related: [
    { kind: "content", section: "guides", slug: "aion-2-flight-system-guide" },
    { kind: "content", section: "guides", slug: "aion-2-unreal-engine-5-world-scale" },
    { kind: "content", section: "guides", slug: "aion-2-gathering-resource-guide" },
    { kind: "content", section: "guides", slug: "aion-2-endgame-path-guide" },
  ],
  translations: {
    en: articleCopy(guideLabels, "en", 4, {
      eyebrow: "WORLD & EXPLORATION",
      title: "Aion 2 Underwater Exploration: Diving Below the Seamless World",
      description: "The Gamescom 2026 preview confirmed the Aion 2 world extends beneath the water surface. Here is what underwater exploration means for traversal, gathering and the curiosity-driven design philosophy.",
      intro: "Aion 2's world does not stop at the shoreline. In its Gamescom 2026 preview, intheGame confirmed that the seamless open world continues below the water surface — players can dive and explore underwater areas as a natural layer of the same world. For a game whose selling point is a world roughly 36 times larger than the original, underwater exploration is a meaningful expansion of what 'big' means. This guide collects what we know and how it shapes exploration.",
      sourceNote: "Based on intheGame's Gamescom 2026 hands-off preview and developer Q&A (August 29, 2026), with world context from the Aion 2 Japan official site.",
      keywords: ["Aion 2 underwater", "Aion 2 diving", "Aion 2 exploration", "Aion 2 open world", "Aion 2 swimming"],
      sections: [
        section("confirmed", "What the Preview Confirmed", ["The write-up describes the world continuing beneath the water surface: players can dive and explore underwater areas, rather than water being a hard boundary.", "Exploration is framed as curiosity-driven — 'what's over there?' — with underwater areas one of the pull factors alongside flight and a seamless landscape with minimal loading screens.", "It remains part of the same seamless open world, roughly 36 times larger than Aion 1's, so expect underwater zones to be continuous with land rather than instanced."]),
        section("traversal", "Underwater as a Traversal Layer", ["Flight gives you freedom in the air; diving gives you freedom under the sea. Together they make the world feel vertical rather than flat, a key part of how Aion 2 sells its scale.", "Because the world is seamless, expect transitions between land, air and water to be part of normal movement rather than loading gates — consistent with the 'as few loading screens as possible' promise.", "The preview's mount detail (characters hanging from a bird's legs or riding a golem's shoulder) hints that mounts may also behave differently across environments."]),
        section("exploration", "Curiosity-Driven Exploration", ["The developers positioned exploration as a reaction to curiosity rather than a quest-marker chase. Underwater areas fit this: you dive because you want to see what is below, not because a marker demands it.", "Pair this with the anti-daily design: content is meant to feel worthwhile, so underwater secrets and rewards are expected to be tied to discovery, not checklist completion.", "The gathering and resource systems already documented on this site are the likely gameplay anchor for these zones — expect underwater gathering nodes."]),
        section("launch-scope", "What to Expect at Launch", ["The global October 5 build should include these underwater areas as part of the opening world; the launch scale test on September 17–18 (level cap 37) is the first chance to see how far the seams hold.", "Until NC details underwater mechanics, treat depth, breath mechanics and underwater combat as unknown — the preview did not specify systems, only that diving is possible.", "This guide will be updated as official details or the LST itself reveal more."]),
      ],
    }),
    "zh-hans": articleCopy(guideLabels, "zh-hans", 4, {
      eyebrow: "世界与探索",
      title: "Aion 2 水下探索：潜入无缝世界的海面之下",
      description: "Gamescom 2026 前瞻确认 Aion 2 世界在海面之下继续延伸。以下说明水下探索对移动、采集与好奇心驱动设计理念的意义。",
      intro: "Aion 2 的世界不止于海岸线。Gamescom 2026 前瞻确认，无缝开放世界在海面之下继续延伸——玩家可潜水探索水下区域，作为同一世界的自然层次。对一款卖点是世界面积约为初代 36 倍的游戏而言，水下探索是对『大』的实质扩展。本指南汇总已知信息与探索方式的含义。",
      sourceNote: "基于 intheGame 的 Gamescom 2026 闭门前瞻与开发者问答（2026-08-29），世界背景以 Aion 2 日本官网为准。",
      keywords: ["Aion 2 水下", "Aion 2 潜水", "Aion 2 探索", "Aion 2 开放世界", "Aion 2 游泳"],
      sections: [
        section("confirmed", "前瞻确认的内容", ["报道描述世界在海面之下继续延伸：玩家可潜水探索水下区域，水不是硬边界。", "探索被定位为好奇心驱动（『那边有什么？』），水下区域与飞行、最少加载屏的无缝地貌同为主要牵引。", "它仍是同一无缝开放世界（约初代 36 倍）的一部分——水下区域应与陆地连续而非独立副本。"]),
        section("traversal", "作为移动层的水下", ["飞行给予天空自由，潜水给予海下自由；两者让世界显得垂直而非扁平，是 Aion 2 体现场景规模的关键。", "由于世界无缝，陆地/空中/水面的转换应是常规移动而非加载门——与『加载屏尽可能少』的承诺一致。", "前瞻中的坐骑细节（挂在鸟腿、骑魔像肩）暗示坐骑在不同环境也可能有不同表现。"]),
        section("exploration", "好奇心驱动探索", ["开发者将探索定位为对好奇心的回应，而非追逐任务标记。水下区域正契合：你潜水是想看看下面有什么，而非标记要求。", "结合反日常设计：内容应让人感到值得，水下秘密与奖励应关联发现而非清单完成。", "站内已文档化的采集与资源系统大概率是这些区域的核心玩法锚点——期待水下采集点。"]),
        section("launch-scope", "上线范围预期", ["全球 10 月 5 日版本应包含这些水下区域作为开篇世界的一部分；9 月 17-18 日上线规模测试（37 级上限）是首次验证无缝边界的窗口。", "在 NC 详述水下机制前，深度、呼吸机制与水下战斗视为未知——前瞻只确认潜水可行，未给系统。", "官方细节或 LST 本身透露更多后，本指南将更新。"]),
      ],
    }),
    ko: articleCopy(guideLabels, "ko", 4, {
      eyebrow: "세계와 탐험",
      title: "Aion 2 수중 탐험: 무니팅 세계의 수면 아래로",
      description: "Gamescom 2026 프리뷰가 Aion 2 세계가 수면 아래로 이어진다는 점을 확인했습니다. 수중 탐험이 이동·채집·호기심 중심 설계에 어떤 의미인지 정리합니다.",
      intro: "Aion 2의 세계는 해안선에서 끝나지 않습니다. Gamescom 2026 프리뷰에서 무니팅 오픈월드가 수면 아래로 이어지며 잠수 탐험이 가능하다는 점이 확인됐습니다.",
      sourceNote: "intheGame의 Gamescom 2026 핸즈오프 프리뷰·개발자 Q&A(2026-08-29)와 Aion 2 일본 공식 사이트의 세계 배경 기반.",
      keywords: ["Aion 2 수중", "Aion 2 잠수", "Aion 2 탐험", "Aion 2 오픈월드", "Aion 2 수영"],
      sections: [
        section("confirmed", "프리뷰가 확인한 것", "수면 아래로 세계가 이어지며 잠수 탐험이 가능합니다. 탐험은 '저쪽에 뭐가 있지?'라는 호기심 중심이며, 무니팅 세계(원작 36배)의 일부로 인스턴스가 아닌 연속적입니다."),
        section("traversal", "이동 레이어로서의 수중", "하늘의 자유(비행)와 바다의 자유(잠수)가 세계를 수직으로 느끼게 합니다. 무니팅 설계상 육지·공중·수중 전환은 로딩 없이 자연스럽게 이뤄질 것으로 보입니다."),
        section("exploration", "호기심 중심 탐험", "탐험은 퀘스트 마커가 아닌 호기심에 대한 반응입니다. 반-데일리 설계와 맞물려 수중 비밀과 보상은 체크리스트가 아닌 발견과 연결될 전망입니다. 수중 채집 노드도 기대됩니다."),
        section("launch-scope", "출시 범위 전망", "10월 5일 글로벌 빌드에 수중 지역이 포함될 것으로 보이며, 9월 17~18일 LST(레벨 상한 37)가 첫 검증 창구입니다. 수심·호흡·수중 전투 메커니즘은 미공개 상태입니다."),
      ],
    }),
    ja: articleCopy(guideLabels, "ja", 4, {
      eyebrow: "世界と探索",
      title: "Aion 2 水中探索：シームレスな世界の水面下へ",
      description: "Gamescom 2026 プレビューが Aion 2 の世界が水面下へ続くことを確認しました。水中探索が移動・採取・好奇心重視設計にどう関わるかをまとめます。",
      intro: "Aion 2 の世界は海岸線で終わりません。Gamescom 2026 プレビューで、シームレスなオープンワールドが水面下へ続き、潜水探索が可能であることが確認されました。",
      sourceNote: "intheGame の Gamescom 2026 ハンズオフプレビュー・開発者Q&A（2026-08-29）と、Aion 2 日本公式サイトの世界観に基づきます。",
      keywords: ["Aion 2 水中", "Aion 2 潜水", "Aion 2 探索", "Aion 2 オープンワールド", "Aion 2 水泳"],
      sections: [
        section("confirmed", "プレビューが確認したこと", "水面下へ世界が続き、潜水探索が可能。探索は「あっちに何がある？」という好奇心中心で、シームレスな世界（初代の36倍）の一部としてインスタンスではない連続です。"),
        section("traversal", "移動レイヤーとしての水中", "空の自由（飛行）と海の自由（潜水）が世界を垂直に感じさせます。シームレス設計上、陸・空・水の移行はローディングなしで自然に行われる見込みです。"),
        section("exploration", "好奇心重視の探索", "探索はクエストマーカーではなく好奇心への反応。反デイリー設計と合わせ、水中の秘密や報酬はチェックリストではなく発見と結びつく見通しです。水中採取ノードも期待されます。"),
        section("launch-scope", "発売時の見通し", "10月5日のグローバルビルドに水中地域が含まれる見込みで、9月17〜18日のLST（レベル上限37）が最初の検証窓口です。水深・呼吸・水中戦闘の仕様は未公開です。"),
      ],
    }),
    fr: articleCopy(guideLabels, "fr", 4, {
      eyebrow: "MONDE & EXPLORATION",
      title: "Exploration sous-marine d'Aion 2 : plonger sous le monde seamless",
      description: "L'aperçu Gamescom 2026 a confirmé que le monde d'Aion 2 s'étend sous la surface. Ce que cela signifie pour les déplacements, la récolte et la conception orientée curiosité.",
      intro: "Le monde d'Aion 2 ne s'arrête pas au rivage : l'aperçu Gamescom 2026 a confirmé que le monde seamless continue sous l'eau, avec plongée et exploration. Pour un monde ~36x plus grand que l'original, c'est un vrai élargissement du « grand ».",
      sourceNote: "Basé sur l'aperçu hands-off Gamescom 2026 d'intheGame (29 août 2026) et le site officiel japonais pour le contexte du monde.",
      keywords: ["Aion 2 sous-marin", "Aion 2 plongée", "Aion 2 exploration", "Aion 2 open world"],
      sections: [
        section("confirmed", "Ce qui est confirmé", "Le monde continue sous la surface ; plongée et exploration possibles. Exploration orientée curiosité, dans le même monde seamless (~36x)."),
        section("traversal", "Plongée comme couche de déplacement", "Le vol donne la liberté du ciel, la plongée celle de la mer — le monde paraît vertical. Transitions terre/air/eau sans écrans de chargement."),
        section("exploration", "Exploration orientée curiosité", "Conçue comme réponse à la curiosité, pas aux marqueurs. Avec l'anti-dailies, les secrets sous-marins devraient être liés à la découverte. Nœuds de récolte sous-marins probables."),
        section("launch-scope", "À attendre au lancement", "Zones sous-marines attendues dans le build du 5 octobre ; le LST des 17-18 septembre (niveau 37) testera la première fois. Mécaniques (profondeur, respiration, combat) non précisées."),
      ],
    }),
    de: articleCopy(guideLabels, "de", 4, {
      eyebrow: "WELT & ERKUNDUNG",
      title: "Aion 2 Unterwasser-Erkundung: Tauchen unter die Seamless-Welt",
      description: "Die Gamescom-2026-Vorschau bestätigte, dass die Aion-2-Welt unter der Wasseroberfläche weitergeht. Was das für Fortbewegung, Sammeln und die neugiergetriebene Erkundung bedeutet.",
      intro: "Die Welt von Aion 2 endet nicht am Ufer: Die Gamescom-2026-Vorschau bestätigte, dass die Seamless-Welt unter Wasser weitergeht, mit Tauchen und Erkundung. Für eine Welt ~36x größer als das Original ist das eine echte Erweiterung von „groß“.",
      sourceNote: "Basierend auf intheGames Hands-off-Gamescom-2026-Vorschau (29. August 2026) und der japanischen offiziellen Website für den Weltkontext.",
      keywords: ["Aion 2 Unterwasser", "Aion 2 Tauchen", "Aion 2 Erkundung", "Aion 2 Open World"],
      sections: [
        section("confirmed", "Was bestätigt ist", "Die Welt geht unter die Wasseroberfläche; Tauchen und Erkundung möglich. Neugiergetriebene Erkundung in derselben Seamless-Welt (~36x)."),
        section("traversal", "Tauchen als Fortbewegung", "Fliegen gibt die Freiheit des Himmels, Tauchen die des Meeres — die Welt wirkt vertikal. Land/Luft/Wasser-Übergänge ohne Ladebildschirme."),
        section("exploration", "Neugiergetriebene Erkundung", "Als Reaktion auf Neugier statt Questmarker konzipiert. Mit Anti-Dailies sollten Unterwasser-Geheimnisse an Entdeckung gekoppelt sein. Unterwasser-Sammelknoten wahrscheinlich."),
        section("launch-scope", "Zum Start erwartet", "Unterwasserzonen im Build vom 5. Oktober erwartet; das LST (17.–18. September, Level 37) testet erstmals. Mechaniken (Tiefe, Atmung, Kampf) nicht spezifiziert."),
      ],
    }),
    es: articleCopy(guideLabels, "es", 4, {
      eyebrow: "MUNDO Y EXPLORACIÓN",
      title: "Exploración submarina de Aion 2: buceando bajo el mundo seamless",
      description: "El avance de Gamescom 2026 confirmó que el mundo de Aion 2 se extiende bajo la superficie. Qué significa para el movimiento, la recolección y la exploración por curiosidad.",
      intro: "El mundo de Aion 2 no termina en la orilla: el avance de Gamescom 2026 confirmó que el mundo seamless continúa bajo el agua, con buceo y exploración. Para un mundo ~36x más grande que el original, es una ampliación real de «grande».",
      sourceNote: "Basado en el avance hands-off de Gamescom 2026 de intheGame (29 de agosto de 2026) y el sitio oficial japonés para el contexto del mundo.",
      keywords: ["Aion 2 submarino", "Aion 2 buceo", "Aion 2 exploración", "Aion 2 open world"],
      sections: [
        section("confirmed", "Lo confirmado", "El mundo continúa bajo la superficie; buceo y exploración posibles. Exploración por curiosidad, en el mismo mundo seamless (~36x)."),
        section("traversal", "El buceo como capa de movimiento", "Volar da la libertad del cielo, bucear la del mar — el mundo se siente vertical. Transiciones tierra/aire/agua sin pantallas de carga."),
        section("exploration", "Exploración por curiosidad", "Concebida como respuesta a la curiosidad, no a los marcadores. Con el anti-dailies, los secretos submarinos deberían ligarse al descubrimiento. Nodos de recolección submarinos probables."),
        section("launch-scope", "Qué esperar al lanzamiento", "Zonas submarinas esperadas en el build del 5 de octubre; el LST del 17-18 de septiembre (nivel 37) probará por primera vez. Mecánicas (profundidad, respiración, combate) sin especificar."),
      ],
    }),
    "pt-br": articleCopy(guideLabels, "pt-br", 4, {
      eyebrow: "MUNDO E EXPLORAÇÃO",
      title: "Exploração subaquática do Aion 2: mergulhando sob o mundo seamless",
      description: "A impressão da Gamescom 2026 confirmou que o mundo do Aion 2 se estende sob a superfície. O que isso significa para movimentação, coleta e exploração por curiosidade.",
      intro: "O mundo do Aion 2 não termina na praia: a impressão da Gamescom 2026 confirmou que o mundo seamless continua debaixo d'água, com mergulho e exploração. Para um mundo ~36x maior que o original, é uma expansão real do «grande».",
      sourceNote: "Com base na impressão hands-off da Gamescom 2026 da intheGame (29 de agosto de 2026) e no site oficial japonês para o contexto do mundo.",
      keywords: ["Aion 2 subaquático", "Aion 2 mergulho", "Aion 2 exploração", "Aion 2 open world"],
      sections: [
        section("confirmed", "O que está confirmado", "O mundo continua sob a superfície; mergulho e exploração possíveis. Exploração por curiosidade, no mesmo mundo seamless (~36x)."),
        section("traversal", "Mergulho como camada de movimento", "Voar dá a liberdade do céu, mergulhar a do mar — o mundo parece vertical. Transições terra/ar/água sem telas de carregamento."),
        section("exploration", "Exploração por curiosidade", "Concebida como resposta à curiosidade, não aos marcadores. Com o anti-dailies, os segredos subaquáticos devem ligar-se à descoberta. Nós de coleta subaquáticos prováveis."),
        section("launch-scope", "O que esperar no lançamento", "Zonas subaquáticas esperadas no build de 5 de outubro; o LST de 17-18 de setembro (nível 37) testará pela primeira vez. Mecânicas (profundidade, respiração, combate) sem especificar."),
      ],
    }),
    ru: articleCopy(guideLabels, "ru", 4, {
      eyebrow: "МИР И ИССЛЕДОВАНИЕ",
      title: "Подводное исследование Aion 2: погружение под бесшовный мир",
      description: "Превью Gamescom 2026 подтвердило, что мир Aion 2 продолжается под водой. Что это значит для передвижения, сбора и исследования, основанного на любопытстве.",
      intro: "Мир Aion 2 не заканчивается у берега: превью Gamescom 2026 подтвердило, что бесшовный мир продолжается под водой, с возможностью нырять и исследовать. Для мира ~в 36 раз больше оригинала это реальное расширение понятия «большой».",
      sourceNote: "На основе превью hands-off Gamescom 2026 от intheGame (29 августа 2026) и японского официального сайта для контекста мира.",
      keywords: ["Aion 2 подводный", "Aion 2 ныряние", "Aion 2 исследование", "Aion 2 open world"],
      sections: [
        section("confirmed", "Что подтверждено", "Мир продолжается под поверхностью; ныряние и исследование возможны. Исследование на любопытстве, в том же бесшовном мире (~36x)."),
        section("traversal", "Погружение как слой передвижения", "Полёт даёт свободу неба, ныряние — свободу моря; мир ощущается вертикальным. Переходы суша/воздух/вода без загрузок."),
        section("exploration", "Исследование на любопытстве", "Задумано как ответ на любопытство, а не на маркеры. С анти-дейли дизайном подводные секреты должны быть связаны с открытиями. Подводные узлы сбора вероятны."),
        section("launch-scope", "Чего ждать на запуске", "Подводные зоны ожидаются в билде 5 октября; LST 17–18 сентября (кап 37) протестирует впервые. Механики (глубина, дыхание, бой) не раскрыты."),
      ],
    }),
    "zh-hant": articleCopy(guideLabels, "zh-hant", 4, {
      eyebrow: "世界與探索",
      title: "Aion 2 水下探索：潛入無縫世界的海面之下",
      description: "Gamescom 2026 前瞻確認 Aion 2 世界在海面之下繼續延伸。以下說明水下探索對移動、採集與好奇心驅動設計理念的意義。",
      intro: "Aion 2 的世界不止於海岸線。Gamescom 2026 前瞻確認，無縫開放世界在海面之下繼續延伸——玩家可潛水探索水下區域，作為同一世界的自然層次。對一款賣點是世界面積約為初代 36 倍的遊戲而言，水下探索是對『大』的實質擴展。本指南彙總已知資訊與探索方式的含義。",
      sourceNote: "基於 intheGame 的 Gamescom 2026 閉門前瞻與開發者問答（2026-08-29），世界背景以 Aion 2 日本官網為準。",
      keywords: ["Aion 2 水下", "Aion 2 潛水", "Aion 2 探索", "Aion 2 開放世界", "Aion 2 游泳"],
      sections: [
        section("confirmed", "前瞻確認的內容", ["報導描述世界在海面之下繼續延伸：玩家可潛水探索水下區域，水不是硬邊界。", "探索被定位為好奇心驅動（『那邊有什麼？』），水下區域與飛行、最少載入畫面的無縫地貌同為主要牽引。", "它仍是同一無縫開放世界（約初代 36 倍）的一部分——水下區域應與陸地連續而非獨立副本。"]),
        section("traversal", "作為移動層的水下", ["飛行給予天空自由，潛水給予海下自由；兩者讓世界顯得垂直而非扁平，是 Aion 2 體現場景規模的關鍵。", "由於世界無縫，陸地/空中/水面的轉換應是常規移動而非載入門——與『載入畫面盡可能少』的承諾一致。", "前瞻中的坐騎細節（掛在鳥腿、騎魔像肩）暗示坐騎在不同環境也可能有不同表現。"]),
        section("exploration", "好奇心驅動探索", ["開發者將探索定位為對好奇心的回應，而非追逐任務標記。水下區域正契合：你潛水是想看看下面有什麼，而非標記要求。", "結合反日常設計：內容應讓人感到值得，水下秘密與獎勵應關聯發現而非清單完成。", "站內已文件化的採集與資源系統大概率是這些區域的核心玩法錨點——期待水下採集點。"]),
        section("launch-scope", "上線範圍預期", ["全球 10 月 5 日版本應包含這些水下區域作為開篇世界的一部分；9 月 17-18 日上線規模測試（37 級上限）是首次驗證無縫邊界的視窗。", "在 NC 詳述水下機制前，深度、呼吸機制與水下戰鬥視為未知——前瞻只確認潛水可行，未給系統。", "官方細節或 LST 本身透露更多後，本指南將更新。"]),
      ],
    }),
  },
};