import { articleCopy, localizations, newsLabels, publishedVerified, section } from "./trending-august-31-shared";
import type { ContentEntry, ContentHeroImage, ContentSource } from "./content-registry";

/* ARTICLE 3 — October 2026 launch crowd: GTA 6 avoidance and where Aion 2 lands (Oct 5) */

const crowdSource1: ContentSource = {
  id: "polygon-october-2026-gta6-2026-08-30",
  kind: "third-party", publisher: "Polygon",
  label: "October 2026 has way too many games trying to escape GTA 6",
  url: "https://www.polygon.com/october-2026-new-video-games/",
  publishedAt: "2026-08-30",
  retrievedAt: "2026-08-31",
  verifiedAt: "2026-08-31",
  localizations: localizations({
    "zh-hans": "2026 年 10 月有太多游戏想逃离 GTA 6",
    en: "October 2026 has way too many games trying to escape GTA 6",
    fr: "Octobre 2026 a bien trop de jeux qui tentent d'échapper à GTA 6",
    de: "Der Oktober 2026 hat viel zu viele Spiele, die vor GTA 6 fliehen wollen",
    es: "Octubre de 2026 tiene demasiados juegos tratando de escapar de GTA 6",
    ja: "2026年10月はGTA 6から逃れようとするゲームが多すぎる",
    "pt-br": "Outubro de 2026 tem jogos demais tentando escapar de GTA 6",
    ru: "Октябрь 2026 — слишком много игр пытаются сбежать от GTA 6",
    ko: "2026년 10월, GTA 6를 피하려는 게임이 너무 많다",
    "zh-hant": "2026 年 10 月有太多遊戲想逃離 GTA 6",
  }, "https://www.polygon.com/october-2026-new-video-games/"),
};

const crowdSource2: ContentSource = {
  id: "massivelyop-week-in-review-2026-08-30",
  kind: "third-party", publisher: "Massively Overpowered",
  label: "MMO Week in Review: Gamescom, Asura, and Ascension",
  url: "https://massivelyop.com/2026/08/30/mmo-week-in-review-gamescom-asura-and-ascension/",
  publishedAt: "2026-08-30",
  retrievedAt: "2026-08-31",
  verifiedAt: "2026-08-31",
  localizations: localizations({
    "zh-hans": "MMO 周报：Gamescom、Asura 与 Ascension",
    en: "MMO Week in Review: Gamescom, Asura, and Ascension",
    fr: "Revue de la semaine MMO : Gamescom, Asura et Ascension",
    de: "MMO-Wochenrückblick: Gamescom, Asura und Ascension",
    es: "Resumen semanal de MMO: Gamescom, Asura y Ascension",
    ja: "MMOウィークリーレビュー：Gamescom、Asura、Ascension",
    "pt-br": "Revista semanal de MMOs: Gamescom, Asura e Ascension",
    ru: "Еженедельный обзор MMO: Gamescom, Asura и Ascension",
    ko: "MMO 위클리 리뷰: Gamescom, Asura, Ascension",
    "zh-hant": "MMO 週報：Gamescom、Asura 與 Ascension",
  }, "https://massivelyop.com/2026/08/30/mmo-week-in-review-gamescom-asura-and-ascension/"),
};

const crowdHero: ContentHeroImage = {
  src: "https://blogfiles.ncsoft.net/news/af7330da-4ff6-4b58-aece-400e6061a3be.jpg",
  width: 1100, height: 605,
  credit: "NC Corporation",
  sourceUrl: "https://aion2.plaync.com/ja-jp/board/notice/list",
  rights: "linked-official-media",
  translations: {
    "zh-hans": { alt: "Aion 2 十月发行潮新闻配图", caption: "NC 官方配图；2026 年 10 月是避开 GTA 6（11 月）的拥挤发行窗口，Aion 2 定档 10 月 5 日。" },
    en: { alt: "Aion 2 October 2026 launch crowd news image", caption: "Official NC artwork; October 2026 is a crowded release window as publishers dodge GTA 6 in November, and Aion 2 is set for October 5." },
    fr: { alt: "Image de la cohue des sorties d'octobre 2026 pour Aion 2", caption: "Visuel officiel NC ; octobre 2026 est une fenêtre de sorties très encombrée, les éditeurs évitant GTA 6 en novembre, et Aion 2 est prévu le 5 octobre." },
    de: { alt: "Bild zum Startgedränge im Oktober 2026 für Aion 2", caption: "Offizielles NC-Artwork; der Oktober 2026 ist ein überfülltes Release-Fenster, da Publisher GTA 6 im November meiden, und Aion 2 startet am 5. Oktober." },
    es: { alt: "Imagen de la avalancha de lanzamientos de octubre 2026 para Aion 2", caption: "Arte oficial de NC; octubre de 2026 es una ventana de lanzamientos abarrotada mientras los editores esquivan GTA 6 en noviembre, y Aion 2 sale el 5 de octubre." },
    ja: { alt: "Aion 2 2026年10月発売ラッシュニュース画像", caption: "NC公式アートワーク；2026年10月は11月のGTA 6を避ける発売ラッシュの時期であり、Aion 2は10月5日予定です。" },
    "pt-br": { alt: "Imagem da maré de lançamentos de outubro de 2026 para o Aion 2", caption: "Arte oficial da NC; outubro de 2026 é uma janela de lançamentos lotada enquanto as editoras evitam GTA 6 em novembro, e o Aion 2 estreia em 5 de outubro." },
    ru: { alt: "Изображение октябрьской лавины релизов 2026 года для Aion 2", caption: "Официальный арт NC; октябрь 2026 — перегруженное окно релизов, так как издатели избегают GTA 6 в ноябре, а Aion 2 выходит 5 октября." },
    ko: { alt: "Aion 2 2026년 10월 출시 러시 뉴스 이미지", caption: "NC 공식 이미지입니다. 2026년 10월은 11월의 GTA 6를 피하는 게임들의 출시 러시 기간이며 Aion 2는 10월 5일로 예정됐습니다." },
    "zh-hant": { alt: "Aion 2 十月發行潮新聞配圖", caption: "NC 官方配圖；2026 年 10 月是避開 GTA 6（11 月）的擁擠發行視窗，Aion 2 定檔 10 月 5 日。" },
  },
};

export const trendingAugust31Article3: ContentEntry = {
  section: "news",
  slug: "aion-2-october-2026-gta6-launch-crowd",
  schemaType: "NewsArticle",
  publishedAt: "2026-08-31",
  updatedAt: "2026-08-31",
  readingMinutes: 5,
  publication: publishedVerified,
  sources: [crowdSource1, crowdSource2],
  heroImage: crowdHero,
  related: [
    { kind: "content", section: "news", slug: "aion-2-release-date-october-5-2026" },
    { kind: "content", section: "news", slug: "aion-2-gamescom-2026-preview-impressions" },
    { kind: "content", section: "guides", slug: "aion-2-language-support-8-languages-guide" },
    { kind: "content", section: "guides", slug: "aion-2-monetization-f2p-cosmetics-guide" },
  ],
  translations: {
    en: articleCopy(newsLabels, "en", 5, {
      eyebrow: "OCTOBER 2026 RELEASE WINDOW",
      title: "Aion 2 and the October 2026 Launch Crowd: Why Everyone Is Dodging GTA 6",
      description: "Polygon reports October 2026 is a logjam of releases as publishers front-load games ahead of GTA 6 in November. Aion 2 lands October 5, one of roughly two dozen titles in the month — including Ace Combat 8 (Oct 2) and Gears of War: E-Day (Oct 6).",
      intro: "The month around Aion 2's October 5 launch is not empty — it is the opposite. Polygon's analysis on August 30 describes October 2026 as a release window that is arguably worse than September, because publishers rushed titles forward to stay ahead of GTA 6 in November. For Aion 2 players this is context worth knowing: what else ships in the same window, why the calendar is so crowded, and what it means for a new MMO fighting for attention at launch.",
      sourceNote: "Based on Polygon's analysis 'October 2026 has way too many games trying to escape GTA 6' (August 30, 2026), cross-checked with Massively Overpowered's MMO Week in Review (August 30, 2026) covering the same Gamescom launch-date wave.",
      keywords: ["Aion 2 October 5", "Aion 2 GTA 6", "October 2026 release window", "Aion 2 launch competition", "Aion 2 release date"],
      sections: [
        section("the-logjam", "A Month Worse Than September", ["Polygon walked back its own September warning, saying October is “arguably going to be worse”: last-minute release dates left a month “bound to go down in backlog history”. The first week of October in particular is “a free-for-all” as the biggest games try to get far enough ahead of GTA 6.", "GTA 6 itself arrives in November. Publishers reasoned that a September buffer was still too close, so they front-loaded into October — and the result is dozens of releases in a single month.", "For a new MMO, that is the environment on day one: not an empty runway, but a packed shelf competing for the same player attention and streaming time."]),
        section("who-else-ships", "Who Else Ships the Same Week", ["Aion 2 (October 5) is surrounded by major titles: Ace Combat 8: Wings of Theve (October 2) and Gears of War: E-Day (October 6) bracket it within days, with Dynasty Warriors 3: Complete Edition Remastered and Rayman Legends Retold on October 1.", "The wider month adds Dragon's Dogma 2: Dark Arisen (October 9), Call of Duty: Modern Warfare 4 (October 23), Final Fantasy Resonance (October 22), Phantom Blade Zero (October 29), and the Castlevania: Belmont's Curse (October 15). Roughly two dozen titles are listed for the month.", "MMO players specifically get a different crowd: Massively Overpowered's week-in-review noted the launch-date wave from Gamescom included both Aion 2 and Path of Exile 2 (1.0 on December 11), so the October MMO audience is not split with PoE 2's full release."]),
        section("why-ncsoft-picked-oct5", "Why NCSoft Landed on October 5", ["NCSoft did not publish a reason for the date itself. Polygon's framing suggests a tactical reading: October 5 is early enough in the month to sit ahead of late-October blockbusters and clear of GTA 6 in November, while still following the September 30 Founder's Pack early access.", "The September 17–18 Launch Scale Test gives NCSoft a built-in rehearsal roughly three weeks before launch — a structure that reads as deliberate sequencing rather than a last-minute slot.", "Massively Overpowered framed it as a ramp of milestones leading toward the October 5 date. Whether the calendar was chosen or endured, the practical effect is a week where Aion 2 shares shelf space with at least two major single-player launches."]),
        section("what-it-means", "What It Means for Launch", ["A crowded window raises the cost of silence: players deciding what to install in the first week of October will see Aion 2 next to Ace Combat 8 and Gears of War: E-Day. A free-to-play entry point helps, because the barrier to trying the game is one click rather than a purchase decision.", "For community-building, the free Launch Scale Test (September 17–18) is the moment to turn curiosity into accounts before the crowd arrives. Anyone who tries the test and likes it is far more likely to return for the October 5 launch.", "Finally, treat the October calendar as volatile: Polygon itself expects “some last-minute delays as publishers accept the reality of the situation”. Dates near Aion 2 can move, which only makes the official Steam store page the reference to trust."]),
        section("takeaway", "The Takeaway", ["Aion 2 launches into the single most crowded month of 2026, a deliberate by-product of the industry clearing the runway for GTA 6 in November. That is neither good nor bad by itself — it depends on execution.", "For players, the actionable takeaway is timing: use the free routes before October 5 — the Launch Scale Test and the Steam Playtest request — to decide before the noise of the month begins.", "For anyone tracking the MMO space, the same week's news wave (Gamescom dates, the Korean-market going-global trend) suggests the genre is positioning for a busy autumn, and Aion 2 is one of the few MMO launches in it."]),
      ],
    }),
    "zh-hans": articleCopy(newsLabels, "zh-hans", 5, {
      eyebrow: "2026 年 10 月发行窗口",
      title: "Aion 2 与 2026 年 10 月发行潮：为什么大家都要躲开 GTA 6",
      description: "Polygon 报道称 2026 年 10 月是一场发行拥堵——厂商抢在 11 月 GTA 6 之前集中上线。Aion 2 定于 10 月 5 日，与 Ace Combat 8（10/2）、Gears of War: E-Day（10/6）等约二十多款作品同月竞争。",
      intro: "Aion 2 定档 10 月 5 日的这个月并不空旷，恰恰相反。Polygon 8 月 30 日的分析将 2026 年 10 月描述为一个可能比 9 月更糟的发行窗口，因为厂商纷纷抢在 11 月 GTA 6 之前提前发售。对 Aion 2 玩家而言，这是值得了解的背景：同一窗口还有什么、为什么排期如此拥挤、以及这对一款上线首日就要争夺注意力的新 MMO 意味着什么。",
      sourceNote: "基于 Polygon 的分析文章《2026 年 10 月有太多游戏想逃离 GTA 6》（2026-08-30），并与 Massively Overpowered 的 MMO 周报（2026-08-30）报道的同一 Gamescom 发行日期浪潮交叉核对。",
      keywords: ["Aion 2 10月5日", "Aion 2 GTA 6", "2026年10月发行潮", "Aion 2 上线竞争", "Aion 2 发售日期"],
      sections: [
        section("the-logjam", "比 9 月更糟的一个月", ["Polygon 收回自己此前的 9 月警告，称 10 月「可以说更糟」：临时敲定的发售日期留下了一个「注定载入游戏史积压榜」的月份。10 月第一周尤其「乱成一团」——最大的几款游戏都尽量赶在 GTA 6 之前足够远的地方。", "GTA 6 本身在 11 月到来。厂商判定 9 月的缓冲仍然太近，于是把作品提前塞进 10 月——结果是单月数十款作品扎堆。", "对一款新 MMO 来说，这就是上线首日的环境：不是空旷跑道，而是塞满货架、争夺同一批玩家注意力与直播时长的竞争。"]),
        section("who-else-ships", "同一周还有谁", ["Aion 2（10 月 5 日）身边是重磅作品：Ace Combat 8: Wings of Theve（10 月 2 日）与 Gears of War: E-Day（10 月 6 日）在数天内夹击，10 月 1 日还有《真三国无双 3 完全版 重制》与 Rayman Legends Retold。", "整个月还有 Dragon's Dogma 2: Dark Arisen（10/9）、使命召唤：现代战争 4（10/23）、Final Fantasy Resonance（10/22）、Phantom Blade Zero（10/29）与 Castlevania: Belmont's Curse（10/15）。月内列出的作品约二十余款。", "MMO 玩家看到的是另一批人：Massively Overpowered 的周报指出，Gamescom 的发行日期浪潮同时包含 Aion 2 与 Path of Exile 2（1.0 于 12 月 11 日），因此 10 月 MMO 受众不会与 PoE 2 正式版分流。"]),
        section("why-ncsoft-picked-oct5", "NCSoft 为什么选 10 月 5 日", ["NCSoft 未公布对日期本身的解释。Polygon 的框架给出一种策略性读法：10 月 5 日足够早，既赶在月末大作之前，又远离 11 月的 GTA 6，同时紧随 9 月 30 日创始人包抢先体验之后。", "9 月 17–18 日的 Launch Scale Test 为 NCSoft 提供了上线前约三周的内建彩排——这一结构更像刻意排序而非临时挤入的档期。", "Massively Overpowered 将其描述为通往 10 月 5 日的一系列里程碑。无论这个日期是选来的还是承受的，实际效果是：这一周 Aion 2 至少与两款大型单人游戏共享货架。"]),
        section("what-it-means", "对上线意味着什么", ["拥挤的窗口提高了沉默的成本：10 月第一周决定装什么的玩家会把 Aion 2 与 Ace Combat 8、Gears of War: E-Day 并列看到。免费游玩入口有帮助，因为试玩的门槛是一次点击而非一次购买决策。", "对社群建设，免费的 Launch Scale Test（9 月 17–18 日）是在人群到来之前把好奇转化为账号的时刻。试过并喜欢的人更可能回到 10 月 5 日的上线。", "最后，把 10 月档期视为易变：Polygon 自己预计会有「一些最后一刻的延期，因为厂商接受现实」。Aion 2 附近的日期可能变动，这只会让官方 Steam 商店页更值得信任。"]),
        section("takeaway", "结论", ["Aion 2 在 2026 年最拥挤的月份上线——这是整个行业为 GTA 6 在 11 月清出跑道而造成的副产品。这本身无所谓好坏，取决于执行。", "对玩家，可操作的结论是时机：在 10 月 5 日之前使用免费渠道——Launch Scale Test 与 Steam Playtest 申请——在月份的噪音开始前做决定。", "对跟踪 MMO 的人，同一周的新闻浪潮（Gamescom 日期、韩厂全球化趋势）表明该品类正在为一个繁忙的秋天布局，而 Aion 2 是其中为数不多的 MMO 上线之一。"]),
      ],
    }),
    ko: articleCopy(newsLabels, "ko", 5, {
      eyebrow: "2026년 10월 출시 창",
      title: "Aion 2와 2026년 10월 출시 러시: 왜 모두 GTA 6를 피하는가",
      description: "Polygon은 2026년 10월이 GTA 6(11월)를 피하려는 게임들의 출시 러시라고 보도합니다. Aion 2는 10월 5일로, Ace Combat 8(10/2)·Gears of War: E-Day(10/6) 등 20여 타이틀과 같은 달입니다.",
      intro: "Aion 2의 10월 5일 출시가 있는 달은 비어 있지 않습니다. Polygon의 8월 30일 분석은 2026년 10월을 9월보다 나쁠 수 있는 출시 창으로 묘사합니다. 신규 MMO가 출시일에 주목을 두고 경쟁해야 하는 환경을 정리합니다.",
      sourceNote: "Polygon 분석(2026-08-30)과 Massively Overpowered MMO 위클리 리뷰(2026-08-30)의 Gamescom 출시일 물결 보도를 교차 확인했습니다.",
      keywords: ["Aion 2 10월 5일", "Aion 2 GTA 6", "2026년 10월 출시 러시", "Aion 2 출시 경쟁", "Aion 2 출시일"],
      sections: [
        section("the-logjam", "9월보다 나쁠 수 있는 달", "Polygon은 10월이 '더 나쁠 것'이라고 말합니다. 첫 주는 특히 난전이며, GTA 6가 11월에 오기 때문입니다. 퍼블리셔들은 9월 완충이 부족하다고 판단해 10월로 앞당겼고, 결과는 한 달에 수십 개 타이틀입니다. 신규 MMO의 1일 차 환경은 빈 활주로가 아니라 꽉 찬 선반입니다."),
        section("who-else-ships", "같은 주에 출시하는 작품", "Aion 2(10월 5일)는 Ace Combat 8(10월 2일)과 Gears of War: E-Day(10월 6일) 사이에 낀 상태입니다. 한 달에 약 20여 타이틀 — Dragon's Dogma 2: Dark Arisen(10/9), Call of Duty: Modern Warfare 4(10/23), Final Fantasy Resonance(10/22), Phantom Blade Zero(10/29) 등. MMO 쪽은 PoE 2 정식판(12/11)과 겹치지 않아 10월 MMO 관객은 분산되지 않습니다."),
        section("why-ncsoft-picked-oct5", "NC소프트가 10월 5일을 고른 이유", "NC소프트는 날짜 자체에 대한 이유를 밝히지 않았습니다. 10월 5일은 9월 30일 파운더스 팩 얼리 액세스 직후이자 11월 GTA 6에서 먼 시점입니다. 9월 17–18일 LST는 약 3주 전 내장 리허설로, 의도된 순서로 읽힙니다. 결과적으로 Aion 2는 같은 주에 최소 두 개의 대형 싱글 게임과 선반을 공유합니다."),
        section("what-it-means", "출시에 주는 의미", "혼잡한 창은 침묵의 비용을 높입니다. 무료 플레이 진입점은 시도 장벽을 구매가 아닌 한 번의 클릭으로 낮춥니다. 커뮤니티 구축에 LST(9/17–18)는 군중이 오기 전에 호기심을 계정으로 바꿀 순간입니다. 마지막으로, 10월 달력은 변동성 큽니다 — Polygon도 막판 연기를 예상하며, 공식 Steam 상점 페이지를 기준으로 삼으세요."),
        section("takeaway", "결론", "Aion 2는 2026년 가장 혼잡한 달에 출시됩니다. 이는 산업이 11월 GTA 6를 위해 활주로를 비운 부산물입니다. 플레이어에게는 출시 전 무료 경로(LST, Steam Playtest)를 먼저 쓰는 타이밍이 실무적 결론이며, MMO 추적자에게는 가을 시즌을 겨냥한 장르의 배치 신호입니다."),
      ],
    }),
    ja: articleCopy(newsLabels, "ja", 5, {
      eyebrow: "2026年10月のリリースラッシュ",
      title: "Aion 2 と2026年10月の発売ラッシュ：なぜみんなGTA 6を避けるのか",
      description: "Polygon は2026年10月がGTA 6（11月）を避けるための発売ラッシュだと報じます。Aion 2 は10月5日で、Ace Combat 8（10/2）・Gears of War: E-Day（10/6）など20余りのタイトルと同じ月です。",
      intro: "Aion 2 の10月5日という発売日がある月は空いていません。Polygon の8月30日の分析は、2026年10月を9月より悪いかもしれない発売窓として描きます。新規MMOが初日に注目を争う環境を整理します。",
      sourceNote: "Polygon の分析（2026-08-30）と、Massively Overpowered のMMOウィークリーレビュー（2026-08-30）による Gamescom 発売日報道を照合しました。",
      keywords: ["Aion 2 10月5日", "Aion 2 GTA 6", "2026年10月発売ラッシュ", "Aion 2 発売競争", "Aion 2 発売日"],
      sections: [
        section("the-logjam", "9月より悪いかもしれない月", "Polygon は10月は「議論の余地なく悪くなる」と述べ、特に最初の1週間は大乱戦だとします。GTA 6 が11月に来るため、各社は9月のバッファを不十分と見て10月に前倒ししました。新規MMOの1日目は、空いた滑走路ではなく満杯の棚での競争です。"),
        section("who-else-ships", "同じ週に何が来るか", "Aion 2（10月5日）は Ace Combat 8（10月2日）と Gears of War: E-Day（10月6日）に挟まれています。月内には約20タイトル — Dragon's Dogma 2: Dark Arisen（10/9）、Call of Duty: Modern Warfare 4（10/23）、Final Fantasy Resonance（10/22）、Phantom Blade Zero（10/29）など。MMO は PoE 2 正式版（12/11）と重ならず、10月のMMO観客は分散しません。"),
        section("why-ncsoft-picked-oct5", "なぜNCソフトは10月5日か", "NCソフトは日付自体の理由を公表していません。10月5日は9月30日ファウンダーズパック先行体験の直後で、11月のGTA 6から遠い位置です。9月17–18日のLSTは約3週間前の内蔵リハーサルで、意図的な順序として読めます。結果として、Aion 2 は同じ週に少なくとも2本の大型シングルゲームと棚を共有します。"),
        section("what-it-means", "発売への意味", "混雑した窓は沈黙のコストを上げます。無料プレイの入口は試す障壁を購入からワンクリックに下げます。コミュニティ構築にはLST（9/17–18）が群衆が来る前に好奇心をアカウントに変える瞬間です。最後に、10月のカレンダーは変動が大きく — Polygon 自身も直前の延期を予想し、公式Steamページを基準にしてください。"),
        section("takeaway", "結論", "Aion 2 は2026年で最も混雑した月に発売します。これは業界が11月のGTA 6のために滑走路を空けた副産物です。プレイヤーへの実務的結論はタイミング — 発売前に無料経路（LST・Steam Playtest）を使い、月のノイズが始まる前に判断することです。"),
      ],
    }),
    fr: articleCopy(newsLabels, "fr", 5, {
      eyebrow: "FENÊTRE DE SORTIES D'OCTOBRE 2026",
      title: "Aion 2 et la cohue des sorties d'octobre 2026 : pourquoi tout le monde esquive GTA 6",
      description: "Polygon rapporte qu'octobre 2026 est un embouteillage de sorties, les éditeurs avançant leurs jeux avant GTA 6 en novembre. Aion 2 sort le 5 octobre, avec une vingtaine de titres le même mois — dont Ace Combat 8 (2 oct.) et Gears of War: E-Day (6 oct.).",
      intro: "Le mois du lancement d'Aion 2 le 5 octobre n'est pas vide — c'est l'inverse. L'analyse de Polygon du 30 août décrit octobre 2026 comme une fenêtre possiblement pire que septembre, car les éditeurs ont avancé leurs sorties pour rester devant GTA 6 en novembre. Voici ce que ça signifie pour un nouveau MMO qui doit se battre pour l'attention.",
      sourceNote: "Basé sur l'analyse de Polygon « October 2026 has way too many games trying to escape GTA 6 » (30 août 2026), recoupé avec la revue de semaine MMO de Massively Overpowered (30 août 2026) couvrant la même vague de dates Gamescom.",
      keywords: ["Aion 2 5 octobre", "Aion 2 GTA 6", "fenêtre de sorties octobre 2026", "Aion 2 concurrence", "Aion 2 date de sortie"],
      sections: [
        section("the-logjam", "Un mois pire que septembre", "Polygon a retiré son propre avertissement de septembre, disant qu'octobre « sera sans doute pire » : des dates de dernière minute laissent un mois « voué à entrer dans l'histoire des arriérés ». La première semaine est « une mêlée générale ». GTA 6 arrive en novembre ; les éditeurs ont jugé septembre trop proche et ont tout poussé en octobre. Pour un nouveau MMO, le jour 1 est une étagère pleine, pas une piste dégagée."),
        section("who-else-ships", "Qui d'autre sort la même semaine", "Aion 2 (5 octobre) est entouré : Ace Combat 8: Wings of Theve (2 octobre) et Gears of War: E-Day (6 octobre) l'encadrent, avec Dynasty Warriors 3 Complete et Rayman Legends Retold le 1er. Le mois ajoute Dragon's Dogma 2: Dark Arisen (9), Call of Duty: Modern Warfare 4 (23), Final Fantasy Resonance (22), Phantom Blade Zero (29), Castlevania: Belmont's Curse (15) — environ deux douzaines de titres. Côté MMO, la vague Gamescom comprend aussi Path of Exile 2 (1.0 le 11 décembre), donc le public MMO d'octobre n'est pas divisé avec la sortie complète de PoE 2."),
        section("why-ncsoft-picked-oct5", "Pourquoi NCSoft a choisi le 5 octobre", "NCSoft n'a pas donné de raison pour la date. La lecture tactique : le 5 octobre est assez tôt pour être devant les blockbusters de fin de mois et loin de GTA 6 en novembre, tout en suivant l'accès anticipé des packs Fondateur du 30 septembre. Le test de charge 17–18 septembre sert de répétition intégrée. Massively OP décrit une rampe de jalons vers le 5 octobre. Effet pratique : une semaine où Aion 2 partage l'étagère avec au moins deux gros jeux solo."),
        section("what-it-means", "Ce que ça change au lancement", "Une fenêtre encombrée augmente le coût du silence : au choix du 1er octobre, Aion 2 côtoie Ace Combat 8 et Gears of War: E-Day. Le free-to-play abaisse la barrière à un clic. Pour la communauté, le test de charge gratuit (17–18 sept.) est le moment de convertir la curiosité en comptes avant la foule. Enfin, traitez le calendrier d'octobre comme volatil : Polygon attend « des retards de dernière minute »."),
        section("takeaway", "Conclusion", "Aion 2 sort dans le mois le plus encombré de 2026, produit de l'industrie qui dégage la piste pour GTA 6 en novembre. Ce n'est ni bon ni mauvais en soi. Pour les joueurs : utilisez les routes gratuites avant le 5 octobre — le test de charge et la demande Steam Playtest — pour décider avant le bruit du mois."),
      ],
    }),
    de: articleCopy(newsLabels, "de", 5, {
      eyebrow: "RELEASE-FENSTER OKTOBER 2026",
      title: "Aion 2 und das Start-Gedränge im Oktober 2026: Warum alle GTA 6 meiden",
      description: "Polygon berichtet, Oktober 2026 sei ein Stau von Veröffentlichungen, da Publisher ihre Spiele vor GTA 6 (November) nach vorn ziehen. Aion 2 startet am 5. Oktober, mit etwa zwei Dutzend Titeln im selben Monat — darunter Ace Combat 8 (2.10.) und Gears of War: E-Day (6.10.).",
      intro: "Der Monat um Aion 2s Start am 5. Oktober ist nicht leer — im Gegenteil. Die Polygon-Analyse vom 30. August beschreibt Oktober 2026 als ein Fenster, das womöglich schlimmer ist als September, weil Publisher ihre Titel nach vorn zogen, um GTA 6 im November auszuweichen. Hier ist, was das für ein neues MMO bedeutet, das am Starttag um Aufmerksamkeit kämpft.",
      sourceNote: "Basierend auf der Polygon-Analyse „October 2026 has way too many games trying to escape GTA 6“ (30. August 2026), abgeglichen mit dem MMO-Wochenrückblick von Massively Overpowered (30. August 2026).",
      keywords: ["Aion 2 5. Oktober", "Aion 2 GTA 6", "Release-Fenster Oktober 2026", "Aion 2 Start-Konkurrenz", "Aion 2 Erscheinungsdatum"],
      sections: [
        section("the-logjam", "Ein Monat, schlimmer als September", "Polygon zog seine eigene September-Warnung zurück und sagt, Oktober sei „wohl noch schlimmer“. Die erste Oktoberwoche sei „ein Kampf jeder gegen jeden“. GTA 6 kommt im November; Publisher hielten September für zu nah und zogen alles in den Oktober. Für ein neues MMO ist Tag 1 also ein volles Regal statt einer freien Bahn."),
        section("who-else-ships", "Wer sonst noch startet", "Aion 2 (5.10.) ist umgeben: Ace Combat 8: Wings of Theve (2.10.) und Gears of War: E-Day (6.10.) flankieren es, dazu Dynasty Warriors 3 Complete und Rayman Legends Retold am 1.10. Im Monat weiter: Dragon's Dogma 2: Dark Arisen (9.), Call of Duty: Modern Warfare 4 (23.), Final Fantasy Resonance (22.), Phantom Blade Zero (29.), Castlevania: Belmont's Curse (15.) — rund zwei Dutzend Titel. MMO-seitig umfasst die Gamescom-Welle auch Path of Exile 2 (1.0 am 11.12.), das Oktober-MMO-Publikum wird also nicht durch PoE 2s Vollversion geteilt."),
        section("why-ncsoft-picked-oct5", "Warum NCSoft den 5. Oktober wählte", "NCSoft nannte keinen Grund für das Datum. Taktische Lesart: Der 5. Oktober ist früh genug, um vor den Blockbustern des Monatsendes und fern von GTA 6 zu liegen, direkt nach dem Founder's-Pack-Frühstart am 30. September. Der LST 17.–18. September dient als eingebaute Generalprobe. Massively OP beschreibt eine Rampe von Meilensteinen zum 5. Oktober. Praktisch teilt Aion 2 die Woche mit mindestens zwei großen Singleplayer-Start."),
        section("what-it-means", "Was das für den Start bedeutet", "Ein volles Fenster erhöht die Kosten des Schweigens. Free-to-play senkt die Einstiegshürde auf einen Klick. Für die Community ist der kostenlose LST (17.–18.9.) der Moment, Neugier vor der Menge in Konten zu verwandeln. Behandeln Sie den Oktober-Kalender als volatil — Polygon selbst erwartet Last-Minute-Verschiebungen."),
        section("takeaway", "Fazit", "Aion 2 startet im vollsten Monat 2026, ein Nebenprodukt der Branche, die die Bahn für GTA 6 freiräumt. Für Spieler ist die handlungsrelevante Konsequenz das Timing: Nutzen Sie vor dem 5. Oktober die kostenlosen Wege (LST, Steam-Playtest-Anfrage) und entscheiden Sie, bevor der Lärm des Monats beginnt."),
      ],
    }),
    es: articleCopy(newsLabels, "es", 5, {
      eyebrow: "VENTANA DE OCTUBRE 2026",
      title: "Aion 2 y la avalancha de lanzamientos de octubre 2026: por qué todos esquivan GTA 6",
      description: "Polygon informa que octubre de 2026 es un atasco de lanzamientos, ya que los editores adelantan sus juegos antes de GTA 6 en noviembre. Aion 2 sale el 5 de octubre, con unas dos docenas de títulos el mismo mes — incluidos Ace Combat 8 (2 oct.) y Gears of War: E-Day (6 oct.).",
      intro: "El mes del lanzamiento de Aion 2 el 5 de octubre no está vacío — es lo contrario. El análisis de Polygon del 30 de agosto describe octubre de 2026 como una ventana posiblemente peor que septiembre, porque los editores adelantaron sus juegos para mantenerse lejos de GTA 6 en noviembre. Esto es lo que significa para un nuevo MMO que debe luchar por la atención.",
      sourceNote: "Basado en el análisis de Polygon «October 2026 has way too many games trying to escape GTA 6» (30 de agosto de 2026), cotejado con el resumen semanal de MMO de Massively Overpowered (30 de agosto de 2026).",
      keywords: ["Aion 2 5 de octubre", "Aion 2 GTA 6", "ventana de octubre 2026", "Aion 2 competencia", "Aion 2 fecha de lanzamiento"],
      sections: [
        section("the-logjam", "Un mes peor que septiembre", "Polygon retiró su propia advertencia de septiembre, diciendo que octubre «sin duda será peor»: fechas de última hora dejan un mes «destinado a pasar a la historia de la acumulación». La primera semana es «una batalla campal». GTA 6 llega en noviembre; los editores juzgaron septiembre demasiado cerca y lo empujaron todo a octubre. Para un nuevo MMO, el día 1 es una estantería llena, no una pista libre."),
        section("who-else-ships", "Quién más sale la misma semana", "Aion 2 (5 de octubre) está rodeado: Ace Combat 8: Wings of Theve (2 de octubre) y Gears of War: E-Day (6 de octubre) lo flanquean, con Dynasty Warriors 3 Complete y Rayman Legends Retold el día 1. El mes suma Dragon's Dogma 2: Dark Arisen (9), Call of Duty: Modern Warfare 4 (23), Final Fantasy Resonance (22), Phantom Blade Zero (29), Castlevania: Belmont's Curse (15) — unas dos docenas de títulos. En el lado MMO, la ola Gamescom incluye también Path of Exile 2 (1.0 el 11 de diciembre), así que el público MMO de octubre no se divide con la versión completa de PoE 2."),
        section("why-ncsoft-picked-oct5", "Por qué NCSoft eligió el 5 de octubre", "NCSoft no dio razón para la fecha. Lectura táctica: el 5 de octubre es bastante pronto para estar delante de los grandes de fin de mes y lejos de GTA 6 en noviembre, justo tras el acceso anticipado de los packs Fundador del 30 de septiembre. El test de carga 17–18 de septiembre sirve de ensayo integrado. Massively OP describe una rampa de hitos hacia el 5 de octubre. Efecto práctico: Aion 2 comparte semana con al menos dos grandes juegos para un jugador."),
        section("what-it-means", "Qué significa al lanzamiento", "Una ventana abarrotada eleva el coste del silencio. Free-to-play baja la barrera a un clic. Para la comunidad, el test de carga gratuito (17–18 de septiembre) es el momento de convertir la curiosidad en cuentas antes de la multitud. Trata el calendario de octubre como volátil — Polygon espera «retrasos de última hora»."),
        section("takeaway", "Conclusión", "Aion 2 sale en el mes más concurrido de 2026, producto de la industria que despeja la pista para GTA 6 en noviembre. Para los jugadores, la conclusión práctica es el momento: usa las vías gratuitas antes del 5 de octubre (test de carga, solicitud de Steam Playtest) para decidir antes de que empiece el ruido del mes."),
      ],
    }),
    "pt-br": articleCopy(newsLabels, "pt-br", 5, {
      eyebrow: "JANELA DE OUTUBRO 2026",
      title: "Aion 2 e a maré de lançamentos de outubro de 2026: por que todos fogem de GTA 6",
      description: "A Polygon informa que outubro de 2026 é um congestionamento de lançamentos, com editoras adiantando seus jogos antes de GTA 6 em novembro. O Aion 2 estreia em 5 de outubro, com cerca de duas dúzias de títulos no mesmo mês — incluindo Ace Combat 8 (2 out.) e Gears of War: E-Day (6 out.).",
      intro: "O mês do lançamento do Aion 2 em 5 de outubro não está vazio — é o contrário. A análise da Polygon de 30 de agosto descreve outubro de 2026 como uma janela possivelmente pior que setembro, porque as editoras anteciparam seus jogos para ficar longe de GTA 6 em novembro. Veja o que isso significa para um novo MMO que precisa brigar por atenção.",
      sourceNote: "Com base na análise da Polygon «October 2026 has way too many games trying to escape GTA 6» (30 de agosto de 2026), cruzado com a revista semanal de MMOs da Massively Overpowered (30 de agosto de 2026).",
      keywords: ["Aion 2 5 de outubro", "Aion 2 GTA 6", "janela de outubro 2026", "Aion 2 concorrência", "Aion 2 data de lançamento"],
      sections: [
        section("the-logjam", "Um mês pior que setembro", "A Polygon retirou o próprio aviso de setembro, dizendo que outubro «sem dúvida será pior»: datas de última hora deixam um mês «destinado a entrar para a história dos acúmulos». A primeira semana é «uma confusão generalizada». GTA 6 chega em novembro; as editoras julgaram setembro perto demais e empurraram tudo para outubro. Para um novo MMO, o dia 1 é uma prateleira cheia, não uma pista livre."),
        section("who-else-ships", "Quem mais lança na mesma semana", "O Aion 2 (5 de outubro) está cercado: Ace Combat 8: Wings of Theve (2 de outubro) e Gears of War: E-Day (6 de outubro) o flanqueiam, com Dynasty Warriors 3 Complete e Rayman Legends Retold no dia 1. O mês soma Dragon's Dogma 2: Dark Arisen (9), Call of Duty: Modern Warfare 4 (23), Final Fantasy Resonance (22), Phantom Blade Zero (29), Castlevania: Belmont's Curse (15) — cerca de duas dúzias de títulos. No lado MMO, a onda Gamescom inclui também Path of Exile 2 (1.0 em 11 de dezembro), então o público MMO de outubro não se divide com a versão completa do PoE 2."),
        section("why-ncsoft-picked-oct5", "Por que a NCSoft escolheu 5 de outubro", "A NCSoft não deu razão para a data. Leitura tática: 5 de outubro é cedo o bastante para ficar diante dos grandes de fim de mês e longe de GTA 6 em novembro, logo após o acesso antecipado dos packs Fundador em 30 de setembro. O teste de carga 17–18 de setembro serve de ensaio integrado. A Massively OP descreve uma rampa de marcos até 5 de outubro. Efeito prático: o Aion 2 divide a semana com pelo menos dois grandes jogos single-player."),
        section("what-it-means", "O que significa no lançamento", "Uma janela lotada eleva o custo do silêncio. Free-to-play baixa a barreira para um clique. Para a comunidade, o teste de carga gratuito (17–18 de setembro) é o momento de converter curiosidade em contas antes da multidão. Trate o calendário de outubro como volátil — a própria Polygon espera «atrasos de última hora»."),
        section("takeaway", "Conclusão", "O Aion 2 lança no mês mais movimentado de 2026, subproduto da indústria que desobstrui a pista para GTA 6 em novembro. Para os jogadores, a conclusão prática é o momento: use as vias gratuitas antes de 5 de outubro (teste de carga, solicitação do Steam Playtest) para decidir antes de começar o barulho do mês."),
      ],
    }),
    ru: articleCopy(newsLabels, "ru", 5, {
      eyebrow: "ОКНО РЕЛИЗОВ ОКТЯБРЯ 2026",
      title: "Aion 2 и лавина релизов октября 2026: почему все бегут от GTA 6",
      description: "Polygon сообщает, что октябрь 2026 — затор релизов: издатели выталкивают игры вперёд, до GTA 6 в ноябре. Aion 2 выходит 5 октября, в один месяц с примерно двумя десятками игр — включая Ace Combat 8 (2 окт.) и Gears of War: E-Day (6 окт.).",
      intro: "Месяц запуска Aion 2 5 октября не пуст — наоборот. Анализ Polygon от 30 августа описывает октябрь 2026 как окно, возможно, худшее, чем сентябрь, ведь издатели сдвинули релизы, чтобы уйти от GTA 6 в ноябре. Вот что это значит для новой MMO, которой приходится бороться за внимание.",
      sourceNote: "На основе анализа Polygon «October 2026 has way too many games trying to escape GTA 6» (30 августа 2026), сверено с еженедельником MMO Massively Overpowered (30 августа 2026).",
      keywords: ["Aion 2 5 октября", "Aion 2 GTA 6", "окно релизов октября 2026", "Aion 2 конкуренция", "Aion 2 дата выхода"],
      sections: [
        section("the-logjam", "Месяц хуже сентября", "Polygon отозвал собственное сентябрьское предупреждение, заявив, что октябрь «без сомнения будет хуже»: даты, объявленные в последний момент, оставили месяц, «обречённый войти в историю отставания». Первая неделя — «всеобщая свалка». GTA 6 выходит в ноябре; издатели сочли сентябрь слишком близким и всё вынесли в октябрь. Для новой MMO день 1 — это полная полка, а не свободная дорожка."),
        section("who-else-ships", "Кто ещё выходит на той же неделе", "Aion 2 (5 октября) окружён: Ace Combat 8: Wings of Theve (2 октября) и Gears of War: E-Day (6 октября) фланкируют его, плюс Dynasty Warriors 3 Complete и Rayman Legends Retold 1 октября. В месяце также Dragon's Dogma 2: Dark Arisen (9), Call of Duty: Modern Warfare 4 (23), Final Fantasy Resonance (22), Phantom Blade Zero (29), Castlevania: Belmont's Curse (15) — около двух десятков игр. В MMO-части волна Gamescom включает и Path of Exile 2 (1.0 11 декабря), так что октябрьская MMO-аудитория не делится с полной версией PoE 2."),
        section("why-ncsoft-picked-oct5", "Почему NCSoft выбрала 5 октября", "NCSoft не объяснила саму дату. Тактическое прочтение: 5 октября достаточно рано, чтобы опередить блокбастеры конца месяца и отойти от GTA 6 в ноябре, сразу после раннего доступа паков основателя 30 сентября. Стресс-тест 17–18 сентября служит встроенной репетицией. Massively OP описывает лестницу вех к 5 октября. Практический эффект: Aion 2 делит неделю минимум с двумя крупными синглплеерными релизами."),
        section("what-it-means", "Что это значит на запуске", "Загруженное окно повышает цену молчания. Free-to-play снижает барьер до одного клика. Для сообщества бесплатный стресс-тест (17–18 сентября) — момент превратить любопытство в аккаунты до толпы. Считайте октябрьский календарь волатильным — сам Polygon ждёт «задержек в последний момент»."),
        section("takeaway", "Вывод", "Aion 2 выходит в самый загруженный месяц 2026-го — побочный продукт индустрии, освобождающей дорогу для GTA 6 в ноябре. Для игроков практический вывод — тайминг: используйте бесплатные пути до 5 октября (стресс-тест, запрос Steam Playtest) и решите до начала шума месяца."),
      ],
    }),
    "zh-hant": articleCopy(newsLabels, "zh-hant", 5, {
      eyebrow: "2026 年 10 月發行窗口",
      title: "Aion 2 與 2026 年 10 月發行潮：為什麼大家都要躲開 GTA 6",
      description: "Polygon 報導稱 2026 年 10 月是一場發行壅塞——廠商搶在 11 月 GTA 6 之前集中上線。Aion 2 定於 10 月 5 日，與 Ace Combat 8（10/2）、Gears of War: E-Day（10/6）等約二十多款作品同月競爭。",
      intro: "Aion 2 定檔 10 月 5 日的這個月並不空曠，恰恰相反。Polygon 8 月 30 日的分析將 2026 年 10 月描述為一個可能比 9 月更糟的發行窗口，因為廠商紛紛搶在 11 月 GTA 6 之前提前發售。對一款上線首日就要爭奪注意力的新 MMO 而言，這正是它要面對的環境。",
      sourceNote: "基於 Polygon 的分析文章《2026 年 10 月有太多遊戲想逃離 GTA 6》（2026-08-30），並與 Massively Overpowered 的 MMO 週報（2026-08-30）報導的同一 Gamescom 發行日期浪潮交叉核對。",
      keywords: ["Aion 2 10月5日", "Aion 2 GTA 6", "2026年10月發行潮", "Aion 2 上線競爭", "Aion 2 發售日期"],
      sections: [
        section("the-logjam", "比 9 月更糟的一個月", "Polygon 收回自己此前的 9 月警告，稱 10 月「可以說更糟」：臨時敲定的發售日期留下了一個「注定載入遊戲史積壓榜」的月份。10 月第一週尤其「亂成一團」——最大的幾款遊戲都盡量趕在 GTA 6 之前。GTA 6 本身在 11 月到來；廠商判定 9 月的緩衝仍然太近，於是提前塞進 10 月。對新 MMO 來說，上線首日就是塞滿貨架的競爭。"),
        section("who-else-ships", "同一週還有誰", "Aion 2（10 月 5 日）身邊是重磅作品：Ace Combat 8: Wings of Theve（10 月 2 日）與 Gears of War: E-Day（10 月 6 日）在數天內夾擊，10 月 1 日還有《真三國無雙 3 完全版 重製》與 Rayman Legends Retold。整個月另有 Dragon's Dogma 2: Dark Arisen（10/9）、決勝時刻：現代戰爭 4（10/23）、Final Fantasy Resonance（10/22）、Phantom Blade Zero（10/29）與 Castlevania: Belmont's Curse（10/15），約二十餘款。MMO 方面，Gamescom 浪潮也包含 Path of Exile 2（1.0 於 12/11），因此 10 月 MMO 受眾不會與 PoE 2 正式版分流。"),
        section("why-ncsoft-picked-oct5", "NCSoft 為什麼選 10 月 5 日", "NCSoft 未公布對日期本身的解釋。策略性讀法：10 月 5 日足夠早，既趕在月末大作之前，又遠離 11 月的 GTA 6，同時緊隨 9 月 30 日創始人包搶先體驗之後。9 月 17–18 日的 Launch Scale Test 為上線前約三週的內建彩排。結果是：這一週 Aion 2 至少與兩款大型單人遊戲共享貨架。"),
        section("what-it-means", "對上線意味著什麼", "擁擠的窗口提高了沉默的成本。免費遊玩入口把試玩門檻降到一次點擊。對社群建設，免費的 Launch Scale Test（9 月 17–18 日）是在人群到來之前把好奇轉化為帳號的時刻。最後，把 10 月檔期視為易變：Polygon 自己預計會有「一些最後一刻的延期」，官方 Steam 商店頁才是最可信的基準。"),
        section("takeaway", "結論", "Aion 2 在 2026 年最擁擠的月份上線——這是整個行業為 GTA 6 在 11 月清出跑道而造成的副產品。對玩家，可操作的結論是時機：在 10 月 5 日之前使用免費渠道——Launch Scale Test 與 Steam Playtest 申請——在月份的噪音開始前做決定。"),
      ],
    }),
  },
};
