import {
  articleCopy,
  localizations,
  guideLabels,
  publishedVerified,
  section,
} from "./trending-september-5-shared";
import type { ContentSource, ContentHeroImage } from "./content-registry";

const officialMountSource: ContentSource = {
  id: "ncsoft-mount-guide",
  kind: "official",
  publisher: "NCSoft",
  label: "AION 2 Official Guide — Mounts and Movement",
  url: "https://aion2.plaync.com/en-us/game/guide/mount",
  publishedAt: "2026-08-20",
  retrievedAt: "2026-09-05",
  verifiedAt: "2026-09-05",
  localizations: localizations(
    {
      "zh-hans": "AION 2 官方指南 — 坐骑与移动", en: "AION 2 Official Guide — Mounts and Movement", fr: "Guide officiel d'AION 2 — Montures et déplacement",
      de: "AION 2 Offizieller Leitfaden — Reittiere und Bewegung", es: "Guía oficial de AION 2 — Monturas y movimiento", ja: "AION 2 公式ガイド — マウントと移動",
      "pt-br": "Guia oficial do AION 2 — Montarias e movimento", ru: "Официальное руководство AION 2 — Маунты и перемещение", ko: "AION 2 공식 가이드 — 마운트 및 이동", "zh-hant": "AION 2 官方指南 — 坐騎與移動",
    },
    "https://aion2.plaync.com/en-us/game/guide/mount",
  ),
};

const communityMountSource: ContentSource = {
  id: "aion2t-mount-collection-guide",
  kind: "third-party",
  publisher: "AION2T",
  label: "AION 2 Mount Guide: All Mount Types, Speeds, and How to Get Them",
  url: "https://aion2t.com/guides/mount-collection-guide/",
  publishedAt: "2026-09-01",
  retrievedAt: "2026-09-05",
  verifiedAt: "2026-09-05",
  localizations: localizations(
    {
      "zh-hans": "AION 2 坐骑指南：所有坐骑类型、速度及获取方式", en: "AION 2 Mount Guide: All Mount Types, Speeds, and How to Get Them", fr: "Guide des montures d'AION 2 : Tous les types, vitesses et comment les obtenir",
      de: "AION 2 Reittier-Leitfaden: Alle Typen, Geschwindigkeiten und wie man sie bekommt", es: "Guía de monturas de AION 2: Todos los tipos, velocidades y cómo obtenerlas", ja: "AION 2 マウントガイド：全タイプ、速度、入手方法",
      "pt-br": "Guia de montarias do AION 2: Todos os tipos, velocidades e como obtê-las", ru: "Руководство по маунтам AION 2: Все типы, скорости и как их получить", ko: "AION 2 마운트 가이드: 모든 유형, 속도 및 획득 방법", "zh-hant": "AION 2 坐騎指南：所有坐騎類型、速度及獲取方式",
    },
    "https://aion2t.com/guides/mount-collection-guide/",
  ),
};

const hero: ContentHeroImage = {
  src: "https://blogfiles.ncsoft.net/news/af7330da-4ff6-4b58-aece-400e6061a3be.jpg",
  width: 1200, height: 630, credit: "NC Corporation",
  sourceUrl: "https://aion2.plaync.com/en-us/game/guide/mount",
  rights: "linked-official-media",
  translations: {
    "zh-hans": { alt: "AION 2 坐骑与移动系统指南", caption: "完整坐骑系统、翅膀滑翔与快速旅行指南。" },
    en: { alt: "AION 2 Mounts and Movement System Guide", caption: "Complete mount system, wing gliding, and fast travel guide." },
    fr: { alt: "Guide des montures et système de déplacement d'AION 2", caption: "Guide complet des montures, vol plané et voyage rapide." },
    de: { alt: "AION 2 Reittiere und Bewegungssystem-Leitfaden", caption: "Vollständiger Leitfaden für Reittiere, Gleitflug und Schnellreise." },
    es: { alt: "Guía de monturas y sistema de movimiento de AION 2", caption: "Guía completa de monturas, planeo y viaje rápido." },
    ja: { alt: "AION 2 マウント・移動システムガイド", caption: "マウントシステム、翼滑空、ファストトラベル完全ガイド。" },
    "pt-br": { alt: "Guia de montarias e sistema de movimento do AION 2", caption: "Guia completo de montarias, planagem e viagem rápida." },
    ru: { alt: "Руководство по маунтам и системе перемещения AION 2", caption: "Полное руководство по маунтам, планированию и быстрому перемещению." },
    ko: { alt: "AION 2 마운트 및 이동 시스템 가이드", caption: "마운트 시스템, 날개 글라이딩, 빠른 이동 완전 가이드." },
    "zh-hant": { alt: "AION 2 坐騎與移動系統指南", caption: "完整坐騎系統、翅膀滑翔與快速旅行指南。" },
  },
};

export const trendingSeptember5Article5 = {
  section: "guides" as const,
  slug: "aion-2-mounts-movement-travel-guide",
  schemaType: "Article" as const,
  publishedAt: "2026-09-05", updatedAt: "2026-09-05",
  readingMinutes: 8,
  publication: publishedVerified,
  sources: [officialMountSource, communityMountSource],
  heroImage: hero,
  related: [
    { kind: "content" as const, section: "guides" as const, slug: "aion-2-solo-leveling-guide-40-cap" },
    { kind: "content" as const, section: "guides" as const, slug: "aion-2-system-requirements-pc-optimization-guide" },
    { kind: "content" as const, section: "guides" as const, slug: "aion-2-endgame-progression-roadmap" },
  ],
  translations: {
    "zh-hans": articleCopy(guideLabels, "zh-hans", 8, {
      eyebrow: "移动指南",
      title: "AION 2 坐骑与移动系统完整指南：地面坐骑、翅膀滑翔与快速旅行",
      description: "全面解析AION 2的移动系统：地面坐骑获取与升级、翅膀系统滑翔机制、传送网络使用技巧、以及各区域最佳移动路线",
      intro: "AION 2的世界广阔而壮丽，高效的移动系统能让你更好地探索这个世界。本文全面解析坐骑、翅膀和传送三大移动方式，帮助你节省时间、不错过风景。",
      keywords: ["AION 2 坐骑", "AION 2 翅膀", "AION 2 快速旅行", "AION 2 传送", "AION 2 移动速度"],
      sourceNote: "基于 NCSoft 官方坐骑指南和 AION2T 坐骑收集攻略（2026-09-01）整理。",
      sections: [
        section("ground-mounts", "地面坐骑", "15级解锁第一个地面坐骑。坐骑分为普通（+100%速度）、高级（+150%速度）和传说（+200%速度）三个等级。获取方式：任务奖励（起始坐骑）、副本掉落、拍卖行购买、商城购买。坐骑可以升级——每次升级需要坐骑口粮和金币。传说坐骑还有独特的外观特效。建议：前期使用任务赠送的普通坐骑即可，中期通过副本积攒材料升级到高级坐骑。"),
        section("wing-system", "翅膀滑翔系统", "翅膀是AION 2标志性的移动方式。翅膀允许从高处起飞后进行长距离滑翔，大幅缩短山地和悬崖区域的旅行时间。翅膀在20级解锁基础版本。翅膀有耐久度——长时间滑翔会消耗耐久，需要定期修复。高级翅膀提供更长的滑翔距离和更慢的下沉速度。翅膀外观也是重要的个性化元素——通过深渊PVP和副本可获得独特翅膀。"),
        section("teleport-network", "传送网络", "AION 2有完善的传送网络：主城传送点（免费）、野外传送碑（消耗少量金币）、公会传送（公会技能）。10级后在每个新区域发现的第一个传送碑应立刻激活。传送费用随距离增加——跨大陆传送较贵，同区域内便宜。建议：在主要城市设置'家'——减少传送费用；利用公会传送节省长途旅行开支。"),
        section("movement-combos", "移动组合技巧", "最高效的长途旅行组合：传送到目标区域附近→坐骑冲刺→翅膀滑翔到达精确位置。中距离移动：坐骑为主，遇到山地/河流切换翅膀滑翔。短距离：跑步即可（坐骑有召唤延迟约3秒）。PVP区域注意：坐骑在战斗中无法使用，翅膀滑翔是脱战后最快的脱身方式。"),
        section("mount-collection", "坐骑收集指南", "AION 2有30+种坐骑可供收集。获取途径分类：任务奖励（约10种）、副本Boss掉落（约8种）、深渊PVP奖励（约5种）、成就系统（约4种）、商城/活动（约5种）。稀有坐骑如飞行龙和凤凰需要大量时间和运气。建议：优先收集功能性坐骑（速度最快的地面坐骑）——外观坐骑可以慢慢积攒。", ),
      ],
    }),
    en: articleCopy(guideLabels, "en", 8, {
      eyebrow: "MOVEMENT GUIDE",
      title: "AION 2 Mounts and Movement System Complete Guide: Ground Mounts, Wing Gliding, and Fast Travel",
      description: "Full analysis of AION 2's movement system: ground mount acquisition and upgrades, wing system gliding mechanics, teleport network tips, and best movement routes per zone",
      intro: "AION 2's world is vast and magnificent — an efficient movement system lets you explore it better. This article fully analyzes mounts, wings, and teleportation — the three major movement methods — to help you save time and not miss the scenery.",
      keywords: ["AION 2 mounts", "AION 2 wings", "AION 2 fast travel", "AION 2 teleport", "AION 2 movement speed"],
      sourceNote: "Based on NCSoft's official mount guide and AION2T mount collection guide (September 1, 2026).",
      sections: [
        section("ground-mounts", "Ground Mounts", "Unlock your first ground mount at level 15. Mounts come in three tiers: Normal (+100% speed), Advanced (+150% speed), and Legendary (+200% speed). Acquisition: quest rewards (starter mount), dungeon drops, auction house, cash shop. Mounts can be upgraded — each upgrade requires mount feed and gold. Legendary mounts have unique visual effects. Tip: use the quest-given normal mount early, upgrade to advanced through dungeon materials mid-game."),
        section("wing-system", "Wing Gliding System", "Wings are AION 2's iconic movement method. Wings allow long-distance gliding after launching from heights, greatly reducing travel time in mountainous and cliff areas. Unlock basic wings at level 20. Wings have durability — prolonged gliding consumes durability, requiring periodic repair. Advanced wings provide longer glide distance and slower descent. Wing appearances are also key customization — obtain unique wings through Abyss PVP and dungeons."),
        section("teleport-network", "Teleport Network", "AION 2 has a comprehensive teleport network: city teleport points (free),野外 teleport monuments (small gold cost), guild teleport (guild skill). After level 10, activate the first teleport monument you discover in each new zone immediately. Teleport costs increase with distance — cross-continental is expensive, same-zone is cheap. Tip: set your 'home' in a major city to reduce teleport costs; use guild teleports to save on long-distance travel."),
        section("movement-combos", "Movement Combo Tips", "Most efficient long-distance combo: teleport near target zone → mount sprint → wing glide to precise location. Medium distance: mount primary, switch to wing gliding over mountains/rivers. Short distance: running is fine (mounts have ~3 second summon delay). PVP zone note: mounts cannot be used in combat; wing gliding is the fastest post-combat escape method."),
        section("mount-collection", "Mount Collection Guide", "AION 2 has 30+ mounts to collect. Acquisition categories: quest rewards (~10), dungeon boss drops (~8), Abyss PVP rewards (~5), achievement system (~4), cash shop/events (~5). Rare mounts like flying dragons and phoenixes require significant time and luck. Tip: prioritize functional mounts (fastest ground mount) first — cosmetic mounts can be collected gradually."),
      ],
    }),
    fr: articleCopy(guideLabels, "fr", 8, {
      eyebrow: "GUIDE DE DÉPLACEMENT",
      title: "Guide complet des montures et système de déplacement d'AION 2 : Montures terrestres, vol plané et voyage rapide",
      description: "Analyse complète du système de déplacement : montures terrestres, ailes, téléportation",
      intro: "Le monde d'AION 2 est vaste — un système de déplacement efficace permet de mieux l'explorer.",
      keywords: ["Montures AION 2", "Ailes AION 2", "Voyage rapide AION 2", "Téléportation AION 2", "Vitesse AION 2"],
      sourceNote: "Basé sur le guide officiel NCSoft et le guide de collection de montures d'AION2T (1er septembre 2026).",
      sections: [
        section("ground-mounts", "Montures terrestres", "Débloquer au niveau 15. Trois niveaux : Normal (+100%), Avancé (+150%), Légendaire (+200%)."),
        section("wing-system", "Système de vol plané", "Les ailes permettent le vol à longue distance depuis les hauteurs. Débloquer au niveau 20. Durabilité à gérer."),
        section("teleport-network", "Réseau de téléportation", "Points de téléportation gratuits en ville, monuments野外 contre or, téléportation de guilde."),
        section("movement-combos", "Combos de déplacement", "Longue distance : téléportation + monture + ailes. Moyenne : monture + ailes. Courte : course."),
        section("mount-collection", "Guide de collection", "30+ montures. Quêtes (~10), donjons (~8), PVP (~5), succès (~4), boutique (~5)."),
      ],
    }),
    de: articleCopy(guideLabels, "de", 8, {
      eyebrow: "BEWEGUNGSLEITFADEN",
      title: "AION 2 Reittiere und Bewegungssystem Kompletter Leitfaden: Bodenreittiere, Gleitflug und Schnellreise",
      description: "Vollständige Analyse des Bewegungssystems: Bodenreittiere, Flügel, Teleportation",
      intro: "AION 2s Welt ist weit — ein effizientes Bewegungssystem ermöglicht bessere Erkundung.",
      keywords: ["Reittiere AION 2", "Flügel AION 2", "Schnellreise AION 2", "Teleportation AION 2", "Geschwindigkeit AION 2"],
      sourceNote: "Basierend auf NCSofts offiziellem Reittier-Leitfaden und AION2T-Sammelleitfaden (1. September 2026).",
      sections: [
        section("ground-mounts", "Bodenreittiere", "Ab Stufe 15 freischaltbar. Drei Stufen: Normal (+100%), Fortgeschritten (+150%), Legendär (+200%)."),
        section("wing-system", "Gleitflugsystem", "Flügel ermöglichen Langstreckengleiten von Höhen. Ab Stufe 20. Haltbarkeit beachten."),
        section("teleport-network", "Teleportationsnetzwerk", "Kostenlose Stadtpunkte,野外-Denkmäler gegen Gold, Gildenteleportation."),
        section("movement-combos", "Bewegungs-Kombos", "Lang: Teleport + Reittier + Flügel. Mittel: Reittier + Flügel. Kurz: Laufen."),
        section("mount-collection", "Sammlungsleitfaden", "30+ Reittiere. Quests (~10), Dungeons (~8), PVP (~5), Erfolge (~4), Shop (~5)."),
      ],
    }),
    es: articleCopy(guideLabels, "es", 8, {
      eyebrow: "GUÍA DE MOVIMIENTO",
      title: "Guía completa de monturas y sistema de movimiento de AION 2: Monturas terrestres, planeo y viaje rápido",
      description: "Análisis completo del sistema de movimiento: monturas terrestres, alas, teletransporte",
      intro: "El mundo de AION 2 es vasto — un sistema de movimiento eficiente permite mejor exploración.",
      keywords: ["Monturas AION 2", "Alas AION 2", "Viaje rápido AION 2", "Teletransporte AION 2", "Velocidad AION 2"],
      sourceNote: "Basado en la guía oficial de NCSoft y guía de colección de monturas de AION2T (1 de septiembre de 2026).",
      sections: [
        section("ground-mounts", "Monturas terrestres", "Desbloquear en nivel 15. Tres niveles: Normal (+100%), Avanzada (+150%), Legendaria (+200%)."),
        section("wing-system", "Sistema de planeo", "Las alas permiten planeo de larga distancia desde alturas. Desbloquear en nivel 20. Durabilidad."),
        section("teleport-network", "Red de teletransporte", "Puntos gratuitos en ciudades, monumentos野外 por oro, teletransporte de hermandad."),
        section("movement-combos", "Combos de movimiento", "Larga: teletransporte + montura + alas. Media: montura + alas. Corta: correr."),
        section("mount-collection", "Guía de colección", "30+ monturas. Misiones (~10), mazmorras (~8), PVP (~5), logros (~4), tienda (~5)."),
      ],
    }),
    ja: articleCopy(guideLabels, "ja", 8, {
      eyebrow: "移動ガイド",
      title: "AION 2 マウント・移動システム完全ガイド：地上マウント、翼滑空、ファストトラベル",
      description: "移動システムの完全分析：地上マウント、翼、テレポート",
      intro: "AION 2の世界は広大 — 効率的な移動システムがより良い探索を可能にします。",
      keywords: ["AION 2 マウント", "AION 2 翼", "AION 2 ファストトラベル", "AION 2 テレポート", "AION 2 移動速度"],
      sourceNote: "NCSoft公式マウントガイドおよびAION2Tコレクションガイド（2026年9月1日）に基づく。",
      sections: [
        section("ground-mounts", "地上マウント", "レベル15で解放。3段階：通常（+100%）、上級（+150%）、伝説（+200%）。"),
        section("wing-system", "翼滑空システム", "翼は高度から長距離滑空を可能にする。レベル20で解放。耐久度に注意。"),
        section("teleport-network", "テレポートネットワーク", "都市の無料ポイント、野外モニュメント（ゴールド）、ギルドテレポート。"),
        section("movement-combos", "移動コンボ", "長距離：テレポート+マウント+翼。中距離：マウント+翼。短距離：走り。"),
        section("mount-collection", "コレクションガイド", "30+マウント。クエスト（~10）、ダンジョン（~8）、PVP（~5）、実績（~4）、ショップ（~5）。"),
      ],
    }),
    "pt-br": articleCopy(guideLabels, "pt-br", 8, {
      eyebrow: "GUIA DE MOVIMENTO",
      title: "Guia completo de montarias e sistema de movimento do AION 2: Montarias terrestres, planagem e viagem rápida",
      description: "Análise completa do sistema de movimento: montarias terrestres, asas, teletransporte",
      intro: "O mundo do AION 2 é vasto — um sistema de movimento eficiente permite melhor exploração.",
      keywords: ["Montarias AION 2", "Asas AION 2", "Viagem rápida AION 2", "Teletransporte AION 2", "Velocidade AION 2"],
      sourceNote: "Baseado no guia oficial da NCSoft e guia de coleção de montarias do AION2T (1 de setembro de 2026).",
      sections: [
        section("ground-mounts", "Montarias terrestres", "Desbloquear no nível 15. Três níveis: Normal (+100%), Avançada (+150%), Lendária (+200%)."),
        section("wing-system", "Sistema de planagem", "Asas permitem planagem de longa distância a partir de alturas. Desbloquear no nível 20. Durabilidade."),
        section("teleport-network", "Rede de teletransporte", "Pontos gratuitos nas cidades, monumentos野外 por ouro, teletransporte de guilda."),
        section("movement-combos", "Combos de movimento", "Longa: teletransporte + montaria + asas. Média: montaria + asas. Curta: correr."),
        section("mount-collection", "Guia de coleção", "30+ montarias. Missões (~10), masmorras (~8), PVP (~5), conquistas (~4), loja (~5)."),
      ],
    }),
    ru: articleCopy(guideLabels, "ru", 8, {
      eyebrow: "РУКОВОДСТВО ПО ПЕРЕМЕЩЕНИЮ",
      title: "Полное руководство по маунтам и системе перемещения AION 2: Наземные маунты, планирование и быстрое перемещение",
      description: "Полный анализ системы перемещения: наземные маунты, крылья, телепортация",
      intro: "Мир AION 2 обширен — эффективная система перемещения позволяет лучше исследовать.",
      keywords: ["Маунты AION 2", "Крылья AION 2", "Быстрое перемещение AION 2", "Телепортация AION 2", "Скорость AION 2"],
      sourceNote: "На основе официального руководства NCSoft и руководства по коллекции маунтов AION2T (1 сентября 2026 г.).",
      sections: [
        section("ground-mounts", "Наземные маунты", "Разблокировка на 15 уровне. Три уровня: Обычный (+100%), Продвинутый (+150%), Легендарный (+200%)."),
        section("wing-system", "Система планирования", "Крылья позволяют планировать на длинные дистанции с высот. Разблокировка на 20 уровне. Прочность."),
        section("teleport-network", "Сеть телепортации", "Бесплатные точки в городах,野外 памятники за золото, гильдейская телепортация."),
        section("movement-combos", "Комбо перемещения", "Длинные: телепортация + маунт + крылья. Средние: маунт + крылья. Короткие: бег."),
        section("mount-collection", "Руководство по коллекции", "30+ маунтов. Квесты (~10), подземелья (~8), PVP (~5), достижения (~4), магазин (~5)."),
      ],
    }),
    ko: articleCopy(guideLabels, "ko", 8, {
      eyebrow: "이동 가이드",
      title: "AION 2 마운트 및 이동 시스템 완전 가이드: 지상 마운트, 날개 글라이딩, 빠른 이동",
      description: "이동 시스템의 완전한 분석: 지상 마운트, 날개 시스템 활공 메커니즘, 텔레포트 네트워크 사용 팁, 각 구역별 최적 이동 경로",
      intro: "AION 2의 세계는 광대하고 장엄합니다. 효율적인 이동 시스템은 이 세계를 더 잘 탐험할 수 있게 해줍니다. 본 기사는 마운트, 날개, 텔레포트 3대 이동 방식을 완전 분석하여 시간을 절약하고 풍경을 놓치지 않도록 도와드립니다.",
      keywords: ["AION 2 마운트", "AION 2 날개", "AION 2 빠른 이동", "AION 2 텔레포트", "AION 2 이동 속도"],
      sourceNote: "NCSoft 공식 마운트 가이드 및 AION2T 마운트 컬렉션 가이드(2026-09-01) 기반.",
      sections: [
        section("ground-mounts", "지상 마운트", "15레벨에 첫 지상 마운트 해제. 마운트는 일반(+100% 속도), 고급(+150% 속도), 전설(+200% 속도) 3단계. 획득 방법: 퀘스트 보상(초기 마운트), 던전 드롭, 경매장 구매, 캐시샵 구매. 마운트는 업그레이드 가능 — 업그레이드마다 마운트 사료와 골드 필요. 전설 마운트는 고유 외형 이펙트. 팁: 초반에는 퀘스트 제공 일반 마운트 사용, 중반에 던전 재료로 고급 마운트로 업그레이드."),
        section("wing-system", "날개 글라이딩 시스템", "날개는 AION 2의 상징적인 이동 방식입니다. 날개는 높은 곳에서 이륙한 후 장거리 활공을 허용하여 산지와 절벽 지역의 이동 시간을 대폭 단축합니다. 20레벨에 기본 버전 해제. 날개는 내구도 있음 — 장시간 활공은 내구도를 소모하므로 정기 수리 필요. 고급 날개는 더 긴 활공 거리와 더 느린 하강 속도 제공. 날개 외형도 중요한 커스터마이징 요소 — 심연 PVP와 던전에서 고유 날개 획득 가능."),
        section("teleport-network", "텔레포트 네트워크", "AION 2는 완벽한 텔레포트 네트워크가 있음: 본_city 텔레포트 지점(무료), 야외 텔레포트 비석(소량 골드 소모), 길드 텔레포트(길드 스킬). 10레벨 후 각 새 지역에서 처음 발견한 텔레포트 비석을 즉시 활성화. 텔레포트 비용은 거리에 따라 증가 — 대륙 간은 비싸고, 동일 지역 내는 저렴. 팁: 주요 도시에 '집' 설정 — 텔레포트 비용 절감; 길드 텔레포트로 장거리 이동비 절약."),
        section("movement-combos", "이동 조합 팁", "가장 효율적인 장거리 이동 조합: 목표 지역 근처로 텔레포트 → 마운트 질주 → 날개 활공으로 정확한 위치 도달. 중거리 이동: 마운트 위주, 산지/하천 만나면 날개 활공으로 전환. 단거리: 달리기면 충분(마운트는 소환 지연 약 3초). PVP 지역 주의: 전투 중에는 마운트 사용 불가, 날개 활공은 전투 후 가장 빠른 탈출 방법."),
        section("mount-collection", "마운트 컬렉션 가이드", "AION 2에는 30종 이상의 마운트가 있음. 획득 경로 분류: 퀘스트 보상(약 10종), 던전 보스 드롭(약 8종), 심연 PVP 보상(약 5종), 업적 시스템(약 4종), 캐시샵/이벤트(약 5종). 비행룡과 봉황 같은 희귀 마운트는 많은 시간과 운이 필요. 팁: 기능적 마운트(가장 빠른 지상 마운트) 우선 수집 — 외형 마운트는 천천히 모으면 됨."),
      ],
    }),
    "zh-hant": articleCopy(guideLabels, "zh-hant", 8, {
      eyebrow: "移動指南",
      title: "AION 2 坐騎與移動系統完整指南：地面坐騎、翅膀滑翔與快速旅行",
      description: "全面解析AION 2的移動系統：地面坐騎獲取與升級、翅膀系統滑翔機制、傳送網絡使用技巧、以及各區域最佳移動路線",
      intro: "AION 2的世界廣闊而壯麗，高效的移動系統能讓你更好地探索這個世界。本文全面解析坐騎、翅膀和傳送三大移動方式，幫助你節省時間、不錯過風景。",
      keywords: ["AION 2 坐騎", "AION 2 翅膀", "AION 2 快速旅行", "AION 2 傳送", "AION 2 移動速度"],
      sourceNote: "基於 NCSoft 官方坐騎指南和 AION2T 坐騎收集攻略（2026-09-01）整理。",
      sections: [
        section("ground-mounts", "地面坐騎", "15級解鎖第一個地面坐騎。坐騎分為普通（+100%速度）、高級（+150%速度）和傳說（+200%速度）三個等級。獲取方式：任務獎勵（起始坐騎）、副本掉落、拍賣行購買、商城購買。坐騎可以升級——每次升級需要坐騎口糧和金幣。傳說坐騎還有獨特的外觀特效。建議：前期使用任務贈送的普通坐騎即可，中期通過副本積攢材料升級到高級坐騎。"),
        section("wing-system", "翅膀滑翔系統", "翅膀是AION 2標誌性的移動方式。翅膀允許從高處起飛後進行長距離滑翔，大幅縮短山地和懸崖區域的旅行時間。翅膀在20級解鎖基礎版本。翅膀有耐久度——長時間滑翔會消耗耐久，需要定期修復。高級翅膀提供更長的滑翔距離和更慢的下沉速度。翅膀外觀也是重要的個性化元素——通過深淵PVP和副本可獲得獨特翅膀。"),
        section("teleport-network", "傳送網絡", "AION 2有完善的傳送網絡：主城傳送點（免費）、野外傳送碑（消耗少量金幣）、公會傳送（公會技能）。10級後在每個新區域發現的第一個傳送碑應立刻激活。傳送費用隨距離增加——跨大陸傳送較貴，同區域內便宜。建議：在主要城市設置'家'——減少傳送費用；利用公會傳送節省長途旅行開支。"),
        section("movement-combos", "移動組合技巧", "最高效的長途旅行組合：傳送到目標區域附近→坐騎衝刺→翅膀滑翔到達精確位置。中距離移動：坐騎為主，遇到山地/河流切換翅膀滑翔。短距離：跑步即可（坐騎有召喚延遲約3秒）。PVP區域注意：坐騎在戰鬥中無法使用，翅膀滑翔是脫戰後最快的脫身方式。"),
        section("mount-collection", "坐騎收集指南", "AION 2有30+種坐騎可供收集。獲取途徑分類：任務獎勵（約10種）、副本Boss掉落（約8種）、深淵PVP獎勵（約5種）、成就系統（約4種）、商城/活動（約5種）。稀有坐騎如飛行龍和鳳凰需要大量時間和運氣。建議：優先收集功能性坐騎（速度最快的地面坐騎）——外觀坐騎可以慢慢積攢。"),
      ],
    }),
  },
};
