import { articleCopy, localizations, newsLabels, publishedVerified, section } from "./trending-september-12-shared";
import type { ContentEntry, ContentHeroImage, ContentSource } from "./content-registry";

/* ARTICLE 1 — NC permanently restricts 11 piloting (대리 게임) organization accounts after Snowfield of Sorrow; 9 commissioning accounts hit with 30-day bans */

const gametocSource: ContentSource = {
  id: "gametoc-aion2-piloting-bans-2026-09-10",
  kind: "third-party",
  publisher: "GameToc (게임톡)",
  label: "Aion 2 Permanently Restricts 'Snowfield of Sorrow' Piloting Organizations",
  url: "https://www.gametoc.co.kr/news/articleView.html?idxno=111377",
  publishedAt: "2026-09-10",
  retrievedAt: "2026-09-12",
  verifiedAt: "2026-09-12",
  localizations: localizations({
    "zh-hans": "Aion 2 对『Snowfield of Sorrow』代练组织永久封禁",
    en: "Aion 2 Permanently Restricts 'Snowfield of Sorrow' Piloting Organizations",
    fr: "Aion 2 restreint définitivement les organisations de pilotage de « Snowfield of Sorrow »",
    de: "Aion 2 sperrt Piloten-Organisationen von „Snowfield of Sorrow“ dauerhaft",
    es: "Aion 2 restringe permanentemente a las organizaciones de pilotaje de «Snowfield of Sorrow»",
    ja: "Aion 2「Snowfield of Sorrow」の代行組織を永久利用制限",
    "pt-br": "Aion 2 restringe permanentemente organizações de pilotagem de 'Snowfield of Sorrow'",
    ru: "Aion 2 навсегда ограничивает организации по пилотингу «Snowfield of Sorrow»",
    ko: "아이온2 '비탄의 설원' 대리 게임 조직 영구 이용제한",
    "zh-hant": "Aion 2 對『Snowfield of Sorrow』代練組織永久封禁",
  }, "https://www.gametoc.co.kr/news/articleView.html?idxno=111377"),
};

const ncNoticeSource: ContentSource = {
  id: "aion2-official-piloting-notice-2026-09-10",
  kind: "official",
  publisher: "NC Corporation",
  label: "AION 2 Notice: Sanctions for Accounts Violating the Piloting Operation Policy",
  url: "https://aion2.plaync.com/ko-kr/board/notice/list",
  publishedAt: "2026-09-10",
  retrievedAt: "2026-09-12",
  verifiedAt: "2026-09-12",
  localizations: localizations({
    "zh-hans": "AION 2 公告：对违反代练运营政策的账户的制裁说明",
    en: "AION 2 Notice: Sanctions for Accounts Violating the Piloting Operation Policy",
    fr: "AION 2 : sanctions pour les comptes en violation de la politique de pilotage",
    de: "AION 2: Maßnahmen gegen Konten, die gegen die Pilotierungsrichtlinie verstoßen",
    es: "AION 2: sanciones para cuentas que violan la política de pilotaje",
    ja: "AION 2 告知：代行運営ポリシー違反アカウントへの制裁",
    "pt-br": "AION 2: sanções para contas que violam a política de pilotagem",
    ru: "AION 2: меры против аккаунтов, нарушивших политику пилотинга",
    ko: "AION 2 공지: 대리 게임 운영정책 위반 계정에 대한 제재 안내",
    "zh-hant": "AION 2 公告：對違反代練營運政策的帳戶之制裁說明",
  }, "https://aion2.plaync.com/ko-kr/board/notice/list"),
};

const pHero: ContentHeroImage = {
  src: "https://blogfiles.ncsoft.net/news/af7330da-4ff6-4b58-aece-400e6061a3be.jpg",
  width: 1200, height: 630,
  credit: "NC Corporation",
  sourceUrl: "https://aion2.plaync.com/en-us/",
  rights: "linked-official-media",
  translations: {
    "zh-hans": { alt: "Aion 2 代练组织封禁新闻横幅", caption: "NC 在 9/9 副本上线两天后即出手：11 个商业化代练组织角色被永久封禁、9 个委托代练的用户被处 30 天限制，并一律剥夺『Snowfield of Sorrow』首杀竞速事件资格。" },
    en: { alt: "Aion 2 piloting crackdown news banner", caption: "Two days after the September 9 raid launch, NC permanently banned 11 commercial piloting organization characters, handed 9 commissioning players 30-day restrictions, and stripped all of them of eligibility for the Snowfield of Sorrow first-clear event." },
    fr: { alt: "Bannière d'actualité de la répression du pilotage d'Aion 2", caption: "Deux jours après le raid du 9 septembre, NC a banni définitivement 11 personnages d'organisations de pilotage, imposé 30 jours à 9 joueurs commanditaires et privé tous de l'événement de premier clear." },
    de: { alt: "News-Banner zur Piloten-Razzia in Aion 2", caption: "Zwei Tage nach dem Raid-Start am 9. September sperrte NC 11 Charaktere kommerzieller Piloten-Organisationen dauerhaft, belegte 9 Auftraggeber mit 30 Tagen und entzog allen die Teilnahme am Erst-Clear-Event." },
    es: { alt: "Banner de noticias de la represión del pilotaje de Aion 2", caption: "Dos días después del raid del 9 de septiembre, NC baneó permanentemente a 11 personajes de organizaciones de pilotaje, sancionó con 30 días a 9 comitentes y les retiró la elegibilidad del evento de primer clear." },
    ja: { alt: "Aion 2 代行組織取締ニュースバナー", caption: "9月9日のレイド実装から2日後、NCは商業代行組織の11キャラを永久利用制限、依頼した9ユーザーを30日間制限し、全員から初クリアレースの参加資格を剥奪しました。" },
    "pt-br": { alt: "Banner de notícias da repressão à pilotagem do Aion 2", caption: "Dois dias após o raid de 9 de setembro, a NC baniu permanentemente 11 personagens de organizações de pilotagem, aplicou 30 dias a 9 comitentes e removeu a elegibilidade de todos no evento do primeiro clear." },
    ru: { alt: "Баннер новостей о борьбе с пилотингом в Aion 2", caption: "Через два дня после рейда 9 сентября NC навсегда забанила 11 персонажей коммерческих пилот-организаций, дала 9 заказчикам по 30 дней и лишила всех права участвовать в гонке первого клира." },
    ko: { alt: "Aion 2 대리 게임 조직 제재 뉴스 배너", caption: "9월 9일 레이드 출시 이틀 만에 NC가 영리 대리 조직 캐릭터 11개를 영구 이용제한하고, 대리를 맡긴 이용자 9개에 30일 제한을 적용했으며 모두의 '비탄의 설원' 최초 토벌 이벤트 참여 권한을 박탈했습니다." },
    "zh-hant": { alt: "Aion 2 代練組織封禁新聞橫幅", caption: "NC 在 9/9 副本上線兩天後即出手：11 個商業化代練組織角色被永久封禁、9 個委託代練的使用者被處 30 天限制，並一律剝奪『Snowfield of Sorrow』首殺競速事件資格。" },
  },
};

export const trendingSeptember12Article1: ContentEntry = {
  section: "news",
  slug: "aion-2-piloting-crackdown-permanent-bans",
  schemaType: "NewsArticle",
  publishedAt: "2026-09-12",
  updatedAt: "2026-09-12",
  readingMinutes: 6,
  publication: publishedVerified,
  sources: [gametocSource, ncNoticeSource],
  heroImage: pHero,
  related: [
    { kind: "content", section: "news", slug: "aion-2-snowfield-of-sorrow-first-clear" },
    { kind: "content", section: "guides", slug: "aion-2-snowfield-of-sorrow-farming-guide" },
    { kind: "content", section: "guides", slug: "aion-2-september-events-daeva-pass-guide" },
    { kind: "content", section: "guides", slug: "aion-2-no-autoplay-anti-grind-design-guide" },
  ],
  translations: {
    en: articleCopy(newsLabels, "en", 6, {
      eyebrow: "ENFORCEMENT",
      title: "Aion 2 Permanently Bans 11 Piloting Organizations After Snowfield of Sorrow Launch; 9 Commissioning Players Restricted for 30 Days",
      description: "Two days after the raid opened, NC permanently banned 11 characters from commercial piloting organizations and handed 30-day restrictions to 9 players who commissioned the service, stripping both from the first-clear event",
      intro: "NCsoft moved fast against paid raid-boosting: on September 10 it posted the first piloting-policy sanction notice, permanently restricting 11 characters that ran commercial piloting (대리 게임) organizations clearing Snowfield of Sorrow for profit, and applying 30-day restrictions to 9 players who commissioned the service. All 20 also lost eligibility for the first-clear event.",
      sourceNote: "Based on GameToc's September 10, 2026 report and NCsoft's official notice on the Aion 2 notice board (both retrieved September 12, 2026). Sanctions apply to the Korean service; the policy context also applies to the global version launching October 5.",
      keywords: ["Aion 2 piloting ban", "Aion 2 대리 게임 permanent restriction", "Aion 2 Snowfield of Sorrow boosting crackdown", "Aion 2 account boosting policy", "Aion 2 first clear event eligibility ban"],
      sections: [
        section("the-ban", "11 Piloting Organizations, Permanently Banned", ["NCsoft posted the sanction notice on the official board on September 10 — two days after the Snowfield of Sorrow update. The 11 permanently restricted characters belonged to organizations that commercially provided, promoted, and brokered raid clears for profit.", "The crackdown follows a policy that was explicitly pre-announced: NC flagged a hard line during the June 30 livestream, and on July 31 added a piloting (대리 게임) item to the operation policy allowing permanent sanctions regardless of offense count for commercial, organized, or brokered activity."]),
        section("commissioning-players", "Commissioning Players: 30-Day Restrictions", ["Beyond the organizations themselves, 9 characters that commissioned the service — taking the clear rewards, goods, and progression benefits while cooperating with the pilots' account access and authentication — received 30-day use restrictions.", "Both groups also lost eligibility for the 'First Subjugation Glory: Snowfield of Sorrow' event (the first-clear race that rewards the first 20 Hard-clearing forces), which closed off the race to anyone caught."]),
        section("policy-basis", "The Policy Basis: A Pre-Announced Hard Line", ["The July 31 policy item was aimed directly at this behavior: treating piloting as a business, or brokering it organizationally, triggers a permanent sanction without regard to offense count.", "The current enforcement adds real teeth to that rule — the first high-profile permanent restrictions since the piloting policy was introduced, targeting the highest-value PvE content in the game."]),
        section("what-it-means", "What It Means for the Community", ["For legitimate players, the ban is a signal that raid progress — especially the first-clear race with its Void pet rewards — is being protected from paid carries and boosting services.", "For anyone considering buying a clear, the 30-day restrictions on commissioning players (plus the event ban) make it a genuinely bad deal: the boost itself can void your event eligibility even if your account survives."]),
        section("global-note", "Note for Global Players", ["The sanctions apply to the Korean service, where the raid is live. The global version launches October 5 with a modified Season 1 — expect the same operation policy and the same enforcement posture for the global raid scene.", "NC's broader fair-play program already includes the macro-rework and anti-autoplay design covered elsewhere on the site; piloting enforcement is the newest piece of that program."]),
      ],
    }),
    "zh-hans": articleCopy(newsLabels, "zh-hans", 6, {
      eyebrow: "执法",
      title: "Aion 2 封禁 11 个代练组织：Snowfield of Sorrow 上线两天后，9 名委托玩家被处 30 天限制",
      description: "副本上线两天后，NC 永久封禁 11 个商业化代练组织角色、对 9 名委托代练的玩家处 30 天限制，并一律剥夺首杀竞速事件资格",
      intro: "NCsoft 对付费代打快速出手：9 月 10 日发布首份代练政策制裁公告，永久封禁 11 个以商业化代练（대리 게임）组织身份代打 Snowfield of Sorrow 的角色，并对 9 名委托玩家处 30 天限制。全部 20 个还被剥夺首杀竞速事件资格。",
      sourceNote: "基于 게임톡（GameToc）2026 年 9 月 10 日报道与 NCsoft 在 Aion 2 公告板的官方公告（均于 2026-09-12 抓取）。制裁针对韩服；政策语境同样适用于 10 月 5 日上线的全球版。",
      keywords: ["Aion 2 代练封禁", "Aion 2 大里游戏 永久封禁", "Aion 2 Snowfield of Sorrow 代打打击", "Aion 2 账号代打政策", "Aion 2 首杀竞速资格剥夺"],
      sections: [
        section("the-ban", "11 个代练组织，永久封禁", ["NCsoft 于 9 月 10 日在官方公告板发布制裁公告——距 Snowfield of Sorrow 更新仅两天。11 个被永久封禁的角色属于以商业目的提供、宣传并介绍副本代打的组织。", "这次打击有明确预告的政策支撑：NC 在 6 月 30 日直播中预告强硬立场，7 月 31 日在运营政策中新增「代练游戏」条款，允许对商业化、组织化或中介化活动无论次数一律永久制裁。"]),
        section("commissioning-players", "委托玩家：30 天限制", ["除组织本身外，9 个委托该服务的角色——在配合代练账号登录与认证的同时获取通关奖励、物资与成长收益——被处 30 天使用限制。", "两组玩家还都被剥夺「Snowfield of Sorrow 最初讨伐的荣耀」（奖励前 20 支 Hard 通关队伍的首杀竞速）事件资格——被逮到即失去竞速资格。"]),
        section("policy-basis", "政策依据：预告过的强硬立场", ["7 月 31 日的政策条款正是针对这一行为：将代练当作营生、或组织化介绍代练，触发无条件永久制裁，不论次数。", "本次执法让规则有了实牙——这是代练政策引入以来首次高调永久封禁，且瞄准的是游戏内价值最高的 PvE 内容。"]),
        section("what-it-means", "对社区的意义", ["对正当玩家，封禁是信号：副本进度——尤其是附 Void 宠物奖励的首杀竞速——正被保护免受付费代打与提升服务侵蚀。", "对任何考虑购买通关的人来说，委托方的 30 天限制（加上事件资格剥夺）让这成为真正的亏本买卖：即使账号幸免，代打本身也可能让事件资格作废。"]),
        section("global-note", "对全球玩家的说明", ["制裁针对副本已上线的韩服。全球版 10 月 5 日以改良版 Season 1 上线——全球副本场景将面对同样的运营政策与执法姿态。", "NC 更广的公平竞技计划已包含本站曾报道的宏重做与反自动玩法设计；代练执法是该计划的最新一环。"]),
      ],
    }),
    fr: articleCopy(newsLabels, "fr", 6, {
      eyebrow: "RÉPRESSION",
      title: "Aion 2 bannit définitivement 11 organisations de pilotage après Snowfield of Sorrow ; 9 joueurs commanditaires restreints 30 jours",
      description: "Deux jours après l'ouverture du raid, NC a banni 11 personnages d'organisations de pilotage commercial, imposé 30 jours à 9 joueurs commanditaires et retiré à tous l'éligibilité à l'événement de premier clear",
      intro: "NCsoft a réagi vite contre le boost payé : le 10 septembre, première annonce de sanction de la politique anti-pilotage — 11 personnages d'organisations commerciales de pilotage (대리 게임) de Snowfield of Sorrow bannis définitivement, 9 commanditaires limités 30 jours. Les 20 perdent aussi l'éligibilité au premier clear.",
      sourceNote: "Basé sur le rapport de GameToc du 10 septembre 2026 et l'annonce officielle de NCsoft sur le tableau d'avis d'Aion 2 (récupérés le 12 septembre 2026).",
      keywords: ["Aion 2 ban pilotage", "Aion 2 restriction permanente 대리", "Aion 2 crackdown boost Snowfield of Sorrow", "Aion 2 politique boost de compte", "Aion 2 événement premier clear éligibilité"],
      sections: [
        section("the-ban", "11 organisations bannies", "Annonce du 10 septembre, deux jours après l'update. Les 11 personnages appartenaient à des organisations fournissant, promouvant et revendant commercialement des clears. Politique pré-annoncée : ligne dure au livestream du 30 juin, item « pilotage » ajouté le 31 juillet (sanction permanente sans égard au nombre d'infractions)."),
        section("commissioning-players", "Commanditaires : 30 jours", "9 personnages ayant commandité le service — profitant des récompenses et coopérant à l'accès des comptes — ont reçu 30 jours. Les deux groupes perdent l'éligibilité à « Première gloire de subjugation : Snowfield of Sorrow »."),
        section("policy-basis", "La base : une ligne dure annoncée", "La clause du 31 juillet cible exactement ce comportement ; la première vague de bannissements permanents depuis son introduction vise le PvE le plus précieux du jeu."),
        section("what-it-means", "Ce que ça signifie", "Pour les joueurs légitimes, le raid — et la course aux pets Void — est protégé. Pour les acheteurs, les 30 jours + la perte d'éligibilité en font une mauvaise affaire."),
        section("global-note", "Note pour le global", "Sanctions coréennes ; le global (5 octobre, Saison 1 modifiée) aura la même politique et la même posture. Le programme fair-play inclut déjà la refonte des macros et l'anti-autoplay."),
      ],
    }),
    de: articleCopy(newsLabels, "de", 6, {
      eyebrow: "DURCHSETZUNG",
      title: "Aion 2 sperrt 11 Piloten-Organisationen nach Snowfield-of-Sorrow-Start dauerhaft; 9 Auftraggeber für 30 Tage gesperrt",
      description: "Zwei Tage nach dem Raid-Start sperrte NC 11 Charaktere kommerzieller Piloten-Organisationen dauerhaft, belegte 9 Auftraggeber mit 30 Tagen und entzog allen die Teilnahme am Erst-Clear-Event",
      intro: "NCsoft reagierte schnell gegen bezahltes Boosten: Am 10. September kam die erste Sanktionsmeldung der Pilotierungsrichtlinie — 11 Charaktere kommerzieller Pilot-Organisationen (대리 게임) von Snowfield of Sorrow dauerhaft gesperrt, 9 Auftraggeber für 30 Tage. Alle 20 verlieren zudem die Erst-Clear-Eligibility.",
      sourceNote: "Basierend auf dem GameToc-Bericht vom 10. September 2026 und der offiziellen Meldung von NCsoft im Aion-2-Anschlagbrett (abgerufen am 12. September 2026).",
      keywords: ["Aion 2 Piloten-Sperre", "Aion 2 permanente Sperre 대리", "Aion 2 Boosting-Razzia Snowfield of Sorrow", "Aion 2 Account-Boosting Richtlinie", "Aion 2 Erst-Clear-Event Sperre"],
      sections: [
        section("the-ban", "11 Piloten-Organisationen gesperrt", "Meldung vom 10. September, zwei Tage nach dem Update. Die 11 Charaktere gehörten Organisationen, die Clears kommerziell anboten, bewarben und vermittelten. Angekündigte Linie: Härte im Livestream vom 30. Juni, Pilotierungs-Item am 31. Juli (dauerhafte Sperre unabhängig von der Anzahl der Verstöße)."),
        section("commissioning-players", "Auftraggeber: 30 Tage", "9 Charaktere, die den Dienst beauftragten — mit Belohnungen und Kooperation beim Account-Zugriff — erhielten 30 Tage. Beide Gruppen verlieren die Eligibility für „Erste Unterwerfungs-Ehre: Snowfield of Sorrow“."),
        section("policy-basis", "Die Basis: eine angekündigte harte Linie", "Die Klausel vom 31. Juli zielt genau auf dieses Verhalten; die erste dauerhafte Sperrwelle seit Einführung trifft das wertvollste PvE des Spiels."),
        section("what-it-means", "Was das bedeutet", "Für legitime Spieler wird der Raid — und das Void-Pet-Rennen — geschützt. Für Käufer machen die 30 Tage plus Event-Sperre das Boosten zu einem schlechten Geschäft."),
        section("global-note", "Hinweis für Global", "Koreanische Sanktionen; Global (5. Oktober, modifizierte Season 1) bekommt dieselbe Politik und Haltung. Das Fair-Play-Programm umfasst bereits die Makro-Überarbeitung und Anti-Autoplay."),
      ],
    }),
    es: articleCopy(newsLabels, "es", 6, {
      eyebrow: "APLICACIÓN",
      title: "Aion 2 banea permanentemente a 11 organizaciones de pilotaje tras Snowfield of Sorrow; 9 comitentes restringidos 30 días",
      description: "Dos días después del raid, NC baneó a 11 personajes de organizaciones de pilotaje comercial, sancionó con 30 días a 9 comitentes y retiró a todos la elegibilidad del evento de primer clear",
      intro: "NCsoft reaccionó rápido contra el boost de pago: el 10 de septiembre publicó el primer aviso de sanción de la política anti-pilotaje — 11 personajes de organizaciones comerciales de pilotaje (대리 게임) de Snowfield of Sorrow baneados, 9 comitentes restringidos 30 días. Los 20 pierden la elegibilidad del primer clear.",
      sourceNote: "Basado en el informe de GameToc del 10 de septiembre de 2026 y el aviso oficial de NCsoft en el tablón de Aion 2 (recuperados el 12 de septiembre de 2026).",
      keywords: ["Aion 2 ban pilotaje", "Aion 2 restricción permanente 대리", "Aion 2 represión boost Snowfield of Sorrow", "Aion 2 política boost de cuentas", "Aion 2 elegibilidad evento primer clear"],
      sections: [
        section("the-ban", "11 organizaciones baneadas", "Aviso del 10 de septiembre, dos días después del update. Los 11 personajes pertenecían a organizaciones que ofrecían, promovían y revendían clears comercialmente. Línea anunciada: dureza en el livestream del 30 de junio, ítem «pilotaje» el 31 de julio (sanción permanente sin importar el número de infracciones)."),
        section("commissioning-players", "Comitentes: 30 días", "9 personajes que encargaron el servicio — con recompensas y cooperación en el acceso — recibieron 30 días. Ambos grupos pierden la elegibilidad de «Primera gloria de subyugación: Snowfield of Sorrow»."),
        section("policy-basis", "La base: una línea dura anunciada", "La cláusula del 31 de julio apunta exactamente a este comportamiento; la primera ola de baneos permanentes desde su introducción golpea el PvE más valioso del juego."),
        section("what-it-means", "Qué significa", "Para jugadores legítimos, el raid — y la carrera de mascotas Void — queda protegido. Para compradores, los 30 días + la pérdida de elegibilidad hacen del boost un mal negocio."),
        section("global-note", "Nota para el global", "Sanciones coreanas; el global (5 de octubre, Temporada 1 modificada) tendrá la misma política y postura. El programa fair-play ya incluye la reforma de macros y el anti-autoplay."),
      ],
    }),
    ja: articleCopy(newsLabels, "ja", 6, {
      eyebrow: "取り締まり",
      title: "Aion 2、Snowfield of Sorrow実装2日後に代行組織11キャラを永久利用制限——依頼した9ユーザーは30日間",
      description: "レイド実装から2日後、NCは商業代行（대리 게임）組織のキャラクター11体を永久利用制限、依頼した9ユーザーに30日間の制限を科し、全員から初クリアレースの参加資格を剥奪",
      intro: "NCは有料代行に素早く対応：9月10日、代行運営ポリシー初の制裁告知を公開——Snowfield of Sorrowの商業代行組織キャラ11体を永久利用制限、依頼した9ユーザーに30日間の制限。20体すべてが初クリアイベントの参加資格も失います。",
      sourceNote: "ゲームトーク2026年9月10日付報道と、NC公式のAion 2告知板のお知らせ（いずれも2026-09-12取得）に基づきます。",
      keywords: ["Aion 2 代行 利用制限", "Aion 2 永久制限 대리", "Aion 2 Snowfield of Sorrow 代行 取り締まり", "Aion 2 アカウント代行 ポリシー", "Aion 2 初クリアレース 資格剥奪"],
      sections: [
        section("the-ban", "代行組織11体を永久制限", "告知は9月10日——Snowfield of Sorrow実装から2日後。永久制限された11体は、レイドクリアを商業的に提供・広告・仲介した組織のキャラクターでした。6月30日の配信で強硬方針が予告され、7月31日に運用ポリシーへ「代行ゲーム」項目が追加（営利・組織的・仲介は回数に関係なく永久制裁）されています。"),
        section("commissioning-players", "依頼ユーザー：30日間", "組織だけでなく、報酬や成長利益を得て代行側のログイン・認証に協力した9キャラにも30日間の利用制限。両グループとも『최초 토벌의 영광: 비탄의 설원』（先着20部隊に報酬の初クリアレース）の参加資格を剥奪されました。"),
        section("policy-basis", "政策の根拠：予告済みの強硬方針", "7月31日追加の条項はまさにこの行為を対象にしています。導入後初の大規模な永久制裁が、ゲーム内で最も価値の高いPvEコンテンツを標的にしています。"),
        section("what-it-means", "コミュニティへの意味", "正当なプレイヤーにとって、レイド（Voidペットレース含む）が有料キャリーから守られるというシグナルです。購入を検討していた人にとっては、依頼側の30日制限＋イベント資格剥奪で、かなり割の悪い取引になります。"),
        section("global-note", "グローバル向けの注記", "制裁はレイド稼働中の韓国サーバー向け。グローバル（10月5日、改良版シーズン1）でも同じ運営ポリシーと姿勢が適用される見込みです。NCのフェアプレイ施策には既報のマクロ改修・反自動操作設計も含まれ、代行取り締まりはその最新ピースです。"),
      ],
    }),
    "pt-br": articleCopy(newsLabels, "pt-br", 6, {
      eyebrow: "EXECUÇÃO",
      title: "Aion 2 bane permanentemente 11 organizações de pilotagem após Snowfield of Sorrow; 9 comitentes restringidos por 30 dias",
      description: "Dois dias após o raid, a NC baniu 11 personagens de organizações de pilotagem comercial, aplicou 30 dias a 9 comitentes e removeu a elegibilidade de todos no evento do primeiro clear",
      intro: "A NCsoft reagiu rápido contra o boost pago: em 10 de setembro publicou o primeiro aviso de sanção da política anti-pilotagem — 11 personagens de organizações comerciais de pilotagem (대리 게임) de Snowfield of Sorrow banidos, 9 comitentes restringidos por 30 dias. Todos os 20 perdem a elegibilidade do primeiro clear.",
      sourceNote: "Baseado no relatório da GameToc de 10 de setembro de 2026 e no aviso oficial da NCsoft no quadro de avisos do Aion 2 (recuperados em 12 de setembro de 2026).",
      keywords: ["Aion 2 ban pilotagem", "Aion 2 restrição permanente 대리", "Aion 2 repressão boost Snowfield of Sorrow", "Aion 2 política boost de contas", "Aion 2 elegibilidade evento primeiro clear"],
      sections: [
        section("the-ban", "11 organizações banidas", "Aviso de 10 de setembro, dois dias após o update. Os 11 personagens pertenciam a organizações que ofereciam, promoviam e revendiam clears comercialmente. Linha anunciada: dureza no livestream de 30 de junho, item «pilotagem» em 31 de julho (sanção permanente independentemente do número de infrações)."),
        section("commissioning-players", "Comitentes: 30 dias", "9 personagens que contrataram o serviço — com recompensas e cooperação no acesso — receberam 30 dias. Ambos os grupos perdem a elegibilidade de «Primeira glória de subjugação: Snowfield of Sorrow»."),
        section("policy-basis", "A base: uma linha dura anunciada", "A cláusula de 31 de julho mira exatamente esse comportamento; a primeira onda de banimentos permanentes desde a introdução atinge o PvE mais valioso do jogo."),
        section("what-it-means", "O que significa", "Para jogadores legítimos, o raid — e a corrida de mascotes Void — fica protegido. Para compradores, os 30 dias + a perda de elegibilidade tornam o boost um mau negócio."),
        section("global-note", "Nota para o global", "Sanções coreanas; o global (5 de outubro, Temporada 1 modificada) terá a mesma política e postura. O programa fair-play já inclui a reforma de macros e o anti-autoplay."),
      ],
    }),
    ru: articleCopy(newsLabels, "ru", 6, {
      eyebrow: "ПРИМЕНЕНИЕ",
      title: "Aion 2 навсегда блокирует 11 пилот-организаций после Snowfield of Sorrow; 9 заказчиков ограничены на 30 дней",
      description: "Через два дня после рейда NC навсегда забанила 11 персонажей коммерческих пилот-организаций, дала 9 заказчикам по 30 дней и лишила всех права участвовать в гонке первого клира",
      intro: "NCsoft быстро отреагировала на платный буст: 10 сентября — первое уведомление о санкциях политики пилотинга — 11 персонажей коммерческих пилот-организаций (대리 게임) Snowfield of Sorrow забанены навсегда, 9 заказчиков ограничены на 30 дней. Все 20 теряют право участвовать в первом клире.",
      sourceNote: "На основе отчёта GameToc от 10 сентября 2026 г. и официального объявления NCsoft на доске объявлений Aion 2 (получены 12 сентября 2026 г.).",
      keywords: ["Aion 2 бан пилотинга", "Aion 2 постоянное ограничение 대리", "Aion 2 борьба с бустом Snowfield of Sorrow", "Aion 2 политика буста аккаунтов", "Aion 2 право участия первый клир"],
      sections: [
        section("the-ban", "11 организаций забанены", "Объявление 10 сентября, через два дня после обновления. 11 персонажей принадлежали организациям, коммерчески предлагавшим, рекламировавшим и продававшим клиры. Анонсированная линия: жёсткость в стриме 30 июня, пункт «пилотинг» добавлен 31 июля (постоянная санкция независимо от числа нарушений)."),
        section("commissioning-players", "Заказчики: 30 дней", "9 персонажей, заказавших услугу — получавших награды и сотрудничавших с доступом к аккаунтам, — получили 30 дней. Обе группы теряют право на «Первую славу покорения: Snowfield of Sorrow»."),
        section("policy-basis", "Основание: анонсированная жёсткая линия", "Пункт от 31 июля нацелен именно на это; первая волна постоянных банов с момента введения бьёт по самому ценному PvE игры."),
        section("what-it-means", "Что это значит", "Для легитимных игроков рейд — и гонка питомцев Void — защищён. Для покупателей 30 дней плюс потеря права на событие делают буст плохой сделкой."),
        section("global-note", "Примечание для глобала", "Корейские санкции; глобал (5 октября, модифицированный Сезон 1) получит ту же политику и позицию. Программа fair-play уже включает переработку макросов и анти-автоплей."),
      ],
    }),
    ko: articleCopy(newsLabels, "ko", 6, {
      eyebrow: "제재",
      title: "아이온2, 비탄의 설원 출시 이틀 만에 대리 조직 11개 영구 이용제한——맡긴 이용자 9개는 30일 제한",
      description: "레이드 출시 이틀 만에 NC가 영리 대리 조직 캐릭터 11개를 영구 이용제한하고, 대리를 맡긴 이용자 9개에 30일 제한을 적용했으며 모두의 첫 클리어 이벤트 참여 권한을 박탈",
      intro: "엔씨소프트가 유료 대리(부스팅)에 신속하게 대응했습니다: 9월 10일, 대리 게임 운영정책 첫 제재 공지를 게재——비탄의 설원 공략을 영리 목적으로 대행한 조직 캐릭터 11개를 영구 이용제한하고, 대리를 맡긴 이용자 9개에 30일 이용제한을 적용했습니다. 20개 모두 첫 클리어 이벤트 참여 권한도 박탈됩니다.",
      sourceNote: "게임톡 2026년 9월 10일자 보도와 NC 공식 아이온2 공지판 안내(모두 2026-09-12 확인)를 기반으로 했습니다.",
      keywords: ["아이온2 대리 게임 이용제한", "아이온2 영구 제재", "아이온2 비탄의 설원 대리 단속", "아이온2 계정 대리 정책", "아이온2 첫 클리어 이벤트 자격 박탈"],
      sections: [
        section("the-ban", "대리 조직 11개, 영구 이용제한", "엔씨는 9월 10일 공식 홈페이지에 제재 안내 공지를 게재했습니다——비탄의 설원 업데이트(9/9) 이틀 만입니다. 영구 이용제한된 11개 캐릭터는 콘텐츠 클리어를 조직적으로 제공·홍보·알선해 부당 이익을 취한 조직의 계정입니다.", "이번 단속에는 사전 예고된 정책이 뒷받침됩니다: 6월 30일 라이브 방송에서 강경 대응을 예고했고, 7월 31일 운영정책에 '대리 게임' 항목을 신설해 영리 목적·조직적·알선 행위는 차수와 관계없이 영구 제재할 수 있게 했습니다."),
        section("commissioning-players", "대리를 맡긴 이용자: 30일 제한", "조직뿐 아니라 대리 서비스로 클리어 보상·재화·성장 이익을 취하고 대리 조직의 계정 접속·인증에 협조한 캐릭터 9개가 30일 이용제한을 받았습니다.", "두 그룹 모두 '최초 토벌의 영광: 비탄의 설원'(선착 20개 포스에 보상하는 첫 클리어 레이스) 이벤트 참여 권한도 박탈됐습니다——적발되면 레이스에서 배제됩니다."),
        section("policy-basis", "정책 근거: 예고된 강경 방침", "7월 31일 신설 조항은 정확히 이 행위를 겨냥합니다: 대리를 업으로 삼거나 조직적으로 알선하면 횟수와 무관하게 영구 제재.", "이번 집행은 그 규칙에 실제 제재력을 더한 사례입니다——도입 후 첫 고강도 영구 제재가 게임 내 가장 가치 높은 PvE 콘텐츠를 겨냥했습니다."),
        section("what-it-means", "커뮤니티에 주는 의미", "정상 플레이어에게 이 제재는 신호입니다: 레이드 진행——특히 보이드 펫 보상이 걸린 첫 클리어 레이스——이 유료 캐리와 부스팅 서비스로부터 보호받고 있다는 뜻입니다.", "클리어 구매를 고려하던 사람에게는, 위탁측 30일 제한(이벤트 자격 박탈 포함)이 아주 나쁜 거래임을 보여줍니다: 계정이 살아남아도 부스트 자체가 이벤트 자격을 무효화할 수 있습니다."),
        section("global-note", "글로벌 플레이어 참고", "제재는 레이드가 운영 중인 한국 서버 대상입니다. 글로벌은 10월 5일 수정판 시즌 1로 출시되며, 동일한 운영정책과 집행 기조가 적용될 것으로 예상됩니다.", "NC의 더 넓은 페어플레이 프로그램에는 이미 본 사이트가 다룬 매크로 개편과 반자동 조작 설계가 포함돼 있으며, 대리 단속이 그 최신 조각입니다."),
      ],
    }),
    "zh-hant": articleCopy(newsLabels, "zh-hant", 6, {
      eyebrow: "執法",
      title: "Aion 2 封禁 11 個代練組織：Snowfield of Sorrow 上線兩天後，9 名委託玩家被處 30 天限制",
      description: "副本上線兩天後，NC 永久封禁 11 個商業化代練組織角色、對 9 名委託代練的玩家處 30 天限制，並一律剝奪首殺競速事件資格",
      intro: "NCsoft 對付費代打快速出手：9 月 10 日發布首份代練政策制裁公告，永久封禁 11 個以商業化代練（대리 게임）組織身份代打 Snowfield of Sorrow 的角色，並對 9 名委託玩家處 30 天限制。全部 20 個還被剝奪首殺競速事件資格。",
      sourceNote: "基於 게임톡（GameToc）2026 年 9 月 10 日報導與 NCsoft 在 Aion 2 公告板的官方公告（均於 2026-09-12 抓取）。制裁針對韓服；政策語境同樣適用於 10 月 5 日上線的全球版。",
      keywords: ["Aion 2 代練封禁", "Aion 2 大里遊戲 永久封禁", "Aion 2 Snowfield of Sorrow 代打打擊", "Aion 2 帳號代打政策", "Aion 2 首殺競速資格剝奪"],
      sections: [
        section("the-ban", "11 個代練組織，永久封禁", ["NCsoft 於 9 月 10 日在官方公告板發布制裁公告——距 Snowfield of Sorrow 更新僅兩天。11 個被永久封禁的角色屬於以商業目的提供、宣傳並介紹副本代打的組織。", "這次打擊有明確預告的政策支撐：NC 在 6 月 30 日直播中預告強硬立場，7 月 31 日在營運政策中新增「代練遊戲」條款，允許對商業化、組織化或仲介化活動無論次數一律永久制裁。"]),
        section("commissioning-players", "委託玩家：30 天限制", ["除組織本身外，9 個委託該服務的角色——在配合代練帳號登入與認證的同時獲取通關獎勵、物資與成長收益——被處 30 天使用限制。", "兩組玩家還都被剝奪「Snowfield of Sorrow 最初討伐的榮耀」（獎勵前 20 支 Hard 通關隊伍的首殺競速）事件資格——被逮到即失去競速資格。"]),
        section("policy-basis", "政策依據：預告過的強硬立場", ["7 月 31 日的政策條款正是針對這一行為：將代練當作營生、或組織化介紹代練，觸發無條件永久制裁，不論次數。", "本次執法讓規則有了實牙——這是代練政策引入以來首次高調永久封禁，且瞄準的是遊戲內價值最高的 PvE 內容。"]),
        section("what-it-means", "對社區的意義", ["對正當玩家，封禁是訊號：副本進度——尤其是附 Void 寵物獎勵的首殺競速——正被保護免受付費代打與提升服務侵蝕。", "對任何考慮購買通關的人來說，委託方的 30 天限制（加上事件資格剝奪）讓這成為真正的虧本買賣：即使帳號倖免，代打本身也可能讓事件資格作廢。"]),
        section("global-note", "對全球玩家的說明", ["制裁針對副本已上線的韓服。全球版 10 月 5 日以改良版 Season 1 上線——全球副本場景將面對同樣的營運政策與執法姿態。", "NC 更廣的公平競技計畫已包含本站曾報導的巨集重做與反自動玩法設計；代練執法是該計畫的最新一環。"]),
      ],
    }),
  },
};