import { articleCopy, localizations, newsLabels, publishedVerified, section } from "./trending-september-8-shared";
import type { ContentEntry, ContentHeroImage, ContentSource } from "./content-registry";

/* ARTICLE 2 — Aion 2 global content model: modified Season 1 at launch, ~1 year of Korean content, seasons every ~3 months, behind Korea */

const wfSource: ContentSource = {
  id: "wccftech-aion2-qa-2026-09-07",
  kind: "third-party",
  publisher: "Wccftech",
  label: "Aion 2 Q&A: Global Launch Content Model Discussed (Season 1, Cadence, Korea Parity)",
  url: "https://wccftech.com/aion-2-qa-dlss-5-console-cross-play/",
  publishedAt: "2026-09-07",
  retrievedAt: "2026-09-08",
  verifiedAt: "2026-09-08",
  localizations: localizations({
    "zh-hans": "Aion 2 Q&A：全球版内容模型讨论（Season 1、节奏、与韩服对齐）",
    en: "Aion 2 Q&A: Global Launch Content Model Discussed (Season 1, Cadence, Korea Parity)",
    fr: "Aion 2 Q&R : le modèle de contenu du lancement global discuté (Saison 1, cadence, parité Corée)",
    de: "Aion 2 Q&A: Inhaltsmodell des Global-Launchs besprochen (Season 1, Kadenz, Korea-Parität)",
    es: "Aion 2 Preguntas y respuestas: modelo de contenido del lanzamiento global (Temporada 1, cadencia, paridad con Corea)",
    ja: "Aion 2 Q&A：グローバル版コンテンツモデルを議論（シーズン1、更新頻度、韓国との同期）",
    "pt-br": "Aion 2 Q&A: modelo de conteúdo do lançamento global discutido (Temporada 1, cadência, paridade com a Coreia)",
    ru: "Aion 2 Q&A: обсуждается контент-модель глобального запуска (Сезон 1, темп, паритет с Кореей)",
    ko: "아이온2 Q&A: 글로벌 콘텐츠 모델 논의 (시즌 1, 주기, 한국과의 동기화)",
    "zh-hant": "Aion 2 Q&A：全球版內容模型討論（Season 1、節奏、與韓服對齊）",
  }, "https://wccftech.com/aion-2-qa-dlss-5-console-cross-play/"),
};

const steamSource: ContentSource = {
  id: "aion2-steam-store-2026-09-08",
  kind: "platform",
  publisher: "Steam",
  label: "AION 2 on Steam (Free to Play, Oct 5 2026)",
  url: "https://store.steampowered.com/app/3393110/AION_2/",
  publishedAt: "2026-08-26",
  retrievedAt: "2026-09-08",
  verifiedAt: "2026-09-08",
  localizations: localizations({
    "zh-hans": "Steam 上的 AION 2（免费游玩，2026-10-05）",
    en: "AION 2 on Steam (Free to Play, Oct 5 2026)",
    fr: "AION 2 sur Steam (free-to-play, 5 oct. 2026)",
    de: "AION 2 auf Steam (Free to Play, 5. Okt. 2026)",
    es: "AION 2 en Steam (gratuito, 5 oct 2026)",
    ja: "SteamのAION 2（基本無料、2026-10-05）",
    "pt-br": "AION 2 na Steam (gratuito, 5 out 2026)",
    ru: "AION 2 в Steam (бесплатная, 05.10.2026)",
    ko: "Steam의 AION 2 (부분 유료, 2026-10-05)",
    "zh-hant": "Steam 上的 AION 2（免費遊玩，2026-10-05）",
  }, "https://store.steampowered.com/app/3393110/AION_2/"),
};

const cmHero: ContentHeroImage = {
  src: "https://blogfiles.ncsoft.net/news/af7330da-4ff6-4b58-aece-400e6061a3be.jpg",
  width: 1200, height: 630,
  credit: "NC Corporation",
  sourceUrl: "https://aion2.plaync.com/en-us/",
  rights: "linked-official-media",
  translations: {
    "zh-hans": { alt: "Aion 2 全球版内容模型新闻横幅", caption: "全球版将以改良版 Season 1 上线（含 QoL 与平衡改动），拥有约一年韩服内容储备，之后按约三个月一季的节奏更新，并落后韩服一段时间。" },
    en: { alt: "Aion 2 global content model news banner", caption: "The global version launches with a modified Season 1 with QoL and balance improvements, holds about a year of Korean content, then updates on a ~3-month season cadence behind Korea." },
    fr: { alt: "Bannière d'actualité modèle de contenu global d'Aion 2", caption: "La version globale lance une Saison 1 modifiée (améliorations QoL et équilibrage), avec environ un an de contenu coréen, puis un rythme saisonnier ~3 mois derrière la Corée." },
    de: { alt: "News-Banner zum globalen Inhaltsmodell von Aion 2", caption: "Die globale Version startet mit einer modifizierten Season 1 (QoL und Balance), hält etwa ein Jahr koreanischen Contents und aktualisiert danach im ~3-Monats-Rhythmus hinter Korea." },
    es: { alt: "Banner de noticias del modelo de contenido global de Aion 2", caption: "La versión global se lanza con una Temporada 1 modificada (mejoras QoL y de equilibrio), con alrededor de un año de contenido coreano y un ritmo de ~3 meses detrás de Corea." },
    ja: { alt: "Aion 2 グローバル版コンテンツモデルニュースバナー", caption: "グローバル版は改良版シーズン1（QoL・バランス調整込み）で開始し、韓国向け約1年分のコンテンツを保持、以後は韓国に遅れて約3カ月ごとに更新。" },
    "pt-br": { alt: "Banner de notícias do modelo de conteúdo global do Aion 2", caption: "A versão global lança com uma Temporada 1 modificada (melhorias de QoL e equilíbrio), cerca de um ano de conteúdo coreano e um ritmo de ~3 meses atrás da Coreia." },
    ru: { alt: "Баннер новостей о глобальной контент-модели Aion 2", caption: "Глобальная версия стартует с модифицированным Сезоном 1 (улучшения QoL и баланса), держит около года корейского контента и далее обновляется раз в ~3 месяца с отставанием от Кореи." },
    ko: { alt: "Aion 2 글로벌 콘텐츠 모델 뉴스 배너", caption: "글로벌 버전은 QoL·밸런스 개선이 포함된 수정판 시즌 1로 시작하며, 한국 기준 약 1년치 콘텐츠를 보유한 뒤 한국보다 늦은 약 3개월 주기로 업데이트합니다." },
    "zh-hant": { alt: "Aion 2 全球版內容模型新聞橫幅", caption: "全球版將以改良版 Season 1 上線（含 QoL 與平衡改動），擁有約一年韓服內容儲備，之後按約三個月一季的節奏更新，並落後韓服一段時間。" },
  },
};

export const trendingSeptember8Article2: ContentEntry = {
  section: "news",
  slug: "aion-2-global-launch-content-model-season-1",
  schemaType: "NewsArticle",
  publishedAt: "2026-09-08",
  updatedAt: "2026-09-08",
  readingMinutes: 6,
  publication: publishedVerified,
  sources: [wfSource, steamSource],
  heroImage: cmHero,
  related: [
    { kind: "content", section: "news", slug: "aion-2-release-date-october-5-2026" },
    { kind: "content", section: "news", slug: "aion-2-october-5-launch-countdown-roadmap" },
    { kind: "content", section: "guides", slug: "aion-2-global-version-changes-guide" },
    { kind: "content", section: "news", slug: "aion-2-prelaunch-roadmap-stress-test-to-october-5" },
  ],
  translations: {
    en: articleCopy(newsLabels, "en", 6, {
      eyebrow: "CONTENT ROADMAP",
      title: "Aion 2 Global Content Model: Modified Season 1 at Launch, ~3-Month Seasons, Behind Korea",
      description: "The global version of Aion 2 launches with a modified Season 1 with QoL and balance improvements, holds about a year of Korean content, then follows a ~3-month season cadence — behind Korea, not day-and-date",
      intro: "In the September 7 Gamescom interview, NCsoft's producers laid out how Aion 2's global content will roll out: the game launches with a modified Season 1 (the same season Korea and Taiwan started with, improved), there is roughly a year of Korean content in reserve, and after launch new seasons arrive about every three months — behind Korea rather than day-and-date.",
      sourceNote: "Based on Wccftech's September 7, 2026 interview with the Aion 2 team, cross-checked with the official Steam store page (retrieved September 8, 2026). Season dates and content names are subject to live-service adjustments.",
      keywords: ["Aion 2 global content model", "Aion 2 Season 1 launch", "Aion 2 content cadence three months", "Aion 2 behind Korea content", "Aion 2 global roadmap content"],
      sections: [
        section("season-1-modified", "Launch Content: A Modified Season 1", ["Merv Lee Kwai confirmed that the global build will not be a straight port of Korea's current state: 'The global version will launch with Season 1, the same season Korea and Taiwan originally released with, but a modified version of it, including the quality of life improvements and balance improvements.'", "In practice that means global players start where the Korean and Taiwanese services started — plus roughly a year of accumulated fixes, so the opening season should feel more polished than the original one did."]),
        section("year-of-content", "About a Year of Content in Reserve", ["Asked whether the Western build includes all Korean content, Kwai noted there is 'about a year's worth of content in Korea' and that the team keeps that stable of content available for the global service.", "How quickly that backlog flows out depends on live player data: the team plans to watch how fast players consume content and adjust release pacing accordingly rather than dumping everything at once."]),
        section("three-month-cadence", "Seasons Every ~3 Months, Following the Korean Model", ["'We'll follow the Korean model closely. In general, they have a new season about every three months, and the global version will be similar,' Kwai said, while adding that the cadence will be tuned by real consumption data.", "That mirrors the Korea/Taiwan cadence covered in the site's launch roadmap and gives global players a predictable rhythm of season passes and major updates."]),
        section("behind-korea", "Behind Korea, Not Day-and-Date", ["On catching up to Korea, Kwai was direct: 'To be day and date with Korea would be very challenging for us. Not impossible, but challenging.'", "The working plan is to stay behind Korea by some amount of time — 'it could be faster, it could be slower' — mainly because localization and publishing overhead make simultaneous releases hard."]),
        section("what-it-means", "What This Means for Launch Planning", ["For a new player, the model is friendly: you are not jumping into a year of catch-up, and the Season 1 content set matches the fresh-start launch window of October 5.", "For returning Korean players, it means the global service is a distinct operation with its own rhythm — worth considering before choosing where to invest time after the free-to-play launch."]),
      ],
    }),
    "zh-hans": articleCopy(newsLabels, "zh-hans", 6, {
      eyebrow: "内容路线",
      title: "Aion 2 全球版内容模型：改良版 Season 1 上线、约三个月一季、落后韩服",
      description: "全球版以含 QoL 与平衡改动的改良版 Season 1 上线，储备约一年韩服内容，之后按约三个月一季更新——落后韩服而非同步",
      intro: "在 9 月 7 日 Gamescom 专访中，NCsoft 制作人阐述了 Aion 2 全球版的内容推进方式：以改良版 Season 1（韩服/台服当年首发时的赛季，但已改进）上线，储备约一年韩服内容，发售后约三个月一季更新——落后韩服而非同日同步。",
      sourceNote: "基于 Wccftech 2026 年 9 月 7 日对 Aion 2 开发团队的专访，并与官方 Steam 商店页（2026-09-08 抓取）交叉核对。赛季日期与内容名称以运营实况为准。",
      keywords: ["Aion 2 全球版内容模型", "Aion 2 Season 1 上线", "Aion 2 内容节奏 三个月", "Aion 2 落后韩服", "Aion 2 全球版内容路线"],
      sections: [
        section("season-1-modified", "上线内容：改良版 Season 1", ["Merv Lee Kwai 确认全球版不会是韩服现状的直接移植：「全球版将以 Season 1 上线——即韩服与台服最初发布时的赛季，但为改良版，包含此前提到的 QoL 与平衡改进。」", "实际意味着全球玩家从韩服/台服当年的起点开始，外加约一年积累的修复，开局赛季会比当初更精良。"]),
        section("year-of-content", "储备约一年内容", ["被问及西区版是否包含全部韩服内容时，Kwai 表示韩服「约有价值一年的内容」，团队会为全球服保留这个内容储备。", "储备释放速度取决于线上玩家数据：团队计划观察玩家消耗速度并据此调整释放节奏，而非一次性全部放出。"]),
        section("three-month-cadence", "约三个月一季，沿用韩服模式", ["「我们会紧密沿用韩服模式。一般来说他们约三个月一个赛季，全球版也会类似。」Kwai 补充说节奏会按实际消耗数据调整。", "这与本站上线路线图中的韩服/台服节奏一致，也让全球玩家对赛季通行证与大更新的节奏有可预期的规律。"]),
        section("behind-korea", "落后韩服，而非同日同步", ["关于追赶韩服，Kwai 直言：「与韩服同日同步对我们来说非常困难。并非不可能，但很有挑战。」", "工作计划是保持落后韩服一段时间——「可能更快也可能更慢」——主要因为本地化与发行成本使同步发布很难。"]),
        section("what-it-means", "对上线规划的意义", ["对新玩家来说这个模型很友好：无需追赶一年进度，Season 1 内容集与 10 月 5 日全新开局的窗口匹配。", "对回流韩服玩家而言，这意味着全球服是节奏独立的另一套运营——在 10 月 5 日免费制上线前值得想清楚把时间投在哪边。"]),
      ],
    }),
    fr: articleCopy(newsLabels, "fr", 6, {
      eyebrow: "ROADMAP CONTENU",
      title: "Modèle de contenu global d'Aion 2 : Saison 1 modifiée au lancement, saisons ~3 mois, derrière la Corée",
      description: "La version globale lance une Saison 1 modifiée (QoL et équilibrage), environ un an de contenu coréen, puis un rythme ~3 mois — derrière la Corée, pas simultané",
      intro: "Dans l'entretien du 7 septembre à la Gamescom, les producteurs de NCsoft ont détaillé le déploiement du contenu global : lancement avec une Saison 1 modifiée (celle de Corée/Taïwan, améliorée), environ un an de contenu coréen en réserve, puis des saisons ~tous les trois mois — derrière la Corée, pas simultanément.",
      sourceNote: "Basé sur l'entretien de Wccftech du 7 septembre 2026 avec l'équipe Aion 2, recoupé avec la page Steam officielle (récupérée le 8 septembre 2026).",
      keywords: ["Aion 2 modèle de contenu global", "Aion 2 Saison 1 lancement", "Aion 2 cadence trois mois", "Aion 2 derrière la Corée", "Aion 2 roadmap contenu global"],
      sections: [
        section("season-1-modified", "Contenu de lancement : une Saison 1 modifiée", "Merv Lee Kwai : « La version globale lancera avec la Saison 1, celle de Corée/Taïwan à l'origine, mais modifiée, avec les améliorations QoL et d'équilibrage. » Les joueurs globaux démarrent où Corée/Taïwan ont démarré, avec ~un an de correctifs en plus."),
        section("year-of-content", "Environ un an de contenu en réserve", "« Environ un an de contenu existe en Corée », conservé pour le service global ; la vitesse de déploiement dépendra des données live de consommation des joueurs."),
        section("three-month-cadence", "Des saisons ~3 mois, selon le modèle coréen", "« Nous suivrons de près le modèle coréen : en général une nouvelle saison ~tous les trois mois, et la version globale sera similaire », ajustée par les données réelles."),
        section("behind-korea", "Derrière la Corée, pas simultané", "« Être simultané avec la Corée serait très difficile. Pas impossible, mais difficile » — le plan est de rester derrière la Corée, surtout à cause de la localisation."),
        section("what-it-means", "Ce que cela signifie", "Pour un nouveau joueur, pas de rattrapage d'un an ; pour un joueur coréen, le service global est une opération distincte avec son propre rythme."),
      ],
    }),
    de: articleCopy(newsLabels, "de", 6, {
      eyebrow: "CONTENT-ROADMAP",
      title: "Globales Inhaltsmodell von Aion 2: modifizierte Season 1 zum Start, ~3-Monats-Seasons, hinter Korea",
      description: "Die globale Version startet mit einer modifizierten Season 1 (QoL und Balance), hält ~ein Jahr koreanischen Contents, dann ~3-Monats-Seasons — hinter Korea, nicht zeitgleich",
      intro: "Im Gamescom-Interview vom 7. September legten NCsoft-Produzenten dar, wie der globale Content von Aion 2 ausgerollt wird: Start mit einer modifizierten Season 1 (die Staffel von Korea/Taiwan, verbessert), etwa ein Jahr koreanischer Content in Reserve, danach neue Seasons etwa alle drei Monate — hinter Korea statt zeitgleich.",
      sourceNote: "Basierend auf dem Wccftech-Interview vom 7. September 2026 mit dem Aion-2-Team, abgeglichen mit der offiziellen Steam-Seite (abgerufen am 8. September 2026).",
      keywords: ["Aion 2 globales Inhaltsmodell", "Aion 2 Season 1 Start", "Aion 2 Inhalts-Takt drei Monate", "Aion 2 hinter Korea", "Aion 2 Content-Roadmap"],
      sections: [
        section("season-1-modified", "Startinhalt: eine modifizierte Season 1", "Merv Lee Kwai: „Die globale Version startet mit Season 1 — derselben Staffel, mit der Korea und Taiwan ursprünglich starteten, aber einer modifizierten, mit QoL- und Balance-Verbesserungen.“ Global beginnt dort, wo Korea/Taiwan begannen, plus ~ein Jahr Fixes."),
        section("year-of-content", "Etwa ein Jahr Content in Reserve", "„In Korea gibt es etwa ein Jahr Content“, der für den globalen Dienst vorgehalten wird; wie schnell er fließt, hängt von den Live-Daten der Spieler ab."),
        section("three-month-cadence", "Seasons ~3 Monate nach koreanischem Modell", "„Wir folgen dem koreanischen Modell eng: eine neue Season etwa alle drei Monate, die globale Version ähnlich“ — justiert durch echte Konsumdaten."),
        section("behind-korea", "Hinter Korea, nicht zeitgleich", "„Gleichzeitig mit Korea wäre sehr herausfordernd. Nicht unmöglich, aber herausfordernd“ — der Plan ist ein gewisser Abstand, vor allem wegen der Lokalisierung."),
        section("what-it-means", "Was das bedeutet", "Neue Spieler müssen kein Jahr aufholen; für koreanische Spieler ist der globale Dienst eine eigene Operation mit eigenem Rhythmus."),
      ],
    }),
    es: articleCopy(newsLabels, "es", 6, {
      eyebrow: "ROADMAP DE CONTENIDO",
      title: "Modelo de contenido global de Aion 2: Temporada 1 modificada en el lanzamiento, temporadas ~3 meses, detrás de Corea",
      description: "La versión global lanza una Temporada 1 modificada (QoL y equilibrio), alrededor de un año de contenido coreano y luego temporadas ~cada 3 meses — detrás de Corea, no simultáneo",
      intro: "En la entrevista del 7 de septiembre en Gamescom, los productores de NCsoft detallaron cómo saldrá el contenido global de Aion 2: lanzamiento con una Temporada 1 modificada (la de Corea/Taiwán, mejorada), aproximadamente un año de contenido coreano en reserva, y luego temporadas ~cada tres meses — detrás de Corea, no en simultáneo.",
      sourceNote: "Basado en la entrevista de Wccftech del 7 de septiembre de 2026 con el equipo de Aion 2, cotejado con la página oficial de Steam (recuperada el 8 de septiembre de 2026).",
      keywords: ["Aion 2 modelo de contenido global", "Aion 2 Temporada 1 lanzamiento", "Aion 2 cadencia tres meses", "Aion 2 detrás de Corea", "Aion 2 roadmap contenido"],
      sections: [
        section("season-1-modified", "Contenido de lanzamiento: una Temporada 1 modificada", "Merv Lee Kwai: «La versión global lanzará con la Temporada 1, la misma con la que Corea y Taiwán lanzaron originalmente, pero modificada, con las mejoras QoL y de equilibrio.» Los jugadores globales empiezan donde empezaron Corea/Taiwán, con ~un año de arreglos extra."),
        section("year-of-content", "Alrededor de un año de contenido en reserva", "«Hay alrededor de un año de contenido en Corea», conservado para el servicio global; la velocidad de lanzamiento dependerá de los datos de consumo en vivo."),
        section("three-month-cadence", "Temporadas ~3 meses, siguiendo el modelo coreano", "«Seguiremos de cerca el modelo coreano: en general una nueva temporada ~cada tres meses, y la versión global será similar», ajustada por datos reales."),
        section("behind-korea", "Detrás de Corea, no simultáneo", "«Ser simultáneo con Corea sería muy difícil. No imposible, pero difícil» — el plan es mantener cierta distancia, sobre todo por la localización."),
        section("what-it-means", "Qué significa", "Para un jugador nuevo no hay un año de puesta al día; para un jugador coreano, el servicio global es una operación distinta con su propio ritmo."),
      ],
    }),
    ja: articleCopy(newsLabels, "ja", 6, {
      eyebrow: "コンテンツロードマップ",
      title: "Aion 2 グローバル版コンテンツモデル：改良版シーズン1で開始、約3カ月ごとのシーズン、韓国より遅れて",
      description: "グローバル版はQoL・バランス改善込みの改良版シーズン1で開始、韓国向け約1年分のコンテンツを保持し、以後は約3カ月ごと——韓国より遅れて、同時ではなく",
      intro: "9月7日のGamescomインタビューでNCのプロデューサーがグローバル版のコンテンツ展開を説明：改良版シーズン1（韓国・台湾が最初に始めたシーズンの改良版）で開始し、韓国向け約1年分を保持、以後は約3カ月ごとにシーズン更新——韓国と同時ではなく遅れて。",
      sourceNote: "Wccftech 2026年9月7日付インタビュー（Aion 2チーム）に基づき、公式Steamストアページ（2026-09-08取得）と照合。",
      keywords: ["Aion 2 グローバル コンテンツモデル", "Aion 2 シーズン1 開始", "Aion 2 更新頻度 3カ月", "Aion 2 韓国より遅れ", "Aion 2 コンテンツロードマップ"],
      sections: [
        section("season-1-modified", "開始コンテンツ：改良版シーズン1", "Merv Lee Kwai氏：\"グローバル版はシーズン1で開始します——韓国・台湾が最初にリリースしたのと同じシーズンですが、QoLとバランス改善を入れた改良版です。\" つまり約1年分の修正を載せた形で、韓国・台湾の出発点から始まります。"),
        section("year-of-content", "約1年分のコンテンツを保持", "\"韓国には約1年分のコンテンツがあります\"——これをグローバル向けに保持し、解放速度はプレイヤーの消費データ次第。一気に全部出すのではなく調整します。"),
        section("three-month-cadence", "約3カ月ごとのシーズン", "\"韓国モデルに密に従います。一般的に約3カ月ごとに新シーズンがあり、グローバル版も同様です\"とKwai氏。実際の消費データで微調整されます。"),
        section("behind-korea", "韓国より遅れて、同時ではなく", "\"韓国と同時は非常に難しい。不可能ではないが困難です\"——主にローカライズの負担で、多少の遅れを保つ方針です。"),
        section("what-it-means", "プレイヤーへの意味", "新規プレイヤーは1年分の追い上げ不要。韓国からの移行を考えるプレイヤーは、グローバルが独自リズムの別サービスだと理解しておきましょう。"),
      ],
    }),
    "pt-br": articleCopy(newsLabels, "pt-br", 6, {
      eyebrow: "ROADMAP DE CONTEÚDO",
      title: "Modelo de conteúdo global do Aion 2: Temporada 1 modificada no lançamento, temporadas ~3 meses, atrás da Coreia",
      description: "A versão global lança uma Temporada 1 modificada (QoL e equilíbrio), cerca de um ano de conteúdo coreano e depois temporadas ~a cada 3 meses — atrás da Coreia, não simultâneo",
      intro: "Na entrevista de 7 de setembro na Gamescom, os produtores da NCsoft detalharam a distribuição do conteúdo global do Aion 2: lançamento com uma Temporada 1 modificada (a da Coreia/Taiwan, melhorada), cerca de um ano de conteúdo coreano em reserva, e depois temporadas ~a cada três meses — atrás da Coreia, não em simultâneo.",
      sourceNote: "Baseado na entrevista da Wccftech de 7 de setembro de 2026 com a equipe do Aion 2, cruzado com a página oficial da Steam (acessada em 8 de setembro de 2026).",
      keywords: ["Aion 2 modelo de conteúdo global", "Aion 2 Temporada 1 lançamento", "Aion 2 cadência três meses", "Aion 2 atrás da Coreia", "Aion 2 roadmap conteúdo"],
      sections: [
        section("season-1-modified", "Conteúdo de lançamento: uma Temporada 1 modificada", "Merv Lee Kwai: «A versão global vai lançar com a Temporada 1, a mesma com que Coreia e Taiwan lançaram originalmente, mas modificada, com as melhorias de QoL e equilíbrio.» Jogadores globais começam onde Coreia/Taiwan começaram, com ~um ano de correções a mais."),
        section("year-of-content", "Cerca de um ano de conteúdo em reserva", "«Há cerca de um ano de conteúdo na Coreia», mantido para o serviço global; a velocidade de liberação dependerá dos dados de consumo ao vivo."),
        section("three-month-cadence", "Temporadas ~3 meses, seguindo o modelo coreano", "«Seguiremos de perto o modelo coreano: em geral uma nova temporada ~a cada três meses, e a versão global será parecida», ajustada por dados reais."),
        section("behind-korea", "Atrás da Coreia, não simultâneo", "«Ser simultâneo com a Coreia seria muito difícil. Não impossível, mas difícil» — o plano é manter certa distância, sobretudo pela localização."),
        section("what-it-means", "O que isso significa", "Para um jogador novo, não há um ano de recuperação; para um jogador coreano, o serviço global é uma operação distinta com ritmo próprio."),
      ],
    }),
    ru: articleCopy(newsLabels, "ru", 6, {
      eyebrow: "КОНТЕНТ-РОАДМАП",
      title: "Глобальная контент-модель Aion 2: модифицированный Сезон 1 на старте, сезоны ~раз в 3 месяца, с отставанием от Кореи",
      description: "Глобальная версия стартует с модифицированным Сезоном 1 (QoL и баланс), держит около года корейского контента, затем сезоны ~раз в 3 месяца — с отставанием от Кореи, не одновременно",
      intro: "В интервью 7 сентября на Gamescom продюсеры NCsoft объяснили, как будет выходить глобальный контент Aion 2: запуск с модифицированным Сезоном 1 (тем же, с которого начинали Корея и Тайвань, но улучшенным), около года корейского контента в запасе, затем новые сезоны примерно раз в три месяца — с отставанием от Кореи, а не одновременно.",
      sourceNote: "На основе интервью Wccftech от 7 сентября 2026 г. с командой Aion 2, сверено с официальной страницей Steam (получена 8 сентября 2026 г.).",
      keywords: ["Aion 2 глобальная контент-модель", "Aion 2 Сезон 1 запуск", "Aion 2 темп обновлений три месяца", "Aion 2 отставание от Кореи", "Aion 2 контент-роадмап"],
      sections: [
        section("season-1-modified", "Контент на старте: модифицированный Сезон 1", "Мерв Ли Квай: «Глобальная версия запустится с Сезоном 1 — тем же, с которого начинали Корея и Тайвань, но модифицированным, с улучшениями QoL и баланса». Глобальные игроки начинают там, где начинали Корея/Тайвань, плюс около года исправлений."),
        section("year-of-content", "Около года контента в запасе", "«В Корее около года контента», который сохраняется для глобального сервиса; скорость выхода будет зависеть от живых данных о потреблении."),
        section("three-month-cadence", "Сезоны ~раз в 3 месяца по корейской модели", "«Мы будем близко следовать корейской модели: в целом новый сезон примерно раз в три месяца, и глобальная версия будет похожа», с корректировкой по реальным данным."),
        section("behind-korea", "С отставанием от Кореи, не одновременно", "«Быть одновременно с Кореей было бы очень сложно. Не невозможно, но сложно» — план держать некоторое отставание, прежде всего из-за локализации."),
        section("what-it-means", "Что это значит", "Новым игрокам не нужно навёрстывать год; для корейских игроков глобальный сервис — отдельная операция со своим ритмом."),
      ],
    }),
    ko: articleCopy(newsLabels, "ko", 6, {
      eyebrow: "콘텐츠 로드맵",
      title: "아이온2 글로벌 콘텐츠 모델: 수정판 시즌 1로 출시, 약 3개월 주기 시즌, 한국보다 늦게",
      description: "글로벌 버전은 QoL·밸런스 개선이 포함된 수정판 시즌 1로 출시, 한국 기준 약 1년치 콘텐츠 보유 후 약 3개월 주기로 업데이트——한국과 동시가 아닌 뒤처진 일정",
      intro: "9월 7일 Gamescom 인터뷰에서 NC 프로듀서들이 글로벌 콘텐츠 전개 방식을 설명했습니다: 한국·대만이 처음 출시했던 시즌의 개선판인 시즌 1로 시작하고, 한국 기준 약 1년치 콘텐츠를 보유한 뒤, 출시 후에는 약 3개월마다 새 시즌——한국과 동시가 아니라 늦은 일정으로 업데이트합니다.",
      sourceNote: "Wccftech 2026년 9월 7일 인터뷰(아이온2 팀)를 기반으로, 공식 Steam 스토어 페이지(2026-09-08 확인)와 교차 검증했습니다.",
      keywords: ["아이온2 글로벌 콘텐츠 모델", "아이온2 시즌 1 출시", "아이온2 콘텐츠 주기 3개월", "아이온2 한국보다 늦음", "아이온2 콘텐츠 로드맵"],
      sections: [
        section("season-1-modified", "출시 콘텐츠: 수정판 시즌 1", "Merv Lee Kwai: \"글로벌 버전은 시즌 1로 출시합니다——한국과 대만이 처음 출시했던 시즌이지만, 방금 언급한 QoL·밸런스 개선을 포함한 수정판입니다.\" 글로벌 플레이어는 한국·대만의 출발점에서 약 1년치 수정을 얹은 상태로 시작합니다."),
        section("year-of-content", "약 1년치 콘텐츠 보유", "\"한국에 약 1년치 콘텐츠가 있습니다\"——이를 글로벌 서비스용으로 보유하고, 공개 속도는 플레이어 소비 데이터에 맞춰 조정합니다. 한꺼번에 쏟아내지 않습니다."),
        section("three-month-cadence", "약 3개월 주기 시즌", "\"한국 모델을 밀접하게 따릅니다. 보통 약 3개월마다 새 시즌이 나오고, 글로벌 버전도 비슷할 것입니다.\" 실제 소비 데이터로 주기를 다듬겠다고 덧붙였습니다."),
        section("behind-korea", "한국보다 늦게, 동시는 아님", "\"한국과 동시 업데이트는 매우 어려울 것입니다. 불가능은 아니지만 도전적입니다\"——주로 현지화 부담 때문에 어느 정도 늦은 일정을 유지하는 방침입니다."),
        section("what-it-means", "출시 준비에 주는 의미", "신규 플레이어에게는 1년치 따라잡기가 없어 유리합니다. 한국에서 복귀를 고려하는 플레이어는 글로벌 서비스가 고유한 리듬의 별도 운영임을 감안해야 합니다."),
      ],
    }),
    "zh-hant": articleCopy(newsLabels, "zh-hant", 6, {
      eyebrow: "內容路線",
      title: "Aion 2 全球版內容模型：改良版 Season 1 上線、約三個月一季、落後韓服",
      description: "全球版以含 QoL 與平衡改動的改良版 Season 1 上線，儲備約一年韓服內容，之後按約三個月一季更新——落後韓服而非同步",
      intro: "在 9 月 7 日 Gamescom 專訪中，NCsoft 製作人闡述了 Aion 2 全球版的內容推進方式：以改良版 Season 1（韓服/台服當年首發時的賽季，但已改進）上線，儲備約一年韓服內容，發售後約三個月一季更新——落後韓服而非同日同步。",
      sourceNote: "基於 Wccftech 2026 年 9 月 7 日對 Aion 2 開發團隊的專訪，並與官方 Steam 商店頁（2026-09-08 抓取）交叉核對。賽季日期與內容名稱以營運實況為準。",
      keywords: ["Aion 2 全球版內容模型", "Aion 2 Season 1 上線", "Aion 2 內容節奏 三個月", "Aion 2 落後韓服", "Aion 2 全球版內容路線"],
      sections: [
        section("season-1-modified", "上線內容：改良版 Season 1", ["Merv Lee Kwai 確認全球版不會是韓服現況的直接移植：「全球版將以 Season 1 上線——即韓服與台服最初發布時的賽季，但為改良版，包含此前提到的 QoL 與平衡改進。」", "實際意味著全球玩家從韓服/台服當年的起點開始，外加約一年累積的修復，開局賽季會比當初更精良。"]),
        section("year-of-content", "儲備約一年內容", ["被問及西區版是否包含全部韓服內容時，Kwai 表示韓服「約有價值一年的內容」，團隊會為全球服保留這個內容儲備。", "儲備釋放速度取決於線上玩家數據：團隊計畫觀察玩家消耗速度並據此調整釋放節奏，而非一次性全部放出。"]),
        section("three-month-cadence", "約三個月一季，沿用韓服模式", ["「我們會緊密沿用韓服模式。一般來說他們約三個月一個賽季，全球版也會類似。」Kwai 補充說節奏會按實際消耗數據調整。", "這與本站上線路線圖中的韓服/台服節奏一致，也讓全球玩家對賽季通行證與大更新的節奏有可預期的規律。"]),
        section("behind-korea", "落後韓服，而非同日同步", ["關於追趕韓服，Kwai 直言：「與韓服同日同步對我們來說非常困難。並非不可能，但很有挑戰。」", "工作計畫是保持落後韓服一段時間——「可能更快也可能更慢」——主要因為在地化與發行成本使同步發布很難。"]),
        section("what-it-means", "對上線規劃的意義", ["對新玩家來說這個模型很友好：無需追趕一年進度，Season 1 內容集與 10 月 5 日全新開局的窗口匹配。", "對回流韓服玩家而言，這意味著全球服是節奏獨立的另一套營運——在 10 月 5 日免費制上線前值得想清楚把時間投在哪邊。"]),
      ],
    }),
  },
};
