import { articleCopy, guideLabels, localizations, publishedVerified, section } from "./trending-september-11-shared";
import type { ContentEntry, ContentHeroImage, ContentSource } from "./content-registry";

/* ARTICLE 2 — Skill preset overhaul guide: per-preset skill levels (Sep 9 update) for raid vs open-world loadouts */

const ncOfficialSource: ContentSource = {
  id: "nc-official-a2-update-2026-09-09",
  kind: "official",
  publisher: "NC Corporation",
  label: "NC's AION 2: New Sanctuary 'Snowfield of Sorrow' Update (Press Release)",
  url: "https://about.ncsoft.com/news/article/A2_update_20260909",
  publishedAt: "2026-09-09",
  retrievedAt: "2026-09-11",
  verifiedAt: "2026-09-11",
  localizations: localizations({
    "zh-hans": "NC 的 AION 2：新 Sanctuary「Snowfield of Sorrow」更新（新闻稿）",
    en: "NC's AION 2: New Sanctuary 'Snowfield of Sorrow' Update (Press Release)",
    fr: "AION 2 de NC : mise à jour du Sanctuary « Snowfield of Sorrow » (communiqué)",
    de: "NCs AION 2: Update „Snowfield of Sorrow“ (Pressemitteilung)",
    es: "AION 2 de NC: actualización del Santuario «Snowfield of Sorrow» (nota de prensa)",
    ja: "NCのAION 2：新サンクチュアリ「Snowfield of Sorrow」アップデート（プレスリリース）",
    "pt-br": "AION 2 da NC: atualização do Santuário 'Snowfield of Sorrow' (comunicado)",
    ru: "AION 2 от NC: обновление Святилища «Snowfield of Sorrow» (пресс-релиз)",
    ko: "엔씨 AION 2: 신규 성역 '비탄의 설원' 업데이트 (보도자료)",
    "zh-hant": "NC 的 AION 2：新 Sanctuary「Snowfield of Sorrow」更新（新聞稿）",
  }, "https://about.ncsoft.com/news/article/A2_update_20260909"),
};

const invenSource: ContentSource = {
  id: "inven-snowfield-sorrow-25730-2026-09-08",
  kind: "third-party",
  publisher: "Inven Global",
  label: "'Aion 2' Adds Highest-Difficulty Sanctuary 'Snowfield of Sorrow'",
  url: "https://www.invenglobal.com/articles/25730/aion-2-adds-highest-difficulty-sanctuary-snowfield-of-sorrow",
  publishedAt: "2026-09-08",
  retrievedAt: "2026-09-11",
  verifiedAt: "2026-09-11",
  localizations: localizations({
    "zh-hans": "『Aion 2』新增最高难度 Sanctuary『Snowfield of Sorrow』",
    en: "'Aion 2' Adds Highest-Difficulty Sanctuary 'Snowfield of Sorrow'",
    fr: "« Aion 2 » ajoute le Sanctuary « Snowfield of Sorrow » de plus haute difficulté",
    de: "„Aion 2“ fügt Sanctuary „Snowfield of Sorrow“ mit höchster Schwierigkeit hinzu",
    es: "«Aion 2» añade el Santuario «Snowfield of Sorrow» de máxima dificultad",
    ja: "『Aion 2』に最高難度サンクチュアリ「Snowfield of Sorrow」追加",
    "pt-br": "'Aion 2' adiciona o Santuário 'Snowfield of Sorrow' de maior dificuldade",
    ru: "«Aion 2» добавляет Святилище «Snowfield of Sorrow» высшей сложности",
    ko: "'아이온2' 최고 난도 성역 '비탄의 설원' 추가",
    "zh-hant": "『Aion 2』新增最高難度 Sanctuary『Snowfield of Sorrow』",
  }, "https://www.invenglobal.com/articles/25730/aion-2-adds-highest-difficulty-sanctuary-snowfield-of-sorrow"),
};

const pHero: ContentHeroImage = {
  src: "https://blogfiles.ncsoft.net/news/af7330da-4ff6-4b58-aece-400e6061a3be.jpg",
  width: 1200, height: 630,
  credit: "NC Corporation",
  sourceUrl: "https://aion2.plaync.com/en-us/",
  rights: "linked-official-media",
  translations: {
    "zh-hans": { alt: "Aion 2 技能预设重构指南横幅", caption: "9/9 韩服更新改进技能预设：每个预设现在可保留不同技能等级——切换副本配置与开放世界配置不再重置技能等级。对全球版 10/5 首发同样适用。" },
    en: { alt: "Aion 2 skill preset overhaul guide banner", caption: "The September 9 Korean update improves skill presets: each preset can now keep different skill levels, so switching between raid and open-world loadouts no longer resets your levels. The same QoL improvement ships in the global build on October 5." },
    fr: { alt: "Bannière du guide de refonte des presets de compétences d'Aion 2", caption: "La mise à jour coréenne du 9 septembre améliore les presets : chaque preset conserve désormais des niveaux de compétences différents — changer de build raid / monde ouvert ne réinitialise plus les niveaux. Idem dans le global le 5 octobre." },
    de: { alt: "Banner zum Leitfaden der Skill-Preset-Überarbeitung von Aion 2", caption: "Das koreanische Update vom 9. September verbessert Skill-Presets: Jedes Preset kann nun eigene Skill-Level behalten — der Wechsel zwischen Raid- und Open-World-Builds setzt Level nicht mehr zurück. Kommt auch in der globalen Version am 5. Oktober." },
    es: { alt: "Banner de la guía de la renovación de presets de habilidades de Aion 2", caption: "La actualización coreana del 9 de septiembre mejora los presets: cada preset puede conservar niveles de habilidad distintos — cambiar entre builds de raid y mundo abierto ya no reinicia niveles. Llega también al global el 5 de octubre." },
    ja: { alt: "Aion 2 スキルプリセット改修ガイドバナー", caption: "9月9日の韓国アップデートでスキルプリセットが改善：プリセットごとにスキルレベルを保持できるため、レイド用とオープンワールド用の切替でレベルがリセットされません。グローバル版（10/5）にも同様に搭載されます。" },
    "pt-br": { alt: "Banner do guia da reforma dos presets de habilidades do Aion 2", caption: "A atualização coreana de 9 de setembro melhora os presets: cada preset pode manter níveis de habilidade diferentes — trocar entre builds de raid e mundo aberto não reinicia mais níveis. Também chega ao global em 5 de outubro." },
    ru: { alt: "Баннер гайда по переработке пресетов навыков Aion 2", caption: "Корейское обновление 9 сентября улучшает пресеты навыков: каждый пресет может хранить свои уровни — смена рейд/открытый мир больше не сбрасывает уровни. Это придёт и в глобал 5 октября." },
    ko: { alt: "Aion 2 스킬 프리셋 개편 가이드 배너", caption: "9월 9일 한국 업데이트로 스킬 프리셋이 개선됐습니다: 프리셋마다 스킬 레벨을 다르게 유지할 수 있어 레이드 세팅과 오픈월드 세팅을 오가도 레벨이 초기화되지 않습니다. 글로벌(10/5)에도 동일하게 적용됩니다." },
    "zh-hant": { alt: "Aion 2 技能預設重構指南橫幅", caption: "9/9 韓服更新改進技能預設：每個預設現在可保留不同技能等級——切換副本配置與開放世界配置不再重置技能等級。對全球版 10/5 首發同樣適用。" },
  },
};

export const trendingSeptember11Article2: ContentEntry = {
  section: "guides",
  slug: "aion-2-skill-preset-overhaul-guide",
  schemaType: "Article",
  publishedAt: "2026-09-11",
  updatedAt: "2026-09-11",
  readingMinutes: 5,
  publication: publishedVerified,
  sources: [ncOfficialSource, invenSource],
  heroImage: pHero,
  related: [
    { kind: "content", section: "guides", slug: "aion-2-class-roles-trinity-guide" },
    { kind: "content", section: "guides", slug: "aion-2-korea-server-class-tier-guide" },
    { kind: "content", section: "guides", slug: "aion-2-class-tier-list-guide" },
    { kind: "content", section: "guides", slug: "aion-2-global-qol-no-daily-gates-guide" },
  ],
  translations: {
    en: articleCopy(guideLabels, "en", 5, {
      eyebrow: "QOL GUIDE",
      title: "Aion 2 Skill Preset Overhaul Guide: Per-Preset Skill Levels for Raid and Open-World Loadouts",
      description: "The September 9 update lets each skill preset keep its own skill levels — swapping between raid and open-world builds no longer resets your points; here's how to use it",
      intro: "One of the quiet QoL wins in the September 9 update is a change to skill presets: each preset can now have different skill levels. If you have been rebuilding your skill tree every time you switched from raiding to open-world play, this removes that chore.",
      sourceNote: "Based on NCsoft's official September 9, 2026 press release and Inven Global's September 8, 2026 report (both retrieved September 11, 2026). Applies to the Korean service; the same QoL improvement is included in the global build launching October 5.",
      keywords: ["Aion 2 skill preset overhaul", "Aion 2 per preset skill levels", "Aion 2 raid open world loadout", "Aion 2 skill tree QoL", "Aion 2 September 9 skill preset"],
      sections: [
        section("what-changed", "What Changed on September 9", ["Before the patch, changing your build meant re-assigning skill points when you swapped presets. The September 9 update lets each skill preset keep different skill levels, so switching presets preserves each build's investment.", "It is listed in the official update notes among the raid's quality-of-life changes, and the same improvement is described by Inven Global as part of the September 9 update's skill preset revamp."]),
        section("why-it-matters", "Why It Matters for Your Builds", ["Raiding and open-world life demand different setups: a raid loadout typically focuses your points on the few skills a boss fight keeps asking for, while open-world play favors sustain, mobility, and gathering utility.", "With per-preset levels you can maintain a damage-focused raid profile and a solo/utility profile at the same time — no re-spec fee, no re-pointing session before and after every raid night."]),
        section("how-to-use", "How to Set It Up", ["1. Open the skill preset UI and create separate presets for your roles — for example 'Raid' and 'Open World'; 2. Allocate the skill levels each preset needs once; 3. Switch freely between them — levels stay where you put them; 4. If a balance patch changes your class, revisit both presets rather than only the one you used that week.", "The preset system pairs naturally with the same update's World Marks and dye-pattern size control — build, mark, and style your loadout without friction."]),
        section("tips", "Tips for Raid and Group Play", ["Name your presets clearly (e.g., 'Raid DPS', 'Support', 'Solo') so everyone on a call knows which one you are switching to; coordinate role-specific presets with your Legion so a boss pull does not surprise anyone with a solo build.", "For the first-clear meta on Hard, the winning 10-player compositions ran single tanks and double healers — preset discipline matters exactly in that kind of coordinated group play."]),
        section("global-note", "Note for Global Players", ["The September 9 patch belongs to the Korean service, and the global version launches October 5 with a modified Season 1 that includes this quality-of-life layer.", "If you are planning two builds for launch — one for your first endgame attempts, one for daily open-world play — this QoL change is exactly what makes that split painless."]),
      ],
    }),
    "zh-hans": articleCopy(guideLabels, "zh-hans", 5, {
      eyebrow: "QoL 指南",
      title: "Aion 2 技能预设重构指南：副本与开放世界配置可各自保留技能等级",
      description: "9 月 9 日更新让每个技能预设可各自保留技能等级——副本与开放世界配置切换不再重置加点；本文说明用法",
      intro: "9 月 9 日更新中一个被低估的 QoL 改动是技能预设：每个预设现在可保留不同技能等级。如果你在每次从副本切换到开放世界时都要重新点技能树，这个改动将消除这项苦差。",
      sourceNote: "基于 NCsoft 官方 2026 年 9 月 9 日新闻稿与 Inven Global 2026 年 9 月 8 日报道（均于 2026-09-11 抓取）。适用于韩服；全球版 10 月 5 日上线同样包含此 QoL 改进。",
      keywords: ["Aion 2 技能预设重构", "Aion 2 预设技能等级", "Aion 2 副本 开放世界 配置", "Aion 2 技能树 QoL", "Aion 2 9月9日 技能预设"],
      sections: [
        section("what-changed", "9 月 9 日改了什么", ["改版前，切换预设等于重新分配技能点。9 月 9 日更新让每个技能预设可保留不同技能等级——切换预设时各配置的投入得以保留。", "它被列入官方更新说明的副本 QoL 改动中，Inven Global 也将同一改进描述为 9 月 9 日更新的技能预设重构组成部分。"]),
        section("why-it-matters", "为什么重要", ["副本与开放世界需求不同：副本配置通常把点数集中在 Boss 战反复要求的技能上，开放世界则偏好续航、机动与采集便利。", "有了按预设保留等级，你可以在维护伤害向副本配置的同时维护单人/功能向配置——无需重洗费，也无需每次副本之夜前后重新加点。"]),
        section("how-to-use", "如何设置", ["1. 打开技能预设界面，为你的角色建立独立预设，例如「副本」与「开放世界」；2. 每个预设所需的技能等级只需分配一次；3. 自由切换——等级停留在你放置的位置；4. 若平衡补丁改动你的职业，两个预设都要复查，而不只是当周在用的那个。", "预设系统与同次更新的世界标记、染色图样尺寸自然搭配——构建、标记与外观调整都毫无阻力。"]),
        section("tips", "副本与组队提示", ["给预设起清晰的名字（如「副本 DPS」「辅助」「单人」），让语音里所有人都知道你切到哪个；与军团协调角色专用预设，避免开 Boss 时有人带着单人配置。", "对 Hard 首杀 meta：获胜的 10 人双队配置是单坦克+双治疗——预设纪律恰恰在这种协调组队中重要。"]),
        section("global-note", "对全球玩家的说明", ["9 月 9 日补丁属于韩服；全球版 10 月 5 日以改良版 Season 1 上线，包含这一 QoL 层。", "如果你计划首发就维护两套配置——一套用于首轮终局尝试、一套用于日常开放世界——这项 QoL 改动正是让这种分工零痛苦的关键。"]),
      ],
    }),
    fr: articleCopy(guideLabels, "fr", 5, {
      eyebrow: "GUIDE QOL",
      title: "Guide de la refonte des presets de compétences d'Aion 2 : niveaux par preset pour raid et monde ouvert",
      description: "La mise à jour du 9 septembre permet à chaque preset de conserver ses niveaux de compétences — changer entre raid et monde ouvert ne réinitialise plus votre arbre ; mode d'emploi",
      intro: "L'une des victoires QoL discrètes de la mise à jour du 9 septembre concerne les presets : chaque preset peut désormais avoir des niveaux différents. Plus besoin de re-pointer son arbre à chaque changement raid / monde ouvert.",
      sourceNote: "Basé sur le communiqué officiel de NCsoft du 9 septembre 2026 et le rapport d'Inven Global du 8 septembre 2026 (récupérés le 11 septembre 2026). Inclus dans le global du 5 octobre.",
      keywords: ["Aion 2 refonte presets compétences", "Aion 2 niveaux par preset", "Aion 2 build raid monde ouvert", "Aion 2 QoL arbre de compétences"],
      sections: [
        section("what-changed", "Ce qui a changé le 9 septembre", "Avant, changer de build = re-pointer les points. Depuis le patch, chaque preset conserve ses niveaux de compétences. Noté dans les notes officielles parmi les améliorations QoL ; Inven le décrit comme une refonte des presets."),
        section("why-it-matters", "Pourquoi c'est utile", "Raid et monde ouvert demandent des setups différents (burst vs endurance/utilité). Avec les niveaux par preset, gardez un profil raid DPS et un profil solo/utilitaire — sans frais de re-spéc, sans re-pointer avant/après chaque soirée raid."),
        section("how-to-use", "Configuration", "1. Créez des presets séparés (ex. « Raid », « Open World ») ; 2. Allouez les niveaux une fois ; 3. Basculez librement ; 4. Après un patch d'équilibrage, revoyez les deux presets. Se marie bien avec les marques mondiales et la taille des motifs du même patch."),
        section("tips", "Conseils raid et groupe", "Nommez clairement les presets (« Raid DPS », « Support », « Solo ») ; coordonnez les presets avec votre Légion. Sur la méta du premier clear Hard (deux groupes de 5, un tank, deux soigneurs), la discipline de preset compte précisément."),
        section("global-note", "Note pour le global", "Patch coréen ; le global du 5 octobre (Saison 1 modifiée) inclut cette couche QoL — idéal pour préparer deux builds à la sortie."),
      ],
    }),
    de: articleCopy(guideLabels, "de", 5, {
      eyebrow: "QOL-LEITFADEN",
      title: "Leitfaden zur Skill-Preset-Überarbeitung von Aion 2: eigene Skill-Level pro Preset für Raid und Open World",
      description: "Das Update vom 9. September erlaubt jedem Skill-Preset eigene Skill-Level — der Wechsel zwischen Raid- und Open-World-Builds setzt deinen Baum nicht mehr zurück; so nutzt du es",
      intro: "Ein leiser QoL-Gewinn im Update vom 9. September betrifft Skill-Presets: Jedes Preset kann jetzt unterschiedliche Skill-Level haben. Wer seinen Baum bei jedem Raid/Open-World-Wechsel neu punktet, spart sich das ab jetzt.",
      sourceNote: "Basierend auf der offiziellen NCsoft-Pressemitteilung vom 9. September 2026 und dem Inven-Global-Bericht vom 8. September 2026 (abgerufen am 11. September 2026). Im Global-Start am 5. Oktober enthalten.",
      keywords: ["Aion 2 Skill-Preset Überarbeitung", "Aion 2 Skill-Level pro Preset", "Aion 2 Raid Open World Build", "Aion 2 Skillbaum QoL"],
      sections: [
        section("what-changed", "Was sich am 9. September änderte", "Vorher bedeutete Build-Wechsel Neuverteilen. Seit dem Patch behält jedes Preset seine Skill-Level. In den offiziellen Notizen als QoL gelistet; Inven beschreibt es als Preset-Überarbeitung des Updates."),
        section("why-it-matters", "Warum es zählt", "Raid und Open World verlangen andere Setups (Burst vs. Ausdauer/Utilität). Mit Leveln pro Preset pflegst du Raid-DPS und Solo/Utility parallel — ohne Respec, ohne Neu-Verteilen vor/nach jedem Raid."),
        section("how-to-use", "Einrichtung", "1. Getrennte Presets anlegen (z. B. „Raid“, „Open World“); 2. Level einmal verteilen; 3. Frei wechseln; 4. Nach Balance-Patches beide Presets prüfen. Passt zu Weltmarken und Färbemuster-Größen desselben Patches."),
        section("tips", "Tipps für Raid und Gruppe", "Presets klar benennen („Raid DPS“, „Support“, „Solo“); mit der Legion koordinieren. In der Erster-Clear-Meta (Hard, zwei Gruppen, ein Tank, zwei Heiler) zählt genau solche Preset-Disziplin."),
        section("global-note", "Hinweis für Global", "Koreanischer Patch; der Global-Start am 5. Oktober (modifizierte Season 1) enthält diese QoL-Schicht — ideal für zwei Builds ab Release."),
      ],
    }),
    es: articleCopy(guideLabels, "es", 5, {
      eyebrow: "GUÍA QOL",
      title: "Guía de la renovación de presets de habilidades de Aion 2: niveles por preset para raid y mundo abierto",
      description: "La actualización del 9 de septiembre permite que cada preset conserve sus niveles de habilidad — cambiar entre raid y mundo abierto ya no reinicia tu árbol; así se usa",
      intro: "Una victoria QoL discreta de la actualización del 9 de septiembre afecta a los presets: cada preset puede tener ahora niveles distintos. Si reasignabas tu árbol en cada cambio raid / mundo abierto, esto elimina esa tarea.",
      sourceNote: "Basado en la nota de prensa oficial de NCsoft del 9 de septiembre de 2026 y el informe de Inven Global del 8 de septiembre de 2026 (recuperados el 11 de septiembre de 2026). Incluido en el global del 5 de octubre.",
      keywords: ["Aion 2 renovación presets habilidades", "Aion 2 niveles por preset", "Aion 2 build raid mundo abierto", "Aion 2 QoL árbol de habilidades"],
      sections: [
        section("what-changed", "Qué cambió el 9 de septiembre", "Antes, cambiar de build = reasignar puntos. Desde el parche, cada preset conserva sus niveles. Listado en las notas oficiales como QoL; Inven lo describe como una renovación de presets."),
        section("why-it-matters", "Por qué importa", "Raid y mundo abierto exigen setups distintos (burst vs. resistencia/utilidad). Con niveles por preset mantienes un perfil de raid DPS y otro solo/utilitario — sin re-espec, sin reasignar cada noche de raid."),
        section("how-to-use", "Cómo configurarlo", "1. Crea presets separados (por ej. «Raid», «Open World»); 2. Asigna los niveles una vez; 3. Cambia libremente; 4. Tras parches de equilibrio revisa ambos. Va bien con las marcas mundiales y el tamaño de patrones del mismo parche."),
        section("tips", "Consejos de raid y grupo", "Nombra los presets claramente («Raid DPS», «Support», «Solo»); coordínalos con tu Legión. En la meta del primer clear Hard (dos grupos de 5, un tanque, dos sanadores), la disciplina de presets cuenta."),
        section("global-note", "Nota para el global", "Parche coreano; el global del 5 de octubre (Temporada 1 modificada) incluye esta capa QoL — ideal para dos builds desde el lanzamiento."),
      ],
    }),
    ja: articleCopy(guideLabels, "ja", 5, {
      eyebrow: "QoLガイド",
      title: "Aion 2 スキルプリセット改修ガイド：レイド用とオープンワールド用でレベルを分けられる",
      description: "9月9日アップデートで、スキルプリセットごとにスキルレベルを保持できるように——レイドとオープンワールドの切り替えで振り直しが不要に；使い方を解説",
      intro: "9月9日アップデートの地味なQoL改善の一つがスキルプリセットです：プリセットごとに異なるスキルレベルを保持できるようになりました。レイドからオープンワールドに切り替えるたびにスキルツリーを振り直していた人には、この手間がなくなります。",
      sourceNote: "NC公式2026年9月9日付プレスリリースとInven Global 2026年9月8日付報道（いずれも2026-09-11取得）に基づきます。グローバル版（10/5）にも同様に含まれます。",
      keywords: ["Aion 2 スキルプリセット 改修", "Aion 2 プリセットごと スキルレベル", "Aion 2 レイド オープンワールド 構築", "Aion 2 スキルツリー QoL"],
      sections: [
        section("what-changed", "9月9日に変わったこと", "以前はビルド変更＝スキルポイントの振り直しでした。9月9日アップデートで、プリセットごとに異なるスキルレベルを保持できるようになり、切り替えても投資が保たれます。公式ノートのQoL項目に記載され、Invenもプリセット改修として紹介しています。"),
        section("why-it-matters", "なぜ重要か", "レイドとオープンワールドでは要求が違います（レイドはボス戦向け集中、オープンワールドは継戦・機動力・採集利便）。プリセットごとのレベル維持により、DPS向けレイドプロファイルとソロ/ユーティリティ向けプロファイルを同時に維持できます——リスペック料も、レイド前後の振り直しも不要です。"),
        section("how-to-use", "設定方法", "1. スキルプリセットUIで役割別に分ける（例「レイド」「オープンワールド」）; 2. 各プリセットに必要なレベルを一度だけ割り当て; 3. 自由に切り替え——レベルはそのまま; 4. バランスパッチ後は使っている方だけでなく両方を見直す。同じパッチのワールドマーク・染色パターンサイズと自然に組み合わさります。"),
        section("tips", "レイド・グループ向けのヒント", "プリセット名を明確に（「レイドDPS」「サポート」「ソロ」）し、ボイスで全員に伝わるように。Hard初クリアメタ（10人2PT、単タンク+2ヒーラー）では、まさにこうしたプリセット管理が重要です。"),
        section("global-note", "グローバル向けの注記", "9月9日パッチは韓国サーバー向けですが、グローバル版（10月5日、改良版シーズン1）にもこのQoL層は含まれます。初日から2ビルド（エンドゲーム挑戦用と日常用）を想定している人にはぴったりの改善です。"),
      ],
    }),
    "pt-br": articleCopy(guideLabels, "pt-br", 5, {
      eyebrow: "GUIA DE QOL",
      title: "Guia da reforma dos presets de habilidades do Aion 2: níveis por preset para raid e mundo aberto",
      description: "A atualização de 9 de setembro permite que cada preset mantenha seus níveis de habilidade — trocar entre raid e mundo aberto não reinicia mais sua árvore; como usar",
      intro: "Uma vitória discreta de QoL na atualização de 9 de setembro afeta os presets: cada preset pode agora ter níveis diferentes. Quem reatribuía a árvore a cada mudança raid / mundo aberto deixa de ter esse trabalho.",
      sourceNote: "Baseado no comunicado oficial da NCsoft de 9 de setembro de 2026 e no relatório da Inven Global de 8 de setembro de 2026 (recuperados em 11 de setembro de 2026). Incluído no global de 5 de outubro.",
      keywords: ["Aion 2 reforma presets habilidades", "Aion 2 níveis por preset", "Aion 2 build raid mundo aberto", "Aion 2 QoL árvore de habilidades"],
      sections: [
        section("what-changed", "O que mudou em 9 de setembro", "Antes, mudar de build = reatribuir pontos. Desde o patch, cada preset mantém seus níveis. Listado nas notas oficiais entre as melhorias QoL; a Inven descreve como uma reforma de presets."),
        section("why-it-matters", "Por que importa", "Raid e mundo aberto pedem setups diferentes (burst vs. resistência/utilidade). Com níveis por preset, mantenha um perfil raid DPS e outro solo/utilitário — sem reespec, sem reatribuir antes/depois de cada noite de raid."),
        section("how-to-use", "Como configurar", "1. Crie presets separados (ex. «Raid», «Open World»); 2. Aloque os níveis uma vez; 3. Alterne livremente; 4. Depois de patches de equilíbrio, revise os dois. Combina bem com marcas mundiais e tamanho de padrões do mesmo patch."),
        section("tips", "Dicas de raid e grupo", "Nomeie os presets claramente («Raid DPS», «Suporte», «Solo»); coordene com sua Legião. Na meta do primeiro clear Hard (dois grupos de 5, um tank, dois curandeiros), a disciplina de presets conta."),
        section("global-note", "Nota para o global", "Patch coreano; o global de 5 de outubro (Temporada 1 modificada) inclui essa camada de QoL — ideal para dois builds desde o lançamento."),
      ],
    }),
    ru: articleCopy(guideLabels, "ru", 5, {
      eyebrow: "ГАЙД ПО QOL",
      title: "Гайд по переработке пресетов навыков Aion 2: уровни навыков для рейда и открытого мира",
      description: "Обновление 9 сентября позволяет каждому пресету хранить свои уровни навыков — смена рейд/открытый мир больше не сбрасывает ваше дерево; как пользоваться",
      intro: "Один из тихих QoL-выигрышей обновления 9 сентября — пресеты навыков: теперь у каждого пресета могут быть свои уровни. Тем, кто пересобирал дерево при каждой смене рейд/открытый мир, это убирает рутину.",
      sourceNote: "На основе официального пресс-релиза NCsoft от 9 сентября 2026 г. и отчёта Inven Global от 8 сентября 2026 г. (получены 11 сентября 2026 г.). Включено в глобал 5 октября.",
      keywords: ["Aion 2 переработка пресетов навыков", "Aion 2 уровни по пресетам", "Aion 2 сборка рейд открытый мир", "Aion 2 QoL дерево навыков"],
      sections: [
        section("what-changed", "Что изменилось 9 сентября", "Раньше смена билда = перераспределение очков. С патча каждый пресет хранит свои уровни. Указано в официальных заметках как QoL; Inven описывает как переработку пресетов."),
        section("why-it-matters", "Почему это важно", "Рейд и открытый мир требуют разных сетов (бурст vs. выносливость/утилита). С уровнями по пресетам держите рейд-DPS и соло/утилиту параллельно — без респека и перераспределения."),
        section("how-to-use", "Как настроить", "1. Создайте отдельные пресеты (например «Рейд», «Открытый мир»); 2. Распределите уровни один раз; 3. Переключайтесь свободно; 4. После балансных патчей проверяйте оба. Хорошо сочетается с мировыми метками и размером узоров окраски."),
        section("tips", "Советы для рейда и группы", "Называйте пресеты понятно («Рейд DPS», «Саппорт», «Соло»); координируйте с легионом. В мете первого клира Hard (две партии, один танк, два хила) важна именно дисциплина пресетов."),
        section("global-note", "Примечание для глобала", "Корейский патч; глобал 5 октября (модифицированный Сезон 1) включает этот QoL-слой — идеально для двух билдов с релиза."),
      ],
    }),
    ko: articleCopy(guideLabels, "ko", 5, {
      eyebrow: "QoL 가이드",
      title: "아이온2 스킬 프리셋 개편 가이드: 레이드용·오픈월드용 스킬 레벨을 각각 유지하는 법",
      description: "9월 9일 업데이트로 스킬 프리셋마다 스킬 레벨을 다르게 유지할 수 있게 됐습니다——레이드 세팅과 오픈월드 세팅을 오가도 포인트가 리셋되지 않음; 활용법을 설명합니다",
      intro: "9월 9일 업데이트의 소소하지만 확실한 QoL 개선 중 하나가 스킬 프리셋입니다: 이제 프리셋마다 스킬 레벨을 다르게 유지할 수 있습니다. 레이드에서 오픈월드로 옮길 때마다 스킬 트리를 다시 찍던 수고가 사라집니다.",
      sourceNote: "NC 공식 2026년 9월 9일자 보도자료와 Inven Global 2026년 9월 8일자 보도(모두 2026-09-11 확인)를 기반으로 했습니다. 글로벌(10/5)에도 동일하게 포함됩니다.",
      keywords: ["아이온2 스킬 프리셋 개편", "아이온2 프리셋별 스킬 레벨", "아이온2 레이드 오픈월드 세팅", "아이온2 스킬 트리 QoL", "아이온2 9월9일 스킬 프리셋"],
      sections: [
        section("what-changed", "9월 9일에 바뀐 것", "패치 전에는 빌드를 바꾸면 프리셋 교체 시 스킬 포인트를 다시 배분해야 했습니다. 9월 9일 업데이트부터 프리셋마다 스킬 레벨을 다르게 유지할 수 있어, 프리셋을 바꿔도 각 빌드에 투자한 레벨이 보존됩니다.", "공식 업데이트 노트의 QoL 항목에 포함돼 있으며, Inven Global도 이번 업데이트의 스킬 프리셋 개편으로 소개했습니다."),
        section("why-it-matters", "왜 중요한가", "레이드와 오픈월드 생활은 다른 세팅을 요구합니다: 레이드 세팅은 보스전이 계속 요구하는 스킬에 포인트를 집중하고, 오픈월드는 지속력·기동력·수집 편의를 선호합니다.", "프리셋별 레벨 유지 덕분에 딜 중심 레이드 프로필과 솔로/생활 프로필을 동시에 유지할 수 있습니다——리스펙 비용 없이, 매 레이드 전후 다시 찍을 일도 없습니다."),
        section("how-to-use", "설정 방법", "1. 스킬 프리셋 UI에서 역할별로 별도 프리셋 생성(예: '레이드', '오픈월드'); 2. 각 프리셋에 필요한 스킬 레벨을 한 번만 배분; 3. 자유롭게 전환——레벨은 그 자리에 유지; 4. 밸런스 패치가 직업을 바꾸면 그 주에 쓴 프리셋뿐 아니라 둘 다 복기합니다.", "프리셋 시스템은 같은 업데이트의 월드 징표·염색 패턴 크기와 자연스럽게 어울립니다——빌드·표시·스타일링을 마찰 없이 다룰 수 있습니다."),
        section("tips", "레이드·파티 플레이 팁", "프리셋 이름을 명확히(예: '레이드 딜러', '서포터', '솔로') 지어 보이스에서 모두가 어떤 프리셋인지 알 수 있게 하세요; 혈맹과 역할별 프리셋을 사전에 맞춰 개전 시 솔로 세팅이 섞이지 않게 하세요.", "Hard 최초 격파 메타(10인 2파티, 단일 탱커+이중 힐러)에서 정확히 이런 프리셋 관리가 중요합니다."),
        section("global-note", "글로벌 플레이어 참고", "9월 9일 패치는 한국 서버 대상이며, 글로벌 버전은 10월 5일 수정판 시즌 1로 출시되면서 이 QoL 계층을 함께 담습니다.", "출시 시점에 두 개 빌드——첫 엔드게임 도전용과 일상 오픈월드용——를 준비한다면, 이 QoL 변경이 바로 그 분리를 수월하게 만드는 핵심입니다."),
      ],
    }),
    "zh-hant": articleCopy(guideLabels, "zh-hant", 5, {
      eyebrow: "QoL 指南",
      title: "Aion 2 技能預設重構指南：副本與開放世界配置可各自保留技能等級",
      description: "9 月 9 日更新讓每個技能預設可各自保留技能等級——副本與開放世界配置切換不再重置加點；本文說明用法",
      intro: "9 月 9 日更新中一個被低估的 QoL 改動是技能預設：每個預設現在可保留不同技能等級。如果你在每次從副本切換到開放世界時都要重新點技能樹，這個改動將消除這項苦差。",
      sourceNote: "基於 NCsoft 官方 2026 年 9 月 9 日新聞稿與 Inven Global 2026 年 9 月 8 日報導（均於 2026-09-11 抓取）。適用於韓服；全球版 10 月 5 日上線同樣包含此 QoL 改進。",
      keywords: ["Aion 2 技能預設重構", "Aion 2 預設技能等級", "Aion 2 副本 開放世界 配置", "Aion 2 技能樹 QoL", "Aion 2 9月9日 技能預設"],
      sections: [
        section("what-changed", "9 月 9 日改了什麼", ["改版前，切換預設等於重新分配技能點。9 月 9 日更新讓每個技能預設可保留不同技能等級——切換預設時各配置的投入得以保留。", "它被列入官方更新說明的副本 QoL 改動中，Inven Global 也將同一改進描述為 9 月 9 日更新的技能預設重構組成部分。"]),
        section("why-it-matters", "為什麼重要", ["副本與開放世界需求不同：副本配置通常把點數集中在 Boss 戰反覆要求的技能上，開放世界則偏好續航、機動與採集便利。", "有了按預設保留等級，你可以在維護傷害向副本配置的同時維護單人/功能向配置——無需重洗費，也無需每次副本之夜前後重新加點。"]),
        section("how-to-use", "如何設定", ["1. 開啟技能預設介面，為你的角色建立獨立預設，例如「副本」與「開放世界」；2. 每個預設所需的技能等級只需分配一次；3. 自由切換——等級停留在你放置的位置；4. 若平衡補丁改動你的職業，兩個預設都要複查，而不只是當週在用的那個。", "預設系統與同次更新的世界標記、染色圖樣尺寸自然搭配——構建、標記與外觀調整都毫無阻力。"]),
        section("tips", "副本與組隊提示", ["給預設起清晰的名字（如「副本 DPS」「輔助」「單人」），讓語音裡所有人都知道你切到哪個；與軍團協調角色專用預設，避免開 Boss 時有人帶著單人配置。", "對 Hard 首殺 meta：獲勝的 10 人雙隊配置是單坦克+雙治療——預設紀律恰恰在這種協調組隊中重要。"]),
        section("global-note", "對全球玩家的說明", ["9 月 9 日補丁屬於韓服；全球版 10 月 5 日以改良版 Season 1 上線，包含這一 QoL 層。", "如果你計畫首發就維護兩套配置——一套用於首輪終局嘗試、一套用於日常開放世界——這項 QoL 改動正是讓這種分工零痛苦的關鍵。"]),
      ],
    }),
  },
};