import { articleCopy, guideLabels, localizations, publishedVerified, section } from "./trending-august-18-shared";
import type { ContentEntry, ContentHeroImage, ContentSource } from "./content-registry";

/* ARTICLE 3 — Encroached Deus Research Base expedition guide */

const expeditionSource1: ContentSource = {
  id: "aion2hub-expedition-08-12-2026-08-18",
  kind: "third-party", publisher: "AION2Hub",
  label: "AION 2 Update — August 12, 2026: Encroached Deus Research Base Expedition",
  url: "https://aion2hub.com/updates",
  publishedAt: "2026-08-12",
  retrievedAt: "2026-08-18",
  verifiedAt: "2026-08-18",
  localizations: localizations({
    "zh-hans": "AION 2 更新 — 2026年8月12日：被侵蚀的神之研究所远征",
    en: "AION 2 Update — August 12, 2026: Encroached Deus Research Base Expedition",
    fr: "AION 2 Mise à jour — 12 août 2026 : expédition Base de recherche envahie de Deus",
    de: "AION 2 Update — 12. August 2026: Expedition 'Eingedrungene Deus-Forschungsbasis'",
    es: "AION 2 Actualización — 12 de agosto de 2026: expedición Base de Investigación Deus Invadida",
    ja: "AION 2 アップデート — 2026年8月12日：蝕まれし神の研究基地（Encroached Deus Research Base）遠征",
    "pt-br": "AION 2 Atualização — 12 de agosto de 2026: expedição Base de Pesquisa Deus Invadida",
    ru: "AION 2 Обновление — 12 августа 2026: экспедиция «Захваченная исследовательская база Деус»",
    ko: "AION 2 업데이트 — 2026년 8월 12일: 침식된 신 연구기지 원정대",
    "zh-hant": "AION 2 更新 — 2026年8月12日：被侵蝕的神之研究所遠征",
  }, "https://aion2hub.com/updates"),
};

const expeditionSource2: ContentSource = {
  id: "mmobomb-healer-rework-2026-08-18",
  kind: "third-party", publisher: "MMOBomb",
  label: "NC Shares What Aion 2 Players Can Expect At Launch On First Global Dev Stream",
  url: "https://www.mmobomb.com/news/nc-shares-what-aion-2-players-can-expect-launch-first-global-dev-stream",
  publishedAt: "2026-08-10",
  retrievedAt: "2026-08-18",
  verifiedAt: "2026-08-18",
  localizations: localizations({
    "zh-hans": "NC 首次全球开发者直播：Aion 2 玩家可期待什么",
    en: "NC Shares What Aion 2 Players Can Expect At Launch On First Global Dev Stream",
    fr: "NC partage ce que les joueurs d'Aion 2 peuvent attendre du lancement lors du premier dev stream mondial",
    de: "NC teilt mit, was Aion 2-Spieler beim Launch vom ersten globalen Dev-Stream erwarten können",
    es: "NC comparte lo que los jugadores de Aion 2 pueden esperar en el lanzamiento en el primer dev stream global",
    ja: "NCが初のグローバル開発者ストリームでAion 2プレイヤーが発売時に期待できることを共有",
    "pt-br": "NC compartilha o que os jogadores de Aion 2 podem esperar no lançamento no primeiro dev stream global",
    ru: "NC делится тем, что игроки Aion 2 могут ожидать от запуска на первом глобальном стриме разработчиков",
    ko: "NC, 첫 글로벌 개발자 스트림에서 Aion 2 플레이어가 출시 시 기대할 수 있는 것 공유",
    "zh-hant": "NC 首次全球開發者直播：Aion 2 玩家可期待什麼",
  }, "https://www.mmobomb.com/news/nc-shares-what-aion-2-players-can-expect-launch-first-global-dev-stream"),
};

const expeditionSource3: ContentSource = {
  id: "plaync-kr-notice-2026-08-18",
  kind: "official", publisher: "NCSOFT",
  label: "AION 2 (KR) — 8/12 업데이트 안내",
  url: "https://aion2.plaync.com/ko-kr/board/notice",
  publishedAt: "2026-08-12",
  retrievedAt: "2026-08-18",
  verifiedAt: "2026-08-18",
  localizations: localizations({
    "zh-hans": "AION 2（韩服）— 8/12 更新公告",
    en: "AION 2 (KR) — 8/12 Update Notice",
    fr: "AION 2 (KR) — Avis de mise à jour du 12/08",
    de: "AION 2 (KR) — Update-Hinweis 12/08",
    es: "AION 2 (KR) — Aviso de actualización 12/08",
    ja: "AION 2 (KR) — 8/12 アップデートのお知らせ",
    "pt-br": "AION 2 (KR) — Aviso de atualização 12/08",
    ru: "AION 2 (KR) — Уведомление об обновлении 12/08",
    ko: "AION 2 (KR) — 8/12 업데이트 안내",
    "zh-hant": "AION 2（韓服）— 8/12 更新公告",
  }, "https://aion2.plaync.com/ko-kr/board/notice"),
};

const expeditionHero: ContentHeroImage = {
  src: "https://blogfiles.ncsoft.net/news/af7330da-4ff6-4b58-aece-400e6061a3be.jpg",
  width: 1100, height: 605,
  credit: "NC Corporation",
  sourceUrl: "https://aion2.plaync.com/ko-kr/board/notice",
  rights: "linked-official-media",
  translations: {
    "zh-hans": { alt: "被侵蚀的神之研究所远征配图", caption: "NC 官方配图；该远征于 8 月 12 日加入韩服，与治疗改版同步上线。" },
    en: { alt: "Encroached Deus Research Base expedition image", caption: "Official NC artwork; the expedition joined the KR service on August 12 alongside the healing rework." },
    fr: { alt: "Image de l'expédition Base de recherche de Deus envahie", caption: "Visuel officiel NC ; l'expédition est arrivée sur le service KR le 12 août avec le rework des soins." },
    de: { alt: "Bild der Expedition 'Eingedrungene Deus-Forschungsbasis'", caption: "Offizielles NC-Artwork; die Expedition kam am 12. August zusammen mit dem Heilungs-Rework zum KR-Dienst." },
    es: { alt: "Imagen de la expedición Base de Investigación Deus Invadida", caption: "Arte oficial de NC; la expedición llegó al servicio KR el 12 de agosto junto al rework de sanación." },
    ja: { alt: "蝕まれし神の研究基地遠征画像", caption: "NC公式アートワーク；この遠征は8月12日にヒーリングリワークとともにKRサービスへ追加されました。" },
    "pt-br": { alt: "Imagem da expedição Base de Pesquisa Deus Invadida", caption: "Arte oficial da NC; a expedição chegou ao serviço KR em 12 de agosto junto com o rework de cura." },
    ru: { alt: "Изображение экспедиции «Захваченная исследовательская база Деус»", caption: "Официальный арт NC; экспедиция добавлена на KR 12 августа вместе с реворком лечения." },
    ko: { alt: "침식된 신 연구기지 원정대 이미지", caption: "NC 공식 이미지입니다. 이 원정대는 8월 12일 힐링 리워크와 함께 KR 서비스에 추가되었습니다." },
    "zh-hant": { alt: "被侵蝕的神之研究所遠征配圖", caption: "NC 官方配圖；該遠征於 8 月 12 日加入韓服，與治療改版同步上線。" },
  },
};

export const trendingAugust18Article3: ContentEntry = {
  section: "guides",
  slug: "aion-2-encroached-deus-research-base-expedition-guide",
  schemaType: "Article",
  publishedAt: "2026-08-18",
  updatedAt: "2026-08-18",
  readingMinutes: 5,
  publication: publishedVerified,
  sources: [expeditionSource1, expeditionSource2, expeditionSource3],
  heroImage: expeditionHero,
  related: [
    { kind: "content", section: "news", slug: "aion-2-update-preview-new-dungeons-housing" },
    { kind: "content", section: "guides", slug: "global-launch-dungeon-raid-size-changes" },
    { kind: "content", section: "guides", slug: "draconic-abyss-gear-august-2026" },
  ],
  translations: {
    en: articleCopy(guideLabels, "en", 5, {
      eyebrow: "EXPEDITION GUIDE",
      title: "Aion 2 Expedition Guide: Encroached Deus Research Base & the Post-Patch Endgame",
      description: "The Encroached Deus Research Base expedition arrived with the August 12 patch. Here's what this content adds, how the healing rework changes expedition play, and how it fits the launch endgame.",
      intro: "Expeditions are Aion 2's premiere 5-player PvE content, and the August 12 patch added a new one: the Encroached Deus Research Base. It landed in the same patch as the Cleric/Chanter healing rework, making this expedition the first real test of the new healing dynamics. This guide covers what the new content adds, how to approach it with the new healer tuning, and what it means for global players.",
      sourceNote: "Based on AION2Hub's August 12 patch notes, NCSoft's official update notice, and MMOBomb's dev stream context on launch dungeons. Expedition mechanics reflect the latest confirmed state.",
      keywords: ["Aion 2 expedition", "Aion 2 Encroached Deus Research Base", "Aion 2 dungeon guide", "Aion 2 healer changes", "Aion 2 5-player content"],
      sections: [
        section("what", "The New Expedition", ["The Encroached Deus Research Base is a new expedition added in the August 12, 2026 update. As an expedition, it is tuned around 5-player groups — the standard size for Aion 2's smaller PvE content.", "Its arrival continues NCSoft's pattern of steadily expanding the PvE endgame on the Korean service. The July update had already reshuffled boss tuning in two other late-game expeditions, and the August patch added this new instance on top of new gear tiers."]),
        section("healing", "Playing It With the New Healing Tuning", ["The August 12 patch reshaped healing in the same update: Cleric and Chanter heals now cover a 40m radius but deal 20-50% less output, and healing passives scale with attack power instead of standing alone.", "For expedition play, the practical effect is repositioning: heals reach farther, so groups spread more without losing coverage, but each heal heals for less — which rewards steady casting over panic bursts. Groups that keep positioning clean will see smoother clears than groups that stack and rely on big heals."]),
        section("fit", "Where It Fits in the Endgame", ["Expeditions fit below Trials in Aion 2's difficulty ladder: Trials are the weekly scaled ceiling, while expeditions are the regular 5-player challenge that feeds gear and progression.", "With the August 12 patch also introducing next Draconic and Abyss accessory tiers and the Noiran's Hidden Legacy transcendence, the new expedition slots into an actively growing endgame loop rather than a one-off addition."]),
        section("global", "What This Means for Global Launch", ["This expedition is KR-service content and is not (yet) confirmed for the September 30 global launch. NCSoft's global roadmap is expected to bring post-launch content over time.", "For launch, the takeaway is simpler: expeditions are the core 5-player content at the heart of Aion 2's endgame, and the healing rework previews how healer gameplay will feel on the global build at launch."]),
      ],
    }),
    "zh-hans": articleCopy(guideLabels, "zh-hans", 5, {
      eyebrow: "远征攻略",
      title: "Aion 2 远征攻略：被侵蚀的神之研究所与改版后的后期玩法",
      description: "被侵蚀的神之研究所远征随 8 月 12 日补丁加入。了解这一内容新增了什么、治疗改版如何改变远征玩法，以及它在上线后期玩法中的定位。",
      intro: "远征是 Aion 2 首选的 5 人 PvE 内容，8 月 12 日补丁新增了一座：被侵蚀的神之研究所。它与牧师/吟游星治疗改版同补丁上线，使这座远征成为新治疗机制的首个实战考验。本指南涵盖新增内容、如何适应新治疗调整，以及对全球玩家的意义。",
      sourceNote: "基于 AION2Hub 8 月 12 日补丁说明、NCSoft 官方更新公告及 MMOBomb 开发者直播的上线副本背景。远征机制反映最新确认状态。",
      keywords: ["Aion 2 远征", "Aion 2 被侵蚀的神之研究所", "Aion 2 副本攻略", "Aion 2 治疗改动", "Aion 2 5人内容"],
      sections: [
        section("what", "新远征", ["被侵蚀的神之研究所是 2026 年 8 月 12 日更新新增的远征。作为远征，它以 5 人队伍为标准规模——Aion 2 小型 PvE 内容的标准尺寸。", "它的加入延续了 NCSoft 在韩服稳步扩充 PvE 后期的模式。7 月的更新已调整了另外两座后期远征的 BOSS 配置，8 月补丁在新增装备层级之上添加了这座新实例。"]),
        section("healing", "以新治疗机制游玩", ["8 月 12 日补丁在同期重塑了治疗：牧师与吟游星的治疗现在覆盖 40 米半径，但输出降低 20-50%，且治疗被动改为随攻击力成长。", "对远征玩法的实际影响是重新站位：治疗范围更远，队伍可以更分散而不失覆盖，但每次治疗量更低——奖励持续施法而非爆发救急。站位清晰的队伍将比抱团依赖大治疗的队伍更顺畅地通关。"]),
        section("fit", "在后期玩法中的定位", ["远征在 Aion 2 难度阶梯中位于试炼之下：试炼是周常扩展的天花板，远征是常规 5 人挑战，为装备与养成提供来源。", "随着 8 月 12 日补丁同时引入新的龙族与深渊饰品层级及「诺伊兰的隐秘遗产」超越，新远征融入了一个持续成长的后期循环，而非一次性添加。"]),
        section("global", "对全球上线的意义", ["该远征是韩服内容，（尚未）确认纳入 9 月 30 日全球首发。NCSoft 的全球路线图预计将逐步带来上线后内容。", "对上线技术而言结论更简单：远征是 Aion 2 后期核心的 5 人内容，治疗改版预示了全球版本上线时治疗玩法的体验。"]),
      ],
    }),
    ko: articleCopy(guideLabels, "ko", 5, {
      eyebrow: "원정대 가이드",
      title: "Aion 2 원정대 가이드: 침식된 신 연구기지와 패치 후 엔드게임",
      description: "침식된 신 연구기지 원정대가 8월 12일 패치와 함께 추가되었습니다. 이 콘텐츠가 더하는 것, 힐링 리워크가 원정대 플레이를 바꾸는 방식, 출시 엔드게임에서의 위치를 알아보세요.",
      intro: "원정대는 Aion 2의 대표 5인 PvE 콘텐츠이며, 8월 12일 패치는 새로운 원정대를 추가했습니다: 침식된 신 연구기지. 클레릭/챈터 힐링 리워크와 같은 패치에 출시되어, 이 원정대는 새로운 힐링 다이내믹의 첫 실전 테스트입니다. 이 가이드는 새 콘텐츠의 내용, 새 힐러 튜닝에 맞춘 접근법, 글로벌 플레이어에게 미치는 의미를 다룹니다.",
      sourceNote: "AION2Hub의 8월 12일 패치 노트, NCSoft 공식 업데이트 공지, MMOBomb 개발자 스트림의 출시 던전 맥락에 기반합니다. 원정대 메커니즘은 최신 확인 상태를 반영합니다.",
      keywords: ["Aion 2 원정대", "Aion 2 침식된 신 연구기지", "Aion 2 던전 가이드", "Aion 2 힐러 변경", "Aion 2 5인 콘텐츠"],
      sections: [
        section("what", "새로운 원정대", ["침식된 신 연구기지는 2026년 8월 12일 업데이트에 추가된 새로운 원정대입니다. 원정대로서 5인 파티를 표준 규모로 하며 — Aion 2 소형 PvE 콘텐츠의 표준 크기입니다.", "추가는 NCSoft가 한국 서비스에서 PvE 엔드게임을 꾸준히 확장하는 패턴을 이어갑니다. 7월 업데이트는 다른 후반 원정대 두 곳의 보스 튜닝을 바꿨고, 8월 패치는 새 장비 티어 위에 이 새 인스턴스를 추가했습니다."]),
        section("healing", "새 힐링 튜닝으로 플레이하기", ["8월 12일 패치는 같은 업데이트에서 힐링을 재구성했습니다: 클레릭과 챈터의 힐은 이제 40m 범위를 커버하지만 출력이 20-50% 감소하고, 힐링 패시브는 독립 대신 공격력에 비례합니다.", "원정대 플레이의 실질적 효과는 재배치입니다: 힐이 더 멀리 닿아 파티가 커버리지를 잃지 않고 더 넓게 퍼질 수 있지만, 힐당 회복량은 적어집니다 — 패닉 폭발보다 꾸준한 시전을 보상합니다. 위치 정리를 잘하는 파티가 몰려서 큰 힐에 의존하는 파티보다 매끄러운 클리어를 볼 것입니다."]),
        section("fit", "엔드게임에서의 위치", ["원정대는 Aion 2 난이도 사다리에서 트라이얼 아래에 위치합니다: 트라이얼은 주간 확장 천장이고, 원정대는 장비와 성장을 공급하는 정규 5인 챌린지입니다.", "8월 12일 패치가 다음 드라코닉·심연 액세서리 티어와 노이란의 은밀한 유산 초월을 함께 도입하면서, 새 원정대는 일회성 추가가 아닌 성장하는 엔드게임 루프에 들어갑니다."]),
        section("global", "글로벌 출시에 미치는 의미", ["이 원정대는 KR 서비스 콘텐츠이며 (아직) 9월 30일 글로벌 출시에 확인되지 않았습니다. NCSoft 글로벌 로드맵은 시간이 지나며 출시 후 콘텐츠를 가져올 것으로 예상됩니다.", "출시 관점의 결론은 더 간단합니다: 원정대는 Aion 2 엔드게임의 핵심 5인 콘텐츠이며, 힐링 리워크는 글로벌 빌드에서 힐러 게임플레이가 어떻게 느껴질지 예고합니다."]),
      ],
    }),
    ja: articleCopy(guideLabels, "ja", 5, {
      eyebrow: "遠征ガイド",
      title: "Aion 2 遠征ガイド：蝕まれし神の研究基地とパッチ後のエンドゲーム",
      description: "蝕まれし神の研究基地（Encroached Deus Research Base）遠征が8月12日パッチで追加されました。このコンテンツがもたらすもの、ヒーリングリワークが遠征プレイを変える方法、ローンチエンドゲームでの位置づけを解説します。",
      intro: "遠征は Aion 2 の代表的な5人 PvE コンテンツであり、8月12日パッチは新しい遠征を追加しました：蝕まれし神の研究基地。クレリック/チャンターのヒーリングリワークと同じパッチに登場し、この遠征は新しいヒーリングダイナミクスの最初の実戦テストです。このガイドは新コンテンツの内容、新しいヒーラーチューニングへの対応、グローバルプレイヤーへの意味を扱います。",
      sourceNote: "AION2Hub の8月12日パッチノート、NCSoft 公式アップデート通知、MMOBomb 開発者ストリームのローンチダンジョン文脈に基づきます。遠征メカニクスは最新確認状態を反映しています。",
      keywords: ["Aion 2 遠征", "Aion 2 蝕まれし神の研究基地", "Aion 2 ダンジョンガイド", "Aion 2 ヒーラー変更", "Aion 2 5人コンテンツ"],
      sections: [
        section("what", "新しい遠征", ["蝕まれし神の研究基地は2026年8月12日アップデートで追加された新しい遠征です。遠征として5人パーティを標準規模とします — Aion 2 の小型 PvE コンテンツの標準サイズです。", "その登場は、NCSoft が韓国サービスで PvE エンドゲームを着実に拡張するパターンの継続です。7月アップデートは他2つの後半遠征のボス調整を変え、8月パッチは新しい装備ティアの上にこの新しいインスタンスを追加しました。"]),
        section("healing", "新しいヒーリングチューニングでプレイする", ["8月12日パッチは同じアップデートでヒーリングを再構築しました：クレリックとチャンターのヒールは40m範囲をカバーする一方、出力が20-50%減少し、ヒールパッシブは独立ではなく攻撃力に比例します。", "遠征プレイへの実質的な効果は再配置です：ヒールがより遠くに届き、パーティはカバレッジを失わずに広がれますが、ヒールあたりの回復量は少なくなり、パニックバーストより安定した詠唱が報われます。位置取りの良いパーティは、固まって大きなヒールに頼るパーティよりスムーズなクリアが見られます。"]),
        section("fit", "エンドゲームでの位置づけ", ["遠征は Aion 2 の難易度ラダーでトライアルの下に位置します：トライアルは週間スケーリングの天井であり、遠征は装備と成長を供給する通常の5人チャレンジです。", "8月12日パッチが次のドラコニック・アビスアクセサリーティアとノイランの秘められた遺産（トランセンデンス）を同時導入したことで、新遠征は一回限りの追加ではなく、成長するエンドゲームループに組み込まれます。"]),
        section("global", "グローバルローンチへの意味", ["この遠征は KR サービスのコンテンツであり、9月30日のグローバルローンチには（まだ）確認されていません。NCSoft のグローバルロードマップは時間をかけてローンチ後コンテンツをもたらすと予想されます。", "ローンチの観点では結論はシンプルです：遠征は Aion 2 エンドゲームの核となる5人コンテンツであり、ヒーリングリワークはグローバルビルドのローンチ時にヒーラープレイがどう感じられるかを予告します。"]),
      ],
    }),
    fr: articleCopy(guideLabels, "fr", 5, {
      eyebrow: "GUIDE EXPÉDITION",
      title: "Guide d'expédition Aion 2 : Base de recherche envahie de Deus et l'endgame post-patch",
      description: "L'expédition Base de recherche envahie de Deus est arrivée avec le patch du 12 août. Ce qu'elle apporte, l'impact du rework des soins et sa place dans l'endgame.",
      intro: "Les expéditions sont le contenu PvE 5 joueurs phare d'Aion 2. La Base de recherche envahie de Deus est arrivée avec le patch du 12 août, en même temps que le rework des soins.",
      sourceNote: "Basé sur les notes de patch AION2Hub du 12 août, l'avis officiel NCSoft et le contexte de MMOBomb.",
      keywords: ["Aion 2 expédition", "Aion 2 Base de recherche Deus", "Aion 2 guide donjon", "Aion 2 soins"],
      sections: [
        section("what", "La nouvelle expédition", ["Ajoutée le 12 août 2026, calibrée pour 5 joueurs. Elle poursuit l'expansion régulière de l'endgame PvE sur le service coréen."]),
        section("healing", "Jouer avec le nouveau système de soins", ["Portée 40 m, -20 à 50 % de puissance, passives liées à la puissance d'attaque. Récompense un positionnement propre et un rythme de soins régulier."]),
        section("fit", "Place dans l'endgame", ["Sous les procès dans l'échelle de difficulté ; alimente le cycle d'équipement et de progression."]),
        section("global", "Pour le lancement global", ["Contenu KR non confirmé pour le 30 septembre ; attendu via la feuille de route mondiale après le lancement."]),
      ],
    }),
    de: articleCopy(guideLabels, "de", 5, {
      eyebrow: "EXPEDITIONS-GUIDE",
      title: "Aion 2 Expeditions-Guide: Eingedrungene Deus-Forschungsbasis & das Endgame nach dem Patch",
      description: "Die Expedition 'Eingedrungene Deus-Forschungsbasis' kam mit dem Patch vom 12. August. Was sie bietet, wie das Heilungs-Rework Expeditionen verändert und ihre Rolle im Endgame.",
      intro: "Expeditionen sind Aion 2s wichtigster 5-Spieler-PvE-Inhalt. Die Eingedrungene Deus-Forschungsbasis kam mit dem Patch vom 12. August, im selben Update wie das Heilungs-Rework.",
      sourceNote: "Basierend auf AION2Hub-Patchnotes vom 12. August, der offiziellen NCSoft-Mitteilung und dem MMOBomb-Kontext.",
      keywords: ["Aion 2 Expedition", "Aion 2 Deus-Forschungsbasis", "Aion 2 Dungeon-Guide", "Aion 2 Heilung"],
      sections: [
        section("what", "Die neue Expedition", ["Hinzugefügt am 12. August 2026, auf 5 Spieler ausgelegt. Sie setzt die stetige Erweiterung des PvE-Endgames auf dem koreanischen Dienst fort."]),
        section("healing", "Spielen mit dem neuen Heilungs-System", ["40 m Reichweite, -20 bis 50 % Wirkung, passive Werte an Angriffskraft gekoppelt. Belohnt sauberes Positionieren und gleichmäßiges Heilen."]),
        section("fit", "Rolle im Endgame", ["Unterhalb der Trials in der Schwierigkeitsskala; speist den Ausrüstungs- und Fortschrittszyklus."]),
        section("global", "Für den globalen Launch", ["KR-Inhalt, für den 30. September nicht bestätigt; nach dem Launch über die globale Roadmap erwartet."]),
      ],
    }),
    es: articleCopy(guideLabels, "es", 5, {
      eyebrow: "GUÍA DE EXPEDICIÓN",
      title: "Guía de expedición de Aion 2: Base de Investigación Deus Invadida y el endgame post-parche",
      description: "La expedición Base de Investigación Deus Invadida llegó con el parche del 12 de agosto. Qué aporta, cómo cambia el rework de sanación el juego en expediciones y su lugar en el endgame.",
      intro: "Las expediciones son el contenido PvE de 5 jugadores insignia de Aion 2. La Base de Investigación Deus Invadida llegó con el parche del 12 de agosto, junto al rework de sanación.",
      sourceNote: "Basado en las notas de parche de AION2Hub del 12 de agosto, el aviso oficial de NCSoft y el contexto de MMOBomb.",
      keywords: ["Aion 2 expedición", "Aion 2 Base de Investigación Deus", "Aion 2 guía de mazmorra", "Aion 2 sanación"],
      sections: [
        section("what", "La nueva expedición", ["Añadida el 12 de agosto de 2026, calibrada para 5 jugadores. Continúa la expansión constante del endgame PvE en el servicio coreano."]),
        section("healing", "Jugar con el nuevo sistema de sanación", ["Alcance de 40 m, -20 a 50 % de potencia, pasivas ligadas al poder de ataque. Recompensa un posicionamiento limpio y curación constante."]),
        section("fit", "Lugar en el endgame", ["Por debajo de los juicios en la escala de dificultad; alimenta el ciclo de equipo y progresión."]),
        section("global", "Para el lanzamiento global", ["Contenido KR no confirmado para el 30 de septiembre; esperado vía la hoja de ruta global tras el lanzamiento."]),
      ],
    }),
    "pt-br": articleCopy(guideLabels, "pt-br", 5, {
      eyebrow: "GUIA DE EXPEDIÇÃO",
      title: "Guia de expedição de Aion 2: Base de Pesquisa Deus Invadida e o endgame pós-patch",
      description: "A expedição Base de Pesquisa Deus Invadida chegou com o patch de 12 de agosto. O que ela traz, como o rework de cura muda as expedições e seu lugar no endgame.",
      intro: "Expedições são o conteúdo PvE de 5 jogadores de destaque de Aion 2. A Base de Pesquisa Deus Invadida chegou com o patch de 12 de agosto, junto ao rework de cura.",
      sourceNote: "Baseado nas notas de patch da AION2Hub de 12 de agosto, no aviso oficial da NCSoft e no contexto da MMOBomb.",
      keywords: ["Aion 2 expedição", "Aion 2 Base de Pesquisa Deus", "Aion 2 guia de masmorra", "Aion 2 cura"],
      sections: [
        section("what", "A nova expedição", ["Adicionada em 12 de agosto de 2026, calibrada para 5 jogadores. Continua a expansão constante do endgame PvE no serviço coreano."]),
        section("healing", "Jogar com o novo sistema de cura", ["Alcance de 40 m, -20 a 50 % de poder, passivas ligadas ao poder de ataque. Recompensa posicionamento limpo e cura constante."]),
        section("fit", "Lugar no endgame", ["Abaixo dos Trials na escala de dificuldade; alimenta o ciclo de equipamento e progressão."]),
        section("global", "Para o lançamento global", ["Conteúdo KR não confirmado para 30 de setembro; esperado via roteiro global após o lançamento."]),
      ],
    }),
    ru: articleCopy(guideLabels, "ru", 5, {
      eyebrow: "ГАЙД ПО ЭКСПЕДИЦИИ",
      title: "Гайд по экспедиции Aion 2: Захваченная исследовательская база Деус и эндгейм после патча",
      description: "Экспедиция «Захваченная исследовательская база Деус» появилась с патчем от 12 августа. Что она даёт, как реворк лечения меняет экспедиции и её место в эндгейме.",
      intro: "Экспедиции — флагманский PvE-контент Aion 2 на 5 игроков. «База Деус» появилась с патчем от 12 августа, вместе с реворком лечения.",
      sourceNote: "На основе патч-ноутов AION2Hub от 12 августа, официального уведомления NCSoft и контекста MMOBomb.",
      keywords: ["Aion 2 экспедиция", "Aion 2 база Деус", "Aion 2 гайд по подземелью", "Aion 2 лечение"],
      sections: [
        section("what", "Новая экспедиция", ["Добавлена 12 августа 2026 года, рассчитана на 5 игроков. Продолжает постоянное расширение PvE-эндгейма на корейском сервисе."]),
        section("healing", "Игра с новой системой лечения", ["Радиус 40 м, −20–50 % мощности, пассивки привязаны к силе атаки. Поощряет чистое позиционирование и стабильное лечение."]),
        section("fit", "Место в эндгейме", ["Ниже испытаний по шкале сложности; питает цикл экипировки и прогрессии."]),
        section("global", "Для глобального запуска", ["KR-контент, не подтверждённый к 30 сентября; ожидается после запуска по глобальной дорожной карте."]),
      ],
    }),
    "zh-hant": articleCopy(guideLabels, "zh-hant", 5, {
      eyebrow: "遠征攻略",
      title: "Aion 2 遠征攻略：被侵蝕的神之研究所與改版後的後期玩法",
      description: "被侵蝕的神之研究所遠征隨 8 月 12 日補丁加入。了解這一內容新增了什麼、治療改版如何改變遠征玩法，以及它在上線後期玩法中的定位。",
      intro: "遠征是 Aion 2 首選的 5 人 PvE 內容，8 月 12 日補丁新增了一座：被侵蝕的神之研究所。它與牧師/吟遊星治療改版同補丁上線，使這座遠征成為新治療機制的首個實戰考驗。本指南涵蓋新增內容、如何適應新治療調整，以及對全球玩家的意義。",
      sourceNote: "基於 AION2Hub 8 月 12 日補丁說明、NCSoft 官方更新公告及 MMOBomb 開發者直播的上線副本背景。遠征機制反映最新確認狀態。",
      keywords: ["Aion 2 遠征", "Aion 2 被侵蝕的神之研究所", "Aion 2 副本攻略", "Aion 2 治療改動", "Aion 2 5人內容"],
      sections: [
        section("what", "新遠征", ["被侵蝕的神之研究所是 2026 年 8 月 12 日更新新增的遠征。作為遠征，它以 5 人隊伍為標準規模——Aion 2 小型 PvE 內容的標準尺寸。", "它的加入延續了 NCSoft 在韓服穩步擴充 PvE 後期的模式。7 月的更新已調整了另外兩座後期遠征的 BOSS 配置，8 月補丁在新增裝備層級之上添加了這座新實例。"]),
        section("healing", "以新治療機制遊玩", ["8 月 12 日補丁在同期重塑了治療：牧師與吟遊星的治療現在覆蓋 40 米半徑，但輸出降低 20-50%，且治療被動改為隨攻擊力成長。", "對遠征玩法的實際影響是重新站位：治療範圍更遠，隊伍可以更分散而不失覆蓋，但每次治療量更低——獎勵持續施法而非爆發救急。站位清晰的隊伍將比抱團依賴大治療的隊伍更順暢地通關。"]),
        section("fit", "在後期玩法中的定位", ["遠征在 Aion 2 難度階梯中位於試煉之下：試煉是週常擴展的天花板，遠征是常規 5 人挑戰，為裝備與養成提供來源。", "隨著 8 月 12 日補丁同時引入新的龍族與深淵飾品層級及「諾伊蘭的隱秘遺產」超越，新遠征融入了一個持續成長的後期循環，而非一次性添加。"]),
        section("global", "對全球上線的意義", ["該遠征是韓服內容，（尚未）確認納入 9 月 30 日全球首發。NCSoft 的全球路線圖預計將逐步帶來上線後內容。", "對上線技術而言結論更簡單：遠征是 Aion 2 後期核心的 5 人內容，治療改版預示了全球版本上線時治療玩法的體驗。"]),
      ],
    }),
  },
};