import { articleCopy, guideLabels, localizations, publishedVerified, section } from "./trending-august-30-shared";
import type { ContentEntry, ContentHeroImage, ContentSource } from "./content-registry";

/* ARTICLE 5 — No auto-combat & anti-grind design philosophy from the Gamescom Q&A */

const agSource1: ContentSource = {
  id: "inthegame-gamescom-preview-2026-08-30-e",
  kind: "third-party", publisher: "intheGame",
  label: "Preview | AION 2 op Gamescom 2026 (combat & time-respect design)",
  url: "https://inthegame.nl/2026/08/29/preview-aion-2-op-gamescom-2026/",
  publishedAt: "2026-08-29",
  retrievedAt: "2026-08-29",
  verifiedAt: "2026-08-29",
  localizations: localizations({
    "zh-hans": "前瞻 | Gamescom 2026 的 Aion 2（战斗与尊重时间的设计）",
    en: "Preview | AION 2 op Gamescom 2026 (combat & time-respect design)",
    fr: "Aperçu | AION 2 au Gamescom 2026 (combat et respect du temps)",
    de: "Vorschau | AION 2 auf der Gamescom 2026 (Kampf & zeitschonendes Design)",
    es: "Impresión | AION 2 en Gamescom 2026 (combate y diseño que respeta el tiempo)",
    ja: "プレビュー | Gamescom 2026 の Aion 2（戦闘と時間尊重の設計）",
    "pt-br": "Impressão | AION 2 na Gamescom 2026 (combate e design que respeita o tempo)",
    ru: "Превью | Aion 2 на Gamescom 2026 (бой и дизайн, уважающий время)",
    ko: "프리뷰 | Gamescom 2026의 Aion 2 (전투·시간 존중 설계)",
    "zh-hant": "前瞻 | Gamescom 2026 的 Aion 2（戰鬥與尊重時間的設計）",
  }, "https://inthegame.nl/2026/08/29/preview-aion-2-op-gamescom-2026/"),
};

const agSource2: ContentSource = {
  id: "steam-dev-message-2026-08-30",
  kind: "third-party", publisher: "Steam",
  label: "AION 2 — A Message from the Developers (design philosophy)",
  url: "https://steamcommunity.com/games/3393110/announcements/detail/1836506165549225",
  publishedAt: "2026-06-25",
  retrievedAt: "2026-08-29",
  verifiedAt: "2026-08-29",
  localizations: localizations({
    "zh-hans": "AION 2——开发者来信（设计理念）",
    en: "AION 2 — A Message from the Developers (design philosophy)",
    fr: "Aion 2 — Un message des développeurs (philosophie de design)",
    de: "Aion 2 — Eine Botschaft der Entwickler (Design-Philosophie)",
    es: "Aion 2 — Un mensaje de los desarrolladores (filosofía de diseño)",
    ja: "Aion 2 — 開発者からのメッセージ（デザイン哲学）",
    "pt-br": "Aion 2 — Mensagem dos desenvolvedores (filosofia de design)",
    ru: "Aion 2 — Письмо разработчиков (философия дизайна)",
    ko: "Aion 2 — 개발자 메시지 (디자인 철학)",
    "zh-hant": "AION 2——開發者來信（設計理念）",
  }, "https://steamcommunity.com/games/3393110/announcements/detail/1836506165549225"),
};

const agHero: ContentHeroImage = {
  src: "https://blogfiles.ncsoft.net/news/af7330da-4ff6-4b58-aece-400e6061a3be.jpg",
  width: 1100, height: 605,
  credit: "NC Corporation",
  sourceUrl: "https://aion2.plaync.com/ja-jp/board/notice/list",
  rights: "linked-official-media",
  translations: {
    "zh-hans": { alt: "Aion 2 反日常设计解析配图", caption: "NC 官方配图；Gamescom 2026 开发者问答确认 Aion 2 无自动战斗、反对把游戏变成每日义务，并提供账号级共享的副职进度。" },
    en: { alt: "Aion 2 anti-grind design analysis image", caption: "Official NC artwork; the Gamescom 2026 developer Q&A confirmed no auto-combat, an anti-daily-obligation stance, and account-wide alt progression." },
    fr: { alt: "Image de l'analyse anti-grind d'Aion 2", caption: "Visuel officiel NC ; le Q&A Gamescom 2026 confirme pas d'auto-combat, une position anti-obligation quotidienne et une progression de rerolls partagée." },
    de: { alt: "Bild zur Aion-2-Anti-Grind-Analyse", caption: "Offizielles NC-Artwork; das Gamescom-2026-Q&A bestätigt keinen Auto-Kampf, eine Anti-Tagespflicht-Haltung und geteilte Alt-Progression." },
    es: { alt: "Imagen del análisis anti-grind de Aion 2", caption: "Arte oficial de NC; el Q&A de Gamescom 2026 confirma sin auto-combate, postura contra la obligación diaria y progresión compartida de alts." },
    ja: { alt: "Aion 2 反デイリー設計分析画像", caption: "NC公式アートワーク；Gamescom 2026 の開発者Q&Aは、オートなし・日課義務化の回避・アカウント共有のサブ進行を確認しました。" },
    "pt-br": { alt: "Imagem da análise anti-grind do Aion 2", caption: "Arte oficial da NC; o Q&A da Gamescom 2026 confirma sem auto-combate, postura contra a obrigação diária e progressão compartilhada de alts." },
    ru: { alt: "Изображение анти-гринд анализа Aion 2", caption: "Официальный арт NC; Q&A Gamescom 2026 подтверждает отсутствие авто-боя, позицию против ежедневных обязанностей и общий прогресс альтов." },
    ko: { alt: "Aion 2 반-일퀘 설계 분석 이미지", caption: "NC 공식 이미지입니다. Gamescom 2026 개발자 Q&A는 오토 없음, 일일 의무화 회피, 계정 공유 서브 진행을 확인했습니다." },
    "zh-hant": { alt: "Aion 2 反日常設計解析配圖", caption: "NC 官方配圖；Gamescom 2026 開發者問答確認 Aion 2 無自動戰鬥、反對把遊戲變成每日義務，並提供帳號級共享的副職進度。" },
  },
};

export const trendingAugust30Article5: ContentEntry = {
  section: "guides",
  slug: "aion-2-no-autoplay-anti-grind-design-guide",
  schemaType: "Article",
  publishedAt: "2026-08-29",
  updatedAt: "2026-08-29",
  readingMinutes: 4,
  publication: publishedVerified,
  sources: [agSource1, agSource2],
  heroImage: agHero,
  related: [
    { kind: "content", section: "guides", slug: "aion-2-great-rebalance-patch-guide" },
    { kind: "content", section: "guides", slug: "aion-2-inheritance-transcendence-guide" },
    { kind: "content", section: "guides", slug: "aion-2-class-tier-list-guide" },
    { kind: "content", section: "guides", slug: "aion-2-endgame-path-guide" },
  ],
  translations: {
    en: articleCopy(guideLabels, "en", 4, {
      eyebrow: "DESIGN PHILOSOPHY",
      title: "Aion 2's Anti-Grind Design: No Auto-Combat, No Daily Checklist, Account-Wide Alts",
      description: "The Gamescom 2026 developer Q&A confirmed three of the most-wanted design choices: no auto-combat, an explicit stance against daily-obligation design, and account-wide alt progression. Here is what each means for launch.",
      intro: "Aion 2's developers used the Gamescom 2026 Q&A to confirm three design choices that cut against typical Korean MMO habits: no auto-combat at all, an explicit refusal to turn the game into a daily obligation, and account-wide progression that makes alts painless. Each of these is a real statement about how the launch game is meant to be played. This guide breaks them down and what they imply.",
      sourceNote: "Based on intheGame's Gamescom 2026 developer Q&A (August 29, 2026) and the developers' earlier design-message on Steam (June 25, 2026).",
      keywords: ["Aion 2 no auto-combat", "Aion 2 no auto play", "Aion 2 daily quests", "Aion 2 alt progression", "Aion 2 anti-grind"],
      sections: [
        section("no-autoplay", "No Auto-Combat, Full Manual Control", ["The demo confirmed there is no auto-combat — every action is manual, reinforcing Aion 2's action-MMO positioning.", "This is a meaningful differentiator: the auto-play that defines much of the modern Korean MMO market is absent by design.", "Expect combat to reward active input — positioning, timing and target selection matter more than gear-checking."]),
        section("no-dailies", "No Daily-Obligation Design", ["The developers explicitly want to avoid the game feeling like a daily obligation — no endless streams of dailies, weeklies or live-service checklists.", "Instead, content is meant to be worthwhile on its own: valuable rewards, not filler to log in for.", "This pairs with the exploration philosophy: curiosity pulls you in, not a checklist of chores."]),
        section("alt-progression", "Account-Wide Alt Progression", ["Progression for alts is account-wide (compared to Guild Wars 2 in the preview): starting a new class does not mean redoing all progression systems.", "This makes experimenting with classes genuinely attractive — your second, third or tenth class builds on the progress you already made.", "Combined with the clear class roles, it lowers the fear of 'wasting' a character on the wrong class at launch."]),
        section("implications", "What It Means at Launch", ["For time-pressed players this is a strong pitch: a game that respects your time, with no obligation to log in daily to avoid falling behind.", "For progression-focused players, account-wide alts mean the roster is the account — invest once, benefit across classes.", "Watch the September 17–18 launch scale test to confirm the anti-daily design holds up in practice."]),
      ],
    }),
    "zh-hans": articleCopy(guideLabels, "zh-hans", 4, {
      eyebrow: "设计理念",
      title: "Aion 2 反日常设计：无自动战斗、无每日清单、账号级副职",
      description: "Gamescom 2026 开发者问答确认三项最受期待的设计选择：无自动战斗、明确反对日常义务化、账号级共享副职进度。以下为各自对上线版本的意义。",
      intro: "Aion 2 开发者借 Gamescom 2026 问答确认三项反韩式 MMO 习惯的设计选择：完全无自动战斗、明确拒绝把游戏变成每日义务、账号级共享进度让副职无痛。每一项都是对上线游戏玩法的真实表态。本指南拆解并说明其含义。",
      sourceNote: "基于 intheGame 的 Gamescom 2026 开发者问答（2026-08-29）与开发者 6 月 25 日于 Steam 发布的设计理念来信。",
      keywords: ["Aion 2 无自动战斗", "Aion 2 无自动游玩", "Aion 2 每日任务", "Aion 2 副职进度", "Aion 2 反日常"],
      sections: [
        section("no-autoplay", "无自动战斗，全手动", ["演示确认没有自动战斗——每个动作皆手动，强化 Aion 2 的动作 MMO 定位。", "这是有意义的差异点：定义现代韩式 MMO 市场的自动玩法被刻意剔除。", "预期战斗奖励主动输入——站位、时机与目标选择比装备检查更重要。"]),
        section("no-dailies", "反对日常义务化", ["开发者明确希望避免游戏像日常义务——没有无穷尽的每日/每周/服务式清单。", "转而让内容本身有价值：奖励值得，而非为登录而登录的填充物。", "这与探索理念相配：好奇心牵引你进入，而非琐事清单。"]),
        section("alt-progression", "账号级共享副职进度", ["副职进度为账号级（前瞻类比《激战2》）：开新职业不必重做所有养成系统。", "这让多职业试验真正有吸引力——第二个、第三个乃至第十个职业都建立在此前进度之上。", "结合清晰职业定位，降低上线时『选错职业浪费角色』的顾虑。"]),
        section("implications", "上线版本的含义", ["对时间有限的玩家是强力卖点：尊重时间的游戏，无需为落后而每日登录。", "对养成型玩家，账号级副职意味着名册即账号——投入一次，全职业受益。", "关注 9 月 17-18 日上线规模测试确认反日常设计在实战中成立。"]),
      ],
    }),
    ko: articleCopy(guideLabels, "ko", 4, {
      eyebrow: "디자인 철학",
      title: "Aion 2 반-그라인드 설계: 오토 없음, 일일 체크리스트 없음, 계정 공유 서브",
      description: "Gamescom 2026 개발자 Q&A가 가장 원했던 설계 선택 3가지를 확인했습니다: 오토 전투 없음, 일일 의무화에 대한 명확한 반대, 계정 공유 서브 진행.",
      intro: "개발진은 Gamescom 2026 Q&A에서 한국 MMO 관행에 반하는 세 가지 설계를 확인했습니다: 완전한 오토 없음, 일일 의무화 거부, 그리고 서브 클래스 진행의 계정 공유. 각각이 출시 게임에 어떤 의미인지 정리합니다.",
      sourceNote: "intheGame의 Gamescom 2026 개발자 Q&A(2026-08-29)와 6월 25일 Steam의 개발자 메시지 기반.",
      keywords: ["Aion 2 오토 없음", "Aion 2 오토 플레이 없음", "Aion 2 일일 퀘스트", "Aion 2 서브 진행", "Aion 2 반-그라인드"],
      sections: [
        section("no-autoplay", "오토 없음, 완전 수동", "데모가 오토 전투 없음을 확인했습니다. 액션 MMO 포지셔닝을 강화하며, 한국 MMO 시장의 상징인 오토 플레이가 의도적으로 제외됐습니다. 위치·타이밍·표적 선택이 중요해집니다."),
        section("no-dailies", "일일 의무화 반대", "개발진은 게임이 일일 의무처럼 느껴지길 원하지 않습니다. 무한한 데일리/위클리/라이브 서비스 체크리스트 대신 그 자체로 가치 있는 콘텐츠를 지향합니다. 탐험 철학과 맞물립니다."),
        section("alt-progression", "계정 공유 서브 진행", "서브 진행이 계정 단위로 공유됩니다(길드워2 유사). 새 클래스를 시작해도 진행 시스템을 다시 할 필요가 없어 다클래스 실험이 매력적입니다."),
        section("implications", "출시 시 의미", "시간이 부족한 플레이어에게 강력한 제안입니다. 계정 단위 진행은 '한 번 투자, 전 클래스 혜택'입니다. 9월 17~18일 LST에서 실전 확인하세요."),
      ],
    }),
    ja: articleCopy(guideLabels, "ja", 4, {
      eyebrow: "デザイン哲学",
      title: "Aion 2 の反-グラインド設計：オートなし、日課なし、アカウント共有サブ",
      description: "Gamescom 2026 の開発者Q&Aが最も望まれた設計3つを確認しました：オート戦闘なし、日課義務化への明確な反対、アカウント共有のサブ進行。",
      intro: "開発陣は Gamescom 2026 のQ&Aで、韓国MMOの慣習に反する3つの設計を確認しました：完全なオートなし、日課義務化の拒否、そしてサブクラス進行のアカウント共有。それぞれが発売時の意味を持ちます。",
      sourceNote: "intheGame の Gamescom 2026 開発者Q&A（2026-08-29）と、6月25日付 Steam の開発者メッセージに基づきます。",
      keywords: ["Aion 2 オートなし", "Aion 2 オートプレイなし", "Aion 2 デイリー", "Aion 2 サブ進行", "Aion 2 反グラインド"],
      sections: [
        section("no-autoplay", "オートなし、完全手動", "デモがオート戦闘なしを確認。アクションMMOの位置づけを強化し、韓国MMO市場の象徴であるオートプレイが意図的に除外されています。位置取り・タイミング・標的選択が重要に。"),
        section("no-dailies", "日課義務化への反対", "開発陣はゲームが日課義務のように感じられるのを避けたいと明言。無限のデイリー/ウィークリー/ライブサービス・チェックリストではなく、それ自体に価値あるコンテンツを志向します。"),
        section("alt-progression", "アカウント共有サブ進行", "サブ進行がアカウント単位で共有（GW2類似）。新クラスを始めても進行システムをやり直す必要がなく、多クラス実験が魅力的になります。"),
        section("implications", "発売時の意味", "時間のないプレイヤーへの強い提案です。アカウント単位の進行は「一度投資、全クラス恩恵」。9月17日〜18日のLSTで実戦確認しましょう。"),
      ],
    }),
    fr: articleCopy(guideLabels, "fr", 4, {
      eyebrow: "PHILOSOPHIE DE DESIGN",
      title: "L'anti-grind d'Aion 2 : pas d'auto-combat, pas de checklist quotidienne, alts partagés",
      description: "Le Q&A Gamescom 2026 a confirmé trois choix design très attendus : pas d'auto-combat, une position explicite anti-obligation quotidienne et une progression d'alts partagée.",
      intro: "Les développeurs ont confirmé trois choix qui tranchent avec les habitudes des MMO coréens : pas d'auto-combat, refus de l'obligation quotidienne, et progression d'alts au niveau du compte. Chacun a un sens pour le lancement.",
      sourceNote: "Basé sur le Q&A Gamescom 2026 d'intheGame (29 août 2026) et le message de design des devs sur Steam (25 juin 2026).",
      keywords: ["Aion 2 sans auto-combat", "Aion 2 auto play", "Aion 2 quêtes quotidiennes", "Aion 2 alts"],
      sections: [
        section("no-autoplay", "Pas d'auto-combat", "Pas d'auto-combat, contrôle manuel total. Un vrai différenciateur face à l'auto-play du marché coréen. Le combat récompense l'input actif (position, timing, cible)."),
        section("no-dailies", "Pas d'obligation quotidienne", "Les devs veulent éviter que le jeu ressemble à une obligation : pas de flots infinis de dailies/weeklies. Des récompenses valables plutôt que du remplissage."),
        section("alt-progression", "Alts partagés", "Progression d'alts au niveau du compte (style Guild Wars 2) : changer de classe ne refait pas tous les systèmes. Expérimenter devient attractif."),
        section("implications", "Pour le lancement", "Un argument fort pour les joueurs pressés. La progression partagée : investir une fois, profiter partout. À vérifier au LST des 17-18 septembre."),
      ],
    }),
    de: articleCopy(guideLabels, "de", 4, {
      eyebrow: "DESIGN-PHILOSOPHIE",
      title: "Aion 2s Anti-Grind-Design: kein Auto-Kampf, keine Tagespflicht, geteilte Alts",
      description: "Das Gamescom-2026-Q&A bestätigte drei gewünschte Design-Entscheidungen: kein Auto-Kampf, eine klare Anti-Tagespflicht-Haltung und geteilte Alt-Progression.",
      intro: "Die Entwickler bestätigten drei Entscheidungen gegen koreanische-MMO-Gewohnheiten: kein Auto-Kampf, Ablehnung der Tagespflicht und Account-weite Alt-Progression. Jede hat Bedeutung für den Start.",
      sourceNote: "Basierend auf dem Gamescom-2026-Q&A von intheGame (29. August 2026) und der Design-Botschaft der Devs auf Steam (25. Juni 2026).",
      keywords: ["Aion 2 kein Auto-Kampf", "Aion 2 Auto Play", "Aion 2 Daily Quests", "Aion 2 Alts"],
      sections: [
        section("no-autoplay", "Kein Auto-Kampf", "Kein Auto-Kampf, volle manuelle Steuerung. Ein echtes Unterscheidungsmerkmal gegen den Auto-Play-Markt. Kampf belohnt aktive Eingaben (Position, Timing, Zielwahl)."),
        section("no-dailies", "Keine Tagespflicht", "Die Devs wollen keine Tagespflicht-Gefühl: keine endlosen Daily/Weekly-Listen. Wertvolle Belohnungen statt Füllstoff."),
        section("alt-progression", "Geteilte Alts", "Alt-Progression ist Account-weit (Guild-Wars-2-Stil): ein neuer Class-Start wiederholt keine Systeme. Ausprobieren wird attraktiv."),
        section("implications", "Zum Start", "Ein starkes Argument für vielbeschäftigte Spieler. Geteilte Progression: einmal investieren, überall profitieren. Im LST (17.–18. September) prüfen."),
      ],
    }),
    es: articleCopy(guideLabels, "es", 4, {
      eyebrow: "FILOSOFÍA DE DISEÑO",
      title: "El anti-grind de Aion 2: sin auto-combate, sin checklist diaria, alts compartidos",
      description: "El Q&A de Gamescom 2026 confirmó tres decisiones de diseño muy esperadas: sin auto-combate, postura explícita contra la obligación diaria y progresión de alts compartida.",
      intro: "Los desarrolladores confirmaron tres decisiones contra las costumbres de los MMO coreanos: sin auto-combate, rechazo de la obligación diaria y progresión de alts a nivel de cuenta. Cada una tiene sentido para el lanzamiento.",
      sourceNote: "Basado en el Q&A de Gamescom 2026 de intheGame (29 de agosto de 2026) y el mensaje de diseño de los devs en Steam (25 de junio de 2026).",
      keywords: ["Aion 2 sin auto-combate", "Aion 2 auto play", "Aion 2 misiones diarias", "Aion 2 alts"],
      sections: [
        section("no-autoplay", "Sin auto-combate", "Sin auto-combate, control manual total. Un diferenciador real frente al auto-play del mercado coreano. El combate premia el input activo (posición, timing, objetivo)."),
        section("no-dailies", "Sin obligación diaria", "Los devs evitan que el juego parezca una obligación: sin listas infinitas de dailies/weeklies. Recompensas valiosas en vez de relleno."),
        section("alt-progression", "Alts compartidos", "Progresión de alts a nivel de cuenta (estilo Guild Wars 2): cambiar de clase no repite sistemas. Experimentar se vuelve atractivo."),
        section("implications", "Para el lanzamiento", "Un argumento fuerte para jugadores ocupados. Progresión compartida: invertir una vez, beneficiarse en todos. A verificar en el LST del 17-18 de septiembre."),
      ],
    }),
    "pt-br": articleCopy(guideLabels, "pt-br", 4, {
      eyebrow: "FILOSOFIA DE DESIGN",
      title: "O anti-grind do Aion 2: sem auto-combate, sem checklist diária, alts compartilhados",
      description: "O Q&A da Gamescom 2026 confirmou três decisões de design muito esperadas: sem auto-combate, postura explícita contra a obrigação diária e progressão de alts compartilhada.",
      intro: "Os desenvolvedores confirmaram três decisões contra os costumes dos MMOs coreanos: sem auto-combate, rejeição da obrigação diária e progressão de alts em nível de conta. Cada uma tem sentido para o lançamento.",
      sourceNote: "Com base no Q&A da Gamescom 2026 da intheGame (29 de agosto de 2026) e na mensagem de design dos devs na Steam (25 de junho de 2026).",
      keywords: ["Aion 2 sem auto-combate", "Aion 2 auto play", "Aion 2 missões diárias", "Aion 2 alts"],
      sections: [
        section("no-autoplay", "Sem auto-combate", "Sem auto-combate, controle manual total. Um diferenciador real contra o auto-play do mercado coreano. O combate premia input ativo (posição, timing, alvo)."),
        section("no-dailies", "Sem obrigação diária", "Os devs evitam que o jogo pareça uma obrigação: sem listas infinitas de dailies/weeklies. Recompensas valiosas em vez de preenchimento."),
        section("alt-progression", "Alts compartilhados", "Progressão de alts em nível de conta (estilo Guild Wars 2): trocar de classe não repete sistemas. Experimentar fica atraente."),
        section("implications", "Para o lançamento", "Um argumento forte para jogadores ocupados. Progressão compartilhada: investir uma vez, beneficiar em todos. A verificar no LST de 17-18 de setembro."),
      ],
    }),
    ru: articleCopy(guideLabels, "ru", 4, {
      eyebrow: "ФИЛОСОФИЯ ДИЗАЙНА",
      title: "Анти-гринд Aion 2: без авто-боя, без ежедневных списков, общие альты",
      description: "Q&A Gamescom 2026 подтвердил три ожидаемых решения: без авто-боя, явная позиция против ежедневных обязанностей и общая прогрессия альтов.",
      intro: "Разработчики подтвердили три решения против привычек корейских MMO: без авто-боя, отказ от ежедневной обязанности и прогрессия альтов на уровне аккаунта. Каждое важно для запуска.",
      sourceNote: "На основе Q&A Gamescom 2026 от intheGame (29 августа 2026) и дизайн-послания разработчиков в Steam (25 июня 2026).",
      keywords: ["Aion 2 без авто-боя", "Aion 2 авто-плей", "Aion 2 ежедневные квесты", "Aion 2 альты"],
      sections: [
        section("no-autoplay", "Без авто-боя", "Нет авто-боя, полное ручное управление. Реальное отличие от авто-плея корейского рынка. Бой вознаграждает активный ввод (позиция, тайминг, цель)."),
        section("no-dailies", "Без ежедневной обязанности", "Разработчики избегают ощущения обязанности: без бесконечных дейли/викли. Ценные награды вместо заполнителя."),
        section("alt-progression", "Общие альты", "Прогрессия альтов на уровне аккаунта (стиль Guild Wars 2): смена класса не повторяет системы. Эксперименты становятся привлекательными."),
        section("implications", "Для запуска", "Сильный аргумент для занятых игроков. Общая прогрессия: инвестируй один раз — получай везде. Проверьте на LST 17–18 сентября."),
      ],
    }),
    "zh-hant": articleCopy(guideLabels, "zh-hant", 4, {
      eyebrow: "設計理念",
      title: "Aion 2 反日常設計：無自動戰鬥、無每日清單、帳號級副職",
      description: "Gamescom 2026 開發者問答確認三項最受期待的設計選擇：無自動戰鬥、明確反對日常義務化、帳號級共享副職進度。以下為各自對上線版本的意義。",
      intro: "Aion 2 開發者藉 Gamescom 2026 問答確認三項反韓式 MMO 習慣的設計選擇：完全無自動戰鬥、明確拒絕把遊戲變成每日義務、帳號級共享進度讓副職無痛。每一項都是對上線遊戲玩法的真實表態。本指南拆解並說明其含義。",
      sourceNote: "基於 intheGame 的 Gamescom 2026 開發者問答（2026-08-29）與開發者 6 月 25 日於 Steam 發布的設計理念來信。",
      keywords: ["Aion 2 無自動戰鬥", "Aion 2 無自動遊玩", "Aion 2 每日任務", "Aion 2 副職進度", "Aion 2 反日常"],
      sections: [
        section("no-autoplay", "無自動戰鬥，全手動", ["演示確認沒有自動戰鬥——每個動作皆手動，強化 Aion 2 的動作 MMO 定位。", "這是有意義的差異點：定義現代韓式 MMO 市場的自動玩法被刻意剔除。", "預期戰鬥獎勵主動輸入——站位、時機與目標選擇比裝備檢查更重要。"]),
        section("no-dailies", "反對日常義務化", ["開發者明確希望避免遊戲像日常義務——沒有無窮盡的每日/每週/服務式清單。", "轉而讓內容本身有價值：獎勵值得，而非為登入而登入的填充物。", "這與探索理念相配：好奇心牽引你進入，而非瑣事清單。"]),
        section("alt-progression", "帳號級共享副職進度", ["副職進度為帳號級（前瞻類比《激戰2》）：開新職業不必重做所有養成系統。", "這讓多職業試驗真正有吸引力——第二個、第三個乃至第十個職業都建立在此前進度之上。", "結合清晰職業定位，降低上線時『選錯職業浪費角色』的顧慮。"]),
        section("implications", "上線版本的含義", ["對時間有限的玩家是強力賣點：尊重時間的遊戲，無需為落後而每日登入。", "對養成型玩家，帳號級副職意味著名冊即帳號——投入一次，全職業受益。", "關注 9 月 17-18 日上線規模測試確認反日常設計在實戰中成立。"]),
      ],
    }),
  },
};