import { articleCopy, localizations, newsLabels, publishedVerified, section } from "./trending-august-31-shared";
import type { ContentEntry, ContentHeroImage, ContentSource } from "./content-registry";

/* ARTICLE 1 — Steam store page publishes an explicit generative-AI asset disclosure for AION 2 */

const aiSource1: ContentSource = {
  id: "steam-store-aion2-disclosure-2026-08-31",
  kind: "platform", publisher: "Steam",
  label: "AION 2 — Steam Store Page (AI Disclosure, Release Date, Languages)",
  url: "https://store.steampowered.com/app/3393110/AION_2/",
  publishedAt: "2026-08-26",
  retrievedAt: "2026-08-31",
  verifiedAt: "2026-08-31",
  localizations: localizations({
    "zh-hans": "AION 2——Steam 商店页（AI 披露、发售日期、语言）",
    en: "AION 2 — Steam Store Page (AI Disclosure, Release Date, Languages)",
    fr: "AION 2 — Page boutique Steam (divulgation IA, date de sortie, langues)",
    de: "AION 2 — Steam-Store-Seite (KI-Hinweis, Erscheinungsdatum, Sprachen)",
    es: "AION 2 — Página de la tienda de Steam (divulgación de IA, fecha de lanzamiento, idiomas)",
    ja: "AION 2 — Steam ストアページ（AI 開示、発売日、対応言語）",
    "pt-br": "AION 2 — Página da loja Steam (divulgação de IA, data de lançamento, idiomas)",
    ru: "AION 2 — Страница Steam (раскрытие ИИ, дата выхода, языки)",
    ko: "AION 2 — Steam 상점 페이지 (AI 사용 공시, 출시일, 언어)",
    "zh-hant": "AION 2——Steam 商店頁（AI 披露、發售日期、語言）",
  }, "https://store.steampowered.com/app/3393110/AION_2/"),
};

const aiSource2: ContentSource = {
  id: "kotaku-onl-genai-slop-2026-08-26",
  kind: "third-party", publisher: "Kotaku",
  label: "Here Are The Opening Night Live Games You Can Ignore Because Of GenAI Slop",
  url: "https://kotaku.com/opening-night-live-2026-genai-slop-games-geoff-keighley-2000728477",
  publishedAt: "2026-08-26",
  retrievedAt: "2026-08-31",
  verifiedAt: "2026-08-31",
  localizations: localizations({
    "zh-hans": "因生成式 AI 内容而被点名的 Opening Night Live 游戏",
    en: "Here Are The Opening Night Live Games You Can Ignore Because Of GenAI Slop",
    fr: "Les jeux d'Opening Night Live à ignorer à cause de la IA générative",
    de: "Diese Opening-Night-Live-Spiele könnt ihr wegen GenAI-Schrott ignorieren",
    es: "Estos juegos de Opening Night Live puedes ignorar por IA generativa",
    ja: "生成AIのせいでスルーしてよい Opening Night Live のゲーム",
    "pt-br": "Estes jogos do Opening Night Live você pode ignorar por IA generativa",
    ru: "Эти игры Opening Night Live можно пропустить из-за генеративного ИИ",
    ko: "생성형 AI 때문에 건너뛸 수 있는 Opening Night Live 게임",
    "zh-hant": "因生成式 AI 內容而被點名的 Opening Night Live 遊戲",
  }, "https://kotaku.com/opening-night-live-2026-genai-slop-games-geoff-keighley-2000728477"),
};

const aiHero: ContentHeroImage = {
  src: "https://blogfiles.ncsoft.net/news/af7330da-4ff6-4b58-aece-400e6061a3be.jpg",
  width: 1100, height: 605,
  credit: "NC Corporation",
  sourceUrl: "https://aion2.plaync.com/ja-jp/board/notice/list",
  rights: "linked-official-media",
  translations: {
    "zh-hans": { alt: "Aion 2 Steam 生成式 AI 披露新闻配图", caption: "NC 官方配图；Aion 2 的 Steam 商店页明确写出部分游戏内资产由 AI 工具协助制作，Arcana 卡牌设计与部分图标使用 AI 生成资产。" },
    en: { alt: "Aion 2 Steam generative AI disclosure news image", caption: "Official NC artwork; the AION 2 Steam store page states that some in-game assets were created with AI assistance, with Arcana card designs and some icons using AI-generated assets." },
    fr: { alt: "Image de la divulgation IA générative d'Aion 2 sur Steam", caption: "Visuel officiel NC ; la page Steam d'AION 2 indique que certains assets du jeu ont été créés avec l'aide de l'IA, cartes Arcana et certaines icônes incluses." },
    de: { alt: "Bild zum KI-Generativa-Hinweis von Aion 2 auf Steam", caption: "Offizielles NC-Artwork; die Steam-Store-Seite von AION 2 weist darauf hin, dass einige In-Game-Assets mit KI erstellt wurden, darunter Arcana-Karten und einige Icons." },
    es: { alt: "Imagen de la divulgación de IA generativa de Aion 2 en Steam", caption: "Arte oficial de NC; la página de Steam de AION 2 indica que algunos elementos del juego se crearon con ayuda de IA, incluidas las cartas Arcana y algunos iconos." },
    ja: { alt: "Aion 2 Steam 生成AI開示ニュース画像", caption: "NC公式アートワーク；AION 2 のSteamストアページは、ゲーム内アセットの一部がAIの補助で作成され、Arcanaカードデザインと一部のアイコンがAI生成アセットであることを明示しています。" },
    "pt-br": { alt: "Imagem da divulgação de IA generativa do Aion 2 na Steam", caption: "Arte oficial da NC; a página da Steam do AION 2 informa que alguns recursos do jogo foram criados com ajuda de IA, incluindo os cards Arcana e alguns ícones." },
    ru: { alt: "Изображение раскрытия генеративного ИИ Aion 2 в Steam", caption: "Официальный арт NC; страница Steam AION 2 указывает, что часть игровых ресурсов создана с помощью ИИ — карточки Arcana и некоторые значки используют сгенерированные активы." },
    ko: { alt: "Aion 2 Steam 생성형 AI 공시 뉴스 이미지", caption: "NC 공식 이미지입니다. AION 2 Steam 상점 페이지는 게임 내 자산 일부가 AI의 도움으로 제작되었고 Arcana 카드 디자인과 일부 아이콘에 AI 생성 자산이 쓰였다고 명시합니다." },
    "zh-hant": { alt: "Aion 2 Steam 生成式 AI 披露新聞配圖", caption: "NC 官方配圖；Aion 2 的 Steam 商店頁明確寫出部分遊戲內資產由 AI 工具協助製作，Arcana 卡牌設計與部分圖示使用 AI 生成資產。" },
  },
};

export const trendingAugust31Article1: ContentEntry = {
  section: "news",
  slug: "aion-2-genai-asset-disclosure-steam",
  schemaType: "NewsArticle",
  publishedAt: "2026-08-31",
  updatedAt: "2026-08-31",
  readingMinutes: 5,
  publication: publishedVerified,
  sources: [aiSource1, aiSource2],
  heroImage: aiHero,
  related: [
    { kind: "content", section: "news", slug: "aion-2-gamescom-2026-preview-impressions" },
    { kind: "content", section: "guides", slug: "aion-2-language-support-8-languages-guide" },
    { kind: "content", section: "news", slug: "aion-2-release-date-october-5-2026" },
    { kind: "content", section: "guides", slug: "aion-2-monetization-f2p-cosmetics-guide" },
  ],
  translations: {
    en: articleCopy(newsLabels, "en", 5, {
      eyebrow: "STEAM AI DISCLOSURE",
      title: "Aion 2 Steam AI Disclosure: Exactly What NC Soft Stated",
      description: "The AION 2 Steam store page now states in plain text that some in-game assets were created with AI assistance, and that Arcana card designs and some icons use AI-generated assets. Here is the verbatim disclosure, what it does and does not cover, and how to verify it yourself.",
      intro: "The AION 2 Steam store page carries an explicit generative-AI statement: “Some in-game assets were created with the assistance of AI tools. Arcana card designs and some icons use AI-generated assets.” It is a one-sentence disclosure, published on Steam's own storefront rather than in a blog post, and it places AION 2 in the small group of Gamescom 2026 announcements that list AI usage openly on the store page itself. This report reproduces the exact wording, explains what scope it claims and what it stays silent on, and gives you a way to check the disclosure yourself before the October 5 launch.",
      sourceNote: "Based on the AION 2 Steam store page (retrieved and verified August 31, 2026) and Kotaku's August 26, 2026 report on generative-AI disclosures among Opening Night Live titles.",
      keywords: ["Aion 2 AI disclosure", "Aion 2 Steam AI", "Aion 2 generative AI assets", "Aion 2 Arcana AI", "Aion 2 genAI"],
      sections: [
        section("disclosure", "The Verbatim Disclosure", ["The store page states it in a single sentence: some in-game assets were created with the assistance of AI tools, and Arcana card designs plus some icons use AI-generated assets. That is the whole official statement. NC Soft did not quantify a share of assets, name the specific AI systems, or commit to removing anything.", "Because the text sits on Steam's storefront, it is durable and machine-readable: it is not a tweet, not a dev blog, and it does not depend on a press release surviving. Players who look at the page before buying will read it.", "This report quotes that sentence directly. Treat the quote, not our paraphrase, as the primary source."]),
        section("scope", "What Is Actually Claimed", ["The disclosure names two specific categories: Arcana card designs and some icons. Both are presentational — card artwork and UI icons — rather than gameplay systems, world geometry, audio, or narrative.", "It also makes a broader, unquantified claim that some in-game assets were created with AI assistance. That second clause is wider than the two named examples and is the one worth reading carefully: it does not say whether those assets are cosmetic-only.", "Notably absent: any statement about gameplay content, procedural generation, NPCs, quest text, audio, or live-service content. Silence here is not confirmation either way."]),
        section("why-now", "Why This Appeared During Gamescom 2026", ["Steam requires developers to disclose AI-assisted asset creation on store pages, and Gamescom 2026's Opening Night Live became the moment several titles were examined against that requirement. Kotaku listed AION 2 among the titles whose store pages “list varying degrees of genAI usage”.", "That context matters for how the disclosure should be read: it is a compliance statement produced for the storefront, not a creative-approach manifesto. NC Soft is telling you a fact about production, and the store page is the official place to find it.", "Other outlets flagged Aion 2 in the same news cycle specifically for players who want to avoid AI-generated content, which is exactly the audience a store-page disclosure exists to reach."]),
        section("how-to-check", "How to Verify It Yourself", ["Open the AION 2 Steam store page and scroll to the disclosure block near the platform and content-rating information. The AI statement sits alongside Steam's standard “In-App Purchases”, “Online PvP” and “Online Co-op” feature tags and the mature-content note.", "The same page confirms the commercial and schedule facts at once: Release 5 Oct 2026, Advance Access Starts 30 Sep, and the Free to Play tag. Verifying the disclosure therefore doubles as verifying the launch timeline.", "If the page changes before launch, the text is the authoritative record of what was published — Steam store pages are dated and widely captured, so a later edit is visible rather than silent."]),
        section("what-it-does-not-say", "What the Disclosure Leaves Open", ["No percentage, no asset count, no named vendor or model, no statement about whether AI output was edited by humans afterwards. The store page deliberately stops at “assistance” and “some assets”.", "There is no commitment to swap any asset for a non-AI alternative, and no player opt-out mechanism. Anyone with a strict AI-free policy has to decide before purchase, because nothing on the page offers a choice in-game.", "For context, the page's own feature tags confirm the game is free to play with in-app purchases and online multiplayer, and it carries a general mature-content and gore note. The AI disclosure sits inside that same block of consumer-facing facts, not in a separate apology or FAQ."]),
      ],
    }),
    "zh-hans": articleCopy(newsLabels, "zh-hans", 5, {
      eyebrow: "STEAM AI 披露",
      title: "Aion 2 Steam AI 披露：NC Soft 原文到底怎么写的",
      description: "AION 2 的 Steam 商店页现已用一句明文写出：部分游戏内资产由 AI 工具协助制作，Arcana 卡牌设计与部分图标使用 AI 生成资产。以下是原文、覆盖范围与自查方法。",
      intro: "AION 2 的 Steam 商店页带有一句明确的生成式 AI 声明：「Some in-game assets were created with the assistance of AI tools. Arcana card designs and some icons use AI-generated assets.」它是一句话披露，发布在 Steam 自己的商店页而非博客上，也让 AION 2 落入 Gamescom 2026 少数在商店页公开列出 AI 使用的作品之列。本报告逐字还原原文、说明它声明了什么、保持了哪些沉默，并给出在 10 月 5 日上线前自查的方法。",
      sourceNote: "基于 AION 2 Steam 商店页（2026-08-31 检索并核对）与 Kotaku 2026 年 8 月 26 日关于 Opening Night Live 各作生成式 AI 披露的报道。",
      keywords: ["Aion 2 AI 披露", "Aion 2 Steam AI", "Aion 2 生成式 AI", "Aion 2 Arcana AI", "Aion 2 生成AI"],
      sections: [
        section("disclosure", "披露原文", ["商店页用一句话说明：部分游戏内资产由 AI 工具协助制作，Arcana 卡牌设计与部分图标使用 AI 生成资产。这就是完整官方表述。NC Soft 未给出资产占比、未点名具体 AI 系统，也未承诺移除任何内容。", "该文本位于 Steam 商店页本身，因此持久且可被机器读取：它不是推文、不是开发博客，也不依赖新闻稿存续。购买前查看商店页的玩家会读到它。", "本报告直接引用该句原文。请以引文而非我们的转述作为一手依据。"]),
        section("scope", "到底声明了什么", ["披露点名了两个具体类别：Arcana 卡牌设计与部分图标。二者均属呈现层——卡牌美术与 UI 图标——而非玩法系统、世界几何、音频或叙事。", "同时它还有一句更宽、未量化的表述：部分游戏内资产由 AI 协助制作。这句比前述两个例子更宽，值得细读：它没有说明这些资产是否仅限外观。", "同样缺失的是：任何关于玩法内容、程序化生成、NPC、任务文本、音频或线上运营内容的声明。这里的沉默不构成任一侧的确认。"]),
        section("why-now", "为什么出现在 Gamescom 2026 期间", ["Steam 要求开发者在商店页披露 AI 辅助资产制作，而 Gamescom 2026 的 Opening Night Live 成了多件作品被对照该要求检视的时刻。Kotaku 将 AION 2 列入「商店页列出不同程度 AI 使用」的作品名单。", "这一背景影响披露的读法：它是为商店页制作的合规声明，而非创作理念宣言。NC Soft 在告知一个生产事实，商店页就是查询它的官方位置。", "同一新闻周期内，另有媒体专门提示希望回避 AI 生成内容的玩家注意 Aion 2——这恰恰是商店页披露所要触达的受众。"]),
        section("how-to-check", "如何自查", ["打开 AION 2 的 Steam 商店页，滚动到平台与内容分级信息附近的披露区块。AI 声明与 Steam 标准的「In-App Purchases」「Online PvP」「Online Co-op」特性标签以及成人内容提示并列。", "同一页面同时确认了商业与日程事实：Release 5 Oct 2026、Advance Access Starts 30 Sep，以及 Free to Play 标签。核对披露因此也等于核对上线时间线。", "若上线前页面发生变更，该文本仍是已发布内容的权威记录——Steam 商店页有日期且被广泛抓取，后续编辑是可观测的而非静默的。"]),
        section("what-it-does-not-say", "披露未回答的部分", ["没有比例、没有资产数量、没有供应商或模型名称，也没有说明 AI 产出是否经人工编辑。商店页有意停在「assistance」与「some assets」。", "没有承诺将任何资产替换为非 AI 版本，也没有玩家层面的退出机制。持严格无 AI 立场的玩家必须在购买前决定，因为页面上不存在游戏内选项。", "作为参照，该页自身的特性标签确认游戏为免费游玩且含内购与在线多人，并带有成人内容与血腥提示。AI 披露与这些面向消费者的事实并列在同一区块，而非单独的致歉或 FAQ。"]),
      ],
    }),
    ko: articleCopy(newsLabels, "ko", 5, {
      eyebrow: "STEAM AI 공시",
      title: "Aion 2 Steam AI 공시: NC소프트가 정확히 무엇을 썼는지",
      description: "AION 2 Steam 상점 페이지가 일부 게임 내 자산이 AI의 도움으로 제작되었고 Arcana 카드 디자인·일부 아이콘에 AI 생성 자산이 쓰였다고 한 문장으로 명시했습니다. 원문·범위·자검 방법을 정리합니다.",
      intro: "AION 2 Steam 상점 페이지에는 생성형 AI 문구가 분명히 있습니다. 10월 5일 출시 전, 그 문장이 무엇을 말하고 무엇을 침묵하는지 스스로 확인할 수 있습니다.",
      sourceNote: "AION 2 Steam 상점 페이지(2026-08-31 확인)와 Kotaku의 2026년 8월 26일 Opening Night Live 생성형 AI 공시 보도 기반.",
      keywords: ["Aion 2 AI 공시", "Aion 2 Steam AI", "Aion 2 생성형 AI", "Aion 2 Arcana AI", "Aion 2 생성AI"],
      sections: [
        section("disclosure", "공시 원문", "상점 페이지는 게임 내 자산 일부가 AI 보조로 제작되었으며 Arcana 카드 디자인과 일부 아이콘에 AI 생성 자산이 쓰였다고 한 문장으로 제시합니다. 자산 비율·특정 AI 시스템·삭제 약속은 없습니다. 텍스트는 Steam 상점 페이지에 있으므로 지속적이고 기계 가독적입니다."),
        section("scope", "어떤 범위를 주장하나", "명시한 범주는 두 가지 — Arcana 카드 디자인과 일부 아이콘. 둘 다 카드 아트와 UI 아이콘이라는 표현 계층이며, 게임 시스템·세계 지오메트리·음성·서사는 아닙니다. 다만 '일부 게임 내 자산'이라는 더 넓은 미정량 문구도 함께 있어, 그것이 반드시 코스메틱만인지 명시되지 않습니다."),
        section("why-now", "왜 Gamescom 2026에 나온가", "Steam은 개발자가 상점 페이지에서 AI 보조 자산 제작을 공시하도록 요구하며, 2026년 Opening Night Live가 여러 작품을 그 기준으로 점검한 계기가 됐습니다. Kotaku는 AION 2를 상점 페이지에서 일정 수준의 AI 사용을 기재한 작품 중 하나로 꼽았습니다. 이는 창작 철학 선언이 아닌 상점 페이지용 규제 준수 문구입니다."),
        section("how-to-check", "직접 확인하는 법", "AION 2 Steam 상점 페이지를 열고 플랫폼·콘텐츠 등급 정보 근처의 공시 블록을 확인하세요. AI 문구는 'In-App Purchases''Online PvP''Online Co-op' 특성 태그와 성인 콘텐츠 안내와 나란히 있습니다. 같은 페이지가 출시일 5 Oct 2026·사전 체험 30 Sep 시작·무료 플레이 태그를 동시에 확인해 주므로 일정 검증까지 가능해요."),
        section("what-it-does-not-say", "공시가 답하지 않은 것", "비율·자산 수량·공급사나 모델명·AI 산출물의 후속 편집 여부는 없습니다. 상점 페이지는 'assistance'와 'some assets'에서 멈춥니다. 비AI 자산 교체 약속이나 게임 내 선택권도 없으므로, 엄격한 무AI 입장을 가진다면 구매 전 판단해야 합니다."),
      ],
    }),
    ja: articleCopy(newsLabels, "ja", 5, {
      eyebrow: "STEAM AI開示",
      title: "Aion 2 Steam AI開示：NCソフトが正確に何と書いているか",
      description: "AION 2 の Steam ストアページは、ゲーム内アセットの一部が AI の補助で作成され、Arcana カードデザインと一部のアイコンが AI 生成アセットであることを一文で明記。原文・範囲・自己確認方法を整理します。",
      intro: "AION 2 の Steam ストアページには生成 AI の明記があります。10 月 5 日の発売前に、その一文が何を言い何を沈黙しているかを確認できます。",
      sourceNote: "AION 2 Steam ストアページ（2026-08-31 確認）と Kotaku の 2026 年 8 月 26 日 Opening Night Live 生成 AI 開示報道に基づきます。",
      keywords: ["Aion 2 AI開示", "Aion 2 Steam AI", "Aion 2 生成AI", "Aion 2 Arcana AI", "Aion 2 生成AI資産"],
      sections: [
        section("disclosure", "開示原文", "ストアページは一文で、ゲーム内アセットの一部が AI の補助で作成され、Arcana カードデザインと一部のアイコンが AI 生成アセットであることを示します。資産比率・具体的な AI システム・削除約束はありません。テキストは Steam ストアページにあるため持続的で機械可読です。"),
        section("scope", "どの範囲を主張しているか", "明示された範疇は二つ — Arcana カードデザインと一部のアイコン。いずれもカードアートと UI アイコンという表現層で、ゲームシステム・世界ジオメトリ・音声・物語ではありません。ただし「ゲーム内アセットの一部」というより広い未定量の表現も併記され、それが必ずしもコスメのみかは明示されていません。"),
        section("why-now", "なぜ Gamescom 2026 に登場したか", "Steam は開発者にストアページでの AI 補助アセット作成の開示を要求しており、2026 年の Opening Night Live は複数の作品がその基準で精査された契機となりました。Kotaku は AION 2 を、ストアページに一定水準の AI 使用を記載した作品の一例として挙げました。これは創作哲学の宣言ではなく、ストアページ向けのコンプライアンス文です。"),
        section("how-to-check", "自分で確認する方法", "AION 2 の Steam ストアページを開き、プラットフォーム・レーティング情報の nearby にある開示ブロックを確認してください。AI 文は「In-App Purchases」「Online PvP」「Online Co-op」の特性タグと成人向けコンテンツの注意書きと並んでいます。同じページで発売日 5 Oct 2026・先行体験 30 Sep 開始・無料プレイタグを同時に確認できるため、日程の検証も兼ねられます。"),
        section("what-it-does-not-say", "開示が答えなかったこと", "比率・資産数・ベンダーやモデル名・AI 出力の後続人間編集の有無はありません。ページは「assistance」と「some assets」で止まっています。非 AI アセットへの差し替え約束もゲーム内での選択手段も無いので、厳格な AI なし方針なら購入前に判断する必要があります。"),
      ],
    }),
    fr: articleCopy(newsLabels, "fr", 5, {
      eyebrow: "DIVULGATION IA SUR STEAM",
      title: "Divulgation IA d'Aion 2 sur Steam : exactement ce que NC Soft a écrit",
      description: "La page Steam d'AION 2 indique en une phrase que certains assets du jeu ont été créés avec l'aide de l'IA, et que les cartes Arcana et certaines icônes utilisent des assets générés par IA. Texte exact, portée et vérification.",
      intro: "La page Steam d'AION 2 porte une déclaration explicite sur l'IA générative, publiée sur la vitrine Steam elle-même plutôt que sur un blog. Voici le texte exact, ce qu'il couvre, ce qu'il tait, et comment le vérifier avant le 5 octobre.",
      sourceNote: "Basé sur la page Steam d'AION 2 (récupérée et vérifiée le 31 août 2026) et le rapport Kotaku du 26 août 2026 sur les divulgations IA d'Opening Night Live.",
      keywords: ["Aion 2 divulgation IA", "Aion 2 Steam IA", "Aion 2 IA générative", "Aion 2 Arcana IA", "Aion 2 genAI"],
      sections: [
        section("disclosure", "Le texte exact", "La page décrit en une phrase que certains assets du jeu ont été créés avec l'aide d'outils IA, et que les cartes Arcana et certaines icônes utilisent des assets générés par IA. C'est l'intégralité de la déclaration officielle. Pas de part chiffrée, pas de système nommé, pas d'engagement de retrait. Étant sur la vitrine Steam, ce texte est durable et lisible par machine."),
        section("scope", "Ce qui est réellement affirmé", "Deux catégories sont nommées : les cartes Arcana et certaines icônes, toutes deux présentielles — art de cartes et icônes UI — et non des systèmes de jeu, de géométrie, d'audio ou de narration. Une seconde clause plus large, non chiffrée, évoque certains assets du jeu créés avec l'aide de l'IA, sans préciser s'ils sont uniquement cosmétiques. Rien n'est dit sur le contenu de jeu, la génération procédurale, les PNJ, le texte de quêtes ou le live-service."),
        section("why-now", "Pourquoi pendant Gamescom 2026", "Steam exige des développeurs qu'ils divulguent l'assistance IA sur les pages boutique, et l'Opening Night Live de Gamescom 2026 a été le moment où plusieurs titres ont été examinés contre cette règle. Kotaku range AION 2 parmi les pages qui « listent différents degrés d'usage de l'IA générative ». C'est une déclaration de conformité de vitrine, pas un manifeste créatif."),
        section("how-to-check", "Comment vérifier vous-même", "Ouvrez la page Steam d'AION 2 et descendez jusqu'au bloc de divulgation près des informations plateformes et de cote. L'énoncé IA figure aux côtés des étiquettes Steam « In-App Purchases », « Online PvP », « Online Co-op » et de la mention de contenu mature. La même page confirme Release 5 Oct 2026, Advance Access Starts 30 Sep et l'étiquette Free to Play : la vérification de la divulgation vaut aussi pour le calendrier."),
        section("what-it-does-not-say", "Ce que la divulgation laisse ouvert", "Aucun pourcentage, aucun décompte d'assets, aucun fournisseur ou modèle nommé, aucune indication sur un retouchage humain. La page s'arrête volontairement à « assistance » et « certains assets ». Aucun engagement de remplacer un asset par une version non IA, aucune option de retrait côté joueur : quiconque suit une politique stricte doit décider avant l'achat."),
      ],
    }),
    de: articleCopy(newsLabels, "de", 5, {
      eyebrow: "KI-HINWEIS AUF STEAM",
      title: "Aion 2 Steam-KI-Hinweis: Genau das, was NC Soft geschrieben hat",
      description: "Die AION 2-Steampage stellt in einem Satz fest, dass einige In-Game-Assets mit KI erstellt wurden und dass Arcana-Karten sowie einige Icons KI-generierte Assets verwenden. Originaltext, Umfang und Selbstprüfung.",
      intro: "Die Steam-Store-Seite von AION 2 trägt eine explizite KI-Generativa-Aussage, veröffentlicht auf der Steam-Einzelhandelsseite selbst und nicht in einem Blog. Hier ist der wörtliche Text, was er erfasst, was er schweigt, und wie ihr ihn vor dem 5. Oktober selbst prüft.",
      sourceNote: "Basierend auf der AION 2-Steampage (abgerufen und verifiziert am 31. August 2026) und dem Kotaku-Bericht vom 26. August 2026 zu KI-Disclosures auf der Opening Night Live.",
      keywords: ["Aion 2 KI-Hinweis", "Aion 2 Steam KI", "Aion 2 generative KI", "Aion 2 Arcana KI", "Aion 2 GenAI"],
      sections: [
        section("disclosure", "Der wörtliche Hinweis", "Die Seite stellt in einem Satz fest, dass einige In-Game-Assets mit KI erstellt wurden und dass Arcana-Kartendesigns sowie einige Icons KI-generierte Assets verwenden. Das ist die gesamte offizielle Aussage. Kein prozentuales Maß, kein genanntes KI-System, kein Rücknahmeversprechen. Weil der Text auf der Steam-Store-Seite liegt, ist er dauerhaft und maschinenlesbar."),
        section("scope", "Was tatsächlich behauptet wird", "Zwei Kategorien werden genannt: Arcana-Kartendesigns und einige Icons — beides Präsentationslayer, Kartenart und UI-Icons, keine Spielsysteme, Weltgeometrie, Audio oder Narration. Daneben steht eine breitere, unquantifizierte Aussage über einige In-Game-Assets, die mit KI erstellt wurden, ohne zu sagen, ob sie rein kosmetisch sind. Über Gameplay-Inhalte, prozedurale Generierung, NPCs, Questtext und Live-Service ist nichts angegeben."),
        section("why-now", "Warum gerade auf der Gamescom 2026", "Steam verlangt von Entwicklern, dass sie KI-gestützte Asset-Erstellung auf Store-Seiten offenlegen, und die Opening Night Live der Gamescom 2026 war der Moment, an dem mehrere Titel dagegen geprüft wurden. Kotaku führt AION 2 unter den Seiten, die unterschiedliche Ausprägungen von GenAI-Nutzung auflisten. Es ist eine Compliance-Aussage für den Store, kein Kreativ-Manifest."),
        section("how-to-check", "So prüft ihr es selbst", "Öffnet die AION 2-Steampage und scrollt zum Offenlegungsblock nahe der Plattform- und Inhaltskennzeichnungsangaben. Der KI-Text steht neben den Standard-Steam-Tags «In-App Purchases», «Online PvP», «Online Co-op» und der Kennzeichnung reifer Inhalte. Die gleiche Seite bestätigt Release 5 Oct 2026, Advance Access Starts 30 Sep und das Free-to-Play-Tag — die Prüfung der Offenlegung dient zugleich der Prüfung des Zeitplans."),
        section("what-it-does-not-say", "Was der Hinweis offen lässt", "Keine Prozente, keine Asset-Zählung, kein genannter Anbieter oder kein Modell, keine Aussage, ob KI-Ausgaben danach menschlich bearbeitet wurden. Die Seite hält sich bewusst an «assistance» und «some assets». Es gibt kein Versprechen, ein Asset durch eine nicht-KI-Version zu ersetzen, und keine Spieler-Opt-out-Option. Wer strikt KI-frei bleiben will, muss vor dem Kauf entscheiden."),
      ],
    }),
    es: articleCopy(newsLabels, "es", 5, {
      eyebrow: "DIVULGACIÓN DE IA EN STEAM",
      title: "Divulgación de IA de Aion 2 en Steam: exactamente lo que escribió NC Soft",
      description: "La página de Steam de AION 2 declara en una frase que algunos elementos del juego se crearon con ayuda de IA y que las cartas Arcana y algunos iconos usan elementos generados por IA. Texto literal, alcance y cómo verificarlo.",
      intro: "La página de Steam de AION 2 incluye una declaración explícita de IA generativa, publicada en la propia tienda de Steam y no en un blog. Aquí está el texto exacto, qué cubre, qué deja en silencio y cómo verificarlo antes del 5 de octubre.",
      sourceNote: "Basado en la página de Steam de AION 2 (recuperada y verificada el 31 de agosto de 2026) y el informe de Kotaku del 26 de agosto de 2026 sobre divulgaciones de IA en Opening Night Live.",
      keywords: ["Aion 2 divulgación IA", "Aion 2 Steam IA", "Aion 2 IA generativa", "Aion 2 Arcana IA", "Aion 2 genAI"],
      sections: [
        section("disclosure", "El texto literal", "La página declara en una frase que algunos elementos del juego se crearon con ayuda de herramientas de IA, y que los diseños de cartas Arcana y algunos iconos usan elementos generados por IA. Esa es la declaración oficial completa. Sin porcentaje, sin sistema nombrado, sin compromiso de retirada. Al estar en la tienda de Steam, el texto es duradero y legible por máquina."),
        section("scope", "Qué se afirma realmente", "Se nombran dos categorías: los diseños de cartas Arcana y algunos iconos, ambos de presentación — arte de cartas y iconos de interfaz —, no sistemas de juego, geometría, audio ni narrativa. Junto a eso, una cláusula más amplia y no cuantificada habla de algunos elementos del juego creados con ayuda de IA, sin aclarar si son solo cosméticos. No se dice nada sobre contenido jugable, generación procedural, PNJ, texto de misiones ni servicio en vivo."),
        section("why-now", "Por qué en Gamescom 2026", "Steam exige a los desarrolladores divulgar el uso de IA asistida en las páginas de la tienda, y la Opening Night Live de Gamescom 2026 fue el momento en que varios títulos se revisaron contra esa regla. Kotaku sitúa a AION 2 entre las páginas que «listan distintos grados de uso de IA generativa». Es una declaración de cumplimiento comercial, no un manifiesto creativo."),
        section("how-to-check", "Cómo verificarlo tú mismo", "Abre la página de Steam de AION 2 y baja hasta el bloque de divulgación cerca de la información de plataformas y clasificación. La frase de IA va junto a las etiquetas estándar de Steam «In-App Purchases», «Online PvP», «Online Co-op» y la advertencia de contenido maduro. La misma página confirma Release 5 Oct 2026, Advance Access Starts 30 Sep y la etiqueta Free to Play: verificar la divulgación también verifica el calendario."),
        section("what-it-does-not-say", "Qué deja abierto", "Sin porcentaje, sin recuento de elementos, sin proveedor o modelo nombrado, sin indicación de retoque humano posterior. La página se detiene deliberadamente en «assistance» y «some assets». No hay compromiso de sustituir un elemento por una versión no IA, ni opción de retirada por parte del jugador: quien siga una política estricta debe decidir antes de comprar."),
      ],
    }),
    "pt-br": articleCopy(newsLabels, "pt-br", 5, {
      eyebrow: "DIVERSÃO DE IA NA STEAM",
      title: "Divulgação de IA do Aion 2 na Steam: exatamente o que a NC Soft escreveu",
      description: "A página da Steam do AION 2 declara em uma frase que alguns recursos do jogo foram criados com ajuda de IA e que os cards Arcana e alguns ícones usam recursos gerados por IA. Texto exato, alcance e verificação.",
      intro: "A página da Steam do AION 2 traz uma declaração explícita sobre IA generativa, publicada na própria loja da Steam e não num blog. Veja o texto exato, o que ele cobre, o que deixa em silêncio e como verificar antes de 5 de outubro.",
      sourceNote: "Com base na página da Steam do AION 2 (recuperada e verificada em 31 de agosto de 2026) e no relato da Kotaku de 26 de agosto de 2026 sobre divulgações de IA no Opening Night Live.",
      keywords: ["Aion 2 divulgação IA", "Aion 2 Steam IA", "Aion 2 IA generativa", "Aion 2 Arcana IA", "Aion 2 genAI"],
      sections: [
        section("disclosure", "O texto exato", "A página declara em uma frase que alguns recursos do jogo foram criados com ajuda de ferramentas de IA, e que os designs de cards Arcana e alguns ícones usam recursos gerados por IA. Essa é a declaração oficial completa. Sem percentual, sem sistema nomeado, sem compromisso de remoção. Por estar na loja da Steam, o texto é durável e legível por máquina."),
        section("scope", "O que é realmente afirmado", "Duas categorias são nomeadas: os designs de cards Arcana e alguns ícones, ambos de apresentação — arte de card e ícones de interface —, não sistemas de jogo, geometria, áudio ou narrativa. Junto a isso, uma cláusula mais ampla e não quantificada fala de alguns recursos do jogo criados com ajuda de IA, sem esclarecer se são apenas cosméticos. Nada é dito sobre conteúdo jogável, geração procedural, NPCs, texto de missões ou live-service."),
        section("why-now", "Por que na Gamescom 2026", "A Steam exige que desenvolvedores divulguem o uso de IA assistida nas páginas da loja, e a Opening Night Live da Gamescom 2026 foi o momento em que vários títulos foram examinados contra essa regra. A Kotaku coloca o AION 2 entre as páginas que «listam diferentes graus de uso de IA generativa». É uma declaração de conformidade de vitrine, não um manifesto criativo."),
        section("how-to-check", "Como verificar você mesmo", "Abra a página da Steam do AION 2 e role até o bloco de divulgação próximo às informações de plataforma e classificação. A frase de IA aparece ao lado das tags padrão da Steam «In-App Purchases», «Online PvP», «Online Co-op」e do aviso de conteúdo maduro. A mesma página confirma Release 5 Oct 2026, Advance Access Starts 30 Sep e a tag Free to Play: verificar a divulgação também verifica o calendário."),
        section("what-it-does-not-say", "O que a divulgação deixa em aberto", "Sem percentual, sem contagem de recursos, sem fornecedor ou modelo nomeado, sem indicação de edição humana posterior. A página se detém deliberadamente em «assistance」e «some assets». Não há compromisso de substituir um recurso por uma versão sem IA, nem opção de saída por parte do jogador: quem segue uma política estrita deve decidir antes de comprar."),
      ],
    }),
    ru: articleCopy(newsLabels, "ru", 5, {
      eyebrow: "РАСКРЫТИЕ ИИ В STEAM",
      title: "Раскрытие ИИ в Aion 2 на Steam: точно то, что написала NC Soft",
      description: "Страница AION 2 в Steam одной фразой указывает, что часть игровых ресурсов создана с помощью ИИ и что карты Arcana и некоторые значки используют сгенерированные активы. Точный текст, охват и самопроверка.",
      intro: "Страница AION 2 в Steam содержит явное заявление о генеративном ИИ, опубликованное на самой витрине Steam, а не в блоге. Ниже — точный текст, что он покрывает, о чём молчит и как проверить это до 5 октября.",
      sourceNote: "На основе страницы AION 2 в Steam (получена и проверена 31 августа 2026) и отчёта Kotaku от 26 августа 2026 о раскрытиях ИИ на Opening Night Live.",
      keywords: ["Aion 2 раскрытие ИИ", "Aion 2 Steam ИИ", "Aion 2 генеративный ИИ", "Aion 2 Arcana ИИ", "Aion 2 genAI"],
      sections: [
        section("disclosure", "Точный текст", "Страница одной фразой указывает, что часть игровых ресурсов создана с помощью инструментов ИИ и что дизайн карт Arcana и некоторые значки используют сгенерированные активы. Это и есть полное официальное заявление. Без процента, без названного ИИ-системы, без обещания удаления. Будучи на витрине Steam, текст устойчив и читаем машиной."),
        section("scope", "Что на самом деле утверждается", "Названы две категории: дизайн карт Arcana и некоторые значки — обе представительские, карта-арт и UI-значки, а не игровые системы, геометрия мира, звук или нарратив. Рядом — более широкое, не количественное утверждение о некоторых ресурсах, созданных с помощью ИИ, без уточнения, косметика ли это. О игровом контентe, процедурной генерации, NPC, тексте квестов и live-service ничего не сказано."),
        section("why-now", "Почему именно на Gamescom 2026", "Steam требует от разработчиков раскрывать создание активов с помощью ИИ на страницах магазина, и Opening Night Live Gamescom 2026 стал моментом, когда несколько игр проверили по этому правилу. Kotaku относит AION 2 к страницам, «списывающим разные степени использования генеративного ИИ». Это декларация соответствия витрины, а не манифест творческой позиции."),
        section("how-to-check", "Как проверить самому", "Откройте страницу AION 2 в Steam и проскролльте к блоку раскрытия рядом с информацией о платформах и рейтинге. Фраза об ИИ стоит рядом с типовыми тегами Steam «In-App Purchases», «Online PvP», 「Online Co-op」и пометкой о взрослом контенте. Та же страница подтверждает Release 5 Oct 2026, Advance Access Starts 30 Sep и тег Free to Play: проверка раскрытия одновременно проверяет и график."),
        section("what-it-does-not-say", "Что раскрытие оставляет открытым", "Без процента, без подсчёта активов, без названного поставщика или модели, без указания на последующую человеческую доработку. Страница намеренно останавливается на「assistance」и「some assets」. Нет обещания заменить актив на не-ИИ версию и нет игрока-выбора: сторонник строгой политики без ИИ должен решить до покупки."),
      ],
    }),
    "zh-hant": articleCopy(newsLabels, "zh-hant", 5, {
      eyebrow: "STEAM AI 披露",
      title: "Aion 2 Steam AI 披露：NC Soft 原文到底怎麼寫的",
      description: "AION 2 的 Steam 商店頁現已用一句明文寫出：部分遊戲內資產由 AI 工具協助製作，Arcana 卡牌設計與部分圖示使用 AI 生成資產。以下是原文、覆蓋範圍與自查方法。",
      intro: "AION 2 的 Steam 商店頁帶有一句明確的生成式 AI 聲明，發布在 Steam 自己的商店頁而非部落格上。以下還原文字、說明它聲明與保持了哪些沉默，並給出 10 月 5 日上線前的自查方法。",
      sourceNote: "基於 AION 2 Steam 商店頁（2026-08-31 檢索並核對）與 Kotaku 2026 年 8 月 26 日關於 Opening Night Live 各作生成式 AI 披露的報導。",
      keywords: ["Aion 2 AI 披露", "Aion 2 Steam AI", "Aion 2 生成式 AI", "Aion 2 Arcana AI", "Aion 2 生成AI"],
      sections: [
        section("disclosure", "披露原文", "商店頁用一句話說明：部分遊戲內資產由 AI 工具協助製作，Arcana 卡牌設計與部分圖示使用 AI 生成資產。這即完整官方表述。NC Soft 未給出資產佔比、未點名具體 AI 系統，也未承諾移除任何內容。該文字位於 Steam 商店頁本身，故持久且可被機器讀取。"),
        section("scope", "到底聲明了什麼", "披露點名了兩個具體類別：Arcana 卡牌設計與部分圖示。二者均屬呈現層——卡牌美術與 UI 圖示——而非玩法系統、世界幾何、音訊或敘事。同時還有一句更寬、未量化的表述：部分遊戲內資產由 AI 協助製作，未說明是否僅限外觀。"),
        section("why-now", "為什麼出現在 Gamescom 2026 期間", "Steam 要求開發者在商店頁披露 AI 輔助資產製作，而 Gamescom 2026 的 Opening Night Live 成了多件作品被對照該要求檢視的時刻。Kotaku 將 AION 2 列入「商店頁列出不同程度 AI 使用」的作品名單。這是為商店頁製作的合規聲明，而非創作理念宣言。"),
        section("how-to-check", "如何自查", "打開 AION 2 的 Steam 商店頁，滾動到平台與內容分級資訊附近的披露區塊。AI 聲明與 Steam 標準的「In-App Purchases」「Online PvP」「Online Co-op」特性標籤以及成人內容提示並列。同一頁面同時確認 Release 5 Oct 2026、Advance Access Starts 30 Sep 與 Free to Play 標籤，核對披露因此也等於核對上線時間線。"),
        section("what-it-does-not-say", "披露未回答的部分", "沒有比例、沒有資產數量、沒有供應商或模型名稱，也沒有說明 AI 產出是否經人工編輯。商店頁有意停在「assistance」與「some assets」。沒有承諾將任何資產替換為非 AI 版本，也沒有玩家層面的退出機制；持嚴格無 AI 立場的玩家必須在購買前決定。"),
      ],
    }),
  },
};
