import { articleCopy, localizations, guideLabels, publishedVerified, section } from "./trending-september-15-shared";
import type { ContentEntry, ContentHeroImage, ContentSource } from "./content-registry";

/* ARTICLE 2 — Siege warfare guide: siege weapons, tactics, territory control */

const siegeSource: ContentSource = {
  id: "nc-aion2-rvr-siege",
  kind: "official",
  publisher: "NC Corporation",
  label: "Aion 2 RvR and Siege Warfare",
  url: "https://aion2.plaync.com/en-us/gameplay/",
  publishedAt: "2026-08-15",
  retrievedAt: "2026-09-15",
  verifiedAt: "2026-09-15",
  localizations: localizations({
    "zh-hans": "Aion 2 RvR 与攻城战",
    en: "Aion 2 RvR and Siege Warfare",
    fr: "Aion 2 RvR et Guerre de Siège",
    de: "Aion 2 RvR und Belagerungskrieg",
    es: "Aion 2 RvR y Guerra de Asedio",
    ja: "Aion 2 RvR と攻城戦",
    "pt-br": "Aion 2 RvR e Guerra de Cerco",
    ru: "Aion 2 RvR и Война осадных дел",
    ko: "Aion 2 RvR 와 포격전",
    "zh-hant": "Aion 2 RvR 與攻城戰",
  }, "https://aion2.plaync.com/en-us/gameplay/"),
};

const siegeHero: ContentHeroImage = {
  src: "https://blogfiles.ncsoft.net/news/af7330da-4ff6-4b58-aece-400e6061a3be.jpg",
  width: 1200, height: 630,
  credit: "NC Corporation",
  sourceUrl: "https://aion2.plaync.com/en-us/",
  rights: "linked-official-media",
  translations: {
    "zh-hans": { alt: "Aion 2 攻城战攻略横幅", caption: "Aion 2 的 RvR 战争是游戏的核心支柱之一。攻城战涉及大规模团体协调、 siege weapon 使用和领土控制策略。" },
    en: { alt: "Aion 2 Siege warfare guide banner", caption: "RvR warfare is a core pillar of Aion 2. Siege warfare involves large-scale group coordination, siege weapon usage, and territory control strategy." },
    fr: { alt: "Bannière du guide de guerre de siège d'Aion 2", caption: "La guerre RvR est un pilier central d'Aion 2. La guerre de siège implique une coordination de groupe à grande échelle, des armes de siège et une stratégie de contrôle territorial." },
    de: { alt: "Banner zum Belagerungskrieg-Guide von Aion 2", caption: "RvR-Krieg ist ein zentraler Pfeiler von Aion 2. Der Belagerungskrieg umfasst groß angelegte Gruppenkoordination, Belagerungswaffen und Territorialkontrolle." },
    es: { alt: "Banner de la guía de guerra de asedio de Aion 2", caption: "La guerra RvR es un pilar central de Aion 2. La guerra de asedio involucra coordinación de grupo a gran escala, armas de asedio y estrategia de control territorial." },
    ja: { alt: "Aion 2 攻城戦ガイドバナー", caption: "RvR戦争はAion 2の中核の柱の一つです。攻城戦は大規模な団体調整、攻城兵器の使用、領土制御戦略に関わります。" },
    "pt-br": { alt: "Banner da guia de guerra de cerco do Aion 2", caption: "A guerra RvR é um pilar central do Aion 2. A guerra de cerco envolve coordenação de grupo em larga escala, armas de cerco e estratégia de controle territorial." },
    ru: { alt: "Баннер гайда по осадной войне Aion 2", caption: "Война RvR — одна из ключевых опор Aion 2. Осадная война включает массовую групповую координацию, осадные орудия и стратегию контроля территории." },
    ko: { alt: "Aion 2 포격전 가이드 배너", caption: "RvR 전쟁은 Aion 2의 핵심 축 중 하나입니다. 포격전은 대규모 단체 조정, 포격 무기 사용, 영토 통제 전략을 포함합니다." },
    "zh-hant": { alt: "Aion 2 攻城戰攻略橫幅", caption: "Aion 2 的 RvR 戰爭是遊戲的核心支柱之一。攻城戰涉及大規模團體協調、siege weapon 使用和領土控制策略。" },
  },
};

export const trendingSeptember15Article2: ContentEntry = {
  section: "guides",
  slug: "aion-2-siege-warfare-guide",
  schemaType: "Article",
  publishedAt: "2026-09-15",
  updatedAt: "2026-09-15",
  readingMinutes: 8,
  publication: publishedVerified,
  sources: [siegeSource],
  heroImage: siegeHero,
  related: [
    { kind: "content", section: "guides", slug: "aion-2-pvp-guide-battlegrounds-abyss" },
    { kind: "content", section: "guides", slug: "aion-2-guild-social-guide" },
    { kind: "content", section: "guides", slug: "aion-2-trinity-roles-guide" },
    { kind: "content", section: "guides", slug: "aion-2-daily-weekly-routine-guide" },
  ],
  translations: {
    en: articleCopy(guideLabels, "en", 8, {
      eyebrow: "RvR",
      title: "Aion 2 Siege Warfare Guide: Territory Control, Siege Weapons, and Large-Scale RvR Strategy",
      description: "A complete guide to siege warfare in Aion 2 — the large-scale RvR endgame where guilds and factions fight for territory control. Learn siege weapon systems, siege tactics, and how to dominate the battlefield.",
      intro: "Siege warfare is the culmination of RvR gameplay in Aion 2. It brings together the guild systems, faction warfare, and territorial control into large-scale battles that define the server landscape. Understanding siege mechanics, weapon systems, and coordination is essential for any guild or faction that wants to compete at the highest level.",
      sourceNote: "Based on NC's official gameplay pages and the Korean service RvR system as of September 2026. Specific siege weapon stats and mechanics may be adjusted for global launch.",
      keywords: ["Aion 2 siege warfare guide", "Aion 2 RvR guide", "Aion 2 siege weapons", "Aion 2 territory control", "Aion 2 faction warfare"],
      sections: [
        section("siege-overview", "Siege Warfare Overview: What You're Fighting For", ["Siege warfare in Aion 2 centers on territory control — factions fight to capture and hold strategic points on the map, each yielding bonuses, resources, and prestige. These territories include castles, outposts, trade routes, and resource nodes that determine which faction dominates a region.", "Siege events occur on scheduled timers and can also be triggered by faction actions. Major sieges (castle sieges) are high-stakes events that can flip regional control and require preparation, coordination, and significant player numbers to win.", "Territory control cascades through the server economy. The faction that controls a region receives trading bonuses, resource extraction rights, and guild perks that make them stronger over time — creating a self-reinforcing power dynamic where controlling territory becomes a strategic necessity, not just an optional activity."]),
        section("siege-weapons", "Siege Weapons: Tools of the Siege", ["Siege weapons are specialized equipment that deal disproportionate damage to structures, fortifications, and other siege vehicles. Each weapon type has unique strengths: battering rams break gates, siege towers provide elevated attack platforms, and siege engines destroy wall sections.", "Siege weapons are built through crafting or guild resources, making them a collective guild investment rather than individual gear. This means that smaller guilds can only field limited siege support, while well-funded guilds can bring overwhelming siege firepower to major conflicts.", "Each siege weapon requires a dedicated crew to operate. The operator manages the weapon's targeting and firing, while support crew members handle ammunition, repairs, and positioning. Crew coordination is critical — a well-operated siege weapon is exponentially more effective than one that's under-coordinated."]),
        section("siege-tactics", "Tactical Approaches: Breach, Defend, and Outlast", ["Offensive sieges typically follow a three-phase approach: approach, breach, and hold. The approach phase involves securing perimeters and dealing with defending sorties. The breach phase focuses on breaking through gates and walls using siege weapons and elite assault teams. The hold phase involves securing the captured point and repelling counter-attacks.", "Defensive sieges are about layering defense and force multiplication. Defense in depth — multiple lines of defense with overlapping fields of fire — means attackers must overcome each layer before reaching the core. Mobile reserves that can plug gaps and counter-attack are essential. Resource management (ammunition, healing, stamina) determines how long a defense can hold.", "For smaller forces, asymmetric tactics are key. Hit-and-run raids, targeted disruption of siege weapon crews, and exploiting terrain features for ambushes can deny territory control without facing the enemy head-on. Guerrilla warfare is a legitimate and effective strategy when facing overwhelming numerical superiority."]),
        section("guild-coordination", "Guild and Faction Coordination", ["Siege warfare is a guild-first activity. Success requires a dedicated leadership structure, clear communication channels, and pre-planned roles for each participant. Voice communication is nearly mandatory for coordination during live sieges — relying on text chat for tactical calls is a liability.", "Guilds should plan siege participation months in advance. This includes building up siege weapon inventory, training officers in siege tactics, stockpiling consumables, and recruiting specialists (siege weapon operators, field healers, scouts). The preparation phase is where most siege campaigns win or lose before the first gate falls.", "Faction-level coordination between allied guilds is equally important. Shared objective assignments, synchronized attack timing, and mutual support agreements prevent friendly fire incidents and ensure that allied forces are not wasted. Regular faction meetings to review strategy and adjust to changing enemy positions are essential."]),
        section("endgame-rewards", "Endgame Rewards and Long-Term Impact", ["Territory control rewards extend far beyond prestige. Controlled territories provide guild income through resource extraction and trade bonuses. Key territories may grant access to exclusive boss encounters or crafting stations. Territory control is also a prerequisite for faction-level achievements and seasonal events.", "The economic impact of siege warfare is persistent — controlling a territory generates ongoing Kinah income that can be reinvested in guild equipment, siege weapons, and training. This creates a snowball effect where successful guilds become increasingly powerful, making it harder for challengers to compete.", "For global launch, expect the same territory control framework with potential adjustments for the modified Season 1 progression curve. Early guilds that establish territory dominance will have a significant economic advantage heading into endgame content."]),
      ],
    }),
    "zh-hans": articleCopy(guideLabels, "zh-hans", 8, {
      eyebrow: "RvR",
      title: "Aion 2 攻城战攻略：领土控制、攻城武器与大规模 RvR 策略",
      description: "Aion 2 攻城战完整指南——公会与阵营为领土控制而战的大规模 RvR 终局。了解攻城武器系统、攻城战术以及如何主导战场。",
      intro: "攻城战是 Aion 2 RvR 玩法的巅峰。它将公会系统、阵营战争和领土控制融合为大规模战斗，定义了服务器格局。理解攻城机制、武器系统和协调是任何想要最高水平竞争的公会或阵营的必修课。",
      sourceNote: "基于 NC 官方游戏页面和韩服 RvR 系统（截至 2026 年 9 月）。全球版的攻城武器属性和机制可能有调整。",
      keywords: ["Aion 2 攻城战攻略", "Aion 2 RvR 攻略", "Aion 2 攻城武器", "Aion 2 领土控制", "Aion 2 阵营战争"],
      sections: [
        section("siege-overview", "攻城战概述：你在为什么而战", ["Aion 2 的攻城战围绕领土控制展开——阵营为争夺地图上的战略据点而战斗，每个据点提供加成、资源和声望。这些领土包括城堡、前哨站、贸易路线和资源节点，决定哪个阵营主导一个区域。", "攻城事件按定时触发，也可由阵营行动触发。大型攻城（城堡攻城）是高风险事件，可能翻转区域控制，需要准备、协调和大量玩家才能获胜。", "领土控制级联影响服务器经济。控制区域的阵营获得交易加成、资源开采权和公会福利，使其随时间变得更强——创造自我强化的权力动态，使控制领土成为战略必要而非可选活动。"]),
        section("siege-weapons", "攻城武器：攻城的工具", ["攻城武器是对建筑、工事和其他攻城载具造成不成比例伤害的专用设备。每种武器类型有独特优势：攻城锤破门，攻城塔提供高攻平台，攻城引擎摧毁城墙段落。", "攻城武器通过制作或公会资源建造，使它们成为公会集体投资而非个人装备。这意味着小编队只能有限的攻城支援，而资金充足的公会可以带来压倒性的攻城火力。", "每件攻城武器需要专门的操作组。操作者管理武器瞄准和射击，辅助组员负责弹药、维修和定位。组内协调至关重要——协调良好的攻城武器效果远超协调不佳的武器。"]),
        section("siege-tactics", "战术方法：突破、防御与消耗", ["进攻性攻城通常遵循三阶段方法：接近、突破、坚守。接近阶段涉及确保外围和应对防御突袭。突破阶段集中在用攻城武器和精英突击队破门破墙。坚守阶段涉及确保占领点并击退反攻。", "防御性攻城是关于分层防御和力量倍增。纵深防御——多层防御与重叠火力——意味着攻击者必须突破每一层才能到达核心。机动预备队填补缺口和反攻至关重要。资源管理（弹药、治疗、耐力）决定防御能维持多久。", "对较小的部队而言，非对称战术是关键。打了就跑的袭击、针对攻城武器组的定向破坏、利用地形进行伏击可以在不正面交锋的情况下拒绝领土控制。游击战是在面对压倒性数量优势时合法且有效的策略。"]),
        section("guild-coordination", "公会与阵营协调", ["攻城战是公会优先的活动。成功需要专门的领导结构、清晰的沟通渠道和每个参与者的预先计划角色。语音通信在实时攻城期间几乎是必需的——依赖文本聊天进行战术呼叫是劣势。", "公会应提前数月计划攻城参与。这包括建造攻城武器库存、训练军官掌握攻城战术、囤积消耗品和招募专家（攻城武器操作者、野战治疗师、侦察员）。准备阶段是大多数攻城战役在城门倒下前就已经胜负的地方。", "联盟公会之间的阵营级协调同样重要。共享目标分配、同步攻击时机和相互支持协议可防止友军误伤并确保盟友力量不被浪费。定期阵营会议审查策略并根据敌方位置变化调整是必需的。"]),
        section("endgame-rewards", "终局奖励与长期影响", ["领土控制奖励远不止声望。控制的领土通过资源开采和交易加成提供公会收入。关键领土可能授予独占 Boss 遭遇或制作站点的访问权。领土控制也是阵营级成就和赛季活动的前提条件。", "攻城战的经济影响是持久的——控制领土产生持续的 Kinah 收入，可再投资于公会装备、攻城武器和训练。这创造滚雪球效应，使成功的公会越来越强，使挑战者更难竞争。", "全球版预期相同的领土控制框架，但改良版 Season 1 进阶曲线可能有调整。早期建立领土主导的公会将在终局内容中获得显著的经济优势。"]),
      ],
    }),
    fr: articleCopy(guideLabels, "fr", 8, {
      eyebrow: "RvR",
      title: "Guide de la Guerre de Siège Aion 2 : Contrôle Territorial, Armes de Siège et Stratégie RvR",
      description: "Un guide complet sur la guerre de siège dans Aion 2 — le contenu endgame RvR à grande échelle où les guildes et factions combattent pour le contrôle territorial.",
      intro: "La guerre de siège est l'apogée du gameplay RvR dans Aion 2. Elle réunit les systèmes de guilde, la guerre de faction et le contrôle territorial dans de grands combats qui définissent l'ensemble du serveur.",
      sourceNote: "Basé sur les pages officielles NC et le système RvR du service coréen (septembre 2026). Les stats des armes de siège peuvent être ajustées pour le lancement mondial.",
      keywords: ["Guide guerre de siège Aion 2", "Guide RvR Aion 2", "Armes de siège Aion 2", "Contrôle territorial Aion 2", "Guerre de faction Aion 2"],
      sections: [
        section("siege-overview", "Vue d'ensemble : ce pour quoi vous combattez", ["La guerre de siège dans Aion 2 tourne autour du contrôle territorial — les factions combattent pour capturer et maintenir des points stratégiques sur la carte, chacun offrant bonus, ressources et prestige.", "Les événements de siège ont lieu sur des minuteries planifiées et peuvent aussi être déclenchés par des actions de faction. Les sièges majeurs (sièges de châteaux) sont des événements à haut enjeu qui peuvent inverser le contrôle régional.", "Le contrôle territorial cascade dans l'économie du serveur. La faction qui contrôle une région reçoit des bonus commerciaux, des droits d'extraction et des avantages de guilde qui la renforcent avec le temps."]),
        section("siege-weapons", "Armes de Siège : les outils du siège", ["Les armes de siège sont des équipements spécialisés qui infligent des dégâts disproportionnés aux structures, fortifications et véhicules de siège. Chaque type a des forces uniques : béliers brisent les portes, tours de siège offrent des plateformes, canons détruisent les murailles.", "Les armes de siège sont construites via l'artisanat ou les ressources de guilde, ce qui en fait un investissement collectif plutôt qu'un équipement individuel. Les guildes mieux financées peuvent apporter une puissance de feu de siège écrasante.", "Chaque arme de siège nécessite un équipage dédié pour son fonctionnement. l'opérateur gère le ciblage et le tir, tandis que l'équipage de soutien gère les munitions, les réparations et le positionnement."]),
        section("siege-tactics", "Approches tactiques : Brèche, Défense et Endurance", ["Les sièges offensifs suivent généralement trois phases : approche, brèche et maintien. L'approche sécurise les périmètres et gère les sorties défensives. La brèche se concentre sur la percée des portes et murailles. Le maintien sécurise le point capturé et repousse les contre-attaques.", "Les sièges défensifs concernent la défense en profondeur et la multiplication de force. Plusieurs lignes de défense avec des champs de tir chevauchants obligent l'assaillant à surmonter chaque couche avant d'atteindre le cœur.", "Pour les forces plus petites, les tactiques asymétriques sont clés. Les raids frappe-et-fuis, la disruption ciblée des équipages de siège et l'exploitation du terrain pour les embuscades peuvent empêcher le contrôle territorial sans affrontement frontal."]),
        section("guild-coordination", "Coordination Guilde et Faction", ["La guerre de siège est une activité première de guilde. Le succès nécessite une structure de leadership dédiée, des canaux de communication clairs et des rôles préplanifiés pour chaque participant. La communication vocale est quasi obligatoire pendant les sièges en direct.", "Les guildes doivent planifier leur participation des mois à l'avance, incluant l'accumulation d'un inventaire d'armes de siège, la formation des officiers, l'accumulation de consommables et le recrutement de spécialistes.", "La coordination au niveau faction entre les guildes alliées est tout aussi importante. L'assignation d'objectifs partagés, la synchronisation des attaques et les accords de soutien mutuel préviennent les dégâts sur alliés."]),
        section("endgame-rewards", "Récompenses Endgame et Impact Long Terme", ["Les récompenses du contrôle territorial dépassent largement le prestige. Les territoires contrôlés fournissent un revenu de guilde via l'extraction de ressources et les bonus commerciaux.", "L'impact économique est permanent — contrôler un territoire génère un revenu Kinah continu qui peut être réinvesti dans l'équipement, les armes de siège et l'entraînement, créant un effet boule de neige.", "Pour le lancement mondial, attendez-vous au même cadre de contrôle territorial avec des ajustements potentiels pour la courbe de progression Season 1 modifiée."]),
      ],
    }),
    de: articleCopy(guideLabels, "de", 8, {
      eyebrow: "RvR",
      title: "Aion 2 Belagerungskrieg-Guide: Territorialkontrolle, Belagerungswaffen und RvR-Strategie",
      description: "Ein umfassender Guide zum Belagerungskrieg in Aion 2 — das großangelegte RvR-Endgame, bei dem Gilden und Fraktionen um die Territorialkontrolle kämpfen.",
      intro: "Der Belagerungskrieg ist der Höhepunkt des RvR-Gameplays in Aion 2. Er vereint das Gildensystem, den Fraktionskrieg und die Territorialkontrolle in große Schlachten, die die Serverlandschaft prägen.",
      sourceNote: "Basierend auf den offiziellen NC-Spielseiten und dem RvR-System des koreanischen Dienstes (September 2026). Belagerungswaffen-Stats können für den globalen Launch angepasst werden.",
      keywords: ["Aion 2 Belagerungskrieg-Guide", "Aion 2 RvR-Guide", "Aion 2 Belagerungswaffen", "Aion 2 Territorialkontrolle", "Aion 2 Fraktionskrieg"],
      sections: [
        section("siege-overview", "Übersicht: Wofür ihr kämpft", ["Der Belagerungskrieg in Aion 2 dreht sich um Territorialkontrolle — Fraktionen kämpfen um strategische Punkte auf der Karte, die jeweils Boni, Ressourcen und Ansehen liefern.", "Belagerungsevents finden nach festgelegten Zeitplänen statt und können auch durch Fraktionsaktionen ausgelöst werden. Große Belagerungen (Schlossbelagerungen) sind Hochrisiko-Events, die die regionale Kontrolle umkehren können.", "Territorialkontrolle wirkt sich kaskadenartig auf die Serverwirtschaft aus. Die kontrollierende Fraktion erhält Handelsboni, Ressourcenrechte und Gildevorteile, die sie mit derl Zeit stärker machen."]),
        section("siege-weapons", "Belagerungswaffen: Werkzeuge der Belagerung", ["Belagerungswaffen sind Spezialgeräte, die unverhältnismäßig hohen Schaden an Strukturen und Befestigungen verursachen. Jede Waffentyp hat einzigartige Stärken: Rammböcke sprengen Tore, Belagerungstürme bieten erhöhte Angriffsplattformen.", "Belagerungswaffen werden durch Handwerk oder Gildenressourcen gebaut, was sie zu einer kollektiven Gildeninvestition macht. Gut finanzierte Gilden können eine überwältigende Belagerungsfeuerkraft bringen.", "Jede Belagerungswaffe benötigt eine dedizierte Crew zur Bedienung. Der Operator steuert Zielung und Schuss, während die Supportcrew Munition, Reparaturen und Positionierung übernimmt."]),
        section("siege-tactics", "Taktische Ansätze: Breach, Verteidigen und Ausdauern", ["Offensive Belagerungen folgen in der Regel drei Phasen: Annäherung, Durchbruch und Halten. Die Annäherungsphase sichert den Perimeter. Die Durchbruchsphase konzentriert sich auf das Brechen von Toren und Wänden. Die Haltephase sichert den eroberten Punkt.", "Defensive Belagerungen basieren auf Verteidigung in der Tiefe und Kraftmultiplikation. Mehrere Verteidigungslinien mit überlappendem Feuer erzwingen, dass Angreifer jede Schicht überwinden müssen, bevor sie das Herz erreichen.", "Für kleinere Streitkräfte sind asymmetrische Taktiken entscheidend. Hit-and-Run-Angriffe, gezielte Störung von Belagerungscrews und die Nutzung von Gelände für Überfälle können die Territorialkontrolle verweigern, ohne dem Gegner frontal zu begegnen."]),
        section("guild-coordination", "Gilden- und Fraktionskoordination", ["Der Belagerungskrieg ist eine gildenzentrierte Aktivität. Erfolg erfordert eine dedizierte Führungsstruktur, klare Kommunikationskanäle und vorab geplane Rollen für jeden Teilnehmer. Sprachkommunikation ist während live Belagerungen fast Pflicht.", "Gilden sollten die Belagerungsteilnahme monatelang im Voraus planen, einschließlich Aufbau des Belagerungswaffenbestands, Ausbildung von Offizieren, Vorräten an Verbrauchsmaterialien und Rekrutierung von Spezialisten.", "Fraktionskoordination zwischen befreundeten Gilden ist ebenso wichtig. Geteilte Zielzuweisungen, synchronisierte Angriffszeitpunkte und gegenseitige Unterstützungsabkommen verhindern friendly-fire-Vorfälle."]),
        section("endgame-rewards", "Endgame-Belohnungen und Langzeitwirkung", ["Die Belohnungen für Territorialkontrolle gingen weit über Prestige hinaus. Kontrollierte Gebiete liefern Gilden Einkünfte durch Ressourcengewinnung und Handelsboni.", "Der wirtschaftliche Einfluss ist anhaltend — die Kontrolle eines Gebiets erzeugt laufendes Kinah-Einkommen, das in Gilden-Ausrüstung, Belagerungswaffen und Training reinvestiert werden kann.", "Für den globalen Launch erwartet man den gleichen Territorialkontrollrahmen mit möglichen Anpassungen an die modifizierte Season-1-Fortschrittskurve."]),
      ],
    }),
    es: articleCopy(guideLabels, "es", 8, {
      eyebrow: "RvR",
      title: "Guía de Guerra de Asedio en Aion 2: Control Territorial, Armas de Asedio y Estrategia RvR",
      description: "Una guía completa sobre la guerra de asedio en Aion 2 — el endgame RvR a gran escala donde gremios y facciones luchan por el control territorial.",
      intro: "La guerra de asedio es el punto culminante del gameplay RvR en Aion 2. Reúne los sistemas de gremio, la guerra de facciones y el control territorial en batallas a gran escala que definen el panorama del servidor.",
      sourceNote: "Basado en las páginas oficiales de NC y el sistema RvR del servicio coreano (septiembre 2026). Las estadísticas de las armas de asedio pueden ajustarse para el lanzamiento global.",
      keywords: ["Guía guerra de asedio Aion 2", "Guía RvR Aion 2", "Armas de asedio Aion 2", "Control territorial Aion 2", "Guerra de facciones Aion 2"],
      sections: [
        section("siege-overview", "Visión general: por lo que luchas", ["La guerra de asedio en Aion 2 gira alrededor del control territorial — las facciones luchan para capturar y mantener puntos estratégicos en el mapa, cada uno otorga bonus, recursos y prestigio.", "Los eventos de asedio ocurren en horarios programados y también pueden ser activados por acciones de facción. Los asedios mayores (asedios de castillo) son eventos de alto riesgo que pueden revertir el control regional.", "El control territorial se cascada en la economía del servidor. La facción que controla una región recibe bonus comerciales, derechos de extracción y ventajas de gremio que los fortalecen con el tiempo."]),
        section("siege-weapons", "Armas de Asedio: herramientas del asedio", ["Las armas de asedio son equipos especializados que infligen daño desproporcionado a estructuras, fortificaciones y vehículos de asedio. Cada tipo tiene fortalezas únicas: arietes rompen puertas, torres de asedio ofrecen plataformas elevadas, cañones destrozan secciones de muro.", "Las armas de asedio se construyen mediante artesanía o recursos de gremio, lo que las convierte en una inversión colectiva del gremio en lugar de equipo individual.", "Cada arma de asedio requiere una tripulación dedicada para su operación. El operador gestiona el apuntado y el disparo, mientras que el equipo de apoyo maneja municiones, reparaciones y posicionamiento."]),
        section("siege-tactics", "Enfoques tácticos: Ruptura, Defender y Aguantar", ["Los asedios ofensivos generalmente siguen tres fases: aproximación, ruptura y sostenimiento. La fase de aproximación asegura perímetros y gestiona salidas defensivas. La fase de ruptura se centra en romper puertas y muros. La fase de sostenimiento asegura el punto capturado y repele contraataques.", "Los asedios defensivos se tratan de defensa en profundidad y multiplicación de fuerza. Múltiples líneas de defensa con campos de fuego solapados obligan al atacante a superar cada capa antes de alcanzar el núcleo.", "Para fuerzas más pequeñas, las tácticas asimétricas son clave. Incursiones de golpe y fuga, la interrupción dirigida de tripulaciones de asedio y la explotación del terreno para emboscadas pueden negar el control territorial sin enfrentar al enemigo de frente."]),
        section("guild-coordination", "Coordinación de Gremio y Facción", ["La guerra de asedio es una actividad de gremio por excelencia. El éxito requiere una estructura de liderazgo dedicada, canales de comunicación claros y roles preplanificados para cada participante. La comunicación de voz es casi obligatoria durante asedios en vivo.", "Los gremios deben planificar su participación en asedios meses antes. Esto incluye construir inventario de armas de asedio, entrenar oficiales en tácticas de asedio, almacenar consumibles y reclutar especialistas.", "La coordinacion a nivel de facción entre gremios aliados es igualmente importante. Asignaciones de objetivos compartidos, tiempos de ataque sincronizados y acuerdos de apoyo mutuo previenen incidentes de fuego amigo."]),
        section("endgame-rewards", "Recompensas Endgame y Impacto a Largo Plazo", ["Las recompensas del control territorial van mucho más allá del prestigio. Los territorios controlados proporcionan ingresos para el gremio a través de la extracción de recursos y bonus comerciales.", " el impacto económico es persistente — controlar un territorio genera ingresos continuos de Kinah que pueden reinvertirse en equipo de gremio, armas de asedio y entrenamiento.", "Para el lanzamiento global, esperen el mismo marco de control territorial con posibles ajustes para la curva de progreso de la Temporada 1 modificada."]),
      ],
    }),
    ja: articleCopy(guideLabels, "ja", 8, {
      eyebrow: "RvR",
      title: "Aion 2 攻城戦ガイド：領土制御、攻城兵器、大規模RvR戦略",
      description: "Aion 2における攻城戦の完全ガイド——ギルドと陣営が領土制御を争う大規模RvRの終局コンテンツ。攻城兵器システム、攻城戦術、戦場の支配方法を学ぼう。",
      intro: "攻城戦はAion 2のRvRプレイの集大成です。ギルドシステム、陣営戦争、領土制御を一つの大規模な戦闘にまとめ、サーバーの景観を定義します。",
      sourceNote: "NC公式ゲームプレイページと韓国サーバーのRvRシステム（2026年9月時点）に基づく。攻城兵器のステータスとメカニクスはグローバル版向けに調整される可能性があります。",
      keywords: ["Aion 2 攻城戦ガイド", "Aion 2 RvRガイド", "Aion 2 攻城兵器", "Aion 2 領土制御", "Aion 2 陣営戦争"],
      sections: [
        section("siege-overview", "攻城戦の概要：何のために戦うのか", ["Aion 2の攻城戦は領土制御を軸とします。陣営はマップ上の戦略ポイントの占領・維持のために戦い、各ポイントにはボーナス、リソース、威信が付与されます。", "攻城イベントは予定時刻に発生しますが、陣営の行動によってもトリガーされることがあります。大規模攻城（城攻城）は高いリスクと見返りを伴うイベントであり、地域支配が逆転する可能性があります。", "領土制御はサーバー経済に連鎖的に影響します。地域を支配する陣営は交易ボーナス、リソース採掘権、ギルド特典を得て、時間の経過とともに強くなる——自己強化型の権力動態を生み出します。"]),
        section("siege-weapons", "攻城兵器：攻城の道具", ["攻城兵器は建造物や防衛施設に対して圧倒的なダメージを与える特殊装備です。各タイプに固有の強みがあり、攻城槌は門を破壊し、攻城塔は高所攻撃プラットフォームとなり、攻城砲は城壁を破壊します。", "攻城兵器はクラフトまたはギルドリソースで建造され、個人装備ではなくギルドの集団投資となります。資金の豊富なギルドは圧倒的な攻城火力を展開できます。", "各攻城兵器には専用の操縦クルーが必要です。操縦者が標的と発射を管理し、補助員が弾薬、修理、配置を担当します。クルーの連携が重要です。"]),
        section("siege-tactics", "戦術アプローチ：突破、防御、消耗", ["攻撃的な攻城は通常三段階を踏みます：接近、突破、維持。接近段階では警戒線と防御側の出撃に対応。突破段階では攻城兵器とエリート突撃隊で門・壁を突破。維持段階では占領点を確保し反撃を退ける。", "防御的な攻城は多層防御と兵力倍増が鍵です。重なり合う火力を持つ多層防御により、攻撃者は各層を突破しなければ核心に到達できません。機動予備隊による穴埋めと反撃が不可欠です。", "小規模な部隊には非対称戦術が重要です。打了就跑の襲撃、攻城兵器クルーへの定点攪乱、地形を利用した伏撃により、正面衝突なしに領土制御を阻止できます。"]),
        section("guild-coordination", "ギルドと陣営の調整", ["攻城戦はギルド中心の活動です。成功には専用リーダーシップ構造、明確なコミュニケーションチャネル、各参加者の事前に計画された役割が必要です。実時間攻城では音声通信がほぼ必須です。", "ギルドは攻城への参加を数ヶ月前から計画すべきです。攻城兵器の在庫確保、将校の戦術訓練、消耗品の備蓄、専門家の採用（攻城兵器操縦者、野戦ヒューラー、偵察員）を含みます。", "同盟ギルド間の陣営レベルの調整も同様に重要です。共有目標の割り当て、攻撃タイミングの同期、相互支援協定により、味方誤射や同盟軍の無駄遣いを防止します。"]),
        section("endgame-rewards", "終局報酬と長期影響", ["領土制御の報酬は威信以上に広がります。支配地域はリソース採掘と交易ボーナスを通じてギルド収入を提供します。重要地域は独占ボス遭遇やクラフトステーションへのアクセスを付与する可能性があります。", "攻城戦の経済的影響は永続的です。地域支配は継続的なKinah収入を生み出し、ギルド装備・攻城兵器・訓練に再投資できます。成功したギルドは強力になり、挑戦者の競争を困難にします。", "グローバル版では同一の領土制御フレームワークを想定していますが、改良版Season 1の進捗曲線に合わせた調整がある可能性があります。"]),
      ],
    }),
    "pt-br": articleCopy(guideLabels, "pt-br", 8, {
      eyebrow: "RvR",
      title: "Guia de Guerra de Cerco do Aion 2: Controle Territorial, Armas de Cerco e Estratégia RvR",
      description: "Um guia completo sobre guerra de cerco no Aion 2 — o conteúdo endgame RvR em larga escala onde guildas e facções lutam pelo controle territorial.",
      intro: "A guerra de cerco é o auge do gameplay RvR no Aion 2. Ela reúne sistemas de guilda, guerra de facções e controle territorial em batalhas em larga escala que definem a paisagem do servidor.",
      sourceNote: "Baseado nas páginas oficiais da NC e no sistema RvR do serviço coreano (setembro de 2026). Estatísticas de armas de cerco podem ser ajustadas para o lançamento global.",
      keywords: ["Guia guerra de cerco Aion 2", "Guia RvR Aion 2", "Armas de cerco Aion 2", "Controle territorial Aion 2", "Guerra de facções Aion 2"],
      sections: [
        section("siege-overview", "Visão geral: pelo que você luta", ["A guerra de cerco no Aion 2 gira em torno do controle territorial — facções lutam para capturar e manter pontos estratégicos no mapa, cada uns oferecendo bônus, recursos e prestígio.", "Eventos de cerco ocorrem em horários programados e também podem ser acionados por ações de facção. Cercos maiores (cerco de castelo) são eventos de alto risco que podem reverter o controle regional.", "O controle territorial se propaga pela economia do servidor. A facção que controla uma região recebe bônus comerciais, direitos de extração e vantagens de guilda que os fortalecem ao longo do tempo."]),
        section("siege-weapons", "Armas de Cerco: ferramentas do cerco", ["Armas de cerco são equipamentos especializados que causam dano desproporcional a estruturas, fortificações e veículos de cerco. Cada tipo tem forças únicas: aríetes quebram portas, torres de cerco oferecem plataformas elevadas, canhões destroem seções de muralha.", "Armas de cerco são construídas através de artesanato ou recursos de guilda, tornando-as um investimento colectivo da guilda em vez de equipamento individual. Guildas bem financiadas podem trazer poder de fogo de cerco esmagador.", "Cada arma de cerco requer uma tripulação dedicada para operação. O operador gerencia mira e disparo, enquanto a equipa de suporte lida com munição, reparos e posicionamento."]),
        section("siege-tactics", "Abordagens táticas: Brecha, Defender e Aguentar", ["Cerco ofensivos geralmente seguem três fases: aproximação, brecha e sustentação. A fase de aproximação garante perímetros e gerencia saídas defensivas. A fase de brecha foca na ruptura de portas e muralhas. A fase de sustentação garante o ponto capturado e repel contra-ataques.", "Cerco defensivos tratam de defesa em profundidade e multiplicação de força. Múltiplas linhas de defesa com campos de tiro sobrepostos significam que os atacantes devem superar cada camada antes de alcançar o núcleo.", "Para forças menores, táticas assimétricas são a chave. Raides golpe-e-fuga, a interrupção direcionada de tripulações de cerco e a exploração do terreno para emboscadas podem negar o controle territorial sem enfrentar o inimigo de frente."]),
        section("guild-coordination", "Coordenação de Guilda e Facção", ["A guerra de cerco é uma atividade centrada na guilda. O sucesso requer uma estrutura de liderança dedicada, canais de comunicação claros e papéis pré-planejados para cada participante. Comunicação de voz é quase obrigatória durante cercos ao vivo.", "Guildas devem planejar sua participação em cercos meses antes. Isso inclui acumular estoque de armas de cerco, treinar oficiais em táticas de cerco, estocar consumíveis e recrutar especialistas.", "A coordenação no nível de facção entre guildas aliadas é igualmente importante. Atribuições de objetivos compartilhados, tempos de ataque sincronizados e acordos de apoio mútuo previnem incidentes de dano a aliados."]),
        section("endgame-rewards", "Recompensas Endgame e Impacto de Longo Prazo", ["As recompensas do controle territorial vão muito além do prestígio. Territórios controlados fornecem renda para a guilda através da extração de recursos e bônus comerciais.", "O impacto econômico é persistente — controlar um território gera renda contínua de Kinah que pode ser reinvestida em equipamento de guilda, armas de cerco e treinamento.", "Para o lançamento global, espere o mesmo quadro de controle territorial com possíveis ajustes para a curva de progresso da Season 1 modificada."]),
      ],
    }),
    ru: articleCopy(guideLabels, "ru", 8, {
      eyebrow: "RvR",
      title: "Гайд по осадной войне Aion 2: Контроль территории, осадные орудия и стратегия RvR",
      description: "Полный гайд по осадной войне в Aion 2 — крупномасштабный RvR-контент, где гильдии и фракции борются за контроль территории.",
      intro: "Осадная война — это вершина RvR-геймплея в Aion 2. Она объединяет систему гильдий, войну фракций и контроль территории в масштабные битвы, определяющие облик сервера.",
      sourceNote: "Основано на официальных игровых страницах NC и системе RvR корейского сервиса (сентябрь 2026). Характеристики осадных орудий могут быть скорректированы для глобального запуска.",
      keywords: ["Гайд осадная война Aion 2", "Гайд RvR Aion 2", "Осадные орудия Aion 2", "Контроль территории Aion 2", "Война фракций Aion 2"],
      sections: [
        section("siege-overview", "Обзор: за что вы сражаетесь", ["Осадная война в Aion 2 сосредоточена на контроле территории — фракции сражаются за захват и удержание стратегических точек на карте, каждая из которых даёт бонусы, ресурсы и престиж.", "События осадных войн происходят по расписанию和 могут также инициироваться действиями фракции. Крупные осады (осада замка) — это высокорисковые события, способные изменить контроль над регионом.", "Контроль территории каскадно влияет на экономику сервера. Фракция, контролирующая регион, получает торговые бонусы, права на добычу ресурсов и преимущества гильдии, которые делают её сильнее со временем."]),
        section("siege-weapons", "Осадные орудия: инструменты осады", ["Осадные орудия — это специализированное оборудование, наносящее непропорциональный урон по зданиям, укреплениям и осадным транспортным средствам. Каждый тип имеет уникальные преимущества: тараны ломают ворота, осадные башни обеспечивают elevated platforms, осадные орудия разрушают участки стен.", "Осадные орудия создаются через ремесло или ресурсы гильдии, что делает их коллективной инвестицией гильдии, а не личным снаряжением. Гильдии с достаточным финансированием могут выдвинуть подавляющую осадную мощь.", "Каждое осадное орудие требует специализированную команду. Оператор управляет прицеливанием и огнём, а команда поддержки отвечает за боеприпасы, ремонт и позиционирование."]),
        section("siege-tactics", "Тактические подходы: прорыв, оборона, выносливость", ["Наступательные осады обычно следуют трёхфазному подходу: подход, прорыв, удержание. Фаза подхода включает обеспечение периметра и отпор вылазкам защитников. Фаза прорыва фокусируется на разрушении ворот и стен с помощью осадных орудий и элитных штурмовых групп. Фаза удержания — закрепление захваченной точки и отпор контратакам.", "Оборонительные осады — это многослойная оборона и умножение силы. Множественные линии обороны с перекрывающимися зонами огня означают, что нападающие должны преодолеть каждый слой, прежде чем достичь ядра.", "Для меньших сил асимметричная тактика ключевая. Рейды «ударил и убежал», целенаправленное разрушение команд осадных орудий и использование особенностей местности для засад могут лишить противника контроля территории без прямою столкновения."]),
        section("guild-coordination", "Координация гильдии и фракции", ["Осадная война — это приоритетная гильдейская активность. Успех требует выделенной структуры руководства, чётких каналов связи и заранее запланированных ролей для каждого участника. Голосовая связь практически обязательна во время живых осад.", "Гильдии должны планировать участие в осадах за месяцы. Это включает накопление запаса осадных орудий, подготовку офицеров в тактике осад, запас расходников и набор специалистов.", "Координация на уровне фракции между союзными гильдиями также важна. Совместное распределение целей, синхронизация атак и соглашения о взаимной поддержке предотвращают дружественный огонь."]),
        section("endgame-rewards", "Endgame-награды и долгосрочное влияние", ["Награды за контроль территории простираются далеко за пределы престижа. Контролируемые территории обеспечивают гильдии доход через добычу ресурсов и торговые бонусы.", "Экономическое влияние осадной войны устойчиво — контроль территории генерирует постоянный доход в Kinah, который можно реинвестировать в гильдейское снаряжение, осадные орудия и обучение.", "Для глобального запуска ожидается та же структура контроля территории с возможными корректировками для изменённой кривой прогрессии Season 1."]),
      ],
    }),
    ko: articleCopy(guideLabels, "ko", 8, {
      eyebrow: "RvR",
      title: "Aion 2 포격전 가이드: 영토 통제, 포격 무기, 대규모 RvR 전략",
      description: "Aion 2 포격전 완전 가이드 — 길드와 진영이 영토 통제를 두고 싸우는 대규모 RvR 엔드게임. 포격 무기 시스템, 포격 전술, 전장 지배 방법을 배우세요.",
      intro: "포격전은 Aion 2의 RvR 플레이의 최고봉입니다. 길드 시스템, 진영 전쟁, 영토 통제를 하나의 대규모 전투로 결합하여 서버 환경을 정의합니다.",
      sourceNote: "NC 공식 게임플레이 페이지와 한국 서버의 RvR 시스템(2026년 9월 기준)에 기반. 포격 무기 스탯과 메카닉은 글로벌 출시용으로 조정될 수 있습니다.",
      keywords: ["Aion 2 포격전 가이드", "Aion 2 RvR 가이드", "Aion 2 포격 무기", "Aion 2 영토 통제", "Aion 2 진영 전쟁"],
      sections: [
        section("siege-overview", "포격전 개요: 무엇을 위해 싸우는가", ["Aion 2의 포격전은 영토 통제를 중심으로 합니다. 진영은 맵 위의 전략적 점령지의 점령·유지를 위해 싸우며, 각 점령지에는 보너스, 리소스, 명성이 부여됩니다.", "포격 이벤트는 일정 시각에 발생하지만, 진영의 행동에 의해 트리거되기도 합니다. 대규모 포격(성 포격)은 높은 위험과 보상을 동반하는 이벤트로, 지역 지배가 뒤집힐 수 있습니다.", "영토 통제는 서버 경제에 연쇄적으로 영향을 미칩니다. 지역을 지배하는 진영은 교역 보너스, 리소스 채굴권, 길드 특전을 받아 시간의 흐름에 따라 강해집니다."]),
        section("siege-weapons", "포격 무기: 포격의 도구", ["포격 무기는 건물이나 방어 시설에 압도적인 피해를 주는 특수 장비입니다. 각 유형에 고유한 강점이 있으며, 돌격병은 문을 파괴하고, 포격탑은 고소 공격 플랫폼이 되며, 포격포는 성벽을 파괴합니다.", "포격 무기는 크래프팅 또는 길드 리소스로 건설되며, 개인 장비가 아닌 길드의 집단 투자로 됩니다. 자금력이 풍부한 길드는 압도적인 포격 화력을 전개할 수 있습니다.", "각 포격 무기에는 전용 조종 크루가 필요합니다. 조종수가 표적과 발사를 관리하고, 보조원이 탄약, 수리, 배치와 책임을 집니다."]),
        section("siege-tactics", "전술 접근법: 돌파, 방어, 소모", ["공격적 포격은 보통 세 단계를 따릅니다: 접근, 돌파, 유지. 접근 단계에서는 경계선과 방어측의 출격을 대응합니다. 돌파 단계에서는 포격 무기와 특급 돌격대가 문·벽을 돌파합니다. 유지 단계에서는 점령지를 확보하고 반격을 저지합니다.", "방어적 포격은 다층 방어와 전력 증강이 핵심입니다. 겹치는 화력을 가진 다층 방어에 의해, 공격자는 각 층을 돌파하지 않으면 핵에 도달할 수 없습니다.", "소규모 부대에는 비대칭 전술이 중요합니다. 打了就跑 습격, 포격 무기 크루에 대한 정점 교란, 지형을 활용한 매복으로 정면 충돌 없이 영토 통제를 저지할 수 있습니다."]),
        section("guild-coordination", "길드와 진영의 조정", ["포격전은 길드 중심의 활동입니다. 성공에는 전용 리더십 구조, 명확한 소통 채널, 각 참가자의 사전에 계획된 역할이 필요합니다. 실시간 포격 중 음성 소통은 거의 필수입니다.", "길드는 포격에 대한 참여를 수개월前에 계획해야 합니다. 포격 무기 재고 확보, 지휘관의 전술 훈련, 소모품 비축, 전문가 채용(포격 무기 조종수, 야전 힐러, 정찰병)을 포함합니다.", "연합 길드 간의 진영 레벨 조정도 동일하게 중요합니다. 공동 목표 배분, 공격 타이밍 동기화, 상호 지원 협정으로 우군 오사와 연합군 낭비를 방지합니다."]),
        section("endgame-rewards", "엔드게임 보상과 장기 영향", ["영토 통제 보상은 명성 이상의 범위를 가집니다. 지배한 지역은 리소스 채굴과 교역 보너스를 통해 길드 수입을 제공합니다. 주요 지역은 독점 보스 전투나 크래프팅 스테이션 접근을 부여할 수 있습니다.", "포격전의 경제적 영향은 지속적입니다. 지역 지배는 계속적인 Kinah 수입을 생성하며, 길드 장비·포격 무기·훈련에 재투자할 수 있습니다.", "글로벌 버전에서는 동일한 영토 통제 프레임워크를 예상하지만, 改良版 Season 1의 진행 곡선에 맞는 조정이 있을 수 있습니다."]),
      ],
    }),
    "zh-hant": articleCopy(guideLabels, "zh-hant", 8, {
      eyebrow: "RvR",
      title: "Aion 2 攻城戰攻略：領土控制、攻城武器與大規模 RvR 策略",
      description: "Aion 2 攻城戰完整指南——公會與陣營為領土控制而戰的大規模 RvR 終局。了解攻城武器系統、攻城戰術以及如何主導戰場。",
      intro: "攻城戰是 Aion 2 RvR 玩法的巔峰。它將公會系統、陣營戰爭和領土控制融合為大規模戰鬥，定義了伺服器格局。理解攻城機制、武器系統和協調是任何想要最高水平競爭的公會或陣營的必修課。",
      sourceNote: "基於 NC 官方遊戲頁面和韓服 RvR 系統（截至 2026 年 9 月）。全球版的攻城武器屬性和機制可能有調整。",
      keywords: ["Aion 2 攻城戰攻略", "Aion 2 RvR 攻略", "Aion 2 攻城武器", "Aion 2 領土控制", "Aion 2 陣營戰爭"],
      sections: [
        section("siege-overview", "攻城戰概述：你在為什麼而戰", ["Aion 2 的攻城戰圍繞領土控制展開——陣營為爭奪地圖上的戰略據點而戰鬥，每個據点提供加成、資源和聲望。這些領土包括城堡、前哨站、貿易路線和資源節點，決定哪個陣營主導一個區域。", "攻城事件按定時觸發，也可由陣營行動觸發。大型攻城（城堡攻城）是高風險事件，可能翻轉區域控制，需要準備、協調和大量玩家才能獲勝。", "領土控制級聯影響伺服器經濟。控制區域的陣營獲得交易加成、資源開採權和公會福利，使其隨時間變得更強——創造自我強化的權力動態，使控制領土成為戰略必要而非可選活動。"]),
        section("siege-weapons", "攻城武器：攻城的工具", ["攻城武器是對建築、工事和其他攻城載具造成不成比例傷害的專用設備。每種武器類型有獨特優勢：攻城槌破門，攻城塔提供高攻平台，攻城引擎摧毀城牆段落。", "攻城武器通過製作或公會資源建造，使它們成為公會集體投資而非個人裝備。這意味著小編隊只能有限的攻城支援，而資金充足的公會可以帶來壓倒性的攻城火力。", "每件攻城武器需要專門的操作組。操作者管理武器瞄準和射擊，輔助組員負責彈藥、維修和定位。組內協調至關重要——協調良好的攻城武器效果遠超協調不佳的武器。"]),
        section("siege-tactics", "戰術方法：突破、防禦與消耗", ["進攻性攻城通常遵循三階段方法：接近、突破、堅守。接近階段涉及確保外圍和應對防禦突襲。突破階段集中在用攻城武器和精英突擊隊破門破牆。堅守階段涉及確保佔領點並擊退反攻。", "防禦性攻城是關於分層防禦和力量倍增。縱深防禦——多層防禦與重疊火力——意味著攻擊者必須突破每一層才能到達核心。機動預備隊填補缺口和反擊至關重要。資源管理（彈藥、治療、耐力）決定防禦能維持多久。", "對較小的部隊而言，非對稱戰術是關鍵。打了就跑的襲擊、針對攻城武器組的定向破壞、利用地形進行伏擊可以在不正面交鋒的情況下拒絕領土控制。游擊戰是在面對壓倒性數量优势時合法且有效的策略。"]),
        section("guild-coordination", "公會與陣營協調", ["攻城戰是公會優先的活動。成功需要專門的領導結構、清晰的溝通渠道和每個參與者的預先計劃角色。語音通信在實時攻城期間幾乎是必需的——依賴文字聊天進行戰術呼叫是劣勢。", "公會應提前數月計劃攻城 참여。這包括建造攻城武器庫存、訓練軍官掌握攻城戰術、囤積消耗品和招募專家（攻城武器操作者、野戰治療師、偵察員）。準備階段是大多數攻城戰役在城門倒下前就已經勝負的地方。", "聯盟公會之間的陣營級協調同樣重要。共享目標分配、同步攻擊時機和相互支持協定可防止友軍誤傷並確保盟友力量不被浪費。定期陣營會議審查策略並根據敵方位置變化調整是必需的。"]),
        section("endgame-rewards", "終局獎勵與長期影響", ["領土控制獎勵遠不止聲望。控制的領土通過資源開採和交易加成提供公會收入。關鍵領土可能授予獨占 Boss 遭遇或製作站点的訪問權。領土控制也是陣營級成就和賽季活動的前提條件。", "攻城戰的經濟影響是持久的——控制領土產生持續的 Kinah 收入，可再投資於公會設備、攻城武器和訓練。這創造滾雪球效應，使成功的公會越來越強，使挑戰者更難競爭。", "全球版預期相同的領土控制框架，但改良版 Season 1 進階曲線可能有調整。早期建立領土主導的公會將在終局內容中獲得顯著的經濟優勢。"]),
      ],
    }),
  },
};
