import { articleCopy, guideLabels, localizations, publishedVerified, section } from "./trending-september-10-shared";
import type { ContentEntry, ContentHeroImage, ContentSource } from "./content-registry";

/* ARTICLE 4 — Hall of Fame, Commendation system, World Marks, dye pattern size (Sept 9 update social/QoL features) */

const ncOfficialSource: ContentSource = {
  id: "nc-official-a2-update-2026-09-09",
  kind: "official",
  publisher: "NC Corporation",
  label: "NC's AION 2: New Sanctuary 'Snowfield of Sorrow' Update (Press Release)",
  url: "https://about.ncsoft.com/news/article/A2_update_20260909",
  publishedAt: "2026-09-09",
  retrievedAt: "2026-09-10",
  verifiedAt: "2026-09-10",
  localizations: localizations({
    "zh-hans": "NC 的 AION 2：新 Sanctuary「Snowfield of Sorrow」更新（新闻稿）",
    en: "NC's AION 2: New Sanctuary 'Snowfield of Sorrow' Update (Press Release)",
    fr: "AION 2 de NC : mise à jour du Sanctuary « Snowfield of Sorrow » (communiqué)",
    de: "NCs AION 2: Update „Snowfield of Sorrow“ (Pressemitteilung)",
    es: "AION 2 de NC: actualización del Santuario «Snowfield of Sorrow» (nota de prensa)",
    ja: "NCのAION 2：新サンクチュアリ「Snowfield of Sorrow」アップデート（プレスリリース）",
    "pt-br": "AION 2 da NC: atualização do Santuário 'Snowfield of Sorrow' (comunicado)",
    ru: "AION 2 от NC: обновление Святилища «Snowfield of Sorrow» (пресс-релиз)",
    ko: "엔씨 AION 2: 신규 성역 '비탄의 설원' 업데이트 (보도자료)",
    "zh-hant": "NC 的 AION 2：新 Sanctuary「Snowfield of Sorrow」更新（新聞稿）",
  }, "https://about.ncsoft.com/news/article/A2_update_20260909"),
};

const invenSource: ContentSource = {
  id: "inven-snowfield-sorrow-25730-2026-09-08",
  kind: "third-party",
  publisher: "Inven Global",
  label: "'Aion 2' Adds Highest-Difficulty Sanctuary 'Snowfield of Sorrow'",
  url: "https://www.invenglobal.com/articles/25730/aion-2-adds-highest-difficulty-sanctuary-snowfield-of-sorrow",
  publishedAt: "2026-09-08",
  retrievedAt: "2026-09-10",
  verifiedAt: "2026-09-10",
  localizations: localizations({
    "zh-hans": "『Aion 2』新增最高难度 Sanctuary『Snowfield of Sorrow』",
    en: "'Aion 2' Adds Highest-Difficulty Sanctuary 'Snowfield of Sorrow'",
    fr: "« Aion 2 » ajoute le Sanctuary « Snowfield of Sorrow » de plus haute difficulté",
    de: "„Aion 2“ fügt Sanctuary „Snowfield of Sorrow“ mit höchster Schwierigkeit hinzu",
    es: "«Aion 2» añade el Santuario «Snowfield of Sorrow» de máxima dificultad",
    ja: "『Aion 2』に最高難度サンクチュアリ「Snowfield of Sorrow」追加",
    "pt-br": "'Aion 2' adiciona o Santuário 'Snowfield of Sorrow' de maior dificuldade",
    ru: "«Aion 2» добавляет Святилище «Snowfield of Sorrow» высшей сложности",
    ko: "'아이온2' 최고 난도 성역 '비탄의 설원' 추가",
    "zh-hant": "『Aion 2』新增最高難度 Sanctuary『Snowfield of Sorrow』",
  }, "https://www.invenglobal.com/articles/25730/aion-2-adds-highest-difficulty-sanctuary-snowfield-of-sorrow"),
};

const hHero: ContentHeroImage = {
  src: "https://blogfiles.ncsoft.net/news/af7330da-4ff6-4b58-aece-400e6061a3be.jpg",
  width: 1200, height: 630,
  credit: "NC Corporation",
  sourceUrl: "https://aion2.plaync.com/en-us/",
  rights: "linked-official-media",
  translations: {
    "zh-hans": { alt: "Aion 2 名人堂与嘉奖系统指南横幅", caption: "9/9 更新新增副本社交功能：名人堂记录前 3 支通关队伍；通关后队友互评「嘉奖系统」（5 类评价）；世界标记可在地图各处使用；染色图样尺寸可调。" },
    en: { alt: "Aion 2 Hall of Fame and commendation guide banner", caption: "The September 9 update adds dungeon social features: a Hall of Fame enshrining the first three clears, a commendation system letting players rate party members in five categories after a clear, World Marks usable across areas, and adjustable dye pattern sizes." },
    fr: { alt: "Bannière du guide Hall of Fame et système de recommandation d'Aion 2", caption: "La mise à jour du 9 septembre ajoute des fonctions sociales : un Hall of Fame pour les trois premiers clears, un système de recommandation en cinq catégories, des marques mondiales utilisables partout et des tailles de motifs de teinture réglables." },
    de: { alt: "Banner zum Hall-of-Fame- und Empfehlungs-Leitfaden von Aion 2", caption: "Das Update vom 9. September fügt soziale Dungeon-Funktionen hinzu: eine Hall of Fame für die ersten drei Clears, ein Empfehlungssystem in fünf Kategorien, überall nutzbare Weltmarken und einstellbare Färbemuster-Größen." },
    es: { alt: "Banner de la guía del Salón de la Fama y el sistema de recomendación de Aion 2", caption: "La actualización del 9 de septiembre añade funciones sociales: un Salón de la Fama para los tres primeros clears, un sistema de recomendación en cinco categorías, marcas mundiales utilizables en todas las zonas y tamaños de patrón de tinte ajustables." },
    ja: { alt: "Aion 2 栄誉の殿堂・推奨システムガイドバナー", caption: "9/9アップデートでダンジョン社交機能が追加：上位3クリアを刻む栄誉の殿堂、クリア後に5カテゴリで評価する推奨システム、全エリアで使えるワールドマーク、染色パターンサイズ調整。" },
    "pt-br": { alt: "Banner do guia do Hall da Fama e sistema de recomendação do Aion 2", caption: "A atualização de 9 de setembro adiciona funções sociais: um Hall da Fama para os três primeiros clears, um sistema de recomendação em cinco categorias, marcas mundiais utilizáveis em todas as áreas e tamanhos de padrão de tingimento ajustáveis." },
    ru: { alt: "Баннер гайда по Залу славы и системе рекомендаций Aion 2", caption: "Обновление 9 сентября добавляет социальные функции: Зал славы для трёх первых клиров, система рекомендаций из пяти категорий, мировые метки во всех зонах и настраиваемый размер узора окраски." },
    ko: { alt: "Aion 2 명예의 전당·추천 시스템 가이드 배너", caption: "9/9 업데이트로 던전 소셜 기능이 추가됐습니다: 상위 3개 클리어를 기록하는 명예의 전당, 클리어 후 5개 카테고리로 평가하는 추천 시스템, 전 지역에서 쓸 수 있는 월드 징표, 염색 패턴 크기 조절." },
    "zh-hant": { alt: "Aion 2 名人堂與嘉獎系統指南橫幅", caption: "9/9 更新新增副本社交功能：名人堂記錄前 3 支通關隊伍；通關後隊友互評「嘉獎系統」（5 類評價）；世界標記可在地圖各處使用；染色圖樣尺寸可調。" },
  },
};

export const trendingSeptember10Article4: ContentEntry = {
  section: "guides",
  slug: "aion-2-hall-of-fame-commendation-guide",
  schemaType: "Article",
  publishedAt: "2026-09-10",
  updatedAt: "2026-09-10",
  readingMinutes: 5,
  publication: publishedVerified,
  sources: [ncOfficialSource, invenSource],
  heroImage: hHero,
  related: [
    { kind: "content", section: "news", slug: "aion-2-snowfield-of-sorrow-first-clear" },
    { kind: "content", section: "guides", slug: "aion-2-snowfield-of-sorrow-farming-guide" },
    { kind: "content", section: "guides", slug: "aion-2-trials-raids-guide" },
    { kind: "content", section: "guides", slug: "aion-2-global-qol-no-daily-gates-guide" },
  ],
  translations: {
    en: articleCopy(guideLabels, "en", 5, {
      eyebrow: "SOCIAL FEATURES",
      title: "Aion 2's New Dungeon Social Features: Hall of Fame, the Commendation System, and World Marks",
      description: "The September 9 update adds social and QoL features around raiding: a Hall of Fame enshrining the first three clears, a five-category commendation system after dungeon clears, World Marks, and dye pattern size control",
      intro: "Alongside the Snowfield of Sorrow raid, the September 9 update introduced a batch of social and quality-of-life features: the Hall of Fame for first clears, the commendation system that lets party members rate each other, World Marks usable across the map, and adjustable dye pattern sizes.",
      sourceNote: "Based on NCsoft's official September 9, 2026 press release and Inven Global's September 8, 2026 report (both retrieved September 10, 2026). Applies to the Korean service; the global version launches October 5 with a modified Season 1.",
      keywords: ["Aion 2 Hall of Fame raid", "Aion 2 commendation system", "Aion 2 World Mark", "Aion 2 dungeon social features", "Aion 2 dye pattern size"],
      sections: [
        section("hall-of-fame", "The Hall of Fame: First-Clear Records", ["The Hall of Fame permanently enshrines the 1st through 3rd forces that clear the new Snowfield of Sorrow Sanctuary, showing the clear date and the full attack-force roster.", "For the Korean service, the first entry is already claimed — a 10-player group cleared Hard about 4 hours 16 minutes after the raid opened on September 9. The feature gives the raiding community a durable, server-wide reference point for the meta."]),
        section("commendation", "The Commendation System: Five Categories", ["After clearing a dungeon, players can commend party members by choosing one of five categories: Outstanding Skill, Reliable Guardian, Devoted Support, Excellent Leadership, or Kind Mentor.", "It activates automatically upon dungeon completion, so no extra menu diving is needed — a lightweight way to recognize good runs and, over time, a reputation signal inside the community."]),
        section("world-marks", "World Marks: Map Notes Everywhere", ["The update adds 'World Marks' — player-placed map notes usable in Fields, Expeditions, Transcendence, Sanctuaries, and the Abyss.", "Practical uses: marking rare mob spawns in the Abyss, pinning boss positions before raid pulls, or flagging gathering routes for your Legion. Because they work across PvE and PvP zones, they double as coordination tools for larger group play."]),
        section("dye-pattern-size", "Dye Pattern Size Control", ["A smaller but welcome change: dye pattern sizes can now be adjusted, giving more control over how clothing patterns scale on your character.", "It joins the skill preset overhaul in the same update — preset builds can now keep different skill levels per preset, so swapping between a raid loadout and an open-world loadout no longer resets your skill levels."]),
        section("why-it-matters", "Why These Features Matter", ["The bundle reads as NCsoft's playbook for healthy group content: recognition (Hall of Fame), positive reinforcement (commendations), coordination (World Marks), and expression (dye sizing).", "For global players, they preview the social layer that ships with the modified Season 1 on October 5 — worth knowing before you form your first Legion runs."]),
      ],
    }),
    "zh-hans": articleCopy(guideLabels, "zh-hans", 5, {
      eyebrow: "社交功能",
      title: "Aion 2 新副本社交功能：名人堂、嘉奖系统与世界标记",
      description: "9 月 9 日更新围绕副本新增社交与 QoL 功能：名人堂记录前三次通关、通关后的五类嘉奖系统、世界标记与染色图样尺寸调节",
      intro: "随 Snowfield of Sorrow 副本一同，9 月 9 日更新引入了一批社交与 QoL 功能：首杀名人堂、让队友互评的嘉奖系统、可在地图各处使用的世界标记，以及可调的染色图样尺寸。",
      sourceNote: "基于 NCsoft 官方 2026 年 9 月 9 日新闻稿与 Inven Global 2026 年 9 月 8 日报道（均于 2026-09-10 抓取）。适用于韩服；全球版 10 月 5 日以改良版 Season 1 上线。",
      keywords: ["Aion 2 名人堂 副本", "Aion 2 嘉奖系统", "Aion 2 世界标记", "Aion 2 副本社交功能", "Aion 2 染色图样尺寸"],
      sections: [
        section("hall-of-fame", "名人堂：首杀记录", ["名人堂永久记录通关新 Sanctuary「Snowfield of Sorrow」的第 1-3 支队伍，显示通关日期与完整攻击队名单。", "韩服首个席位已被认领——一支 10 人队在 9 月 9 日副本开放约 4 小时 16 分后完成 Hard 首杀。该功能为竞速社区提供了持久、全服可见的 meta 参照点。"]),
        section("commendation", "嘉奖系统：五类评价", ["通关副本后，玩家可从五类中选择嘉奖队友：出色实力、可靠守护者、奉献支援、出色领导力、亲切导师。", "系统在副本完成时自动激活，无需额外菜单——一种轻量的认可方式，长期看也是社区内的声誉信号。"]),
        section("world-marks", "世界标记：无处不在的地图笔记", ["更新新增「世界标记」——玩家放置的地图笔记，可在野外、远征、超越、Sanctuary 与深渊使用。", "实用场景：标记深渊稀有怪刷新点、团队开怪前标记 Boss 位置、为军团标注采集路线。由于 PvE 与 PvP 区域通用，也可作为大团队协调工具。"]),
        section("dye-pattern-size", "染色图样尺寸调节", ["一个较小但受欢迎的变化：染色图样尺寸现在可调，让你对角色的衣物图样缩放有更多控制。", "它与同次更新的技能预设重构一同到来——预设现在可保留不同的技能等级，切换副本配置与开放世界配置不再重置技能等级。"]),
        section("why-it-matters", "这些功能的意义", ["这一组合体现了 NCsoft 对健康组队内容的手册：认可（名人堂）、正向强化（嘉奖）、协调（世界标记）与表达（染色尺寸）。", "对全球玩家：它们预览了 10 月 5 日改良版 Season 1 随附的社交层——在组建第一批军团活动前值得了解。"]),
      ],
    }),
    fr: articleCopy(guideLabels, "fr", 5, {
      eyebrow: "FONCTIONS SOCIALES",
      title: "Les nouvelles fonctions sociales de donjon d'Aion 2 : Hall of Fame, recommandations et marques mondiales",
      description: "La mise à jour du 9 septembre ajoute des fonctions sociales et QoL autour du raid : un Hall of Fame pour les trois premiers clears, des recommandations en cinq catégories, des marques mondiales et le contrôle de la taille des motifs",
      intro: "Avec le raid Snowfield of Sorrow, la mise à jour du 9 septembre ajoute des fonctions sociales et QoL : le Hall of Fame, le système de recommandation entre membres, les marques mondiales et les tailles de motifs de teinture.",
      sourceNote: "Basé sur le communiqué officiel de NCsoft du 9 septembre 2026 et le rapport d'Inven Global du 8 septembre 2026 (récupérés le 10 septembre 2026).",
      keywords: ["Aion 2 Hall of Fame raid", "Aion 2 système de recommandation", "Aion 2 marque mondiale", "Aion 2 fonctions sociales donjon", "Aion 2 taille motif teinture"],
      sections: [
        section("hall-of-fame", "Le Hall of Fame : records de premier clear", "Le Hall of Fame grave les forces 1 à 3 qui clairent le Sanctuary Snowfield of Sorrow (date + liste complète). La première entrée coréenne est prise : un groupe de 10 a clearé Hard ~4 h 16 après l'ouverture le 9 septembre."),
        section("commendation", "Recommandations : cinq catégories", "Après un clear, on recommande ses coéquipiers dans 5 catégories : compétence remarquable, gardien fiable, soutien dévoué, leadership excellent, mentor aimable. Activation automatique en fin de donjon."),
        section("world-marks", "Marques mondiales", "Notes de carte placées par les joueurs, utilisables en Champ, Expédition, Transcendance, Sanctuary et Abysse — spawns rares, positions de boss, routes de collecte, coordination de groupe."),
        section("dye-pattern-size", "Taille des motifs de teinture", "Tailles de motifs réglables ; les presets de compétences conservent des niveaux par preset (l'échange raid / monde ouvert ne réinitialise plus les niveaux)."),
        section("why-it-matters", "Pourquoi c'est important", "Le lot reflète le playbook de NC : reconnaissance (Hall of Fame), renforcement positif (recommandations), coordination (marques) et expression (teinture). Pour le global : aperçu de la couche sociale de la Saison 1 modifiée du 5 octobre."),
      ],
    }),
    de: articleCopy(guideLabels, "de", 5, {
      eyebrow: "SOZIALE FUNKTIONEN",
      title: "Die neuen sozialen Dungeon-Funktionen von Aion 2: Hall of Fame, Empfehlungen und Weltmarken",
      description: "Das Update vom 9. September fügt soziale und QoL-Funktionen rund ums Raiden hinzu: eine Hall of Fame für die ersten drei Clears, ein Empfehlungssystem in fünf Kategorien, Weltmarken und Färbemuster-Größen",
      intro: "Zusammen mit dem Raid Snowfield of Sorrow fügt das Update vom 9. September soziale und QoL-Funktionen hinzu: die Hall of Fame, das Empfehlungssystem, überall nutzbare Weltmarken und einstellbare Färbemuster-Größen.",
      sourceNote: "Basierend auf der offiziellen NCsoft-Pressemitteilung vom 9. September 2026 und dem Inven-Global-Bericht vom 8. September 2026 (abgerufen am 10. September 2026).",
      keywords: ["Aion 2 Hall of Fame Raid", "Aion 2 Empfehlungssystem", "Aion 2 Weltmarke", "Aion 2 soziale Dungeon-Funktionen", "Aion 2 Färbemuster-Größe"],
      sections: [
        section("hall-of-fame", "Die Hall of Fame", "Die Hall of Fame verewigt die Forces 1-3, die das Sanctuary Snowfield of Sorrow clearen (Datum + volle Liste). Der erste koreanische Eintrag ist vergeben: Eine 10-Spieler-Gruppe clearte Hard ~4 h 16 min nach Öffnung am 9. September."),
        section("commendation", "Das Empfehlungssystem", "Nach einem Clear empfehlen Spieler Mitspieler in 5 Kategorien: herausragendes Können, zuverlässiger Beschützer, hingebungsvolle Unterstützung, exzellente Führung, freundlicher Mentor. Automatisch nach Dungeon-Ende aktiv."),
        section("world-marks", "Weltmarken", "Spielerplatzierte Kartennotizen in Feld, Expedition, Transzendenz, Sanctuary und Abyss — seltene Spawns, Boss-Positionen, Sammelrouten, Gruppenkoordination."),
        section("dye-pattern-size", "Färbemuster-Größen", "Muster-Größen einstellbar; Skill-Presets behalten unterschiedliche Skill-Level (Raid-/Open-World-Wechsel setzt Level nicht mehr zurück)."),
        section("why-it-matters", "Warum das wichtig ist", "Das Paket spiegelt NCs Playbook: Anerkennung (Hall of Fame), positive Verstärkung (Empfehlungen), Koordination (Marken) und Ausdruck (Färbung). Für Global: Vorschau auf die soziale Schicht der modifizierten Season 1 (5. Oktober)."),
      ],
    }),
    es: articleCopy(guideLabels, "es", 5, {
      eyebrow: "FUNCIONES SOCIALES",
      title: "Las nuevas funciones sociales de mazmorra de Aion 2: Salón de la Fama, recomendaciones y marcas mundiales",
      description: "La actualización del 9 de septiembre añade funciones sociales y QoL alrededor del raideo: un Salón de la Fama para los tres primeros clears, recomendaciones en cinco categorías, marcas mundiales y control del tamaño de los patrones de tinte",
      intro: "Junto al raid Snowfield of Sorrow, la actualización del 9 de septiembre añade funciones sociales y QoL: el Salón de la Fama, el sistema de recomendaciones entre miembros, marcas mundiales y tamaños de patrón de tinte ajustables.",
      sourceNote: "Basado en la nota de prensa oficial de NCsoft del 9 de septiembre de 2026 y el informe de Inven Global del 8 de septiembre de 2026 (recuperados el 10 de septiembre de 2026).",
      keywords: ["Aion 2 Salón de la Fama raid", "Aion 2 sistema de recomendación", "Aion 2 marca mundial", "Aion 2 funciones sociales mazmorra", "Aion 2 tamaño patrón tinte"],
      sections: [
        section("hall-of-fame", "El Salón de la Fama", "El Salón de la Fama graba las fuerzas 1-3 que superan el Santuario Snowfield of Sorrow (fecha + lista completa). La primera entrada coreana está tomada: un grupo de 10 superó Hard ~4 h 16 min tras la apertura el 9 de septiembre."),
        section("commendation", "Recomendaciones: cinco categorías", "Tras un clear, se recomienda a los compañeros en 5 categorías: habilidad sobresaliente, guardián fiable, apoyo dedicado, liderazgo excelente, mentor amable. Activación automática al terminar la mazmorra."),
        section("world-marks", "Marcas mundiales", "Notas de mapa colocadas por jugadores, utilizables en Campo, Expedición, Trascendencia, Santuario y Abismo — spawns raros, posiciones de jefes, rutas de recolección, coordinación de grupo."),
        section("dye-pattern-size", "Tamaño de los patrones de tinte", "Tamaños de patrón ajustables; los presets de habilidades conservan niveles por preset (el cambio raid / mundo abierto ya no reinicia niveles)."),
        section("why-it-matters", "Por qué importa", "El conjunto refleja el manual de NC: reconocimiento (Salón de la Fama), refuerzo positivo (recomendaciones), coordinación (marcas) y expresión (tinte). Para el global: vista previa de la capa social de la Temporada 1 modificada (5 de octubre)."),
      ],
    }),
    ja: articleCopy(guideLabels, "ja", 5, {
      eyebrow: "ソーシャル機能",
      title: "Aion 2 の新ダンジョンソーシャル機能：栄誉の殿堂・推奨システム・ワールドマーク",
      description: "9月9日アップデートでレイド周りのソーシャル・QoL機能が追加：上位3クリアを刻む栄誉の殿堂、5カテゴリの推奨システム、ワールドマーク、染色パターンサイズ調整",
      intro: "レイド「Snowfield of Sorrow」と同時に、9月9日アップデートはソーシャル・QoL機能を導入しました：初クリアの栄誉の殿堂、パーティメンバーを相互評価する推奨システム、全マップで使えるワールドマーク、調整可能な染色パターンサイズ。",
      sourceNote: "NC公式2026年9月9日付プレスリリースとInven Global 2026年9月8日付報道（いずれも2026-09-10取得）に基づきます。",
      keywords: ["Aion 2 栄誉の殿堂 レイド", "Aion 2 推奨システム", "Aion 2 ワールドマーク", "Aion 2 ダンジョン ソーシャル機能", "Aion 2 染色パターンサイズ"],
      sections: [
        section("hall-of-fame", "栄誉の殿堂：初クリア記録", "栄誉の殿堂は新サンクチュアリ「Snowfield of Sorrow」をクリアした1〜3位の部隊をクリア日時と完全な名簿とともに永久記録します。韓国サーバーの最初の座はすでに確定：10人編成が9月9日のオープンから約4時間16分でHardを初クリアしました。"),
        section("commendation", "推奨システム：5カテゴリ", "ダンジョンクリア後、パーティメンバーを5カテゴリで評価します：優れた実力、頼れる守護者、献身的な支援、素晴らしいリーダーシップ、親切なメンター。クリア時に自動で有効化される軽量な称賛機能で、長期的にはコミュニティ内の評判シグナルになります。"),
        section("world-marks", "ワールドマーク", "プレイヤーが設置できるマップメモで、フィールド・遠征・超越・サンクチュアリ・アビスで使用可能——レアモブのスポーン位置、開戦前のボス位置、採集ルート、大規模集団の連携ツールとして使えます。"),
        section("dye-pattern-size", "染色パターンサイズ調整", "パターンサイズが調整可能に。同じアップデートのスキルプリセット改修では、プリセットごとにスキルレベルを維持できるため、レイド用とオープンワールド用の切替でレベルがリセットされません。"),
        section("why-it-matters", "なぜ重要か", "この組み合わせはNCの健全なグループコンテンツ運営の手法です：承認（栄誉の殿堂）、正の強化（推奨）、連携（マーク）、表現（染色）。グローバル向け：10月5日の改良版シーズン1に付属するソーシャル層のプレビューです。"),
      ],
    }),
    "pt-br": articleCopy(guideLabels, "pt-br", 5, {
      eyebrow: "FUNÇÕES SOCIAIS",
      title: "As novas funções sociais de masmorra do Aion 2: Hall da Fama, recomendações e marcas mundiais",
      description: "A atualização de 9 de setembro adiciona funções sociais e de QoL ao redor de raides: um Hall da Fama para os três primeiros clears, recomendações em cinco categorias, marcas mundiais e controle do tamanho dos padrões de tingimento",
      intro: "Junto ao raid Snowfield of Sorrow, a atualização de 9 de setembro adiciona funções sociais e de QoL: o Hall da Fama, o sistema de recomendações entre membros, marcas mundiais e tamanhos de padrão de tingimento ajustáveis.",
      sourceNote: "Baseado no comunicado oficial da NCsoft de 9 de setembro de 2026 e no relatório da Inven Global de 8 de setembro de 2026 (recuperados em 10 de setembro de 2026).",
      keywords: ["Aion 2 Hall da Fama raid", "Aion 2 sistema de recomendação", "Aion 2 marca mundial", "Aion 2 funções sociais masmorra", "Aion 2 tamanho padrão tingimento"],
      sections: [
        section("hall-of-fame", "O Hall da Fama", "O Hall da Fama grava as forças 1-3 que zeram o Santuário Snowfield of Sorrow (data + lista completa). A primeira entrada coreana está ocupada: um grupo de 10 zerou o Hard ~4h16 após a abertura em 9 de setembro."),
        section("commendation", "Recomendações: cinco categorias", "Após um clear, recomenda-se os companheiros em 5 categorias: habilidade notável, guardião confiável, suporte dedicado, liderança excelente, mentor gentil. Ativação automática no fim da masmorra."),
        section("world-marks", "Marcas mundiais", "Notas de mapa colocadas por jogadores, utilizáveis em Campo, Expedição, Transcendência, Santuário e Abismo — spawns raros, posições de chefes, rotas de coleta, coordenação de grupo."),
        section("dye-pattern-size", "Tamanho dos padrões de tingimento", "Tamanhos de padrão ajustáveis; os presets de habilidades mantêm níveis por preset (a troca raid / mundo aberto não reinicia mais níveis)."),
        section("why-it-matters", "Por que isso importa", "O conjunto reflete o manual da NC: reconhecimento (Hall da Fama), reforço positivo (recomendações), coordenação (marcas) e expressão (tingimento). Para o global: prévia da camada social da Temporada 1 modificada (5 de outubro)."),
      ],
    }),
    ru: articleCopy(guideLabels, "ru", 5, {
      eyebrow: "СОЦИАЛЬНЫЕ ФУНКЦИИ",
      title: "Новые социальные функции подземелий Aion 2: Зал славы, рекомендации и мировые метки",
      description: "Обновление 9 сентября добавляет социальные и QoL-функции вокруг рейдов: Зал славы для трёх первых клиров, рекомендации в пяти категориях, мировые метки и регулировку размера узора окраски",
      intro: "Вместе с рейдом Snowfield of Sorrow обновление 9 сентября добавляет социальные и QoL-функции: Зал славы, систему рекомендаций между участниками, мировые метки и регулируемые размеры узоров окраски.",
      sourceNote: "На основе официального пресс-релиза NCsoft от 9 сентября 2026 г. и отчёта Inven Global от 8 сентября 2026 г. (получены 10 сентября 2026 г.).",
      keywords: ["Aion 2 Зал славы рейд", "Aion 2 система рекомендаций", "Aion 2 мировая метка", "Aion 2 социальные функции подземелья", "Aion 2 размер узора окраски"],
      sections: [
        section("hall-of-fame", "Зал славы", "Зал славы увековечивает силы 1–3, прошедшие Святилище Snowfield of Sorrow (дата + полный состав). Первая корейская запись занята: группа из 10 прошла Hard через ~4 ч 16 мин после открытия 9 сентября."),
        section("commendation", "Рекомендации: пять категорий", "После клира игроки рекомендуют соратников в 5 категориях: выдающееся мастерство, надёжный защитник, преданная поддержка, отличное лидерство, добрый наставник. Активация автоматически по завершении подземелья."),
        section("world-marks", "Мировые метки", "Заметки на карте от игроков, работают в Поле, Экспедиции, Трансценденции, Святилище и Бездне — редкие спавны, позиции боссов, маршруты сбора, координация группы."),
        section("dye-pattern-size", "Размер узора окраски", "Размеры узоров регулируются; пресеты навыков сохраняют уровни (смена рейд / открытый мир больше не сбрасывает уровни)."),
        section("why-it-matters", "Почему это важно", "Набор отражает подход NC: признание (Зал славы), позитивное подкрепление (рекомендации), координация (метки) и самовыражение (окраска). Для глобала: превью социального слоя модифицированного Сезона 1 (5 октября)."),
      ],
    }),
    ko: articleCopy(guideLabels, "ko", 5, {
      eyebrow: "소셜 기능",
      title: "아이온2 신규 던전 소셜 기능: 명예의 전당·추천 시스템·월드 징표",
      description: "9월 9일 업데이트로 레이드 주변 소셜·QoL 기능이 추가됐습니다: 상위 3개 클리어를 기록하는 명예의 전당, 클리어 후 5개 카테고리 추천 시스템, 월드 징표, 염색 패턴 크기 조절",
      intro: "레이드 '비탄의 설원'과 함께, 9월 9일 업데이트는 소셜·QoL 기능을 한꺼번에 도입했습니다: 첫 클리어 명예의 전당, 파티원을 서로 평가하는 추천 시스템, 지도 곳곳에서 쓸 수 있는 월드 징표, 조절 가능한 염색 패턴 크기.",
      sourceNote: "NC 공식 2026년 9월 9일자 보도자료와 Inven Global 2026년 9월 8일자 보도(모두 2026-09-10 확인)를 기반으로 했습니다.",
      keywords: ["아이온2 명예의 전당 레이드", "아이온2 추천 시스템", "아이온2 월드 징표", "아이온2 던전 소셜 기능", "아이온2 염색 패턴 크기"],
      sections: [
        section("hall-of-fame", "명예의 전당: 첫 클리어 기록", "명예의 전당은 신규 성역 '비탄의 설원'을 클리어한 1~3위 포스를 격파 일시와 공격대 전체 명단과 함께 영구 기록합니다.", "한국 서버의 첫 자리는 이미 채워졌습니다: 10인 공격대가 9월 9일 오픈 약 4시간 16분 만에 Hard를 최초 격파했습니다. 레이딩 커뮤니티에 지속적이고 서버 전체가 볼 수 있는 메타의 기준점을 제공합니다."),
        section("commendation", "추천 시스템: 5개 카테고리", "던전 클리어 후 파티원을 다섯 가지 카테고리 중 하나로 추천할 수 있습니다: 뛰어난 실력, 든든한 수호자, 헌신적인 지원, 훌륭한 리더십, 친절한 멘토.", "던전 완료 시 자동으로 활성화되어 추가 메뉴 탐색이 필요 없습니다——좋은 플레이를 인정하는 가벼운 방식이자, 장기적으로는 커뮤니티 내 평판 신호가 됩니다."),
        section("world-marks", "월드 징표: 전 지역 지도 메모", "업데이트로 '월드 징표'가 추가됐습니다——플레이어가 설치하는 지도 메모로, 필드·원정·초월·성역·어비스에서 사용할 수 있습니다.", "실용 용례: 아비스 희귀 몬스터 리젠 위치 표시, 오픈 전 보스 위치 핀, 혈맹용 채집 루트 표시. PvE·PvP 지역 모두에서 쓸 수 있어 대규모 집단 플레이의 조율 도구로도 활용됩니다."),
        section("dye-pattern-size", "염색 패턴 크기 조절", "작지만 반가운 변화: 염색 패턴 크기를 조절할 수 있어 캐릭터 옷 문양의 스케일을 더 세밀하게 다룰 수 있습니다.", "같은 업데이트의 스킬 프리셋 개편과 함께 옵니다——프리셋마다 스킬 레벨을 다르게 유지할 수 있어, 레이드 세팅과 오픈월드 세팅을 오가도 스킬 레벨이 초기화되지 않습니다."),
        section("why-it-matters", "이 기능들이 중요한 이유", "이 묶음은 NC의 건강한 그룹 콘텐츠 운영법을 보여줍니다: 인정(명예의 전당), 긍정 강화(추천), 조율(징표), 표현(염색).", "글로벌 플레이어에게: 10월 5일 수정판 시즌 1과 함께 제공될 소셜 레이어의 프리뷰입니다——첫 혈맹 활동을 꾸리기 전에 알아두면 좋습니다."),
      ],
    }),
    "zh-hant": articleCopy(guideLabels, "zh-hant", 5, {
      eyebrow: "社交功能",
      title: "Aion 2 新副本社交功能：名人堂、嘉獎系統與世界標記",
      description: "9 月 9 日更新圍繞副本新增社交與 QoL 功能：名人堂記錄前三次通關、通關後的五類嘉獎系統、世界標記與染色圖樣尺寸調節",
      intro: "隨 Snowfield of Sorrow 副本一同，9 月 9 日更新引入了一批社交與 QoL 功能：首殺名人堂、讓隊友互評的嘉獎系統、可在地圖各處使用的世界標記，以及可調的染色圖樣尺寸。",
      sourceNote: "基於 NCsoft 官方 2026 年 9 月 9 日新聞稿與 Inven Global 2026 年 9 月 8 日報導（均於 2026-09-10 抓取）。適用於韓服；全球版 10 月 5 日以改良版 Season 1 上線。",
      keywords: ["Aion 2 名人堂 副本", "Aion 2 嘉獎系統", "Aion 2 世界標記", "Aion 2 副本社交功能", "Aion 2 染色圖樣尺寸"],
      sections: [
        section("hall-of-fame", "名人堂：首殺記錄", ["名人堂永久記錄通關新 Sanctuary「Snowfield of Sorrow」的第 1-3 支隊伍，顯示通關日期與完整攻擊隊名單。", "韓服首個席位已被認領——一支 10 人隊在 9 月 9 日副本開放約 4 小時 16 分後完成 Hard 首殺。該功能為競速社區提供了持久、全服可見的 meta 參照點。"]),
        section("commendation", "嘉獎系統：五類評價", ["通關副本後，玩家可從五類中選擇嘉獎隊友：出色實力、可靠守護者、奉獻支援、出色領導力、親切導師。", "系統在副本完成時自動啟動，無需額外選單——一種輕量的認可方式，長期看也是社區內的聲譽訊號。"]),
        section("world-marks", "世界標記：無處不在的地圖筆記", ["更新新增「世界標記」——玩家放置的地圖筆記，可在野外、遠征、超越、Sanctuary 與深淵使用。", "實用場景：標記深淵稀有怪重生點、團隊開怪前標記 Boss 位置、為軍團標註採集路線。由於 PvE 與 PvP 區域通用，也可作為大團隊協調工具。"]),
        section("dye-pattern-size", "染色圖樣尺寸調節", ["一個較小但受歡迎的變化：染色圖樣尺寸現在可調，讓你對角色的衣物圖樣縮放有更多控制。", "它與同次更新的技能預設重構一同到來——預設現在可保留不同的技能等級，切換副本配置與開放世界配置不再重置技能等級。"]),
        section("why-it-matters", "這些功能的意義", ["這一組合體現了 NCsoft 對健康組隊內容的手冊：認可（名人堂）、正向強化（嘉獎）、協調（世界標記）與表達（染色尺寸）。", "對全球玩家：它們預覽了 10 月 5 日改良版 Season 1 隨附的社交層——在組建第一批軍團活動前值得了解。"]),
      ],
    }),
  },
};
