import { articleCopy, localizations, newsLabels, publishedVerified, section } from "./trending-august-18-shared";
import type { ContentEntry, ContentHeroImage, ContentSource } from "./content-registry";

/* ARTICLE 1 — Gamescom 2026 watch guide */

const watchGuideSource1: ContentSource = {
  id: "aion2hub-gamescom-onl-2026-08-18",
  kind: "third-party", publisher: "AION2Hub",
  label: "AION 2 Heads to Gamescom 2026 Opening Night Live",
  url: "https://aion2hub.com/news/aion-2-heads-to-gamescom-2026-opening-night-live",
  publishedAt: "2026-08-10",
  retrievedAt: "2026-08-18",
  verifiedAt: "2026-08-18",
  localizations: localizations({
    "zh-hans": "AION 2 将亮相 2026 科隆游戏展开幕之夜现场",
    en: "AION 2 Heads to Gamescom 2026 Opening Night Live",
    fr: "AION 2 se rend à l'Opening Night Live de la Gamescom 2026",
    de: "AION 2 geht zur Opening Night Live der Gamescom 2026",
    es: "AION 2 llega al Opening Night Live de la Gamescom 2026",
    ja: "AION 2、Gamescom 2026 オープニングナイトライブへ",
    "pt-br": "AION 2 vai ao Opening Night Live da Gamescom 2026",
    ru: "AION 2 отправляется на Opening Night Live Gamescom 2026",
    ko: "AION 2, Gamescom 2026 오프닝 나이트 라이브 참가",
    "zh-hant": "AION 2 將亮相 2026 科隆遊戲展開幕之夜現場",
  }, "https://aion2hub.com/news/aion-2-heads-to-gamescom-2026-opening-night-live"),
};

const watchGuideSource2: ContentSource = {
  id: "mmobomb-gamescom-tease-2026-08-18",
  kind: "third-party", publisher: "MMOBomb",
  label: "NC Teases New Game Announcement For Gamescom",
  url: "https://www.mmobomb.com/news/nc-teases-new-game-announcement-gamescom",
  publishedAt: "2026-08-14",
  retrievedAt: "2026-08-18",
  verifiedAt: "2026-08-18",
  localizations: localizations({
    "zh-hans": "NC 在科隆展前预告新作发布",
    en: "NC Teases New Game Announcement For Gamescom",
    fr: "NC taquine une nouvelle annonce de jeu pour la Gamescom",
    de: "NC teasert neue Spielankündigung für die Gamescom",
    es: "NC adelanta un nuevo anuncio de juego para la Gamescom",
    ja: "NC、Gamescom で新作発表を予告",
    "pt-br": "NC provoca novo anúncio de jogo para a Gamescom",
    ru: "NC дразнит анонсом новой игры на Gamescom",
    ko: "NC, Gamescom에서 신작 발표 예고",
    "zh-hant": "NC 在科隆展前預告新作發布",
  }, "https://www.mmobomb.com/news/nc-teases-new-game-announcement-gamescom"),
};

const watchGuideSource3: ContentSource = {
  id: "nvidia-gamescom-event-2026-08-18",
  kind: "third-party", publisher: "Gamescom",
  label: "Gamescom 2026 — Official Event Page",
  url: "https://www.gamescom.global/",
  publishedAt: "2026-07-01",
  retrievedAt: "2026-08-18",
  verifiedAt: "2026-08-18",
  localizations: localizations({
    "zh-hans": "2026 科隆游戏展——官方活动页",
    en: "Gamescom 2026 — Official Event Page",
    fr: "Gamescom 2026 — Page officielle de l'événement",
    de: "Gamescom 2026 — Offizielle Veranstaltungsseite",
    es: "Gamescom 2026 — Página oficial del evento",
    ja: "Gamescom 2026 — 公式イベントページ",
    "pt-br": "Gamescom 2026 — Página oficial do evento",
    ru: "Gamescom 2026 — официальная страница события",
    ko: "Gamescom 2026 — 공식 행사 페이지",
    "zh-hant": "2026 科隆遊戲展——官方活動頁",
  }, "https://www.gamescom.global/"),
};

const watchGuideHero: ContentHeroImage = {
  src: "https://blogfiles.ncsoft.net/news/af7330da-4ff6-4b58-aece-400e6061a3be.jpg",
  width: 1100, height: 605,
  credit: "NC Corporation",
  sourceUrl: "https://aion2.plaync.com/ko-kr/board/notice",
  rights: "linked-official-media",
  translations: {
    "zh-hans": { alt: "Gamescom 2026 观赛指南配图", caption: "NC 官方配图；Aion 2 将亮相 8 月 25 日开幕之夜现场与 8 月 26 日开幕的科隆游戏展。" },
    en: { alt: "Gamescom 2026 watch guide image", caption: "Official NC artwork; Aion 2 will appear at Opening Night Live on August 25 and at Gamescom 2026 opening August 26." },
    fr: { alt: "Image du guide de visionnage Gamescom 2026", caption: "Visuel officiel NC ; Aion 2 sera présent à l'Opening Night Live du 25 août et à la Gamescom 2026 du 26 août." },
    de: { alt: "Gamescom-2026-Watch-Guide-Bild", caption: "Offizielles NC-Artwork; Aion 2 wird am 25. August bei der Opening Night Live und ab 26. August auf der Gamescom 2026 erscheinen." },
    es: { alt: "Imagen de la guía de visionado de Gamescom 2026", caption: "Arte oficial de NC; Aion 2 estará en el Opening Night Live del 25 de agosto y en la Gamescom 2026 que abre el 26 de agosto." },
    ja: { alt: "Gamescom 2026 視聴ガイド画像", caption: "NC公式アートワーク；Aion 2 は8月25日のオープニングナイトライブと8月26日開幕の Gamescom 2026 に登場します。" },
    "pt-br": { alt: "Imagem do guia de assistir da Gamescom 2026", caption: "Arte oficial da NC; Aion 2 aparecerá no Opening Night Live de 25 de agosto e na Gamescom 2026 que abre em 26 de agosto." },
    ru: { alt: "Изображение гайда по просмотру Gamescom 2026", caption: "Официальный арт NC; Aion 2 появится на Opening Night Live 25 августа и на Gamescom 2026, открывающейся 26 августа." },
    ko: { alt: "Gamescom 2026 시청 가이드 이미지", caption: "NC 공식 이미지입니다. Aion 2는 8월 25일 오프닝 나이트 라이브와 8월 26일 개막하는 Gamescom 2026에 등장합니다." },
    "zh-hant": { alt: "Gamescom 2026 觀賽指南配圖", caption: "NC 官方配圖；Aion 2 將亮相 8 月 25 日開幕之夜現場與 8 月 26 日開幕的科隆遊戲展。" },
  },
};

export const trendingAugust18Article1: ContentEntry = {
  section: "news",
  slug: "gamescom-2026-aion-2-watch-guide",
  schemaType: "NewsArticle",
  publishedAt: "2026-08-18",
  updatedAt: "2026-08-18",
  readingMinutes: 5,
  publication: publishedVerified,
  sources: [watchGuideSource1, watchGuideSource2, watchGuideSource3],
  heroImage: watchGuideHero,
  related: [
    { kind: "content", section: "news", slug: "gamescom-2026-ncsoft-lineup-project-bonfire" },
    { kind: "content", section: "news", slug: "aion-2-first-global-dev-stream-recap" },
    { kind: "content", section: "guides", slug: "aion-2-global-server-regions-guide" },
  ],
  translations: {
    en: articleCopy(newsLabels, "en", 5, {
      eyebrow: "GAMESCOM 2026",
      title: "Gamescom 2026 Aion 2 Watch Guide: When to Tune In & What to Expect",
      description: "Aion 2 heads to Gamescom 2026 Opening Night Live on August 25, with the show floor opening August 26. Here's the full schedule, where to watch, and what NCSoft may reveal.",
      intro: "With Western early access arriving September 30, Gamescom 2026 is the final big stage before Aion 2's global launch — and NCSoft has confirmed it will be there. This guide compiles the event schedule, viewing channels, and a realistic expectation list so you do not miss a single announcement.",
      sourceNote: "Based on AION2Hub's Gamescom Opening Night Live report (August 10), MMOBomb's NCSoft Gamescom tease (August 14), and the official Gamescom event page. Dates reflect the latest confirmed schedule.",
      keywords: ["Gamescom 2026 schedule", "Aion 2 Gamescom", "Gamescom Opening Night Live Aion 2", "Aion 2 news August 2026", "where to watch Gamescom"],
      sections: [
        section("schedule", "Gamescom 2026 Schedule for Aion 2 Fans", ["Opening Night Live airs on August 25, 2026 — NCSoft has confirmed Aion 2 will be part of the show, alongside the Project Bonfire world premiere and more on Cinder City. ONL is where the biggest reveals land, so it is the must-watch slot.", "The Gamescom show floor opens August 26 and runs for several days after. NCSoft's booth presence is confirmed for the event as a whole, though specific Aion 2 on-floor activities (demos, meet-and-greets) have not been detailed."]),
        section("watch", "Where & How to Watch", ["Opening Night Live streams for free on Gamescom's official channels — typically YouTube, Twitch, and the gamescom website. No ticket is needed for the digital broadcast.", "For following Aion 2 specifically, watch NCSoft's official channels and the gamescom broadcast; most MMO news outlets will also live-blog the Aion 2 segments if you prefer text summaries."]),
        section("expect", "What to Expect for Aion 2", ["With early access confirmed for September 30, the most likely announcements are a concrete global launch timeline for the free-to-play full release, new trailers, or extra detail on launch-window systems.", "NCSoft has already detailed customization, eight classes, five server regions, PvP, and Founder's Packs in its August dev stream — so Gamescom is the natural moment for the next step: release date specifics for the full launch and any post-launch roadmap."]),
        section("prep", "How to Prepare Before the Show", ["Lock in your server region and Founder's Pack decision before Gamescom if you have not already — any launch-window announcements in Cologne will make the September 30 early access start that much smoother.", "Bookmark our hub and check back after each event: we will summarize every Aion 2 reveal from Gamescom week the moment it lands."]),
      ],
    }),
    "zh-hans": articleCopy(newsLabels, "zh-hans", 5, {
      eyebrow: "2026 科隆游戏展",
      title: "Gamescom 2026 Aion 2 观赛指南：何时观看及可期待什么",
      description: "Aion 2 将亮相 8 月 25 日的 2026 科隆游戏展开幕之夜现场，展馆于 8 月 26 日开放。以下为完整日程、观看渠道与 NCSoft 可能发布的内容。",
      intro: "随着西方服抢先体验于 9 月 30 日到来，Gamescom 2026 是 Aion 2 全球上线前的最后大舞台——NCSoft 已确认参展。本指南汇总活动日程、观看渠道与现实预期清单，确保你不会错过任何一项公告。",
      sourceNote: "基于 AION2Hub 8 月 10 日 Gamescom 开幕之夜现场报道、MMOBomb 8 月 14 日 NCSoft Gamescom 预告及 Gamescom 官方活动页。日期反映最新确认日程。",
      keywords: ["Gamescom 2026 日程", "Aion 2 科隆游戏展", "Gamescom 开幕之夜 Aion 2", "Aion 2 2026年8月新闻", "哪里看 Gamescom"],
      sections: [
        section("schedule", "Aion 2 玩家的 Gamescom 2026 日程", ["开幕之夜现场（Opening Night Live）将于 2026 年 8 月 25 日播出——NCSoft 已确认 Aion 2 将亮相该秀，此外还有 Project Bonfire 世界首秀与更多 Cinder City 信息。ONL 是重磅发布落地的时刻，是必看场次。", "科隆游戏展馆将于 8 月 26 日开放并持续数日。NCSoft 已确认整体参展，但 Aion 2 展台的具体活动（试玩、见面会）尚未公开细节。"]),
        section("watch", "在哪里与如何观看", ["开幕之夜现场将在 Gamescom 官方频道免费直播——通常是 YouTube、Twitch 及 gamescom 官网。数字直播无需门票。", "若要专门跟进 Aion 2，请关注 NCSoft 官方频道与 gamescom 直播；多数 MMO 新闻媒体也会图文直播 Aion 2 片段，偏好文字摘要者可选择。"]),
        section("expect", "对 Aion 2 的预期", ["鉴于抢先体验已确认 9 月 30 日，最可能的公告是免费游玩正式上线的具体全球时间线、新预告片，或上线窗口系统的更多细节。", "NCSoft 已在 8 月开发者直播中详述自定义、八职业、五个服务器区域、PvP 与创始人包——因此科隆展是下一步的自然时机：全球正式上线的日期细节及上线后路线图。"]),
        section("prep", "展会前的准备", ["如果你还没做决定，请在科隆展前锁定服务器区域与创始人包选择——科隆的任何上线窗口公告都会让 9 月 30 日抢先体验的启动更顺畅。", "收藏本站并在每场活动后回来查看：我们将在科隆周第一时间汇总每项 Aion 2 发布内容。"]),
      ],
    }),
    ko: articleCopy(newsLabels, "ko", 5, {
      eyebrow: "게임스컴 2026",
      title: "Gamescom 2026 Aion 2 시청 가이드: 언제 시청하고 무엇을 기대할까",
      description: "Aion 2는 8월 25일 Gamescom 2026 오프닝 나이트 라이브에 참가하며, 전시장은 8월 26일 문을 엽니다. 전체 일정, 시청 채널, NCSoft가 공개할 수 있는 내용을 정리했습니다.",
      intro: "서구권 얼리 액세스가 9월 30일에 다가오면서 Gamescom 2026은 Aion 2 글로벌 출시 전 마지막 큰 무대입니다 — NCSoft 참가가 확인되었습니다. 이 가이드는 행사 일정, 시청 채널, 현실적인 기대 목록을 정리해 어떤 발표도 놓치지 않게 해줍니다.",
      sourceNote: "AION2Hub의 Gamescom 오프닝 나이트 라이브 보도(8월 10일), MMOBomb의 NCSoft Gamescom 티저(8월 14일), 공식 Gamescom 행사 페이지에 기반합니다. 날짜는 최신 확인 일정을 반영합니다.",
      keywords: ["Gamescom 2026 일정", "Aion 2 게임스컴", "게임스컴 오프닝 나이트 라이브 Aion 2", "Aion 2 2026년 8월 뉴스", "게임스컴 시청처"],
      sections: [
        section("schedule", "Aion 2 팬을 위한 Gamescom 2026 일정", ["오프닝 나이트 라이브는 2026년 8월 25일에 방송됩니다 — NCSoft는 Project Bonfire 월드 프리미어와 Cinder City 추가 정보와 함께 Aion 2가 쇼의 일부임을 확인했습니다. ONL은 최대 규모 발표가 나오는 자리이므로 반드시 봐야 할 시간대입니다.", "게임스컴 전시장은 8월 26일에 열리며 며칠간 이어집니다. NCSoft의 부스 참가가 전체 행사로 확인되었지만, Aion 2 현장 활동(데모, 팬미팅)의 구체적 내용은 아직 공개되지 않았습니다."]),
        section("watch", "어디서 어떻게 시청할까", ["오프닝 나이트 라이브는 Gamescom 공식 채널에서 무료로 스트리밍됩니다 — 일반적으로 YouTube, Twitch, gamescom 웹사이트. 디지털 방송에는 티켓이 필요 없습니다.", "Aion 2를 특별히 팔로우하려면 NCSoft 공식 채널과 gamescom 방송을 보세요. 대부분 MMO 뉴스 매체도 Aion 2 부분을 생중계하므로 텍스트 요약을 선호하면 그것도 선택지입니다."]),
        section("expect", "Aion 2에 기대할 것", ["얼리 액세스가 9월 30일로 확인된 가운데, 가장 유력한 발표는 무료 플레이 정식 출시의 구체적 글로벌 출시 일정, 새 트레일러, 또는 출시 창구 시스템의 추가 세부사항입니다.", "NCSoft는 8월 개발자 스트림에서 커스터마이징, 8개 클래스, 5개 서버 지역, PvP, 파운더스 팩을 이미 상세히 공개했으므로, Gamescom은 다음 단계를 위한 자연스러운 시점입니다: 정식 출시 날짜 세부사항과 출시 후 로드맵."]),
        section("prep", "쇼 전 준비 방법", ["아직 결정하지 않았다면 Gamescom 전에 서버 지역과 파운더스 팩 결정을 확정하세요 — 쾰른에서 나오는 출시 창구 발표가 9월 30일 얼리 액세스 시작을 훨씬 수월하게 만듭니다.", "저희 허브를 즐겨찾기하고 각 이벤트 후 돌아오세요: Gamescom 주간의 모든 Aion 2 공개를 가장 먼저 요약해 드립니다."]),
      ],
    }),
    ja: articleCopy(newsLabels, "ja", 5, {
      eyebrow: "ゲームズコム2026",
      title: "Gamescom 2026 Aion 2 視聴ガイド：いつ視聴するか、何が期待できるか",
      description: "Aion 2 は8月25日の Gamescom 2026 オープニングナイトライブに登場し、会場は8月26日に開幕します。完全なスケジュール、視聴チャンネル、NCSoft が発表しうる内容をまとめました。",
      intro: "西側早期アクセスが9月30日に迫る中、Gamescom 2026 は Aion 2 グローバルローンチ前最後の大きなステージです — NCSoft の参加が確認されています。このガイドはイベントスケジュール、視聴チャンネル、現実的な期待リストをまとめ、発表をひとつも逃さないようにします。",
      sourceNote: "AION2Hub の Gamescom オープニングナイトライブ報道（8月10日）、MMOBomb の NCSoft Gamescom ティーザー（8月14日）、公式 Gamescom イベントページに基づきます。日付は最新確認スケジュールを反映しています。",
      keywords: ["Gamescom 2026 スケジュール", "Aion 2 Gamescom", "Gamescom オープニングナイトライブ Aion 2", "Aion 2 2026年8月ニュース", "Gamescom 視聴方法"],
      sections: [
        section("schedule", "Aion 2 ファンのための Gamescom 2026 スケジュール", ["オープニングナイトライブは2026年8月25日に放送されます — NCSoft は Project Bonfire の世界初公開や Cinder City の追加情報とともに、Aion 2 がショーの一部であることを確認しました。ONL は最大級の発表が行われる時間帯のため、必見です。", "Gamescom 会場は8月26日に開幕し、数日間続きます。NCSoft のブース参加はイベント全体で確認されていますが、Aion 2 の会場内アクティビティ（デモ、ファンミーティング）の詳細はまだ公開されていません。"]),
        section("watch", "どこで・どう視聴するか", ["オープニングナイトライブは Gamescom 公式チャンネルで無料配信されます — 通常は YouTube、Twitch、gamescom ウェブサイト。デジタル放送にチケットは不要です。", "Aion 2 を特に追うなら、NCSoft 公式チャンネルと gamescom 放送をチェックしてください。テキスト要約を好むなら、多くの MMO ニュース媒体が Aion 2 のパートをライブブログで配信します。"]),
        section("expect", "Aion 2 に期待できること", ["早期アクセスが9月30日に確定している中、最も可能性が高いのは無料プレイ正式リリースの具体的なグローバルリリース時期、新トレーラー、またはローンチウィンドウシステムの追加詳細です。", "NCSoft は8月の開発者ストリームでカスタマイズ、8クラス、5サーバーリージョン、PvP、ファウンダーズパックをすでに詳述しているため、Gamescom は次のステップの自然な場です：正式リリース日付の詳細とローンチ後ロードマップ。"]),
        section("prep", "ショー前にできる準備", ["まだ決めていなければ、Gamescom 前にサーバーリージョンとファウンダーズパックの決定を確定させましょう — ケルンでのローンチウィンドウ発表で、9月30日の早期アクセス開始がよりスムーズになります。", "当ハブをブックマークし、各イベント後にチェックしてください：Gamescom 週のすべての Aion 2 発表をリアルタイムで要約します。"]),
      ],
    }),
    fr: articleCopy(newsLabels, "fr", 5, {
      eyebrow: "GAMESCOM 2026",
      title: "Guide de visionnage Gamescom 2026 Aion 2 : quand suivre et à quoi s'attendre",
      description: "Aion 2 se rend à l'Opening Night Live de la Gamescom 2026 le 25 août, le salon ouvrant le 26 août. Programme complet, chaînes de diffusion et annonces possibles de NCSoft.",
      intro: "Avec l'accès anticipé occidental le 30 septembre, la Gamescom 2026 est la dernière grande scène avant le lancement mondial d'Aion 2 — et NCSoft a confirmé sa présence.",
      sourceNote: "Basé sur le rapport d'AION2Hub (10 août), le tease MMOBomb (14 août) et la page officielle Gamescom.",
      keywords: ["Gamescom 2026 programme", "Aion 2 Gamescom", "Aion 2 août 2026", "regarder Gamescom"],
      sections: [
        section("schedule", "Programme Gamescom 2026", ["L'Opening Night Live aura lieu le 25 août 2026 — Aion 2 sera présent, avec la première mondiale de Project Bonfire et plus sur Cinder City.", "Le salon ouvre le 26 août pour plusieurs jours. Des activités Aion 2 précises au stand n'ont pas encore été détaillées."]),
        section("watch", "Où et comment regarder", ["L'ONL est diffusé gratuitement sur les chaînes officielles Gamescom (YouTube, Twitch, site web).", "Suivez aussi les chaînes officielles NCSoft et les médias MMO pour des résumés textuels."]),
        section("expect", "À quoi s'attendre pour Aion 2", ["Avec l'accès anticipé le 30 septembre, attendez-vous à une date de sortie mondiale concrète, de nouvelles bandes-annonces ou des détails sur les systèmes de lancement."]),
        section("prep", "Préparation avant le salon", ["Verrouillez votre région de serveur et votre pack Fondateur avant Gamescom, et suivez notre hub pour les résumés de la semaine Gamescom."]),
      ],
    }),
    de: articleCopy(newsLabels, "de", 5, {
      eyebrow: "GAMESCOM 2026",
      title: "Gamescom-2026-Aion-2-Watch-Guide: Wann einschalten & was zu erwarten ist",
      description: "Aion 2 erscheint am 25. August in der Opening Night Live der Gamescom 2026, die Messe öffnet am 26. August. Programm, Kanäle und mögliche NCSoft-Ankündigungen.",
      intro: "Mit dem Western-Early-Access am 30. September ist die Gamescom 2026 die letzte große Bühne vor dem globalen Launch von Aion 2 — und NCSoft hat seine Teilnahme bestätigt.",
      sourceNote: "Basierend auf dem AION2Hub-Bericht (10. August), dem MMOBomb-Tease (14. August) und der offiziellen Gamescom-Seite.",
      keywords: ["Gamescom 2026 Programm", "Aion 2 Gamescom", "Aion 2 August 2026", "Gamescom sehen"],
      sections: [
        section("schedule", "Gamescom-2026-Zeitplan", ["Die Opening Night Live findet am 25. August 2026 statt — Aion 2 wird dabei sein, neben der Weltpremiere von Project Bonfire und Neuem zu Cinder City.", "Die Messe öffnet am 26. August. Konkrete Aion-2-Standaktivitäten sind noch nicht detailliert."]),
        section("watch", "Wo und wie zuschauen", ["Die ONL wird gratis auf den offiziellen Gamescom-Kanälen gestreamt (YouTube, Twitch, Website).", "Folgen Sie auch NCSofts offiziellen Kanälen und MMO-Medien für Textzusammenfassungen."]),
        section("expect", "Was für Aion 2 zu erwarten ist", ["Mit dem Early Access am 30. September: konkrete Release-Details, neue Trailer oder Systemdetails für das Launch-Fenster."]),
        section("prep", "Vorbereitung vor der Messe", ["Legen Sie Serverregion und Founder's Pack vor Gamescom fest und folgen Sie unserem Hub für Zusammenfassungen der Gamescom-Woche."]),
      ],
    }),
    es: articleCopy(newsLabels, "es", 5, {
      eyebrow: "GAMESCOM 2026",
      title: "Guía de visionado de Gamescom 2026 de Aion 2: cuándo verlo y qué esperar",
      description: "Aion 2 llega al Opening Night Live de la Gamescom 2026 el 25 de agosto, con el salón abriendo el 26. Programa completo, canales y posibles anuncios de NCSoft.",
      intro: "Con el acceso anticipado occidental el 30 de septiembre, la Gamescom 2026 es el último gran escenario antes del lanzamiento global de Aion 2 — y NCSoft ha confirmado su presencia.",
      sourceNote: "Basado en el informe de AION2Hub (10 de agosto), el adelanto de MMOBomb (14 de agosto) y la página oficial de Gamescom.",
      keywords: ["Gamescom 2026 programa", "Aion 2 Gamescom", "Aion 2 agosto 2026", "ver Gamescom"],
      sections: [
        section("schedule", "Programa de Gamescom 2026", ["El Opening Night Live se emitirá el 25 de agosto de 2026 — Aion 2 estará presente, junto al estreno mundial de Project Bonfire y más sobre Cinder City.", "El salón abre el 26 de agosto. Las actividades específicas de Aion 2 en el stand aún no se detallan."]),
        section("watch", "Dónde y cómo verlo", ["La ONL se transmite gratis en los canales oficiales de Gamescom (YouTube, Twitch, sitio web).", "Sigue también los canales oficiales de NCSoft y los medios MMO para resúmenes en texto."]),
        section("expect", "Qué esperar de Aion 2", ["Con el acceso anticipado el 30 de septiembre: fecha de lanzamiento mundial concreta, nuevos tráileres o detalles de los sistemas de lanzamiento."]),
        section("prep", "Preparación antes del evento", ["Fija tu región de servidor y tu paquete de fundador antes de Gamescom, y sigue nuestro hub para resúmenes de la semana Gamescom."]),
      ],
    }),
    "pt-br": articleCopy(newsLabels, "pt-br", 5, {
      eyebrow: "GAMESCOM 2026",
      title: "Guia de como assistir à Gamescom 2026 de Aion 2: quando ver e o que esperar",
      description: "Aion 2 vai ao Opening Night Live da Gamescom 2026 em 25 de agosto, com o salão abrindo em 26. Programação completa, canais e possíveis anúncios da NCSoft.",
      intro: "Com o acesso antecipado ocidental em 30 de setembro, a Gamescom 2026 é o último grande palco antes do lançamento global de Aion 2 — e a NCSoft confirmou presença.",
      sourceNote: "Baseado no relatório da AION2Hub (10 de agosto), no teaser da MMOBomb (14 de agosto) e na página oficial da Gamescom.",
      keywords: ["Gamescom 2026 programação", "Aion 2 Gamescom", "Aion 2 agosto 2026", "assistir Gamescom"],
      sections: [
        section("schedule", "Programação da Gamescom 2026", ["O Opening Night Live vai ao ar em 25 de agosto de 2026 — Aion 2 estará presente, junto com a estreia mundial de Project Bonfire e mais sobre Cinder City.", "O salão abre em 26 de agosto. Atividades específicas de Aion 2 no estande ainda não foram detalhadas."]),
        section("watch", "Onde e como assistir", ["A ONL é transmitida gratuitamente nos canais oficiais da Gamescom (YouTube, Twitch, site).", "Siga também os canais oficiais da NCSoft e mídias de MMO para resumos em texto."]),
        section("expect", "O que esperar de Aion 2", ["Com o acesso antecipado em 30 de setembro: data de lançamento global concreta, novos trailers ou detalhes dos sistemas de lançamento."]),
        section("prep", "Preparação antes do evento", ["Defina sua região de servidor e seu pacote de fundador antes da Gamescom, e siga nosso hub para resumos da semana Gamescom."]),
      ],
    }),
    ru: articleCopy(newsLabels, "ru", 5, {
      eyebrow: "GAMESCOM 2026",
      title: "Гайд по просмотру Gamescom 2026 для Aion 2: когда смотреть и чего ждать",
      description: "Aion 2 появится на Opening Night Live Gamescom 2026 25 августа, выставочные залы откроются 26-го. Полное расписание, каналы и возможные анонсы NCSoft.",
      intro: "С западным ранним доступом 30 сентября Gamescom 2026 — последняя большая сцена перед глобальным запуском Aion 2, и NCSoft подтвердила участие.",
      sourceNote: "На основе отчёта AION2Hub (10 августа), тизера MMOBomb (14 августа) и официальной страницы Gamescom.",
      keywords: ["Gamescom 2026 расписание", "Aion 2 Gamescom", "Aion 2 август 2026", "смотреть Gamescom"],
      sections: [
        section("schedule", "Расписание Gamescom 2026", ["Opening Night Live пройдёт 25 августа 2026 года — Aion 2 будет там, вместе с мировой премьерой Project Bonfire и новостями о Cinder City.", "Залы открываются 26 августа. Конкретные активности Aion 2 на стенде пока не раскрыты."]),
        section("watch", "Где и как смотреть", ["ONL транслируется бесплатно на официальных каналах Gamescom (YouTube, Twitch, сайт).", "Следите также за каналами NCSoft и MMO-СМИ для текстовых сводок."]),
        section("expect", "Чего ждать от Aion 2", ["С ранним доступом 30 сентября: конкретная дата мирового релиза, новые трейлеры или детали систем окна запуска."]),
        section("prep", "Подготовка перед шоу", ["Зафиксируйте регион сервера и набор основателя до Gamescom и следите за нашим хабом для сводок недели Gamescom."]),
      ],
    }),
    "zh-hant": articleCopy(newsLabels, "zh-hant", 5, {
      eyebrow: "2026 科隆遊戲展",
      title: "Gamescom 2026 Aion 2 觀賽指南：何時觀看及可期待什麼",
      description: "Aion 2 將亮相 8 月 25 日的 2026 科隆遊戲展開幕之夜現場，展館於 8 月 26 日開放。以下為完整日程、觀看管道與 NCSoft 可能發布的內容。",
      intro: "隨著西方服搶先體驗於 9 月 30 日到來，Gamescom 2026 是 Aion 2 全球上線前的最後大舞台——NCSoft 已確認參展。本指南彙總活動日程、觀看管道與現實預期清單，確保你不會錯過任何一項公告。",
      sourceNote: "基於 AION2Hub 8 月 10 日 Gamescom 開幕之夜現場報導、MMOBomb 8 月 14 日 NCSoft Gamescom 預告及 Gamescom 官方活動頁。日期反映最新確認日程。",
      keywords: ["Gamescom 2026 日程", "Aion 2 科隆遊戲展", "Gamescom 開幕之夜 Aion 2", "Aion 2 2026年8月新聞", "哪裡看 Gamescom"],
      sections: [
        section("schedule", "Aion 2 玩家的 Gamescom 2026 日程", ["開幕之夜現場（Opening Night Live）將於 2026 年 8 月 25 日播出——NCSoft 已確認 Aion 2 將亮相該秀，此外還有 Project Bonfire 世界首秀與更多 Cinder City 資訊。ONL 是重磅發布落地的時刻，是必看場次。", "科隆遊戲展館將於 8 月 26 日開放並持續數日。NCSoft 已確認整體參展，但 Aion 2 展台的具體活動（試玩、見面會）尚未公開細節。"]),
        section("watch", "在哪裡與如何觀看", ["開幕之夜現場將在 Gamescom 官方頻道免費直播——通常是 YouTube、Twitch 及 gamescom 官網。數位直播無需門票。", "若要專門跟進 Aion 2，請關注 NCSoft 官方頻道與 gamescom 直播；多數 MMO 新聞媒體也會圖文直播 Aion 2 片段，偏好文字摘要者可選擇。"]),
        section("expect", "對 Aion 2 的預期", ["鑑於搶先體驗已確認 9 月 30 日，最可能的公告是免費遊玩正式上線的具體全球時間線、新預告片，或上線窗口系統的更多細節。", "NCSoft 已在 8 月開發者直播中詳述自訂、八職業、五個伺服器區域、PvP 與創始人包——因此科隆展是下一步的自然時機：全球正式上線的日期細節及上線後路線圖。"]),
        section("prep", "展會前的準備", ["如果你還沒做決定，請在科隆展前鎖定伺服器區域與創始人包選擇——科隆的任何上線窗口公告都會讓 9 月 30 日搶先體驗的啟動更順暢。", "收藏本站並在每場活動後回來查看：我們將在科隆週第一時間彙總每項 Aion 2 發布內容。"]),
      ],
    }),
  },
};