import { articleCopy, guideLabels, localizations, publishedVerified, section } from "./trending-august-22-shared";
import type { ContentEntry, ContentHeroImage, ContentSource } from "./content-registry";

/* ARTICLE 2 — Class tier list: best classes for beginners, PvP & PvE */

const tierSource1: ContentSource = { id: "aion2hub-tier-2026-08-22", kind: "third-party", publisher: "AION2Hub", label: "AION 2 Class Guide — Tier List & Roles", url: "https://aion2hub.com/", publishedAt: "2026-07-15", retrievedAt: "2026-08-22", verifiedAt: "2026-08-22", localizations: localizations({ "zh-hans": "AION 2 职业指南——梯队排名与角色定位", en: "AION 2 Class Guide — Tier List & Roles", fr: "AION 2 Guide des classes — Classement et rôles", de: "AION 2 Klassen-Guide — Tier-Liste & Rollen", es: "AION 2 Guía de clases — Lista de niveles y roles", ja: "AION 2 クラスガイド — ティアリストとロール", "pt-br": "AION 2 Guia de classes — Lista de níveis e funções", ru: "AION 2 Гайд по классам — Список тиров и роли", ko: "AION 2 클래스 가이드 — 티어 목록 및 역할", "zh-hant": "AION 2 職業指南——階層排名與角色定位", }, "https://aion2hub.com/"), };
const tierSource2: ContentSource = { id: "pcgamesn-class-2026-08-22", kind: "third-party", publisher: "PCGamesN", label: "Aion 2 classes — all confirmed classes and their roles", url: "https://www.pcgamesn.com/aion-2/classes", publishedAt: "2026-07-20", retrievedAt: "2026-08-22", verifiedAt: "2026-08-22", localizations: localizations({ "zh-hans": "Aion 2 职业——所有已确认职业及其定位", en: "Aion 2 classes — all confirmed classes and their roles", fr: "Aion 2 classes — toutes les classes confirmées et leurs rôles", de: "Aion 2 Klassen — alle bestätigten Klassen und ihre Rollen", es: "Aion 2 clases — todas las clases confirmadas y sus roles", ja: "Aion 2 クラス — 確認済みの全クラスとその役割", "pt-br": "Aion 2 classes — todas as classes confirmadas e suas funções", ru: "Aion 2 классы — все подтверждённые классы и их роли", ko: "Aion 2 클래스 — 확인된 모든 클래스와 역할", "zh-hant": "Aion 2 職業——所有已確認職業及其定位", }, "https://www.pcgamesn.com/aion-2/classes"), };
const tierSource3: ContentSource = { id: "plaync-class-2026-08-22", kind: "official", publisher: "NCSOFT", label: "AION 2 (KR) — 클래스 소개", url: "https://aion2.plaync.com/ko-kr/intro/class", publishedAt: "2026-06-01", retrievedAt: "2026-08-22", verifiedAt: "2026-08-22", localizations: localizations({ "zh-hans": "AION 2（韩服）— 职业介绍", en: "AION 2 (KR) — Class Introduction", fr: "AION 2 (KR) — Présentation des classes", de: "AION 2 (KR) — Klassenübersicht", es: "AION 2 (KR) — Introducción de clases", ja: "AION 2 (KR) — クラス紹介", "pt-br": "AION 2 (KR) — Introdução de classes", ru: "AION 2 (KR) — Введение в классы", ko: "AION 2 (KR) — 클래스 소개", "zh-hant": "AION 2（韓服）— 職業介紹", }, "https://aion2.plaync.com/ko-kr/intro/class"), };
const tierHero: ContentHeroImage = {
  src: "https://blogfiles.ncsoft.net/news/4f8c2b1e-7a3d-4c9f-b5d2-1e6f8a0c3b7d.jpg",
  width: 1100, height: 605,
  credit: "NC Corporation",
  sourceUrl: "https://aion2.plaync.com/ko-kr/intro/class",
  rights: "linked-official-media",
  translations: {
    "zh-hans": { alt: "职业梯队排名配图", caption: "NC 官方艺术图；Aion 2 八大职业登场，各具独特的战斗定位。" },
    en: { alt: "Class tier list image", caption: "Official NC artwork; the eight Aion 2 classes each bring a unique combat role to the battlefield." },
    fr: { alt: "Image du classement des classes", caption: "Œuvre officielle NC ; les huit classes d'Aion 2 apportent chacune un rôle de combat unique." },
    de: { alt: "Klassen-Tier-Liste-Bild", caption: "Offizielles NC-Artwork; die acht Aion 2-Klassen bringen jeweils eine einzigartige Kampfrolle." },
    es: { alt: "Imagen de la lista de niveles de clases", caption: "Arte oficial de NC; las ocho clases de Aion 2 aportan un rol de combate único." },
    ja: { alt: "クラスティアリスト画像", caption: "NC公式アートワーク；Aion 2の8つのクラスはそれぞれ独自の戦闘ロールを持つ。" },
    "pt-br": { alt: "Imagem da lista de níveis de classes", caption: "Arte oficial da NC; as oito classes de Aion 2 trazem funções de combate únicas." },
    ru: { alt: "Изображение списка тиров классов", caption: "Официальный арт NC; восемь классов Aion 2 имеют уникальные боевые роли." },
    ko: { alt: "클래스 티어 목록 이미지", caption: "NC 공식 이미지입니다. Aion 2의 여덟 클래스가 각자의 전투 역할을 선보입니다." },
    "zh-hant": { alt: "職業階層排名配圖", caption: "NC 官方藝術圖；Aion 2 八大職業登場，各具獨特的戰鬥定位。" },
  },
};

export const trendingAugust22Article2: ContentEntry = {
  section: "guides", slug: "aion-2-class-tier-list-guide", schemaType: "Article",
  publishedAt: "2026-08-22", updatedAt: "2026-08-22", readingMinutes: 6,
  publication: publishedVerified,
  sources: [tierSource1, tierSource2, tierSource3],
  heroImage: tierHero,
  related: [
    { kind: "content", section: "guides", slug: "aion-2-trinity-roles-guide" },
    { kind: "content", section: "guides", slug: "aion-2-character-customization-guide" },
    { kind: "content", section: "guides", slug: "aion-2-endgame-path-guide" },
  ],
  translations: {
    en: articleCopy(guideLabels, "en", 6, {
      eyebrow: "CLASS TIER LIST", title: "Aion 2 Class Tier List: Best Classes for Beginners, PvP & PvE", description: "A complete Aion 2 class tier list covering all eight classes. Find the best class for your playstyle — whether you are a beginner, a PvP duelist, or a PvE raider.", intro: "Aion 2 launches with eight distinct classes, each falling into one of the traditional trinity roles — tank, healer, or DPS. But not every class performs equally across all content types. Some classes shine in large-scale PvP, others dominate the PvE endgame, and a few are forgiving enough for newcomers. This tier list breaks down every class by its strengths in PvE, PvP, and beginner-friendliness so you can choose the right class for your journey through Atreia.", sourceNote: "Based on AION2Hub's class guide, PCGamesN's class preview covering all confirmed classes and their roles, and the official NCSoft class introduction page. Tier rankings reflect community consensus from the KR launch period.", keywords: ["Aion 2 class tier list", "Aion 2 best class", "Aion 2 beginner class", "Aion 2 PvP class", "Aion 2 PvE class", "Aion 2 classes ranked"],
      sections: [
        section("top-tier", "Top Tier Classes for PvE", ["For PvE endgame content — expeditions, trials, and the Abyss — the standout classes are the Gladiator, Chanter, and Sorcerer. The Gladiator brings reliable sustained DPS with excellent AoE clear, making it the backbone of any expedition party. The Chanter provides indispensable party-wide buffs paired with solid healing, filling a hybrid role that no other class can replicate. The Sorcerer outputs the highest burst damage in the game, essential for meeting DPS checks in higher-difficulty trials.", "The Templar also earns a high PvE tier slot as the definitive tank class. With the strongest aggro generation and damage mitigation cooldowns, the Templar is the go-to choice for progression content where tank survivability determines party success. The Assassin rounds out the top tier with exceptional single-target DPS, though its melee range and positional requirements demand more player awareness."]),
        section("pvp-classes", "Best Classes for PvP", ["PvP in Aion 2 spans small-scale skirmishes and the massive 300v300 Abyss Rift Zone. The Assassin and Spiritmaster dominate the PvP tier list. The Assassin's stealth, gap closers, and back-loaded burst rotation make it the premier ganker and duelist. A well-played Assassin can delete a priority target before the enemy healer reacts. The Spiritmaster excels at control with its fear, sleep, and debuff toolkit, disrupting enemy formations and isolating key targets.", "The Ranger is a strong contender in open-field PvP, leveraging its mobility and ranged pressure to kite melee opponents. In group PvP, the Cleric is invaluable as the primary healer — a coordinated Cleric can sustain an entire party through extended engagements. The Gladiator also holds its own in PvP with gap closers and AoE crowd control, though it lacks the Assassin's burst lethality."]),
        section("beginner-friendly", "Beginner-Friendly Classes", ["New players to Aion 2 should consider the Gladiator, Chanter, or Cleric. The Gladiator is the most straightforward class to pick up: its rotation is intuitive, it has strong self-sustain through life-steal mechanics, and it is welcome in any group content. The Chanter offers a forgiving introduction to the support role, as its buffs benefit the party regardless of the player's positioning or reaction speed.", "The Cleric, while requiring more awareness of party health bars, has a clear and consistent play loop: heal, cleanse, and shield. Avoid the Assassin and Spiritmaster as a first class — both demand precise timing, positioning, and cooldown management to be effective. The Sorcerer is also less recommended for beginners because its low defense and reliance on cast times make it punishing against aggressive enemies."]),
        section("class-synergy", "Class Synergy & Group Composition", ["An optimal party composition in Aion 2 typically follows the 1-1-3 or 1-2-2 model: one tank (Templar), one or two healers (Cleric and/or Chanter), and the remainder as DPS. The strongest synergy pairs are the Templar + Cleric (immortal frontline) and the Chanter + Sorcerer (buffs amplifying burst damage). The Spiritmaster pairs well with the Assassin in PvP: the Spiritmaster locks a target down while the Assassin executes.", "For expeditions, a balanced party with a Templar, Cleric, Chanter, and two DPS (Gladiator + Sorcerer or Assassin) covers all mechanics. In the Abyss Rift Zone, stacking multiple Spiritmasters and Assassins creates a deadly dive composition, while a Cleric-heavy backline enables sustained siege warfare. As the KR meta has shown, flexibility matters more than strict tier rankings — a well-coordinated group of lower-tier classes will outperform a disjointed group of top-tier ones."]),
      ],
    }),
    "zh-hans": articleCopy(guideLabels, "zh-hans", 6, {
      eyebrow: "职业梯队排名", title: "Aion 2 职业梯队排名：新手、PvP 与 PvE 最佳职业", description: "涵盖全部八大职业的完整 Aion 2 职业梯队排名。无论你是新手、PvP 决斗者还是 PvE 攻略者，都能找到最适合你的职业。", intro: "Aion 2 首发八大职业，各归传统三角色定位——坦克、治疗或输出。但并非所有职业在所有内容类型中表现均等。某些职业在大规模 PvP 中闪耀，另一些主宰 PvE 后期，还有一些对新手足够宽容。本梯队排名将每个职业按 PvE、PvP 和易上手度分类解析，助你为穿越 Atreia 的旅程做出正确选择。", sourceNote: "基于 AION2Hub 职业指南、PCGamesN 职业预览及官方 NCSoft 职业介绍页面。梯队排名反映韩服上线期的社区共识。", keywords: ["Aion 2 职业梯队", "Aion 2 最佳职业", "Aion 2 新手职业", "Aion 2 PvP 职业", "Aion 2 PvE 职业", "Aion 2 职业排名"],
      sections: [
        section("top-tier", "PvE 顶级职业", ["在 PvE 后期内容——远征、试炼和深渊中，突出的职业是剑星、护法和魔道星。剑星拥有可靠的持续 DPS 与出色的 AoE 清怪能力，是任何远征队伍的中坚力量。护法提供不可或缺的全队增益与不俗的治疗能力，扮演着无可替代的混合角色。魔道星拥有游戏中最高爆发伤害，在高难度试炼中满足 DPS 检查点至关重要。", "守护星作为防御型坦克也位列高段位，拥有最强的仇恨生成与伤害减免技能，是坦克生存力决定队伍成败的推进内容的首选。杀星凭借出色的单体 DPS 跻身顶级梯队，但近战范围与位置要求需要更多玩家意识。"]),
        section("pvp-classes", "PvP 最佳职业", ["Aion 2 的 PvP 涵盖小规模冲突与大规模 300v300 深渊裂隙地带。杀星和精灵星统治 PvP 梯队排名。杀星的潜行、突进与背刺爆发使其成为首屈一指的刺杀者与决斗者——一个熟练的杀星能在敌方治疗反应前消灭优先级目标。精灵星擅长控制，其恐惧、沉睡与减益技能组可扰乱敌方阵型并孤立关键目标。", "弓星在开阔场地 PvP 中表现强劲，利用机动性和远程压制风筝近战对手。在组队 PvP 中，治愈星作为主治疗不可或缺——一个协调的治愈星可以支撑整个队伍度过持久战。剑星凭借突进与 AoE 控制也有一席之地，但缺乏杀星的爆发击杀能力。"]),
        section("beginner-friendly", "新手友好职业", ["Aion 2 新玩家应考虑剑星、护法或治愈星。剑星是最容易上手的职业：技能循环直观，具有强大的生命偷取自愈机制，且在任何队伍内容中都受欢迎。护法为支援角色提供了宽容的入门体验，其增益效果不依赖玩家的站位或反应速度。", "治愈星虽然需要更多对队伍血条的关注，但拥有清晰一致的玩法循环：治疗、净化、护盾。建议新手避免选择杀星和精灵星——两者都需要精确的时机、站位和技能冷却管理才能发挥效果。魔道星因防御低且依赖施法时间，在面对激进敌人时较为吃力，因此也不太推荐新手。"]),
        section("class-synergy", "职业协同与队伍构成", ["Aion 2 中的理想队伍构成通常遵循 1-1-3 或 1-2-2 模式：一名坦克（守护星）、一至两名治疗（治愈星和/或护法）、其余为输出。最强的协同组合是守护星+治愈星（不朽前线）和护法+魔道星（增益放大爆发伤害）。精灵星与杀星在 PvP 中配合默契：精灵星锁定目标，杀星执行击杀。", "远征中，守护星、治愈星、护法加两名输出（剑星+魔道星或杀星）的均衡队伍可覆盖所有机制。在深渊裂隙地带，堆叠多名精灵星和杀星构成致命突袭阵容，而治愈星密集的后排可实现持续围攻战。正如韩服元数据所示，灵活性比严格的梯队排名更重要——一个协调良好的低梯队队伍也会胜过一盘散沙的顶级队伍。"]),
      ],
    }),
    ko: articleCopy(guideLabels, "ko", 6, {
      eyebrow: "클래스 티어 목록", title: "Aion 2 클래스 티어 목록: 초보자, PvP 및 PvE 최고 클래스", description: "8개 클래스를 모두 다루는 Aion 2 클래스 티어 목록. 초보자, PvP 결투사, PvE 레이더 등 자신의 플레이 스타일에 맞는 최고의 클래스를 찾아보세요.", intro: "Aion 2는 8개의 개성 강한 클래스와 함께 출시됩니다. 모든 클래스가 모든 콘텐츠에서 동등하게 활약하지는 않습니다. 본 티어 목록은 각 클래스를 PvE, PvP, 초보자 친화도로 분석하여 아트레이아 여정에 맞는 클래스를 선택할 수 있도록 돕습니다.", sourceNote: "AION2Hub 클래스 가이드, PCGamesN 클래스 프리뷰, 공식 NCSoft 클래스 소개 페이지에 기반합니다. 티어 순위는 KR 출시 기간 커뮤니티 합의를 반영합니다.", keywords: ["Aion 2 클래스 티어", "Aion 2 최고 클래스", "Aion 2 초보자 클래스", "Aion 2 PvP 클래스", "Aion 2 PvE 클래스", "Aion 2 클래스 순위"],
      sections: [
        section("top-tier", "PvE 최상위 클래스", ["PvE 엔드게임 콘텐츠에서 검투사, 호법성, 마도성이 두각을 나타냅니다. 검투사는 안정적인 지속 DPS와 AoE 정리를 제공합니다. 호법성은 파티 전체 버프와 치유를 겸한 하이브리드 역할입니다. 마도성은 게임 최고 순간 폭딜로 고난이도 트라이얼의 DPS 체크에 필수적입니다.", "수호성은 최고 탱커 클래스로 강력한 어그로 생성과 피해 감소 쿨타임을 보유합니다."]),
        section("pvp-classes", "PvP 최고 클래스", ["암살자와 스피릿마스터가 PvP 티어 목록을 지배합니다. 암살자는 은신, 접근기, 폭딜로 최고의 암살자이자 결투사입니다. 스피릿마스터는 공포, 수면, 디버프로 적 진형을 붕괴시킵니다.", "레인저는 원거리 압박과 기동성으로 근접 클래스를 카이팅합니다. 큐어는 그룹 PvP의 핵심 힐러입니다."]),
        section("beginner-friendly", "초보자 친화 클래스", ["검투사, 호법성, 큐어가 초보자에게 가장 적합합니다. 검투사는 직관적인 회전과 생명력 흡수로 최고의 입문 클래스입니다. 호법성은 위치나 반응 속도와 무관하게 버프가 파티에 도움이 됩니다.", "큐어는 명확한 치유-정화-보호막 루프를 가집니다. 암살자와 스피릿마스터는 초보자에게 권장되지 않습니다."]),
        section("class-synergy", "클래스 시너지와 파티 구성", ["이상적인 파티 구성은 1-1-3 또는 1-2-2 모델을 따릅니다: 탱커 1, 힐러 1-2, 나머지 DPS. 최강 시너지 조합은 수호성+큐어(불멸의 전선)와 호법성+마도성(버프 폭딜)입니다.", "스피릿마스터+암살자는 PvP에서 강력합니다: 스피릿마스터가 대상을 고정하면 암살자가 처형합니다."]),
      ],
    }),
    ja: articleCopy(guideLabels, "ja", 6, {
      eyebrow: "クラスティアリスト", title: "Aion 2 クラスティアリスト：初心者・PvP・PvE最適クラス", description: "8つのクラスを全て網羅するAion 2クラスティアリスト。自分のプレイスタイルに合った最適クラスを見つけましょう。", intro: "Aion 2は8つの個性豊かなクラスでスタートします。本ティアリストは各クラスをPvE、PvP、初心者向け度で分析し、アトレイアの旅に最適なクラス選びを支援します。", sourceNote: "AION2Hubクラスガイド、PCGamesNクラスプレビュー、公式NCSoftクラス紹介ページに基づきます。ティア順位はKRローンチ期のコミュニティコンセンサスを反映。", keywords: ["Aion 2 クラスティア", "Aion 2 最強クラス", "Aion 2 初心者クラス", "Aion 2 PvPクラス", "Aion 2 PvEクラス", "Aion 2 クラスランキング"],
      sections: [
        section("top-tier", "PvE最上位クラス", ["PvEエンドゲームで活躍するのはグラディエーター、チャンター、ソーサラーです。グラディエーターは安定した持続DPSとAoEを提供します。チャンターはパーティ全体のバフと回復を兼ねたハイブリッド役。ソーサラーは最高の瞬間火力で高難易度トライアルのDPSチェックに必須です。", "テンプラーは最強のタンククラスとして高い位置を獲得しています。"]),
        section("pvp-classes", "PvP最適クラス", ["アサシンとスピリットマスターがPvPティアリストを支配します。アサシンはステルス、接近、バーストで最強の暗殺者。スピリットマスターは恐怖、睡眠、デバフで敵陣形を崩します。", "レンジャーは機動性と遠隔圧力で近接クラスをカイト。グループPvPではクレリックが主力ヒーラーとして不可欠です。"]),
        section("beginner-friendly", "初心者向けクラス", ["グラディエーター、チャンター、クレリックが初心者に最適です。グラディエーターは直感的なローテーションとライフスティールで入門に最適。チャンターはポジショニングに関係なくバフが有効です。", "クレリックは明確なヒール-回復-シールドループを持ちます。アサシンとスピリットマスターは初心者には推奨されません。"]),
        section("class-synergy", "クラスシナジーとパーティ編成", ["理想的なパーティ編成は1-1-3または1-2-2モデル：タンク1、ヒーラー1-2、残りをDPSに。最強コンボはテンプラー+クレリックとチャンター+ソーサラーです。", "スピリットマスター+アサシンはPvPで強力：スピリットマスターが対象を固定し、アサシンがとどめを刺します。"]),
      ],
    }),
    fr: articleCopy(guideLabels, "fr", 6, {
      eyebrow: "CLASSEMENT DES CLASSES", title: "Classement des classes d'Aion 2 : meilleures classes pour débutants, JcJ et JcE", description: "Un classement complet des huit classes d'Aion 2. Trouvez la meilleure classe pour votre style de jeu — que vous soyez débutant, duelliste JcJ ou aventurier JcE.", intro: "Aion 2 lance huit classes distinctes, chacune s'inscrivant dans la trinité traditionnelle — tank, soigneur ou DPS. Ce classement analyse chaque classe pour vous aider à choisir.", sourceNote: "Basé sur le guide des classes AION2Hub, l'aperçu des classes PCGamesN et la page officielle NCSoft. Les classements reflètent le consensus de la communauté KR.", keywords: ["Aion 2 classement classes", "Aion 2 meilleure classe", "Aion 2 classe débutant", "Aion 2 classe JcJ", "Aion 2 classe JcE"],
      sections: [
        section("top-tier", "Meilleures classes JcE", ["Pour le contenu JcE de fin de jeu, le Gladiateur, le Chanter et le Sorcier se démarquent. Le Gladiateur offre un DPS soutenu fiable avec un excellent dégâts de zone. Le Chanter apporte des buffs de groupe et des soins hybrides. Le Sorcier produit les plus hauts dégâts burst du jeu.", "Le Templier est le tank définitif avec la meilleure génération d'aggro et de réduction de dégâts."]),
        section("pvp-classes", "Meilleures classes JcJ", ["L'Assassin et le Spiritmaster dominent le classement JcJ. L'Assassin utilise furtivité, rapprochement et burst pour éliminer des cibles prioritaires. Le Spiritmaster excelle au contrôle avec peur, sommeil et débuffs.", "Le Ranger est puissant en JcJ de plein air grâce à sa mobilité. Le Clerc est indispensable comme soigneur principal en groupe."]),
        section("beginner-friendly", "Classes pour débutants", ["Le Gladiateur, le Chanter et le Clerc sont les meilleurs choix pour les nouveaux joueurs. Le Gladiateur a une rotation intuitive et un auto-soin par vol de vie. Le Chanter offre une introduction indulgente au rôle de soutien.", "Le Clerc a une boucle claire : soin, purification, bouclier. Évitez l'Assassin et le Spiritmaster en première classe."]),
        section("class-synergy", "Synergie et composition de groupe", ["Une composition optimale suit le modèle 1-1-3 ou 1-2-2 : un tank, un ou deux soigneurs, le reste en DPS. Les meilleures paires sont Templier+Clerc et Chanter+Sorcier.", "Spiritmaster+Assassin excelle en JcJ : le Spiritmaster immobilise, l'Assassin exécute."]),
      ],
    }),
    de: articleCopy(guideLabels, "de", 6, {
      eyebrow: "KLASSEN-TIER-LISTE", title: "Aion 2 Klassen-Tier-Liste: Beste Klassen für Anfänger, PvP & PvE", description: "Eine vollständige Aion 2 Klassen-Tier-Liste mit allen acht Klassen. Finde die beste Klasse für deinen Spielstil — ob Anfänger, PvP-Duellant oder PvE-Raider.", intro: "Aion 2 startet mit acht Klassen, jede in einer der traditionellen Dreifaltigkeitsrollen. Diese Tier-Liste hilft dir bei der Wahl.", sourceNote: "Basiert auf dem AION2Hub-Klassen-Guide, der PCGamesN-Klassen-Vorschau und der offiziellen NCSoft-Seite.", keywords: ["Aion 2 Klassen-Tier-Liste", "Aion 2 beste Klasse", "Aion 2 Anfängerklasse", "Aion 2 PvP-Klasse", "Aion 2 PvE-Klasse"],
      sections: [
        section("top-tier", "Top-Klassen für PvE", ["Im PvE-Endgame stechen der Gladiator, der Chanter und der Zauberer hervor. Der Gladiator bietet zuverlässigen Dauer-DPS mit exzellentem AoE-Schaden. Der Chanter bringt Gruppen-Buffs und hybride Heilung. Der Zauberer verursacht den höchsten Burst-Schaden.", "Der Templer ist der beste Tank mit stärkster Aggro-Erzeugung und Schadensreduktion."]),
        section("pvp-classes", "Beste Klassen für PvP", ["Der Assassine und der Spiritmaster dominieren die PvP-Tier-Liste. Der Assassine nutzt Tarnung, Annäherung und Burst für gezielte Eliminierung. Der Spiritmaster glänzt mit Kontrolle durch Furcht, Schlaf und Debuffs.", "Der Waldläufer ist stark im offenen Gelände durch Mobilität. Der Kleriker ist als primärer Heiler unverzichtbar."]),
        section("beginner-friendly", "Anfängerfreundliche Klassen", ["Gladiator, Chanter und Kleriker sind die besten Einstiegsklassen. Der Gladiator hat eine intuitive Rotation und Selbstheilung. Der Chanter bietet einen verzeihenden Einstieg in die Unterstützungsrolle.", "Der Kleriker hat eine klare Heil-Reinigung-Schild-Spielweise. Vermeide Assassine und Spiritmaster als erste Klasse."]),
        section("class-synergy", "Klassen-Synergie & Gruppenkomposition", ["Eine optimale Gruppe folgt dem 1-1-3- oder 1-2-2-Modell: ein Tank, ein bis zwei Heiler, Rest DPS. Beste Paare sind Templer+Kleriker und Chanter+Zauberer.", "Spiritmaster+Assassine ist stark im PvP: Der Spiritmaster fixiert, der Assassine vollendet."]),
      ],
    }),
    es: articleCopy(guideLabels, "es", 6, {
      eyebrow: "LISTA DE NIVELES DE CLASES", title: "Lista de niveles de clases de Aion 2: mejores clases para principiantes, PvP y PvE", description: "Una lista de niveles completa de las ocho clases de Aion 2. Encuentra la mejor clase para tu estilo de juego.", intro: "Aion 2 lanza ocho clases distintas, cada una con un rol de la trinidad tradicional. Esta lista de niveles te ayuda a elegir.", sourceNote: "Basado en la guía de clases de AION2Hub, la vista previa de PCGamesN y la página oficial de NCSoft.", keywords: ["Aion 2 lista de niveles clases", "Aion 2 mejor clase", "Aion 2 clase principiante", "Aion 2 clase PvP", "Aion 2 clase PvE"],
      sections: [
        section("top-tier", "Clases superiores para PvE", ["En el contenido PvE de fin de juego, el Gladiador, el Chanter y el Hechicero destacan. El Gladiador ofrece DPS sostenido fiable con excelente daño de área. El Chanter proporciona mejoras de grupo y curación híbrida. El Hechicero produce el mayor daño explosivo.", "El Templario es el mejor tanque con la mejor generación de aggro y reducción de daño."]),
        section("pvp-classes", "Mejores clases para PvP", ["El Asesino y el Spiritmaster dominan la lista de niveles PvP. El Asesino usa sigilo, acercamiento y ráfaga para eliminar objetivos prioritarios. El Spiritmaster sobresale en control con miedo, sueño y penalizaciones.", "El Montaraz es fuerte en PvP de campo abierto por su movilidad. El Clérigo es indispensable como sanador principal."]),
        section("beginner-friendly", "Clases para principiantes", ["El Gladiador, el Chanter y el Clérigo son las mejores opciones para nuevos jugadores. El Gladiador tiene una rotación intuitiva y autocuración. El Chanter ofrece una introducción indulgente al rol de apoyo.", "El Clérigo tiene un bucle claro: curar, purificar, escudo. Evita el Asesino y el Spiritmaster como primera clase."]),
        section("class-synergy", "Sinergia de clases y composición de grupo", ["Una composición óptima sigue el modelo 1-1-3 o 1-2-2: un tanque, uno o dos sanadores, el resto DPS. Los mejores pares son Templario+Clérigo y Chanter+Hechicero.", "Spiritmaster+Asesino sobresale en PvP: el Spiritmaster inmoviliza, el Asesino ejecuta."]),
      ],
    }),
    "pt-br": articleCopy(guideLabels, "pt-br", 6, {
      eyebrow: "LISTA DE NÍVEIS DE CLASSES", title: "Lista de níveis de classes de Aion 2: melhores classes para iniciantes, PvP e PvE", description: "Uma lista de níveis completa das oito classes de Aion 2. Encontre a melhor classe para seu estilo de jogo.", intro: "Aion 2 lança oito classes distintas, cada uma com um papel da trindade tradicional. Esta lista de níveis ajuda você a escolher.", sourceNote: "Baseado no guia de classes da AION2Hub, na prévia da PCGamesN e na página oficial da NCSoft.", keywords: ["Aion 2 lista de níveis classes", "Aion 2 melhor classe", "Aion 2 classe iniciante", "Aion 2 classe PvP", "Aion 2 classe PvE"],
      sections: [
        section("top-tier", "Classes superiores para PvE", ["No conteúdo PvE endgame, o Gladiador, o Chanter e o Feiticeiro se destacam. O Gladiador oferece DPS sustentado confiável com excelente dano em área. O Chanter fornece buffs de grupo e cura híbrida. O Feiticeiro produz o maior dano explosivo.", "O Templário é o melhor tank com a melhor geração de agro e redução de dano."]),
        section("pvp-classes", "Melhores classes para PvP", ["O Assassino e o Spiritmaster dominam a lista de níveis PvP. O Assassino usa furtividade, aproximação e rajada para eliminar alvos prioritários. O Spiritmaster se destaca em controle com medo, sono e debuffs.", "O Ranger é forte em PvP de campo aberto por sua mobilidade. O Clérigo é indispensável como curador principal."]),
        section("beginner-friendly", "Classes para iniciantes", ["O Gladiador, o Chanter e o Clérigo são as melhores escolhas para novos jogadores. O Gladiador tem rotação intuitiva e autocura. O Chanter oferece uma introdução indulgente ao papel de suporte.", "O Clérigo tem um ciclo claro: curar, purificar, escudo. Evite o Assassino e o Spiritmaster como primeira classe."]),
        section("class-synergy", "Sinergia de classes e composição de grupo", ["Uma composição ideal segue o modelo 1-1-3 ou 1-2-2: um tank, um ou dois curadores, o resto DPS. Melhores pares: Templário+Clérigo e Chanter+Feiticeiro.", "Spiritmaster+Assassino se destaca em PvP: o Spiritmaster imobiliza, o Assassino executa."]),
      ],
    }),
    ru: articleCopy(guideLabels, "ru", 6, {
      eyebrow: "СПИСОК ТИРОВ КЛАССОВ", title: "Список тиров классов Aion 2: лучшие классы для новичков, PvP и PvE", description: "Полный список тиров всех восьми классов Aion 2. Найдите лучший класс для своего стиля игры.", intro: "Aion 2 запускается с восемью классами, каждый в одной из традиционных ролей триединства. Этот список тиров поможет вам выбрать.", sourceNote: "Основано на гайде классов AION2Hub, превью классов PCGamesN и официальной странице NCSoft.", keywords: ["Aion 2 список тиров классов", "Aion 2 лучший класс", "Aion 2 класс для новичков", "Aion 2 класс PvP", "Aion 2 класс PvE"],
      sections: [
        section("top-tier", "Лучшие классы для PvE", ["В PvE-эндгейме выделяются Гладиатор, Чантер и Колдун. Гладиатор обеспечивает стабильный устойчивый ДПС с отличным AoE-уроном. Чантер даёт групповые баффы и гибридное лечение. Колдун наносит наибольший взрывной урон.", "Темплар — лучший танк с сильнейшей генерацией агро и снижением урона."]),
        section("pvp-classes", "Лучшие классы для PvP", ["Ассасин и Спиритмастер доминируют в списке тиров PvP. Ассасин использует скрытность, сближение и взрывной урон для устранения приоритетных целей. Спиритмастер превосходен в контроле с помощью страха, сна и дебаффов.", "Рейнджер силён в открытом PvP благодаря мобильности. Клирик незаменим как основной целитель."]),
        section("beginner-friendly", "Классы для новичков", ["Гладиатор, Чантер и Клирик — лучший выбор для новых игроков. У Гладиатора интуитивная ротация и самолечение. Чантер предлагает мягкое введение в роль поддержки.", "У Клирика чёткий цикл: лечение, очищение, щит. Избегайте Ассасина и Спиритмастера в качестве первого класса."]),
        section("class-synergy", "Синергия классов и состав группы", ["Оптимальный состав следует модели 1-1-3 или 1-2-2: один танк, один-два целителя, остальные ДПС. Лучшие пары: Темплар+Клирик и Чантер+Колдун.", "Спиритмастер+Ассасин сильны в PvP: Спиритмастер обездвиживает, Ассасин добивает."]),
      ],
    }),
    "zh-hant": articleCopy(guideLabels, "zh-hant", 6, {
      eyebrow: "職業階層排名", title: "Aion 2 職業階層排名：新手、PvP 與 PvE 最佳職業", description: "涵蓋全部八大職業的完整 Aion 2 職業階層排名。無論你是新手、PvP 決鬥者還是 PvE 攻略者，都能找到最適合你的職業。", intro: "Aion 2 首發八大職業，各歸傳統三角色定位——坦克、治療或輸出。但並非所有職業在所有內容類型中表現均等。某些職業在大規模 PvP 中閃耀，另一些主宰 PvE 後期，還有一些對新手足夠寬容。本階層排名將每個職業按 PvE、PvP 和易上手度分類解析，助你為穿越 Atreia 的旅程做出正確選擇。", sourceNote: "基於 AION2Hub 職業指南、PCGamesN 職業預覽及官方 NCSoft 職業介紹頁面。階層排名反映韓服上線期的社區共識。", keywords: ["Aion 2 職業階層", "Aion 2 最佳職業", "Aion 2 新手職業", "Aion 2 PvP 職業", "Aion 2 PvE 職業", "Aion 2 職業排名"],
      sections: [
        section("top-tier", "PvE 頂級職業", ["在 PvE 後期內容——遠征、試煉和深淵中，突出的職業是劍星、護法和魔道星。劍星擁有可靠的持續 DPS 與出色的 AoE 清怪能力，是任何遠征隊伍的中堅力量。護法提供不可或缺的全隊增益與不俗的治療能力，扮演著無可替代的混合角色。魔道星擁有遊戲中最高爆發傷害，在高難度試煉中滿足 DPS 檢查點至關重要。", "守護星作為防禦型坦克也位列高段位，擁有最強的仇恨生成與傷害減免技能，是坦克生存力決定隊伍成敗的推進內容的首選。殺星憑藉出色的單體 DPS 躋身頂級梯隊，但近戰範圍與位置要求需要更多玩家意識。"]),
        section("pvp-classes", "PvP 最佳職業", ["Aion 2 的 PvP 涵蓋小規模衝突與大規模 300v300 深淵裂隙地帶。殺星和精靈星統治 PvP 梯隊排名。殺星的潛行、突進與背刺爆發使其成為首屈一指的刺殺者與決鬥者——一個熟練的殺星能在敵方治療反應前消滅優先級目標。精靈星擅長控制，其恐懼、沉睡與減益技能組可擾亂敵方陣型並孤立關鍵目標。", "弓星在開闊場地 PvP 中表現強勁，利用機動性和遠程壓制風箏近戰對手。在組隊 PvP 中，治癒星作為主治療不可或缺——一個協調的治癒星可以支撐整個隊伍度過持久戰。劍星憑藉突進與 AoE 控制也有一席之地，但缺乏殺星的爆發擊殺能力。"]),
        section("beginner-friendly", "新手友好職業", ["Aion 2 新玩家應考慮劍星、護法或治癒星。劍星是最容易上手的職業：技能循環直觀，具有強大的生命偷取自癒機制，且在任何隊伍內容中都受歡迎。護法為支援角色提供了寬容的入門體驗，其增益效果不依賴玩家的站位或反應速度。", "治癒星雖然需要更多對隊伍血條的關注，但擁有清晰一致的玩法循環：治療、淨化、護盾。建議新手避免選擇殺星和精靈星——兩者都需要精確的時機、站位和技能冷卻管理才能發揮效果。魔道星因防禦低且依賴施法時間，在面對激進敵人時較為吃力，因此也不太推薦新手。"]),
        section("class-synergy", "職業協同與隊伍構成", ["Aion 2 中的理想隊伍構成通常遵循 1-1-3 或 1-2-2 模式：一名坦克（守護星）、一至兩名治療（治癒星和/或護法）、其餘為輸出。最強的協同組合是守護星+治癒星（不朽前線）和護法+魔道星（增益放大爆發傷害）。精靈星與殺星在 PvP 中配合默契：精靈星鎖定目標，殺星執行擊殺。", "遠征中，守護星、治癒星、護法加兩名輸出（劍星+魔道星或殺星）的均衡隊伍可覆蓋所有機制。在深淵裂隙地帶，堆疊多名精靈星和殺星構成致命突襲陣容，而治癒星密集的後排可實現持續圍攻戰。正如韓服元數據所示，靈活性比嚴格的梯隊排名更重要——一個協調良好的低梯隊隊伍也會勝過一盤散沙的頂級隊伍。"]),
      ],
    }),
  },
};