import { articleCopy, localizations, newsLabels, publishedVerified, section } from "./trending-september-12-shared";
import type { ContentEntry, ContentHeroImage, ContentSource } from "./content-registry";

/* ARTICLE 2 — Aion 2 global playable at six hardware booths at TGS 2026 before the Oct 5 launch */

const gamevuSource: ContentSource = {
  id: "gamevu-aion2-tgs-hardware-2026-09-10",
  kind: "third-party",
  publisher: "GameVu (게임뷰)",
  label: "NC's Aion 2 Global Collaborates With Hardware Vendors at TGS",
  url: "https://www.gamevu.co.kr/news/articleView.html?idxno=60711",
  publishedAt: "2026-09-10",
  retrievedAt: "2026-09-12",
  verifiedAt: "2026-09-12",
  localizations: localizations({
    "zh-hans": "NC 的 Aion 2 全球版在 TGS 与硬件厂商合作",
    en: "NC's Aion 2 Global Collaborates With Hardware Vendors at TGS",
    fr: "Le Aion 2 global de NC collabore avec des vendeurs de matériel au TGS",
    de: "NCs globales Aion 2 arbeitet auf der TGS mit Hardware-Anbietern zusammen",
    es: "El Aion 2 global de NC colabora con fabricantes de hardware en el TGS",
    ja: "NCのAion 2グローバル、TGSでハードウェア各社と協業",
    "pt-br": "O Aion 2 global da NC colabora com fabricantes de hardware na TGS",
    ru: "Глобальный Aion 2 от NC сотрудничает с производителями железа на TGS",
    ko: "엔씨 '아이온2' 글로벌, TGS서 하드웨어 업체와 협업",
    "zh-hant": "NC 的 Aion 2 全球版在 TGS 與硬體廠商合作",
  }, "https://www.gamevu.co.kr/news/articleView.html?idxno=60711"),
};

const tHero: ContentHeroImage = {
  src: "https://blogfiles.ncsoft.net/news/af7330da-4ff6-4b58-aece-400e6061a3be.jpg",
  width: 1200, height: 630,
  credit: "NC Corporation",
  sourceUrl: "https://aion2.plaync.com/en-us/",
  rights: "linked-official-media",
  translations: {
    "zh-hans": { alt: "Aion 2 TGS 2026 硬件展位新闻横幅", caption: "Aion 2 全球版将在 TGS 2026 的 6 家硬件厂商展位提供试玩（BenQ、ASUS ROG、Sofmap、Crowxis·CFD Sales、MSI、Lenovo）——10 月 5 日全球首发前的首批日本公开接触。" },
    en: { alt: "Aion 2 TGS 2026 hardware booth news banner", caption: "Aion 2 global will be playable at six hardware vendor booths at TGS 2026 — BenQ, ASUS ROG, Sofmap, Crowxis·CFD Sales, MSI, and Lenovo — the first public hands-on in Japan before the October 5 global launch." },
    fr: { alt: "Bannière d'actualité des stands matériel TGS 2026 d'Aion 2", caption: "Aion 2 global sera jouable sur six stands matériel au TGS 2026 — BenQ, ASUS ROG, Sofmap, Crowxis·CFD Sales, MSI et Lenovo — premiers essais publics au Japon avant le lancement du 5 octobre." },
    de: { alt: "News-Banner zu den TGS-2026-Hardware-Ständen von Aion 2", caption: "Aion 2 Global wird auf der TGS 2026 an sechs Hardware-Ständen spielbar sein — BenQ, ASUS ROG, Sofmap, Crowxis·CFD Sales, MSI und Lenovo — die ersten öffentlichen Hands-ons in Japan vor dem Launch am 5. Oktober." },
    es: { alt: "Banner de noticias de los stands de hardware TGS 2026 de Aion 2", caption: "Aion 2 global será jugable en seis stands de fabricantes de hardware en el TGS 2026 — BenQ, ASUS ROG, Sofmap, Crowxis·CFD Sales, MSI y Lenovo — primeros probadores públicos en Japón antes del lanzamiento del 5 de octubre." },
    ja: { alt: "Aion 2 TGS 2026 ハードウェアブースニュースバナー", caption: "Aion 2グローバルはTGS 2026で6社のハードウェアブース（BenQ、ASUS ROG、Sofmap、Crowxis・CFD販売、MSI、Lenovo）で試遊可能に——10月5日のグローバルローンチ前、日本初の公開ハンズオンです。" },
    "pt-br": { alt: "Banner de notícias dos estandes de hardware TGS 2026 do Aion 2", caption: "O Aion 2 global será jogável em seis estandes de fabricantes de hardware na TGS 2026 — BenQ, ASUS ROG, Sofmap, Crowxis·CFD Sales, MSI e Lenovo — primeiros testes públicos no Japão antes do lançamento de 5 de outubro." },
    ru: { alt: "Баннер новостей о стендах железа на TGS 2026 для Aion 2", caption: "Глобальный Aion 2 будет играбелен на шести стендах производителей железа на TGS 2026 — BenQ, ASUS ROG, Sofmap, Crowxis·CFD Sales, MSI и Lenovo — первый публичный хендс-он в Японии перед запуском 5 октября." },
    ko: { alt: "Aion 2 TGS 2026 하드웨어 부스 뉴스 배너", caption: "아이온2 글로벌이 TGS 2026에서 하드웨어 업체 부스 6곳(벤큐, 에이수스 ROG, 소프맵, 크로우시스·CFD판매, MSI, 레노버)에서 시연됩니다——10월 5일 글로벌 출시 전 일본 첫 공개 핸즈온입니다." },
    "zh-hant": { alt: "Aion 2 TGS 2026 硬體展位新聞橫幅", caption: "Aion 2 全球版將在 TGS 2026 的 6 家硬體廠商展位提供試玩（BenQ、ASUS ROG、Sofmap、Crowxis·CFD Sales、MSI、Lenovo）——10 月 5 日全球首發前的首批日本公開接觸。" },
  },
};

export const trendingSeptember12Article2: ContentEntry = {
  section: "news",
  slug: "aion-2-tgs-2026-hardware-booth-hands-on",
  schemaType: "NewsArticle",
  publishedAt: "2026-09-12",
  updatedAt: "2026-09-12",
  readingMinutes: 5,
  publication: publishedVerified,
  sources: [gamevuSource],
  heroImage: tHero,
  related: [
    { kind: "content", section: "news", slug: "aion-2-nc-chuseok-offensive" },
    { kind: "content", section: "guides", slug: "aion-2-launch-scale-test-preparation-guide" },
    { kind: "content", section: "guides", slug: "aion-2-prelaunch-access-routes-guide" },
    { kind: "content", section: "news", slug: "aion-2-october-5-launch-countdown-roadmap" },
  ],
  translations: {
    en: articleCopy(newsLabels, "en", 5, {
      eyebrow: "TGS 2026",
      title: "Aion 2 Global Playable at 6 Hardware Booths at TGS 2026: BenQ, ASUS ROG, MSI, Lenovo and More Before the October 5 Launch",
      description: "Aion 2 global gets its first public hands-on in Japan at TGS 2026 across six hardware vendor booths — BenQ, ASUS ROG, Sofmap, Crowxis·CFD Sales, MSI, Lenovo — while NC's own booth focuses on Astraea Oratio",
      intro: "NCsoft confirmed that Aion 2 global will be playable at Tokyo Game Show 2026 across six hardware vendor booths — BenQ, ASUS ROG, Sofmap, Crowxis·CFD Sales, MSI, and Lenovo. The hands-on demos give Japanese players their first public contact with the game before the October 5 launch, while NC's own TGS booth showcases its subculture title Astraea Oratio.",
      sourceNote: "Based on GameVu's September 10, 2026 report (retrieved September 12, 2026). Booth list as announced via NC's official SNS; booth availability is subject to TGS floor changes.",
      keywords: ["Aion 2 TGS 2026 hands-on", "Aion 2 Tokyo Game Show hardware booth", "Aion 2 BenQ ASUS ROG MSI Lenovo demo", "Aion 2 playable Japan October 5", "Aion 2 TGS Astraea Oratio booth"],
      sections: [
        section("tgs-plan", "TGS 2026: Playable Aion 2, No Standalone Booth", ["NCsoft confirmed Aion 2 global will be playable at Tokyo Game Show 2026 — but without a standalone Aion 2 booth. Instead, the game gets hands-on demos inside six hardware vendors' booths, announced through NC's official SNS.", "The approach trades a single owned space for six foot-traffic streams: each hardware partner shows off its monitors, PCs, and peripherals with a real game, while Aion 2 reaches Japanese players ahead of the global launch."]),
        section("six-booths", "The Six Hardware Booths", ["The confirmed booth partners are BenQ, ASUS ROG, Sofmap, Crowxis·CFD Sales, MSI, and Lenovo.", "Aion 2 runs on Unreal Engine 5 with high-resolution, high-quality graphics — a natural fit for gaming-display and PC vendors demonstrating performance. Expect the demo build to lean on the DLSS 4.5 baseline confirmed for the global build."]),
        section("why-hardware", "Why Hardware Booths Instead of an NC Booth", ["NC's main exhibition space at TGS 2026 is dedicated to Astraea Oratio, its subculture RPG aimed at the Japanese market, which gets a standalone booth and first playable demo.", "Splitting Aion 2 out to hardware booths is an efficient space strategy at big shows: publishers get exposure across multiple booths without paying for a second major build-out, and the demonstrated-game collaboration is a growing industry pattern."]),
        section("global-context", "The Global Launch Context", ["The TGS hands-on is the latest stop on Aion 2 global's pre-launch road: the free Launch Scale Test runs September 17-18 (overlapping the TGS dates), Founder's Pack advance access starts September 30, and the free-to-play global launch is October 5.", "For Japanese players, TGS is the first public touchpoint; for everyone else, the demos double as a signal that NC is actively courting the Japanese audience before launch."]),
        section("what-it-means", "What This Means", ["If you are at TGS, the six hardware booths are your chance to try the game hands-on; if not, the LST four days after the show starts is the free route to the same build.", "The hardware-collaboration pattern also hints at how NC plans to market the global launch: performance-first messaging around Unreal Engine 5 and DLSS, aimed at PC players in each region."]),
      ],
    }),
    "zh-hans": articleCopy(newsLabels, "zh-hans", 5, {
      eyebrow: "TGS 2026",
      title: "Aion 2 全球版在 TGS 2026 的 6 个硬件展位可试玩：BenQ、ASUS ROG、MSI、Lenovo 等——10 月 5 日首发前",
      description: "Aion 2 全球版在 TGS 2026 的 6 家硬件厂商展位提供首次日本公开试玩——BenQ、ASUS ROG、Sofmap、Crowxis·CFD Sales、MSI、Lenovo；NC 自家展台主推 Astraea Oratio",
      intro: "NCsoft 确认 Aion 2 全球版将在东京游戏展（TGS 2026）的 6 家硬件厂商展位提供试玩——BenQ、ASUS ROG、Sofmap、Crowxis·CFD Sales、MSI 与 Lenovo。这些试玩让日本玩家在 10 月 5 日首发前首次公开接触游戏，而 NC 自家 TGS 展台展示的是其亚文化新作 Astraea Oratio。",
      sourceNote: "基于 게임뷰（GameVu）2026 年 9 月 10 日报道（2026-09-12 抓取）。展位名单经 NC 官方 SNS 公布；具体展位以 TGS 现场为准。",
      keywords: ["Aion 2 TGS 2026 试玩", "Aion 2 东京电玩展 硬件展位", "Aion 2 BenQ ASUS ROG MSI Lenovo 演示", "Aion 2 日本试玩 10月5日", "Aion 2 TGS Astraea Oratio 展台"],
      sections: [
        section("tgs-plan", "TGS 2026：可试玩 Aion 2，但无独立展台", ["NCsoft 确认 Aion 2 全球版将在 TGS 2026 提供试玩——但没有 Aion 2 独立展台。取而代之，游戏在 6 家硬件厂商展位内提供试玩，名单经 NC 官方 SNS 公布。", "这一做法用一个自有空间换取六条人流：每家硬件伙伴用真实游戏展示其显示器、PC 与周边，而 Aion 2 在首发前触达日本玩家。"]),
        section("six-booths", "六个硬件展位", ["确认的展位伙伴：BenQ、ASUS ROG、Sofmap、Crowxis·CFD Sales、MSI 与 Lenovo。", "Aion 2 基于 Unreal Engine 5，画面为高分辨率高质量——天然适合展示电竞显示器与 PC 性能。预计演示构建会依赖全球版已确认的 DLSS 4.5 基线。"]),
        section("why-hardware", "为何用硬件展位而非 NC 展台", ["NC 在 TGS 2026 的主展区留给面向日本市场的亚文化 RPG《Astraea Oratio》——独立展台与首次试玩。", "把 Aion 2 拆到硬件展位是大型展会上的高效空间策略：厂商无需再付一个大型展台，就能在多个展位获得曝光；游戏×硬件的联动演示也是行业增长中的模式。"]),
        section("global-context", "全球首发语境", ["TGS 试玩是 Aion 2 全球版首发前之路的最新一站：免费规模测试 9 月 17-18 日举行（与 TGS 档期重叠）、创始人包抢先体验 9 月 30 日开始、免费制全球首发 10 月 5 日。", "对日本玩家，TGS 是首个公开触点；对其他人，这些演示同时是 NC 在首发前积极争取日本受众的信号。"]),
        section("what-it-means", "意义", ["如果你在 TGS，六个硬件展位就是亲手试玩的机会；如果不在，展会四天后的 LST 是体验同一构建的免费途径。", "硬件合作模式也暗示了 NC 的全球营销打法：围绕 Unreal Engine 5 与 DLSS 的性能优先话术，瞄准各地区的 PC 玩家。"]),
      ],
    }),
    fr: articleCopy(newsLabels, "fr", 5, {
      eyebrow: "TGS 2026",
      title: "Aion 2 global jouable sur 6 stands matériel au TGS 2026 : BenQ, ASUS ROG, MSI, Lenovo et plus avant le 5 octobre",
      description: "Aion 2 global fait ses premiers essais publics au Japon au TGS 2026 sur six stands matériel — BenQ, ASUS ROG, Sofmap, Crowxis·CFD Sales, MSI, Lenovo — pendant que le stand NC accueille Astraea Oratio",
      intro: "NCsoft confirme qu'Aion 2 global sera jouable au Tokyo Game Show 2026 sur six stands matériel — BenQ, ASUS ROG, Sofmap, Crowxis·CFD Sales, MSI et Lenovo. Les essais donnent aux joueurs japonais leur premier contact public avant le lancement du 5 octobre ; le stand NC montre Astraea Oratio.",
      sourceNote: "Basé sur le rapport de GameVu du 10 septembre 2026 (récupéré le 12 septembre 2026). Liste annoncée via les SNS officiels de NC ; sujette aux changements du plan du TGS.",
      keywords: ["Aion 2 TGS 2026 essai", "Aion 2 Tokyo Game Show stand matériel", "Aion 2 démo BenQ ASUS ROG MSI Lenovo", "Aion 2 jouable Japon 5 octobre", "Aion 2 TGS Astraea Oratio stand"],
      sections: [
        section("tgs-plan", "TGS 2026 : jouable, sans stand dédié", "Aion 2 global sera jouable au TGS 2026, mais sans stand Aion 2 dédié : les démos se font dans six stands matériel, via les SNS officiels de NC. Un espace unique échangé contre six flux de visiteurs."),
        section("six-booths", "Les six stands", "BenQ, ASUS ROG, Sofmap, Crowxis·CFD Sales, MSI et Lenovo. UE5 + haute résolution = démonstration idéale pour moniteurs/PC ; la build s'appuie sur la base DLSS 4.5 confirmée."),
        section("why-hardware", "Pourquoi des stands matériel", "L'espace principal de NC au TGS 2026 est pour Astraea Oratio (stand dédié, première démo jouable). Scinder Aion 2 sur des stands matériel = stratégie spatiale efficace et tendance croissante des collaborations jeu × matériel."),
        section("global-context", "Le contexte du lancement", "Le LST gratuit 17-18 septembre (chevauche TGS), accès anticipé Founder's Pack le 30 septembre, lancement free-to-play le 5 octobre. TGS = premier contact public japonais."),
        section("what-it-means", "Ce que ça signifie", "Au TGS, essayez sur les six stands ; sinon le LST quatre jours plus tard est la voie gratuite. Le pattern matériel laisse entrevoir un marketing performance-first (UE5, DLSS) pour chaque région PC."),
      ],
    }),
    de: articleCopy(newsLabels, "de", 5, {
      eyebrow: "TGS 2026",
      title: "Aion 2 Global auf 6 Hardware-Ständen der TGS 2026 spielbar: BenQ, ASUS ROG, MSI, Lenovo u.a. vor dem Start am 5. Oktober",
      description: "Aion 2 Global feiert auf der TGS 2026 sein erstes öffentliches Hands-on in Japan an sechs Hardware-Ständen — BenQ, ASUS ROG, Sofmap, Crowxis·CFD Sales, MSI, Lenovo — während der NC-Stand Astraea Oratio zeigt",
      intro: "NCsoft bestätigt, dass Aion 2 Global auf der Tokyo Game Show 2026 an sechs Hardware-Ständen spielbar sein wird — BenQ, ASUS ROG, Sofmap, Crowxis·CFD Sales, MSI und Lenovo. Die Hands-ons geben japanischen Spielern den ersten öffentlichen Kontakt vor dem 5. Oktober; der NC-Stand zeigt Astraea Oratio.",
      sourceNote: "Basierend auf dem GameVu-Bericht vom 10. September 2026 (abgerufen am 12. September 2026). Liste über NCS offizielle SNS; Änderungen am TGS-Grundriss vorbehalten.",
      keywords: ["Aion 2 TGS 2026 Hands-on", "Aion 2 Tokyo Game Show Hardware-Stand", "Aion 2 Demo BenQ ASUS ROG MSI Lenovo", "Aion 2 spielbar Japan 5. Oktober", "Aion 2 TGS Astraea Oratio Stand"],
      sections: [
        section("tgs-plan", "TGS 2026: spielbar, ohne eigenen Stand", "Aion 2 Global wird auf der TGS 2026 spielbar sein — aber ohne eigenen Aion-2-Stand: Die Demos laufen in sechs Hardware-Ständen, angekündigt über NCS offizielle SNS. Ein eigener Raum gegen sechs Besucherströme getauscht."),
        section("six-booths", "Die sechs Stände", "BenQ, ASUS ROG, Sofmap, Crowxis·CFD Sales, MSI und Lenovo. UE5 + hohe Auflösung = ideale Demonstration für Monitore/PCs; die Build stützt sich auf die bestätigte DLSS-4.5-Basis."),
        section("why-hardware", "Warum Hardware-Stände", "NCS Hauptfläche ist für Astraea Oratio (eigener Stand, erste spielbare Demo). Aion 2 auf Hardware-Stände zu verteilen ist eine effiziente Raumstrategie — und ein wachsendes Muster von Spiel × Hardware-Kooperationen."),
        section("global-context", "Der Launch-Kontext", "Kostenloser LST 17.-18. September (überlappt mit TGS), Founder's-Pack-Frühzugang 30. September, Free-to-Play-Start 5. Oktober. TGS = erster öffentlicher Japan-Kontakt."),
        section("what-it-means", "Was das bedeutet", "Auf der TGS an den sechs Ständen anspielen; sonst ist der LST vier Tage später der kostenlose Weg. Das Hardware-Muster deutet auf ein performance-first-Marketing (UE5, DLSS) für jede PC-Region hin."),
      ],
    }),
    es: articleCopy(newsLabels, "es", 5, {
      eyebrow: "TGS 2026",
      title: "Aion 2 global jugable en 6 stands de hardware en el TGS 2026: BenQ, ASUS ROG, MSI, Lenovo y más antes del 5 de octubre",
      description: "Aion 2 global hace sus primeras pruebas públicas en Japón en el TGS 2026 en seis stands de hardware — BenQ, ASUS ROG, Sofmap, Crowxis·CFD Sales, MSI, Lenovo — mientras el stand de NC muestra Astraea Oratio",
      intro: "NCsoft confirma que Aion 2 global será jugable en el Tokyo Game Show 2026 en seis stands de fabricantes de hardware — BenQ, ASUS ROG, Sofmap, Crowxis·CFD Sales, MSI y Lenovo. Las pruebas dan a los jugadores japoneses su primer contacto público antes del 5 de octubre; el stand de NC muestra Astraea Oratio.",
      sourceNote: "Basado en el informe de GameVu del 10 de septiembre de 2026 (recuperado el 12 de septiembre de 2026). Lista anunciada vía SNS oficiales de NC; sujeta a cambios del plano del TGS.",
      keywords: ["Aion 2 TGS 2026 prueba", "Aion 2 Tokyo Game Show stand hardware", "Aion 2 demo BenQ ASUS ROG MSI Lenovo", "Aion 2 jugable Japón 5 octubre", "Aion 2 TGS Astraea Oratio stand"],
      sections: [
        section("tgs-plan", "TGS 2026: jugable, sin stand propio", "Aion 2 global será jugable en el TGS 2026, pero sin stand propio: las demos corren en seis stands de hardware, vía SNS oficiales de NC. Un espacio propio intercambiado por seis flujos de visitantes."),
        section("six-booths", "Los seis stands", "BenQ, ASUS ROG, Sofmap, Crowxis·CFD Sales, MSI y Lenovo. UE5 + alta resolución = demostración ideal para monitores/PC; la build usa la base DLSS 4.5 confirmada."),
        section("why-hardware", "Por qué stands de hardware", "El espacio principal de NC en el TGS 2026 es para Astraea Oratio (stand propio, primera demo jugable). Repartir Aion 2 en stands de hardware es una estrategia espacial eficiente y un patrón creciente de colaboración juego × hardware."),
        section("global-context", "El contexto del lanzamiento", "LST gratuito 17-18 de septiembre (solapa con TGS), acceso anticipado de Founder's Pack el 30 de septiembre, lanzamiento free-to-play el 5 de octubre. TGS = primer contacto público japonés."),
        section("what-it-means", "Qué significa", "En el TGS, prueba en los seis stands; si no, el LST cuatro días después es la vía gratuita. El patrón de hardware apunta a un marketing performance-first (UE5, DLSS) para cada región de PC."),
      ],
    }),
    ja: articleCopy(newsLabels, "ja", 5, {
      eyebrow: "TGS 2026",
      title: "Aion 2 グローバル、TGS 2026でハードウェア6社ブースで試遊可能——BenQ、ASUS ROG、MSI、Lenovoほか、10月5日ローンチ前に",
      description: "Aion 2 グローバルがTGS 2026で日本初の公開ハンズオン——6社のハードウェアブース（BenQ、ASUS ROG、Sofmap、Crowxis・CFD販売、MSI、Lenovo）で試遊可能に；NC自社ブースはアストラエ・オラティオ",
      intro: "NCはAion 2グローバルが東京ゲームショウ2026でハードウェア6社のブース（BenQ、ASUS ROG、Sofmap、Crowxis・CFD販売、MSI、Lenovo）にて試遊可能になることを確認しました。10月5日ローンチ前に日本で初めて公開に触れる機会で、NC自社TGSブースはサブカルチャー新作『アストラエ・オラティオ』です。",
      sourceNote: "ゲームビュー（GameVu）2026年9月10日付報道（2026-09-12取得）に基づきます。ブースリストはNC公式SNS発表分；TGS会場の都合で変わり得ます。",
      keywords: ["Aion 2 TGS 2026 試遊", "Aion 2 東京ゲームショウ ハードウェアブース", "Aion 2 BenQ ASUS ROG MSI Lenovo デモ", "Aion 2 日本 試遊 10月5日", "Aion 2 TGS アストラエ・オラティオ ブース"],
      sections: [
        section("tgs-plan", "TGS 2026：試遊はあるが単独ブースなし", "NCはAion 2グローバルをTGS 2026で試遊可能にすると確認しましたが、単独ブースは出しません。代わりにハードウェア6社のブース内でハンズオンを実施し、リストはNC公式SNSで発表されました。1つの自社空間を6つの人流と交換する戦略です。"),
        section("six-booths", "6社のハードウェアブース", "確認されたブースはBenQ、ASUS ROG、Sofmap、Crowxis・CFD販売、MSI、Lenovo。Aion 2はUnreal Engine 5で高解像度・高画質——ゲーミングモニター・PCメーカーの性能展示にうってつけで、デモビルドはグローバル向けに確認済みのDLSS 4.5ベースが想定されます。"),
        section("why-hardware", "なぜハードウェアブースなのか", "NCのTGS 2026メイン展示は、日本市場向けサブカルチャーRPG『アストラエ・オラティオ』（単独ブース、初のプレイアブルデモ）です。Aion 2をハードウェアブースに分けるのは大型展示会での効率的な空間戦略——複数ブースで露出を得つつ、ゲーム×ハードウェアの連携デモという業界の広がるパターンでもあります。"),
        section("global-context", "グローバルローンチの文脈", "TGSハンズオンはローンチ前ロードの最新地点です：無料LSTは9月17-18日（TGSと日程が重なる）、ファウンダーズパック先行は9月30日、F2Pグローバルローンチは10月5日。"),
        section("what-it-means", "意味するところ", "TGSに行くなら6ブースで試遊を。行けない人には、4日後のLSTが同じビルドへの無料ルートです。ハードウェア連携のパターンは、UE5とDLSSを前面に出したパフォーマンス優先のマーケティングを示唆しています。"),
      ],
    }),
    "pt-br": articleCopy(newsLabels, "pt-br", 5, {
      eyebrow: "TGS 2026",
      title: "Aion 2 global jogável em 6 estandes de hardware na TGS 2026: BenQ, ASUS ROG, MSI, Lenovo e mais antes de 5 de outubro",
      description: "Aion 2 global faz seus primeiros testes públicos no Japão na TGS 2026 em seis estandes de hardware — BenQ, ASUS ROG, Sofmap, Crowxis·CFD Sales, MSI, Lenovo — enquanto o estande da NC mostra Astraea Oratio",
      intro: "A NCsoft confirma que o Aion 2 global será jogável no Tokyo Game Show 2026 em seis estandes de fabricantes de hardware — BenQ, ASUS ROG, Sofmap, Crowxis·CFD Sales, MSI e Lenovo. Os testes dão aos jogadores japoneses o primeiro contato público antes de 5 de outubro; o estande da NC mostra Astraea Oratio.",
      sourceNote: "Baseado no relatório da GameVu de 10 de setembro de 2026 (recuperado em 12 de setembro de 2026). Lista anunciada via SNS oficiais da NC; sujeita a mudanças do layout da TGS.",
      keywords: ["Aion 2 TGS 2026 teste", "Aion 2 Tokyo Game Show estande hardware", "Aion 2 demo BenQ ASUS ROG MSI Lenovo", "Aion 2 jogável Japão 5 outubro", "Aion 2 TGS Astraea Oratio estande"],
      sections: [
        section("tgs-plan", "TGS 2026: jogável, sem estande próprio", "O Aion 2 global será jogável na TGS 2026, mas sem estande próprio: as demos rodam em seis estandes de hardware, via SNS oficiais da NC. Um espaço próprio trocado por seis fluxos de visitantes."),
        section("six-booths", "Os seis estandes", "BenQ, ASUS ROG, Sofmap, Crowxis·CFD Sales, MSI e Lenovo. UE5 + alta resolução = demonstração ideal para monitores/PCs; a build usa a base DLSS 4.5 confirmada."),
        section("why-hardware", "Por que estandes de hardware", "O espaço principal da NC na TGS 2026 é para Astraea Oratio (estande próprio, primeira demo jogável). Espalhar o Aion 2 em estandes de hardware é uma estratégia espacial eficiente e um padrão crescente de colaboração jogo × hardware."),
        section("global-context", "O contexto do lançamento", "LST gratuito 17-18 de setembro (sobrepõe a TGS), acesso antecipado do Founder's Pack em 30 de setembro, lançamento free-to-play em 5 de outubro. TGS = primeiro contato público japonês."),
        section("what-it-means", "O que isso significa", "Na TGS, teste nos seis estandes; se não, o LST quatro dias depois é a via gratuita. O padrão de hardware aponta para marketing performance-first (UE5, DLSS) para cada região de PC."),
      ],
    }),
    ru: articleCopy(newsLabels, "ru", 5, {
      eyebrow: "TGS 2026",
      title: "Глобальный Aion 2 играбелен на 6 стендах железа на TGS 2026: BenQ, ASUS ROG, MSI, Lenovo и другие до 5 октября",
      description: "Глобальный Aion 2 делает первые публичные хендс-оны в Японии на TGS 2026 на шести стендах железа — BenQ, ASUS ROG, Sofmap, Crowxis·CFD Sales, MSI, Lenovo — пока стенд NC показывает Astraea Oratio",
      intro: "NCsoft подтверждает: глобальный Aion 2 будет играбелен на Tokyo Game Show 2026 на шести стендах производителей железа — BenQ, ASUS ROG, Sofmap, Crowxis·CFD Sales, MSI и Lenovo. Хендс-оны дают японским игрокам первый публичный контакт до запуска 5 октября; стенд NC показывает Astraea Oratio.",
      sourceNote: "На основе отчёта GameVu от 10 сентября 2026 г. (получен 12 сентября 2026 г.). Список объявлен через официальные SNS NC; возможны изменения планировки TGS.",
      keywords: ["Aion 2 TGS 2026 хендс-он", "Aion 2 Tokyo Game Show стенд железа", "Aion 2 демо BenQ ASUS ROG MSI Lenovo", "Aion 2 играбельно Япония 5 октября", "Aion 2 TGS Astraea Oratio стенд"],
      sections: [
        section("tgs-plan", "TGS 2026: играбельно, без своего стенда", "Глобальный Aion 2 будет играбелен на TGS 2026, но без отдельного стенда: демо идут на шести стендах железа, объявленных через официальные SNS NC. Одно своё место обменяно на шесть потоков посетителей."),
        section("six-booths", "Шесть стендов", "BenQ, ASUS ROG, Sofmap, Crowxis·CFD Sales, MSI и Lenovo. UE5 + высокое разрешение = идеальная демонстрация для мониторов/ПК; билд опирается на подтверждённую базу DLSS 4.5."),
        section("why-hardware", "Почему стенды железа", "Главная площадь NC на TGS 2026 отдана Astraea Oratio (отдельный стенд, первое играбельное демо). Разнести Aion 2 по стендам железа — эффективная пространственная стратегия и растущий паттерн коллабораций игра × железо."),
        section("global-context", "Контекст запуска", "Бесплатный LST 17–18 сентября (пересекается с TGS), ранний доступ Founder's Pack 30 сентября, free-to-play запуск 5 октября. TGS — первый публичный контакт в Японии."),
        section("what-it-means", "Что это значит", "На TGS — пробуйте на шести стендах; иначе LST через четыре дня — бесплатный путь к тому же билду. Паттерн железа намекает на маркетинг performance-first (UE5, DLSS) для каждой PC-региона."),
      ],
    }),
    ko: articleCopy(newsLabels, "ko", 5, {
      eyebrow: "TGS 2026",
      title: "아이온2 글로벌, TGS 2026에서 하드웨어 6개 부스에서 시연——벤큐·ASUS ROG·MSI·레노버 등, 10월 5일 출시 전",
      description: "아이온2 글로벌이 TGS 2026에서 하드웨어 업체 부스 6곳(벤큐, 에이수스 ROG, 소프맵, 크로우시스·CFD판매, MSI, 레노버)에서 첫 일본 공개 시연을 진행합니다; NC 자체 부스는 아스트라에 오라티오",
      intro: "엔씨소프트가 아이온2 글로벌을 도쿄게임쇼(TGS 2026)에서 하드웨어 6개 업체 부스(벤큐, 에이수스 ROG, 소프맵, 크로우시스·CFD판매, MSI, 레노버)에서 시연한다고 확인했습니다. 10월 5일 글로벌 출시 전, 일본 플레이어에게 첫 공개 접점이 되는 자리이며, NC 자체 TGS 부스는 서브컬처 신작 '아스트라에 오라티오'입니다.",
      sourceNote: "게임뷰 2026년 9월 10일자 보도(2026-09-12 확인)를 기반으로 했습니다. 부스 목록은 NC 공식 SNS 발표분이며, TGS 현장 구성에 따라 달라질 수 있습니다.",
      keywords: ["아이온2 TGS 2026 시연", "아이온2 도쿄게임쇼 하드웨어 부스", "아이온2 벤큐 ASUS ROG MSI 레노버 데모", "아이온2 일본 시연 10월5일", "아이온2 TGS 아스트라에 오라티오 부스"],
      sections: [
        section("tgs-plan", "TGS 2026: 시연은 있지만 단독 부스는 없음", "엔씨는 아이온2 글로벌을 TGS 2026에서 시연 가능하게 한다고 확인했지만, 아이온2 단독 부스는 내지 않습니다. 대신 하드웨어 6개 업체 부스 안에서 핸즈온을 제공하며, 목록은 NC 공식 SNS로 발표됐습니다.", "자체 공간 하나를 여섯 갈래의 관람객 동선과 맞바꾸는 방식입니다: 각 하드웨어 파트너는 자사 모니터·PC·주변기기를 실제 게임으로 선보이고, 아이온2는 출시 전에 일본 플레이어에게 다가갑니다."),
        section("six-booths", "하드웨어 6개 부스", "확인된 부스 파트너는 벤큐, 에이수스 ROG, 소프맵, 크로우시스·CFD판매, MSI, 레노버입니다.", "아이온2는 Unreal Engine 5 기반의 고해상도·고품질 그래픽——게이밍 모니터·PC 업체의 성능 시연에 자연스럽게 어울립니다. 데모 빌드는 글로벌 빌드에 확인된 DLSS 4.5 기준을 활용할 것으로 예상됩니다."),
        section("why-hardware", "왜 하드웨어 부스인가", "NC의 TGS 2026 주 전시 공간은 일본 시장을 겨냥한 서브컬처 RPG '아스트라에 오라티오'(단독 부스, 첫 플레이어블 데모)에 배정됐습니다.", "아이온2를 하드웨어 부스로 분산하는 것은 대형 전시회의 효율적인 공간 전략입니다: 두 번째 대형 부스를 만들지 않고도 여러 부스에서 노출을 얻고, 게임×하드웨어 연동 데모라는 업계의 커지는 패턴이기도 합니다."),
        section("global-context", "글로벌 출시 맥락", "TGS 시연은 아이온2 글로벌 출시 전 로드의 최신 지점입니다: 무료 규모 테스트(LST)는 9월 17-18일(TGS와 일정이 겹침), 파운더스 팩 선행 접속은 9월 30일, F2P 글로벌 출시는 10월 5일입니다.", "일본 플레이어에게 TGS는 첫 공개 접점이고, 다른 지역 플레이어에게는 NC가 출시 전 일본 관객을 적극 공략하고 있다는 신호로 읽힙니다."),
        section("what-it-means", "의미", "TGS에 간다면 6개 부스에서 직접 시연해 볼 수 있고, 못 간다면 전시 4일 뒤 시작되는 LST가 같은 빌드를 무료로 체험할 길입니다.", "하드웨어 협력 패턴은 NC의 글로벌 마케팅 방향도 암시합니다: Unreal Engine 5와 DLSS를 내세운 성능 우선 메시지로 각 지역의 PC 플레이어를 노린다는 뜻입니다."),
      ],
    }),
    "zh-hant": articleCopy(newsLabels, "zh-hant", 5, {
      eyebrow: "TGS 2026",
      title: "Aion 2 全球版在 TGS 2026 的 6 個硬體展位可試玩：BenQ、ASUS ROG、MSI、Lenovo 等——10 月 5 日首發前",
      description: "Aion 2 全球版在 TGS 2026 的 6 家硬體廠商展位提供首次日本公開試玩——BenQ、ASUS ROG、Sofmap、Crowxis·CFD Sales、MSI、Lenovo；NC 自家展台主推 Astraea Oratio",
      intro: "NCsoft 確認 Aion 2 全球版將在東京電玩展（TGS 2026）的 6 家硬體廠商展位提供試玩——BenQ、ASUS ROG、Sofmap、Crowxis·CFD Sales、MSI 與 Lenovo。這些試玩讓日本玩家在 10 月 5 日首發前首次公開接觸遊戲，而 NC 自家 TGS 展台展示的是其亞文化新作 Astraea Oratio。",
      sourceNote: "基於 게임뷰（GameVu）2026 年 9 月 10 日報導（2026-09-12 抓取）。展位名單經 NC 官方 SNS 公布；具體展位以 TGS 現場為準。",
      keywords: ["Aion 2 TGS 2026 試玩", "Aion 2 東京電玩展 硬體展位", "Aion 2 BenQ ASUS ROG MSI Lenovo 演示", "Aion 2 日本試玩 10月5日", "Aion 2 TGS Astraea Oratio 展台"],
      sections: [
        section("tgs-plan", "TGS 2026：可試玩 Aion 2，但無獨立展台", ["NCsoft 確認 Aion 2 全球版將在 TGS 2026 提供試玩——但沒有 Aion 2 獨立展台。取而代之，遊戲在 6 家硬體廠商展位內提供試玩，名單經 NC 官方 SNS 公布。", "這一做法用一個自有空間換取六條人流：每家硬體夥伴用真實遊戲展示其顯示器、PC 與周邊，而 Aion 2 在首發前觸達日本玩家。"]),
        section("six-booths", "六個硬體展位", ["確認的展位夥伴：BenQ、ASUS ROG、Sofmap、Crowxis·CFD Sales、MSI 與 Lenovo。", "Aion 2 基於 Unreal Engine 5，畫面為高解析度高效能——天然適合展示電競顯示器與 PC 效能。預計示範建置會依賴全球版已確認的 DLSS 4.5 基線。"]),
        section("why-hardware", "為何用硬體展位而非 NC 展台", ["NC 在 TGS 2026 的主展區留給面向日本市場的亞文化 RPG《Astraea Oratio》——獨立展台與首次試玩。", "把 Aion 2 拆到硬體展位是大型展會上的高效空間策略：廠商無需再付一個大型展台，就能在多個展位獲得曝光；遊戲×硬體的聯動演示也是行業成長中的模式。"]),
        section("global-context", "全球首發語境", ["TGS 試玩是 Aion 2 全球版首發前之路的最新一站：免費規模測試 9 月 17-18 日舉行（與 TGS 檔期重疊）、創辦人包搶先體驗 9 月 30 日開始、免費制全球首發 10 月 5 日。", "對日本玩家，TGS 是首個公開觸點；對其他人，這些演示同時是 NC 在首發前積極爭取日本受眾的訊號。"]),
        section("what-it-means", "意義", ["如果你在 TGS，六個硬體展位就是親手試玩的機會；如果不在，展會四天後的 LST 是體驗同一建置的免費途徑。", "硬體合作模式也暗示了 NC 的全球行銷打法：圍繞 Unreal Engine 5 與 DLSS 的效能優先話術，瞄準各地區的 PC 玩家。"]),
      ],
    }),
  },
};