import { articleCopy, guideLabels, localizations, publishedVerified, section } from "./trending-september-12-shared";
import type { ContentEntry, ContentHeroImage, ContentSource } from "./content-registry";

/* ARTICLE 4 — Aion 2 fair-play policy guide: piloting rules, macro rework, abuse enforcement, anti-autoplay design */

const gametocSource: ContentSource = {
  id: "gametoc-aion2-piloting-bans-2026-09-10",
  kind: "third-party",
  publisher: "GameToc (게임톡)",
  label: "Aion 2 Permanently Restricts 'Snowfield of Sorrow' Piloting Organizations",
  url: "https://www.gametoc.co.kr/news/articleView.html?idxno=111377",
  publishedAt: "2026-09-10",
  retrievedAt: "2026-09-12",
  verifiedAt: "2026-09-12",
  localizations: localizations({
    "zh-hans": "Aion 2 对『Snowfield of Sorrow』代练组织永久封禁",
    en: "Aion 2 Permanently Restricts 'Snowfield of Sorrow' Piloting Organizations",
    fr: "Aion 2 restreint définitivement les organisations de pilotage de « Snowfield of Sorrow »",
    de: "Aion 2 sperrt Piloten-Organisationen von „Snowfield of Sorrow“ dauerhaft",
    es: "Aion 2 restringe permanentemente a las organizaciones de pilotaje de «Snowfield of Sorrow»",
    ja: "Aion 2「Snowfield of Sorrow」の代行組織を永久利用制限",
    "pt-br": "Aion 2 restringe permanentemente organizações de pilotagem de 'Snowfield of Sorrow'",
    ru: "Aion 2 навсегда ограничивает организации по пилотингу «Snowfield of Sorrow»",
    ko: "아이온2 '비탄의 설원' 대리 게임 조직 영구 이용제한",
    "zh-hant": "Aion 2 對『Snowfield of Sorrow』代練組織永久封禁",
  }, "https://www.gametoc.co.kr/news/articleView.html?idxno=111377"),
};

const policySource: ContentSource = {
  id: "aion2-official-operation-policy-2026-07-31",
  kind: "official",
  publisher: "NC Corporation",
  label: "AION 2 Operation Policy (includes the piloting item added July 31, 2026)",
  url: "https://www.plaync.com/policy/operation/aion2/",
  publishedAt: "2026-07-31",
  retrievedAt: "2026-09-12",
  verifiedAt: "2026-09-12",
  localizations: localizations({
    "zh-hans": "AION 2 运营政策（含 2026-07-31 新增的代练条款）",
    en: "AION 2 Operation Policy (includes the piloting item added July 31, 2026)",
    fr: "Politique d'exploitation AION 2 (incluant l'item pilotage ajouté le 31 juillet 2026)",
    de: "AION-2-Betriebsrichtlinie (inkl. des am 31. Juli 2026 ergänzten Pilotierungs-Items)",
    es: "Política de operación de AION 2 (incluye el ítem de pilotaje añadido el 31 de julio de 2026)",
    ja: "AION 2 運営ポリシー（2026年7月31日追加の代行項目を含む）",
    "pt-br": "Política de operação do AION 2 (inclui o item de pilotagem adicionado em 31 de julho de 2026)",
    ru: "Операционная политика AION 2 (включая пункт о пилотинге, добавленный 31 июля 2026 г.)",
    ko: "AION 2 운영정책 (2026-07-31 신설된 대리 게임 항목 포함)",
    "zh-hant": "AION 2 營運政策（含 2026-07-31 新增的代練條款）",
  }, "https://www.plaync.com/policy/operation/aion2/"),
};

const fHero: ContentHeroImage = {
  src: "https://blogfiles.ncsoft.net/news/af7330da-4ff6-4b58-aece-400e6061a3be.jpg",
  width: 1200, height: 630,
  credit: "NC Corporation",
  sourceUrl: "https://aion2.plaync.com/en-us/",
  rights: "linked-official-media",
  translations: {
    "zh-hans": { alt: "Aion 2 公平竞技政策指南横幅", caption: "Aion 2 的公平竞技框架：代练条款（7/31 起商业组织化活动永久制裁）+ 首次执法（11 个代练组织封禁/9 个委托玩家 30 天）+ 宏重做与反自动玩法设计。" },
    en: { alt: "Aion 2 fair-play policy guide banner", caption: "Aion 2's fair-play framework: the piloting policy item (permanent sanctions for commercial organized activity since July 31), its first enforcement (11 organizations banned, 9 commissioners restricted 30 days), plus the macro rework and anti-autoplay design." },
    fr: { alt: "Bannière du guide de la politique fair-play d'Aion 2", caption: "Le cadre fair-play d'Aion 2 : l'item pilotage (sanctions permanentes pour activité commerciale depuis le 31 juillet), sa première application (11 organisations bannies, 9 commanditaires 30 jours), plus la refonte des macros et l'anti-autoplay." },
    de: { alt: "Banner zum Fair-Play-Leitfaden von Aion 2", caption: "Das Fair-Play-Gerüst von Aion 2: das Pilotierungs-Item (permanente Sanktionen für kommerzielle organisierte Aktivität seit 31. Juli), die erste Anwendung (11 Organisationen gesperrt, 9 Auftraggeber 30 Tage) sowie Makro-Überarbeitung und Anti-Autoplay." },
    es: { alt: "Banner de la guía de la política de juego limpio de Aion 2", caption: "El marco de juego limpio de Aion 2: el ítem de pilotaje (sanciones permanentes para actividad comercial organizada desde el 31 de julio), su primera aplicación (11 organizaciones baneadas, 9 comitentes 30 días), más la reforma de macros y el anti-autoplay." },
    ja: { alt: "Aion 2 フェアプレイポリシーガイドバナー", caption: "Aion 2のフェアプレイ体制：代行項目（7月31日以降、営利・組織的活動は永久制裁）、初の適用（代行組織11を制限、依頼9を30日）、マクロ改修と反自動操作設計。" },
    "pt-br": { alt: "Banner do guia da política fair-play do Aion 2", caption: "O framework fair-play do Aion 2: o item de pilotagem (sanções permanentes para atividade comercial organizada desde 31 de julho), sua primeira aplicação (11 organizações banidas, 9 comitentes 30 dias), além da reforma de macros e do anti-autoplay." },
    ru: { alt: "Баннер гайда по политике честной игры Aion 2", caption: "Каркас честной игры Aion 2: пункт о пилотинге (постоянные санкции за коммерческую организованную деятельность с 31 июля), первое применение (11 организаций забанены, 9 заказчиков на 30 дней), плюс переработка макросов и анти-автоплей." },
    ko: { alt: "Aion 2 페어플레이 정책 가이드 배너", caption: "아이온2의 페어플레이 체계: 대리 게임 항목(7/31 이후 영리·조직적 활동은 영구 제재), 첫 집행(대리 조직 11개 제한/위탁 9개 30일), 매크로 개편과 반자동 조작 설계까지." },
    "zh-hant": { alt: "Aion 2 公平競技政策指南橫幅", caption: "Aion 2 的公平競技框架：代練條款（7/31 起商業組織化活動永久制裁）+ 首次執法（11 個代練組織封禁/9 個委託玩家 30 天）+ 巨集重做與反自動玩法設計。" },
  },
};

export const trendingSeptember12Article4: ContentEntry = {
  section: "guides",
  slug: "aion-2-fair-play-policy-guide",
  schemaType: "Article",
  publishedAt: "2026-09-12",
  updatedAt: "2026-09-12",
  readingMinutes: 6,
  publication: publishedVerified,
  sources: [gametocSource, policySource],
  heroImage: fHero,
  related: [
    { kind: "content", section: "news", slug: "aion-2-piloting-crackdown-permanent-bans" },
    { kind: "content", section: "guides", slug: "aion-2-no-autoplay-anti-grind-design-guide" },
    { kind: "content", section: "guides", slug: "aion-2-snowfield-of-sorrow-first-clear-composition-guide" },
    { kind: "content", section: "news", slug: "aion-2-snowfield-of-sorrow-first-clear" },
  ],
  translations: {
    en: articleCopy(guideLabels, "en", 6, {
      eyebrow: "FAIR-PLAY GUIDE",
      title: "Aion 2 Fair-Play Policy Guide: Piloting Rules, Macro Enforcement, and What Gets You Banned",
      description: "How Aion 2's operation policy works after the first piloting crackdown: commercial piloting means permanent bans regardless of offense count, commissioning players get 30-day restrictions plus event disqualification, and the broader anti-macro/anti-autoplay framework",
      intro: "NCsoft's first piloting crackdown — 11 commercial boosting organizations permanently banned, 9 commissioning players restricted for 30 days — is the visible edge of Aion 2's fair-play policy. This guide explains the piloting rules, the macro and abuse enforcement around them, and what behavior actually gets accounts sanctioned.",
      sourceNote: "Based on GameToc's September 10, 2026 report and NCsoft's official Aion 2 operation policy (retrieved September 12, 2026). Policy applies to the Korean service; the global version launching October 5 operates under the same framework.",
      keywords: ["Aion 2 operation policy piloting", "Aion 2 what gets you banned", "Aion 2 macro policy enforcement", "Aion 2 anti-abuse rules", "Aion 2 fair play account sanctions"],
      sections: [
        section("piloting-rules", "The Piloting Rules: Permanent for Commercial Activity", ["Aion 2's operation policy added a piloting (대리 게임) item on July 31, after NC previewed a hard line during the June 30 livestream. The core rule: treating piloting as a business, or organizing and brokering it, triggers a permanent sanction regardless of offense count.", "Even commissioning the service is a violation — players who take the rewards and progression benefits while cooperating with a boosting org's account access face use restrictions (30 days in the first enforcement round) and lose event eligibility."]),
        section("the-crackdown", "The First Crackdown: What Got Banned", ["On September 10, two days after Snowfield of Sorrow opened, NC permanently restricted 11 characters belonging to commercial piloting organizations that cleared the raid for profit, and applied 30-day restrictions to 9 characters that commissioned the service.", "All 20 were also stripped of eligibility for the 'First Subjugation Glory: Snowfield of Sorrow' event — the first-clear race. The message: raid progress, especially the Void-pet race, is protected from paid carries."]),
        section("macro-abuse", "Macro and Abuse Enforcement", ["The piloting crackdown sits inside a broader anti-abuse program. NC has publicly reworked the macro structure that let damage come out of pure macro inputs, and warned that confirmed abuse is sanctioned without exception.", "The enforcement logic across all of these: sanctions weigh the act's content, repetition, organization, and impact on the service — one-off mistakes and organized businesses are treated very differently."]),
        section("anti-autoplay-design", "The Anti-Autoplay Design Backstop", ["The policy layer is reinforced by the game design itself: Aion 2's Korean service has no full-autoplay, and the global build confirms no daily/weekly content gates and PvP as optional — reducing the grind pressure that typically drives players toward piloting and bot services.", "That design is covered in the site's anti-grind design guide; enforcement and design together are the fair-play system."]),
        section("staying-safe", "How to Stay Safe", ["1. Do not buy raid clears — commissioning is itself a violation and voids your first-clear event eligibility; 2. Do not share account credentials with 'verification' services — cooperation with boosting orgs' account access is part of what triggered the 30-day bans; 3. Avoid macro-only rotation setups while the macro rework is in force; 4. For the global launch on October 5, expect the same policy and enforcement posture in the modified Season 1."]),
      ],
    }),
    "zh-hans": articleCopy(guideLabels, "zh-hans", 6, {
      eyebrow: "公平竞技指南",
      title: "Aion 2 公平竞技政策指南：代练条款、宏执法与什么会被封号",
      description: "首轮代练打击之后 Aion 2 运营政策的运作方式：商业代练无论次数一律永久封禁、委托玩家 30 天限制+事件资格剥夺，以及更广的反宏/反自动玩法框架",
      intro: "NCsoft 的首轮代练打击——11 个商业化提升组织被永久封禁、9 名委托玩家被处 30 天限制——是 Aion 2 公平竞技政策的可见边缘。本指南说明代练条款、围绕它的宏与滥用执法，以及什么行为会真正让账号被制裁。",
      sourceNote: "基于 게임톡（GameToc）2026 年 9 月 10 日报道与 NCsoft 官方 Aion 2 运营政策（2026-09-12 抓取）。政策适用于韩服；10 月 5 日上线的全球版在同一框架下运营。",
      keywords: ["Aion 2 运营政策 代练", "Aion 2 什么会被封号", "Aion 2 宏 政策 执法", "Aion 2 反滥用规则", "Aion 2 公平竞技 账号制裁"],
      sections: [
        section("piloting-rules", "代练条款：商业活动即永久", ["Aion 2 运营政策于 7 月 31 日新增「代练游戏」条款——此前 NC 在 6 月 30 日直播中预告强硬立场。核心规则：把代练当作营生、或组织化介绍代练，无论次数一律触发永久制裁。", "即使只是委托服务也是违规——获取通关奖励与成长收益、同时配合提升组织账号访问的玩家将面临使用限制（首轮执法为 30 天）并失去事件资格。"]),
        section("the-crackdown", "首轮执法：封了什么", ["9 月 10 日——Snowfield of Sorrow 开放两天后——NC 永久封禁了 11 个属于商业代练组织、代打副本获利 的角色，并对 9 个委托该服务的角色处 30 天限制。", "全部 20 个还被剥夺「Snowfield of Sorrow 最初讨伐的荣耀」首杀竞速事件资格。信息明确：副本进度，尤其是 Void 宠物竞速，受到保护。"]),
        section("macro-abuse", "宏与滥用执法", ["代练打击位于更广的反滥用计划之内。NC 已公开重做让纯宏输入也能打出伤害的宏结构，并警告确认滥用将无例外制裁。", "所有此类执法的共同逻辑：制裁会权衡行为内容、重复性、组织性与对服务的影响——一次性失误与组织化营生处理方式截然不同。"]),
        section("anti-autoplay-design", "反自动玩法设计兜底", ["政策层还有游戏设计本身的支撑：Aion 2 韩服无全自动玩法，全球版确认无日常/周常内容门槛且 PvP 可选——降低通常把玩家推向代练与挂机服务的刷取压力。", "该设计见本站反刷取设计指南；执法与设计共同构成公平竞技系统。"]),
        section("staying-safe", "如何避坑", ["1. 不要购买副本通关——委托本身就是违规，且会使首杀竞速事件资格作废；2. 不要向「验证」服务共享账号凭据——配合提升组织的账号访问正是触发 30 天封禁的因素之一；3. 在宏重做施行期间避免纯宏循环配置；4. 对 10 月 5 日全球首发，预期改良版 Season 1 采用同样的政策与执法姿态。"]),
      ],
    }),
    fr: articleCopy(guideLabels, "fr", 5, {
      eyebrow: "GUIDE FAIR-PLAY",
      title: "Guide de la politique fair-play d'Aion 2 : règles de pilotage, application des macros, ce qui fait bannir",
      description: "Comment fonctionne la politique d'exploitation d'Aion 2 après la première répression : le pilotage commercial mène au bannissement permanent quel que soit le nombre, les commanditaires prennent 30 jours plus la disqualification, et le cadre anti-macro/anti-autoplay",
      intro: "La première répression du pilotage — 11 organisations de boost commercial bannies, 9 commanditaires restreints 30 jours — est le bord visible de la politique fair-play d'Aion 2. Ce guide explique les règles, l'application des macros et ce qui sanctionne réellement les comptes.",
      sourceNote: "Basé sur le rapport de GameToc du 10 septembre 2026 et la politique d'exploitation officielle d'Aion 2 (récupérés le 12 septembre 2026). Politique coréenne ; le global du 5 octobre fonctionne sous le même cadre.",
      keywords: ["Aion 2 politique pilotage", "Aion 2 ce qui fait bannir", "Aion 2 politique macros", "Aion 2 règles anti-abuse", "Aion 2 sanctions comptes fair play"],
      sections: [
        section("piloting-rules", "Règles de pilotage : permanent pour l'activité commerciale", "Item « pilotage » ajouté le 31 juillet après la ligne dure du 30 juin : le pilotage comme métier, ou l'organisation/la revente, mène à une sanction permanente sans égard au nombre. Même commander est une violation (30 jours + perte d'éligibilité pour les commanditaires)."),
        section("the-crackdown", "La première répression", "Le 10 septembre : 11 personnages d'organisations commerciales bannis définitivement, 9 commanditaires 30 jours, tous privés de « Première gloire de subjugation » — le raid et sa course de pets Void sont protégés."),
        section("macro-abuse", "Macros et abus", "Refonte publique de la structure de macros qui laissait le DPS sortir de pures entrées ; abus confirmés sanctionnés sans exception. Logique : contenu, répétition, organisation, impact sur le service."),
        section("anti-autoplay-design", "Le backstop anti-autoplay", "Le design renforce la politique : pas de plein autoplay en Corée, et le global confirme l'absence de seuils quotidiens/hebdomadaires et le PvP optionnel — réduisant la pression qui pousse vers le pilotage et les bots."),
        section("staying-safe", "Comment rester safe", "1. N'achetez pas de clears ; 2. Ne partagez pas vos identifiants avec des services de « vérification » ; 3. Évitez les rotations 100 % macro ; 4. Attendez-vous à la même politique dans le global du 5 octobre."),
      ],
    }),
    de: articleCopy(guideLabels, "de", 5, {
      eyebrow: "FAIR-PLAY-LEITFADEN",
      title: "Fair-Play-Leitfaden für Aion 2: Pilotierungsregeln, Makro-Durchsetzung und was zu Sperren führt",
      description: "Wie die Betriebsrichtlinie von Aion 2 nach der ersten Piloten-Razzia funktioniert: kommerzielles Piloting = permanente Sperre egal wie oft, Auftraggeber 30 Tage plus Event-Disqualifikation, und das Anti-Makro/Anti-Autoplay-Gerüst",
      intro: "Die erste Piloten-Razzia — 11 kommerzielle Boosting-Organisationen dauerhaft gesperrt, 9 Auftraggeber für 30 Tage — ist die sichtbare Kante der Fair-Play-Politik von Aion 2. Dieser Leitfaden erklärt die Regeln, die Makro-Durchsetzung und was wirklich sanktioniert wird.",
      sourceNote: "Basierend auf dem GameToc-Bericht vom 10. September 2026 und der offiziellen Betriebsrichtlinie von Aion 2 (abgerufen am 12. September 2026). Politik für den koreanischen Dienst; Global (5. Oktober) unter demselben Rahmen.",
      keywords: ["Aion 2 Betriebsrichtlinie Pilotierung", "Aion 2 was sperrt", "Aion 2 Makro-Politik", "Aion 2 Anti-Abuse-Regeln", "Aion 2 Fair-Play Konten-Sanktionen"],
      sections: [
        section("piloting-rules", "Pilotierungsregeln: permanent für kommerzielle Aktivität", "Item „Pilotierung“ am 31. Juli ergänzt nach der harten Linie vom 30. Juni: Pilotieren als Geschäft oder organisierte Vermittlung = permanente Sanktion unabhängig von der Anzahl. Auch Beauftragen ist ein Verstoß (30 Tage + Event-Ausschluss)."),
        section("the-crackdown", "Die erste Razzia", "Am 10. September: 11 Charaktere kommerzieller Organisationen dauerhaft gesperrt, 9 Auftraggeber 30 Tage, alle ohne „Erste Unterwerfungs-Ehre“ — der Raid und sein Void-Pet-Rennen sind geschützt."),
        section("macro-abuse", "Makros und Abuses", "Öffentliche Überarbeitung der Makro-Struktur, die DPS aus reinen Makro-Eingaben erlaubte; bestätigte Abuses werden ausnahmslos sanktioniert. Logik: Inhalt, Wiederholung, Organisation, Auswirkung auf den Dienst."),
        section("anti-autoplay-design", "Das Anti-Autoplay-Backstop", "Das Design verstärkt die Politik: kein volles Autoplay in Korea, Global ohne Tages-/Wochen-Gates und optionales PvP — weniger Grind-Druck, der zu Pilotieren und Bots treibt."),
        section("staying-safe", "Sicher bleiben", "1. Keine Clears kaufen; 2. Zugangsdaten nicht mit „Verifizierungs“-Diensten teilen; 3. Reine Makro-Rotationen vermeiden; 4. Gleiche Politik im Global ab 5. Oktober erwarten."),
      ],
    }),
    es: articleCopy(guideLabels, "es", 5, {
      eyebrow: "GUÍA FAIR-PLAY",
      title: "Guía de la política de juego limpio de Aion 2: reglas de pilotaje, aplicación de macros y qué causa baneo",
      description: "Cómo funciona la política de operación de Aion 2 tras la primera represión: el pilotaje comercial implica baneo permanente sin importar el número, los comitentes reciben 30 días más descalificación, y el marco anti-macro/anti-autoplay",
      intro: "La primera represión del pilotaje — 11 organizaciones de boost comercial baneadas, 9 comitentes restringidos 30 días — es el borde visible de la política de juego limpio de Aion 2. Esta guía explica las reglas, la aplicación de macros y qué sanciona de verdad a las cuentas.",
      sourceNote: "Basado en el informe de GameToc del 10 de septiembre de 2026 y la política de operación oficial de Aion 2 (recuperados el 12 de septiembre de 2026). Política coreana; el global del 5 de octubre opera bajo el mismo marco.",
      keywords: ["Aion 2 política de pilotaje", "Aion 2 qué causa baneo", "Aion 2 política de macros", "Aion 2 reglas anti-abuso", "Aion 2 sanciones cuentas fair play"],
      sections: [
        section("piloting-rules", "Reglas de pilotaje: permanente para actividad comercial", "Ítem «pilotaje» añadido el 31 de julio tras la línea dura del 30 de junio: el pilotaje como negocio, o la organización/venta, lleva a sanción permanente sin importar el número. Incluso encargarlo es una violación (30 días + pérdida de elegibilidad)."),
        section("the-crackdown", "La primera represión", "El 10 de septiembre: 11 personajes de organizaciones comerciales baneados, 9 comitentes 30 días, todos sin «Primera gloria de subyugación» — el raid y su carrera de mascotas Void están protegidos."),
        section("macro-abuse", "Macros y abusos", "Reforma pública de la estructura de macros que dejaba salir DPS de puras entradas de macro; abusos confirmados sancionados sin excepción. Lógica: contenido, repetición, organización, impacto en el servicio."),
        section("anti-autoplay-design", "El respaldo anti-autoplay", "El diseño refuerza la política: sin autoplay pleno en Corea, y el global confirma sin límites diarios/semanales y PvP opcional — reduciendo la presión que empuja al pilotaje y a los bots."),
        section("staying-safe", "Cómo mantenerse a salvo", "1. No compres clears; 2. No compartas credenciales con servicios de «verificación»; 3. Evita rotaciones 100 % macro; 4. Espera la misma política en el global del 5 de octubre."),
      ],
    }),
    ja: articleCopy(guideLabels, "ja", 5, {
      eyebrow: "フェアプレイガイド",
      title: "Aion 2 フェアプレイポリシーガイド：代行ルール、マクロ取締、アカウント停止になる行為",
      description: "初の代行取り締まり後のAion 2運営ポリシー：営利代行は回数に関係なく永久制裁、依頼側は30日制限＋イベント資格剥奪、さらに反マクロ・反自動操作の枠組み",
      intro: "NCの初の代行取り締まり——営利ブースト組織11体を永久制限、依頼した9ユーザーを30日制限——はAion 2フェアプレイポリシーの見える端です。本ガイドは代行ルール、周辺のマクロ・不正取締、実際に制裁される行為を説明します。",
      sourceNote: "ゲームトーク2026年9月10日付報道とNC公式のAion 2運営ポリシー（2026-09-12取得）に基づきます。ポリシーは韓国サービス向け。10月5日開始のグローバルも同じ枠組みで運営されます。",
      keywords: ["Aion 2 運営ポリシー 代行", "Aion 2 停止になる行為", "Aion 2 マクロ ポリシー 取締", "Aion 2 不正対策ルール", "Aion 2 フェアプレイ アカウント制裁"],
      sections: [
        section("piloting-rules", "代行ルール：営利活動は永久", "Aion 2運営ポリシーは7月31日に「代行ゲーム」項目を追加しました（6月30日の配信で強硬方針を予告後）。核心：代行を生業とする、または組織的に紹介する行為は、回数に関係なく永久制裁です。依頼側も違反——報酬・成長利益を得てブースト組織のアカウントアクセスに協力したプレイヤーは利用制限（初回30日）とイベント資格剥奪を受けます。"),
        section("the-crackdown", "初の取り締まり：何が制限されたか", "9月10日——Snowfield of Sorrow実装の2日後——NCはレイドクリアを営利で代行した組織のキャラ11体を永久利用制限、依頼した9キャラに30日間の制限を適用しました。", "20体すべてが『최초 토벌의 영광: 비탄의 설원』（初クリアレース）の参加資格も剥奪。メッセージは明確です：レイド進行、特にVoidペットレースは有料キャリーから保護されます。"),
        section("macro-abuse", "マクロと不正の取締", "代行取り締まりはより広い不正対策プログラムの中にあります。NCは純マクロ入力でDPSが出ていた構造を公開改修し、確認された不正は例外なく制裁すると警告しています。制裁は行為の内容・反復性・組織性・サービスへの影響を総合判断します——一回限りのミスと組織的ビジネスは扱いがまったく異なります。"),
        section("anti-autoplay-design", "反自動操作設計の受け皿", "ポリシー層はゲーム設計自体が補強します：韓国サービスはフルオートプレイなし、グローバルは日次/週次ゲートなし・PvP任意を確認済み——代行やbotに走らせる要因となるグラインド圧を下げます。この設計は本サイトの反グラインド設計ガイドで解説済みで、取締と設計が一体でフェアプレイ体制を成します。"),
        section("staying-safe", "安全にプレイするには", "1. レイドクリアを購入しない——依頼自体が違反で、初クリアイベント資格を失います; 2. 「認証」サービスにアカウント情報を渡さない——ブースト組織のアカウントアクセスへの協力が30日制限の要因です; 3. マクロ改修が効いている間は純マクロ運用を避ける; 4. 10月5日のグローバルでも同じポリシーと姿勢を想定。"),
      ],
    }),
    "pt-br": articleCopy(guideLabels, "pt-br", 5, {
      eyebrow: "GUIA FAIR-PLAY",
      title: "Guia da política fair-play do Aion 2: regras de pilotagem, aplicação de macros e o que gera ban",
      description: "Como funciona a política de operação do Aion 2 após a primeira repressão: pilotagem comercial implica ban permanente independentemente do número, comitentes recebem 30 dias mais desclassificação, e o framework anti-macro/anti-autoplay",
      intro: "A primeira repressão à pilotagem — 11 organizações de boost comercial banidas, 9 comitentes restringidos por 30 dias — é a borda visível da política fair-play do Aion 2. Este guia explica as regras, a aplicação de macros e o que realmente sanciona contas.",
      sourceNote: "Baseado no relatório da GameToc de 10 de setembro de 2026 e na política de operação oficial do Aion 2 (recuperados em 12 de setembro de 2026). Política coreana; o global de 5 de outubro opera sob o mesmo framework.",
      keywords: ["Aion 2 política de pilotagem", "Aion 2 o que gera ban", "Aion 2 política de macros", "Aion 2 regras anti-abuso", "Aion 2 sanções de contas fair play"],
      sections: [
        section("piloting-rules", "Regras de pilotagem: permanente para atividade comercial", "Item «pilotagem» adicionado em 31 de julho após a linha dura de 30 de junho: pilotar como negócio, ou organizar/revender, leva a sanção permanente independentemente do número. Até contratar é violação (30 dias + perda de elegibilidade)."),
        section("the-crackdown", "A primeira repressão", "Em 10 de setembro: 11 personagens de organizações comerciais banidos, 9 comitentes 30 dias, todos sem «Primeira glória de subjugação» — o raid e sua corrida de mascotes Void estão protegidos."),
        section("macro-abuse", "Macros e abusos", "Reforma pública da estrutura de macros que deixava o DPS sair de puros inputs; abusos confirmados sancionados sem exceção. Lógica: conteúdo, repetição, organização, impacto no serviço."),
        section("anti-autoplay-design", "O respaldo anti-autoplay", "O design reforça a política: sem autoplay pleno na Coreia, e o global confirma sem limites diários/semanais e PvP opcional — reduzindo a pressão que leva à pilotagem e aos bots."),
        section("staying-safe", "Como se manter seguro", "1. Não compre clears; 2. Não compartilhe credenciais com serviços de «verificação»; 3. Evite rotações 100% macro; 4. Espere a mesma política no global de 5 de outubro."),
      ],
    }),
    ru: articleCopy(guideLabels, "ru", 5, {
      eyebrow: "ГАЙД ПО ЧЕСТНОЙ ИГРЕ",
      title: "Гайд по политике честной игры Aion 2: правила пилотинга, макросы, за что банят",
      description: "Как работает операционная политика Aion 2 после первой облавы: коммерческий пилотинг = постоянный бан независимо от числа, заказчики получают 30 дней плюс дисквалификацию, и анти-макро/анти-автоплей каркас",
      intro: "Первая облава на пилотинг — 11 коммерческих буст-организаций забанены, 9 заказчиков ограничены на 30 дней — видимый край политики честной игры Aion 2. Гайд объясняет правила, применение к макросам и что реально санкционирует аккаунты.",
      sourceNote: "На основе отчёта GameToc от 10 сентября 2026 г. и официальной операционной политики Aion 2 (получены 12 сентября 2026 г.). Политика корейская; глобал с 5 октября работает в том же каркасе.",
      keywords: ["Aion 2 политика пилотинга", "Aion 2 за что банят", "Aion 2 политика макросов", "Aion 2 анти-абуз правила", "Aion 2 санкции аккаунтов честная игра"],
      sections: [
        section("piloting-rules", "Правила пилотинга: коммерция = навсегда", "Пункт «пилотинг» добавлен 31 июля после жёсткой линии 30 июня: пилотинг как бизнес или организованная продажа = постоянная санкция независимо от числа. Даже заказ — нарушение (30 дней + потеря права)."),
        section("the-crackdown", "Первая облава", "10 сентября: 11 персонажей коммерческих организаций забанены, 9 заказчиков на 30 дней, все без «Первой славы покорения» — рейд и гонка питомцев Void защищены."),
        section("macro-abuse", "Макросы и абуз", "Публичная переработка макроструктуры, позволявшей ДПС из чистых макро-вводов; подтверждённые абузы санкционируются без исключений. Логика: содержание, повторяемость, организованность, влияние на сервис."),
        section("anti-autoplay-design", "Анти-автоплей как основа", "Дизайн усиливает политику: без полного автоплея в Корее, глобал — без ежедневных/еженедельных ограничений и с необязательным PvP — меньше гринд-давления, толкающего к пилотингу и ботам."),
        section("staying-safe", "Как оставаться в безопасности", "1. Не покупайте клиры; 2. Не делитесь учётными данными с «верификационными» сервисами; 3. Избегайте чисто макро-ротаций; 4. Ждите той же политики в глобале с 5 октября."),
      ],
    }),
    ko: articleCopy(guideLabels, "ko", 5, {
      eyebrow: "페어플레이 가이드",
      title: "아이온2 페어플레이 정책 가이드: 대리 게임 규칙, 매크로 단속, 정지되는 행동",
      description: "첫 대리 단속 이후 아이온2 운영정책의 작동 방식: 영리 대리는 횟수와 관계없이 영구 제재, 위탁 플레이어는 30일 제한+이벤트 자격 박탈, 그리고 반매크로·반자동 조작 프레임워크",
      intro: "NC의 첫 대리 단속——영리 부스팅 조직 11개 영구 제한, 위탁한 이용자 9개 30일 제한——은 아이온2 페어플레이 정책의 보이는 끝입니다. 이 가이드는 대리 규칙, 주변의 매크로·어뷰징 단속, 그리고 실제로 계정이 제재되는 행동을 설명합니다.",
      sourceNote: "게임톡 2026년 9월 10일자 보도와 NC 공식 아이온2 운영정책(2026-09-12 확인)을 기반으로 했습니다. 정책은 한국 서비스 대상이며, 10월 5일 출시되는 글로벌도 동일한 프레임워크로 운영됩니다.",
      keywords: ["아이온2 운영정책 대리", "아이온2 정지되는 행동", "아이온2 매크로 정책 단속", "아이온2 어뷰징 규칙", "아이온2 페어플레이 계정 제재"],
      sections: [
        section("piloting-rules", "대리 규칙: 영리 활동은 무조건 영구", "아이온2 운영정책은 7월 31일에 '대리 게임' 항목을 신설했습니다(6월 30일 라이브 방송에서 강경 대응을 예고한 뒤). 핵심 규칙: 대리를 업으로 삼거나 조직적으로 알선하면 차수와 관계없이 영구 제재입니다.", "위탁도 위반입니다——보상과 성장 이익을 취하면서 부스팅 조직의 계정 접속에 협조한 플레이어는 이용 제한(첫 집행에서는 30일)과 이벤트 자격 박탈을 받습니다."),
        section("the-crackdown", "첫 단속: 무엇이 제재됐나", "9월 10일——비탄의 설원 오픈 이틀 만에——NC는 레이드 클리어를 영리 목적으로 대행한 조직의 캐릭터 11개를 영구 이용제한하고, 서비스를 위탁한 캐릭터 9개에 30일 제한을 적용했습니다.", "20개 모두 '최초 토벌의 영광: 비탄의 설원' 첫 클리어 레이스 참여 권한도 박탈됐습니다. 메시지는 분명합니다: 레이드 진행, 특히 보이드 펫 레이스는 유료 캐리로부터 보호받습니다."),
        section("macro-abuse", "매크로와 어뷰징 단속", "대리 단속은 더 넓은 반어뷰징 프로그램 안에 있습니다. NC는 순수 매크로 입력만으로 딜이 나오던 구조를 공개적으로 손봤고, 확인된 어뷰징은 예외 없이 제재하겠다고 경고했습니다.", "이 모든 제재의 공통 논리는 행위의 내용·반복성·조직성·서비스 영향도를 종합 판단한다는 것입니다——일회성 실수와 조직적 영업은 다르게 취급됩니다."),
        section("anti-autoplay-design", "반자동 조작 설계의 받침대", "정책 층은 게임 설계 자체가 보강합니다: 한국 서비스는 풀 오토플레이가 없고, 글로벌은 일일/주간 게이트 없음·PvP 선택을 확인——대리와 봇 서비스로 몰리게 하는 그라인드 압력을 줄입니다.", "이 설계는 본 사이트의 반그라인드 설계 가이드에서 다루며, 단속과 설계가 함께 페어플레이 체계를 이룹니다."),
        section("staying-safe", "제재를 피하는 법", "1. 레이드 클리어를 구매하지 말 것——위탁 자체가 위반이고 첫 클리어 이벤트 자격을 무효화합니다; 2. '인증' 서비스에 계정 정보를 공유하지 말 것——부스팅 조직의 계정 접속 협조가 30일 제재의 요인이었습니다; 3. 매크로 개편이 적용되는 동안 순수 매크로 로테이션을 피할 것; 4. 10월 5일 글로벌에서도 같은 정책과 집행 기조를 기대하세요."),
      ],
    }),
    "zh-hant": articleCopy(guideLabels, "zh-hant", 5, {
      eyebrow: "公平競技指南",
      title: "Aion 2 公平競技政策指南：代練條款、巨集執法與什麼會被封號",
      description: "首輪代練打擊之後 Aion 2 營運政策的運作方式：商業代練無論次數一律永久封禁、委託玩家 30 天限制+事件資格剝奪，以及更廣的反巨集/反自動玩法框架",
      intro: "NCsoft 的首輪代練打擊——11 個商業化提升組織被永久封禁、9 名委託玩家被處 30 天限制——是 Aion 2 公平競技政策的可見邊緣。本指南說明代練條款、圍繞它的巨集與濫用執法，以及什麼行為會真正讓帳號被制裁。",
      sourceNote: "基於 게임톡（GameToc）2026 年 9 月 10 日報導與 NCsoft 官方 Aion 2 營運政策（2026-09-12 抓取）。政策適用於韓服；10 月 5 日上線的全球版在同一框架下營運。",
      keywords: ["Aion 2 營運政策 代練", "Aion 2 什麼會被封號", "Aion 2 巨集 政策 執法", "Aion 2 反濫用規則", "Aion 2 公平競技 帳號制裁"],
      sections: [
        section("piloting-rules", "代練條款：商業活動即永久", ["Aion 2 營運政策於 7 月 31 日新增「代練遊戲」條款——此前 NC 在 6 月 30 日直播中預告強硬立場。核心規則：把代練當作營生、或組織化介紹代練，無論次數一律觸發永久制裁。", "即使只是委託服務也是違規——獲取通關獎勵與成長收益、同時配合提升組織帳號存取的玩家將面臨使用限制（首輪執法為 30 天）並失去事件資格。"]),
        section("the-crackdown", "首輪執法：封了什麼", ["9 月 10 日——Snowfield of Sorrow 開放兩天後——NC 永久封禁了 11 個屬於商業代練組織、代打副本獲利 的角色，並對 9 個委託該服務的角色處 30 天限制。", "全部 20 個還被剝奪「Snowfield of Sorrow 最初討伐的榮耀」首殺競速事件資格。資訊明確：副本進度，尤其是 Void 寵物競速，受到保護。"]),
        section("macro-abuse", "巨集與濫用執法", ["代練打擊位於更廣的反濫用計畫之內。NC 已公開重做讓純巨集輸入也能打出傷害的巨集結構，並警告確認濫用將無例外制裁。", "所有此類執法的共同邏輯：制裁會權衡行為內容、重複性、組織性與對服務的影響——一次性失誤與組織化營生處理方式截然不同。"]),
        section("anti-autoplay-design", "反自動玩法設計兜底", ["政策層還有遊戲設計本身的支撐：Aion 2 韓服無全自動玩法，全球版確認無日常/週常內容門檻且 PvP 可選——降低通常把玩家推向代練與掛機服務的刷取壓力。", "該設計見本站反刷取設計指南；執法與設計共同構成公平競技系統。"]),
        section("staying-safe", "如何避坑", ["1. 不要購買副本通關——委託本身就是違規，且會使首殺競速事件資格作廢；2. 不要向「驗證」服務共享帳號憑據——配合提升組織的帳號存取正是觸發 30 天封禁的因素之一；3. 在巨集重做施行期間避免純巨集循環配置；4. 對 10 月 5 日全球首發，預期改良版 Season 1 採用同樣的政策與執法姿態。"]),
      ],
    }),
  },
};