import { articleCopy, localizations, newsLabels, publishedVerified, section } from "./trending-september-10-shared";
import type { ContentEntry, ContentHeroImage, ContentSource } from "./content-registry";

/* ARTICLE 1 — Aion 2's hardest Sanctuary 'Snowfield of Sorrow' (비탄의 설원) was first-cleared in 4h16m on day one (Sep 9 KST) */

const gametokSource: ContentSource = {
  id: "gametok-snowfield-first-clear-2026-09-09",
  kind: "third-party",
  publisher: "GameToc (게임톡)",
  label: "Aion 2: 'Snowfield of Sorrow' First-Cleared Within 4 Hours",
  url: "https://v.daum.net/v/20260909150237053",
  publishedAt: "2026-09-09",
  retrievedAt: "2026-09-10",
  verifiedAt: "2026-09-10",
  localizations: localizations({
    "zh-hans": "Aion 2：『Snowfield of Sorrow』4 小时内被首杀",
    en: "Aion 2: 'Snowfield of Sorrow' First-Cleared Within 4 Hours",
    fr: "Aion 2 : « Snowfield of Sorrow » vaincu en moins de 4 heures",
    de: "Aion 2: „Snowfield of Sorrow“ in unter 4 Stunden erstgecleart",
    es: "Aion 2: 'Snowfield of Sorrow' superado en menos de 4 horas",
    ja: "Aion 2：「Snowfield of Sorrow」が4時間足らずで初クリア",
    "pt-br": "Aion 2: 'Snowfield of Sorrow' zerado em menos de 4 horas",
    ru: "Aion 2: «Snowfield of Sorrow» пройден менее чем за 4 часа",
    ko: "아이온2: '비탄의 설원' 4시간 만에 최초 격파",
    "zh-hant": "Aion 2：『Snowfield of Sorrow』4 小時內被首殺",
  }, "https://v.daum.net/v/20260909150237053"),
};

const ncOfficialSource: ContentSource = {
  id: "nc-official-a2-update-2026-09-09",
  kind: "official",
  publisher: "NC Corporation",
  label: "NC's AION 2: New Sanctuary 'Snowfield of Sorrow' Update (Press Release)",
  url: "https://about.ncsoft.com/news/article/A2_update_20260909",
  publishedAt: "2026-09-09",
  retrievedAt: "2026-09-10",
  verifiedAt: "2026-09-10",
  localizations: localizations({
    "zh-hans": "NC 的 AION 2：新 Sanctuary「Snowfield of Sorrow」更新（新闻稿）",
    en: "NC's AION 2: New Sanctuary 'Snowfield of Sorrow' Update (Press Release)",
    fr: "AION 2 de NC : mise à jour du Sanctuary « Snowfield of Sorrow » (communiqué)",
    de: "NCs AION 2: Update „Snowfield of Sorrow“ (Pressemitteilung)",
    es: "AION 2 de NC: actualización del Santuario «Snowfield of Sorrow» (nota de prensa)",
    ja: "NCのAION 2：新サンクチュアリ「Snowfield of Sorrow」アップデート（プレスリリース）",
    "pt-br": "AION 2 da NC: atualização do Santuário 'Snowfield of Sorrow' (comunicado)",
    ru: "AION 2 от NC: обновление Святилища «Snowfield of Sorrow» (пресс-релиз)",
    ko: "엔씨 AION 2: 신규 성역 '비탄의 설원' 업데이트 (보도자료)",
    "zh-hant": "NC 的 AION 2：新 Sanctuary「Snowfield of Sorrow」更新（新聞稿）",
  }, "https://about.ncsoft.com/news/article/A2_update_20260909"),
};

const invenSource: ContentSource = {
  id: "inven-snowfield-sorrow-25730-2026-09-08",
  kind: "third-party",
  publisher: "Inven Global",
  label: "'Aion 2' Adds Highest-Difficulty Sanctuary 'Snowfield of Sorrow'",
  url: "https://www.invenglobal.com/articles/25730/aion-2-adds-highest-difficulty-sanctuary-snowfield-of-sorrow",
  publishedAt: "2026-09-08",
  retrievedAt: "2026-09-10",
  verifiedAt: "2026-09-10",
  localizations: localizations({
    "zh-hans": "『Aion 2』新增最高难度 Sanctuary『Snowfield of Sorrow』",
    en: "'Aion 2' Adds Highest-Difficulty Sanctuary 'Snowfield of Sorrow'",
    fr: "« Aion 2 » ajoute le Sanctuary « Snowfield of Sorrow » de plus haute difficulté",
    de: "„Aion 2“ fügt Sanctuary „Snowfield of Sorrow“ mit höchster Schwierigkeit hinzu",
    es: "«Aion 2» añade el Santuario «Snowfield of Sorrow» de máxima dificultad",
    ja: "『Aion 2』に最高難度サンクチュアリ「Snowfield of Sorrow」追加",
    "pt-br": "'Aion 2' adiciona o Santuário 'Snowfield of Sorrow' de maior dificuldade",
    ru: "«Aion 2» добавляет Святилище «Snowfield of Sorrow» высшей сложности",
    ko: "'아이온2' 최고 난도 성역 '비탄의 설원' 추가",
    "zh-hant": "『Aion 2』新增最高難度 Sanctuary『Snowfield of Sorrow』",
  }, "https://www.invenglobal.com/articles/25730/aion-2-adds-highest-difficulty-sanctuary-snowfield-of-sorrow"),
};

const fcHero: ContentHeroImage = {
  src: "https://blogfiles.ncsoft.net/news/af7330da-4ff6-4b58-aece-400e6061a3be.jpg",
  width: 1200, height: 630,
  credit: "NC Corporation",
  sourceUrl: "https://aion2.plaync.com/en-us/",
  rights: "linked-official-media",
  translations: {
    "zh-hans": { alt: "Aion 2 Snowfield of Sorrow 首杀新闻横幅", caption: "韩服 9 月 9 日上线的最难 Sanctuary「Snowfield of Sorrow」在维护结束约 4 小时 16 分后即被 10 人队首杀（Hard 难度）；开发团队原预期 5-6 小时。" },
    en: { alt: "Aion 2 Snowfield of Sorrow first-clear news banner", caption: "The hardest Sanctuary 'Snowfield of Sorrow', live in Korea on September 9, was first-cleared on Hard by a 10-player group about 4 hours 16 minutes after maintenance ended — faster than the 5-6 hours the dev team had expected." },
    fr: { alt: "Bannière d'actualité du premier clear de Snowfield of Sorrow d'Aion 2", caption: "Le Sanctuary « Snowfield of Sorrow », le plus difficile, lancé en Corée le 9 septembre, a été vaincu en Hard par un groupe de 10 joueurs environ 4 h 16 après la fin de la maintenance — plus vite que les 5-6 h attendues." },
    de: { alt: "News-Banner zum Erster-Clear von Snowfield of Sorrow in Aion 2", caption: "Das schwerste Sanctuary „Snowfield of Sorrow“ (Korea, 9. September) wurde auf Hard von einer 10-Spieler-Gruppe rund 4 h 16 min nach Wartungsende erstgecleart — schneller als die erwarteten 5-6 Stunden." },
    es: { alt: "Banner de noticias del primer clear de Snowfield of Sorrow de Aion 2", caption: "El Santuario más difícil, «Snowfield of Sorrow», lanzado en Corea el 9 de septiembre, fue superado en Hard por un grupo de 10 jugadores unas 4 h 16 min tras el mantenimiento — más rápido de lo esperado (5-6 h)." },
    ja: { alt: "Aion 2 Snowfield of Sorrow 初クリアニュースバナー", caption: "韓国で9月9日に実装された最高難度サンクチュアリ「Snowfield of Sorrow」は、メンテ終了から約4時間16分で10人編成によりHard初クリア——開発陣の想定（5〜6時間）より速い記録です。" },
    "pt-br": { alt: "Banner de notícias do primeiro clear de Snowfield of Sorrow do Aion 2", caption: "O Santuário mais difícil, 'Snowfield of Sorrow', lançado na Coreia em 9 de setembro, foi zerado no Hard por um grupo de 10 jogadores cerca de 4h16 após o fim da manutenção — mais rápido do que as 5-6h esperadas." },
    ru: { alt: "Баннер новостей о первом клире Snowfield of Sorrow в Aion 2", caption: "Труднейшее Святилище «Snowfield of Sorrow», вышедшее в Корее 9 сентября, было пройдено на Hard группой из 10 игроков примерно через 4 ч 16 мин после окончания работ — быстрее ожидаемых 5–6 часов." },
    ko: { alt: "Aion 2 비탄의 설원 최초 격파 뉴스 배너", caption: "9월 9일 한국 서버에 출시된 최고 난도 성역 '비탄의 설원'이 점검 종료 약 4시간 16분 만에 10인 공격대에 의해 Hard 최초 격파됐습니다——개발진 예상(5~6시간)보다 빠른 기록입니다." },
    "zh-hant": { alt: "Aion 2 Snowfield of Sorrow 首殺新聞橫幅", caption: "韓服 9 月 9 日上線的最難 Sanctuary「Snowfield of Sorrow」在維護結束約 4 小時 16 分後即被 10 人隊首殺（Hard 難度）；開發團隊原預期 5-6 小時。" },
  },
};

export const trendingSeptember10Article1: ContentEntry = {
  section: "news",
  slug: "aion-2-snowfield-of-sorrow-first-clear",
  schemaType: "NewsArticle",
  publishedAt: "2026-09-10",
  updatedAt: "2026-09-10",
  readingMinutes: 6,
  publication: publishedVerified,
  sources: [gametokSource, ncOfficialSource, invenSource],
  heroImage: fcHero,
  related: [
    { kind: "content", section: "news", slug: "aion-2-snowfield-of-grief-sanctuary-raid" },
    { kind: "content", section: "guides", slug: "aion-2-september-events-daeva-pass-guide" },
    { kind: "content", section: "guides", slug: "aion-2-seal-system-guide" },
    { kind: "content", section: "guides", slug: "aion-2-true-dragon-lord-gear-guide" },
  ],
  translations: {
    en: articleCopy(newsLabels, "en", 6, {
      eyebrow: "KOREA RACE RESULT",
      title: "Aion 2's Hardest Sanctuary 'Snowfield of Sorrow' First-Cleared in 4 Hours 16 Minutes on Day One",
      description: "Korea's first clear of the new Snowfield of Sorrow Sanctuary came about 4h16m after the September 9 maintenance ended — faster than the 5-6 hours the developers expected, with the Golden Void pet and title on the line",
      intro: "The 'Be the First to Lift the Chalice' race is already over for first place: Korea's first Hard clear of the new Snowfield of Sorrow Sanctuary was recorded at 14:16 KST on September 9 — roughly 4 hours and 16 minutes after maintenance ended at 10:00, and faster than the 5-6 hours the development team had predicted during the preview livestream.",
      sourceNote: "Based on GameToc's September 9, 2026 report (via Daum), NCsoft's official September 9 press release, and Inven Global's September 8 report on the update (all retrieved September 10, 2026). First-clear group and time reflect the Korean service.",
      keywords: ["Aion 2 Snowfield of Sorrow first clear", "Aion 2 비탄의 설원 first clear 4 hours", "Aion 2 Golden Void pet race", "Aion 2 Hard clear Hall of Fame", "Aion 2 September 9 raid race result"],
      sections: [
        section("race-result", "First Clear in 4 Hours 16 Minutes", ["The Snowfield of Sorrow Sanctuary opened with the September 9 maintenance in Korea, and the first Hard clear came at 14:16 KST — about 4 hours 16 minutes after servers came back at 10:00 KST.", "That beat the developers' own forecast: during the September 8 preview livestream they had expected the first clear to take 5-6 hours. The 10-player clear group is recorded in the new Hall of Fame with the clear date and roster."]),
        section("the-rewards", "What the First Force Earned", ["NCsoft's first-clear event rewards the first 20 forces that clear Hard: 1st place gets the 'Golden Void' pet and the title 'The First to Break the Sword of Extreme Cold and Chill', forces 2-5 get the 'Silver Void' pet, and forces 6-20 get the 'Bronze Void' pet.", "With first place now decided, the remaining Silver and Bronze Void rewards are still being contested by the forces racing through the raid."]),
        section("hall-of-fame", "The New Hall of Fame", ["The update adds a Hall of Fame that enshrines the 1st through 3rd forces to clear the dungeon, showing the clear date and the full attack-force roster.", "That makes the record permanent and verifiable server-wide — a fixture for the raiding community and a reference point for the raid's ongoing meta."]),
        section("entry-bar", "The Entry Bar: Up to Item Level 6,200", ["The raid scales its entry requirement by difficulty: 5,800 for Easy, 6,000 for Normal, and 6,200 for Hard — the highest PvE content bar in the game so far.", "A day-one Hard clear at that bar says a lot about how prepared the top Korean forces are, and it sets the expected item level for the global endgame curve."]),
        section("whats-next", "What's Next After the Race", ["The same livestream that previewed the raid also outlined upcoming Chapter 1 content: the 'Temple of Fire' expedition trial dungeon for item level 4,800+ players, and an auto-tuning feature for Soul Engraving that repeats until the target option is obtained.", "For global players, treat this race as a preview of the raiding cadence to expect: the October 5 launch ships a modified Season 1, and the content model confirmed earlier keeps Korea ahead by roughly three-month seasons."]),
      ],
    }),
    "zh-hans": articleCopy(newsLabels, "zh-hans", 6, {
      eyebrow: "韩服竞速结果",
      title: "Aion 2 最难副本『Snowfield of Sorrow』上线首日 4 小时 16 分即被首杀",
      description: "韩服新 Sanctuary「Snowfield of Sorrow」在 9 月 9 日维护结束后约 4 小时 16 分即被首杀（Hard）——比开发团队预期的 5-6 小时更快，黄金 Void 宠物与称号名花有主",
      intro: "「Be the First to Lift the Chalice」首杀竞速的头名已经决出：韩服 Snowfield of Sorrow 的首个 Hard 击杀记录于 9 月 9 日 14:16 KST——即 10:00 维护结束后的约 4 小时 16 分，比开发团队在预览直播中预测的 5-6 小时更快。",
      sourceNote: "基于 게임톡（GameToc）2026 年 9 月 9 日报道（经 Daum）、NCsoft 官方 9 月 9 日新闻稿与 Inven Global 9 月 8 日报道（均于 2026-09-10 抓取）。首杀队伍与时间针对韩服。",
      keywords: ["Aion 2 Snowfield of Sorrow 首杀", "Aion 2 泪之雪原 4小时首杀", "Aion 2 黄金 Void 宠物竞速", "Aion 2 Hard 名人堂", "Aion 2 9月9日竞速结果"],
      sections: [
        section("race-result", "4 小时 16 分首杀", ["Snowfield of Sorrow 随 9 月 9 日韩服维护上线，首个 Hard 击杀出现在 14:16 KST——即 10:00 KST 开服后约 4 小时 16 分。", "这一成绩快于开发团队的预测：在 9 月 8 日预览直播中，他们原本预期首杀需要 5-6 小时。10 人首杀队在新增的名人堂中留下了通关日期与完整名单。"]),
        section("the-rewards", "首杀队获得的奖励", ["NCsoft 的首杀活动奖励前 20 支通关 Hard 的队伍：第 1 名获得『黄金 Void』宠物与称号「최초로 혹한과 냉기의 검을 꺾은 자」（最早斩断严寒之剑者），第 2-5 名获得『白银 Void』宠物，第 6-20 名获得『青铜 Void』宠物。", "头名已定，剩余的白银/青铜 Void 仍在被竞速队伍争夺。"]),
        section("hall-of-fame", "新的名人堂", ["更新新增名人堂，永久记录第 1 至第 3 支通关队伍，显示通关日期与完整攻击队名单。", "这让记录全服可见且可查证——既是竞速社区的荣誉榜，也是副本后续 meta 的参照点。"]),
        section("entry-bar", "入场门槛：最高 6,200 装分", ["副本按难度分级入场要求：Easy 5,800、Normal 6,000、Hard 6,200——目前游戏中 PvE 内容最高门槛。", "首日即在该门槛完成 Hard 首杀，说明韩服顶级队伍的准备程度，也为全球版终局装分曲线设定了预期。"]),
        section("whats-next", "竞速之后", ["预告副本的同一直播还概述了 Chapter 1 后续：面向 4,800+ 装分玩家的「Temple of Fire」远征试炼副本，以及重复运行至目标选项出现的灵魂刻印自动调优功能。", "对全球玩家：把这场竞速视为未来副本节奏的预览——10 月 5 日上线为改良版 Season 1，此前确认的内容模型保持韩服领先约三个月一季。"]),
      ],
    }),
    fr: articleCopy(newsLabels, "fr", 6, {
      eyebrow: "RÉSULTAT CORÉE",
      title: "Le Sanctuary le plus difficile d'Aion 2, « Snowfield of Sorrow », vaincu en 4 h 16 dès le premier jour",
      description: "Le premier clear coréen du Sanctuary Snowfield of Sorrow est tombé ~4 h 16 après la fin de la maintenance du 9 septembre — plus vite que les 5-6 h attendues, avec le pet Void doré et le titre en jeu",
      intro: "La course « Be the First to Lift the Chalice » a déjà son vainqueur : le premier clear Hard coréen de Snowfield of Sorrow a été enregistré à 14:16 KST le 9 septembre — environ 4 h 16 après la fin de la maintenance à 10:00, plus vite que les 5-6 h prédites par l'équipe.",
      sourceNote: "Basé sur le rapport de GameToc du 9 septembre 2026 (via Daum), le communiqué officiel de NCsoft du 9 septembre et le rapport d'Inven Global du 8 septembre (récupérés le 10 septembre 2026).",
      keywords: ["Aion 2 Snowfield of Sorrow premier clear", "Aion 2 premier clear 4 heures", "Aion 2 pet Void doré", "Aion 2 Hall of Fame Hard", "Aion 2 course 9 septembre"],
      sections: [
        section("race-result", "Premier clear en 4 h 16", "Le Sanctuary Snowfield of Sorrow a ouvert avec la maintenance du 9 septembre ; le premier clear Hard est tombé à 14:16 KST, ~4 h 16 après l'ouverture à 10:00. Plus vite que les 5-6 h prédites par l'équipe lors du livestream du 8 septembre. Le groupe de 10 est inscrit au Hall of Fame."),
        section("the-rewards", "Ce que la première force a gagné", "Les 20 premières forces en Hard : 1re = pet « Void doré » + titre « Le premier à briser l'épée du froid extrême » ; 2-5 = « Void argenté » ; 6-20 = « Void bronze ». La 1re place est décidée ; l'argenté et le bronze restent à disputer."),
        section("hall-of-fame", "Le nouveau Hall of Fame", "Le Hall of Fame enregistre les forces 1 à 3, avec date de clear et liste complète — permanent et vérifiable pour toute la communauté."),
        section("entry-bar", "Le niveau d'équipement d'entrée", "Entrée par difficulté : 5 800 (Easy), 6 000 (Normal), 6 200 (Hard) — la barre PvE la plus haute du jeu. Un clear Hard le jour même en dit long sur la préparation des forces coréennes."),
        section("whats-next", "Et après la course ?", "Le même livestream a présenté la suite du Chapitre 1 : le donjon d'expédition « Temple of Fire » (niveau 4 800+), et l'auto-réglage de Soul Engraving répété jusqu'à l'option visée. Pour le global : la course est un aperçu de la cadence PvE ; lancement le 5 octobre en Saison 1 modifiée."),
      ],
    }),
    de: articleCopy(newsLabels, "de", 6, {
      eyebrow: "KOREA-RENNEN",
      title: "Das schwerste Sanctuary von Aion 2, „Snowfield of Sorrow“, am ersten Tag in 4 h 16 min erstgecleart",
      description: "Der koreanische Erster-Clear des neuen Snowfield-of-Sorrow-Sanctuarys kam ~4 h 16 min nach dem Wartungsende vom 9. September — schneller als die erwarteten 5-6 Stunden, mit Golden-Void-Pet und Titel",
      intro: "Das Rennen „Be the First to Lift the Chalice“ hat seinen Sieger: Der erste koreanische Hard-Clear von Snowfield of Sorrow wurde am 9. September um 14:16 KST verbucht — rund 4 h 16 min nach dem Ende der Wartung um 10:00, schneller als die 5-6 Stunden, die das Team im Livestream vorhergesagt hatte.",
      sourceNote: "Basierend auf dem GameToc-Bericht vom 9. September 2026 (via Daum), der offiziellen NCsoft-Pressemitteilung vom 9. September und dem Inven-Global-Bericht vom 8. September (abgerufen am 10. September 2026).",
      keywords: ["Aion 2 Snowfield of Sorrow Erster-Clear", "Aion 2 Erster-Clear 4 Stunden", "Aion 2 Golden Void Pet", "Aion 2 Hall of Fame Hard", "Aion 2 Rennen 9. September"],
      sections: [
        section("race-result", "Erster-Clear in 4 h 16 min", "Das Sanctuary Snowfield of Sorrow öffnete mit der Wartung am 9. September; der erste Hard-Clear kam um 14:16 KST, ~4 h 16 min nach Serverstart um 10:00. Schneller als die 5-6 Stunden, die das Team im Livestream am 8. September erwartet hatte. Die 10-Spieler-Gruppe steht in der Hall of Fame."),
        section("the-rewards", "Was die erste Force erhielt", "Die ersten 20 Forces auf Hard: 1. = „Golden Void“-Begleiter + Titel „Der Erste, der das Schwert der bitteren Kälte bricht“; 2-5 = „Silver Void“; 6-20 = „Bronze Void“. Platz 1 ist entschieden; Silber und Bronze sind noch umkämpft."),
        section("hall-of-fame", "Die neue Hall of Fame", "Die Hall of Fame verewigt die Forces 1-3 mit Clear-Datum und vollständiger Liste — dauerhaft und serverweit überprüfbar."),
        section("entry-bar", "Die Einstiegshürde", "Eintritt nach Schwierigkeit: 5 800 (Easy), 6 000 (Normal), 6 200 (Hard) — die höchste PvE-Hürde des Spiels. Ein Hard-Clear am ersten Tag zeigt die Vorbereitung der Top-Forces."),
        section("whats-next", "Was nach dem Rennen kommt", "Derselbe Livestream zeigte die nächsten Kapitel-1-Inhalte: das Expeditions-Trial „Temple of Fire“ (Stufe 4 800+) und die Auto-Tuning-Funktion für Soul Engraving. Für Global: der Start am 5. Oktober nutzt eine modifizierte Season 1; die PvE-Kadenz folgt Korea."),
      ],
    }),
    es: articleCopy(newsLabels, "es", 6, {
      eyebrow: "RESULTADO COREA",
      title: "El Santuario más difícil de Aion 2, «Snowfield of Sorrow», superado en 4 h 16 min el primer día",
      description: "El primer clear coreano del Santuario Snowfield of Sorrow llegó ~4 h 16 min tras el mantenimiento del 9 de septiembre — más rápido de lo esperado (5-6 h), con la mascota Void dorada y el título en juego",
      intro: "La carrera «Be the First to Lift the Chalice» ya tiene ganador: el primer clear coreano en Hard de Snowfield of Sorrow se registró a las 14:16 KST del 9 de septiembre — unas 4 h 16 min tras el fin del mantenimiento a las 10:00, más rápido de lo previsto (5-6 h).",
      sourceNote: "Basado en el informe de GameToc del 9 de septiembre de 2026 (vía Daum), la nota de prensa oficial de NCsoft del 9 de septiembre y el informe de Inven Global del 8 de septiembre (recuperados el 10 de septiembre de 2026).",
      keywords: ["Aion 2 Snowfield of Sorrow primer clear", "Aion 2 primer clear 4 horas", "Aion 2 mascota Void dorada", "Aion 2 Hall of Fame Hard", "Aion 2 carrera 9 septiembre"],
      sections: [
        section("race-result", "Primer clear en 4 h 16 min", "El Santuario Snowfield of Sorrow abrió con el mantenimiento del 9 de septiembre; el primer clear en Hard llegó a las 14:16 KST, ~4 h 16 min tras la apertura a las 10:00. Más rápido de lo previsto (5-6 h). El grupo de 10 está en el Salón de la Fama."),
        section("the-rewards", "Lo que ganó la primera fuerza", "Las 20 primeras fuerzas en Hard: 1.ª = mascota «Void dorado» + título «El primero en romper la espada del frío extremo»; 2-5 = «Void plateado»; 6-20 = «Void bronce». El 1.er puesto está decidido; plata y bronce siguen en disputa."),
        section("hall-of-fame", "El nuevo Salón de la Fama", "El Salón de la Fama registra las fuerzas 1-3 con fecha de clear y lista completa — permanente y verificable en todo el servidor."),
        section("entry-bar", "El requisito de entrada", "Entrada por dificultad: 5 800 (Easy), 6 000 (Normal), 6 200 (Hard) — la barra PvE más alta del juego. Un clear en Hard el primer día habla de la preparación de las fuerzas coreanas."),
        section("whats-next", "Qué viene después", "El mismo livestream mostró la continuación del Capítulo 1: la mazmorra de expedición «Temple of Fire» (nivel 4 800+) y el autoajuste de Soul Engraving. Para el global: la carrera es un adelanto de la cadencia PvE; lanzamiento el 5 de octubre con Temporada 1 modificada."),
      ],
    }),
    ja: articleCopy(newsLabels, "ja", 6, {
      eyebrow: "韓国レース結果",
      title: "Aion 2 最難関サンクチュアリ「Snowfield of Sorrow」、初日に4時間16分で初クリア",
      description: "韓国サーバーの新サンクチュアリ「Snowfield of Sorrow」は9月9日のメンテ終了から約4時間16分でHard初クリア——開発陣の想定（5〜6時間）より速く、ゴールデンボイドペットと称号の行方が確定",
      intro: "「Be the First to Lift the Chalice」レースの首位が確定しました：韓国サーバーでのSnowfield of Sorrow初のHardクリアは9月9日14:16 KST——10:00のメンテ終了から約4時間16分。プレビュー配信で開発陣が予想した5〜6時間より速い記録です。",
      sourceNote: "ゲームトーク（GameToc）2026年9月9日付報道（Daum経由）、NC公式9月9日付プレスリリース、Inven Global 9月8日付報道（いずれも2026-09-10取得）に基づきます。",
      keywords: ["Aion 2 Snowfield of Sorrow 初クリア", "Aion 2 初クリア 4時間", "Aion 2 ゴールデンボイドペット", "Aion 2 栄誉の殿堂 Hard", "Aion 2 9月9日レース結果"],
      sections: [
        section("race-result", "4時間16分で初クリア", "Snowfield of Sorrowは9月9日のメンテで実装され、最初のHardクリアは14:16 KST——10:00のオープンから約4時間16分。9月8日の配信で開発陣が予想した5〜6時間より速い記録です。10人編成の初クリア部隊は、新設の栄誉の殿堂にクリア日時・名簿とともに刻まれます。"),
        section("the-rewards", "初クリア部隊の報酬", "NCの初クリアイベントはHardをクリアした先着20部隊に報酬：1位は「ゴールデンボイド」ペットと称号「최초로 혹한과 냉기의 검을 꺾은 자」（最初に極寒の剣を折った者）、2-5位は「シルバーボイド」、6-20位は「ブロンズボイド」。1位は確定し、銀・銅はレース継続中です。"),
        section("hall-of-fame", "新設の栄誉の殿堂", "アップデートで栄誉の殿堂が追加され、クリアした1〜3位の部隊がクリア日時と完全な名簿とともに記録されます——サーバー全体に恒久的で検証可能な記録です。"),
        section("entry-bar", "入場条件：装備スコア最大6,200", "入場条件は難易度別：Easy 5,800、Normal 6,000、Hard 6,200——現行PvEで最高のハードルです。初日にこの水準でHardクリアした韓国トップ部隊の準備度がうかがえます。"),
        section("whats-next", "レースのその後", "同じ配信でChapter 1の続きも紹介：装備スコア4,800+向け遠征試練ダンジョン「Temple of Fire」、目標オプションが出るまで繰り返すソウル刻印オートチューニング。グローバルは10月5日、改良版シーズン1で開始し、このレースは今後のPvEペースのプレビューです。"),
      ],
    }),
    "pt-br": articleCopy(newsLabels, "pt-br", 6, {
      eyebrow: "RESULTADO COREIA",
      title: "O Santuário mais difícil do Aion 2, 'Snowfield of Sorrow', zerado em 4h16 no primeiro dia",
      description: "O primeiro clear coreano do Santuário Snowfield of Sorrow veio ~4h16 após o fim da manutenção de 9 de setembro — mais rápido do que as 5-6h esperadas, com o mascote Void dourado e o título em jogo",
      intro: "A corrida 'Be the First to Lift the Chalice' já tem vencedor: o primeiro clear coreano no Hard de Snowfield of Sorrow foi registrado às 14:16 KST de 9 de setembro — cerca de 4h16 após o fim da manutenção às 10:00, mais rápido do que as 5-6h previstas.",
      sourceNote: "Baseado no relatório da GameToc de 9 de setembro de 2026 (via Daum), no comunicado oficial da NCsoft de 9 de setembro e no relatório da Inven Global de 8 de setembro (recuperados em 10 de setembro de 2026).",
      keywords: ["Aion 2 Snowfield of Sorrow primeiro clear", "Aion 2 primeiro clear 4 horas", "Aion 2 mascote Void dourado", "Aion 2 Hall da Fama Hard", "Aion 2 corrida 9 setembro"],
      sections: [
        section("race-result", "Primeiro clear em 4h16", "O Santuário Snowfield of Sorrow abriu com a manutenção de 9 de setembro; o primeiro clear no Hard veio às 14:16 KST, ~4h16 após a abertura às 10:00. Mais rápido do que as 5-6h previstas. O grupo de 10 está no Hall da Fama."),
        section("the-rewards", "O que a primeira força ganhou", "As 20 primeiras forças no Hard: 1.ª = mascote 'Void dourado' + título 'O primeiro a quebrar a espada do frio extremo'; 2-5 = 'Void prata'; 6-20 = 'Void bronze'. O 1.º lugar está decidido; prata e bronze seguem em disputa."),
        section("hall-of-fame", "O novo Hall da Fama", "O Hall da Fama registra as forças 1-3 com data do clear e lista completa — permanente e verificável no servidor inteiro."),
        section("entry-bar", "O requisito de entrada", "Entrada por dificuldade: 5.800 (Easy), 6.000 (Normal), 6.200 (Hard) — a barreira PvE mais alta do jogo. Um clear no Hard no primeiro dia mostra a preparação das forças coreanas."),
        section("whats-next", "O que vem depois", "O mesmo livestream mostrou a continuação do Capítulo 1: a masmorra de expedição 'Temple of Fire' (nível 4.800+) e o autoajuste do Soul Engraving. Para o global: a corrida é uma prévia da cadência PvE; lançamento em 5 de outubro com Temporada 1 modificada."),
      ],
    }),
    ru: articleCopy(newsLabels, "ru", 6, {
      eyebrow: "РЕЗУЛЬТАТ КОРЕИ",
      title: "Труднейшее Святилище Aion 2 «Snowfield of Sorrow» пройдено за 4 ч 16 мин в первый день",
      description: "Первый корейский клир Святилища Snowfield of Sorrow случился через ~4 ч 16 мин после окончания работ 9 сентября — быстрее ожидаемых 5–6 часов, на кону были питомец Void Gold и титул",
      intro: "Гонка «Be the First to Lift the Chalice» уже определила победителя: первый корейский клир Snowfield of Sorrow на Hard зафиксирован в 14:16 KST 9 сентября — примерно через 4 ч 16 мин после окончания работ в 10:00, быстрее, чем предсказанные командой 5–6 часов.",
      sourceNote: "На основе отчёта GameToc от 9 сентября 2026 г. (через Daum), официального пресс-релиза NCsoft от 9 сентября и отчёта Inven Global от 8 сентября (получены 10 сентября 2026 г.).",
      keywords: ["Aion 2 Snowfield of Sorrow первый клир", "Aion 2 первый клир 4 часа", "Aion 2 питомец Void Gold", "Aion 2 Зал славы Hard", "Aion 2 гонка 9 сентября"],
      sections: [
        section("race-result", "Первый клир за 4 ч 16 мин", "Святилище Snowfield of Sorrow открылось с работами 9 сентября; первый клир на Hard случился в 14:16 KST, ~4 ч 16 мин после открытия в 10:00. Быстрее предсказанных 5–6 часов. Группа из 10 игроков увековечена в Зале славы."),
        section("the-rewards", "Что получила первая сила", "Первые 20 сил на Hard: 1-е = питомец «Void Gold» + титул «Первый, сломавший меч лютого холода»; 2–5 = «Void Silver»; 6–20 = «Void Bronze». Первое место определено; серебро и бронза ещё разыгрываются."),
        section("hall-of-fame", "Новый Зал славы", "Зал славы увековечивает силы 1–3 с датой клира и полным составом — постоянно и проверяемо для всего сервера."),
        section("entry-bar", "Порог входа", "Вход по сложности: 5 800 (Easy), 6 000 (Normal), 6 200 (Hard) — высочайший PvE-порог в игре. Клир на Hard в первый же день говорит о готовности топовых корейских сил."),
        section("whats-next", "Что дальше", "Тот же стрим показал продолжение Главы 1: экспедиционное испытание «Temple of Fire» (уровень 4 800+) и автоподстройку Soul Engraving. Для глобала: запуск 5 октября с модифицированным Сезоном 1; темп PvE следует за Кореей."),
      ],
    }),
    ko: articleCopy(newsLabels, "ko", 6, {
      eyebrow: "한국 레이스 결과",
      title: "아이온2 최고 난도 성역 '비탄의 설원', 첫날 4시간 16분 만에 최초 격파",
      description: "한국 서버의 신규 성역 '비탄의 설원'이 9월 9일 점검 종료 후 약 4시간 16분 만에 Hard 최초 격파됐습니다——개발진 예상(5~6시간)보다 빠른 기록이며, 골든 보이드 펫과 칭호 주인공이 결정됐습니다",
      intro: "'Be the First to Lift the Chalice' 레이스의 1위가 결정됐습니다: 한국 서버에서 비탄의 설원의 첫 Hard 격파는 9월 9일 14:16 KST——10:00 점검 종료 후 약 4시간 16분 만에 나왔습니다. 9월 8일 프리뷰 라이브 방송에서 개발진이 예상한 5~6시간보다 빠른 기록입니다.",
      sourceNote: "게임톡 2026년 9월 9일자 보도(Daum 경유), NC 공식 9월 9일자 보도자료, Inven Global 9월 8일자 보도(모두 2026-09-10 확인)를 기반으로 했습니다.",
      keywords: ["아이온2 비탄의 설원 최초 격파", "아이온2 첫 클리어 4시간", "아이온2 골든 보이드 펫", "아이온2 명예의 전당 Hard", "아이온2 9월 9일 레이스 결과"],
      sections: [
        section("race-result", "4시간 16분 만의 최초 격파", "비탄의 설원은 9월 9일 점검과 함께 문을 열었고, 첫 Hard 격파는 14:16 KST에 나왔습니다——10:00 KST 오픈 후 약 4시간 16분 만입니다.", "이는 9월 8일 프리뷰 라이브에서 개발진이 예상한 5~6시간보다 빠른 기록입니다. 10인 공격대는 신설된 명예의 전당에 격파 일시와 명단과 함께 기록됩니다."),
        section("the-rewards", "첫 격파 혈맹의 보상", "NC의 첫 클리어 이벤트는 Hard를 클리어한 선착 20개 포스에 보상을 지급합니다: 1위는 '펫: 황금빛 보이드'와 칭호 '최초로 혹한과 냉기의 검을 꺾은 자', 2~5위는 '펫: 은빛 보이드', 6~20위는 '펫: 구릿빛 보이드'.", "1위가 확정된 가운데, 은빛과 구릿빛 보이드는 아직 레이스를 달리는 혈맹들의 몫입니다."),
        section("hall-of-fame", "신설된 명예의 전당", "업데이트로 명예의 전당이 추가되어, 클리어에 성공한 1~3위 포스가 격파 일시와 공격대 전체 명단과 함께 영구 기록됩니다.", "서버 전체에 영구적이고 검증 가능한 기록으로 남아, 레이딩 커뮤니티의 영예의 장이자 레이드 메타의 기준점이 됩니다."),
        section("entry-bar", "입장 문턱: 최대 6,200", "난이도별 입장 요건: 쉬움 5,800 / 보통 6,000 / 어려움 6,200——현재 게임 내 PvE 콘텐츠 최고 수준의 문턱입니다.", "첫날 6,200 문턱에서 Hard를 클리어한 것은 한국 톱 포스들의 준비도를 보여주며, 글로벌 엔드게임 장비 곡선의 기준을 제시합니다."),
        section("whats-next", "레이스 이후", "같은 라이브 방송에서 Chapter 1 후속이 소개됐습니다: 장비 점수 4,800+ 대상 신규 원정 시련 던전 '불의 사원', 목표 옵션이 나올 때까지 반복하는 영혼 각인 오토 튜닝.", "글로벌 플레이어에게 이 레이스는 앞으로 맞이할 레이드 페이스의 프리뷰입니다. 10월 5일 글로벌은 수정판 시즌 1로 시작하며, 콘텐츠 모델상 한국이 약 3개월 주기로 앞서갑니다."),
      ],
    }),
    "zh-hant": articleCopy(newsLabels, "zh-hant", 6, {
      eyebrow: "韓服競速結果",
      title: "Aion 2 最難副本『Snowfield of Sorrow』上線首日 4 小時 16 分即被首殺",
      description: "韓服新 Sanctuary「Snowfield of Sorrow」在 9 月 9 日維護結束後約 4 小時 16 分即被首殺（Hard）——比開發團隊預期的 5-6 小時更快，黃金 Void 寵物與稱號名花有主",
      intro: "「Be the First to Lift the Chalice」首殺競速的頭名已經決出：韓服 Snowfield of Sorrow 的首個 Hard 擊殺記錄於 9 月 9 日 14:16 KST——即 10:00 維護結束後的約 4 小時 16 分，比開發團隊在預覽直播中預測的 5-6 小時更快。",
      sourceNote: "基於 게임톡（GameToc）2026 年 9 月 9 日報導（經 Daum）、NCsoft 官方 9 月 9 日新聞稿與 Inven Global 9 月 8 日報導（均於 2026-09-10 抓取）。首殺隊伍與時間針對韓服。",
      keywords: ["Aion 2 Snowfield of Sorrow 首殺", "Aion 2 淚之雪原 4小時首殺", "Aion 2 黃金 Void 寵物競速", "Aion 2 Hard 名人堂", "Aion 2 9月9日競速結果"],
      sections: [
        section("race-result", "4 小時 16 分首殺", ["Snowfield of Sorrow 隨 9 月 9 日韓服維護上線，首個 Hard 擊殺出現在 14:16 KST——即 10:00 KST 開服後約 4 小時 16 分。", "這一成績快於開發團隊的預測：在 9 月 8 日預覽直播中，他們原本預期首殺需要 5-6 小時。10 人首殺隊在新增的名人堂中留下了通關日期與完整名單。"]),
        section("the-rewards", "首殺隊獲得的獎勵", ["NCsoft 的首殺活動獎勵前 20 支通關 Hard 的隊伍：第 1 名獲得『黃金 Void』寵物與稱號「최초로 혹한과 냉기의 검을 꺾은 자」（最早斬斷嚴寒之劍者），第 2-5 名獲得『白銀 Void』寵物，第 6-20 名獲得『青銅 Void』寵物。", "頭名已定，剩餘的白銀/青銅 Void 仍在被競速隊伍爭奪。"]),
        section("hall-of-fame", "新的名人堂", ["更新新增名人堂，永久記錄第 1 至第 3 支通關隊伍，顯示通關日期與完整攻擊隊名單。", "這讓記錄全服可見且可查證——既是競速社區的榮譽榜，也是副本後續 meta 的參照點。"]),
        section("entry-bar", "入場門檻：最高 6,200 裝分", ["副本按難度分級入場要求：Easy 5,800、Normal 6,000、Hard 6,200——目前遊戲中 PvE 內容最高門檻。", "首日即在該門檻完成 Hard 首殺，說明韓服頂級隊伍的準備程度，也為全球版終局裝分曲線設定了預期。"]),
        section("whats-next", "競速之後", ["預告副本的同一直播還概述了 Chapter 1 後續：面向 4,800+ 裝分玩家的「Temple of Fire」遠征試煉副本，以及重複運行至目標選項出現的靈魂刻印自動調優功能。", "對全球玩家：把這場競速視為未來副本節奏的預覽——10 月 5 日上線為改良版 Season 1，此前確認的內容模型保持韓服領先約三個月一季。"]),
      ],
    }),
  },
};
