import { articleCopy, guideLabels, localizations, publishedVerified, section } from "./trending-august-27-shared";
import type { ContentEntry, ContentHeroImage, ContentSource } from "./content-registry";

/* ARTICLE 4 — Global version changes vs Korean release */

const globalChangesSource1: ContentSource = {
  id: "gamesbeat-global-build-2026-08-26",
  kind: "third-party", publisher: "GamesBeat",
  label: "NC promotes Aion 2 during Gamescom Opening Night Live ahead of Western early access launch",
  url: "https://gamesbeat.com/nc-promotes-aion-2-during-gamescom-opening-night-live-ahead-of-western-early-access-launch/",
  publishedAt: "2026-08-25",
  retrievedAt: "2026-08-26",
  verifiedAt: "2026-08-26",
  localizations: localizations({
    "zh-hans": "NC 在 Gamescom 开幕之夜现场推介 Aion 2（西服抢先体验前）",
    en: "NC promotes Aion 2 during Gamescom Opening Night Live ahead of Western early access launch",
    fr: "NC promeut Aion 2 à l'Opening Night Live de la Gamescom avant l'accès anticipé occidental",
    de: "NC bewirbt Aion 2 bei der Gamescom Opening Night Live vor dem West-Start des Early Access",
    es: "NC promociona Aion 2 durante el Opening Night Live de la Gamescom antes del acceso anticipado occidental",
    ja: "NC、Gamescom オープニングナイトライブで西側早期アクセス前の Aion 2 をアピール",
    "pt-br": "NC promove Aion 2 no Opening Night Live da Gamescom antes do acesso antecipado ocidental",
    ru: "NC продвигает Aion 2 на Opening Night Live Gamescom перед западным ранним доступом",
    ko: "NC, 서구 조기 접속 앞두고 Gamescom 오프닝 나이트 라이브에서 Aion 2 홍보",
    "zh-hant": "NC 在 Gamescom 開幕之夜現場推介 Aion 2（西服搶先體驗前）",
  }, "https://gamesbeat.com/nc-promotes-aion-2-during-gamescom-opening-night-live-ahead-of-western-early-access-launch/"),
};

const globalChangesSource2: ContentSource = {
  id: "mmoexp-global-tweak-2026-08-26",
  kind: "third-party", publisher: "MMOEXP",
  label: "AION 2 Weekly News: Global Launch Tweak, Marriage System, and Gamescom 2026 Reveals",
  url: "https://www.mmoexp.com/News/aion-2-weekly-news-global-launch-tweak-marriage-system-and-gamescom-2026-reveals.html",
  publishedAt: "2026-08-22",
  retrievedAt: "2026-08-26",
  verifiedAt: "2026-08-26",
  localizations: localizations({
    "zh-hans": "AION 2 每周新闻：全球发布调整、婚姻系统与 Gamescom 2026 披露",
    en: "AION 2 Weekly News: Global Launch Tweak, Marriage System, and Gamescom 2026 Reveals",
    fr: "Actualités hebdo AION 2 : ajustement du lancement mondial, système de mariage et révélations Gamescom 2026",
    de: "AION 2 Wochennews: Global-Launch-Anpassung, Hochzeitssystem und Gamescom-2026-Reveals",
    es: "Noticias semanales de AION 2: ajuste del lanzamiento global, sistema de matrimonio y revelaciones de Gamescom 2026",
    ja: "AION 2 ウィークリーニュース：グローバルローンチ調整、結婚システム、Gamescom 2026 の発表",
    "pt-br": "Notícias semanais do AION 2: ajuste do lançamento global, sistema de casamento e revelações da Gamescom 2026",
    ru: "Еженедельные новости AION 2: корректировка глобального запуска, система брака и откровения Gamescom 2026",
    ko: "AION 2 주간 뉴스: 글로벌 출시 조정, 결혼 시스템, Gamescom 2026 공개",
    "zh-hant": "AION 2 每週新聞：全球發布調整、婚姻系統與 Gamescom 2026 披露",
  }, "https://www.mmoexp.com/News/aion-2-weekly-news-global-launch-tweak-marriage-system-and-gamescom-2026-reveals.html"),
};

const globalChangesSource3: ContentSource = {
  id: "nc-official-global-changes-2026-08-26",
  kind: "official", publisher: "NC",
  label: "AION 2 Official Website — Dev Stream & Patch Notes",
  url: "https://aion2.plaync.com/ko-kr/board/notice",
  publishedAt: "2026-08-01",
  retrievedAt: "2026-08-26",
  verifiedAt: "2026-08-26",
  localizations: localizations({
    "zh-hans": "AION 2 官方网站——开发者直播与更新说明",
    en: "AION 2 Official Website — Dev Stream & Patch Notes",
    fr: "Site officiel AION 2 — stream des devs et notes de mise à jour",
    de: "AION 2 Offizielle Website — Dev-Stream & Patch-Notes",
    es: "Sitio web oficial de AION 2 — stream de desarrolladores y notas de parche",
    ja: "AION 2 公式サイト — 開発者ストリーム＆パッチノート",
    "pt-br": "Site oficial do AION 2 — transmissão de devs e notas de atualização",
    ru: "Официальный сайт AION 2 — стрим разработчиков и патчноуты",
    ko: "AION 2 공식 사이트 — 개발자 스트림 및 패치 노트",
    "zh-hant": "AION 2 官方網站——開發者直播與更新說明",
  }, "https://aion2.plaync.com/ko-kr/board/notice"),
};

const globalChangesHero: ContentHeroImage = {
  src: "https://blogfiles.ncsoft.net/news/af7330da-4ff6-4b58-aece-400e6061a3be.jpg",
  width: 1100, height: 605,
  credit: "NC Corporation",
  sourceUrl: "https://aion2.plaync.com/ko-kr/board/notice",
  rights: "linked-official-media",
  translations: {
    "zh-hans": { alt: "Aion 2 全球版改动指南配图", caption: "NC 官方配图；全球版基于韩版反馈调整了副本人数、战场、宠物上限等系统。" },
    en: { alt: "Aion 2 global version changes guide image", caption: "Official NC artwork; the global build adjusts dungeons, battlegrounds, pet caps, and more based on Korean feedback." },
    fr: { alt: "Image du guide des changements de la version mondiale d'Aion 2", caption: "Visuel officiel NC ; la version mondiale ajuste donjons, champs de bataille, quotas d'animaux et plus." },
    de: { alt: "Bild zum Guide zu den Änderungen der globalen Aion-2-Version", caption: "Offizielles NC-Artwork; die globale Version passt Dungeons, Schlachtfelder, Haustierlimits und mehr an." },
    es: { alt: "Imagen de la guía de cambios de la versión global de Aion 2", caption: "Arte oficial de NC; la versión global ajusta mazmorras, campos de batalla, límites de mascotas y más." },
    ja: { alt: "Aion 2 グローバル版変更ガイド画像", caption: "NC公式アートワーク；グローバル版は韓国版のフィードバックに基づきダンジョン・バトルグラウンド・ペット上限などを調整。" },
    "pt-br": { alt: "Imagem do guia de mudanças da versão global de Aion 2", caption: "Arte oficial da NC; a versão global ajusta masmorras, campos de batalha, limites de pets e mais." },
    ru: { alt: "Изображение гайда по изменениям глобальной версии Aion 2", caption: "Официальный арт NC; глобальная версия корректирует данжи, батлграунды, лимиты питомцев и другое." },
    ko: { alt: "Aion 2 글로벌 버전 변경 가이드 이미지", caption: "NC 공식 이미지입니다. 글로벌 버전은 한국 서버 피드백에 따라 던전, 배틀그라운드, 펫 상한 등을 조정합니다." },
    "zh-hant": { alt: "Aion 2 全球版改動指南配圖", caption: "NC 官方配圖；全球版基於韓版回饋調整了副本人數、戰場、寵物上限等系統。" },
  },
};

export const trendingAugust27Article4: ContentEntry = {
  section: "guides",
  slug: "aion-2-global-version-changes-guide",
  schemaType: "Article",
  publishedAt: "2026-08-26",
  updatedAt: "2026-08-26",
  readingMinutes: 6,
  publication: publishedVerified,
  sources: [globalChangesSource1, globalChangesSource2, globalChangesSource3],
  heroImage: globalChangesHero,
  related: [
    { kind: "content", section: "news", slug: "aion-2-first-global-dev-stream-recap" },
    { kind: "content", section: "news", slug: "global-quna-kinah-exchange-p2w-changes" },
    { kind: "content", section: "guides", slug: "global-launch-dungeon-raid-size-changes" },
    { kind: "content", section: "guides", slug: "aion-2-global-server-regions-guide" },
  ],
  translations: {
    en: articleCopy(guideLabels, "en", 6, {
      eyebrow: "GLOBAL VERSION",
      title: "Aion 2 Global Version: Every Confirmed Change vs the Korean Release",
      description: "The Aion 2 global build is not a copy of the Korean version — dungeons, raids, battlegrounds, pets, monetization, and membership were adjusted. Here is every confirmed difference before the September 30 early access.",
      intro: "NC has said it clearly since the August dev stream: the global version of Aion 2 is being adjusted based on feedback and lessons from the Korean and Taiwanese services, and it is not a direct copy of the existing build. For players deciding what to expect on September 30, this guide collects every confirmed global-specific change in one place, and marks what is still unannounced.",
      sourceNote: "Based on GamesBeat's coverage of the global build (August 25), MMOEXP's weekly report on the global launch adjustments (August 22), and official NC announcements and dev stream notes. Differences below are sourced; where something is reported rather than officially confirmed, it is marked.",
      keywords: ["Aion 2 global version changes", "Aion 2 vs Korea version", "Aion 2 global launch changes", "Aion 2 global build differences", "Aion 2 adjusted for the West"],
      sections: [
        section("why-different", "Why the Global Version Is Different", ["According to NC's own messaging, the global rollout incorporates feedback and lessons from the Korean and Taiwanese versions, which launched in November 2025. The studio has been communicating directly with international players — most visibly through the August 7 'Beyond the Abyss' dev stream — and has repeatedly emphasized that global will not simply mirror the Asian build.", "Two goals seem to drive this: smoothing the first-week experience for players new to the franchise, and normalizing competitive systems so that PvP feels fair regardless of spending. Both show up in the concrete changes below.", "Players transferring expectations from the KR/TW service should treat any KR mechanic as 'subject to change' until an official global notice confirms it."]),
        section("group-content", "Group Content: Dungeons & Raids", ["The global launch confirmed the biggest raid tier change since the Asian release: dungeon parties expand from 4 to 5 players, and the first raid tier expands from 8 to 10 players. This was announced at the August dev stream as a deliberate global adjustment.", "The change matters beyond the headcount: 5-player dungeons and a 10-player first raid change class composition math, dungeon mechanics tuning, and how guides and party finder presets are built. All existing global-facing dungeon advice on this site is written against these sizes.", "No other raid or dungeon group sizes have been announced to differ; treat the 4→5 and 8→10 changes as the complete list for now."]),
        section("pvp-battlegrounds", "PvP: Battleground Normalization", ["Battlegrounds standardize at 10v10 for the global version, with stats normalized — meaning gear and progression differences are flattened inside the mode so matches are decided by skill and team play rather than spending.", "This is a significant philosophical shift from parts of the Asian service, where progression gaps can carry into competitive modes. Combined with the Quna-to-Kinah exchange limit, it signals NC is designing the global PvP loop to be fairer by default.", "The open-world Abyss PvPvE zone remains the place where gear differences can still show; battleground norms and open-world rules are covered separately in our PvP guides."]),
        section("economy-membership", "Economy, Pets & Membership", ["The Quna-to-Kinah exchange is limited in the global version compared to Korea and Taiwan, reducing the pay-to-win ceiling for whaling on currency — a direct answer to the biggest criticism of the Asian services.", "Pet cap changes: the per-player pet cap was reduced in the global version, and the monthly Pet Auto-Loot Ticket cap applies in global too. Choose your main pet carefully, since auto-loot is gated by these tickets.", "Membership: all three Founder's Pack tiers include 30 days of Membership, retroactively applied to packs purchased since July 22 — and the monthly Membership subscription gates access to Market and Exchange features in the same way as planned for global."]),
        section("servers-launch", "Servers, Launch & What's Unannounced", ["Service regions are confirmed as North America, South America, Europe, and Japan, running five servers with no regional locks — one roster, one global community, and the freedom to play with friends across regions.", "Timing: early access starts September 30 for Founder's Pack owners, with the free-to-play opening expected around October 5 per press reports — NC has not yet confirmed the full-launch date or opening hour, nor the final server names.", "Also unannounced: preload timing, regional pricing details beyond the USD reference tiers, and whether any KR systems still under review (such as the reported marriage system) will ever reach global."]),
      ],
    }),
    "zh-hans": articleCopy(guideLabels, "zh-hans", 6, {
      eyebrow: "全球版",
      title: "Aion 2 全球版：与韩服相比的每一处已确认改动",
      description: "Aion 2 全球版并非韩服的复制——副本、团队本、战场、宠物、货币化与会员均经调整。以下是 9 月 30 日抢先体验前的全部已确认差异。",
      intro: "NC 自 8 月开发者直播起便明确表示：全球版将基于韩国与台湾服的经验与反馈进行调整，并非现有版本的直接复制。本指南汇总所有已确认的全球专属改动，并标出仍未公布的部分。",
      sourceNote: "基于 GamesBeat 对全球版的报道（8 月 25 日）、MMOEXP 关于全球发布调整的周报（8 月 22 日）及 NC 官方公告与开发者直播。已报道但未官方确认的内容已标注。",
      keywords: ["Aion 2 全球版改动", "Aion 2 韩服区别", "Aion 2 全球上线调整", "Aion 2 全球版差异", "Aion 2 西方特调"],
      sections: [
        section("why-different", "全球版为何不同", ["NC 表示全球部署吸收了 2025 年 11 月上线的韩国与台湾版的经验与反馈。工作室通过 8 月 7 日「Beyond the Abyss」开发者直播等渠道直接与国际玩家沟通，并反复强调全球版不会照搬亚洲版本。", "两个目标驱动了这些改动：平滑新玩家首周体验，以及规范化竞技系统让 PvP 不因投入高低而失衡。"]),
        section("group-content", "组队内容：副本与团队本", ["全球版确认了自亚洲版以来最大的团队规模调整：副本队伍由 4 人扩至 5 人，首个团队本由 8 人扩至 10 人。这是在 8 月开发者直播中公布的全球专属调整。", "规模变化不只是人数：5 人副本与 10 人团队本会改变职业构成与机制调校。本站所有面向全球的副本建议均按此人数编写。"]),
        section("pvp-battlegrounds", "PvP：战场属性平衡", ["全球版战场统一为 10v10 且属性平衡（stat-normalized）——模式内抹平装备与成长差距，胜负取决于操作与团队配合而非投入。", "这是与亚洲服务部分内容的重要理念差异。结合 Quna 兑换 Kinah 限制，说明 NC 正在把全球 PvP 设计得更公平。", "开放世界深渊 PvPvE 区域仍存在装备差距的影响，规则另见 PvP 指南。"]),
        section("economy-membership", "经济、宠物与会员", ["全球版限制了 Quna 兑换 Kinah 的额度，降低「氪金兑换货币」的上限——直接回应了亚洲服最大的批评点。", "宠物上限下调，每月宠物自动拾取券上限同样适用全球。请谨慎选择主力宠物。", "三个创始人包档位均含 30 天会员，自 7 月 22 日购买的包追溯适用；月度会员订阅在 Market 与 Exchange 功能的门槛上与全球版规划一致。"]),
        section("servers-launch", "服务器、上线时间与未公布事项", ["服务区域确认为北美、南美、欧洲与日本，共五台服务器且无区域锁定——同一个名册、同一个全球社群。", "时间：9 月 30 日创始人包持有者抢先体验，免费游玩预计 10 月 5 日开放（媒体报道，NC 未确认正式日期与开放时间，也未公布最终服务器名称）。", "尚未公布：预载时间、除美元参考价外的区域定价细节，以及仍在评估中的韩服系统（如报道中的婚姻系统）是否会登陆全球。"]),
      ],
    }),
    ko: articleCopy(guideLabels, "ko", 6, {
      eyebrow: "글로벌 버전",
      title: "Aion 2 글로벌 버전: 한국 서버와 다른 모든 확정 변경점",
      description: "Aion 2 글로벌 빌드는 한국 서버의 복사본이 아닙니다 — 던전, 레이드, 배틀그라운드, 펫, 과금 구조, 멤버십이 조정됐습니다. 9월 30일 조기 접속 전의 모든 확정 차이를 정리합니다.",
      intro: "NC는 8월 개발자 스트림부터 분명히 밝혔습니다: 글로벌 버전은 한국·대만 서비스의 피드백과 교훈에 따라 조정되며 기존 빌드의 직접 복사가 아닙니다. 확정된 글로벌 전용 변경을 한곳에 모으고 미발표 사항을 표시합니다.",
      sourceNote: "GamesBeat 보도(8/25), MMOEXP 주간 보고(8/22), NC 공식 발표·개발자 스트림 기반. 보도 수준의 내용은 별도 표기.",
      keywords: ["Aion 2 글로벌 버전 변경", "Aion 2 한국 서버 차이", "Aion 2 글로벌 출시 조정", "Aion 2 글로벌 빌드 차이", "Aion 2 서구 맞춤"],
      sections: [
        section("why-different", "글로벌 버전이 다른 이유", ["NC는 2025년 11월 출시된 한국·대만 서비스의 피드백과 교훈을 글로벌 롤아웃에 반영한다고 밝혔습니다. 8월 7일 'Beyond the Abyss' 개발자 스트림 등으로 국제 플레이어와 직접 소통 중입니다.", "두 목표가 보입니다: 신규 유저의 첫 주 경험 개선, 그리고 투자 여부와 무관하게 공정한 PvP를 위한 경쟁 시스템 정규화."]),
        section("group-content", "그룹 콘텐츠: 던전 & 레이드", ["글로벌 출시에서 아시아 출시 이후 최대 그룹 규모 변경이 확정됐습니다: 던전 파티 4→5인, 첫 레이드 8→10인. 8월 개발자 스트림에서 글로벌 전용 조정으로 발표됐습니다.", "인원 변화는 직업 구성과 메커니즘 튜닝까지 바꿉니다. 본 사이트의 모든 글로벌 던전 조언은 이 규모 기준입니다."]),
        section("pvp-battlegrounds", "PvP: 배틀그라운드 스탯 평준화", ["글로벌 버전 배틀그라운드는 10v10으로 통일되고 스탯이 평준화됩니다 — 장비와 성장 격차가 사라지고 실력과 팀워크로 승부가 갈립니다.", "Quna→Kinah 환전 제한과 함께 NC가 글로벌 PvP를 기본적으로 더 공정하게 설계하고 있음을 보여줍니다.", "오픈월드 심연 PvPvE 지역은 장비 격차가 여전히 작용할 수 있습니다. 규칙은 PvP 가이드를 참고하세요."]),
        section("economy-membership", "경제, 펫 & 멤버십", ["글로벌 버전은 Quna→Kinah 환전 한도를 제한해 과금으로 화폐를 얻는 상한을 낮췄습니다 — 아시아 서비스 최대 비판에 대한 직접적 답변입니다.", "플레이어당 펫 상한이 줄었고 월간 펫 자동 루팅 티켓 상한도 글로벌에 적용됩니다. 주력 펫을 신중히 고르세요.", "파운더스 팩 3종 모두 30일 멤버십 포함, 7월 22일 이후 구매분 소급 적용. 월간 멤버십은 Market·Exchange 접근 게이트로 작동합니다."]),
        section("servers-launch", "서버, 출시 & 미발표 사항", ["서비스 지역: 북미·남미·유럽·일본, 5개 서버에 지역 잠금 없음 — 하나의 명부, 하나의 글로벌 커뮤니티입니다.", "일정: 9월 30일 파운더스 팩 보유자 조기 접속, 무료 플레이 오픈은 보도상 10월 5일 전후 — NC는 정식 출시일·개시 시각·최종 서버명을 아직 미확정입니다.", "미발표: 사전 다운로드 시점, USD 참고가 외 지역별 가격, 보고된 결혼 시스템 등 검토 중인 한국 서버 시스템의 글로벌 도입 여부."]),
      ],
    }),
    ja: articleCopy(guideLabels, "ja", 6, {
      eyebrow: "グローバル版",
      title: "Aion 2 グローバル版：韓国版との確認済み変更点まとめ",
      description: "Aion 2 グローバル版は韓国版のコピーではありません — ダンジョン、レイド、バトルグラウンド、ペット、課金構造、メンバーシップが調整されています。9月30日の早期アクセス前の全確認済み差異をまとめます。",
      intro: "NC は8月の開発者ストリームから明確にしています：グローバル版は韓国・台湾サービスのフィードバックに基づき調整され、既存ビルドの直接コピーではないと。確認済みのグローバル専用変更を一箇所にまとめ、未発表事項も示します。",
      sourceNote: "GamesBeat の報道（8/25）、MMOEXP 週間報告（8/22）、NC 公式発表・開発者ストリームに基づきます。報道レベルの内容は別途表記。",
      keywords: ["Aion 2 グローバル版変更", "Aion 2 韓国版との違い", "Aion 2 グローバルローンチ調整", "Aion 2 グローバルビルド", "Aion 2 西側向け調整"],
      sections: [
        section("why-different", "グローバル版が異なる理由", "NC は2025年11月に始まった韓国・台湾サービスのフィードバックと教訓をグローバル展開に反映すると明言。8月7日の『Beyond the Abyss』ストリームなどを通じ国際プレイヤーと直接対話しています。"),
        section("group-content", "グループコンテンツ：ダンジョン＆レイド", "グローバル版でアジア版以降最大のグループ規模変更が確定：ダンジョン4→5人、最初のレイド8→10人。8月の開発者ストリームでグローバル専用調整として発表されました。"),
        section("pvp-battlegrounds", "PvP：バトルグラウンドのステータス平準化", "グローバル版のバトルグラウンドは10v10に統一されステータスが平準化 — 装備差が消え、スキルとチームワークで勝敗が決まります。Quna→Kinah 両替制限と合わせ、NC がより公平な PvP を設計している証拠です。"),
        section("economy-membership", "経済、ペット＆メンバーシップ", "グローバル版は Quna→Kinah 両替を制限し、課金で通貨を得る上限を引き下げました。ペット上限削減と月間ペット自動ルートチケット上限も適用。ファウンダーズパック3種に30日メンバーシップ込み（7月22日以降購入分も遡及）。"),
        section("servers-launch", "サーバー、リリース＆未発表事項", "サービス地域は北米・南米・欧州・日本、5サーバーで地域ロックなし。9月30日早期アクセス、無料プレイは報道上10月5日前後 — NC は正式リリース日・開始時刻・最終サーバー名を未確定。事前DL時期や地域価格も未発表です。"),
      ],
    }),
    fr: articleCopy(guideLabels, "fr", 6, {
      eyebrow: "VERSION MONDIALE",
      title: "Version mondiale d'Aion 2 : tous les changements confirmés face à la version coréenne",
      description: "La version mondiale d'Aion 2 n'est pas une copie de la coréenne : donjons, raids, champs de bataille, animaux, monétisation et adhésion ont été ajustés. Toutes les différences confirmées avant le 30 septembre.",
      intro: "NC l'a dit clairement depuis la diffusion d'août : la version mondiale d'Aion 2 est ajustée selon les retours des services coréen et taïwanais, et n'est pas une copie directe.",
      sourceNote: "Basé sur la couverture de GamesBeat (25/08), le rapport hebdo MMOEXP (22/08) et les annonces officielles de NC. Les éléments rapportés mais non confirmés sont signalés.",
      keywords: ["Aion 2 changements version mondiale", "Aion 2 vs version coréenne", "Aion 2 lancement mondial", "Aion 2 différences"],
      sections: [
        section("why-different", "Pourquoi la version mondiale diffère", "NC intègre les retours des versions coréenne et taïwanaise (nov. 2025) et communique directement avec les joueurs internationaux, notamment via le stream du 7 août. Deux objectifs : lisser l'expérience des nouveaux et normaliser le PvP."),
        section("group-content", "Donjons & raids", "Confirmé pour le lancement mondial : les groupes de donjon passent de 4 à 5 joueurs et le premier raid de 8 à 10. Un ajustement mondial délibéré annoncé au stream d'août, qui change aussi la composition des classes."),
        section("pvp-battlegrounds", "PvP : normalisation", "Les champs de bataille passent à 10v10 avec statistiques normalisées : l'équipement est aplani dans le mode, la victoire tient à la compétence. Couplé à la limite d'échange Quna→Kinah, cela rend le PvP plus équitable."),
        section("economy-membership", "Économie, animaux & adhésion", "L'échange Quna→Kinah est limité (moins pay-to-win). Le plafond d'animaux par joueur est réduit, ainsi que le ticket mensuel d'auto-loot. Les packs Fondateur incluent 30 jours d'adhésion, rétroactifs depuis le 22 juillet."),
        section("servers-launch", "Serveurs, lancement & à venir", "Régions : Amérique du Nord/Sud, Europe, Japon ; 5 serveurs sans verrouillage régional. Accès anticipé le 30 septembre, ouverture F2P vers le 5 octobre (non confirmé), nom des serveurs et préchargement non annoncés."),
      ],
    }),
    de: articleCopy(guideLabels, "de", 6, {
      eyebrow: "GLOBALE VERSION",
      title: "Aion 2 globale Version: Alle bestätigten Änderungen gegenüber der koreanischen Version",
      description: "Die globale Aion-2-Version ist keine Kopie der koreanischen: Dungeons, Raids, Schlachtfelder, Haustiere, Monetarisierung und Mitgliedschaft wurden angepasst. Alle bestätigten Unterschiede vor dem 30. September.",
      intro: "NC sagt es seit dem August-Stream klar: Die globale Version von Aion 2 wird nach Feedback der koreanischen und taiwanesischen Dienste angepasst und ist keine direkte Kopie.",
      sourceNote: "Basierend auf GamesBeat (25.08.), dem MMOEXP-Wochenbericht (22.08.) und offiziellen NC-Ankündigungen. Berichtete, aber unbestätigte Punkte sind markiert.",
      keywords: ["Aion 2 globale Version Änderungen", "Aion 2 vs koreanische Version", "Aion 2 globaler Launch", "Aion 2 Unterschiede"],
      sections: [
        section("why-different", "Warum sich die globale Version unterscheidet", "NC übernimmt Feedback der koreanischen und taiwanesischen Version (Nov. 2025) und spricht direkt mit internationalen Spielern, etwa im Stream vom 7. August. Ziele: reibungsloser Start und fairerer PvP."),
        section("group-content", "Dungeons & Raids", "Bestätigt: Dungeon-Gruppen von 4 auf 5, der erste Raid von 8 auf 10 Spieler — eine bewusste globale Anpassung aus dem August-Stream, die auch die Klassenkomposition ändert."),
        section("pvp-battlegrounds", "PvP: Normalisierung", "Schlachtfelder auf 10v10 mit normalisierten Werten: Ausrüstung wird eingeebnet, Sieg hängt von Können ab. Zusammen mit dem Quna→Kinah-Limit macht das PvP grundsätzlich fairer."),
        section("economy-membership", "Wirtschaft, Haustiere & Mitgliedschaft", "Quna→Kinah-Tausch gedeckelt (weniger Pay-to-Win). Haustier-Limit pro Spieler reduziert, monatliches Auto-Loot-Ticket limitiert. Alle Founder-Packs enthalten 30 Tage Mitgliedschaft, rückwirkend seit 22. Juli."),
        section("servers-launch", "Server, Launch & offene Punkte", "Regionen: Nord-/Südamerika, Europa, Japan; 5 Server ohne Regionssperre. Early Access am 30. September, F2P-Öffnung um den 5. Oktober (unbestätigt); Servernamen und Preload noch offen."),
      ],
    }),
    es: articleCopy(guideLabels, "es", 6, {
      eyebrow: "VERSIÓN GLOBAL",
      title: "Versión global de Aion 2: todos los cambios confirmados frente a la versión coreana",
      description: "La versión global de Aion 2 no es una copia de la coreana: mazmorras, incursiones, campos de batalla, mascotas, monetización y membresía fueron ajustados. Todas las diferencias confirmadas antes del 30 de septiembre.",
      intro: "NC lo dijo claramente desde la transmisión de agosto: la versión global de Aion 2 se ajusta según los comentarios de los servicios coreano y taiwanés, y no es una copia directa.",
      sourceNote: "Basado en la cobertura de GamesBeat (25/08), el informe semanal de MMOEXP (22/08) y los anuncios oficiales de NC. Los puntos reportados pero no confirmados están marcados.",
      keywords: ["Aion 2 cambios versión global", "Aion 2 vs versión coreana", "Aion 2 lanzamiento global", "Aion 2 diferencias"],
      sections: [
        section("why-different", "Por qué difiere la versión global", "NC incorpora los comentarios de Corea y Taiwán (nov. 2025) y habla directamente con los jugadores internacionales, como en la transmisión del 7 de agosto. Objetivos: suavizar el arranque y normalizar el PvP."),
        section("group-content", "Mazmorras e incursiones", "Confirmado para el lanzamiento mundial: grupos de mazmorra de 4 a 5 jugadores y la primera incursión de 8 a 10. Un ajuste mundial deliberado anunciado en la transmisión de agosto, que también cambia la composición de clases."),
        section("pvp-battlegrounds", "PvP: normalización", "Los campos de batalla pasan a 10v10 con estadísticas normalizadas: el equipo se aplana, la victoria depende de la habilidad. Junto con el límite de Quna→Kinah, el PvP global se vuelve más justo."),
        section("economy-membership", "Economía, mascotas y membresía", "El intercambio Quna→Kinah está limitado (menos pay-to-win). El tope de mascotas por jugador se reduce y el ticket mensual de auto-loot aplica en global. Los packs de fundador incluyen 30 días de membresía, retroactivos desde el 22 de julio."),
        section("servers-launch", "Servidores, lanzamiento y pendientes", "Regiones: Norteamérica, Sudamérica, Europa y Japón; 5 servidores sin bloqueo regional. Acceso anticipado el 30 de septiembre, apertura F2P hacia el 5 de octubre (sin confirmar); nombres de servidores y precarga sin anunciar."),
      ],
    }),
    "pt-br": articleCopy(guideLabels, "pt-br", 6, {
      eyebrow: "VERSÃO GLOBAL",
      title: "Versão global de Aion 2: todas as mudanças confirmadas em relação à versão coreana",
      description: "A versão global de Aion 2 não é uma cópia da coreana: masmorras, raides, campos de batalha, pets, monetização e assinatura foram ajustados. Todas as diferenças confirmadas antes de 30 de setembro.",
      intro: "A NC deixou claro desde a transmissão de agosto: a versão global de Aion 2 é ajustada com base no feedback dos serviços coreano e taiwanês, e não é uma cópia direta.",
      sourceNote: "Baseado na cobertura da GamesBeat (25/08), no relatório semanal da MMOEXP (22/08) e em anúncios oficiais da NC. Itens reportados, mas não confirmados, estão marcados.",
      keywords: ["Aion 2 mudanças versão global", "Aion 2 vs versão coreana", "Aion 2 lançamento global", "Aion 2 diferenças"],
      sections: [
        section("why-different", "Por que a versão global difere", "A NC incorpora o feedback das versões coreana e taiwanesa (nov. 2025) e fala diretamente com jogadores internacionais, como na transmissão de 7 de agosto. Objetivos: suavizar a estreia e normalizar o PvP."),
        section("group-content", "Masmorras e raides", "Confirmado para o lançamento global: grupos de masmorra de 4 para 5 e a primeira raide de 8 para 10 jogadores. Um ajuste global deliberado anunciado na transmissão de agosto, que também muda a composição de classes."),
        section("pvp-battlegrounds", "PvP: normalização", "Os campos de batalha passam a 10v10 com atributos normalizados: o equipamento é achatado e a vitória depende da habilidade. Com o limite de Quna→Kinah, o PvP global fica mais justo."),
        section("economy-membership", "Economia, pets e assinatura", "A troca Quna→Kinah é limitada (menos pay-to-win). O limite de pets por jogador cai e o ticket mensal de auto-loot vale no global. Os pacotes de fundador incluem 30 dias de assinatura, retroativos desde 22 de julho."),
        section("servers-launch", "Servidores, lançamento e pendências", "Regiões: América do Norte/Sul, Europa e Japão; 5 servidores sem bloqueio regional. Acesso antecipado em 30 de setembro, abertura F2P por volta de 5 de outubro (não confirmado); nomes de servidores e pré-carregamento pendentes."),
      ],
    }),
    ru: articleCopy(guideLabels, "ru", 6, {
      eyebrow: "ГЛОБАЛЬНАЯ ВЕРСИЯ",
      title: "Глобальная версия Aion 2: все подтверждённые отличия от корейской версии",
      description: "Глобальная версия Aion 2 — не копия корейской: данжи, рейды, батлграунды, питомцы, монетизация и подписка были скорректированы. Все подтверждённые различия до 30 сентября.",
      intro: "NC заявила ещё в августовском стриме: глобальная версия Aion 2 настраивается по отзывам корейского и тайваньского сервисов и не является прямой копией.",
      sourceNote: "На основе освещения GamesBeat (25.08), еженедельного отчёта MMOEXP (22.08) и официальных объявлений NC. Сообщённое, но не подтверждённое — отмечено.",
      keywords: ["Aion 2 изменения глобальной версии", "Aion 2 vs корейская версия", "Aion 2 глобальный запуск", "Aion 2 отличия"],
      sections: [
        section("why-different", "Почему глобальная версия отличается", "NC учитывает отзывы корейской и тайваньской версий (ноя. 2025) и напрямую общается с международными игроками, например в стриме 7 августа. Цели: сгладить старт и нормализовать PvP."),
        section("group-content", "Данжи и рейды", "Подтверждено для глобального запуска: группы в данжах с 4 до 5, первый рейд с 8 до 10 игроков. Делибератная глобальная корректировка, которая меняет и состав классов."),
        section("pvp-battlegrounds", "PvP: нормализация", "Батлграунды переходят на 10v10 с нормализованными статами: экипировка сглаживается, победа зависит от умения. Вместе с лимитом обмена Quna→Kinah это делает PvP честнее."),
        section("economy-membership", "Экономика, питомцы и подписка", "Обмен Quna→Kinah ограничен (меньше pay-to-win). Лимит питомцев на игрока снижен, месячный тикет автолута действует в глобальной версии. Все наборы основателя включают 30 дней подписки, ретроактивно с 22 июля."),
        section("servers-launch", "Серверы, запуск и нерешённое", "Регионы: Северная/Южная Америка, Европа, Япония; 5 серверов без региональной привязки. Ранний доступ 30 сентября, F2P-открытие около 5 октября (не подтверждено); имена серверов и предзагрузка не объявлены."),
      ],
    }),
    "zh-hant": articleCopy(guideLabels, "zh-hant", 6, {
      eyebrow: "全球版",
      title: "Aion 2 全球版：與韓服相比的每一處已確認改動",
      description: "Aion 2 全球版並非韓服的複製——副本、團隊本、戰場、寵物、貨幣化與會員均經調整。以下是 9 月 30 日搶先體驗前的全部已確認差異。",
      intro: "NC 自 8 月開發者直播起便明確表示：全球版將基於韓國與台灣服的經驗與回饋進行調整，並非現有版本的直接複製。本指南彙總所有已確認的全球專屬改動，並標出仍未公布的部分。",
      sourceNote: "基於 GamesBeat 對全球版的報導（8 月 25 日）、MMOEXP 關於全球發布調整的週報（8 月 22 日）及 NC 官方公告與開發者直播。已報導但未官方確認的內容已標註。",
      keywords: ["Aion 2 全球版改動", "Aion 2 韓服區別", "Aion 2 全球上線調整", "Aion 2 全球版差異", "Aion 2 西方特調"],
      sections: [
        section("why-different", "全球版為何不同", ["NC 表示全球部署吸收了 2025 年 11 月上線的韓國與台灣版的經驗與回饋。工作室透過 8 月 7 日「Beyond the Abyss」開發者直播等管道直接與國際玩家溝通，並反覆強調全球版不會照搬亞洲版本。", "兩個目標驅動了這些改動：平滑新玩家首週體驗，以及規範化競技系統讓 PvP 不因投入高低而失衡。"]),
        section("group-content", "組隊內容：副本與團隊本", ["全球版確認了自亞洲版以來最大的團隊規模調整：副本隊伍由 4 人擴至 5 人，首個團隊本由 8 人擴至 10 人。這是在 8 月開發者直播中公布的全球專屬調整。", "規模變化不只是人數：5 人副本與 10 人團隊本會改變職業構成與機制調校。本站所有面向全球的副本建議均按此人數編寫。"]),
        section("pvp-battlegrounds", "PvP：戰場屬性平衡", ["全球版戰場統一為 10v10 且屬性平衡（stat-normalized）——模式內抹平裝備與成長差距，勝負取決於操作與團隊配合而非投入。", "這是與亞洲服務部分內容的重要理念差異。結合 Quna 兌換 Kinah 限制，說明 NC 正在把全球 PvP 設計得更公平。"]),
        section("economy-membership", "經濟、寵物與會員", ["全球版限制了 Quna 兌換 Kinah 的額度，降低「課金兌換貨幣」的上限——直接回應了亞洲服最大的批評點。", "寵物上限下調，每月寵物自動拾取券上限同樣適用全球。請謹慎選擇主力寵物。", "三個創始人包檔位均含 30 天會員，自 7 月 22 日購買的包追溯適用；月度會員訂閱在 Market 與 Exchange 功能的門檻上與全球版規劃一致。"]),
        section("servers-launch", "伺服器、上線時間與未公布事項", ["服務區域確認為北美、南美、歐洲與日本，共五台伺服器且無區域鎖定——同一個名冊、同一個全球社群。", "時間：9 月 30 日創始人包持有者搶先體驗，免費遊玩預計 10 月 5 日開放（媒體報導，NC 未確認正式日期與開放時間，也未公布最終伺服器名稱）。", "尚未公布：預載時間、除美元參考價外的區域定價細節，以及仍在評估中的韓服系統（如報導中的婚姻系統）是否會登陸全球。"]),
      ],
    }),
  },
};