import { articleCopy, localizations, newsLabels, publishedVerified, section } from "./trending-september-11-shared";
import type { ContentEntry, ContentHeroImage, ContentSource } from "./content-registry";

/* ARTICLE 1 — Launch Scale Test in 6 days: pre-download Sep 16, LST Sep 17-18, plus what has been confirmed since the announcement */

const steamLstSource: ContentSource = {
  id: "aion2-steam-lst-announcement-2026-08-26",
  kind: "platform",
  publisher: "NCsoft (Steam Community)",
  label: "Launch Scale Test Coming Up (Steam Announcement, Sep 16 pre-download, Sep 17-18 LST)",
  url: "https://store.steampowered.com/news/app/3393110/view/1842212951298118",
  publishedAt: "2026-08-26",
  retrievedAt: "2026-09-11",
  verifiedAt: "2026-09-11",
  localizations: localizations({
    "zh-hans": "发布规模测试即将到来（Steam 公告：9/16 预载、9/17-18 测试）",
    en: "Launch Scale Test Coming Up (Steam Announcement, Sep 16 pre-download, Sep 17-18 LST)",
    fr: "Le test d'échelle de lancement arrive (annonce Steam, pré-téléchargement 16 sept., LST 17-18 sept.)",
    de: "Launch Scale Test steht bevor (Steam-Ankündigung, Pre-Download 16. Sept., LST 17.-18. Sept.)",
    es: "Se acerca la prueba de escala de lanzamiento (anuncio de Steam, precarga 16 sept., LST 17-18 sept.)",
    ja: "ランチスケールテスト間近（Steam告知：9/16プリダウンロード、9/17-18 LST）",
    "pt-br": "Teste de escala de lançamento chegando (anúncio na Steam, pré-download 16 set., LST 17-18 set.)",
    ru: "Масштабный тест запуска близко (анонс Steam: предзагрузка 16 сент., LST 17–18 сент.)",
    ko: "런치 스케일 테스트가 다가옵니다 (Steam 공지: 9/16 사전 다운로드, 9/17-18 LST)",
    "zh-hant": "發布規模測試即將到來（Steam 公告：9/16 預載、9/17-18 測試）",
  }, "https://store.steampowered.com/news/app/3393110/view/1842212951298118"),
};

const wfSource: ContentSource = {
  id: "wccftech-aion2-qa-2026-09-07",
  kind: "third-party",
  publisher: "Wccftech",
  label: "Aion 2 Q&A: NVIDIA DLSS 5 Confirmed in the Works; Console Launch Is Coming, but Cross-Play Likely Isn't",
  url: "https://wccftech.com/aion-2-qa-dlss-5-console-cross-play/",
  publishedAt: "2026-09-07",
  retrievedAt: "2026-09-11",
  verifiedAt: "2026-09-11",
  localizations: localizations({
    "zh-hans": "Aion 2 Q&A：DLSS 5 确认开发中；主机版将至，但跨平台大概率不支持",
    en: "Aion 2 Q&A: NVIDIA DLSS 5 Confirmed in the Works; Console Launch Is Coming, but Cross-Play Likely Isn't",
    fr: "Aion 2 Q&R : DLSS 5 confirmé, lancement console à venir, mais le cross-play probablement pas",
    de: "Aion 2 Q&A: DLSS 5 bestätigt, Konsolen-Launch kommt, Cross-Play wohl nicht",
    es: "Aion 2 Preguntas y respuestas: DLSS 5 confirmado, lanzamiento de consola en camino, pero el cross-play probablemente no",
    ja: "Aion 2 Q&A：DLSS 5 開発中を確認、コンソール版準備中、クロスプレイはおそらく非対応",
    "pt-br": "Aion 2 Q&A: DLSS 5 confirmado, lançamento para consoles a caminho, mas cross-play provavelmente não",
    ru: "Aion 2 Q&A: DLSS 5 подтверждён, консольный запуск готовится, кросс-плей вряд ли будет",
    ko: "아이온2 Q&A: DLSS 5 개발 중 확인, 콘솔 출시 준비 중, 크로스플레이는 아마 미지원",
    "zh-hant": "Aion 2 Q&A：DLSS 5 確認開發中；主機版將至，但跨平台大概率不支援",
  }, "https://wccftech.com/aion-2-qa-dlss-5-console-cross-play/"),
};

const lstHero: ContentHeroImage = {
  src: "https://blogfiles.ncsoft.net/news/af7330da-4ff6-4b58-aece-400e6061a3be.jpg",
  width: 1200, height: 630,
  credit: "NC Corporation",
  sourceUrl: "https://aion2.plaync.com/en-us/",
  rights: "linked-official-media",
  translations: {
    "zh-hans": { alt: "Aion 2 规模测试倒计时新闻横幅", caption: "距离 Aion 2 免费规模测试（LST）还有 6 天：9 月 16 日开放预载、9 月 17-18 日测试——自公告以来已确认 DLSS 4.5 上线/DLSS 5 开发中、手柄支持、$15 会员与无日常/周常门槛等新事实。" },
    en: { alt: "Aion 2 Launch Scale Test countdown news banner", caption: "Six days until the free Launch Scale Test: pre-download opens September 16 and the test runs September 17-18 — with DLSS 4.5 live and DLSS 5 in development, controller support, the $15 membership, and no daily/weekly gates confirmed since the announcement." },
    fr: { alt: "Bannière d'actualité du compte à rebours du test d'échelle d'Aion 2", caption: "Six jours avant le test d'échelle gratuit : pré-téléchargement le 16 septembre et test les 17-18 — DLSS 4.5 en jeu et DLSS 5 en développement, manettes, adhésion à 15 $ et absence de seuils quotidiens/hebdomadaires confirmés." },
    de: { alt: "News-Banner zum Countdown des Launch Scale Tests von Aion 2", caption: "Sechs Tage bis zum kostenlosen Launch Scale Test: Pre-Download am 16. September, Test am 17.-18. — mit DLSS 4.5 live und DLSS 5 in Entwicklung, Controller, 15-$-Membership und keinen Tages-/Wochen-Gates bestätigt." },
    es: { alt: "Banner de noticias de la cuenta atrás de la prueba de escala de Aion 2", caption: "Seis días para la prueba gratuita: precarga el 16 de septiembre y prueba el 17-18 — con DLSS 4.5 activo y DLSS 5 en desarrollo, mandos, membresía de $15 y sin límites diarios/semanales confirmados." },
    ja: { alt: "Aion 2 ランチスケールテストカウントダウンニュースバナー", caption: "無料ランチスケールテストまで6日：9月16日プリダウンロード、9月17-18日実施——告知後にDLSS 4.5導入済み・DLSS 5開発中、コントローラー、15ドルメンバーシップ、日次/週次ゲートなしが確認されています。" },
    "pt-br": { alt: "Banner de notícias da contagem regressiva do teste de escala do Aion 2", caption: "Seis dias para o teste de escala gratuito: pré-download em 16 de setembro e teste em 17-18 — com DLSS 4.5 ativo e DLSS 5 em desenvolvimento, controles, associação de US$ 15 e sem limites diários/semanais confirmados." },
    ru: { alt: "Баннер новостей об отсчёте до масштабного теста Aion 2", caption: "Шесть дней до бесплатного масштабного теста: предзагрузка 16 сентября, тест 17–18 — с подтверждёнными DLSS 4.5 в игре и DLSS 5 в разработке, геймпадами, подпиской $15 и без ежедневных/еженедельных ограничений." },
    ko: { alt: "Aion 2 런치 스케일 테스트 카운트다운 뉴스 배너", caption: "무료 규모 테스트(LST)까지 6일 남았습니다: 9월 16일 사전 다운로드, 9월 17-18일 테스트——공지 이후 DLSS 4.5 적용·DLSS 5 개발 중, 컨트롤러 지원, $15 멤버십, 일일/주간 게이트 없음 등이 확인됐습니다." },
    "zh-hant": { alt: "Aion 2 規模測試倒數新聞橫幅", caption: "距離 Aion 2 免費規模測試（LST）還有 6 天：9 月 16 日開放預載、9 月 17-18 日測試——自公告以來已確認 DLSS 4.5 上線/DLSS 5 開發中、手把支援、$15 會員與無日常/週常門檻等新事實。" },
  },
};

export const trendingSeptember11Article1: ContentEntry = {
  section: "news",
  slug: "aion-2-launch-scale-test-countdown-6-days",
  schemaType: "NewsArticle",
  publishedAt: "2026-09-11",
  updatedAt: "2026-09-11",
  readingMinutes: 5,
  publication: publishedVerified,
  sources: [steamLstSource, wfSource],
  heroImage: lstHero,
  related: [
    { kind: "content", section: "guides", slug: "aion-2-launch-scale-test-preparation-guide" },
    { kind: "content", section: "guides", slug: "aion-2-prelaunch-access-routes-guide" },
    { kind: "content", section: "news", slug: "aion-2-october-5-launch-countdown-roadmap" },
    { kind: "content", section: "guides", slug: "aion-2-global-version-changes-guide" },
  ],
  translations: {
    en: articleCopy(newsLabels, "en", 5, {
      eyebrow: "LAUNCH COUNTDOWN",
      title: "Aion 2 Launch Scale Test in 6 Days: Pre-Download Sept 16, LST Sept 17-18, and What's Confirmed Since",
      description: "The free Launch Scale Test runs September 17-18 with pre-download on September 16 — six days from now, with DLSS 4.5 live and DLSS 5 in development, controller support, the $15 membership, and the no-gates QoL build confirmed since the announcement",
      intro: "Aion 2's free Launch Scale Test (LST) is six days away: pre-download opens September 16 and the test runs September 17-18 via Steam. Since the announcement was made, NCsoft has confirmed a batch of details worth knowing before you jump in — from DLSS and controller support to the $15 membership and the no-daily-gates build.",
      sourceNote: "Based on the official Steam announcement of the Launch Scale Test (published August 26, 2026) and Wccftech's September 7, 2026 interview with the Aion 2 team for the 'confirmed since' details (both retrieved September 11, 2026).",
      keywords: ["Aion 2 Launch Scale Test September", "Aion 2 LST pre-download Sep 16", "Aion 2 launch scale test countdown", "Aion 2 LST what to expect", "Aion 2 free test Steam September 2026"],
      sections: [
        section("countdown", "Six Days to the Launch Scale Test", ["The free Launch Scale Test runs September 17-18, with pre-download starting September 16. It is free for everyone and accessed through the Steam page, and it is the last public test before the October 5 global launch.", "For server-capacity testing, participation not only helps NCsoft stress the infrastructure — it is also the real-world check of the QoL changes before they go live for the Season 1 launch."]),
        section("what-we-learned", "What's Been Confirmed Since the Announcement", ["Performance: DLSS 4.5 is already live in the game, and NVIDIA DLSS 5 is confirmed in development together with NC. Controllers are supported on PC, and the global build is PC-only for now (Steam + PURPLE launcher), with a console version in preparation after the global launch.", "Economy: the dual subscription system was consolidated into a single $15/month membership, and Founder's Packs include a 30-day membership. Design: the global build has no daily or weekly content gates, smoothed item progression, and PvP as an option rather than a requirement."]),
        section("what-to-expect", "What the LST Is For", ["The LST is a scale test first: it verifies server capacity and matchmaking under load. Expect queues, longer loading, and possible hotfixes during the window — the purpose is catching infrastructure issues, not polishing final balance.", "It also runs the Korean-fielded mechanics and content structure that the global Season 1 will ship with, so treat the experience as a preview of the modified Season 1 rather than the final day-one state."]),
        section("how-to-prepare", "How to Prepare This Week", ["1. Pre-download on September 16 so you can start at the test's opening; 2. Check your GPU settings against the DLSS 4.5 baseline during the test — it is the launch performance target; 3. Controller users should confirm gamepad input works on their setup; 4. Expect the no-gates design: you can sample endgame-style content on your own schedule without daily stacks; 5. If you are considering the $15 membership, you can evaluate the features it covers during the test rather than guessing."]),
        section("whats-next", "The Road After the LST", ["After the LST, Founder's Pack owners get advance access from September 30, and the free-to-play global launch follows on October 5 with a modified Season 1 — roughly a year of Korean content in reserve, then three-month seasons behind Korea.", "If you are new, the site's Launch Scale Test preparation guide and the launch access routes guide cover the steps in detail — this countdown is the reminder that the moment to test your setup is now, not on launch day."]),
      ],
    }),
    "zh-hans": articleCopy(newsLabels, "zh-hans", 5, {
      eyebrow: "上线倒计时",
      title: "Aion 2 规模测试 6 天后举行：9 月 16 日预载、9 月 17-18 日测试，及公告后确认的新事实",
      description: "免费规模测试（LST）9 月 17-18 日举行、9 月 16 日开放预载——就在 6 天后；公告以来已确认 DLSS 4.5 上线/DLSS 5 开发中、手柄支持、$15 会员与无日常/周常门槛的 QoL 全球版",
      intro: "Aion 2 免费规模测试（LST）就在 6 天后：9 月 16 日开放预载，9 月 17-18 日经 Steam 测试。自公告以来，NCsoft 确认了一批入场前值得了解的细节——从 DLSS 与手柄支持，到 $15 会员与无日常门槛版本。",
      sourceNote: "基于官方 Steam 规模测试公告（2026-08-26 发布）与 Wccftech 2026 年 9 月 7 日对 Aion 2 团队的专访（「公告后确认」部分）（均于 2026-09-11 抓取）。",
      keywords: ["Aion 2 规模测试 9月", "Aion 2 LST 9月16日预载", "Aion 2 规模测试倒计时", "Aion 2 规模测试 内容", "Aion 2 免费测试 Steam 2026年9月"],
      sections: [
        section("countdown", "距离规模测试 6 天", ["免费规模测试（LST）于 9 月 17-18 日举行，9 月 16 日起开放预载。测试对所有玩家免费、经 Steam 页面进入，是 10 月 5 日全球首发前的最后一次公开测试。", "作为服务器容量测试，参与不仅能帮 NCsoft 检验基础设施——也是在 Season 1 上线前对 QoL 改动的一次真实检验。"]),
        section("what-we-learned", "公告之后确认的新事实", ["性能：DLSS 4.5 已在游戏内上线，NVIDIA DLSS 5 确认正与 NC 联合开发中。PC 支持手柄，全球版现阶段仅 PC（Steam+PURPLE 启动器），主机版在全球首发之后筹备中。", "经济：双订阅系统整合为每月 $15 单一会员，创始人包附带 30 天会员。设计：全球版无日常/周常内容门槛、物品成长曲线平滑化、PvP 可变可选。"]),
        section("what-to-expect", "测试的作用", ["LST 首先是规模测试：验证负载下的服务器容量与匹配。期间可能遇到排队、较长加载与热修——目的是发现基础设施问题，而非打磨最终平衡。", "它也会运行全球 Season 1 将搭载的、已在韩服验证的机制与内容结构——把体验视为改良版 Season 1 的预览，而非最终的日后状态。"]),
        section("how-to-prepare", "本周如何准备", ["1. 9 月 16 日预载，测试开启即可进入；2. 测试期间对照 DLSS 4.5 基线检查显卡设置——这是首发性能目标；3. 手柄用户确认自己的设置下输入正常；4. 体验无门槛设计：可按自己的节奏体验类终局内容，无需日常堆积；5. 若考虑 $15 会员，可在测试中实评其覆盖功能，而非猜测。"]),
        section("whats-next", "测试之后的路", ["LST 之后，创始人包持有者 9 月 30 日起抢先体验，免费制全球首发 10 月 5 日上线——改良版 Season 1，储备约一年韩服内容，之后以三个月一季落后韩服。", "如果你是新人，本站的规模测试准备指南与上线访问路径指南有详细步骤——这个倒计时提醒你：现在就该测试配置，而不是上线当天。"]),
      ],
    }),
    fr: articleCopy(newsLabels, "fr", 5, {
      eyebrow: "COMPTE À REBOURS",
      title: "Test d'échelle d'Aion 2 dans 6 jours : pré-téléchargement le 16 sept., LST les 17-18 sept., et ce qui est confirmé depuis",
      description: "Le test d'échelle gratuit aura lieu les 17-18 septembre avec pré-téléchargement le 16 — à six jours, avec DLSS 4.5 en jeu et DLSS 5 en développement, manettes, adhésion à 15 $ et build sans seuils confirmés",
      intro: "Le test d'échelle gratuit (LST) d'Aion 2 est à six jours : pré-téléchargement le 16 septembre, test les 17-18 via Steam. Depuis l'annonce, NCsoft a confirmé des détails utiles avant de se lancer — DLSS, manettes, adhésion à 15 $, build sans seuils.",
      sourceNote: "Basé sur l'annonce officielle Steam du test d'échelle (publiée le 26 août 2026) et l'entretien de Wccftech du 7 septembre 2026 (récupérés le 11 septembre 2026).",
      keywords: ["Aion 2 test d'échelle septembre", "Aion 2 LST pré-téléchargement 16 sept", "Aion 2 compte à rebours test d'échelle", "Aion 2 test gratuit Steam septembre 2026"],
      sections: [
        section("countdown", "Six jours avant le LST", "Test gratuit les 17-18 septembre, pré-téléchargement dès le 16. Dernier test public avant le lancement global du 5 octobre. Bonus : vérification réelle des changements QoL en conditions réelles."),
        section("what-we-learned", "Ce qui est confirmé depuis", "Performance : DLSS 4.5 en jeu, DLSS 5 confirmé en développement avec NV ; manettes supportées ; global PC-only (Steam + PURPLE), console en préparation. Économie : abonnement unique à 15 $/mois, Founder's Packs avec 30 jours. Design : aucun seuil quotidien/hebdomadaire, progression lissée, PvP optionnel."),
        section("what-to-expect", "À quoi sert le LST", "Test de capacité d'abord : files, chargements, hotfixes possibles. Contenu et structure de la Saison 1 modifiée — traitez-le comme une préview, pas l'état final."),
        section("how-to-prepare", "Préparation cette semaine", "1. Pré-télécharger le 16 ; 2. Vérifier DLSS 4.5 pendant le test ; 3. Validation manettes ; 4. Réalité du no-gates ; 5. Évaluer l'adhésion à 15 $ sur pièces."),
        section("whats-next", "Après le LST", "Accès anticipé Founder's Pack le 30 septembre, lancement free-to-play le 5 octobre (Saison 1 modifiée, ~un an de contenu coréen puis saisons trimestrielles). Le guide de préparation du LST du site couvre le détail."),
      ],
    }),
    de: articleCopy(newsLabels, "de", 5, {
      eyebrow: "LAUNCH-COUNTDOWN",
      title: "Aion 2 Launch Scale Test in 6 Tagen: Pre-Download am 16. Sept., LST 17.-18. Sept., und was seitdem bestätigt ist",
      description: "Der kostenlose Launch Scale Test läuft am 17.-18. September, Pre-Download ab dem 16. — in sechs Tagen, mit live DLSS 4.5 und DLSS 5 in Entwicklung, Controller, 15-$-Membership und dem No-Gates-Build bestätigt",
      intro: "Der kostenlose Launch Scale Test (LST) von Aion 2 ist sechs Tage entfernt: Pre-Download am 16. September, Test am 17.-18. über Steam. Seit der Ankündigung hat NCsoft Details bestätigt, die man vor dem Einstieg kennen sollte.",
      sourceNote: "Basierend auf der offiziellen Steam-Ankündigung des LST (26. August 2026) und dem Wccftech-Interview mit dem Aion-2-Team vom 7. September 2026 (abgerufen am 11. September 2026).",
      keywords: ["Aion 2 Launch Scale Test September", "Aion 2 LST Pre-Download 16. Sep", "Aion 2 Countdown Scale Test", "Aion 2 kostenloser Test Steam September 2026"],
      sections: [
        section("countdown", "Sechs Tage bis zum LST", "Kostenloser Test am 17.-18. September, Pre-Download ab dem 16. — der letzte öffentliche Test vor dem Global-Launch am 5. Oktober, inklusive Realtest der QoL-Änderungen."),
        section("what-we-learned", "Was seitdem bestätigt ist", "Performance: DLSS 4.5 live, DLSS 5 mit NVIDIA in Entwicklung; Controller unterstützt; Global PC-only (Steam + PURPLE), Konsole in Vorbereitung. Ökonomie: eine Membership für 15 $/Monat, Founder's Packs mit 30 Tagen. Design: keine Tages-/Wochen-Gates, geglättete Progression, optionales PvP."),
        section("what-to-expect", "Wozu der LST dient", "Kapazitätstest: Warteschlangen, Ladepausen, Hotfixes möglich. Inhalte der modifizierten Season 1 — als Preview, nicht als Endstand."),
        section("how-to-prepare", "Diese Woche vorbereiten", "1. Am 16. vordownloaden ; 2. DLSS 4.5 im Test prüfen ; 3. Controller validieren ; 4. No-Gates-Design selbst erleben ; 5. 15-$-Membership praktisch bewerten."),
        section("whats-next", "Nach dem LST", "Founder's-Pack-Frühzugang am 30. September, Free-to-Play-Launch am 5. Oktober (modifizierte Season 1, ~ein Jahr koreanischer Content, dann Quartalsseasons). Der LST-Vorbereitungs-Leitfaden der Seite deckt die Details ab."),
      ],
    }),
    es: articleCopy(newsLabels, "es", 5, {
      eyebrow: "CUENTA ATRÁS",
      title: "Prueba de escala de Aion 2 en 6 días: precarga el 16 sept., LST los 17-18 sept. y lo confirmado desde entonces",
      description: "La prueba gratuita será los días 17-18 de septiembre con precarga el 16 — a seis días, con DLSS 4.5 activo y DLSS 5 en desarrollo, mandos, membresía de $15 y build sin límites confirmado",
      intro: "La prueba gratuita de escala (LST) de Aion 2 está a seis días: precarga el 16 de septiembre, prueba los 17-18 vía Steam. Desde el anuncio, NCsoft ha confirmado detalles útiles antes de entrar.",
      sourceNote: "Basado en el anuncio oficial de Steam de la prueba (publicado el 26 de agosto de 2026) y la entrevista de Wccftech del 7 de septiembre de 2026 (recuperados el 11 de septiembre de 2026).",
      keywords: ["Aion 2 prueba de escala septiembre", "Aion 2 LST precarga 16 sept", "Aion 2 cuenta atrás prueba de escala", "Aion 2 prueba gratis Steam septiembre 2026"],
      sections: [
        section("countdown", "Seis días para el LST", "Prueba gratuita los 17-18 de septiembre, precarga desde el 16. Última prueba pública antes del lanzamiento global del 5 de octubre, con verificación real de los cambios QoL."),
        section("what-we-learned", "Lo confirmado desde entonces", "Rendimiento: DLSS 4.5 activo, DLSS 5 confirmado en desarrollo con NVIDIA; mandos soportados; global solo PC (Steam + PURPLE), consola en preparación. Economía: única membresía de $15/mes, Founder's Packs con 30 días. Diseño: sin límites diarios/semanales, progresión suavizada, PvP opcional."),
        section("what-to-expect", "Para qué sirve el LST", "Prueba de capacidad: colas, cargas y hotfixes posibles. Contenido de la Temporada 1 modificada — trátalo como preview, no estado final."),
        section("how-to-prepare", "Preparación esta semana", "1. Precargar el 16; 2. Comprobar DLSS 4.5 durante la prueba; 3. Validar mandos; 4. Vivir el diseño sin límites; 5. Evaluar la membresía de $15 sobre el terreno."),
        section("whats-next", "Después del LST", "Acceso anticipado de Founder's Pack el 30 de septiembre, lanzamiento free-to-play el 5 de octubre (Temporada 1 modificada). La guía de preparación del LST del sitio cubre el detalle."),
      ],
    }),
    ja: articleCopy(newsLabels, "ja", 5, {
      eyebrow: "ローンチカウントダウン",
      title: "Aion 2 ランチスケールテストまで6日：9/16プリダウンロード、9/17-18実施、告知後に確認されたこと",
      description: "無料ランチスケールテスト（LST）は9月17-18日に実施、9月16日からプリダウンロード——6日後に迫る。告知後、DLSS 4.5導入済み・DLSS 5開発中、コントローラー、$15メンバーシップ、デイリー/ウィークリー制限なしのQoLビルドが確認済み",
      intro: "Aion 2の無料ランチスケールテスト（LST）まで6日です：9月16日からプリダウンロード、9月17-18日にSteam経由で実施。告知以後、NCが参加前に知っておきたい詳細を次々と確認しています——DLSSやコントローラー対応、$15メンバーシップ、デイリー制限なしのビルドまで。",
      sourceNote: "公式SteamのLST告知（2026-08-26公開）と、Wccftech 2026年9月7日付Aion 2チームインタビュー（「告知後確認」部分、いずれも2026-09-11取得）に基づきます。",
      keywords: ["Aion 2 ランチスケールテスト 9月", "Aion 2 LST 9月16日 プリダウンロード", "Aion 2 スケールテスト カウントダウン", "Aion 2 無料テスト Steam 2026年9月"],
      sections: [
        section("countdown", "LSTまで6日", "無料テストは9月17-18日、プリダウンロードは9月16日から。10月5日のグローバルローンチ前、最後の公開テストです。サーバー容量検証の参加という意味に加え、QoL変更の実環境チェックにもなります。"),
        section("what-we-learned", "告知後に確認されたこと", "性能：DLSS 4.5はゲーム内で導入済み、DLSS 5はNVIDIAと共同開発中と確認。コントローラー対応、グローバルは当面PCのみ（Steam+PURPLE）、コンソール版は準備中。経済：二重サブスクを月$15の単一メンバーシップに統合、ファウンダーズパックに30日分。設計：日次/週次ゲートなし、成長の平滑化、PvPは任意。"),
        section("what-to-expect", "LSTの役割", "まずは容量テスト：負荷下のサーバーとマッチングを検証します。待機列や長めのロード、ホットフィックスがあり得ます——インフラ問題の発見が目的で、最終バランスの研磨ではありません。"),
        section("how-to-prepare", "今週の準備", "1. 9月16日にプリダウンロード; 2. テスト中にDLSS 4.5基準でGPU設定を確認（ローンチ性能目標）; 3. コントローラー入力を確認; 4. ゲートなし設計を体感; 5. $15メンバーシップの機能を実地で評価。"),
        section("whats-next", "LSTの後", "ファウンダーズパック先行は9月30日、F2Pローンチは10月5日（改良版シーズン1）。本サイトのLST準備ガイドが詳細をカバーしています——設定確認はローンチ当日ではなく今です。"),
      ],
    }),
    "pt-br": articleCopy(newsLabels, "pt-br", 5, {
      eyebrow: "CONTAGEM REGRESSIVA",
      title: "Teste de escala do Aion 2 em 6 dias: pré-download em 16 set., LST 17-18 set. e o que foi confirmado desde então",
      description: "O teste gratuito acontece nos dias 17-18 de setembro com pré-download no dia 16 — em seis dias, com DLSS 4.5 ativo e DLSS 5 em desenvolvimento, controles, associação de US$ 15 e build sem limites confirmados",
      intro: "O teste gratuito de escala (LST) do Aion 2 está a seis dias: pré-download em 16 de setembro, teste nos dias 17-18 via Steam. Desde o anúncio, a NCsoft confirmou detalhes úteis antes de você entrar.",
      sourceNote: "Baseado no anúncio oficial da Steam do teste (publicado em 26 de agosto de 2026) e na entrevista da Wccftech de 7 de setembro de 2026 (recuperados em 11 de setembro de 2026).",
      keywords: ["Aion 2 teste de escala setembro", "Aion 2 LST pré-download 16 set", "Aion 2 contagem regressiva teste de escala", "Aion 2 teste grátis Steam setembro 2026"],
      sections: [
        section("countdown", "Seis dias para o LST", "Teste gratuito nos dias 17-18 de setembro, pré-download a partir do dia 16. Último teste público antes do lançamento global de 5 de outubro, com verificação real das mudanças de QoL."),
        section("what-we-learned", "O que foi confirmado desde então", "Desempenho: DLSS 4.5 ativo, DLSS 5 confirmado em desenvolvimento com a NVIDIA; controles suportados; global só PC (Steam + PURPLE), console em preparação. Economia: associação única de US$ 15/mês, Founder's Packs com 30 dias. Design: sem limites diários/semanais, progressão suavizada, PvP opcional."),
        section("what-to-expect", "Para que serve o LST", "Teste de capacidade: filas, carregamentos e hotfixes possíveis. Conteúdo da Temporada 1 modificada — trate como preview, não estado final."),
        section("how-to-prepare", "Preparação desta semana", "1. Pré-baixar no dia 16; 2. Conferir DLSS 4.5 durante o teste; 3. Validar controles; 4. Viver o design sem limites; 5. Avaliar a associação de US$ 15 no terreno."),
        section("whats-next", "Depois do LST", "Acesso antecipado do Founder's Pack em 30 de setembro, lançamento free-to-play em 5 de outubro (Temporada 1 modificada). O guia de preparação do LST do site cobre os detalhes."),
      ],
    }),
    ru: articleCopy(newsLabels, "ru", 5, {
      eyebrow: "ОБРАТНЫЙ ОТСЧЁТ",
      title: "Масштабный тест Aion 2 через 6 дней: предзагрузка 16 сентября, LST 17–18 сентября и что подтверждено с тех пор",
      description: "Бесплатный масштабный тест пройдёт 17–18 сентября с предзагрузкой 16-го — через шесть дней, с подтверждёнными DLSS 4.5 в игре и DLSS 5 в разработке, геймпадами, подпиской $15 и билдом без ограничений",
      intro: "Бесплатный масштабный тест (LST) Aion 2 — через шесть дней: предзагрузка 16 сентября, тест 17–18 числа через Steam. После анонса NCsoft подтвердила детали, которые стоит знать до входа.",
      sourceNote: "На основе официального анонса Steam масштабного теста (опубликован 26 августа 2026 г.) и интервью Wccftech с командой Aion 2 от 7 сентября 2026 г. (получены 11 сентября 2026 г.).",
      keywords: ["Aion 2 масштабный тест сентябрь", "Aion 2 LST предзагрузка 16 сентября", "Aion 2 бесплатный тест Steam сентябрь 2026"],
      sections: [
        section("countdown", "Шесть дней до LST", "Бесплатный тест 17–18 сентября, предзагрузка с 16-го. Последний публичный тест перед глобальным запуском 5 октября, включая реальную проверку изменений QoL."),
        section("what-we-learned", "Что подтверждено с тех пор", "Производительность: DLSS 4.5 уже в игре, DLSS 5 готовится с NVIDIA; геймпады поддерживаются; глобал только на ПК (Steam + PURPLE), консоль готовится. Экономика: единая подписка $15/мес, в Founder's Packs — 30 дней. Дизайн: без ежедневных/еженедельных ограничений, сглаженная прокачка, PvP по выбору."),
        section("what-to-expect", "Зачем нужен LST", "Прежде всего нагрузочный тест: очереди, длинные загрузки и возможные хотфиксы. Контент модифицированного Сезона 1 — считайте это превью, а не финальным состоянием."),
        section("how-to-prepare", "Подготовка на этой неделе", "1. Предзагрузить 16-го; 2. Проверить DLSS 4.5 во время теста; 3. Проверить геймпад; 4. Оценить дизайн без ограничений; 5. Пощупать подписку $15 на практике."),
        section("whats-next", "После LST", "Ранний доступ Founder's Pack — 30 сентября, бесплатный запуск — 5 октября (модифицированный Сезон 1). Гайд по подготовке к LST на сайте покрывает детали."),
      ],
    }),
    ko: articleCopy(newsLabels, "ko", 5, {
      eyebrow: "런치 카운트다운",
      title: "Aion 2 런치 스케일 테스트 6일 전: 9/16 사전 다운로드, 9/17-18 진행, 공지 이후 확인된 것들",
      description: "무료 규모 테스트(LST)는 9월 17-18일에 진행되며 9월 16일부터 사전 다운로드——6일 앞으로. 공지 이후 DLSS 4.5 적용·DLSS 5 개발 중, 컨트롤러 지원, $15 멤버십, 일일/주간 게이트 없는 QoL 빌드가 확인됐습니다",
      intro: "Aion 2 무료 규모 테스트(LST)가 6일 앞으로 다가왔습니다: 9월 16일 사전 다운로드, 9월 17-18일 Steam으로 진행. 공지 이후 NC는 입장 전에 알아두면 좋은 세부 사항들을 다수 확인시켜 줬습니다——DLSS와 컨트롤러 지원부터 $15 멤버십, 데일리 게이트 없는 빌드까지.",
      sourceNote: "공식 Steam 규모 테스트 공지(2026-08-26 발행)와 Wccftech 2026년 9월 7일자 Aion 2 팀 인터뷰(『공지 이후 확인』 부분, 모두 2026-09-11 확인)를 기반으로 했습니다.",
      keywords: ["아이온2 런치 스케일 테스트 9월", "아이온2 LST 9월16일 사전 다운로드", "아이온2 규모 테스트 카운트다운", "아이온2 무료 테스트 Steam 2026년 9월"],
      sections: [
        section("countdown", "LST까지 6일", "무료 규모 테스트는 9월 17-18일, 사전 다운로드는 9월 16일부터 시작됩니다. 10월 5일 글로벌 출시 전 마지막 공개 테스트이며, 서버 용량 검증 참여라는 의미와 함께 QoL 변경 사항의 실전 점검 역할도 합니다."),
        section("what-we-learned", "공지 이후 확인된 것들", "성능: DLSS 4.5가 게임 내 적용돼 있고, DLSS 5는 NVIDIA와 공동 개발 중임이 확인됐습니다. 컨트롤러 지원, 글로벌은 당분간 PC 전용(Steam+PURPLE), 콘솔 버전은 준비 중입니다. 경제: 이중 구독을 월 $15 단일 멤버십으로 통합, 파운더스 팩에 30일 포함. 설계: 일일/주간 콘텐츠 게이트 없음, 성장 곡선의 유연화, PvP는 선택 참여."),
        section("what-to-expect", "LST의 역할", "우선은 규모 테스트입니다: 부하 상황의 서버 용량과 매칭을 검증합니다. 대기열·긴 로딩·핫픽스가 있을 수 있습니다——인프라 문제 발견이 목적이며 최종 밸런스 다듬기가 아닙니다."),
        section("how-to-prepare", "이번 주 준비법", "1. 9월 16일에 사전 다운로드; 2. 테스트 중 DLSS 4.5 기준으로 GPU 설정 점검(출시 성능 목표); 3. 컨트롤러 입력 확인; 4. 게이트 없는 설계 체감; 5. $15 멤버십의 기능을 실전으로 평가."),
        section("whats-next", "LST 이후", "파운더스 팩 선행 접속은 9월 30일, F2P 글로벌 출시는 10월 5일(수정판 시즌 1). 본 사이트의 LST 준비 가이드와 출시 접근 경로 가이드가 자세한 절차를 다룹니다——셋업 점검은 출시 당일이 아니라 지금입니다."),
      ],
    }),
    "zh-hant": articleCopy(newsLabels, "zh-hant", 5, {
      eyebrow: "上線倒數",
      title: "Aion 2 規模測試 6 天後舉行：9 月 16 日預載、9 月 17-18 日測試，及公告後確認的新事實",
      description: "免費規模測試（LST）9 月 17-18 日舉行、9 月 16 日開放預載——就在 6 天後；公告以來已確認 DLSS 4.5 上線/DLSS 5 開發中、手把支援、$15 會員與無日常/週常門檻的 QoL 全球版",
      intro: "Aion 2 免費規模測試（LST）就在 6 天後：9 月 16 日開放預載，9 月 17-18 日經 Steam 測試。自公告以來，NCsoft 確認了一批入場前值得了解的細節——從 DLSS 與手把支援，到 $15 會員與無日常門檻版本。",
      sourceNote: "基於官方 Steam 規模測試公告（2026-08-26 發布）與 Wccftech 2026 年 9 月 7 日對 Aion 2 團隊的專訪（「公告後確認」部分）（均於 2026-09-11 抓取）。",
      keywords: ["Aion 2 規模測試 9月", "Aion 2 LST 9月16日預載", "Aion 2 規模測試倒數", "Aion 2 規模測試 內容", "Aion 2 免費測試 Steam 2026年9月"],
      sections: [
        section("countdown", "距離規模測試 6 天", ["免費規模測試（LST）於 9 月 17-18 日舉行，9 月 16 日起開放預載。測試對所有玩家免費、經 Steam 頁面進入，是 10 月 5 日全球首發前的最後一次公開測試。", "作為伺服器容量測試，參與不僅能幫 NCsoft 檢驗基礎設施——也是在 Season 1 上線前對 QoL 改動的一次真實檢驗。"]),
        section("what-we-learned", "公告之後確認的新事實", ["效能：DLSS 4.5 已在遊戲內上線，NVIDIA DLSS 5 確認正與 NC 聯合開發中。PC 支援手把，全球版現階段僅 PC（Steam+PURPLE 啟動器），主機版在全球首發之後籌備中。", "經濟：雙訂閱系統整合為每月 $15 單一會員，創辦人包附帶 30 天會員。設計：全球版無日常/週常內容門檻、物品成長曲線平滑化、PvP 變為可選。"]),
        section("what-to-expect", "測試的作用", ["LST 首先是規模測試：驗證負載下的伺服器容量與匹配。期間可能遇到排隊、較長載入與熱修——目的是發現基礎設施問題，而非打磨最終平衡。", "它也會運行全球 Season 1 將搭載的、已在韓服驗證的機制與內容結構——把體驗視為改良版 Season 1 的預覽，而非最終的日後狀態。"]),
        section("how-to-prepare", "本週如何準備", ["1. 9 月 16 日預載，測試開啟即可進入；2. 測試期間對照 DLSS 4.5 基線檢查顯示卡設定——這是首發效能目標；3. 手把使用者確認自己的設定下輸入正常；4. 體驗無門檻設計：可按自己的節奏體驗類終局內容，無需日常堆疊；5. 若考慮 $15 會員，可在測試中實評其覆蓋功能，而非猜測。"]),
        section("whats-next", "測試之後的路", ["LST 之後，創辦人包持有者 9 月 30 日起搶先體驗，免費制全球首發 10 月 5 日上線——改良版 Season 1，儲備約一年韓服內容，之後以三個月一季落後韓服。", "如果你是新人，本站的規模測試準備指南與上線訪問路徑指南有詳細步驟——這個倒數提醒你：現在就該測試配置，而不是上線當天。"]),
      ],
    }),
  },
};