import { articleCopy, localizations, newsLabels, publishedVerified, section } from "./trending-september-12-shared";
import type { ContentEntry, ContentHeroImage, ContentSource } from "./content-registry";

/* ARTICLE 3 — Analyst cuts NC target price as Aion 2's KR/TW revenue decline runs steeper than expected; global launch risk flagged */

const newsquestSource: ContentSource = {
  id: "newsquest-aion2-global-revenue-risk-2026-09-10",
  kind: "third-party",
  publisher: "Newsquest (뉴스퀘스트)",
  label: "User Complaints Become Results... As Aion 2 Stumbles, Warning Lights for NC's Global Revenue",
  url: "https://www.newsquest.co.kr/news/articleView.html?idxno=300674",
  publishedAt: "2026-09-10",
  retrievedAt: "2026-09-12",
  verifiedAt: "2026-09-12",
  localizations: localizations({
    "zh-hans": "用户不满成为业绩…Aion 2 步履蹒跚，NC 全球营收亮起警示灯",
    en: "User Complaints Become Results... As Aion 2 Stumbles, Warning Lights for NC's Global Revenue",
    fr: "Les plaintes des joueurs deviennent des résultats… Aion 2 trébuche, NC voit ses revenus globaux clignoter",
    de: "Nutzerbeschwerden werden zu Zahlen… Aion 2 stolpert, NCs globale Einnahmen warnen",
    es: "Las quejas de los usuarios se vuelven resultados… Aion 2 tropieza y las alarmas se encienden para los ingresos globales de NC",
    ja: "ユーザー不満が業績に…Aion 2 がつまずき、NCのグローバル売上に警告灯",
    "pt-br": "Reclamações de usuários viram resultados... Aion 2 tropeça e os alarmes acendem para a receita global da NC",
    ru: "Недовольство игроков становится результатами… Aion 2 спотыкается, у NC загораются огни тревоги по глобальной выручке",
    ko: "유저 불만이 실적으로…'아이온2' 삐걱대자 NC 글로벌 매출에도 경고등",
    "zh-hant": "使用者不滿成為業績…Aion 2 步履蹣跚，NC 全球營收亮起警示燈",
  }, "https://www.newsquest.co.kr/news/articleView.html?idxno=300674"),
};

const rHero: ContentHeroImage = {
  src: "https://blogfiles.ncsoft.net/news/af7330da-4ff6-4b58-aece-400e6061a3be.jpg",
  width: 1200, height: 630,
  credit: "NC Corporation",
  sourceUrl: "https://aion2.plaync.com/en-us/",
  rights: "linked-official-media",
  translations: {
    "zh-hans": { alt: "Aion 2 全球营收风险分析新闻横幅", caption: "Kiwoom 证券维持 BUY 但把 NC 目标价从 43 万降至 35 万韩元：Aion 2 在韩服/台服的收入下滑快于预期（平衡不满驱动），并把该模式延伸至 10/5 全球版预估。" },
    en: { alt: "Aion 2 global revenue risk analysis news banner", caption: "Kiwoom Securities keeps BUY but cuts NC's target price from 430,000 to 350,000 KRW: Aion 2's Korea/Taiwan revenue decline is running steeper than expected on balance dissatisfaction, and the pattern is being applied to the October 5 global estimates." },
    fr: { alt: "Bannière d'analyse du risque de revenus globaux d'Aion 2", caption: "Kiwoom Securities garde BUY mais abaisse l'objectif de NC de 430 000 à 350 000 KRW : le déclin des revenus coréens/taiwanais d'Aion 2 est plus rapide que prévu, et le schéma est appliqué aux estimations globales du 5 octobre." },
    de: { alt: "Analyse-Banner zum globalen Umsatzrisiko von Aion 2", caption: "Kiwoom Securities hält BUY, senkt aber das Kursziel von NC von 430 000 auf 350 000 KRW: Aion 2s Korea/Taiwan-Umsatzrückgang läuft schneller als erwartet, das Muster wird auf die Global-Schätzungen (5. Oktober) angewendet." },
    es: { alt: "Banner de análisis del riesgo de ingresos globales de Aion 2", caption: "Kiwoom Securities mantiene BUY pero recorta el precio objetivo de NC de 430.000 a 350.000 KRW: la caída de ingresos de Aion 2 en Corea/Taiwán es más pronunciada de lo previsto y el patrón se aplica a las estimaciones globales del 5 de octubre." },
    ja: { alt: "Aion 2 グローバル売上リスク分析ニュースバナー", caption: "Kiwoom証券はBUY維持もNC目標株価を43万→35万ウォンに引き下げ：Aion 2の韓国・台湾売上がバランス不満により想定より速く低下、10月5日のグローバル予想にも同パターンを適用。" },
    "pt-br": { alt: "Banner de análise do risco de receita global do Aion 2", caption: "A Kiwoom Securities mantém BUY mas corta o preço-alvo da NC de 430.000 para 350.000 KRW: a queda de receita do Aion 2 na Coreia/Taiwan é mais rápida que o previsto e o padrão é aplicado às estimativas globais de 5 de outubro." },
    ru: { alt: "Баннер анализа глобального риска выручки Aion 2", caption: "Kiwoom Securities держит BUY, но снижает целевую цену NC с 430 000 до 350 000 KRW: спад выручки Aion 2 в Корее/Тайване быстрее ожиданий, паттерн применяется к глобальным оценкам 5 октября." },
    ko: { alt: "Aion 2 글로벌 매출 리스크 분석 뉴스 배너", caption: "키움증권이 BUY를 유지하면서도 NC 목표주가를 43만→35만 원으로 낮췄습니다: 아이온2의 한국·대만 매출 하락이 밸런스 불만으로 예상보다 가파르며, 10/5 글로벌 추정치에도 같은 패턴을 적용합니다." },
    "zh-hant": { alt: "Aion 2 全球營收風險分析新聞橫幅", caption: "Kiwoom 證券維持 BUY 但把 NC 目標價從 43 萬降至 35 萬韓元：Aion 2 在韓服/台服的收入下滑快於預期（平衡不滿驅動），並把該模式延伸至 10/5 全球版預估。" },
  },
};

export const trendingSeptember12Article3: ContentEntry = {
  section: "news",
  slug: "aion-2-global-launch-revenue-risk-analysis",
  schemaType: "NewsArticle",
  publishedAt: "2026-09-12",
  updatedAt: "2026-09-12",
  readingMinutes: 5,
  publication: publishedVerified,
  sources: [newsquestSource],
  heroImage: rHero,
  related: [
    { kind: "content", section: "news", slug: "aion-2-nc-chuseok-offensive" },
    { kind: "content", section: "news", slug: "aion-2-nc-two-track-global-strategy-shooters" },
    { kind: "content", section: "guides", slug: "aion-2-global-version-changes-guide" },
    { kind: "content", section: "news", slug: "aion-2-western-launch-monetization-model-details" },
  ],
  translations: {
    en: articleCopy(newsLabels, "en", 5, {
      eyebrow: "MARKET ANALYSIS",
      title: "Aion 2 Global Launch Under the Microscope: Analyst Cuts NC Target as Korea/Taiwan Revenue Declines Steeper Than Expected",
      description: "Kiwoom Securities keeps a BUY rating but cuts NCsoft's target price from 430,000 to 350,000 KRW, citing Aion 2's steeper-than-expected Korea/Taiwan revenue decline on balance dissatisfaction — and flagging the risk that the pattern repeats globally after October 5",
      intro: "With Aion 2's global launch 23 days away, the market is starting to price the risk. Kiwoom Securities lowered NCsoft's target price from 430,000 to 350,000 KRW (BUY maintained), pointing to Aion 2's steeper-than-expected revenue decline in Korea and Taiwan driven by growing balance dissatisfaction — and applying that pattern to next year's global estimates.",
      sourceNote: "Based on Newsquest's September 10, 2026 report of Kiwoom Securities' analysis (retrieved September 12, 2026). Figures are analyst estimates; the Korean service data reflects post-launch trends, not the global build.",
      keywords: ["Aion 2 global launch revenue risk", "NCsoft target price cut Kiwoom", "Aion 2 Korea Taiwan revenue decline", "Aion 2 balance dissatisfaction analysts", "NC stock Aion 2 October 5"],
      sections: [
        section("the-cut", "Target Price Cut to 350,000 KRW", ["Kiwoom Securities maintained its BUY rating but cut NCsoft's target price from 430,000 to 350,000 KRW — a new target derived from 2026 controlling-shareholder equity of 503.3 billion KRW at a 15x target PER. NC closed at 210,500 KRW on September 9.", "The cut is a judgment on Aion 2 specifically: the revenue decline in existing regions (Korea and Taiwan) is running steeper than prior estimates, so peak normalized profit is now attributed to 2026."]),
        section("why", "The Driver: Post-Launch Balance Dissatisfaction", ["The report links the steeper decline to growing user dissatisfaction with Aion 2's game balance after launch — the same balance conversation the site has covered in the Korea update coverage, from the Abyss rework to the new raid's difficulty curve.", "Note the timing: Korea's 9/9 update (Snowfield of Sorrow, Abyss rework, Seal system) landed the same week, and the Sep 10-11 enforcement actions (piloting bans) show NC is actively managing the live-service environment."]),
        section("global-risk", "The Global Risk: Applying the Korea/Taiwan Pattern", ["The key warning: the Korea/Taiwan decline pattern is being '준용' (applied by analogy) to next year's estimates, out of concern that global regions could see a similar decline after the October 5 launch.", "The global launch first-quarter revenue estimate is 158.5 billion KRW. NC's 2026 estimates stand at 2.8694 trillion KRW revenue (+90.4% YoY) and 551.6 billion KRW operating profit (+3,426%), with 2027 at 3.0776 trillion / 506.2 billion KRW."]),
        section("the-numbers", "The Numbers at a Glance", ["Target price 430,000 → 350,000 KRW (BUY held); Sep 9 close 210,500 KRW; 2026E revenue 2.8694 trillion KRW (+90.4%), OP 551.6 billion KRW (+3,426%); 2027E 3.0776 trillion / 506.2 billion; global launch Q4 revenue estimate 158.5 billion KRW.", "The operating profit estimate was cut more than the top line, because Aion 2 and Lineage Classic carry lower contribution margins — revenue mix matters as much as total growth."]),
        section("what-it-means", "What It Means", ["For players, the analyst debate is about revenue persistence, not playability — and it frames the pressure NC is under to make the modified Season 1 land well on October 5.", "For the global launch, the mitigating factors are real: the global build ships the QoL and balance improvements confirmed in the September 7 interview (no daily/weekly gates, smoothed progression, PvP optional), which directly address the dissatisfaction pattern analysts point to."]),
      ],
    }),
    "zh-hans": articleCopy(newsLabels, "zh-hans", 5, {
      eyebrow: "市场分析",
      title: "Aion 2 全球首发接受审视：分析师下调 NC 目标价——韩服/台服收入下滑快于预期",
      description: "Kiwoom 证券维持 BUY 但把 NCsoft 目标价从 43 万降至 35 万韩元，理由是 Aion 2 韩服/台服收入因平衡不满而下滑快于预期——并提示该模式可能在 10 月 5 日全球版重演",
      intro: "距 Aion 2 全球首发还有 23 天，市场开始为此定价。Kiwoom 证券把 NCsoft 目标价从 43 万降至 35 万韩元（维持 BUY），指出 Aion 2 韩服/台服收入因日益增长的平衡不满而下滑快于预期——并把该模式延伸到明年的全球版预估。",
      sourceNote: "基于 뉴스퀘스트（Newsquest）2026 年 9 月 10 日对 Kiwoom 证券分析的报道（2026-09-12 抓取）。数字为分析师预估；韩服数据反映的是上线后趋势，并非全球版。",
      keywords: ["Aion 2 全球首发 营收风险", "NCsoft 目标价下调 Kiwoom", "Aion 2 韩服台服 收入下滑", "Aion 2 平衡不满 分析师", "NC 股价 Aion 2 10月5日"],
      sections: [
        section("the-cut", "目标价下调至 35 万韩元", ["Kiwoom 证券维持 BUY 评级，但把 NCsoft 目标价从 43 万降至 35 万韩元——新目标由 2026 年控股股东权益 5,033 亿韩元 × 目标 PER 15 倍得出。NC 于 9 月 9 日收于 210,500 韩元。", "下调针对的正是 Aion 2：现有地区（韩服与台服）收入下滑快于此前预估，因此常态利润峰值被归到 2026 年。"]),
        section("why", "驱动因素：上线后的平衡不满", ["报告把更陡的下滑与上线后日益增长的 Aion 2 游戏平衡不满联系起来——即本站韩服更新报道中持续追踪的平衡议题，从深渊改版到新副本的难度曲线。", "注意时点：韩服 9 月 9 日更新（Snowfield of Sorrow、深渊改版、印章系统）与报告同周落地，9 月 10-11 的执法行动（代练封禁）也说明 NC 正在积极管理长线运营环境。"]),
        section("global-risk", "全球版风险：套用韩服/台服模式", ["关键警告：韩服/台服下滑模式正被「準用」（类推）到明年的预估中——担心全球地区在 10 月 5 日上线后出现类似下滑。", "全球版首发当季收入预估为 1,585 亿韩元。NC 2026 年预估：营收 2.8694 万亿韩元（+90.4%）、营业利润 5,516 亿韩元（+3,426%）；2027 年为 3.0776 万亿 / 5,062 亿韩元。"]),
        section("the-numbers", "数字一览", ["目标价 43 万 → 35 万韩元（维持 BUY）；9 月 9 日收盘 210,500 韩元；2026E 营收 2.8694 万亿（+90.4%）、营业利润 5,516 亿（+3,426%）；2027E 3.0776 万亿 / 5,062 亿；全球版首发 Q4 收入预估 1,585 亿韩元。", "营业利润预估的下调幅度大于营收——因为 Aion 2 与天堂经典版的贡献利润率较低：收入结构几乎与总量增长同等重要。"]),
        section("what-it-means", "意义", ["对玩家，分析师之争关乎收入持续性而非可玩性——它框定了 NC 在 10 月 5 日让改良版 Season 1 落好所承受的压力。", "对全球首发，缓解因素真实存在：全球版搭载 9 月 7 日专访确认的 QoL 与平衡改进（无日常/周常门槛、成长平滑化、PvP 可选），直接针对分析师所指的不满模式。"]),
      ],
    }),
    fr: articleCopy(newsLabels, "fr", 5, {
      eyebrow: "ANALYSE MARCHÉ",
      title: "Le lancement global d'Aion 2 sous la loupe : l'analyste baisse l'objectif de NC, le déclin Corée/Taïwan plus rapide que prévu",
      description: "Kiwoom Securities garde BUY mais abaisse l'objectif de NCsoft de 430 000 à 350 000 KRW : déclin des revenus coréens/taiwanais d'Aion 2 plus rapide que prévu (insatisfaction d'équilibrage), risque que le schéma se répète après le 5 octobre",
      intro: "À 23 jours du lancement global, le marché commence à intégrer le risque. Kiwoom Securities a abaissé l'objectif de NCsoft de 430 000 à 350 000 KRW (BUY maintenu), citant le déclin plus rapide que prévu des revenus coréens/taiwanais d'Aion 2 et appliquant ce schéma aux estimations globales.",
      sourceNote: "Basé sur le rapport de Newsquest du 10 septembre 2026 sur l'analyse de Kiwoom Securities (récupéré le 12 septembre 2026). Estimations d'analystes ; les données coréennes reflètent les tendances post-lancement.",
      keywords: ["Aion 2 risque revenus lancement global", "NCsoft objectif abaissé Kiwoom", "Aion 2 déclin Corée Taïwan", "Aion 2 insatisfaction équilibrage analystes", "NC action Aion 2 5 octobre"],
      sections: [
        section("the-cut", "Objectif abaissé à 350 000 KRW", "Kiwoom garde BUY mais abaisse l'objectif de 430 000 à 350 000 KRW (équité 2026 de 503,3 Md KRW × PER 15x) ; NC a clôturé à 210 500 KRW le 9 septembre. La coupe vise Aion 2 : déclin KR/TW plus rapide que prévu."),
        section("why", "Le moteur : l'insatisfaction d'équilibrage", "Le déclin est lié à l'insatisfaction croissante sur l'équilibrage post-lancement. Contexte : l'update du 9 septembre (Snowfield of Sorrow, refonte Abyss, système de Sceaux) est tombé la même semaine ; les actions du 10-11 (bans de pilotage) montrent une gestion active."),
        section("global-risk", "Le risque global : appliquer le schéma KR/TW", "Le schéma de déclin est « appliqué par analogie » aux estimations 2027 par crainte d'un déclin similaire après le 5 octobre. Estimation T1 global : 158,5 Md KRW ; NC 2026 : 2,8694 T (+90,4 %) / 551,6 Md OP (+3 426 %) ; 2027 : 3,0776 T / 506,2 Md."),
        section("the-numbers", "Les chiffres", "Objectif 430 000 → 350 000 KRW (BUY) ; clôture 210 500 ; 2026E 2,8694 T / 551,6 Md ; 2027E 3,0776 T / 506,2 Md ; T1 global 158,5 Md. L'OP a été coupé plus que le CA : marges de contribution plus faibles pour Aion 2 et Lineage Classic."),
        section("what-it-means", "Ce que ça signifie", "Pour les joueurs, c'est une question de persistance des revenus, pas de jouabilité — et le cadre de la pression sur la Saison 1 modifiée. Atténuants réels : QoL et équilibrage du 7 septembre (sans seuils, progression lissée, PvP optionnel)."),
      ],
    }),
    de: articleCopy(newsLabels, "de", 5, {
      eyebrow: "MARKTANALYSE",
      title: "Aion 2 Global-Start unter der Lupe: Analyst senkt NC-Kursziel, Korea/Taiwan-Umsätze fallen schneller als erwartet",
      description: "Kiwoom Securities hält BUY, senkt aber das Kursziel von 430 000 auf 350 000 KRW: Aion 2s Korea/Taiwan-Umsatzrückgang läuft schneller als erwartet (Balance-Unzufriedenheit), Risiko einer Wiederholung nach dem 5. Oktober",
      intro: "23 Tage vor dem Global-Start beginnt der Markt, das Risiko einzupreisen. Kiwoom Securities senkte das Kursziel von NCsoft von 430 000 auf 350 000 KRW (BUY gehalten) — Aion 2s Korea/Taiwan-Umsatzrückgang läuft schneller als erwartet, das Muster wird auf die Global-Schätzungen übertragen.",
      sourceNote: "Basierend auf dem Newsquest-Bericht vom 10. September 2026 über die Analyse von Kiwoom Securities (abgerufen am 12. September 2026). Analystenschätzungen; Korea-Daten spiegeln Post-Launch-Trends.",
      keywords: ["Aion 2 Global-Start Umsatzrisiko", "NCsoft Kursziel Senkung Kiwoom", "Aion 2 Korea Taiwan Umsatzrückgang", "Aion 2 Balance-Unzufriedenheit Analysten", "NC Aktie Aion 2 5. Oktober"],
      sections: [
        section("the-cut", "Kursziel auf 350 000 KRW gesenkt", "Kiwoom hält BUY, senkt aber von 430 000 auf 350 000 KRW (2026-Eigenkapital 503,3 Mrd. × PER 15x); NC schloss am 9. September bei 210 500 KRW. Die Senkung zielt auf Aion 2: KR/TW-Rückgang schneller als erwartet."),
        section("why", "Der Treiber: Balance-Unzufriedenheit", "Der Rückgang wird mit wachsender Unzufriedenheit über die Balance verbunden. Kontext: Das Update vom 9. September (Snowfield of Sorrow, Abyss-Überarbeitung, Seal-System) kam dieselbe Woche; die Maßnahmen vom 10.-11. (Piloten-Sperren) zeigen aktives Live-Service-Management."),
        section("global-risk", "Das Global-Risiko: Muster-Übertragung", "Das KR/TW-Muster wird analog auf 2027 übertragen — Sorge vor ähnlichem Rückgang nach dem 5. Oktober. Global T1-Schätzung: 158,5 Mrd. KRW; NC 2026: 2,8694 Bio. (+90,4 %) / 551,6 Mrd. OP (+3 426 %); 2027: 3,0776 Bio. / 506,2 Mrd."),
        section("the-numbers", "Die Zahlen", "Kursziel 430 000 → 350 000 KRW (BUY); Schlusskurs 210 500; 2026E 2,8694 Bio. / 551,6 Mrd.; 2027E 3,0776 Bio. / 506,2 Mrd.; Global T1 158,5 Mrd. OP stärker gesenkt als Umsatz: niedrigere Beitragsmargen von Aion 2 und Lineage Classic."),
        section("what-it-means", "Was das bedeutet", "Für Spieler geht es um Umsatzpersistenz, nicht Spielbarkeit — und um den Druck auf die modifizierte Season 1. Echte Abschwächung: QoL und Balance vom 7. September (keine Gates, geglättete Progression, optionales PvP)."),
      ],
    }),
    es: articleCopy(newsLabels, "es", 5, {
      eyebrow: "ANÁLISIS DE MERCADO",
      title: "El lanzamiento global de Aion 2 bajo la lupa: el analista recorta el objetivo de NC, el declive Corea/Taiwán es más pronunciado de lo previsto",
      description: "Kiwoom Securities mantiene BUY pero recorta el objetivo de NCsoft de 430.000 a 350.000 KRW: declive de ingresos de Aion 2 en Corea/Taiwán más rápido de lo previsto (insatisfacción de equilibrio), riesgo de repetición tras el 5 de octubre",
      intro: "A 23 días del lanzamiento global, el mercado empieza a descontar el riesgo. Kiwoom Securities recortó el objetivo de NCsoft de 430.000 a 350.000 KRW (BUY mantenido), citando el declive más rápido de lo previsto en Corea/Taiwán y aplicando ese patrón a las estimaciones globales.",
      sourceNote: "Basado en el informe de Newsquest del 10 de septiembre de 2026 sobre el análisis de Kiwoom Securities (recuperado el 12 de septiembre de 2026). Estimaciones de analistas; los datos coreanos reflejan tendencias posteriores al lanzamiento.",
      keywords: ["Aion 2 riesgo ingresos lanzamiento global", "NCsoft objetivo recortado Kiwoom", "Aion 2 declive Corea Taiwán", "Aion 2 insatisfacción equilibrio analistas", "NC acción Aion 2 5 octubre"],
      sections: [
        section("the-cut", "Objetivo recortado a 350.000 KRW", "Kiwoom mantiene BUY pero recorta de 430.000 a 350.000 KRW (equidad 2026 de 503,3 mil millones × PER 15x); NC cerró a 210.500 el 9 de septiembre. El recorte apunta a Aion 2: declive KR/TW más rápido de lo previsto."),
        section("why", "El motor: insatisfacción de equilibrio", "El declive se vincula a la insatisfacción creciente con el equilibrio post-lanzamiento. Contexto: el update del 9 de septiembre (Snowfield of Sorrow, reforma de Abyss, sistema de Sellos) cayó la misma semana; las acciones del 10-11 (bans de pilotaje) muestran gestión activa."),
        section("global-risk", "El riesgo global: aplicar el patrón KR/TW", "El patrón de declive se aplica por analogía a 2027 por temor a un declive similar tras el 5 de octubre. Estimación T1 global: 158,5 mil millones; NC 2026: 2,8694 billones (+90,4 %) / 551,6 mil millones de OP (+3 426 %); 2027: 3,0776 billones / 506,2 mil millones."),
        section("the-numbers", "Los números", "Objetivo 430.000 → 350.000 KRW (BUY); cierre 210.500; 2026E 2,8694 billones / 551,6 mil millones; 2027E 3,0776 billones / 506,2 mil millones; T1 global 158,5 mil millones. El OP se recortó más que el ingreso: menores márgenes de contribución de Aion 2 y Lineage Classic."),
        section("what-it-means", "Qué significa", "Para los jugadores, es una cuestión de persistencia de ingresos, no de jugabilidad — y el marco de la presión sobre la Temporada 1 modificada. Mitigantes reales: QoL y equilibrio del 7 de septiembre (sin límites, progresión suavizada, PvP opcional)."),
      ],
    }),
    ja: articleCopy(newsLabels, "ja", 5, {
      eyebrow: "市場分析",
      title: "Aion 2 グローバルローンチを再点検：アナリストがNC目標株価を引き下げ——韓国・台湾の売上低下が想定より速く",
      description: "Kiwoom証券はBUY維持もNC目標株価を43万→35万ウォンに引き下げ：Aion 2の韓国・台湾売上がバランス不満で想定より速く低下、10月5日以降のグローバルでも同パターンが繰り返されるリスクを警告",
      intro: "グローバルローンチまで23日、市場はリスクを織り込み始めました。Kiwoom証券はNC目標株価を43万→35万ウォンに引き下げ（BUY維持）。韓国・台湾でのAion 2売上低下がバランス不満により想定より速いとし、そのパターンを来年のグローバル予想に適用しています。",
      sourceNote: "ニュースクエスト2026年9月10日付のKiwoom証券分析報道（2026-09-12取得）に基づきます。数字はアナリスト推定で、韓国データはローンチ後のトレンドを反映します。",
      keywords: ["Aion 2 グローバルローンチ 売上リスク", "NCsoft 目標株価 引き下げ Kiwoom", "Aion 2 韓国 台湾 売上低下", "Aion 2 バランス不満 アナリスト", "NC 株 Aion 2 10月5日"],
      sections: [
        section("the-cut", "目標株価35万ウォンへ", "Kiwoom証券はBUYを維持しつつ目標株価を43万→35万ウォンに引き下げました（2026年支配株主持分5,033億ウォン×目標PER15倍）。NCは9月9日に210,500ウォンで終値。引き下げはAion 2が対象：韓国・台湾の売上低下が想定より速いため、正常化利益のピークは2026年に帰属されました。"),
        section("why", "要因：ローンチ後のバランス不満", "報告は急な低下を、ローンチ後に高まるゲームバランスへの不満と結び付けています——本サイトの韓国アップデート報道（アビス改修、新レイドの難易度曲線）で追ってきたテーマです。9月9日のアップデート（Snowfield of Sorrow、アビス改修、シールシステム）は同じ週に投入され、9月10-11日の代行取り締まりもライブサービス運営を積極管理していることを示します。"),
        section("global-risk", "グローバルリスク：KR/TWパターンの適用", "重要な警告：韓国・台湾の低下パターンは「準用」され、10月5日以降のグローバルで同様の低下があり得るという懸念から来年の予想に適用されています。グローバル初四半期売上は1,585億ウォン。NC 2026年予想：売上2兆8,694億（+90.4%）、営業利益5,516億（+3,426%）；2027年は3兆776億／5,062億ウォン。"),
        section("the-numbers", "数字の要点", "目標株価43万→35万ウォン（BUY維持）；9月9日終値210,500ウォン；2026E売上2兆8,694億（+90.4%）・営業利益5,516億（+3,426%）；2027E 3兆776億／5,062億；グローバルT1売上1,585億。営業利益の下方修正が売上より大きいのは、Aion 2とリネージュクラシックの貢献利益率が低いためです。"),
        section("what-it-means", "意味するところ", "プレイヤーにとってこの論争は、プレイアビリティではなく売上の持続性についてです——10月5日に改良版シーズン1を着地させるプレッシャーの枠組みでもあります。緩和要素は現実にあります：グローバルは9月7日インタビュー確認済みのQoL・バランス改善（ゲートなし、成長の平滑化、PvP任意）を搭載し、アナリストが指す不満パターンに直接対応します。"),
      ],
    }),
    "pt-br": articleCopy(newsLabels, "pt-br", 5, {
      eyebrow: "ANÁLISE DE MERCADO",
      title: "O lançamento global do Aion 2 sob a lupa: analista corta o alvo da NC, queda de receita Coreia/Taiwan mais rápida que o previsto",
      description: "A Kiwoom Securities mantém BUY mas corta o alvo da NCsoft de 430.000 para 350.000 KRW: queda de receita do Aion 2 na Coreia/Taiwan mais rápida que o previsto (insatisfação de equilíbrio), risco de repetição após 5 de outubro",
      intro: "A 23 dias do lançamento global, o mercado começa a precificar o risco. A Kiwoom Securities cortou o alvo da NCsoft de 430.000 para 350.000 KRW (BUY mantido), citando a queda mais rápida que o previsto na Coreia/Taiwan e aplicando esse padrão às estimativas globais.",
      sourceNote: "Baseado no relatório da Newsquest de 10 de setembro de 2026 sobre a análise da Kiwoom Securities (recuperado em 12 de setembro de 2026). Estimativas de analistas; os dados coreanos refletem tendências pós-lançamento.",
      keywords: ["Aion 2 risco receita lançamento global", "NCsoft alvo cortado Kiwoom", "Aion 2 queda Coreia Taiwan", "Aion 2 insatisfação equilíbrio analistas", "NC ação Aion 2 5 outubro"],
      sections: [
        section("the-cut", "Alvo cortado para 350.000 KRW", "A Kiwoom mantém BUY mas corta de 430.000 para 350.000 KRW (equidade 2026 de 503,3 bilhões × PER 15x); a NC fechou a 210.500 em 9 de setembro. O corte mira o Aion 2: queda KR/TW mais rápida que o previsto."),
        section("why", "O motor: insatisfação de equilíbrio", "A queda é ligada à insatisfação crescente com o equilíbrio pós-lançamento. Contexto: o update de 9 de setembro (Snowfield of Sorrow, reforma do Abismo, sistema de Selos) caiu na mesma semana; as ações de 10-11 (bans de pilotagem) mostram gestão ativa."),
        section("global-risk", "O risco global: aplicar o padrão KR/TW", "O padrão de queda é aplicado por analogia a 2027, com receio de queda similar após 5 de outubro. Estimativa T1 global: 158,5 bilhões; NC 2026: 2,8694 trilhões (+90,4%) / 551,6 bilhões de OP (+3.426%); 2027: 3,0776 trilhões / 506,2 bilhões."),
        section("the-numbers", "Os números", "Alvo 430.000 → 350.000 KRW (BUY); fechamento 210.500; 2026E 2,8694 trilhões / 551,6 bilhões; 2027E 3,0776 trilhões / 506,2 bilhões; T1 global 158,5 bilhões. O OP foi cortado mais que a receita: margens de contribuição menores de Aion 2 e Lineage Classic."),
        section("what-it-means", "O que significa", "Para jogadores, é uma questão de persistência de receita, não de jogabilidade — e o quadro da pressão sobre a Temporada 1 modificada. Mitigantes reais: QoL e equilíbrio de 7 de setembro (sem limites, progressão suavizada, PvP opcional)."),
      ],
    }),
    ru: articleCopy(newsLabels, "ru", 5, {
      eyebrow: "РЫНОЧНЫЙ АНАЛИЗ",
      title: "Глобальный запуск Aion 2 под лупой: аналитик снижает таргет NC, спад Кореи/Тайваня быстрее ожиданий",
      description: "Kiwoom Securities держит BUY, но снижает целевую цену NCsoft с 430 000 до 350 000 KRW: спад выручки Aion 2 в Корее/Тайване быстрее ожиданий (недовольство балансом), риск повторения после 5 октября",
      intro: "За 23 дня до глобального запуска рынок начинает закладывать риск. Kiwoom Securities снизила целевую цену NCsoft с 430 000 до 350 000 KRW (BUY сохранён), указав на более быстрый, чем ожидалось, спад выручки Aion 2 в Корее/Тайване и применив этот паттерн к глобальным оценкам.",
      sourceNote: "На основе отчёта Newsquest от 10 сентября 2026 г. об анализе Kiwoom Securities (получен 12 сентября 2026 г.). Оценки аналитиков; корейские данные отражают тренды после запуска.",
      keywords: ["Aion 2 риск выручки глобальный запуск", "NCsoft снижение таргета Kiwoom", "Aion 2 спад Корея Тайвань", "Aion 2 недовольство балансом аналитики", "NC акции Aion 2 5 октября"],
      sections: [
        section("the-cut", "Таргет снижен до 350 000 KRW", "Kiwoom держит BUY, но снижает с 430 000 до 350 000 KRW (собственный капитал 2026 — 503,3 млрд × PER 15x); NC закрылась на 210 500 9 сентября. Снижение адресовано Aion 2: спад KR/TW быстрее ожиданий."),
        section("why", "Драйвер: недовольство балансом", "Спад связывается с растущим недовольством балансом после запуска. Контекст: обновление 9 сентября (Snowfield of Sorrow, переработка Бездны, система Печатей) вышло в ту же неделю; меры 10–11 (баны пилотинга) показывают активное управление live-сервисом."),
        section("global-risk", "Глобальный риск: перенос паттерна KR/TW", "Паттерн спада применяется по аналогии к 2027-му из опасения похожего спада после 5 октября. Оценка глобального T1: 158,5 млрд; NC 2026: 2,8694 трлн (+90,4%) / 551,6 млрд OP (+3 426%); 2027: 3,0776 трлн / 506,2 млрд."),
        section("the-numbers", "Цифры", "Таргет 430 000 → 350 000 KRW (BUY); закрытие 210 500; 2026E 2,8694 трлн / 551,6 млрд; 2027E 3,0776 трлн / 506,2 млрд; глобальный T1 158,5 млрд. OP урезан сильнее выручки: низкие маржи вклада Aion 2 и Lineage Classic."),
        section("what-it-means", "Что это значит", "Для игроков спор о персистентности выручки, а не играбельности — и о давлении на модифицированный Сезон 1. Реальные смягчающие: QoL и баланс от 7 сентября (без гейтов, сглаженная прокачка, необязательный PvP)."),
      ],
    }),
    ko: articleCopy(newsLabels, "ko", 5, {
      eyebrow: "시장 분석",
      title: "아이온2 글로벌 출시를 다시 보다: 증권사가 NC 목표주가를 낮췄다——한국·대만 매출 하락이 예상보다 가파르게",
      description: "키움증권이 BUY를 유지하면서도 NC 목표주가를 43만→35만 원으로 하향: 아이온2의 한국·대만 매출이 밸런스 불만으로 예상보다 가파르게 감소, 10월 5일 이후 글로벌에서도 같은 패턴이 반복될 리스크를 경고",
      intro: "글로벌 출시까지 23일, 시장이 리스크를 가격에 반영하기 시작했습니다. 키움증권은 NC 목표주가를 43만→35만 원으로 내렸습니다(BUY 유지). 아이온2의 한국·대만 매출 하락이 밸런스 불만 증가로 예상보다 가파르다고 지적하고, 그 패턴을 내년 글로벌 추정치에 적용하고 있습니다.",
      sourceNote: "뉴스퀘스트 2026년 9월 10일자 키움증권 분석 보도(2026-09-12 확인)를 기반으로 했습니다. 숫자는 애널리스트 추정치이며, 한국 데이터는 출시 후 트렌드를 반영합니다.",
      keywords: ["아이온2 글로벌 출시 매출 리스크", "NC 목표주가 하향 키움증권", "아이온2 한국 대만 매출 하락", "아이온2 밸런스 불만 애널리스트", "NC 주가 아이온2 10월5일"],
      sections: [
        section("the-cut", "목표주가 35만 원으로 하향", "키움증권은 BUY 등급을 유지하면서 NC 목표주가를 43만→35만 원으로 내렸습니다——2026년 지배주주 지분 5,033억 원 × 목표 PER 15배로 산출한 새 목표입니다. NC는 9월 9일 210,500원에 마감했습니다.", "하향의 초점은 아이온2입니다: 기존 지역(한국·대만)의 매출 하락이 종전 추정보다 가파르게 진행돼, 정상화 이익의 피크가 올해(2026)로 잡혔습니다."),
        section("why", "원인: 출시 후 밸런스 불만", "보고서는 더 가파른 하락을 출시 후 커진 아이온2 게임 밸런스에 대한 유저 불만과 연결합니다——본 사이트의 한국 업데이트 보도(아비스 개편, 신규 레이드 난이도 곡선)에서 계속 다뤄온 주제입니다.", "시점을 보면: 한국의 9월 9일 업데이트(비탄의 설원, 아비스 개편, 인장 시스템)가 같은 주에 나왔고, 9월 10-11일 제재 조치(대리 게임 영구 제한)도 라이브 서비스 환경을 적극 관리하고 있음을 보여줍니다."),
        section("global-risk", "글로벌 리스크: 한·대만 패턴 적용", "핵심 경고: 한국·대만 하락 패턴이 '준용'돼, 10월 5일 출시 후 글로벌 지역에서도 유사한 하락이 있을 수 있다는 우려가 내년 추정에 반영됐습니다.", "글로벌 출시 첫 분기 매출 추정은 1,585억 원입니다. NC 2026년 추정: 매출 2조 8,694억 원(+90.4%), 영업이익 5,516억 원(+3,426%); 2027년은 3조 776억/5,062억 원."),
        section("the-numbers", "숫자 요약", "목표주가 43만→35만 원(BUY 유지); 9월 9일 종가 210,500원; 2026E 매출 2조 8,694억(+90.4%)·영업이익 5,516억(+3,426%); 2027E 3조 776억/5,062억; 글로벌 T1 매출 1,585억 원.", "영업이익 추정 하향이 매출보다 큰 이유는 아이온2와 리니지클래식의 기여 마진이 낮기 때문입니다——매출 구성이 총성장만큼 중요합니다."),
        section("what-it-means", "의미", "플레이어에게 이 논쟁은 플레이 가능성이 아니라 매출 지속성에 대한 것이며——10월 5일 수정판 시즌 1을 잘 안착시켜야 하는 압박의 틀을 보여줍니다.", "글로벌 출시의 완충 요인은 실재합니다: 글로벌 빌드는 9월 7일 인터뷰에서 확인된 QoL·밸런스 개선(일일/주간 게이트 없음, 성장의 유연화, PvP 선택)을 탑재하며, 애널리스트가 지적한 불만 패턴을 직접 겨냥합니다."),
      ],
    }),
    "zh-hant": articleCopy(newsLabels, "zh-hant", 5, {
      eyebrow: "市場分析",
      title: "Aion 2 全球首發接受審視：分析師下調 NC 目標價——韓服/台服收入下滑快於預期",
      description: "Kiwoom 證券維持 BUY 但把 NCsoft 目標價從 43 萬降至 35 萬韓元，理由是 Aion 2 韓服/台服收入因平衡不滿而下滑快於預期——並提示該模式可能在 10 月 5 日全球版重演",
      intro: "距 Aion 2 全球首發還有 23 天，市場開始為此定價。Kiwoom 證券把 NCsoft 目標價從 43 萬降至 35 萬韓元（維持 BUY），指出 Aion 2 韓服/台服收入因日益增長的平衡不滿而下滑快於預期——並把該模式延伸到明年的全球版預估。",
      sourceNote: "基於 뉴스퀘스트（Newsquest）2026 年 9 月 10 日對 Kiwoom 證券分析的報導（2026-09-12 抓取）。數字為分析師預估；韓服數據反映的是上線後趨勢，並非全球版。",
      keywords: ["Aion 2 全球首發 營收風險", "NCsoft 目標價下調 Kiwoom", "Aion 2 韓服台服 收入下滑", "Aion 2 平衡不滿 分析師", "NC 股價 Aion 2 10月5日"],
      sections: [
        section("the-cut", "目標價下調至 35 萬韓元", ["Kiwoom 證券維持 BUY 評級，但把 NCsoft 目標價從 43 萬降至 35 萬韓元——新目標由 2026 年控股股東權益 5,033 億韓元 × 目標 PER 15 倍得出。NC 於 9 月 9 日收於 210,500 韓元。", "下調針對的正是 Aion 2：現有地區（韓服與台服）收入下滑快於此前預估，因此常態利潤峰值被歸到 2026 年。"]),
        section("why", "驅動因素：上線後的平衡不滿", ["報告把更陡的下滑與上線後日益增長的 Aion 2 遊戲平衡不滿聯繫起來——即本站韓服更新報導中持續追蹤的平衡議題，從深淵改版到新副本的難度曲線。", "注意時點：韓服 9 月 9 日更新（Snowfield of Sorrow、深淵改版、印章系統）與報告同週落地，9 月 10-11 的執法行動（代練封禁）也說明 NC 正在積極管理長線營運環境。"]),
        section("global-risk", "全球版風險：套用韓服/台服模式", ["關鍵警告：韓服/台服下滑模式正被「準用」（類推）到明年的預估中——擔心全球地區在 10 月 5 日上線後出現類似下滑。", "全球版首發當季收入預估為 1,585 億韓元。NC 2026 年預估：營收 2.8694 兆韓元（+90.4%）、營業利潤 5,516 億韓元（+3,426%）；2027 年為 3.0776 兆 / 5,062 億韓元。"]),
        section("the-numbers", "數字一覽", ["目標價 43 萬 → 35 萬韓元（維持 BUY）；9 月 9 日收盤 210,500 韓元；2026E 營收 2.8694 兆（+90.4%）、營業利潤 5,516 億（+3,426%）；2027E 3.0776 兆 / 5,062 億；全球版首發 Q4 收入預估 1,585 億韓元。", "營業利潤預估的下調幅度大於營收——因為 Aion 2 與天堂經典版的貢獻利潤率較低：收入結構幾乎與總量成長同等重要。"]),
        section("what-it-means", "意義", ["對玩家，分析師之爭關乎收入持續性而非可玩性——它框定了 NC 在 10 月 5 日讓改良版 Season 1 落好所承受的壓力。", "對全球首發，緩解因素真實存在：全球版搭載 9 月 7 日專訪確認的 QoL 與平衡改進（無日常/週常門檻、成長平滑化、PvP 可選），直接針對分析師所指的不滿模式。"]),
      ],
    }),
  },
};