import { articleCopy, guideLabels, localizations, publishedVerified, section } from "./trending-august-31-shared";
import type { ContentEntry, ContentHeroImage, ContentSource } from "./content-registry";

/* ARTICLE 4 — Pre-launch access map: Steam Playtest request, LST, Founder's Pack early access, Oct 5 launch */

const accessSource1: ContentSource = {
  id: "steam-store-aion2-access-2026-08-31",
  kind: "platform", publisher: "Steam",
  label: "AION 2 — Steam Store Page (Playtest, Advance Access, Release Date)",
  url: "https://store.steampowered.com/app/3393110/AION_2/",
  publishedAt: "2026-08-26",
  retrievedAt: "2026-08-31",
  verifiedAt: "2026-08-31",
  localizations: localizations({
    "zh-hans": "AION 2——Steam 商店页（试玩、抢先体验、发售日期）",
    en: "AION 2 — Steam Store Page (Playtest, Advance Access, Release Date)",
    fr: "AION 2 — Page boutique Steam (playtest, accès anticipé, date de sortie)",
    de: "AION 2 — Steam-Store-Seite (Playtest, Vorabzugang, Erscheinungsdatum)",
    es: "AION 2 — Página de la tienda de Steam (playtest, acceso anticipado, fecha de lanzamiento)",
    ja: "AION 2 — Steam ストアページ（プレイテスト・先行体験・発売日）",
    "pt-br": "AION 2 — Página da loja Steam (playtest, acesso antecipado, data de lançamento)",
    ru: "AION 2 — Страница Steam (плейтест, ранний доступ, дата выхода)",
    ko: "AION 2 — Steam 상점 페이지(플레이테스트·얼리 액세스·출시일)",
    "zh-hant": "AION 2——Steam 商店頁（試玩、搶先體驗、發售日期）",
  }, "https://store.steampowered.com/app/3393110/AION_2/"),
};

const accessSource2: ContentSource = {
  id: "massivelyop-gamescom-access-2026-08-25",
  kind: "third-party", publisher: "Massively Overpowered",
  label: "Gamescom 2026: Aion 2 October 5 global debut following stress test and headstart",
  url: "https://massivelyop.com/2026/08/25/gamescom-2026-aion-2-makes-its-global-debut-october-5-following-stress-test-and-headstart/",
  publishedAt: "2026-08-25",
  retrievedAt: "2026-08-31",
  verifiedAt: "2026-08-31",
  localizations: localizations({
    "zh-hans": "Gamescom 2026：Aion 2 10 月 5 日全球首发，压测与抢先体验先行",
    en: "Gamescom 2026: Aion 2 October 5 global debut following stress test and headstart",
    fr: "Gamescom 2026 : Aion 2 débute le 5 octobre après test de charge et accès anticipé",
    de: "Gamescom 2026: Aion 2 startet am 5. Oktober nach Stresstest und Headstart",
    es: "Gamescom 2026: Aion 2 debuta el 5 de octubre tras prueba de carga y acceso anticipado",
    ja: "Gamescom 2026：Aion 2 は負荷試験と先行体験を経て10月5日にグローバルデビュー",
    "pt-br": "Gamescom 2026: Aion 2 estreia em 5 de outubro após teste de carga e acesso antecipado",
    ru: "Gamescom 2026: Aion 2 выходит 5 октября после стресс-теста и раннего старта",
    ko: "Gamescom 2026: Aion 2는 부하 테스트와 헤드스타트 후 10월 5일 글로벌 데뷔",
    "zh-hant": "Gamescom 2026：Aion 2 10 月 5 日全球首發，壓測與搶先體驗先行",
  }, "https://massivelyop.com/2026/08/25/gamescom-2026-aion-2-makes-its-global-debut-october-5-following-stress-test-and-headstart/"),
};

const accessHero: ContentHeroImage = {
  src: "https://blogfiles.ncsoft.net/news/af7330da-4ff6-4b58-aece-400e6061a3be.jpg",
  width: 1100, height: 605,
  credit: "NC Corporation",
  sourceUrl: "https://aion2.plaync.com/ja-jp/board/notice/list",
  rights: "linked-official-media",
  translations: {
    "zh-hans": { alt: "Aion 2 预发布接入路线图配图", caption: "NC 官方配图；Aion 2 上线前有四条官方路径：Steam Playtest 申请、9 月 17–18 日 Launch Scale Test、9 月 30 日创始人包抢先体验，以及 10 月 5 日免费游玩上线。" },
    en: { alt: "Aion 2 pre-launch access map image", caption: "Official NC artwork; four official paths lead into Aion 2 before launch: the Steam Playtest request, the September 17–18 Launch Scale Test, Founder's Pack early access on September 30, and the October 5 free-to-play launch." },
    fr: { alt: "Image de la carte d'accès avant lancement d'Aion 2", caption: "Visuel officiel NC ; quatre chemins officiels mènent à Aion 2 avant le lancement : la demande Playtest Steam, le test de charge 17–18 septembre, l'accès anticipé des packs Fondateur le 30 septembre et le lancement gratuit du 5 octobre." },
    de: { alt: "Bild zur Vorstart-Zugangskarte von Aion 2", caption: "Offizielles NC-Artwork; vier offizielle Wege führen vor dem Start in Aion 2: die Steam-Playtest-Anfrage, der LST 17.–18. September, der Founder's-Pack-Frühstart am 30. September und der Free-to-play-Start am 5. Oktober." },
    es: { alt: "Imagen del mapa de acceso previo al lanzamiento de Aion 2", caption: "Arte oficial de NC; cuatro caminos oficiales llevan a Aion 2 antes del lanzamiento: la solicitud de Steam Playtest, el test de carga 17–18 de septiembre, el acceso anticipado de packs Fundador el 30 de septiembre y el lanzamiento gratuito del 5 de octubre." },
    ja: { alt: "Aion 2 リリース前アクセス地図画像", caption: "NC公式アートワーク；発売前にAion 2へ入る公式経路は4つです：Steam Playtest申請、9月17–18日のLaunch Scale Test、9月30日のファウンダーズパック先行体験、10月5日の基本無料発売。" },
    "pt-br": { alt: "Imagem do mapa de acesso pré-lançamento do Aion 2", caption: "Arte oficial da NC; quatro caminhos oficiais levam ao Aion 2 antes do lançamento: o pedido de acesso ao Steam Playtest, o teste de carga 17–18 de setembro, o acesso antecipado dos packs Fundador em 30 de setembro e o lançamento gratuito de 5 de outubro." },
    ru: { alt: "Изображение карты доступа до запуска Aion 2", caption: "Официальный арт NC; до запуска в Aion 2 ведут четыре официальных пути: запрос Steam Playtest, стресс-тест 17–18 сентября, ранний доступ паков основателя 30 сентября и бесплатный запуск 5 октября." },
    ko: { alt: "Aion 2 출시 전 접근 맵 이미지", caption: "NC 공식 이미지입니다. 출시 전 Aion 2에 들어가는 공식 경로는 네 가지: Steam Playtest 신청, 9월 17–18일 LST, 9월 30일 파운더스 팩 얼리 액세스, 10월 5일 무료 플레이 출시입니다." },
    "zh-hant": { alt: "Aion 2 預發布接入路線圖配圖", caption: "NC 官方配圖；Aion 2 上線前有四條官方路徑：Steam Playtest 申請、9 月 17–18 日 Launch Scale Test、9 月 30 日創始人包搶先體驗，以及 10 月 5 日免費遊玩上線。" },
  },
};

export const trendingAugust31Article4: ContentEntry = {
  section: "guides",
  slug: "aion-2-prelaunch-access-routes-guide",
  schemaType: "Article",
  publishedAt: "2026-08-31",
  updatedAt: "2026-08-31",
  readingMinutes: 5,
  publication: publishedVerified,
  sources: [accessSource1, accessSource2],
  heroImage: accessHero,
  related: [
    { kind: "content", section: "news", slug: "aion-2-launch-scale-test-september-17-18" },
    { kind: "content", section: "news", slug: "aion-2-release-date-october-5-2026" },
    { kind: "content", section: "guides", slug: "aion-2-language-support-8-languages-guide" },
    { kind: "content", section: "guides", slug: "founders-pack-comparison" },
  ],
  translations: {
    en: articleCopy(guideLabels, "en", 5, {
      eyebrow: "PRE-LAUNCH ACCESS MAP",
      title: "Aion 2 Pre-Launch Access Map: Playtest, LST, Early Access, and the October 5 Launch",
      description: "Four official paths lead into Aion 2 before launch: the Steam Playtest access request, the September 17–18 Launch Scale Test (open to everyone, no keys), Founder's Pack early access September 30 – October 4, and the free-to-play launch October 5. This guide sorts them by who gets in, what carries over, and what each costs.",
      intro: "Between now and the October 5 launch, Aion 2 offers four separate official ways in, and they are easy to confuse: a Steam Playtest button that says “request access”, an open Launch Scale Test in mid-September, a paid Founder's Pack early access window, and then the free-to-play launch itself. This guide maps each route — who can use it, what is included, what is wiped, and which one you actually want.",
      sourceNote: "Based on the AION 2 Steam store page (retrieved and verified August 31, 2026), cross-checked with Massively Overpowered's Gamescom 2026 report detailing the stress test (September 17–18) and the Founder's Pack headstart (September 30 – October 4).",
      keywords: ["Aion 2 pre-launch access", "Aion 2 playtest request", "Aion 2 Launch Scale Test", "Aion 2 early access", "Aion 2 how to play early"],
      sections: [
        section("four-routes", "The Four Routes at a Glance", ["The Steam store page currently shows a “Join the AION 2 Playtest” section that asks you to request access; a separate announcement covers the September 17–18 Launch Scale Test; the three Founder's Packs all mark “Advance Access Starts 30 Sep”; and the release date itself is October 5. Those are four distinct mechanisms, not one.", "The key distinction: the Playtest request and the Launch Scale Test are free and limited; the Founder's Pack early access is paid and gives five days; the October 5 launch is free and permanent. Knowing which is which prevents paying for something you could get free, or missing a test window entirely.", "This map treats the store page as the source of truth and flags anything that depends on a separate announcement."]),
        section("playtest-request", "Route 1 — Steam Playtest Request (Free, Invite-Based)", ["The store page invites you to “Request access and you'll get notified when the developer is ready for more participants.” This is Steam's playtest mechanism: you apply, and access can be granted in waves, not on a fixed date.", "It is free and low-stakes — applying costs nothing and does not commit you to anything. Treat it as a first-come queue that may be used for smaller rounds before the big public test.", "Separate from this, the Launch Scale Test on September 17–18 was announced as open to everyone with no keys, no invites, and no registration — so the Playtest request and the LST are not the same door. You can request the playtest anyway; it costs nothing."]),
        section("lst", "Route 2 — Launch Scale Test, September 17–18 (Free, Open to All)", ["NCSoft announced a Launch Scale Test on Thursday and Friday, September 17–18, building an environment similar to the actual service to check server and infrastructure stability, while letting players experience the game before launch. Pre-download opens September 16.", "The test is open to everyone on Steam and PURPLE — no key, no invite, no registration. Progression is capped and wiped at the end of the test; the site's dedicated LST report has the level cap, daily hours, and wipe details.", "This is the best free way to test your PC's performance before committing to the paid early access or the launch-day queue."]),
        section("founder-early-access", "Route 3 — Founder's Pack Early Access, September 30 – October 4 (Paid)", ["All three Founder's Packs — Standard, Deluxe, and Ultimate — grant “Advance Access Starts 30 Sep”, meaning five days of early access from September 30 to October 4 before the full launch on October 5.", "The packs are a purchase decision, not a free route: you are buying the game's pre-launch access plus pack contents. The store page prices the tiers in local currency, and PURPLE offers paid upgrade paths between tiers while Steam does not currently list one.", "If your goal is simply to play early without spending, this route is not for you — the LST and the October 5 launch cover that. If your goal is a head start on your character, this is the only paid route."]),
        section("launch", "Route 4 — Free-to-Play Launch, October 5", ["The game releases as free to play on PC (Steam and PURPLE) on October 5, 2026, across North America, South America, Europe, and Asia. The Steam page lists the release date as “5 Oct, 2026” with a “Coming 5 Oct, 2026” header and an “unlocks in approximately 5 weeks” note as of late August.", "No purchase is required to play at launch; in-app purchases are present as the monetization layer. Progress from the Launch Scale Test does not carry over, and the early access head start is the only permanent head start.", "If you are cost-sensitive, the entire pre-launch sequence is optional: request the playtest, join the free LST, and show up October 5."]),
        section("decision-guide", "Which Route Do You Want?", ["Free and curious — request the Steam Playtest and join the September 17–18 LST. Both cost nothing and let you validate performance and gameplay before launch.", "Paid head start — buy a Founder's Pack for the September 30 – October 4 early access. Choose your tier once; Steam currently has no listed upgrade path between tiers, so pick before checkout.", "Just want the game — wait for October 5. Everything before that is optional, and the free LST is still worth taking for a performance check. Whatever you choose, the store page is the reference that stays current as dates settle."]),
      ],
    }),
    "zh-hans": articleCopy(guideLabels, "zh-hans", 5, {
      eyebrow: "预发布接入路线图",
      title: "Aion 2 预发布接入路线图：Playtest、LST、抢先体验与 10 月 5 日上线",
      description: "上线前有四条官方路径进入 Aion 2：Steam Playtest 接入申请、9 月 17–18 日 Launch Scale Test（全开放、免 key）、9 月 30 日–10 月 4 日创始人包抢先体验，以及 10 月 5 日免费游玩上线。本指南按准入、是否保留、各自代价来梳理。",
      intro: "从现在到 10 月 5 日上线，Aion 2 提供四条彼此独立、又容易混淆的官方进入路径：写着「request access」的 Steam Playtest 按钮、9 月中全开放的 Launch Scale Test、付费的创始人包抢先体验窗口，以及免费游玩上线本身。本指南逐条标注每一条——谁能用、包含什么、什么会被清空、你真正需要哪一条。",
      sourceNote: "基于 AION 2 Steam 商店页（2026-08-31 检索并核对），并与 Massively Overpowered 的 Gamescom 2026 报道（压测 9 月 17–18 日、创始人包抢先 9 月 30 日–10 月 4 日）交叉核对。",
      keywords: ["Aion 2 预发布接入", "Aion 2 Playtest 申请", "Aion 2 Launch Scale Test", "Aion 2 抢先体验", "Aion 2 提前玩"],
      sections: [
        section("four-routes", "四条路径一览", ["Steam 商店页现显示一个「Join the AION 2 Playtest」区块要求申请接入；另一则公告覆盖 9 月 17–18 日 Launch Scale Test；三个创始人包均标记「Advance Access Starts 30 Sep」；发售日期本身是 10 月 5 日。这是四个不同机制，而非一个。", "关键区别：Playtest 申请与 Launch Scale Test 免费且受限；创始人包抢先体验付费且给 5 天；10 月 5 日上线免费且永久。弄清彼此，避免为可免费获得的东西付费，或完全错过测试窗口。", "本图以商店页为准，任何依赖单独公告的内容都会标明。"]),
        section("playtest-request", "路径 1——Steam Playtest 申请（免费、邀请制）", ["商店页邀请你「Request access and you'll get notified when the developer is ready for more participants.」这是 Steam 的 playtest 机制：你申请，接入可能分批发放，而非固定日期。", "它免费且低风险——申请不花钱，也不构成任何承诺。把它当作一个先到先得的队列，可能在大型公开测试之前用于较小的轮次。", "与此独立的 9 月 17–18 日 Launch Scale Test 公告称全开放、免 key、免邀请、免注册——所以 Playtest 申请与 LST 不是同一扇门。你仍可顺便申请 playtest，反正免费。"]),
        section("lst", "路径 2——Launch Scale Test，9 月 17–18 日（免费、全开放）", ["NCSoft 公布于 9 月 17–18 日（周四、周五）举办 Launch Scale Test，构建与真实服务相近的环境以检验服务器与基础设施稳定性，同时让玩家在上线前体验游戏。预下载 9 月 16 日开启。", "测试对 Steam 与 PURPLE 上所有人开放——无 key、无邀请、无注册。进度封顶并在测试结束时清空；本站 LST 专文有等级上限、每日时长与清空细节。", "这是付费抢先或上线日排队之前，免费检验你 PC 性能的最佳途径。"]),
        section("founder-early-access", "路径 3——创始人包抢先体验，9 月 30 日–10 月 4 日（付费）", ["三个创始人包——标准、豪华、终极——均授予「Advance Access Starts 30 Sep」，即 9 月 30 日至 10 月 4 日共五天抢先体验，之后 10 月 5 日正式上线。", "这些包是购买决策，而非免费路径：你购买的是上线前接入加包内容。商店页以本地币种标价三档，PURPLE 提供档位间的付费升级路径，Steam 目前未列出。", "如果你的目标只是不花钱提前玩，这条不适合你——LST 与 10 月 5 日上线已覆盖。如果你的目标是为角色抢跑，这是唯一的付费路径。"]),
        section("launch", "路径 4——免费游玩上线，10 月 5 日", ["游戏于 2026 年 10 月 5 日在 PC（Steam 与 PURPLE）免费游玩上线，覆盖北美、南美、欧洲与亚洲。Steam 页面将发售日列为「5 Oct, 2026」，并带「Coming 5 Oct, 2026」标题与 8 月末「约 5 周后解锁」的注记。", "上线游玩无需购买；内购是变现层。Launch Scale Test 的进度不保留，抢先体验是唯一永久领先。", "若你对成本敏感，整套预发布流程都是可选的：申请 playtest、参加免费 LST、10 月 5 日到场即可。"]),
        section("decision-guide", "你该选哪一条？", ["免费且好奇——申请 Steam Playtest 并参加 9 月 17–18 日 LST。两者免费，可在上线前验证性能与玩法。", "付费抢跑——购买创始人包获取 9 月 30 日–10 月 4 日抢先体验。一次选好档位；Steam 目前无档位升级路径，请在结账前定夺。", "只想要游戏——等到 10 月 5 日。此前一切都可选，免费的 LST 仍值得做一次性能体检。无论选哪条，商店页都是随档期稳定而持续更新的参考。"]),
      ],
    }),
    ko: articleCopy(guideLabels, "ko", 5, {
      eyebrow: "출시 전 접근 맵",
      title: "Aion 2 출시 전 접근 맵: Playtest, LST, 얼리 액세스, 10월 5일 출시",
      description: "출시 전에 Aion 2로 들어가는 공식 경로는 네 가지: Steam Playtest 신청, 9월 17–18일 Launch Scale Test(전원 오픈·키 없음), 9월 30일–10월 4일 파운더스 팩 얼리 액세스, 10월 5일 무료 플레이 출시. 각각의 자격·유지 여부·비용을 정리합니다.",
      intro: "지금부터 10월 5일 출시까지 Aion 2는 서로 다른 공식 진입 경로 네 개를 제공하며 쉽게 혼동됩니다. 이 가이드는 각 경로의 자격·포함 내용·삭제 여부·실제로 필요한 것을 정리합니다.",
      sourceNote: "AION 2 Steam 상점 페이지(2026-08-31 확인)와 Massively Overpowered의 Gamescom 2026 보도(부하 테스트 9/17–18, 파운더스 팩 헤드스타트 9/30–10/4) 교차 확인 기반.",
      keywords: ["Aion 2 출시 전 접근", "Aion 2 플레이테스트 신청", "Aion 2 Launch Scale Test", "Aion 2 얼리 액세스", "Aion 2 먼저 하기"],
      sections: [
        section("four-routes", "네 가지 경로 한눈에", "Steam 상점 페이지는 'Join the AION 2 Playtest' 신청 섹션, 9월 17–18일 LST, 세 파운더스 팩의 'Advance Access Starts 30 Sep', 10월 5일 출시일을 각각 보여줍니다. 네 메커니즘은 서로 다릅니다. Playtest·LST는 무료·제한, 파운더스 팩은 유료·5일, 10월 5일 출시는 무료·영구입니다."),
        section("playtest-request", "경로 1 — Steam Playtest 신청(무료·초청제)", "상점 페이지는 'Request access and you'll get notified when the developer is ready for more participants.'라고 안내합니다. 고정 날짜가 아닌 웨이브식 접근 부여입니다. 무료·저위험이며, 9월 17–18일 LST는 키 없이 전원 오픈으로 별개의 문입니다. 그래도 신청해도 무방합니다."),
        section("lst", "경로 2 — Launch Scale Test, 9월 17–18일(무료·전원 오픈)", "NC소프트가 실제 서비스와 유사한 환경으로 서버·인프라 안정성을 점검하는 LST를 9월 17–18일(목·금)에 개최합니다. 사전 다운로드는 9월 16일. Steam·PURPLE 모두 키·초청·등록 없이 참여 가능하고, 진행은 상한 적용 후 테스트 종료 시 삭제됩니다. 유료 진입 전 PC 성능을 무료로 확인할 최선의 경로입니다."),
        section("founder-early-access", "경로 3 — 파운더스 팩 얼리 액세스, 9월 30일–10월 4일(유료)", "세 파운더스 팩(Standard·Deluxe·Ultimate) 모두 'Advance Access Starts 30 Sep'로 9월 30일부터 10월 4일까지 5일 얼리 액세스를 줍니다. 팩은 구매 결정이지 무료 경로가 아닙니다. PURPLE은 티어 간 유료 업그레이드가 있으나 Steam은 현재 미공지 — 결제 전에 티어를 정하세요."),
        section("launch", "경로 4 — 무료 플레이 출시, 10월 5일", "게임은 2026년 10월 5일 PC(Steam·PURPLE)에서 북미·남미·유럽·아시아에 무료로 출시됩니다. Steam 페이지는 출시일을 '5 Oct, 2026'로 표시합니다. 구매 없이 플레이 가능하며, LST 진행은 이월되지 않습니다. 비용에 민감하다면 전체 사전 절차는 선택 사항입니다."),
        section("decision-guide", "어느 경로를 원하나?", "무료·호기심 — Steam Playtest 신청과 9월 17–18일 LST 참여. 유료 선발 — 파운더스 팩으로 9월 30일–10월 4일 얼리 액세스, 한 번에 티어 선택. 그냥 게임 — 10월 5일 대기, 무료 LST는 성능 점검으로 권장. 무엇을 고르든 상점 페이지가 최신 기준입니다."),
      ],
    }),
    ja: articleCopy(guideLabels, "ja", 5, {
      eyebrow: "リリース前アクセスマップ",
      title: "Aion 2 リリース前アクセスマップ：Playtest、LST、先行体験、10月5日発売",
      description: "発売前にAion 2へ入る公式経路は4つ：Steam Playtest申請、9月17–18日のLaunch Scale Test（全員オープン・キー不要）、9月30日–10月4日のファウンダーズパック先行体験、10月5日の基本無料発売。各経路の資格・維持・コストを整理します。",
      intro: "今から10月5日の発売まで、Aion 2 は互いに独立しつつ紛らわしい公式経路を4つ提供します。本ガイドは各経路の対象者・内容・消去の有無・本当に必要な経路を整理します。",
      sourceNote: "AION 2 Steam ストアページ（2026-08-31 確認）と、Massively Overpowered の Gamescom 2026 報道（負荷試験9/17–18、ファウンダーズパック先行9/30–10/4）の照合に基づきます。",
      keywords: ["Aion 2 発売前アクセス", "Aion 2 プレイテスト申請", "Aion 2 Launch Scale Test", "Aion 2 先行体験", "Aion 2 先に遊ぶ"],
      sections: [
        section("four-routes", "4つの経路一覧", "Steamストアページは「Join the AION 2 Playtest」申請セクション、9月17–18日のLST、3つのファウンダーズパックの「Advance Access Starts 30 Sep」、10月5日の発売日をそれぞれ示します。4つの仕組みは別物です。Playtest・LSTは無料・限定、パック先行は有料・5日、10月5日は無料・恒久です。"),
        section("playtest-request", "経路1 — Steam Playtest申請（無料・招待制）", "ストアページは「Request access and you'll get notified when the developer is ready for more participants.」と案内します。固定日ではなく波状にアクセスが付与されます。無料・低リスクで、9月17–18日のLSTはキー不要・全員オープンの別のドアです。申請しておいても損はありません。"),
        section("lst", "経路2 — Launch Scale Test、9月17–18日（無料・全員オープン）", "NCソフトは実際のサービスに近い環境でサーバー・インフラの安定性を検証するLSTを9月17–18日（木・金）に開催します。事前DLは9月16日。Steam・PURPLEともにキー・招待・登録なしで参加でき、進行は上限適用後、テスト終了時に消去されます。有料先行の前にPC性能を無料確認する最良の経路です。"),
        section("founder-early-access", "経路3 — ファウンダーズパック先行体験、9月30日–10月4日（有料）", "3つのファウンダーズパック（Standard・Deluxe・Ultimate）はすべて「Advance Access Starts 30 Sep」で、9月30日から10月4日まで5日間の先行体験を与えます。パックは購入判断であり無料経路ではありません。PURPLEはティア間の有料アップグレードがありますが、Steamは現在未公表 — 決済前にティアを選んでください。"),
        section("launch", "経路4 — 基本無料発売、10月5日", "ゲームは2026年10月5日にPC（Steam・PURPLE）で北米・南米・欧州・アジアへ無料で発売されます。Steamページは発売日を「5 Oct, 2026」と表示します。購入なしでプレイ可能で、LSTの進行は引き継がれません。費用に敏感なら、発売前の一連の手続きはすべて任意です。"),
        section("decision-guide", "どの経路を選ぶか", "無料・好奇心 — Steam Playtest申請と9月17–18日LST参加。有料の先行 — ファウンダーズパックで9月30日–10月4日の先行体験、ティアは一度で決定。ゲームだけ — 10月5日を待ち、無料のLSTは性能チェックとして推奨。何を選んでも、ストアページが最新の基準です。"),
      ],
    }),
    fr: articleCopy(guideLabels, "fr", 5, {
      eyebrow: "CARTE D'ACCÈS PRÉ-LANCEMENT",
      title: "Carte d'accès pré-lancement d'Aion 2 : Playtest, LST, accès anticipé et lancement du 5 octobre",
      description: "Quatre chemins officiels mènent à Aion 2 avant le lancement : la demande d'accès Steam Playtest, le test de charge 17–18 septembre (ouvert à tous, sans clé), l'accès anticipé des packs Fondateur du 30 septembre au 4 octobre, et le lancement gratuit du 5 octobre. Triés par qui entre, ce qui reste, et le coût.",
      intro: "D'ici au lancement du 5 octobre, Aion 2 offre quatre accès officiels distincts, faciles à confondre : un bouton Steam Playtest « request access », un test de charge ouvert mi-septembre, une fenêtre d'accès anticipé payante, puis le lancement gratuit. Ce guide cartographie chaque voie — qui peut l'utiliser, ce qu'elle inclut, ce qui est effacé.",
      sourceNote: "Basé sur la page Steam d'AION 2 (récupérée et vérifiée le 31 août 2026), recoupé avec le rapport Gamescom 2026 de Massively Overpowered (test de charge 17–18 septembre, tête de série des packs Fondateur 30 septembre – 4 octobre).",
      keywords: ["Aion 2 accès pré-lancement", "Aion 2 demande playtest", "Aion 2 Launch Scale Test", "Aion 2 accès anticipé", "Aion 2 jouer tôt"],
      sections: [
        section("four-routes", "Les quatre voies en bref", "La page Steam montre une section « Join the AION 2 Playtest » demandant un accès ; une annonce séparée couvre le test de charge 17–18 septembre ; les trois packs Fondateur marquent « Advance Access Starts 30 Sep » ; la sortie est le 5 octobre. Quatre mécanismes distincts. Playtest et LST sont gratuits et limités ; le pack Fondateur est payant et donne 5 jours ; le 5 octobre est gratuit et permanent."),
        section("playtest-request", "Voie 1 — Demande Steam Playtest (gratuite, sur invitation)", "La page invite à « Request access and you'll get notified when the developer is ready for more participants. » C'est le mécanisme playtest de Steam : accès accordé par vagues, pas à date fixe. Gratuit et sans engagement. Le LST du 17–18 septembre est une porte séparée, ouverte à tous sans clé. Demandez quand même le playtest, c'est gratuit."),
        section("lst", "Voie 2 — Launch Scale Test, 17–18 septembre (gratuit, ouvert à tous)", "NCSoft annonce un test de charge jeudi et vendredi 17–18 septembre, dans un environnement proche du service réel, pour vérifier la stabilité des serveurs et laisser les joueurs essayer avant le lancement. Pré-téléchargement le 16. Ouvert à tous sur Steam et PURPLE, sans clé, sans invitation, sans inscription. Progression plafonnée puis effacée. Meilleur moyen gratuit de tester votre PC avant le paiement."),
        section("founder-early-access", "Voie 3 — Accès anticipé packs Fondateur, 30 septembre – 4 octobre (payant)", "Les trois packs (Standard, Deluxe, Ultimate) donnent « Advance Access Starts 30 Sep », soit cinq jours d'accès anticipé du 30 septembre au 4 octobre. C'est un achat, pas une route gratuite. PURPLE propose des montées de gamme payantes entre paliers ; Steam n'en liste pas pour l'instant — choisissez votre palier avant le paiement."),
        section("launch", "Voie 4 — Lancement gratuit, 5 octobre", "Le jeu sort en free-to-play sur PC (Steam et PURPLE) le 5 octobre 2026 en Amérique du Nord, du Sud, en Europe et en Asie. La page Steam affiche « 5 Oct, 2026 » et « Coming 5 Oct, 2026 ». Aucun achat requis ; achats intégrés présents. La progression du LST ne se reporte pas."),
        section("decision-guide", "Quelle voie voulez-vous ?", "Gratuit et curieux — demandez le Playtest et rejoignez le LST du 17–18 septembre. Avance payante — achetez un pack Fondateur pour l'accès du 30 septembre au 4 octobre, choisissez le palier une fois. Voulez juste le jeu — attendez le 5 octobre ; le LST gratuit reste utile pour un contrôle de performances."),
      ],
    }),
    de: articleCopy(guideLabels, "de", 5, {
      eyebrow: "ZUGANGSKARTE VOR DEM START",
      title: "Aion-2-Zugangskarte vor dem Start: Playtest, LST, Frühstart und der 5. Oktober",
      description: "Vier offizielle Wege führen vor dem Start in Aion 2: die Steam-Playtest-Anfrage, der Launch Scale Test 17.–18. September (für alle offen, ohne Key), der Founder's-Pack-Frühstart 30. September – 4. Oktober und der Free-to-play-Start am 5. Oktober. Sortiert nach Zugang, Übernahme und Kosten.",
      intro: "Bis zum Start am 5. Oktober bietet Aion 2 vier separate, leicht verwechselbare offizielle Wege: einen Steam-Playtest-Knopf mit „request access“, einen offenen Test Mitte September, ein bezahltes Frühstart-Fenster und dann den Free-to-play-Start. Dieser Guide kartiert jeden Weg — wer ihn nutzen kann, was enthalten ist, was gelöscht wird.",
      sourceNote: "Basierend auf der AION-2-Steampage (abgerufen und verifiziert am 31. August 2026), abgeglichen mit dem Gamescom-2026-Bericht von Massively Overpowered (Stresstest 17.–18. September, Founder's-Pack-Headstart 30. September – 4. Oktober).",
      keywords: ["Aion 2 Zugang vor Start", "Aion 2 Playtest Anfrage", "Aion 2 Launch Scale Test", "Aion 2 Frühstart", "Aion 2 früh spielen"],
      sections: [
        section("four-routes", "Die vier Wege im Überblick", "Die Steampage zeigt einen „Join the AION 2 Playtest“-Bereich; eine separate Ankündigung deckt den LST 17.–18. September ab; alle drei Founder's-Packs markieren „Advance Access Starts 30 Sep“; das Erscheinungsdatum ist der 5. Oktober. Vier verschiedene Mechanismen. Playtest und LST sind kostenlos und begrenzt; der Pack-Frühstart ist bezahlt (5 Tage); der 5. Oktober ist kostenlos und dauerhaft."),
        section("playtest-request", "Weg 1 — Steam-Playtest-Anfrage (kostenlos, einladungsbasiert)", "Die Seite lädt ein zu „Request access and you'll get notified when the developer is ready for more participants.“ Das ist Steams Playtest-Mechanismus: Zugriff in Wellen, nicht an festen Terminen. Kostenlos und unverbindlich. Der LST 17.–18. September ist eine getrennte Tür, offen für alle ohne Key. Fordern Sie den Playtest trotzdem an — es kostet nichts."),
        section("lst", "Weg 2 — Launch Scale Test, 17.–18. September (kostenlos, für alle offen)", "NCSoft kündigt einen LST für Donnerstag und Freitag, 17.–18. September, an — Umgebung ähnlich dem echten Dienst, um Server- und Infrastrukturstabilität zu prüfen und Spielern das Erlebnis vor dem Start zu ermöglichen. Vorabdownload am 16. Für alle auf Steam und PURPLE, ohne Key, Einladung oder Registrierung. Fortschritt wird gedeckelt und am Ende gelöscht. Bester kostenloser Leistungscheck vor dem Bezahlen."),
        section("founder-early-access", "Weg 3 — Founder's-Pack-Frühstart, 30. September – 4. Oktober (bezahlt)", "Alle drei Packs (Standard, Deluxe, Ultimate) gewähren „Advance Access Starts 30 Sep“ — fünf Tage Frühstart vom 30. September bis 4. Oktober. Ein Kauf, kein freier Weg. PURPLE bietet bezahlte Upgrades zwischen Stufen; Steam listet derzeit keins — wählen Sie die Stufe vor dem Checkout."),
        section("launch", "Weg 4 — Free-to-play-Start, 5. Oktober", "Das Spiel erscheint am 5. Oktober 2026 kostenlos auf dem PC (Steam und PURPLE) in Nord-/Südamerika, Europa und Asien. Die Steampage zeigt „5 Oct, 2026“ und „Coming 5 Oct, 2026“. Kein Kauf nötig; In-App-Käufe vorhanden. LST-Fortschritt überträgt sich nicht."),
        section("decision-guide", "Welchen Weg wollen Sie?", "Kostenlos und neugierig — Playtest anfordern und LST 17.–18. September mitmachen. Bezahlter Frühstart — ein Founder's-Pack für den Zugang 30. September – 4. Oktober, Stufe einmal wählen. Nur das Spiel — auf den 5. Oktober warten; der kostenlose LST lohnt für einen Performance-Check trotzdem."),
      ],
    }),
    es: articleCopy(guideLabels, "es", 5, {
      eyebrow: "MAPA DE ACCESO PREVIA AL LANZAMIENTO",
      title: "Mapa de acceso previo de Aion 2: Playtest, LST, acceso anticipado y el lanzamiento del 5 de octubre",
      description: "Cuatro caminos oficiales llevan a Aion 2 antes del lanzamiento: la solicitud de Steam Playtest, el test de carga 17–18 de septiembre (abierto a todos, sin clave), el acceso anticipado de packs Fundador del 30 de septiembre al 4 de octubre, y el lanzamiento gratuito del 5 de octubre. Ordenados por quién entra, qué permanece y el costo.",
      intro: "Hasta el lanzamiento del 5 de octubre, Aion 2 ofrece cuatro accesos oficiales distintos y fáciles de confundir: un botón de Steam Playtest «request access», un test abierto a mediados de septiembre, una ventana de acceso anticipado de pago y luego el lanzamiento gratuito. Este mapa detalla cada vía — quién puede usarla, qué incluye, qué se borra.",
      sourceNote: "Basado en la página de Steam de AION 2 (recuperada y verificada el 31 de agosto de 2026), cotejado con el informe Gamescom 2026 de Massively Overpowered (test de carga 17–18 de septiembre, ventaja inicial de packs Fundador 30 de septiembre – 4 de octubre).",
      keywords: ["Aion 2 acceso previo", "Aion 2 solicitud playtest", "Aion 2 Launch Scale Test", "Aion 2 acceso anticipado", "Aion 2 jugar antes"],
      sections: [
        section("four-routes", "Las cuatro vías de un vistazo", "La página de Steam muestra una sección «Join the AION 2 Playtest»; un anuncio aparte cubre el test de carga 17–18 de septiembre; los tres packs Fundador marcan «Advance Access Starts 30 Sep»; la salida es el 5 de octubre. Cuatro mecanismos distintos. Playtest y LST son gratuitos y limitados; el pack Fundador es de pago (5 días); el 5 de octubre es gratuito y permanente."),
        section("playtest-request", "Vía 1 — Solicitud de Steam Playtest (gratuita, por invitación)", "La página invita a «Request access and you'll get notified when the developer is ready for more participants.» Es el mecanismo playtest de Steam: acceso por oleadas, no en fecha fija. Gratuito y sin compromiso. El LST del 17–18 de septiembre es una puerta aparte, abierta a todos sin clave. Solicita igualmente el playtest, no cuesta nada."),
        section("lst", "Vía 2 — Launch Scale Test, 17–18 de septiembre (gratuito, abierto a todos)", "NCSoft anuncia un test de carga jueves y viernes 17–18 de septiembre, en un entorno similar al servicio real, para comprobar la estabilidad de servidores e infraestructura y dejar probar el juego antes del lanzamiento. Precarga el 16. Abierto a todos en Steam y PURPLE, sin clave, invitación ni registro. Progresión limitada y borrada al final. Mejor control gratuito de rendimiento antes de pagar."),
        section("founder-early-access", "Vía 3 — Acceso anticipado de packs Fundador, 30 de septiembre – 4 de octubre (de pago)", "Los tres packs (Standard, Deluxe, Ultimate) dan «Advance Access Starts 30 Sep»: cinco días de acceso anticipado del 30 de septiembre al 4 de octubre. Es una compra, no una vía gratuita. PURPLE ofrece mejoras de pago entre niveles; Steam no lista ninguna — elige tu nivel antes del pago."),
        section("launch", "Vía 4 — Lanzamiento gratuito, 5 de octubre", "El juego sale free-to-play en PC (Steam y PURPLE) el 5 de octubre de 2026 en Norteamérica, Sudamérica, Europa y Asia. La página de Steam muestra «5 Oct, 2026» y «Coming 5 Oct, 2026». Sin compra necesaria; compras integradas presentes. La progresión del LST no se transfiere."),
        section("decision-guide", "¿Qué vía quieres?", "Gratis y curioso — solicita el Playtest y únete al LST del 17–18 de septiembre. Ventaja de pago — compra un pack Fundador para el acceso del 30 de septiembre al 4 de octubre, elige el nivel una vez. Solo quieres el juego — espera al 5 de octubre; el LST gratuito sigue valiendo para un control de rendimiento."),
      ],
    }),
    "pt-br": articleCopy(guideLabels, "pt-br", 5, {
      eyebrow: "MAPA DE ACESSO PRÉ-LANÇAMENTO",
      title: "Mapa de acesso pré-lançamento do Aion 2: Playtest, LST, acesso antecipado e o lançamento de 5 de outubro",
      description: "Quatro caminhos oficiais levam ao Aion 2 antes do lançamento: o pedido de acesso ao Steam Playtest, o teste de carga 17–18 de setembro (aberto a todos, sem chave), o acesso antecipado dos packs Fundador de 30 de setembro a 4 de outubro, e o lançamento gratuito de 5 de outubro. Ordenados por quem entra, o que permanece e o custo.",
      intro: "Até o lançamento de 5 de outubro, o Aion 2 oferece quatro acessos oficiais distintos e fáceis de confundir: um botão de Steam Playtest «request access», um teste aberto em meados de setembro, uma janela de acesso antecipado paga e depois o lançamento gratuito. Este mapa detalha cada via — quem pode usá-la, o que inclui, o que é apagado.",
      sourceNote: "Com base na página da Steam do AION 2 (recuperada e verificada em 31 de agosto de 2026), cruzado com o relato Gamescom 2026 da Massively Overpowered (teste de carga 17–18 de setembro, vantagem inicial dos packs Fundador 30 de setembro – 4 de outubro).",
      keywords: ["Aion 2 acesso pré-lançamento", "Aion 2 pedido playtest", "Aion 2 Launch Scale Test", "Aion 2 acesso antecipado", "Aion 2 jogar antes"],
      sections: [
        section("four-routes", "As quatro vias de uma olhada", "A página da Steam mostra uma seção «Join the AION 2 Playtest»; um anúncio à parte cobre o teste de carga 17–18 de setembro; os três packs Fundador marcam «Advance Access Starts 30 Sep»; o lançamento é 5 de outubro. Quatro mecanismos distintos. Playtest e LST são gratuitos e limitados; o pack Fundador é pago (5 dias); 5 de outubro é gratuito e permanente."),
        section("playtest-request", "Via 1 — Pedido de Steam Playtest (gratuito, por convite)", "A página convida a «Request access and you'll get notified when the developer is ready for more participants.» É o mecanismo playtest da Steam: acesso por ondas, não em data fixa. Gratuito e sem compromisso. O LST de 17–18 de setembro é uma porta separada, aberta a todos sem chave. Peça o playtest mesmo assim, não custa nada."),
        section("lst", "Via 2 — Launch Scale Test, 17–18 de setembro (gratuito, aberto a todos)", "A NCSoft anuncia um teste de carga quinta e sexta, 17–18 de setembro, em ambiente semelhante ao serviço real, para verificar a estabilidade de servidores e infraestrutura e deixar os jogadores experimentarem antes do lançamento. Pré-download dia 16. Aberto a todos na Steam e PURPLE, sem chave, convite ou registro. Progressão limitada e apagada ao final. Melhor verificação gratuita de desempenho antes de pagar."),
        section("founder-early-access", "Via 3 — Acesso antecipado dos packs Fundador, 30 de setembro – 4 de outubro (pago)", "Os três packs (Standard, Deluxe, Ultimate) dão «Advance Access Starts 30 Sep»: cinco dias de acesso antecipado de 30 de setembro a 4 de outubro. É uma compra, não uma via gratuita. A PURPLE oferece melhorias pagas entre níveis; a Steam não lista nenhuma — escolha seu nível antes do pagamento."),
        section("launch", "Via 4 — Lançamento gratuito, 5 de outubro", "O jogo sai free-to-play no PC (Steam e PURPLE) em 5 de outubro de 2026 na América do Norte, do Sul, Europa e Ásia. A página da Steam mostra «5 Oct, 2026» e «Coming 5 Oct, 2026». Sem compra necessária; compras integradas presentes. A progressão do LST não é transferida."),
        section("decision-guide", "Qual via você quer?", "Grátis e curioso — peça o Playtest e entre no LST de 17–18 de setembro. Vantagem paga — compre um pack Fundador para o acesso de 30 de setembro a 4 de outubro, escolha o nível uma vez. Só quer o jogo — espere 5 de outubro; o LST gratuito ainda vale para um controle de desempenho."),
      ],
    }),
    ru: articleCopy(guideLabels, "ru", 5, {
      eyebrow: "КАРТА ДОСТУПА ДО ЗАПУСКА",
      title: "Карта доступа до запуска Aion 2: Playtest, LST, ранний доступ и запуск 5 октября",
      description: "Четыре официальных пути ведут в Aion 2 до запуска: запрос доступа Steam Playtest, стресс-тест 17–18 сентября (открыт для всех, без ключа), ранний доступ паков основателя 30 сентября – 4 октября и бесплатный запуск 5 октября. Разбор по доступу, сохранению и цене.",
      intro: "До запуска 5 октября Aion 2 предлагает четыре отдельных и легко перепутываемых официальных пути: кнопка Steam Playtest «request access», открытый тест в середине сентября, платное окно раннего доступа и сам бесплатный запуск. Эта карта разбирает каждый путь — кто может им пользоваться, что он включает, что удаляется.",
      sourceNote: "На основе страницы AION 2 в Steam (получена и проверена 31 августа 2026), сверено с отчётом Massively Overpowered с Gamescom 2026 (стресс-тест 17–18 сентября, ранний старт паков основателя 30 сентября – 4 октября).",
      keywords: ["Aion 2 доступ до запуска", "Aion 2 запрос плейтеста", "Aion 2 Launch Scale Test", "Aion 2 ранний доступ", "Aion 2 сыграть раньше"],
      sections: [
        section("four-routes", "Четыре пути в двух словах", "Страница Steam показывает секцию «Join the AION 2 Playtest»; отдельный анонс покрывает стресс-тест 17–18 сентября; все три пака основателя помечены «Advance Access Starts 30 Sep»; релиз — 5 октября. Четыре разных механизма. Playtest и LST бесплатны и ограничены; ранний доступ пака платный (5 дней); 5 октября бесплатно и навсегда."),
        section("playtest-request", "Путь 1 — Запрос Steam Playtest (бесплатно, по приглашениям)", "Страница приглашает «Request access and you'll get notified when the developer is ready for more participants.» Это механизм playtest Steam: доступ волнами, не по фиксированной дате. Бесплатно и без обязательств. LST 17–18 сентября — отдельная дверь, открытая всем без ключа. Запросите плейтест всё равно — это бесплатно."),
        section("lst", "Путь 2 — Launch Scale Test, 17–18 сентября (бесплатно, открыт всем)", "NCSoft анонсирует стресс-тест в четверг и пятницу, 17–18 сентября, в среде, близкой к реальному сервису, чтобы проверить стабильность серверов и инфраструктуры и дать игрокам попробовать игру до запуска. Предзагрузка 16-го. Открыт всем на Steam и PURPLE, без ключа, приглашения и регистрации. Прогресс ограничен и удаляется в конце. Лучшая бесплатная проверка ПК перед оплатой."),
        section("founder-early-access", "Путь 3 — Ранний доступ паков основателя, 30 сентября – 4 октября (платно)", "Все три пака (Standard, Deluxe, Ultimate) дают «Advance Access Starts 30 Sep»: пять дней раннего доступа с 30 сентября по 4 октября. Это покупка, а не бесплатный путь. PURPLE предлагает платные апгрейды между уровнями; Steam сейчас не публикует — выбирайте уровень до оплаты."),
        section("launch", "Путь 4 — Бесплатный запуск, 5 октября", "Игра выходит free-to-play на ПК (Steam и PURPLE) 5 октября 2026 в Северной/Южной Америке, Европе и Азии. Страница Steam показывает «5 Oct, 2026» и «Coming 5 Oct, 2026». Без покупки; встроенные покупки есть. Прогресс LST не переносится."),
        section("decision-guide", "Какой путь вам нужен?", "Бесплатно и любопытно — запросите Playtest и присоединитесь к LST 17–18 сентября. Платное преимущество — купите пак основателя для доступа 30 сентября – 4 октября, уровень выберите один раз. Просто хотите игру — ждите 5 октября; бесплатный LST всё равно полезен для проверки производительности."),
      ],
    }),
    "zh-hant": articleCopy(guideLabels, "zh-hant", 5, {
      eyebrow: "預發布接入路線圖",
      title: "Aion 2 預發布接入路線圖：Playtest、LST、搶先體驗與 10 月 5 日上線",
      description: "上線前有四條官方路徑進入 Aion 2：Steam Playtest 接入申請、9 月 17–18 日 Launch Scale Test（全開放、免 key）、9 月 30 日–10 月 4 日創始人包搶先體驗，以及 10 月 5 日免費遊玩上線。本指南按准入、是否保留、各自代價來梳理。",
      intro: "從現在到 10 月 5 日上線，Aion 2 提供四條彼此獨立、又容易混淆的官方進入路徑：寫著「request access」的 Steam Playtest 按鈕、9 月中全開放的 Launch Scale Test、付費的創始人包搶先體驗視窗，以及免費遊玩上線本身。本指南逐條標注每一條——誰能用、包含什麼、什麼會被清空、你真正需要哪一條。",
      sourceNote: "基於 AION 2 Steam 商店頁（2026-08-31 檢索並核對），並與 Massively Overpowered 的 Gamescom 2026 報導（壓測 9 月 17–18 日、創始人包搶先 9 月 30 日–10 月 4 日）交叉核對。",
      keywords: ["Aion 2 預發布接入", "Aion 2 Playtest 申請", "Aion 2 Launch Scale Test", "Aion 2 搶先體驗", "Aion 2 提前玩"],
      sections: [
        section("four-routes", "四條路徑一覽", "Steam 商店頁現顯示一個「Join the AION 2 Playtest」區塊要求申請接入；另一則公告覆蓋 9 月 17–18 日 Launch Scale Test；三個創始人包均標記「Advance Access Starts 30 Sep」；發售日期本身是 10 月 5 日。這是四個不同機制，而非一個。關鍵區別：Playtest 申請與 LST 免費且受限；創始人包搶先體驗付費且給 5 天；10 月 5 日上線免費且永久。"),
        section("playtest-request", "路徑 1——Steam Playtest 申請（免費、邀請制）", "商店頁邀請你「Request access and you'll get notified when the developer is ready for more participants.」這是 Steam 的 playtest 機制：你申請，接入可能分批發放，而非固定日期。它免費且低風險——申請不花錢，也不構成任何承諾。與此獨立的 9 月 17–18 日 LST 公告稱全開放、免 key，所以兩者不是同一扇門。你仍可順便申請 playtest，反正免費。"),
        section("lst", "路徑 2——Launch Scale Test，9 月 17–18 日（免費、全開放）", "NCSoft 公布於 9 月 17–18 日（週四、週五）舉辦 LST，構建與真實服務相近的環境以檢驗伺服器與基礎設施穩定性，同時讓玩家在上線前體驗遊戲。預下載 9 月 16 日開啟。測試對 Steam 與 PURPLE 上所有人開放——無 key、無邀請、無註冊。進度封頂並在測試結束時清空。這是付費搶先或上線日排隊之前，免費檢驗你 PC 效能的最佳途徑。"),
        section("founder-early-access", "路徑 3——創始人包搶先體驗，9 月 30 日–10 月 4 日（付費）", "三個創始人包——標準、豪華、終極——均授予「Advance Access Starts 30 Sep」，即 9 月 30 日至 10 月 4 日共五天搶先體驗，之後 10 月 5 日正式上線。這些包是購買決策，而非免費路徑。PURPLE 提供檔位間的付費升級路徑，Steam 目前未列出——請在結帳前一次選好。"),
        section("launch", "路徑 4——免費遊玩上線，10 月 5 日", "遊戲於 2026 年 10 月 5 日在 PC（Steam 與 PURPLE）免費遊玩上線，覆蓋北美、南美、歐洲與亞洲。Steam 頁面將發售日列為「5 Oct, 2026」。上線遊玩無需購買；內購是變現層。LST 的進度不保留，搶先體驗是唯一永久領先。"),
        section("decision-guide", "你該選哪一條？", "免費且好奇——申請 Steam Playtest 並參加 9 月 17–18 日 LST。付費搶跑——購買創始人包獲取 9 月 30 日–10 月 4 日搶先體驗，一次選好檔位。只想要遊戲——等到 10 月 5 日；免費的 LST 仍值得做一次效能體檢。無論選哪條，商店頁都是隨檔期穩定而持續更新的參考。"),
      ],
    }),
  },
};
