import { articleCopy, localizations, newsLabels, publishedVerified, section } from "./trending-september-1-shared";
import type { ContentEntry, ContentHeroImage, ContentSource } from "./content-registry";

/* ARTICLE 3 — Rumor check: a August 30 headline claimed a September launch and a "P2W reversal"; the record says October 5 */

const rcSource1: ContentSource = {
  id: "vpesports-p2w-headline-2026-08-30",
  kind: "third-party", publisher: "VPEsports",
  label: "AION 2: P2W scandal reversed, global launch September (headline-checked; article body not retrievable)",
  url: "https://news.google.com/rss/search?q=%22Aion+2%22+P2W+when%3A120h&hl=en-US&gl=US&ceid=US:en",
  publishedAt: "2026-08-30",
  retrievedAt: "2026-09-01",
  verifiedAt: "2026-09-01",
  localizations: localizations({
    "zh-hans": "AION 2：P2W 争议逆转，全球 9 月上线（仅标题核实）",
    en: "AION 2: P2W scandal reversed, global launch September (headline only)",
    fr: "AION 2 : controverse P2W inversée, lancement mondial en septembre (titre seul)",
    de: "AION 2: P2W-Skandal dreht sich um, Weltstart im September (nur Titel)",
    es: "AION 2: polémica P2W revertida, lanzamiento mundial en septiembre (solo titular)",
    ja: "AION 2：P2W論争が逆転、グローバル発売は9月（見出しのみ）",
    "pt-br": "AION 2: polêmica P2W revertida, lançamento global em setembro (apenas título)",
    ru: "AION 2: скандал P2W отменён, мировой запуск в сентябре (только заголовок)",
    ko: "AION 2: P2W 논란 뒤집힘, 9월 글로벌 출시(제목만 확인)",
    "zh-hant": "AION 2：P2W 爭議逆轉，全球 9 月上市（僅標題核實）",
  }, "https://news.google.com/rss/search?q=%22Aion+2%22+P2W+when%3A120h&hl=en-US&gl=US&ceid=US:en"),
};

const rcSource2: ContentSource = {
  id: "steam-store-aion2-release-2026-09-01",
  kind: "platform", publisher: "Steam",
  label: "AION 2 — Steam Store Page (Release 5 Oct 2026; Advance Access Starts 30 Sep)",
  url: "https://store.steampowered.com/app/3393110/AION_2/",
  publishedAt: "2026-08-26",
  retrievedAt: "2026-09-01",
  verifiedAt: "2026-09-01",
  localizations: localizations({
    "zh-hans": "AION 2——Steam 商店页（发售 2026-10-05；抢先体验 9-30 开始）",
    en: "AION 2 — Steam Store Page (Release 5 Oct 2026; Advance Access Starts 30 Sep)",
    fr: "AION 2 — Page boutique Steam (sortie le 5 oct. 2026 ; accès anticipé le 30 sept.)",
    de: "AION 2 — Steam-Store-Seite (Release 5. Okt. 2026; Vorabzugang ab 30. Sep.)",
    es: "AION 2 — Página de Steam (lanzamiento 5 oct 2026; acceso anticipado 30 sep)",
    ja: "AION 2 — Steam ストアページ（2026-10-05発売、先行体験9-30開始）",
    "pt-br": "AION 2 — Página da Steam (lançamento 5 out 2026; acesso antecipado 30 set)",
    ru: "AION 2 — Страница Steam (выход 05.10.2026; ранний доступ с 30.09)",
    ko: "AION 2 — Steam 상점 페이지(2026-10-05 출시, 9-30 얼리 액세스 시작)",
    "zh-hant": "AION 2——Steam 商店頁（發售 2026-10-05；搶先體驗 9-30 開始）",
  }, "https://store.steampowered.com/app/3393110/AION_2/"),
};

const rcHero: ContentHeroImage = {
  src: "https://blogfiles.ncsoft.net/news/af7330da-4ff6-4b58-aece-400e6061a3be.jpg",
  width: 1100, height: 605,
  credit: "NC Corporation",
  sourceUrl: "https://aion2.plaync.com/ja-jp/board/notice/list",
  rights: "linked-official-media",
  translations: {
    "zh-hans": { alt: "Aion 2 上线日期流言核查配图", caption: "NC 官方配图；8 月底有媒体标题称 Aion 2「全球 9 月上线」，但 Steam 商店页明示发售日为 2026-10-05、抢先体验 9-30 开始。" },
    en: { alt: "Aion 2 release-date rumor check image", caption: "Official NC artwork; a late-August headline claimed Aion 2 would launch globally in September, but the Steam store page lists the release as 2026-10-05 with advance access starting September 30." },
    fr: { alt: "Image de vérification de la rumeur de sortie d'Aion 2", caption: "Visuel officiel NC ; un titre de fin août affirmait un lancement mondial en septembre, mais la page Steam liste la sortie au 05/10/2026 avec accès anticipé le 30/09." },
    de: { alt: "Bild zum Gerücht-Check des Aion-2-Starttermins", caption: "Offizielles NC-Artwork; eine Schlagzeile von Ende August behauptete einen Weltstart im September, die Steampage listet den Release aber am 05.10.2026 mit Vorabzugang ab 30.09." },
    es: { alt: "Imagen del control de rumores de la fecha de lanzamiento de Aion 2", caption: "Arte oficial de NC; un titular de finales de agosto afirmaba un lanzamiento mundial en septiembre, pero la página de Steam lista la salida el 05/10/2026 con acceso anticipado el 30/09." },
    ja: { alt: "Aion 2 発売日デマ検証画像", caption: "NC公式アートワーク；8月末の見出しは9月のグローバル発売としましたが、Steamストアページは正式リリース2026-10-05・先行体験9-30開始と記載しています。" },
    "pt-br": { alt: "Imagem da verificação do boato da data de lançamento do Aion 2", caption: "Arte oficial da NC; um título de fim de agosto afirmava lançamento global em setembro, mas a página da Steam lista a saída em 05/10/2026 com acesso antecipado em 30/09." },
    ru: { alt: "Изображение проверки слуха о дате выхода Aion 2", caption: "Официальный арт NC; заголовок конца августа утверждал мировой запуск в сентябре, но страница Steam указывает выход 05.10.2026 и ранний доступ с 30.09." },
    ko: { alt: "Aion 2 출시일 루머 확인 이미지", caption: "NC 공식 이미지입니다. 8월 말 한 매체가 9월 글로벌 출시라고 했지만 Steam 상점 페이지는 정식 출시 2026-10-05·얼리 액세스 9-30 시작으로 표시합니다." },
    "zh-hant": { alt: "Aion 2 上市日期流言核查配圖", caption: "NC 官方配圖；8 月底有媒體標題稱 Aion 2「全球 9 月上市」，但 Steam 商店頁明示發售日為 2026-10-05、搶先體驗 9-30 開始。" },
  },
};

export const trendingSeptember1Article3: ContentEntry = {
  section: "news",
  slug: "aion-2-release-date-rumor-check",
  schemaType: "NewsArticle",
  publishedAt: "2026-09-01",
  updatedAt: "2026-09-01",
  readingMinutes: 5,
  publication: publishedVerified,
  sources: [rcSource1, rcSource2],
  heroImage: rcHero,
  related: [
    { kind: "content", section: "news", slug: "aion-2-release-date-october-5-2026" },
    { kind: "content", section: "news", slug: "aion-2-steam-store-countdown-four-weeks" },
    { kind: "content", section: "news", slug: "aion-2-genai-asset-disclosure-steam" },
    { kind: "content", section: "guides", slug: "aion-2-monetization-f2p-cosmetics-guide" },
  ],
  translations: {
    en: articleCopy(newsLabels, "en", 5, {
      eyebrow: "RUMOR CHECK",
      title: "Aion 2 “September launch” Headline Checked: Steam Says October 5",
      description: "A late-August headline claimed Aion 2's P2W controversy was “reversed” and the global launch was “September”. The verifiable record differs: the Steam store page lists release as 2026-10-05, with advance access starting September 30. Here is what is true, what is not, and why the confusion exists.",
      intro: "On August 30, a headline aggregating around Aion 2 claimed the game's global launch would happen in September and that a pay-to-win controversy had been “reversed”. Neither claim survives contact with the primary sources we verified on September 1: Steam lists the release as 2026-10-05, and advance access starts September 30. This report separates the signal from the noise.",
      sourceNote: "The August 30 headline exists in Google News (title-verified; the article body was not retrievable from the source domain). The authoritative contradiction comes from the Aion 2 Steam store page, fetched and verified on September 1, 2026.",
      keywords: ["Aion 2 release date check", "Aion 2 September launch rumor", "Aion 2 P2W controversy", "Aion 2 October 5", "Aion 2 false headline"],
      sections: [
        section("the-headline", "The Headline That Circulated", ["On August 30, an outlet indexed by Google News published the headline “AION 2: P2W scandal reversed, global launch September”. We verified the headline's existence in the index; we could not verify the article body, which the source domain did not serve.", "The headline bundles two claims: a monetization reversal and a September launch window. Both are checkable against primary sources — which is the point of this report.", "Verification matters because launch-date confusion costs players real decisions: when to request a playtest, when to pre-load, and when to book time off."]),
        section("what-steam-says", "What the Store Page Actually Says", ["The Aion 2 Steam store page, fetched on September 1, 2026, lists “Release Date: 5 Oct, 2026” and repeats “Coming 5 Oct, 2026” in the store panel. Advance access is stated as “Advance Access Starts 30 Sep”, five days ahead of release.", "The countdown line reads “This game plans to unlock in approximately 4 weeks”, which is consistent with an October 5 unlock, not a September one.", "There is no September global-release date anywhere on the page. The only September reference is the 30th — the advance access start."]),
        section("the-september-confusion", "Where the September Confusion Comes From", ["September 30 is real, and it is a launch-adjacent date: Founder's Packs grant five days of early access beginning September 30. A headline that compresses “September 30 early access” into “September launch” is technically wrong but not hard to stumble into.", "The Launch Scale Test also lands mid-September (September 17–18), adding more “September” signals for anyone not checking dates precisely.", "NCsoft itself once suggested a September launch for the global service before the Gamescom confirmations settled on October 5 — so older pages can carry the earlier framing too."]),
        section("the-p2w-claim", "The P2W Reversal Claim, Separately", ["The “P2W scandal reversed” part of the headline is harder to pin down because the article body was not retrievable. What the store page verifiably shows is a cosmetics-led free-to-play posture with in-app purchases, and our site's earlier verified coverage documents the monetization Q&A around member benefits.", "What this site independently documented: the monetization conversation is ongoing and NCsoft has publicly positioned the global game as free-to-play with a cosmetic-led shop (see our monetization guide). Whether that satisfies the word “reversal” is a judgment the headline made, not a fact it proved.", "Treat the P2W characterization as an editorial claim unless NCsoft publishes a change notice we can cite."]),
        section("bottom-line", "The Bottom Line", ["Release date: October 5, 2026, per Steam and the Gamescom confirmations. Advance access: September 30. The Launch Scale Test: September 17–18. Those are the dates that matter.", "If you see “September launch” anywhere, read it as sloppy shorthand for the September 30 advance access, not a change in plan.", "Bookmark the Steam store page as the reference: it is dated, machine-readable, and currently unambiguous."]),
      ],
    }),
    "zh-hans": articleCopy(newsLabels, "zh-hans", 5, {
      eyebrow: "流言核查",
      title: "Aion 2「9 月上线」标题核查：Steam 明示 10 月 5 日",
      description: "8 月底有媒体标题称 Aion 2 的 P2W 争议「逆转」、全球「9 月上线」。可核实的事实不同：Steam 商店页明示发售日 2026-10-05，抢先体验 9 月 30 日开始。以下是真相、误读与混淆来源。",
      intro: "8 月 30 日，一则围绕 Aion 2 的标题声称游戏全球上线将在 9 月、且一场付费变强争议已「逆转」。两个说法都经不住 9 月 1 日我们核实的一手来源：Steam 明示发售日 2026-10-05，抢先体验 9 月 30 日开始。本报告区分信号与噪音。",
      sourceNote: "8 月 30 日标题存在于 Google News（已核实标题；源域名未提供正文）。权威反驳来自 Aion 2 Steam 商店页，2026-09-01 抓取并核对。",
      keywords: ["Aion 2 发售日期核查", "Aion 2 9月上线流言", "Aion 2 P2W 争议", "Aion 2 10月5日", "Aion 2 假标题"],
      sections: [
        section("the-headline", "流传的标题", ["8 月 30 日，Google News 收录的某媒体发布标题「AION 2：P2W 争议逆转，全球 9 月上线」。我们核实了标题存在于索引；无法核实正文，源域名未提供。", "标题捆绑两个说法：变现逆转与 9 月上线窗口。两者都可对照一手来源核查——这正是本报告的意义。", "核实重要，因为日期混淆让玩家付出真实代价：何时申请试玩、何时预载、何时请假。"]),
        section("what-steam-says", "商店页实际显示什么", ["Aion 2 Steam 商店页（2026-09-01 抓取）列出「Release Date: 5 Oct, 2026」，商店面板重复「Coming 5 Oct, 2026」。抢先体验标注「Advance Access Starts 30 Sep」，即发售前 5 天。", "倒计时行「This game plans to unlock in approximately 4 weeks」与 10 月 5 日解锁一致，而非 9 月。", "页面上没有任何 9 月全球发售日期。唯一的 9 月参照是 30 日——抢先体验开始。"]),
        section("the-september-confusion", "「9 月」混淆从何而来", ["9 月 30 日是真的，且是临近发售的日期：创始人包自 9 月 30 日起提供五天抢先体验。把「9 月 30 日抢先」压缩成「9 月上线」的标题在技术上错误，但并非不可能踩到。", "Launch Scale Test 也落在 9 月中旬（9 月 17–18 日），为不精确核对日期的人增加「9 月」信号。", "NCsoft 早年公告确曾暗示全球服务 9 月上线，后经 Gamescom 确认落在 10 月 5 日——所以旧页面可能仍带早期表述。"]),
        section("the-p2w-claim", "P2W 逆转说法，分开看", ["「P2W 争议逆转」部分更难落定，因为正文不可取。商店页可核实的是以外观为主导的免费游玩姿态并含内购；本站此前已核实变现问答。", "本站独立记录的是：变现讨论仍在进行，NCsoft 公开将全球版定位为免费游玩、外观主导商店（见本站变现指南）。称其为「逆转」是标题的判断，不是它证明的事实。", "若无 NCsoft 可引用的变更公告，请把 P2W 定性视为编辑主张。"]),
        section("bottom-line", "结论", ["发售日：2026 年 10 月 5 日（Steam 与 Gamescom 确认一致）。抢先体验：9 月 30 日。Launch Scale Test：9 月 17–18 日。这些才是重要的日期。", "看到「9 月上线」，请读作对 9 月 30 日抢先体验的粗糙简写，而非计划变更。", "把 Steam 商店页设为参照：它有日期戳、可机读、当前毫不含糊。"]),
      ],
    }),
    ko: articleCopy(newsLabels, "ko", 5, {
      eyebrow: "루머 확인",
      title: "아이온2 '9월 출시' 제목 검증: Steam은 10월 5일",
      description: "8월 말 한 매체가 아이온2의 P2W 논란이 '뒤집혔다'며 9월 글로벌 출시라고 했습니다. 검증 가능한 사실은 다릅니다: Steam 상점 페이지는 정식 출시 2026-10-05, 얼리 액세스 9월 30일 시작입니다.",
      intro: "8월 30일 자동 집계된 헤드라인이 아이온2의 9월 출시와 P2W 논란 '역전'을 주장했습니다. 두 주장 모두 9월 1일 확인한 1차 출처에 부딪혀 무너집니다. 본 기사는 신호와 잡음을 구분합니다.",
      sourceNote: "8월 30일 헤드라인은 Google News 인덱스에 존재합니다(제목 확인; 본문은 소스 도메인이 제공하지 않아 확인 불가). 권위 있는 반증은 아이온2 Steam 상점 페이지(2026-09-01 실측)입니다.",
      keywords: ["아이온2 출시일 확인", "아이온2 9월 출시 루머", "아이온2 P2W 논란", "아이온2 10월 5일", "아이온2 오정보"],
      sections: [
        section("the-headline", "유포된 헤드라인", "8월 30일 Google News 색인에 '아이온2: P2W 논란 역전, 9월 글로벌 출시' 제목이 나타났습니다. 제목의 존재는 확인했지만 본문은 소스 도메인이 제공하지 않아 확인 불가입니다. 두 가지 주장(수익화 역전·9월 창) 모두 1차 출처로 대조할 수 있습니다."),
        section("what-steam-says", "상점 페이지가 실제로 보여주는 것", "아이온2 Steam 상점 페이지(2026-09-01)는 'Release Date: 5 Oct, 2026'을 표시하고 'Coming 5 Oct, 2026'을 반복합니다. 얼리 액세스는 'Advance Access Starts 30 Sep'(출시 5일 전)입니다. 카운트다운도 10월 5일 해제와 일치합니다. 9월 발매일은 페이지에 없습니다."),
        section("the-september-confusion", "'9월' 혼동의 출처", "9월 30일은 실제이며 출시 인접 날짜입니다: 파운더스 팩이 9월 30일부터 5일 얼리 액세스를 줍니다. '9월 30일 선행'을 '9월 출시'로 압축한 제목은 기술적으로 틀립니다. LST(9월 17–18일)도 9월 신호를 더합니다. NC소프트의 초기 공지도 9월을 암시한 적 있습니다."),
        section("the-p2w-claim", "P2W 역전 주장은 별도로", "'P2W 논란 역전' 부분은 본문을 얻을 수 없어 더 어렵습니다. 상점 페이지가 확인시켜 주는 것은 외형 중심 무료 플레이 자세와 인앱 구매입니다. '역전'이라는 단어는 헤드라인의 판단이지 증명된 사실이 아닙니다. NC소프트가 인용 가능한 변경 공지를 내기 전까지는 편집적 주장으로 취급하세요."),
        section("bottom-line", "결론", "출시일은 2026년 10월 5일(Steam·Gamescom 확인 일치), 얼리 액세스 9월 30일, LST 9월 17–18일입니다. '9월 출시'는 9월 30일 선행의 부정확한 약칭으로 읽으세요. Steam 상점 페이지가 기준입니다."),
      ],
    }),
    ja: articleCopy(newsLabels, "ja", 5, {
      eyebrow: "デマ検証",
      title: "Aion 2「9月発売」見出し検証：Steamは10月5日",
      description: "8月末の見出しが、Aion 2 のP2W論争は「逆転」しグローバル発売は「9月」と主張しました。検証可能な事実は異なります：Steamストアページは正式リリース2026-10-05、先行体験9月30日開始です。",
      intro: "8月30日、Aion 2 を巡る見出しが9月のグローバル発売とP2W論争の「逆転」を主張しました。どちらも9月1日に確認した一次情報源で崩れます。本記事はシグナルとノイズを分けます。",
      sourceNote: "8月30日の見出しはGoogle Newsインデックスに存在します(タイトル確認;本文はソースドメインが提供せず確認不可)。権威ある反証はAion 2 Steamストアページ(2026-09-01取得)です。",
      keywords: ["Aion 2 発売日検証", "Aion 2 9月発売デマ", "Aion 2 P2W論争", "Aion 2 10月5日", "Aion 2 誤情報"],
      sections: [
        section("the-headline", "流布した見出し", "8月30日、Google Newsに索引された見出しが「AION 2：P2W論争逆転、9月グローバル発売」と報じました。見出しの存在は確認しましたが、本文はソースドメインが提供せず確認できません。二つの主張(収益化逆転・9月窓)はどちらも一次情報源で照合できます。"),
        section("what-steam-says", "ストアページが実際に示すもの", "Aion 2 Steamストアページ(2026-09-01取得)は「Release Date: 5 Oct, 2026」を表示し「Coming 5 Oct, 2026」を繰り返します。先行体験は「Advance Access Starts 30 Sep」(5日前)。カウントダウンも10月5日解放と一致し、ページに9月発売日はありません。"),
        section("the-september-confusion", "「9月」混乱の出所", "9月30日は実在し、発売に隣接する日付です:ファウンダーズパックが9月30日から5日間の先行体験を与えます。「9月30日先行」を「9月発売」に圧縮した見出しは技術的に誤りです。LST(9月17–18日)も9月シグナルを足します。NCソフトの初期告知も9月を示唆していました。"),
        section("the-p2w-claim", "P2W逆転主張は別建て", "「P2W論争逆転」部分は本文を得られず確定が困難です。ストアページが確認できるのは外見重視の基本無料姿勢とアプリ内課金です。「逆転」は見出しの判断であり証明された事実ではありません。NCソフトが引用可能な変更告知を出すまで編集的主張として扱ってください。"),
        section("bottom-line", "結論", "発売日は2026年10月5日(Steam・Gamescom確認が一致)、先行体験9月30日、LST 9月17–18日です。「9月発売」は9月30日先行の雑な略記として読み、Steamストアページを基準にしてください。"),
      ],
    }),
    fr: articleCopy(newsLabels, "fr", 5, {
      eyebrow: "VÉRIFICATION DE RUMEUR",
      title: "Titre « lancement en septembre » d'Aion 2 vérifié : Steam dit 5 octobre",
      description: "Un titre de fin août affirmait que la controverse P2W d'Aion 2 était « inversée » et le lancement mondial « en septembre ». Les faits vérifiables diffèrent : la page Steam liste la sortie au 05/10/2026, avec accès anticipé dès le 30 septembre.",
      intro: "Le 30 août, un titre autour d'Aion 2 prétendait un lancement mondial en septembre et une controverse P2W « inversée ». Les deux s'effondrent face aux sources primaires vérifiées le 1er septembre : Steam liste la sortie au 05/10/2026.",
      sourceNote: "Le titre du 30 août existe dans Google News (titre vérifié ; corps indisponible). La contradiction autoritaire vient de la page Steam d'Aion 2, récupérée le 1er septembre 2026.",
      keywords: ["Aion 2 date de sortie vérifiée", "Aion 2 rumeur septembre", "Aion 2 controverse P2W", "Aion 2 5 octobre", "Aion 2 fausse info"],
      sections: [
        section("the-headline", "Le titre diffusé", "Le 30 août, un média indexé par Google News a publié « AION 2 : controverse P2W inversée, lancement mondial en septembre ». Titre vérifié ; corps non serviable par le domaine source. Deux affirmations à confronter aux sources primaires."),
        section("what-steam-says", "Ce que dit vraiment la page", "La page Steam d'Aion 2 (1er septembre 2026) liste « Release Date: 5 Oct, 2026 » et « Coming 5 Oct, 2026 ». Accès anticipé : « Advance Access Starts 30 Sep ». Le compte à rebours (« environ 4 semaines ») convient au 5 octobre. Aucune date de septembre."),
        section("the-september-confusion", "D'où vient la confusion", "Le 30 septembre est réel et adjacent au lancement : les packs Fondateur donnent cinq jours dès le 30 septembre. Le test de charge (17–18 septembre) ajoute des signaux « septembre ». NCsoft a aussi suggéré septembre avant les confirmations de Gamescom."),
        section("the-p2w-claim", "Le volet P2W, séparément", "La partie « controverse P2W inversée » est difficile à établir faute de corps. Ce que la page vérifie : une posture free-to-play cosmétique avec achats intégrés. Le mot « inversée » est un jugement du titre, pas un fait prouvé."),
        section("bottom-line", "Conclusion", "Sortie : 5 octobre 2026 (Steam et Gamescom). Accès anticipé : 30 septembre. LST : 17–18 septembre. Un « lancement en septembre » doit se lire comme un raccourci du 30 septembre. La page Steam fait référence."),
      ],
    }),
    de: articleCopy(newsLabels, "de", 5, {
      eyebrow: "GERÜCHTE-CHECK",
      title: "Aion-2-„September-Start“-Schlagzeile geprüft: Steam sagt 5. Oktober",
      description: "Eine Schlagzeile von Ende August behauptete, die P2W-Kontroverse von Aion 2 sei „gedreht“ und der Weltstart sei „im September“. Die belegbare Lage ist anders: Die Steampage listet den Release am 05.10.2026, Vorabzugang ab 30. September.",
      intro: "Am 30. August behauptete eine Schlagzeile einen September-Weltstart und eine „gedrehte“ P2W-Kontroverse. Beides hält den am 1. September verifizierten Primärquellen nicht stand: Steam listet den Release am 05.10.2026.",
      sourceNote: "Die Schlagzeile vom 30. August existiert in Google News (Titel verifiziert; Körper nicht abrufbar). Der maßgebliche Widerspruch ist die Aion-2-Steampage, abgerufen am 1. September 2026.",
      keywords: ["Aion 2 Starttermin geprüft", "Aion 2 September-Gerücht", "Aion 2 P2W-Kontroverse", "Aion 2 5. Oktober", "Aion 2 Fehlinfo"],
      sections: [
        section("the-headline", "Die kursierende Schlagzeile", "Am 30. August veröffentlichte ein von Google News indexiertes Medium „AION 2: P2W-Skandal gedreht, Weltstart im September“. Titel verifiziert; der Körper war vom Quell-Domain nicht abrufbar. Beide Behauptungen lassen sich an Primärquellen prüfen."),
        section("what-steam-says", "Was die Seite wirklich zeigt", "Die Aion-2-Steampage (1. September 2026) listet „Release Date: 5 Oct, 2026“ und „Coming 5 Oct, 2026“. Vorabzugang: „Advance Access Starts 30 Sep“. Der Countdown passt zum 5. Oktober. Kein September-Datum auf der Seite."),
        section("the-september-confusion", "Woher die September-Verwirrung kommt", "Der 30. September ist real und startnah: Die Founder's Packs geben ab dem 30. September fünf Tage Vorabzugang. Der LST (17.–18. September) addiert „September“-Signale. NCsoft deutete vor Gamescom ebenfalls September an."),
        section("the-p2w-claim", "Der P2W-Teil, getrennt", "Der Teil „P2W gedreht“ ist ohne Körper schwer zu belegen. Die Seite belegt eine kosmetikgeführte Free-to-play-Haltung mit In-App-Käufen. „Gedreht“ ist ein Urteil der Schlagzeile, keine bewiesene Tatsache."),
        section("bottom-line", "Fazit", "Release: 5. Oktober 2026 (Steam und Gamescom). Vorabzugang: 30. September. LST: 17.–18. September. „Im September“ ist eine ungenaue Abkürzung für den 30. September. Die Steampage ist die Referenz."),
      ],
    }),
    es: articleCopy(newsLabels, "es", 5, {
      eyebrow: "VERIFICACIÓN DE RUMORES",
      title: "Titular de «lanzamiento en septiembre» de Aion 2 verificado: Steam dice 5 de octubre",
      description: "Un titular de finales de agosto afirmaba que la polémica P2W de Aion 2 estaba «revertida» y el lanzamiento mundial «en septiembre». Los hechos verificables difieren: la página de Steam lista la salida el 05/10/2026, con acceso anticipado el 30 de septiembre.",
      intro: "El 30 de agosto, un titular en torno a Aion 2 afirmaba un lanzamiento mundial en septiembre y una polémica P2W «revertida». Ambas afirmaciones se derrumban ante las fuentes primarias verificadas el 1 de septiembre: Steam lista la salida el 05/10/2026.",
      sourceNote: "El titular del 30 de agosto existe en Google News (título verificado; cuerpo no recuperable). La contradicción autorizada viene de la página de Steam de Aion 2, recuperada el 1 de septiembre de 2026.",
      keywords: ["Aion 2 fecha de lanzamiento verificada", "Aion 2 rumor septiembre", "Aion 2 polémica P2W", "Aion 2 5 de octubre", "Aion 2 desinformación"],
      sections: [
        section("the-headline", "El titular circulado", "El 30 de agosto, un medio indexado en Google News publicó «AION 2: polémica P2W revertida, lanzamiento mundial en septiembre». Título verificado; cuerpo no servido por el dominio fuente. Dos afirmaciones contrastables con fuentes primarias."),
        section("what-steam-says", "Lo que dice realmente la página", "La página de Steam de Aion 2 (1 de septiembre de 2026) lista «Release Date: 5 Oct, 2026» y «Coming 5 Oct, 2026». Acceso anticipado: «Advance Access Starts 30 Sep». El conteo («aproximadamente 4 semanas») cuadra con el 5 de octubre. Sin fecha de septiembre."),
        section("the-september-confusion", "De dónde viene la confusión", "El 30 de septiembre es real y adyacente: los packs Fundador dan cinco días desde el 30 de septiembre. El test de carga (17–18 de septiembre) suma señales de «septiembre». NCsoft también sugirió septiembre antes de las confirmaciones de Gamescom."),
        section("the-p2w-claim", "El apartado P2W, por separado", "La parte «polémica P2W revertida» es difícil de probar sin el cuerpo. Lo que la página verifica: una postura free-to-play cosmética con compras integradas. «Revertida» es un juicio del titular, no un hecho probado."),
        section("bottom-line", "Conclusión", "Salida: 5 de octubre de 2026 (Steam y Gamescom). Acceso anticipado: 30 de septiembre. LST: 17–18 de septiembre. Un «lanzamiento en septiembre» debe leerse como abreviatura del 30 de septiembre. La página de Steam es la referencia."),
      ],
    }),
    "pt-br": articleCopy(newsLabels, "pt-br", 5, {
      eyebrow: "VERIFICAÇÃO DE BOATO",
      title: "Título de «lançamento em setembro» do Aion 2 verificado: a Steam diz 5 de outubro",
      description: "Um título de fim de agosto afirmava que a polêmica P2W do Aion 2 estava «revertida» e o lançamento global «em setembro». Os fatos verificáveis diferem: a página da Steam lista a saída em 05/10/2026, com acesso antecipado a partir de 30 de setembro.",
      intro: "Em 30 de agosto, um título em torno do Aion 2 afirmou lançamento global em setembro e polêmica P2W «revertida». Ambas caem diante das fontes primárias verificadas em 1º de setembro: a Steam lista a saída em 05/10/2026.",
      sourceNote: "O título de 30 de agosto existe no Google News (título verificado; corpo indisponível). A contradição autorizada vem da página da Steam do Aion 2, recuperada em 1º de setembro de 2026.",
      keywords: ["Aion 2 data de lançamento verificada", "Aion 2 boato setembro", "Aion 2 polêmica P2W", "Aion 2 5 de outubro", "Aion 2 desinformação"],
      sections: [
        section("the-headline", "O título que circulou", "Em 30 de agosto, um meio indexado no Google News publicou «AION 2: polêmica P2W revertida, lançamento global em setembro». Título verificado; corpo não servido pelo domínio de origem. Duas afirmações confrontáveis com fontes primárias."),
        section("what-steam-says", "O que a página realmente diz", "A página da Steam do Aion 2 (1º de setembro de 2026) lista «Release Date: 5 Oct, 2026» e «Coming 5 Oct, 2026». Acesso antecipado: «Advance Access Starts 30 Sep». A contagem («aproximadamente 4 semanas») fecha com 5 de outubro. Nenhuma data em setembro."),
        section("the-september-confusion", "De onde vem a confusão", "30 de setembro é real e adjacente: os packs Fundador dão cinco dias a partir de 30 de setembro. O teste de carga (17–18 de setembro) soma sinais de «setembro». A NCSoft também sugeriu setembro antes das confirmações da Gamescom."),
        section("the-p2w-claim", "O trecho P2W, à parte", "A parte «polêmica P2W revertida» é difícil de provar sem o corpo. O que a página verifica: postura free-to-play cosmética com compras integradas. «Revertida» é juízo do título, não fato provado."),
        section("bottom-line", "Conclusão", "Saída: 5 de outubro de 2026 (Steam e Gamescom). Acesso antecipado: 30 de setembro. LST: 17–18 de setembro. Um «lançamento em setembro» deve ser lido como abreviação de 30 de setembro. A página da Steam é a referência."),
      ],
    }),
    ru: articleCopy(newsLabels, "ru", 5, {
      eyebrow: "ПРОВЕРКА СЛУХА",
      title: "Заголовок о «сентябрьском запуске» Aion 2 проверен: Steam говорит 5 октября",
      description: "Заголовок конца августа утверждал, что скандал P2W в Aion 2 «отменён» и мировой запуск «в сентябре». Проверяемые факты иные: страница Steam указывает выход 05.10.2026 и ранний доступ с 30 сентября.",
      intro: "30 августа заголовок вокруг Aion 2 утверждал мировой запуск в сентябре и «отмену» скандала P2W. Оба утверждения рушатся о проверенные 1 сентября первоисточники: Steam указывает 05.10.2026.",
      sourceNote: "Заголовок от 30 августа есть в Google News (заголовок проверен; тело недоступно). Авторитетное противоречие — страница Steam Aion 2, полученная 1 сентября 2026.",
      keywords: ["Aion 2 проверка даты выхода", "Aion 2 слух сентябрь", "Aion 2 скандал P2W", "Aion 2 5 октября", "Aion 2 дезинформация"],
      sections: [
        section("the-headline", "Распространившийся заголовок", "30 августа издание, индексируемое Google News, опубликовало «AION 2: скандал P2W отменён, мировой запуск в сентябре». Заголовок проверен; тело недоступно. Оба утверждения можно проверить по первоисточникам."),
        section("what-steam-says", "Что на самом деле показывает страница", "Страница Steam Aion 2 (1 сентября 2026) указывает «Release Date: 5 Oct, 2026» и «Coming 5 Oct, 2026». Ранний доступ: «Advance Access Starts 30 Sep». Отсчёт («примерно 4 недели») совпадает с 5 октября. Сентябрьской даты на странице нет."),
        section("the-september-confusion", "Откуда путаница", "30 сентября реально и смежно с запуском: паки основателя дают пять дней с 30 сентября. Стресс-тест (17–18 сентября) добавляет сентябрьских сигналов. NCsoft тоже указывала на сентябрь до подтверждений Gamescom."),
        section("the-p2w-claim", "Часть про P2W отдельно", "Часть «скандал P2W отменён» без тела доказать трудно. Что страница проверяет: косметический free-to-play с встроенными покупками. «Отменён» — суждение заголовка, а не доказанный факт."),
        section("bottom-line", "Итог", "Выход: 5 октября 2026 (Steam и Gamescom). Ранний доступ: 30 сентября. LST: 17–18 сентября. «Запуск в сентябре» — неточное сокращение для 30 сентября. Ориентир — страница Steam."),
      ],
    }),
    "zh-hant": articleCopy(newsLabels, "zh-hant", 5, {
      eyebrow: "流言核查",
      title: "Aion 2「9 月上市」標題核查：Steam 明示 10 月 5 日",
      description: "8 月底有媒體標題稱 Aion 2 的 P2W 爭議「逆轉」、全球「9 月上市」。可核實的事實不同：Steam 商店頁明示發售日 2026-10-05，搶先體驗 9 月 30 日開始。",
      intro: "8 月 30 日，一則圍繞 Aion 2 的標題聲稱全球上線將在 9 月、且一場付費變強爭議已「逆轉」。兩個說法都經不住 9 月 1 日我們核實的一手來源：Steam 明示發售日 2026-10-05。",
      sourceNote: "8 月 30 日標題存在於 Google News（已核實標題；源網域未提供正文）。權威反駁來自 Aion 2 Steam 商店頁，2026-09-01 抓取並核對。",
      keywords: ["Aion 2 發售日期核查", "Aion 2 9月上市流言", "Aion 2 P2W 爭議", "Aion 2 10月5日", "Aion 2 假標題"],
      sections: [
        section("the-headline", "流傳的標題", ["8 月 30 日，Google News 收錄的某媒體發布標題「AION 2：P2W 爭議逆轉，全球 9 月上市」。我們核實了標題存在於索引；無法核實正文。標題捆綁兩個說法：變現逆轉與 9 月上市窗口。"]),
        section("what-steam-says", "商店頁實際顯示什麼", ["Aion 2 Steam 商店頁（2026-09-01 抓取）列出「Release Date: 5 Oct, 2026」，商店面板重複「Coming 5 Oct, 2026」。搶先體驗標注「Advance Access Starts 30 Sep」。倒計時與 10 月 5 日解鎖一致。頁面上沒有任何 9 月全球發售日期。"]),
        section("the-september-confusion", "「9 月」混淆從何而來", ["9 月 30 日是真的，是臨近發售的日期：創始人包自 9 月 30 日起提供五天搶先體驗。把「9 月 30 日搶先」壓縮成「9 月上市」的標題在技術上錯誤。LST 也落在 9 月中旬，NCsoft 早年公告也曾暗示 9 月。"]),
        section("the-p2w-claim", "P2W 逆轉說法，分開看", ["「P2W 爭議逆轉」部分更難落定，因為正文不可取。商店頁可核實的是以外觀為主導的免費遊玩姿態並含內購。稱其為「逆轉」是標題的判斷，不是它證明的事實。"]),
        section("bottom-line", "結論", ["發售日：2026 年 10 月 5 日（Steam 與 Gamescom 確認一致）。搶先體驗：9 月 30 日。LST：9 月 17–18 日。看到「9 月上市」，請讀作對 9 月 30 日搶先體驗的粗糙簡寫。"]),
      ],
    }),
  },
};