import { articleCopy, localizations, guideLabels, publishedVerified, section } from "./trending-september-7-shared";
import type { ContentSource, ContentHeroImage } from "./content-registry";

/* ARTICLE 3 — Early-game free gear progression guide (western free-to-play path to fully equipped, no membership required) */

const ggSource1: ContentSource = {
  id: "guided-news-western-model-2026-09-06",
  kind: "third-party",
  publisher: "Guided News",
  label: "AION 2: NC will beim westlichen Release vieles besser machen (monetization details)",
  url: "https://guided.news/en/opinion/aion-2-nc-wants-to-do-a-lot-better-with-the-western-release/",
  publishedAt: "2026-09-06",
  retrievedAt: "2026-09-07",
  verifiedAt: "2026-09-07",
  localizations: localizations({
    "zh-hans": "AION 2：NC 要让西区发行做得更好（变现细节）",
    en: "AION 2: NC wants to do a lot better with the western release (monetization details)",
    fr: "AION 2 : NC veut faire mieux pour l'Occident (détails de monétisation)",
    de: "AION 2: NC will es im Westen besser machen (Monetarisierungsdetails)",
    es: "AION 2: NC quiere hacerlo mejor en Occidente (detalles de monetización)",
    ja: "AION 2：NCは西側でより良くしたい（課金モデル詳細）",
    "pt-br": "AION 2: a NC quer fazer melhor no Ocidente (detalhes de monetização)",
    ru: "AION 2: NC хочет сделать лучше на Западе (детали монетизации)",
    ko: "AION 2: NC, 서구에서 더 잘 하고 싶다 (과금 모델 세부)",
    "zh-hant": "AION 2：NC 要讓西區做得更好（變現細節）",
  }, "https://guided.news/en/opinion/aion-2-nc-wants-to-do-a-lot-better-with-the-western-release/"),
};

const ggSource2: ContentSource = {
  id: "aion2-official-store-2026-09-07",
  kind: "official",
  publisher: "NCSoft",
  label: "AION 2 Official Site — Founder's Pack & F2P",
  url: "https://aion2.plaync.com/en-us/",
  publishedAt: "2026-08-25",
  retrievedAt: "2026-09-07",
  verifiedAt: "2026-09-07",
  localizations: localizations({
    "zh-hans": "AION 2 官网——创始人包与免费模式",
    en: "AION 2 Official Site — Founder's Pack & F2P",
    fr: "Site officiel d'AION 2 — Founder's Pack & F2P",
    de: "AION 2 Offizielle Website — Founder's Pack & F2P",
    es: "Sitio oficial de AION 2 — Founder's Pack y F2P",
    ja: "AION 2 公式サイト——ファウンダーズパックとF2P",
    "pt-br": "Site oficial do AION 2 — Founder's Pack e F2P",
    ru: "Официальный сайт AION 2 — Founder's Pack и F2P",
    ko: "AION 2 공식 사이트 — 파운더스 팩 & F2P",
    "zh-hant": "AION 2 官網——創辦人包與免費模式",
  }, "https://aion2.plaync.com/en-us/"),
};

const ggSource3: ContentSource = {
  id: "steam-aion2-store-2026-09-07",
  kind: "platform",
  publisher: "Steam",
  label: "AION 2 on Steam (Free to Play, Oct 5 2026)",
  url: "https://store.steampowered.com/app/3393110/AION_2/",
  publishedAt: "2026-08-26",
  retrievedAt: "2026-09-07",
  verifiedAt: "2026-09-07",
  localizations: localizations({
    "zh-hans": "Steam 上的 AION 2（免费游玩，2026-10-05）",
    en: "AION 2 on Steam (Free to Play, Oct 5 2026)",
    fr: "AION 2 sur Steam (free-to-play, 5 oct. 2026)",
    de: "AION 2 auf Steam (Free to Play, 5. Okt. 2026)",
    es: "AION 2 en Steam (gratuito, 5 oct 2026)",
    ja: "SteamのAION 2（基本無料、2026-10-05）",
    "pt-br": "AION 2 na Steam (gratuito, 5 out 2026)",
    ru: "AION 2 в Steam (бесплатная, 05.10.2026)",
    ko: "Steam의 AION 2 (부분 유료, 2026-10-05)",
    "zh-hant": "Steam 上的 AION 2（免費遊玩，2026-10-05）",
  }, "https://store.steampowered.com/app/3393110/AION_2/"),
};

const ggHero: ContentHeroImage = {
  src: "https://blogfiles.ncsoft.net/news/af7330da-4ff6-4b58-aece-400e6061a3be.jpg",
  width: 1200, height: 630,
  credit: "NC Corporation",
  sourceUrl: "https://aion2.plaync.com/en-us/",
  rights: "linked-official-media",
  translations: {
    "zh-hans": { alt: "Aion 2 前期免费装备成长指南横幅", caption: "不花一分钱也能武装角色：免费玩家通过任务、单人副本、制作与掉落逐步构建装备。" },
    en: { alt: "Aion 2 early-game free gear progression guide banner", caption: "You can fully equip a character without spending: quests, solo dungeons, crafting, and drops are the free-player gear path." },
    fr: { alt: "Bannière du guide de progression d'équipement gratuit d'AION 2", caption: "Équipez votre personnage sans dépenser : quêtes, donjons solo, artisanat et butins sont la voie gratuite." },
    de: { alt: "Banner zum kostenlosen Ausrüstungs-Leitfaden für Aion 2", caption: "Ohne Geld den Charakter komplett ausrüsten: Quests, Solo-Dungeons, Crafting und Drops sind der kostenlose Weg." },
    es: { alt: "Banner de la guía de progresión de equipo gratuita de AION 2", caption: "Equipa tu personaje sin gastar: misiones, mazmorras en solitario, crafteo y botines son la vía gratuita." },
    ja: { alt: "Aion 2 序盤無料装備ガイドバナー", caption: "課金せずに装備を整える：クエスト、ソロダンジョン、クラフト、ドロップが無課金の道。" },
    "pt-br": { alt: "Banner do guia de progressão de equipamento gratuito do AION 2", caption: "Equipe seu personagem sem gastar: quests, masmorras solo, crafting e drops são o caminho gratuito." },
    ru: { alt: "Баннер гайда по бесплатной прокачке экипировки AION 2", caption: "Полностью экипируйте персонажа без трат: квесты, соло-подземелья, крафт и дроп — бесплатный путь." },
    ko: { alt: "Aion 2 초반 무료 장비 성장 가이드 배너", caption: "돈을 쓰지 않고도 장비 완성: 퀘스트, 솔로 던전, 제작, 드롭이 무과금의 길입니다." },
    "zh-hant": { alt: "Aion 2 前期免費裝備成長指南橫幅", caption: "不花一分錢也能武裝角色：免費玩家透過任務、單人副本、製作與掉落逐步構建裝備。" },
  },
};

export const trendingSeptember7Article3: ContentEntry = {
  section: "guides",
  slug: "aion-2-early-game-free-gear-progression-guide",
  schemaType: "Article",
  publishedAt: "2026-09-07",
  updatedAt: "2026-09-07",
  readingMinutes: 7,
  publication: publishedVerified,
  sources: [ggSource1, ggSource2, ggSource3],
  heroImage: ggHero,
  related: [
    { kind: "content", section: "guides", slug: "aion-2-endgame-gear-guide" },
    { kind: "content", section: "guides", slug: "aion-2-gear-enhancement-guide" },
    { kind: "content", section: "guides", slug: "aion-2-solo-leveling-guide-40-cap" },
  ],
  translations: {
    en: articleCopy(guideLabels, "en", 7, {
      eyebrow: "F2P GEAR GUIDE",
      title: "Aion 2 Early-Game Free Gear Progression: Fully Equip Your Character Without Spending",
      description: "Free-to-play gear path in Aion 2's western model: quests and solo dungeons, self-crafted equipment, drop-based upgrades, cosmetics you can earn in game — no membership required to gear up",
      intro: "Aion 2's western model promises that free players can fully outfit their characters by playing. This guide maps the early-game gear path — quest rewards, solo and 4-player dungeons, crafting, drops, and earnable cosmetics — so you can plan a zero-spend setup before the October 5 launch.",
      keywords: ["Aion 2 free gear progression", "Aion 2 gear without paying", "Aion 2 early game equipment guide", "Aion 2 free to play gear path", "Aion 2 earn gear in game"],
      sourceNote: "Based on Guided News' September 6 report of NCsoft's western monetization briefing, the official AION 2 site, and the Steam store page (all retrieved September 7, 2026). Exact drop tables and dungeon loot are subject to launch data.",
      sections: [
        section("free-first-principle", "The Free-First Principle in Aion 2's Western Model", ["Per the September 6 Gamescom report, NCsoft's western model keeps free players inside the content: you are not locked out of dungeons, raids, or PvP, and you can fully equip your character without a monthly membership.", "What membership gates is the economy — buying or trading certain items from other players on the marketplace. Gear itself is earned through gameplay, so 'free progression' means choosing the play-earned path over the marketplace path."]),
        section("quest-and-solo-sources", "Quest Rewards and Solo Content as Your First Gear", ["The early game feeds gear through quest lines and solo dungeons, where you learn boss mechanics and collect rewards for successful fights — progression that does not require a group or a purchase.", "Talking to the quest chain and clearing each zone's content before moving on gives a steady baseline set, matching the leveling route in our solo leveling guide (1-40) and the free 40-cap path."]),
        section("crafting-and-gathering", "Self-Crafted Gear: The Free-Player's Controlled Upgrade", ["Crafting and gathering let free players build their own equipment, avoiding the marketplace entirely. The western briefing lists crafting/gathering supplies in the shop, but the professions themselves are play-accessible — consistent with the six-craft/four-gather system covered in our crafting guide.", "The steady route is: gather materials while leveling, craft to fill gear gaps, and keep the leftovers as tradeable material or kinah income."]),
        section("drops-and-dungeons", "Drops, 4-Player Dungeons, and the Group Step", ["Dungeon runs — 4-player at the base tier, 8-player raids above — are the main source of upgrades beyond quest gear, and their rewards come from playing, not paying.", "If you intend to stay fully free, the efficient order is solo-dungeon training first, then 4-player dungeons, then raid content as your gear score allows; party-based drops cannot be purchased by other players unless you buy membership — so the free player's edge is simply running the content."]),
        section("launch-checklist", "Zero-Spend Launch Checklist", ["1. Try the September 17-18 Launch Scale Test to check your class and early loot feel; 2. Commit to a class whose gear you can self-craft or readily find; 3. Follow quests and zone content for your baseline set; 4. Run solo dungeons early to learn mechanics and bank starter rewards; 5. Keep kinah — you will need it for craft materials and enhancements, not marketplace purchases; 6. Treat shop cosmetics as optional: the briefing says many skins and customizations are earnable in-game, with only some exclusive to real money; 7. When your baseline is set, move to 4-player dungeons — that is where free progression accelerates."]),
      ],
    }),
    "zh-hans": articleCopy(guideLabels, "zh-hans", 7, {
      eyebrow: "免费装备攻略",
      title: "Aion 2 前期免费装备成长：不花钱也能完整武装角色",
      description: "Aion 2 西区模式的免费装备路线：任务与单人副本、自制装备、掉落升级、游戏内可得外观——不需要会员也能成型",
      intro: "Aion 2 西区模式承诺免费玩家可以仅凭游玩完整武装角色。本攻略梳理前期装备路线——任务奖励、单人/四人副本、制作、掉落与可赚取外观——让你在 10 月 5 日上线前规划好零花费方案。",
      sourceNote: "基于 Guided News 9 月 6 日对 NC 西区变现说明的报道、AION 2 官网与 Steam 商店页（均于 2026-09-07 抓取）。具体掉落表与副本战利品以上线版数据为准。",
      keywords: ["Aion 2 免费装备成长", "Aion 2 不花钱装备", "Aion 2 前期装备攻略", "Aion 2 免费玩家装备路线", "Aion 2 游戏内获得装备"],
      sections: [
        section("free-first-principle", "西区模式的「免费优先」原则", ["据 9 月 6 日 Gamescom 报道，NC 的西区模式不会把免费玩家挡在内容之外：副本、团队与 PvP 均可游玩，且无需月费会员即可完整武装角色。", "会员所限制的是经济——从其他玩家处购买/交易特定物品（交易市场）。装备本身靠游戏内容获得，因此「免费成长」= 选择游玩获取路径而非市场路径。"]),
        section("quest-and-solo-sources", "任务与单人内容：第一桶装备", ["前期通过任务线与单人副本提供装备——你在其中学习首领机制并凭成功战斗获得奖励，无需组队或付费。", "沿任务链推进、进入新区域前清完当前内容，能获得稳定基础套装，与本站单人练级指南（1-40 级）和 40 级封顶免费路径吻合。"]),
        section("crafting-and-gathering", "自制装备：免费玩家可控的升级", ["制作与采集让免费玩家自给自足，完全绕开交易市场。西区说明将制作/采集物资列为商店商品，但职业本身可玩——与本站「6 大制作+4 大采集」攻略一致。", "稳妥路线：练级时顺手采集，制作填补装备空缺，富余材料作为可交易物资或基纳收入。"]),
        section("drops-and-dungeons", "掉落、四人副本与组队阶段", ["副本（基础为四人、其上为八人团队）是任务外装备升级的主要来源，奖励来自游玩而非付费。", "若保持纯免费，高效顺序是：先单人副本练手→四人副本→装备允许后进入团队副本；未开会员时他人无法直接卖你装备，免费玩家的优势就是多刷。"]),
        section("launch-checklist", "零花费上线清单", ["1. 参加 9 月 17-18 LST，熟悉职业与早期掉落手感；2. 选择可自制或易获取装备的职业；3. 沿任务与区域内容获得基础套装；4. 早期多打单人副本学机制、攒初期奖励；5. 攒基纳——用于制作材料与强化，而非市场购买；6. 商店外观按需：官方说明多数外观可游戏内获得，仅部分真钱专属；7. 基础成型后进四人副本——免费成长从此加速。"]),
      ],
    }),
    fr: articleCopy(guideLabels, "fr", 7, {
      eyebrow: "GUIDE ÉQUIPEMENT F2P",
      title: "Progression d'équipement gratuite au début d'Aion 2 : équipez votre personnage sans dépenser",
      description: "La voie d'équipement gratuite du modèle occidental d'Aion 2 : quêtes et donjons solo, objet fabriqué, butins, cosmétiques gagnables en jeu — sans adhésion",
      intro: "Le modèle occidental d'Aion 2 promet que les joueurs gratuits peuvent équiper entièrement leur personnage en jouant. Ce guide trace la voie initiale — quêtes, donjons solo et à 4, artisanat, butins, cosmétiques gagnables.",
      sourceNote: "Basé sur le rapport de Guided News du 6 septembre, le site officiel d'AION 2 et la page Steam (récupérés le 7 septembre 2026).",
      keywords: ["Progression d'équipement gratuite Aion 2", "Aion 2 équipement sans payer", "Aion 2 guide équipement début", "Aion 2 voie F2P équipement", "Aion 2 gagner équipement en jeu"],
      sections: [
        section("free-first-principle", "Le principe « gratuit d'abord »", "Le modèle occidental garde les gratuits dans le contenu — donjons, raids, PvP accessibles, personnage équipable sans adhésion ; ce que l'adhésion ouvre, c'est l'économie (achat/échange de certains objets sur le marché)."),
        section("quest-and-solo-sources", "Quêtes et contenu solo", "Les quêtes et donjons solo fournissent l'équipement de départ et des récompenses de combat — sans groupe ni paiement ; suivre la chaîne de quêtes suffit pour une base stable."),
        section("crafting-and-gathering", "Objet fabriqué : la voie contrôlée", "Craftez et récoltez pour éviter le marché : les métiers sont accessibles en jouant ; récoltez en montant de niveau, craftez vos manques, gardez l'excédent comme revenu."),
        section("drops-and-dungeons", "Butins et donjons à 4", "Les donjons (4 joueurs de base, raids de 8 au-dessus) sont la source principale d'améliorations ; ordre efficace : solo d'abord, puis à 4, puis raids — l'avantage du gratuit est de courir le contenu."),
        section("launch-checklist", "Checklist zéro dépense", "1. Testez le LST 17-18 septembre ; 2. Choisissez une classe à équipement fabricable ; 3. Suivez les quêtes pour la base ; 4. Donjons solo pour les mécaniques ; 5. Gardez le kinah pour le craft ; 6. Cosmétiques : la plupart gagnables en jeu ; 7. Ensuite, les donjons à 4."),
      ],
    }),
    de: articleCopy(guideLabels, "de", 7, {
      eyebrow: "F2P-AUSRÜSTUNG",
      title: "Kostenlose Ausrüstungsentwicklung in Aion 2: Charakter ohne Geld vollständig ausrüsten",
      description: "Der kostenlose Ausrüstungsweg im West-Modell von Aion 2: Quests und Solo-Dungeons, selbst gefertigte Ausrüstung, Drops, erspielbare Kosmetik — ganz ohne Membership",
      intro: "Das West-Modell von Aion 2 verspricht: Free-to-Play-Spieler können ihren Charakter komplett durchs Spielen ausrüsten. Dieser Leitfaden zeigt den frühen Weg — Quests, Solo- und 4er-Dungeons, Crafting, Drops, erspielbare Kosmetik.",
      sourceNote: "Basiert auf dem Guided-News-Bericht vom 6. September, der offiziellen AION-2-Seite und dem Steam-Shop (abgerufen am 7. September 2026).",
      keywords: ["Aion 2 kostenlose Ausrüstung", "Aion 2 Ausrüstung ohne Bezahlen", "Aion 2 Ausrüstungs-Guide", "Aion 2 F2P Weg", "Aion 2 Ausrüstung erspielen"],
      sections: [
        section("free-first-principle", "Das Kostenlos-zuerst-Prinzip", "Das West-Modell lässt Free-Player im Content — Dungeons, Raids, PvP zugänglich, Charakter ohne Membership ausrüstbar; die Membership öffnet die Wirtschaft (Marktplatz-Handel), nicht die Ausrüstung."),
        section("quest-and-solo-sources", "Quests und Solo-Inhalte", "Quests und Solo-Dungeons liefern die erste Ausrüstung und Kampfbelohnungen — ohne Gruppe und ohne Kauf; die Questkette reicht für ein solides Grundset."),
        section("crafting-and-gathering", "Selbst gefertigte Ausrüstung", "Crafting und Gathering umgehen den Marktplatz: Berufe sind spielbar zugänglich; beim Leveln sammeln, Lücken craften, Reste als Kinah-Quelle."),
        section("drops-and-dungeons", "Drops und 4er-Dungeons", "Dungeons (4er Basis, 8er Raids darüber) sind die Hauptquelle für Upgrades; effiziente Reihenfolge: Solo zuerst, dann 4er, dann Raids — der Vorteil des Free-Players ist schlicht das Farmen."),
        section("launch-checklist", "Null-Euro-Checkliste", "1. LST 17.-18. September testen; 2. Klasse mit craftbarer Ausrüstung wählen; 3. Quests für das Grundset; 4. Solo-Dungeons für Mechaniken; 5. Kinah fürs Craften sparen; 6. Kosmetik: vieles erspielbar; 7. Dann 4er-Dungeons."),
      ],
    }),
    es: articleCopy(guideLabels, "es", 7, {
      eyebrow: "GUÍA EQUIPO F2P",
      title: "Progresión de equipo gratuita en Aion 2: equipa a tu personaje sin gastar",
      description: "La vía de equipo gratuita del modelo occidental de Aion 2: misiones y mazmorras en solitario, equipo crafteado, botines, cosméticos obtenibles — sin membresía",
      intro: "El modelo occidental de Aion 2 promete que los jugadores gratuitos pueden equipar totalmente a su personaje jugando. Esta guía traza la vía inicial: misiones, mazmorras solo y de 4, crafteo, botines y cosméticos obtenibles.",
      sourceNote: "Basado en el informe de Guided News del 6 de septiembre, el sitio oficial de AION 2 y la página de Steam (recuperados el 7 de septiembre de 2026).",
      keywords: ["Progresión de equipo gratuita Aion 2", "Aion 2 equipo sin pagar", "Guía equipo Aion 2 inicio", "Aion 2 ruta F2P", "Aion 2 ganar equipo en juego"],
      sections: [
        section("free-first-principle", "El principio «gratis primero»", "El modelo occidental mantiene a los gratuitos en el contenido — mazmorras, incursiones y PvP accesibles, personaje equipable sin membresía; lo que abre la membresía es la economía (comercio de ciertos objetos en el mercado)."),
        section("quest-and-solo-sources", "Misiones y contenido en solitario", "Las misiones y mazmorras en solitario dan el equipo inicial y recompensas — sin grupo ni pago; la cadena de misiones basta para una base estable."),
        section("crafting-and-gathering", "Equipo crafteado: la vía controlada", "Craftea y recolecta para evitar el mercado: los oficios son accesibles jugando; recolecta mientras subes, craftea tus carencias, guarda el sobrante como ingreso."),
        section("drops-and-dungeons", "Botines y mazmorras de 4", "Las mazmorras (4 jugadores base, incursiones de 8 encima) son la fuente principal de mejoras; orden eficiente: solo primero, luego de 4, luego incursiones — la ventaja del gratuito es correr el contenido."),
        section("launch-checklist", "Lista de verificación de gasto cero", "1. Prueba el LST 17-18 de septiembre; 2. Elige una clase con equipo crafteable; 3. Sigue las misiones para la base; 4. Mazmorras solo para mecánicas; 5. Guarda kinah para el crafteo; 6. Cosméticos: la mayoría obtenibles en juego; 7. Luego, mazmorras de 4."),
      ],
    }),
    ja: articleCopy(guideLabels, "ja", 7, {
      eyebrow: "無課金装備ガイド",
      title: "Aion 2序盤の無課金装備成長：お金をかけずにキャラを完全装備",
      description: "西側モデルの無課金装備ルート：クエストとソロダンジョン、自作装備、ドロップ、ゲーム内入手可能なコスメ——メンバーシップ不要",
      intro: "Aion 2の西側モデルは、無課金でもプレイだけでキャラを完全装備できるとしています。このガイドでは序盤の装備ルート——クエスト、ソロ/4人ダンジョン、クラフト、ドロップ、入手可能コスメを整理します。",
      sourceNote: "Guided News 9月6日付NC西側課金ブリーフィング報道、AION 2公式サイト、Steamストア（いずれも2026-09-07取得）に基づく。",
      keywords: ["Aion 2 無課金装備", "Aion 2 課金せず装備", "Aion 2 序盤装備ガイド", "Aion 2 無料プレイ装備", "Aion 2 ゲーム内装備入手"],
      sections: [
        section("free-first-principle", "西側モデルの「無料優先」原則", "西側モデルは無課金プレイヤーをコンテンツから締め出さない——ダンジョン・レイド・PvPプレイ可、メンバーシップなしで装備も完了可能。メンバーシップが開くのは経済（マーケットでの他人との取引）です。"),
        section("quest-and-solo-sources", "クエストとソロコンテンツ", "序盤はクエスト線とソロダンジョンが装備の供給源——ボス機構を学びつつ報酬を得られ、グループも課金も不要です。"),
        section("crafting-and-gathering", "自作装備：無課金の管理可能な強化", "クラフトと採取でマーケットを完全回避可能。職業はプレイで開放され、レベル上げ中に採取→空き枠をクラフト→余剰はキナ収入に。"),
        section("drops-and-dungeons", "ドロップと4人ダンジョン", "ダンジョン（基本4人、上位8人レイド）がクエスト装備の次の主な強化源。効率的な順序はソロ→4人→レイド。無課金の強みはコンテンツを回すことです。"),
        section("launch-checklist", "ゼロ課金リスト", "1. LST(9/17-18)で感触確認；2. クラフト可能な装備のクラスを選択；3. クエストで基礎装備；4. ソロダンジョンで機構習得；5. キナはクラフト用に確保；6. コスメは大半ゲーム内入手可；7. 基礎が揃ったら4人ダンジョンへ。"),
      ],
    }),
    "pt-br": articleCopy(guideLabels, "pt-br", 7, {
      eyebrow: "GUIA DE EQUIPAMENTO F2P",
      title: "Progressão de equipamento gratuita no início do Aion 2: equipe seu personagem sem gastar",
      description: "A via gratuita de equipamento do modelo ocidental do Aion 2: quests e masmorras solo, equipamento fabricado, drops, cosméticos obtíveis — sem assinatura",
      intro: "O modelo ocidental do Aion 2 promete que jogadores gratuitos podem equipar totalmente seu personagem jogando. Este guia traça a via inicial: quests, masmorras solo e de 4, crafting, drops e cosméticos obtíveis.",
      sourceNote: "Baseado no relato da Guided News de 6 de setembro, no site oficial do AION 2 e na página da Steam (acessados em 7 de setembro de 2026).",
      keywords: ["Progressão de equipamento gratuita Aion 2", "Aion 2 equipamento sem pagar", "Guia de equipamento Aion 2 início", "Aion 2 rota F2P", "Aion 2 ganhar equipamento no jogo"],
      sections: [
        section("free-first-principle", "O princípio «grátis primeiro»", "O modelo ocidental mantém gratuitos no conteúdo — masmorras, raides e PvP acessíveis, personagem equipável sem assinatura; o que a assinatura abre é a economia (troca de certos itens no mercado)."),
        section("quest-and-solo-sources", "Quests e conteúdo solo", "Quests e masmorras solo dão o equipamento inicial e recompensas de combate — sem grupo nem pagamento; a cadeia de quests basta para uma base estável."),
        section("crafting-and-gathering", "Equipamento fabricado: a via controlada", "Crafte e colete para evitar o mercado: os ofícios são acessíveis jogando; colete enquanto sobe, crafte suas lacunas, guarde o excedente como renda."),
        section("drops-and-dungeons", "Drops e masmorras de 4", "Masmorras (4 jogadores base, raides de 8 acima) são a principal fonte de melhorias; ordem eficiente: solo primeiro, depois 4, depois raides — a vantagem do gratuito é rodar o conteúdo."),
        section("launch-checklist", "Checklist de gasto zero", "1. Teste o LST 17-18 de setembro; 2. Escolha uma classe com equipamento fabricável; 3. Siga as quests para a base; 4. Masmorras solo para mecânicas; 5. Guarde kinah para o craft; 6. Cosméticos: a maioria obtível no jogo; 7. Depois, masmorras de 4."),
      ],
    }),
    ru: articleCopy(guideLabels, "ru", 7, {
      eyebrow: "ГАЙД ПО ЭКИПИРОВКЕ",
      title: "Бесплатная прокачка экипировки в начале Aion 2: полностью оденьте персонажа без трат",
      description: "Бесплатный путь экипировки в западной модели Aion 2: квесты и соло-подземелья, собственный крафт, дроп, косметика за игру — без подписки",
      intro: "Западная модель Aion 2 обещает: бесплатные игроки могут полностью экипировать персонажа самой игрой. Этот гайд описывает ранний путь — квесты, соло- и 4-местные подземелья, крафт, дроп, косметику за игру.",
      sourceNote: "На основе отчёта Guided News от 6 сентября, официального сайта AION 2 и страницы Steam (получены 7 сентября 2026 г.).",
      keywords: ["Aion 2 бесплатная экипировка", "Aion 2 экипировка без оплаты", "Гайд экипировка Aion 2", "Aion 2 путь F2P", "Aion 2 получить экипировку в игре"],
      sections: [
        section("free-first-principle", "Принцип «сначала бесплатно»", "Западная модель оставляет бесплатных в контенте — подземелья, рейды и PvP доступны, персонаж экипируется без подписки; подписка открывает экономику (покупку/обмен некоторых предметов на аукционе)."),
        section("quest-and-solo-sources", "Квесты и соло-контент", "Квесты и соло-подземелья дают стартовую экипировку и награды за бой — без группы и оплаты; цепочки квестов хватает на стабильную базу."),
        section("crafting-and-gathering", "Собственный крафт", "Крафт и сбор обходят аукцион: профессии доступны в игре; собирайте на прокачке, крафтите пробелы, остаток — в доход."),
        section("drops-and-dungeons", "Дроп и подземелья на 4", "Подземелья (база на 4, рейды на 8 выше) — главный источник апгрейдов; эффективный порядок: соло → четвёрка → рейд; преимущество бесплатного — просто фармить контент."),
        section("launch-checklist", "Чеклист без трат", "1. Попробуйте LST 17–18 сентября; 2. Класс с крафтовой экипировкой; 3. Квесты для базы; 4. Соло-подземелья для механик; 5. Копите кина для крафта; 6. Косметика — многое за игру; 7. Затем подземелья на 4."),
      ],
    }),
    ko: articleCopy(guideLabels, "ko", 7, {
      eyebrow: "무과금 장비 가이드",
      title: "아이온2 초반 무과금 장비 성장: 돈을 쓰지 않고도 캐릭터 완전 장비",
      description: "서구 모델의 무과금 장비 루트: 퀘스트와 솔로 던전, 직접 제작, 드롭, 게임 내 획득 가능 코스메틱——멤버십 불필요",
      intro: "아이온2 서구 모델은 무과금 유저도 플레이만으로 캐릭터를 완전히 장비할 수 있다고 합니다. 이 가이드는 초반 장비 루트——퀘스트, 솔로/4인 던전, 제작, 드롭, 획득 가능 코스메틱을 정리합니다.",
      sourceNote: "Guided News 9월 6일자 NC 서구 과금 브리핑 보도, AION 2 공식 사이트, Steam 상점(모두 2026-09-07 확인) 기반.",
      keywords: ["아이온2 무과금 장비", "아이온2 돈 없이 장비", "아이온2 초반 장비 가이드", "아이온2 F2P 장비 루트", "아이온2 게임 내 장비 획득"],
      sections: [
        section("free-first-principle", "서구 모델의 '무료 우선' 원칙", "서구 모델은 무과금 유저를 콘텐츠에서 막지 않습니다——던전·레이드·PvP 가능, 멤버십 없이도 장비 완성 가능. 멤버십이 여는 것은 경제(마켓플레이스에서 타인과의 거래)입니다."),
        section("quest-and-solo-sources", "퀘스트와 솔로 콘텐츠", "초반 장비는 퀘스트 라인과 솔로 던전이 공급합니다——보스 메커니즘을 배우며 보상을 얻고, 그룹도 결제도 필요 없습니다."),
        section("crafting-and-gathering", "자체 제작: 무과금의 통제 가능한 강화", "제작과 채집으로 마켓플레이스를 완전히 우회할 수 있습니다. 직업은 플레이로 열리고, 레벨 업 중 채집→빈자리 제작→여분은 키나 수입으로."),
        section("drops-and-dungeons", "드롭과 4인 던전", "던전(기본 4인, 상위 8인 레이드)이 퀘스트 장비 다음의 주요 강화 원천. 효율 순서는 솔로→4인→레이드. 무과금의 강점은 콘텐츠를 돌리는 것입니다."),
        section("launch-checklist", "무과금 출시 체크리스트", "1. LST(9/17-18)에서 감각 확인; 2. 제작 가능 장비의 클래스 선택; 3. 퀘스트로 기반 장비; 4. 솔로 던전으로 메커니즘 학습; 5. 키나는 크래프트용으로 절약; 6. 코스메틱은 대부분 게임 내 획득; 7. 기반이 갖춰지면 4인 던전으로."),
      ],
    }),
    "zh-hant": articleCopy(guideLabels, "zh-hant", 7, {
      eyebrow: "免費裝備攻略",
      title: "Aion 2 前期免費裝備成長：不花錢也能完整武裝角色",
      description: "Aion 2 西區模式的免費裝備路線：任務與單人副本、自製裝備、掉落升級、遊戲內可得外觀——不需要會員也能成型",
      intro: "Aion 2 西區模式承諾免費玩家可以僅憑遊玩完整武裝角色。本攻略梳理前期裝備路線——任務獎勵、單人/四人副本、製作、掉落與可賺取外觀——讓你在 10 月 5 日上線前規劃好零花費方案。",
      sourceNote: "基於 Guided News 9 月 6 日對 NC 西區變現說明的報導、AION 2 官網與 Steam 商店頁（均於 2026-09-07 抓取）。具體掉落表與副本戰利品以上線版數據為準。",
      keywords: ["Aion 2 免費裝備成長", "Aion 2 不花錢裝備", "Aion 2 前期裝備攻略", "Aion 2 免費玩家裝備路線", "Aion 2 遊戲內獲得裝備"],
      sections: [
        section("free-first-principle", "西區模式的「免費優先」原則", ["據 9 月 6 日 Gamescom 報導，NC 的西區模式不會把免費玩家擋在內容之外：副本、團隊與 PvP 均可遊玩，且無需月費會員即可完整武裝角色。", "會員所限制的是經濟——從其他玩家處購買/交易特定物品（交易市場）。裝備本身靠遊戲內容獲得，因此「免費成長」= 選擇遊玩獲取路徑而非市場路徑。"]),
        section("quest-and-solo-sources", "任務與單人內容：第一桶裝備", ["前期透過任務線與單人副本提供裝備——你在其中學習首領機制並憑成功戰鬥獲得獎勵，無需組隊或付費。", "沿任務鏈推進、進入新區域前清完當前內容，能獲得穩定基礎套裝，與本站單人練級指南（1-40 級）和 40 級封頂免費路徑吻合。"]),
        section("crafting-and-gathering", "自製裝備：免費玩家可控的升級", ["製作與採集讓免費玩家自給自足，完全繞開交易市場。西區說明將製作/採集物資列為商店商品，但職業本身可玩——與本站「6 大製作+4 大採集」攻略一致。", "穩妥路線：練級時順手採集，製作填補裝備空缺，富餘材料作為可交易物資或基納收入。"]),
        section("drops-and-dungeons", "掉落、四人副本與組隊階段", ["副本（基礎為四人、其上為八人團隊）是任務外裝備升級的主要來源，獎勵來自遊玩而非付費。", "若保持純免費，高效順序是：先單人副本練手→四人副本→裝備允許後進入團隊副本；未開會員時他人無法直接賣你裝備，免費玩家的優勢就是多刷。"]),
        section("launch-checklist", "零花費上線清單", ["1. 參加 9 月 17-18 LST，熟悉職業與早期掉落手感；2. 選擇可自製或易取得裝備的職業；3. 沿任務與區域內容獲得基礎套裝；4. 早期多打單人副本學機制、攢初期獎勵；5. 攢基納——用於製作材料與強化，而非市場購買；6. 商店外觀按需：官方說明多數外觀可遊戲內獲得，僅部分真錢專屬；7. 基礎成型後進四人副本——免費成長從此加速。"]),
      ],
    }),
  },
};