import { articleCopy, guideLabels, localizations, publishedVerified, section } from "./trending-august-18-shared";
import type { ContentEntry, ContentHeroImage, ContentSource } from "./content-registry";

/* ARTICLE 4 — Built-in DPS meter vs community tools */

const meterSource1: ContentSource = {
  id: "aion2hub-meter-0401-2026-08-18",
  kind: "third-party", publisher: "AION2Hub",
  label: "AION 2 Update — April 1, 2026: Built-In DPS Meter",
  url: "https://aion2hub.com/updates",
  publishedAt: "2026-04-01",
  retrievedAt: "2026-08-18",
  verifiedAt: "2026-08-18",
  localizations: localizations({
    "zh-hans": "AION 2 更新 — 2026年4月1日：内置 DPS 计量表",
    en: "AION 2 Update — April 1, 2026: Built-In DPS Meter",
    fr: "AION 2 Mise à jour — 1er avril 2026 : DPS Meter intégré",
    de: "AION 2 Update — 1. April 2026: Integriertes DPS-Meter",
    es: "AION 2 Actualización — 1 de abril de 2026: medidor de DPS integrado",
    ja: "AION 2 アップデート — 2026年4月1日：内蔵DPSメーター",
    "pt-br": "AION 2 Atualização — 1º de abril de 2026: medidor de DPS integrado",
    ru: "AION 2 Обновление — 1 апреля 2026: встроенный DPS-метр",
    ko: "AION 2 업데이트 — 2026년 4월 1일: 내장 DPS 미터",
    "zh-hant": "AION 2 更新 — 2026年4月1日：內建 DPS 計量表",
  }, "https://aion2hub.com/updates"),
};

const meterSource2: ContentSource = {
  id: "aion2hub-aionflex-2026-08-18",
  kind: "third-party", publisher: "AION2Hub",
  label: "AION 2 DPS Meter is live — parse every fight & climb the ranks on AionFlex",
  url: "https://aion2hub.com/",
  publishedAt: "2026-08-10",
  retrievedAt: "2026-08-18",
  verifiedAt: "2026-08-18",
  localizations: localizations({
    "zh-hans": "AION 2 DPS 计量表已上线——在 AionFlex 上分析每场战斗并冲击排行榜",
    en: "AION 2 DPS Meter is live — parse every fight & climb the ranks on AionFlex",
    fr: "Le DPS Meter AION 2 est en ligne — analysez chaque combat et grimpez les classements sur AionFlex",
    de: "AION 2 DPS-Meter ist live — analysiere jeden Kampf und klettere die Ränge auf AionFlex",
    es: "El medidor de DPS de AION 2 está activo — analiza cada combate y sube en los rankings en AionFlex",
    ja: "AION 2 DPSメーターが稼働 — AionFlex で全戦闘を解析しランクを駆け上がれ",
    "pt-br": "O medidor de DPS do AION 2 está no ar — analise cada luta e suba nos rankings no AionFlex",
    ru: "DPS-метр AION 2 запущен — анализируйте каждый бой и поднимайтесь в рейтингах на AionFlex",
    ko: "AION 2 DPS 미터 출시 — AionFlex에서 모든 전투를 분석하고 랭킹에 오르세요",
    "zh-hant": "AION 2 DPS 計量表已上線——在 AionFlex 上分析每場戰鬥並衝擊排行榜",
  }, "https://aion2hub.com/"),
};

const meterSource3: ContentSource = {
  id: "aionflex-home-2026-08-18",
  kind: "third-party", publisher: "AionFlex",
  label: "AionFlex — AION 2 DPS Meter & Combat Parsing",
  url: "https://aionflex.com/",
  publishedAt: "2026-08-10",
  retrievedAt: "2026-08-18",
  verifiedAt: "2026-08-18",
  localizations: localizations({
    "zh-hans": "AionFlex —— AION 2 DPS 计量表与战斗分析",
    en: "AionFlex — AION 2 DPS Meter & Combat Parsing",
    fr: "AionFlex — DPS Meter AION 2 et analyse de combat",
    de: "AionFlex — AION 2 DPS-Meter & Kampfanalyse",
    es: "AionFlex — medidor de DPS de AION 2 y análisis de combate",
    ja: "AionFlex — AION 2 DPSメーター＆戦闘解析",
    "pt-br": "AionFlex — medidor de DPS do AION 2 e análise de combate",
    ru: "AionFlex — DPS-метр AION 2 и анализ боя",
    ko: "AionFlex — AION 2 DPS 미터 및 전투 분석",
    "zh-hant": "AionFlex —— AION 2 DPS 計量表與戰鬥分析",
  }, "https://aionflex.com/"),
};

const meterHero: ContentHeroImage = {
  src: "https://blogfiles.ncsoft.net/news/af7330da-4ff6-4b58-aece-400e6061a3be.jpg",
  width: 1100, height: 605,
  credit: "NC Corporation",
  sourceUrl: "https://aion2.plaync.com/ko-kr/board/notice",
  rights: "linked-official-media",
  translations: {
    "zh-hans": { alt: "DPS 计量表对比指南配图", caption: "NC 官方配图；韩服 4 月 1 日起内置 DPS 计量表，社区工具 AionFlex 于 8 月上线排行功能。" },
    en: { alt: "DPS meter comparison guide image", caption: "Official NC artwork; the KR service added a built-in DPS meter on April 1, and the community tool AionFlex launched with rankings in August." },
    fr: { alt: "Image du guide de comparaison des DPS Meters", caption: "Visuel officiel NC ; le service KR a ajouté un DPS Meter intégré le 1er avril, et AionFlex a lancé des classements en août." },
    de: { alt: "DPS-Meter-Vergleichs-Guide-Bild", caption: "Offizielles NC-Artwork; der KR-Dienst erhielt am 1. April ein integriertes DPS-Meter, AionFlex startete im August mit Ranglisten." },
    es: { alt: "Imagen de la guía de comparación de medidores de DPS", caption: "Arte oficial de NC; el servicio KR añadió un medidor de DPS integrado el 1 de abril y AionFlex lanzó clasificaciones en agosto." },
    ja: { alt: "DPSメーター比較ガイド画像", caption: "NC公式アートワーク；KRサービスは4月1日に内蔵DPSメーターを追加し、AionFlex は8月にランキングを開始しました。" },
    "pt-br": { alt: "Imagem do guia de comparação de medidores de DPS", caption: "Arte oficial da NC; o serviço KR adicionou um medidor de DPS integrado em 1º de abril e a AionFlex lançou rankings em agosto." },
    ru: { alt: "Изображение гайда по сравнению DPS-метров", caption: "Официальный арт NC; на KR добавлен встроенный DPS-метр 1 апреля, AionFlex запустил рейтинги в августе." },
    ko: { alt: "DPS 미터 비교 가이드 이미지", caption: "NC 공식 이미지입니다. KR 서비스는 4월 1일에 내장 DPS 미터를 추가했고, AionFlex는 8월에 랭킹을 출시했습니다." },
    "zh-hant": { alt: "DPS 計量表對比指南配圖", caption: "NC 官方配圖；韓服 4 月 1 日起內建 DPS 計量表，社群工具 AionFlex 於 8 月上線排行功能。" },
  },
};

export const trendingAugust18Article4: ContentEntry = {
  section: "guides",
  slug: "aion-2-dps-meter-built-in-vs-aionflex",
  schemaType: "Article",
  publishedAt: "2026-08-18",
  updatedAt: "2026-08-18",
  readingMinutes: 5,
  publication: publishedVerified,
  sources: [meterSource1, meterSource2, meterSource3],
  heroImage: meterHero,
  related: [
    { kind: "content", section: "guides", slug: "aion-2-dps-meter-guide" },
    { kind: "content", section: "guides", slug: "aion-2-launch-classes-guide" },
    { kind: "content", section: "guides", slug: "post-patch-class-tier-list-august-2026" },
  ],
  translations: {
    en: articleCopy(guideLabels, "en", 5, {
      eyebrow: "TOOLS GUIDE",
      title: "Aion 2 DPS Meter: Built-In vs AionFlex — Which Should You Use?",
      description: "Aion 2 has both a built-in DPS meter (added to the KR service in April) and the new community tool AionFlex. Compare what each offers and when to use which.",
      intro: "Good news for anyone who wants to parse damage in Aion 2: you do not need to choose between official and community — both exist. The KR service has shipped a built-in DPS meter since the April 1 update, and the community tool AionFlex added a ranked parsing layer this August. This guide compares the two and explains when each makes sense.",
      sourceNote: "Based on AION2Hub's April 1 built-in meter note, the AionFlex launch announcement on Aion2Hub, and the AionFlex tool listing.",
      keywords: ["Aion 2 DPS meter built-in", "Aion 2 AionFlex", "Aion 2 damage parser", "Aion 2 parse damage", "Aion 2 combat log"],
      sections: [
        section("builtin", "The Built-In DPS Meter", ["The Korean service added a DPS meter as part of the April 1, 2026 update. As a first-party feature it ships inside the client — no external tools, no upload flow, no ToS questions.", "The built-in meter is the safe default: it tracks your own and your group's damage during fights with official data. If you only want to confirm 'am I playing my rotation well,' this is all you need."]),
        section("aionflex", "AionFlex — the Community Layer", ["AionFlex's AION 2 DPS Meter launched in August 2026, promoted through Aion2Hub: 'parse every fight & climb the ranks.' Where it differs is the ranked layer — community standings, per-fight breakdowns, and cross-group comparisons.", "Because it is a third-party tool, exact workflows (log capture, upload, platform support) depend on the tool's current documentation. Community tools are convenient for progression raiders who want public benchmarks."]),
        section("choose", "Which Should You Use?", ["Use the built-in meter for daily play: rotation checks, raid screenshots, and quick confirmation after a build change — zero setup and always up to date with the game.", "Pair it with AionFlex (or similar community parsers) when you want public rankings, deeper per-fight analysis, or comparisons between builds over time. There is no conflict: built-in for in-game verification, community tools for the external record."]),
        section("global", "What Global Players Should Know", ["NCSoft has not yet confirmed whether the built-in meter ships with the September 30 global launch — KR features have historically arrived on the global build gradually. Community meters for the global launch are not confirmed either.", "Practical advice: whichever meters the global service ships with at launch, the skill of using parses to improve your rotation transfers directly. Focus on mastering rotations now so you can read your numbers well on day one."]),
      ],
    }),
    "zh-hans": articleCopy(guideLabels, "zh-hans", 5, {
      eyebrow: "工具指南",
      title: "Aion 2 DPS 计量表：内置版 vs AionFlex——该用哪个？",
      description: "Aion 2 既有内置 DPS 计量表（4 月加入韩服），也有新的社区工具 AionFlex。比较两者各自的功能与适用场景。",
      intro: "想在 Aion 2 中分析伤害的玩家有好消息：你无需在官方与社区之间二选一——两者并存。韩服自 4 月 1 日更新起已内置 DPS 计量表，社区工具 AionFlex 在今年 8 月加入了排行分析层。本指南对比两者并说明何时各取所需。",
      sourceNote: "基于 AION2Hub 4 月 1 日内置计量表说明、Aion2Hub 上的 AionFlex 上线公告及 AionFlex 工具列表。",
      keywords: ["Aion 2 内置 DPS 计量表", "Aion 2 AionFlex", "Aion 2 伤害解析器", "Aion 2 解析伤害", "Aion 2 战斗日志"],
      sections: [
        section("builtin", "内置 DPS 计量表", ["韩服在 2026 年 4 月 1 日更新中加入 DPS 计量表。作为第一方功能，它内置于客户端——无需外部工具、无需上传流程、无使用条款问题。", "内置计量表是安全的默认选择：它用官方数据追踪你与队伍在战斗中的伤害。如果你只想确认「我的循环打得好吗」，这已足够。"]),
        section("aionflex", "AionFlex——社区层", ["AionFlex 的 AION 2 DPS 计量表于 2026 年 8 月上线，通过 Aion2Hub 推广：「分析每场战斗并冲击排行榜」。其差异在于排行层——社区排名、逐场战斗分解与跨队伍比较。", "作为第三方工具，具体工作流（日志捕获、上传、平台支持）取决于工具当前文档。社区工具适合想要公开基准的进度型开荒玩家。"]),
        section("choose", "该用哪个？", ["日常游玩使用内置计量表：循环检查、团本截图、构筑改动后的快速确认——零配置且始终与游戏同步。", "当你想要公开排行、更深入的逐场分析或跨时间构筑比较时，搭配 AionFlex（或类似社区解析器）。两者并不冲突：内置版用于游戏内验证，社区工具用于外部记录。"]),
        section("global", "全球玩家须知", ["NCSoft 尚未确认内置计量表是否随 9 月 30 日全球上线提供——韩服功能历史上逐步抵达全球版本。全球上线的社区计量表同样未确认。", "实用建议：无论全球服务上线时提供何种计量表，用解析改进循环的技能可直接迁移。现在专注于掌握循环，以便第一天就能读懂你的数字。"]),
      ],
    }),
    ko: articleCopy(guideLabels, "ko", 5, {
      eyebrow: "도구 가이드",
      title: "Aion 2 DPS 미터: 내장 vs AionFlex — 무엇을 써야 할까?",
      description: "Aion 2에는 내장 DPS 미터(4월부터 KR 서비스 제공)와 새로운 커뮤니티 도구 AionFlex가 모두 있습니다. 각각의 기능과 사용 시점을 비교합니다.",
      intro: "Aion 2에서 데미지를 파싱하고 싶은 플레이어에게 좋은 소식: 공식과 커뮤니티 사이에서 선택할 필요가 없습니다 — 둘 다 존재합니다. KR 서비스는 4월 1일 업데이트부터 내장 DPS 미터를 제공했으며, 커뮤니티 도구 AionFlex는 올해 8월 랭킹 파싱 레이어를 추가했습니다. 이 가이드는 둘을 비교하고 언제 어떤 것이 맞는지 설명합니다.",
      sourceNote: "AION2Hub의 4월 1일 내장 미터 노트, Aion2Hub의 AionFlex 출시 발표, AionFlex 도구 목록에 기반합니다.",
      keywords: ["Aion 2 내장 DPS 미터", "Aion 2 AionFlex", "Aion 2 데미지 파서", "Aion 2 데미지 파싱", "Aion 2 전투 로그"],
      sections: [
        section("builtin", "내장 DPS 미터", ["한국 서비스는 2026년 4월 1일 업데이트의 일부로 DPS 미터를 추가했습니다. 퍼스트파티 기능으로 클라이언트 안에 내장되어 있습니다 — 외부 도구, 업로드 절차, 이용약관 문제가 없습니다.", "내장 미터는 안전한 기본값입니다: 전투 중 자신과 파티의 피해를 공식 데이터로 추적합니다. '내 로테이션을 잘 돌리고 있나'만 확인하려면 이것으로 충분합니다."]),
        section("aionflex", "AionFlex — 커뮤니티 레이어", ["AionFlex의 AION 2 DPS 미터는 2026년 8월에 출시되어 Aion2Hub를 통해 홍보되었습니다: '모든 전투를 분석하고 랭킹에 오르세요.' 차이는 랭킹 레이어입니다 — 커뮤니티 순위, 전투별 분석, 파티 간 비교.", "서드파티 도구이므로 정확한 워크플로(로그 캡처, 업로드, 플랫폼 지원)는 도구의 현재 문서에 달려 있습니다. 커뮤니티 도구는 공개 벤치마크를 원하는 레이드 플레이어에게 편리합니다."]),
        section("choose", "무엇을 써야 할까?", ["일상 플레이에는 내장 미터를 사용하세요: 로테이션 확인, 레이드 스크린샷, 빌드 변경 후 빠른 확인 — 설정 없이 항상 최신입니다.", "공개 랭킹, 더 깊은 전투별 분석, 시간 경과에 따른 빌드 비교를 원한다면 AionFlex(또는 유사 커뮤니티 파서)와 함께 사용하세요. 충돌하지 않습니다: 게임 내 검증은 내장, 외부 기록은 커뮤니티 도구입니다."]),
        section("global", "글로벌 플레이어가 알아야 할 것", ["NCSoft는 내장 미터가 9월 30일 글로벌 출시에 포함될지 아직 확인하지 않았습니다 — KR 기능은 역사적으로 글로벌 빌드에 점진적으로 도착했습니다. 글로벌 출시용 커뮤니티 미터도 확인되지 않았습니다.", "실용적 조언: 글로벌 서비스가 출시 시 어떤 미터를 제공하든, 파스를 이용한 로테이션 개선 기술은 그대로 이전됩니다. 지금 로테이션을 마스터해 첫날부터 숫자를 잘 읽으세요."]),
      ],
    }),
    ja: articleCopy(guideLabels, "ja", 5, {
      eyebrow: "ツールガイド",
      title: "Aion 2 DPSメーター：内蔵 vs AionFlex — どちらを使うべきか",
      description: "Aion 2 には内蔵DPSメーター（4月からKRサービス提供）と新しいコミュニティツール AionFlex の両方があります。それぞれの機能と使い分けを比較します。",
      intro: "Aion 2 でダメージをパースしたいプレイヤーに朗報です：公式とコミュニティのどちらかを選ぶ必要はありません — 両方存在します。KR サービスは4月1日アップデート以降、内蔵DPSメーターを提供し、コミュニティツール AionFlex は今年8月にランキングパース層を追加しました。このガイドは両者を比較し、いつどちらが適しているかを説明します。",
      sourceNote: "AION2Hub の4月1日内蔵メーターノート、Aion2Hub の AionFlex ローンチ発表、AionFlex ツールリストに基づきます。",
      keywords: ["Aion 2 内蔵DPSメーター", "Aion 2 AionFlex", "Aion 2 ダメージパーサー", "Aion 2 ダメージパース", "Aion 2 戦闘ログ"],
      sections: [
        section("builtin", "内蔵DPSメーター", ["韓国サービスは2026年4月1日アップデートの一部としてDPSメーターを追加しました。ファーストパーティ機能としてクライアント内に内蔵されています — 外部ツール、アップロード手順、利用規約の問題がありません。", "内蔵メーターは安全なデフォルトです：戦闘中の自分とパーティのダメージを公式データで追跡します。「自分のローテーションをうまく回せているか」だけ確認したいならこれで十分です。"]),
        section("aionflex", "AionFlex — コミュニティレイヤー", ["AionFlex の AION 2 DPSメーターは2026年8月にローンチし、Aion2Hub を通じて宣伝されました：『すべての戦闘を解析しランクを駆け上がれ』。違いはランキングレイヤーです — コミュニティ順位、戦闘別分析、パーティ間比較。", "サードパーティツールであるため、正確なワークフロー（ログキャプチャ、アップロード、プラットフォーム対応）はツールの現在のドキュメントによります。公開ベンチマークを求めるレイドプレイヤーに便利です。"]),
        section("choose", "どちらを使うべきか", ["日常プレイには内蔵メーターを使いましょう：ローテーション確認、レイドスクリーンショット、ビルド変更後のクイック確認 — セットアップ不要で常に最新です。", "公開ランキング、より深い戦闘別分析、時間経過でのビルド比較が必要なら AionFlex（または同様のコミュニティパーサー）と組み合わせてください。競合しません：ゲーム内検証は内蔵、外部記録はコミュニティツールです。"]),
        section("global", "グローバルプレイヤーが知るべきこと", ["NCSoft は内蔵メーターが9月30日のグローバルローンチに含まれるかまだ確認していません — KR 機能は歴史的にグローバルビルドへ段階的に到着します。グローバルローンチ向けのコミュニティメーターも未確認です。", "実用的な助言：グローバルサービスがどのメーターを提供しても、パースでローテーションを改善するスキルはそのまま移転します。今ローテーションを習得して、初日から数字を正しく読みましょう。"]),
      ],
    }),
    fr: articleCopy(guideLabels, "fr", 5, {
      eyebrow: "GUIDE D'OUTILS",
      title: "DPS Meter d'Aion 2 : intégré vs AionFlex — lequel utiliser ?",
      description: "Aion 2 a à la fois un DPS Meter intégré (KR depuis avril) et AionFlex. Comparez les deux et sachez quand utiliser chacun.",
      intro: "Pas besoin de choisir : le service KR dispose d'un DPS Meter intégré depuis le 1er avril et AionFlex a ajouté un classement en août.",
      sourceNote: "Basé sur la note d'AION2Hub du 1er avril, l'annonce AionFlex et la liste d'outils.",
      keywords: ["Aion 2 DPS meter intégré", "Aion 2 AionFlex", "Aion 2 parseur de dégâts"],
      sections: [
        section("builtin", "Le DPS Meter intégré", ["Ajouté le 1er avril sur KR : intégré au client, données officielles, aucune question de ToS. Suffisant pour vérifier sa rotation."]),
        section("aionflex", "AionFlex", ["Lancé en août : classements communautaires et analyses par combat. Outil tiers, workflows dépendants de la documentation."]),
        section("choose", "Lequel choisir ?", ["Intégré pour le quotidien, AionFlex pour les classements publics et les comparaisons à long terme."]),
        section("global", "Pour les joueurs globaux", ["Non confirmé pour le 30 septembre. La compétence de lecture de parses se transfère quel que soit l'outil."]),
      ],
    }),
    de: articleCopy(guideLabels, "de", 5, {
      eyebrow: "TOOLS-GUIDE",
      title: "Aion 2 DPS-Meter: Integriert vs AionFlex — was nutzen?",
      description: "Aion 2 hat sowohl ein integriertes DPS-Meter (KR seit April) als auch das neue Tool AionFlex. Vergleichen Sie beide und wissen Sie, wann was sinnvoll ist.",
      intro: "Kein Entweder-oder: Der KR-Dienst hat seit dem 1. April ein integriertes DPS-Meter, und AionFlex hat im August eine Ranking-Schicht hinzugefügt.",
      sourceNote: "Basierend auf der AION2Hub-Notiz vom 1. April, der AionFlex-Ankündigung und der Tool-Liste.",
      keywords: ["Aion 2 integriertes DPS-Meter", "Aion 2 AionFlex", "Aion 2 Schadensparser"],
      sections: [
        section("builtin", "Das integrierte DPS-Meter", ["Seit 1. April auf KR: im Client integriert, offizielle Daten, keine ToS-Fragen. Für Rotations-Checks völlig ausreichend."]),
        section("aionflex", "AionFlex", ["Seit August: Community-Rankings und Kampf-für-Kampf-Analysen. Drittanbieter, Workflows lautaktueller Doku."]),
        section("choose", "Was nutzen?", ["Integriert für den Alltag, AionFlex für öffentliche Rankings und Langzeitvergleiche."]),
        section("global", "Für Global-Spieler", ["Für den 30. September nicht bestätigt. Die Parse-Lesekompetenz überträgt sich unabhängig vom Tool."]),
      ],
    }),
    es: articleCopy(guideLabels, "es", 5, {
      eyebrow: "GUÍA DE HERRAMIENTAS",
      title: "Medidor de DPS de Aion 2: integrado vs AionFlex — ¿cuál usar?",
      description: "Aion 2 tiene tanto un medidor de DPS integrado (KR desde abril) como la nueva herramienta AionFlex. Compara ambos y cuándo usar cada uno.",
      intro: "No hace falta elegir: el servicio KR tiene un medidor integrado desde el 1 de abril y AionFlex añadió un ranking en agosto.",
      sourceNote: "Basado en la nota de AION2Hub del 1 de abril, el anuncio de AionFlex y la lista de herramientas.",
      keywords: ["Aion 2 medidor de DPS integrado", "Aion 2 AionFlex", "Aion 2 parser de daño"],
      sections: [
        section("builtin", "El medidor integrado", ["Añadido el 1 de abril en KR: integrado en el cliente, datos oficiales, sin problemas de ToS. Suficiente para comprobar la rotación."]),
        section("aionflex", "AionFlex", ["Lanzado en agosto: rankings comunitarios y análisis por combate. Herramienta de terceros, flujos según documentación."]),
        section("choose", "Cuál usar", ["Integrado para el día a día, AionFlex para rankings públicos y comparaciones a largo plazo."]),
        section("global", "Para jugadores globales", ["No confirmado para el 30 de septiembre. La habilidad de leer parses se transfiere con cualquier herramienta."]),
      ],
    }),
    "pt-br": articleCopy(guideLabels, "pt-br", 5, {
      eyebrow: "GUIA DE FERRAMENTAS",
      title: "Medidor de DPS de Aion 2: integrado vs AionFlex — qual usar?",
      description: "Aion 2 tem tanto um medidor de DPS integrado (KR desde abril) quanto a nova ferramenta AionFlex. Compare os dois e saiba quando usar cada um.",
      intro: "Sem necessidade de escolher: o serviço KR tem um medidor integrado desde 1º de abril e a AionFlex adicionou rankings em agosto.",
      sourceNote: "Baseado na nota da AION2Hub de 1º de abril, no anúncio da AionFlex e na lista de ferramentas.",
      keywords: ["Aion 2 medidor de DPS integrado", "Aion 2 AionFlex", "Aion 2 parser de dano"],
      sections: [
        section("builtin", "O medidor integrado", ["Adicionado em 1º de abril na KR: integrado ao cliente, dados oficiais, sem problemas de ToS. Suficiente para verificar a rotação."]),
        section("aionflex", "AionFlex", ["Lançado em agosto: rankings da comunidade e análises por luta. Ferramenta de terceiros, fluxos conforme documentação."]),
        section("choose", "Qual usar", ["Integrado para o dia a dia, AionFlex para rankings públicos e comparações de longo prazo."]),
        section("global", "Para jogadores globais", ["Não confirmado para 30 de setembro. A habilidade de ler parses se transfere com qualquer ferramenta."]),
      ],
    }),
    ru: articleCopy(guideLabels, "ru", 5, {
      eyebrow: "ГАЙД ПО ИНСТРУМЕНТАМ",
      title: "DPS-метр Aion 2: встроенный vs AionFlex — что использовать?",
      description: "У Aion 2 есть и встроенный DPS-метр (в KR с апреля), и новый инструмент AionFlex. Сравните их и узнайте, когда что использовать.",
      intro: "Выбирать не нужно: в KR встроенный DPS-метр появился 1 апреля, а AionFlex добавил рейтинги в августе.",
      sourceNote: "На основе записи AION2Hub от 1 апреля, анонса AionFlex и списка инструментов.",
      keywords: ["Aion 2 встроенный DPS-метр", "Aion 2 AionFlex", "Aion 2 парсер урона"],
      sections: [
        section("builtin", "Встроенный метр", ["Добавлен 1 апреля в KR: встроен в клиент, официальные данные, без вопросов к ToS. Достаточно для проверки ротации."]),
        section("aionflex", "AionFlex", ["Запущен в августе: комьюнити-рейтинги и разбор по боям. Сторонний инструмент, сценарии по документации."]),
        section("choose", "Что использовать", ["Встроенный — для повседневной игры, AionFlex — для публичных рейтингов и долгосрочных сравнений."]),
        section("global", "Глобальным игрокам", ["Не подтверждено к 30 сентября. Навык чтения парсеров переносится независимо от инструмента."]),
      ],
    }),
    "zh-hant": articleCopy(guideLabels, "zh-hant", 5, {
      eyebrow: "工具指南",
      title: "Aion 2 DPS 計量表：內建版 vs AionFlex——該用哪個？",
      description: "Aion 2 既有內建 DPS 計量表（4 月加入韓服），也有新的社群工具 AionFlex。比較兩者各自的功能與適用時機。",
      intro: "想在 Aion 2 中分析傷害的玩家有好消息：你無需在官方與社群之間二選一——兩者並存。韓服自 4 月 1 日更新起已內建 DPS 計量表，社群工具 AionFlex 在今年 8 月加入了排行分析層。本指南對比兩者並說明何時各取所需。",
      sourceNote: "基於 AION2Hub 4 月 1 日內建計量表說明、Aion2Hub 上的 AionFlex 上線公告及 AionFlex 工具列表。",
      keywords: ["Aion 2 內建 DPS 計量表", "Aion 2 AionFlex", "Aion 2 傷害解析器", "Aion 2 解析傷害", "Aion 2 戰鬥日誌"],
      sections: [
        section("builtin", "內建 DPS 計量表", ["韓服在 2026 年 4 月 1 日更新中加入 DPS 計量表。作為第一方功能，它內建於用戶端——無需外部工具、無需上傳流程、無使用條款問題。", "內建計量表是安全的預設選擇：它用官方資料追蹤你與隊伍在戰鬥中的傷害。如果你只想確認「我的循環打得好嗎」，這已足夠。"]),
        section("aionflex", "AionFlex——社群層", ["AionFlex 的 AION 2 DPS 計量表於 2026 年 8 月上線，透過 Aion2Hub 推廣：「分析每場戰鬥並衝擊排行榜」。其差異在於排行層——社群排名、逐場戰鬥分解與跨隊伍比較。", "作為第三方工具，具體工作流（日誌擷取、上傳、平台支援）取決於工具當前文件。社群工具適合想要公開基準的進度型開荒玩家。"]),
        section("choose", "該用哪個？", ["日常遊玩使用內建計量表：循環檢查、團本截圖、構築改動後的快速確認——零設定且始終與遊戲同步。", "當你想要公開排行、更深入的逐場分析或跨時間構築比較時，搭配 AionFlex（或類似社群解析器）。兩者並不衝突：內建版用於遊戲內驗證，社群工具用於外部記錄。"]),
        section("global", "全球玩家須知", ["NCSoft 尚未確認內建計量表是否隨 9 月 30 日全球上線提供——韓服功能歷史上逐步抵達全球版本。全球上線的社群計量表同樣未確認。", "實用建議：無論全球服務上線時提供何種計量表，用解析改進循環的技能可直接遷移。現在專注於掌握循環，以便第一天就能讀懂你的數字。"]),
      ],
    }),
  },
};