import { articleCopy, localizations, newsLabels, publishedVerified, section } from "./trending-august-17-shared";
import type { ContentEntry, ContentHeroImage, ContentSource } from "./content-registry";

/* ARTICLE 2 — August 2026 update preview: new dungeons + housing teaser */

const updatePreviewSource1: ContentSource = {
  id: "msn-update-preview-2026-08-17",
  kind: "third-party", publisher: "MSN",
  label: "Aion 2 reveals new dungeons and class concept enhancements; 'housing' up next",
  url: "https://www.msn.com/en-us/entertainment/general/aion-2-reveals-new-dungeons-and-class-concept-enhancements-housing-up-next/ar-AA29QqfP",
  publishedAt: "2026-08-11",
  retrievedAt: "2026-08-17",
  verifiedAt: "2026-08-17",
  localizations: localizations({
    "zh-hans": "Aion 2 公布新副本与职业概念增强，住房系统紧随其后",
    en: "Aion 2 reveals new dungeons and class concept enhancements; 'housing' up next",
    fr: "Aion 2 dévoile de nouveaux donjons et des améliorations de concepts de classes ; 'housing' à venir",
    de: "Aion 2 enthüllt neue Dungeons und Klassenkonzept-Verbesserungen; 'Housing' als Nächstes",
    es: "Aion 2 revela nuevas mazmorras y mejoras de conceptos de clases; 'housing' a continuación",
    ja: "Aion 2、新ダンジョンとクラスコンセプト強化を発表、『ハウジング』は次に",
    "pt-br": "Aion 2 revela novos calabouços e melhorias de conceitos de classes; 'housing' por vir",
    ru: "Aion 2 показал новые подземелья и улучшения концепций классов; дальше — 'жильё'",
    ko: "Aion 2, 새 던전과 클래스 콘셉트 개선 공개, '하우징'은 다음",
    "zh-hant": "Aion 2 公布新副本與職業概念增強，住房系統緊隨其後",
  }, "https://www.msn.com/en-us/entertainment/general/aion-2-reveals-new-dungeons-and-class-concept-enhancements-housing-up-next/ar-AA29QqfP"),
};

const updatePreviewSource2: ContentSource = {
  id: "aion2hub-update-aug12-2026-08-17",
  kind: "third-party", publisher: "AION2Hub",
  label: "AION 2 Update — August 12, 2026",
  url: "https://aion2hub.com/updates",
  publishedAt: "2026-08-12",
  retrievedAt: "2026-08-17",
  verifiedAt: "2026-08-17",
  localizations: localizations({
    "zh-hans": "AION 2 更新 — 2026年8月12日",
    en: "AION 2 Update — August 12, 2026",
    fr: "AION 2 Mise à jour — 12 août 2026",
    de: "AION 2 Update — 12. August 2026",
    es: "AION 2 Actualización — 12 de agosto de 2026",
    ja: "AION 2 アップデート — 2026年8月12日",
    "pt-br": "AION 2 Atualização — 12 de agosto de 2026",
    ru: "AION 2 Обновление — 12 августа 2026",
    ko: "AION 2 업데이트 — 2026년 8월 12일",
    "zh-hant": "AION 2 更新 — 2026年8月12日",
  }, "https://aion2hub.com/updates"),
};

const updatePreviewSource3: ContentSource = {
  id: "plaync-kr-update-2026-08-17",
  kind: "official", publisher: "NCSOFT",
  label: "AION 2 (KR) — 업데이트 미리보기: 챕터 1 파트 2",
  url: "https://aion2.plaync.com/ko-kr/board/notice",
  publishedAt: "2026-08-11",
  retrievedAt: "2026-08-17",
  verifiedAt: "2026-08-17",
  localizations: localizations({
    "zh-hans": "AION 2（韩服）— 更新预览：第一章第二部分",
    en: "AION 2 (KR) — Update Preview: Chapter 1 Part 2",
    fr: "AION 2 (KR) — Aperçu de la mise à jour : chapitre 1 partie 2",
    de: "AION 2 (KR) — Update-Vorschau: Kapitel 1 Teil 2",
    es: "AION 2 (KR) — Vista previa de la actualización: capítulo 1 parte 2",
    ja: "AION 2 (KR) — アップデートプレビュー：第1章パート2",
    "pt-br": "AION 2 (KR) — Prévia da atualização: capítulo 1 parte 2",
    ru: "AION 2 (KR) — Превью обновления: глава 1, часть 2",
    ko: "AION 2 (KR) — 업데이트 미리보기: 챕터 1 파트 2",
    "zh-hant": "AION 2（韓服）— 更新預覽：第一章第二部分",
  }, "https://aion2.plaync.com/ko-kr/board/notice"),
};

const updatePreviewHero: ContentHeroImage = {
  src: "https://blogfiles.ncsoft.net/news/af7330da-4ff6-4b58-aece-400e6061a3be.jpg",
  width: 1100, height: 605,
  credit: "NC Corporation",
  sourceUrl: "https://aion2.plaync.com/ko-kr/board/notice",
  rights: "linked-official-media",
  translations: {
    "zh-hans": { alt: "Aion 2 更新预览直播公告图", caption: "NC 官方配图；NCSoft 在8月11日直播中公布了第一章第二部分与住房系统预告。" },
    en: { alt: "Aion 2 update preview broadcast announcement image", caption: "Official NC artwork; NCSoft's August 11 broadcast revealed Chapter 1 Part 2 and a housing teaser." },
    fr: { alt: "Image d'annonce de la diffusion d'aperçu de mise à jour Aion 2", caption: "Visuel officiel NC ; la diffusion du 11 août a révélé le chapitre 1 partie 2 et un aperçu du logement." },
    de: { alt: "Aion 2 Update-Vorschau-Ankündigungsbild", caption: "Offizielles NC-Artwork; die Sendung vom 11. August enthüllte Kapitel 1 Teil 2 und einen Housing-Teaser." },
    es: { alt: "Imagen de anuncio de la transmisión de avance de Aion 2", caption: "Arte oficial de NC; la transmisión del 11 de agosto reveló el capítulo 1 parte 2 y un adelanto de vivienda." },
    ja: { alt: "Aion 2 アップデートプレビュー放送告知画像", caption: "NC公式アートワーク；8月11日の放送で第1章パート2とハウジングティーザーが公開されました。" },
    "pt-br": { alt: "Imagem de anúncio da transmissão de prévia de atualização do Aion 2", caption: "Arte oficial da NC; a transmissão de 11 de agosto revelou o capítulo 1 parte 2 e um vislumbre de housing." },
    ru: { alt: "Изображение анонса трансляции-превью обновления Aion 2", caption: "Официальный арт NC; трансляция 11 августа раскрыла главу 1 часть 2 и тизер жилья." },
    ko: { alt: "Aion 2 업데이트 프리뷰 방송 공지 이미지", caption: "NC 공식 이미지입니다. 8월 11일 방송에서 챕터 1 파트 2와 하우징 티저가 공개되었습니다." },
    "zh-hant": { alt: "Aion 2 更新預覽直播公告圖", caption: "NC 官方配圖；NCSoft 在8月11日直播中公佈了第一章第二部分與住房系統預告。" },
  },
};

export const trendingAugust17Article2: ContentEntry = {
  section: "news",
  slug: "aion-2-update-preview-new-dungeons-housing",
  schemaType: "NewsArticle",
  publishedAt: "2026-08-17",
  updatedAt: "2026-08-17",
  readingMinutes: 6,
  publication: publishedVerified,
  sources: [updatePreviewSource1, updatePreviewSource2, updatePreviewSource3],
  heroImage: updatePreviewHero,
  related: [
    { kind: "content", section: "guides", slug: "aion-2-housing-system-preview" },
    { kind: "content", section: "guides", slug: "aion-2-pet-system-guide" },
    { kind: "content", section: "guides", slug: "global-launch-dungeon-raid-size-changes" },
  ],
  translations: {
    en: articleCopy(newsLabels, "en", 6, {
      eyebrow: "KR UPDATE PREVIEW",
      title: "Aion 2 Update Preview: Chapter 1 Part 2 Brings New Dungeons, Class Concept Upgrades & a Housing Teaser",
      description: "NCSoft's August 11 Aion 2 preview broadcast revealed Chapter 1 Part 2 content — new dungeons, class concept enhancements, and a first teaser for a housing system. Here's what was shown and what it means for global players.",
      intro: "On August 11, 2026, NCSoft aired a preview broadcast for the second part of Aion 2's Chapter 1 — the first part launched in July. The broadcast, described as revealing 'a wealth of content, reminiscent of a grand feast,' covered new dungeons, class concept enhancements, and ended with the biggest news of all: a housing system is coming next. For global players waiting on the September 30 early access, this is your best window into what Aion 2's content pipeline looks like.",
      sourceNote: "Based on MSN's August 11 coverage of the Aion 2 update preview broadcast and AION2Hub's patch notes for the August 12 update that followed. KR service details confirmed via NCSOFT's official notice board.",
      keywords: ["Aion 2 Chapter 1 Part 2", "Aion 2 new dungeons", "Aion 2 housing system", "Aion 2 class concept update", "Aion 2 KR update preview"],
      sections: [
        section("overview", "The August 11 Preview Broadcast", ["NCSoft's August 11 preview broadcast set the stage for the second part of Chapter 1, which first launched in July. Following the pattern of previous update cycles, the broadcast combined a look at the immediate patch with a roadmap of what comes after.", "The most striking takeaway was the breadth of the announcement — new dungeon and expedition content, refinements to how classes express their identities, and a tease of a housing system positioned as the next major milestone. It signals that Aion 2's KR service continues to expand rapidly, with global service expected to inherit this roadmap over time."]),
        section("dungeons", "New Dungeon & Expedition Content", ["The preview highlighted new instanced content arriving with the update, adding to the launch-era dungeons. The August 12 patch that followed delivered the Encroached Deus Research Base expedition and expanded late-game progression with new Draconic and Abyss accessory tiers.", "For global players, the dungeon pipeline is a reminder that launch content (as detailed in our dungeon and raid size guide) is only the beginning — NCSoft is actively expanding the PvE endgame on the KR service, and much of it is expected to arrive globally in the months after launch."]),
        section("classes", "Class Concept Enhancements", ["The broadcast also walked through class concept enhancements aimed at sharpening each job's identity. The accompanying August 12 patch reshaped healing roles: Cleric and Chanter heal effects gained a 40m radius but lost 20-50% of their output, and both healing passives now scale with attack power.", "This rework illustrates NCSoft's philosophy — reinforcing the trinity by making healers' contribution clearer and more buildable, while keeping party dynamics intact. Global players choosing Cleric or Chanter should factor these mechanics into their launch plans."]),
        section("housing", "Housing Teaser — What's Next", ["The headline news was the housing system teaser. NCSoft confirmed housing is 'up next' as the next major addition after Chapter 1 Part 2, marking the first official nod to player housing in Aion 2.", "Details are deliberately thin — no release timing, feature list, or implementation specifics were shared beyond the tease. For a full breakdown of what this could mean and how to set expectations, see our housing preview guide."]),
        section("global", "What Global Players Should Expect", ["The KR preview has direct implications for global players. NCSoft has said the global version launches free-to-play with Western early access starting September 30, and content parity with KR will build gradually.", "Expect the Chapter 1 Part 2 content and the housing system to reach global service in the months after launch. For now, focus on the launch basics: classes, five server regions, and the core dungeon-to-raid loop."]),
      ],
    }),
    "zh-hans": articleCopy(newsLabels, "zh-hans", 6, {
      eyebrow: "韩服更新预览",
      title: "Aion 2 更新预览：第一章第二部分带来新副本、职业概念升级与住房预告",
      description: "NCSoft 在 8 月 11 日的 Aion 2 预览直播中公布了第一章第二部分内容——新副本、职业概念增强，以及住房系统的首次预告。以下是展示内容及其对全球玩家的意义。",
      intro: "2026 年 8 月 11 日，NCSoft 举行了 Aion 2 第一章第二部分的预览直播——第一部分已于 7 月上线。这场被形容为「盛宴般丰富内容」的直播涵盖新副本、职业概念增强，并以最重磅的新闻收尾：住房系统即将到来。对于等待 9 月 30 日抢先体验的全球玩家而言，这是了解 Aion 2 内容管线的最佳窗口。",
      sourceNote: "基于 MSN 8 月 11 日对 Aion 2 更新预览直播的报道，以及 AION2Hub 对随后 8 月 12 日补丁的更新日志。韩服细节经 NCSOFT 官方公告确认。",
      keywords: ["Aion 2 第一章第二部分", "Aion 2 新副本", "Aion 2 住房系统", "Aion 2 职业概念更新", "Aion 2 韩服更新预览"],
      sections: [
        section("overview", "8 月 11 日预览直播", ["NCSoft 的 8 月 11 日预览直播为第一章的第二部分定下基调，第一部分已于 7 月上线。延续以往更新周期的模式，直播既展示了即将到来的补丁，也预告了后续路线图。", "最令人瞩目的是一系列重磅内容——新副本与远征内容、职业定位的精细化调整，以及被定位为下一个重大里程碑的住房系统预告。这表明韩服服务仍在快速扩张，全球服预计将逐步继承这一路线图。"]),
        section("dungeons", "新副本与远征内容", ["预览重点展示了随更新到来的新实例内容，扩充了首发期的副本阵容。随后的 8 月 12 日补丁上线了「被侵蚀的神之研究所」远征，并以新的龙族与深渊饰品等级延伸后期养成。", "对全球玩家而言，副本管线提醒我们：首发内容（详见我们的副本与团本规模指南）只是开始——NCSoft 正在韩服积极扩充 PvE 后期内容，其中大部分预计将在全球上线后的数月内陆续到来。"]),
        section("classes", "职业概念增强", ["直播还讲解了旨在强化各职业定位的职业概念增强。随附的 8 月 12 日补丁重塑了治疗角色：牧师与吟游星的治疗效果范围提升至 40 米，但输出降低 20-50%，且两个治疗被动改为随攻击力成长。", "这次改版体现了 NCSoft 的理念——通过让治疗者的贡献更清晰、更可构筑来强化铁三角，同时保持队伍动力学不变。全球玩家若选择牧师或吟游星，应将这套机制纳入首发规划。"]),
        section("housing", "住房预告——下一步", ["头条新闻是住房系统预告。NCSoft 确认住房系统是第一章第二部分之后的下一个重大新增内容，这也是 Aion 2 首次官方提及玩家住房。", "细节刻意从简——除预告外未分享发布时间、功能清单或实现细节。有关这意味着什么以及如何设定预期的完整解读，请参阅我们的住房系统前瞻指南。"]),
        section("global", "全球玩家应期待什么", ["韩服预览对全球玩家有直接影响。NCSoft 表示全球版将以免费游玩形式上线，西方服抢先体验于 9 月 30 日开始，与韩服的内容对齐将逐步推进。", "预计第一章第二部分内容与住房系统将在全球上线后数月内抵达全球服。目前请聚焦上线基础：职业、五大服务器区域，以及从副本到团本的核心循环。"]),
      ],
    }),
    ko: articleCopy(newsLabels, "ko", 6, {
      eyebrow: "KR 업데이트 프리뷰",
      title: "Aion 2 업데이트 프리뷰: 챕터 1 파트 2, 새 던전·클래스 콘셉트 강화·하우징 티저",
      description: "NCSoft의 8월 11일 Aion 2 프리뷰 방송에서 챕터 1 파트 2 콘텐츠가 공개되었습니다 — 새 던전, 클래스 콘셉트 강화, 그리고 하우징 시스템의 첫 티저. 공개된 내용과 글로벌 플레이어에게 미치는 의미입니다.",
      intro: "2026년 8월 11일, NCSoft는 7월에 출시된 챕터 1의 두 번째 파트를 위한 프리뷰 방송을 진행했습니다. '성대한 향연을 연상케 하는 풍부한 콘텐츠'로 묘사된 방송은 새 던전, 클래스 콘셉트 강화를 다루었고, 최대 뉴스인 하우징 시스템이 다음으로 온다는 소식으로 마무리되었습니다. 9월 30일 얼리 액세스를 기다리는 글로벌 플레이어에게 이는 Aion 2 콘텐츠 파이프라인의 최고의 창입니다.",
      sourceNote: "MSN의 8월 11일 Aion 2 업데이트 프리뷰 방송 보도와 이어지는 8월 12일 패치의 AION2Hub 패치 노트에 기반합니다. KR 서비스 세부 사항은 NCSOFT 공식 게시판으로 확인되었습니다.",
      keywords: ["Aion 2 챕터 1 파트 2", "Aion 2 새 던전", "Aion 2 하우징 시스템", "Aion 2 클래스 콘셉트 업데이트", "Aion 2 KR 업데이트 프리뷰"],
      sections: [
        section("overview", "8월 11일 프리뷰 방송", ["NCSoft의 8월 11일 프리뷰 방송은 7월에 출시된 챕터 1의 두 번째 파트를 위한 무대를 마련했습니다. 이전 업데이트 주기의 패턴대로, 곧 도착할 패치와 그 후의 로드맵을 함께 보여주었습니다.", "가장 인상적인 점은 발표의 폭이었습니다 — 새 던전과 원정대 콘텐츠, 클래스 정체성의 정교화, 그리고 다음 주요 이정표로 자리잡은 하우징 시스템 티저까지. KR 서비스가 빠르게 확장 중이며 글로벌 서비스가 이 로드맵을 점진적으로 물려받을 것임을 시사합니다."]),
        section("dungeons", "새 던전 및 원정대 콘텐츠", ["프리뷰는 출시기 던전에 더해 업데이트와 함께 도착하는 새 인스턴스 콘텐츠를 강조했습니다. 이어진 8월 12일 패치는 '침식된 신 연구기지' 원정대를 추가하고 새 드라코닉·심연 액세서리 티어로 후반 성장을 확장했습니다.", "글로벌 플레이어에게 던전 파이프라인은 출시 콘텐츠(던전·레이드 규모 가이드 참조)가 시작에 불과하며, NCSoft가 KR 서비스에서 PvE 엔드게임을 적극 확장 중이고 그중 상당수가 출시 후 수개월 내 글로벌에 도착할 것임을 상기시킵니다."]),
        section("classes", "클래스 콘셉트 강화", ["방송은 각 직업의 정체성을 날카롭게 하는 클래스 콘셉트 강화도 다루었습니다. 동반된 8월 12일 패치는 힐러 역할을 재구성했습니다: 클레릭과 챈터의 힐 효과는 40m 범위를 얻는 대신 출력이 20-50% 감소했고, 두 힐링 패시브는 공격력에 비례하도록 변경되었습니다.", "이 리워크는 NCSoft의 철학을 보여줍니다 — 힐러의 기여를 더 명확하고 빌드 가능하게 만들어 삼위일체를 강화하면서 파티 다이내믹은 유지하는 것. 글로벌에서 클레릭이나 챈터를 선택할 플레이어는 이 메커니즘을 출시 계획에 반영해야 합니다."]),
        section("housing", "하우징 티저 — 다음 소식", ["헤드라인 뉴스는 하우징 시스템 티저였습니다. NCSoft는 하우징이 챕터 1 파트 2 이후 다음 주요 추가 기능으로 온다고 확인했으며, 이는 Aion 2에서 플레이어 하우징에 대한 첫 공식 언급입니다.", "세부 사항은 의도적으로 최소화되었습니다 — 티저 외에 출시 시기, 기능 목록, 구현 세부 사항은 공유되지 않았습니다. 이것이 무엇을 의미하는지, 기대치를 어떻게 설정할지에 대한 전체 분석은 하우징 프리뷰 가이드를 참조하세요."]),
        section("global", "글로벌 플레이어가 기대할 것", ["KR 프리뷰는 글로벌 플레이어에게 직접적인 의미가 있습니다. NCSoft는 글로벌 버전이 무료 플레이로 출시되고 서구권 얼리 액세스가 9월 30일에 시작되며, KR과의 콘텐츠 동일성은 점진적으로 구축될 것이라고 밝혔습니다.", "챕터 1 파트 2 콘텐츠와 하우징 시스템은 출시 후 수개월 내에 글로벌 서비스에 도달할 것으로 예상하세요. 지금은 클래스, 5개 서버 지역, 던전-레이드 핵심 루프 등 출시 기본에 집중하세요."]),
      ],
    }),
    ja: articleCopy(newsLabels, "ja", 6, {
      eyebrow: "KRアップデートプレビュー",
      title: "Aion 2 アップデートプレビュー：第1章パート2で新ダンジョン、クラスコンセプト強化、ハウジングティーザー",
      description: "NCSoft の8月11日 Aion 2 プレビュー放送で第1章パート2のコンテンツが公開されました — 新ダンジョン、クラスコンセプト強化、そしてハウジングシステムの初ティーザー。公開内容とグローバルプレイヤーへの意味をまとめます。",
      intro: "2026年8月11日、NCSoft は7月に開始した第1章の第2部に向けたプレビュー放送を行いました。『豪華な饗宴を思わせる豊富なコンテンツ』と評された放送は、新ダンジョン、クラスコンセプト強化を取り上げ、そして最大のニュースである『ハウジングが次に来る』という発表で締めくくられました。9月30日の早期アクセスを待つグローバルプレイヤーにとって、これは Aion 2 のコンテンツパイプラインを最もよく知る窓口です。",
      sourceNote: "MSN の8月11日 Aion 2 アップデートプレビュー放送報道と、それに続く8月12日パッチの AION2Hub パッチノートに基づきます。KR サービスの詳細は NCSOFT 公式掲示板で確認済みです。",
      keywords: ["Aion 2 第1章パート2", "Aion 2 新ダンジョン", "Aion 2 ハウジングシステム", "Aion 2 クラスコンセプト更新", "Aion 2 KRアップデートプレビュー"],
      sections: [
        section("overview", "8月11日プレビュー放送", ["NCSoft の8月11日プレビュー放送は、7月に開始した第1章の第2部に向けた舞台を整えました。これまでのアップデートサイクルのパターンに従い、直近のパッチとその先のロードマップを同時に示しました。", "最も印象的だったのは発表の幅でした — 新ダンジョン・遠征コンテンツ、クラスのアイデンティティ表現の洗練、そして次の大型マイルストーンとして位置づけられたハウジングシステムのティーザーまで。KR サービスが急速に拡大しており、グローバルサービスがこのロードマップを段階的に引き継ぐことが示唆されます。"]),
        section("dungeons", "新ダンジョンと遠征コンテンツ", ["プレビューは、アップデートとともに到着する新インスタンスコンテンツを強調し、ローンチ時代のダンジョン群を拡充しました。続く8月12日パッチでは『蝕まれた神の研究基地』遠征が追加され、新ドラコニック・アビスアクセサリーティアで後半育成が拡張されました。", "グローバルプレイヤーにとって、ダンジョンパイプラインは、ローンチコンテンツ（ダンジョン・レイド規模ガイド参照）が始まりに過ぎず、NCSoft が KR サービスで PvE エンドゲームを積極拡張しており、その多くがローンチ後数ヶ月以内にグローバルに到着する見込みであることを思い出させます。"]),
        section("classes", "クラスコンセプト強化", ["放送は各ジョブのアイデンティティを明確化するクラスコンセプト強化も紹介しました。伴う8月12日パッチはヒーラーの役割を再構築：クレリックとチャンターのヒール効果は40m範囲を得る代わりに出力が20〜50%減少し、両ヒールパッシブは攻撃力に比例するようになりました。", "このリワークは NCSoft の哲学を示しています — ヒーラーの貢献を明確でビルド可能にすることでトリニティを強化しつつ、パーティーダイナミクスを維持するというもの。グローバルでクレリックやチャンターを選ぶプレイヤーはこのメカニクスをローンチ計画に組み込むべきです。"]),
        section("housing", "ハウジングティーザー — 次の大型追加", ["ヘッドラインはハウジングシステムのティーザーでした。NCSoft は、ハウジングが第1章パート2の次に来る大型追加機能であると確認し、Aion 2 でのプレイヤーハウジングへの初の公式言及となりました。", "詳細は意図的に伏せられています — ティーザー以外に、リリース時期、機能リスト、実装の詳細は共有されていません。これが何を意味するか、期待値をどう設定するかの完全な解説は、ハウジングプレビューガイドをご覧ください。"]),
        section("global", "グローバルプレイヤーが期待できること", ["KR プレビューはグローバルプレイヤーに直接的な意味を持ちます。NCSoft は、グローバル版は無料プレイでローンチし、西側早期アクセスが9月30日に始まり、KR とのコンテンツ同等性は段階的に構築されると述べています。", "第1章パート2コンテンツとハウジングシステムは、ローンチ後数ヶ月以内にグローバルサービスに到達すると予想してください。今はクラス、5サーバーリージョン、ダンジョンからレイドへのコアループといったローンチの基本に集中しましょう。"]),
      ],
    }),
    fr: articleCopy(newsLabels, "fr", 6, {
      eyebrow: "APERÇU MISE À JOUR KR",
      title: "Aperçu de la mise à jour Aion 2 : le chapitre 1 partie 2 apporte donjons, améliorations de classes et un aperçu du logement",
      description: "La diffusion d'aperçu Aion 2 du 11 août de NCSoft a révélé le contenu du chapitre 1 partie 2 — nouveaux donjons, améliorations de concepts de classes et premier aperçu du système de logement.",
      intro: "Le 11 août 2026, NCSoft a diffusé un aperçu de la deuxième partie du chapitre 1 d'Aion 2. La diffusion, décrite comme révélant 'une richesse de contenu, rappelant un grand festin,' a couvert les nouveaux donjons, les améliorations de classes et s'est terminée par le système de logement.",
      sourceNote: "Basé sur la couverture MSN du 11 août et les notes de patch AION2Hub du 12 août. Détails KR confirmés via le tableau d'affichage officiel de NCSOFT.",
      keywords: ["Aion 2 chapitre 1 partie 2", "Aion 2 nouveaux donjons", "Aion 2 système de logement", "Aion 2 améliorations classes", "aperçu mise à jour Aion 2 KR"],
      sections: [
        section("overview", "La diffusion d'aperçu du 11 août", ["L'aperçu du 11 août a préparé le terrain pour la deuxième partie du chapitre 1, qui a débuté en juillet. La diffusion a combiné le patch immédiat avec une feuille de route.", "La principale conclusion : une ampleur d'annonces impressionnante — nouveaux donjons, raffinements de classes et un aperçu du logement comme prochain jalon majeur."]),
        section("dungeons", "Nouveaux donjons et expéditions", ["L'aperçu a mis en avant de nouveaux contenus instanciés. Le patch du 12 août a livré l'expédition Base de recherche envahie de Deus et élargi la progression avec de nouveaux paliers d'accessoires Draconic et Abyss.", "Le pipeline de donjons rappelle que le contenu de lancement n'est que le début de l'endgame PvE, qui s'étend activement côté KR."]),
        section("classes", "Améliorations de concepts de classes", ["Le patch du 12 août a remodelé les rôles de soin : les soins de Clerc et de Chanteur ont gagné une portée de 40 m mais perdu 20-50 % de puissance, avec des passifs de soin évoluant avec la puissance d'attaque.", "Ce rework renforce la trinité et rend la contribution des soigneurs plus claire — un point clé pour les joueurs globaux planifiant leur classe."]),
        section("housing", "Logement : ce qui arrive ensuite", ["La nouvelle majeure : NCSoft a confirmé que le logement est 'à venir' comme prochain ajout majeur après le chapitre 1 partie 2, une première mention officielle du logement joueur dans Aion 2.", "Les détails sont volontairement minces. Voir notre guide d'aperçu du logement pour une analyse complète."]),
        section("global", "Ce que les joueurs globaux peuvent attendre", ["Le service global lancera en free-to-play avec accès anticipé occidental le 30 septembre, et la parité avec KR se construira progressivement.", "Attendez-vous au contenu du chapitre 1 partie 2 et au logement dans les mois suivant le lancement. Pour l'instant, concentrez-vous sur les bases."]),
      ],
    }),
    de: articleCopy(newsLabels, "de", 6, {
      eyebrow: "KR-UPDATE-VORSCHAU",
      title: "Aion 2 Update-Vorschau: Kapitel 1 Teil 2 bringt neue Dungeons, Klassenkonzept-Upgrades und einen Housing-Teaser",
      description: "NCSofts Aion-2-Vorschau vom 11. August enthüllte Inhalte für Kapitel 1 Teil 2 — neue Dungeons, Klassenkonzept-Verbesserungen und einen ersten Teaser für ein Housing-System.",
      intro: "Am 11. August 2026 strahlte NCSoft eine Vorschau für den zweiten Teil von Aion 2s Kapitel 1 aus. Die Sendung, beschrieben als Offenlegung 'eines Reichtums an Inhalten, der an ein großes Festmahl erinnert,' behandelte neue Dungeons und Klassenverbesserungen und endete mit der Ankündigung des Housing-Systems.",
      sourceNote: "Basierend auf MSNs Berichterstattung vom 11. August und AION2Hub-Patchnotes vom 12. August. KR-Details über NCSOFTs offizielles Anschlagbrett bestätigt.",
      keywords: ["Aion 2 Kapitel 1 Teil 2", "Aion 2 neue Dungeons", "Aion 2 Housing-System", "Aion 2 Klassenkonzept-Update", "Aion 2 KR-Update-Vorschau"],
      sections: [
        section("overview", "Die Vorschau vom 11. August", ["Die Vorschau bereitete die Bühne für den zweiten Teil von Kapitel 1. Wie in früheren Zyklen wurden der unmittelbare Patch und die Roadmap gezeigt.", "Das auffälligste Ergebnis: die Breite der Ankündigungen — neue Dungeons, Klassenzuschnitte und ein Housing-Teaser als nächstes großes Meilenstein-Projekt."]),
        section("dungeons", "Neue Dungeons und Expeditionen", ["Die Vorschau hob neue Instanz-Inhalte hervor. Der Patch vom 12. August lieferte die Expedition 'Eingedrungene Deus-Forschungsbasis' und erweiterte den Fortschritt mit neuen Draconic- und Abyss-Accessoire-Stufen.", "Die Dungeon-Pipeline erinnert daran, dass der Launch-Inhalt erst der Anfang des PvE-Endgames ist."]),
        section("classes", "Klassenkonzept-Verbesserungen", ["Der Patch vom 12. August formte Heilerrollen um: Cleric- und Chanter-Heilungen erhielten 40 m Reichweite, verloren aber 20-50 % Wirkung; beide Heilungs-Passive skalieren nun mit Angriffskraft.", "Dieses Rework stärkt die Trinität und macht den Beitrag der Heiler klarer — wichtig für Global-Spieler bei der Klassenwahl."]),
        section("housing", "Housing — was als Nächstes kommt", ["Die wichtigste Nachricht: NCSoft bestätigte, dass Housing als nächste große Ergänzung nach Kapitel 1 Teil 2 kommt — die erste offizielle Erwähnung von Spieler-Housing in Aion 2.", "Details sind bewusst knapp. Siehe unseren Housing-Vorschau-Guide für eine vollständige Analyse."]),
        section("global", "Was Global-Spieler erwarten können", ["Der globale Dienst startet Free-to-Play mit Western-Early-Access am 30. September; die Inhaltsgleichheit mit KR wächst schrittweise.", "Rechnen Sie mit Kapitel-1-Teil-2-Inhalten und Housing in den Monaten nach dem Launch. Fokussieren Sie jetzt auf die Grundlagen."]),
      ],
    }),
    es: articleCopy(newsLabels, "es", 6, {
      eyebrow: "AVANCE DE ACTUALIZACIÓN KR",
      title: "Avance de actualización de Aion 2: el capítulo 1 parte 2 trae nuevas mazmorras, mejoras de clases y un adelanto de vivienda",
      description: "La transmisión de avance de Aion 2 del 11 de agosto de NCSoft reveló el contenido del capítulo 1 parte 2: nuevas mazmorras, mejoras de conceptos de clases y el primer adelanto del sistema de vivienda.",
      intro: "El 11 de agosto de 2026, NCSoft transmitió un avance de la segunda parte del capítulo 1 de Aion 2. La transmisión, descrita como reveladora de 'una gran cantidad de contenido, similar a un gran festín', cubrió nuevas mazmorras, mejoras de clases y terminó con el sistema de vivienda.",
      sourceNote: "Basado en la cobertura de MSN del 11 de agosto y las notas de parche de AION2Hub del 12 de agosto. Detalles KR confirmados vía el tablón oficial de NCSOFT.",
      keywords: ["Aion 2 capítulo 1 parte 2", "Aion 2 nuevas mazmorras", "Aion 2 sistema de vivienda", "Aion 2 mejoras de clases", "avance de actualización Aion 2 KR"],
      sections: [
        section("overview", "La transmisión de avance del 11 de agosto", ["El avance del 11 de agosto preparó el terreno para la segunda parte del capítulo 1, que comenzó en julio. Combinó el parche inmediato con una hoja de ruta.", "Lo más llamativo: la amplitud de los anuncios — nuevas mazmorras, refinamientos de clases y un adelanto de vivienda como próximo hito."]),
        section("dungeons", "Nuevas mazmorras y expediciones", ["El avance destacó nuevos contenidos instanciados. El parche del 12 de agosto entregó la expedición Base de Investigación Deus Invadida y amplió la progresión con nuevos niveles de accesorios Draconic y Abyss.", "El canal de mazmorras recuerda que el contenido de lanzamiento es solo el comienzo del endgame PvE."]),
        section("classes", "Mejoras de conceptos de clases", ["El parche del 12 de agosto reformó los roles de sanación: las curaciones de Clérigo y Cantor ganaron 40 m de alcance pero perdieron 20-50 % de poder, con pasivas de sanación escalando con poder de ataque.", "Este rework refuerza la trinidad y aclara la contribución de los sanadores — clave para los jugadores globales."]),
        section("housing", "Vivienda: lo que sigue", ["La gran noticia: NCSoft confirmó que la vivienda es 'lo siguiente' como próxima gran adición tras el capítulo 1 parte 2, la primera mención oficial de vivienda de jugador en Aion 2.", "Los detalles son deliberadamente escasos. Consulta nuestra guía de avance de vivienda."]),
        section("global", "Qué esperar para los jugadores globales", ["El servicio global lanzará free-to-play con acceso anticipado occidental el 30 de septiembre, y la paridad con KR crecerá progresivamente.", "Espera el contenido del capítulo 1 parte 2 y la vivienda en los meses posteriores al lanzamiento."]),
      ],
    }),
    "pt-br": articleCopy(newsLabels, "pt-br", 6, {
      eyebrow: "PRÉVIA DE ATUALIZAÇÃO KR",
      title: "Prévia da atualização de Aion 2: capítulo 1 parte 2 traz novas masmorras, melhorias de classes e um vislumbre de housing",
      description: "A transmissão de prévia de Aion 2 de 11 de agosto da NCSoft revelou o conteúdo do capítulo 1 parte 2 — novas masmorras, melhorias de conceitos de classes e o primeiro vislumbre do sistema de housing.",
      intro: "Em 11 de agosto de 2026, a NCSoft exibiu uma prévia da segunda parte do capítulo 1 de Aion 2. A transmissão, descrita como revelando 'uma riqueza de conteúdo, reminiscente de um grande banquete', cobriu novas masmorras, melhorias de classes e terminou com o sistema de housing.",
      sourceNote: "Baseado na cobertura da MSN de 11 de agosto e nas notas de patch da AION2Hub de 12 de agosto. Detalhes KR confirmados via quadro oficial da NCSOFT.",
      keywords: ["Aion 2 capítulo 1 parte 2", "Aion 2 novas masmorras", "Aion 2 sistema de housing", "Aion 2 melhorias de classes", "prévia de atualização Aion 2 KR"],
      sections: [
        section("overview", "A transmissão de prévia de 11 de agosto", ["A prévia de 11 de agosto preparou o terreno para a segunda parte do capítulo 1, iniciado em julho. Combinou o patch imediato com um roteiro.", "O destaque: a amplitude dos anúncios — novas masmorras, refinamentos de classes e um vislumbre de housing como próximo marco."]),
        section("dungeons", "Novas masmorras e expedições", ["A prévia destacou novos conteúdos instanciados. O patch de 12 de agosto entregou a expedição Base de Pesquisa Deus Invadida e expandiu a progressão com novos níveis de acessórios Draconic e Abyss.", "O pipeline de masmorras lembra que o conteúdo de lançamento é só o começo do endgame PvE."]),
        section("classes", "Melhorias de conceitos de classes", ["O patch de 12 de agosto reformulou os papéis de cura: as curas de Clérigo e Cantor ganharam 40 m de alcance, mas perderam 20-50 % de poder, com passivas de cura escalando com poder de ataque.", "Esse rework fortalece a trindade e esclarece a contribuição dos curadores — chave para jogadores globais."]),
        section("housing", "Housing: o que vem em seguida", ["A grande notícia: a NCSoft confirmou que housing é 'o próximo' grande acréscimo após o capítulo 1 parte 2, a primeira menção oficial de housing de jogador em Aion 2.", "Os detalhes são deliberadamente escassos. Veja nosso guia de prévia de housing."]),
        section("global", "O que os jogadores globais podem esperar", ["O serviço global lançará free-to-play com acesso antecipado ocidental em 30 de setembro, e a paridade com KR crescerá progressivamente.", "Espere o conteúdo do capítulo 1 parte 2 e housing nos meses após o lançamento."]),
      ],
    }),
    ru: articleCopy(newsLabels, "ru", 6, {
      eyebrow: "ПРЕВЬЮ ОБНОВЛЕНИЯ KR",
      title: "Превью обновления Aion 2: глава 1 часть 2 приносит новые подземелья, улучшения концепций классов и тизер жилья",
      description: "Трансляция-превью Aion 2 от 11 августа раскрыла контент главы 1 части 2 — новые подземелья, улучшения концепций классов и первый тизер системы жилья.",
      intro: "11 августа 2026 года NCSoft провела трансляцию-превью второй части главы 1 Aion 2. Трансляция, описанная как раскрывающая 'богатство контента, напоминающее роскошный пир', охватила новые подземелья, улучшения классов и завершилась новостью о системе жилья.",
      sourceNote: "На основе материала MSN от 11 августа и патч-ноутов AION2Hub от 12 августа. Детали KR подтверждены через официальную доску NCSoft.",
      keywords: ["Aion 2 глава 1 часть 2", "Aion 2 новые подземелья", "Aion 2 система жилья", "Aion 2 улучшения классов", "превью обновления Aion 2 KR"],
      sections: [
        section("overview", "Трансляция-превью 11 августа", ["Превью подготовило почву для второй части главы 1, начатой в июле. Как и в прошлые циклы, показаны ближайший патч и дорожная карта.", "Главное: широта анонсов — новые подземелья, уточнение классов и тизер жилья как следующего крупного этапа."]),
        section("dungeons", "Новые подземелья и экспедиции", ["Превью подчеркнуло новые инстанс-контенты. Патч от 12 августа принёс экспедицию «Захваченная исследовательская база Деус» и расширил прогрессию новыми уровнями аксессуаров Draconic и Abyss.", "Пайплайн подземелий напоминает, что контент запуска — лишь начало PvE-эндейма."]),
        section("classes", "Улучшения концепций классов", ["Патч от 12 августа перестроил роли лечения: исцеления Клирика и Заклинателя получили радиус 40 м, но потеряли 20-50 % мощности, а обе пассивки лечения теперь зависят от силы атаки.", "Этот реворк укрепляет триаду и делает вклад лекарей яснее — важно для глобальных игроков."]),
        section("housing", "Жильё: что дальше", ["Главная новость: NCSoft подтвердила, что жильё — следующее крупное дополнение после главы 1 части 2, первое официальное упоминание жилья игроков в Aion 2.", "Детали сознательно скудны. Полный разбор — в нашем превью-гайде по жилью."]),
        section("global", "Чего ждать глобальным игрокам", ["Глобальный сервис стартует free-to-play с западным ранним доступом 30 сентября; паритет с KR будет строиться постепенно.", "Ожидайте контент главы 1 части 2 и жильё в месяцы после запуска. Пока сосредоточьтесь на основах."]),
      ],
    }),
    "zh-hant": articleCopy(newsLabels, "zh-hant", 6, {
      eyebrow: "韓服更新預覽",
      title: "Aion 2 更新預覽：第一章第二部分帶來新副本、職業概念升級與住房預告",
      description: "NCSoft 在 8 月 11 日的 Aion 2 預覽直播中公佈了第一章第二部分內容——新副本、職業概念增強，以及住房系統的首次預告。以下是展示內容及其對全球玩家的意義。",
      intro: "2026 年 8 月 11 日，NCSoft 舉行了 Aion 2 第一章第二部分的預覽直播——第一部分已於 7 月上線。這場被形容為「盛宴般豐富內容」的直播涵蓋新副本、職業概念增強，並以最重磅的新聞收尾：住房系統即將到來。對於等待 9 月 30 日搶先體驗的全球玩家而言，這是了解 Aion 2 內容管線的最佳窗口。",
      sourceNote: "基於 MSN 8 月 11 日對 Aion 2 更新預覽直播的報導，以及 AION2Hub 對隨後 8 月 12 日補丁的更新日誌。韓服細節經 NCSOFT 官方公告確認。",
      keywords: ["Aion 2 第一章第二部分", "Aion 2 新副本", "Aion 2 住房系統", "Aion 2 職業概念更新", "Aion 2 韓服更新預覽"],
      sections: [
        section("overview", "8 月 11 日預覽直播", ["NCSoft 的 8 月 11 日預覽直播為第一章的第二部分定下基調，第一部分已於 7 月上線。延續以往更新週期的模式，直播既展示了即將到來的補丁，也預告了後續路線圖。", "最令人矚目的是一系列重磅內容——新副本與遠征內容、職業定位的精細化調整，以及被定位為下一個重大里程碑的住房系統預告。這表明韓服服務仍在快速擴張，全球服預計將逐步繼承這一路線圖。"]),
        section("dungeons", "新副本與遠征內容", ["預覽重點展示了隨更新到來的新實例內容，擴充了首發期的副本陣容。隨後的 8 月 12 日補丁上線了「被侵蝕的神之研究所」遠征，並以新的龍族與深淵飾品等級延伸後期養成。", "對全球玩家而言，副本管線提醒我們：首發內容（詳見我們的副本與團本規模攻略）只是開始——NCSoft 正在韓服積極擴充 PvE 後期內容，其中大部分預計將在全球上線後的數月內陸續到來。"]),
        section("classes", "職業概念增強", ["直播還講解了旨在強化各職業定位的職業概念增強。隨附的 8 月 12 日補丁重塑了治療角色：牧師與吟遊星（Chanter）的治療效果範圍提升至 40 米，但輸出降低 20-50%，且兩個治療被動改為隨攻擊力成長。", "這次改版體現了 NCSoft 的理念——透過讓治療者的貢獻更清晰、更可構築來強化鐵三角，同時保持隊伍動力學不變。全球玩家若選擇牧師或吟遊星，應將這套機制納入首發規劃。"]),
        section("housing", "住房預告——下一步", ["頭條新聞是住房系統預告。NCSoft 確認住房系統是第一章第二部分之後的下一個重大新增內容，這也是 Aion 2 首次官方提及玩家住房。", "細節刻意從簡——除預告外未分享發布時間、功能清單或實現細節。有關這意味著什麼以及如何設定預期的完整解讀，請參閱我們的住房系統前瞻攻略。"]),
        section("global", "全球玩家應期待什麼", ["韓服預覽對全球玩家有直接影響。NCSoft 表示全球版將以免費遊玩形式上線，西方服搶先體驗於 9 月 30 日開始，與韓服的內容對齊將逐步推進。", "預計第一章第二部分內容與住房系統將在全球上線後數月內抵達全球服。目前請聚焦上線基礎：職業、五大伺服器區域，以及從副本到團本的核心循環。"]),
      ],
    }),
  },
};