import { articleCopy, guideLabels, localizations, publishedVerified, section } from "./trending-august-18-shared";
import type { ContentEntry, ContentHeroImage, ContentSource } from "./content-registry";

/* ARTICLE 2 — Trial system guide: Vakron Sky Island */

const trialSource1: ContentSource = {
  id: "aion2hub-trial-vakron-2026-08-18",
  kind: "third-party", publisher: "AION2Hub",
  label: "AION 2 Update — July 15, 2026: New Trial 'Vakron Sky Island'",
  url: "https://aion2hub.com/updates",
  publishedAt: "2026-07-15",
  retrievedAt: "2026-08-18",
  verifiedAt: "2026-08-18",
  localizations: localizations({
    "zh-hans": "AION 2 更新 — 2026年7月15日：新试炼「巴克隆空中岛」",
    en: "AION 2 Update — July 15, 2026: New Trial 'Vakron Sky Island'",
    fr: "AION 2 Mise à jour — 15 juillet 2026 : nouveau procès « Vakron Sky Island »",
    de: "AION 2 Update — 15. Juli 2026: Neues Trial 'Vakron Sky Island'",
    es: "AION 2 Actualización — 15 de julio de 2026: nuevo juicio 'Vakron Sky Island'",
    ja: "AION 2 アップデート — 2026年7月15日：新トライアル「ヴァクロン・スカイアイランド」",
    "pt-br": "AION 2 Atualização — 15 de julho de 2026: novo Trial 'Vakron Sky Island'",
    ru: "AION 2 Обновление — 15 июля 2026: новое испытание «Vakron Sky Island»",
    ko: "AION 2 업데이트 — 2026년 7월 15일: 신규 트라이얼 '바크론 스카이 아일랜드'",
    "zh-hant": "AION 2 更新 — 2026年7月15日：新試煉「巴克隆空中島」",
  }, "https://aion2hub.com/updates"),
};

const trialSource2: ContentSource = {
  id: "aion2hub-chapter1-classes-2026-08-18",
  kind: "third-party", publisher: "AION2Hub",
  label: "AION 2 Chapter 1 — Content Guide & Trial Overview",
  url: "https://aion2hub.com/",
  publishedAt: "2026-07-10",
  retrievedAt: "2026-08-18",
  verifiedAt: "2026-08-18",
  localizations: localizations({
    "zh-hans": "AION 2 第一章——内容指南与试炼概览",
    en: "AION 2 Chapter 1 — Content Guide & Trial Overview",
    fr: "AION 2 Chapitre 1 — Guide de contenu et aperçu des procès",
    de: "AION 2 Kapitel 1 — Content-Guide & Trial-Übersicht",
    es: "AION 2 Capítulo 1 — guía de contenido y descripción general de juicios",
    ja: "AION 2 第1章 — コンテンツガイドとトライアル概要",
    "pt-br": "AION 2 Capítulo 1 — guia de conteúdo e visão geral de Trials",
    ru: "AION 2 Глава 1 — гайд по контенту и обзор испытаний",
    ko: "AION 2 챕터 1 — 콘텐츠 가이드 및 트라이얼 개요",
    "zh-hant": "AION 2 第一章——內容指南與試煉概覽",
  }, "https://aion2hub.com/"),
};

const trialSource3: ContentSource = {
  id: "plaync-kr-trial-2026-08-18",
  kind: "official", publisher: "NCSOFT",
  label: "AION 2 (KR) — 트라이얼: 바로크론 하늘 섬 안내",
  url: "https://aion2.plaync.com/ko-kr/board/notice",
  publishedAt: "2026-07-15",
  retrievedAt: "2026-08-18",
  verifiedAt: "2026-08-18",
  localizations: localizations({
    "zh-hans": "AION 2（韩服）— 试炼：巴克隆空中岛指南",
    en: "AION 2 (KR) — Trial: Vakron Sky Island Guide",
    fr: "AION 2 (KR) — Guide du procès : Vakron Sky Island",
    de: "AION 2 (KR) — Trial-Guide: Vakron Sky Island",
    es: "AION 2 (KR) — Guía del juicio: Vakron Sky Island",
    ja: "AION 2 (KR) — トライアル：ヴァクロン・スカイアイランドガイド",
    "pt-br": "AION 2 (KR) — Guia do Trial: Vakron Sky Island",
    ru: "AION 2 (KR) — Гайд испытания: Vakron Sky Island",
    ko: "AION 2 (KR) — 트라이얼: 바로크론 하늘 섬 안내",
    "zh-hant": "AION 2（韓服）— 試煉：巴克隆空中島指南",
  }, "https://aion2.plaync.com/ko-kr/board/notice"),
};

const trialHero: ContentHeroImage = {
  src: "https://blogfiles.ncsoft.net/news/af7330da-4ff6-4b58-aece-400e6061a3be.jpg",
  width: 1100, height: 605,
  credit: "NC Corporation",
  sourceUrl: "https://aion2.plaync.com/ko-kr/board/notice",
  rights: "linked-official-media",
  translations: {
    "zh-hans": { alt: "试炼系统指南配图", caption: "NC 官方配图；新试炼「巴克隆空中岛」于 7 月 15 日加入韩服，条目等级 4800。" },
    en: { alt: "Trial system guide image", caption: "Official NC artwork; the new Trial 'Vakron Sky Island' joined the KR service on July 15 with item level 4,800." },
    fr: { alt: "Image du guide des procès", caption: "Visuel officiel NC ; le nouveau procès « Vakron Sky Island » est arrivé sur le service KR le 15 juillet (niveau d'objet 4 800)." },
    de: { alt: "Trial-System-Guide-Bild", caption: "Offizielles NC-Artwork; das neue Trial 'Vakron Sky Island' kam am 15. Juli zum KR-Dienst (Gegenstandsstufe 4.800)." },
    es: { alt: "Imagen de la guía de juicios", caption: "Arte oficial de NC; el nuevo juicio 'Vakron Sky Island' llegó al servicio KR el 15 de julio (nivel de objeto 4.800)." },
    ja: { alt: "トライアルシステムガイド画像", caption: "NC公式アートワーク；新トライアル「ヴァクロン・スカイアイランド」が7月15日にKRサービスへ追加されました（アイテムレベル4800）。" },
    "pt-br": { alt: "Imagem do guia de Trials", caption: "Arte oficial da NC; o novo Trial 'Vakron Sky Island' chegou ao serviço KR em 15 de julho (item level 4.800)." },
    ru: { alt: "Изображение гайда по испытаниям", caption: "Официальный арт NC; новое испытание «Vakron Sky Island» добавлено на KR 15 июля (уровень предмета 4800)." },
    ko: { alt: "트라이얼 시스템 가이드 이미지", caption: "NC 공식 이미지입니다. 신규 트라이얼 '바크론 스카이 아일랜드'가 7월 15일 KR 서비스에 추가되었습니다 (아이템 레벨 4,800)." },
    "zh-hant": { alt: "試煉系統指南配圖", caption: "NC 官方配圖；新試煉「巴克隆空中島」於 7 月 15 日加入韓服，條目等級 4800。" },
  },
};

export const trendingAugust18Article2: ContentEntry = {
  section: "guides",
  slug: "aion-2-trial-guide-vakron-sky-island",
  schemaType: "Article",
  publishedAt: "2026-08-18",
  updatedAt: "2026-08-18",
  readingMinutes: 5,
  publication: publishedVerified,
  sources: [trialSource1, trialSource2, trialSource3],
  heroImage: trialHero,
  related: [
    { kind: "content", section: "guides", slug: "global-launch-dungeon-raid-size-changes" },
    { kind: "content", section: "news", slug: "aion-2-update-preview-new-dungeons-housing" },
    { kind: "content", section: "guides", slug: "aion-2-launch-classes-guide" },
  ],
  translations: {
    en: articleCopy(guideLabels, "en", 5, {
      eyebrow: "ENDGAME GUIDE",
      title: "Aion 2 Trial Guide: Vakron Sky Island, Difficulty & Weekly Rewards",
      description: "Aion 2's Trial mode is a scaled weekly challenge. Learn how Vakron Sky Island works — item level 4,800, difficulty 4-16, and the weekly Proof-of-Overcoming shop.",
      intro: "Trials are Aion 2's endgame challenge system — instanced content with scaling difficulty and weekly rewards. The newest Trial, Vakron Sky Island, arrived on the KR service on July 15, 2026, and gives the clearest picture yet of what late-game trials look like in Aion 2. This guide explains how Trials work, what Vakron Sky Island involves, and what global players should expect.",
      sourceNote: "Based on AION2Hub's July 15 update notes and NCSoft's official KR notice board. Trial mechanics reflect the latest confirmed state of the Korean service.",
      keywords: ["Aion 2 Trial", "Aion 2 Vakron Sky Island", "Aion 2 weekly challenge", "Aion 2 endgame Korea", "Aion 2 trial difficulty"],
      sections: [
        section("what", "What Are Trials in Aion 2", ["Trials are repeatable instanced challenges with selectable difficulty — the mode Aion 2 uses to scale its hardest PvE content for players who outgear standard expeditions and dungeons.", "Each Trial has an item level requirement and a difficulty range. Clear rates and completions reset on a weekly cadence, with rewards tied to a dedicated shop currency — the Proof of Overcoming."]),
        section("vakron", "Vakron Sky Island — The New Trial", ["Vakron Sky Island joined the KR service on July 15, 2026 with an item level of 4,800 and difficulty selectable between 4 and 16 — a wide ladder spanning late-game groups.", "The name and setting suggest a vertical, sky-island arena. Because difficulty scales, groups progress from learning the mechanics to pushing for higher clears over the season, which is how Trial progression works in Aion 2."]),
        section("rewards", "Weekly Rewards & the Proof-of-Overcoming Shop", ["Completing Trials grants weekly Proof-of-Overcoming currency, spent in a dedicated weekly shop. The shop carries progression items tailored to players working on late-game gear and transcendence.", "The weekly reset plus capped-but-generous currencies means regular clears are the intended loop — you are rewarded for weekly participation, not for one-and-done clears."]),
        section("global", "What Global Players Should Expect", ["Trials are not confirmed for the September 30 global launch content list yet; like most KR endgame systems, they are expected to reach the global build in the months after launch.", "For launch, focus on the core expedition-to-raid loop and treat Trials as the next tier of endgame to look forward to — if you enjoy scaling challenges, this is the mode to watch."]),
      ],
    }),
    "zh-hans": articleCopy(guideLabels, "zh-hans", 5, {
      eyebrow: "后期玩法指南",
      title: "Aion 2 试炼指南：巴克隆空中岛、难度与周常奖励",
      description: "Aion 2 的试炼模式是可扩展的周常挑战。了解巴克隆空中岛的运作方式——条目等级 4800、难度 4-16、以及周常「克服之证」商店。",
      intro: "试炼是 Aion 2 的后期挑战系统——带难度扩展与周常奖励的实例内容。最新试炼「巴克隆空中岛」于 2026 年 7 月 15 日登陆韩服，是迄今对 Aion 2 后期试炼形态最清晰的展现。本指南解释试炼的运作方式、巴克隆空中岛的内容构成，以及全球玩家的预期。",
      sourceNote: "基于 AION2Hub 7 月 15 日更新说明与 NCSoft 官方韩服公告板。试炼机制反映韩服最新确认状态。",
      keywords: ["Aion 2 试炼", "Aion 2 巴克隆空中岛", "Aion 2 周常挑战", "Aion 2 韩服后期", "Aion 2 试炼难度"],
      sections: [
        section("what", "Aion 2 中的试炼是什么", ["试炼是带可选难度的可重复实例挑战——Aion 2 用它为装备超越标准远征与副本的玩家扩展最难的 PvE 内容。", "每个试炼有物品等级要求与难度区间。通关率与通关进度按周重置，奖励与专属商店货币——「克服之证」挂钩。"]),
        section("vakron", "巴克隆空中岛——新试炼", ["巴克隆空中岛于 2026 年 7 月 15 日登陆韩服，物品等级 4800，难度可选 4 至 16——覆盖后期团体的宽梯子。", "名称与设定暗示了垂直方向的空中岛屿竞技场。由于难度可扩展，队伍从学习机制开始，随赛季推进挑战更高通关，这正是 Aion 2 中试炼进度的运作方式。"]),
        section("rewards", "周常奖励与「克服之证」商店", ["完成试炼可获得每周「克服之证」货币，用于专属周常商店。商店提供为后期装备与超越进度定制的养成物品。", "周重置加上有上限但慷慨的货币，意味着定期通关是预期循环——奖励每周参与，而非一次性通关。"]),
        section("global", "全球玩家的预期", ["试炼尚未确认纳入 9 月 30 日全球首发内容清单；与多数韩服后期系统一样，预计将在上线后数月内抵达全球版本。", "上线时请聚焦从远征到团本的核心循环，将试炼视为下一个值得期待的后期层级——如果你喜欢扩展挑战，这个模式值得关注。"]),
      ],
    }),
    ko: articleCopy(guideLabels, "ko", 5, {
      eyebrow: "엔드게임 가이드",
      title: "Aion 2 트라이얼 가이드: 바크론 스카이 아일랜드, 난이도와 주간 보상",
      description: "Aion 2의 트라이얼 모드는 확장형 주간 챌린지입니다. 바크론 스카이 아일랜드의 작동 방식 — 아이템 레벨 4,800, 난이도 4-16, 주간 '극복의 증표' 상점 — 을 알아보세요.",
      intro: "트라이얼은 Aion 2의 엔드게임 도전 시스템입니다 — 난이도 확장과 주간 보상이 있는 인스턴스 콘텐츠입니다. 최신 트라이얼 '바크론 스카이 아일랜드'는 2026년 7월 15일 KR 서비스에 추가되었으며, Aion 2 후반 트라이얼의 모습을 가장 또렷하게 보여줍니다. 이 가이드는 트라이얼의 작동 방식, 바크론 스카이 아일랜드의 내용, 글로벌 플레이어의 기대치를 설명합니다.",
      sourceNote: "AION2Hub의 7월 15일 업데이트 노트와 NCSoft 공식 KR 공지 게시판에 기반합니다. 트라이얼 메커니즘은 한국 서비스의 최신 확인 상태를 반영합니다.",
      keywords: ["Aion 2 트라이얼", "Aion 2 바크론 스카이 아일랜드", "Aion 2 주간 챌린지", "Aion 2 한국 엔드게임", "Aion 2 트라이얼 난이도"],
      sections: [
        section("what", "Aion 2의 트라이얼이란", ["트라이얼은 난이도를 선택할 수 있는 반복 가능한 인스턴스 챌린지입니다 — 표준 원정대와 던전을 넘어선 장비를 갖춘 플레이어를 위해 Aion 2가 가장 어려운 PvE 콘텐츠를 확장하는 방식입니다.", "각 트라이얼에는 아이템 레벨 요구치와 난이도 범위가 있습니다. 클리어율과 진행은 주간 주기로 초기화되며, 보상은 전용 상점 화폐인 '극복의 증표'와 연결됩니다."]),
        section("vakron", "바크론 스카이 아일랜드 — 새로운 트라이얼", ["바크론 스카이 아일랜드는 2026년 7월 15일 KR 서비스에 추가되었습니다 — 아이템 레벨 4,800, 난이도 4에서 16 사이에서 선택 가능한 넓은 사다리입니다.", "이름과 설정은 수직적 스카이 아일랜드 아레나를 시사합니다. 난이도가 확장되므로 파티는 메커닉 학습부터 시작해 시즌을 거치며 더 높은 클리어를 노립니다 — 이것이 Aion 2 트라이얼 진행의 작동 방식입니다."]),
        section("rewards", "주간 보상과 '극복의 증표' 상점", ["트라이얼 완료 시 주간 '극복의 증표' 화폐를 얻으며, 전용 주간 상점에서 사용합니다. 상점은 후반 장비와 초월 진행을 위한 성장 아이템을 제공합니다.", "주간 초기화와 상한 있지만 넉넉한 화폐는 정기 클리어가 의도된 루프임을 의미합니다 — 일회성 클리어가 아닌 주간 참여를 보상합니다."]),
        section("global", "글로벌 플레이어가 기대할 것", ["트라이얼은 9월 30일 글로벌 출시 콘텐츠 목록에 아직 확인되지 않았습니다. 대부분의 KR 엔드게임 시스템과 마찬가지로 출시 후 수개월 내에 글로벌 빌드에 도착할 것으로 예상됩니다.", "출시 시에는 원정대-레이드 핵심 루프에 집중하고, 트라이얼은 다음으로 기대할 엔드게임 단계로 여기세요 — 확장형 챌린지를 좋아한다면 주목할 모드입니다."]),
      ],
    }),
    ja: articleCopy(guideLabels, "ja", 5, {
      eyebrow: "エンドゲームガイド",
      title: "Aion 2 トライアルガイド：ヴァクロン・スカイアイランド、難易度と週間報酬",
      description: "Aion 2 のトライアルモードは拡張型の週間チャレンジです。ヴァクロン・スカイアイランドの仕組み — アイテムレベル4800、難易度4-16、週間「克服の証」ショップ — を学びましょう。",
      intro: "トライアルは Aion 2 のエンドゲームチャレンジシステムです — 難易度スケーリングと週間報酬を持つインスタンスコンテンツ。最新のトライアル「ヴァクロン・スカイアイランド」は2026年7月15日に KR サービスへ追加され、Aion 2 の後半トライアルの姿を最も明確に示しています。このガイドはトライアルの仕組み、ヴァクロン・スカイアイランドの内容、グローバルプレイヤーの期待値を説明します。",
      sourceNote: "AION2Hub の7月15日アップデートノートと NCSoft 公式 KR 掲示板に基づきます。トライアルメカニクスは韓国サービスの最新確認状態を反映しています。",
      keywords: ["Aion 2 トライアル", "Aion 2 ヴァクロン・スカイアイランド", "Aion 2 週間チャレンジ", "Aion 2 韓国エンドゲーム", "Aion 2 トライアル難易度"],
      sections: [
        section("what", "Aion 2 のトライアルとは", ["トライアルは難易度を選択できる反復可能なインスタンスチャレンジです — 標準の遠征やダンジョンを超えた装備を持つプレイヤーのために、Aion 2 が最も難しい PvE コンテンツをスケールさせる方式です。", "各トライアルにはアイテムレベル要件と難易度レンジがあります。クリア率と進行は週間サイクルでリセットされ、報酬は専用ショップ通貨である「克服の証」に紐づきます。"]),
        section("vakron", "ヴァクロン・スカイアイランド — 新トライアル", ["ヴァクロン・スカイアイランドは2026年7月15日に KR サービスへ追加されました — アイテムレベル4800、難易度は4から16の間で選択可能な広いラダーです。", "名前と設定は垂直方向のスカイアイランドアリーナを示唆します。難易度がスケールするため、パーティはメカニクス習得から始め、シーズンを通じてより高いクリアを目指します — これが Aion 2 のトライアル進行の仕組みです。"]),
        section("rewards", "週間報酬と「克服の証」ショップ", ["トライアル完了で週間の「克服の証」通貨を獲得し、専用週間ショップで使用します。ショップは後半装備と超越進行向けの育成アイテムを提供します。", "週間リセットと上限付きだが寛大な通貨は、定期的なクリアが意図されたループであることを意味します — 一度きりのクリアではなく週間参加が報われます。"]),
        section("global", "グローバルプレイヤーが期待できること", ["トライアルは9月30日のグローバルローンチコンテンツリストには未確認です。ほとんどの KR エンドゲームシステムと同様、ローンチ後数ヶ月以内にグローバルビルドへ到達すると予想されます。", "ローンチ時は遠征からレイドへのコアループに集中し、トライアルは次に楽しみなエンドゲーム層として見てください — スケーリングチャレンジが好きなら注目のモードです。"]),
      ],
    }),
    fr: articleCopy(guideLabels, "fr", 5, {
      eyebrow: "GUIDE ENDGAME",
      title: "Guide des procès d'Aion 2 : Vakron Sky Island, difficulté et récompenses hebdomadaires",
      description: "Le mode Procès d'Aion 2 est un défi hebdomadaire évolutif. Découvrez Vakron Sky Island — niveau d'objet 4 800, difficulté 4-16 et boutique hebdomadaire.",
      intro: "Les procès sont le système de défi endgame d'Aion 2 — contenu instancié à difficulté évolutive. Vakron Sky Island est arrivé sur le service KR le 15 juillet 2026.",
      sourceNote: "Basé sur les notes d'AION2Hub du 15 juillet et le tableau officiel NCSoft KR.",
      keywords: ["Aion 2 procès", "Aion 2 Vakron Sky Island", "Aion 2 défi hebdomadaire", "Aion 2 endgame"],
      sections: [
        section("what", "Les procès dans Aion 2", ["Défis instanciés à difficulté sélectionnable, conçus pour les joueurs au-delà des expéditions standards, avec reset hebdomadaire et monnaie dédiée."]),
        section("vakron", "Vakron Sky Island", ["Ajouté le 15 juillet 2026 : niveau d'objet 4 800, difficulté 4-16. Un arène verticale type îles célestes, avec progression par difficulté."]),
        section("rewards", "Récompenses hebdomadaires", ["Monnaie semainale 'Preuve de dépassement' dépensée dans une boutique dédiée pour des objets de progression tardive."]),
        section("global", "Attentes pour le global", ["Non confirmé pour le 30 septembre ; attendu dans les mois suivant le lancement global."]),
      ],
    }),
    de: articleCopy(guideLabels, "de", 5, {
      eyebrow: "ENDGAME-GUIDE",
      title: "Aion 2 Trial-Guide: Vakron Sky Island, Schwierigkeit & Wochenbelohnungen",
      description: "Aion 2s Trial-Modus ist eine skalierte Wochen-Herausforderung. Erfahren Sie, wie Vakron Sky Island funktioniert — Gegenstandsstufe 4.800, Schwierigkeit 4-16 und der wöchentliche Shop.",
      intro: "Trials sind Aion 2s Endgame-Herausforderungssystem — Instanzinhalte mit skalierender Schwierigkeit. Vakron Sky Island kam am 15. Juli 2026 zum KR-Dienst.",
      sourceNote: "Basierend auf AION2Hub-Notizen vom 15. Juli und dem offiziellen NCSoft-KR-Board.",
      keywords: ["Aion 2 Trial", "Aion 2 Vakron Sky Island", "Aion 2 Wochen-Herausforderung", "Aion 2 Endgame"],
      sections: [
        section("what", "Was Trials in Aion 2 sind", ["Instanz-Herausforderungen mit wählbarer Schwierigkeit für Spieler jenseits der Standard-Expeditionen, mit wöchentlichem Reset und eigener Währung."]),
        section("vakron", "Vakron Sky Island", ["Seit 15. Juli 2026: Gegenstandsstufe 4.800, Schwierigkeit 4-16. Eine vertikale Himmelsinsel-Arena mit Fortschritt über die Schwierigkeitsgrade."]),
        section("rewards", "Wochenbelohnungen", ["Wöchentliche Währung 'Beweis der Überwindung' für einen eigenen Shop mit spätspielbezogenen Fortschrittsgegenständen."]),
        section("global", "Erwartungen für Global", ["Nicht für den 30. September bestätigt; in den Monaten nach dem globalen Launch erwartet."]),
      ],
    }),
    es: articleCopy(guideLabels, "es", 5, {
      eyebrow: "GUÍA DE ENDGAME",
      title: "Guía de los juicios de Aion 2: Vakron Sky Island, dificultad y recompensas semanales",
      description: "El modo Juicio de Aion 2 es un desafío semanal escalable. Aprende cómo funciona Vakron Sky Island — nivel de objeto 4.800, dificultad 4-16 y la tienda semanal.",
      intro: "Los juicios son el sistema de desafío endgame de Aion 2 — contenido instanciado con dificultad escalable. Vakron Sky Island llegó al servicio KR el 15 de julio de 2026.",
      sourceNote: "Basado en las notas de AION2Hub del 15 de julio y el tablón oficial de NCSoft KR.",
      keywords: ["Aion 2 juicios", "Aion 2 Vakron Sky Island", "Aion 2 desafío semanal", "Aion 2 endgame"],
      sections: [
        section("what", "Qué son los juicios en Aion 2", ["Desafíos instanciados con dificultad seleccionable para jugadores más allá de las expediciones estándar, con reinicio semanal y moneda dedicada."]),
        section("vakron", "Vakron Sky Island", ["Añadido el 15 de julio de 2026: nivel de objeto 4.800, dificultad 4-16. Una arena vertical de islas celestes con progresión por dificultad."]),
        section("rewards", "Recompensas semanales", ["Moneda semanal 'Prueba de Superación' para una tienda dedicada con objetos de progresión tardía."]),
        section("global", "Qué esperar para el global", ["No confirmado para el 30 de septiembre; esperado en los meses posteriores al lanzamiento global."]),
      ],
    }),
    "pt-br": articleCopy(guideLabels, "pt-br", 5, {
      eyebrow: "GUIA DE ENDGAME",
      title: "Guia de Trials de Aion 2: Vakron Sky Island, dificuldade e recompensas semanais",
      description: "O modo Trial de Aion 2 é um desafio semanal escalável. Saiba como funciona Vakron Sky Island — item level 4.800, dificuldade 4-16 e a loja semanal.",
      intro: "Trials são o sistema de desafio endgame de Aion 2 — conteúdo instanciado com dificuldade escalável. Vakron Sky Island chegou ao serviço KR em 15 de julho de 2026.",
      sourceNote: "Baseado nas notas da AION2Hub de 15 de julho e no quadro oficial da NCSoft KR.",
      keywords: ["Aion 2 Trials", "Aion 2 Vakron Sky Island", "Aion 2 desafio semanal", "Aion 2 endgame"],
      sections: [
        section("what", "O que são Trials em Aion 2", ["Desafios instanciados com dificuldade selecionável para jogadores além das expedições padrão, com reset semanal e moeda dedicada."]),
        section("vakron", "Vakron Sky Island", ["Adicionado em 15 de julho de 2026: item level 4.800, dificuldade 4-16. Uma arena vertical de ilhas celestes com progressão por dificuldade."]),
        section("rewards", "Recompensas semanais", ["Moeda semanal 'Prova de Superação' para uma loja dedicada com itens de progressão tardia."]),
        section("global", "O que esperar no global", ["Não confirmado para 30 de setembro; esperado nos meses após o lançamento global."]),
      ],
    }),
    ru: articleCopy(guideLabels, "ru", 5, {
      eyebrow: "ЭНДГЕЙМ-ГАЙД",
      title: "Гайд по испытаниям Aion 2: Vakron Sky Island, сложность и еженедельные награды",
      description: "Режим испытаний Aion 2 — масштабируемое еженедельное испытание. Узнайте, как работает Vakron Sky Island — уровень предмета 4800, сложность 4-16 и еженедельный магазин.",
      intro: "Испытания — система эндгейм-челленджей Aion 2: инстанс-контент с масштабируемой сложностью. Vakron Sky Island появилась на KR 15 июля 2026 года.",
      sourceNote: "На основе записей AION2Hub от 15 июля и официальной доски NCSoft KR.",
      keywords: ["Aion 2 испытания", "Aion 2 Vakron Sky Island", "Aion 2 еженедельный челлендж", "Aion 2 эндгейм"],
      sections: [
        section("what", "Что такое испытания в Aion 2", ["Инстанс-челленджи с выбираемой сложностью для игроков за пределами стандартных экспедиций, с еженедельным сбросом и особой валютой."]),
        section("vakron", "Vakron Sky Island", ["Добавлена 15 июля 2026: уровень предмета 4800, сложность 4-16. Вертикальная арена небесных островов с прогрессией по сложности."]),
        section("rewards", "Еженедельные награды", ["Еженедельная валюта «Доказательство преодоления» для особого магазина с предметами позднего прогресса."]),
        section("global", "Ожидания для глобала", ["Не подтверждено для 30 сентября; ожидается в месяцы после глобального запуска."]),
      ],
    }),
    "zh-hant": articleCopy(guideLabels, "zh-hant", 5, {
      eyebrow: "後期玩法指南",
      title: "Aion 2 試煉指南：巴克隆空中島、難度與週常獎勵",
      description: "Aion 2 的試煉模式是可擴展的週常挑戰。了解巴克隆空中島的運作方式——條目等級 4800、難度 4-16、以及週常「克服之證」商店。",
      intro: "試煉是 Aion 2 的後期挑戰系統——帶難度擴展與週常獎勵的實例內容。最新試煉「巴克隆空中島」於 2026 年 7 月 15 日登陸韓服，是迄今對 Aion 2 後期試煉形態最清晰的展現。本指南解釋試煉的運作方式、巴克隆空中島的內容構成，以及全球玩家的預期。",
      sourceNote: "基於 AION2Hub 7 月 15 日更新說明與 NCSoft 官方韓服公告板。試煉機制反映韓服最新確認狀態。",
      keywords: ["Aion 2 試煉", "Aion 2 巴克隆空中島", "Aion 2 週常挑戰", "Aion 2 韓服後期", "Aion 2 試煉難度"],
      sections: [
        section("what", "Aion 2 中的試煉是什麼", ["試煉是帶可選難度的可重複實例挑戰——Aion 2 用它為裝備超越標準遠征與副本的玩家擴展最難的 PvE 內容。", "每個試煉有物品等級要求與難度區間。通關率與通關進度按週重置，獎勵與專屬商店貨幣——「克服之證」掛鉤。"]),
        section("vakron", "巴克隆空中島——新試煉", ["巴克隆空中島於 2026 年 7 月 15 日登陸韓服，物品等級 4800，難度可選 4 至 16——覆蓋後期團體的寬梯子。", "名稱與設定暗示了垂直方向的空中島嶼競技場。由於難度可擴展，隊伍從學習機制開始，隨賽季推進挑戰更高通關，這正是 Aion 2 中試煉進度的運作方式。"]),
        section("rewards", "週常獎勵與「克服之證」商店", ["完成試煉可獲得每週「克服之證」貨幣，用於專屬週常商店。商店提供為後期裝備與超越進度定制的養成物品。", "週重置加上有上限但慷慨的貨幣，意味著定期通關是預期循環——獎勵每週參與，而非一次性通關。"]),
        section("global", "全球玩家的預期", ["試煉尚未確認納入 9 月 30 日全球首發內容清單；與多數韓服後期系統一樣，預計將在上線後數月內抵達全球版本。", "上線時請聚焦從遠征到團本的核心循環，將試煉視為下一個值得期待的後期層級——如果你喜歡擴展挑戰，這個模式值得關注。"]),
      ],
    }),
  },
};