import { articleCopy, guideLabels, localizations, publishedVerified, section } from "./trending-august-18-shared";
import type { ContentEntry, ContentHeroImage, ContentSource } from "./content-registry";

/* ARTICLE 5 — Brokerage / trade market guide */

const marketSource1: ContentSource = {
  id: "aion2hub-market-notes-2026-08-18",
  kind: "third-party", publisher: "AION2Hub",
  label: "AION 2 Brokerage & Economy Patch Notes (2025-2026)",
  url: "https://aion2hub.com/updates",
  publishedAt: "2026-03-25",
  retrievedAt: "2026-08-18",
  verifiedAt: "2026-08-18",
  localizations: localizations({
    "zh-hans": "AION 2 拍卖行与经济补丁说明（2025-2026）",
    en: "AION 2 Brokerage & Economy Patch Notes (2025-2026)",
    fr: "AION 2 Notes de patch courtage et économie (2025-2026)",
    de: "AION 2 Brokerage- & Wirtschafts-Patchnotes (2025-2026)",
    es: "AION 2 Notas del parche de corretaje y economía (2025-2026)",
    ja: "AION 2 ブローカー・経済パッチノート（2025-2026）",
    "pt-br": "AION 2 Notas de patch de corretagem e economia (2025-2026)",
    ru: "AION 2 Патч-ноуты брокеража и экономики (2025-2026)",
    ko: "AION 2 경매장·경제 패치 노트 (2025-2026)",
    "zh-hant": "AION 2 拍賣行與經濟補丁說明（2025-2026）",
  }, "https://aion2hub.com/updates"),
};

const marketSource2: ContentSource = {
  id: "aion2hub-quna-kinah-2026-08-18",
  kind: "third-party", publisher: "AION2Hub",
  label: "AION 2 Global — Quna/Kinah Exchange & Monetization Overview",
  url: "https://aion2hub.com/",
  publishedAt: "2026-07-10",
  retrievedAt: "2026-08-18",
  verifiedAt: "2026-08-18",
  localizations: localizations({
    "zh-hans": "AION 2 全球版——Quna/基纳兑换与货币化概览",
    en: "AION 2 Global — Quna/Kinah Exchange & Monetization Overview",
    fr: "AION 2 Global — aperçu de l'échange Quna/Kinah et de la monétisation",
    de: "AION 2 Global — Quna/Kinah-Umtausch & Monetarisierungsübersicht",
    es: "AION 2 Global — descripción general del intercambio Quna/Kinah y monetización",
    ja: "AION 2 グローバル — Quna/キナー交換とマネタイズ概要",
    "pt-br": "AION 2 Global — visão geral de troca Quna/Kinah e monetização",
    ru: "AION 2 Global — обзор обмена Quna/Kinah и монетизации",
    ko: "AION 2 글로벌 — 구나/키나 거래 및 수익화 개요",
    "zh-hant": "AION 2 全球版——Quna/基納兌換與貨幣化概覽",
  }, "https://aion2hub.com/"),
};

const marketSource3: ContentSource = {
  id: "plaync-kr-economy-2026-08-18",
  kind: "official", publisher: "NCSOFT",
  label: "AION 2 (KR) — 거래/경제 시스템 안내",
  url: "https://aion2.plaync.com/ko-kr/board/notice",
  publishedAt: "2026-03-25",
  retrievedAt: "2026-08-18",
  verifiedAt: "2026-08-18",
  localizations: localizations({
    "zh-hans": "AION 2（韩服）— 交易/经济系统说明",
    en: "AION 2 (KR) — Trade & Economy System Guide",
    fr: "AION 2 (KR) — Guide du système de commerce et d'économie",
    de: "AION 2 (KR) — Handels- & Wirtschaftssystem-Guide",
    es: "AION 2 (KR) — Guía del sistema de comercio y economía",
    ja: "AION 2 (KR) — 取引・経済システムガイド",
    "pt-br": "AION 2 (KR) — Guia do sistema de comércio e economia",
    ru: "AION 2 (KR) — Гайд по торговле и экономике",
    ko: "AION 2 (KR) — 거래/경제 시스템 안내",
    "zh-hant": "AION 2（韓服）— 交易/經濟系統說明",
  }, "https://aion2.plaync.com/ko-kr/board/notice"),
};

const marketHero: ContentHeroImage = {
  src: "https://blogfiles.ncsoft.net/news/af7330da-4ff6-4b58-aece-400e6061a3be.jpg",
  width: 1100, height: 605,
  credit: "NC Corporation",
  sourceUrl: "https://aion2.plaync.com/ko-kr/board/notice",
  rights: "linked-official-media",
  translations: {
    "zh-hans": { alt: "拍卖行与市场指南配图", caption: "NC 官方配图；拍卖行涵盖跨服世界拍卖、灵魂绑定基纳与会员门控等机制。" },
    en: { alt: "Brokerage and market guide image", caption: "Official NC artwork; the brokerage spans cross-server trading, Soul-bound Kinah, and membership-gated features." },
    fr: { alt: "Image du guide du courtage et du marché", caption: "Visuel officiel NC ; le courtage couvre le commerce inter-serveurs, la Kinah liée à l'âme et des fonctions réservées aux membres." },
    de: { alt: "Brokerage- und Markt-Guide-Bild", caption: "Offizielles NC-Artwork; die Brokerage umfasst serverseitigen Handel, seelengebundenes Kinah und mitgliedschaftsgebundene Funktionen." },
    es: { alt: "Imagen de la guía de corretaje y mercado", caption: "Arte oficial de NC; el corretaje incluye comercio entre servidores, Kinah ligada al alma y funciones exclusivas para miembros." },
    ja: { alt: "ブローカー・マーケットガイド画像", caption: "NC公式アートワーク；ブローカーはクロスサーバー取引、魂拘束キナー、メンバー限定機能をカバーします。" },
    "pt-br": { alt: "Imagem do guia de corretagem e mercado", caption: "Arte oficial da NC; a corretagem abrange comércio entre servidores, Kinah ligada à alma e recursos exclusivos para membros." },
    ru: { alt: "Изображение гайда по брокеражу и рынку", caption: "Официальный арт NC; брокераж включает межсерверную торговлю, связанную с душой Кину и функции для подписчиков." },
    ko: { alt: "경매장·시장 가이드 이미지", caption: "NC 공식 이미지입니다. 경매장은 서버 간 거래, 영혼 귀속 키나, 멤버십 전용 기능을 포함합니다." },
    "zh-hant": { alt: "拍賣行與市場指南配圖", caption: "NC 官方配圖；拍賣行涵蓋跨服世界拍賣、靈魂綁定基納與會員門控等機制。" },
  },
};

export const trendingAugust18Article5: ContentEntry = {
  section: "guides",
  slug: "aion-2-brokerage-market-guide",
  schemaType: "Article",
  publishedAt: "2026-08-18",
  updatedAt: "2026-08-18",
  readingMinutes: 6,
  publication: publishedVerified,
  sources: [marketSource1, marketSource2, marketSource3],
  heroImage: marketHero,
  related: [
    { kind: "content", section: "news", slug: "global-quna-kinah-exchange-p2w-changes" },
    { kind: "content", section: "news", slug: "aion-2-founders-packs-30-day-membership" },
    { kind: "content", section: "guides", slug: "aion-2-housing-system-preview" },
  ],
  translations: {
    en: articleCopy(guideLabels, "en", 6, {
      eyebrow: "ECONOMY GUIDE",
      title: "Aion 2 Brokerage Guide: Auction House, Soul-Bound Kinah & the Global Market",
      description: "Aion 2's brokerage (auction house) is the heart of its player economy. Learn how listings work, the Kinah vs Soul-bound Kinah split, membership-gated features, and what global players should expect.",
      intro: "Every MMO economy needs a marketplace, and in Aion 2 that role falls to the brokerage. Between cross-server trading, the Kinah/Soul-bound Kinah split, and membership gates added to fight bots, navigating the market takes a little knowledge. This guide breaks down how the brokerage works, what the currency system means for your wallet, and what the global version is likely to copy.",
      sourceNote: "Based on AION2Hub's economy and patch notes (March-December 2026 cycle), the official global monetization overview, and NCSoft's KR trade system notices.",
      keywords: ["Aion 2 auction house", "Aion 2 brokerage", "Aion 2 Kinah", "Aion 2 Soul-bound Kinah", "Aion 2 economy"],
      sections: [
        section("basics", "How the Brokerage Works", ["The brokerage is Aion 2's player-to-player marketplace: list items for other players to buy, bid or buy out, and collect proceeds in Kinah. It covers gear, consumables, materials, and more.", "The system has grown careful anti-bot features over time — brokerage functions were gated to members at one point, and hunting-Kinah caps were introduced to choke farming bots. Expect sensible listing limits rather than an open free-for-all."]),
        section("currency", "Kinah vs Soul-bound Kinah", ["A March 2026 update split Kinah into two forms: spendable Kinah and Soul-bound Kinah (bound to your character). Soul-bound Kinah comes from certain sources and cannot be freely moved — important when you plan sales and purchases.", "Some shop items — like the pet auto-loot ticket — are explicitly sellable for Soul-bound Kinah, giving players a route to trade purchased convenience back into the economy. Knowing which currency an item buys with is half the skill of using the market."]),
        section("cross-server", "Cross-Server Trading & Living Market", ["A December 2025 update introduced a cross-server World Brokerage, letting players buy and sell beyond their own server — a major step for market liquidity, especially for niche items and late-game materials.", "For global players, a living market matters most at launch: five server regions means liquidity is thin early. Cross-server trading, if it arrives on the global build, will make the economy dramatically more usable from day one."]),
        section("global", "What the Global Version Should Copy", ["NCSoft's official global monetization plan confirmed the Quna-backed shop economy with exchange systems. The global version is expected to carry the same core brokerage mechanics as KR, delivered with launch-appropriate tuning.", "Practical advice: learn the market early. At launch, early birds who understand listing windows, currency splits, and cross-server opportunities can fund their progression more efficiently than players who ignore the economy entirely."]),
      ],
    }),
    "zh-hans": articleCopy(guideLabels, "zh-hans", 6, {
      eyebrow: "经济指南",
      title: "Aion 2 拍卖行指南：拍卖行、灵魂绑定基纳与全球市场",
      description: "Aion 2 的拍卖行（brokerage）是玩家经济的核心。了解上架机制、基纳与灵魂绑定基纳的区分、会员门控功能，以及全球玩家的预期。",
      intro: "每个 MMO 经济都需要市场，在 Aion 2 中这一角色由拍卖行承担。从跨服交易、基纳/灵魂绑定基纳拆分，到为反机器人加入的会员门控，在这片市场里游刃有余需要一点知识。本指南拆解拍卖行的运作方式、货币体系对你的钱包意味着什么，以及全球版可能复制什么。",
      sourceNote: "基于 AION2Hub 的经济与补丁说明（2026 年 3-12 月周期）、官方全球货币化概览及 NCSoft 韩服交易系统公告。",
      keywords: ["Aion 2 拍卖行", "Aion 2 交易所", "Aion 2 基纳", "Aion 2 灵魂绑定基纳", "Aion 2 经济"],
      sections: [
        section("basics", "拍卖行如何运作", ["拍卖行是 Aion 2 的玩家间市场：上架物品供其他玩家购买、竞标或一口价，以基纳收款。覆盖装备、消耗品、材料等。", "该系统随时间加入了谨慎的反机器人功能——拍卖功能曾一度对会员门控，并引入了狩猎基纳上限以抑制刷怪机器人。预期合理的上架限制，而非完全开放的自由市场。"]),
        section("currency", "基纳与灵魂绑定基纳", ["2026 年 3 月更新将基纳拆分为两种形态：可流通基纳与灵魂绑定基纳（绑定角色）。灵魂绑定基纳来自特定来源，不能随意转移——规划交易时很重要。", "部分商店物品——如宠物自动拾取券——明确可以灵魂绑定基纳出售，为玩家提供将购买的便利再投入经济的途径。了解物品以何种货币购买是使用市场的一半技巧。"]),
        section("cross-server", "跨服交易与活跃市场", ["2025 年 12 月更新引入了跨服世界拍卖行，让玩家可以超越本服买卖——这是市场流动性的重大一步，尤其对冷门物品与后期材料。", "对全球玩家而言，活跃市场在上线时最重要：五个服务器区域意味着初期流动性薄弱。如果跨服交易抵达全球版本，将从上线第一天起极大提升经济可用性。"]),
        section("global", "全球版应复制什么", ["NCSoft 的官方全球货币化计划确认了以 Quna 为后盾的商店经济与兑换系统。全球版预计将沿用与韩服相同的核心拍卖机制，并以上线适配的调校交付。", "实用建议：尽早了解市场。上线时，理解上架窗口、货币拆分与跨服机会的先行者能比完全忽视经济的玩家更高效地支撑养成。"]),
      ],
    }),
    ko: articleCopy(guideLabels, "ko", 6, {
      eyebrow: "경제 가이드",
      title: "Aion 2 경매장 가이드: 거래소, 영혼 귀속 키나와 글로벌 시장",
      description: "Aion 2의 경매장(브로커리지)은 플레이어 경제의 핵심입니다. 등록 메커니즘, 키나와 영혼 귀속 키나의 구분, 멤버십 전용 기능, 글로벌 플레이어의 기대치를 알아보세요.",
      intro: "모든 MMO 경제에는 시장이 필요하며, Aion 2에서는 그 역할을 경매장이 맡습니다. 서버 간 거래, 키나/영혼 귀속 키나 분리, 봇 방지를 위한 멤버십 게이트까지, 시장을 헤쳐 나가려면 약간의 지식이 필요합니다. 이 가이드는 경매장의 작동 방식, 통화 시스템이 지갑에 미치는 의미, 글로벌 버전이 무엇을 복사할지 설명합니다.",
      sourceNote: "AION2Hub의 경제·패치 노트(2026년 3-12월 주기), 공식 글로벌 수익화 개요, NCSoft KR 거래 시스템 공지에 기반합니다.",
      keywords: ["Aion 2 경매장", "Aion 2 거래소", "Aion 2 키나", "Aion 2 영혼 귀속 키나", "Aion 2 경제"],
      sections: [
        section("basics", "경매장 작동 방식", ["경매장은 Aion 2의 플레이어 간 시장입니다: 아이템을 등록해 다른 플레이어가 사거나 입찰·즉시 구매하고 수익을 키나로 받습니다. 장비, 소모품, 재료 등을 아우릅니다.", "시스템은 시간이 지나며 신중한 안티봇 기능을 갖추었습니다 — 경매 기능은 한때 멤버십 전용이었고, 파밍 봇을 막기 위해 사냥 키나 상한이 도입되었습니다. 완전한 자유방임 대신 합리적인 등록 제한을 기대하세요."]),
        section("currency", "키나 vs 영혼 귀속 키나", ["2026년 3월 업데이트는 키나를 두 형태로 분리했습니다: 사용 가능한 키나와 영혼 귀속 키나(캐릭터에 귀속). 영혼 귀속 키나는 특정 출처에서 나오며 자유롭게 이동할 수 없습니다 — 매매 계획 시 중요합니다.", "일부 상점 아이템 — 펫 자동 루팅 티켓처럼 — 은 영혼 귀속 키나로 판매할 수 있어, 구매한 편의를 다시 경제로 돌리는 경로를 제공합니다. 아이템이 어떤 화폐로 구매되는지 아는 것이 시장 사용의 절반입니다."]),
        section("cross-server", "서버 간 거래와 살아있는 시장", ["2025년 12월 업데이트는 서버 간 세계 경매장을 도입해 플레이어가 자기 서버를 넘어 거래할 수 있게 했습니다 — 시장 유동성, 특히 희소 아이템과 후반 재료에 큰 진전입니다.", "글로벌 플레이어에게 살아있는 시장은 출시 시 가장 중요합니다: 5개 서버 지역은 초기 유동성이 얇다는 뜻입니다. 서버 간 거래가 글로벌 빌드에 도착한다면 첫날부터 경제가 훨씬 유용해집니다."]),
        section("global", "글로벌 버전이 복사할 것", ["NCSoft의 공식 글로벌 수익화 계획은 Quna 기반 상점 경제와 환전 시스템을 확인했습니다. 글로벌 버전은 출시에 맞춘 튜닝과 함께 KR과 동일한 핵심 경매장 메커니즘을 가져갈 것으로 예상됩니다.", "실용적 조언: 시장을 일찍 배우세요. 출시 시 등록 시점, 통화 분리, 서버 간 기회를 이해하는 얼리버드는 경제를 무시하는 플레이어보다 효율적으로 성장을 지원할 수 있습니다."]),
      ],
    }),
    ja: articleCopy(guideLabels, "ja", 6, {
      eyebrow: "経済ガイド",
      title: "Aion 2 ブローカーガイド：オークションハウス、魂拘束キナーとグローバル市場",
      description: "Aion 2 のブローカー（オークションハウス）はプレイヤー経済の中心です。出品の仕組み、キナーと魂拘束キナーの区分、メンバーシップ限定機能、グローバルプレイヤーの期待値を解説します。",
      intro: "すべての MMO 経済にはマーケットプレイスが必要であり、Aion 2 ではその役割をブローカーが担います。クロスサーバー取引、キナー/魂拘束キナー分割、ボット対策のメンバーシップゲートまで、市場を渡り歩くには少しの知識が要ります。このガイドはブローカーの仕組み、通貨システムがあなたの財布に与える意味、グローバル版が何をコピーするかを説明します。",
      sourceNote: "AION2Hub の経済・パッチノート（2026年3-12月サイクル）、公式グローバル収益化概要、NCSoft KR 取引システム通知に基づきます。",
      keywords: ["Aion 2 オークションハウス", "Aion 2 ブローカー", "Aion 2 キナー", "Aion 2 魂拘束キナー", "Aion 2 経済"],
      sections: [
        section("basics", "ブローカーの仕組み", ["ブローカーは Aion 2 のプレイヤー間マーケットです：アイテムを出品し、他のプレイヤーが購入・入札・即決価格で支払い、収益をキナーで受け取ります。装備、消耗品、素材などをカバーします。", "このシステムは時間とともに慎重なアンチボット機能を備えました — ブローカー機能は一時メンバーシップ限定となり、ファーミングボットを絞るため狩りキナー上限が導入されました。完全な自由市場ではなく、合理的な出品制限を期待してください。"]),
        section("currency", "キナー vs 魂拘束キナー", ["2026年3月のアップデートはキナーを2形態に分けました：使用可能なキナーと魂拘束キナー（キャラクターに拘束）。魂拘束キナーは特定の出所に由来し、自由に移動できません — 売買計画に重要です。", "一部のショップアイテム — ペット自動ルートチケットなど — は魂拘束キナーで売却可能と明記されており、購入した利便性を経済へ戻す経路を提供します。アイテムがどの通貨で購入されるかを知ることは、市場利用の半分のスキルです。"]),
        section("cross-server", "クロスサーバー取引と活発な市場", ["2025年12月のアップデートはクロスサーバー世界ブローカーを導入し、プレイヤーが自サーバーを越えて売買できるようにしました — 特にニッチアイテムと後半素材の市場流動性にとって大きな前進です。", "グローバルプレイヤーにとって、活発な市場はローンチ時に最も重要です：5サーバーリージョンは初期流動性が薄いことを意味します。クロスサーバー取引がグローバルビルドに届けば、初日から経済の使い勝手が劇的に向上します。"]),
        section("global", "グローバル版がコピーすべきもの", ["NCSoft の公式グローバル収益化プランは、Quna 基盤のショップ経済と交換システムを確認しました。グローバル版はローンチ向け調整とともに KR と同じコアブローカーメカニクスを引き継ぐと予想されます。", "実用的な助言：市場を早く学びましょう。ローンチ時、出品タイミング、通貨分割、クロスサーバーの機会を理解するアーリーバードは、経済を無視するプレイヤーより効率的に育成を支えられます。"]),
      ],
    }),
    fr: articleCopy(guideLabels, "fr", 6, {
      eyebrow: "GUIDE ÉCONOMIE",
      title: "Guide du courtage d'Aion 2 : hôtel des ventes, Kinah liée à l'âme et marché global",
      description: "Le courtage (hôtel des ventes) d'Aion 2 est le cœur de l'économie joueur. Fonctionnement, Kinah et Kinah liée à l'âme, fonctions réservées aux membres et attentes pour le global.",
      intro: "Le courtage est le marché joueur-à-joueur d'Aion 2. Trade inter-serveurs, scission de la Kinah et anti-bot en font un système à connaître.",
      sourceNote: "Basé sur les notes d'AION2Hub, l'aperçu officiel de monétisation mondiale et les avis de système NCSoft KR.",
      keywords: ["Aion 2 hôtel des ventes", "Aion 2 courtage", "Aion 2 Kinah", "Aion 2 économie"],
      sections: [
        section("basics", "Fonctionnement du courtage", ["Marché joueur : enchères, achats directs, gains en Kinah. Fonctions anti-bot et limites d'annonces au fil des patches."]),
        section("currency", "Kinah vs Kinah liée à l'âme", ["Depuis mars 2026 : Kinah libre et Kinah liée à l'âme, non transférable. Certains objets de boutique se revendent en Kinah liée."]),
        section("cross-server", "Commerce inter-serveurs", ["Courtage mondial inter-serveurs depuis décembre 2025 : meilleure liquidité pour les objets de niche."]),
        section("global", "Ce que le global devrait reprendre", ["Mêmes mécaniques de courtage que KR, avec réglages adaptés au lancement. Apprenez le marché tôt."]),
      ],
    }),
    de: articleCopy(guideLabels, "de", 6, {
      eyebrow: "WIRTSCHAFTS-GUIDE",
      title: "Aion 2 Brokerage-Guide: Auktionshaus, seelengebundenes Kinah & der globale Markt",
      description: "Die Brokerage (Auktionshaus) von Aion 2 ist das Herz der Spielerwirtschaft. Funktionsweise, Kinah vs. seelengebundenes Kinah, Mitgliedschaftsfunktionen und Erwartungen für Global.",
      intro: "Die Brokerage ist der Spieler-zu-Spieler-Markt von Aion 2. Serverübergreifender Handel, Kinah-Aufteilung und Anti-Bot-Maßnahmen machen das System wissenswert.",
      sourceNote: "Basierend auf AION2Hub-Bereichen, der offiziellen Monetarisierungsübersicht und NCSoft-KR-Systemhinweisen.",
      keywords: ["Aion 2 Auktionshaus", "Aion 2 Brokerage", "Aion 2 Kinah", "Aion 2 Wirtschaft"],
      sections: [
        section("basics", "So funktioniert die Brokerage", ["Spielermarkt: Auktionen, Sofortkauf, Erlöse in Kinah. Anti-Bot-Funktionen und Listenlimits über die Patches hinweg."]),
        section("currency", "Kinah vs. seelengebundenes Kinah", ["Seit März 2026: freies und seelengebundenes Kinah. Einige Shop-Artikel sind gegen gebundenes Kinah verkaufbar."]),
        section("cross-server", "Serverübergreifender Handel", ["Weltweite Brokerage über Server hinweg seit Dezember 2025: bessere Liquidität für Nischenartikel."]),
        section("global", "Was Global übernehmen sollte", ["Dieselben Brokerage-Mechaniken wie KR mit Launch-Tuning. Lernen Sie den Markt früh."]),
      ],
    }),
    es: articleCopy(guideLabels, "es", 6, {
      eyebrow: "GUÍA DE ECONOMÍA",
      title: "Guía del corretaje de Aion 2: casa de subastas, Kinah ligada al alma y el mercado global",
      description: "El corretaje (casa de subastas) de Aion 2 es el corazón de la economía de jugadores. Funcionamiento, Kinah y Kinah ligada al alma, funciones para miembros y expectativas globales.",
      intro: "El corretaje es el mercado jugador a jugador de Aion 2. Comercio entre servidores, división de Kinah y funciones anti-bot hacen que valga la pena conocerlo.",
      sourceNote: "Basado en las notas de AION2Hub, el resumen oficial de monetización global y los avisos de sistemas de NCSoft KR.",
      keywords: ["Aion 2 casa de subastas", "Aion 2 corretaje", "Aion 2 Kinah", "Aion 2 economía"],
      sections: [
        section("basics", "Cómo funciona el corretaje", ["Mercado de jugador a jugador: subastas, compra directa, ganancias en Kinah. Funciones anti-bot y límites de anuncios."]),
        section("currency", "Kinah vs. Kinah ligada al alma", ["Desde marzo de 2026: Kinah libre y ligada al alma. Algunos artículos de tienda se venden por Kinah ligada."]),
        section("cross-server", "Comercio entre servidores", ["Corretaje mundial entre servidores desde diciembre de 2025: mejor liquidez para artículos de nicho."]),
        section("global", "Qué debería copiar el global", ["Mismas mecánicas de corretaje que KR con ajustes de lanzamiento. Aprende el mercado temprano."]),
      ],
    }),
    "pt-br": articleCopy(guideLabels, "pt-br", 6, {
      eyebrow: "GUIA DE ECONOMIA",
      title: "Guia de corretagem de Aion 2: casa de leilões, Kinah ligada à alma e o mercado global",
      description: "A corretagem (casa de leilões) de Aion 2 é o coração da economia de jogadores. Funcionamento, Kinah e Kinah ligada à alma, recursos para membros e expectativas globais.",
      intro: "A corretagem é o mercado jogador-a-jogador de Aion 2. Comércio entre servidores, divisão de Kinah e funções anti-bot fazem valer a pena conhecê-la.",
      sourceNote: "Baseado nas notas da AION2Hub, na visão geral oficial de monetização global e nos avisos de sistema da NCSoft KR.",
      keywords: ["Aion 2 casa de leilões", "Aion 2 corretagem", "Aion 2 Kinah", "Aion 2 economia"],
      sections: [
        section("basics", "Como a corretagem funciona", ["Mercado jogador a jogador: leilões, compra direta, ganhos em Kinah. Funções anti-bot e limites de anúncios."]),
        section("currency", "Kinah vs. Kinah ligada à alma", ["Desde março de 2026: Kinah livre e ligada à alma. Alguns itens de loja são vendidos por Kinah ligada."]),
        section("cross-server", "Comércio entre servidores", ["Corretagem mundial entre servidores desde dezembro de 2025: melhor liquidez para itens de nicho."]),
        section("global", "O que o global deve copiar", ["Mesmas mecânicas de corretagem da KR com ajustes de lançamento. Aprenda o mercado cedo."]),
      ],
    }),
    ru: articleCopy(guideLabels, "ru", 6, {
      eyebrow: "ЭКОНОМИЧЕСКИЙ ГАЙД",
      title: "Гайд по брокеражу Aion 2: аукционный дом, связанная с душой Кина и глобальный рынок",
      description: "Брокераж (аукцион) Aion 2 — сердце игровой экономики. Механизм, Кина и связанная с душой Кина, функции для подписчиков и ожидания для глобала.",
      intro: "Брокераж — рынок «игрок-игрок» в Aion 2. Межсерверная торговля, разделение Кины и антибот-меры делают систему полезной к изучению.",
      sourceNote: "На основе записей AION2Hub, официального обзора монетизации и системных уведомлений NCSoft KR.",
      keywords: ["Aion 2 аукцион", "Aion 2 брокераж", "Aion 2 Кина", "Aion 2 экономика"],
      sections: [
        section("basics", "Как работает брокераж", ["Рынок «игрок-игрок»: аукционы, мгновенная покупка, выручка в Кине. Антибот-функции и лимиты объявлений."]),
        section("currency", "Кина и связанная с душой Кина", ["С марта 2026: свободная и связанная Кина. Некоторые товары магазина продаются за связанную Кину."]),
        section("cross-server", "Межсерверная торговля", ["Межсерверный мировой брокераж с декабря 2025: выше ликвидность для нишевых предметов."]),
        section("global", "Что глобал должен перенять", ["Те же механики брокеража с настройками под запуск. Изучите рынок заранее."]),
      ],
    }),
    "zh-hant": articleCopy(guideLabels, "zh-hant", 6, {
      eyebrow: "經濟指南",
      title: "Aion 2 拍賣行指南：拍賣行、靈魂綁定基納與全球市場",
      description: "Aion 2 的拍賣行（brokerage）是玩家經濟的核心。了解上架機制、基納與靈魂綁定基納的區分、會員門控功能，以及全球玩家的預期。",
      intro: "每個 MMO 經濟都需要市場，在 Aion 2 中這一角色由拍賣行承擔。從跨服交易、基納/靈魂綁定基納拆分，到為反機器人加入的會員門控，在這片市場裡游刃有餘需要一點知識。本指南拆解拍賣行的運作方式、貨幣體系對你的錢包意味著什麼，以及全球版可能複製什麼。",
      sourceNote: "基於 AION2Hub 的經濟與補丁說明（2026 年 3-12 月週期）、官方全球貨幣化概覽及 NCSoft 韓服交易系統公告。",
      keywords: ["Aion 2 拍賣行", "Aion 2 交易所", "Aion 2 基納", "Aion 2 靈魂綁定基納", "Aion 2 經濟"],
      sections: [
        section("basics", "拍賣行如何運作", ["拍賣行是 Aion 2 的玩家間市場：上架物品供其他玩家購買、競標或一口價，以基納收款。覆蓋裝備、消耗品、材料等。", "該系統隨時間加入了謹慎的反機器人功能——拍賣功能曾一度對會員門控，並引入了狩獵基納上限以抑制刷怪機器人。預期合理的上架限制，而非完全開放的自由市場。"]),
        section("currency", "基納與靈魂綁定基納", ["2026 年 3 月更新將基納拆分為兩種形態：可流通基納與靈魂綁定基納（綁定角色）。靈魂綁定基納來自特定來源，不能隨意轉移——規劃交易時很重要。", "部分商店物品——如寵物自動拾取券——明確可以靈魂綁定基納出售，為玩家提供將購買的便利再投入經濟的途徑。了解物品以何種貨幣購買是使用市場的一半技巧。"]),
        section("cross-server", "跨服交易與活躍市場", ["2025 年 12 月更新引入了跨服世界拍賣行，讓玩家可以超越本服買賣——這是市場流動性的重大一步，尤其對冷門物品與後期材料。", "對全球玩家而言，活躍市場在上線時最重要：五個伺服器區域意味著初期流動性薄弱。如果跨服交易抵達全球版本，將從上線第一天起極大提升經濟可用性。"]),
        section("global", "全球版應複製什麼", ["NCSoft 的官方全球貨幣化計畫確認了以 Quna 為後盾的商店經濟與兌換系統。全球版預計將沿用與韓服相同的核心拍賣機制，並以上線適配的調校交付。", "實用建議：盡早了解市場。上線時，理解上架窗口、貨幣拆分與跨服機會的先行者能比完全忽視經濟的玩家更高效地支撐養成。"]),
      ],
    }),
  },
};