import { articleCopy, localizations, newsLabels, publishedVerified, section } from "./trending-september-7-shared";
import type { ContentEntry, ContentHeroImage, ContentSource } from "./content-registry";

/* ARTICLE 1 — Western launch monetization model: NCsoft details a less aggressive F2P model (marketplace trade behind membership, quarterly season pass, free Abyss access) */

const gmSource1: ContentSource = {
  id: "guided-news-western-release-2026-09-06",
  kind: "third-party",
  publisher: "Guided News",
  label: "AION 2: NC will beim westlichen Release vieles besser machen (Gamescom appointment)",
  url: "https://guided.news/en/opinion/aion-2-nc-wants-to-do-a-lot-better-with-the-western-release/",
  publishedAt: "2026-09-06",
  retrievedAt: "2026-09-07",
  verifiedAt: "2026-09-07",
  localizations: localizations({
    "zh-hans": "AION 2：NC 要让西区发行做得更好（Gamescom 约谈报道）",
    en: "AION 2: NC wants to do a lot better with the western release (Gamescom appointment report)",
    fr: "AION 2 : NC veut faire beaucoup mieux pour le lancement occidental (article basé sur un rendez-vous Gamescom)",
    de: "AION 2: NC will beim westlichen Release vieles besser machen (Gamescom-Terminbericht)",
    es: "AION 2: NC quiere hacerlo mucho mejor con el lanzamiento occidental (informe de cita en Gamescom)",
    ja: "AION 2：NCは西側ローンチをもっと良くしたい（Gamescom取材記事）",
    "pt-br": "AION 2: a NC quer fazer muito melhor no lançamento ocidental (relato de reunião na Gamescom)",
    ru: "AION 2: NC хочет сделать западный запуск намного лучше (отчёт о встрече на Gamescom)",
    ko: "AION 2: NC, 서구 출시를 훨씬 잘 하고 싶다 (Gamescom 미팅 보도)",
    "zh-hant": "AION 2：NC 要讓西區發行做得更好（Gamescom 約談報導）",
  }, "https://guided.news/en/opinion/aion-2-nc-wants-to-do-a-lot-better-with-the-western-release/"),
};

const gmSource2: ContentSource = {
  id: "aion2-official-founders-store-2026-09-07",
  kind: "official",
  publisher: "NCSoft",
  label: "AION 2 Official Founder's Pack Store",
  url: "https://aion2.plaync.com/en-us/store/founders-pack",
  publishedAt: "2026-08-25",
  retrievedAt: "2026-09-07",
  verifiedAt: "2026-09-07",
  localizations: localizations({
    "zh-hans": "AION 2 官方创始人包商店",
    en: "AION 2 Official Founder's Pack Store",
    fr: "Boutique officielle des packs Fondateurs d'AION 2",
    de: "AION 2 Offizieller Founder's-Pack-Shop",
    es: "Tienda oficial de paquetes de fundador de AION 2",
    ja: "AION 2 公式ファウンダーズパックストア",
    "pt-br": "Loja oficial de pacotes de fundador do AION 2",
    ru: "Официальный магазин Founder's Pack AION 2",
    ko: "AION 2 공식 파운더스 팩 스토어",
    "zh-hant": "AION 2 官方創辦人包商店",
  }, "https://aion2.plaync.com/en-us/store/founders-pack"),
};

const gmHero: ContentHeroImage = {
  src: "https://blogfiles.ncsoft.net/news/af7330da-4ff6-4b58-aece-400e6061a3be.jpg",
  width: 1200, height: 630,
  credit: "NC Corporation",
  sourceUrl: "https://aion2.plaync.com/en-us/",
  rights: "linked-official-media",
  translations: {
    "zh-hans": { alt: "AION 2 西区变现模式新闻横幅", caption: "NC 在 Gamescom 约谈中披露西区免费模式细节：交易市场随会员开放、季度通行证、深渊免费开放。" },
    en: { alt: "AION 2 western monetization news banner", caption: "At a Gamescom appointment, NC outlined its western free-to-play details: marketplace trade behind membership, a quarterly season pass, and free Abyss access." },
    fr: { alt: "Bannière d'actualité monétisation occidentale d'AION 2", caption: "À la Gamescom, NC a détaillé son modèle free-to-play occidental : marché derrière l'adhésion, pass saisonnier trimestriel, accès gratuit à l'Abysse." },
    de: { alt: "News-Banner zur westlichen Monetarisierung von AION 2", caption: "Bei einem Gamescom-Termin skizzierte NC die westliche Free-to-Play-Details: Marktplatz hinter der Membership, vierteljährlicher Season Pass, kostenloser Abyss-Zugang." },
    es: { alt: "Banner de noticias de monetización occidental de AION 2", caption: "En Gamescom, NC detalló su modelo free-to-play occidental: mercado tras la membresía, pase de temporada trimestral y acceso gratuito al Abismo." },
    ja: { alt: "AION 2 西側課金モデルニュースバナー", caption: "NCはGamescom取材で西側F2Pモデルを説明：マーケットはメンバーシップ必須、四半期シーズンパス、アビス無料開放。" },
    "pt-br": { alt: "Banner de notícias sobre monetização ocidental do AION 2", caption: "Na Gamescom, a NC detalhou o modelo free-to-play ocidental: mercado atrás da assinatura, passe de temporada trimestral e Abismo gratuito." },
    ru: { alt: "Баннер новостей о западной монетизации AION 2", caption: "На встрече в Gamescom NC рассказала о западной F2P-модели: торговая площадка за подпиской, ежеквартальный сезонный пропуск, свободный доступ в Бездну." },
    ko: { alt: "AION 2 서구 과금 모델 뉴스 배너", caption: "NC가 Gamescom 미팅에서 서구 F2P 모델을 설명: 멤버십 필요 마켓플레이스, 분기 시즌 패스, 아비스 무료 접근." },
    "zh-hant": { alt: "AION 2 西區變現模式新聞橫幅", caption: "NC 在 Gamescom 約談中披露西區免費模式細節：交易市場隨會員開放、季度通行證、深淵免費開放。" },
  },
};

export const trendingSeptember7Article1: ContentEntry = {
  section: "news",
  slug: "aion-2-western-launch-monetization-model-details",
  schemaType: "NewsArticle",
  publishedAt: "2026-09-07",
  updatedAt: "2026-09-07",
  readingMinutes: 6,
  publication: publishedVerified,
  sources: [gmSource1, gmSource2],
  heroImage: gmHero,
  related: [
    { kind: "content", section: "guides", slug: "aion-2-monetization-f2p-cosmetics-guide" },
    { kind: "content", section: "guides", slug: "aion-2-founders-pack-complete-guide" },
    { kind: "content", section: "guides", slug: "aion-2-abyss-system-complete-guide" },
  ],
  translations: {
    en: articleCopy(newsLabels, "en", 6, {
      eyebrow: "MONETIZATION",
      title: "Aion 2 Western Launch Monetization: NCsoft Details a Less Aggressive F2P Model — Marketplace Trade Behind Membership",
      description: "Gamescom appointment report (September 6) on Aion 2's western free-to-play model: marketplace trading behind membership, quarterly season pass, no Abyss time limits for free players, premium currency via the marketplace",
      intro: "In a September 6 report based on a Gamescom appointment, German outlet Guided News detailed what NCsoft has planned for Aion 2's western monetization. The headline: the global free-to-play model is meant to be much less aggressive than the Korean version, keeping free players inside the content while gating player-to-player trade and convenience behind membership.",
      sourceNote: "Based on Guided News' September 6 report of its Gamescom appointment with NCsoft, cross-checked with the official AION 2 Founder's Pack store page (retrieved September 7, 2026).",
      keywords: ["Aion 2 monetization western launch", "Aion 2 membership marketplace", "Aion 2 season pass quarterly", "Aion 2 Abyss free players", "Aion 2 pay to win model"],
      sections: [
        section("what-nc-told-press", "What NCsoft Told Press at Gamescom", ["In the September 6 report, Guided News summarizes the studio's pitch: Aion 2 is meant to be the game the original Aion could not technically achieve, set 200 years later on a Unreal Engine 5 world roughly 36 times larger, where 'what you see, you can reach.'", "On monetization specifically, NC said the western model is 'much less aggressive' than the Korean release — free players are not locked out of core content, and restrictions concentrate on trade and convenience rather than blocking dungeons, raids, or PvP."]),
        section("membership-and-marketplace", "Membership and the Marketplace", ["The biggest difference for free players is the game economy: player-to-player trading on the marketplace requires a monthly membership, which per the report is mainly useful for very active endgame players.", "Without membership you can still fully outfit your character by earning gear in gameplay, but you cannot buy or trade certain items from other players on the market. NC also listed convenience benefits around the warehouse and certain repeatable activities."]),
        section("in-game-shop-and-premium-currency", "In-Game Shop and Premium Currency", ["A classic in-game shop remains: cosmetics (some exclusive to real money), consumables such as Resurrection Stones, crafting and gathering supplies, plus a premium currency.", "The premium currency can — under conditions — be traded on the marketplace, with full access to these economy features tied to membership. Guided News' read: items like Resurrection Stones are pay-to-convenience as long as they are also earnable in-game and grant no permanent power."]),
        section("abyss-and-pvp-stay-free", "Abyss and PvP Stay Free", ["One of the report's most concrete promises: free players face no daily time limit that pushes them out of the Abyss faction PvP area — you can spend as long as you like fighting the opposing faction.", "Dungeons, raids, and PvP content are not pay-walled; the monetization leans on cosmetics, consumables, season pass, and the membership-gated economy instead."]),
        section("season-pass-and-verdict", "The Quarterly Season Pass and the Press Verdict", ["A season pass refreshes roughly every three months, and its rewards — together with crafting materials and consumables — are where Guided News still wants to watch real pay-to-progress risk after launch.", "The outlet's verdict is cautious optimism: the western model sounds substantially friendlier than Korea's, but full assurance will only come after the October 5 release proves how the economy holds up."]),
      ],
    }),
    "zh-hans": articleCopy(newsLabels, "zh-hans", 6, {
      eyebrow: "变现模式",
      title: "Aion 2 西区上线变现模式：NC 披露更温和的免费模式——交易市场随会员开放",
      description: "9 月 6 日 Gamescom 约谈报道：Aion 2 西区免费模式细节——交易市场需会员、季度通行证、免费玩家深渊无时限、高级货币可经市场流转",
      intro: "德国媒体 Guided News 在 9 月 6 日基于 Gamescom 约谈发布报道，详述 NCsoft 对 Aion 2 西区变现的规划。核心信息：全球免费模式将比韩服「温和得多」，免费玩家不会被挡在核心内容之外，限制集中在交易与便利性上。",
      sourceNote: "基于 Guided News 9 月 6 日 Gamescom 约谈报道，并与 AION 2 官方创始人包商店页（2026-09-07 抓取）交叉核对。",
      keywords: ["Aion 2 西区变现", "Aion 2 会员交易市场", "Aion 2 季度通行证", "Aion 2 深渊免费玩家", "Aion 2 氪金变强"],
      sections: [
        section("what-nc-told-press", "NC 在 Gamescom 向媒体说了什么", ["9 月 6 日报道概括了官方说法：Aion 2 是初代 Aion 当年因技术限制无法做成的游戏——设定在 200 年后、基于 UE5、世界约为初代 36 倍大，且「目之所及皆可抵达」。", "在变现上，NC 表示西区模型将比韩服「温和得多」：免费玩家不会被挡在核心内容之外，限制集中在交易与便利性，而非副本、团队或 PvP。"]),
        section("membership-and-marketplace", "会员与交易市场", ["免费玩家最大的差异在游戏经济：交易市场（玩家间交易）需要月度会员，报道称其主要用于深度终局玩家。", "没有会员仍可完全武装角色——装备通过游戏内容赚取，但不能从他人处购买/交易特定物品。会员还附带仓库与部分重复活动的便利特权。"]),
        section("in-game-shop-and-premium-currency", "游戏内商店与高级货币", ["经典游戏内商店保留：外观（部分仅限真钱购买）、复活石等消耗品、制作与采集物资，以及一种高级货币。", "高级货币可在特定条件下经交易市场流转，完整经济功能需会员。Guided News 判断：只要复活石类物品也能在游戏内获得且不提供永久战力，就属于「便利型付费」而非强度付费。"]),
        section("abyss-and-pvp-stay-free", "深渊与 PvP 保持免费", ["报道中最具体的承诺：免费玩家在深渊阵营 PvP 区域不会被每日时限赶出场——可随时与敌对阵营交战。", "副本、团队与 PvP 内容不设付费墙；变现落在外观、消耗品、通行证与会员经济上。"]),
        section("season-pass-and-verdict", "季度通行证与媒体评价", ["赛季通行证约每三个月刷新一次；其奖励连同制作材料与消耗品，是 Guided News 认为仍需观察「强度型付费」风险的地方。", "该媒体给出谨慎乐观：西区模型听起来明显比韩服友好，但要等 10 月 5 日上线后经济系统真正运转才能完全确认。"]),
      ],
    }),
    fr: articleCopy(newsLabels, "fr", 6, {
      eyebrow: "MONÉTISATION",
      title: "Monétisation du lancement occidental d'Aion 2 : NC détaille un modèle F2P moins agressif — marché derrière l'adhésion",
      description: "Rapport du 6 septembre (rendez-vous Gamescom) : marché entre joueurs derrière l'adhésion, pass saisonnier trimestriel, Abysse sans limite pour les joueurs gratuits",
      intro: "Selon un rapport du 6 septembre fondé sur un rendez-vous Gamescom, le modèle occidental d'Aion 2 sera « beaucoup moins agressif » que la version coréenne : les joueurs gratuits gardent l'accès au contenu, les restrictions portant sur le commerce et le confort.",
      sourceNote: "Basé sur le rapport de Guided News du 6 septembre, recoupé avec la boutique officielle Founder's Pack (récupérée le 7 septembre 2026).",
      keywords: ["Monétisation Aion 2 occidentale", "Aion 2 adhésion marché", "Aion 2 pass saisonnier", "Aion 2 Abysse gratuit", "Aion 2 pay to win"],
      sections: [
        section("what-nc-told-press", "Ce que NC a dit à la presse", "Le successeur serait le jeu que le premier Aion ne pouvait techniquement pas offrir, 200 ans plus tard, avec un monde UE5 ~36 fois plus grand et « ce que vous voyez, vous pouvez l'atteindre » ; le modèle occidental est « beaucoup moins agressif » que la version coréenne."),
        section("membership-and-marketplace", "Adhésion et marché", "Le commerce entre joueurs (marketplace) nécessite l'adhésion mensuelle, utile surtout en endgame ; sans elle, vous pouvez toujours équiper votre personnage en jouant, sans acheter aux autres joueurs."),
        section("in-game-shop-and-premium-currency", "Boutique et monnaie premium", "Boutique classique : cosmétiques (certains exclusifs), consommables (pierres de résurrection), matériaux de craft, monnaie premium échangeable sur le marché sous conditions, avec adhésion pour l'économie complète."),
        section("abyss-and-pvp-stay-free", "Abysse et PvP gratuits", "Pas de limite de temps quotidienne excluant les joueurs gratuits de l'Abysse ; les donjons, raids et PvP ne sont pas derrière un paywall."),
        section("season-pass-and-verdict", "Pass saisonnier et verdict", "Un pass saisonnier ~tous les trois mois ; Guided News reste prudent sur les matériaux de craft et les récompenses du pass, en attendant le lancement du 5 octobre."),
      ],
    }),
    de: articleCopy(newsLabels, "de", 6, {
      eyebrow: "MONETARISIERUNG",
      title: "Westliche Monetarisierung von Aion 2: NC skizziert ein weniger aggressives F2P-Modell — Marktplatz hinter der Membership",
      description: "Gamescom-Terminbericht (6. September): Marktplatz-Handel hinter der Membership, vierteljährlicher Season Pass, Abyss ohne Zeitlimit für Free-Player",
      intro: "Ein Bericht vom 6. September auf Basis eines Gamescom-Termins: Das westliche Modell von Aion 2 soll „viel weniger aggressiv\u201c sein als die koreanische Version — Free-Player behalten Zugang zu den Inhalten, Einschränkungen betreffen Handel und Komfort.",
      sourceNote: "Basierend auf dem Guided-News-Bericht vom 6. September, abgeglichen mit dem offiziellen Founder's-Pack-Shop (abgerufen am 7. September 2026).",
      keywords: ["Aion 2 westliche Monetarisierung", "Aion 2 Membership Marktplatz", "Aion 2 Season Pass", "Aion 2 Abyss kostenlos", "Aion 2 Pay to Win"],
      sections: [
        section("what-nc-told-press", "Was NC der Presse sagte", "Der Nachfolger soll das Spiel sein, das das Original technisch nicht leisten konnte: 200 Jahre später, UE5-Welt ~36-mal größer, „was du siehst, kannst du erreichen\u201c; das westliche Modell ist „viel weniger aggressiv\u201c als die koreanische Version."),
        section("membership-and-marketplace", "Membership und Marktplatz", "Spielerhandel über den Marktplatz erfordert die monatliche Membership (vor allem Endgame-relevant); ohne sie rüstet man den Charakter komplett durch Gameplay aus, ohne von anderen zu kaufen."),
        section("in-game-shop-and-premium-currency", "Shop und Premiumwährung", "Klassischer Shop: Kosmetik (teils exklusiv), Verbrauchsgüter (Wiederbelebungssteine), Crafting-/Gathering-Materialien, Premiumwährung — unter Bedingungen über den Marktplatz handelbar, volle Wirtschaft mit Membership."),
        section("abyss-and-pvp-stay-free", "Abyss und PvP bleiben frei", "Kein tägliches Zeitlimit, das Free-Player aus dem Abyss-Fraktions-PvP drängt; Dungeons, Raids und PvP sind nicht hinter einer Paywall."),
        section("season-pass-and-verdict", "Season Pass und Fazit", "Ein Season Pass erneuert sich etwa alle drei Monate; Guided News will Crafting-Materialien und Pass-Belohnungen nach dem Start beobachten — vorsichtiger Optimismus."),
      ],
    }),
    es: articleCopy(newsLabels, "es", 6, {
      eyebrow: "MONETIZACIÓN",
      title: "Monetización del lanzamiento occidental de Aion 2: NC detalla un modelo F2P menos agresivo — mercado tras la membresía",
      description: "Informe del 6 de septiembre (cita en Gamescom): comercio en el mercado tras la membresía, pase de temporada trimestral, Abismo sin límites para jugadores gratuitos",
      intro: "Según un informe del 6 de septiembre basado en una cita en Gamescom, el modelo occidental de Aion 2 será «mucho menos agresivo» que la versión coreana: los jugadores gratuitos mantienen acceso al contenido, con restricciones centradas en el comercio y la comodidad.",
      sourceNote: "Basado en el informe de Guided News del 6 de septiembre, cotejado con la tienda oficial de Founder's Pack (recuperada el 7 de septiembre de 2026).",
      keywords: ["Monetización Aion 2 occidente", "Aion 2 membresía mercado", "Aion 2 pase de temporada", "Aion 2 Abismo gratis", "Aion 2 pay to win"],
      sections: [
        section("what-nc-told-press", "Lo que NC dijo a la prensa", "El sucesor sería el juego que el primer Aion no pudo hacer técnicamente, 200 años después, con un mundo UE5 ~36 veces mayor y «lo que ves, puedes alcanzarlo»; el modelo occidental es «mucho menos agresivo» que el coreano."),
        section("membership-and-marketplace", "Membresía y mercado", "El comercio entre jugadores (mercado) requiere la membresía mensual, útil sobre todo en el endgame; sin ella puedes equipar tu personaje jugando, sin comprar a otros."),
        section("in-game-shop-and-premium-currency", "Tienda y moneda premium", "Tienda clásica: cosméticos (algunos exclusivos), consumibles (piedras de resurrección), materiales de crafteo, moneda premium canjeable en el mercado bajo condiciones, con la membresía para la economía completa."),
        section("abyss-and-pvp-stay-free", "Abismo y PvP gratuitos", "Sin límite de tiempo diario que expulse a los gratuitos del Abismo; las mazmorras, incursiones y el PvP no están tras un muro de pago."),
        section("season-pass-and-verdict", "Pase de temporada y veredicto", "Un pase de temporada se renueva cada ~tres meses; Guided News mantiene cautela sobre materiales de crafteo y recompensas, a la espera del lanzamiento del 5 de octubre."),
      ],
    }),
    ja: articleCopy(newsLabels, "ja", 6, {
      eyebrow: "課金モデル",
      title: "Aion 2 西側ローンチの課金モデル：NCが明かすより穏やかなF2P——マーケット取引はメンバーシップ必須",
      description: "9月6日 Gamescom取材記事：西側F2Pモデルの詳細——マーケットはメンバーシップ制、四半期シーズンパス、アビス無料開放、プレミアム通貨の市場流通",
      intro: "9月6日付けGamescom取材記事で、NCが西側課金モデルの構想を説明。見出しは「韓国版よりはるかに穏やかな」F2P——無課金でもコアコンテンツは遊べ、制限は取引と利便性に集中します。",
      sourceNote: "Guided News 2026年9月6日付Gamescom取材記事に基づき、公式ファウンダーズパックストア（2026-09-07取得）と照合。",
      keywords: ["Aion 2 西側課金", "Aion 2 メンバーシップ マーケット", "Aion 2 シーズンパス", "Aion 2 アビス 無課金", "Aion 2 ペイトゥウィン"],
      sections: [
        section("what-nc-told-press", "NCがメディアに語ったこと", "続編は初代Aionが技術的に実現できなかったゲーム——200年後、UE5の世界は約36倍で「見える場所には行ける」；西側モデルは「韓国版よりはるかに穏やか」。"),
        section("membership-and-marketplace", "メンバーシップとマーケット", "プレイヤー間取引（マーケット）は月額メンバーシップが必要（主に高レベル向け）。なしでもゲーム内で装備を整えられますが、他人からの購入・取引は不可。"),
        section("in-game-shop-and-premium-currency", "ゲーム内ショップとプレミアム通貨", "定番ショップ：コスメ（一部は現金限定）、復活の石などの消耗品、クラフト/採取素材、プレミアム通貨——条件付きでマーケット流通可、完全経済はメンバーシップ。"),
        section("abyss-and-pvp-stay-free", "アビスとPvPは無料", "無課金プレイヤーをアビスの陣営PvPから締め出す毎日時間制限なし；ダンジョン・レイド・PvPはペイウォールの背後にない。"),
        section("season-pass-and-verdict", "シーズンパスと評価", "シーズンパスは約3カ月ごとに更新。メディアはクラフト素材とパス報酬に注視しつつ「慎重な楽観」を表明、10月5日を待つとしています。"),
      ],
    }),
    "pt-br": articleCopy(newsLabels, "pt-br", 6, {
      eyebrow: "MONETIZAÇÃO",
      title: "Monetização do lançamento ocidental do Aion 2: NC detalha um modelo F2P menos agressivo — mercado atrás da assinatura",
      description: "Relato do dia 6 de setembro (reunião na Gamescom): comércio no mercado atrás da assinatura, passe de temporada trimestral, Abismo sem limites para gratuitos",
      intro: "Segundo um relato do dia 6 de setembro baseado em uma reunião na Gamescom, o modelo ocidental do Aion 2 será «muito menos agressivo» que a versão coreana: gratuitos mantêm acesso ao conteúdo, com restrições focadas no comércio e conveniência.",
      sourceNote: "Baseado no relato da Guided News de 6 de setembro, cruzado com a loja oficial de Founder's Pack (acessada em 7 de setembro de 2026).",
      keywords: ["Monetização Aion 2 ocidente", "Aion 2 assinatura mercado", "Aion 2 passe de temporada", "Aion 2 Abismo gratuito", "Aion 2 pay to win"],
      sections: [
        section("what-nc-told-press", "O que a NC disse à imprensa", "A sequência seria o jogo que o primeiro Aion não pôde fazer tecnicamente, 200 anos depois, com mundo UE5 ~36 vezes maior e «o que você vê, você alcança»; o modelo ocidental é «muito menos agressivo» que o coreano."),
        section("membership-and-marketplace", "Assinatura e mercado", "O comércio entre jogadores (mercado) exige a assinatura mensal, útil sobretudo no endgame; sem ela, você equipa seu personagem jogando, sem comprar de outros."),
        section("in-game-shop-and-premium-currency", "Loja e moeda premium", "Loja clássica: cosméticos (alguns exclusivos), consumíveis (pedras de ressurreição), materiais de crafting, moeda premium negociável no mercado sob condições, com assinatura para a economia completa."),
        section("abyss-and-pvp-stay-free", "Abismo e PvP gratuitos", "Sem limite diário de tempo que exclua gratuitos do Abismo; masmorras, raides e PvP não ficam atrás de paywall."),
        section("season-pass-and-verdict", "Passe de temporada e veredito", "Um passe de temporada é renovado a cada ~três meses; a Guided News segue cautelosa sobre materiais de crafting e recompensas, aguardando o lançamento em 5 de outubro."),
      ],
    }),
    ru: articleCopy(newsLabels, "ru", 6, {
      eyebrow: "МОНЕТИЗАЦИЯ",
      title: "Западная монетизация Aion 2: NC раскрывает более мягкую F2P-модель — торговля на аукционе за подпиской",
      description: "Отчёт от 6 сентября (встреча на Gamescom): торговля на аукционе за подпиской, ежеквартальный сезонный пропуск, Бездна без лимита для бесплатных",
      intro: "Согласно отчёту от 6 сентября по итогам встречи на Gamescom, западная модель Aion 2 будет «гораздо менее агрессивной», чем корейская: бесплатные игроки сохраняют доступ к контенту, ограничения касаются торговли и удобств.",
      sourceNote: "На основе отчёта Guided News от 6 сентября, сверено с официальным магазином Founder's Pack (получен 7 сентября 2026 г.).",
      keywords: ["Монетизация Aion 2 запад", "Aion 2 подписка аукцион", "Aion 2 сезонный пропуск", "Aion 2 Бездна бесплатно", "Aion 2 pay to win"],
      sections: [
        section("what-nc-told-press", "Что NC рассказала прессе", "Продолжение — игра, которую первый Aion не смог сделать технически: 200 лет спустя, мир UE5 ~в 36 раз больше, «что видишь — то достижимо»; западная модель «гораздо менее агрессивна», чем корейская."),
        section("membership-and-marketplace", "Подписка и аукцион", "Торговля между игроками (аукцион) требует ежемесячной подписки (полезно в основном в эндгейме); без неё персонажа можно полностью экипировать игрой, не покупая у других."),
        section("in-game-shop-and-premium-currency", "Магазин и премиум-валюта", "Классический магазин: косметика (часть эксклюзивна), расходники (камни воскрешения), материалы крафта, премиум-валюта — при условиях торгуется на аукционе, полная экономика с подпиской."),
        section("abyss-and-pvp-stay-free", "Бездна и PvP бесплатны", "Нет дневного лимита времени, выталкивающего бесплатных из Бездны; подземелья, рейды и PvP не за пейволлом."),
        section("season-pass-and-verdict", "Сезонный пропуск и вердикт", "Сезонный пропуск обновляется примерно раз в три месяца; Guided News осторожно оптимистичен, ожидая запуска 5 октября, чтобы проверить экономику."),
      ],
    }),
    ko: articleCopy(newsLabels, "ko", 6, {
      eyebrow: "과금 모델",
      title: "아이온2 서구 출시 과금 모델: 엔씨가 공개한 더 온건한 F2P — 마켓플레이스 거래는 멤버십 필요",
      description: "9월 6일 Gamescom 미팅 보도: 서구 F2P 모델 세부사항 — 멤버십 필요 마켓플레이스, 분기 시즌 패스, 아비스 무료 접근, 프리미엄 통화 시장 유통",
      intro: "9월 6일 Gamescom 미팅 보도에서 엔씨가 서구 과금 모델 구상을 설명했습니다. 핵심: 글로벌 F2P 모델은 한국 버전보다 '훨씬 덜 공격적'이며, 무료 이용자도 코어 콘텐츠를 즐기고 제한은 거래와 편의에 집중됩니다.",
      sourceNote: "Guided News 9월 6일 Gamescom 미팅 보도를 기반으로, AION 2 공식 파운더스 팩 스토어(2026-09-07 확인)와 교차 확인했습니다.",
      keywords: ["아이온2 서구 과금", "아이온2 멤버십 마켓플레이스", "아이온2 시즌 패스", "아이온2 아비스 무료", "아이온2 페이투윈"],
      sections: [
        section("what-nc-told-press", "엔씨가 언론에 밝힌 내용", "후속작은 원작 Aion이 기술적으로 이룰 수 없었던 게임——200년 후, UE5 세계는 약 36배 크고 '보이는 곳은 갈 수 있다'; 서구 모델은 한국 버전보다 '훨씬 덜 공격적'입니다."),
        section("membership-and-marketplace", "멤버십과 마켓플레이스", "플레이어 간 거래(마켓플레이스)는 월간 멤버십 필요(주로 엔드게임 유저용). 없어도 게임플레이로 장비를 완성할 수 있지만 타인 구매·거래는 불가."),
        section("in-game-shop-and-premium-currency", "게임 내 상점과 프리미엄 통화", "정석 상점: 코스메틱(일부 현금 전용), 부활석 등 소모품, 제작/채집 재료, 프리미엄 통화——조건부로 마켓플레이스 유통 가능, 완전 경제는 멤버십."),
        section("abyss-and-pvp-stay-free", "아비스와 PvP는 무료", "무료 이용자를 아비스 진영 PvP에서 밀어내는 일일 시간 제한 없음; 던전·레이드·PvP는 유료 장벽 뒤에 있지 않습니다."),
        section("season-pass-and-verdict", "분기 시즌 패스와 평가", "시즌 패스는 약 3개월마다 갱신됩니다. 언론은 제작 재료와 패스 보상에 주목하며 '조심스러운 낙관'을 표했습니다."),
      ],
    }),
    "zh-hant": articleCopy(newsLabels, "zh-hant", 6, {
      eyebrow: "變現模式",
      title: "Aion 2 西區上線變現模式：NC 披露更溫和的免費模式——交易市場隨會員開放",
      description: "9 月 6 日 Gamescom 約談報導：Aion 2 西區免費模式細節——交易市場需會員、季度通行證、免費玩家深淵無時限、高級貨幣可經市場流轉",
      intro: "德國媒體 Guided News 在 9 月 6 日基於 Gamescom 約談發布報導，詳述 NCsoft 對 Aion 2 西區變現的規劃。核心資訊：全球免費模式將比韓服「溫和得多」，免費玩家不會被擋在核心內容之外，限制集中在交易與便利性上。",
      sourceNote: "基於 Guided News 9 月 6 日 Gamescom 約談報導，並與 AION 2 官方創辦人包商店頁（2026-09-07 抓取）交叉核對。",
      keywords: ["Aion 2 西區變現", "Aion 2 會員交易市場", "Aion 2 季度通行證", "Aion 2 深淵免費玩家", "Aion 2 課金變強"],
      sections: [
        section("what-nc-told-press", "NC 在 Gamescom 向媒體說了什麼", ["9 月 6 日報導概括了官方說法：Aion 2 是初代 Aion 當年因技術限制無法做成的遊戲——設定在 200 年後、基於 UE5、世界約為初代 36 倍大，且「目之所及皆可抵達」。", "在變現上，NC 表示西區模型將比韓服「溫和得多」：免費玩家不會被擋在核心內容之外，限制集中在交易與便利性，而非副本、團隊或 PvP。"]),
        section("membership-and-marketplace", "會員與交易市場", ["免費玩家最大的差異在遊戲經濟：交易市場（玩家間交易）需要月度會員，報導稱其主要用於深度終局玩家。", "沒有會員仍可完全武裝角色——裝備透過遊戲內容賺取，但不能從他人處購買/交易特定物品。會員還附帶倉庫與部分重複活動的便利特權。"]),
        section("in-game-shop-and-premium-currency", "遊戲內商店與高級貨幣", ["經典遊戲內商店保留：外觀（部分僅限真錢購買）、復活石等消耗品、製作與採集物資，以及一種高級貨幣。", "高級貨幣可在特定條件下經交易市場流轉，完整經濟功能需會員。Guided News 判斷：只要復活石類物品也能在遊戲內獲得且不提供永久戰力，就屬於「便利型付費」而非強度付費。"]),
        section("abyss-and-pvp-stay-free", "深淵與 PvP 保持免費", ["報導中最具體的承諾：免費玩家在深淵陣營 PvP 區域不會被每日時限趕出場——可隨時與敵對陣營交戰。", "副本、團隊與 PvP 內容不設付費牆；變現落在外觀、消耗品、通行證與會員經濟上。"]),
        section("season-pass-and-verdict", "季度通行證與媒體評價", ["賽季通行證約每三個月刷新一次；其獎勵連同製作材料與消耗品，是 Guided News 認為仍需觀察「強度型付費」風險的地方。", "該媒體給出謹慎樂觀：西區模型聽起來明顯比韓服友好，但要等 10 月 5 日上線後經濟系統真正運轉才能完全確認。"]),
      ],
    }),
  },
};