import { articleCopy, guideLabels, localizations, publishedVerified, section } from "./trending-august-28-shared";
import type { ContentEntry, ContentHeroImage, ContentSource } from "./content-registry";

/* ARTICLE 3 — Server transfers: how they work & when to move */

const stSource1: ContentSource = {
  id: "aion2t-server-transfer-2026-08-28",
  kind: "third-party", publisher: "AION2T",
  label: "Aion 2 — August 26 Update Notes: Server Transfers",
  url: "https://aion2t.com/news/40",
  publishedAt: "2026-08-26",
  retrievedAt: "2026-08-27",
  verifiedAt: "2026-08-27",
  localizations: localizations({
    "zh-hans": "Aion 2 —— 8 月 26 日更新说明：服务器转移",
    en: "Aion 2 — August 26 Update Notes: Server Transfers",
    fr: "Aion 2 — Notes du 26 août : transferts de serveur",
    de: "Aion 2 — Update-Notizen vom 26. August: Servertransfers",
    es: "Aion 2 — Notas del 26 de agosto: transferencias de servidor",
    ja: "Aion 2 — 8月26日アップデートノート：サーバー移行",
    "pt-br": "Aion 2 — Notas de 26 de agosto: transferências de servidor",
    ru: "Aion 2 — Заметки от 26 августа: перенос серверов",
    ko: "Aion 2 — 8월 26일 업데이트 노트: 서버 이전",
    "zh-hant": "Aion 2 —— 8 月 26 日更新說明：伺服器轉移",
  }, "https://aion2t.com/news/40"),
};

const stSource2: ContentSource = {
  id: "nc-official-server-transfer-2026-08-28",
  kind: "official", publisher: "NC",
  label: "AION 2 Official Website — Server Transfer Notice",
  url: "https://aion2.plaync.com/ko-kr/board/notice",
  publishedAt: "2026-08-26",
  retrievedAt: "2026-08-27",
  verifiedAt: "2026-08-27",
  localizations: localizations({
    "zh-hans": "AION 2 官方网站——服务器转移公告",
    en: "AION 2 Official Website — Server Transfer Notice",
    fr: "Site officiel AION 2 — avis de transfert de serveur",
    de: "AION 2 Offizielle Website — Hinweis zum Servertransfer",
    es: "Sitio web oficial de AION 2 — aviso de transferencia de servidor",
    ja: "AION 2 公式サイト — サーバー移行のお知らせ",
    "pt-br": "Site oficial do AION 2 — aviso de transferência de servidor",
    ru: "Официальный сайт AION 2 — уведомление о переносе серверов",
    ko: "AION 2 공식 사이트 — 서버 이전 안내",
    "zh-hant": "AION 2 官方網站——伺服器轉移公告",
  }, "https://aion2.plaync.com/ko-kr/board/notice"),
};

const stHero: ContentHeroImage = {
  src: "https://blogfiles.ncsoft.net/news/af7330da-4ff6-4b58-aece-400e6061a3be.jpg",
  width: 1100, height: 605,
  credit: "NC Corporation",
  sourceUrl: "https://aion2.plaync.com/ko-kr/board/notice",
  rights: "linked-official-media",
  translations: {
    "zh-hans": { alt: "Aion 2 服务器转移指南配图", caption: "NC 官方配图；8 月 26 日上线限时服务器转移（1000 金纳基础 + 每角色 200，仅 20:00-24:00）。" },
    en: { alt: "Aion 2 server transfer guide image", caption: "Official NC artwork; a limited server transfer feature launched August 26 (1,000 Quna base + 200 per character, 20:00-24:00 only)." },
    fr: { alt: "Image du guide de transfert de serveur d'Aion 2", caption: "Visuel officiel NC ; transfert de serveur limité lancé le 26 août (1 000 Quna + 200/personnage, 20h-24h)." },
    de: { alt: "Bild zum Servertransfer-Guide für Aion 2", caption: "Offizielles NC-Artwork; limitierter Servertransfer ab 26. August (1000 Quna + 200/Charakter, 20-24 Uhr)." },
    es: { alt: "Imagen de la guía de transferencia de servidor de Aion 2", caption: "Arte oficial de NC; transferencia limitada lanzada el 26 de agosto (1000 Quna + 200/personaje, 20-24 h)." },
    ja: { alt: "Aion 2 サーバー移行ガイド画像", caption: "NC公式アートワーク；8月26日に限定サーバー移行（1000キナ+キャラ200、20:00-24:00）が実装されました。" },
    "pt-br": { alt: "Imagem do guia de transferência de servidor de Aion 2", caption: "Arte oficial da NC; transferência limitada lançada em 26 de agosto (1000 Quna + 200/personagem, 20h-24h)." },
    ru: { alt: "Изображение гайда по переносу серверов в Aion 2", caption: "Официальный арт NC; ограниченный перенос серверов запущен 26 августа (1000 Кина + 200/персонаж, 20:00-24:00)." },
    ko: { alt: "Aion 2 서버 이전 가이드 이미지", caption: "NC 공식 이미지입니다. 8월 26일 한정 서버 이전(1000 큐나+캐릭터당 200, 20:00-24:00)이 적용됐습니다." },
    "zh-hant": { alt: "Aion 2 伺服器轉移指南配圖", caption: "NC 官方配圖；8 月 26 日上線限時伺服器轉移（1000 金納基礎 + 每角色 200，僅 20:00-24:00）。" },
  },
};

export const trendingAugust28Article3: ContentEntry = {
  section: "guides",
  slug: "aion-2-server-transfers-guide",
  schemaType: "Article",
  publishedAt: "2026-08-27",
  updatedAt: "2026-08-27",
  readingMinutes: 5,
  publication: publishedVerified,
  sources: [stSource1, stSource2],
  heroImage: stHero,
  related: [
    { kind: "content", section: "guides", slug: "aion-2-server-regions-guide" },
    { kind: "content", section: "guides", slug: "aion-2-brokerage-market-guide" },
    { kind: "content", section: "guides", slug: "aion-2-global-version-changes-guide" },
  ],
  translations: {
    en: articleCopy(guideLabels, "en", 5, {
      eyebrow: "SERVER TRANSFERS",
      title: "Aion 2 Server Transfer: How It Works & When to Move",
      description: "The August 26 patch introduced limited-time server transfers on the Asian service. Here is how the feature works, what it costs, and how to decide whether moving servers is right for you.",
      intro: "Server transfers arrived with the August 26 'Great Rebalance' patch, letting players move characters between servers for a limited window. The feature is currently on the Korean/Taiwanese service; this guide explains the confirmed mechanics, the cost structure, the restrictions, and how to think about the decision — including what it may look like on the global launch.",
      sourceNote: "Based on AION2T's August 26 update notes and NC's official server transfer notice. The feature's current form applies to the Asian service; global rules may differ at the October 5 launch.",
      keywords: ["Aion 2 server transfer", "Aion 2 move server", "Aion 2 change server", "Aion 2 server transfer cost", "Aion 2 server switch guide"],
      sections: [
        section("mechanics", "What the Feature Does", ["Server transfer lets you move a character (and its progression) from one server to another. The August 26 implementation is a time-limited window rather than an always-on service — transfers are only processed during the stated availability period, so planning around the window matters.", "Because it is a limited feature tied to the patch, treat it as a launch-style event: eligible characters can be transferred during the window, and once it closes you wait for the next opportunity. Always verify the current availability period on the official notice before acting.", "The transfer moves the character's progression; confirm what carries (gear, kinah, items, Daeva Pass progress) against the official notice for your service, since limits are common."]),
        section("cost", "Cost & Limits", ["The confirmed pricing is a base of 1,000 Quna per transfer plus 200 Quna per character. Quna is the premium currency, so transfers are not free — budget for the base fee even for a single character.", "A practical cap to note: transfers are only processed between 20:00 and 24:00 (server time). If your schedule falls outside that window, plan accordingly — the feature is not available around the clock.", "The one-week duration means there is no rush to decide on day one, but there is also no room to procrastinate past the closing date."]),
        section("when", "When You Should Consider Moving", ["Move if your current server's population or faction balance does not match how you play — for example, if your faction is chronically outnumbered, or your guild is leaving and you want to stay with them.", "Move if you want to play with friends on another server, or if server health (queue times, market prices, lag) is worse where you are. The brokerage market guide is a useful reference for comparing economies between servers.", "Do not move just because a server is new or hyped; a transfer costs real currency and progression carries, so weigh the benefit against the fee and the risk of landing on an equally crowded server."]),
        section("limits", "What Usually Doesn't Transfer", ["Transfers in Aion 2 come with the usual exclusions: character-bound items, some account-level services, and faction/region-locked content may not move. Confirm the exact exclusion list for your service before paying the fee.", "Bound Kina, character-specific progression, and any server-tied economy items are prime candidates to stay behind — read the notice to avoid surprises.", "If you are unsure whether a specific item carries, the safe move is to assume it does not and only transfer what the official notice guarantees."]),
        section("global", "What This Means for the Global Launch", ["Server transfer is currently an Asian-service feature. The global version launches October 5 with five servers and no regional locks, which reduces the need for transfers early on — you can already play with friends anywhere.", "Still, cross-server mobility may arrive on the global service after launch, and when it does, expect similar economics (a Quna fee, per-character cost, and a processing window) unless NC changes course.", "For now, the best preparation is choosing your home server deliberately at launch and using the no-lock structure to your advantage, rather than planning to pay for a move later."]),
      ],
    }),
    "zh-hans": articleCopy(guideLabels, "zh-hans", 5, {
      eyebrow: "服务器转移",
      title: "Aion 2 服务器转移：机制与何时迁移",
      description: "8 月 26 日补丁在亚服引入限时服务器转移。以下为该功能机制、费用与如何判断是否该换服。",
      intro: "服务器转移随 8 月 26 日『大平衡』补丁上线，让玩家在限时窗口内跨服转移角色。该功能当前在韩/台服；本指南解读已确认机制、费用结构、限制与决策思路（含全球版可能的形态）。",
      sourceNote: "基于 AION2T 8 月 26 日更新说明与 NC 官方服务器转移公告。当前形式适用于亚服；全球版 10 月 5 日上线时规则或有不同。",
      keywords: ["Aion 2 服务器转移", "Aion 2 换服", "Aion 2 服务器迁移", "Aion 2 转移费用", "Aion 2 换服指南"],
      sections: [
        section("mechanics", "功能机制", ["服务器转移让你把角色（及其进度）从一个服务器移到另一个。8 月 26 日实现为限时窗口而非常驻服务——仅在公布时段内处理，需围绕窗口规划。", "操作前务必以官方公告核对当前可用时段与可携带内容（装备、金纳、物品、Daeva Pass 进度）。"]),
        section("cost", "费用与限制", ["确认定价：每次转移 1000 金纳基础 + 每角色 200 金纳。金纳为高级货币，转移并非免费。", "处理时段仅 20:00-24:00（服务器时间）。", "窗口为期一周，不必首日决定，但也不能拖过截止日。"]),
        section("when", "何时该考虑迁移", ["当前服务器人口或阵营失衡不符合你的玩法、公会离开而你想追随、想与另一服好友同玩，或服务器健康度（排队/物价/延迟）较差时。", "不要仅为追逐新服或热度而转移——费用为真实货币且进度迁移，需权衡。"]),
        section("limits", "通常不迁移的内容", ["角色绑定物品、部分账号级服务、阵营/区域锁定内容通常不迁移。绑定基纳、角色专属进度与服务器绑定经济物品可能留下。", "不确定某物品是否携带时，按『不带』处理，仅迁移官方保证的内容。"]),
        section("global", "对全球上线的意义", ["服务器转移目前是亚服功能。全球版 10 月 5 日上线，五台服务器无区域锁定，初期换服需求低。", "跨服迁移可能在全球服上线后到来，届时费用结构与处理窗口或类似。", "当下最佳准备是上线时审慎选服，善用无锁定结构。"]),
      ],
    }),
    ko: articleCopy(guideLabels, "ko", 5, {
      eyebrow: "서버 이전",
      title: "Aion 2 서버 이전: 작동 방식과 이전 시점",
      description: "8월 26일 패치로 아시아 서버에 한정 서버 이전이 도입됐습니다. 기능 방식, 비용, 이전 판단 기준을 정리합니다.",
      intro: "서버 이전이 8월 26일 '그레이트 리밸런스' 패치와 함께 도입됐습니다. 현재 한/대만 서버 기능이며, 확정 메커니즘·비용 구조·제한·판단 기준을 다룹니다.",
      sourceNote: "AION2T 8월 26일 업데이트 노트와 NC 공식 서버 이전 공지 기반. 현재 형태는 아시아 서버 기준이며 글로벌은 다를 수 있습니다.",
      keywords: ["Aion 2 서버 이전", "Aion 2 서버 이동", "Aion 2 서버 변경", "Aion 2 이전 비용", "Aion 2 서버 변경 가이드"],
      sections: [
        section("mechanics", "기능 방식", "캐릭터와 진행도를 한 서버에서 다른 서버로 이동. 8월 26일 구현은 상시가 아닌 한정 창. 공지에서 현재 가능 기간과 이전 가능 내용(장비·키나·아이템·대에바 패스)을 확인하세요."),
        section("cost", "비용과 제한", "기본 1000 큐나 + 캐릭터당 200 큐나. 처리 시간은 20:00-24:00(서버 시간)뿐. 창은 1주일."),
        section("when", "이전 고려 시점", "인구/진영 불균형, 길드 이동 동행, 다른 서버 친구와 합류, 서버 상태(대기·물가·렉) 악화 시. 신서버나 과대 광고만으로 이전하지 마세요."),
        section("limits", "이전되지 않는 것", "캐릭터 귀속 아이템, 일부 계정 서비스, 진영/지역 잠금 콘텐츠, 귀속 키나 등. 불확실하면 공식 보장분만 이전하세요."),
        section("global", "글로벌 출시 의미", "서버 이전은 현재 아시아 기능. 글로벌은 10월 5일 5개 서버·지역 잠금 없음으로 초기 이전 수요가 낮습니다. 출시 후 비슷한 경제 구조로 올 수 있습니다."),
      ],
    }),
    ja: articleCopy(guideLabels, "ja", 5, {
      eyebrow: "サーバー移行",
      title: "Aion 2 サーバー移行：仕組みと移行のタイミング",
      description: "8月26日のパッチでアジアサーバーに期間限定のサーバー移行が実装されました。仕組み、費用、移行判断の基準をまとめます。",
      intro: "サーバー移行が8月26日の『グレートリバランス』パッチと共に実装されました。現在は韓国・台湾サーバーの機能で、確定した仕組み・費用構造・制限・判断基準を解説します。",
      sourceNote: "AION2T の8月26日アップデートノートと NC 公式のサーバー移行告知に基づきます。現在の形態はアジアサーバー基準で、グローバルでは異なる可能性があります。",
      keywords: ["Aion 2 サーバー移行", "Aion 2 サーバー移動", "Aion 2 サーバー変更", "Aion 2 移行費用", "Aion 2 サーバー変更ガイド"],
      sections: [
        section("mechanics", "仕組み", "キャラクターと進行度を別サーバーへ移動。8月26日実装は常設ではなく期間限定ウィンドウ。公式告知で可能期間と移行可能な内容（装備・キナ・アイテム・デーバパス）を確認してください。"),
        section("cost", "費用と制限", "基本1000キナ＋キャラクター200キナ。処理は20:00-24:00（サーバー時間）のみ。ウィンドウは1週間。"),
        section("when", "移行を検討するタイミング", "人口・陣営不均衡、ギルド移動への同行、別サーバーの友人との合流、サーバー状態（待機・物価・ラグ）悪化時。新サーバーや話題性だけで移行しないこと。"),
        section("limits", "移行されないもの", "キャラクター帰属アイテム、一部アカウントサービス、陣営・地域ロックコンテンツ、バインドキナなど。不明なら公式保証分のみ移行してください。"),
        section("global", "グローバルリリースへの意味", "サーバー移行は現在アジア機能。グローバルは10月5日、5サーバーで地域ロックなしのため初期の移行需要は低いです。"),
      ],
    }),
    fr: articleCopy(guideLabels, "fr", 5, {
      eyebrow: "TRANSFERTS DE SERVEUR",
      title: "Transfert de serveur d'Aion 2 : fonctionnement et quand migrer",
      description: "Le patch du 26 août a introduit des transferts de serveur limités sur le service asiatique. Le fonctionnement, le coût et comment décider de migrer.",
      intro: "Les transferts de serveur sont arrivés avec le patch « Great Rebalance » du 26 août, permettant de déplacer un personnage entre serveurs sur une fenêtre limitée. Actuellement sur le service coréen/taiwanais.",
      sourceNote: "Basé sur les notes du 26 août d'AION2T et l'avis officiel NC. Forme actuelle pour le service asiatique ; la version mondiale peut différer.",
      keywords: ["Aion 2 transfert de serveur", "Aion 2 changer de serveur", "Aion 2 coût transfert", "Aion 2 guide transfert"],
      sections: [
        section("mechanics", "Fonctionnement", "Déplace un personnage (et sa progression) entre serveurs. Fenêtre limitée plutôt que service permanent. Vérifiez la période et ce qui est transféré sur l'avis officiel."),
        section("cost", "Coût et limites", "1 000 Quna de base + 200 par personnage. Traitement uniquement entre 20h et 24h (heure serveur). Fenêtre d'une semaine."),
        section("when", "Quand migrer", "Si la population/faction de votre serveur ne convient pas, si votre guilde part, pour rejoindre des amis, ou si le serveur est en mauvaise santé. Ne migrez pas juste pour un serveur « tendance »."),
        section("limits", "Ce qui ne transfère pas", "Objets liés, services de compte, contenu verrouillé par faction/région, Kina liée. En cas de doute, ne transférez que ce que l'avis garantit."),
        section("global", "Pour la sortie mondiale", "Fonction asiatique pour l'instant. La version mondiale (5 octobre, 5 serveurs sans verrouillage) réduit le besoin de transfert au départ."),
      ],
    }),
    de: articleCopy(guideLabels, "de", 5, {
      eyebrow: "SERVERTRANSFERS",
      title: "Aion-2-Servertransfer: So funktioniert es & wann man wechselt",
      description: "Der Patch vom 26. August führte zeitlich begrenzte Servertransfers im asiatischen Dienst ein. Funktionsweise, Kosten und Entscheidungshilfe.",
      intro: "Servertransfers kamen mit dem „Great-Rebalance“-Patch vom 26. August, um Charaktere in einem begrenzten Zeitfenster zwischen Servern zu verschieben. Derzeit im koreanischen/taiwanesischen Dienst.",
      sourceNote: "Basierend auf den Notizen vom 26. August von AION2T und der offiziellen NC-Mitteilung. Aktuelle Form für den asiatischen Dienst; global kann sie abweichen.",
      keywords: ["Aion 2 Servertransfer", "Aion 2 Server wechseln", "Aion 2 Transferkosten", "Aion 2 Serverwechsel-Guide"],
      sections: [
        section("mechanics", "Funktionsweise", "Verschiebt einen Charakter (inkl. Fortschritt) zwischen Servern. Zeitfenster statt Dauerfunktion. Zeitraum und Übertragungsinhalt auf der offiziellen Mitteilung prüfen."),
        section("cost", "Kosten & Grenzen", "1000 Quna Basis + 200 pro Charakter. Verarbeitung nur 20-24 Uhr (Serverzeit). Fenster eine Woche."),
        section("when", "Wann wechseln", "Bei unpassender Population/Faktion, wenn die Gilde geht, um Freunde zu erreichen oder bei schlechter Servergesundheit. Nicht nur wegen „Trend“-Servern wechseln."),
        section("limits", "Was nicht übertragen wird", "Gebundene Items, einige Account-Dienste, faktion/regionsgebundene Inhalte, gebundenes Kina. Im Zweifel nur offiziell Garantiertes übertragen."),
        section("global", "Für den globalen Start", "Derzeit asiatische Funktion. Die globale Version (5. Oktober, 5 Server ohne Sperre) senkt den Transferbedarf anfangs."),
      ],
    }),
    es: articleCopy(guideLabels, "es", 5, {
      eyebrow: "TRANSFERENCIAS DE SERVIDOR",
      title: "Transferencia de servidor de Aion 2: cómo funciona y cuándo migrar",
      description: "El parche del 26 de agosto introdujo transferencias limitadas de servidor en el servicio asiático. Funcionamiento, costo y cómo decidir migrar.",
      intro: "Las transferencias de servidor llegaron con el parche «Gran rebalanceo» del 26 de agosto, para mover personajes entre servidores en una ventana limitada. Actualmente en el servicio coreano/taiwanés.",
      sourceNote: "Basado en las notas del 26 de agosto de AION2T y el aviso oficial de NC. Forma actual para el servicio asiático; la versión global puede diferir.",
      keywords: ["Aion 2 transferencia de servidor", "Aion 2 cambiar de servidor", "Aion 2 costo transferencia", "Aion 2 guía transferencia"],
      sections: [
        section("mechanics", "Funcionamiento", "Mueve un personaje (y su progreso) entre servidores. Ventana limitada en vez de servicio permanente. Verifica el período y qué se transfiere en el aviso oficial."),
        section("cost", "Costo y límites", "1000 Quna de base + 200 por personaje. Procesamiento solo entre 20:00 y 24:00 (hora del servidor). Ventana de una semana."),
        section("when", "Cuándo migrar", "Si la población/facción de tu servidor no encaja, si tu gremio se va, para unirte a amigos o si el servidor está en mal estado. No migres solo por servidores «de moda»."),
        section("limits", "Lo que no transfiere", "Objetos vinculados, servicios de cuenta, contenido bloqueado por facción/región, Kina vinculada. En caso de duda, transfiere solo lo que el aviso garantice."),
        section("global", "Para el lanzamiento global", "Función asiática por ahora. La versión global (5 de octubre, 5 servidores sin bloqueo) reduce la necesidad de transferencia al inicio."),
      ],
    }),
    "pt-br": articleCopy(guideLabels, "pt-br", 5, {
      eyebrow: "TRANSFERÊNCIAS DE SERVIDOR",
      title: "Transferência de servidor do Aion 2: como funciona e quando migrar",
      description: "O patch de 26 de agosto introduziu transferências limitadas de servidor no serviço asiático. Funcionamento, custo e como decidir migrar.",
      intro: "As transferências de servidor chegaram com o patch «Grande reequilíbrio» de 26 de agosto, movendo personagens entre servidores em uma janela limitada. Atualmente no serviço coreano/taiwanês.",
      sourceNote: "Baseado nas notas de 26 de agosto da AION2T e no aviso oficial da NC. Forma atual para o serviço asiático; a versão global pode diferir.",
      keywords: ["Aion 2 transferência de servidor", "Aion 2 mudar de servidor", "Aion 2 custo transferência", "Aion 2 guia transferência"],
      sections: [
        section("mechanics", "Funcionamento", "Move um personagem (e seu progresso) entre servidores. Janela limitada em vez de serviço permanente. Verifique o período e o que é transferido no aviso oficial."),
        section("cost", "Custo e limites", "1000 Quna de base + 200 por personagem. Processamento apenas entre 20h e 24h (horário do servidor). Janela de uma semana."),
        section("when", "Quando migrar", "Se a população/facção do seu servidor não encaixa, se sua guilda vai sair, para juntar-se a amigos ou se o servidor está em mau estado. Não migre só por servidores «da moda»."),
        section("limits", "O que não transfere", "Itens vinculados, serviços de conta, conteúdo bloqueado por facção/região, Kina vinculada. Em dúvida, transfira apenas o que o aviso garante."),
        section("global", "Para o lançamento global", "Função asiática por enquanto. A versão global (5 de outubro, 5 servidores sem bloqueio) reduz a necessidade de transferência no início."),
      ],
    }),
    ru: articleCopy(guideLabels, "ru", 5, {
      eyebrow: "ПЕРЕНОС СЕРВЕРОВ",
      title: "Перенос сервера в Aion 2: как работает и когда переезжать",
      description: "Патч от 26 августа ввёл ограниченный перенос серверов на азиатском сервисе. Механика, стоимость и как решить, переезжать ли.",
      intro: "Перенос серверов появился с патчем «Великий ребаланс» от 26 августа, позволяя перемещать персонажа между серверами в ограниченное окно. Сейчас на корейско-тайваньском сервисе.",
      sourceNote: "На основе заметок AION2T от 26 августа и официального уведомления NC. Текущая форма для азиатского сервиса; глобальная может отличаться.",
      keywords: ["Aion 2 перенос сервера", "Aion 2 сменить сервер", "Aion 2 стоимость переноса", "Aion 2 гайд переноса"],
      sections: [
        section("mechanics", "Механика", "Перемещает персонажа (и прогресс) между серверами. Ограниченное окно, а не постоянная услуга. Проверьте период и переносимый контент в официальном уведомлении."),
        section("cost", "Стоимость и лимиты", "1000 Кина база + 200 за персонажа. Обработка только 20:00-24:00 (время сервера). Окно — неделя."),
        section("when", "Когда переезжать", "Если население/фракция сервера не подходит, гильдия уходит, чтобы быть с друзьями, или сервер в плохом состоянии. Не переезжайте только из-за «модных» серверов."),
        section("limits", "Что не переносится", "Привязанные предметы, часть аккаунт-сервисов, контент с фракционной/региональной привязкой, связанная Кина. При сомнении переносите только гарантированное."),
        section("global", "Для глобального запуска", "Пока азиатская функция. Глобальная версия (5 октября, 5 серверов без привязки) снижает потребность в переносе на старте."),
      ],
    }),
    "zh-hant": articleCopy(guideLabels, "zh-hant", 5, {
      eyebrow: "伺服器轉移",
      title: "Aion 2 伺服器轉移：機制與何時遷移",
      description: "8 月 26 日修補程式在亞服引入限時伺服器轉移。以下為該功能機制、費用與如何判斷是否該換服。",
      intro: "伺服器轉移隨 8 月 26 日『大平衡』修補程式上線，讓玩家在限時視窗內跨服轉移角色。該功能目前在韓/台服；本指南解讀已確認機制、費用結構、限制與決策思路（含全球版可能的形態）。",
      sourceNote: "基於 AION2T 8 月 26 日更新說明與 NC 官方伺服器轉移公告。目前形式適用於亞服；全球版 10 月 5 日上線時規則或有不同。",
      keywords: ["Aion 2 伺服器轉移", "Aion 2 換服", "Aion 2 伺服器遷移", "Aion 2 轉移費用", "Aion 2 換服指南"],
      sections: [
        section("mechanics", "功能機制", ["伺服器轉移讓你把角色（及其進度）從一個伺服器移到另一個。8 月 26 日實作為限時視窗而非常駐服務——僅在公布時段內處理。", "操作前務必以官方公告核對目前可用時段與可攜帶內容。"]),
        section("cost", "費用與限制", ["確認定價：每次轉移 1000 金納基礎 + 每角色 200 金納。金納為高級貨幣，轉移並非免費。", "處理時段僅 20:00-24:00（伺服器時間）。", "視窗為期一週，不必首日決定，但也不能拖過截止日。"]),
        section("when", "何時該考慮遷移", ["目前伺服器人口或陣營失衡不符合你的玩法、公會離開而你想追隨、想與另一服好友同玩，或伺服器健康度（排隊/物價/延遲）較差時。", "不要僅為追逐新服或熱度而轉移——費用為真實貨幣且進度遷移，需權衡。"]),
        section("limits", "通常不遷移的內容", ["角色綁定物品、部分帳號級服務、陣營/區域鎖定內容通常不遷移。綁定金納、角色專屬進度與伺服器綁定經濟物品可能留下。", "不確定某物品是否攜帶時，按『不帶』處理。"]),
        section("global", "對全球上線的意義", ["伺服器轉移目前是亞服功能。全球版 10 月 5 日上線，五台伺服器無區域鎖定，初期換服需求低。", "跨服遷移可能在全球服上線後到來，屆時費用結構與處理視窗或類似。", "當下最佳準備是上線時審慎選服，善用無鎖定結構。"]),
      ],
    }),
  },
};