import { articleCopy, localizations, newsLabels, publishedVerified, section } from "./trending-august-27-shared";
import type { ContentEntry, ContentHeroImage, ContentSource } from "./content-registry";

/* ARTICLE 1 — Gamescom 2026 Opening Night Live recap */

const onlRecapSource1: ContentSource = {
  id: "gamesbeat-onl-2026-08-26",
  kind: "third-party", publisher: "GamesBeat",
  label: "NC promotes Aion 2 during Gamescom Opening Night Live ahead of Western early access launch",
  url: "https://gamesbeat.com/nc-promotes-aion-2-during-gamescom-opening-night-live-ahead-of-western-early-access-launch/",
  publishedAt: "2026-08-25",
  retrievedAt: "2026-08-26",
  verifiedAt: "2026-08-26",
  localizations: localizations({
    "zh-hans": "NC 在 Gamescom 开幕之夜现场推介 Aion 2（西服抢先体验前）",
    en: "NC promotes Aion 2 during Gamescom Opening Night Live ahead of Western early access launch",
    fr: "NC promeut Aion 2 à l'Opening Night Live de la Gamescom avant l'accès anticipé occidental",
    de: "NC bewirbt Aion 2 bei der Gamescom Opening Night Live vor dem West-Start des Early Access",
    es: "NC promociona Aion 2 durante el Opening Night Live de la Gamescom antes del acceso anticipado occidental",
    ja: "NC、Gamescom オープニングナイトライブで西側早期アクセス前の Aion 2 をアピール",
    "pt-br": "NC promove Aion 2 no Opening Night Live da Gamescom antes do acesso antecipado ocidental",
    ru: "NC продвигает Aion 2 на Opening Night Live Gamescom перед западным ранним доступом",
    ko: "NC, 서구 조기 접속 앞두고 Gamescom 오프닝 나이트 라이브에서 Aion 2 홍보",
    "zh-hant": "NC 在 Gamescom 開幕之夜現場推介 Aion 2（西服搶先體驗前）",
  }, "https://gamesbeat.com/nc-promotes-aion-2-during-gamescom-opening-night-live-ahead-of-western-early-access-launch/"),
};

const onlRecapSource2: ContentSource = {
  id: "ign-onl-trailer-2026-08-26",
  kind: "third-party", publisher: "IGN",
  label: "Aion 2 - Official Gameplay Trailer | gamescom 2026",
  url: "https://www.ign.com/videos/aion-2-official-gameplay-trailer-gamescom-2026",
  publishedAt: "2026-08-25",
  retrievedAt: "2026-08-26",
  verifiedAt: "2026-08-26",
  localizations: localizations({
    "zh-hans": "Aion 2 - 官方实机预告 | gamescom 2026（IGN）",
    en: "Aion 2 - Official Gameplay Trailer | gamescom 2026",
    fr: "Aion 2 - Bande-annonce de gameplay officielle | gamescom 2026",
    de: "Aion 2 - Offizieller Gameplay-Trailer | gamescom 2026",
    es: "Aion 2 - Tráiler de juego oficial | gamescom 2026",
    ja: "Aion 2 - 公式ゲームプレイトレーラー | gamescom 2026",
    "pt-br": "Aion 2 - Trailer de jogabilidade oficial | gamescom 2026",
    ru: "Aion 2 - Официальный геймплейный трейлер | gamescom 2026",
    ko: "Aion 2 - 공식 게임플레이 트레일러 | gamescom 2026",
    "zh-hant": "Aion 2 - 官方實機預告 | gamescom 2026（IGN）",
  }, "https://www.ign.com/videos/aion-2-official-gameplay-trailer-gamescom-2026"),
};

const onlRecapSource3: ContentSource = {
  id: "steam-aion2-store-2026-08-26",
  kind: "platform", publisher: "Steam",
  label: "AION 2 on Steam",
  url: "https://store.steampowered.com/app/3393110/AION_2/",
  publishedAt: "2026-07-25",
  retrievedAt: "2026-08-26",
  verifiedAt: "2026-08-26",
  localizations: localizations({
    "zh-hans": "Steam 上的 AION 2",
    en: "AION 2 on Steam",
    fr: "AION 2 sur Steam",
    de: "AION 2 bei Steam",
    es: "AION 2 en Steam",
    ja: "Steam の AION 2",
    "pt-br": "AION 2 na Steam",
    ru: "AION 2 в Steam",
    ko: "스팀의 AION 2",
    "zh-hant": "Steam 上的 AION 2",
  }, "https://store.steampowered.com/app/3393110/AION_2/"),
};

const onlRecapHero: ContentHeroImage = {
  src: "https://blogfiles.ncsoft.net/news/af7330da-4ff6-4b58-aece-400e6061a3be.jpg",
  width: 1100, height: 605,
  credit: "NC Corporation",
  sourceUrl: "https://aion2.plaync.com/ko-kr/board/notice",
  rights: "linked-official-media",
  translations: {
    "zh-hans": { alt: "Gamescom 2026 开幕之夜现场回顾配图", caption: "NC 官方配图；Aion 2 于 8 月 25 日亮相开幕之夜现场并带来全新实机预告。" },
    en: { alt: "Gamescom 2026 Opening Night Live recap image", caption: "Official NC artwork; Aion 2 appeared at Opening Night Live on August 25 with a new gameplay trailer." },
    fr: { alt: "Image récapitulative de l'Opening Night Live Gamescom 2026", caption: "Visuel officiel NC ; Aion 2 est apparu à l'Opening Night Live du 25 août avec un nouveau trailer de gameplay." },
    de: { alt: "Bild zur Recap der Gamescom-2026-Opening-Night-Live", caption: "Offizielles NC-Artwork; Aion 2 erschien am 25. August bei der Opening Night Live mit neuem Gameplay-Trailer." },
    es: { alt: "Imagen del resumen del Opening Night Live de Gamescom 2026", caption: "Arte oficial de NC; Aion 2 apareció en el Opening Night Live del 25 de agosto con un nuevo tráiler de juego." },
    ja: { alt: "Gamescom 2026 オープニングナイトライブまとめ画像", caption: "NC公式アートワーク；Aion 2 は8月25日のオープニングナイトライブで新ゲームプレイトレーラーを公開しました。" },
    "pt-br": { alt: "Imagem do resumo do Opening Night Live da Gamescom 2026", caption: "Arte oficial da NC; Aion 2 apareceu no Opening Night Live de 25 de agosto com novo trailer de jogabilidade." },
    ru: { alt: "Обзорное изображение Opening Night Live Gamescom 2026", caption: "Официальный арт NC; Aion 2 появился на Opening Night Live 25 августа с новым геймплейным трейлером." },
    ko: { alt: "Gamescom 2026 오프닝 나이트 라이브 요약 이미지", caption: "NC 공식 이미지입니다. Aion 2는 8월 25일 오프닝 나이트 라이브에서 새 게임플레이 트레일러를 공개했습니다." },
    "zh-hant": { alt: "Gamescom 2026 開幕之夜現場回顧配圖", caption: "NC 官方配圖；Aion 2 於 8 月 25 日亮相開幕之夜現場並帶來全新實機預告。" },
  },
};

export const trendingAugust27Article1: ContentEntry = {
  section: "news",
  slug: "aion-2-gamescom-2026-opening-night-live-recap",
  schemaType: "NewsArticle",
  publishedAt: "2026-08-26",
  updatedAt: "2026-08-26",
  readingMinutes: 5,
  publication: publishedVerified,
  sources: [onlRecapSource1, onlRecapSource2, onlRecapSource3],
  heroImage: onlRecapHero,
  related: [
    { kind: "content", section: "guides", slug: "aion-2-gamescom-2026-trailer-analysis" },
    { kind: "content", section: "news", slug: "gamescom-2026-aion-2-watch-guide" },
    { kind: "content", section: "guides", slug: "aion-2-pre-launch-checklist" },
    { kind: "content", section: "guides", slug: "aion-2-steam-release-guide" },
  ],
  translations: {
    en: articleCopy(newsLabels, "en", 5, {
      eyebrow: "GAMESCOM 2026 RECAP",
      title: "Aion 2 at Gamescom 2026 Opening Night Live: Full Recap",
      description: "NC showcased Aion 2 at Gamescom 2026 Opening Night Live on August 25 with a new official gameplay trailer. Here is everything shown, the launch timeline, and what comes next on the show floor.",
      intro: "Gamescom 2026 Opening Night Live aired on August 25, and Aion 2 had a featured spot. NC used the stage to push the game ahead of the Western early access launch on September 30, pairing a fresh official gameplay trailer with renewed momentum for the free-to-play release. This recap compiles what was shown, what the event confirmed about the launch window, and what to watch for during show floor week.",
      sourceNote: "Based on GamesBeat's Opening Night Live report (August 25), IGN's official gameplay trailer upload, and the AION 2 Steam store page. The free-to-play full launch date remains reported by outlets but unconfirmed by NC.",
      keywords: ["Aion 2 Gamescom 2026 recap", "Aion 2 Opening Night Live", "Aion 2 gameplay trailer", "Aion 2 October 5 launch", "Gamescom 2026 Aion 2"],
      sections: [
        section("onl-highlights", "What NC Showed at Opening Night Live", ["Aion 2 was part of the Gamescom 2026 Opening Night Live broadcast on August 25, in a featured segment designed to build momentum ahead of the Western launch. The centerpiece was a new official gameplay trailer, published on outlets such as IGN, showing the game's hybrid action-flight combat, character customization, and faction PvP in motion — the same pillars NC has emphasized in its community livestreams.", "No brand-new system was announced during the segment; instead, the trailer condensed the confirmed pitch: PC through Steam and PURPLE, eight launch classes, reworked dungeons and PvP, and the five global server regions. For players, the value of the segment was less a big reveal and more a signal — NC is using its biggest Western stage before launch to push Aion 2.", "Gamescom's main show floor opened on August 26 in Cologne and runs through August 30, with NC's presence confirmed for the event. On-floor details such as playable demos had not been formally detailed as of this write-up."]),
        section("launch-timeline", "The Launch Timeline After Gamescom", ["The event gave NC another moment to repeat what is already confirmed: Founder's Packs are on sale with three tiers, include early access and a 30-day membership, and early access begins September 30. That five-day window runs before the game opens to all players as a free-to-play release.", "What remains in flux is the full-launch date. Multiple outlets, including MMORPG.com, have reported the free-to-play global launch is expected on October 5, and the Steam listing points to that date — but NC has not formally named a full-launch date or opening hour, with official materials still listing only a broader September window.", "Until NC publishes a single authoritative notice, treat September 30 early access as the fixed anchor and October 5 as the widely reported, unconfirmed free-to-play date."]),
        section("show-floor", "Show Floor Week: August 26-30", ["With Opening Night Live done, attention moves to the Gamescom floor in Cologne from August 26 to 30. NC's attendance covers the event as a whole, and the company said its ONL slot was meant to connect with players worldwide ahead of the global launch.", "On-floor coverage — hands-on impressions, booth photos, and interviews — typically appears on gaming press channels throughout the week. For players who cannot attend, the practical result is usually a stream of screenshots and videos that clarify how the current global build actually feels.", "We will continue tracking Gamescom week coverage and update this report if NC confirms demos, additional live segments, or any launch-date details from the floor."]),
        section("global-context", "Why the Momentum Matters", ["Aion 2 has been a major driver of NC's recent results: the company reported PC game revenue up about 210% year-over-year in Q1 2026, reaching roughly $223 million, following the game's Korean and Taiwanese release in November 2025.", "For the global rollout, NC has identified North America, South America, Europe, and Japan as service regions, with five servers and no regional locks confirmed. The global build is not a direct copy of the Asian version — dungeon party sizes, the first raid tier, battlegrounds, and other systems were adjusted for the Western audience.", "With the September 30 early access roughly five weeks away at the time of writing, Gamescom was effectively the last big marketing beat before launch."]),
        section("whats-next", "What to Watch Next", ["The two announcements players care about most are still pending: an official full-launch date and opening hour for the free-to-play release, and the final server list with names and regions. NC has confirmed neither.", "Preload timing and download details for the 100 GB client are also unannounced, though our client and pre-download guide covers what is known so far. Watch NC's official channels and the AION 2 Steam page — any launch-date change will land there first.", "Bookmark the KINA news hub for day-one coverage of every Gamescom week announcement."]),
      ],
    }),
    "zh-hans": articleCopy(newsLabels, "zh-hans", 5, {
      eyebrow: "GAMESCOM 2026 回顾",
      title: "Aion 2 亮相 Gamescom 2026 开幕之夜现场：完整回顾",
      description: "NC 于 8 月 25 日在 Gamescom 2026 开幕之夜现场展示 Aion 2 并发布全新官方实机预告。以下为全部看点、发布节奏与展馆周后续安排。",
      intro: "Gamescom 2026 开幕之夜现场于 8 月 25 日播出，Aion 2 占据重要位置。NC 在 9 月 30 日西服抢先体验前借该舞台造势，并带来了全新的官方实机预告。本回顾汇总所有看点、发布窗口信息与展馆周的关注内容。",
      sourceNote: "基于 GamesBeat 8 月 25 日开幕之夜现场报道、IGN 官方实机预告发布及 AION 2 Steam 商店页。免费游玩正式上线日期仍为媒体报道、NC 未正式确认。",
      keywords: ["Aion 2 Gamescom 2026 回顾", "Aion 2 开幕之夜现场", "Aion 2 实机预告", "Aion 2 10月5日上线", "Gamescom 2026 Aion 2"],
      sections: [
        section("onl-highlights", "开幕之夜现场展示了什么", ["Aion 2 在 8 月 25 日的开幕之夜现场获得重点推介，核心是一支全新官方实机预告，展示了混合空战、角色自定义与阵营 PvP。", "现场没有公布全新系统，而是强化既有卖点：Steam/PURPLE 双平台、八职业、重构副本与 PvP、五大服务器区域。"]),
        section("launch-timeline", "科隆展后的发布节奏", ["已确认：创始人包三档在售、含抢先体验与 30 天会员，9 月 30 日开始提前 5 天游玩。", "免费游玩正式上线日期仍待官方确认——MMORPG.com 等媒体与 Steam 页面指向 10 月 5 日，但 NC 未正式公布。"]),
        section("show-floor", "展馆周（8月26-30日）", ["科隆展馆于 8 月 26 日开放至 30 日，NC 确认参展。现场试玩等细节尚未正式公布。", "本周各游戏媒体将放出上手体验、展台实拍与访谈，可在线上跟进。"]),
        section("global-context", "造势背后的意义", ["Aion 2 是 NC 近期的业绩主力：2026 年 Q1 PC 游戏收入同比增长约 210%（约 2.23 亿美元），该游戏于 2025 年 11 月在韩国与台湾上线。", "全球版服务区域为北美、南美、欧洲与日本，五台服务器无区域锁定；副本人数、首个团队本、战场等系统均为西方玩家调整。"]),
        section("whats-next", "接下来关注什么", ["玩家最关心的两项尚未公布：免费游玩的正式上线日期与开放时间、最终服务器列表。", "100 GB 客户端的预载时间也未公布，可关注 NC 官方渠道与 Steam 页面。请收藏 KINA 新闻中心获取科隆周第一手报道。"]),
      ],
    }),
    ko: articleCopy(newsLabels, "ko", 5, {
      eyebrow: "게임스컴 2026 요약",
      title: "Gamescom 2026 오프닝 나이트 라이브의 Aion 2: 전체 요약",
      description: "NC는 8월 25일 Gamescom 2026 오프닝 나이트 라이브에서 Aion 2를 소개하며 새 공식 게임플레이 트레일러를 공개했습니다. 공개된 내용, 출시 타임라인, 전시장 다음 일정을 정리합니다.",
      intro: "Gamescom 2026 오프닝 나이트 라이브가 8월 25일에 방송됐고, Aion 2가 주요 자리를 차지했습니다. NC는 9월 30일 서구 조기 접속을 앞두고 새 게임플레이 트레일러로 분위기를 끌어올렸습니다.",
      sourceNote: "GamesBeat의 오프닝 나이트 라이브 보도(8/25), IGN의 게임플레이 트레일러, Steam 스토어 페이지 기반. 정식 무료 출시일은 미확정(보도 수준).",
      keywords: ["Aion 2 Gamescom 2026 요약", "Aion 2 오프닝 나이트 라이브", "Aion 2 게임플레이 트레일러", "Aion 2 10월 5일 출시", "Gamescom 2026 Aion 2"],
      sections: [
        section("onl-highlights", "오프닝 나이트 라이브에서 공개된 것", ["Aion 2는 8월 25일 오프닝 나이트 라이브에서 중점적으로 소개됐으며, 혼합 공중 전투·캐릭터 커스터마이징·진영 PvP를 보여주는 공식 게임플레이 트레일러가 핵심이었습니다.", "신규 시스템 발표는 없었고, Steam/PURPLE PC 출시·8개 클래스·재설계된 던전과 PvP·5개 서버 지역 등 기존 확정 내용이 집약됐습니다."]),
        section("launch-timeline", "게임스컴 이후 출시 일정", ["확정된 부분: 파운더스 팩 3종 판매 중, 30일 멤버십 포함, 9월 30일부터 5일 조기 접속.", "무료 플레이 정식 출시일은 미확정 — MMORPG.com 등과 Steam은 10월 5일으로 보도하지만 NC 공식 확인은 없습니다."]),
        section("show-floor", "전시장 주간 (8/26~30)", ["쾰른 전시장은 8월 26일부터 30일까지 열리며 NC 참가가 확인됐습니다. 실기 데모 등 세부사항은 미공개.", "게임 언론의 체험기·부스 사진·인터뷰가 주간 내내 올라올 예정입니다."]),
        section("global-context", "이런 분위기가 중요한 이유", ["Aion 2는 NC 최근 실적의 핵심입니다: 2026 Q1 PC 게임 매출이 전년 대비 약 210% 증가(약 2.23억 달러), 2025년 11월 한국·대만 출시 이후.", "글로벌 서비스 지역은 북미·남미·유럽·일본이고 5개 서버에 지역 잠금이 없습니다. 던전 인원·첫 레이드·배틀그라운드 등이 서구권에 맞게 조정됐습니다."]),
        section("whats-next", "다음 주목 포인트", "무료 플레이 정식 출시일과 개시 시각, 최종 서버 목록(이름·지역)이 아직 미발표입니다. 100GB 클라이언트 선다운로드 시점도 미정입니다. KINA 뉴스 허브에서 게임스컴 주간 소식을 확인하세요."),
      ],
    }),
    ja: articleCopy(newsLabels, "ja", 5, {
      eyebrow: "ゲームズコム2026振り返り",
      title: "Gamescom 2026 オープニングナイトライブの Aion 2：完全まとめ",
      description: "NC は8月25日の Gamescom 2026 オープニングナイトライブで Aion 2 を紹介し、新しい公式ゲームプレイトレーラーを公開しました。内容、ローンチ時期、展示会の今後の予定をまとめます。",
      intro: "Gamescom 2026 オープニングナイトライブは8月25日に放送され、Aion 2 が大きな扱いを受けました。NC は9月30日の西側早期アクセスを前に、新トレーラーで勢いを高めました。",
      sourceNote: "GamesBeat の報道（8/25）、IGN の公式トレーラー、Steam ストアページに基づきます。無料プレイ正式リリース日は報道のみで未確認です。",
      keywords: ["Aion 2 Gamescom 2026 まとめ", "Aion 2 オープニングナイトライブ", "Aion 2 ゲームプレイトレーラー", "Aion 2 10月5日", "Gamescom 2026 Aion 2"],
      sections: [
        section("onl-highlights", "オープニングナイトライブで公開されたもの", ["Aion 2 は8月25日のオンラインライブで重点紹介され、新しい公式ゲームプレイトレーラーが公開されました。ハイブリッド空戦・キャラカスタマイズ・陣営PvPが描かれています。", "新システムの発表はなく、Steam/PURPLE での PC 展開・8クラス・リワークされたダンジョンとPvP・5つのサーバー地域などの既存の確認事項が凝縮されました。"]),
        section("launch-timeline", "ゲームズコム後のリリース時期", ["確定：ファウンダーズパック3種販売中、30日メンバーシップ込み、9月30日から5日間の早期アクセス。", "無料プレイ正式リリース日は未確定 — MMORPG.com などと Steam は10月5日と報じますが、NC は正式発表していません。"]),
        section("show-floor", "展示会週（8/26〜30）", ["ケルンの展示会は8月26日から30日まで開催され、NC の参加が確認されています。試遊デモなどの詳細は未発表。", "ゲームメディアのハンズオンやブース写真、インタビューが週を通して出る見込みです。"]),
        section("global-context", "この流れが重要な理由", ["Aion 2 は NC の直近業績の柱です：2026年Q1のPCゲーム収益は前年比約210%増（約2.23億ドル）、2025年11月の韓国・台湾リリース後。", "グローバルサービス地域は北米・南米・欧州・日本、5サーバーで地域ロックなし。ダンジョン人数・最初のレイド・バトルグラウンドなどは西側向けに調整済みです。"]),
        section("whats-next", "次に注目すべきこと", "無料プレイ正式リリース日と開始時刻、最終サーバーリスト（名前・地域）が未発表です。100GB クライアントの事前DL時期も未定。KINA ニュースハブでゲームズコム週の情報をチェックしてください。"),
      ],
    }),
    fr: articleCopy(newsLabels, "fr", 5, {
      eyebrow: "RÉSUMÉ GAMESCOM 2026",
      title: "Aion 2 à l'Opening Night Live de la Gamescom 2026 : le récapitulatif complet",
      description: "NC a présenté Aion 2 à l'Opening Night Live de la Gamescom 2026 le 25 août avec un nouveau trailer de gameplay officiel. Tout ce qui a été montré, le calendrier de lancement et la suite.",
      intro: "L'ONL a été diffusé le 25 août avec Aion 2 en vedette, avant l'accès anticipé occidental du 30 septembre.",
      sourceNote: "Basé sur le rapport GamesBeat (25/08), le trailer IGN et la page Steam. La date de sortie F2P reste non confirmée par NC.",
      keywords: ["Aion 2 Gamescom 2026 récap", "Aion 2 Opening Night Live", "Aion 2 trailer gameplay", "Aion 2 5 octobre", "Gamescom 2026 Aion 2"],
      sections: [
        section("onl-highlights", "Ce que NC a montré", ["Aion 2 a eu une place de choix à l'ONL du 25 août, avec un nouveau trailer de gameplay officiel montrant le combat hybride action-vol, la personnalisation et le PvP de faction.", "Aucun nouveau système n'a été annoncé - le segment a consolidé le pitch déjà confirmé."]),
        section("launch-timeline", "Le calendrier après Gamescom", ["Confirmé : packs Fondateur en vente, accès anticipé le 30 septembre pendant 5 jours.", "La date du lancement F2P reste non confirmée - MMORPG.com et Steam indiquent le 5 octobre."]),
        section("show-floor", "Semaine salon (26-30 août)", ["Le salon ouvre le 26 août à Cologne. La présence NC est confirmée pour l'événement.", "Les médias publieront des impressions et photos tout au long de la semaine."]),
        section("global-context", "Pourquoi c'est important", ["Aion 2 a porté les résultats de NC : revenus PC +210% en glissement annuel au T1 2026 (~223 M$).", "Régions : Amérique du Nord/Sud, Europe, Japon ; 5 serveurs sans verrouillage régional."]),
        section("whats-next", "À suivre", "Date et heure de lancement F2P officielles, liste des serveurs, et timing de préchargement restent à annoncer. Suivez le hub KINA."),
      ],
    }),
    de: articleCopy(newsLabels, "de", 5, {
      eyebrow: "GAMESCOM-2026-RECAP",
      title: "Aion 2 bei der Gamescom 2026 Opening Night Live: kompletter Rückblick",
      description: "NC präsentierte Aion 2 am 25. August bei der Gamescom 2026 Opening Night Live mit einem neuen offiziellen Gameplay-Trailer. Alle Highlights, Launch-Termine und Ausblick.",
      intro: "Die ONL lief am 25. August mit Aion 2 in prominenter Rolle, vor dem Western-Early-Access am 30. September.",
      sourceNote: "Basierend auf dem GamesBeat-Bericht (25.08.), dem IGN-Trailer und der Steam-Seite. Das F2P-Release-Datum bleibt von NC unbestätigt.",
      keywords: ["Aion 2 Gamescom 2026 Rückblick", "Aion 2 Opening Night Live", "Aion 2 Gameplay-Trailer", "Aion 2 5. Oktober", "Gamescom 2026 Aion 2"],
      sections: [
        section("onl-highlights", "Was NC zeigte", ["Aion 2 hatte einen prominenten Platz in der ONL vom 25. August, mit einem neuen offiziellen Gameplay-Trailer zu Action-Flug-Kampf, Anpassung und Fraktions-PvP.", "Es gab keine neuen Systemankündigungen - das Segment festigte das bereits bestätigte Konzept."]),
        section("launch-timeline", "Launch-Zeitplan nach Gamescom", ["Bestätigt: Founder's Packs im Verkauf, Early Access ab 30. September für 5 Tage.", "Das F2P-Release-Datum bleibt unbestätigt - MMORPG.com und Steam nennen den 5. Oktober."]),
        section("show-floor", "Messewoche (26.-30. August)", ["Die Messe öffnet am 26. August in Köln. NC-Präsenz ist für das Event bestätigt.", "Die Presse veröffentlicht die Woche über Hands-on-Eindrücke und Fotos."]),
        section("global-context", "Warum das Momentum zählt", ["Aion 2 trug maßgeblich zu NCs Ergebnissen bei: PC-Umsatz +210% im Jahresvergleich im Q1 2026 (~223 Mio. US-$).", "Regionen: Nord-/Südamerika, Europa, Japan; 5 Server ohne regionale Sperren."]),
        section("whats-next", "Als Nächstes", "Offizielles F2P-Release-Datum und Eröffnungszeit, Serverliste und Preload-Timing stehen noch aus. Bleiben Sie über den KINA-Hub informiert."),
      ],
    }),
    es: articleCopy(newsLabels, "es", 5, {
      eyebrow: "RESUMEN GAMESCOM 2026",
      title: "Aion 2 en el Opening Night Live de Gamescom 2026: resumen completo",
      description: "NC mostró Aion 2 en el Opening Night Live de Gamescom 2026 del 25 de agosto con un nuevo tráiler de juego oficial. Todo lo mostrado, el calendario de lanzamiento y lo que viene.",
      intro: "El ONL se emitió el 25 de agosto con Aion 2 en un lugar destacado, antes del acceso anticipado occidental del 30 de septiembre.",
      sourceNote: "Basado en el informe de GamesBeat (25/08), el tráiler de IGN y la página de Steam. La fecha de lanzamiento F2P sigue sin confirmar por NC.",
      keywords: ["Aion 2 Gamescom 2026 resumen", "Aion 2 Opening Night Live", "Aion 2 tráiler gameplay", "Aion 2 5 de octubre", "Gamescom 2026 Aion 2"],
      sections: [
        section("onl-highlights", "Lo que mostró NC", ["Aion 2 tuvo un lugar destacado en el ONL del 25 de agosto, con un nuevo tráiler de juego oficial mostrando combate híbrido acción-vuelo, personalización y PvP de facción.", "No se anunciaron sistemas nuevos: el segmento consolidó la propuesta ya confirmada."]),
        section("launch-timeline", "El calendario tras Gamescom", ["Confirmado: paquetes de fundador a la venta, acceso anticipado el 30 de septiembre durante 5 días.", "La fecha del lanzamiento F2P sigue sin confirmar: MMORPG.com y Steam apuntan al 5 de octubre."]),
        section("show-floor", "Semana del salón (26-30 de agosto)", "El salón abre el 26 de agosto en Colonia. La presencia de NC está confirmada para el evento. Los medios publicarán impresiones y fotos durante la semana."),
        section("global-context", "Por qué importa", "Aion 2 impulsó los resultados de NC: ingresos de PC +210 % interanual en el Q1 2026 (~223 M$). Regiones: Norteamérica, Sudamérica, Europa y Japón; 5 servidores sin bloqueo regional."),
        section("whats-next", "Qué sigue", "Fecha y hora oficiales del lanzamiento F2P, lista de servidores y timing de precarga siguen pendientes. Sigue el hub de KINA."),
      ],
    }),
    "pt-br": articleCopy(newsLabels, "pt-br", 5, {
      eyebrow: "RESUMO GAMESCOM 2026",
      title: "Aion 2 no Opening Night Live da Gamescom 2026: resumo completo",
      description: "A NC mostrou Aion 2 no Opening Night Live da Gamescom 2026 em 25 de agosto com um novo trailer oficial de jogabilidade. Tudo o que foi mostrado, o cronograma de lançamento e o que vem a seguir.",
      intro: "O ONL foi ao ar em 25 de agosto com Aion 2 em destaque, antes do acesso antecipado ocidental em 30 de setembro.",
      sourceNote: "Baseado no relatório da GamesBeat (25/08), no trailer da IGN e na página da Steam. A data do lançamento F2P segue não confirmada pela NC.",
      keywords: ["Aion 2 Gamescom 2026 resumo", "Aion 2 Opening Night Live", "Aion 2 trailer gameplay", "Aion 2 5 de outubro", "Gamescom 2026 Aion 2"],
      sections: [
        section("onl-highlights", "O que a NC mostrou", "Aion 2 teve um espaço de destaque no ONL de 25 de agosto, com um novo trailer oficial de jogabilidade mostrando combate híbrido ação-voo, personalização e PvP de facção. Nenhum sistema novo foi anunciado."),
        section("launch-timeline", "O cronograma após a Gamescom", "Confirmado: pacotes de fundador à venda, acesso antecipado em 30 de setembro por 5 dias. A data do lançamento F2P segue não confirmada — MMORPG.com e a Steam apontam para 5 de outubro."),
        section("show-floor", "Semana do salão (26-30 de agosto)", "O salão abre em 26 de agosto em Colônia. A presença da NC está confirmada. A imprensa publicará impressões e fotos durante a semana."),
        section("global-context", "Por que isso importa", "Aion 2 impulsionou os resultados da NC: receita de PC +210% na comparação anual no Q1 2026 (~US$ 223 mi). Regiões: América do Norte/Sul, Europa e Japão; 5 servidores sem bloqueio regional."),
        section("whats-next", "O que vem a seguir", "Data e hora oficiais do lançamento F2P, lista de servidores e o momento do pré-carregamento seguem pendentes. Acompanhe o hub da KINA."),
      ],
    }),
    ru: articleCopy(newsLabels, "ru", 5, {
      eyebrow: "ИТОГИ GAMESCOM 2026",
      title: "Aion 2 на Opening Night Live Gamescom 2026: полный обзор",
      description: "NC показала Aion 2 на Opening Night Live Gamescom 2026 25 августа с новым официальным геймплейным трейлером. Всё показанное, сроки запуска и дальнейшие планы.",
      intro: "ONL прошло 25 августа с Aion 2 в центре внимания — перед западным ранним доступом 30 сентября.",
      sourceNote: "На основе отчёта GamesBeat (25.08), трейлера IGN и страницы Steam. Дата F2P-запуска остаётся неподтверждённой.",
      keywords: ["Aion 2 Gamescom 2026 обзор", "Aion 2 Opening Night Live", "Aion 2 геймплейный трейлер", "Aion 2 5 октября", "Gamescom 2026 Aion 2"],
      sections: [
        section("onl-highlights", "Что показала NC", "Aion 2 получила заметное место на ONL 25 августа с новым официальным геймплейным трейлером: гибридный воздушно-боевой геймплей, кастомизация и фракционный PvP. Новых систем не анонсировали."),
        section("launch-timeline", "Сроки после Gamescom", "Подтверждено: наборы основателя в продаже, ранний доступ с 30 сентября на 5 дней. Дата F2P-запуска не подтверждена — MMORPG.com и Steam указывают на 5 октября."),
        section("show-floor", "Выставочная неделя (26–30 августа)", "Выставочные залы открываются 26 августа в Кёльне. Присутствие NC подтверждено. Пресса публикует впечатления и фото всю неделю."),
        section("global-context", "Почему это важно", "Aion 2 — ключевой драйвер результатов NC: выручка в PC-сегменте выросла на ~210% г/г в Q1 2026 (~$223 млн). Регионы: Северная/Южная Америка, Европа, Япония; 5 серверов без региональной привязки."),
        section("whats-next", "Что дальше", "Официальные дата и время F2P-запуска, список серверов и сроки предзагрузки пока не объявлены. Следите за хабом KINA."),
      ],
    }),
    "zh-hant": articleCopy(newsLabels, "zh-hant", 5, {
      eyebrow: "GAMESCOM 2026 回顧",
      title: "Aion 2 亮相 Gamescom 2026 開幕之夜現場：完整回顧",
      description: "NC 於 8 月 25 日在 Gamescom 2026 開幕之夜現場展示 Aion 2 並發布全新官方實機預告。以下為全部看點、發布節奏與展館週後續安排。",
      intro: "Gamescom 2026 開幕之夜現場於 8 月 25 日播出，Aion 2 佔據重要位置。NC 在 9 月 30 日西服搶先體驗前藉該舞台造勢，並帶來了全新的官方實機預告。本回顧彙總所有看點、發布窗口資訊與展館週的關注內容。",
      sourceNote: "基於 GamesBeat 8 月 25 日開幕之夜現場報導、IGN 官方實機預告發布及 AION 2 Steam 商店頁。免費遊玩正式上線日期仍為媒體報導、NC 未正式確認。",
      keywords: ["Aion 2 Gamescom 2026 回顧", "Aion 2 開幕之夜現場", "Aion 2 實機預告", "Aion 2 10月5日上線", "Gamescom 2026 Aion 2"],
      sections: [
        section("onl-highlights", "開幕之夜現場展示了什麼", ["Aion 2 在 8 月 25 日的開幕之夜現場獲得重點推介，核心是一支全新官方實機預告，展示了混合空戰、角色自訂與陣營 PvP。", "現場沒有公布全新系統，而是強化既有賣點：Steam/PURPLE 雙平台、八職業、重構副本與 PvP、五大伺服器區域。"]),
        section("launch-timeline", "科隆展後的發布節奏", ["已確認：創始人包三檔在售、含搶先體驗與 30 天會員，9 月 30 日開始提前 5 天遊玩。", "免費遊玩正式上線日期仍待官方確認——MMORPG.com 等媒體與 Steam 頁面指向 10 月 5 日，但 NC 未正式公布。"]),
        section("show-floor", "展館週（8月26-30日）", ["科隆展館於 8 月 26 日開放至 30 日，NC 確認參展。現場試玩等細節尚未正式公布。", "本週各遊戲媒體將放出上手體驗、展台實拍與訪談，可在線上跟進。"]),
        section("global-context", "造勢背後的意義", ["Aion 2 是 NC 近期的業績主力：2026 年 Q1 PC 遊戲收入年增約 210%（約 2.23 億美元），該遊戲於 2025 年 11 月在韓國與台灣上線。", "全球版服務區域為北美、南美、歐洲與日本，五台伺服器無區域鎖定；副本人數、首個團隊本、戰場等系統均為西方玩家調整。"]),
        section("whats-next", "接下來關注什麼", ["玩家最關心的兩項尚未公布：免費遊玩的正式上線日期與開放時間、最終伺服器列表。", "100 GB 用戶端的預載時間也未公布，可關注 NC 官方管道與 Steam 頁面。請收藏 KINA 新聞中心獲取科隆週第一手報導。"]),
      ],
    }),
  },
};