import { articleCopy, localizations, guideLabels, publishedVerified, section } from "./trending-september-15-shared";
import type { ContentEntry, ContentHeroImage, ContentSource } from "./content-registry";

/* ARTICLE 3 — Story & chapter progression guide: narrative chapters, story missions */

const storySource: ContentSource = {
  id: "nc-aion2-story",
  kind: "official",
  publisher: "NC Corporation",
  label: "Aion 2 Story and Gameplay",
  url: "https://aion2.plaync.com/en-us/gameplay/",
  publishedAt: "2026-08-15",
  retrievedAt: "2026-09-15",
  verifiedAt: "2026-09-15",
  localizations: localizations({
    "zh-hans": "Aion 2 剧情与游戏内容",
    en: "Aion 2 Story and Gameplay",
    fr: "Aion 2 Histoire et Gameplay",
    de: "Aion 2 Story und Gameplay",
    es: "Aion 2 Historia y Jugabilidad",
    ja: "Aion 2 ストーリーとゲームプレイ",
    "pt-br": "Aion 2 História e Gameplay",
    ru: "Aion 2 Сюжет и Геймплей",
    ko: "Aion 2 스토리와 게임플레이",
    "zh-hant": "Aion 2 劇情與遊戲內容",
  }, "https://aion2.plaync.com/en-us/gameplay/"),
};

const storyHero: ContentHeroImage = {
  src: "https://blogfiles.ncsoft.net/news/af7330da-4ff6-4b58-aece-400e6061a3be.jpg",
  width: 1200, height: 630,
  credit: "NC Corporation",
  sourceUrl: "https://aion2.plaync.com/en-us/",
  rights: "linked-official-media",
  translations: {
    "zh-hans": { alt: "Aion 2 剧情章节攻略横幅", caption: "Aion 2 的故事系统为游戏世界提供丰富上下文。章节式叙事和主线任务将玩家带入永恒的天空。" },
    en: { alt: "Aion 2 Story and chapter progression guide banner", caption: "Aion 2's story system provides rich context for the game world. Chapter-based narrative and main missions take players into the eternal sky." },
    fr: { alt: "Bannière du guide d'avancement narratif d'Aion 2", caption: "Le système narratif d'Aion 2 offre un contexte riche pour le monde du jeu. La narration par chapitres et les quêtes principales emmènent les joueurs dans le ciel éternel." },
    de: { alt: "Banner zum Story-Fortschrittsguide von Aion 2", caption: "Das Story-System von Aion 2 bietet reichhaltige Kontexte für die Spielwelt. Die Kapitel-Narration und Hauptquests nehmen Spieler in den ewigen Himmel mit." },
    es: { alt: "Banner de la guía de progreso narrativo de Aion 2", caption: "El sistema de historia de Aion 2 proporciona un contexto rico para el mundo del juego. La narrativa por capítulos y misiones principales toman a los jugadores al cielo eterno." },
    ja: { alt: "Aion 2 ストーリー進捗ガイドバナー", caption: "Aion 2のストーリーシステムはゲーム世界に豊かな文脈を提供します。章構成のストーリーとメインクエストがプレイヤーを永遠の空へ導きます。" },
    "pt-br": { alt: "Banner da guia de progresso da história do Aion 2", caption: "O sistema de história do Aion 2 fornece um contexto rico para o mundo do jogo. A narrativa por capítulos e as missões principais levam os jogadores ao céu eterno." },
    ru: { alt: "Баннер гайда по сюжетному прогрессу Aion 2", caption: "Сюжетная система Aion 2 предоставляет богатый контекст для игрового мира. Главоподобная нарративная структура и основные квесты ведут игроков в вечное небо." },
    ko: { alt: "Aion 2 스토리 진행 가이드 배너", caption: "Aion 2의 스토리 시스템은 게임 세계에 풍부한 맥락을 제공합니다. 챕터 기반 서사 구조와 메인 미션이 플레이어를 영원의 하늘로 이끕니다." },
    "zh-hant": { alt: "Aion 2 劇情章節攻略橫幅", caption: "Aion 2 的故事系統為遊戲世界提供豐富上下文。章節式敘事和主線任務將玩家帶入永恆的天空。" },
  },
};

export const trendingSeptember15Article3: ContentEntry = {
  section: "guides",
  slug: "aion-2-story-chapter-progression-guide",
  schemaType: "Article",
  publishedAt: "2026-09-15",
  updatedAt: "2026-09-15",
  readingMinutes: 6,
  publication: publishedVerified,
  sources: [storySource],
  heroImage: storyHero,
  related: [
    { kind: "content", section: "guides", slug: "aion-2-daily-weekly-routine-guide" },
    { kind: "content", section: "guides", slug: "aion-2-leveling-guide-1-50" },
    { kind: "content", section: "guides", slug: "aion-2-solo-player-guide" },
    { kind: "content", section: "guides", slug: "aion-2-trials-raids-guide" },
  ],
  translations: {
    en: articleCopy(guideLabels, "en", 6, {
      eyebrow: "Story",
      title: "Aion 2 Story and Chapter Progression Guide: Main Quests, Narrative Chapters, and How to Maximize Your Adventure",
      description: "Understand how Aion 2's story system works — narrative chapters, main quests, side missions, and chapter-based progression. Learn which story paths to prioritize and how to extract maximum experience and rewards from the narrative content.",
      intro: "Aion 2's story system is designed to be a guided experience that introduces you to the world, its mechanics, and its factions. The chapter-based narrative structure delivers a carefully paced story while integrating gameplay systems — combat, gathering, crafting, and PvP — into the progression flow. Understanding how chapters and quests work helps you progress faster and enjoy the narrative more deeply.",
      sourceNote: "Based on NC's official gameplay pages and the Korean service story structure as of September 2026. Global version chapter structure may be adjusted for the modified Season 1 progression curve.",
      keywords: ["Aion 2 story guide", "Aion 2 chapter progression", "Aion 2 main quests", "Aion 2 narrative guide", "Aion 2 story missions"],
      sections: [
        section("story-overview", "The Story Framework: Chapters and Quests", ["Aion 2's narrative is organized into chapters — each chapter covers a story arc with its own set of main quests and side missions. Chapters advance the story while introducing new areas, mechanics, and systems. Completing chapter main quests unlocks the next chapter and often new gameplay features.", "Main quests are the core narrative spine of each chapter. They are linear and guide you through story-critical encounters, boss fights, and lore discoveries. Side missions branch off from the main quest chain and offer alternative perspectives, additional context, or bonus rewards.", "Each chapter typically spans 2-4 hours of playtime and covers one thematic area. Chapter 1 focuses on the basics of character creation and early game systems. Subsequent chapters explore faction politics, the world's conflicts, and the mechanics that define Aion 2's endgame."]),
        section("main-quests", "Main Quest Chains: Your Guided Path", ["Main quests are designed to be the backbone of progression. Each main quest gives you experience, unlocks new features, and moves you toward the endgame. Unlike side quests, main quests are always worth your time — they're the path of least resistance to maximum progress.", "Main quest chains are sequenced: complete Chapter 1 to unlock Chapter 2, Chapter 2 to unlock Chapter 3, and so on. This linear structure ensures you have the necessary tools, gear, and knowledge before encountering more demanding content.", "As you progress through chapters, main quests increasingly require group participation. Later chapters introduce siege warfare, faction events, and dungeon content that expect multiple players. Having guildmates or friends for these chapters makes the experience smoother and more rewarding."]),
        section("side-quests", "Side Missions: Depth and Additional Rewards", ["Side missions are the narrative depth of Aion 2. They expand on chapter themes, introduce NPC lore, and provide alternative story perspectives. Some side missions unlock unique dialogue options, character insights, or bonus rewards not available through the main path.", "Side missions vary in commitment — some are quick 5-10 minute encounters that offer minor rewards, while others are multi-step chains that require exploration, combat, or gathering. The experience reward per time invested is generally lower than main quests, but the narrative depth is unmatched.", "For time-critical players, prioritize side missions that offer exclusive rewards, unlock hidden content, or provide lore that enriches the endgame story. Side missions that simply repeat a theme without adding new information can be safely skipped."]),
        section("progression-strategy", "Progression Strategy: Chapters to Levels", ["Aion 2 uses a modified Season 1 progression curve for global launch. Chapters unlock new levels and areas at a faster pace than the original Korean service. The global version aims to have players reach endgame levels within 5-10 hours of focused play.", "Each chapter corresponds to a level range. Completing all main quests in a chapter typically levels you to the next range. However, side missions and optional activities can accelerate this — players who do all content in each chapter will level faster but spend more time in each story segment.", "For the fastest path to endgame, focus on main quests and skip optional side content. You can always return to chapters later to complete side missions once you're in endgame gear. The story doesn't have irreversible choices — you can always go back and fill in the gaps."]),
        section("endgame-stories", "Endgame Stories and Content", ["Once you reach endgame levels, the story doesn't stop. Endgame chapters introduce new narrative arcs — faction escalation, cross-server events, seasonal stories, and character-specific storylines. These are accessed through in-game NPCs and the campaign hub.", "Endgame story content is designed for players who have already established their character's core progression. It requires endgame gear and group play, and it delivers rewards that are competitive with endgame PvP and dungeon content.", "For global launch, expect the same endgame story framework with potential pacing adjustments. The modified Season 1 curve means you'll reach endgame stories earlier than Korean service players did, but the story content itself remains equally rich."]),
      ],
    }),
    "zh-hans": articleCopy(guideLabels, "zh-hans", 6, {
      eyebrow: "剧情",
      title: "Aion 2 剧情章节攻略：主线任务、叙事章节与冒险最大化",
      description: "了解 Aion 2 剧情系统的工作原理——叙事章节、主线任务、支线任务和章节式进阶。学习哪些剧情路线应优先推进，以及如何从叙事内容中获得最大经验和奖励。",
      intro: "Aion 2 的剧情系统旨在提供引导式体验，向你介绍世界、机制和阵营。章节式叙事结构在融入游戏系统（战斗、采集、制作、PvP）的同时，提供精心把控节奏的故事。理解章节和任务的工作方式可以帮助你更快进阶并更深刻地享受叙事。",
      sourceNote: "基于 NC 官方游戏页面和韩服剧情结构（截至 2026 年 9 月）。全球版章节结构可能为改良版 Season 1 进阶曲线做调整。",
      keywords: ["Aion 2 剧情攻略", "Aion 2 章节进阶", "Aion 2 主线任务", "Aion 2 叙事指南", "Aion 2 剧情任务"],
      sections: [
        section("story-overview", "剧情框架：章节与任务", ["Aion 2 的叙事按章节组织——每个章节覆盖一段故事弧线，配有自己的主线任务和支线任务集。章节推进故事同时引入新区域、机制和系统。完成章节主线任务解锁下一章，通常也会解锁新的游戏玩法功能。", "主线任务是每个章节的叙事骨干。它们是线性的，引导你经历剧情关键遭遇、Boss 战和背景发现。支线任务从主线链分叉，提供替代视角、额外背景或额外奖励。", "每个章节通常包含 2-4 小时的游戏时间，覆盖一个主题区域。第一章聚焦于角色创建和早期游戏系统的基础知识。后续章节探索阵营政治、世界冲突以及定义 Aion 2 终局的机制。"]),
        section("main-quests", "主线任务链：你的引导路径", ["主线任务旨在成为进阶的骨干。每个主线任务为你提供经验、解锁新功能并将你推向终局。与支线任务不同，主线任务始终值得你的时间——它们是最少阻力、最大进度的路径。", "主线任务链是有序的：完成第一章解锁第二章，第二章解锁第三章，以此类推。这种线性结构确保你在遇到更具挑战性的内容之前，拥有必要的工具、装备和知识。", "随着你通过章节推进，主线任务越来越多地需要多人参与。后续章节引入攻城战、阵营活动和地下城内容，期望多名玩家参与。有公会伙伴或朋友在这些章节会使体验更顺畅、更有回报。"]),
        section("side-quests", "支线任务：深度与额外奖励", ["支线任务是 Aion 2 的叙事深度。它们扩展章节主题、引入 NPC 背景和提供替代故事视角。部分支线任务解锁独特对话选项、角色洞察或主线无法获得的额外奖励。", "支线任务的投入度不同——有些是仅需 5-10 分钟的快速遭遇，提供少量奖励；其他则是多步骤链，需要探索、战斗或采集。每单位时间投入的经验回报通常低于主线任务，但叙事深度无与伦比。", "对时间敏感的玩家，应优先完成提供独占奖励、解锁隐藏内容或提供丰富终局故事的背景信息的支线任务。仅重复主题而无新增信息的支线任务可安全跳过。"]),
        section("progression-strategy", "进阶策略：从章节到等级", ["Aion 2 全球版采用改良版 Season 1 进阶曲线。章节以比韩服原始版更快的节奏解锁新等级和区域。全球版的目标是在 5-10 小时专注游戏后让玩家达到终局等级。", "每个章节对应一个等级区间。完成一个章节的所有主线任务通常将你的等级提升至下一区间。然而，支线任务和可选活动可以加速这一过程——在每个章节完成所有内容可以更快升级，但在每个故事段落花费更多时间。", "要最快到达终局，专注于主线任务并跳过可选支线内容。到达终局装备后，随时可以返回章节完成支线任务。剧情没有不可逆选择——你可以随时回头补齐差距。"]),
        section("endgame-stories", "终局剧情与内容", ["一旦达到终局等级，剧情不会停止。终局章节引入新的叙事弧线——阵营升级、跨服活动、赛季故事和角色专属故事线。这些通过游戏内 NPC 和战役中心进入。", "终局剧情内容为已建立角色核心进阶的玩家设计。它需要终局装备和多人游戏，提供的奖励与终局 PvP 和地下城内容有竞争力。", "全球版预期相同的终局剧情框架，可能有节奏调整。改良版 Season 1 曲线意味着你会比韩服玩家更早到达终局剧情，但剧情内容本身同样丰富。"]),
      ],
    }),
    fr: articleCopy(guideLabels, "fr", 6, {
      eyebrow: "Histoire",
      title: "Guide de l'Avancement Narratif Aion 2 : Quêtes Principales, Chapitres et Optimisation de Votre Aventure",
      description: "Comprenez comment fonctionne le système narratif d'Aion 2 — chapitres, quêtes principales, quêtes secondaires et progression par chapitre. Apprenez quelles voies narratives prioriser et comment tirer un maximum d'expérience et de récompenses.",
      intro: "Le système narratif d'Aion 2 est conçu comme une expérience guidée qui vous introduit au monde, à ses mécaniques et à ses factions. La structure narrative par chapitres délivre une histoire à la cadence soignée tout en intégrant les systèmes de gameplay — combat, récolte, artisanat et PvP — dans le flux de progression.",
      sourceNote: "Basé sur les pages officielles NC et la structure narrative du service coréen (septembre 2026). La structure de chapitres du lancement mondial peut être ajustée pour la courbe Season 1 modifiée.",
      keywords: ["Guide histoire Aion 2", "Avancement chapitre Aion 2", "Quêtes principales Aion 2", "Guide narratif Aion 2", "Quêtes d'histoire Aion 2"],
      sections: [
        section("story-overview", "Le cadre narratif : chapitres et quêtes", ["La narration d'Aion 2 est organisée en chapitres — chaque chapitre couvre un arc narratif avec son propre ensemble de quêtes principales et secondaires. Les chapitres font avancer l'histoire tout en introduisant de nouvelles zones, mécaniques et systèmes.", "Les quêtes principales sont l'épine dorsale narrative de chaque chapitre. Elles sont linéaires et vous guident à travers des rencontres critiques, des combats de boss et des découvertes lore. Les quêtes secondaires s'en branchent et offrent des perspectives alternatives ou des récompenses bonus.", "Chaque chapitre couvre typiquement 2 à 4 heures de jeu et traite d'un domaine thématique. Le chapitre 1 se concentre sur les bases de la création de personnage et des systèmes débutants. Les chapitres suivants explorent la politique de faction et les conflits du monde."]),
        section("main-quests", "Chaînes de quêtes principales : votre chemin guidé", ["Les quêtes principales sont conçues comme la colonne vertébrale de la progression. Chaque quête principale donne de l'expérience, débloque de nouvelles fonctionnalités et vous mène vers l'endgame.", "Les chaînes de quêtes principales sont séquencées : terminez le chapitre 1 pour débloquer le chapitre 2, le chapitre 2 pour le chapitre 3, et ainsi de suite. Cette structure linéaire garantit que vous avez les outils nécessaires avant de rencontrer un contenu plus exigeant.", "Au fur et à mesure que vous progressez, les quêtes principales nécessitent de plus en plus de participation en groupe. Les chapitres ultérieurs introduisent la guerre de siège, les événements de faction et le contenu de donjon."]),
        section("side-quests", "Quêtes secondaires : profondeur et récompenses supplémentaires", ["Les quêtes secondaires sont la profondeur narrative d'Aion 2. Elles développent les thèmes des chapitres, introduisent le lore des PNJ et offrent des perspectives narratives alternatives.", "Les quêtes secondaires varient en engagement — certaines sont des rencontres rapides de 5 à 10 minutes offrant des récompenses mineures, tandis que d'autres sont des chaînes multi-étapes nécessitant exploration, combat ou récolte.", "Pour les joueurs à court de temps, priorisez les quêtes secondaires offrant des récompenses exclusives, débloquant un contenu caché ou fournissant du lore qui enrichit l'histoire de l'endgame."]),
        section("progression-strategy", "Stratégie de progression : chapitres vers niveaux", ["Aion 2 utilise une courbe de progression Season 1 modifiée pour le lancement mondial. Les chapitres débloquent de nouveaux niveaux et zones à un rythme plus rapide que le service coréen original.", "Chaque chapitre correspond à une plage de niveaux. Terminer toutes les quêtes principales d'un chapitre vous fait typiquement atteindre la plage suivante. Cependant, les quêtes secondaires peuvent accélérer ce processus.", "Pour le chemin le plus rapide vers l'endgame, concentrez-vous sur les quêtes principales et passez outre le contenu secondaire optionnel. Vous pouvez toujours retourner aux chapitres plus tard."]),
        section("endgame-stories", "Histoires et contenus d'endgame", ["Une fois le niveau d'endgame atteint, l'histoire ne s'arrête pas. Les chapitres d'endgame introduisent de nouveaux arcs narratifs — escalade de faction, événements entre serveurs, histoires saisonnières et scénarios spécifiques aux personnages.", "Le contenu narratif d'endgame est conçu pour les joueurs qui ont déjà établi la progression centrale de leur personnage. Il nécessite un équipement d'endgame et du jeu en groupe, et offre des récompenses compétitives avec le contenu PvP et donjon d'endgame.", "Pour le lancement mondial, attendez-vous au même cadre narratif d'endgame avec d'éventuels ajustements de rythme."]),
      ],
    }),
    de: articleCopy(guideLabels, "de", 6, {
      eyebrow: "Story",
      title: "Aion 2 Story- und Kapitel-Fortschrittsguide: Hauptquests, Erzählkapitel und Adventure-Optimierung",
      description: "Erfahren Sie, wie das Story-System von Aion 2 funktioniert — Erzählkapitel, Hauptquests, Nebenquests und kapitelbasierter Fortschritt. Lernen Sie, welche Story-Pfade Sie priorisieren sollten.",
      intro: "Das Story-System von Aion 2 ist als geführte Erfahrung konzipiert, die Sie in die Welt, ihre Mechaniken und ihre Fraktionen einführt. Die kapitelbasierte Erzählstruktur liefert eine sorgfältig getaktete Geschichte, während Gameplay-Systeme in den Fortschrittsfluss integriert werden.",
      sourceNote: "Basierend auf den offiziellen NC-Spielseiten und der Story-Struktur des koreanischen Dienstes (September 2026). Die Kapitelstruktur der globalen Version kann für die modifizierte Season-1-Kurve angepasst werden.",
      keywords: ["Aion 2 Story-Guide", "Aion 2 Kapitel-Fortschritt", "Aion 2 Hauptquests", "Aion 2 Erzählguide", "Aion 2 Story-Missionen"],
      sections: [
        section("story-overview", "Der Story-Rahmen: Kapitel und Quests", ["Die Erzählung von Aion 2 ist in Kapitel organisiert — jedes Kapitel deckt einen Story-Arc mit eigener Hauptquests und Nebenquests ab. Kapitel bringen die Geschichte voran und führen neue Bereiche, Mechaniken und Systeme ein.", "Hauptquests sind das narrative Rückgrat jedes Kapitels. Sie sind linear und führen Sie durch story-kritische Begegnungen, Bosskämpfe und Lore-Entdeckungen. Nebenquests verzweigen sich von der Hauptkette und bieten alternative Perspektiven.", "Jedes Kapitel umfasst typischerweise 2-4 Stunden Spielzeit und behandelt ein thematisches Gebiet. Kapitel 1 konzentriert sich auf die Grundlagen der Charaktererstellung. Spätere Kapitel erkunden Fraktionspolitik und die Konflikte der Welt."]),
        section("main-quests", "Hauptquest-Ketten: Ihr geführter Pfad", ["Hauptquests sind als Rückgrat der Fortschritt geplant. Jede Hauptquest gibt Erfahrung, schaltet neue Features frei und führt Sie zum Endgame.", "Hauptquest-Ketten sind sequenziert: Schließen Sie Kapitel 1 ab, um Kapitel 2 freizuschalten, Kapitel 2 für Kapitel 3, und so weiter. Diese lineare Struktur stellt sicher, dass Sie über die notwendigen Werkzeuge verfügen, bevor Sie anspruchsvolleren Inhalt treffen.", "Mit fortschreitendem Kapitelverlauf erfordern Hauptquests zunehmend Gruppenbeteiligung. Spätere Kapitel führen Belagerungskrieg, Fraktionsereignisse und Dungeons ein."]),
        section("side-quests", "Nebenquests: Tiefe und zusätzliche Belohnungen", ["Nebenquests sind die narrative Tiefe von Aion 2. Sie erweitern Kapitel-Themen, führen NPC-Lore ein und bieten alternative Story-Perspektiven.", "Nebenquests variieren im Aufwand — einige sind schnelle 5-10 Minuten Begegnungen mit geringen Belohnungen, während andere mehrstufige Ketten sind, die Erkundung, Kampf oder Sammeln erfordern.", "Für zeitkritische Spieler priorisieren Sie Nebenquests, die exklusive Belohnungen bieten, versteckten Inhalt freischalten oder Lore bereitstellen, die die Endgame-Geschichte bereichern."]),
        section("progression-strategy", "Fortschrittsstrategie: Von Kapiteln zu Stufen", ["Aion 2 verwendet für den globalen Launch eine modifizierte Season-1-Fortschrittskurve. Kapitel schalten neue Stufen und Bereiche in einem schnelleren Tempo als der ursprüngliche koreanische Dienst frei.", "Jedes Kapitel entspricht einem Stufenbereich. Das Abschließen aller Hauptquests in einem Kapitel bringt Sie typischerweise in den nächsten Bereich. Nebenquests und optionale Aktivitäten können dies beschleunigen.", "Für den schnellsten Weg zum Endgame konzentrieren Sie sich auf Hauptquests und überspringen optionale Nebeninhalte. Sie können später immer noch zu den Kapiteln zurückkehren."]),
        section("endgame-stories", "Endgame-Storys und Inhalte", ["Sobald Sie die Endgame-Stufe erreicht haben, endet die Geschichte nicht. Endgame-Kapitel führen neue Erzählbögen ein — Fraktions-Eskalation, Cross-Server-Events, Saison-Storys und charakter-spezifische Handlungsstränge.", "Endgame-Story-Inhalte sind für Spieler konzipiert, die bereits die Kern-Fortschrittslinie ihres Charakters aufgebaut haben. Es erfordert Endgame-Ausrüstung und Gruppen-Spiel.", "Für den globalen Launch ist der gleiche Endgame-Story-Rahmen zu erwarten, mit möglichen Tempoanpassungen."]),
      ],
    }),
    es: articleCopy(guideLabels, "es", 6, {
      eyebrow: "Historia",
      title: "Guía de Progreso Narrativo de Aion 2: Misiones Principales, Capítulos y Cómo Maximizar tu Aventura",
      description: "Entiende cómo funciona el sistema de historia de Aion 2 — capítulos narrativos, misiones principales, misiones secundarias y progreso por capítulos. Aprende qué rutas de historia priorizar.",
      intro: "El sistema de historia de Aion 2 está diseñado como una experiencia guiada que te presenta al mundo, sus mecánicas y facciones. La estructura narrativa por capítulos entrega una historia con un ritmo cuidadosamente controlado mientras integra sistemas de juego en el flujo de progreso.",
      sourceNote: "Basado en las páginas oficiales de NC y la estructura narrativa del servicio coreano (septiembre 2026). La estructura de capítulos de la versión global puede ajustarse para la curva de progreso Season 1 modificada.",
      keywords: ["Guía historia Aion 2", "Progreso capítulo Aion 2", "Misiones principales Aion 2", "Guía narrativa Aion 2", "Misiones de historia Aion 2"],
      sections: [
        section("story-overview", "El marco narrativo: capítulos y misiones", ["La narrativa de Aion 2 está organizada en capítulos — cada capítulo cubre un arco narrativo con su propio conjunto de misiones principales y secundarias. Los capítulos avanzan la historia mientras introducen nuevas zonas, mecánicas y sistemas.", "Las misiones principales son la columna vertebral narrativa de cada capítulo. Son lineales y te guían a través de encuentros críticos de la historia, peleas de jefes y descubrimientos de lore. Las misiones secundarias se ramifican de la cadena principal y ofrecen perspectivas alternativas.", "Cada capítulo cubre típicamente 2-4 horas de juego y trata un área temática. El capítulo 1 se centra en las bases de la creación de personaje y los sistemas de juego inicial."]),
        section("main-quests", "Cadenas de misiones principales: tu camino guiado", ["Las misiones principales están diseñadas como la columna vertebral del progreso. Cada misión principal te da experiencia, desbloquea nuevas funciones y te lleva hacia el endgame.", "Las cadenas de misiones principales están secuenciadas: completa el capítulo 1 para desbloquear el capítulo 2, el capítulo 2 para el capítulo 3, y así sucesivamente.", "A medida que avanzas, las misiones principales requieren cada vez más participación grupal. Los capítulos posteriores introducen guerra de asedio, eventos de facción y contenido de mazmorra."]),
        section("side-quests", "Misiones secundarias: profundidad y recompensas adicionales", ["Las misiones secundarias son la profundidad narrativa de Aion 2. Expanden temas de capítulos, introducen lore de NPCs y ofrecen perspectivas narrativas alternativas.", "Las misiones secundarias varían en compromiso — algunas son encuentros rápidos de 5-10 minutos que ofrecen recompensas menores, mientras que otras son cadenas de múltiples pasos que requieren exploración, combate o recolección.", "Para jugadores a los que les falta tiempo, prioriza misiones secundarias que ofrezcan recompensas exclusivas, desbloqueen contenido oculto o proporcionen lore que enriquezca la historia del endgame."]),
        section("progression-strategy", "Estrategia de progreso: de capítulos a niveles", ["Aion 2 usa una curva de progreso de Season 1 modificada para el lanzamiento global. Los capítulos desbloquean nuevos niveles y áreas a un ritmo más rápido que el servicio coreano original.", "Cada capítulo corresponde a un rango de niveles. Completar todas las misiones principales de un capítulo típicamente te lleva al siguiente rango. Sin embargo, las misiones secundarias y actividades opcionales pueden acelerar este proceso.", "Para el camino más rápido al endgame, concéntrate en las misiones principales y omite el contenido secundario opcional. Siempre puedes regresar a los capítulos más tarde."]),
        section("endgame-stories", "Historias e contenidos del endgame", ["Una vez que alcanzas el nivel de endgame, la historia no se detiene. Los capítulos de endgame introducen nuevos arcos narrativos — escalada de facción, eventos entre servidores, historias de temporada y líneas de trama específicas por personaje.", "Los contenidos narrativos de endgame están diseñados para jugadores que ya han establecido el progreso central de su personaje. Requieren equipo de endgame y juego en grupo.", "Para el lanzamiento global, espere el mismo marco narrativo de endgame con posibles ajustes de ritmo."]),
      ],
    }),
    ja: articleCopy(guideLabels, "ja", 6, {
      eyebrow: "ストーリー",
      title: "Aion 2 ストーリー進捗ガイド：メインクエスト、章構成、冒険の最大化",
      description: "Aion 2のストーリーシステムを理解しよう——章構成のストーリー、メインクエスト、サブクエスト、章ベースの進捗。どのストーリーパスを優先すべきか、また最大限の経験値と報酬を得る方法を学ぼう。",
      intro: "Aion 2のストーリーシステムは、世界・メカニクス・陣営にプレイヤーを導入するためのガイド体験として設計されています。章構成のストーリー構造は、ゲームプレイシステムを融合させつつ、じっくりとストーリーを進行させます。",
      sourceNote: "NC公式ゲームプレイページと韓国サーバーのストーリー構造（2026年9月時点）に基づく。グローバル版の章構造は改良版Season 1の進捗曲線に合わせて調整される可能性があります。",
      keywords: ["Aion 2 ストーリーガイド", "Aion 2 章進捗", "Aion 2 メインクエスト", "Aion 2 叙事ガイド", "Aion 2 ストーリーミッション"],
      sections: [
        section("story-overview", "ストーリーフレームワーク：章とクエスト", ["Aion 2のナラティブは章で構成されています。各章はストーリーアークを1つカバーし、それに伴うメインクエストとサブクエストセットを持っています。章はストーリーを進行させつつ、新エリア・メカニクス・システムを導入します。", "メインクエストは各章のナラティブの骨格です。それらは直線的であり、ストーリー критическиеな遭遇、ボス戦、ロア発見へと導きます。サブクエストはメインクエストチェーンから分岐し、代替の視点や追加の背景、ボーナス報酬を提供します。", "各章は通常2〜4時間のゲームプレイ時間を含み、1つのテーマ領域をカバーします。第1章はキャラクター作成と早期ゲームシステムの基礎に焦点を当てています。"]),
        section("main-quests", "メインクエストチェーン：あなたのガイドされたパス", ["メインクエストは進捗の骨格として設計されています。各メインクエストは経験値を与え、新機能をアンロックし、エンドゲームへと導きます。", "メインクエストチェーンは順序付けられています：第1章をクリアすると第2章がアンロックされ、第2章をクリアすると第3章がアンロックされます。この直線的な構造により、より過酷なコンテンツに遭遇する前に必要なツールと装備を整えます。", "章を通過するにつれ、メインクエストはより多くの複数参加を必要とします。後続の章は攻城戦、陣営イベント、ダンジョンコンテンツを導入します。"]),
        section("side-quests", "サブクエスト：深さと追加報酬", ["サブクエストはAion 2のナラティブの深さです。章テーマを展開し、NPCロアを導入し、代替ストーリーの視点を提供します。", "サブクエストの投入度は異なります——5〜10分のクイック遭遇から、探索・戦闘・採集を必要とする複数ステップのチェーンまであります。投入時間あたりの経験値報酬は通常メインクエストより低いです。", "時間に制約されたプレイヤーは、独占報酬、隠しコンテンツ、エンドゲームストーリーを豊かにするロアを提供するサブクエストを優先すべきです。"]),
        section("progression-strategy", "進捗戦略：章からレベルへ", ["Aion 2はグローバル版向けに改良版Season 1進捗曲線を使用します。章は韓国サーバーのオリジナルよりも速いペースで新しいレベルとエリアをアンロックします。", "各章はレベル範囲に対応します。1章すべてのメインクエストをクリアすると通常次の範囲にレベルアップします。しかしサブクエストやオプションアクティビティはこのプロセスを加速できます。", "最も早くエンドゲームに到達するには、メインクエストに集中しオプションのサブコンテンツをスキップしてください。後にいつでも章に戻れます。"]),
        section("endgame-stories", "エンドゲームストーリーとコンテンツ", ["エンドゲームレベルに達してもストーリーは止まりません。エンドゲーム章は新しいナラティブアークを導入します——陣営のEscalation、クロスサーバーイベント、シーズンストーリー、キャラクター固有のストーリーラインです。", "エンドゲームストーリーコンテンツはキャラクターの核心進捗を確立したプレイヤー向けに設計されています。エンドゲーム装備と複数プレイを必要とし、エンドゲームPvPやダンジョンコンテンツと同等の報酬を提供します。", "グローバル版では同一のエンドゲームストーリーフレームワークを想定していますが、テンポ調整がある可能性があります。"]),
      ],
    }),
    "pt-br": articleCopy(guideLabels, "pt-br", 6, {
      eyebrow: "História",
      title: "Guia de Progressão da História do Aion 2: Missões Principais, Capítulos e Como Maximizar Sua Aventura",
      description: "Entenda como o sistema de história do Aion 2 funciona — capítulos narrativos, missões principais, missões secundarias e progressão por capítulo. Aprenda quais rotas de história priorizar e como extrair o máximo de recompensas.",
      intro: "O sistema de história do Aion 2 é projetado como uma experiência guiada que apresenta o mundo, suas mecânicas e facções. A estrutura narrativa por capítulos entrega uma história com ritmo cuidadosamente controlado enquanto integra sistemas de jogo no fluxo de progresso.",
      sourceNote: "Baseado nas páginas oficiais da NC e na estrutura narrativa do serviço coreano (setembro de 2026). A estrutura de capítulos da versão global pode ser ajustada para a curva de progressão da Season 1 modificada.",
      keywords: ["Guia história Aion 2", "Progressão capítulo Aion 2", "Missões principais Aion 2", "Guia narrativa Aion 2", "Missões de história Aion 2"],
      sections: [
        section("story-overview", "O marco narrativo: capítulos e missões", ["A narrativa do Aion 2 é organizada em capítulos — cada capítulo cobre um arco narrativo com seu próprio conjunto de missões principais e secundárias. Capítulos fazem a história avançar enquanto introduzem novas áreas, mecânicas e sistemas.", "As missões principais são a espinha dorsal narrativa de cada capítulo. São lineares e guiam você por encontros críticos da história, batalhas de chefe e descobertas de lore. As missões secundárias se ramificam da cadeia principal e oferecem perspectivas alternativas.", "Cada capítulo tipicamente cobre 2-4 horas de jogo e trata uma área temática. O capítulo 1 se concentra nas bases da criação de personagem e sistemas de jogo inicial."]),
        section("main-quests", "Cadeias de missões principais: seu caminho guiado", ["As missões principais são projetadas como a espinha dorsal do progresso. Cada missão principal dá experiência, desbloqueia novas funcionalidades e te leva ao endgame.", "As cadeias de missões principais são sequenciadas: complete o capítulo 1 para desbloquear o capítulo 2, o capítulo 2 para o capítulo 3, e assim por diante. Esta estrutura linear garante que você tenha as ferramentas necessárias antes de encontrar conteúdo mais exigente.", "À medida que você avança, as missões principais exigem cada vez mais participação em grupo. Capítulos posteriores introduzem guerra de cerco, eventos de facção e conteúdo de masmorra."]),
        section("side-quests", "Missões secundárias: profundidade e recompensas adicionais", ["As missões secundárias são a profundidade narrativa do Aion 2. Elas expandem temas de capítulos, introduzem lore de NPCs e oferecem perspectivas narrativas alternativas.", "As missões secundárias variam em comprometimento — algumas são encontros rápidos de 5-10 minutos que oferecem recompensas menores, enquanto outras são cadeias de múltiplas etapas que requerem exploração, combate ou coleta.", "Para jogadores com pouco tempo, priorize missões secundárias que ofereçam recompensas exclusivas, desbloqueiem conteúdo oculto ou forneçam lore que enriquece a história do endgame."]),
        section("progression-strategy", "Estratégia de progressão: de capítulos a níveis", ["Aion 2 usa uma curva de progressão da Season 1 modificada para o lançamento global. Capítulos desbloqueiam novos níveis e áreas a um ritmo mais rápido que o serviço coreano original.", "Cada capítulo corresponde a um intervalo de níveis. Completar todas as missões principais de um capítulo tipicamente te leva ao próximo intervalo. No entanto, missões secundárias e atividades opcionais podem acelerar esse processo.", "Para o caminho mais rápido ao endgame, concentre-se nas missões principais e pule o conteúdo secundário opcional. Você pode sempre retornar aos capítulos mais tarde."]),
        section("endgame-stories", "Histórias e conteúdos de endgame", ["Uma vez que você alcance o nível de endgame, a história não para. Capítulos de endgame introduzem novos arcos narrativos — escalada de facção, eventos entre servidores, histórias de temporada e linhas de trama específicas por personagem.", "Conteúdos narrativos de endgame são projetados para jogadores que já estabeleceram o progresso central do seu personagem. Requer equipamento de endgame e jogo em grupo.", "Para o lançamento global, espere o mesmo marco narrativo de endgame com possíveis ajustes de ritmo."]),
      ],
    }),
    ru: articleCopy(guideLabels, "ru", 6, {
      eyebrow: "Сюжет",
      title: "Гайд по сюжетному прогрессу Aion 2: Основные квесты, главы и как максимизировать своё приключение",
      description: "Поймите, как работает сюжетная система Aion 2 — нарративные главы, основные квесты, побочные квесты и главолоподобный прогресс. Узнайте, какие сюжетные пути приоритетизировать.",
      intro: "Сюжетная система Aion 2 спроектирована как направляемый опыт, знакомящий вас с миром, его механиками и фракциями. Главолоподобная нарративная структура обеспечивает тщательно выверенный ритм истории, интегрируя системы геймплея в поток прогрессии.",
      sourceNote: "Основано на официальных игровых страницах NC и структуре сюжета корейского сервиса (сентябрь 2026). Структура глав глобальной версии может быть скорректирована для изменённой кривой Season 1.",
      keywords: ["Гайд сюжет Aion 2", "Прогресс глав Aion 2", "Основные квесты Aion 2", "Гайд нарратив Aion 2", "Сюжетные миссии Aion 2"],
      sections: [
        section("story-overview", "Сюжетная рамка: главы и квесты", ["Нарратив Aion 2 организован в главы — каждая глава покрывает сюжетную дугу с собственным набором основных и побочных квестов. Главы продвигают историю, одновременно представляя новые области, механики и системы.", "Основные квесты — это нарративный позвоночник каждой главы. Они линейны и ведут вас через критические сюжетные встречи, битвы с боссами и открытия lore. Побочные квесты ветвятся от основной цепи и предлагают альтернативные перспективы или дополнительные награды.", "Каждая глава обычно охватывает 2-4 часа игры и покрывает одну тематическую область. Глава 1 фокусируется на основах создания персонажа и ранних системах. Последующие главы исследуют фракционную политику и конфликты мира."]),
        section("main-quests", "Цепочки основных квестов: ваш направляемый путь", ["Основные квесты спроектированы как позвоночник прогрессии. Каждый основной квест даёт опыт, открывает новые функции и ведёт вас к endgame.", "Цепочки основных квестов упорядочены: завершите главу 1 для разблокировки главы 2, главу 2 для главы 3 и так далее. Эта линейная структура гарантирует, что у вас есть необходимые инструменты и снаряжение до столкновения с более требовательным контентом.", "По мере продвижения через главы основные квесты всё больше требуют участия группы. Поздние главы вводят осадную войну, фракционные события и подземный контент."]),
        section("side-quests", "Побочные квесты: глубина и дополнительные награды", ["Побочные квесты — это нарративная глубина Aion 2. Они расширяют темы глав, представляют lore NPC и предлагают альтернативные нарративные перспективы.", "Побочные квесты варьируются по вовлечённости — некоторые это быстрые 5-10 минутные встречи с небольшими наградами, тогда как другие это многоэтапные цепочки, требующие исследования, боя или сбора.", "Для игроков, ограниченных во времени, приоритизируйте побочные квесты, предлагающие эксклюзивные награды, открывающие скрытый контент или предоставляющие lore, который обогащает историю endgame."]),
        section("progression-strategy", "Стратегия прогрессии: от глав к уровням", ["Aion 2 использует модифицированную кривую прогрессии Season 1 для глобального запуска. Главы разблокируют новые уровни и области быстрее оригинального корейского сервиса.", "Каждая глава соответствует диапазону уровней. Завершение всех основных квестов в главе обычно приводит вас к следующему диапазону. Однако побочные квесты и необязательные активности могут ускорить этот процесс.", "Для самого быстрого пути к endgame сосредоточьтесь на основных квестах и пропустите необязательный побочный контент. Вы всегда можете вернуться к главам позже."]),
        section("endgame-stories", "Endgame-сюжеты и контент", ["Как только вы достигнете endgame-уровня, история не останавливается. Endgame-главы вводят новые нарративные дуги — эскалацию фракции, кросс-серверные события, сезонные истории и персонаж-специфические сюжетные линии.", "Endgame-сюжетный контент предназначен для игроков, которые уже установили основной прогресс своего персонажа. Он требует endgame-снаряжения и групповой игры и предоставляет награды, конкурентные с endgame PvP и подземным контентом.", "Для глобального запуска ожидается та же endgame-сюжетная структура с возможными корректировками темпа."]),
      ],
    }),
    ko: articleCopy(guideLabels, "ko", 6, {
      eyebrow: "스토리",
      title: "Aion 2 스토리 진행 가이드: 메인 퀘스트, 챕터 구조, 모험 최대화",
      description: "Aion 2의 스토리 시스템이 어떻게 작동하는지 알아보세요 — 챕터 기반 서사, 메인 퀘스트, 서브 퀘스트, 챕터 방식 진행. 어떤 스토리 라우트를 우선해야 하는지와 최대 경험치·보상을 얻는 방법을 배우세요.",
      intro: "Aion 2의 스토리 시스템은 세계, 메커니즘, 진영을 플레이어에게 소개하기 위한 가이드 체험으로 설계되었습니다. 챕터 기반 서사 구조는 게임플레이 시스템을 통합하면서 정밀하게 조절된 리듬의 스토리를 제공합니다.",
      sourceNote: "NC 공식 게임플레이 페이지와 한국 서버의 스토리 구조(2026년 9월 기준)에 기반. 글로벌 버전 챕터 구조는改良版 Season 1 진행 곡선에 맞춰 조정될 수 있습니다.",
      keywords: ["Aion 2 스토리 가이드", "Aion 2 챕터 진행", "Aion 2 메인 퀘스트", "Aion 2 서사 가이드", "Aion 2 스토리 미션"],
      sections: [
        section("story-overview", "스토리 프레임워크: 챕터와 퀘스트", ["Aion 2의 서사는 챕터로 구성되어 있습니다. 각 챕터는 서사 아크를 하나 커버하고, 이에 수반하는 메인 퀘스트와 서브 퀘스트 세트를 가집니다. 챕터는 스토리를 진행시키면서 새로운 지역, 메커니즘, 시스템을 도입합니다.", "메인 퀘스트는 각 챕터의 서사 뼈대입니다. 직선식이며, 스토리 비판적인 만남, 보스전, lore 발견으로 인도합니다. 서브 퀘스트는 메인 퀘스트 체인에서 분기하여 대체 관점이나 추가 배경, 보너스 보상을 제공합니다.", "각 챕터는 보통 2-4시간 게임 플레이 시간을 포함하고, 하나의 테마 영역을 커버합니다. 1장은 캐릭터 생성과 초기 게임 시스템의 기본에 초점을 맞춥니다."]),
        section("main-quests", "메인 퀘스트 체인: 여러분의 가이드된 패스", ["메인 퀘스트는 진행의 뼈대로 설계되었습니다. 각 메인 퀘스트는 경험치를 제공하며, 새로운 기능을 해제하고, endgame으로 이끕니다.", "메인 퀘스트 체인은 순서화되어 있습니다: 1장을 완료하면 2장이 해제되고, 2장을 완료하면 3장이 해제됩니다. 이 직선적 구조는 더 어려운 콘텐츠에 직면하기 전에 필요한 도구와 장비를 갖추게 합니다.", "챕터를 진행할수록 메인 퀘스트는 더 많은 복수 참여를 필요로 합니다. 후속 챕터는 포격전, 진영 이벤트, 던전 콘텐츠를 도입합니다."]),
        section("side-quests", "서브 퀘스트: 깊이와 추가 보상", ["서브 퀘스트는 Aion 2의 서사 깊이입니다. 챕터 테마를 확장하고, NPC lore를 도입하며, 대체 서사 관점을 제공합니다.", "서브 퀘스트의 투입도는 다양합니다 — 5-10분의 빠른 만남부터 탐색·전투·채집을 필요로 하는 다단계 체인까지 있습니다. 투입 시간당 경험치 보상은 보통 메인 퀘스트보다 낮습니다.", "시간에 제약된 플레이어는 독점 보상, 은닉 콘텐츠, endgame 스토리를 풍부하게 하는 lore를 제공하는 서브 퀘스트를 우선해야 합니다."]),
        section("progression-strategy", "진행 전략: 챕터에서 레벨로", ["Aion 2는 글로벌 출시용으로改良版 Season 1 진행 곡선을 사용합니다. 챕터는 한국 서버의 오리지널보다 빠른 속도로 새로운 레벨과 지역을 해제합니다.", "각 챕터는 레벨 범위에 해당합니다. 한 챕터의 모든 메인 퀘스트를 완료하면 보통 다음 범위로 레벨업합니다. 그러나 서브 퀘스트와 옵션 활동은 이 과정을 가속할 수 있습니다.", "가장 빠르게 endgame에 도달하려면 메인 퀘스트에 집중하고 옵션 서브 콘텐츠를 스킵하세요. 나중에 언제든지 챕터로 돌아올 수 있습니다."]),
        section("endgame-stories", "Endgame 스토리와 콘텐츠", ["endgame 레벨에 도달해도 스토리는 멈추지 않습니다. endgame 챕터는 새로운 서사 아크를 도입합니다 — 진영의 Escalation, 크로스 서버 이벤트, 시즌 스토리, 캐릭터 고유 스토리 라인입니다.", "endgame 스토리 콘텐츠는 이미 캐릭터 핵심 진보를 확립한 플레이어용으로 설계되었습니다. endgame 장비와 복수 플레이가 필요하며, endgame PvP 및 던전 콘텐츠와 동등한 보상을 제공합니다.", "글로벌 버전에서는 동일한 endgame 스토리 프레임워크를 예상하지만, 템포 조정이 있을 수 있습니다."]),
      ],
    }),
    "zh-hant": articleCopy(guideLabels, "zh-hant", 6, {
      eyebrow: "劇情",
      title: "Aion 2 劇情章節攻略：主線任務、敘事章節與冒險最大化",
      description: "了解 Aion 2 劇情系統的工作原理——敘事章節、主線任務、支線任務和章節式進階。學習哪些劇情路線應優先推進，以及如何從敘事內容中獲得最大經驗和獎勵。",
      intro: "Aion 2 的劇情系統旨在提供引導式體驗，向你介紹世界、機制和陣營。章節式敘事結構在融入遊戲系統（戰鬥、採集、製作、PvP）的同時，提供精心把控節奏的故事。理解章節和任務的工作方式可以幫助你更快進階並更深刻地享受敘事。",
      sourceNote: "基於 NC 官方遊戲頁面和韓服劇情結構（截至 2026 年 9 月）。全球版章節結構可能為改良版 Season 1 進階曲線做調整。",
      keywords: ["Aion 2 劇情攻略", "Aion 2 章節進階", "Aion 2 主線任務", "Aion 2 敘事指南", "Aion 2 劇情任務"],
      sections: [
        section("story-overview", "劇情框架：章節與任務", ["Aion 2 的敘事按章節組織——每個章節覆蓋一段故事弧線，配有自己的主線任務和支線任務集。章節推進故事同時引入新區域、機制和系統。完成章節主線任務解鎖下一章，通常也會解鎖新的遊戲玩法功能。", "主線任務是每個章節的敘事骨架。它們是線性的，引導你經歷劇情關鍵遭遇、Boss 戰和背景發現。支線任務從主線鏈分叉，提供替代視角、額外背景或額外獎勵。", "每個章節通常包含 2-4 小時的遊戲時間，覆蓋一個主題區域。第一章聚焦於角色創建和早期遊戲系統的基礎知識。後續章節探索陣營政治、世界衝突以及定義 Aion 2 終局的機制。"]),
        section("main-quests", "主線任務鏈：你的引導路徑", ["主線任務旨在成為進階的骨架。每個主線任務為你提供經驗、解鎖新功能並將你推向終局。與支線任務不同，主線任務始終值得你的時間——它們是最少阻力、最大進度的路徑。", "主線任務鏈是有序的：完成第一章解鎖第二章，第二章解鎖第三章，以此類推。這種線性結構確保你在遇到更具挑戰性的內容之前，擁有必要的工具、裝備和知識。", "隨著你通過章節推進，主線任務越來越多地需要多人參與。後續章節引入攻城戰、陣營活動和地下城內容，期望多名玩家參與。有公會夥伴或朋友在這些章節會使體驗更順暢、更有回報。"]),
        section("side-quests", "支線任務：深度與額外獎勵", ["支線任務是 Aion 2 的敘事深度。它們擴展章節主題、引入 NPC 背景和提供替代故事視角。部分支線任務解鎖獨特對話選項、角色洞察或主線無法獲得的額外獎勵。", "支線任務的投入度不同——有些是僅需 5-10 分鐘的快速遭遇，提供少量獎勵；其他則是多步驟鏈，需要探索、戰鬥或採集。每單位時間投入的經驗回報通常低於主線任務，但敘事深度無與倫比。", "對時間敏感的玩家，應優先完成提供獨佔獎勵、解鎖隱藏內容或提供豐富終局故事的背景信息的支線任務。僅重複主題而無新增信息的支線任務可安全跳過。"]),
        section("progression-strategy", "進階策略：從章節到等級", ["Aion 2 全球版採用改良版 Season 1 進階曲線。章節以比韓服原始版更快的節奏解鎖新等級和區域。全球版的目標是在 5-10 小時專注遊戲後讓玩家達到終局等級。", "每個章节對應一個等級區間。完成一個章節的所有主線任務通常將你的等級提升至下一區間。然而，支線任務和可選活動可以加速這一過程——在每個章節完成所有內容可以更快升級，但在每個故事段落花費更多時間。", "要最快到達終局，專注於主線任務並跳過可選支線內容。到達終局裝備后，隨時可以返回章節完成支線任務。劇情沒有不可逆選擇——你可以隨時回頭補齊差距。"]),
        section("endgame-stories", "終局劇情與內容", ["一旦達到終局等級，劇情不會停止。終局章節引入新的敘事弧線——陣營升級、跨服活動、賽季故事和角色專屬故事線。這些通過遊戲內 NPC 和戰役中心進入。", "終局劇情內容為已建立角色核心進階的玩家設計。它需要終局裝備和多人遊戲，提供的獎勵與終局 PvP 和地下城內容有競爭力。", "全球版預期相同的終局劇情框架，可能有節奏調整。改良版 Season 1 曲線意味著你會比韓服玩家更早到達終局劇情，但劇情內容本身同樣豐富。"]),
      ],
    }),
  },
};
