import { articleCopy, guideLabels, localizations, publishedVerified, section } from "./trending-august-29-shared";
import type { ContentEntry, ContentHeroImage, ContentSource } from "./content-registry";

/* ARTICLE 4 — New dungeons & ascension trials found in the August 26 datamine */

const dnSource1: ContentSource = {
  id: "aion2t-datamine-41-2026-08-29",
  kind: "third-party", publisher: "AION2T",
  label: "AION 2 — A Tenth Class, a War for the Fields, and a Temple Nobody Can Enter Yet",
  url: "https://aion2t.com/news/41",
  publishedAt: "2026-08-26",
  retrievedAt: "2026-08-28",
  verifiedAt: "2026-08-28",
  localizations: localizations({
    "zh-hans": "Aion 2 —— 第十个职业、田野之战，以及一座尚无人能进入的寺庙",
    en: "Aion 2 — A Tenth Class, a War for the Fields, and a Temple Nobody Can Enter Yet",
    fr: "Aion 2 — Une dixième classe, une guerre des champs et un temple inaccessible",
    de: "Aion 2 — Eine zehnte Klasse, ein Krieg um die Felder und ein noch unbetretbarer Tempel",
    es: "Aion 2 — Una décima clase, una guerra por los campos y un templo inaccesible",
    ja: "Aion 2 — 10番目のクラス、野の戦争、そしてまだ誰も入れない寺院",
    "pt-br": "Aion 2 — Uma décima classe, uma guerra pelos campos e um templo inacessível",
    ru: "Aion 2 — Десятый класс, война за поля и недоступный храм",
    ko: "Aion 2 — 열 번째 클래스, 들판의 전쟁, 아직 아무도 들어갈 수 없는 사원",
    "zh-hant": "Aion 2 —— 第十個職業、田野之戰，以及一座尚無人能進入的寺廟",
  }, "https://aion2t.com/news/41"),
};

const dnSource2: ContentSource = {
  id: "aion2t-aug26-patch-2026-08-29",
  kind: "third-party", publisher: "AION2T",
  label: "AION 2 — August 26, 2026 Update Notes (Great Rebalance context)",
  url: "https://aion2t.com/news/40",
  publishedAt: "2026-08-26",
  retrievedAt: "2026-08-28",
  verifiedAt: "2026-08-28",
  localizations: localizations({
    "zh-hans": "Aion 2——2026 年 8 月 26 日更新说明（大平衡背景）",
    en: "AION 2 — August 26, 2026 Update Notes (Great Rebalance context)",
    fr: "Aion 2 — Notes de mise à jour du 26 août 2026 (contexte Grand rééquilibrage)",
    de: "Aion 2 — Update-Notizen vom 26. August 2026 (Great-Rebalance-Kontext)",
    es: "Aion 2 — Notas de la actualización del 26 de agosto de 2026 (contexto del Gran rebalanceo)",
    ja: "Aion 2 — 2026年8月26日アップデートノート（グレートリバランスの文脈）",
    "pt-br": "Aion 2 — Notas da atualização de 26 de agosto de 2026 (contexto do Grande reequilíbrio)",
    ru: "Aion 2 — Примечания к обновлению от 26 августа 2026 (контекст Великого ребаланса)",
    ko: "Aion 2 — 2026년 8월 26일 업데이트 노트(그레이트 리밸런스 맥락)",
    "zh-hant": "Aion 2——2026 年 8 月 26 日更新說明（大平衡背景）",
  }, "https://aion2t.com/news/40"),
};

const dnHero: ContentHeroImage = {
  src: "https://blogfiles.ncsoft.net/news/af7330da-4ff6-4b58-aece-400e6061a3be.jpg",
  width: 1100, height: 605,
  credit: "NC Corporation",
  sourceUrl: "https://aion2.plaync.com/ko-kr/board/notice",
  rights: "linked-official-media",
  translations: {
    "zh-hans": { alt: "Aion 2 新副本与升阶试炼数据挖掘指南配图", caption: "NC 官方配图；8 月 26 日客户端数据挖掘指向一系列开发中的副本——埃拉库斯地下神殿（57 级）与已登记的升阶单人试炼等，均为非官方开发中内容。" },
    en: { alt: "Aion 2 new dungeons and ascension trials datamine guide image", caption: "Official NC artwork; the August 26 client datamine points to a set of in-development dungeons — the Eracus Underground Temple (level 57) and registered ascension solo trials among them — all unofficial." },
    fr: { alt: "Image du guide sur les nouveaux donjons et épreuves d'ascension d'Aion 2 (datamining)", caption: "Visuel officiel NC ; le datamining du 26 août évoque des donjons en développement — le temple souterrain d'Eracus (niveau 57) et des épreuves d'ascension enregistrées." },
    de: { alt: "Bild zum Guide zu neuen Aion-2-Dungeons und Aufstiegsprüfungen (Datamining)", caption: "Offizielles NC-Artwork; das Datamining vom 26. August deutet auf neue Dungeons hin — den Eracus-Untergrundtempel (Stufe 57) und registrierte Aufstiegs-Soloprüfungen." },
    es: { alt: "Imagen de la guía de nuevas mazmorras y pruebas de ascensión de Aion 2 (datamining)", caption: "Arte oficial de NC; el datamining del 26 de agosto apunta a mazmorras en desarrollo — el Templo subterráneo de Eracus (nivel 57) y pruebas de ascensión registradas." },
    ja: { alt: "Aion 2 新ダンジョンと昇華トライアル（データマイニング）ガイド画像", caption: "NC公式アートワーク；8月26日のデータマイニングは開発中のダンジョン群—エラクス地下神殿（Lv57）と登録済みの昇華ソロ試練などを示唆しています。" },
    "pt-br": { alt: "Imagem do guia de novas masmorras e provas de ascensão do Aion 2 (datamining)", caption: "Arte oficial da NC; o datamining de 26 de agosto aponta para masmorras em desenvolvimento — o Templo subterrâneo de Eracus (nível 57) e provas de ascensão registradas." },
    ru: { alt: "Изображение гайда по новым данжам и испытаниям вознесения Aion 2 (датамайнинг)", caption: "Официальный арт NC; датамайнинг от 26 августа указывает на разрабатываемые данжи — Подземный храм Эракуса (ур. 57) и зарегистрированные сольные испытания вознесения." },
    ko: { alt: "Aion 2 신규 던전·승화 시련 데이터 마이닝 가이드 이미지", caption: "NC 공식 이미지입니다. 8월 26일 클라이언트 데이터 마이닝은 개발 중 던전들—에라쿠스 지하 사원(Lv57)과 등록된 승화 솔로 시련 등을 가리킵니다. 전부 비공식입니다." },
    "zh-hant": { alt: "Aion 2 新副本與升階試煉資料挖掘指南配圖", caption: "NC 官方配圖；8 月 26 日用戶端資料挖掘指向一系列開發中的副本——埃拉庫斯地下神殿（57 級）與已登記的升階單人試煉等，均為非官方開發中內容。" },
  },
};

export const trendingAugust29Article4: ContentEntry = {
  section: "guides",
  slug: "aion-2-new-dungeons-ascension-trials-august-2026",
  schemaType: "Article",
  publishedAt: "2026-08-28",
  updatedAt: "2026-08-28",
  readingMinutes: 5,
  publication: publishedVerified,
  sources: [dnSource1, dnSource2],
  heroImage: dnHero,
  related: [
    { kind: "content", section: "guides", slug: "aion-2-dungeon-guide" },
    { kind: "content", section: "guides", slug: "aion-2-trials-raids-guide" },
    { kind: "content", section: "guides", slug: "aion-2-expedition-boss-guide" },
    { kind: "content", section: "guides", slug: "aion-2-tenth-class-guide" },
  ],
  translations: {
    en: articleCopy(guideLabels, "en", 5, {
      eyebrow: "DATAMINE — UNOFFICIAL",
      title: "Aion 2 New Dungeons & Ascension Trials: Aug 26 Datamine Breakdown",
      description: "The August 26 client datamine maps out a level 57 Eracus Underground Temple, a Marchutan's Shell story arc, and two registered solo trials. Here is everything found — clearly marked as unofficial.",
      intro: "Datamining of the August 26 update (client build dated August 25) surfaced the game's next wave of dungeon content: the biggest single addition was a level 57 Eracus Underground Temple, but the same dump contained story dungeons for both factions, registered solo trials under an ascension series, and a wave of world-restocking data. None of it is announced or dated. This guide organizes what was found and what it suggests about the roadmap.",
      sourceNote: "Based on AION2T's August 26 datamine report. All details here are unconfirmed, unofficial, in-development content pulled from the game client; NC has not announced any of it and anything may change or be cancelled.",
      keywords: ["Aion 2 new dungeons", "Aion 2 Eracus Underground Temple", "Aion 2 ascension trials", "Aion 2 Marchutan", "Aion 2 datamine August 2026"],
      sections: [
        section("eracus", "Eracus Underground Temple (Level 57)", ["The centerpiece: a level 57 dungeon whose boss is Lamuatan, with elite temple guardians, two invisible trap actors (Sand Vortex and Trap Blade), and four named characters waiting inside. It gained more new files this week than anything else — more than a third of all new assets.", "The map layout is a detached entry chamber, a single approach, then a branching cave running east — and a separate Eracus ruins map built for parties grew alongside it.", "A level 57 dungeon with this much active work is the strongest signal of the batch that a major raid-tier dungeon is being staged for the coming months."]),
        section("story-dungeons", "Story Dungeons for Both Factions", ["On the Asmodian side, two story dungeons are near finished: one guarded by Sigebert (with a Hebera mid-boss and corrupted Daeva bestiary), and a level 60–65 fight against Drakan and Beritra troops whose boss is listed as 'Marchutan's Shell' — the arc ends at an Empyrean Lord.", "Cutscene dialogue is already written and involves Nemon, Marchutan, Fafnir, Sigebert, Kromede and Hebera — substantial new story content for the faction narrative.", "On the Elyos side, a level 45 dungeon called Life Prison is being built around boss Jailor Iagosh, and another orbits a Mirror Guardian — mid-level content aimed at the 40–50 progression gap."]),
        section("ascension", "Registered Solo Trials: Chloris's & Sigebert's Abyss", ["Two solo trials are already fully registered — names, entrances, level ranges and all: Chloris's Abyss on the Elyos side and Sigebert's Abyss on the Asmodian side.", "They belong to an ascension trial series whose highest rank is called 'Worth Proven Beyond the Abyss', and Sigebert's Abyss is guarded by a level 50 boss named Abyssal Sigebert.", "Registered trials are the closest to shipping of everything in this dump — if you are planning around new solo endgame, this series is the most likely near-term addition."]),
        section("world-data", "World Restocking & New Creatures", ["Over two thousand new creature spawn points arrived: 1,196 in Eltnen and 1,061 in Morheim across 106 species, of which 96 still have no name, level or stats — the new spawns cluster under area labels that appear nowhere in existing wildlife.", "Rideable models flagged in earlier patches (Cramer, Kundishi, Campsha, Mooscoos and more) that ship as both monsters and mounts are the obvious tameable mounts; Morheim also gains Lycan variants alongside a new Silver Lycan Tribe of humanoid NPCs.", "Six padlocked Unique wings (frost, twilight, flame, ember-black, verdant gold, dark blue) arrived as a matched set with commissioned illustrators — strong evidence of future premium wings."]),
        section("caveats", "Read This With Care", ["Agnita (a boss with no dungeon), Frozen Lament (a party dungeon with a new breakable arena floor), VoidArkanis and a new tower called Erech all moved this patch — more content staged with no date attached.", "Everything above is datamined and unofficial. Content of this stage has shipped within a month before, but has also sat untouched for half a year. Treat the roadmap reading as direction, not promise.", "We will update this guide as NC announces the actual release schedules for these dungeons and trials."]),
      ],
    }),
    "zh-hans": articleCopy(guideLabels, "zh-hans", 5, {
      eyebrow: "数据挖掘——非官方",
      title: "Aion 2 新副本与升阶试炼：8 月 26 日数据挖掘拆解",
      description: "8 月 26 日客户端数据挖掘拼出 57 级埃拉库斯地下神殿、『马尔库坦之壳』剧情线以及两个已登记的试炼。以下为全部发现——均明确标注为非官方。",
      intro: "对 8 月 26 日更新（客户端构建日期 8 月 25 日）的数据挖掘浮出游戏下一波副本内容：最大单项是 57 级埃拉库斯地下神殿，同一批数据还包含双方阵营剧情副本、登记在『升阶』系列下的单人试炼，以及一波世界补量数据。以上均未公布、无日期。本指南梳理发现并按路线图推理其含义。",
      sourceNote: "基于 AION2T 8 月 26 日数据挖掘报告。本文全部细节为未确认、非官方的开发中内容；NC 未公布任何一项，随时可能变更或取消。",
      keywords: ["Aion 2 新副本", "Aion 2 埃拉库斯地下神殿", "Aion 2 升阶试炼", "Aion 2 马尔库坦", "Aion 2 2026年8月数据挖掘"],
      sections: [
        section("eracus", "埃拉库斯地下神殿（57 级）", ["主角：57 级副本，首领拉穆阿坦，含精英神殿守卫、两个隐形陷阱（沙暴漩涡与陷阱之刃）以及四名有名字的角色。本周新增文件数超过全部新资产的 1/3。", "地图结构为独立入口厅、单一通道，再向东分叉的洞穴；旁边还同步长出面向小队的埃拉库斯遗迹地图。", "工作量如此集中的 57 级副本，是本批中『大团队本正在排期』的最强信号。"]),
        section("story-dungeons", "双方阵营剧情副本", ["阿斯莫迪安侧两座剧情副本接近完成：一座由西格贝特守卫（含希贝拉中boss与堕落达埃瓦图鉴），另一座为 60-65 级对战德拉坎与贝里特拉军队，首领列为『马尔库坦之壳』——剧情线以一位至高大天使收尾。", "过场对话已写好，涉及内蒙、马尔库坦、法夫尼尔、西格贝特、克罗梅德与希贝拉。", "埃利奥斯侧：45 级『生命监狱』围绕首领狱卒伊阿戈什建造，另一座围绕镜之守护者——瞄准 40-50 级进阶空档的中级内容。"]),
        section("ascension", "已登记单人试炼：克罗丽丝深渊与西格贝特深渊", ["两座单人试炼已完整登记——名称、入口、等级范围齐备：埃利奥斯侧克罗丽丝深渊、阿斯莫迪安侧西格贝特深渊。", "它们归属『升阶』试炼系列，最高称号为『深渊之外已证其名』；西格贝特深渊由 50 级首领『深渊西格贝特』守卫。", "已登记的试炼是本批中最接近上线的内容——若在规划新单人终局，该系列是最可能的近期添加。"]),
        section("world-data", "世界补量与新生物", ["新增 2000+ 生物刷新点：埃尔特内 1,196、莫尔海姆 1,061，跨 106 物种，其中 96 种尚无名称、等级或属性——新刷新点聚簇在既有野生动物中不存在的地区标签下。", "早前补丁标记的乘骑模型（克拉默、昆迪希、坎普沙、穆斯库斯等）同时以怪物与坐骑出现，是明显的可驯服坐骑；莫尔海姆还随新的银狼人部落人类 NPC 获得狼人变体。", "六件上锁的 Unique 翅膀（霜、暮、焰、余烬黑、翠金、深蓝）以成套且已委托插画的方式抵达——高级翅膀的强信号。"]),
        section("caveats", "谨慎阅读", ["阿尼亚（无副本的首领）、冰冻挽歌（获得可破坏竞技场地板的小队副本）、虚空阿尔卡尼斯与新塔『埃雷奇』本刀均有动静——更多内容已排期但未定日期。", "以上全部为数据挖掘、非官方。此阶段内容曾在一个月内上线，也曾半年无人问津。将路线图解读视为方向而非承诺。", "NC 公布这些副本与试炼的实际上线计划后，本指南将更新。"]),
      ],
    }),
    ko: articleCopy(guideLabels, "ko", 5, {
      eyebrow: "데이터 마이닝 — 비공식",
      title: "Aion 2 신규 던전·승화 시련: 8월 26일 데이터 마이닝 분석",
      description: "8월 26일 클라이언트 데이터 마이닝은 57레벨 에라쿠스 지하 사원, '마르쿠탄의 껍질' 스토리 라인, 등록된 솔로 시련 2개를 보여줍니다. 발견된 모든 내용을 비공식임을 명시해 정리합니다.",
      intro: "8월 26일 업데이트(8월 25일자 빌드) 데이터 마이닝은 다음 던전 웨이브를 드러냈습니다. 최대 항목은 57레벨 에라쿠스 지하 사원이며, 양 진영 스토리 던전, '승화' 시리즈의 등록된 솔로 시련, 대규모 월드 보강 데이터가 포함됩니다. 모두 미공개·무기한입니다.",
      sourceNote: "AION2T의 8월 26일 데이터 마이닝 보고 기반. 모든 세부는 미확인·비공식이며 NC가 발표하지 않았고 언제든 변경·취소될 수 있습니다.",
      keywords: ["Aion 2 신규 던전", "Aion 2 에라쿠스 지하 사원", "Aion 2 승화 시련", "Aion 2 마르쿠탄", "Aion 2 2026년 8월 데이터 마이닝"],
      sections: [
        section("eracus", "에라쿠스 지하 사원 (Lv57)", "보스 라무아탄, 정예 사원 수호자, 은신 함정 2종(모래 소용돌이, 함정 칼날), 이름 있는 NPC 4명. 이번 패치 신규 에셋의 1/3 이상 차지. 파티용 에라쿠스 유적 지도도 동시에 성장."),
        section("story-dungeons", "양 진영 스토리 던전", "아스모디안: 지크베르트 가디언 + 헤베라 중간 보스, 60~65레벨 '마르쿠탄의 껍질' 보스전, 엠피리언 로드로 마무리. 엘리오스: 45레벨 '생명 감옥'(보스 간수 이아고쉬)과 거울 수호자 던전."),
        section("ascension", "등록된 솔로 시련: 클로리스·지크베르트 심연", "두 솔로 시련이 이름·입구·레벨 범위까지 완전 등록됐습니다. '승화' 시리즈로 최고 칭호는 '심연 너머 증명된 가치', 지크베르트 심연은 Lv50 보스 심연 지크베르트가 수호합니다."),
        section("world-data", "월드 보강과 신규 생물", "엘트넨 1,196·모르헤임 1,061 스폰(106종, 96종 미명명). 탈것 모델(크라머, 쿤디시, 캄샤, 무스쿠스)은 사냥감이자 탈것으로 타먹기 가능. 모르헤임은 은빛 리칸 부족 NPC와 리칸 변이체 추가. 잠긴 유니크 날개 6종."),
        section("caveats", "주의해서 읽기", "아그니타, 프로즌 라멘트, 보이드아르카니스, 에레흐 타워도 움직였습니다. 전부 비공식이며 일정 미정. 로드맵 해석은 방향일 뿐 약속이 아닙니다."),
      ],
    }),
    ja: articleCopy(guideLabels, "ja", 5, {
      eyebrow: "データマイニング — 非公式",
      title: "Aion 2 新ダンジョン＆昇華トライアル：8月26日データマイニング分析",
      description: "8月26日のクライアントデータマイニングは、Lv57 エラクス地下神殿、『マルクタンの殻』ストーリー、登録済みソロトライアル2つを示します。発見内容を非公式と明示して整理します。",
      intro: "8月26日アップデート（8月25日ビルド）のデータマイニングで次のダンジョン群が判明しました。最大は Lv57 エラクス地下神殿で、両陣営のストーリーダンジョン、『昇華』シリーズの登録済みソロトライアル、大規模なワールド追加データが含まれます。すべて未発表・日程未定です。",
      sourceNote: "AION2T の8月26日データマイニング報告に基づきます。すべて非確認・非公式の開発中コンテンツで、NC は何も発表しておらず変更・中止があり得ます。",
      keywords: ["Aion 2 新ダンジョン", "Aion 2 エラクス地下神殿", "Aion 2 昇華トライアル", "Aion 2 マルクタン", "Aion 2 2026年8月 データマイニング"],
      sections: [
        section("eracus", "エラクス地下神殿（Lv57）", "ボスはラムアタン。精鋭守護者、透明トラップ2種（砂の渦、罠の刃）、名前付きNPC4人。今週の新規アセットの3分の1以上を占め、パーティ用エラクス遺跡マップも成長中。"),
        section("story-dungeons", "両陣営ストーリーダンジョン", "アスモディアン側：ジグベルト守護＋ヘベラ中ボス、Lv60-65『マルクタンの殻』戦（エンピリアンロードで完結）。エリオス側：Lv45『生命監獄』（ボス、看守イアゴーシュ）と鏡の守護者ダンジョン。"),
        section("ascension", "登録済みソロトライアル", "クロリスの深淵（エリオス）とジグベルトの深淵（アスモディアン）が完全登録済み。『昇華』シリーズで最高位は『深淵の先で証明された価値』。Lv50ボス深淵ジグベルトがいます。"),
        section("world-data", "ワールド追加と新生物", "エルトネン1,196・モルヘイム1,061スポーン（106種、96種未命名）。乗騎モデル（クラマー、クンディシ、カンプシャ等）はモンスター兼マウントとして捕獲可能に。銀リカン族NPCとリカン亜種。ロック付きユニーク翼6種。"),
        section("caveats", "注意点", "アグニタ、フローズンラメント、ヴォイドアルカニス、エレフの塔も動きました。すべて非公式・未定です。ロードマップ解釈は方向性であって約束ではありません。"),
      ],
    }),
    fr: articleCopy(guideLabels, "fr", 5, {
      eyebrow: "DATAMINE — NON OFFICIEL",
      title: "Nouveaux donjons et épreuves d'ascension d'Aion 2 : analyse du datamining du 26 août",
      description: "Le datamining du 26 août révèle un temple souterrain d'Eracus (niveau 57), une arc scénaristique « Coquille de Marchutan » et deux épreuves solo enregistrées. Tout est non officiel.",
      intro: "Le datamining du 26 août (build du 25 août) a révélé la prochaine vague de donjons : le temple souterrain d'Eracus (niveau 57), des donjons scénaristiques pour les deux factions, des épreuves solo enregistrées et une grande refonte du monde. Rien n'est annoncé ni daté.",
      sourceNote: "Basé sur le datamining d'AION2T du 26 août. Tout est non confirmé, non officiel, en développement ; NC n'a rien annoncé.",
      keywords: ["Aion 2 nouveaux donjons", "Aion 2 temple d'Eracus", "Aion 2 épreuves d'ascension", "Aion 2 Marchutan"],
      sections: [
        section("eracus", "Temple souterrain d'Eracus (niveau 57)", "Boss Lamuatan, gardiens d'élite, deux pièges invisibles, quatre PNJ nommés. Plus d'un tiers des nouveaux assets. Une carte ruines d'Eracus pour groupes accompagne."),
        section("story-dungeons", "Donjons scénaristiques", "Côté Asmodien : Sigebert + mid-boss Hebera, et un combat 60-65 contre les troupes de Drakan/Beritra dont le boss est « Coquille de Marchutan ». Côté Elyos : Prison de la Vie (niveau 45, boss Iagosh)."),
        section("ascension", "Épreuves solo enregistrées", "Chloris's Abyss (Elyos) et Sigebert's Abyss (Asmodien) sont entièrement enregistrées — série d'ascension, plus haut rang « Worth Proven Beyond the Abyss », boss niveau 50 Abyssal Sigebert."),
        section("world-data", "Monde et créatures", "1 196 spawns à Eltnen, 1 061 à Morheim, 106 espèces (96 sans nom). Montures apprivoisables (Cramer, Kundishi, Campsha, Mooscoos), variantes Lycan et tribu Lycan argentée. Six ailes Uniques cadenassées."),
        section("caveats", "À lire avec prudence", "Agnita, Frozen Lament, VoidArkanis et la tour Erech ont aussi bougé. Tout est dataminé, non officiel et sans date."),
      ],
    }),
    de: articleCopy(guideLabels, "de", 5, {
      eyebrow: "DATAMINE — INOFFIZIELL",
      title: "Neue Aion-2-Dungeons & Aufstiegsprüfungen: Datamining vom 26. August",
      description: "Das Datamining vom 26. August zeigt einen Eracus-Untergrundtempel (Stufe 57), eine „Marchutans Schale“-Story und zwei registrierte Solo-Prüfungen. Alles inoffiziell.",
      intro: "Das Datamining vom 26. August (Build vom 25. August) offenbarte die nächste Dungeon-Welle: Eracus-Untergrundtempel (Stufe 57), Story-Dungeons für beide Fraktionen, registrierte Solo-Prüfungen und große Welt-Nachbestückung. Nichts ist angekündigt oder datiert.",
      sourceNote: "Basierend auf dem Datamining-Bericht von AION2T vom 26. August. Alles ist unbestätigt und inoffiziell; NC hat nichts angekündigt.",
      keywords: ["Aion 2 neue Dungeons", "Aion 2 Eracus-Tempel", "Aion 2 Aufstiegsprüfungen", "Aion 2 Marchutan"],
      sections: [
        section("eracus", "Eracus-Untergrundtempel (Stufe 57)", "Boss Lamuatan, Elitetempelwächter, zwei unsichtbare Fallen, vier benannte NPCs. Mehr als ein Drittel der neuen Assets. Dazu eine Eracus-Ruinen-Karte für Gruppen."),
        section("story-dungeons", "Story-Dungeons", "Asmodier: Sigebert + Mid-Boss Hebera, und ein 60-65-Kampf gegen Drakan/Beritra-Truppen mit „Marchutans Schale“. Elyos: Lebensgefängnis (Stufe 45, Boss Iagosh) und ein Spiegelwächter-Dungeon."),
        section("ascension", "Registrierte Solo-Prüfungen", "Chloris's Abyss (Elyos) und Sigebert's Abyss (Asmodier) sind vollständig registriert — Aufstiegsserie, höchster Rang „Worth Proven Beyond the Abyss“, Boss Stufe 50 Abyssal Sigebert."),
        section("world-data", "Welt und Kreaturen", "1.196 Spawns in Eltnen, 1.061 in Morheim, 106 Arten (96 unbenannt). Zähmbare Reittiere (Cramer, Kundishi, Campsha, Mooscoos), Lycan-Varianten und Silber-Lycan-Stamm. Sechs gesperrte Unique-Flügel."),
        section("caveats", "Vorsicht", "Agnita, Frozen Lament, VoidArkanis und der Turm Erech haben sich auch bewegt. Alles datamined, inoffiziell und ohne Datum."),
      ],
    }),
    es: articleCopy(guideLabels, "es", 5, {
      eyebrow: "DATAMINE — NO OFICIAL",
      title: "Nuevas mazmorras y pruebas de ascensión de Aion 2: datamining del 26 de agosto",
      description: "El datamining del 26 de agosto muestra un Templo subterráneo de Eracus (nivel 57), un arco «Cáscara de Marchutan» y dos pruebas en solitario registradas. Todo no oficial.",
      intro: "El datamining del 26 de agosto (build del 25) reveló la siguiente oleada de mazmorras: Templo subterráneo de Eracus (nivel 57), mazmorras de historia para ambas facciones, pruebas en solitario registradas y una gran reposición del mundo. Nada está anunciado ni fechado.",
      sourceNote: "Basado en el datamining de AION2T del 26 de agosto. Todo es no confirmado y no oficial; NC no ha anunciado nada.",
      keywords: ["Aion 2 nuevas mazmorras", "Aion 2 Templo de Eracus", "Aion 2 pruebas de ascensión", "Aion 2 Marchutan"],
      sections: [
        section("eracus", "Templo subterráneo de Eracus (nivel 57)", "Boss Lamuatan, guardianes de élite, dos trampas invisibles, cuatro PNJ con nombre. Más de un tercio de los nuevos assets. Una ruinas de Eracus para grupos acompaña."),
        section("story-dungeons", "Mazmorras de historia", "Asmodiano: Sigebert + mid-boss Hebera, y un combate 60-65 con «Cáscara de Marchutan». Elyos: Prisión de la Vida (nivel 45, boss Iagosh) y un Guardián del Espejo."),
        section("ascension", "Pruebas en solitario registradas", "Chloris's Abyss (Elyos) y Sigebert's Abyss (Asmodiano) están totalmente registradas — serie de ascensión, rango más alto «Worth Proven Beyond the Abyss», boss nivel 50 Abyssal Sigebert."),
        section("world-data", "Mundo y criaturas", "1.196 spawns en Eltnen, 1.061 en Morheim, 106 especies (96 sin nombre). Monturas domesticables (Cramer, Kundishi, Campsha, Mooscoos), variantes Lycan y tribu Lycan plateada. Seis alas Únicas con candado."),
        section("caveats", "Con cautela", "Agnita, Frozen Lament, VoidArkanis y la torre Erech también se movieron. Todo dataminado, no oficial y sin fecha."),
      ],
    }),
    "pt-br": articleCopy(guideLabels, "pt-br", 5, {
      eyebrow: "DATAMINE — NÃO OFICIAL",
      title: "Novas masmorras e provas de ascensão do Aion 2: datamining de 26 de agosto",
      description: "O datamining de 26 de agosto mostra um Templo subterrâneo de Eracus (nível 57), um arco «Concha de Marchutan» e duas provas solo registradas. Tudo não oficial.",
      intro: "O datamining de 26 de agosto (build de 25 de agosto) revelou a próxima onda de masmorras: Templo subterrâneo de Eracus (nível 57), masmorras de história para as duas facções, provas solo registradas e uma grande reposição do mundo. Nada foi anunciado ou datado.",
      sourceNote: "Com base no datamining da AION2T de 26 de agosto. Tudo é não confirmado e não oficial; a NC não anunciou nada.",
      keywords: ["Aion 2 novas masmorras", "Aion 2 Templo de Eracus", "Aion 2 provas de ascensão", "Aion 2 Marchutan"],
      sections: [
        section("eracus", "Templo subterrâneo de Eracus (nível 57)", "Boss Lamuatan, guardiões de elite, duas armadilhas invisíveis, quatro NPCs com nome. Mais de um terço dos novos assets. Um mapa de ruínas de Eracus para grupos acompanha."),
        section("story-dungeons", "Masmorras de história", "Asmodiano: Sigebert + mid-boss Hebera, e um combate 60-65 com «Concha de Marchutan». Elyos: Prisão da Vida (nível 45, boss Iagosh) e um Guardião do Espelho."),
        section("ascension", "Provas solo registradas", "Chloris's Abyss (Elyos) e Sigebert's Abyss (Asmodiano) estão totalmente registradas — série de ascensão, posto mais alto «Worth Proven Beyond the Abyss», boss nível 50 Abyssal Sigebert."),
        section("world-data", "Mundo e criaturas", "1.196 spawns em Eltnen, 1.061 em Morheim, 106 espécies (96 sem nome). Montarias domesticáveis (Cramer, Kundishi, Campsha, Mooscoos), variantes Lycan e tribo Lycan prateada. Seis asas Únicas com cadeado."),
        section("caveats", "Leia com cuidado", "Agnita, Frozen Lament, VoidArkanis e a torre Erech também se mexeram. Tudo dataminado, não oficial e sem data."),
      ],
    }),
    ru: articleCopy(guideLabels, "ru", 5, {
      eyebrow: "ДАТАМАЙНИНГ — НЕОФИЦИАЛЬНО",
      title: "Новые данжи и испытания вознесения Aion 2: разбор датамайнинга от 26 августа",
      description: "Датамайнинг от 26 августа показывает Подземный храм Эракуса (ур. 57), сюжетную арку «Оболочка Маркутана» и два зарегистрированных соло-испытания. Всё неофициально.",
      intro: "Датамайнинг обновления от 26 августа (билд от 25-го) раскрыл следующую волну данжей: Подземный храм Эракуса (ур. 57), сюжетные данжи обеих фракций, зарегистрированные соло-испытания и крупное наполнение мира. Ничего не анонсировано и не датировано.",
      sourceNote: "На основе отчёта AION2T от 26 августа. Всё неподтверждённо и неофициально; NC ничего не анонсировала.",
      keywords: ["Aion 2 новые данжи", "Aion 2 храм Эракуса", "Aion 2 испытания вознесения", "Aion 2 Маркутан"],
      sections: [
        section("eracus", "Подземный храм Эракуса (ур. 57)", "Босс Ламуатан, элитные стражи, две невидимые ловушки, четыре именованных NPC. Более трети новых ассетов. Рядом — карта руин Эракуса для групп."),
        section("story-dungeons", "Сюжетные данжи", "Асмодиане: Зигберт + мид-босс Хебера, и бой 60-65 с «Оболочкой Маркутана». Элиос: Тюрьма Жизни (ур. 45, босс Иагош) и данж Стража Зеркала."),
        section("ascension", "Зарегистрированные соло-испытания", "Бездна Хлорис (Элиос) и Бездна Зигберта (Асмодиане) полностью зарегистрированы — серия вознесения, высший ранг «Worth Proven Beyond the Abyss», босс ур. 50 Бездный Зигберт."),
        section("world-data", "Мир и существа", "1 196 спавнов в Эльтнене, 1 061 в Морхейме, 106 видов (96 без имён). Обучаемые ездовые (Крамер, Кундиши, Кампша, Мусскус), варианты ликанов и племя серебряных ликанов. Шесть запертых Уникальных крыльев."),
        section("caveats", "Читайте с осторожностью", "Агнита, Замёрзший плач, ВойдАрканис и башня Эрех тоже сдвинулись. Всё датамайнинг, неофициально и без дат."),
      ],
    }),
    "zh-hant": articleCopy(guideLabels, "zh-hant", 5, {
      eyebrow: "資料挖掘——非官方",
      title: "Aion 2 新副本與升階試煉：8 月 26 日資料挖掘拆解",
      description: "8 月 26 日用戶端資料挖掘拼出 57 級埃拉庫斯地下神殿、『馬爾庫坦之殼』劇情線以及兩個已登記的試煉。以下為全部發現——均明確標註為非官方。",
      intro: "對 8 月 26 日更新（用戶端建置日期 8 月 25 日）的資料挖掘浮出遊戲下一波副本內容：最大單項是 57 級埃拉庫斯地下神殿，同一批資料還包含雙方陣營劇情副本、登記在『升階』系列下的單人試煉，以及一波世界補量資料。以上均未公布、無日期。本指南梳理發現並按路線圖推理其含義。",
      sourceNote: "基於 AION2T 8 月 26 日資料挖掘報告。本文全部細節為未確認、非官方的開發中內容；NC 未公布任何一項，隨時可能變更或取消。",
      keywords: ["Aion 2 新副本", "Aion 2 埃拉庫斯地下神殿", "Aion 2 升階試煉", "Aion 2 馬爾庫坦", "Aion 2 2026年8月資料挖掘"],
      sections: [
        section("eracus", "埃拉庫斯地下神殿（57 級）", ["主角：57 級副本，首領拉穆阿坦，含精英神殿守衛、兩個隱形陷阱（沙暴漩渦與陷阱之刃）以及四名有名字的角色。本週新增檔案數超過全部新資產的 1/3。", "地圖結構為獨立入口廳、單一通道，再向東分叉的洞穴；旁邊還同步長出面向小隊的埃拉庫斯遺跡地圖。", "工作量如此集中的 57 級副本，是本批中『大型團隊本正在排期』的最強訊號。"]),
        section("story-dungeons", "雙方陣營劇情副本", ["阿斯莫迪安側兩座劇情副本接近完成：一座由西格貝特守衛（含希貝拉中boss與墮落達埃瓦圖鑑），另一座為 60-65 級對戰德拉坎與貝里特拉軍隊，首領列為『馬爾庫坦之殼』——劇情線以一位至高大天使收尾。", "過場對話已寫好，涉及內蒙、馬爾庫坦、法夫尼爾、西格貝特、克羅梅德與希貝拉。", "埃利奧斯側：45 級『生命監獄』圍繞首領獄卒伊阿戈什建造，另一座圍繞鏡之守護者——瞄準 40-50 級進階空檔的中級內容。"]),
        section("ascension", "已登記單人試煉：克羅麗絲深淵與西格貝特深淵", ["兩座單人試煉已完整登記——名稱、入口、等級範圍齊備：埃利奧斯側克羅麗絲深淵、阿斯莫迪安側西格貝特深淵。", "它們歸屬『升階』試煉系列，最高稱號為『深淵之外已證其名』；西格貝特深淵由 50 級首領『深淵西格貝特』守衛。", "已登記的試煉是本批中最接近上線的內容——若在規劃新單人終局，該系列是最可能的近期添加。"]),
        section("world-data", "世界補量與新生物", ["新增 2000+ 生物刷新點：埃爾特內 1,196、莫爾海姆 1,061，跨 106 物種，其中 96 種尚無名稱、等級或屬性——新刷新點聚簇在既有野生動物中不存在的地區標籤下。", "早前修補程式標記的乘騎模型（克拉默、昆迪希、坎普沙、穆斯庫斯等）同時以怪物與坐騎出現，是明顯的可馴服坐騎；莫爾海姆還隨新的銀狼人部落人類 NPC 獲得狼人變體。", "六件上鎖的 Unique 翅膀（霜、暮、焰、餘燼黑、翠金、深藍）以成套且已委託插畫的方式抵達——高級翅膀的強訊號。"]),
        section("caveats", "謹慎閱讀", ["阿尼亞（無副本的首領）、冰凍輓歌（獲得可破壞競技場地板的隊伍副本）、虛空阿爾卡尼斯與新塔『埃雷奇』本刀均有動靜——更多內容已排期但未定日期。", "以上全部為資料挖掘、非官方。此階段內容曾在一個月內上線，也曾半年無人問津。將路線圖解讀視為方向而非承諾。", "NC 公布這些副本與試煉的實際上線計畫後，本指南將更新。"]),
      ],
    }),
  },
};