import { articleCopy, guideLabels, localizations, publishedVerified, section } from "./trending-august-22-shared";
import type { ContentEntry, ContentHeroImage, ContentSource } from "./content-registry";

/* ARTICLE 3 — Server regions guide: Global, TW & KR */

const regionSource1: ContentSource = { id: "aion2hub-servers-2026-08-22", kind: "third-party", publisher: "AION2Hub", label: "AION 2 Server Regions — Global, TW, KR Comparison", url: "https://aion2hub.com/", publishedAt: "2026-07-15", retrievedAt: "2026-08-22", verifiedAt: "2026-08-22", localizations: localizations({ "zh-hans": "AION 2 服务器区域——全球、台服、韩服对比", en: "AION 2 Server Regions — Global, TW, KR Comparison", fr: "Régions des serveurs AION 2 — Comparaison Global, TW, KR", de: "AION 2 Serverregionen — Global, TW, KR im Vergleich", es: "Regiones de servidores de AION 2 — Comparativa Global, TW, KR", ja: "AION 2 サーバーリージョン — グローバル、TW、KR 比較", "pt-br": "Regiões de servidores de AION 2 — Comparação Global, TW, KR", ru: "Регионы серверов AION 2 — Сравнение Global, TW, KR", ko: "AION 2 서버 지역 — 글로벌, TW, KR 비교", "zh-hant": "AION 2 伺服器區域——全球、台服、韓服對比", }, "https://aion2hub.com/"), };
const regionSource2: ContentSource = { id: "plaync-servers-2026-08-22", kind: "official", publisher: "NCSOFT", label: "AION 2 (KR) — 서버 안내", url: "https://aion2.plaync.com/ko-kr/intro/server", publishedAt: "2026-06-15", retrievedAt: "2026-08-22", verifiedAt: "2026-08-22", localizations: localizations({ "zh-hans": "AION 2（韩服）— 服务器说明", en: "AION 2 (KR) — Server Guide", fr: "AION 2 (KR) — Guide des serveurs", de: "AION 2 (KR) — Server-Anleitung", es: "AION 2 (KR) — Guía de servidores", ja: "AION 2 (KR) — サーバーガイド", "pt-br": "AION 2 (KR) — Guia de servidores", ru: "AION 2 (KR) — Руководство по серверам", ko: "AION 2 (KR) — 서버 안내", "zh-hant": "AION 2（韓服）— 伺服器說明", }, "https://aion2.plaync.com/ko-kr/intro/server"), };
const regionSource3: ContentSource = { id: "steam-aion2-2026-08-22", kind: "third-party", publisher: "Steam", label: "AION 2 on Steam — Global Server Info", url: "https://store.steampowered.com/app/3393110/AION_2/", publishedAt: "2026-07-20", retrievedAt: "2026-08-22", verifiedAt: "2026-08-22", localizations: localizations({ "zh-hans": "AION 2 Steam 页面", en: "AION 2 on Steam", fr: "AION 2 sur Steam", de: "AION 2 auf Steam", es: "AION 2 en Steam", ja: "Steam の AION 2", "pt-br": "AION 2 na Steam", ru: "AION 2 в Steam", ko: "Steam의 AION 2", "zh-hant": "AION 2 Steam 頁面", }, "https://store.steampowered.com/app/3393110/AION_2/"), };
const regionHero: ContentHeroImage = { src: "https://blogfiles.ncsoft.net/news/bcba48a7-39dc-40ff-b53c-266a7547d63c.jpg", width: 1100, height: 605, credit: "NC Corporation", sourceUrl: "https://aion2.plaync.com/ko-kr/intro/server", rights: "linked-official-media", translations: { "zh-hans": { alt: "服务器区域指南配图", caption: "NC 官方配图；AION 2 在全球多个区域运营，每个区域都有独特的社区与运营特点。" }, en: { alt: "Server regions guide image", caption: "Official NC artwork; AION 2 operates across multiple regions, each with its own community and service characteristics." }, fr: { alt: "Image du guide des régions de serveurs", caption: "Visuel officiel NC ; AION 2 est disponible dans plusieurs régions avec des caractéristiques uniques." }, de: { alt: "Serverregionen-Guide-Bild", caption: "Offizielles NC-Artwork; AION 2 wird in mehreren Regionen mit eigenen Communities betrieben." }, es: { alt: "Imagen de la guía de regiones de servidores", caption: "Arte oficial de NC; AION 2 opera en múltiples regiones con comunidades y características únicas." }, ja: { alt: "サーバーリージョンガイド画像", caption: "NC公式アートワーク；AION 2 は複数のリージョンで運営され、それぞれ独自のコミュニティと特徴があります。" }, "pt-br": { alt: "Imagem do guia de regiões de servidores", caption: "Arte oficial da NC; AION 2 opera em múltiplas regiões, cada uma com sua própria comunidade." }, ru: { alt: "Изображение гайда по регионам серверов", caption: "Официальный арт NC; AION 2 работает в нескольких регионах с уникальными сообществами." }, ko: { alt: "서버 지역 가이드 이미지", caption: "NC 공식 이미지입니다. AION 2는 여러 지역에서 운영되며, 각 지역마다 고유한 커뮤니티와 운영 특징이 있습니다." }, "zh-hant": { alt: "伺服器區域指南配圖", caption: "NC 官方配圖；AION 2 在全球多個區域營運，每個區域都有獨特的社群與營運特點。" }, }, };

export const trendingAugust22Article3: ContentEntry = {
  section: "guides", slug: "aion-2-server-regions-guide", schemaType: "Article",
  publishedAt: "2026-08-22", updatedAt: "2026-08-22", readingMinutes: 5,
  publication: publishedVerified,
  sources: [regionSource1, regionSource2, regionSource3],
  heroImage: regionHero,
  related: [
    { kind: "content", section: "guides", slug: "aion-2-client-pre-download-guide" },
    { kind: "content", section: "guides", slug: "aion-2-leveling-guide-1-50" },
    { kind: "content", section: "guides", slug: "aion-2-pvp-guide" },
  ],
  translations: {
    en: articleCopy(guideLabels, "en", 5, {
      eyebrow: "SERVER REGIONS", title: "Aion 2 Server Regions Guide: Global, TW & KR — Which Server to Choose", description: "Aion 2 runs on three separate regional servers — Global, Taiwan, and Korea. Each has its own publisher, language support, payment model, and community. This guide breaks down the differences so you can pick the right home.", intro: "Aion 2 is not a single unified server. NCSoft operates three separate regional services: the Global server (via Steam), the Taiwan server (via Gamania), and the Korea server (via plaync). Each region has its own client build, localization, update schedule, cash shop, and community. Your choice of server determines everything from latency and language to the player economy and endgame population. This guide compares all three regions across every major factor so you can make an informed decision before you commit.", sourceNote: "Based on AION2Hub's server comparison, the official NCSoft plaync server guide, and the Steam global release page. Regional differences reflect the current service structures as of August 2026.", keywords: ["Aion 2 server regions", "Aion 2 global server", "Aion 2 Taiwan server", "Aion 2 Korea server", "Aion 2 which server to choose", "Aion 2 server comparison"],
      sections: [
        section("global-server", "Global Server: Western Early Access", ["The Global server is the primary destination for Western players. Launched via Steam in early access, it supports English, French, German, Spanish, and other European languages. The Global version uses the latest game build and follows the Chapter 1 content roadmap aligned with the global release schedule.", "Key advantages include official English-language support, Steam integration for easy payment and friend management, and a growing population of Western players. The Global cash shop is priced in USD, and the endgame population is active during NA/EU primetime hours. Cross-region play with TW or KR servers is not supported — Global is a completely isolated ecosystem."]),
        section("tw-server", "Taiwan Server: Chinese Community Hub", ["The Taiwan server is operated by Gamania under license from NCSoft. It serves players from Taiwan, Hong Kong, Macau, and the broader traditional Chinese-speaking community. The client is fully localized in Traditional Chinese (zh-hant), with in-game text, UI, and voice-over all in Chinese.", "The Taiwan server has its own distinct update schedule that often differs from the Global and KR releases. Gamania operates localized events, promotions, and cash shop pricing in NTD. Latency is excellent for players in East and Southeast Asia, and the community is tightly knit. However, the Taiwan server does not support English UI or cross-region transfers."]),
        section("kr-server", "Korea Server: The Original Experience", ["The Korea server, operated directly by NCSoft on plaync, is the original version of Aion 2. It runs on the most advanced build and receives patches first — Global and TW builds are ported from the KR version. The Korean server requires a Korean resident registration number (KSSN) for account creation, which effectively gates access to non-residents.", "For Korean players, the KR server offers the lowest latency, the most complete content at any given time, and deep integration with NCSoft's broader ecosystem (including the plaync launcher and Korean payment methods). The cash shop uses KRW, and the community is almost entirely Korean-speaking. For non-Korean players who can access it, the KR server offers the earliest access to new content, but the language barrier and payment friction are significant."]),
        section("server-selection", "Which Server Should You Choose?", ["Your choice comes down to language, latency, and community. If you are a Western player who wants English-language support and Steam convenience, the Global server is the clear choice. If you are a Traditional Chinese speaker in Taiwan, Hong Kong, or Macau, the TW server offers full localization and local payment options. If you are a Korean resident or a player who wants the earliest access to new content and can navigate the KSSN and language hurdles, the KR server is the original experience.", "For most players, the Global server is the recommended starting point: it has the largest international population, official English support, and the most accessible payment and account creation process. The server population is growing steadily through the early access and launch windows, and the endgame community is active across all time zones. Whichever server you choose, Aion 2's core gameplay — the action combat, the Legion system, the Abyss PvP, and the expedition loops — is identical across all three regions."]),
      ],
    }),
    "zh-hans": articleCopy(guideLabels, "zh-hans", 5, {
      eyebrow: "服务器区域", title: "Aion 2 服务器区域指南：全球、台服、韩服——如何选择", description: "Aion 2 在三个独立的区域服务器上运营——全球、台湾和韩国。每个服务器有自己的发行商、语言支持、付费模式和社区。本指南详细对比差异，帮你选择正确的家。", intro: "Aion 2 并非统一的服务器。NCSoft 运营三个独立的区域服务：全球服务器（通过 Steam）、台湾服务器（通过游戏橘子）和韩国服务器（通过 plaync）。每个区域拥有自己的客户端版本、本地化、更新计划、商城和社区。", sourceNote: "基于 AION2Hub 的服务器对比、NCSoft plaync 官方服务器指南以及 Steam 全球发布页面。", keywords: ["Aion 2 服务器区域", "Aion 2 全球服务器", "Aion 2 台服", "Aion 2 韩服", "Aion 2 服务器选择"],
      sections: [
        section("global-server", "全球服务器：西方抢先体验", ["全球服务器是西方玩家的主要目的地。通过 Steam 抢先体验发布，支持英语、法语、德语、西班牙语等欧洲语言。全球版使用最新游戏版本，遵循与全球发布计划一致的第二章内容路线图。", "主要优势包括官方英语支持、Steam 集成、以及快速增长的西方玩家群体。全球商城以美元定价。不支持与台服或韩服的跨区游戏。"]),
        section("tw-server", "台湾服务器：中文社区中心", ["台湾服务器由游戏橘子（Gamania）在 NCSoft 授权下运营，服务于台湾、香港、澳门及整个繁体中文社区的玩家。客户端完全本地化为繁体中文。", "台湾服务器拥有自己独特的更新计划，通常与全球和韩服发布不同步。游戏橘子运营本地化活动、促销活动，商城以新台币定价。"]),
        section("kr-server", "韩国服务器：原汁原味体验", ["韩国服务器由 NCSoft 直接在 plaync 上运营，是 Aion 2 的原始版本。它运行在最新的版本上，最先接收补丁。韩服账号注册需要韩国居民身份证号（KSSN），这实际上限制了非居民的访问。", "对于韩国玩家，韩服提供最低延迟、最完整的内容和与 NCSoft 生态系统的深度整合。商城以韩元定价，社区几乎全是韩语。"]),
        section("server-selection", "你应该选择哪个服务器？", ["你的选择取决于语言、延迟和社区。西方玩家需要英语支持的话，全球服务器是明确选择。繁体中文玩家在台湾、香港、澳门的话，台服提供完整本地化和本地支付选项。", "对于大多数玩家，全球服务器是推荐起点：拥有最大的国际人口、官方英语支持以及最便捷的支付和账号创建流程。"]),
      ],
    }),
    ko: articleCopy(guideLabels, "ko", 5, {
      eyebrow: "서버 지역", title: "Aion 2 서버 지역 가이드: 글로벌, TW, KR — 어떤 서버를 선택할까", description: "Aion 2는 글로벌, 대만, 한국의 세 가지 독립적인 지역 서버로 운영됩니다. 각 서버는 고유한 퍼블리셔, 언어 지원, 결제 모델 및 커뮤니티를 가지고 있습니다.", intro: "Aion 2는 단일 통합 서버가 아닙니다. NCSoft는 글로벌(Steam), 대만(게임니아), 한국(plaync)의 세 가지 독립적인 지역 서비스를 운영합니다. 각 지역마다 고유한 클라이언트 빌드, 현지화, 업데이트 일정, 캐시샵 및 커뮤니티가 있습니다.", sourceNote: "AION2Hub의 서버 비교, 공식 NCSoft plaync 서버 가이드, Steam 글로벌 출시 페이지에 기반합니다.", keywords: ["Aion 2 서버 지역", "Aion 2 글로벌 서버", "Aion 2 대만 서버", "Aion 2 한국 서버", "Aion 2 서버 선택"],
      sections: [
        section("global-server", "글로벌 서버: 서양 얼리 액세스", ["글로벌 서버는 서양 플레이어를 위한 주요 서버입니다. Steam을 통해 얼리 액세스로 출시되었으며 영어, 프랑스어, 독일어, 스페인어 등을 지원합니다.", "주요 장점은 공식 영어 지원, Steam 통합, 빠르게 성장하는 서양 플레이어 기반입니다. 캐시샵은 USD로 가격이 책정됩니다."]),
        section("tw-server", "대만 서버: 중국어 커뮤니티 허브", ["대만 서버는 게임니아(Gamania)가 NCSoft의 라이선스 하에 운영합니다. 대만, 홍콩, 마카오 및 번체 중국어 사용자 커뮤니티를 대상으로 합니다.", "대만 서버는 글로벌 및 KR 릴리스와 다른 고유한 업데이트 일정을 가지고 있습니다. 게임니아는 현지화된 이벤트와 프로모션을 운영합니다."]),
        section("kr-server", "한국 서버: 오리지널 경험", ["한국 서버는 NCSoft가 plaync에서 직접 운영하는 Aion 2의 원본 버전입니다. 가장 최신 빌드로 실행되며 패치를 가장 먼저 받습니다.", "한국 플레이어에게 최저 지연 시간, 가장 완전한 콘텐츠, NCSoft 생태계와의 깊은 통합을 제공합니다. 비한국인 접근은 KSSN 장벽이 있습니다."]),
        section("server-selection", "어떤 서버를 선택해야 할까?", ["선택은 언어, 지연 시간 및 커뮤니티에 달려 있습니다. 대부분의 플레이어에게 글로벌 서버가 권장 시작점입니다: 가장 큰 국제 인구, 공식 영어 지원, 가장 접근하기 쉬운 계정 생성 프로세스를 제공합니다."]),
      ],
    }),
    ja: articleCopy(guideLabels, "ja", 5, {
      eyebrow: "サーバーリージョン", title: "Aion 2 サーバーリージョンガイド：グローバル、TW、KR — どのサーバーを選ぶべきか", description: "Aion 2 はグローバル、台湾、韓国の3つの独立した地域サーバーで運営されています。各サーバーには独自のパブリッシャー、言語サポート、決済モデル、コミュニティがあります。", intro: "Aion 2 は単一の統合サーバーではありません。NCSoft はグローバル（Steam）、台湾（Gamania）、韓国（plaync）の3つの独立した地域サービスを運営しています。", sourceNote: "AION2Hub のサーバー比較、公式 NCSoft plaync サーバーガイド、Steam グローバルリリースページに基づきます。", keywords: ["Aion 2 サーバーリージョン", "Aion 2 グローバルサーバー", "Aion 2 台湾サーバー", "Aion 2 韓国サーバー", "Aion 2 サーバー選択"],
      sections: [
        section("global-server", "グローバルサーバー：西洋アーリーアクセス", ["グローバルサーバーは西洋プレイヤーの主要な拠点です。Steam でアーリーアクセスリリースされ、英語、フランス語、ドイツ語、スペイン語などをサポートしています。", "主な利点は公式英語サポート、Steam 統合、成長する西洋プレイヤーベースです。キャッシュショップは USD 価格です。"]),
        section("tw-server", "台湾サーバー：中国語圏コミュニティハブ", ["台湾サーバーは Gamania が NCSoft のライセンスの下で運営しています。台湾、香港、マカオ、および繁体字中国語圏コミュニティ向けです。", "台湾サーバーはグローバルや KR とは異なる独自の更新スケジュールを持ち、Gamania がローカライズイベントを運営しています。"]),
        section("kr-server", "韓国サーバー：オリジナル体験", ["韓国サーバーは NCSoft が plaync で直接運営する Aion 2 のオリジナルバージョンです。最新ビルドで実行され、パッチを最も早く受け取ります。", "韓国プレイヤーに最低遅延、最も完全なコンテンツ、NCSoft エコシステムとの深い統合を提供します。"]),
        section("server-selection", "どのサーバーを選ぶべきか？", ["選択は言語、遅延、コミュニティによって決まります。ほとんどのプレイヤーにはグローバルサーバーが推奨されます：最大の国際人口、公式英語サポート、最もアクセスしやすいアカウント作成プロセスを備えています。"]),
      ],
    }),
    fr: articleCopy(guideLabels, "fr", 5, {
      eyebrow: "RÉGIONS DE SERVEURS", title: "Guide des régions de serveurs d'Aion 2 : Global, TW & KR — Quel serveur choisir", description: "Aion 2 fonctionne sur trois serveurs régionaux distincts — Global, Taiwan et Corée. Chacun a son propre éditeur, support linguistique, modèle de paiement et communauté.", intro: "Aion 2 n'est pas un serveur unifié. NCSoft exploite trois services régionaux séparés : le serveur Global (via Steam), le serveur Taiwan (via Gamania) et le serveur Corée (via plaync).", sourceNote: "Basé sur la comparaison des serveurs d'AION2Hub, le guide officiel plaync NCSoft et la page de sortie Steam.", keywords: ["Aion 2 régions de serveurs", "Aion 2 serveur global", "Aion 2 serveur Taiwan", "Aion 2 serveur Corée", "Aion 2 choix de serveur"],
      sections: [
        section("global-server", "Serveur Global : Accès anticipé occidental", ["Le serveur Global est la destination principale pour les joueurs occidentaux. Lancé via Steam en accès anticipé, il prend en charge l'anglais, le français, l'allemand, l'espagnol et d'autres langues européennes.", "Avantages : support officiel en anglais, intégration Steam, population occidentale croissante. La boutique est en USD."]),
        section("tw-server", "Serveur Taiwan : Hub communautaire chinois", ["Le serveur Taiwan est exploité par Gamania sous licence NCSoft. Il dessert les joueurs de Taiwan, Hong Kong, Macao et de la communauté chinoise traditionnelle.", "Le serveur a son propre calendrier de mises à jour, des événements localisés et des prix en NTD."]),
        section("kr-server", "Serveur Corée : L'expérience originale", ["Le serveur Corée, exploité directement par NCSoft sur plaync, est la version originale d'Aion 2. Il reçoit les patchs en premier.", "Pour les joueurs coréens : latence minimale, contenu le plus complet, intégration profonde avec l'écosystème NCSoft."]),
        section("server-selection", "Quel serveur choisir ?", ["Le choix dépend de la langue, de la latence et de la communauté. Pour la plupart des joueurs, le serveur Global est recommandé : plus grande population internationale, support officiel en anglais, processus de création de compte le plus accessible."]),
      ],
    }),
    de: articleCopy(guideLabels, "de", 5, {
      eyebrow: "SERVERREGIONEN", title: "Aion 2 Serverregionen-Guide: Global, TW & KR — Welchen Server wählen", description: "Aion 2 wird auf drei separaten regionalen Servern betrieben — Global, Taiwan und Korea. Jeder hat seinen eigenen Publisher, Sprachsupport, Bezahlmodell und Community.", intro: "Aion 2 ist kein einheitlicher Server. NCSoft betreibt drei separate regionale Dienste: den Global-Server (via Steam), den Taiwan-Server (via Gamania) und den Korea-Server (via plaync).", sourceNote: "Basiert auf dem Serververgleich von AION2Hub, dem offiziellen plaync NCSoft-Server-Guide und der Steam-Release-Seite.", keywords: ["Aion 2 Serverregionen", "Aion 2 Global-Server", "Aion 2 Taiwan-Server", "Aion 2 Korea-Server", "Aion 2 Serverwahl"],
      sections: [
        section("global-server", "Global-Server: Westlicher Early Access", ["Der Global-Server ist das Hauptziel für westliche Spieler. Über Steam im Early Access gestartet, unterstützt er Englisch, Französisch, Deutsch, Spanisch und andere europäische Sprachen.", "Vorteile: offizieller englischer Support, Steam-Integration, wachsende westliche Spielerbasis. Der Shop ist in USD bepreist."]),
        section("tw-server", "Taiwan-Server: Chinesischer Community-Hub", ["Der Taiwan-Server wird von Gamania unter NCSoft-Lizenz betrieben. Er bedient Spieler aus Taiwan, Hongkong, Macau und der traditionell chinesischsprachigen Community.", "Der Server hat seinen eigenen Update-Zeitplan, lokalisierte Events und Preise in NTD."]),
        section("kr-server", "Korea-Server: Das Original-Erlebnis", ["Der Korea-Server, direkt von NCSoft auf plaync betrieben, ist die Originalversion von Aion 2. Er erhält Patches zuerst.", "Für koreanische Spieler: niedrigste Latenz, vollständigste Inhalte, tiefe Integration mit dem NCSoft-Ökosystem."]),
        section("server-selection", "Welchen Server solltest du wählen?", ["Die Wahl hängt von Sprache, Latenz und Community ab. Für die meisten Spieler ist der Global-Server die Empfehlung: größte internationale Bevölkerung, offizieller englischer Support, zugänglichster Account-Erstellungsprozess."]),
      ],
    }),
    es: articleCopy(guideLabels, "es", 5, {
      eyebrow: "REGIONES DE SERVIDORES", title: "Guía de regiones de servidores de Aion 2: Global, TW y KR — Qué servidor elegir", description: "Aion 2 funciona en tres servidores regionales separados: Global, Taiwán y Corea. Cada uno tiene su propio editor, soporte de idioma, modelo de pago y comunidad.", intro: "Aion 2 no es un servidor unificado. NCSoft opera tres servicios regionales separados: el servidor Global (vía Steam), el servidor Taiwán (vía Gamania) y el servidor Corea (vía plaync).", sourceNote: "Basado en la comparación de servidores de AION2Hub, la guía oficial de servidores de plaync NCSoft y la página de lanzamiento de Steam.", keywords: ["Aion 2 regiones de servidores", "Aion 2 servidor global", "Aion 2 servidor Taiwán", "Aion 2 servidor Corea", "Aion 2 elección de servidor"],
      sections: [
        section("global-server", "Servidor Global: Acceso anticipado occidental", ["El servidor Global es el destino principal para los jugadores occidentales. Lanzado vía Steam en acceso anticipado, soporta inglés, francés, alemán, español y otros idiomas europeos.", "Ventajas: soporte oficial en inglés, integración con Steam, población occidental creciente. La tienda está en USD."]),
        section("tw-server", "Servidor Taiwán: Centro comunitario chino", ["El servidor Taiwán es operado por Gamania bajo licencia de NCSoft. Atiende a jugadores de Taiwán, Hong Kong, Macao y la comunidad de habla china tradicional.", "El servidor tiene su propio calendario de actualizaciones, eventos localizados y precios en NTD."]),
        section("kr-server", "Servidor Corea: La experiencia original", ["El servidor Corea, operado directamente por NCSoft en plaync, es la versión original de Aion 2. Recibe parches primero.", "Para jugadores coreanos: latencia más baja, contenido más completo, integración profunda con el ecosistema NCSoft."]),
        section("server-selection", "¿Qué servidor deberías elegir?", ["La elección depende del idioma, la latencia y la comunidad. Para la mayoría de los jugadores, el servidor Global es la recomendación: mayor población internacional, soporte oficial en inglés, proceso de creación de cuenta más accesible."]),
      ],
    }),
    "pt-br": articleCopy(guideLabels, "pt-br", 5, {
      eyebrow: "REGIÕES DE SERVIDORES", title: "Guia de regiões de servidores de Aion 2: Global, TW e KR — Qual servidor escolher", description: "Aion 2 opera em três servidores regionais separados — Global, Taiwan e Coreia. Cada um tem seu próprio editor, suporte de idioma, modelo de pagamento e comunidade.", intro: "Aion 2 não é um servidor unificado. A NCSoft opera três serviços regionais separados: o servidor Global (via Steam), o servidor Taiwan (via Gamania) e o servidor Coreia (via plaync).", sourceNote: "Baseado na comparação de servidores da AION2Hub, no guia oficial de servidores da plaync NCSoft e na página de lançamento da Steam.", keywords: ["Aion 2 regiões de servidores", "Aion 2 servidor global", "Aion 2 servidor Taiwan", "Aion 2 servidor Coreia", "Aion 2 escolha de servidor"],
      sections: [
        section("global-server", "Servidor Global: Acesso antecipado ocidental", ["O servidor Global é o destino principal para jogadores ocidentais. Lançado via Steam em acesso antecipado, suporta inglês, francês, alemão, espanhol e outros idiomas europeus.", "Vantagens: suporte oficial em inglês, integração Steam, população ocidental crescente. A loja é em USD."]),
        section("tw-server", "Servidor Taiwan: Hub da comunidade chinesa", ["O servidor Taiwan é operado pela Gamania sob licença da NCSoft. Atende jogadores de Taiwan, Hong Kong, Macau e da comunidade de língua chinesa tradicional.", "O servidor tem seu próprio calendário de atualizações, eventos localizados e preços em NTD."]),
        section("kr-server", "Servidor Coreia: A experiência original", ["O servidor Coreia, operado diretamente pela NCSoft no plaync, é a versão original de Aion 2. Recebe patches primeiro.", "Para jogadores coreanos: menor latência, conteúdo mais completo, integração profunda com o ecossistema NCSoft."]),
        section("server-selection", "Qual servidor escolher?", ["A escolha depende do idioma, latência e comunidade. Para a maioria dos jogadores, o servidor Global é a recomendação: maior população internacional, suporte oficial em inglês, processo de criação de conta mais acessível."]),
      ],
    }),
    ru: articleCopy(guideLabels, "ru", 5, {
      eyebrow: "РЕГИОНЫ СЕРВЕРОВ", title: "Гайд по регионам серверов Aion 2: Global, TW и KR — какой сервер выбрать", description: "Aion 2 работает на трёх отдельных региональных серверах — Global, Тайвань и Корея. У каждого свой издатель, языковая поддержка, платёжная модель и сообщество.", intro: "Aion 2 — это не единый сервер. NCSoft управляет тремя отдельными региональными сервисами: Global (через Steam), Тайвань (через Gamania) и Корея (через plaync).", sourceNote: "На основе сравнения серверов AION2Hub, официального руководства plaync NCSoft и страницы запуска Steam.", keywords: ["Aion 2 регионы серверов", "Aion 2 глобальный сервер", "Aion 2 сервер Тайвань", "Aion 2 сервер Корея", "Aion 2 выбор сервера"],
      sections: [
        section("global-server", "Глобальный сервер: Западный ранний доступ", ["Глобальный сервер — основное место для западных игроков. Запущен через Steam в раннем доступе, поддерживает английский, французский, немецкий, испанский и другие европейские языки.", "Преимущества: официальная поддержка английского, интеграция Steam, растущая западная аудитория. Магазин в USD."]),
        section("tw-server", "Тайваньский сервер: Китайский хаб сообщества", ["Тайваньский сервер управляется Gamania по лицензии NCSoft. Он обслуживает игроков из Тайваня, Гонконга, Макао и сообщества традиционного китайского языка.", "У сервера свой график обновлений, локализованные события и цены в NTD."]),
        section("kr-server", "Корейский сервер: Оригинальный опыт", ["Корейский сервер, управляемый напрямую NCSoft на plaync, — оригинальная версия Aion 2. Он получает патчи первым.", "Для корейских игроков: минимальная задержка, самый полный контент, глубокая интеграция с экосистемой NCSoft."]),
        section("server-selection", "Какой сервер выбрать?", ["Выбор зависит от языка, задержки и сообщества. Для большинства игроков рекомендуется глобальный сервер: самое большое международное население, официальная поддержка английского, самый доступный процесс создания аккаунта."]),
      ],
    }),
    "zh-hant": articleCopy(guideLabels, "zh-hant", 5, {
      eyebrow: "伺服器區域", title: "Aion 2 伺服器區域指南：全球、台服、韓服——如何選擇", description: "Aion 2 在三個獨立的區域伺服器上營運——全球、台灣和韓國。每個伺服器有自己的發行商、語言支援、付費模式和社群。", intro: "Aion 2 並非統一的伺服器。NCSoft 營運三個獨立的區域服務：全球伺服器（透過 Steam）、台灣伺服器（透過遊戲橘子）和韓國伺服器（透過 plaync）。", sourceNote: "基於 AION2Hub 的伺服器對比、NCSoft plaync 官方伺服器指南以及 Steam 全球發佈頁面。", keywords: ["Aion 2 伺服器區域", "Aion 2 全球伺服器", "Aion 2 台服", "Aion 2 韓服", "Aion 2 伺服器選擇"],
      sections: [
        section("global-server", "全球伺服器：西方搶先體驗", ["全球伺服器是西方玩家的主要目的地。透過 Steam 搶先體驗發布，支援英語、法語、德語、西班牙語等歐洲語言。全球版使用最新遊戲版本。", "主要優勢包括官方英語支援、Steam 整合、以及快速成長的西方玩家群體。全球商城以美元定價。"]),
        section("tw-server", "台灣伺服器：中文社群中心", ["台灣伺服器由遊戲橘子（Gamania）在 NCSoft 授權下營運，服務於台灣、香港、澳門及整個繁體中文社群的玩家。客戶端完全本地化為繁體中文。", "台灣伺服器擁有自己獨特的更新計劃，通常與全球和韓服發布不同步。遊戲橘子營運本地化活動，商城以新台幣定價。"]),
        section("kr-server", "韓國伺服器：原汁原味體驗", ["韓國伺服器由 NCSoft 直接在 plaync 上營運，是 Aion 2 的原始版本。它運行在最新的版本上，最先接收修補程式。韓服帳號註冊需要韓國居民身份證號（KSSN）。", "對於韓國玩家，韓服提供最低延遲、最完整的內容和與 NCSoft 生態系統的深度整合。商城以韓元定價。"]),
        section("server-selection", "你應該選擇哪個伺服器？", ["你的選擇取決於語言、延遲和社群。對於大多數玩家，全球伺服器是推薦起點：擁有最大的國際人口、官方英語支援以及最便捷的支付和帳號建立流程。"]),
      ],
    }),
  },
};