import { articleCopy, localizations, newsLabels, publishedVerified, section } from "./trending-september-2-shared";
import type { ContentEntry, ContentHeroImage, ContentSource } from "./content-registry";

/* ARTICLE 3 — Sept 2 KR update: Spacetime Rift Domination live + partial revert of Aug 26 rebalance + Kaira scheduled */

const krSource1: ContentSource = {
  id: "ncsoft-kr-update-2026-09-02",
  kind: "third-party", publisher: "NCSoft (via Aion2t)",
  label: "아이온2 9월 2일 업데이트 — 시공의 균열 지배전 등장, 지난주 절반 원복",
  url: "https://aion2t.com/news/42",
  publishedAt: "2026-09-02",
  retrievedAt: "2026-09-02",
  verifiedAt: "2026-09-02",
  localizations: localizations({
    "zh-hans": "Aion 2 9 月 2 日更新——时空裂隙·统治战登场，上周一半内容回滚",
    en: "Aion 2 September 2 update — Spacetime Rift Domination arrives, half of last week undone",
    fr: "Mise à jour Aion 2 du 2 septembre — Domination des Failles arrive, la moitié de la semaine dernière annulée",
    de: "Aion-2-Update vom 2. September — Spacetime-Rift-Domination kommt, halbe letzte Woche rückgängig",
    es: "Actualización de Aion 2 del 2 de septiembre — llega la Dominación de Fisuras, se revierte media semana pasada",
    ja: "Aion 2 9月2日アップデート — 時空の亀裂・支配戦登場、先週の半分が元に戻る",
    "pt-br": "Atualização de 2 de setembro do Aion 2 — Dominação de Fendas chega, metade da semana passada revertida",
    ru: "Обновление Aion 2 от 2 сентября — прибывает Доминация Разломов, половина прошлой недели отменена",
    ko: "아이온2 9월 2일 업데이트 — 시공의 균열 지배전 등장, 지난주 절반 원복",
    "zh-hant": "Aion 2 9 月 2 日更新——時空裂隙·統治戰登場，上週一半內容回滾",
  }, "https://aion2t.com/news/42"),
};

const krSource2: ContentSource = {
  id: "ncsoft-kr-update-original-2026-09-02",
  kind: "third-party", publisher: "NCSOFT",
  label: "아이온2 업데이트 안내 (September 2, 2026, Korean official)",
  url: "https://aion2.plaync.com/ko-kr/board/update/list",
  publishedAt: "2026-09-02",
  retrievedAt: "2026-09-02",
  verifiedAt: "2026-09-02",
  localizations: localizations({
    "zh-hans": "Aion 2 更新公告（2026-09-02，韩服官方）",
    en: "Aion 2 update notes (September 2, 2026, KR official)",
    fr: "Notes de mise à jour d'Aion 2 (2 septembre 2026, officiel KR)",
    de: "Aion-2-Update-Hinweise (2. September 2026, KR offiziell)",
    es: "Notas de actualización de Aion 2 (2 de septiembre de 2026, oficial KR)",
    ja: "Aion 2 更新案内（2026年9月2日、KR公式）",
    "pt-br": "Notas de atualização do Aion 2 (2 de setembro de 2026, oficial KR)",
    ru: "Заметки об обновлении Aion 2 (2 сентября 2026, официально KR)",
    ko: "아이온2 업데이트 안내 (2026-09-02, KR 공식)",
    "zh-hant": "Aion 2 更新公告（2026-09-02，韓服官方）",
  }, "https://aion2.plaync.com/ko-kr/board/update/list"),
};

const krHero: ContentHeroImage = {
  src: "https://blogfiles.ncsoft.net/news/af7330da-4ff6-4b58-aece-400e6061a3be.jpg",
  width: 1100, height: 605,
  credit: "NC Corporation",
  sourceUrl: "https://aion2.plaync.com/ja-jp/board/notice/list",
  rights: "linked-official-media",
  translations: {
    "zh-hans": { alt: "Aion 2 9 月 2 日韩服更新新闻配图", caption: "NC 官方配图；9/2 韩服更新上线开放世界阵营战「时空裂隙·统治战」（周一/四/六 20:00、23:00），并回滚 8/26 大重做的部分职业改动。" },
    en: { alt: "Aion 2 September 2 KR update news image", caption: "Official NC artwork; the Sept 2 KR update adds the open-world faction war “Spacetime Rift Domination” (Mon/Thu/Sat 20:00 & 23:00) and rolls back part of the Aug 26 rebalance." },
    fr: { alt: "Image de la mise à jour KR du 2 septembre d'Aion 2", caption: "Visuel officiel NC ; la mise à jour du 2 sept. ajoute la guerre de factions « Domination des Failles » (lun/jeu/sam 20:00 et 23:00) et annule une partie du rééquilibrage du 26 août." },
    de: { alt: "Bild zum KR-Update vom 2. September für Aion 2", caption: "Offizielles NC-Artwork; das Update vom 2. Sept. fügt den Open-World-Fraktionenkrieg „Spacetime-Rift-Domination“ hinzu (Mo/Do/Sa 20:00 & 23:00) und rollt Teile des Rebalancings vom 26. August zurück." },
    es: { alt: "Imagen de la actualización KR del 2 de septiembre de Aion 2", caption: "Arte oficial de NC; la actualización del 2 sept. añade la guerra de facciones «Dominación de Fisuras» (lun/jue/sáb 20:00 y 23:00) y revierte parte del reequilibrio del 26 de agosto." },
    ja: { alt: "Aion 2 9月2日KRアップデートニュース画像", caption: "NC公式アートワーク；9月2日のKRアップデートはオープンワールド陣営戦『時空の亀裂・支配戦』（月・木・土 20:00・23:00）を追加し、8月26日リバランスの一部を巻き戻します。" },
    "pt-br": { alt: "Imagem da atualização KR de 2 de setembro do Aion 2", caption: "Arte oficial da NC; a atualização de 2 set. adiciona a guerra de facções «Dominação de Fendas» (seg/qui/sáb 20:00 e 23:00) e reverte parte do rebalanceamento de 26 de agosto." },
    ru: { alt: "Изображение KR-обновления Aion 2 от 2 сентября", caption: "Официальный арт NC; обновление от 2 сент. добавляет открытую войну фракций «Доминация Разломов» (пн/чт/сб 20:00 и 23:00) и откатывает часть ребаланса от 26 августа." },
    ko: { alt: "Aion 2 9월 2일 KR 업데이트 뉴스 이미지", caption: "NC 공식 이미지입니다. 9월 2일 KR 업데이트는 오픈월드 진영전 '시공의 균열 지배전'(월·목·토 20:00·23:00)을 추가하고 8월 26일 리밸런스의 일부를 되돌립니다." },
    "zh-hant": { alt: "Aion 2 9 月 2 日韓服更新新聞配圖", caption: "NC 官方配圖；9/2 韓服更新上線開放世界陣營戰「時空裂隙·統治戰」（週一/四/六 20:00、23:00），並回滾 8/26 大重做的部分職業改動。" },
  },
};

export const trendingSeptember2Article3: ContentEntry = {
  section: "news",
  slug: "aion-2-kr-update-september-2-domination-revert",
  schemaType: "NewsArticle",
  publishedAt: "2026-09-02",
  updatedAt: "2026-09-02",
  readingMinutes: 5,
  publication: publishedVerified,
  sources: [krSource1, krSource2],
  heroImage: krHero,
  related: [
    { kind: "content", section: "guides", slug: "aion-2-great-rebalance-patch-guide" },
    { kind: "content", section: "guides", slug: "aion-2-prelaunch-access-routes-guide" },
    { kind: "content", section: "news", slug: "aion-2-global-launch-no-oceania-server" },
    { kind: "content", section: "news", slug: "aion-2-release-date-october-5-2026" },
  ],
  translations: {
    en: articleCopy(newsLabels, "en", 5, {
      eyebrow: "KR UPDATE SEPT 2",
      title: "Aion 2 September 2 Update: Spacetime Rift Domination Is Live, Part of the Big Rebalance Is Undone",
      description: "The September 2 KR update activates the open-world faction war Spacetime Rift Domination (Mon/Thu/Sat 20:00 & 23:00), reverts part of the August 26 class rebalance (Chanter/Templar), makes Watcher Kaira a scheduled boss, and refunds item-restore charges from the bulk-sell bug.",
      intro: "Wednesday September 2 brought Aion 2's Korea service its first September patch, and it moves fast: the previously datamined open-world faction war Spacetime Rift Domination is now live with schedule and rules, while part of the August 26 rebalance is being walked back — Chanter and Templar changes revert toward their pre-rebalance values. This report covers the headline event, the class reversals and their stated reason, the Kaira scheduling change, and the item-restore refund.",
      sourceNote: "Based on NCSOFT's September 2 Korean update notes (published Wednesday, September 2, 2026) as covered by Aion2t, which tracks the official notes and links the original NCSoft post. Global-launch relevance is framed separately from KR-service content.",
      keywords: ["Aion 2 September 2 update", "Aion 2 Spacetime Rift Domination", "Aion 2 Chanter revert", "Aion 2 Watcher Kaira", "Aion 2 KR patch notes"],
      sections: [
        section("domination-live", "Spacetime Rift Domination Is Now Live", ["NCSOFT published the update notes for Wednesday, September 2, whose headline is the open-world faction war Spacetime Rift Domination — the feature previously read from the client in the August 26 datamine, now with schedule and rules attached.", "It runs every Monday, Thursday, and Saturday at 20:00 and 23:00 (Spacetime Rift times) over the strongholds of Verteron and Altgard, with attack/defence swapping weekly: week 1 Verteron with the Elyos defending, week 2 Altgard with the Asmodians defending.", "The entry gate is demanding: level 50+, item level 4,500+, 500.0k Combat Power, and tier VI of the Stronghold Sweep achievement in both territories. Three Event Keys recharge weekly and one is consumed per reward — a hard ceiling on farming."]),
        section("how-domination-works", "How the Faction War Works", ["The event needs minimum 60 and maximum 200 characters per side; the portal opens and the event begins 5 minutes later, running 25 minutes, with entry possible for the 10 minutes the portal stays up.", "During Domination you cannot use Expedition, Transcendence, or Sanctuary content; S-PVP mode activates for participants, and only S-PVP characters can fight each other, with field guards still able to attack them.", "Five strongholds form a group and one of three groups opens at random per event. A stronghold falls when all three monoliths are destroyed; attackers win by taking 3+ of 5, defenders by holding the majority when time runs out.", "Rewards follow per-class contribution ranking for players who reach a minimum contribution; a Domination-only Kisk (attacking side only) and weekly Domination missions are added."]),
        section("the-revert", "Part of the Big Rebalance Is Undone", ["The Chanter changes from August 26 are largely reversed: Spinning Strike's cooldown returns from 15s to 30s, MP cost from 100 to 250, and groggy damage from 10 back to 15 — but it becomes a 20m ranged AoE with +50% PVE damage, a real compensation.", "Impactful Crush's cooldown goes back from 10s to 15s. Templar sees Pummel −10%, Punishing Strike −20%, Judgment +15%, and Threatening Blow +30%, with Vicious/Decisive/Desperate Strike getting +30% PVE damage.", "NCSOFT's stated reason: chaining into Vicious Strike was losing efficiency, and damage is being redistributed to widen skill choice. The site's editor's take is blunt: the August rebalance shipped under-tested and is being tuned in public, one week at a time."]),
        section("kaira-and-refund", "Kaira Scheduling and the Item-Restore Refund", ["Watcher Kaira in the Abyss becomes a scheduled boss: spawn chance rises from 20% to 100%, on a 4-hour cycle from midnight, at a random location in Lower Reshanta — turning a lottery into a calendar entry.", "Abyss boss and Dimensional Core stats are raised substantially for the third consecutive week, along with the contribution earned through PvP.", "NCsoft is refunding the [Item Restore] charge spent by players who accidentally bulk-sold items due to the August 26 sale-registration/bulk-sell malfunction — restores are a limited resource, so the refund is a meaningful gesture."]),
        section("what-it-means", "What It Means for Global Players", ["These are Korea-service notes; the global build launches October 5 and its content state at launch is governed by the global roadmap, not this KR patch.", "Still, the direction matters: open-world faction war with a hard gear gate and weekly key ceiling is exactly the endgame shape global players should expect to see mirrored in the months after launch.", "The public rebalancing loop — ship, measure, revert partially in a week — is a preview of how live-service balance will be handled globally, and the Kaira-style scheduled-boss pattern improves world-boss predictability."]),
      ],
    }),
    "zh-hans": articleCopy(newsLabels, "zh-hans", 5, {
      eyebrow: "9/2 韩服更新",
      title: "Aion 2 9 月 2 日更新：时空裂隙·统治战上线，大重做部分回滚",
      description: "9 月 2 日韩服更新上线开放世界阵营战「时空裂隙·统治战」（周一/四/六 20:00、23:00），回滚 8/26 大重做的部分职业改动（Chanter/Templar），Watcher Kaira 定时化，并退还批量出售故障消耗的物品恢复次数。",
      intro: "9 月 2 日（周三）Aion 2 韩服迎来 9 月首个补丁，动作很快：此前数据挖掘的开放世界阵营战「时空裂隙·统治战」现已上线并带日程与规则；同时 8/26 大重做的一部分被收回——Chanter 与 Templar 的改动向重做前值回退。本报告覆盖头条事件、职业回退及其官方理由、Kaira 定时化与物品恢复退还。",
      sourceNote: "基于 NCsoft 2026 年 9 月 2 日（周三）韩服官方更新公告，经 Aion2t 转述并链接 NCSoft 原文。全球上线相关性另作框架说明。",
      keywords: ["Aion 2 9月2日更新", "Aion 2 时空裂隙统治战", "Aion 2 Chanter 回滚", "Aion 2 Watcher Kaira", "Aion 2 韩服补丁"],
      sections: [
        section("domination-live", "时空裂隙·统治战现已上线", ["NCsoft 于 9 月 2 日（周三）发布更新公告，头条是开放世界阵营战「时空裂隙·统治战」——即 8/26 数据挖掘报告中读到的功能，现附日程与规则。", "它于每周一、周四、周六 20:00 与 23:00（时空裂隙时刻）在维尔特伦与阿尔特加德的要塞举行，攻防每周轮换：第一周维尔特伦、埃利奥斯防守；第二周阿尔特加德、阿斯莫迪安防守。", "入场门槛苛刻：等级 50+、装备分 4,500+、战力 500.0k+、两个区域都要有 VI 级要塞扫荡成就。每周自动补充 3 枚事件钥匙，每次领取奖励消耗 1 枚——对刷取设了硬上限。"]),
        section("how-domination-works", "阵营战规则", ["事件每边最少 60、最多 200 人；传送门开启后 5 分钟开战，持续 25 分钟，传送门保持 10 分钟可入场。", "期间不可使用远征、超越或圣域内容；参战者进入 S-PVP 模式，仅 S-PVP 角色可互相攻击，野外守卫仍可攻击 S-PVP 角色。", "5 座要塞为一组，每次随机开启三组之一。要塞在三个方尖碑全部被毁时陷落；进攻方夺取 5 座中 3 座以上获胜，防守方在时间结束时仍占多数则获胜。", "奖励按职业贡献排名发放给达到最低贡献的玩家；新增仅限进攻方使用的统治战专用基斯克与每周统治战任务。"]),
        section("the-revert", "大重做部分被收回", ["8/26 的 Chanter 改动大体被回退：Spinning Strike 冷却从 15s 回到 30s、MP 消耗 100→250、致晕伤害 10→15——但它变为 20m 远程范围技能并 +50% PVE 伤害，是实在的补偿。", "Impactful Crush 冷却从 10s 回到 15s。Templar：Pummel −10%、Punishing Strike −20%、Judgment +15%、Threatening Blow +30%，Vicious/Decisive/Desperate Strike +30% PVE 伤害。", "官方理由：连段进入 Vicious Strike 的效率在下降，正在重新分配伤害以拓宽技能选择。站点编辑的评语很直接：8 月大重做未经充分测试就上线，正在公开环境里一周一周地调。"]),
        section("kaira-and-refund", "Kaira 定时化与物品恢复退还", ["深渊的 Watcher Kaira 变为定时首领：出现率从 20% 提到 100%，自午夜起每 4 小时一个周期，位于下雷相塔随机位置——把抽奖变成日程项。", "深渊首领与次元核心属性连续第三周大幅提升，同时 PvP 获得的贡献提高。", "NCsoft 将退还因 8/26 出售登记/批量出售故障而不慎批量出售物品的玩家消耗的[物品恢复]次数——恢复是有限资源，这一退还颇具诚意。"]),
        section("what-it-means", "对全球玩家的意义", ["这些是韩服公告；全球版 10 月 5 日上线，其首发内容状态由全球路线图决定，而非本韩服补丁。", "但方向重要：带硬装备门槛与每周钥匙上限的开放世界阵营战，正是全球玩家应在上线后数月内看到被镜像的终局形态。", "公开调平衡循环——上线、观测、一周内部分回退——预告了全球长线平衡的处理方式；Kaira 式定时首领模式也提升了世界首领的可预期性。"]),
      ],
    }),
    ko: articleCopy(newsLabels, "ko", 5, {
      eyebrow: "9/2 KR 업데이트",
      title: "아이온2 9월 2일 업데이트: 시공의 균열 지배전 등장, 대규모 리밸런스 일부 원복",
      description: "9월 2일 KR 업데이트가 오픈월드 진영전 '시공의 균열 지배전'(월·목·토 20:00·23:00)을 활성화하고, 8월 26일 리밸런스 일부(채터/템플러)를 되돌리며, 왓처 카이라를 정기 보스로 바꾸고 대량 판매 버그 소모품 복구 횟수를 환불합니다.",
      intro: "9월 2일(수) 아이온2 한국 서비스의 9월 첫 패치가 나왔고 빠릅니다. 데이터마이닝으로 알려졌던 오픈월드 진영전 '시공의 균열 지배전'이 일정과 규칙과 함께 라이브로 전환됐고, 8월 26일 리밸런스의 일부가 되돌려집니다. 본 기사는 주요 이벤트와 직업 원복, 카이라 일정 변경, 복구 횟수 환불을 다룹니다.",
      sourceNote: "NCSOFT 9월 2일(수) 한국 공식 업데이트 공지를 Aion2t가 정리한 내용 기반입니다. 글로벌 출시 관련성은 KR 서비스 콘텐츠와 별개로 구분해 서술합니다.",
      keywords: ["아이온2 9월 2일 업데이트", "아이온2 시공의 균열 지배전", "아이온2 채터 원복", "아이온2 왓처 카이라", "아이온2 KR 패치"],
      sections: [
        section("domination-live", "시공의 균열 지배전 라이브", "NCSOFT가 9월 2일(수) 업데이트 공지를 발표했고, 핵심은 8월 26일 데이터마이닝에서 읽은 오픈월드 진영전 '시공의 균열 지배전'입니다. 매주 월·목·토 20:00·23:00(균열 시간)에 베르테론·알트가르트 요새에서 열리며, 주마다 공수 교대(1주 베르테론 엘리오스 수비, 2주 알트가르트 아스모디안 수비)입니다. 입장 관문은 레벨 50+, 장비 점수 4,500+, 전투력 500.0k+, 양 지역 6단계 요새 쓸기 업적이며, 주당 이벤트 키 3개가 재충전되고 보상마다 1개가 소모됩니다."),
        section("how-domination-works", "진영전 규칙", "한쪽 최소 60·최대 200명, 포털이 열리고 5분 후 시작, 25분 진행, 포털 10분간 입장 가능. 진행 중 원정·초월·성역 콘텐츠 사용 불가, S-PVP 모드 활성화로 S-PVP 캐릭터끼리만 전투 가능(필드 경비병은 공격 가능). 5개 요새가 한 그룹이며 3개 그룹 중 하나가 무작위로 열립니다. 오벨리스크 3개가 모두 파괴되면 요새가 함락되고, 공격자는 5개 중 3개 이상 점령 시, 수비자는 시간 종료 시 다수 보유 시 승리합니다."),
        section("the-revert", "대규모 리밸런스 일부 원복", "8월 26일의 채터 변경은 대부분 되돌아갑니다: 스피닝 스트라이크 쿨다운 15초→30초, MP 100→250, 그로그 피해 10→15 — 단 20m 원거리 범위로 바뀌고 PVE 피해 +50%라는 실질 보상이 붙습니다. 임팩트풀 크러시 10초→15초. 템플러는 퍼멀 −10%, 패니싱 스트라이크 −20%, 저지먼트 +15%, 스레트닝 블로우 +30%, 비셔스·디시시브·디스페레이트 스트라이크 PVE +30%. 이유는 비셔스 스트라이크 연계 효율 저하와 스킬 선택 다양화를 위한 피해 재분배입니다."),
        section("kaira-and-refund", "카이라 일정화와 복구 환불", "심연의 왓처 카이라가 정기 보스가 됩니다: 출현 확률 20%→100%, 자정 기준 4시간 주기, 하부 레샨타 무작위 위치. 심연 보스·차원 코어 스탯이 3주 연속 대폭 상승하며 PvP 기여도도 상승합니다. NC소프트는 8월 26일 판매 등록·대량 판매 오류로 실수로 대량 판매한 플레이어가 쓴 [아이템 복구] 횟수를 환불합니다."),
        section("what-it-means", "글로벌 플레이어에게 주는 의미", "이는 한국 서비스 공지이며, 글로벌 빌드는 10월 5일에 출시됩니다. 다만 방향은 중요합니다: 하드 기어 게이트와 주간 키 상한의 오픈월드 진영전은 글로벌에서도 출시 후 몇 달 안에 비슷한 형태로 보일 엔드게임 구조입니다."),
      ],
    }),
    ja: articleCopy(newsLabels, "ja", 5, {
      eyebrow: "9/2 KRアップデート",
      title: "Aion 2 9月2日アップデート：時空の亀裂・支配戦が登場、大規模リバランスの一部を巻き戻し",
      description: "9月2日のKRアップデートがオープンワールド陣営戦『時空の亀裂・支配戦』（月・木・土 20:00・23:00）を有効化し、8月26日リバランスの一部（チャンター/テンプラー）を戻し、ワッチャー・カイラを定期ボス化し、大量販売バグの復元回数を返還します。",
      intro: "9月2日（水）、Aion 2 韓国サービスに9月最初のパッチが入り、動きは速いです。データマイニングで判明していたオープンワールド陣営戦『時空の亀裂・支配戦』が日程と規則付きでライブになり、8月26日リバランスの一部が巻き戻されます。本記事は主要イベント・職業の巻き戻し・カイラの定期化・復元返還を扱います。",
      sourceNote: "NCSOFT 9月2日（水）韓国公式アップデート告知をAion2tが整理した内容に基づきます。グローバル発売との関連性はKRサービスと分けて記述します。",
      keywords: ["Aion 2 9月2日アップデート", "Aion 2 時空の亀裂・支配戦", "Aion 2 チャンター巻き戻し", "Aion 2 ワッチャー・カイラ", "Aion 2 KRパッチ"],
      sections: [
        section("domination-live", "時空の亀裂・支配戦がライブ", "NCSOFTが9月2日（水）のアップデート告知を出し、目玉は8月26日データマイニングで読まれたオープンワールド陣営戦『時空の亀裂・支配戦』です。毎週月・木・土 20:00・23:00（亀裂時刻）にベルテロン・アルトガルトの要塞で行われ、週ごとに攻守交代（1週目ベルテロン、エリオス守備／2週目アルトガルト、アスモディアン守備）。入場はレベル50+、装備スコア4,500+、戦闘力500.0k+、両地域6段階要塞掃討の達成が必要で、週3個のイベントキーが補充され報酬ごとに1個消費されます。"),
        section("how-domination-works", "陣営戦のルール", "片側最低60・最大200人、ポータルが開き5分後に開始、25分間進行、ポータル10分間入場可。進行中は遠征・超越・聖域を使用できず、S-PVPモードで参加者同士のみ戦闘可（フィールド警備兵は攻撃可）。5要塞が1グループで、3グループのうち1つがランダムに開放。オベリスク3つ全て破壊で要塞陥落、攻撃側は5つのうち3つ以上で勝利、守備側は時間切れ時点の多数保持で勝利です。"),
        section("the-revert", "大規模リバランスの一部を巻き戻し", "8月26日のチャンター変更は大半が戻ります:スピニングストライクCD15秒→30秒、MP100→250、グロッギー10→15 — ただし20m遠隔範囲化とPVE+50%という実質補償付き。インパクトフルクラッシュ10秒→15秒。テンプラーはパンメル−10%、パニッシングストライク−20%、ジャッジメント+15%、スレットニングブロウ+30%、ビシャス系3種PVE+30%。理由はビシャスストライク連携効率低下とスキル選択の多様化のための再分配です。"),
        section("kaira-and-refund", "カイラ定期化と復元返還", "深淵のワッチャー・カイラが定期ボスに:出現率20%→100%、真夜中起点4時間周期、下部レシャンタのランダム位置。深淵ボス・次元コアのステータスが3週連続で大幅上昇し、PvP貢献度も上昇。NCソフトは8月26日の販売登録・一括販売不具合で誤って一括販売したプレイヤーが使った[アイテム復元]回数を返還します。"),
        section("what-it-means", "グローバルプレイヤーへの意味", "これは韓国サービス告知であり、グローバルビルドは10月5日に発売します。ただし方向性は重要です:ハードな装備ゲートと週間キー上限のオープンワールド陣営戦は、発売後数ヶ月でグローバルにも似た形で現れるであろうエンドゲーム構造です。"),
      ],
    }),
    fr: articleCopy(newsLabels, "fr", 5, {
      eyebrow: "MISE À JOUR KR 2 SEPT.",
      title: "Aion 2 mise à jour du 2 septembre : Domination des Failles en ligne, une partie du grand rééquilibrage annulée",
      description: "La mise à jour KR du 2 septembre active la guerre de factions « Domination des Failles » (lun/jeu/sam 20:00 et 23:00), revient sur une partie du rééquilibrage du 26 août (Chanter/Templier), planifie le boss Watcher Kaira et rembourse les charges de restauration d'objets.",
      intro: "Mercredi 2 septembre a apporté au service coréen d'Aion 2 son premier patch de septembre — et il va vite : la guerre de factions « Domination des Failles » est en ligne avec horaires et règles, tandis qu'une partie du rééquilibrage du 26 août est retirée. Cet article couvre l'événement, les reversions de classes, le boss planifié et le remboursement.",
      sourceNote: "Basé sur les notes officielles coréennes du 2 septembre 2026 telles que couvertes par Aion2t. La pertinence pour le lancement mondial est traitée séparément.",
      keywords: ["Aion 2 mise à jour 2 septembre", "Aion 2 Domination des Failles", "Aion 2 reversion Chanter", "Aion 2 Watcher Kaira", "Aion 2 patch KR"],
      sections: [
        section("domination-live", "Domination des Failles en ligne", "Les notes du mercredi 2 septembre activent la guerre de factions « Domination des Failles » (lun/jeu/sam 20:00 et 23:00) sur les forteresses de Verteron et Altgard, avec rotation offensive/défensive hebdomadaire. Porte d'entrée exigeante : niveau 50+, score d'équipement 4 500+, 500,0k de puissance de combat, balayage des forteresses niveau VI dans les deux zones. Trois clés d'événement par semaine, une consommée par récompense."),
        section("how-domination-works", "Comment fonctionne la guerre", "60 à 200 personnages par camp, portail 10 minutes, début 5 min plus tard, 25 min de combat. Pas d'expédition/transcendance/sanctuaire pendant l'événement ; mode S-PVP entre participants uniquement. Cinq forteresses par groupe, un des trois groupes s'ouvre au hasard ; chute quand les trois obélisques sont détruits ; les attaquants gagnent à 3+/5, les défenseurs en gardant la majorité."),
        section("the-revert", "Une partie du rééquilibrage annulée", "Chanter : Spinning Strike revient à 30s/250 MP/15 de dégâts groggy mais devient AoE 20m +50 % PVE ; Impactful Crush 15s. Templier : Pummel −10 %, Punishing Strike −20 %, Judgment +15 %, Threatening Blow +30 %. Raison : l'efficacité d'enchaînement vers Vicious Strike baissait."),
        section("kaira-and-refund", "Boss planifié et remboursement", "Watcher Kaira devient un boss planifié (100 % toutes les 4 h à partir de minuit). Les stats des boss de l'Abîme montent pour la 3e semaine. NCsoft rembourse la charge de restauration d'objets consommée à cause du bug de vente en masse du 26 août."),
        section("what-it-means", "Pour les joueurs mondiaux", "Ce sont des notes KR ; le build mondial sort le 5 octobre. Mais la direction compte : la guerre de factions avec portail d'équipement dur et plafond de clés est la forme d'endgame à attendre en mondial aussi."),
      ],
    }),
    de: articleCopy(newsLabels, "de", 5, {
      eyebrow: "KR-UPDATE 2. SEPT.",
      title: "Aion-2-Update vom 2. September: Spacetime-Rift-Domination live, Teil des großen Rebalancings zurückgenommen",
      description: "Das KR-Update vom 2. September aktiviert den Open-World-Fraktionenkrieg „Spacetime-Rift-Domination“ (Mo/Do/Sa 20:00 & 23:00), nimmt Teile des Rebalancings vom 26. August zurück (Chanter/Templar), plant Boss Watcher Kaira und erstattet Gegenstandswiederherstellungs-Ladungen.",
      intro: "Mittwoch, 2. September brachte dem Korea-Dienst von Aion 2 den ersten September-Patch — und der geht schnell: Der Open-World-Fraktionenkrieg „Spacetime-Rift-Domination“ ist mit Zeitplan und Regeln live, während Teile des Rebalancings vom 26. August zurückgenommen werden. Dieser Artikel deckt das Event, die Klassen-Rücknahmen, den geplanten Boss und die Erstattung ab.",
      sourceNote: "Basierend auf den offiziellen koreanischen Notizen vom 2. September 2026, wie von Aion2t aufbereitet. Die Relevanz für den Weltstart wird getrennt eingeordnet.",
      keywords: ["Aion 2 Update 2. September", "Aion 2 Spacetime-Rift-Domination", "Aion 2 Chanter-Rücknahme", "Aion 2 Watcher Kaira", "Aion 2 KR-Patch"],
      sections: [
        section("domination-live", "Spacetime-Rift-Domination live", "Die Notizen vom Mittwoch, 2. September aktivieren den Open-World-Fraktionenkrieg „Spacetime-Rift-Domination“ (Mo/Do/Sa 20:00 und 23:00) über die Festungen von Verteron und Altgard, mit wöchentlichem Angriff/Verteidigungs-Wechsel. Hohe Eintrittsschwelle: Level 50+, Ausrüstung 4.500+, Kampfkraft 500,0k, Festungs-Fegen Stufe VI in beiden Gebieten. Drei Event-Schlüssel pro Woche, einer pro Belohnung."),
        section("how-domination-works", "Wie der Fraktionenkrieg funktioniert", "60 bis 200 Charaktere pro Seite, Portal 10 Minuten, Start 5 Minuten später, 25 Minuten Kampf. Währenddessen keine Expedition/Transzendenz/Sanktuarium; S-PVP-Modus nur zwischen Teilnehmern. Fünf Festungen pro Gruppe, eine von drei Gruppen öffnet zufällig; Eroberung bei Zerstörung aller drei Obelisken; Angreifer gewinnen bei 3+/5, Verteidiger durch Mehrheit."),
        section("the-revert", "Teil des Rebalancings zurückgenommen", "Chanter: Spinning Strike zurück auf 30s/250 MP/15 Groggy-Schaden, wird aber 20m-AoE mit +50 % PVE; Impactful Crush 15s. Templar: Pummel −10 %, Punishing Strike −20 %, Judgment +15 %, Threatening Blow +30 %. Grund: Effizienzverlust der Kette in Vicious Strike."),
        section("kaira-and-refund", "Geplanter Boss und Erstattung", "Watcher Kaira wird geplanter Boss (100 %, alle 4 Stunden ab Mitternacht). Abyss-Boss-Stats steigen die 3. Woche. NCsoft erstattet die Wiederherstellungs-Ladung vom Massenverkaufs-Bug des 26. August."),
        section("what-it-means", "Für globale Spieler", "Das sind KR-Notizen; der globale Build startet am 5. Oktober. Aber die Richtung zählt: Fraktionenkrieg mit hartem Gear-Gate und Wochen-Schlüssel-Deckel ist die Endgame-Form, die auch global zu erwarten ist."),
      ],
    }),
    es: articleCopy(newsLabels, "es", 5, {
      eyebrow: "ACTUALIZACIÓN KR 2 SEPT.",
      title: "Actualización de Aion 2 del 2 de septiembre: Dominación de Fisuras en vivo, parte del gran reequilibrio revertida",
      description: "La actualización KR del 2 de septiembre activa la guerra de facciones «Dominación de Fisuras» (lun/jue/sáb 20:00 y 23:00), revierte parte del reequilibrio del 26 de agosto (Chanter/Templario), planifica al jefe Watcher Kaira y reembolsa cargas de restauración de objetos.",
      intro: "El miércoles 2 de septiembre trajo al servicio coreano de Aion 2 su primer parche de septiembre — y va rápido: la guerra de facciones «Dominación de Fisuras» está en vivo con horarios y reglas, mientras parte del reequilibrio del 26 de agosto se retira. Este informe cubre el evento, las reversiones de clases, el jefe planificado y el reembolso.",
      sourceNote: "Basado en las notas oficiales coreanas del 2 de septiembre de 2026 según Aion2t. La relevancia para el lanzamiento mundial se trata por separado.",
      keywords: ["Aion 2 actualización 2 de septiembre", "Aion 2 Dominación de Fisuras", "Aion 2 reversión Chanter", "Aion 2 Watcher Kaira", "Aion 2 parche KR"],
      sections: [
        section("domination-live", "Dominación de Fisuras en vivo", "Las notas del miércoles 2 de septiembre activan la guerra de facciones «Dominación de Fisuras» (lun/jue/sáb 20:00 y 23:00) sobre las fortalezas de Verteron y Altgard, con rotación semanal. Puerta exigente: nivel 50+, puntuación de equipo 4.500+, poder de combate 500,0k, barrido de fortalezas nivel VI en ambas zonas. Tres claves de evento por semana, una por recompensa."),
        section("how-domination-works", "Cómo funciona la guerra", "60 a 200 personajes por bando, portal 10 minutos, inicio 5 min después, 25 min de combate. Sin expedición/trascendencia/santuario; modo S-PVP solo entre participantes. Cinco fortalezas por grupo, uno de tres se abre al azar; caída con tres obeliscos destruidos; los atacantes ganan a 3+/5."),
        section("the-revert", "Parte del gran reequilibrio revertida", "Chanter: Spinning Strike vuelve a 30s/250 MP/15 de daño groggy, pero pasa a AoE 20m con +50 % PVE; Impactful Crush 15s. Templario: Pummel −10 %, Punishing Strike −20 %, Judgment +15 %, Threatening Blow +30 %. Razón: caía la eficiencia del encadenado a Vicious Strike."),
        section("kaira-and-refund", "Jefe planificado y reembolso", "Watcher Kaira se vuelve jefe planificado (100 %, cada 4 horas desde medianoche). Las estadísticas de los jefes del Abismo suben la 3.ª semana. NCsoft reembolsa la carga de restauración de objetos por el bug de venta masiva del 26 de agosto."),
        section("what-it-means", "Para jugadores globales", "Son notas KR; el build global sale el 5 de octubre. Pero la dirección cuenta: la guerra de facciones con puerta dura y tope de claves es la forma de endgame que esperar también en global."),
      ],
    }),
    "pt-br": articleCopy(newsLabels, "pt-br", 5, {
      eyebrow: "ATUALIZAÇÃO KR 2 SET.",
      title: "Atualização de 2 de setembro do Aion 2: Dominação de Fendas no ar, parte do grande rebalanceamento revertida",
      description: "A atualização KR de 2 de setembro ativa a guerra de facções «Dominação de Fendas» (seg/qui/sáb 20:00 e 23:00), reverte parte do rebalanceamento de 26 de agosto (Chanter/Templário), agenda o chefe Watcher Kaira e reembolsa cargas de restauração de itens.",
      intro: "Quarta-feira, 2 de setembro trouxe ao serviço coreano do Aion 2 seu primeiro patch de setembro — e é rápido: a guerra de facções «Dominação de Fendas» está no ar com horários e regras, enquanto parte do rebalanceamento de 26 de agosto é retirada. Este relatório cobre o evento, as reversões de classes, o chefe agendado e o reembolso.",
      sourceNote: "Com base nas notas oficiais coreanas de 2 de setembro de 2026, conforme a Aion2t. A relevância para o lançamento global é tratada à parte.",
      keywords: ["Aion 2 atualização 2 de setembro", "Aion 2 Dominação de Fendas", "Aion 2 reversão Chanter", "Aion 2 Watcher Kaira", "Aion 2 patch KR"],
      sections: [
        section("domination-live", "Dominação de Fendas no ar", "As notas de quarta-feira, 2 de setembro ativam a guerra de facções «Dominação de Fendas» (seg/qui/sáb 20:00 e 23:00) sobre as fortalezas de Verteron e Altgard, com rotação semanal. Portão exigente: nível 50+, pontuação de equipamento 4.500+, poder de combate 500,0k, varredura de fortalezas nível VI nas duas zonas. Três chaves de evento por semana, uma por recompensa."),
        section("how-domination-works", "Como funciona a guerra", "60 a 200 personagens por lado, portal 10 minutos, início 5 min depois, 25 min de combate. Sem expedição/transcendência/santuário; modo S-PVP só entre participantes. Cinco fortalezas por grupo, um de três abre ao acaso; queda com três obeliscos destruídos; atacantes vencem a 3+/5."),
        section("the-revert", "Parte do grande rebalanceamento revertida", "Chanter: Spinning Strike volta a 30s/250 MP/15 de dano groggy, mas vira AoE de 20m com +50 % PVE; Impactful Crush 15s. Templário: Pummel −10 %, Punishing Strike −20 %, Judgment +15 %, Threatening Blow +30 %. Razão: caía a eficiência do encadeado ao Vicious Strike."),
        section("kaira-and-refund", "Chefe agendado e reembolso", "Watcher Kaira vira chefe agendado (100 %, a cada 4 horas a partir da meia-noite). As estatísticas dos chefes do Abismo sobem pela 3.ª semana. A NCSoft reembolsa a carga de restauração de itens pelo bug de venda em massa de 26 de agosto."),
        section("what-it-means", "Para jogadores globais", "São notas KR; o build global sai em 5 de outubro. Mas a direção conta: a guerra de facções com portão duro e teto de chaves é a forma de endgame esperada também no global."),
      ],
    }),
    ru: articleCopy(newsLabels, "ru", 5, {
      eyebrow: "KR-ОБНОВЛЕНИЕ 2 СЕНТ.",
      title: "Обновление Aion 2 от 2 сентября: Доминация Разломов в игре, часть большого ребаланса отменена",
      description: "KR-обновление от 2 сентября включает открытую войну фракций «Доминация Разломов» (пн/чт/сб 20:00 и 23:00), откатывает часть ребаланса от 26 августа (Chanter/Templar), делает босса Watcher Kaira плановым и возвращает заряды восстановления предметов.",
      intro: "Среда, 2 сентября принесла корейскому сервису Aion 2 первый сентябрьский патч — и он быстрый: война фракций «Доминация Разломов» в игре с расписанием и правилами, а часть ребаланса от 26 августа откатывается. Этот отчёт охватывает событие, откаты классов, планового босса и возврат.",
      sourceNote: "На основе официальных корейских заметок от 2 сентября 2026 в пересказе Aion2t. Отношение к мировому запуску рассматривается отдельно.",
      keywords: ["Aion 2 обновление 2 сентября", "Aion 2 Доминация Разломов", "Aion 2 откат Chanter", "Aion 2 Watcher Kaira", "Aion 2 KR-патч"],
      sections: [
        section("domination-live", "Доминация Разломов в игре", "Заметки среды, 2 сентября включают открытую войну фракций «Доминация Разломов» (пн/чт/сб 20:00 и 23:00) за крепости Вертерона и Альтгарда с еженедельной ротацией атаки/обороны. Высокий порог: уровень 50+, экипировка 4 500+, сила 500,0k, зачистка крепостей VI уровня в обеих зонах. Три ключа события в неделю, один за награду."),
        section("how-domination-works", "Как работает война", "От 60 до 200 персонажей на сторону, портал 10 минут, старт через 5 минут, 25 минут боя. Без экспедиции/трансценденции/святилища; режим S-PVP только между участниками. Пять крепостей в группе, одна из трёх открывается случайно; падение при разрушении трёх обелисков; атакующие побеждают при 3+/5."),
        section("the-revert", "Часть большого ребаланса отменена", "Chanter: Spinning Strike возвращается к 30с/250 MP/15 урона, но становится AoE 20м с +50 % PVE; Impactful Crush 15с. Templar: Pummel −10 %, Punishing Strike −20 %, Judgment +15 %, Threatening Blow +30 %. Причина: падала эффективность цепочки в Vicious Strike."),
        section("kaira-and-refund", "Плановый босс и возврат", "Watcher Kaira становится плановым боссом (100 %, каждые 4 часа от полуночи). Статы боссов Бездны растут 3-ю неделю. NCsoft возвращает заряд восстановления предметов за баг массовой продажи от 26 августа."),
        section("what-it-means", "Для глобальных игроков", "Это KR-заметки; глобальная сборка выходит 5 октября. Но направление важно: война фракций с жёстким порогом экипировки и недельным лимитом ключей — это форма эндгейма, которую стоит ждать и в глобале."),
      ],
    }),
    "zh-hant": articleCopy(newsLabels, "zh-hant", 5, {
      eyebrow: "9/2 韓服更新",
      title: "Aion 2 9 月 2 日更新：時空裂隙·統治戰上線，大重做部分回滾",
      description: "9 月 2 日韓服更新上線開放世界陣營戰「時空裂隙·統治戰」（週一/四/六 20:00、23:00），回滾 8/26 大重做的部分職業改動（Chanter/Templar），Watcher Kaira 定時化，並退還批量出售故障消耗的物品恢復次數。",
      intro: "9 月 2 日（週三）Aion 2 韓服迎來 9 月首個補丁，動作很快：此前數據挖掘的開放世界陣營戰「時空裂隙·統治戰」現已上線並帶日程與規則；同時 8/26 大重做的一部分被收回。本報告覆蓋頭條事件、職業回退及其官方理由、Kaira 定時化與物品恢復退還。",
      sourceNote: "基於 NCsoft 2026 年 9 月 2 日（週三）韓服官方更新公告，經 Aion2t 轉述並連結 NCSoft 原文。全球上線相關性另作框架說明。",
      keywords: ["Aion 2 9月2日更新", "Aion 2 時空裂隙統治戰", "Aion 2 Chanter 回滾", "Aion 2 Watcher Kaira", "Aion 2 韓服補丁"],
      sections: [
        section("domination-live", "時空裂隙·統治戰現已上線", ["NCsoft 於 9 月 2 日（週三）發布更新公告，頭條是開放世界陣營戰「時空裂隙·統治戰」——即 8/26 數據挖掘報告中讀到的功能，現附日程與規則。每週一、四、六 20:00 與 23:00 在維爾特倫與阿爾特加德的要塞舉行，攻防每週輪換。入場門檻苛刻：等級 50+、裝備分 4,500+、戰力 500.0k+、兩區域都要有 VI 級要塞掃蕩成就；每週 3 枚事件鑰匙，每次領取獎勵消耗 1 枚。"]),
        section("how-domination-works", "陣營戰規則", ["每邊最少 60、最多 200 人；傳送門開啟後 5 分鐘開戰，持續 25 分鐘，傳送門保持 10 分鐘可入場。期間不可使用遠征、超越或聖域內容；參戰者進入 S-PVP 模式。5 座要塞為一組，每次隨機開啟三組之一。要塞在三座方尖碑全部被毀時陷落；進攻方奪取 5 座中 3 座以上獲勝。"]),
        section("the-revert", "大重做部分被收回", ["8/26 的 Chanter 改動大體被回退：Spinning Strike 冷卻 15s→30s、MP 100→250、致暈傷害 10→15——但變為 20m 遠程範圍技並 +50% PVE 傷害。Impactful Crush 10s→15s。Templar：Pummel −10%、Punishing Strike −20%、Judgment +15%、Threatening Blow +30%。官方理由：連段進入 Vicious Strike 的效率下降，重新分配傷害以拓寬技能選擇。"]),
        section("kaira-and-refund", "Kaira 定時化與物品恢復退還", ["深淵的 Watcher Kaira 變為定時首領：出現率 20%→100%，自午夜起每 4 小時一週期，位於下雷相塔隨機位置。深淵首領與次元核心屬性連續第三週大幅提升。NCsoft 將退還因 8/26 批量出售故障而不慎批量出售物品的玩家消耗的[物品恢復]次數。"]),
        section("what-it-means", "對全球玩家的意義", ["這些是韓服公告；全球版 10 月 5 日上線，其首發內容狀態由全球路線圖決定。但方向重要：帶硬裝備門檻與每週鑰匙上限的開放世界陣營戰，正是全球玩家應在上線後數月內看到被鏡像的終局形態。"]),
      ],
    }),
  },
};