import { articleCopy, localizations, newsLabels, publishedVerified, section } from "./trending-august-31-shared";
import type { ContentEntry, ContentHeroImage, ContentSource } from "./content-registry";

/* ARTICLE 5 — Korean publishers rewrite the "test in Korea first, then go overseas" playbook; Aion 2 as the bridge case */

const koreaSource1: ContentSource = {
  id: "digitaltoday-k-games-global-playbook-2026-08-30",
  kind: "third-party", publisher: "디지털투데이",
  label: "한국서 검증 후 해외로 옛말…K-게임 '글로벌 공식' 바꿨다",
  url: "https://www.digitaltoday.co.kr/news/articleView.html?idxno=696412",
  publishedAt: "2026-08-30",
  retrievedAt: "2026-08-31",
  verifiedAt: "2026-08-31",
  localizations: localizations({
    "zh-hans": "「先在本土验证再出海」成往事……韩国游戏改写「全球化公式」",
    en: "“Validate in Korea first, then go overseas” is a thing of the past — Korean games rewrite the “global playbook”",
    fr: "« Valider en Corée puis partir à l'étranger » appartient au passé — les jeux coréens réécrivent la « formule mondiale »",
    de: "„Erst in Korea validieren, dann ins Ausland“ ist vorbei — koreanische Spiele schreiben das „globale Rezept“ neu",
    es: "«Validar en Corea y luego salir al extranjero» es cosa del pasado — los juegos coreanos reescriben la «fórmula global»",
    ja: "「韓国で検証してから海外へ」は昔話に — K-ゲームが「グローバルの公式」を書き換える",
    "pt-br": "«Validar na Coreia e depois ir ao exterior» é passado — jogos coreanos reescrevem a «fórmula global»",
    ru: "«Сначала валидация в Корее, потом за границу» — в прошлом: корейские игры переписывают «глобальную формулу»",
    ko: "한국서 검증 후 해외로 옛말…K-게임 '글로벌 공식' 바꿨다",
    "zh-hant": "「先在本土驗證再出海」成往事……韓國遊戲改寫「全球化公式」",
  }, "https://www.digitaltoday.co.kr/news/articleView.html?idxno=696412"),
};

const koreaSource2: ContentSource = {
  id: "massivelyop-week-in-review-korea-2026-08-30",
  kind: "third-party", publisher: "Massively Overpowered",
  label: "MMO Week in Review: Gamescom, Asura, and Ascension",
  url: "https://massivelyop.com/2026/08/30/mmo-week-in-review-gamescom-asura-and-ascension/",
  publishedAt: "2026-08-30",
  retrievedAt: "2026-08-31",
  verifiedAt: "2026-08-31",
  localizations: localizations({
    "zh-hans": "MMO 周报：Gamescom、Asura 与 Ascension",
    en: "MMO Week in Review: Gamescom, Asura, and Ascension",
    fr: "Revue de la semaine MMO : Gamescom, Asura et Ascension",
    de: "MMO-Wochenrückblick: Gamescom, Asura und Ascension",
    es: "Resumen semanal de MMO: Gamescom, Asura y Ascension",
    ja: "MMOウィークリーレビュー：Gamescom、Asura、Ascension",
    "pt-br": "Revista semanal de MMOs: Gamescom, Asura e Ascension",
    ru: "Еженедельный обзор MMO: Gamescom, Asura и Ascension",
    ko: "MMO 위클리 리뷰: Gamescom, Asura, Ascension",
    "zh-hant": "MMO 週報：Gamescom、Asura 與 Ascension",
  }, "https://massivelyop.com/2026/08/30/mmo-week-in-review-gamescom-asura-and-ascension/"),
};

const koreaHero: ContentHeroImage = {
  src: "https://blogfiles.ncsoft.net/news/af7330da-4ff6-4b58-aece-400e6061a3be.jpg",
  width: 1100, height: 605,
  credit: "NC Corporation",
  sourceUrl: "https://aion2.plaync.com/ja-jp/board/notice/list",
  rights: "linked-official-media",
  translations: {
    "zh-hans": { alt: "Aion 2 与韩厂全球化战略新闻配图", caption: "NC 官方配图；Aion 2 去年先在韩国与台湾推出，10 月 5 日经 Steam 与 PURPLE 扩展至北美、南美、欧洲与亚洲。" },
    en: { alt: "Aion 2 and Korean publishers' globalization strategy news image", caption: "Official NC artwork; Aion 2 launched first in Korea and Taiwan last year and expands to North America, South America, Europe, and Asia via Steam and PURPLE on October 5." },
    fr: { alt: "Image de la stratégie de mondialisation d'Aion 2 et des éditeurs coréens", caption: "Visuel officiel NC ; Aion 2 est sorti d'abord en Corée et à Taïwan l'an dernier et s'étend en Amérique du Nord, du Sud, en Europe et en Asie via Steam et PURPLE le 5 octobre." },
    de: { alt: "Bild zur Globalisierungsstrategie von Aion 2 und koreanischen Publishern", caption: "Offizielles NC-Artwork; Aion 2 erschien letztes Jahr zuerst in Korea und Taiwan und weitet sich am 5. Oktober über Steam und PURPLE auf Nord-/Südamerika, Europa und Asien aus." },
    es: { alt: "Imagen de la estrategia de globalización de Aion 2 y los editores coreanos", caption: "Arte oficial de NC; Aion 2 se lanzó primero en Corea y Taiwán el año pasado y se expande el 5 de octubre a Norteamérica, Sudamérica, Europa y Asia vía Steam y PURPLE." },
    ja: { alt: "Aion 2 と韓国パブリッシャーのグローバル戦略ニュース画像", caption: "NC公式アートワーク；Aion 2 は昨年韓国・台湾で先行発売され、10月5日にSteam・PURPLE経由で北米・南米・欧州・アジアへ拡大します。" },
    "pt-br": { alt: "Imagem da estratégia de globalização do Aion 2 e das editoras coreanas", caption: "Arte oficial da NC; o Aion 2 lançou primeiro na Coreia e Taiwan no ano passado e expande em 5 de outubro para América do Norte, do Sul, Europa e Ásia via Steam e PURPLE." },
    ru: { alt: "Изображение стратегии глобализации Aion 2 и корейских издателей", caption: "Официальный арт NC; Aion 2 вышел сначала в Корее и на Тайване в прошлом году и расширяется 5 октября на Северную/Южную Америку, Европу и Азию через Steam и PURPLE." },
    ko: { alt: "Aion 2와 한국 퍼블리셔 글로벌화 전략 뉴스 이미지", caption: "NC 공식 이미지입니다. 아이온2는 지난해 한국·대만에서 먼저 출시된 뒤 10월 5일 스팀과 퍼플을 통해 북미·남미·유럽·아시아로 서비스를 확장합니다." },
    "zh-hant": { alt: "Aion 2 與韓廠全球化戰略新聞配圖", caption: "NC 官方配圖；Aion 2 去年先在韓國與台灣推出，10 月 5 日經 Steam 與 PURPLE 擴展至北美、南美、歐洲與亞洲。" },
  },
};

export const trendingAugust31Article5: ContentEntry = {
  section: "news",
  slug: "aion-2-ncsoft-global-strategy-korea-playbook",
  schemaType: "NewsArticle",
  publishedAt: "2026-08-31",
  updatedAt: "2026-08-31",
  readingMinutes: 5,
  publication: publishedVerified,
  sources: [koreaSource1, koreaSource2],
  heroImage: koreaHero,
  related: [
    { kind: "content", section: "news", slug: "aion-2-release-date-october-5-2026" },
    { kind: "content", section: "news", slug: "aion-2-october-2026-gta6-launch-crowd" },
    { kind: "content", section: "guides", slug: "aion-2-global-version-changes-guide" },
    { kind: "content", section: "guides", slug: "aion-2-prelaunch-access-routes-guide" },
  ],
  translations: {
    en: articleCopy(newsLabels, "en", 5, {
      eyebrow: "KOREA'S GLOBAL PLAYBOOK",
      title: "Aion 2 and the New Korean Global Playbook: Two Models Inside NCSoft",
      description: "Korean trade outlet 디지털투데이 reports the old “validate in Korea, then go overseas” formula is being rewritten. Inside NCSoft both models now coexist: Aion 2 follows the classic Korea-and-Taiwan-first expansion to four regions on October 5, while Cinder City and Like or Die test overseas appetite from the development stage.",
      intro: "The business story behind Aion 2's October 5 global launch is bigger than one release date. A Korean industry report published on August 30 argues the country's games industry is rewriting its global formula — no longer “validate at home, then export”, but a spectrum where some titles build for overseas from day one. Aion 2 is the clearest example of the old model still working at scale, and the report explains why NCSoft runs both approaches in parallel.",
      sourceNote: "Based on 디지털투데이's report “한국서 검증 후 해외로 옛말…K-게임 '글로벌 공식' 바꿨다” (August 30, 2026), cross-checked with Massively Overpowered's MMO Week in Review (August 30, 2026) covering the same Gamescom launch-date wave.",
      keywords: ["Aion 2 global strategy", "Aion 2 Korea first", "NCSoft globalization", "Korean MMO global launch", "Aion 2 four regions"],
      sections: [
        section("the-shift", "The Old Formula Is Being Rewritten", ["The Korean trade press frames Aion 2's release as part of a structural shift: the old pattern — launch in Korea, prove the game, then export years later — is no longer the only playbook. Korean publishers now range from Korea-first to global-first, and some test overseas appetite before local launch.", "Gamescom 2026 is cited as evidence of the scale of that change: 1,600+ exhibitors, 67 countries, and around 70% of attendees coming from outside Korea — a show where Korean studios measure themselves against a global audience directly.", "The report's core point is that the industry has stopped treating “domestic validation” as a mandatory gate. Global response can now shape development itself, not just a release plan."]),
        section("two-models", "Two Models, One Company: NCSoft", ["The report highlights that both approaches coexist inside NCSoft. Aion 2 follows the traditional path — launched in Korea and Taiwan last year, and now expanding to North America, South America, Europe, and Asia via Steam and PURPLE on October 5.", "Alongside it, Cinder City and Like or Die represent the newer model: Cinder City ran a pre-alpha test in August that explicitly included overseas players, and Like or Die was first revealed to a global audience at Gamescom rather than in Korea.", "Having both in one portfolio is the practical definition of the new normal — there is no single “Korean formula” anymore, there are several."]),
        section("aion2-case", "Aion 2 as the Bridge Case", ["The report's Aion 2 passage (quoted in the source) reads: Aion 2 launched first in Korea and Taiwan last year, and on October 5 expands via Steam and PURPLE to North America, South America, Europe, and Asia. That is the classic sequence executed at full scale.", "What makes it a bridge case: the October 5 launch is a global simultaneous date, not a delayed export. Korea and Taiwan got the head start, but every other region opens the same day — a far tighter worldwide cadence than the old multi-year lag.", "For players this means a fully localized global build at launch (see the language-support guide for the current 8-language list) rather than a stripped export."]),
        section("what-it-means", "What It Means for Players", ["A global-simultaneous launch changes expectations: server capacity, language support, and monetization are decided for a world audience from day one, not retrofitted later. Aion 2's free-to-play model and cosmetics-led shop are the visible result.", "It also means competition for players' attention is global from hour one — the same week as Ace Combat 8 and Gears of War: E-Day (see the October launch-crowd report), against other Korean and Western titles.", "And it raises the stakes for the September 17–18 Launch Scale Test: a successful global stress test is the prerequisite for a smooth October 5 for players in all four regions, not just Korea."]),
        section("takeaway", "The Takeaway", ["Aion 2's October 5 launch is not just a date — it is NCSoft operating the classic Korea-first playbook one more time, at global scale, while also running the newer global-first experiments in the same portfolio.", "The industry context from the Korean report is that this dual-track is the new normal across the country's studios, with Gamescom as the measuring stick.", "For anyone deciding whether to play at launch, the practical reading is positive: a global-simultaneous, free-to-play launch with a localized build and a public stress test beforehand is a stronger setup than the old model ever offered."]),
      ],
    }),
    "zh-hans": articleCopy(newsLabels, "zh-hans", 5, {
      eyebrow: "韩厂全球化新剧本",
      title: "Aion 2 与韩厂新全球化剧本：NCSoft 内部的两条路线",
      description: "韩国产业媒体 디지털투데이 报道称「先在本土验证、再出海」的旧公式正在被改写。NCSoft 内部两条路线并存：Aion 2 沿经典「韩国+台湾先行」路线于 10 月 5 日扩展至四个大区；Cinder City 与 Like or Die 则在开发阶段就检验海外反响。",
      intro: "Aion 2 10 月 5 日全球上线背后的商业故事比一个发售日期更大。8 月 30 日发布的韩国产业报道认为，该国游戏产业正在改写自己的全球化公式——不再是「先本土验证、再出口」，而是一个从韩国先行到全球先行的谱系，部分作品从第一天就为海外打造。Aion 2 是旧模型仍在大规模运转的最清晰例证，报道解释了为什么 NCSoft 并行运作两种做法。",
      sourceNote: "基于 디지털투데이 的报道《한국서 검증 후 해외로 옛말…K-게임 '글로벌 공식' 바꿨다》（2026-08-30），并与 Massively Overpowered 的 MMO 周报（2026-08-30）报道的同一 Gamescom 发行日期浪潮交叉核对。",
      keywords: ["Aion 2 全球化战略", "Aion 2 韩国先行", "NCSoft 全球化", "韩国 MMO 全球上线", "Aion 2 四区域"],
      sections: [
        section("the-shift", "旧公式正在被改写", ["韩国产业媒体将 Aion 2 的发售定位为结构性转变的一部分：旧的模式——在韩国上线、验证游戏、多年后再出口——已不再是唯一剧本。韩国发行商如今横跨「韩国先行」到「全球先行」的谱系，部分作品在本土上线前就检验海外需求。", "Gamescom 2026 被引为这种变化规模的一个证据：1,600+ 展商、67 国，约七成参观者来自韩国以外——这是韩国厂商直接以全球观众为标尺的展会。", "报道的核心是：行业已不再把「本土验证」当作必经门槛。全球反应如今可以反过来塑造开发本身，而不仅是发行计划。"]),
        section("two-models", "一家公司两条路线：NCSoft", ["报道指出两种做法在 NCSoft 内部并存。Aion 2 走传统路线——去年先在韩国与台湾上线，如今于 10 月 5 日经 Steam 与 PURPLE 扩展至北美、南美、欧洲与亚洲。", "与它并列，Cinder City 与 Like or Die 代表更新模式：Cinder City 在 8 月举办了明确包含海外玩家的 pre-alpha 测试，Like or Die 则是在 Gamescom 首次面向全球观众公开，而非在韩国首发。", "同一投资组合中两者兼有，就是新常态的实务定义——「韩式公式」已不复存在，有的只是多种公式。"]),
        section("aion2-case", "Aion 2 作为桥梁案例", ["报道中的 Aion 2 段落（原文引用于来源）：Aion 2 去年先在韩国与台湾推出，10 月 5 日经 Steam 与 PURPLE 扩展至北美、南美、欧洲与亚洲。这是经典序列的大规模执行。", "它之所以是桥梁案例：10 月 5 日是全球同步日期，而非延迟出口。韩国与台湾获得领先，但其余所有大区同一天开启——节奏远比旧有的多年滞后紧凑。", "对玩家而言，这意味着上线时是一个完整本地化的全球版本（当前 8 种语言清单见语言支持指南），而非精简出口版。"]),
        section("what-it-means", "对玩家的意义", ["全球同步上线改变了预期：服务器容量、语言支持与变现从第一天就按世界受众决定，而非事后修补。Aion 2 的免费游玩模式与外观主导商店是可见的结果。", "它也意味着对玩家注意力的竞争从第一小时就是全球性的——与 Ace Combat 8、Gears of War: E-Day 同一周（见十月发行潮报道），同时对阵其他韩厂与欧美作品。", "它还抬高了 9 月 17–18 日 Launch Scale Test 的分量：成功的全球压测，是四个大区玩家都能顺畅迎接 10 月 5 日的前提，而不只是韩国。"]),
        section("takeaway", "结论", ["Aion 2 的 10 月 5 日上线不只是个日期——它是一次全球规模的经典「韩国先行」剧本执行，同时同一组合中也在运行更新的「全球先行」实验。", "韩国报道给出的产业语境是：双轨并进已是大势，Gamescom 就是标尺。", "对任何决定是否首发游玩的玩家，务实的解读是正面的：全球同步、免费游玩、本地化完整、且有公开压测在先——这比旧模型任何时候能提供的都要扎实。"]),
      ],
    }),
    ko: articleCopy(newsLabels, "ko", 5, {
      eyebrow: "K-게임 글로벌 신공식",
      title: "아이온2와 한국 글로벌 신공식: NC소프트 내부의 두 모델",
      description: "디지털투데이는 '한국서 검증 후 해외로'라는 옛 공식이 다시 쓰이고 있다고 보도합니다. NC소프트 내부에 두 모델이 공존합니다: 아이온2는 고전적 한국·대만 선행 모델로 10월 5일 4개 리전에 확장, 신더시티·라이크 오어 다이는 개발 단계부터 해외 반응을 확인합니다.",
      intro: "아이온2의 10월 5일 글로벌 출시 뒤에는 하나의 출시일보다 큰 비즈니스 이야기가 있습니다. 8월 30일 발표된 한국 업계 보도는 한국 게임 산업이 글로벌 공식을 다시 쓰고 있다고 주장합니다. 아이온2는 옛 모델이 여전히 대규모로 작동하는 가장 분명한 사례이며, 왜 NC소프트가 두 방식을 병행하는지 설명합니다.",
      sourceNote: "디지털투데이 보도(2026-08-30)와 Massively Overpowered MMO 위클리 리뷰(2026-08-30)의 Gamescom 출시일 물결 보도를 교차 확인했습니다.",
      keywords: ["아이온2 글로벌 전략", "아이온2 한국 선행", "NC소프트 글로벌화", "한국 MMO 글로벌 출시", "아이온2 4개 리전"],
      sections: [
        section("the-shift", "옛 공식이 다시 쓰이고 있다", "한국 업계 언론은 아이온2의 출시를 구조적 변화의 일부로 봅니다. 한국에서 검증 후 수년 뒤 해외로 나가는 옛 패턴은 더 이상 유일한 공식이 아닙니다. Gamescom 2026이 그 규모의 증거로 인용됩니다: 1,600+ 전시사, 67개국, 참관객 약 70%가 해외. '국내 검증'이 더 이상 필수 관문이 아니라는 것이 핵심입니다."),
        section("two-models", "한 회사 두 모델: NC소프트", "아이온2는 고전적 경로 — 지난해 한국·대만 먼저, 10월 5일 Steam·PURPLE로 북미·남미·유럽·아시아 확장. 신더시티·라이크 오어 다이는 새 모델 — 신더시티는 해외 플레이어를 포함한 pre-alpha(8월)를, 라이크 오어 다이는 Gamescom에서 처음 글로벌 공개. 한 포트폴리오에 둘 다 있는 것이 새 표준의 실무적 정의입니다."),
        section("aion2-case", "아이온2, 다리 역할 사례", "보고서의 아이온2 단락(출처에서 인용): '아이온2는 지난해 한국·대만에 먼저 출시된 뒤 10월 5일 스팀과 퍼플을 통해 북미·남미·유럽·아시아로 서비스를 확장한다.' 10월 5일은 전역 동시 출시일이며, 한국·대만이 헤드스타트를 얻되 모든 리전이 같은 날 열립니다. 플레이어에게는 출시 시 완전히 로컬라이즈된 글로벌 빌드를 의미합니다."),
        section("what-it-means", "플레이어에게 주는 의미", "글로벌 동시 출시는 기대를 바꿉니다: 서버 용량·언어 지원·수익화가 1일차부터 세계 관객 기준으로 결정됩니다. 경쟁도 1시간째부터 글로벌입니다(같은 주 Ace Combat 8·Gears of War: E-Day). 그리고 9월 17–18일 LST의 중요성을 높입니다 — 성공적인 글로벌 부하 테스트가 4개 리전 모두의 원활한 10월 5일의 전제입니다."),
        section("takeaway", "결론", "아이온2의 10월 5일 출시는 날짜 이상입니다 — 고전적 한국 선행 공식의 글로벌 규모 재실행이면서, 같은 포트폴리오의 신모델 실험이기도 합니다. 플레이어에게는 전역 동시·무료·로컬라이즈·사전 공개 스트레스 테스트라는 더 강한 출시 구도로 읽힙니다."),
      ],
    }),
    ja: articleCopy(newsLabels, "ja", 5, {
      eyebrow: "韓国グローバル新公式",
      title: "Aion 2 と韓国の新グローバル公式：NCソフト内の二つのモデル",
      description: "韓国業界メディア 디지털투데이 は「韓国で検証してから海外へ」という旧公式が書き換えられていると報じます。NCソフト内に二つのモデルが併存：Aion 2 は古典的な韓国・台湾先行で10月5日に4リージョンへ拡大、シンダーシティとライク・オア・ダイは開発段階から海外の反応を確認します。",
      intro: "Aion 2 の10月5日グローバル発売の裏には、一つの発売日より大きなビジネスストーリーがあります。8月30日発表の韓国業界報道は、同国のゲーム産業がグローバル公式を書き換えつつあると論じます。Aion 2 は旧モデルがまだ大規模に機能する最も明確な事例であり、なぜNCソフトが両アプローチを並行するかを説明します。",
      sourceNote: "디지털투데이 報道（2026-08-30）と、Massively Overpowered のMMOウィークリーレビュー（2026-08-30）の Gamescom 発売日報道を照合しました。",
      keywords: ["Aion 2 グローバル戦略", "Aion 2 韓国先行", "NCソフト グローバル化", "韓国MMO グローバル発売", "Aion 2 4リージョン"],
      sections: [
        section("the-shift", "旧公式が書き換えられている", "韓国業界紙はAion 2のリリースを構造変化の一部と位置づけます。韓国で検証し数年後に輸出する旧パターンは唯一の公式ではなくなりました。Gamescom 2026が規模の証拠として引用されます：1,600以上の出展社・67カ国・来場者の約70%が海外。『国内検証』が必須のゲートではなくなったのが核心です。"),
        section("two-models", "一社二モデル：NCソフト", "Aion 2 は古典的経路 — 昨年韓国・台湾先行、10月5日にSteam・PURPLEで北米・南米・欧州・アジアへ拡大。シンダーシティとライク・オア・ダイは新モデル — シンダーシティは海外プレイヤーを含むpre-alpha（8月）を、ライク・オア・ダイはGamescomで初めてグローバル公開。一つのポートフォリオに両方あるのが新常態の実務的な定義です。"),
        section("aion2-case", "Aion 2 という橋渡し事例", "報道のAion 2の段落（出典で引用）：『아이온2는 지난해 한국·대만에 먼저 출시된 뒤 10월 5일 스팀과 퍼플을 통해 북미·남미·유럽·아시아로 서비스를 확장한다.』10月5日は全地域同時の日付で、韓国・台湾が先行しつつ全リージョンが同日に開きます。プレイヤーには、発売時に完全にローカライズされたグローバルビルドを意味します。"),
        section("what-it-means", "プレイヤーへの意味", "グローバル同時発売は期待を変えます：サーバー容量・言語対応・収益化が初日から世界基準で決まります。競争も最初の1時間からグローバルです（同じ週にAce Combat 8・Gears of War: E-Day）。そして9月17–18日のLSTの重みを高めます — 成功するグローバル負荷試験が、4リージョンすべての円滑な10月5日の前提です。"),
        section("takeaway", "結論", "Aion 2 の10月5日発売は日付以上です — 古典的な韓国先行公式のグローバル規模での再実行であり、同時に同じポートフォリオ内の新モデル実験です。プレイヤーには、全地域同時・無料・ローカライズ・事前の公開ストレステストという、旧モデルより強い発売構えとして読めます。"),
      ],
    }),
    fr: articleCopy(newsLabels, "fr", 5, {
      eyebrow: "LE NOUVEAU PLAYBOOK CORÉEN",
      title: "Aion 2 et le nouveau playbook mondial coréen : deux modèles chez NCSoft",
      description: "디지털투데이 rapporte que la formule « valider en Corée, puis partir à l'étranger » est réécrite. Chez NCSoft, deux modèles coexistent : Aion 2 suit la classique expansion Corée-Taïwan vers quatre régions le 5 octobre, tandis que Cinder City et Like or Die testent l'appétit mondial dès le développement.",
      intro: "Derrière le lancement mondial d'Aion 2 le 5 octobre, il y a une histoire plus grande qu'une date. Un rapport de l'industrie coréenne publié le 30 août affirme que le pays réécrit sa formule mondiale — fini « valider chez soi puis exporter ». Aion 2 est l'exemple le plus net de l'ancien modèle qui fonctionne encore à grande échelle, et le rapport explique pourquoi NCSoft mène les deux approches en parallèle.",
      sourceNote: "Basé sur le rapport de 디지털투데이 « 한국서 검증 후 해외로 옛말…K-게임 '글로벌 공식' 바꿨다 » (30 août 2026), recoupé avec la revue de semaine MMO de Massively Overpowered (30 août 2026) couvrant la même vague de dates Gamescom.",
      keywords: ["Aion 2 stratégie mondiale", "Aion 2 Corée d'abord", "NCSoft mondialisation", "MMO coréen lancement mondial", "Aion 2 quatre régions"],
      sections: [
        section("the-shift", "L'ancienne formule est réécrite", "La presse coréenne cadre Aion 2 comme un changement structurel : lancer en Corée, prouver le jeu, exporter des années plus tard n'est plus l'unique playbook. Gamescom 2026 en est la preuve : plus de 1 600 exposants, 67 pays, environ 70 % de visiteurs étrangers. La validation domestique n'est plus un passage obligé."),
        section("two-models", "Deux modèles, une entreprise : NCSoft", "Aion 2 suit le chemin classique — Corée et Taïwan l'an dernier, puis extension via Steam et PURPLE le 5 octobre en Amérique du Nord, du Sud, en Europe et en Asie. Cinder City (pre-alpha d'août incluant des joueurs étrangers) et Like or Die (révélé d'abord au monde à Gamescom) représentent le modèle neuf. Avoir les deux dans un portefeuille est la définition pratique de la nouvelle norme."),
        section("aion2-case", "Aion 2 comme cas-pont", "Le passage sur Aion 2 du rapport (cité dans la source) : lancé d'abord en Corée et à Taïwan l'an dernier, il s'étend le 5 octobre via Steam et PURPLE à l'Amérique du Nord, du Sud, à l'Europe et à l'Asie. Le 5 octobre est une date mondiale simultanée, pas une exportation tardive — la Corée et Taïwan ont l'avance, mais toutes les régions ouvrent le même jour."),
        section("what-it-means", "Ce que ça change pour les joueurs", "Un lancement mondial simultané décide dès le jour 1 des serveurs, des langues et de la monétisation. La concurrence est mondiale dès la première heure (Ace Combat 8 et Gears of War: E-Day la même semaine). Et cela soulève l'enjeu du test de charge 17–18 septembre : un test mondial réussi est la condition d'un 5 octobre fluide pour les quatre régions."),
        section("takeaway", "Conclusion", "Le 5 octobre n'est pas qu'une date : c'est NCSoft exécutant encore le playbook Corée-d'abord à échelle mondiale tout en menant les expériences global-first dans le même portefeuille. Pour un joueur, la lecture pratique est positive : lancement mondial simultané, gratuit, localisé, avec test public avant — plus solide que ce que l'ancien modèle offrait."),
      ],
    }),
    de: articleCopy(newsLabels, "de", 5, {
      eyebrow: "DAS NEUE KOREANISCHE GLOBAL-PLAYBOOK",
      title: "Aion 2 und das neue koreanische Global-Playbook: Zwei Modelle bei NCSoft",
      description: "디지털투데이 berichtet, die alte Formel „erst in Korea validieren, dann ins Ausland“ werde neu geschrieben. Bei NCSoft koexistieren beide Modelle: Aion 2 folgt der klassischen Korea-Taiwan-zuerst-Expansion in vier Regionen am 5. Oktober, während Cinder City und Like or Die die Auslandsnachfrage bereits in der Entwicklung testen.",
      intro: "Hinter dem globalen Start von Aion 2 am 5. Oktober steckt eine größere Geschichte als ein Datum. Ein koreanischer Branchenbericht vom 30. August argumentiert, die Branche schreibe ihre globale Formel um — nicht mehr „erst daheim validieren, dann exportieren“. Aion 2 ist das klarste Beispiel dafür, dass das alte Modell noch immer im großen Stil funktioniert, und der Bericht erklärt, warum NCSoft beide Ansätze parallel fährt.",
      sourceNote: "Basierend auf dem Bericht von 디지털투데이 „한국서 검증 후 해외로 옛말…K-게임 '글로벌 공식' 바꿨다“ (30. August 2026), abgeglichen mit dem MMO-Wochenrückblick von Massively Overpowered (30. August 2026).",
      keywords: ["Aion 2 globale Strategie", "Aion 2 Korea zuerst", "NCSoft Globalisierung", "koreanisches MMO globaler Start", "Aion 2 vier Regionen"],
      sections: [
        section("the-shift", "Die alte Formel wird umgeschrieben", "Die koreanische Branchenpresse rahmt Aion 2 als strukturellen Wandel: In Korea starten, beweisen, Jahre später exportieren ist nicht mehr das einzige Playbook. Gamescom 2026 als Beleg: über 1.600 Aussteller, 67 Länder, rund 70 % ausländische Besucher. Die heimische Validierung ist kein Pflicht-Gate mehr."),
        section("two-models", "Zwei Modelle, ein Unternehmen: NCSoft", "Aion 2 folgt dem klassischen Weg — Korea und Taiwan letztes Jahr, dann Ausweitung über Steam und PURPLE am 5. Oktober auf Nord-/Südamerika, Europa und Asien. Cinder City (August-Pre-alpha mit ausländischen Spielern) und Like or Die (zuerst global auf der Gamescom enthüllt) stehen für das neue Modell. Beides im selben Portfolio ist die praktische Definition des neuen Normals."),
        section("aion2-case", "Aion 2 als Brückenfall", "Die Aion-2-Passage des Berichts (im Quelltext zitiert): letztes Jahr zuerst in Korea und Taiwan, dann am 5. Oktober über Steam und PURPLE nach Nord-/Südamerika, Europa und Asien. Der 5. Oktober ist ein globales Simultandatum, kein verzögerter Export — Korea und Taiwan haben den Vorsprung, aber alle Regionen öffnen am selben Tag."),
        section("what-it-means", "Was das für Spieler bedeutet", "Ein global-simultaner Start entscheidet Server, Sprachen und Monetarisierung ab Tag 1 für ein Weltpublikum. Die Konkurrenz ist von der ersten Stunde global (Ace Combat 8 und Gears of War: E-Day in derselben Woche). Und es erhöht das Gewicht des LST 17.–18. September: Ein erfolgreicher globaler Stresstest ist die Voraussetzung für einen reibungslosen 5. Oktober in allen vier Regionen."),
        section("takeaway", "Fazit", "Der 5. Oktober ist mehr als ein Datum: NCSoft führt das klassische Korea-zuerst-Playbook erneut in globaler Größenordnung aus, während im selben Portfolio die Global-first-Experimente laufen. Für Spieler ist die praktische Lesart positiv: global-simultan, kostenlos, lokalisiert und mit öffentlichem Test davor — stärker als alles, was das alte Modell je bot."),
      ],
    }),
    es: articleCopy(newsLabels, "es", 5, {
      eyebrow: "EL NUEVO MANUAL MUNDIAL COREANO",
      title: "Aion 2 y el nuevo manual mundial coreano: dos modelos en NCSoft",
      description: "디지털투데이 informa que la fórmula «validar en Corea, luego salir al extranjero» se está reescribiendo. En NCSoft coexisten dos modelos: Aion 2 sigue la clásica expansión Corea-Taiwán hacia cuatro regiones el 5 de octubre, mientras que Cinder City y Like or Die prueban el apetito mundial desde el desarrollo.",
      intro: "Detrás del lanzamiento mundial de Aion 2 el 5 de octubre hay una historia mayor que una fecha. Un informe de la industria coreana publicado el 30 de agosto sostiene que el país está reescribiendo su fórmula mundial — ya no «validar en casa y exportar». Aion 2 es el ejemplo más claro del modelo antiguo que aún funciona a gran escala, y el informe explica por qué NCSoft dirige ambos enfoques en paralelo.",
      sourceNote: "Basado en el informe de 디지털투데이 «한국서 검증 후 해외로 옛말…K-게임 '글로벌 공식' 바꿨다» (30 de agosto de 2026), cotejado con el resumen semanal de MMO de Massively Overpowered (30 de agosto de 2026).",
      keywords: ["Aion 2 estrategia mundial", "Aion 2 Corea primero", "NCSoft globalización", "MMO coreano lanzamiento mundial", "Aion 2 cuatro regiones"],
      sections: [
        section("the-shift", "La vieja fórmula se reescribe", "La prensa coreana enmarca Aion 2 como un cambio estructural: lanzar en Corea, probar el juego y exportar años después ya no es el único manual. Gamescom 2026 como prueba: más de 1.600 expositores, 67 países, alrededor del 70 % de visitantes extranjeros. La validación nacional ya no es una puerta obligatoria."),
        section("two-models", "Dos modelos, una empresa: NCSoft", "Aion 2 sigue el camino clásico — Corea y Taiwán el año pasado, luego expansión vía Steam y PURPLE el 5 de octubre a Norteamérica, Sudamérica, Europa y Asia. Cinder City (pre-alpha de agosto con jugadores extranjeros) y Like or Die (revelado primero al mundo en Gamescom) representan el modelo nuevo. Tener ambos en una cartera es la definición práctica de la nueva normalidad."),
        section("aion2-case", "Aion 2 como caso-puente", "El pasaje de Aion 2 del informe (citado en la fuente): lanzado primero en Corea y Taiwán el año pasado, se expande el 5 de octubre vía Steam y PURPLE a Norteamérica, Sudamérica, Europa y Asia. El 5 de octubre es una fecha mundial simultánea, no una exportación tardía — Corea y Taiwán tienen la ventaja, pero todas las regiones abren el mismo día."),
        section("what-it-means", "Qué significa para los jugadores", "Un lanzamiento mundial simultáneo decide desde el día 1 servidores, idiomas y monetización. La competencia es mundial desde la primera hora (Ace Combat 8 y Gears of War: E-Day la misma semana). Y eleva el peso del test de carga 17–18 de septiembre: un test mundial exitoso es el requisito de un 5 de octubre fluido en las cuatro regiones."),
        section("takeaway", "Conclusión", "El 5 de octubre no es solo una fecha: NCSoft ejecuta el manual Corea-primero una vez más a escala mundial mientras corre los experimentos global-first en la misma cartera. Para un jugador, la lectura práctica es positiva: lanzamiento mundial simultáneo, gratuito, localizado y con prueba pública antes — más sólido que lo que ofrecía el modelo antiguo."),
      ],
    }),
    "pt-br": articleCopy(newsLabels, "pt-br", 5, {
      eyebrow: "O NOVO MANUAL MUNDIAL COREANO",
      title: "Aion 2 e o novo manual mundial coreano: dois modelos na NCSoft",
      description: "디지털투데이 informa que a fórmula «validar na Coreia e depois ir ao exterior» está sendo reescrita. Na NCSoft, dois modelos coexistem: o Aion 2 segue a clássica expansão Coreia-Taiwan para quatro regiões em 5 de outubro, enquanto Cinder City e Like or Die testam o apetite mundial desde o desenvolvimento.",
      intro: "Por trás do lançamento mundial do Aion 2 em 5 de outubro há uma história maior que uma data. Um relatório da indústria coreana publicado em 30 de agosto defende que o país está reescrevendo sua fórmula mundial — não mais «validar em casa e exportar». O Aion 2 é o exemplo mais claro do modelo antigo ainda funcionando em escala, e o relatório explica por que a NCSoft conduz ambas as abordagens em paralelo.",
      sourceNote: "Com base no relatório de 디지털투데이 «한국서 검증 후 해외로 옛말…K-게임 '글로벌 공식' 바꿨다» (30 de agosto de 2026), cruzado com a revista semanal de MMOs da Massively Overpowered (30 de agosto de 2026).",
      keywords: ["Aion 2 estratégia mundial", "Aion 2 Coreia primeiro", "NCSoft globalização", "MMO coreano lançamento mundial", "Aion 2 quatro regiões"],
      sections: [
        section("the-shift", "A velha fórmula está sendo reescrita", "A imprensa coreana enquadra o Aion 2 como uma mudança estrutural: lançar na Coreia, provar o jogo e exportar anos depois não é mais o único manual. A Gamescom 2026 como prova: mais de 1.600 expositores, 67 países, cerca de 70 % de visitantes estrangeiros. A validação doméstica não é mais um portão obrigatório."),
        section("two-models", "Dois modelos, uma empresa: NCSoft", "O Aion 2 segue o caminho clássico — Coreia e Taiwan no ano passado, depois expansão via Steam e PURPLE em 5 de outubro para América do Norte, do Sul, Europa e Ásia. Cinder City (pre-alpha de agosto com jogadores estrangeiros) e Like or Die (revelado primeiro ao mundo na Gamescom) representam o modelo novo. Ter ambos num portfólio é a definição prática da nova normalidade."),
        section("aion2-case", "O Aion 2 como caso-ponte", "A passagem do Aion 2 no relatório (citada na fonte): lançado primeiro na Coreia e Taiwan no ano passado, expande em 5 de outubro via Steam e PURPLE para América do Norte, do Sul, Europa e Ásia. O 5 de outubro é uma data mundial simultânea, não uma exportação tardia — Coreia e Taiwan têm a vantagem, mas todas as regiões abrem no mesmo dia."),
        section("what-it-means", "O que significa para os jogadores", "Um lançamento mundial simultâneo decide desde o dia 1 servidores, idiomas e monetização. A concorrência é mundial desde a primeira hora (Ace Combat 8 e Gears of War: E-Day na mesma semana). E eleva o peso do teste de carga 17–18 de setembro: um teste mundial bem-sucedido é o requisito de um 5 de outubro fluido nas quatro regiões."),
        section("takeaway", "Conclusão", "O 5 de outubro não é só uma data: a NCSoft executa o manual Coreia-primeiro mais uma vez em escala mundial enquanto roda os experimentos global-first no mesmo portfólio. Para um jogador, a leitura prática é positiva: lançamento mundial simultâneo, gratuito, localizado e com teste público antes — mais sólido do que o modelo antigo oferecia."),
      ],
    }),
    ru: articleCopy(newsLabels, "ru", 5, {
      eyebrow: "НОВЫЙ КОРЕЙСКИЙ ГЛОБАЛЬНЫЙ СЦЕНАРИЙ",
      title: "Aion 2 и новый корейский глобальный сценарий: две модели внутри NCSoft",
      description: "디지털투데이 сообщает, что старая формула «сначала валидация в Корее, потом за границу» переписывается. Внутри NCSoft сосуществуют две модели: Aion 2 следует классической экспансии Корея-Тайвань в четыре региона 5 октября, а Cinder City и Like or Die тестируют мировой спрос уже на этапе разработки.",
      intro: "За мировым запуском Aion 2 5 октября стоит история больше, чем дата. Отраслевой отчёт от 30 августа утверждает, что корейская индустрия переписывает свою глобальную формулу — не «сначала дома, потом экспорт». Aion 2 — самый ясный пример старой модели, всё ещё работающей в масштабе, и отчёт объясняет, почему NCSoft ведёт оба подхода параллельно.",
      sourceNote: "На основе отчёта 디지털투데이 «한국서 검증 후 해외로 옛말…K-게임 '글로벌 공식' 바꿨다» (30 августа 2026), сверено с еженедельником MMO Massively Overpowered (30 августа 2026).",
      keywords: ["Aion 2 глобальная стратегия", "Aion 2 сначала Корея", "NCSoft глобализация", "корейская MMO мировой запуск", "Aion 2 четыре региона"],
      sections: [
        section("the-shift", "Старая формула переписывается", "Корейская отраслевая пресса рассматривает Aion 2 как структурный сдвиг: запустить в Корее, доказать игру и экспортировать годами позже — больше не единственный сценарий. Gamescom 2026 как доказательство: более 1 600 экспонентов, 67 стран, около 70 % иностранных посетителей. Домашняя валидация больше не обязательный барьер."),
        section("two-models", "Две модели, одна компания: NCSoft", "Aion 2 идёт классическим путём — Корея и Тайвань в прошлом году, затем расширение через Steam и PURPLE 5 октября на Северную/Южную Америку, Европу и Азию. Cinder City (августовская pre-alpha с иностранными игроками) и Like or Die (впервые показан миру на Gamescom) представляют новую модель. Наличие обеих в одном портфеле — практическое определение новой нормы."),
        section("aion2-case", "Aion 2 как мостовой случай", "Фрагмент отчёта об Aion 2 (цитируется в источнике): сначала запуск в Корее и на Тайване в прошлом году, затем 5 октября расширение через Steam и PURPLE на Северную/Южную Америку, Европу и Азию. 5 октября — глобальная одновременная дата, а не запоздалый экспорт: Корея и Тайвань имеют фору, но все регионы открываются в один день."),
        section("what-it-means", "Что это значит для игроков", "Глобальный одновременный запуск решает серверы, языки и монетизацию с первого дня под мировую аудиторию. Конкуренция глобальна с первого часа (Ace Combat 8 и Gears of War: E-Day в ту же неделю). И это повышает вес стресс-теста 17–18 сентября: успешный глобальный тест — условие плавного 5 октября во всех четырёх регионах."),
        section("takeaway", "Вывод", "5 октября — больше, чем дата: NCSoft снова исполняет классический сценарий «сначала Корея» в мировом масштабе, одновременно ведя эксперименты global-first в том же портфеле. Для игрока практическое чтение позитивно: глобальный одновременный, бесплатный, локализованный запуск с публичным тестом заранее — прочнее, чем предлагала старая модель."),
      ],
    }),
    "zh-hant": articleCopy(newsLabels, "zh-hant", 5, {
      eyebrow: "韓廠全球化新劇本",
      title: "Aion 2 與韓廠新全球化劇本：NCSoft 內部的兩條路線",
      description: "韓國產業媒體 디지털투데이 報導稱「先在本土驗證、再出海」的舊公式正在被改寫。NCSoft 內部兩條路線並存：Aion 2 沿經典「韓國+台灣先行」路線於 10 月 5 日擴展至四個大區；Cinder City 與 Like or Die 則在開發階段就檢驗海外反響。",
      intro: "Aion 2 10 月 5 日全球上線背後的商業故事比一個發售日期更大。8 月 30 日發布的韓國產業報導認為，該國遊戲產業正在改寫自己的全球化公式——不再是「先本土驗證、再出口」，而是一個從韓國先行到全球先行的譜系。Aion 2 是舊模型仍在大規模運轉的最清晰例證，報導解釋了為什麼 NCSoft 並行運作兩種做法。",
      sourceNote: "基於 디지털투데이 的報導《한국서 검증 후 해외로 옛말…K-게임 '글로벌 공식' 바꿨다》（2026-08-30），並與 Massively Overpowered 的 MMO 週報（2026-08-30）報導的同一 Gamescom 發行日期浪潮交叉核對。",
      keywords: ["Aion 2 全球化戰略", "Aion 2 韓國先行", "NCSoft 全球化", "韓國 MMO 全球上線", "Aion 2 四區域"],
      sections: [
        section("the-shift", "舊公式正在被改寫", "韓國產業媒體將 Aion 2 的發售定位為結構性轉變的一部分：舊的模式——在韓國上線、驗證遊戲、多年後再出口——已不再是唯一劇本。Gamescom 2026 被引為規模證據：1,600+ 展商、67 國，約七成參觀者來自韓國以外。行業已不再把「本土驗證」當作必經門檻。"),
        section("two-models", "一家公司兩條路線：NCSoft", "Aion 2 走傳統路線——去年先在韓國與台灣上線，如今於 10 月 5 日經 Steam 與 PURPLE 擴展至北美、南美、歐洲與亞洲。與它並列，Cinder City 與 Like or Die 代表更新模式：Cinder City 在 8 月舉辦了明確包含海外玩家的 pre-alpha 測試，Like or Die 則是在 Gamescom 首次面向全球觀眾公開。"),
        section("aion2-case", "Aion 2 作為橋樑案例", "報導中的 Aion 2 段落（原文引用于來源）：Aion 2 去年先在韓國與台灣推出，10 月 5 日經 Steam 與 PURPLE 擴展至北美、南美、歐洲與亞洲。10 月 5 日是全球同步日期，而非延遲出口——韓國與台灣獲得領先，但其餘所有大區同一天開啟。"),
        section("what-it-means", "對玩家的意義", "全球同步上線改變了預期：伺服器容量、語言支援與變現從第一天就按世界受眾決定。競爭從第一小時就是全球性的——與 Ace Combat 8、Gears of War: E-Day 同一週。它還抬高了 9 月 17–18 日 LST 的分量：成功的全球壓測，是四個大區玩家都能順暢迎接 10 月 5 日的前提。"),
        section("takeaway", "結論", "Aion 2 的 10 月 5 日上線不只是個日期——它是一次全球規模的經典「韓國先行」劇本執行，同時同一組合中也在運行更新的「全球先行」實驗。對任何決定是否首發遊玩的玩家，務實的解讀是正面的：全球同步、免費遊玩、本地化完整、且有公開壓測在先。"),
      ],
    }),
  },
};
