import { articleCopy, localizations, guideLabels, publishedVerified, section } from "./trending-september-16-shared";
import type { ContentEntry, ContentHeroImage, ContentSource } from "./content-registry";

const combatSource: ContentSource = {
  id: "nc-aion2-official-combat",
  kind: "official",
  publisher: "NC Corporation",
  label: "Aion 2 Official — Combat System",
  url: "https://aion2.plaync.com/en-us/gameplay/",
  publishedAt: "2026-08-15",
  retrievedAt: "2026-09-16",
  verifiedAt: "2026-09-16",
  localizations: localizations({
    "zh-hans": "Aion 2 官方 — 战斗系统", en: "Aion 2 Official — Combat System",
    fr: "Aion 2 Officiel — Système de Combat", de: "Aion 2 Offiziell — Kampfsystem",
    es: "Aion 2 Oficial — Sistema de Combate", ja: "Aion 2 公式 — 戦闘システム",
    "pt-br": "Aion 2 Oficial — Sistema de Combate", ru: "Aion 2 Официальный — Боевая Система",
    ko: "Aion 2 공식 — 전투 시스템", "zh-hant": "Aion 2 官方 — 戰鬥系統",
  }, "https://aion2.plaync.com/en-us/gameplay/"),
};

const combatHero: ContentHeroImage = {
  src: "https://blogfiles.ncsoft.net/news/af7330da-4ff6-4b58-aece-400e6061a3be.jpg",
  width: 1200, height: 630,
  credit: "NC Corporation", sourceUrl: "https://aion2.plaync.com/en-us/", rights: "linked-official-media",
  translations: {
    "zh-hans": { alt: "Aion 2 战斗机制攻略横幅", caption: "Aion 2 动作战斗系统深度解析——技能循环、走位、控制和后期战斗。" },
    en: { alt: "Aion 2 Combat Mechanics Guide Banner", caption: "Deep dive into Aion 2's action combat system — skill rotations, positioning, crowd control, and endgame combat." },
    fr: { alt: "Bannière Guide Mécaniques de Combat Aion 2", caption: "Plongée dans le système de combat action d'Aion 2 — rotations, positionnement, contrôle et combat endgame." },
    de: { alt: "Aion 2 Kampfmechanik-Guide Banner", caption: "Tiefer Einblick in Aion 2s Action-Kampfsystem — Rotationen, Positionierung, Crowd-Control und Endgame." },
    es: { alt: "Banner Guía Mecánicas de Combate Aion 2", caption: "Análisis del sistema de combate action de Aion 2 — rotaciones, posicionamiento, control y combate endgame." },
    ja: { alt: "Aion 2 戦闘メカニクスガイドバナー", caption: "Aion 2アクション戦闘システムの深層——スキルローテーション、ポジショニング、CC、エンドゲーム。" },
    "pt-br": { alt: "Banner Guia Mecânicas de Combate Aion 2", caption: "Análise do sistema de combate action do Aion 2 — rotações, posicionamento, controle e combate endgame." },
    ru: { alt: "Баннер Гайд Боевые Механики Aion 2", caption: "Глубокий анализ экшн-боевой системы Aion 2 — ротации, позиционирование, контроль и эндшпиль." },
    ko: { alt: "Aion 2 전투 메커니즘 가이드 배너", caption: "Aion 2 액션 전투 시스템 심층 분석 — 스킬 로테이션, 포지셔닝, CC, 엔드게임." },
    "zh-hant": { alt: "Aion 2 戰鬥機制攻略橫幅", caption: "Aion 2 動作戰鬥系統深度解析——技能循環、走位、控制和後期戰鬥。" },
  },
};

export const trendingSeptember16Article4: ContentEntry = {
  section: "guides",
  slug: "aion-2-combat-mechanics-guide",
  schemaType: "Article",
  publishedAt: "2026-09-16",
  updatedAt: "2026-09-16",
  readingMinutes: 7,
  publication: publishedVerified,
  sources: [combatSource],
  heroImage: combatHero,
  related: [
    { kind: "content", section: "guides", slug: "aion-2-skill-system-deep-dive" },
    { kind: "content", section: "guides", slug: "aion-2-trinity-roles-guide" },
    { kind: "content", section: "guides", slug: "aion-2-dps-meter-guide" },
    { kind: "content", section: "guides", slug: "aion-2-pvp-guide-battlegrounds-abyss" },
  ],
  translations: {
    en: articleCopy(guideLabels, "en", 7, {
      eyebrow: "COMBAT SYSTEM",
      title: "Aion 2 Combat Mechanics Deep Dive: Action Combat, Skill Rotations, Positioning, and Crowd Control",
      description: "Master Aion 2's action combat system — from basic combos and positioning to advanced crowd control chains and endgame raid mechanics. A comprehensive guide to the combat mechanics that define your success.",
      intro: "Aion 2's action combat system is one of the biggest changes from the tab-target era of Aion 1. Every ability requires manual aiming, positioning affects damage output, and understanding crowd control is essential for both PvE and PvP success. This guide breaks down every layer of the combat system.",
      sourceNote: "Based on NC's official combat system documentation and Korean service mechanics as of September 2026. Global launch balance may differ.",
      keywords: ["Aion 2 combat guide", "Aion 2 combat mechanics", "Aion 2 action combat", "Aion 2 skill rotation", "Aion 2 crowd control"],
      sections: [
        section("combat-fundamentals", "Combat Fundamentals: The Action Combat Loop", ["Aion 2 uses a full action combat system where every skill requires manual aiming. Auto-attacks are directional — your character attacks in the direction you face. This means positioning is always relevant, even for basic damage.", "The combat loop revolves around three phases: opener (burst damage skills with long cooldowns), sustained rotation (medium-cooldown skills that generate resources), and finisher (high-damage skills that consume accumulated resources). Learning this loop is the foundation of effective combat.", "Stamina management is a critical element. Dodging, sprinting, and some skills consume stamina, and running out leaves you vulnerable. Always maintain a stamina buffer for emergency dodges, especially in dungeon and PvP content where a single missed dodge can mean death."]),
        section("skill-rotation", "Building Effective Skill Rotations", ["Your rotation should follow a priority system rather than a fixed sequence. Start with high-impact opener skills (usually your strongest burst abilities), then fill gaps with sustained damage skills, and use finishers when your resource bar is full.", "Skill synergy is key. Many skills apply debuffs or conditions that increase the damage of subsequent skills. For example, a skill that applies a bleed effect might be followed by a skill that deals bonus damage to bleeding targets. Learn these chains for maximum damage output.", "Defensive cooldowns should be woven into your rotation rather than saved for emergencies. Using a damage reduction skill during a known high-damage phase is more effective than panic-pressing it when you are nearly dead. Plan your defensive usage around encounter mechanics."]),
        section("positioning-mobility", "Positioning and Mobility: Where You Stand Matters", ["Aion 2 rewards positional attacks. Back attacks and flanking attacks deal bonus damage — typically 15-25% more than frontal attacks. This means that for DPS classes, learning to attack from behind or the side is essential for maximizing damage output.", "Mobility skills are not just for closing gaps. Use them to maintain positional advantage, dodge telegraphed attacks, and reposition during AoE-heavy encounters. Classes with high mobility can maintain damage output while staying safe, while immobile classes must trade positioning for survival.", "Kiting is a viable combat strategy for ranged classes. Maintain distance from melee opponents while dealing damage, using movement skills to create separation when they close in. Healers should also practice kiting to avoid melee pressure in PvP content."]),
        section("crowd-control", "Understanding Crowd Control: CC Types and Interactions", ["Aion 2 has five main CC types: stun (complete action prevention), knockdown (forced prone state), silence (skill prevention), root (movement prevention), and slow (movement reduction). Each type has different counters and immunity mechanics.", "CC immunity windows are crucial. After being affected by a CC effect, you gain a brief immunity period (typically 3-5 seconds). This means CC chains must be timed carefully — follow up with the next CC as the immunity expires, not before.", "In PvE, raid bosses have CC resistance thresholds. Stuns and knockdowns become less effective as the boss takes more CC, and some mechanics are completely immune to certain CC types. Check your dungeon guides for specific boss CC interactions.", "In PvP, CC chains are the core of competitive play. A well-timed chain of stun into silence into knockdown can lock down an opponent for 10+ seconds. However, CC skills have long cooldowns — waste them and you are vulnerable for the rest of the fight."]),
        section("endgame-combat", "Endgame Combat Considerations", ["Trial raids introduce complex mechanics that go beyond basic rotation. Boss abilities require specific positioning, interrupt timing, and role-specific responsibilities. Study encounter guides before attempting content to avoid costly mistakes.", "Open world PvP engagements require different skills than instanced combat. Awareness of terrain, escape routes, and potential reinforcements is as important as your combat rotation. Never fight in a position where you cannot retreat if the situation turns against you.", "Siege warfare is the pinnacle of Aion 2 combat. Large-scale battles with hundreds of players require coordination, target prioritization, and the ability to adapt quickly. Communication tools (voice chat, guild commands) are essential for effective siege participation.", "Balance patches regularly shift the combat meta. Stay updated on patch notes and adjust your rotation, CC usage, and build accordingly. A rotation that was optimal last patch may be suboptimal after a balance change."]),
      ],
    }),
    "zh-hans": articleCopy(guideLabels, "zh-hans", 7, {
      eyebrow: "战斗系统",
      title: "Aion 2 战斗机制深度解析：动作战斗、技能循环、走位与控制",
      description: "掌握 Aion 2 的动作战斗系统——从基础连招和走位到高级控制链和后期副本机制。全面的战斗机制指南。",
      intro: "Aion 2 的动作战斗系统是与 Aion 1 锁定目标时代最大的变化之一。每个技能需要手动瞄准，走位影响伤害输出，理解控制对 PvE 和 PvP 都至关重要。",
      sourceNote: "基于 NC 官方战斗系统文档和韩服机制（截至 2026 年 9 月）。全球版平衡可能不同。",
      keywords: ["Aion 2 战斗攻略", "Aion 2 战斗机制", "Aion 2 动作战斗", "Aion 2 技能循环", "Aion 2 控制"],
      sections: [
        section("combat-fundamentals", "战斗基础：动作战斗循环", ["Aion 2 使用全面动作战斗系统，每个技能需要手动瞄准。自动攻击是有方向的——角色朝你面对的方向攻击。走位始终重要。", "战斗循环围绕三个阶段：开场（高爆发长冷却技能）、持续循环（中等冷却产生资源的技能）和终结（消耗累积资源的高伤害技能）。", "体力管理是关键要素。闪避、冲刺和部分技能消耗体力，耗尽会让你陷入脆弱。始终保持体力缓冲用于紧急闪避。"]),
        section("skill-rotation", "构建有效技能循环", ["循环应遵循优先级系统而非固定顺序。先用高影响力开场技能，再用持续伤害技能填充间隙，资源条满时使用终结技。", "技能协同是关键。许多技能施加 debuff 或状态，增加后续技能伤害。学习这些连锁以获得最大伤害输出。", "防御冷却应编入循环而非留给紧急情况。在已知高伤害阶段使用减伤技能比快死时慌忙按下更有效。"]),
        section("positioning-mobility", "走位与机动性", ["Aion 2 奖励位置攻击。背刺和侧翼攻击有额外伤害——通常比正面攻击高 15-25%。DPS 职业必须学会从背后或侧面攻击。", "机动技能不仅用于缩短距离。用于维持位置优势、躲避预告攻击和 AoE 密集战斗中重新定位。", "风筝对远程职业是可行策略。保持与近战对手距离同时输出，使用移动技能在他们靠近时拉开距离。"]),
        section("crowd-control", "理解控制：CC 类型与交互", ["Aion 2 有五种主要 CC：眩晕（完全阻止行动）、击倒（强制倒地）、沉默（阻止技能）、定身（阻止移动）和减速（降低移速）。", "CC 免疫窗口至关重要。被 CC 后获得短暂免疫期（通常 3-5 秒）。CC 链需仔细计时——在免疫结束后接下一个 CC。", "PvE 中团队副本 Boss 有 CC 抗性阈值。某些机制完全免疫特定 CC 类型。查看副本攻略了解 Boss 的 CC 交互。", "PvP 中 CC 链是竞技核心。精心计时的眩晕→沉默→击倒链可以锁定对手 10 秒以上。但 CC 技能冷却长——浪费意味着整场战斗都处于脆弱状态。"]),
        section("endgame-combat", "后期战斗注意事项", ["试炼副本引入超越基础循环的复杂机制。Boss 技能需要特定走位、打断时机和职业专属职责。尝试前研究副本攻略避免代价高昂的错误。", "开放世界 PvP 需要不同于副本战斗的技能。对地形、逃跑路线和潜在增援的感知与你的战斗循环同样重要。", "攻城战是 Aion 2 战斗的巅峰。数百人的大规模战斗需要协调、目标优先级和快速适应能力。语音通讯和公会命令对有效参与攻城战至关重要。", "平衡补丁定期改变战斗 meta。关注补丁说明并相应调整循环、CC 使用和构建。"]),
      ],
    }),
    fr: articleCopy(guideLabels, "fr", 7, {
      eyebrow: "SYSTÈME DE COMBAT",
      title: "Mécaniques de Combat d'Aion 2 : Combat Action, Rotations, Positionnement et Contrôle",
      description: "Maîtrisez le système de combat action d'Aion 2 — des combos de base au contrôle avancé et aux mécaniques de raids.",
      intro: "Le système de combat action d'Aion 2 est l'un des plus grands changements par rapport à l'ère tab-target d'Aion 1.",
      sourceNote: "Basé sur la documentation officielle du système de combat de NC (septembre 2026).",
      keywords: ["Guide combat Aion 2", "Mécaniques combat Aion 2", "Combat action Aion 2"],
      sections: [
        section("combat-fundamentals", "Fondamentaux du Combat", ["Aion 2 utilise un système de combat action complet où chaque compétence nécessite un visée manuelle.", "La boucle de combat tourne autour de trois phases : ouverture, rotation soutenue et finisseur.", "La gestion de l'endurance est un élément critique. Maintenez toujours un tampon d'endurance pour les esquives d'urgence."]),
        section("skill-rotation", "Construire des Rotations Efficaces", ["Votre rotation doit suivre un système de priorité plutôt qu'une séquence fixe.", "La synergie des compétences est clé. De nombreuses compétences appliquent des debuffs qui augmentent les dégâts des compétences suivantes.", "Les cooldowns défensifs doivent être intégrés dans votre rotation plutôt que réservés pour les urgences."]),
        section("positioning-mobility", "Positionnement et Mobilité", ["Aion 2 récompense les attaques positionnelles. Les attaques dans le dos et de flanc infligent des bonus de dégâts.", "Les compétences de mobilité ne servent pas qu'à combler les écarts. Utilisez-les pour maintenir l'avantage positionnel.", "Le kiting est une stratégie viable pour les classes à distance."]),
        section("crowd-control", "Comprendre le Contrôle des Foules", ["Aion 2 a cinq types de CC principaux : étourdissement, mise à terre, silence, enracinement et ralentissement.", "Les fenêtres d'immunité CC sont cruciales. Après un CC, vous gagnez une brève période d'immunité.", "En PvE, les boss de raid ont des seuils de résistance CC.", "En PvP, les chaînes CC sont le cœur du jeu compétitif."]),
        section("endgame-combat", "Considérations de Combat Endgame", ["Les raids d'épreuve introduisent des mécaniques complexes. Les capacités de boss nécessitent un positionnement spécifique.", "Les engagements PvP en monde ouvert nécessitent une conscience du terrain et des routes de fuite.", "La guerre de siège est le sommet du combat d'Aion 2.", "Les patches d'équilibre déplacent régulièrement la meta. Restez à jour."]),
      ],
    }),
    de: articleCopy(guideLabels, "de", 7, {
      eyebrow: "KAMPFSYSTEM",
      title: "Aion 2 Kampfmechanik: Action-Kampf, Skill-Rotationen, Positionierung und Crowd-Control",
      description: "Meistern Sie Aion 2s Action-Kampfsystem — von Basis-Kombos bis zu fortgeschrittenen CC-Ketten und Endgame-Raids.",
      intro: "Aion 2s Action-Kampfsystem ist eine der größten Veränderungen gegenüber der Tab-Target-Ära von Aion 1.",
      sourceNote: "Basierend auf NCs offizieller Kampfsystem-Dokumentation (September 2026).",
      keywords: ["Aion 2 Kampf-Guide", "Aion 2 Kampfmechanik"],
      sections: [
        section("combat-fundamentals", "Kampf-Grundlagen", ["Aion 2 verwendet ein vollständiges Action-Kampfsystem. Jede Fähigkeit erfordert manuelles Zielen.", "Die Kampf-Schleife dreht sich um drei Phasen: Eröffner, nachhaltige Rotation und Finisher.", "Stamina-Management ist ein kritisches Element."]),
        section("skill-rotation", "Effektive Skill-Rotationen Bauen", ["Ihre Rotation sollte einem Prioritätssystem folgen.", "Skill-Synergie ist der Schlüssel.", "Defensive Cooldowns sollten in Ihre Rotation eingebaut werden."]),
        section("positioning-mobility", "Positionierung und Mobilität", ["Aion 2 belohnt Positionsangriffe. Rücken- und Flankenangriffe verursachen Bonusschaden.", "Mobilitätsfähigkeiten dienen nicht nur zum Schließen von Lücken.", "Kiting ist eine praktikable Kampfstrategie für Fernkampf-Klassen."]),
        section("crowd-control", "Crowd-Control Verstehen", ["Aion 2 hat fünf Haupt-CC-Typen: Betäubung, Niederschlag, Stille, Wurzel und Verlangsamung.", "CC-Immunitätsfenster sind entscheidend.", "Im PvE haben Raid-Bosse CC-Widerstandsschwellen.", "Im PvP sind CC-Ketten der Kern des kompetitiven Spiels."]),
        section("endgame-combat", "Endgame-Kampf Überlegungen", ["Prüfungs-Raids führen komplexe Mechaniken ein.", "Open-World-PvP erfordert andere Fähigkeiten.", "Belagerungskrieg ist der Höhepunkt des Aion 2-Kampfes.", "Balance-Patches verschieben regelmäßig die Meta."]),
      ],
    }),
    es: articleCopy(guideLabels, "es", 7, {
      eyebrow: "SISTEMA DE COMBATE",
      title: "Mecánicas de Combate de Aion 2: Combate Action, Rotaciones, Posicionamiento y CC",
      description: "Domina el sistema de combate action de Aion 2 — desde combos básicos hasta cadenas CC avanzadas y mecánicas de raids.",
      intro: "El sistema de combate action de Aion 2 es uno de los mayores cambios respecto a la era tab-target de Aion 1.",
      sourceNote: "Basado en la documentación oficial del sistema de combate de NC (septiembre 2026).",
      keywords: ["Guía combate Aion 2", "Mecánicas combate Aion 2"],
      sections: [
        section("combat-fundamentals", "Fundamentos del Combate", ["Aion 2 usa un sistema de combate action completo donde cada habilidad requiere apuntado manual.", "El ciclo de combate gira en torno a tres fases: apertura, rotación sostenida y finalizador.", "La gestión de estamina es un elemento crítico."]),
        section("skill-rotation", "Construir Rotaciones Efectivas", ["Tu rotación debe seguir un sistema de prioridad.", "La sinergia de habilidades es clave.", "Los cooldowns defensivos deben integrarse en tu rotación."]),
        section("positioning-mobility", "Posicionamiento y Movilidad", ["Aion 2 recompensa los ataques posicionales.", "Las habilidades de movilidad no son solo para cerrar distancias.", "El kiting es una estrategia viable para clases a distancia."]),
        section("crowd-control", "Entendiendo el Control de Masas", ["Aion 2 tiene cinco tipos principales de CC: stun, knockdown, silence, root y slow.", "Las ventanas de inmunidad CC son cruciales.", "En PvE, los bosses de raid tienen umbrales de resistencia CC.", "En PvP, las cadenas CC son el núcleo del juego competitivo."]),
        section("endgame-combat", "Consideraciones de Combate Endgame", ["Las raids introducen mecánicas complejas.", "El PvP en mundo abierto requiere habilidades diferentes.", "La guerra de asedio es la cúspide del combate de Aion 2.", "Los parches de balance cambian regularmente la meta."]),
      ],
    }),
    ja: articleCopy(guideLabels, "ja", 7, {
      eyebrow: "戦闘システム",
      title: "Aion 2 戦闘メカニクス深層ガイド：アクション戦闘、スキルローテーション、ポジショニング、CC",
      description: "Aion 2のアクション戦闘システムをマスター——基本コンボから上級CCチェーン、レイドメカニクスまで。",
      intro: "Aion 2のアクション戦闘システムはAion 1のタブターゲット時代からの最大の変化の一つです。",
      sourceNote: "NC公式戦闘システム文書基準（2026年9月）。",
      keywords: ["Aion 2 戦闘ガイド", "Aion 2 戦闘メカニクス"],
      sections: [
        section("combat-fundamentals", "戦闘の基礎", ["Aion 2はフルアクション戦闘システムで、全スキルに手動エイミングが必要。", "戦闘ループは3フェーズ：オープナー、持続ローテーション、フィニッシャー。", "スタミナ管理が重要要素。"]),
        section("skill-rotation", "効果的なスキルローテーション構築", ["ローテーションは優先度システムに従うべき。", "スキルシナジーが鍵。", "防御クールダウンはローテーションに組み込むべき。"]),
        section("positioning-mobility", "ポジショニングと機動性", ["Aion 2は位置取り攻撃を報酬。背面や側面攻撃がボーナスダメージ。", "機動スキルはギャップを埋めるだけではない。", "カイティングは遠距離クラスに有効な戦略。"]),
        section("crowd-control", "クラウドコントロールの理解", ["Aion 2には5つの主要CCタイプ：スタン、ノックダウン、サイレンス、ルート、スロウ。", "CC免疫ウィンドウが重要。", "PvEではレイドボスにCC抵抗閾値。", "PvPではCCチェーンが競技プレイの核心。"]),
        section("endgame-combat", "エンドゲーム戦闘の考慮事項", ["試練レイドは複雑なメカニクスを導入。", "オープンワールドPvPは異なるスキルを要求。", "攻城戦はAion 2戦闘の頂点。", "バランスパッチが定期的にメタを変更。"]),
      ],
    }),
    "pt-br": articleCopy(guideLabels, "pt-br", 7, {
      eyebrow: "SISTEMA DE COMBATE",
      title: "Mecânicas de Combate do Aion 2: Combate Action, Rotações, Posicionamento e CC",
      description: "Domine o sistema de combate action do Aion 2 — de combos básicos a cadeias CC avançadas e mecânicas de raids.",
      intro: "O sistema de combate action do Aion 2 é uma das maiores mudanças da era tab-target do Aion 1.",
      sourceNote: "Baseado na documentação oficial do sistema de combate da NC (setembro 2026).",
      keywords: ["Guia combate Aion 2", "Mecânicas combate Aion 2"],
      sections: [
        section("combat-fundamentals", "Fundamentos do Combate", ["Aion 2 usa um sistema de combate action completo. Cada habilidade requer apontamento manual.", "O ciclo de combate gira em torno de três fases: abertura, rotação sustentada e finalizador.", "Gerenciamento de estamina é um elemento crítico."]),
        section("skill-rotation", "Construindo Rotações Eficazes", ["Sua rotação deve seguir um sistema de prioridade.", "Sinergia de habilidades é a chave.", "Cooldowns defensivos devem ser integrados à sua rotação."]),
        section("positioning-mobility", "Posicionamento e Mobilidade", ["Aion 2 recompensa ataques posicionais.", "Habilidades de mobilidade não são apenas para fechar gaps.", "Kiting é uma estratégia viável para classes à distância."]),
        section("crowd-control", "Entendendo Crowd Control", ["Aion 2 tem cinco tipos principais de CC: stun, knockdown, silence, root e slow.", "Janelas de imunidade CC são cruciais.", "Em PvE, bosses de raid têm limiares de resistência CC.", "Em PvP, cadeias CC são o núcleo do jogo competitivo."]),
        section("endgame-combat", "Considerações de Combate Endgame", ["Raids de trial introduzem mecânicas complexas.", "PvP em mundo aberto requer habilidades diferentes.", "Guerra de cerco é o ápice do combate do Aion 2.", "Patches de balance mudam regularmente a meta."]),
      ],
    }),
    ru: articleCopy(guideLabels, "ru", 7, {
      eyebrow: "БОЕВАЯ СИСТЕМА",
      title: "Боевые Механики Aion 2: Экшн-Бой, Ротации, Позиционирование и Контроль",
      description: "Освойте экшн-боевую систему Aion 2 — от базовых комбо до продвинутых CC-цепочек и рейдовых механик.",
      intro: "Экшн-боевая система Aion 2 — одно из крупнейших изменений от эры таб-таргета Aion 1.",
      sourceNote: "На основе официальной документации боевой системы NC (сентябрь 2026).",
      keywords: ["Гайд бой Aion 2", "Боевые механики Aion 2"],
      sections: [
        section("combat-fundamentals", "Основы Боя", ["Aion 2 использует полную экшн-боевую систему. Каждая способность требует ручного прицеливания.", "Боевой цикл вращается вокруг трёх фаз: открывающий, устойчивая ротация и финишер.", "Управление выносливостью — критический элемент."]),
        section("skill-rotation", "Построение Эффективных Ротаций", ["Ваша ротация должна следовать системе приоритетов.", "Синергия навыков — ключ.", "Защитные кулдауны должны быть вплетены в вашу ротацию."]),
        section("positioning-mobility", "Позиционирование и Мобильность", ["Aion 2 награждает позиционные атаки.", "Навыки мобильности не только для закрытия разрывов.", "Кайтинг — жизнеспособная стратегия для классов дальнего боя."]),
        section("crowd-control", "Понимание Контроля Толпы", ["Aion 2 имеет пять основных типов КТ: оглушение, нокдаун, молчание, корень и замедление.", "Окна иммунитета КТ критичны.", "В PvE у рейд-боссов есть пороги сопротивления КТ.", "В PvP КТ-цепочки — ядро соревновательной игры."]),
        section("endgame-combat", "Соображения Эндшпиль-Боя", ["Рейдовые испытания вводят сложные механики.", "Открытый мир PvP требует других навыков.", "Осадная война — вершина боя Aion 2.", "Патчи баланса регулярно сдвигают мету."]),
      ],
    }),
    ko: articleCopy(guideLabels, "ko", 7, {
      eyebrow: "전투 시스템",
      title: "Aion 2 전투 메커니즘 심층 분석: 액션 전투, 스킬 로테이션, 포지셔닝, CC",
      description: "Aion 2의 액션 전투 시스템을 마스터 — 기본 콤보부터 고급 CC 체인, 레이드 메커니즘까지.",
      intro: "Aion 2의 액션 전투 시스템은 Aion 1의 탭 타겟 시대 이후 가장 큰 변화 중 하나입니다.",
      sourceNote: "NC 공식 전투 시스템 문서 기준 (2026년 9월).",
      keywords: ["Aion 2 전투 가이드", "Aion 2 전투 메커니즘"],
      sections: [
        section("combat-fundamentals", "전투 기본", ["Aion 2는 풀 액션 전투 시스템을 사용합니다. 모든 스킬에 수동 조준이 필요합니다.", "전투 루프는 3단계: 오프너, 지속 로테이션, 피니셔.", "스태미나 관리가 핵심 요소입니다."]),
        section("skill-rotation", "효과적인 스킬 로테이션 구축", ["로테이션은 우선순위 시스템을 따라야 합니다.", "스킬 시너지가 핵심입니다.", "방어 쿨다운은 로테이션에 짜여져야 합니다."]),
        section("positioning-mobility", "포지셔닝과 기동성", ["Aion 2는 위치 공격에 보상을 줍니다.", "기동 스킬은 갭을 좁히는 것만이 아닙니다.", "카이팅은 원거리 클래스에 유효한 전략입니다."]),
        section("crowd-control", "군중 제어 이해", ["Aion 2는 5가지 주요 CC 타입: 스턴, 넉다운, 침묵, 속박, 감속.", "CC 면역 창이 중요합니다.", "PvE에서 레이드 보스는 CC 저항 임계값이 있습니다.", "PvP에서 CC 체인은 경쟁 플레이의 핵심입니다."]),
        section("endgame-combat", "엔드게임 전투 고려사항", ["시련 레이드는 복잡한 메커니즘을 도입합니다.", "오픈 월드 PvP는 다른 스킬을 요구합니다.", "공성전은 Aion 2 전투의 정점입니다.", "밸런스 패치가 정기적으로 메타를 변경합니다."]),
      ],
    }),
    "zh-hant": articleCopy(guideLabels, "zh-hant", 7, {
      eyebrow: "戰鬥系統",
      title: "Aion 2 戰鬥機制深度解析：動作戰鬥、技能循環、走位與控制",
      description: "掌握 Aion 2 的動作戰鬥系統——從基礎連招和走位到高級控制鏈和後期副本機制。",
      intro: "Aion 2 的動作戰鬥系統是與 Aion 1 鎖定目標時代最大的變化之一。",
      sourceNote: "基於 NC 官方戰鬥系統文檔和韓服機制（截至 2026 年 9 月）。",
      keywords: ["Aion 2 戰鬥攻略", "Aion 2 戰鬥機制"],
      sections: [
        section("combat-fundamentals", "戰鬥基礎：動作戰鬥循環", ["Aion 2 使用全面動作戰鬥系統，每個技能需要手動瞄準。", "戰鬥循環圍繞三個階段：開場、持續循環和終結。", "體力管理是關鍵要素。"]),
        section("skill-rotation", "構建有效技能循環", ["循環應遵循優先級系統而非固定順序。", "技能協同是關鍵。", "防禦冷卻應編入循環。"]),
        section("positioning-mobility", "走位與機動性", ["Aion 2 獎勵位置攻擊。背刺和側翼攻擊有額外傷害。", "機動技能不僅用於縮短距離。", "風箏對遠程職業是可行策略。"]),
        section("crowd-control", "理解控制", ["Aion 2 有五種主要 CC：眩暈、擊倒、沉默、定身和減速。", "CC 免疫窗口至關重要。", "PvE 團隊副本 Boss 有 CC 抗性閾值。", "PvP 中 CC 鏈是競技核心。"]),
        section("endgame-combat", "後期戰鬥注意事項", ["試煉副本引入複雜機制。", "開放世界 PvP 需要不同技能。", "攻城戰是 Aion 2 戰鬥的巔峰。", "平衡补丁定期改變 meta。"]),
      ],
    }),
  },
};
