import { articleCopy, guideLabels, localizations, publishedVerified, section } from "./trending-september-9-shared";
import type { ContentEntry, ContentHeroImage, ContentSource } from "./content-registry";

/* ARTICLE 4 — [True] Genesis / Nemesis Dragon Lord gear guide: Tier 4 crafted weapons and guarders via inheritance crafting */

const invenSource: ContentSource = {
  id: "inven-aion2-snowfield-preview-2026-09-08",
  kind: "third-party",
  publisher: "Inven Global",
  label: "Aion 2 Unveils New Raid Content 'Snowfield of Grief' (True Azure/Extinction Dragon gear)",
  url: "https://www.invenglobal.com/articles/25688/aion-2-unveils-new-raid-content-snowfield-of-grief",
  publishedAt: "2026-09-08",
  retrievedAt: "2026-09-09",
  verifiedAt: "2026-09-09",
  localizations: localizations({
    "zh-hans": "Aion 2 公布新团队副本「Snowfield of Grief」（True 蓝龙/灭绝龙装备）",
    en: "Aion 2 Unveils New Raid Content 'Snowfield of Grief' (True Azure/Extinction Dragon gear)",
    fr: "Aion 2 dévoile le raid « Snowfield of Grief » (équipement True Azure/Extinction Dragon)",
    de: "Aion 2 enthüllt Raid „Snowfield of Grief“ (True Azure/Extinction Dragon Ausrüstung)",
    es: "Aion 2 desvela el raid «Snowfield of Grief» (equipo True Azure/Extinction Dragon)",
    ja: "Aion 2 新レイド「Snowfield of Grief」公開（True Azure/Extinction Dragon装備）",
    "pt-br": "Aion 2 revela o raid 'Snowfield of Grief' (equipamento True Azure/Extinction Dragon)",
    ru: "Aion 2 анонсирует рейд «Snowfield of Grief» (экипировка True Azure/Extinction Dragon)",
    ko: "아이온2 신규 레이드 '슬픔의 설원' 공개 (True 아주르/멸절 드래곤 장비)",
    "zh-hant": "Aion 2 公布新團隊副本「Snowfield of Grief」（True 藍龍/滅絕龍裝備）",
  }, "https://www.invenglobal.com/articles/25688/aion-2-unveils-new-raid-content-snowfield-of-grief"),
};

const officialPatchSource: ContentSource = {
  id: "aion2-official-update-2026-09-09",
  kind: "official",
  publisher: "NC Corporation",
  label: "AION 2 Update Notes — September 9, 2026 ([True] Genesis/Nemesis Dragon Lord gear)",
  url: "https://aion2.plaync.com/ko-kr/board/update/view?articleId=6aa062386b722c561dc6a46c",
  publishedAt: "2026-09-09",
  retrievedAt: "2026-09-09",
  verifiedAt: "2026-09-09",
  localizations: localizations({
    "zh-hans": "AION 2 更新说明——2026-09-09（[True] 创世/灭绝龙神装备）",
    en: "AION 2 Update Notes — September 9, 2026 ([True] Genesis/Nemesis Dragon Lord gear)",
    fr: "Notes de mise à jour AION 2 — 9 septembre 2026 (équipement [True] Genesis/Nemesis Dragon Lord)",
    de: "AION-2-Update-Notizen — 9. September 2026 ([True] Genesis/Nemesis Dragon Lord Ausrüstung)",
    es: "Notas de actualización de AION 2 — 9 de septiembre de 2026 (equipo [True] Genesis/Nemesis Dragon Lord)",
    ja: "AION 2 アップデートノート——2026-09-09（[True] 창세/멸절 드래곤 로드装備）",
    "pt-br": "Notas de atualização do AION 2 — 9 de setembro de 2026 (equipamento [True] Genesis/Nemesis Dragon Lord)",
    ru: "Заметки об обновлении AION 2 — 9 сентября 2026 (экипировка [True] Genesis/Nemesis Dragon Lord)",
    ko: "AION 2 업데이트 노트 — 2026-09-09 ([True] 창세/멸절 드래곤 로드 장비)",
    "zh-hant": "AION 2 更新說明——2026-09-09（[True] 創世/滅絕龍神裝備）",
  }, "https://aion2.plaync.com/ko-kr/board/update/view?articleId=6aa062386b722c561dc6a46c"),
};

const gHero: ContentHeroImage = {
  src: "https://blogfiles.ncsoft.net/news/af7330da-4ff6-4b58-aece-400e6061a3be.jpg",
  width: 1200, height: 630,
  credit: "NC Corporation",
  sourceUrl: "https://aion2.plaync.com/en-us/",
  rights: "linked-official-media",
  translations: {
    "zh-hans": { alt: "Aion 2 [True] 龙神装备指南横幅", caption: "9/9 韩服更新新增「[True] 创世龙神 / [True] 灭绝龙神」武器与守护者：由闪耀版经传承制作升级，可延展效果作为默认属性且不占用灵魂刻印位。" },
    en: { alt: "Aion 2 [True] Dragon Lord gear guide banner", caption: "The September 9 Korean update adds '[True] Genesis Dragon Lord' and '[True] Nemesis Dragon Lord' weapons and guarders, upgraded from the Splendent versions via inheritance crafting, with the extendable effect as a default stat that does not occupy a Soul Imprint option." },
    fr: { alt: "Bannière du guide d'équipement [True] Dragon Lord d'Aion 2", caption: "La mise à jour coréenne du 9 septembre ajoute les armes et gardes « [True] Genesis / Nemesis Dragon Lord », issues des versions Splendent par artisanat d'héritage, l'effet extensible étant un statut par défaut sans occuper d'option Soul Imprint." },
    de: { alt: "Banner zum [True] Dragon Lord Ausrüstungs-Leitfaden von Aion 2", caption: "Das koreanische Update vom 9. September fügt „[True] Genesis/Nemesis Dragon Lord“-Waffen und -Garder hinzu, per Vererbungs-Handwerk aus den Splendent-Versionen, mit erweiterbarem Effekt als Standard-Stat ohne Soul-Imprint-Platz." },
    es: { alt: "Banner de la guía de equipo [True] Dragon Lord de Aion 2", caption: "La actualización coreana del 9 de septiembre añade armas y guardas «[True] Genesis/Nemesis Dragon Lord», mejoradas desde las versiones Splendent por artesanía de herencia, con efecto extensible como estadística por defecto sin ocupar opción de Soul Imprint." },
    ja: { alt: "Aion 2 [True]ドラゴンロード装備ガイドバナー", caption: "9/9韓国アップデートで「[True]창세/멸절 드래곤 로드」武器・ガーダー追加：Splendent版から継承制作で昇格、拡張効果はソウル刻印を占有しないデフォルトステータス。" },
    "pt-br": { alt: "Banner do guia de equipamento [True] Dragon Lord do Aion 2", caption: "A atualização coreana de 9 de setembro adiciona armas e guardas '[True] Genesis/Nemesis Dragon Lord', melhoradas das versões Splendent via artesanato de herança, com efeito extensível como stat padrão sem ocupar opção de Soul Imprint." },
    ru: { alt: "Баннер гайда по экипировке [True] Dragon Lord в Aion 2", caption: "Корейское обновление 9 сентября добавляет оружие и гарды «[True] Genesis/Nemesis Dragon Lord», улучшаемые из Splendent-версий наследованием, с расширяемым эффектом как базовым статом без слота Soul Imprint." },
    ko: { alt: "Aion 2 [True] 드래곤 로드 장비 가이드 배너", caption: "9/9 한국 업데이트로 '[True] 창세/멸절 드래곤 로드' 무기·가더 추가: Splendent 버전에서 계승 제작으로 승급, 확장 효과는 소울 각인을 차지하지 않는 기본 스탯으로 제공." },
    "zh-hant": { alt: "Aion 2 [True] 龍神裝備指南橫幅", caption: "9/9 韓服更新新增「[True] 創世龍神 / [True] 滅絕龍神」武器與守護者：由閃耀版經傳承製作升級，可延展效果作為預設屬性且不佔用靈魂刻印位。" },
  },
};

export const trendingSeptember9Article4: ContentEntry = {
  section: "guides",
  slug: "aion-2-true-dragon-lord-gear-guide",
  schemaType: "Article",
  publishedAt: "2026-09-09",
  updatedAt: "2026-09-09",
  readingMinutes: 5,
  publication: publishedVerified,
  sources: [invenSource, officialPatchSource],
  heroImage: gHero,
  related: [
    { kind: "content", section: "guides", slug: "aion-2-endgame-gear-guide" },
    { kind: "content", section: "guides", slug: "aion-2-gear-enhancement-guide" },
    { kind: "content", section: "guides", slug: "aion-2-early-game-free-gear-progression-guide" },
    { kind: "content", section: "guides", slug: "aion-2-great-rebalance-patch-guide" },
  ],
  translations: {
    en: articleCopy(guideLabels, "en", 5, {
      eyebrow: "GEAR GUIDE",
      title: "Aion 2 [True] Genesis / Nemesis Dragon Lord Gear Guide: Tier 4 Weapons and Guarders via Inheritance Crafting",
      description: "How the new [True] Genesis and Nemesis Dragon Lord weapons and guarders work: upgraded from Splendent versions via inheritance crafting, with Liberated White Night gear as materials and the extendable effect as a default stat",
      intro: "The September 9 Korean update adds the next step of crafted Tier 4 gear: '[True] Genesis Dragon Lord' and '[True] Nemesis Dragon Lord' weapons and guarders. This guide covers how they are made from the Splendent versions, what the stepped growth structure means, and why the extendable effect matters.",
      sourceNote: "Based on the official Korean update notes of September 9, 2026 and Inven Global's September 8, 2026 preview report (both retrieved September 9, 2026). Note that English outlets translate the item names differently — Inven uses 'True Azure Dragon / True Extinction Dragon' and 'Shining' for the Splendent versions.",
      keywords: ["Aion 2 True Genesis Dragon Lord", "Aion 2 True Nemesis Dragon Lord", "Aion 2 Tier 4 weapons guarders", "Aion 2 inheritance crafting gear", "Aion 2 Liberated White Night materials"],
      sections: [
        section("what-is-true", "What the [True] Dragon Lord Gear Is", ["The update adds blueprints for '[True] Genesis Dragon Lord' and '[True] Nemesis Dragon Lord' weapons and guarders — the latest step of crafted Tier 4 gear for the Korean service, alongside the 'Liberated White Night' (Tier 4) series that drops from the new raid on Hard.", "The names vary by outlet: Inven Global renders them 'True Azure Dragon / True Extinction Dragon'. Both refer to the same crafted tier-4 set added in the September 9 patch."]),
        section("succession-crafting", "Succession Crafting From the Splendent Versions", ["The core upgrade path is inheritance crafting: a new blueprint converts 'Splendent Genesis Dragon Lord' / 'Splendent Nemesis Dragon Lord' weapons and guarders into their [True] versions ('Shining Azure Dragon / Extinction Dragon' in Inven's naming).", "This is a stepped growth structure — you keep your existing progression line and push it one tier higher rather than restarting. One condition to note: the September 9 patch adds an enhancement-level requirement to inheritance materials, so you will need your source gear enhanced to a certain level before it can be used."]),
        section("white-night-materials", "Liberated White Night as Crafting Materials", ["'Liberated White Night' weapons and guarders — the raid drops — can be material-converted into crafting materials for the [True] Genesis / Nemesis Dragon Lord weapons and guarders.", "That closes the loop between the new raid and the crafted set: raid for Liberated White Night gear, convert it into materials, and complete your [True] Dragon Lord pieces."]),
        section("extendable-effect", "The Extendable Effect, Without the Soul Imprint Cost", ["One of the most valuable details: the extendable effect on the True gear is provided as a default stat, so it does not occupy a Soul Imprint option.", "In practice that means the [True] tier adds a free damage or defense extension on top of your existing build, leaving your Soul Imprint slots free for other choices — a meaningful quality-of-life improvement for endgame min-maxing."]),
        section("planning-notes", "Planning Notes", ["1. Confirm the enhancement-level condition on inheritance materials before you craft; 2. Run the new Sanctuary on the difficulty you can clear for Liberated White Night drops; 3. Convert surplus raid gear into [True] crafting materials; 4. Factor the free extendable effect into your build — you can skip one Soul Imprint option you were reserving for it.", "For global players: this is Korean-service progression. The global launch on October 5 ships a modified Season 1, so treat this guide as the shape of the Tier 4 crafted-gear path you will see later."]),
      ],
    }),
    "zh-hans": articleCopy(guideLabels, "zh-hans", 5, {
      eyebrow: "装备指南",
      title: "Aion 2 [True] 创世/灭绝龙神装备指南：传承制作出 Tier 4 武器与守护者",
      description: "新 [True] 创世龙神/灭绝龙神武器与守护者如何运作：由闪耀版经传承制作升级、Liberated White Night 装备作材料、可延展效果作为默认属性",
      intro: "9 月 9 日韩服更新新增制作 Tier 4 装备的下一步：「[True] 创世龙神」与「[True] 灭绝龙神」武器与守护者。本指南说明如何从闪耀版升级、逐步成长结构的含义，以及可延展效果的价值。",
      sourceNote: "基于 2026 年 9 月 9 日官方韩服更新说明与 Inven Global 2026 年 9 月 8 日预览报道（均于 2026-09-09 抓取）。注意不同英文媒体译名不同——Inven 使用「True Azure Dragon / True Extinction Dragon」，闪耀版称「Shining」。",
      keywords: ["Aion 2 True 创世龙神", "Aion 2 True 灭绝龙神", "Aion 2 Tier 4 武器 守护者", "Aion 2 传承制作 装备", "Aion 2 Liberated White Night 材料"],
      sections: [
        section("what-is-true", "[True] 龙神装备是什么", ["更新新增「[True] 创世龙神」与「[True] 灭绝龙神」武器与守护者的图纸——这是韩服制作 Tier 4 装备的最新一步，与 Hard 难度新副本掉落的「Liberated White Night」（Tier 4）系列并列。", "不同媒体译名不同：Inven Global 写作「True Azure Dragon / True Extinction Dragon」。两者指的都是 9 月 9 日补丁加入的同一套制作 Tier 4 装备。"]),
        section("succession-crafting", "由闪耀版经传承制作升级", ["核心升级路径是传承制作：新图纸将「Splendent 创世龙神 / Splendent 灭绝龙神」武器与守护者转换为 [True] 版（Inven 译名「Shining Azure Dragon / Extinction Dragon」）。", "这是逐步成长结构——保留既有成长线推高一阶而非重来。需注意一点：9 月 9 日补丁为传承材料新增了强化等级条件，源装备需强化到一定等级才能作为材料。"]),
        section("white-night-materials", "Liberated White Night 作材料", ["副本掉落的「Liberated White Night」武器与守护者可材料转换为 [True] 创世/灭绝龙神武器与守护者的制作材料。", "这把新副本与制作套连接起来：刷 Liberated White Night、转换为材料、补齐 [True] 龙神部件。"]),
        section("extendable-effect", "可延展效果，不占灵魂刻印位", ["最有价值的细节之一：True 装备的可延展效果作为默认属性提供，不占用灵魂刻印选项。", "实际意味着 [True] 阶在现有构建之上免费附加伤害/防御延展，灵魂刻印位可留给其他选择——对终局精算玩家是有意义的 QoL 改进。"]),
        section("planning-notes", "规划提示", ["1. 制作前确认传承材料的强化等级条件；2. 打你能通关的难度刷 Liberated White Night；3. 将多余副本装备转换为 [True] 制作材料；4. 把免费可延展效果计入构建——可省掉一个原本留给它的灵魂刻印位。", "对全球玩家：这是韩服成长内容。全球版 10 月 5 日以改良版 Season 1 上线，把本指南视为未来 Tier 4 制作路线的形态。"]),
      ],
    }),
    fr: articleCopy(guideLabels, "fr", 5, {
      eyebrow: "GUIDE ÉQUIPEMENT",
      title: "Guide de l'équipement [True] Genesis / Nemesis Dragon Lord d'Aion 2 : armes et gardes de rang 4 par artisanat d'héritage",
      description: "Comment fonctionnent les armes et gardes [True] Genesis/Nemesis Dragon Lord : améliorées des versions Splendent par artisanat d'héritage, avec le Liberated White Night en matériaux et l'effet extensible en statut par défaut",
      intro: "La mise à jour coréenne du 9 septembre ajoute l'étape suivante de l'équipement de rang 4 fabriqué : les armes et gardes « [True] Genesis Dragon Lord » et « [True] Nemesis Dragon Lord ». Ce guide couvre leur fabrication depuis les versions Splendent, la structure de croissance et l'effet extensible.",
      sourceNote: "Basé sur les notes de mise à jour officielles coréennes du 9 septembre 2026 et le rapport d'Inven Global du 8 septembre 2026 (récupérés le 9 septembre 2026). Les traductions anglaises diffèrent (Inven : True Azure/Extinction Dragon, Shining pour Splendent).",
      keywords: ["Aion 2 True Genesis Dragon Lord", "Aion 2 True Nemesis Dragon Lord", "Aion 2 armes gardes rang 4", "Aion 2 artisanat d'héritage", "Aion 2 Liberated White Night matériaux"],
      sections: [
        section("what-is-true", "L'équipement [True] Dragon Lord", "Le patch ajoute les plans des armes et gardes « [True] Genesis / Nemesis Dragon Lord » — l'étape suivante du rang 4 fabriqué, aux côtés du « Liberated White Night » (rang 4) du raid en Hard. Noms variables : Inven écrit « True Azure/Extinction Dragon »."),
        section("succession-crafting", "Héritage depuis les versions Splendent", "Voie d'amélioration : un plan convertit les « Splendent Genesis/Nemesis Dragon Lord » en versions [True] (Shining chez Inven). Structure de croissance par palier — on conserve sa ligne. Condition : exigence de niveau d'amélioration sur les matériaux d'héritage depuis le patch."),
        section("white-night-materials", "Liberated White Night en matériaux", "Les armes et gardes « Liberated White Night » (drops du raid) se convertissent en matériaux de fabrication [True] Genesis/Nemesis — bouclant la boucle raid ↔ set fabriqué."),
        section("extendable-effect", "L'effet extensible, sans coût Soul Imprint", "L'effet extensible du rang [True] est un statut par défaut : il n'occupe pas d'option Soul Imprint — une extension gratuite de dégâts/défense qui libère vos emplacements."),
        section("planning-notes", "Notes de planification", "1. Vérifiez l'exigence de niveau d'amélioration avant de fabriquer ; 2. Faites le raid à la difficulté que vous pouvez ; 3. Convertissez l'excédent en matériaux ; 4. Comptez l'effet extensible gratuit dans votre build. Pour le global : progression coréenne, arrivée plus tard (Saison 1 modifiée le 5 octobre)."),
      ],
    }),
    de: articleCopy(guideLabels, "de", 5, {
      eyebrow: "AUSRÜSTUNGS-LEITFADEN",
      title: "Leitfaden zu [True] Genesis / Nemesis Dragon Lord Ausrüstung in Aion 2: Tier-4-Waffen und -Garder per Vererbungs-Handwerk",
      description: "Wie die neuen [True] Genesis- und Nemesis-Dragon-Lord-Waffen und -Garder funktionieren: aus Splendent-Versionen per Vererbungs-Handwerk, Liberated White Night als Material, erweiterbarer Effekt als Standard-Stat",
      intro: "Das koreanische Update vom 9. September fügt die nächste Stufe gefertigter Tier-4-Ausrüstung hinzu: „[True] Genesis Dragon Lord“- und „[True] Nemesis Dragon Lord“-Waffen und -Garder. Dieser Leitfaden deckt die Herstellung aus den Splendent-Versionen, die Stufenstruktur und den erweiterbaren Effekt ab.",
      sourceNote: "Basierend auf den offiziellen koreanischen Update-Notizen vom 9. September 2026 und dem Inven-Global-Preview vom 8. September 2026 (abgerufen am 9. September 2026). Englische Namen variieren (Inven: True Azure/Extinction Dragon, Shining für Splendent).",
      keywords: ["Aion 2 True Genesis Dragon Lord", "Aion 2 True Nemesis Dragon Lord", "Aion 2 Tier 4 Waffen Garder", "Aion 2 Vererbungs-Handwerk", "Aion 2 Liberated White Night Material"],
      sections: [
        section("what-is-true", "Die [True] Dragon Lord Ausrüstung", "Das Update fügt Blaupausen für „[True] Genesis/Nemesis Dragon Lord“-Waffen und -Garder hinzu — die nächste Stufe gefertigter Tier-4-Ausrüstung neben der „Liberated White Night“-Serie aus dem neuen Raid auf Hard. Inven: „True Azure/Extinction Dragon“."),
        section("succession-crafting", "Vererbung aus den Splendent-Versionen", "Ein neues Rezept wandelt „Splendent Genesis/Nemesis Dragon Lord“ in die [True]-Versionen (Shining bei Inven). Gestufte Struktur — bestehende Linie wird eine Stufe höher geschoben. Bedingung: Verstärkungsstufen-Anforderung an Vererbungsmaterialien seit dem Patch."),
        section("white-night-materials", "Liberated White Night als Material", "„Liberated White Night“-Waffen und -Garder (Raid-Drops) lassen sich in Materialien für [True] Genesis/Nemesis umwandeln — Raid und Set sind verbunden."),
        section("extendable-effect", "Der erweiterbare Effekt ohne Soul-Imprint-Kosten", "Der erweiterbare Effekt der [True]-Stufe ist ein Standard-Stat: kein Soul-Imprint-Platz belegt — eine kostenlose Schadens-/Verteidigungs-Erweiterung für dein Build."),
        section("planning-notes", "Planungsnotizen", "1. Verstärkungsstufen-Bedingung vor dem Handwerk prüfen; 2. Raid auf machbarer Stufe für Drops laufen; 3. Überschuss in Materialien umwandeln; 4. Kostenlosen Effekt einplanen. Für Global: koreanische Progression, später in modifizierter Season 1 (5. Oktober)."),
      ],
    }),
    es: articleCopy(guideLabels, "es", 5, {
      eyebrow: "GUÍA DE EQUIPO",
      title: "Guía del equipo [True] Genesis / Nemesis Dragon Lord de Aion 2: armas y guardas Tier 4 por artesanía de herencia",
      description: "Cómo funcionan las nuevas armas y guardas [True] Genesis y Nemesis Dragon Lord: mejoradas desde las versiones Splendent por artesanía de herencia, con Liberated White Night como material y el efecto extensible como estadística por defecto",
      intro: "La actualización coreana del 9 de septiembre añade el siguiente paso del equipo Tier 4 fabricado: las armas y guardas «[True] Genesis Dragon Lord» y «[True] Nemesis Dragon Lord». Esta guía cubre su fabricación desde las versiones Splendent, la estructura de crecimiento y el efecto extensible.",
      sourceNote: "Basado en las notas de actualización oficiales coreanas del 9 de septiembre de 2026 y el informe de Inven Global del 8 de septiembre de 2026 (recuperados el 9 de septiembre de 2026). Los nombres en inglés varían (Inven: True Azure/Extinction Dragon, Shining para Splendent).",
      keywords: ["Aion 2 True Genesis Dragon Lord", "Aion 2 True Nemesis Dragon Lord", "Aion 2 armas guardas Tier 4", "Aion 2 artesanía de herencia", "Aion 2 Liberated White Night materiales"],
      sections: [
        section("what-is-true", "El equipo [True] Dragon Lord", "El parche añade planos de armas y guardas «[True] Genesis/Nemesis Dragon Lord» — el siguiente paso del Tier 4 fabricado, junto a la serie «Liberated White Night» (Tier 4) del raid en Hard. Nombres variables: Inven escribe «True Azure/Extinction Dragon»."),
        section("succession-crafting", "Herencia desde las versiones Splendent", "Vía de mejora: un plano convierte «Splendent Genesis/Nemesis Dragon Lord» en versiones [True] (Shining en Inven). Estructura escalonada — se conserva la línea. Condición: requisito de nivel de mejora en materiales de herencia desde el parche."),
        section("white-night-materials", "Liberated White Night como material", "Las armas y guardas «Liberated White Night» (drops del raid) se convierten en materiales de fabricación [True] Genesis/Nemesis — cerrando el ciclo raid ↔ set fabricado."),
        section("extendable-effect", "El efecto extensible, sin coste de Soul Imprint", "El efecto extensible del rango [True] es una estadística por defecto: no ocupa una opción de Soul Imprint — una extensión gratuita de daño/defensa que libera tus ranuras."),
        section("planning-notes", "Notas de planificación", "1. Verifica el requisito de nivel de mejora antes de fabricar; 2. Haz el raid a la dificultad que puedas; 3. Convierte el excedente en materiales; 4. Cuenta el efecto extensible gratis en tu build. Para el global: progresión coreana, llegará después (Temporada 1 modificada el 5 de octubre)."),
      ],
    }),
    ja: articleCopy(guideLabels, "ja", 5, {
      eyebrow: "装備ガイド",
      title: "Aion 2 [True] 創世/滅絶ドラゴンロード装備ガイド：継承制作でTier 4武器・ガーダーを",
      description: "新[True]創世/滅絶ドラゴンロード武器・ガーダーの仕組み：Splendent版から継承制作で昇格、Liberated White Nightを素材に、拡張効果はデフォルトステータスとして",
      intro: "9月9日の韓国アップデートで、制作Tier 4装備の次段階「[True] 創世ドラゴンロード」「[True] 滅絶ドラゴンロード」武器・ガーダーが追加されました。本ガイドはSplendent版からの製作、段階的成長構造、拡張効果の価値を解説します。",
      sourceNote: "2026年9月9日付公式韓国アップデートノートとInven Global 2026年9月8日付プレビュー（いずれも2026-09-09取得）に基づきます。英語メディアで名称表記が異なります（Inven: True Azure/Extinction Dragon、Splendent=Shining）。",
      keywords: ["Aion 2 True 創世ドラゴンロード", "Aion 2 True 滅絶ドラゴンロード", "Aion 2 Tier 4 武器 ガーダー", "Aion 2 継承制作", "Aion 2 Liberated White Night 素材"],
      sections: [
        section("what-is-true", "[True] ドラゴンロード装備とは", "アップデートで「[True] 創世ドラゴンロード」「[True] 滅絶ドラゴンロード」武器・ガーダーの設計図が追加されました——新レイドHardでドロップする「Liberated White Night」（Tier 4）シリーズと並ぶ、制作Tier 4の最新段階です。", "メディアにより表記が異なります：Inven Globalは「True Azure Dragon / True Extinction Dragon」と表記。どちらも9月9日パッチの同じ制作Tier 4セットを指します。"),
        section("succession-crafting", "Splendent版からの継承制作", "核心は継承制作です：新設計図で「Splendent 創世/滅絶ドラゴンロード」武器・ガーダーを[True]版に変換します（Inven表記ではShining Azure/Extinction Dragon）。", "段階的成長構造なので、既存の成長ラインを維持したまま一段階押し上げます。注意点：9月9日パッチで継承素材に強化レベル条件が追加され、一定レベルまで強化した装備が素材として必要です。"),
        section("white-night-materials", "Liberated White Nightを素材に", "レイドドロップの「Liberated White Night」武器・ガーダーは、[True] 創世/滅絶ドラゴンロードの製作素材に素材変換できます。", "新レイドと制作セットがつながります：Liberated White Nightを集め、素材変換し、[True]パーツを完成させます。"),
        section("extendable-effect", "拡張効果——ソウル刻印枠を消費しない", "最も価値ある詳細の一つ：True装備の拡張効果はデフォルトステータスとして付与され、ソウル刻印オプションを占有しません。", "既存ビルドの上に無料のダメージ/防御拡張が乗り、刻印枠は他に使えます——エンドゲームの最適化における実質的なQoL改善です。"),
        section("planning-notes", "計画ノート", "1. 製作前に継承素材の強化レベル条件を確認; 2. クリア可能な難易度でLiberated White Nightを集める; 3. 余剰レイド装備を[True]素材に変換; 4. 無料の拡張効果をビルドに組み込む——刻印枠を1つ節約できます。グローバルは10月5日に改良版シーズン1で開始し、この内容は後日到来します。"),
      ],
    }),
    "pt-br": articleCopy(guideLabels, "pt-br", 5, {
      eyebrow: "GUIA DE EQUIPAMENTO",
      title: "Guia do equipamento [True] Genesis / Nemesis Dragon Lord do Aion 2: armas e guardas Tier 4 por artesanato de herança",
      description: "Como funcionam as novas armas e guardas [True] Genesis e Nemesis Dragon Lord: melhoradas das versões Splendent via artesanato de herança, com Liberated White Night como material e o efeito extensível como stat padrão",
      intro: "A atualização coreana de 9 de setembro adiciona o próximo passo do equipamento Tier 4 fabricado: as armas e guardas '[True] Genesis Dragon Lord' e '[True] Nemesis Dragon Lord'. Este guia cobre a fabricação a partir das versões Splendent, a estrutura escalonada e o efeito extensível.",
      sourceNote: "Baseado nas notas de atualização oficiais coreanas de 9 de setembro de 2026 e no relatório de preview da Inven Global de 8 de setembro de 2026 (recuperados em 9 de setembro de 2026). Os nomes em inglês variam (Inven: True Azure/Extinction Dragon, Shining para Splendent).",
      keywords: ["Aion 2 True Genesis Dragon Lord", "Aion 2 True Nemesis Dragon Lord", "Aion 2 armas guardas Tier 4", "Aion 2 artesanato de herança", "Aion 2 Liberated White Night materiais"],
      sections: [
        section("what-is-true", "O equipamento [True] Dragon Lord", "O patch adiciona planos de armas e guardas '[True] Genesis/Nemesis Dragon Lord' — o próximo passo do Tier 4 fabricado, ao lado da série 'Liberated White Night' (Tier 4) do raid no Hard. Nomes variáveis: Inven escreve 'True Azure/Extinction Dragon'."),
        section("succession-crafting", "Herança a partir das versões Splendent", "Via de melhoria: um plano converte 'Splendent Genesis/Nemesis Dragon Lord' em versões [True] (Shining na Inven). Estrutura escalonada — mantém-se a linha. Condição: requisito de nível de aprimoramento em materiais de herança desde o patch."),
        section("white-night-materials", "Liberated White Night como material", "As armas e guardas 'Liberated White Night' (drops do raid) se convertem em materiais de fabricação [True] Genesis/Nemesis — fechando o ciclo raid ↔ set fabricado."),
        section("extendable-effect", "O efeito extensível, sem custo de Soul Imprint", "O efeito extensível do nível [True] é um stat padrão: não ocupa uma opção de Soul Imprint — uma extensão gratuita de dano/defesa que libera seus slots."),
        section("planning-notes", "Notas de planejamento", "1. Verifique o requisito de nível de aprimoramento antes de fabricar; 2. Faça o raid na dificuldade que conseguir; 3. Converta o excedente em materiais; 4. Conte o efeito extensível grátis no seu build. Para o global: progressão coreana, chega depois (Temporada 1 modificada em 5 de outubro)."),
      ],
    }),
    ru: articleCopy(guideLabels, "ru", 5, {
      eyebrow: "ГАЙД ПО ЭКИПИРОВКЕ",
      title: "Гайд по экипировке [True] Genesis / Nemesis Dragon Lord в Aion 2: оружие и гарды Tier 4 через наследование",
      description: "Как работают новые оружие и гарды [True] Genesis и Nemesis Dragon Lord: улучшаются из Splendent-версий наследованием, с Liberated White Night в качестве материала и расширяемым эффектом как базовым статом",
      intro: "Корейское обновление 9 сентября добавляет следующую ступень крафтовой экипировки Tier 4: оружие и гарды «[True] Genesis Dragon Lord» и «[True] Nemesis Dragon Lord». Гайд охватывает изготовление из Splendent-версий, ступенчатую структуру и расширяемый эффект.",
      sourceNote: "На основе официальных корейских заметок об обновлении от 9 сентября 2026 г. и превью Inven Global от 8 сентября 2026 г. (получены 9 сентября 2026 г.). Английские названия различаются (Inven: True Azure/Extinction Dragon, Shining для Splendent).",
      keywords: ["Aion 2 True Genesis Dragon Lord", "Aion 2 True Nemesis Dragon Lord", "Aion 2 оружие гарды Tier 4", "Aion 2 наследование экипировки", "Aion 2 Liberated White Night материалы"],
      sections: [
        section("what-is-true", "Экипировка [True] Dragon Lord", "Патч добавляет чертежи оружия и гардов «[True] Genesis/Nemesis Dragon Lord» — следующую ступень крафтового Tier 4 рядом с серией «Liberated White Night» (Tier 4) из рейда на Hard. Названия различаются: Inven пишет «True Azure/Extinction Dragon»."),
        section("succession-crafting", "Наследование из Splendent-версий", "Путь улучшения: чертёж конвертирует «Splendent Genesis/Nemesis Dragon Lord» в [True]-версии (Shining у Inven). Ступенчатая структура — линия сохраняется. Условие: требование уровня улучшения у материалов наследования с патча."),
        section("white-night-materials", "Liberated White Night как материал", "Оружие и гарды «Liberated White Night» (дроп рейда) конвертируются в материалы для [True] Genesis/Nemesis — рейд и крафтовый сет замыкаются."),
        section("extendable-effect", "Расширяемый эффект без затрат Soul Imprint", "Расширяемый эффект уровня [True] — базовый стат: он не занимает слот Soul Imprint — бесплатное расширение урона/защиты, освобождающее слоты."),
        section("planning-notes", "Заметки по планированию", "1. Проверьте требование уровня улучшения перед крафтом; 2. Проходите рейд на доступной сложности; 3. Конвертируйте излишки в материалы; 4. Учтите бесплатный эффект в билде. Для глобала: корейская прогрессия, появится позже (модифицированный Сезон 1, 5 октября)."),
      ],
    }),
    ko: articleCopy(guideLabels, "ko", 5, {
      eyebrow: "장비 가이드",
      title: "아이온2 [True] 창세/멸절 드래곤 로드 장비 가이드: 계승 제작으로 Tier 4 무기·가더를",
      description: "신규 [True] 창세/멸절 드래곤 로드 무기·가더의 작동 방식: Splendent 버전에서 계승 제작으로 승급, Liberated White Night를 재료로, 확장 효과는 기본 스탯으로",
      intro: "9월 9일 한국 업데이트로 제작 Tier 4 장비의 다음 단계인 '[True] 창세 드래곤 로드'와 '[True] 멸절 드래곤 로드' 무기·가더가 추가됐습니다. 이 가이드는 Splendent 버전에서의 제작, 단계적 성장 구조, 확장 효과의 가치를 다룹니다.",
      sourceNote: "2026년 9월 9일자 공식 한국 업데이트 노트와 Inven Global 2026년 9월 8일자 프리뷰 보도(모두 2026-09-09 확인)를 기반으로 했습니다. 영어 매체마다 표기가 다릅니다(Inven: True Azure/Extinction Dragon, Splendent=Shining).",
      keywords: ["아이온2 True 창세 드래곤 로드", "아이온2 True 멸절 드래곤 로드", "아이온2 Tier 4 무기 가더", "아이온2 계승 제작", "아이온2 해방된 화이트 나이트 재료"],
      sections: [
        section("what-is-true", "[True] 드래곤 로드 장비란", "업데이트로 '[True] 창세 드래곤 로드'와 '[True] 멸절 드래곤 로드' 무기·가더 설계도가 추가됐습니다——새 레이드 Hard에서 드랍되는 '해방된 화이트 나이트'(Tier 4) 시리즈와 나란히 서는, 제작 Tier 4의 최신 단계입니다.", "매체별 표기가 다릅니다: Inven Global은 'True Azure Dragon / True Extinction Dragon'으로 표기합니다. 둘 다 9월 9일 패치의 동일한 제작 Tier 4 세트를 가리킵니다."),
        section("succession-crafting", "Splendent 버전에서 계승 제작", "핵심 승급 경로는 계승 제작입니다: 새 설계도로 'Splendent 창세/멸절 드래곤 로드' 무기·가더를 [True] 버전으로 전환합니다(Inven 표기: Shining Azure/Extinction Dragon).", "단계적 성장 구조라 기존 성장선을 유지한 채 한 단계 끌어올립니다. 주의점: 9월 9일 패치부터 계승 재료에 강화 레벨 조건이 추가되어, 일정 레벨까지 강화한 장비가 재료로 필요합니다."),
        section("white-night-materials", "해방된 화이트 나이트를 재료로", "레이드 드랍인 '해방된 화이트 나이트' 무기·가더는 [True] 창세/멸절 드래곤 로드 무기·가더의 제작 재료로 재료 변환할 수 있습니다.", "이로써 새 레이드와 제작 세트가 연결됩니다: 해방된 화이트 나이트를 모아 재료로 변환하고 [True] 부위를 완성합니다."),
        section("extendable-effect", "확장 효과——소울 각인 칸을 차지하지 않음", "가장 가치 있는 디테일 중 하나: True 장비의 확장 효과는 기본 스탯으로 제공되어 소울 각인 옵션을 차지하지 않습니다.", "기존 빌드 위에 무료 피해/방어 확장이 얹히고, 각인 칸은 다른 선택에 쓸 수 있습니다——엔드게임 세팅에서 실질적인 QoL 개선입니다."),
        section("planning-notes", "계획 노트", "1. 제작 전에 계승 재료의 강화 레벨 조건을 확인; 2. 클리어 가능한 난이도로 해방된 화이트 나이트를 모으기; 3. 남는 레이드 장비를 [True] 제작 재료로 변환; 4. 무료 확장 효과를 빌드에 반영——소울 각인 칸 하나를 아낄 수 있습니다. 글로벌은 10월 5일 수정판 시즌 1로 시작하며, 이 내용은 나중에 도착합니다."),
      ],
    }),
    "zh-hant": articleCopy(guideLabels, "zh-hant", 5, {
      eyebrow: "裝備指南",
      title: "Aion 2 [True] 創世/滅絕龍神裝備指南：傳承製作出 Tier 4 武器與守護者",
      description: "新 [True] 創世龍神/滅絕龍神武器與守護者如何運作：由閃耀版經傳承製作升級、Liberated White Night 裝備作材料、可延展效果作為預設屬性",
      intro: "9 月 9 日韓服更新新增製作 Tier 4 裝備的下一步：「[True] 創世龍神」與「[True] 滅絕龍神」武器與守護者。本指南說明如何從閃耀版升級、逐步成長結構的含義，以及可延展效果的價值。",
      sourceNote: "基於 2026 年 9 月 9 日官方韓服更新說明與 Inven Global 2026 年 9 月 8 日預覽報導（均於 2026-09-09 抓取）。注意不同英文媒體譯名不同——Inven 使用「True Azure Dragon / True Extinction Dragon」，閃耀版稱「Shining」。",
      keywords: ["Aion 2 True 創世龍神", "Aion 2 True 滅絕龍神", "Aion 2 Tier 4 武器 守護者", "Aion 2 傳承製作 裝備", "Aion 2 Liberated White Night 材料"],
      sections: [
        section("what-is-true", "[True] 龍神裝備是什麼", ["更新新增「[True] 創世龍神」與「[True] 滅絕龍神」武器與守護者的圖紙——這是韓服製作 Tier 4 裝備的最新一步，與 Hard 難度新副本掉落的「Liberated White Night」（Tier 4）系列並列。", "不同媒體譯名不同：Inven Global 寫作「True Azure Dragon / True Extinction Dragon」。兩者指的都是 9 月 9 日補丁加入的同一套製作 Tier 4 裝備。"]),
        section("succession-crafting", "由閃耀版經傳承製作升級", ["核心升級路徑是傳承製作：新圖紙將「Splendent 創世龍神 / Splendent 滅絕龍神」武器與守護者轉換為 [True] 版（Inven 譯名「Shining Azure Dragon / Extinction Dragon」）。", "這是逐步成長結構——保留既有成長線推高一階而非重來。需注意一點：9 月 9 日補丁為傳承材料新增了強化等級條件，源裝備需強化到一定等級才能作為材料。"]),
        section("white-night-materials", "Liberated White Night 作材料", ["副本掉落的「Liberated White Night」武器與守護者可材料轉換為 [True] 創世/滅絕龍神武器與守護者的製作材料。", "這把新副本與製作套連接起來：刷 Liberated White Night、轉換為材料、補齊 [True] 龍神部件。"]),
        section("extendable-effect", "可延展效果，不佔靈魂刻印位", ["最有價值的細節之一：True 裝備的可延展效果作為預設屬性提供，不佔用靈魂刻印選項。", "實際意味著 [True] 階在現有構建之上免費附加傷害/防禦延展，靈魂刻印位可留給其他選擇——對終局精算玩家是有意義的 QoL 改進。"]),
        section("planning-notes", "規劃提示", ["1. 製作前確認傳承材料的強化等級條件；2. 打你能通關的難度刷 Liberated White Night；3. 將多餘副本裝備轉換為 [True] 製作材料；4. 把免費可延展效果計入構建——可省掉一個原本留給它的靈魂刻印位。", "對全球玩家：這是韓服成長內容。全球版 10 月 5 日以改良版 Season 1 上線，把本指南視為未來 Tier 4 製作路線的形態。"]),
      ],
    }),
  },
};
