import { articleCopy, guideLabels, localizations, publishedVerified, section } from "./trending-august-27-shared";
import type { ContentEntry, ContentHeroImage, ContentSource } from "./content-registry";

/* ARTICLE 2 — Marriage system: what is known */

const marriageSource1: ContentSource = {
  id: "mmoexp-weekly-marriage-2026-08-26",
  kind: "third-party", publisher: "MMOEXP",
  label: "AION 2 Weekly News: Global Launch Tweak, Marriage System, and Gamescom 2026 Reveals",
  url: "https://www.mmoexp.com/News/aion-2-weekly-news-global-launch-tweak-marriage-system-and-gamescom-2026-reveals.html",
  publishedAt: "2026-08-22",
  retrievedAt: "2026-08-26",
  verifiedAt: "2026-08-26",
  localizations: localizations({
    "zh-hans": "AION 2 每周新闻：全球发布调整、婚姻系统与 Gamescom 2026 披露",
    en: "AION 2 Weekly News: Global Launch Tweak, Marriage System, and Gamescom 2026 Reveals",
    fr: "Actualités hebdo AION 2 : ajustement du lancement mondial, système de mariage et révélations Gamescom 2026",
    de: "AION 2 Wochennews: Global-Launch-Anpassung, Hochzeitssystem und Gamescom-2026-Reveals",
    es: "Noticias semanales de AION 2: ajuste del lanzamiento global, sistema de matrimonio y revelaciones de Gamescom 2026",
    ja: "AION 2 ウィークリーニュース：グローバルローンチ調整、結婚システム、Gamescom 2026 の発表",
    "pt-br": "Notícias semanais do AION 2: ajuste do lançamento global, sistema de casamento e revelações da Gamescom 2026",
    ru: "Еженедельные новости AION 2: корректировка глобального запуска, система брака и откровения Gamescom 2026",
    ko: "AION 2 주간 뉴스: 글로벌 출시 조정, 결혼 시스템, Gamescom 2026 공개",
    "zh-hant": "AION 2 每週新聞：全球發布調整、婚姻系統與 Gamescom 2026 披露",
  }, "https://www.mmoexp.com/News/aion-2-weekly-news-global-launch-tweak-marriage-system-and-gamescom-2026-reveals.html"),
};

const marriageSource2: ContentSource = {
  id: "nc-official-site-2026-08-26",
  kind: "official", publisher: "NC",
  label: "AION 2 Official Website & Community",
  url: "https://aion2.plaync.com/",
  publishedAt: "2026-06-01",
  retrievedAt: "2026-08-26",
  verifiedAt: "2026-08-26",
  localizations: localizations({
    "zh-hans": "AION 2 官方网站与社区",
    en: "AION 2 Official Website & Community",
    fr: "Site officiel et communauté AION 2",
    de: "AION 2 Offizielle Website und Community",
    es: "Sitio web oficial y comunidad de AION 2",
    ja: "AION 2 公式サイト＆コミュニティ",
    "pt-br": "Site oficial e comunidade do AION 2",
    ru: "Официальный сайт и сообщество AION 2",
    ko: "AION 2 공식 사이트 및 커뮤니티",
    "zh-hant": "AION 2 官方網站與社群",
  }, "https://aion2.plaync.com/"),
};

const marriageHero: ContentHeroImage = {
  src: "https://blogfiles.ncsoft.net/news/af7330da-4ff6-4b58-aece-400e6061a3be.jpg",
  width: 1100, height: 605,
  credit: "NC Corporation",
  sourceUrl: "https://aion2.plaync.com/ko-kr/board/notice",
  rights: "linked-official-media",
  translations: {
    "zh-hans": { alt: "Aion 2 社交与婚姻系统指南配图", caption: "NC 官方配图；报道称 NC 正在探索更强的玩家社交与关系系统。" },
    en: { alt: "Aion 2 social and marriage system guide image", caption: "Official NC artwork; reports suggest NC is exploring stronger player social and relationship systems." },
    fr: { alt: "Image du guide sur les systèmes sociaux et le mariage d'Aion 2", caption: "Visuel officiel NC ; des rapports suggèrent que NC explore des systèmes sociaux renforcés." },
    de: { alt: "Bild zum Guide zu Sozial- und Hochzeitssystemen in Aion 2", caption: "Offizielles NC-Artwork; Berichten zufolge prüft NC stärkere soziale Systeme." },
    es: { alt: "Imagen de la guía de sistemas sociales y matrimonio de Aion 2", caption: "Arte oficial de NC; informes sugieren que NC explora sistemas sociales más fuertes." },
    ja: { alt: "Aion 2 ソーシャル・結婚システムガイド画像", caption: "NC公式アートワーク；NC がより強いソーシャル・関係性システムを模索しているとの報道があります。" },
    "pt-br": { alt: "Imagem do guia de sistemas sociais e casamento de Aion 2", caption: "Arte oficial da NC; relatos sugerem que a NC explora sistemas sociais mais fortes." },
    ru: { alt: "Изображение гайда по социальным системам и браку в Aion 2", caption: "Официальный арт NC; сообщается, что NC изучает более сильные социальные системы." },
    ko: { alt: "Aion 2 소셜·결혼 시스템 가이드 이미지", caption: "NC 공식 이미지입니다. NC가 더 강한 소셜·관계 시스템을 모색 중이라는 보도가 있습니다." },
    "zh-hant": { alt: "Aion 2 社交與婚姻系統指南配圖", caption: "NC 官方配圖；報導稱 NC 正在探索更強的玩家社交與關係系統。" },
  },
};

export const trendingAugust27Article2: ContentEntry = {
  section: "guides",
  slug: "aion-2-marriage-system-guide",
  schemaType: "Article",
  publishedAt: "2026-08-26",
  updatedAt: "2026-08-26",
  readingMinutes: 5,
  publication: publishedVerified,
  sources: [marriageSource1, marriageSource2],
  heroImage: marriageHero,
  related: [
    { kind: "content", section: "guides", slug: "aion-2-guild-social-guide" },
    { kind: "content", section: "guides", slug: "aion-2-character-customization-guide" },
    { kind: "content", section: "news", slug: "aion-2-first-global-dev-stream-recap" },
    { kind: "content", section: "guides", slug: "aion-2-housing-guide" },
  ],
  translations: {
    en: articleCopy(guideLabels, "en", 5, {
      eyebrow: "SOCIAL SYSTEM WATCH",
      title: "Aion 2 Marriage System: What We Know & What to Expect",
      description: "Reports suggest NC is exploring a marriage system for Aion 2. Here is what has been reported, how it could fit the game's social layer, and what to expect around the September 30 early access.",
      intro: "Aion 2 already leans on community: guilds, a party finder, housing neighborhoods, and heavy character customization. Now reports indicate NC is exploring relationship features — commonly framed as a marriage system — to give players more reasons to form long-term partnerships. Official details are limited, so this guide separates what has been reported from what is still speculation, and explains how the feature could land.",
      sourceNote: "Based on MMOEXP's weekly Aion 2 news (August 22) and the official Aion 2 website and community channels. NC has not formally announced a marriage system; details below are reported or speculative.",
      keywords: ["Aion 2 marriage system", "Aion 2 social features", "Aion 2 relationship system", "Aion 2 wedding", "Aion 2 community features"],
      sections: [
        section("reported", "What Has Been Reported", ["Weekly MMO news coverage on August 22 highlighted a potential marriage system as one of the topics gaining attention around Aion 2, alongside adjustments to the global launch and expectations for Gamescom 2026. The reports describe social and relationship mechanics that could expand interaction between players and encourage long-term partnerships.", "Crucially, NC has not formally announced or detailed a marriage system. There is no official name, no feature list, and no confirmed timeline. Treat any specific claims about wedding ceremonies, partner bonuses, or exclusive cosmetics as community expectations until NC publishes a roadmap.", "The reporting context matters: it arrived in the same week NC was adjusting the global version based on Korean and Taiwanese feedback — a sign the studio is actively reworking social and progression systems for the international build."]),
        section("typical-features", "What a Marriage System Usually Includes", ["In other MMORPGs, marriage systems typically pair a social ceremony (sometimes player-hosted) with mechanical hooks: a shared quest line, partner titles or outfits, and light gameplay cooperation such as an XP bonus when playing together. Some games add cosmetic items, home-sharing, or emote sets purchasable through the cash shop.", "None of these are confirmed for Aion 2. They are offered here only as a reference frame based on genre conventions, so players know what a 'marriage system' announcement might plausibly contain if it ever ships.", "If NC follows its own pattern — confirming systems gradually through dev streams and KR patch notes — the feature will appear in the Korean service first, giving global players a preview of the final form."]),
        section("fitting-aion2", "How It Could Fit Aion 2's Social Layer", ["Aion 2's confirmed social layer already includes guilds with guild halls and recruitment, a party finder with normalizing the global party structure, and housing neighborhoods that returned as the first confirmed life content. A relationship system would slot naturally alongside these — especially with housing and the planned sailing life content giving characters persistent spaces to share.", "The game's character customization focus (200+ options, presets, glamour) also creates a natural market for partner-themed cosmetics, one of the most common revenue hooks for such systems in the genre.", "For solo players, the main effect would be optional: reports describe social features as expanding interaction beyond combat and progression, not as a required progression gate. Guild guides remain the primary path for grouping either way."]),
        section("launch-expectation", "What to Expect at Launch", ["As of August 26, no release date has been attached to any relationship feature. The September 30 early access and the reported October 5 free-to-play launch are focused on the confirmed launch systems: eight classes, five server regions, reworked dungeons and PvP, and Founder's Pack benefits.", "Players who want the feature at launch should assume it will not be there. The realistic pattern — matching housing — is a Korea-first rollout followed by a global timing announcement once the system is stable.", "That makes the September launch a poor reason to delay commitment decisions, and a good moment to set expectations with your in-game community about what social features exist day one (guilds, party finder) versus what is still on the horizon."]),
        section("stay-updated", "How to Stay Updated", ["Watch NC's official channels and the Korean service patch notes first — every life or social system confirmed so far (housing, sailing, the second new class) was revealed there before any global announcement.", "Community weekly news roundups are useful early signals, but always verify their claims against an official notice before treating them as fact. The AION 2 news hub tracks both official announcements and sourced community reporting.", "If a formal marriage system announcement lands, we will update this guide with the official details, names, and timeline as soon as NC publishes them."]),
      ],
    }),
    "zh-hans": articleCopy(guideLabels, "zh-hans", 5, {
      eyebrow: "社交系统观察",
      title: "Aion 2 婚姻系统：已知信息与预期",
      description: "报道称 NC 正在探索为 Aion 2 加入婚姻系统。以下为已报道内容、它如何融入游戏社交层，以及 9 月 30 日抢先体验前的预期。",
      intro: "Aion 2 已经非常注重社群：公会、队伍查找器、住房社区与丰富的角色自定义。如今报道称 NC 正在探索关系系统（通常称为婚姻系统），让玩家有更多理由建立长期伙伴关系。官方细节有限，本指南将已报道内容与猜测分开，并解释该功能可能的落地方式。",
      sourceNote: "基于 MMOEXP 8 月 22 日 Aion 2 周报与 Aion 2 官方网站/社区。NC 尚未正式公布婚姻系统，以下内容为报道或推测性质。",
      keywords: ["Aion 2 婚姻系统", "Aion 2 社交功能", "Aion 2 关系系统", "Aion 2 婚礼", "Aion 2 社区功能"],
      sections: [
        section("reported", "已报道的内容", ["8 月 22 日的 MMO 周报将潜在婚姻系统列为 Aion 2 的受关注话题之一，与全球发布调整和 Gamescom 2026 预期并列，描述为可扩展玩家互动、鼓励长期伙伴关系的社交机制。", "重要提示：NC 并未正式公布或详述婚姻系统，没有官方名称、功能列表或时间表。任何关于婚礼仪式、伙伴加成或专属外观的具体说法都应视为社区预期。"]),
        section("typical-features", "婚姻系统通常包含什么", ["在多数 MMORPG 中，婚姻系统通常结合社交仪式与机制钩子：共享任务线、伴侣称号/外观、组队经验加成，部分游戏还加入外观饰品、共享家园或表情包等。", "以上均未在 Aion 2 中确认，仅供参考框架。如果 NC 遵循既有节奏（先开发者直播、先韩服更新），该功能将先出现在韩服，为全球玩家提供预览。"]),
        section("fitting-aion2", "它如何融入 Aion 2 的社交层", ["Aion 2 已确认的社交层包括公会（公会厅与招募）、队伍查找器，以及作为首个生活内容回归的住房社区。关系系统可自然融入其中——尤其是住房与计划中的航海生活内容为角色提供了可共享的持久空间。", "角色自定义（200+ 选项、预设、外观）也为伴侣主题外观创造了天然需求，这是该类型系统最常见的变现钩子之一。", "对单人玩家而言，主要影响是可选的：报道中的社交功能是扩展战斗与成长之外的互动，而非强制进度门槛。"]),
        section("launch-expectation", "上线时的预期", ["截至 8 月 26 日，任何关系功能都未附带发布日期。9 月 30 日抢先体验与报道的 10 月 5 日免费游玩上线均聚焦于已确认的系统：八职业、五大服务器区域、重构副本与 PvP、创始人包权益。", "期望该功能在上线时可用是不现实的：现实节奏（与住房一致）是韩服先行、稳定后再公布全球时间。", "因此 9 月上线不是推迟承诺决定的理由，而是与游戏内社群对齐预期（上线首日有什么社交功能 vs 仍在路上）的好时机。"]),
        section("stay-updated", "如何保持更新", ["首先关注 NC 官方渠道与韩服更新说明——迄今确认的生活/社交系统（住房、航海、第二新职业）都是先在那里公布。", "社区周报是有用的早期信号，但务必以官方公告为准。Aion 2 新闻中心同时跟踪官方公告与有来源的社区报道。", "如果正式的婚姻系统公告落地，我们将在 NC 发布后立即更新本指南。"]),
      ],
    }),
    ko: articleCopy(guideLabels, "ko", 5, {
      eyebrow: "소셜 시스템 워치",
      title: "Aion 2 결혼 시스템: 알려진 것과 기대할 것",
      description: "NC가 Aion 2에 결혼 시스템 도입을 모색 중이라는 보도가 있습니다. 보도된 내용, 게임의 소셜 레이어에 맞는 방식, 9월 30일 조기 접속 전 기대치를 정리합니다.",
      intro: "Aion 2는 이미 길드, 파티 찾기, 하우징 커뮤니티, 캐릭터 커스터마이징으로 커뮤니티에 힘을 주고 있습니다. 이제 NC가 관계 시스템(일반적으로 결혼 시스템)을 모색 중이라는 보도가 나왔습니다. 공식 세부사항은 제한적이라 보도와 추측을 구분해 정리합니다.",
      sourceNote: "MMOEXP 주간 뉴스(8/22)와 공식 Aion 2 사이트·커뮤니티 기반. NC의 공식 발표는 없으며 아래 내용은 보도 또는 추측입니다.",
      keywords: ["Aion 2 결혼 시스템", "Aion 2 소셜 기능", "Aion 2 관계 시스템", "Aion 2 웨딩", "Aion 2 커뮤니티 기능"],
      sections: [
        section("reported", "보도된 내용", ["8월 22일 MMO 주간 보도는 잠재적 결혼 시스템을 Aion 2의 주목받는 주제 중 하나로 다뤘습니다 — 글로벌 출시 조정, Gamescom 2026 기대와 함께요. 플레이어 간 상호작용을 확장하고 장기적 파트너십을 장려하는 사회적 메커니즘으로 묘사됩니다.", "중요: NC는 아직 공식 발표가 없습니다. 이름, 기능 목록, 일정 모두 미확정입니다. 구체적 주장은 커뮤니티 기대치로 취급하세요."]),
        section("typical-features", "결혼 시스템의 일반적 구성", ["다른 MMORPG에서 결혼 시스템은 공유 퀘스트, 파트너 칭호/의상, 파티 경험치 보너스 같은 메커니즘을 포함합니다. 일부 게임은 코스메틱, 홈 공유, 이모트를 추가합니다.", "이상은 Aion 2에서 확인되지 않았습니다. 장르 관례 기준의 참고 프레임일 뿐입니다. NC 패턴상(개발자 스트림, 한국 서버 패치) 한국 서버에 먼저 나올 가능성이 높습니다."]),
        section("fitting-aion2", "Aion 2 소셜 레이어와의 조화", ["확정된 소셜 레이어: 길드(길드 홀·모집), 파티 찾기, 첫 생활 콘텐츠로 확정된 하우징 커뮤니티. 관계 시스템은 하우징·항해 생활 콘텐츠와 자연스럽게 어울립니다.", "200+ 커스터마이징 옵션도 파트너 테마 코스메틱의 자연스러운 수요처입니다.", "솔로 플레이어에게는 선택 사항입니다: 전투와 성장을 넘어선 상호작용 확장이지 필수 진척 관문이 아닙니다."]),
        section("launch-expectation", "출시 시 기대치", ["2026년 8월 26일 기준 어떤 관계 기능에도 출시일이 붙지 않았습니다. 9월 30일 조기 접속과 10월 5일(보도) 무료 출시는 확정 시스템(8개 클래스, 5개 지역, 던전·PvP, 파운더스 팩)에 집중됩니다.", "출시 시점에 이 기능을 기대하는 것은 현실적이지 않습니다 — 하우징과 동일하게 한국 서버 우선 후 글로벌 시기 공개가 유력합니다."]),
        section("stay-updated", "정보를 계속 받는 법", "NC 공식 채널과 한국 서버 패치 노트를 먼저 보세요. 하우징, 항해, 두 번째 신규 클래스 모두 거기서 먼저 공개됐습니다. 공식 공지로 확인하기 전에는 보도를 사실로 취급하지 마세요."),
      ],
    }),
    ja: articleCopy(guideLabels, "ja", 5, {
      eyebrow: "ソーシャルシステムウォッチ",
      title: "Aion 2 結婚システム：判明していることと期待されること",
      description: "NC が Aion 2 に結婚システムの導入を模索しているとの報道があります。報道内容、ゲームのソーシャル面への適合性、9月30日の早期アクセスまでの期待値をまとめます。",
      intro: "Aion 2 はギルド、パーティファインダー、ハウジングコミュニティ、キャラカスタマイズでコミュニティに力を入れています。今度は関係システム（一般に結婚システム）を模索しているとの報道です。公式情報は限定的なため、報道と推測を分けて整理します。",
      sourceNote: "MMOEXP 週間ニュース（8/22）と公式 Aion 2 サイト・コミュニティに基づきます。NC からの正式発表はなく、以下は報道・推測です。",
      keywords: ["Aion 2 結婚システム", "Aion 2 ソーシャル機能", "Aion 2 関係システム", "Aion 2 ウェディング", "Aion 2 コミュニティ機能"],
      sections: [
        section("reported", "報道された内容", "8月22日のMMO週間報道は潜在的な結婚システムをAion 2の注目トピックとして取り上げました。プレイヤー間の交流を広げ、長期的なパートナーシップを促す社会的メカニズムとされています。重要なのは公式発表がまだないことです。"),
        section("typical-features", "結婚システムの一般的な内容", "他のMMORPGでは共有クエスト、パートナー称号・衣装、パーティ経験値ボーナスなどを含みます。一部はコスメ、ホーム共有、エモートを追加。いずれもAion 2では未確認で、参考枠組みです。"),
        section("fitting-aion2", "Aion 2 のソーシャル面との適合", "確定済みのソーシャル面：ギルド（ギルドホール・勧誘）、パーティファインダー、最初の生活コンテンツに確定したハウジング。関係システムはハウジング・帆走と自然に調和します。"),
        section("launch-expectation", "ローンチ時点の期待値", "2026年8月26日時点で関係機能にリリース日は設定されていません。9月30日の早期アクセスと10月5日（報道）の無料リリースは確定済みシステムに集中します。ハウジングと同様、韓国サーバー先行が有力です。"),
        section("stay-updated", "情報の入手方法", "NC 公式チャンネルと韓国サーバーのパッチノートを最優先にチェックしてください。ハウジング、帆走、2つ目の新クラスもすべてそこで先に公開されました。"),
      ],
    }),
    fr: articleCopy(guideLabels, "fr", 5, {
      eyebrow: "VEILLE SOCIALE",
      title: "Système de mariage d'Aion 2 : ce que l'on sait et ce qu'il faut attendre",
      description: "Des rapports suggèrent que NC explore un système de mariage pour Aion 2. Ce qui a été rapporté, comment cela s'intégrerait, et à quoi s'attendre avant le 30 septembre.",
      intro: "Aion 2 mise déjà sur la communauté : guildes, cherche-groupe, quartiers de logement et personnalisation. Des rapports évoquent désormais un système de relations — souvent appelé mariage.",
      sourceNote: "Basé sur les actualités hebdo MMOEXP (22/08) et le site officiel. NC n'a rien annoncé officiellement ; détails rapportés ou spéculatifs.",
      keywords: ["Aion 2 système de mariage", "Aion 2 fonctionnalités sociales", "Aion 2 mariage", "Aion 2 social"],
      sections: [
        section("reported", "Ce qui a été rapporté", "La presse MMO du 22 août a cité un potentiel système de mariage parmi les sujets qui prennent de l'ampleur autour d'Aion 2, décrit comme un moyen d'encourager des partenariats de longue durée. Aucune annonce officielle de NC à ce jour."),
        section("typical-features", "Ce qu'inclut généralement un tel système", "Dans d'autres MMORPG : quête partagée, titres et tenues de partenaire, bonus d'XP en groupe, cosmétiques, partage de maison. Rien n'est confirmé pour Aion 2 ; simple cadre de référence."),
        section("fitting-aion2", "Intégration dans Aion 2", "Le socle social confirmé (guildes, cherche-groupe, logement) s'accorderait naturellement avec un système de relations, surtout avec le contenu de vie (logement, navigation)."),
        section("launch-expectation", "Attentes au lancement", "Aucune date n'est attachée à ces fonctionnalités au 26 août. La sortie du 30 septembre se concentre sur les systèmes confirmés. Modèle probable : déploiement Corée d'abord, comme le logement."),
        section("stay-updated", "Rester informé", "Suivez les canaux officiels et les notes de patch coréennes en priorité. Les rumeurs doivent être vérifiées sur une notice officielle."),
      ],
    }),
    de: articleCopy(guideLabels, "de", 5, {
      eyebrow: "SOCIAL-SYSTEME BEOBACHTUNG",
      title: "Aion-2-Hochzeitssystem: Was wir wissen & was zu erwarten ist",
      description: "Berichten zufolge prüft NC ein Hochzeitssystem für Aion 2. Was berichtet wurde, wie es ins Spiel passen könnte und was vor dem 30. September zu erwarten ist.",
      intro: "Aion 2 setzt bereits stark auf Community: Gilden, Gruppensuche, Wohnviertel und Charakteranpassung. Nun gibt es Berichte über ein Beziehungssystem — meist als Hochzeitssystem bezeichnet.",
      sourceNote: "Basierend auf MMOEXP-Wochennews (22.08.) und der offiziellen Website. NC hat nichts offiziell angekündigt; Details sind berichtet oder spekulativ.",
      keywords: ["Aion 2 Hochzeitssystem", "Aion 2 soziale Funktionen", "Aion 2 Beziehungssystem", "Aion 2 Hochzeit"],
      sections: [
        section("reported", "Was berichtet wurde", "Die MMO-Presse vom 22. August nannte ein potenzielles Hochzeitssystem als wachsendes Thema rund um Aion 2, beschrieben als Mechanik für langfristige Partnerschaften. Bisher keine offizielle Ankündigung von NC."),
        section("typical-features", "Was ein solches System üblicherweise bietet", "In anderen MMORPGs: gemeinsame Quests, Partner-Titel und -Outfits, Gruppen-XP-Bonus, Kosmetik, gemeinsames Zuhause. Für Aion 2 nichts bestätigt; nur ein Referenzrahmen."),
        section("fitting-aion2", "Integration in Aion 2", "Das bestätigte soziale Fundament (Gilden, Gruppensuche, Wohnen) passt natürlich zu einem Beziehungssystem, besonders mit Wohn- und Segel-Lebensinhalten."),
        section("launch-expectation", "Erwartungen zum Launch", "Bis 26. August ist kein Datum an solche Funktionen gebunden. Der 30. September fokussiert auf bestätigte Systeme. Wahrscheinlich: Korea zuerst, wie beim Wohnen."),
        section("stay-updated", "Aktuell bleiben", "Offizielle Kanäle und koreanische Patch-Notes zuerst prüfen; Gerüchte erst nach offizieller Bestätigung als Fakt behandeln."),
      ],
    }),
    es: articleCopy(guideLabels, "es", 5, {
      eyebrow: "OBSERVATORIO SOCIAL",
      title: "Sistema de matrimonio de Aion 2: lo que sabemos y qué esperar",
      description: "Informes sugieren que NC explora un sistema de matrimonio para Aion 2. Lo informado, cómo encajaría y qué esperar antes del 30 de septiembre.",
      intro: "Aion 2 ya apuesta por la comunidad: gremios, buscador de grupo, barrios de vivienda y personalización. Ahora se habla de un sistema de relaciones — comúnmente llamado matrimonio.",
      sourceNote: "Basado en las noticias semanales de MMOEXP (22/08) y el sitio oficial. NC no ha anunciado nada oficialmente; los detalles son informados o especulativos.",
      keywords: ["Aion 2 sistema de matrimonio", "Aion 2 funciones sociales", "Aion 2 matrimonio", "Aion 2 social"],
      sections: [
        section("reported", "Lo informado", "La prensa MMO del 22 de agosto citó un posible sistema de matrimonio entre los temas en auge de Aion 2, como mecánica para fomentar asociaciones a largo plazo. Sin anuncio oficial de NC."),
        section("typical-features", "Qué suele incluir", "En otros MMORPG: misión compartida, títulos y atuendos de pareja, bonus de XP en grupo, cosméticos, hogar compartido. Nada confirmado para Aion 2; solo marco de referencia."),
        section("fitting-aion2", "Integración en Aion 2", "La base social confirmada (gremios, buscador de grupo, vivienda) encajaría naturalmente con un sistema de relaciones, sobre todo con el contenido de vida (vivienda, navegación)."),
        section("launch-expectation", "Expectativas en el lanzamiento", "Ninguna fecha está ligada a estas funciones al 26 de agosto. El 30 de septiembre se centra en los sistemas confirmados. Patrón probable: primero Corea, como la vivienda."),
        section("stay-updated", "Mantenerse al día", "Sigue primero los canales oficiales y las notas de parche de Corea; verifica los rumores contra un aviso oficial."),
      ],
    }),
    "pt-br": articleCopy(guideLabels, "pt-br", 5, {
      eyebrow: "OBSERVATÓRIO SOCIAL",
      title: "Sistema de casamento de Aion 2: o que sabemos e o que esperar",
      description: "Relatos sugerem que a NC explora um sistema de casamento para Aion 2. O que foi relatado, como se encaixaria e o que esperar antes de 30 de setembro.",
      intro: "Aion 2 já aposta na comunidade: guildas, buscador de grupo, bairros de moradia e personalização. Agora há relatos de um sistema de relacionamentos — comumente chamado de casamento.",
      sourceNote: "Baseado nas notícias semanais da MMOEXP (22/08) e no site oficial. A NC não anunciou nada oficialmente; detalhes são relatados ou especulativos.",
      keywords: ["Aion 2 sistema de casamento", "Aion 2 funções sociais", "Aion 2 casamento", "Aion 2 social"],
      sections: [
        section("reported", "O que foi relatado", "A imprensa de MMO de 22 de agosto citou um possível sistema de casamento entre os temas em alta de Aion 2, como mecânica para fomentar parcerias de longo prazo. Sem anúncio oficial da NC."),
        section("typical-features", "O que costuma incluir", "Em outros MMORPGs: missão compartilhada, títulos e visuais de parceiro, bônus de XP em grupo, cosméticos, lar compartilhado. Nada confirmado para Aion 2; apenas referência."),
        section("fitting-aion2", "Integração em Aion 2", "A base social confirmada (guildas, buscador de grupo, moradia) encaixaria naturalmente com um sistema de relacionamentos, sobretudo com o conteúdo de vida (moradia, navegação)."),
        section("launch-expectation", "Expectativas no lançamento", "Nenhuma data está ligada a essas funções em 26 de agosto. O lançamento de 30 de setembro foca nos sistemas confirmados. Padrão provável: Coreia primeiro, como a moradia."),
        section("stay-updated", "Como se manter informado", "Acompanhe primeiro os canais oficiais e as notas de patch da Coreia; verifique boatos contra um aviso oficial."),
      ],
    }),
    ru: articleCopy(guideLabels, "ru", 5, {
      eyebrow: "СОЦИАЛЬНЫЙ ОБЗОР",
      title: "Система брака в Aion 2: что известно и чего ожидать",
      description: "Сообщается, что NC изучает систему брака для Aion 2. Что известно, как это впишется в игру и чего ждать до 30 сентября.",
      intro: "Aion 2 уже делает ставку на сообщество: гильдии, поиск группы, жилые районы и кастомизацию. Теперь сообщается о системе отношений — обычно называемой системой брака.",
      sourceNote: "На основе еженедельных новостей MMOEXP (22.08) и официального сайта. NC официально ничего не объявляла; детали — сообщения или предположения.",
      keywords: ["Aion 2 система брака", "Aion 2 социальные функции", "Aion 2 отношения", "Aion 2 свадьба"],
      sections: [
        section("reported", "Что сообщается", "MMO-пресса от 22 августа назвала потенциальную систему брака растущей темой вокруг Aion 2 — механикой для долгосрочных партнёрств. Официальных анонсов NC нет."),
        section("typical-features", "Что обычно включает", "В других MMORPG: общий квест, титулы и наряды партнёра, бонус опыта в группе, косметика, совместный дом. Для Aion 2 ничего не подтверждено; только рамки для справки."),
        section("fitting-aion2", "Как это впишется", "Подтверждённая социальная база (гильдии, поиск группы, жильё) естественно сочетается с системой отношений — особенно с жизненным контентом (жильё, мореплавание)."),
        section("launch-expectation", "Ожидания на запуске", "По состоянию на 26 августа дат у этих функций нет. Запуск 30 сентября сосредоточен на подтверждённых системах. Вероятно: сначала Корея, как с жильём."),
        section("stay-updated", "Как оставаться в курсе", "Сначала официальные каналы и патчноуты Кореи; слухи сверяйте с официальными уведомлениями."),
      ],
    }),
    "zh-hant": articleCopy(guideLabels, "zh-hant", 5, {
      eyebrow: "社交系統觀察",
      title: "Aion 2 婚姻系統：已知資訊與預期",
      description: "報導稱 NC 正在探索為 Aion 2 加入婚姻系統。以下為已報導內容、它如何融入遊戲社交層，以及 9 月 30 日搶先體驗前的預期。",
      intro: "Aion 2 已經非常注重社群：公會、隊伍查找器、住房社區與豐富的角色自訂。如今報導稱 NC 正在探索關係系統（通常稱為婚姻系統），讓玩家有更多理由建立長期夥伴關係。官方細節有限，本指南將已報導內容與猜測分開，並解釋該功能可能的落地方式。",
      sourceNote: "基於 MMOEXP 8 月 22 日 Aion 2 週報與 Aion 2 官方網站/社群。NC 尚未正式公布婚姻系統，以下內容為報導或推測性質。",
      keywords: ["Aion 2 婚姻系統", "Aion 2 社交功能", "Aion 2 關係系統", "Aion 2 婚禮", "Aion 2 社群功能"],
      sections: [
        section("reported", "已報導的內容", ["8 月 22 日的 MMO 週報將潛在婚姻系統列為 Aion 2 的受關注話題之一，與全球發布調整和 Gamescom 2026 預期並列，描述為可擴展玩家互動、鼓勵長期夥伴關係的社交機制。", "重要提示：NC 並未正式公布或詳述婚姻系統，沒有官方名稱、功能列表或時間表。任何關於婚禮儀式、夥伴加成或專屬外觀的具體說法都應視為社群預期。"]),
        section("typical-features", "婚姻系統通常包含什麼", ["在多數 MMORPG 中，婚姻系統通常結合社交儀式與機制鉤子：共享任務線、伴侶稱號/外觀、組隊經驗加成，部分遊戲還加入外觀飾品、共享家園或表情包等。", "以上均未在 Aion 2 中確認，僅供參考框架。如果 NC 遵循既有節奏（先開發者直播、先韓服更新），該功能將先出現在韓服，為全球玩家提供預覽。"]),
        section("fitting-aion2", "它如何融入 Aion 2 的社交層", ["Aion 2 已確認的社交層包括公會（公會廳與招募）、隊伍查找器，以及作為首個生活內容回歸的住房社區。關係系統可自然融入其中——尤其是住房與計畫中的航海生活內容為角色提供了可共享的持久空間。", "角色自訂（200+ 選項、預設、外觀）也為伴侶主題外觀創造了天然需求，這是該類型系統最常見的變現鉤子之一。"]),
        section("launch-expectation", "上線時的預期", ["截至 8 月 26 日，任何關係功能都未附帶發布日期。9 月 30 日搶先體驗與報導的 10 月 5 日免費遊玩上線均聚焦於已確認的系統。", "期望該功能在上線時可用是不現實的：現實節奏（與住房一致）是韓服先行、穩定後再公布全球時間。"]),
        section("stay-updated", "如何保持更新", ["首先關注 NC 官方管道與韓服更新說明——迄今確認的生活/社交系統（住房、航海、第二新職業）都是先在那裡公布。", "社群週報是有用的早期訊號，但務必以官方公告為準。Aion 2 新聞中心同時追蹤官方公告與有來源的社群報導。"]),
      ],
    }),
  },
};