import { articleCopy, localizations, newsLabels, publishedVerified, section } from "./trending-august-29-shared";
import type { ContentEntry, ContentHeroImage, ContentSource } from "./content-registry";

/* ARTICLE 1 — Launch Scale Test announced: September 17–18 */

const lstSource1: ContentSource = {
  id: "steam-lst-announcement-2026-08-29",
  kind: "platform", publisher: "Steam",
  label: "AION 2 — Launch Scale Test Coming Up",
  url: "https://store.steampowered.com/news/app/3393110/view/675129723539424082",
  publishedAt: "2026-08-26",
  retrievedAt: "2026-08-28",
  verifiedAt: "2026-08-28",
  localizations: localizations({
    "zh-hans": "AION 2——上线规模测试即将开始",
    en: "AION 2 — Launch Scale Test Coming Up",
    fr: "AION 2 — Test à grande échelle de lancement à venir",
    de: "AION 2 — Launch Scale Test steht bevor",
    es: "AION 2 — Prueba de escala de lanzamiento próximamente",
    ja: "AION 2 — ローンチスケールテスト開催のお知らせ",
    "pt-br": "AION 2 — Teste de escala de lançamento em breve",
    ru: "AION 2 — Приближается масштабный запуск-тест",
    ko: "AION 2 — 출시 규모 테스트가 다가옵니다",
    "zh-hant": "AION 2——上線規模測試即將開始",
  }, "https://store.steampowered.com/news/app/3393110/view/675129723539424082"),
};

const lstSource2: ContentSource = {
  id: "80lv-lst-2026-08-29",
  kind: "third-party", publisher: "80 Level",
  label: "AION 2 Shows Off Epic Battles in New Trailer & Invites to Launch Scale Test",
  url: "https://80.lv/articles/aion-2-shows-off-epic-battles-in-new-trailer-invites-to-launch-scale-test",
  publishedAt: "2026-08-27",
  retrievedAt: "2026-08-28",
  verifiedAt: "2026-08-28",
  localizations: localizations({
    "zh-hans": "AION 2 新预告展示史诗战斗并邀请参与上线规模测试",
    en: "AION 2 Shows Off Epic Battles in New Trailer & Invites to Launch Scale Test",
    fr: "AION 2 dévoile des batailles épiques dans une nouvelle bande-annonce et invite au test de lancement",
    de: "AION 2 zeigt epische Schlachten in neuem Trailer und lädt zum Launch Scale Test ein",
    es: "AION 2 muestra batallas épicas en un nuevo tráiler e invita a la prueba de escala de lanzamiento",
    ja: "AION 2 が新トレーラーで壮大な戦闘を披露し、ローンチスケールテストを告知",
    "pt-br": "AION 2 mostra batalhas épicas em novo trailer e convida para o teste de escala de lançamento",
    ru: "AION 2 показывает эпичные сражения в новом трейлере и приглашает на масштабный тест",
    ko: "AION 2가 새 트레일러로 장대한 전투를 공개하고 출시 규모 테스트를 초대합니다",
    "zh-hant": "AION 2 新預告展示史詩戰鬥並邀請參與上線規模測試",
  }, "https://80.lv/articles/aion-2-shows-off-epic-battles-in-new-trailer-invites-to-launch-scale-test"),
};

const lstSource3: ContentSource = {
  id: "nc-official-global-lst-2026-08-29",
  kind: "official", publisher: "NC",
  label: "AION 2 Global Official Site — Launch Scale Test & Release Info",
  url: "https://aion2.ncsoft.jp/ja/contents",
  publishedAt: "2026-08-01",
  retrievedAt: "2026-08-28",
  verifiedAt: "2026-08-28",
  localizations: localizations({
    "zh-hans": "AION 2 全球官网——上线规模测试与上线信息",
    en: "AION 2 Global Official Site — Launch Scale Test & Release Info",
    fr: "Site officiel mondial AION 2 — info test à grande échelle et sortie",
    de: "AION 2 Globale offizielle Website — Launch-Scale-Test & Release-Infos",
    es: "Sitio oficial global de AION 2 — prueba de escala y lanzamiento",
    ja: "AION 2 グローバル公式サイト — ローンチスケールテスト＆リリース情報",
    "pt-br": "Site oficial global do AION 2 — teste de escala e lançamento",
    ru: "Официальный глобальный сайт AION 2 — тест и релиз",
    ko: "Aion 2 글로벌 공식 사이트 — 출시 규모 테스트 및 출시 정보",
    "zh-hant": "AION 2 全球官網——上線規模測試與上線資訊",
  }, "https://aion2.ncsoft.jp/ja/contents"),
};

const lstHero: ContentHeroImage = {
  src: "https://blogfiles.ncsoft.net/news/af7330da-4ff6-4b58-aece-400e6061a3be.jpg",
  width: 1100, height: 605,
  credit: "NC Corporation",
  sourceUrl: "https://aion2.plaync.com/ja-jp/board/notice/list",
  rights: "linked-official-media",
  translations: {
    "zh-hans": { alt: "Aion 2 上线规模测试公告配图", caption: "NC 官方配图；Aion 2 上线规模测试（LST）定于 2026 年 9 月 17-18 日，9 月 16 日开放预载，向所有玩家开放。" },
    en: { alt: "Aion 2 launch scale test announcement image", caption: "Official NC artwork; the Aion 2 Launch Scale Test runs September 17–18, 2026, with pre-download on September 16, open to all players." },
    fr: { alt: "Image de l'annonce du test à grande échelle d'Aion 2", caption: "Visuel officiel NC ; le test à grande échelle d'Aion 2 se tient les 17-18 septembre 2026, préchargement le 16 septembre, ouvert à tous." },
    de: { alt: "Bild zur Ankündigung des Aion-2-Launch-Scale-Tests", caption: "Offizielles NC-Artwork; der Aion-2-Launch-Scale-Test läuft vom 17.–18. September 2026, Vorabdownload am 16. September, offen für alle." },
    es: { alt: "Imagen del anuncio de la prueba de escala de Aion 2", caption: "Arte oficial de NC; la prueba de escala de Aion 2 se celebra del 17 al 18 de septiembre de 2026, precarga el 16 de septiembre, abierta a todos." },
    ja: { alt: "Aion 2 ローンチスケールテスト告知画像", caption: "NC公式アートワーク；Aion 2 のローンチスケールテストは2026年9月17日〜18日、9月16日プリロード、すべてのプレイヤーが対象です。" },
    "pt-br": { alt: "Imagem do anúncio do teste de escala do Aion 2", caption: "Arte oficial da NC; o teste de escala do Aion 2 ocorre de 17 a 18 de setembro de 2026, com pré-download em 16 de setembro, aberto a todos." },
    ru: { alt: "Изображение анонса масштабного теста Aion 2", caption: "Официальный арт NC; масштабный запуск-тест Aion 2 пройдёт 17–18 сентября 2026, предзагрузка 16 сентября, открыт для всех." },
    ko: { alt: "Aion 2 출시 규모 테스트 공지 이미지", caption: "NC 공식 이미지입니다. Aion 2 출시 규모 테스트(LST)는 2026년 9월 17~18일, 9월 16일 사전 다운로드, 모든 플레이어에게 열려 있습니다." },
    "zh-hant": { alt: "Aion 2 上線規模測試公告配圖", caption: "NC 官方配圖；Aion 2 上線規模測試（LST）定於 2026 年 9 月 17-18 日，9 月 16 日開放預載，向所有玩家開放。" },
  },
};

export const trendingAugust29Article1: ContentEntry = {
  section: "news",
  slug: "aion-2-launch-scale-test-september-17-18",
  schemaType: "NewsArticle",
  publishedAt: "2026-08-28",
  updatedAt: "2026-08-28",
  readingMinutes: 5,
  publication: publishedVerified,
  sources: [lstSource1, lstSource2, lstSource3],
  heroImage: lstHero,
  related: [
    { kind: "content", section: "guides", slug: "aion-2-pre-launch-checklist" },
    { kind: "content", section: "guides", slug: "aion-2-steam-release-guide" },
    { kind: "content", section: "news", slug: "aion-2-release-date-october-5-2026" },
    { kind: "content", section: "guides", slug: "aion-2-pc-performance-guide" },
  ],
  translations: {
    en: articleCopy(newsLabels, "en", 5, {
      eyebrow: "LAUNCH SCALE TEST",
      title: "Aion 2 Launch Scale Test: September 17–18 — Everything Announced",
      description: "NCSoft announced the Aion 2 Launch Scale Test for September 17–18, with pre-download on September 16. Open to everyone on Steam and PURPLE, level cap 37, six hours per day, and all progression wiped at the end.",
      intro: "On August 26, NCSoft announced a Launch Scale Test (LST) for Aion 2 running September 17–18 — the last large-scale rehearsal before the September 30 early access and October 5 free-to-play launch. The test is open to everyone: no keys, no invites, no registration. This report breaks down the exact schedule, what the test includes and excludes, and what you need to do before and after.",
      sourceNote: "Based on the official Steam announcement 'Launch Scale Test Coming Up' (August 26), the AION 2 global official site, and 80 Level's August 27 coverage of the announcement and new trailer.",
      keywords: ["Aion 2 Launch Scale Test", "Aion 2 LST dates", "Aion 2 September 17 test", "Aion 2 closed beta", "Aion 2 pre-download September 16"],
      sections: [
        section("schedule", "The Exact Schedule", ["Pre-download opens September 16: from 6:00 AM PDT (15:00 CEST) all the way to September 17, 6:00 AM PDT (15:00 CEST) — a full 24-hour window to install the test client.", "Day 1 is September 17, from 6:00 AM to 12:00 PM PDT (15:00–21:00 CEST). Day 2 is September 18, from 12:00 PM to 6:00 PM PDT (21:00 September 18 to 03:00 CEST September 19).", "Play time is capped at six hours per day (12 hours total). In Japan Standard Time the same windows are 22:00 JST for Day 1 and 04:00–10:00 JST for Day 2, as confirmed on the global official site."]),
        section("how-to-join", "How to Join", ["No keys, invites, or registration list: the LST is open to everyone on both platforms — Steam and the PURPLE launcher.", "On Steam, access is through the Playtest app (store.steampowered.com/app/4972320), with the client pre-downloadable from September 16.", "After the test ends, Steam players must uninstall the Playtest app and download AION 2 separately for Advanced Access on September 30. PURPLE players need to do nothing extra."]),
        section("content", "What's In the Test", ["Characters can reach a maximum level of 37, which means all content gated above that level is out of reach during the test — the focus is server load and the opening experience, not endgame.", "The environment includes the game's signature open-world structure: flight combat, faction warfare, and large-scale battles shown in the new batch of trailers.", "Progression carries over from Day 1 to Day 2 within the test. Everything is wiped at the end of Day 2 — nothing transfers to Advanced Access or the October 5 launch."]),
        section("disabled", "What's Turned Off", ["No purchases of any kind: the Shop, Quna, passes, memberships, and all payment portals are disabled.", "The Marketplace, Quna exchange, and player-to-player trading are disabled, so the economy will not be tested during LST.", "Founder's Pack items are not available, and the Closet is disabled — players use default outfits only during the test."]),
        section("what-it-means", "Why It Matters", ["An open, keyless scale test roughly three weeks before launch is a strong signal that NCSoft is treating the September 30 early access as the real launch and using LST as the load rehearsal — your feedback and server stress directly shape opening week.", "For launch planning, treat LST as the best practice window: pre-download the client, tune your graphics settings, and confirm the game runs on your PC before Advanced Access.", "Expect a wave of videos and build discussion around September 17–18; the site's PC performance guide is a good reference to pair with this test."]),
      ],
    }),
    "zh-hans": articleCopy(newsLabels, "zh-hans", 5, {
      eyebrow: "上线规模测试",
      title: "Aion 2 上线规模测试：9 月 17-18 日——全部已公布信息",
      description: "NCSoft 公布 Aion 2 上线规模测试定于 9 月 17-18 日，9 月 16 日开放预载。Steam 与 PURPLE 双平台、无需资格、等级上限 37、每日 6 小时，测试结束全部进度清空。",
      intro: "8 月 26 日 NCSoft 公布 Aion 2 上线规模测试（LST）定于 9 月 17-18 日——这是 9 月 30 日抢先体验与 10 月 5 日免费游玩上线前的最后一次大规模演练。测试向所有人开放：无需密钥、无需邀请、无需注册。本报道拆解完整时间表、测试包含与排除的内容，以及前后各需要做的事。",
      sourceNote: "基于 Steam 官方公告『Launch Scale Test Coming Up』（8 月 26 日）、AION 2 全球官网与 80 Level 8 月 27 日对公告与新预告的报道。",
      keywords: ["Aion 2 上线规模测试", "Aion 2 LST 时间", "Aion 2 9月17日测试", "Aion 2 内测", "Aion 2 9月16日预载"],
      sections: [
        section("schedule", "完整时间表", ["预载 9 月 16 日开放：从 6:00 PDT（15:00 CEST）持续到 9 月 17 日 6:00 PDT（15:00 CEST）——整整 24 小时窗口安装测试端。", "第 1 天 9 月 17 日 6:00-12:00 PDT（15:00-21:00 CEST）；第 2 天 9 月 18 日 12:00-18:00 PDT（9 月 18 日 21:00 至 9 月 19 日 03:00 CEST）。", "每日限玩 6 小时（共 12 小时）。全球官网确认日本时间窗口为第 1 天 22:00 JST、第 2 天 04:00-10:00 JST。"]),
        section("how-to-join", "如何加入", ["无需密钥、邀请或注册名单：LST 对 Steam 与 PURPLE 两个平台的所有人开放。", "Steam 端通过 Playtest 应用（store.steampowered.com/app/4972320）进入，9 月 16 日起可预载客户端。", "测试结束后，Steam 玩家须卸载 Playtest 应用，并于 9 月 30 日另行下载 AION 2 进入抢先体验。PURPLE 玩家无需额外操作。"]),
        section("content", "测试内容", ["角色最高升至 37 级，更高等级门控的内容不可达——重点在服务器压力与开篇体验，而非终局。", "环境包含游戏标志性开放世界结构：飞行战斗、阵营战争与大规模战斗，与最新一批预告展示一致。", "进度在第 1 天与第 2 天间延续；第 2 天结束时全部清空——不转入抢先体验或 10 月 5 日上线。"]),
        section("disabled", "已关闭内容", ["无任何购买：商店、Quna、通行证、会员与全部支付渠道停用。", "拍卖行、Quna 兑换与玩家间交易禁用，LST 期间不测试经济。", "创始人包物品不可用；更衣室禁用，测试期间仅限默认外观。"]),
        section("what-it-means", "意义", ["上线前三周开放免密钥规模测试，强烈表明 NCSoft 视 9 月 30 日抢先体验为真正上线，用 LST 做负载演练——你的反馈与服务器压力直接影响开服首周。", "对上线规划：把 LST 当作最佳实践窗口——预载客户端、调好画面设置、确认电脑可跑游戏。", "9 月 17-18 日将涌现大量视频与配置讨论；站内 PC 性能指南是搭配本测试的参考。"]),
      ],
    }),
    ko: articleCopy(newsLabels, "ko", 5, {
      eyebrow: "출시 규모 테스트",
      title: "Aion 2 출시 규모 테스트: 9월 17~18일 — 공개된 모든 정보",
      description: "NCSoft가 Aion 2 출시 규모 테스트(LST)를 9월 17~18일에 개최한다고 발표했습니다. 9월 16일 사전 다운로드, Steam·PURPLE 모두 오픈, 레벨 상한 37, 하루 6시간, 종료 시 전부 초기화됩니다.",
      intro: "8월 26일 NCSoft는 9월 30일 조기 접속과 10월 5일 무료 플레이 출시 전 마지막 대규모 리허설인 출시 규모 테스트(LST)를 9월 17~18일로 발표했습니다. 키·초청·등록 없이 모두에게 열려 있습니다. 일정, 포함·제외 내용, 사전·사후 준비를 정리합니다.",
      sourceNote: "Steam 공식 공지 'Launch Scale Test Coming Up'(8월 26일), Aion 2 글로벌 공식 사이트, 80 Level의 8월 27일 보도 기반입니다.",
      keywords: ["Aion 2 출시 규모 테스트", "Aion 2 LST 일정", "Aion 2 9월 17일 테스트", "Aion 2 비공개 테스트", "Aion 2 9월 16일 사전 다운로드"],
      sections: [
        section("schedule", "정확한 일정", "사전 다운로드는 9월 16일 06:00 PDT(15:00 CEST)부터 9월 17일 06:00 PDT(15:00 CEST)까지 24시간 열립니다. 1일차는 9월 17일 06:00~12:00 PDT, 2일차는 9월 18일 12:00~18:00 PDT입니다. 하루 6시간 한정, 일본 시간은 1일차 22:00 JST, 2일차 04:00~10:00 JST입니다."),
        section("how-to-join", "참여 방법", "키·초청·등록 없이 Steam과 PURPLE 모두 열려 있습니다. Steam은 Playtest 앱(store.steampowered.com/app/4972320)으로 접속하며 9월 16일부터 설치할 수 있습니다. 테스트 후 Steam 유저는 Playtest 앱을 삭제하고 9월 30일 조기 접속용 AION 2를 별도로 받아야 합니다. PURPLE은 추가 절차 없음."),
        section("content", "테스트 내용", "레벨 상한 37. 비행 전투, 진영 전쟁, 대규모 전투 등 오픈월드 구조를 체험할 수 있습니다. 진행은 1일차에서 2일차로 이어지며, 2일차 종료 시 모두 초기화되어 조기 접속이나 출시로 이전되지 않습니다."),
        section("disabled", "비활성화된 기능", "상점·Quna·패스·멤버십·결제 수단 모두 비활성화. 거래소, Quna 교환, 거래가 차단되어 경제 시스템은 테스트하지 않습니다. 파운더스 팩 아이템 없음, 옷장 비활성화로 기본 외형만 사용합니다."),
        section("what-it-means", "의미", "출시 3주 전 열린 무키 테스트는 NCSoft가 9월 30일 조기 접속을 실제 출시로 보고 LST를 부하 리허설로 삼는다는 신호입니다. LST를 최적화 연습 창구로 활용하세요. 9월 17~18일에는 영상과 빌드 논의가 쏟아질 예정입니다."),
      ],
    }),
    ja: articleCopy(newsLabels, "ja", 5, {
      eyebrow: "ローンチスケールテスト",
      title: "Aion 2 ローンチスケールテスト：9月17日〜18日 — 発表された全情報",
      description: "NCSoft は Aion 2 のローンチスケールテスト（LST）を9月17日〜18日に実施すると発表しました。9月16日事前DL、Steam・PURPLE とも参加自由、レベル上限37、1日6時間、終了時に全データ削除です。",
      intro: "8月26日、NCSoft は9月30日の早期アクセスと10月5日の無料プレイ前に最後の大規模リハーサルとなる LST を9月17日〜18日に開催すると発表しました。キー・招待・登録なしで全員参加可能です。正確な日程、含まれる内容と制限、前後の準備をまとめます。",
      sourceNote: "Steam 公式告知『Launch Scale Test Coming Up』（8月26日）、Aion 2 グローバル公式サイト、80 Level の8月27日報に基づきます。",
      keywords: ["Aion 2 ローンチスケールテスト", "Aion 2 LST 日程", "Aion 2 9月17日テスト", "Aion 2 ベータ", "Aion 2 9月16日事前DL"],
      sections: [
        section("schedule", "正確な日程", "事前DLは9月16日06:00 PDT（15:00 CEST）から9月17日06:00 PDT（15:00 CEST）まで24時間。1日目は9月17日06:00〜12:00 PDT、2日目は9月18日12:00〜18:00 PDT。1日6時間まで。日本時間は1日目22:00 JST、2日目は9月19日04:00〜10:00 JST。"),
        section("how-to-join", "参加方法", "キー・招待・登録リスト不要で Steam と PURPLE の全員に開放。Steam は Playtest アプリ（store.steampowered.com/app/4972320）から、9月16日より事前DL可。テスト後、Steam は Playtest アプリをアンインストールし、9月30日の早期アクセス用に AION 2 を別途DL。PURPLE は追加手続き不要。"),
        section("content", "テスト内容", "レベル上限37。飛行戦闘、陣営戦争、大規模バトルなどオープンワールド構造を体験可能。進行は1日目から2日目に引き継がれ、2日目終了時に全消去。早期アクセスやリリースへの移行はありません。"),
        section("disabled", "無効な機能", "ショップ・Quna・パス・メンバーシップ・決済手段はすべて停止。マーケットプレイス、Quna交換、取引も無効で経済はテストしません。ファウンダーズパックアイテムなし、クローゼット無効でデフォルト装備のみ。"),
        section("what-it-means", "意味", "発売3週間前のオープンテストは、NCSoft が9月30日を実質のローンチと見て LST を負荷リハーサルにしている証拠です。LST を事前DL・設定調整の練習窓口にしてください。9月17日〜18日は動画とビルド議論が盛り上がるでしょう。"),
      ],
    }),
    fr: articleCopy(newsLabels, "fr", 5, {
      eyebrow: "TEST À GRANDE ÉCHELLE",
      title: "Test à grande échelle d'Aion 2 : les 17-18 septembre — tout ce qui est annoncé",
      description: "NCSoft a annoncé le test à grande échelle (LST) d'Aion 2 pour les 17-18 septembre, préchargement le 16. Ouvert à tous sur Steam et PURPLE, niveau max 37, six heures par jour, progression effacée à la fin.",
      intro: "Le 26 août, NCSoft a annoncé un test à grande échelle (LST) pour Aion 2 les 17-18 septembre — la dernière répétition avant l'accès anticipé du 30 septembre et le lancement gratuit du 5 octobre. Ouvert à tous, sans clé ni inscription.",
      sourceNote: "Basé sur l'annonce Steam « Launch Scale Test Coming Up » (26 août), le site officiel mondial et la couverture de 80 Level du 27 août.",
      keywords: ["Aion 2 test à grande échelle", "Aion 2 dates LST", "Aion 2 test 17 septembre", "Aion 2 bêta", "Aion 2 préchargement 16 septembre"],
      sections: [
        section("schedule", "Le calendrier exact", "Préchargement le 16 septembre 6h-6h PDT ; Jour 1 le 17 septembre 6h-12h PDT ; Jour 2 le 18 septembre 12h-18h PDT. 6 heures par jour, 12 au total. En heure du Japon : 22h00 JST le jour 1, 04h00-10h00 JST le jour 2."),
        section("how-to-join", "Comment participer", "Sans clé, invitation ni inscription : ouvert à tous sur Steam et PURPLE. Sur Steam, via l'app Playtest, préchargement dès le 16 septembre. Après le test, désinstallez l'app et téléchargez AION 2 pour le 30 septembre."),
        section("content", "Contenu du test", "Niveau maximal 37. Monde ouvert, combat aérien, guerre de factions. La progression se poursuit du jour 1 au jour 2, puis tout est supprimé."),
        section("disabled", "Ce qui est désactivé", "Aucun achat ; Marketplace, échange Quna et trading désactivés ; objets des packs Fondateur indisponibles ; garde-robe désactivée, tenues par défaut seulement."),
        section("what-it-means", "Pourquoi c'est important", "Un test ouvert sans clé trois semaines avant le lancement montre que NCSoft traite le 30 septembre comme le vrai départ. Utilisez le LST pour préinstaller et régler vos options PC."),
      ],
    }),
    de: articleCopy(newsLabels, "de", 5, {
      eyebrow: "LAUNCH SCALE TEST",
      title: "Aion 2 Launch Scale Test: 17.–18. September — Alle Ankündigungen",
      description: "NCSoft hat den Launch Scale Test für Aion 2 für den 17.–18. September angekündigt, Vorabdownload am 16. September. Offen für alle auf Steam und PURPLE, Level-Cap 37, sechs Stunden pro Tag, Fortschritt wird gelöscht.",
      intro: "Am 26. August kündigte NCSoft einen Launch Scale Test (LST) für Aion 2 vom 17.–18. September an — die letzte Generalprobe vor dem Early Access am 30. September und dem Free-to-Play-Start am 5. Oktober. Ohne Key, ohne Einladung, ohne Registrierung.",
      sourceNote: "Basierend auf der offiziellen Steam-Ankündigung „Launch Scale Test Coming Up“ (26. August), der globalen offiziellen Seite und der Berichterstattung von 80 Level vom 27. August.",
      keywords: ["Aion 2 Launch Scale Test", "Aion 2 LST Termine", "Aion 2 Test 17. September", "Aion 2 Beta", "Aion 2 Vorabdownload 16. September"],
      sections: [
        section("schedule", "Der genaue Zeitplan", "Vorabdownload 16. September 6–6 Uhr PDT; Tag 1 am 17. September 6–12 Uhr PDT; Tag 2 am 18. September 12–18 Uhr PDT. 6 Stunden pro Tag, 12 gesamt. In Japan: 22:00 JST Tag 1, 04:00–10:00 JST Tag 2."),
        section("how-to-join", "So nimmst du teil", "Ohne Key, Einladung oder Registrierung: offen für alle auf Steam und PURPLE. Auf Steam über die Playtest-App, Vorabdownload ab 16. September. Danach App deinstallieren und AION 2 separat laden."),
        section("content", "Inhalt des Tests", "Maximallevel 37. Open World, Flugkampf, Fraktionskrieg. Fortschritt überträgt sich von Tag 1 auf Tag 2, danach wird alles gelöscht."),
        section("disabled", "Was abgeschaltet ist", "Keine Käufe; Marketplace, Quna-Tausch und Handel deaktiviert; Founder's-Pack-Items nicht verfügbar; Kleiderschrank deaktiviert, nur Standard-Outfits."),
        section("what-it-means", "Warum es zählt", "Ein offener Test ohne Key drei Wochen vor dem Start zeigt, dass NCSoft den 30. September als echten Launch behandelt. Nutze das LST zum Vorladen und Einstellen deiner Grafikoptionen."),
      ],
    }),
    es: articleCopy(newsLabels, "es", 5, {
      eyebrow: "PRUEBA DE ESCALA",
      title: "Prueba de escala de Aion 2: 17-18 de septiembre — todo lo anunciado",
      description: "NCSoft anunció la prueba de escala (LST) de Aion 2 para el 17-18 de septiembre, precarga el 16. Abierta a todos en Steam y PURPLE, nivel máx. 37, seis horas al día, progreso borrado al final.",
      intro: "El 26 de agosto, NCSoft anunció una prueba de escala (LST) para Aion 2 del 17-18 de septiembre — el último ensayo antes del acceso anticipado del 30 de septiembre y el lanzamiento gratuito del 5 de octubre. Abierta a todos, sin claves ni registro.",
      sourceNote: "Basado en el anuncio oficial de Steam «Launch Scale Test Coming Up» (26 de agosto), el sitio oficial global y la cobertura de 80 Level del 27 de agosto.",
      keywords: ["Aion 2 prueba de escala", "Aion 2 fechas LST", "Aion 2 test 17 septiembre", "Aion 2 beta", "Aion 2 precarga 16 septiembre"],
      sections: [
        section("schedule", "El calendario exacto", "Precarga el 16 de septiembre 6:00-6:00 PDT; día 1 el 17 de septiembre 6:00-12:00 PDT; día 2 el 18 de septiembre 12:00-18:00 PDT. 6 horas diarias, 12 en total. En Japón: 22:00 JST día 1, 04:00-10:00 JST día 2."),
        section("how-to-join", "Cómo participar", "Sin claves, invitaciones ni registro: abierta a todos en Steam y PURPLE. En Steam vía la app Playtest, precarga desde el 16. Después, desinstala la app y descarga AION 2 para el 30 de septiembre."),
        section("content", "Contenido de la prueba", "Nivel máximo 37. Mundo abierto, combate aéreo, guerra de facciones. El progreso continúa del día 1 al día 2 y luego se borra todo."),
        section("disabled", "Qué está desactivado", "Sin compras; Marketplace, intercambio Quna y trading desactivados; objetos de packs de fundador no disponibles; armario desactivado, solo atuendos por defecto."),
        section("what-it-means", "Por qué importa", "Una prueba abierta sin claves tres semanas antes del lanzamiento muestra que NCSoft trata el 30 de septiembre como el inicio real. Usa el LST para preinstalar y ajustar tus opciones gráficas."),
      ],
    }),
    "pt-br": articleCopy(newsLabels, "pt-br", 5, {
      eyebrow: "TESTE DE ESCALA",
      title: "Teste de escala do Aion 2: 17-18 de setembro — tudo que foi anunciado",
      description: "A NCSoft anunciou o teste de escala (LST) do Aion 2 para 17-18 de setembro, pré-download no dia 16. Aberto a todos na Steam e PURPLE, nível máx. 37, seis horas por dia, progresso apagado no final.",
      intro: "Em 26 de agosto, a NCSoft anunciou um teste de escala (LST) para o Aion 2 em 17-18 de setembro — o último ensaio antes do acesso antecipado de 30 de setembro e do lançamento gratuito de 5 de outubro. Aberto a todos, sem chaves nem registro.",
      sourceNote: "Com base no anúncio oficial da Steam «Launch Scale Test Coming Up» (26 de agosto), no site oficial global e na cobertura da 80 Level de 27 de agosto.",
      keywords: ["Aion 2 teste de escala", "Aion 2 datas LST", "Aion 2 teste 17 setembro", "Aion 2 beta", "Aion 2 pré-download 16 setembro"],
      sections: [
        section("schedule", "O cronograma exato", "Pré-download em 16 de setembro 6h-6h PDT; dia 1 em 17 de setembro 6h-12h PDT; dia 2 em 18 de setembro 12h-18h PDT. 6 horas por dia, 12 no total. No Japão: 22:00 JST dia 1, 04:00-10:00 JST dia 2."),
        section("how-to-join", "Como participar", "Sem chaves, convites ou registro: aberto a todos na Steam e PURPLE. Na Steam via app Playtest, pré-download a partir do dia 16. Depois, desinstale o app e baixe o AION 2 para 30 de setembro."),
        section("content", "Conteúdo do teste", "Nível máximo 37. Mundo aberto, combate aéreo, guerra de facções. O progresso continua do dia 1 ao dia 2 e depois tudo é apagado."),
        section("disabled", "O que está desativado", "Sem compras; Marketplace, troca Quna e negociação desativados; itens de pacotes de fundador indisponíveis; armário desativado, apenas visuais padrão."),
        section("what-it-means", "Por que importa", "Um teste aberto sem chaves três semanas antes do lançamento mostra que a NCSoft trata 30 de setembro como o início real. Use o LST para pré-instalar e ajustar suas opções gráficas."),
      ],
    }),
    ru: articleCopy(newsLabels, "ru", 5, {
      eyebrow: "МАСШТАБНЫЙ ТЕСТ",
      title: "Масштабный запуск-тест Aion 2: 17–18 сентября — всё, что анонсировано",
      description: "NCSoft анонсировала масштабный запуск-тест (LST) Aion 2 на 17–18 сентября, предзагрузка 16-го. Открыт для всех в Steam и PURPLE, кап уровня 37, шесть часов в день, прогресс стирается.",
      intro: "26 августа NCSoft анонсировала масштабный запуск-тест (LST) Aion 2 на 17–18 сентября — последнюю репетицию перед ранним доступом 30 сентября и бесплатным запуском 5 октября. Открыт для всех: без ключей, приглашений и регистрации.",
      sourceNote: "На основе официального анонса Steam «Launch Scale Test Coming Up» (26 августа), глобального официального сайта и материала 80 Level от 27 августа.",
      keywords: ["Aion 2 масштабный тест", "Aion 2 даты LST", "Aion 2 тест 17 сентября", "Aion 2 бета", "Aion 2 предзагрузка 16 сентября"],
      sections: [
        section("schedule", "Точное расписание", "Предзагрузка 16 сентября 6:00–6:00 PDT; день 1 — 17 сентября 6:00–12:00 PDT; день 2 — 18 сентября 12:00–18:00 PDT. 6 часов в день, 12 всего. В Японии: 22:00 JST день 1, 04:00–10:00 JST день 2."),
        section("how-to-join", "Как участвовать", "Без ключей, приглашений и регистрации: открыт для всех в Steam и PURPLE. В Steam через Playtest-приложение, предзагрузка с 16-го. После теста удалите приложение и скачайте AION 2 отдельно к 30 сентября."),
        section("content", "Содержание теста", "Максимальный уровень 37. Открытый мир, воздушный бой, война фракций. Прогресс переносится с дня 1 на день 2, затем всё стирается."),
        section("disabled", "Что отключено", "Никаких покупок; маркетплейс, обмен Quna и торговля отключены; предметы наборов основателя недоступны; гардероб отключён, только стандартные наряды."),
        section("what-it-means", "Почему это важно", "Открытый тест без ключей за три недели до запуска показывает, что NCSoft считает 30 сентября реальным стартом. Используйте LST для предустановки и настройки графики."),
      ],
    }),
    "zh-hant": articleCopy(newsLabels, "zh-hant", 5, {
      eyebrow: "上線規模測試",
      title: "Aion 2 上線規模測試：9 月 17-18 日——全部已公布資訊",
      description: "NCSoft 公布 Aion 2 上線規模測試定於 9 月 17-18 日，9 月 16 日開放預載。Steam 與 PURPLE 雙平台、無需資格、等級上限 37、每日 6 小時，測試結束全部進度清空。",
      intro: "8 月 26 日 NCSoft 公布 Aion 2 上線規模測試（LST）定於 9 月 17-18 日——這是 9 月 30 日搶先體驗與 10 月 5 日免費遊玩上線前的最後一次大規模演練。測試向所有人開放：無需密鑰、無需邀請、無需註冊。本報導拆解完整時間表、測試包含與排除的內容，以及前後各需要做的事。",
      sourceNote: "基於 Steam 官方公告『Launch Scale Test Coming Up』（8 月 26 日）、AION 2 全球官網與 80 Level 8 月 27 日對公告與新預告的報導。",
      keywords: ["Aion 2 上線規模測試", "Aion 2 LST 時間", "Aion 2 9月17日測試", "Aion 2 內測", "Aion 2 9月16日預載"],
      sections: [
        section("schedule", "完整時間表", ["預載 9 月 16 日開放：從 6:00 PDT（15:00 CEST）持續到 9 月 17 日 6:00 PDT（15:00 CEST）——整整 24 小時視窗安裝測試端。", "第 1 天 9 月 17 日 6:00-12:00 PDT（15:00-21:00 CEST）；第 2 天 9 月 18 日 12:00-18:00 PDT（9 月 18 日 21:00 至 9 月 19 日 03:00 CEST）。", "每日限玩 6 小時（共 12 小時）。全球官網確認日本時間視窗為第 1 天 22:00 JST、第 2 天 04:00-10:00 JST。"]),
        section("how-to-join", "如何加入", ["無需密鑰、邀請或註冊名單：LST 對 Steam 與 PURPLE 兩個平台的所有人開放。", "Steam 端透過 Playtest 應用（store.steampowered.com/app/4972320）進入，9 月 16 日起可預載用戶端。", "測試結束後，Steam 玩家須解除安裝 Playtest 應用，並於 9 月 30 日另行下載 AION 2 進入搶先體驗。PURPLE 玩家無需額外操作。"]),
        section("content", "測試內容", ["角色最高升至 37 級，更高等級門控的內容不可達——重點在伺服器壓力與開篇體驗，而非終局。", "環境包含遊戲標誌性開放世界結構：飛行戰鬥、陣營戰爭與大規模戰鬥，與最新一批預告展示一致。", "進度在第 1 天與第 2 天間延續；第 2 天結束時全部清空——不轉入搶先體驗或 10 月 5 日上線。"]),
        section("disabled", "已關閉內容", ["無任何購買：商店、Quna、通行證、會員與全部支付管道停用。", "拍賣行、Quna 兌換與玩家間交易禁用，LST 期間不測試經濟。", "創始人包物品不可用；更衣室禁用，測試期間僅限預設外觀。"]),
        section("what-it-means", "意義", ["上線前三週開放免密鑰規模測試，強烈表明 NCSoft 視 9 月 30 日搶先體驗為真正上線，用 LST 做負載演練——你的回饋與伺服器壓力直接影響開服首週。", "對上線規劃：把 LST 當作最佳實務視窗——預載用戶端、調好畫面設定、確認電腦可跑遊戲。", "9 月 17-18 日將湧現大量影片與配置討論；站內 PC 效能指南是搭配本測試的參考。"]),
      ],
    }),
  },
};