import { articleCopy, localizations, newsLabels, publishedVerified, section } from "./trending-september-2-shared";
import type { ContentEntry, ContentHeroImage, ContentSource } from "./content-registry";

/* ARTICLE 2 — NVIDIA DLSS 5 officially releases Sept 4, 2026; Aion 2 on the confirmed support list (no date) */

const dlssSource1: ContentSource = {
  id: "nvidia-dlss5-release-2026-09-01",
  kind: "third-party", publisher: "NVIDIA",
  label: "DLSS 5 Launches In NBA 2K27 September 3rd. Plus DLSS Comes To STAR WARS Zero Company™, Onimusha: Way of the Sword & The Blood of Dawnwalker",
  url: "https://www.nvidia.com/en-us/geforce/news/dlss-5-launch/",
  publishedAt: "2026-09-01",
  retrievedAt: "2026-09-02",
  verifiedAt: "2026-09-02",
  localizations: localizations({
    "zh-hans": "DLSS 5 于 9 月 3 日随 NBA 2K27 首发，并扩展至多款作品",
    en: "DLSS 5 Launches In NBA 2K27 September 3rd; expands to more titles",
    fr: "Le DLSS 5 arrive avec NBA 2K27 le 3 septembre et s'étend à d'autres titres",
    de: "DLSS 5 startet am 3. September mit NBA 2K27 und erweitert sich auf weitere Titel",
    es: "DLSS 5 llega con NBA 2K27 el 3 de septiembre y se expande a más títulos",
    ja: "DLSS 5 はNBA 2K27で9月3日に開始、さらに他タイトルへ拡大",
    "pt-br": "DLSS 5 chega com NBA 2K27 em 3 de setembro e se expande a mais títulos",
    ru: "DLSS 5 стартует с NBA 2K27 3 сентября и расширяется на другие игры",
    ko: "DLSS 5, NBA 2K27로 9월 3일 시작, 더 많은 타이틀로 확대",
    "zh-hant": "DLSS 5 於 9 月 3 日隨 NBA 2K27 首發，並擴展至多款作品",
  }, "https://www.nvidia.com/en-us/geforce/news/dlss-5-launch/"),
};

const dlssSource2: ContentSource = {
  id: "dsogaming-dlss5-2026-09-01",
  kind: "third-party", publisher: "DSOGaming",
  label: "NVIDIA DLSS 5 Will Be Officially Released on September 4th",
  url: "https://www.dsogaming.com/news/nvidia-dlss-5-will-be-officially-released-on-september-4th/",
  publishedAt: "2026-09-01",
  retrievedAt: "2026-09-02",
  verifiedAt: "2026-09-02",
  localizations: localizations({
    "zh-hans": "NVIDIA DLSS 5 将于 9 月 4 日正式发布",
    en: "NVIDIA DLSS 5 Will Be Officially Released on September 4th",
    fr: "Le DLSS 5 de NVIDIA sortira officiellement le 4 septembre",
    de: "NVIDIA DLSS 5 wird offiziell am 4. September veröffentlicht",
    es: "NVIDIA DLSS 5 se lanzará oficialmente el 4 de septiembre",
    ja: "NVIDIA DLSS 5 は9月4日に正式リリースへ",
    "pt-br": "NVIDIA DLSS 5 será lançado oficialmente em 4 de setembro",
    ru: "NVIDIA DLSS 5 официально выйдет 4 сентября",
    ko: "NVIDIA DLSS 5가 9월 4일 공식 출시됩니다",
    "zh-hant": "NVIDIA DLSS 5 將於 9 月 4 日正式發布",
  }, "https://www.dsogaming.com/news/nvidia-dlss-5-will-be-officially-released-on-september-4th/"),
};

const dlssHero: ContentHeroImage = {
  src: "https://blogfiles.ncsoft.net/news/af7330da-4ff6-4b58-aece-400e6061a3be.jpg",
  width: 1100, height: 605,
  credit: "NC Corporation",
  sourceUrl: "https://aion2.plaync.com/ja-jp/board/notice/list",
  rights: "linked-official-media",
  translations: {
    "zh-hans": { alt: "Aion 2 DLSS 5 新闻配图", caption: "NC 官方配图；NVIDIA DLSS 5 于 2026 年 9 月 4 日官方发布，Aion 2 位列首批确认支持名单（补丁日期未定，仅 RTX 50 系列）。" },
    en: { alt: "Aion 2 DLSS 5 news image", caption: "Official NC artwork; NVIDIA DLSS 5 releases officially September 4, 2026, with Aion 2 on the confirmed support list (patch date not set, RTX 50 series only)." },
    fr: { alt: "Image DLSS 5 d'Aion 2", caption: "Visuel officiel NC ; le DLSS 5 de NVIDIA sort officiellement le 4 septembre 2026, Aion 2 étant sur la liste de support confirmée (date de patch non fixée, RTX 50 uniquement)." },
    de: { alt: "Bild zu Aion 2 und DLSS 5", caption: "Offizielles NC-Artwork; NVIDIA DLSS 5 erscheint offiziell am 4. September 2026, Aion 2 steht auf der bestätigten Support-Liste (Patch-Termin offen, nur RTX 50)." },
    es: { alt: "Imagen de Aion 2 y DLSS 5", caption: "Arte oficial de NC; NVIDIA DLSS 5 se lanza oficialmente el 4 de septiembre de 2026, con Aion 2 en la lista de soporte confirmada (fecha de parche sin fijar, solo RTX 50)." },
    ja: { alt: "Aion 2 DLSS 5 ニュース画像", caption: "NC公式アートワーク；NVIDIA DLSS 5 は2026年9月4日に正式リリースされ、Aion 2 は確認済みサポートリストに入っています（パッチ日未定、RTX 50シリーズのみ）。" },
    "pt-br": { alt: "Imagem de Aion 2 e DLSS 5", caption: "Arte oficial da NC; o NVIDIA DLSS 5 é lançado oficialmente em 4 de setembro de 2026, com o Aion 2 na lista confirmada de suporte (data de patch indefinida, apenas RTX 50)." },
    ru: { alt: "Изображение Aion 2 и DLSS 5", caption: "Официальный арт NC; NVIDIA DLSS 5 официально выходит 4 сентября 2026, Aion 2 в подтверждённом списке поддержки (дата патча не назначена, только RTX 50)." },
    ko: { alt: "Aion 2 DLSS 5 뉴스 이미지", caption: "NC 공식 이미지입니다. NVIDIA DLSS 5는 2026년 9월 4일 공식 출시되며, 아이온2가 확인된 지원 목록에 있습니다(패치 날짜 미정, RTX 50 시리즈만)." },
    "zh-hant": { alt: "Aion 2 DLSS 5 新聞配圖", caption: "NC 官方配圖；NVIDIA DLSS 5 於 2026 年 9 月 4 日官方發布，Aion 2 位列首批確認支援名單（補丁日期未定，僅 RTX 50 系列）。" },
  },
};

export const trendingSeptember2Article2: ContentEntry = {
  section: "news",
  slug: "aion-2-dlss-5-support-release-september",
  schemaType: "NewsArticle",
  publishedAt: "2026-09-02",
  updatedAt: "2026-09-02",
  readingMinutes: 5,
  publication: publishedVerified,
  sources: [dlssSource1, dlssSource2],
  heroImage: dlssHero,
  related: [
    { kind: "content", section: "guides", slug: "aion-2-dlss-45-rtx-support-guide" },
    { kind: "content", section: "guides", slug: "aion-2-pc-performance-guide" },
    { kind: "content", section: "news", slug: "aion-2-steam-store-countdown-four-weeks" },
    { kind: "content", section: "guides", slug: "aion-2-global-version-changes-guide" },
  ],
  translations: {
    en: articleCopy(newsLabels, "en", 5, {
      eyebrow: "DLSS 5",
      title: "Aion 2 on the DLSS 5 List: NVIDIA's Next Upscaling Launches September 4",
      description: "NVIDIA's DLSS 5 officially launches September 4, 2026, with NBA 2K27 first and Aion 2 on the confirmed list of titles set to support it — patch dates not yet set, RTX 50 series only. Here is what the launch means for Aion 2 players.",
      intro: "On September 1, 2026, NVIDIA announced DLSS 5's official release for September 4, with NBA 2K27 as the first title — and Aion 2 is on the confirmed list of games set to support it, alongside Assassin's Creed Shadows, Cinder City, Starfield, and others. Patch dates for those titles are not yet set, and support is RTX 50 series only. This report covers the announcement, what it does and does not promise for Aion 2, and how it relates to the DLSS 4.5 support NCsoft already confirmed.",
      sourceNote: "Based on NVIDIA's September 1, 2026 announcement and DSOGaming's September 1 report on the official release date; Aion 2's pre-existing DLSS 4.5 support was previously documented on this site (see our DLSS guide).",
      keywords: ["Aion 2 DLSS 5", "DLSS 5 September 4", "Aion 2 DLSS support list", "NVIDIA DLSS 5 Aion 2", "Aion 2 RTX 50"],
      sections: [
        section("the-announcement", "What NVIDIA Announced", ["NVIDIA's September 1 announcement names DLSS 5's official release on September 4, 2026, with NBA 2K27 first on September 3; DSOGaming confirms the September 4 date.", "Aion 2 is listed among “the first games set to support DLSS 5”: AION 2, Assassin's Creed Shadows, Black State, CINDER CITY, Delta Force, Hogwarts Legacy, Justice, NARAKA: BLADEPOINT, NTE: Neverness to Everness, Resident Evil Requiem, Sea of Remnants, Starfield, The Elder Scrolls IV: Oblivion Remastered, and Where Winds Meet.", "Crucially, these are future-support titles: “we do not yet know when these games will get their DLSS 5 updates.” NBA 2K27 is the only launch-day title."]),
        section("for-aion2", "What It Means for Aion 2", ["Aion 2 being on the list confirms DLSS 5 is planned — but with no patch date. It is a roadmap statement from NVIDIA's side, not a launch feature of the October 5 global release.", "The game's currently confirmed upscaling support is DLSS 4.5 (as documented on this site); DLSS 5 will arrive later, as a separate update, once NVIDIA and the game team ship it.", "Practical expectation: at the October 5 launch, players should rely on the confirmed DLSS 4.5 path; DLSS 5 is a future upgrade, not a day-one feature."]),
        section("hardware", "Hardware Requirement: RTX 50 Series", ["DLSS 5 is officially supported only on the NVIDIA RTX 50 series GPUs, per DSOGaming. Modders may get it running on older GPUs, but NVIDIA's official position is 50-series only.", "That narrows the audience: if you are planning to use DLSS 5 in Aion 2, the RTX 50-series requirement is the same hardware gate as other DLSS 5 titles.", "For players on RTX 40 or older, the DLSS 4.5 path NCsoft confirmed remains the relevant upscaling option at launch."]),
        section("performance-context", "The Performance Context", ["DSOGaming reports NVIDIA stating the performance cost of an official DLSS 5 implementation is around 50–60% — a non-trivial overhead that games must be built or patched to absorb.", "NVIDIA also reports DLSS 5 performance has been improved over five times since March 2026, and that Multi-Frame Generation is enabled with DLSS 5.", "For an MMO with large-scale PvP and open-world population spikes, the practical question will be how Aion 2's implementation balances DLSS 5's cost against crowded-screen scenarios."]),
        section("takeaway", "The Takeaway", ["DLSS 5 officially launches September 4, 2026; Aion 2 is confirmed for future support with no date, RTX 50 series only.", "At the October 5 global launch, rely on the confirmed DLSS 4.5 support; treat DLSS 5 as a follow-up upgrade to watch for rather than a day-one feature.", "Bookmark NVIDIA's announcement as the authoritative roadmap: when Aion 2's DLSS 5 patch is dated, it will appear there first."]),
      ],
    }),
    "zh-hans": articleCopy(newsLabels, "zh-hans", 5, {
      eyebrow: "DLSS 5",
      title: "Aion 2 列入 DLSS 5 名单：NVIDIA 新一代超分辨率 9 月 4 日发布",
      description: "NVIDIA DLSS 5 于 2026 年 9 月 4 日官方发布，NBA 2K27 首发，Aion 2 位列首批确认支持名单——补丁日期未定，仅 RTX 50 系列。以下是该发布对 Aion 2 玩家的意义。",
      intro: "2026 年 9 月 1 日，NVIDIA 宣布 DLSS 5 于 9 月 4 日正式发布，NBA 2K27 为首款作品——而 Aion 2 位列确认支持名单，与《刺客信条：影》、Cinder City、Starfield 等并列。这些作品的补丁日期未定，支持仅限 RTX 50 系列。本报告覆盖公告内容、它对 Aion 2 承诺了什么与没承诺什么，以及它与 NCsoft 已确认的 DLSS 4.5 支持的关系。",
      sourceNote: "基于 NVIDIA 2026-09-01 公告与 DSOGaming 9 月 1 日关于官方发布日期的报道；Aion 2 此前的 DLSS 4.5 支持已由本站记录（见 DLSS 指南）。",
      keywords: ["Aion 2 DLSS 5", "DLSS 5 9月4日", "Aion 2 DLSS 支持名单", "NVIDIA DLSS 5 Aion 2", "Aion 2 RTX 50"],
      sections: [
        section("the-announcement", "NVIDIA 公布了什么", ["NVIDIA 9 月 1 日公告将 DLSS 5 官方发布定为 2026 年 9 月 4 日，NBA 2K27 于 9 月 3 日首发；DSOGaming 确认 9 月 4 日。", "Aion 2 位列「首批将支持 DLSS 5 的作品」：AION 2、《刺客信条：影》、Black State、CINDER CITY、三角洲行动、霍格沃茨之遗、Justice、永劫无间、NTE、生化危机：安魂曲、Sea of Remnants、星空、上古卷轴 IV：湮灭重制版、Where Winds Meet。", "关键是这些是未来支持作品：「我们尚不知道这些游戏何时获得 DLSS 5 更新。」NBA 2K27 是唯一首发日作品。"]),
        section("for-aion2", "对 Aion 2 的意义", ["Aion 2 在名单上确认了 DLSS 5 有计划——但无补丁日期。这是来自 NVIDIA 侧的路线图声明，而非 10 月 5 日全球上线的首发功能。", "游戏当前已确认的超分辨率支持是 DLSS 4.5（本站已记录）；DLSS 5 将作为后续独立更新到来。", "务实预期：10 月 5 日上线时，玩家应依赖已确认的 DLSS 4.5 路径；DLSS 5 是未来升级，不是首日功能。"]),
        section("hardware", "硬件要求：RTX 50 系列", ["据 DSOGaming，DLSS 5 官方仅支持 NVIDIA RTX 50 系列 GPU。Modder 或可让它在旧 GPU 上运行，但官方立场是仅 50 系列。", "这缩小了受众：若你计划在 Aion 2 中使用 DLSS 5，RTX 50 系列要求与其他 DLSS 5 作品相同。", "对 RTX 40 及更旧的玩家，NCsoft 确认的 DLSS 4.5 路径仍是上线时的相关超分辨率选项。"]),
        section("performance-context", "性能语境", ["DSOGaming 报道 NVIDIA 表示官方 DLSS 5 实现的性能开销约 50–60%——这是游戏必须构建或打补丁才能吸收的非平凡开销。", "NVIDIA 还称自 2026 年 3 月以来 DLSS 5 性能已改善五倍以上，且 DLSS 5 启用多帧生成。", "对含大规模 PvP 与开放世界人口尖峰的 MMO，实际问题将是 Aion 2 的实现如何在拥挤屏幕场景下平衡 DLSS 5 的开销。"]),
        section("takeaway", "结论", ["DLSS 5 于 2026 年 9 月 4 日正式发布；Aion 2 确认未来支持但无日期，仅 RTX 50 系列。", "在 10 月 5 日全球上线时，依赖已确认的 DLSS 4.5 支持；把 DLSS 5 当作后续升级关注，而非首日功能。", "把 NVIDIA 公告设为权威路线图：Aion 2 的 DLSS 5 补丁一旦定档，会先出现在那里。"]),
      ],
    }),
    ko: articleCopy(newsLabels, "ko", 5, {
      eyebrow: "DLSS 5",
      title: "아이온2, DLSS 5 목록에 — NVIDIA 차세대 업스케일 9월 4일 출시",
      description: "NVIDIA DLSS 5가 2026년 9월 4일 공식 출시되며 NBA 2K27이 첫 타이틀, 아이온2는 확인된 지원 목록에 있습니다 — 패치 날짜 미정, RTX 50 시리즈만.",
      intro: "2026년 9월 1일 NVIDIA가 DLSS 5의 9월 4일 공식 출시를 발표했고, 아이온2가 지원 목록에 포함됐습니다. 본 기사는 발표 내용과 아이온2에게 주는 의미, 기존 DLSS 4.5 지원과의 관계를 정리합니다.",
      sourceNote: "NVIDIA 9월 1일 발표와 DSOGaming 9월 1일 보도를 기반으로 하며, 아이온2의 기존 DLSS 4.5 지원은 이 사이트가 이미 기록했습니다.",
      keywords: ["아이온2 DLSS 5", "DLSS 5 9월 4일", "아이온2 DLSS 지원 목록", "NVIDIA DLSS 5 아이온2", "아이온2 RTX 50"],
      sections: [
        section("the-announcement", "NVIDIA가 발표한 것", "NVIDIA는 DLSS 5 공식 출시를 2026년 9월 4일로, NBA 2K27을 9월 3일 첫 타이틀로 발표했습니다. 아이온2는 'DLSS 5를 지원할 첫 작품' 목록에 포함됐지만, '이 게임들이 언제 DLSS 5 업데이트를 받을지는 아직 모른다'고 명시했습니다. NBA 2K27만 출시일 타이틀입니다."),
        section("for-aion2", "아이온2에게 주는 의미", "목록 포함은 DLSS 5 지원 계획을 확인하지만 패치 날짜는 없습니다. 이는 NVIDIA 쪽 로드맵 성명이지 10월 5일 글로벌 출시의 기본 기능이 아닙니다. 현재 확인된 업스케일링 지원은 DLSS 4.5이며, DLSS 5는 이후 별도 업데이트로 옵니다."),
        section("hardware", "하드웨어 요구: RTX 50 시리즈", "DLSS 5는 공식적으로 NVIDIA RTX 50 시리즈 GPU만 지원합니다. RTX 40 이하 플레이어에게는 확인된 DLSS 4.5 경로가 출시 시 관련 옵션입니다."),
        section("performance-context", "성능 맥락", "DSOGaming에 따르면 NVIDIA는 공식 DLSS 5 구현의 성능 비용이 약 50–60%라고 밝혔으며, 2026년 3월 이후 DLSS 5 성능을 5배 이상 개선했고 멀티 프레임 생성이 활성화됩니다. 대규모 PvP MMO에서 구현이 어떻게 균형을 잡을지가 실질적 질문입니다."),
        section("takeaway", "결론", "DLSS 5는 2026년 9월 4일 공식 출시, 아이온2는 날짜 없는 미래 지원 확정(RTX 50 시리즈만). 10월 5일 출시에서는 확인된 DLSS 4.5를 사용하고, DLSS 5는 후속 업그레이드로 지켜보세요."),
      ],
    }),
    ja: articleCopy(newsLabels, "ja", 5, {
      eyebrow: "DLSS 5",
      title: "Aion 2 が DLSS 5 リストに — NVIDIA次世代アップスケールが9月4日リリース",
      description: "NVIDIA DLSS 5 が2026年9月4日に正式リリースされ、NBA 2K27 が第一弾、Aion 2 は確認済みサポートリストに含まれます — パッチ日未定、RTX 50シリーズのみ。",
      intro: "2026年9月1日、NVIDIA が DLSS 5 の9月4日公式リリースを発表し、Aion 2 がサポートリストに入りました。本記事は発表内容とアイオン2への意味、既存のDLSS 4.5サポートとの関係を整理します。",
      sourceNote: "NVIDIA 9月1日発表とDSOGaming 9月1日報道に基づきます。Aion 2 の既存DLSS 4.5サポートは当サイトが既に記録しています。",
      keywords: ["Aion 2 DLSS 5", "DLSS 5 9月4日", "Aion 2 DLSS サポートリスト", "NVIDIA DLSS 5 Aion 2", "Aion 2 RTX 50"],
      sections: [
        section("the-announcement", "NVIDIAが発表したこと", "NVIDIA は DLSS 5 の公式リリースを2026年9月4日、NBA 2K27 を9月3日の第一弾と発表しました。Aion 2 は「DLSS 5 をサポートする最初の作品」リストに入りましたが、「いつアップデートされるかは未定」と明記されています。NBA 2K27 のみ発売日タイトルです。"),
        section("for-aion2", "アイオン2への意味", "リスト入りは DLSS 5 対応計画を確認しますが、パッチ日はありません。これは NVIDIA 側のロードマップであり、10月5日グローバル発売の基本機能ではありません。現在確認済みのアップスケーリングは DLSS 4.5 で、DLSS 5 は後の別更新です。"),
        section("hardware", "ハードウェア要件: RTX 50シリーズ", "DLSS 5 は公式には NVIDIA RTX 50 シリーズGPUのみ対応です。RTX 40 以下のプレイヤーには、確認済みの DLSS 4.5 が発売時点の関連オプションです。"),
        section("performance-context", "性能の文脈", "DSOGaming によると NVIDIA は公式 DLSS 5 実装の性能コストを約50–60%とし、2026年3月以降5倍以上改善し、マルチフレーム生成が有効化されます。大規模PvP MMOで実装がどうバランスを取るかが実質的な問いです。"),
        section("takeaway", "結論", "DLSS 5 は2026年9月4日公式リリース、アイオン2は日付なしの将来サポート確定（RTX 50のみ）。10月5日発売では確認済みの DLSS 4.5 を使い、DLSS 5 は後続アップグレードとして見守ってください。"),
      ],
    }),
    fr: articleCopy(newsLabels, "fr", 5, {
      eyebrow: "DLSS 5",
      title: "Aion 2 sur la liste DLSS 5 : le nouveau suréchantillonnage NVIDIA sort le 4 septembre",
      description: "Le DLSS 5 de NVIDIA sort officiellement le 4 septembre 2026, NBA 2K27 en premier et Aion 2 sur la liste confirmée des titres qui le supporteront — dates de patch non fixées, RTX 50 uniquement.",
      intro: "Le 1er septembre 2026, NVIDIA a annoncé la sortie officielle du DLSS 5 pour le 4 septembre, avec NBA 2K27 en premier — et Aion 2 figure sur la liste confirmée. Cet article couvre l'annonce, ce qu'elle promet (ou non) pour Aion 2, et le lien avec le DLSS 4.5 déjà confirmé.",
      sourceNote: "Basé sur l'annonce NVIDIA du 1er septembre 2026 et le report de DSOGaming du 1er septembre ; le support DLSS 4.5 d'Aion 2 a déjà été documenté sur ce site.",
      keywords: ["Aion 2 DLSS 5", "DLSS 5 4 septembre", "Aion 2 liste DLSS", "NVIDIA DLSS 5 Aion 2", "Aion 2 RTX 50"],
      sections: [
        section("the-announcement", "Ce que NVIDIA a annoncé", "Sortie officielle le 4 septembre 2026, NBA 2K27 en premier le 3 septembre. Aion 2 figure parmi « les premiers jeux prêts à supporter le DLSS 5 » mais « on ne sait pas encore quand » — NBA 2K27 est le seul titre du jour du lancement."),
        section("for-aion2", "Ce que ça veut dire pour Aion 2", "La présence sur la liste confirme un DLSS 5 prévu, sans date. C'est un énoncé de feuille de route côté NVIDIA, pas une fonctionnalité de lancement du 5 octobre. Le support confirmé actuel est le DLSS 4.5 ; le DLSS 5 viendra plus tard."),
        section("hardware", "Matériel requis : RTX 50", "Le DLSS 5 n'est officiellement supporté que sur les RTX 50. Pour les RTX 40 et moins, le DLSS 4.5 confirmé reste l'option pertinente au lancement."),
        section("performance-context", "Contexte de performance", "NVIDIA chiffre le coût d'une implémentation DLSS 5 à environ 50–60 %, a amélioré les performances de plus de cinq fois depuis mars 2026 et active la génération multi-images."),
        section("takeaway", "Conclusion", "DLSS 5 sort le 4 septembre 2026 ; Aion 2 est confirmé pour plus tard, sans date, RTX 50 uniquement. Au lancement, utilisez le DLSS 4.5 confirmé."),
      ],
    }),
    de: articleCopy(newsLabels, "de", 5, {
      eyebrow: "DLSS 5",
      title: "Aion 2 auf der DLSS-5-Liste: NVIDIA's nächstes Upscaling startet am 4. September",
      description: "NVIDIAs DLSS 5 erscheint offiziell am 4. September 2026, mit NBA 2K27 zuerst und Aion 2 auf der bestätigten Unterstützungsliste — Patch-Termine offen, nur RTX 50.",
      intro: "Am 1. September 2026 kündigte NVIDIA die offizielle DLSS-5-Veröffentlichung für den 4. September an, NBA 2K27 zuerst — und Aion 2 steht auf der bestätigten Liste. Dieser Artikel deckt die Ankündigung und ihre Bedeutung für Aion 2 ab.",
      sourceNote: "Basierend auf der NVIDIA-Ankündigung vom 1. September 2026 und dem DSOGaming-Bericht vom 1. September; Aion 2s bestehende DLSS-4.5-Unterstützung wurde hier bereits dokumentiert.",
      keywords: ["Aion 2 DLSS 5", "DLSS 5 4. September", "Aion 2 DLSS-Liste", "NVIDIA DLSS 5 Aion 2", "Aion 2 RTX 50"],
      sections: [
        section("the-announcement", "Was NVIDIA ankündigte", "Offizielle Veröffentlichung am 4. September 2026, NBA 2K27 zuerst am 3. September. Aion 2 steht auf der Liste „erster Spiele für DLSS 5“, aber „wann die Updates kommen, wissen wir noch nicht“ — nur NBA 2K27 ist Launch-Titel."),
        section("for-aion2", "Was es für Aion 2 bedeutet", "Die Listung bestätigt geplantes DLSS 5 ohne Datum — eine Roadmap-Aussage, kein Startfeature des 5. Oktober. Die bestätigte Unterstützung ist DLSS 4.5; DLSS 5 kommt später als separates Update."),
        section("hardware", "Hardware: RTX 50", "DLSS 5 offiziell nur auf RTX 50. Für RTX 40 und älter bleibt das bestätigte DLSS 4.5 die relevante Option."),
        section("performance-context", "Performance-Kontext", "NVIDIA beziffert die Kosten einer offiziellen DLSS-5-Implementierung auf rund 50–60 %, hat die Performance seit März 2026 um mehr als das Fünffache verbessert und Multi-Frame-Generation aktiviert."),
        section("takeaway", "Fazit", "DLSS 5 erscheint am 4. September 2026; Aion 2 ist für später bestätigt, ohne Datum, nur RTX 50. Beim Start das bestätigte DLSS 4.5 nutzen."),
      ],
    }),
    es: articleCopy(newsLabels, "es", 5, {
      eyebrow: "DLSS 5",
      title: "Aion 2 en la lista DLSS 5: el nuevo reescalado de NVIDIA sale el 4 de septiembre",
      description: "El DLSS 5 de NVIDIA sale oficialmente el 4 de septiembre de 2026, con NBA 2K27 primero y Aion 2 en la lista confirmada de títulos que lo soportarán — sin fecha de parche, solo RTX 50.",
      intro: "El 1 de septiembre de 2026, NVIDIA anunció el lanzamiento oficial del DLSS 5 para el 4 de septiembre, con NBA 2K27 primero — y Aion 2 está en la lista confirmada. Este informe cubre el anuncio y su significado para Aion 2.",
      sourceNote: "Basado en el anuncio de NVIDIA del 1 de septiembre de 2026 y el informe de DSOGaming del 1 de septiembre; el soporte DLSS 4.5 de Aion 2 ya está documentado en este sitio.",
      keywords: ["Aion 2 DLSS 5", "DLSS 5 4 de septiembre", "Aion 2 lista DLSS", "NVIDIA DLSS 5 Aion 2", "Aion 2 RTX 50"],
      sections: [
        section("the-announcement", "Qué anunció NVIDIA", "Lanzamiento oficial el 4 de septiembre de 2026, NBA 2K27 primero el 3 de septiembre. Aion 2 está en la lista de «primeros juegos listos para DLSS 5» pero «aún no sabemos cuándo» — solo NBA 2K27 es título del día."),
        section("for-aion2", "Qué significa para Aion 2", "Estar en la lista confirma DLSS 5 previsto sin fecha: una declaración de hoja de ruta, no una función del lanzamiento del 5 de octubre. El soporte confirmado es DLSS 4.5; DLSS 5 llegará después."),
        section("hardware", "Hardware: RTX 50", "DLSS 5 solo es oficial en RTX 50. Para RTX 40 y anteriores, el DLSS 4.5 confirmado sigue siendo la opción relevante."),
        section("performance-context", "Contexto de rendimiento", "NVIDIA cifra el coste de una implementación DLSS 5 en ~50–60 %, ha mejorado el rendimiento más de cinco veces desde marzo de 2026 y activa la generación multi-fotograma."),
        section("takeaway", "Conclusión", "DLSS 5 sale el 4 de septiembre de 2026; Aion 2 está confirmado para después, sin fecha, solo RTX 50. En el lanzamiento, usa el DLSS 4.5 confirmado."),
      ],
    }),
    "pt-br": articleCopy(newsLabels, "pt-br", 5, {
      eyebrow: "DLSS 5",
      title: "Aion 2 na lista DLSS 5: o novo upscaling da NVIDIA chega em 4 de setembro",
      description: "O DLSS 5 da NVIDIA é lançado oficialmente em 4 de setembro de 2026, com NBA 2K27 primeiro e o Aion 2 na lista confirmada de títulos que o suportarão — sem data de patch, apenas RTX 50.",
      intro: "Em 1º de setembro de 2026, a NVIDIA anunciou o lançamento oficial do DLSS 5 para 4 de setembro, com NBA 2K27 primeiro — e o Aion 2 está na lista confirmada. Este relatório cobre o anúncio e seu significado para o Aion 2.",
      sourceNote: "Com base no anúncio da NVIDIA de 1º de setembro de 2026 e no relato da DSOGaming de 1º de setembro; o suporte DLSS 4.5 do Aion 2 já está documentado neste site.",
      keywords: ["Aion 2 DLSS 5", "DLSS 5 4 de setembro", "Aion 2 lista DLSS", "NVIDIA DLSS 5 Aion 2", "Aion 2 RTX 50"],
      sections: [
        section("the-announcement", "O que a NVIDIA anunciou", "Lançamento oficial em 4 de setembro de 2026, NBA 2K27 primeiro em 3 de setembro. O Aion 2 está na lista de «primeiros jogos prontos para DLSS 5», mas «ainda não sabemos quando» — só o NBA 2K27 é título do dia."),
        section("for-aion2", "O que significa para o Aion 2", "Estar na lista confirma DLSS 5 planejado sem data: uma declaração de roteiro, não um recurso do lançamento de 5 de outubro. O suporte confirmado é DLSS 4.5; o DLSS 5 virá depois."),
        section("hardware", "Hardware: RTX 50", "DLSS 5 só é oficial em RTX 50. Para RTX 40 e anteriores, o DLSS 4.5 confirmado segue como a opção relevante."),
        section("performance-context", "Contexto de desempenho", "A NVIDIA estima o custo de uma implementação DLSS 5 em ~50–60 %, melhorou o desempenho mais de cinco vezes desde março de 2026 e ativa a geração de múltiplos quadros."),
        section("takeaway", "Conclusão", "DLSS 5 chega em 4 de setembro de 2026; o Aion 2 está confirmado para depois, sem data, apenas RTX 50. No lançamento, use o DLSS 4.5 confirmado."),
      ],
    }),
    ru: articleCopy(newsLabels, "ru", 5, {
      eyebrow: "DLSS 5",
      title: "Aion 2 в списке DLSS 5: новый апскейл NVIDIA выходит 4 сентября",
      description: "DLSS 5 от NVIDIA официально выходит 4 сентября 2026, NBA 2K27 первым, а Aion 2 — в подтверждённом списке игр с поддержкой (дата патча не назначена, только RTX 50).",
      intro: "1 сентября 2026 NVIDIA объявила официальный выход DLSS 5 на 4 сентября, NBA 2K27 первым — и Aion 2 есть в подтверждённом списке. Этот отчёт освещает анонс и его значение для Aion 2.",
      sourceNote: "На основе анонса NVIDIA от 1 сентября 2026 и отчёта DSOGaming от 1 сентября; существующая поддержка DLSS 4.5 у Aion 2 уже задокументирована на этом сайте.",
      keywords: ["Aion 2 DLSS 5", "DLSS 5 4 сентября", "Aion 2 список DLSS", "NVIDIA DLSS 5 Aion 2", "Aion 2 RTX 50"],
      sections: [
        section("the-announcement", "Что анонсировала NVIDIA", "Официальный выход 4 сентября 2026, NBA 2K27 первым 3 сентября. Aion 2 в списке «первых игр для DLSS 5», но «когда выйдут обновления, пока неизвестно» — только NBA 2K27 титул дня запуска."),
        section("for-aion2", "Что это значит для Aion 2", "Наличие в списке подтверждает планируемый DLSS 5 без даты — заявление о дорожной карте, не функция запуска 5 октября. Подтверждённая поддержка — DLSS 4.5; DLSS 5 придёт позже отдельным обновлением."),
        section("hardware", "Оборудование: RTX 50", "DLSS 5 официально только на RTX 50. Для RTX 40 и старше подтверждённый DLSS 4.5 остаётся актуальной опцией."),
        section("performance-context", "Контекст производительности", "NVIDIA оценивает стоимость официальной реализации DLSS 5 в ~50–60 %, улучшила производительность более чем в пять раз с марта 2026 и включает мультикадровую генерацию."),
        section("takeaway", "Вывод", "DLSS 5 выходит 4 сентября 2026; Aion 2 подтверждён на будущее без даты, только RTX 50. При запуске используйте подтверждённый DLSS 4.5."),
      ],
    }),
    "zh-hant": articleCopy(newsLabels, "zh-hant", 5, {
      eyebrow: "DLSS 5",
      title: "Aion 2 列入 DLSS 5 名單：NVIDIA 新一代超解析度 9 月 4 日發布",
      description: "NVIDIA DLSS 5 於 2026 年 9 月 4 日官方發布，NBA 2K27 首發，Aion 2 位列首批確認支援名單——補丁日期未定，僅 RTX 50 系列。",
      intro: "2026 年 9 月 1 日，NVIDIA 宣布 DLSS 5 於 9 月 4 日正式發布，NBA 2K27 為首款作品——而 Aion 2 位列確認支援名單。本報告覆蓋公告內容、它對 Aion 2 承諾了什麼，以及與已確認 DLSS 4.5 支援的關係。",
      sourceNote: "基於 NVIDIA 2026-09-01 公告與 DSOGaming 9 月 1 日報導；Aion 2 此前的 DLSS 4.5 支援已由本站記錄。",
      keywords: ["Aion 2 DLSS 5", "DLSS 5 9月4日", "Aion 2 DLSS 支援名單", "NVIDIA DLSS 5 Aion 2", "Aion 2 RTX 50"],
      sections: [
        section("the-announcement", "NVIDIA 公布了什麼", ["NVIDIA 9 月 1 日公告將 DLSS 5 官方發布定為 2026 年 9 月 4 日，NBA 2K27 於 9 月 3 日首發。Aion 2 位列「首批將支援 DLSS 5 的作品」——但「尚不知道這些遊戲何時獲得 DLSS 5 更新」。NBA 2K27 是唯一首發日作品。"]),
        section("for-aion2", "對 Aion 2 的意義", ["Aion 2 在名單上確認了 DLSS 5 有計畫——但無補丁日期。這是來自 NVIDIA 側的藍圖聲明，而非 10 月 5 日全球上線的首發功能。目前確認的超解析度支援是 DLSS 4.5；DLSS 5 將作為後續獨立更新到來。"]),
        section("hardware", "硬體要求：RTX 50 系列", ["據 DSOGaming，DLSS 5 官方僅支援 NVIDIA RTX 50 系列 GPU。對 RTX 40 及更舊的玩家，已確認的 DLSS 4.5 路徑仍是上線時的相關超解析度選項。"]),
        section("performance-context", "性能語境", ["NVIDIA 表示官方 DLSS 5 實現的效能開銷約 50–60%，自 2026 年 3 月以來效能已改善五倍以上，且 DLSS 5 啟用多幀生成。"]),
        section("takeaway", "結論", ["DLSS 5 於 2026 年 9 月 4 日正式發布；Aion 2 確認未來支援但無日期，僅 RTX 50 系列。在 10 月 5 日全球上線時，依賴已確認的 DLSS 4.5 支援。"]),
      ],
    }),
  },
};