import { articleCopy, guideLabels, localizations, publishedVerified, section } from "./trending-august-17-shared";
import type { ContentEntry, ContentHeroImage, ContentSource } from "./content-registry";

/* ARTICLE 5 — DPS Meter guide */

const dpsSource1: ContentSource = {
  id: "aion2hub-dps-meter-2026-08-17",
  kind: "third-party", publisher: "AION2Hub",
  label: "AION 2 DPS Meter is live — parse every fight & climb the ranks on AionFlex",
  url: "https://aion2hub.com/",
  publishedAt: "2026-08-10",
  retrievedAt: "2026-08-17",
  verifiedAt: "2026-08-17",
  localizations: localizations({
    "zh-hans": "AION 2 DPS 计量表已上线——在 AionFlex 上分析每场战斗并冲击排行榜",
    en: "AION 2 DPS Meter is live — parse every fight & climb the ranks on AionFlex",
    fr: "Le DPS Meter AION 2 est en ligne — analysez chaque combat et grimpez les classements sur AionFlex",
    de: "AION 2 DPS-Meter ist live — analysiere jeden Kampf und klettere die Ränge auf AionFlex",
    es: "El medidor de DPS de AION 2 está activo: analiza cada combate y sube en los rankings en AionFlex",
    ja: "AION 2 DPSメーターが稼働 — AionFlex で全戦闘を解析しランクを駆け上がれ",
    "pt-br": "O medidor de DPS do AION 2 está no ar — analise cada luta e suba nos rankings no AionFlex",
    ru: "DPS-метр AION 2 запущен — анализируйте каждый бой и поднимайтесь в рейтингах на AionFlex",
    ko: "AION 2 DPS 미터 출시 — AionFlex에서 모든 전투를 분석하고 랭킹에 오르세요",
    "zh-hant": "AION 2 DPS 計量表已上線——在 AionFlex 上分析每場戰鬥並衝擊排行榜",
  }, "https://aion2hub.com/"),
};

const dpsSource2: ContentSource = {
  id: "mmobomb-dev-stream-2026-08-17",
  kind: "third-party", publisher: "MMOBomb",
  label: "NC Shares What Aion 2 Players Can Expect At Launch On First Global Dev Stream",
  url: "https://www.mmobomb.com/news/nc-shares-what-aion-2-players-can-expect-launch-first-global-dev-stream",
  publishedAt: "2026-08-10",
  retrievedAt: "2026-08-17",
  verifiedAt: "2026-08-17",
  localizations: localizations({
    "zh-hans": "NC 首次全球开发者直播：Aion 2 玩家可期待什么",
    en: "NC Shares What Aion 2 Players Can Expect At Launch On First Global Dev Stream",
    fr: "NC partage ce que les joueurs d'Aion 2 peuvent attendre du lancement lors du premier dev stream mondial",
    de: "NC teilt mit, was Aion 2-Spieler beim Launch vom ersten globalen Dev-Stream erwarten können",
    es: "NC comparte lo que los jugadores de Aion 2 pueden esperar en el lanzamiento en el primer dev stream global",
    ja: "NCが初のグローバル開発者ストリームでAion 2プレイヤーが発売時に期待できることを共有",
    "pt-br": "NC compartilha o que os jogadores de Aion 2 podem esperar no lançamento no primeiro dev stream global",
    ru: "NC делится тем, что игроки Aion 2 могут ожидать от запуска на первом глобальном стриме разработчиков",
    ko: "NC, 첫 글로벌 개발자 스트림에서 Aion 2 플레이어가 출시 시 기대할 수 있는 것 공유",
    "zh-hant": "NC 首次全球開發者直播：Aion 2 玩家可期待什麼",
  }, "https://www.mmobomb.com/news/nc-shares-what-aion-2-players-can-expect-launch-first-global-dev-stream"),
};

const dpsSource3: ContentSource = {
  id: "aionflex-dps-meter-2026-08-17",
  kind: "third-party", publisher: "AionFlex",
  label: "AionFlex — AION 2 DPS Meter & Combat Parsing",
  url: "https://aionflex.com/",
  publishedAt: "2026-08-10",
  retrievedAt: "2026-08-17",
  verifiedAt: "2026-08-17",
  localizations: localizations({
    "zh-hans": "AionFlex —— AION 2 DPS 计量表与战斗分析",
    en: "AionFlex — AION 2 DPS Meter & Combat Parsing",
    fr: "AionFlex — DPS Meter AION 2 et analyse de combat",
    de: "AionFlex — AION 2 DPS-Meter & Kampfanalyse",
    es: "AionFlex — medidor de DPS de AION 2 y análisis de combate",
    ja: "AionFlex — AION 2 DPSメーター＆戦闘解析",
    "pt-br": "AionFlex — medidor de DPS do AION 2 e análise de combate",
    ru: "AionFlex — DPS-метр AION 2 и анализ боя",
    ko: "AionFlex — AION 2 DPS 미터 및 전투 분석",
    "zh-hant": "AionFlex —— AION 2 DPS 計量表與戰鬥分析",
  }, "https://aionflex.com/"),
};

const dpsHero: ContentHeroImage = {
  src: "https://blogfiles.ncsoft.net/news/af7330da-4ff6-4b58-aece-400e6061a3be.jpg",
  width: 1100, height: 605,
  credit: "NC Corporation",
  sourceUrl: "https://aion2.plaync.com/ko-kr/board/notice",
  rights: "linked-official-media",
  translations: {
    "zh-hans": { alt: "Aion 2 DPS 计量表指南配图", caption: "NC 官方配图；社区工具 AionFlex 已上线 Aion 2 DPS 计量表功能。" },
    en: { alt: "Aion 2 DPS meter guide image", caption: "Official NC artwork; the community tool AionFlex launched its Aion 2 DPS meter." },
    fr: { alt: "Image du guide du DPS Meter Aion 2", caption: "Visuel officiel NC ; l'outil communautaire AionFlex a lancé son DPS Meter Aion 2." },
    de: { alt: "Aion 2 DPS-Meter-Guide-Bild", caption: "Offizielles NC-Artwork; das Community-Tool AionFlex hat sein Aion-2-DPS-Meter gestartet." },
    es: { alt: "Imagen de la guía del medidor de DPS de Aion 2", caption: "Arte oficial de NC; la herramienta comunitaria AionFlex lanzó su medidor de DPS de Aion 2." },
    ja: { alt: "Aion 2 DPSメーターガイド画像", caption: "NC公式アートワーク；コミュニティツール AionFlex が Aion 2 DPSメーターをリリースしました。" },
    "pt-br": { alt: "Imagem do guia do medidor de DPS do Aion 2", caption: "Arte oficial da NC; a ferramenta comunitária AionFlex lançou seu medidor de DPS do Aion 2." },
    ru: { alt: "Изображение гайда по DPS-метру Aion 2", caption: "Официальный арт NC; комьюнити-инструмент AionFlex запустил DPS-метр Aion 2." },
    ko: { alt: "Aion 2 DPS 미터 가이드 이미지", caption: "NC 공식 이미지입니다. 커뮤니티 도구 AionFlex가 Aion 2 DPS 미터를 출시했습니다." },
    "zh-hant": { alt: "Aion 2 DPS 計量表指南配圖", caption: "NC 官方配圖；社群工具 AionFlex 已上線 Aion 2 DPS 計量表功能。" },
  },
};

export const trendingAugust17Article5: ContentEntry = {
  section: "guides",
  slug: "aion-2-dps-meter-guide",
  schemaType: "Article",
  publishedAt: "2026-08-17",
  updatedAt: "2026-08-17",
  readingMinutes: 5,
  publication: publishedVerified,
  sources: [dpsSource1, dpsSource2, dpsSource3],
  heroImage: dpsHero,
  related: [
    { kind: "content", section: "guides", slug: "aion-2-launch-classes-guide" },
    { kind: "content", section: "guides", slug: "aion-2-pvp-guide-battlegrounds-abyss" },
    { kind: "content", section: "guides", slug: "post-patch-class-tier-list-august-2026" },
  ],
  translations: {
    en: articleCopy(guideLabels, "en", 5, {
      eyebrow: "TOOLS GUIDE",
      title: "Aion 2 DPS Meter Guide: Parsing Damage with AionFlex & Community Tools",
      description: "The community DPS meter for Aion 2 just went live. Here's what parsers are for, how the AionFlex meter works, and how to use combat logs to improve your build ahead of the September 30 early access.",
      intro: "Community combat parsers are a staple of MMO endgame, and Aion 2 now has its first live one: the AionFlex DPS Meter, announced on Aion2Hub in mid-August and billed as letting players 'parse every fight & climb the ranks.' This guide explains what a DPS meter does, how to use the new tool, and how to turn parser numbers into real build improvements before launch.",
      sourceNote: "Based on the AionFlex DPS Meter announcement on AION2Hub, MMOBomb's dev stream recap for class context, and the AionFlex tool listing. Tool features reflect what has been publicly announced.",
      keywords: ["Aion 2 DPS meter", "Aion 2 parser", "AionFlex", "Aion 2 combat logs", "Aion 2 damage meter"],
      sections: [
        section("what", "What Is a DPS Meter & Why Use One", ["A DPS (damage per second) meter reads combat logs and reports how much damage and healing each player contributed during a fight. They are the standard way MMO players measure rotations, confirm build choices, and screen group members for raids.", "For Aion 2, where 5-player expeditions and 10-player raids reward execution, a parser lets you separate 'how good is my build' from 'how well am I playing' — the two numbers you need to improve efficiently."]),
        section("aionflex", "AionFlex DPS Meter — What's Available Now", ["The AionFlex DPS Meter went live in mid-August 2026, promoted through Aion2Hub: 'parse every fight & climb the ranks on AionFlex.' It adds a ranked layer on top of classic parsing, letting players compare their numbers publicly.", "As a community tool, expect the standard workflow: generate or capture combat data, upload or import it, and review per-fight breakdowns. Feature specifics and platform support continue to evolve as the tool matures ahead of the global launch."]),
        section("improve", "Turning Parser Numbers into Improvements", ["The fastest wins come from three outputs: rotation uptime (are you pressing skills as fast as your cooldowns allow?), skill priority (which ability deals the most damage per second?), and buff/debuff consistency across a full fight.", "Use the class tier context to set realistic targets per class — an Assassin and a Chanter measure very differently. Then pick ONE metric to improve per session rather than chasing everything at once."]),
        section("pve-pvp", "PvE vs PvP: Where Parsers Help", ["Parsers are most useful in PvE, where encounters are fixed and your numbers translate directly to clear times in expeditions and raids at launch.", "PvP is different: Aion 2's 10v10 battlegrounds use stat normalization, so raw damage numbers matter less than target selection and coordination. Use parsers to check damage volume, but judge PvP performance on outcomes, not throughput."]),
      ],
    }),
    "zh-hans": articleCopy(guideLabels, "zh-hans", 5, {
      eyebrow: "工具指南",
      title: "Aion 2 DPS 计量表指南：使用 AionFlex 与社区工具分析伤害",
      description: "Aion 2 的社区 DPS 计量表刚刚上线。以下是解析工具的用途、AionFlex 计量表的运作方式，以及如何在 9 月 30 日抢先体验前利用战斗日志改进你的构筑。",
      intro: "社区战斗解析器是 MMO 后期的标配，而 Aion 2 现在有了第一个上线版本：AionFlex DPS 计量表，8 月中旬在 Aion2Hub 上发布，宣传语是让玩家「分析每场战斗并冲击排行榜」。本指南解释 DPS 计量表的作用、如何使用这个新工具，以及如何在上线前将解析数字转化为真正的构筑改进。",
      sourceNote: "基于 AION2Hub 上的 AionFlex DPS 计量表公告、MMOBomb 开发者直播总结（职业背景）以及 AionFlex 工具列表。工具功能反映已公开的信息。",
      keywords: ["Aion 2 DPS 计量表", "Aion 2 解析器", "AionFlex", "Aion 2 战斗日志", "Aion 2 伤害计量表"],
      sections: [
        section("what", "什么是 DPS 计量表及为何使用", ["DPS（每秒伤害）计量表读取战斗日志，报告战斗中每位玩家的伤害与治疗贡献。这是 MMO 玩家衡量循环、确认构筑选择、筛选团本队员的标准方式。", "对于 Aion 2 而言——5 人远征与 10 人团本奖励执行力——解析器能帮你区分「我的构筑有多好」与「我玩得有多好」这两个需要分别改进的数字。"]),
        section("aionflex", "AionFlex DPS 计量表——现可使用", ["AionFlex DPS 计量表于 2026 年 8 月中旬上线，通过 Aion2Hub 推广：「在 AionFlex 上分析每场战斗并冲击排行榜」。它在经典解析基础上增加了排行层，让玩家可以公开比较数字。", "作为社区工具，预期有标准工作流：生成或捕获战斗数据、上传或导入、查看逐场战斗分解。随着工具在全球上线前成熟，功能细节与平台支持将持续演进。"]),
        section("improve", "将解析数字转化为改进", ["最快的提升来自三个输出：循环利用率（你的技能施放是否跟得上冷却节奏？）、技能优先级（哪个技能每秒伤害最高？）、以及整场战斗中的增益/减益一致性。", "结合职业强度背景为每个职业设定现实目标——刺客与吟游星的衡量标准大不相同。然后每次只选择一项指标改进，而不是同时追求所有指标。"]),
        section("pve-pvp", "PvE 与 PvP：解析器在何处有用", ["解析器在 PvE 中最有用——遭遇战固定，你的数字直接转化为上线时远征与团本的通关时间。", "PvP 则不同：Aion 2 的 10v10 战场使用属性标准化，原始伤害数字不如目标选择与协同重要。用解析器检查伤害量，但以结果而非吞吐量评判 PvP 表现。"]),
      ],
    }),
    ko: articleCopy(guideLabels, "ko", 5, {
      eyebrow: "도구 가이드",
      title: "Aion 2 DPS 미터 가이드: AionFlex와 커뮤니티 도구로 데미지 파싱하기",
      description: "Aion 2용 커뮤니티 DPS 미터가 막 출시되었습니다. 파서의 용도, AionFlex 미터의 작동 방식, 9월 30일 얼리 액세스 전에 전투 로그로 빌드를 개선하는 방법을 설명합니다.",
      intro: "커뮤니티 전투 파서는 MMO 엔드게임의 필수품이며, Aion 2는 이제 첫 라이브 버전을 갖게 되었습니다: 8월 중순 Aion2Hub에서 발표된 AionFlex DPS 미터 — '모든 전투를 분석하고 랭킹에 오르세요.' 이 가이드는 DPS 미터의 역할, 새 도구 사용법, 출시 전에 파서 숫자를 실제 빌드 개선으로 전환하는 방법을 설명합니다.",
      sourceNote: "AION2Hub의 AionFlex DPS 미터 발표, MMOBomb 개발자 스트림 요약(클래스 맥락), AionFlex 도구 목록에 기반합니다. 도구 기능은 공개된 정보를 반영합니다.",
      keywords: ["Aion 2 DPS 미터", "Aion 2 파서", "AionFlex", "Aion 2 전투 로그", "Aion 2 데미지 미터"],
      sections: [
        section("what", "DPS 미터란 무엇이며 왜 쓰나", ["DPS(초당 피해) 미터는 전투 로그를 읽고 각 플레이어의 피해·힐 기여도를 보고합니다. MMO 플레이어가 로테이션을 측정하고, 빌드 선택을 확인하고, 레이드 그룹을 선별하는 표준 도구입니다.", "5인 원정대와 10인 레이드가 실행력을 보상하는 Aion 2에서, 파서는 '내 빌드가 얼마나 좋은가'와 '내 실력이 어떤가'를 분리해 효율적으로 개선하게 해줍니다."]),
        section("aionflex", "AionFlex DPS 미터 — 현재 사용 가능한 것", ["AionFlex DPS 미터는 2026년 8월 중순에 출시되어 Aion2Hub를 통해 홍보되었습니다: '모든 전투를 분석하고 AionFlex에서 랭킹에 오르세요.' 기존 파싱 위에 랭킹 계층을 더해 플레이어가 숫자를 공개 비교할 수 있습니다.", "커뮤니티 도구로서 표준 워크플로를 기대하세요: 전투 데이터 생성·캡처, 업로드·임포트, 전투별 분석 확인. 도구가 글로벌 출시 전에 성숙함에 따라 기능 세부사항과 플랫폼 지원은 계속 진화합니다."]),
        section("improve", "파서 숫자를 개선으로 전환하기", ["가장 빠른 성과는 세 가지 출력에서 나옵니다: 로테이션 업타임(쿨다운 허용 속도만큼 스킬을 누르고 있나?), 스킬 우선순위(초당 가장 높은 피해를 주는 스킬은?), 전체 전투에서의 버프·디버프 일관성.", "클래스 티어 맥락으로 클래스별 현실적 목표를 설정하세요 — 어쌔신과 챈터는 매우 다르게 측정됩니다. 그리고 한 세션에 한 가지 지표만 개선하세요."]),
        section("pve-pvp", "PvE vs PvP: 파서가 유용한 곳", ["파서는 PvE에서 가장 유용합니다 — 전투가 고정되어 숫자가 원정대·레이드 클리어 시간에 직접 연결됩니다.", "PvP는 다릅니다: Aion 2의 10v10 전장은 스탯 균등화를 사용해 원시 피해 숫자보다 표적 선택과 협력이 중요합니다. 파서로 피해량을 확인하되, PvP 성과는 처리량이 아닌 결과로 판단하세요."]),
      ],
    }),
    ja: articleCopy(guideLabels, "ja", 5, {
      eyebrow: "ツールガイド",
      title: "Aion 2 DPSメーターガイド：AionFlex とコミュニティツールでダメージを解析",
      description: "Aion 2 向けコミュニティ DPSメーターが稼働しました。パーサーの目的、AionFlex メーターの仕組み、9月30日の早期アクセス前に戦闘ログでビルドを改善する方法を解説します。",
      intro: "コミュニティ戦闘パーサーは MMO エンドゲームの定番であり、Aion 2 に最初のライブ版が登場しました：8月中旬に Aion2Hub で発表された AionFlex DPSメーター — 『すべての戦闘を解析しランクを駆け上がれ』。このガイドは DPSメーターの役割、新ツールの使い方、ローンチ前にパーサー数値を実際のビルド改善へ転換する方法を説明します。",
      sourceNote: "AION2Hub での AionFlex DPSメーター発表、MMOBomb 開発者ストリーム要約（クラス文脈）、AionFlex ツールリストに基づきます。ツール機能は公開情報を反映しています。",
      keywords: ["Aion 2 DPSメーター", "Aion 2 パーサー", "AionFlex", "Aion 2 戦闘ログ", "Aion 2 ダメージメーター"],
      sections: [
        section("what", "DPSメーターとは何か、なぜ使うか", ["DPS（秒間ダメージ）メーターは戦闘ログを読み、各プレイヤーのダメージ・ヒール貢献を報告します。ローテーションの計測、ビルド選択の確認、レイドメンバーのスクリーニングに使う標準ツールです。", "5人遠征と10人レイドが実行力を報われる Aion 2 では、パーサーは『ビルドの良さ』と『プレイの巧さ』を分離し、効率的に改善する手段を提供します。"]),
        section("aionflex", "AionFlex DPSメーター — 現在利用可能なもの", ["AionFlex DPSメーターは2026年8月中旬に稼働し、Aion2Hub を通じて宣伝されました：『AionFlex で全ての戦闘を解析しランクを駆け上がれ』。従来のパースにランキング層を加え、プレイヤーが数字を公開比較できます。", "コミュニティツールとして標準的な流れを想定してください：戦闘データの生成・キャプチャ、アップロード・インポート、戦闘別の内訳確認。ツールがグローバルローンチ前に成熟するにつれ、機能詳細とプラットフォーム対応は進化し続けます。"]),
        section("improve", "パーサー数値を改善に転換する", ["最速の成果は3つの出力から得られます：ローテーションのアップタイム（クールダウン許容速度でスキルを押せているか）、スキル優先度（秒間最高ダメージのスキルはどれか）、戦闘全体を通じたバフ・デバフの一貫性。", "クラスティアの文脈でクラス別の現実的な目標を設定してください — アサシンとチャンターは測定が大きく異なります。そして1セッションに1つの指標だけを改善しましょう。"]),
        section("pve-pvp", "PvE vs PvP: パーサーが役立つ場所", ["パーサーはPvEで最も有用です — 戦闘が固定され、数字が遠征・レイドのクリアタイムに直接つながります。", "PvPは異なります：Aion 2 の10v10バトルグラウンドはステータス均等化を使うため、生のダメージ数値より標的選択と連携が重要です。パーサーでダメージ量を確認しつつ、PvPのパフォーマンスはスループットではなく結果で判断しましょう。"]),
      ],
    }),
    fr: articleCopy(guideLabels, "fr", 5, {
      eyebrow: "GUIDE D'OUTILS",
      title: "Guide du DPS Meter d'Aion 2 : analyser les dégâts avec AionFlex et les outils communautaires",
      description: "Le DPS Meter communautaire d'Aion 2 vient d'être lancé. Ce qu'il sert, comment fonctionne le mètre AionFlex et comment améliorer votre build avant le 30 septembre.",
      intro: "Les parseurs de combat communautaires sont un pilier de l'endgame MMO, et Aion 2 a maintenant son premier en ligne : le DPS Meter AionFlex. Ce guide explique son rôle, son utilisation et comment transformer les chiffres en améliorations.",
      sourceNote: "Basé sur l'annonce AionFlex sur AION2Hub, le récapitulatif MMOBomb et la liste d'outils AionFlex.",
      keywords: ["Aion 2 DPS meter", "Aion 2 parseur", "AionFlex", "Aion 2 journaux de combat"],
      sections: [
        section("what", "Qu'est-ce qu'un DPS Meter", ["Un DPS meter lit les journaux de combat et rapporte les contributions de dégâts et de soins par joueur — l'outil standard pour mesurer les rotations et filtrer les membres de raid.", "Dans Aion 2, il sépare la qualité du build de la qualité du jeu."]),
        section("aionflex", "DPS Meter AionFlex — disponible maintenant", ["Le mètre AionFlex est en ligne depuis mi-août 2026 : 'parsez chaque combat et grimpez les classements.' Il ajoute un classement public au parsing classique.", "Workflow standard : capturez les données de combat, importez-les, examinez les décompositions par combat."]),
        section("improve", "Transformer les chiffres en améliorations", ["Trois sorties : uptime de rotation, priorité de compétences, cohérence des buffs. Fixez des objectifs réalistes par classe et améliorez un seul indicateur par session."]),
        section("pve-pvp", "PvE vs PvP", ["En PvE, les chiffres se traduisent en temps de clear. En PvP, la normalisation des stats rend la sélection de cibles plus importante que le débit brut."]),
      ],
    }),
    de: articleCopy(guideLabels, "de", 5, {
      eyebrow: "TOOLS-GUIDE",
      title: "Aion 2 DPS-Meter-Guide: Schaden mit AionFlex & Community-Tools parsen",
      description: "Das Community-DPS-Meter für Aion 2 ist live. Wofür Parser da sind, wie das AionFlex-Meter funktioniert und wie Sie Ihren Build vor dem 30. September verbessern.",
      intro: "Community-Kampfparser sind ein fester Bestandteil des MMO-Endgames, und Aion 2 hat jetzt seinen ersten Live-Parser: das AionFlex-DPS-Meter. Dieser Guide erklärt Rolle, Nutzung und wie Sie Zahlen in echte Verbesserungen umwandeln.",
      sourceNote: "Basierend auf der AionFlex-Ankündigung auf AION2Hub, dem MMOBomb-Recap und der AionFlex-Tool-Liste.",
      keywords: ["Aion 2 DPS-Meter", "Aion 2 Parser", "AionFlex", "Aion 2 Kampflogs"],
      sections: [
        section("what", "Was ist ein DPS-Meter", ["Ein DPS-Meter liest Kampflogs und meldet Schadens- und Heilungsbeiträge pro Spieler — der Standard, um Rotationen zu messen und Raid-Mitglieder zu filtern.", "In Aion 2 trennt es die Build-Qualität von der Spielqualität."]),
        section("aionflex", "AionFlex DPS-Meter — jetzt verfügbar", ["Das AionFlex-Meter ist seit Mitte August 2026 live: 'parse every fight & climb the ranks.' Es fügt dem klassischen Parsen eine Rangliste hinzu.", "Standard-Workflow: Kampfdaten erfassen, importieren, Kampf-für-Kampf-Aufschlüsselung prüfen."]),
        section("improve", "Zahlen in Verbesserungen umwandeln", ["Drei Outputs: Rotations-Uptime, Skill-Priorität, Buff-Konsistenz. Setzen Sie realistische Ziele pro Klasse und verbessern Sie eine Kennzahl pro Session."]),
        section("pve-pvp", "PvE vs PvP", ["In PvE übersetzen sich Zahlen direkt in Clear-Zeiten. In PvP macht die Stat-Normalisierung Zielauswahl wichtiger als rohen Durchsatz."]),
      ],
    }),
    es: articleCopy(guideLabels, "es", 5, {
      eyebrow: "GUÍA DE HERRAMIENTAS",
      title: "Guía del medidor de DPS de Aion 2: analizando daño con AionFlex y herramientas comunitarias",
      description: "El medidor de DPS comunitario de Aion 2 acaba de lanzarse. Para qué sirven los parsers, cómo funciona el medidor AionFlex y cómo mejorar tu build antes del 30 de septiembre.",
      intro: "Los parsers de combate comunitarios son un pilar del endgame MMO, y Aion 2 tiene ahora su primer parser en vivo: el DPS Meter de AionFlex. Esta guía explica su papel, uso y cómo convertir números en mejoras reales.",
      sourceNote: "Basado en el anuncio de AionFlex en AION2Hub, el resumen de MMOBomb y la lista de herramientas de AionFlex.",
      keywords: ["Aion 2 medidor de DPS", "Aion 2 parser", "AionFlex", "Aion 2 registros de combate"],
      sections: [
        section("what", "Qué es un medidor de DPS", ["Un medidor de DPS lee registros de combate y reporta contribuciones de daño y sanación por jugador — el estándar para medir rotaciones y filtrar miembros de raid.", "En Aion 2, separa la calidad del build de la calidad del juego."]),
        section("aionflex", "Medidor AionFlex — disponible ahora", ["El medidor de AionFlex está en vivo desde mediados de agosto de 2026: 'parsea cada pelea y sube en los rankings.' Añade un ranking público al parsing clásico.", "Flujo estándar: captura datos de combate, impórtalos, revisa desgloses por pelea."]),
        section("improve", "Convirtiendo números en mejoras", ["Tres salidas: uptime de rotación, prioridad de habilidades, consistencia de buffs. Fija objetivos realistas por clase y mejora una métrica por sesión."]),
        section("pve-pvp", "PvE vs PvP", ["En PvE, los números se traducen en tiempos de limpieza. En PvP, la normalización de stats hace que la selección de objetivos importe más que el throughput bruto."]),
      ],
    }),
    "pt-br": articleCopy(guideLabels, "pt-br", 5, {
      eyebrow: "GUIA DE FERRAMENTAS",
      title: "Guia do medidor de DPS de Aion 2: analisando dano com AionFlex e ferramentas da comunidade",
      description: "O medidor de DPS comunitário de Aion 2 acabou de entrar no ar. Para que servem os parsers, como funciona o medidor AionFlex e como melhorar seu build antes de 30 de setembro.",
      intro: "Parsers de combate comunitários são um pilar do endgame de MMO, e Aion 2 agora tem seu primeiro parser ao vivo: o DPS Meter da AionFlex. Este guia explica seu papel, uso e como transformar números em melhorias reais.",
      sourceNote: "Baseado no anúncio da AionFlex no AION2Hub, no resumo da MMOBomb e na lista de ferramentas da AionFlex.",
      keywords: ["Aion 2 medidor de DPS", "Aion 2 parser", "AionFlex", "Aion 2 registros de combate"],
      sections: [
        section("what", "O que é um medidor de DPS", ["Um medidor de DPS lê registros de combate e reporta contribuições de dano e cura por jogador — o padrão para medir rotações e filtrar membros de raid.", "Em Aion 2, separa a qualidade do build da qualidade do jogo."]),
        section("aionflex", "Medidor AionFlex — disponível agora", ["O medidor da AionFlex está no ar desde meados de agosto de 2026: 'analise cada luta e suba nos rankings.' Ele adiciona um ranking público ao parsing clássico.", "Fluxo padrão: capture dados de combate, importe, revise detalhamentos por luta."]),
        section("improve", "Transformando números em melhorias", ["Três saídas: uptime de rotação, prioridade de habilidades, consistência de buffs. Defina metas realistas por classe e melhore uma métrica por sessão."]),
        section("pve-pvp", "PvE vs PvP", ["Em PvE, os números viram tempos de clear. Em PvP, a normalização de stats torna a seleção de alvos mais importante que o throughput bruto."]),
      ],
    }),
    ru: articleCopy(guideLabels, "ru", 5, {
      eyebrow: "ГАЙД ПО ИНСТРУМЕНТАМ",
      title: "Гайд по DPS-метру Aion 2: разбор урона с AionFlex и комьюнити-инструментами",
      description: "Комьюнити- DPS-метр для Aion 2 только что запущен. Зачем нужны парсеры, как работает метр AionFlex и как улучшить билд до 30 сентября.",
      intro: "Боевые парсеры — неотъемлемая часть MMO-эндгейма, и у Aion 2 теперь есть первый живой парсер: DPS-метр AionFlex. Этот гайд объясняет его роль, использование и превращение цифр в реальные улучшения.",
      sourceNote: "На основе анонса AionFlex на AION2Hub, резюме MMOBomb и списка инструментов AionFlex.",
      keywords: ["Aion 2 DPS-метр", "Aion 2 парсер", "AionFlex", "Aion 2 боевые логи"],
      sections: [
        section("what", "Что такое DPS-метр", ["DPS-метр читает боевые логи и отчитывает вклад урона и лечения каждого игрока — стандарт для измерения ротаций и отбора участников рейдов.", "В Aion 2 он отделяет качество билда от качества игры."]),
        section("aionflex", "Метр AionFlex — доступен сейчас", ["Метр AionFlex запущен в середине августа 2026: 'разбирайте каждый бой и поднимайтесь в рейтингах.' Он добавляет публичный рейтинг к классическому парсингу.", "Стандартный порядок: захват боевых данных, импорт, разбор по боям."]),
        section("improve", "Превращение цифр в улучшения", ["Три выхода: аптайм ротации, приоритет скиллов, консистентность баффов. Ставьте реалистичные цели по классам и улучшайте одну метрику за сессию."]),
        section("pve-pvp", "PvE против PvP", ["В PvE цифры напрямую влияют на время зачисток. В PvP нормализация статов делает выбор цели важнее сырого дамага."]),
      ],
    }),
    "zh-hant": articleCopy(guideLabels, "zh-hant", 5, {
      eyebrow: "工具指南",
      title: "Aion 2 DPS 計量表指南：使用 AionFlex 與社群工具分析傷害",
      description: "Aion 2 的社群 DPS 計量表剛剛上線。以下是解析工具的用途、AionFlex 計量表的運作方式，以及如何在 9 月 30 日搶先體驗前利用戰鬥日誌改進你的構築。",
      intro: "社群戰鬥解析器是 MMO 後期的標配，而 Aion 2 現在有了第一個上線版本：AionFlex DPS 計量表，8 月中旬在 Aion2Hub 上發布，宣傳語是讓玩家「分析每場戰鬥並衝擊排行榜」。本指南解釋 DPS 計量表的作用、如何使用這個新工具，以及如何在上線前將解析數字轉化為真正的構築改進。",
      sourceNote: "基於 AION2Hub 上的 AionFlex DPS 計量表公告、MMOBomb 開發者直播總結（職業背景）以及 AionFlex 工具列表。工具功能反映已公開的資訊。",
      keywords: ["Aion 2 DPS 計量表", "Aion 2 解析器", "AionFlex", "Aion 2 戰鬥日誌", "Aion 2 傷害計量表"],
      sections: [
        section("what", "什麼是 DPS 計量表及為何使用", ["DPS（每秒傷害）計量表讀取戰鬥日誌，報告戰鬥中每位玩家的傷害與治療貢獻。這是 MMO 玩家衡量循環、確認構築選擇、篩選團本隊員的標準方式。", "對於 Aion 2 而言——5 人遠征與 10 人團本獎勵執行力——解析器能幫你區分「我的構築有多好」與「我玩得有多好」這兩個需要分別改進的數字。"]),
        section("aionflex", "AionFlex DPS 計量表——現可使用", ["AionFlex DPS 計量表於 2026 年 8 月中旬上線，透過 Aion2Hub 推廣：「在 AionFlex 上分析每場戰鬥並衝擊排行榜」。它在經典解析基礎上增加了排行層，讓玩家可以公開比較數字。", "作為社群工具，預期有標準工作流：產生或擷取戰鬥資料、上傳或匯入、檢視逐場戰鬥分解。隨著工具在全球上線前成熟，功能細節與平台支援將持續演進。"]),
        section("improve", "將解析數字轉化為改進", ["最快的提升來自三個輸出：循環利用率（你的技能施放是否跟得上冷卻節奏？）、技能優先級（哪個技能每秒傷害最高？）、以及整場戰鬥中的增益/減益一致性。", "結合職業強度背景為每個職業設定現實目標——刺客與吟遊星的衡量標準大不相同。然後每次只選擇一項指標改進，而不是同時追求所有指標。"]),
        section("pve-pvp", "PvE 與 PvP：解析器在何處有用", ["解析器在 PvE 中最有用——遭遇戰固定，你的數字直接轉化為上線時遠征與團本的通關時間。", "PvP 則不同：Aion 2 的 10v10 戰場使用屬性標準化，原始傷害數字不如目標選擇與協同重要。用解析器檢查傷害量，但以結果而非吞吐量評判 PvP 表現。"]),
      ],
    }),
  },
};