import { articleCopy, guideLabels, localizations, publishedVerified, section } from "./trending-august-31-shared";
import type { ContentEntry, ContentHeroImage, ContentSource } from "./content-registry";

/* ARTICLE 2 — Steam lists 8 supported languages for the global version, no Chinese */

const langSource1: ContentSource = {
  id: "steam-store-aion2-languages-2026-08-31",
  kind: "platform", publisher: "Steam",
  label: "AION 2 — Steam Store Page (Supported Languages)",
  url: "https://store.steampowered.com/app/3393110/AION_2/",
  publishedAt: "2026-08-26",
  retrievedAt: "2026-08-31",
  verifiedAt: "2026-08-31",
  localizations: localizations({
    "zh-hans": "AION 2——Steam 商店页（支持语言）",
    en: "AION 2 — Steam Store Page (Supported Languages)",
    fr: "AION 2 — Page boutique Steam (langues prises en charge)",
    de: "AION 2 — Steam-Store-Seite (unterstützte Sprachen)",
    es: "AION 2 — Página de la tienda de Steam (idiomas compatibles)",
    ja: "AION 2 — Steam ストアページ（対応言語）",
    "pt-br": "AION 2 — Página da loja Steam (idiomas suportados)",
    ru: "AION 2 — Страница Steam (поддерживаемые языки)",
    ko: "AION 2 — Steam 상점 페이지(지원 언어)",
    "zh-hant": "AION 2——Steam 商店頁（支援語言）",
  }, "https://store.steampowered.com/app/3393110/AION_2/"),
};

const langSource2: ContentSource = {
  id: "massivelyop-gamescom-aion2-2026-08-25",
  kind: "third-party", publisher: "Massively Overpowered",
  label: "Gamescom 2026: Aion 2 makes its global debut October 5 (regions, stress test, headstart)",
  url: "https://massivelyop.com/2026/08/25/gamescom-2026-aion-2-makes-its-global-debut-october-5-following-stress-test-and-headstart/",
  publishedAt: "2026-08-25",
  retrievedAt: "2026-08-31",
  verifiedAt: "2026-08-31",
  localizations: localizations({
    "zh-hans": "Gamescom 2026：Aion 2 定于 10 月 5 日全球首发（大区、压测、抢先体验）",
    en: "Gamescom 2026: Aion 2 makes its global debut October 5 (regions, stress test, headstart)",
    fr: "Gamescom 2026 : Aion 2 fait ses débuts mondiaux le 5 octobre (régions, test de charge, accès anticipé)",
    de: "Gamescom 2026: Aion 2 startet am 5. Oktober weltweit (Regionen, Stresstest, Headstart)",
    es: "Gamescom 2026: Aion 2 debuta en todo el mundo el 5 de octubre (regiones, prueba de carga, acceso anticipado)",
    ja: "Gamescom 2026：Aion 2 は10月5日にグローバルデビュー（リージョン・負荷試験・先行体験）",
    "pt-br": "Gamescom 2026: Aion 2 estreia globalmente em 5 de outubro (regiões, teste de carga, acesso antecipado)",
    ru: "Gamescom 2026: Aion 2 выходит в мире 5 октября (регионы, стресс-тест, ранний доступ)",
    ko: "Gamescom 2026: Aion 2가 10월 5일 글로벌 데뷔(리전·부하 테스트·헤드스타트)",
    "zh-hant": "Gamescom 2026：Aion 2 定於 10 月 5 日全球首發（大區、壓測、搶先體驗）",
  }, "https://massivelyop.com/2026/08/25/gamescom-2026-aion-2-makes-its-global-debut-october-5-following-stress-test-and-headstart/"),
};

const langHero: ContentHeroImage = {
  src: "https://blogfiles.ncsoft.net/news/af7330da-4ff6-4b58-aece-400e6061a3be.jpg",
  width: 1100, height: 605,
  credit: "NC Corporation",
  sourceUrl: "https://aion2.plaync.com/ja-jp/board/notice/list",
  rights: "linked-official-media",
  translations: {
    "zh-hans": { alt: "Aion 2 全球版本地化语言指南配图", caption: "NC 官方配图；Aion 2 全球版 Steam 商店页现列出 8 种支持语言，简体中文与繁体中文均不在其中。" },
    en: { alt: "Aion 2 global version language support guide image", caption: "Official NC artwork; the AION 2 global Steam store page currently lists 8 supported languages, and neither Simplified nor Traditional Chinese is among them." },
    fr: { alt: "Image du guide des langues de la version globale d'Aion 2", caption: "Visuel officiel NC ; la page Steam globale d'AION 2 liste actuellement 8 langues, sans chinois simplifié ni traditionnel." },
    de: { alt: "Bild zum Sprachguide der globalen Aion-2-Version", caption: "Offizielles NC-Artwork; die globale AION-2-Steampage listet derzeit 8 unterstützte Sprachen, darunter weder vereinfachtes noch traditionelles Chinesisch." },
    es: { alt: "Imagen de la guía de idiomas de la versión global de Aion 2", caption: "Arte oficial de NC; la página global de Steam de AION 2 lista actualmente 8 idiomas, sin chino simplificado ni tradicional." },
    ja: { alt: "Aion 2 グローバル版言語対応ガイド画像", caption: "NC公式アートワーク；AION 2 グローバル版のSteamストアページは現在8言語を掲載しており、簡体字・繁体字中国語は含まれていません。" },
    "pt-br": { alt: "Imagem do guia de idiomas da versão global do Aion 2", caption: "Arte oficial da NC; a página global da Steam do AION 2 lista atualmente 8 idiomas, sem chinês simplificado nem tradicional." },
    ru: { alt: "Изображение руководства по языкам глобальной версии Aion 2", caption: "Официальный арт NC; глобальная страница Steam AION 2 сейчас перечисляет 8 поддерживаемых языков, ни упрощённого, ни традиционного китайского среди них нет." },
    ko: { alt: "Aion 2 글로벌 버전 언어 지원 가이드 이미지", caption: "NC 공식 이미지입니다. AION 2 글로벌 Steam 상점 페이지는 현재 8개 언어를 지원하며, 간체·번체 중국어는 포함되지 않습니다." },
    "zh-hant": { alt: "Aion 2 全球版本地化語言指南配圖", caption: "NC 官方配圖；Aion 2 全球版 Steam 商店頁現列出 8 種支援語言，簡體中文與繁體中文均不在其中。" },
  },
};

export const trendingAugust31Article2: ContentEntry = {
  section: "guides",
  slug: "aion-2-language-support-8-languages-guide",
  schemaType: "Article",
  publishedAt: "2026-08-31",
  updatedAt: "2026-08-31",
  readingMinutes: 5,
  publication: publishedVerified,
  sources: [langSource1, langSource2],
  heroImage: langHero,
  related: [
    { kind: "content", section: "news", slug: "aion-2-genai-asset-disclosure-steam" },
    { kind: "content", section: "news", slug: "aion-2-release-date-october-5-2026" },
    { kind: "content", section: "guides", slug: "aion-2-global-version-changes-guide" },
    { kind: "content", section: "guides", slug: "aion-2-platforms" },
  ],
  translations: {
    en: articleCopy(guideLabels, "en", 5, {
      eyebrow: "LANGUAGE SUPPORT CHECK",
      title: "Aion 2 Global Language Support: 8 Languages on Steam, No Chinese",
      description: "The AION 2 Steam store page lists 8 supported languages — English, French, German, Spanish (Spain), Japanese, Portuguese (Brazil), Russian, and Korean — with full audio in all eight and subtitles in English, Japanese, and Korean. Neither Simplified nor Traditional Chinese is on the list, despite earlier statements that planned ten languages.",
      intro: "Before the October 5 global launch, the question of which languages the AION 2 global version actually ships with matters for every non-English player. The current Steam store page lists exactly eight supported languages, and Chinese — either simplified or traditional — is not among them. This guide lays out the exact list, the audio-versus-subtitle breakdown, how regions differ from languages, and what the gap means for Simplified Chinese readers who plan to play at launch.",
      sourceNote: "Based on the AION 2 Steam store page (retrieved and verified August 31, 2026), cross-checked with Massively Overpowered's Gamescom 2026 report confirming the October 5 launch across North America, South America, Europe, and Asia.",
      keywords: ["Aion 2 language support", "Aion 2 supported languages", "Aion 2 no Chinese", "Aion 2 subtitles", "Aion 2 Steam languages"],
      sections: [
        section("what-steam-lists", "The Exact 8-Language List", ["Steam currently lists “English and 7 more” for AION 2. The eight languages are English, French, German, Spanish (Spain), Japanese, Portuguese (Brazil), Russian, and Korean. That is the complete, machine-readable list on the storefront as of August 31, 2026.", "The list is notable for what it omits: no Italian, no Polish, no Arabic, and — most relevant for this site's readers — no Simplified Chinese and no Traditional Chinese. The global storefront, not a press release, is the authoritative record, and this is what it shows today.", "Because store pages change, re-check the page before launch. The date-stamped fetch behind this guide is the snapshot; if NC adds languages later, the page will show it."]),
        section("audio-subtitles", "Audio and Subtitles Breakdown", ["All eight languages are marked with full audio. That is a stronger guarantee than many MMO localizations, which often ship subtitles-only.", "Only three languages carry subtitles as well: English, Japanese, and Korean. For the other five — French, German, Spanish (Spain), Portuguese (Brazil), and Russian — the interface and audio are localised but subtitle text is not marked.", "In practice, players in FR/DE/ES/PT-BR/RU should expect the interface and voice to be in their language, while on-screen subtitle text falls back to English. Players in EN/JA/KO get both."]),
        section("chinese-gap", "The Chinese Language Gap", ["Earlier announcements and older coverage described the global version as planning ten languages, including Simplified and Traditional Chinese, with Chinese marked for full audio in some descriptions. The current Steam page does not reflect that: the eight languages above are all that is listed, and neither Chinese script appears.", "This matters for launch decisions. A Simplified Chinese player cannot rely on a Chinese interface on the global Steam client today; the fallback is English, with Japanese and Korean as the only full-audio-plus-subtitle options.", "The situation can change — localization support is not frozen at announcement time — but as of the verification date of this guide, plan for English as the working interface if you are a Chinese-speaking player."]),
        section("regions-vs-languages", "Regions Are Not Languages", ["NCSoft announced the global launch on PC (Steam and PURPLE) across North America, South America, Europe, and Asia. Those are server regions — where you connect from — and they are separate from interface languages.", "A player in any of those regions can in principle use any of the supported interface languages; region choice affects latency, server population, and which storefront price you see, not which languages are installed.", "For players near Asia, the Asia region and the Korean-language interface are separate decisions: picking a server region does not force a language, and picking a language does not pick a region."]),
        section("what-it-means", "What This Means at Launch", ["If you are multilingual, the practical recommendation is to verify your primary language's coverage: interface, full audio, and subtitles each matter differently. For full-audio-plus-subtitles in a familiar script, English, Japanese, and Korean are currently the safe choices.", "If you are a Simplified Chinese player planning to play the global version, budget for an English interface at launch and re-check the store page after any localization announcement. NCSoft may add Chinese, but nothing on the storefront promises it today.", "The game's free-to-play launch on October 5 means you can test the actual language options in the client before spending anything — the Steam Playtest request and the September 17–18 Launch Scale Test are both free ways to confirm what is localised before the paid Founder's Pack early access begins September 30."]),
      ],
    }),
    "zh-hans": articleCopy(guideLabels, "zh-hans", 5, {
      eyebrow: "语言支持核查",
      title: "Aion 2 全球版语言支持：Steam 实列 8 种，无中文",
      description: "AION 2 的 Steam 商店页现列出 8 种支持语言——英、法、德、西（西班牙）、日、葡（巴西）、俄、韩——八种全语音，字幕仅英、日、韩。简体与繁体中文均不在名单内，与早前「计划 10 种语言」的说法存在出入。",
      intro: "在 10 月 5 日全球上线前，AION 2 全球版到底支持哪些语言，对每一位非英语玩家都至关重要。当前 Steam 商店页恰好列出八种支持语言，而中文——无论简体还是繁体——都不在其中。本指南给出完整清单、语音与字幕细分、大区与语言的区别，以及这一缺口对计划首发游玩的简体中文玩家的实操含义。",
      sourceNote: "基于 AION 2 Steam 商店页（2026-08-31 检索并核对），并与 Massively Overpowered 的 Gamescom 2026 报道（确认 10 月 5 日在北美、南美、欧洲与亚洲上线）交叉核对。",
      keywords: ["Aion 2 语言支持", "Aion 2 支持语言", "Aion 2 无中文", "Aion 2 字幕", "Aion 2 Steam 语言"],
      sections: [
        section("what-steam-lists", "实列的 8 种语言", ["Steam 目前将 AION 2 标为「英语及另外 7 种」。八种语言为：英语、法语、德语、西班牙语（西班牙）、日语、葡萄牙语（巴西）、俄语、韩语。这是截至 2026-08-31 商店页上完整、可机器读取的名单。", "这份名单的可注意之处在于它的缺项：没有意大利语、没有波兰语、没有阿拉伯语，而——对本站读者最关键——没有简体中文，也没有繁体中文。商店页而非新闻稿才是权威记录，今天它显示的就是这样。", "商店页会变，上线前请复查页面。本指南背后的检索快照是时间点证据；若 NC 日后新增语言，页面会体现。"]),
        section("audio-subtitles", "语音与字幕细分", ["八种语言全部标记为「完整语音」。这是比许多仅字幕 MMO 本地化更强的保证。", "仅三种语言同时带有字幕：英语、日语、韩语。其余五种——法语、德语、西班牙语（西班牙）、葡萄牙语（巴西）、俄语——界面与语音本地化，但未标记字幕文本。", "实操上，FR/DE/ES/PT-BR/RU 玩家应预期界面与配音为母语，而屏幕字幕文本回退英语；EN/JA/KO 玩家则两者兼得。"]),
        section("chinese-gap", "中文缺席", ["早前的公告与旧报道将全球版描述为计划支持十种语言，包含简体与繁体中文，部分描述还称中文提供完整语音。当前 Steam 页面并未体现这一点：上面八种即全部列出，两种中文均未出现。", "这对上线决策很关键。今日的全球 Steam 客户端上，简体中文玩家无法依赖中文界面；回退语言是英语，仅日、韩提供全语音加字幕。", "局面可能变化——本地化并非在公告日冻结——但以本指南核对日为准，中文玩家请按英语界面做首发计划。"]),
        section("regions-vs-languages", "大区不等于语言", ["NCSoft 宣布全球版在 PC（Steam 与 PURPLE）于北美、南美、欧洲与亚洲上线。这些是服务器大区——你从哪里连接——与界面语言是两回事。", "任一大区的玩家原则上都可使用任何受支持的界面语言；大区选择影响延迟、服务器人口与商店价格，而非安装了哪些语言。", "对亚洲附近的玩家：亚洲大区与韩语界面是各自独立的决定——选大区不强制语言，选语言不决定大区。"]),
        section("what-it-means", "上线时的实操含义", ["若你掌握多语，实际建议是先确认主用语言的覆盖：界面、完整语音、字幕三者权重不同。对「熟悉文字 + 全语音 + 字幕」，英语、日语、韩语目前是稳妥之选。", "若你是计划玩全球版的简体中文玩家，请按上线时使用英语界面做预算，并在任何本地化公告后复查商店页。NCSoft 可能加入中文，但今日商店页没有任何承诺。", "10 月 5 日免费游玩上线意味着你可以在付费前实测客户端的语言选项——Steam Playtest 申请与 9 月 17–18 日的 Launch Scale Test 都是免费途径，可在 9 月 30 日创始人包抢先体验付费前确认哪些已本地化。"]),
      ],
    }),
    ko: articleCopy(guideLabels, "ko", 5, {
      eyebrow: "언어 지원 확인",
      title: "Aion 2 글로벌 언어 지원: Steam은 8개 언어, 중국어 없음",
      description: "AION 2 Steam 상점 페이지는 8개 지원 언어(영·불·독·서(스페인)·일·포(브라질)·러·한)를 명시하며 8개 모두 풀 보이스, 자막은 영·일·한만. 간체·번체 중국어는 모두 없습니다.",
      intro: "10월 5일 글로벌 출시 전, 글로벌 버전이 실제로 어떤 언어를 지원하는지는 비영어권 플레이어 모두에게 중요합니다. 현재 Steam 상점 페이지는 정확히 8개 언어를 나열하며 중국어는 없습니다. 이 가이드는 전체 목록·음성/자막 구분·리전과 언어의 차이·간체 중국어 독자에 대한 실무 의미를 정리합니다.",
      sourceNote: "AION 2 Steam 상점 페이지(2026-08-31 확인)와 Massively Overpowered의 Gamescom 2026 보도(10월 5일 북미·남미·유럽·아시아 출시 확인) 교차 확인 기반.",
      keywords: ["Aion 2 언어 지원", "Aion 2 지원 언어", "Aion 2 중국어 없음", "Aion 2 자막", "Aion 2 Steam 언어"],
      sections: [
        section("what-steam-lists", "정확한 8개 언어 목록", "Steam은 AION 2를 '영어 외 7개'로 표시합니다. 여덟 언어는 영어·프랑스어·독일어·스페인어(스페인)·일본어·포르투갈어(브라질)·러시아어·한국어입니다. 2026-08-31 기준 상점 페이지의 완전한 목록입니다. 이탈리아어·폴란드어·아랍어가 없고, 가장 중요한 것은 간체·번체 중국어가 없다는 점입니다. 상점 페이지는 변하므로 출시 전 재확인하세요."),
        section("audio-subtitles", "음성/자막 구분", "여덟 언어 모두 '풀 보이스' 표시입니다. 많은 MMO가 자막만 지원하는 것보다 강한 보장입니다. 자막까지 있는 언어는 영어·일본어·한국어 세 개뿐이며, 나머지 다섯(프랑스어·독일어·스페인어·포르투갈어·러시아어)은 인터페이스와 음성만 로컬라이즈됩니다. FR/DE/ES/PT-BR/RU 플레이어는 화면 자막이 영어로 폴백됨을 예상해야 합니다."),
        section("chinese-gap", "중국어 부재", "이전 발표와 오래된 보도는 글로벌 버전이 간체·번체 중국어를 포함한 10개 언어를 계획한다고 했습니다. 현재 Steam 페이지는 그와 다릅니다. 오늘 글로벌 Steam 클라이언트에서 간체 중국어 사용자는 중국어 인터페이스를 기대할 수 없고, 영어가 폴백이며, 풀 보이스+자막은 일·한뿐입니다. 본 가이드 확인일 기준으로 영어 인터페이스를 전제로 계획하세요."),
        section("regions-vs-languages", "리전 ≠ 언어", "NC소프트는 글로벌 출시를 PC(Steam·PURPLE) 북미·남미·유럽·아시아로 발표했습니다. 이는 서버 리전이며 인터페이스 언어와 별개입니다. 리전은 지연·서버 인구·상점 가격에 영향을 주고 설치 언어에는 영향을 주지 않습니다. 아시아 근처 플레이어에게도 리전 선택이 언어를 강제하지 않습니다."),
        section("what-it-means", "출시 시 실무 의미", "다국어 사용자는 주 언어의 커버리지(인터페이스·풀 보이스·자막)를 확인하세요. 간체 중국어 플레이어라면 출시 시 영어 인터페이스를 예산에 넣고, 로컬라이제이션 공지 후 상점 페이지를 다시 확인하세요. 10월 5일 무료 플레이 출시와 9월 17–18일 LST, Steam Playtest 신청은 유료 결제 전에 로컬라이즈 현황을 확인할 무료 경로입니다."),
      ],
    }),
    ja: articleCopy(guideLabels, "ja", 5, {
      eyebrow: "言語対応の確認",
      title: "Aion 2 グローバル版の言語対応：Steamは8言語、中国語なし",
      description: "AION 2 の Steam ストアページは8つの対応言語（英・仏・独・西・日・葡・露・韓）を掲載し、8言語すべてフル音声、字幕は英・日・韓のみ。簡体・繁体中国語はどちらも含まれていません。",
      intro: "10月5日のグローバル発売前に、グローバル版が実際にどの言語に対応するかは非英語圏のプレイヤー全員にとって重要です。現在の Steam ストアページは8言語を掲載し、中国語は含まれていません。本ガイドは正確な一覧・音声/字幕の内訳・リージョンと言語の違い・中国語話者への実務的な意味をまとめます。",
      sourceNote: "AION 2 Steam ストアページ（2026-08-31 確認）と、Massively Overpowered の Gamescom 2026 報道（10月5日に北米・南米・欧州・アジアで発売）の照合に基づきます。",
      keywords: ["Aion 2 言語対応", "Aion 2 対応言語", "Aion 2 中国語なし", "Aion 2 字幕", "Aion 2 Steam 言語"],
      sections: [
        section("what-steam-lists", "正確な8言語リスト", "Steam は AION 2 を「英語と他7言語」と表示します。8言語は英語・フランス語・ドイツ語・スペイン語（スペイン）・日本語・ポルトガル語（ブラジル）・ロシア語・韓国語です。2026-08-31 時点のストアページの完全なリストです。イタリア語・ポーランド語・アラビア語はなく、最重要として簡体・繁体中国語がありません。ストアページは変わるため発売前に再確認してください。"),
        section("audio-subtitles", "音声と字幕の内訳", "8言語すべて「フル音声」表記です。字幕も持つのは英語・日本語・韓国語の3言語のみで、残り5言語（仏・独・西・葡・露）はインターフェースと音声のみローカライズされます。FR/DE/ES/PT-BR/RU のプレイヤーは字幕テキストが英語にフォールバックする点に注意してください。"),
        section("chinese-gap", "中国語の不在", "以前の発表と古い報道は、グローバル版が簡体・繁体中国語を含む10言語を計画しているとしていました。現在の Steam ページはそれを反映していません。今日のグローバル Steam クライアントでは、簡体中国語プレイヤーは中国語インターフェースを当てにできず、英語がフォールバックで、フル音声+字幕は日・韓のみです。本ガイドの確認日基準で英語インターフェース前提の計画を推奨します。"),
        section("regions-vs-languages", "リージョン ≠ 言語", "NCソフトはグローバル発売を PC（Steam・PURPLE）で北米・南米・欧州・アジアに展開すると発表しました。これはサーバーリージョンであり、インターフェース言語とは別です。リージョンはレイテンシ・サーバー人口・ストア価格に影響し、言語には影響しません。"),
        section("what-it-means", "発売時点の実務", "多言語話者は主要言語のカバレッジ（UI・フル音声・字幕）を確認してください。簡体中国語プレイヤーは英語インターフェース前提で計画し、ローカライズ発表後にストアページを再確認してください。10月5日の無料プレイ発売と9月17–18日のLST、Steam Playtest 申請は、有料のファウンダーズパック先行体験（9月30日開始）前にローカライズ状況を無料で確認する手段です。"),
      ],
    }),
    fr: articleCopy(guideLabels, "fr", 5, {
      eyebrow: "VÉRIFICATION DES LANGUES",
      title: "Langues de la version globale d'Aion 2 : 8 langues sur Steam, pas de chinois",
      description: "La page Steam d'AION 2 liste 8 langues — anglais, français, allemand, espagnol (Espagne), japonais, portugais (Brésil), russe et coréen — toutes en audio complet, avec sous-titres en anglais, japonais et coréen. Ni chinois simplifié ni traditionnel.",
      intro: "Avant le lancement du 5 octobre, savoir quelles langues la version globale d'AION 2 embarque compte pour tout joueur non-anglophone. La page Steam actuelle liste exactement huit langues, et le chinois n'en fait pas partie. Ce guide détaille la liste, l'audio vs les sous-titres, la différence région/langue et l'impact pour les lecteurs en chinois simplifié.",
      sourceNote: "Basé sur la page Steam d'AION 2 (récupérée et vérifiée le 31 août 2026), recoupé avec le rapport Gamescom 2026 de Massively Overpowered confirmant le 5 octobre en Amérique du Nord, du Sud, en Europe et en Asie.",
      keywords: ["Aion 2 langues", "Aion 2 langues supportées", "Aion 2 pas de chinois", "Aion 2 sous-titres", "Aion 2 langues Steam"],
      sections: [
        section("what-steam-lists", "La liste exacte de 8 langues", "Steam affiche « anglais et 7 autres » pour AION 2. Les huit langues : anglais, français, allemand, espagnol (Espagne), japonais, portugais (Brésil), russe, coréen. C'est la liste complète et lisible par machine au 31 août 2026. Pas d'italien, pas de polonais, pas d'arabe, et surtout pas de chinois simplifié ni traditionnel. La page boutique, pas le communiqué, fait foi."),
        section("audio-subtitles", "Audio et sous-titres", "Les huit langues sont marquées en audio complet. Seules trois ont aussi des sous-titres : anglais, japonais, coréen. Pour les cinq autres (français, allemand, espagnol, portugais, russe), l'interface et l'audio sont localisés, pas le texte des sous-titres : attendez-vous à un repli en anglais."),
        section("chinese-gap", "L'absence du chinois", "Les annonces précédentes décrivaient un plan de dix langues incluant le chinois simplifié et traditionnel. La page Steam actuelle ne le reflète pas : huit langues, aucune écriture chinoise. Aujourd'hui, un joueur chinois simplifié ne peut pas compter sur une interface chinoise sur le client Steam global ; le repli est l'anglais, avec le japonais et le coréen comme seuls audio+ sous-titres complets. La situation peut évoluer, mais planifiez sur l'anglais à la date de vérification."),
        section("regions-vs-languages", "Les régions ne sont pas les langues", "NCSoft lance sur PC (Steam et PURPLE) en Amérique du Nord, du Sud, en Europe et en Asie. Ce sont des régions de serveurs, distinctes des langues d'interface. Choisir une région n'impose pas une langue et inversement."),
        section("what-it-means", "Ce que ça change au lancement", "Vérifiez la couverture de votre langue principale : interface, audio complet, sous-titres pèsent différemment. En anglais, japonais et coréen, vous avez les trois. En chinois simplifié, prévoyez l'interface en anglais et re-vérifiez après toute annonce de localisation. Le lancement free-to-play du 5 octobre, le test de charge 17–18 septembre et la demande Steam Playtest permettent de vérifier avant le paiement."),
      ],
    }),
    de: articleCopy(guideLabels, "de", 5, {
      eyebrow: "SPRACH-CHECK",
      title: "Aion-2-Sprachsupport (global): 8 Sprachen bei Steam, kein Chinesisch",
      description: "Die AION-2-Steampage listet 8 Sprachen — Englisch, Französisch, Deutsch, Spanisch (Spanien), Japanisch, Portugiesisch (Brasilien), Russisch und Koreanisch — alle mit Vollton, Untertitel nur Englisch, Japanisch, Koreanisch. Weder vereinfachtes noch traditionelles Chinesisch.",
      intro: "Vor dem Start am 5. Oktober zählt für jeden nicht-englischen Spieler, welche Sprachen die globale AION-2-Version wirklich unterstützt. Die aktuelle Steampage listet genau acht Sprachen — Chinesisch fehlt. Dieser Guide zeigt die Liste, Audio vs. Untertitel, Region vs. Sprache und die Bedeutung für Leser mit vereinfachtem Chinesisch.",
      sourceNote: "Basierend auf der AION-2-Steampage (abgerufen und verifiziert am 31. August 2026), abgeglichen mit dem Gamescom-2026-Bericht von Massively Overpowered (Start 5. Oktober in Nord-/Südamerika, Europa, Asien).",
      keywords: ["Aion 2 Sprachunterstützung", "Aion 2 unterstützte Sprachen", "Aion 2 ohne Chinesisch", "Aion 2 Untertitel", "Aion 2 Steam Sprachen"],
      sections: [
        section("what-steam-lists", "Die exakte 8-Sprachen-Liste", "Steam zeigt für AION 2 „Englisch und 7 weitere“ an. Die acht Sprachen: Englisch, Französisch, Deutsch, Spanisch (Spanien), Japanisch, Portugiesisch (Brasilien), Russisch und Koreanisch — die vollständige, maschinenlesbare Liste zum 31. August 2026. Kein Italienisch, kein Polnisch, kein Arabisch und vor allem kein vereinfachtes oder traditionelles Chinesisch. Die Store-Seite, nicht die Pressemitteilung, ist maßgeblich."),
        section("audio-subtitles", "Audio- und Untertitel-Aufteilung", "Alle acht Sprachen sind mit vollem Ton markiert. Nur drei haben auch Untertitel: Englisch, Japanisch, Koreanisch. Bei den anderen fünf (Französisch, Deutsch, Spanisch, Portugiesisch, Russisch) sind Oberfläche und Ton lokalisiert, Untertiteltext jedoch nicht — rechnen Sie mit englischem Fallback."),
        section("chinese-gap", "Die chinesische Lücke", "Frühere Ankündigungen sprachen von zehn geplanten Sprachen inklusive vereinfachtem und traditionellem Chinesisch. Die aktuelle Steampage spiegelt das nicht wider. Heute kann ein Spieler mit vereinfachtem Chinesisch auf dem globalen Steam-Client keine chinesische Oberfläche erwarten; der Fallback ist Englisch, mit Japanisch und Koreanisch als einzigen Vollton-plus-Untertitel-Optionen. Die Lage kann sich ändern, planen Sie aber zum Prüfdatum mit Englisch."),
        section("regions-vs-languages", "Regionen sind keine Sprachen", "NCSoft startet global auf dem PC (Steam und PURPLE) in Nord-/Südamerika, Europa und Asien. Das sind Serverregionen, getrennt von der Oberflächensprache. Eine Region wählen erzwingt keine Sprache und umgekehrt."),
        section("what-it-means", "Was das zum Start bedeutet", "Prüfen Sie die Abdeckung Ihrer Hauptsprache: Oberfläche, Vollton, Untertitel wiegen unterschiedlich. Für Vollton + Untertitel sind Englisch, Japanisch, Koreanisch die sicheren Optionen. Als vereinfachter-chinesischer Spieler planen Sie die englische Oberfläche ein und prüfen nach jeder Lokalisierungsankündigung erneut. Der Free-to-play-Start am 5. Oktober, der LST 17.–18. September und die Steam-Playtest-Anfrage sind kostenlose Wege zur Verifikation."),
      ],
    }),
    es: articleCopy(guideLabels, "es", 5, {
      eyebrow: "VERIFICACIÓN DE IDIOMAS",
      title: "Idiomas de la versión global de Aion 2: 8 idiomas en Steam, sin chino",
      description: "La página de Steam de AION 2 lista 8 idiomas — inglés, francés, alemán, español (España), japonés, portugués (Brasil), ruso y coreano — todos con audio completo, con subtítulos en inglés, japonés y coreano. Sin chino simplificado ni tradicional.",
      intro: "Antes del lanzamiento del 5 de octubre, saber qué idiomas trae la versión global de AION 2 importa a todo jugador no anglófono. La página de Steam actual lista exactamente ocho idiomas, y el chino no está entre ellos. Esta guía detalla la lista, audio frente a subtítulos, la diferencia región/idioma y el impacto para lectores de chino simplificado.",
      sourceNote: "Basado en la página de Steam de AION 2 (recuperada y verificada el 31 de agosto de 2026), cotejado con el informe de Gamescom 2026 de Massively Overpowered que confirma el 5 de octubre en Norteamérica, Sudamérica, Europa y Asia.",
      keywords: ["Aion 2 idiomas", "Aion 2 idiomas soportados", "Aion 2 sin chino", "Aion 2 subtítulos", "Aion 2 idiomas Steam"],
      sections: [
        section("what-steam-lists", "La lista exacta de 8 idiomas", "Steam muestra «inglés y 7 más» para AION 2. Los ocho idiomas: inglés, francés, alemán, español (España), japonés, portugués (Brasil), ruso y coreano — la lista completa y legible por máquina al 31 de agosto de 2026. Sin italiano, sin polaco, sin árabe y, sobre todo, sin chino simplificado ni tradicional. La página de la tienda, no el comunicado, es la fuente."),
        section("audio-subtitles", "Audio y subtítulos", "Los ocho idiomas están marcados con audio completo. Solo tres tienen también subtítulos: inglés, japonés y coreano. En los otros cinco (francés, alemán, español, portugués, ruso) la interfaz y el audio están localizados, pero no el texto de subtítulos: espera un retroceso al inglés."),
        section("chinese-gap", "La ausencia del chino", "Anuncios anteriores describían un plan de diez idiomas, incluido el chino simplificado y tradicional. La página de Steam actual no lo refleja: ocho idiomas, ninguna escritura china. Hoy un jugador de chino simplificado no puede contar con interfaz china en el cliente global de Steam; el retroceso es el inglés, con japonés y coreano como únicas opciones de audio+subtítulos completos. La situación puede cambiar, pero planifica en inglés a la fecha de verificación."),
        section("regions-vs-languages", "Las regiones no son idiomas", "NCSoft lanza en PC (Steam y PURPLE) en Norteamérica, Sudamérica, Europa y Asia. Son regiones de servidores, distintas de los idiomas de interfaz. Elegir una región no impone un idioma ni al revés."),
        section("what-it-means", "Qué significa al lanzamiento", "Verifica la cobertura de tu idioma principal: interfaz, audio completo y subtítulos pesan distinto. En inglés, japonés y coreano tienes los tres. En chino simplificado, presupuesta la interfaz en inglés y re-verifica tras cualquier anuncio de localización. El lanzamiento gratuito del 5 de octubre, el test de carga del 17–18 de septiembre y la solicitud de Steam Playtest permiten verificar antes de pagar."),
      ],
    }),
    "pt-br": articleCopy(guideLabels, "pt-br", 5, {
      eyebrow: "VERIFICAÇÃO DE IDIOMAS",
      title: "Idiomas da versão global do Aion 2: 8 idiomas na Steam, sem chinês",
      description: "A página da Steam do AION 2 lista 8 idiomas — inglês, francês, alemão, espanhol (Espanha), japonês, português (Brasil), russo e coreano — todos com áudio completo, com legendas em inglês, japonês e coreano. Sem chinês simplificado nem tradicional.",
      intro: "Antes do lançamento em 5 de outubro, saber quais idiomas a versão global do AION 2 realmente traz importa para todo jogador não anglófono. A página atual da Steam lista exatamente oito idiomas, e o chinês não está entre eles. Este guia detalha a lista, áudio versus legendas, a diferença região/idioma e o impacto para leitores de chinês simplificado.",
      sourceNote: "Com base na página da Steam do AION 2 (recuperada e verificada em 31 de agosto de 2026), cruzado com o relato da Gamescom 2026 da Massively Overpowered confirmando 5 de outubro na América do Norte, do Sul, Europa e Ásia.",
      keywords: ["Aion 2 idiomas", "Aion 2 idiomas suportados", "Aion 2 sem chinês", "Aion 2 legendas", "Aion 2 idiomas Steam"],
      sections: [
        section("what-steam-lists", "A lista exata de 8 idiomas", "A Steam mostra «inglês e mais 7» para o AION 2. Os oito idiomas: inglês, francês, alemão, espanhol (Espanha), japonês, português (Brasil), russo e coreano — a lista completa e legível por máquina em 31 de agosto de 2026. Sem italiano, sem polonês, sem árabe e, sobretudo, sem chinês simplificado nem tradicional. A página da loja, não o comunicado, é a fonte."),
        section("audio-subtitles", "Áudio e legendas", "Os oito idiomas estão marcados com áudio completo. Apenas três têm também legendas: inglês, japonês e coreano. Nos outros cinco (francês, alemão, espanhol, português, russo), interface e áudio estão localizados, mas não o texto das legendas: espere o retorno ao inglês."),
        section("chinese-gap", "A ausência do chinês", "Anúncios anteriores descreviam um plano de dez idiomas, incluindo o chinês simplificado e tradicional. A página atual da Steam não reflete isso: oito idiomas, nenhuma escrita chinesa. Hoje um jogador de chinês simplificado não pode contar com interface chinesa no cliente global da Steam; o retorno é o inglês, com japonês e coreano como únicas opções de áudio+legendas completos. A situação pode mudar, mas planeje em inglês na data de verificação."),
        section("regions-vs-languages", "Regiões não são idiomas", "A NCSoft lança em PC (Steam e PURPLE) na América do Norte, do Sul, Europa e Ásia. São regiões de servidores, distintas dos idiomas de interface. Escolher uma região não impõe um idioma nem o contrário."),
        section("what-it-means", "O que significa no lançamento", "Verifique a cobertura do seu idioma principal: interface, áudio completo e legendas pesam diferente. Em inglês, japonês e coreano você tem os três. Em chinês simplificado, planeje a interface em inglês e re-verifique após qualquer anúncio de localização. O lançamento gratuito de 5 de outubro, o teste de carga de 17–18 de setembro e o pedido de acesso ao Steam Playtest permitem verificar antes de pagar."),
      ],
    }),
    ru: articleCopy(guideLabels, "ru", 5, {
      eyebrow: "ПРОВЕРКА ЯЗЫКОВ",
      title: "Языки глобальной версии Aion 2: 8 языков в Steam, без китайского",
      description: "Страница AION 2 в Steam перечисляет 8 языков — английский, французский, немецкий, испанский (Испания), японский, португальский (Бразилия), русский и корейский — все с полной озвучкой, субтитры только на английском, японском и корейском. Ни упрощённого, ни традиционного китайского.",
      intro: "Перед запуском 5 октября каждому не-англоговорящему игроку важно знать, какие языки реально поддерживает глобальная версия AION 2. Текущая страница Steam перечисляет ровно восемь языков, и китайского среди них нет. Этот гайд разбирает список, разницу озвучка/субтитры, регионы против языков и значение для читателей на упрощённом китайском.",
      sourceNote: "На основе страницы AION 2 в Steam (получена и проверена 31 августа 2026), сверено с отчётом Massively Overpowered с Gamescom 2026 (запуск 5 октября в Северной/Южной Америке, Европе и Азии).",
      keywords: ["Aion 2 языки", "Aion 2 поддерживаемые языки", "Aion 2 без китайского", "Aion 2 субтитры", "Aion 2 языки Steam"],
      sections: [
        section("what-steam-lists", "Точный список из 8 языков", "Steam показывает для AION 2 «английский и ещё 7». Восемь языков: английский, французский, немецкий, испанский (Испания), японский, португальский (Бразилия), русский и корейский — полный, машинно-читаемый список на 31 августа 2026. Нет итальянского, польского, арабского и, главное, ни упрощённого, ни традиционного китайского. Страница магазина, а не пресс-релиз, является источником."),
        section("audio-subtitles", "Озвучка и субтитры", "Все восемь языков отмечены полной озвучкой. Субтитры есть только у трёх: английский, японский, корейский. У остальных пяти (французский, немецкий, испанский, португальский, русский) локализованы интерфейс и озвучка, но не текст субтитров — ожидайте откат на английский."),
        section("chinese-gap", "Отсутствие китайского", "Более ранние анонсы описывали план из десяти языков, включая упрощённый и традиционный китайский. Текущая страница Steam этого не отражает. Сегодня игрок с упрощённым китайским не может рассчитывать на китайский интерфейс в глобальном клиенте Steam; откат — английский, а полная озвучка+субтитры есть только на японском и корейском. Ситуация может измениться, но планируйте на английский на дату проверки."),
        section("regions-vs-languages", "Регионы ≠ языки", "NCSoft запускает на ПК (Steam и PURPLE) в Северной/Южной Америке, Европе и Азии. Это серверные регионы, отдельные от языков интерфейса. Выбор региона не навязывает язык и наоборот."),
        section("what-it-means", "Что это значит на запуске", "Проверьте покрытие основного языка: интерфейс, полная озвучка и субтитры весят по-разному. Для озвучки+субтитров — английский, японский, корейский. Игроку с упрощённым китайским стоит закладывать английский интерфейс и перепроверять страницу после анонсов локализации. Бесплатный запуск 5 октября, LST 17–18 сентября и запрос Steam Playtest — бесплатные способы проверить локализацию до оплаты."),
      ],
    }),
    "zh-hant": articleCopy(guideLabels, "zh-hant", 5, {
      eyebrow: "語言支援核查",
      title: "Aion 2 全球版語言支援：Steam 實列 8 種，無中文",
      description: "AION 2 的 Steam 商店頁現列出 8 種支援語言——英、法、德、西（西班牙）、日、葡（巴西）、俄、韓——八種全語音，字幕僅英、日、韓。簡體與繁體中文均不在名單內。",
      intro: "在 10 月 5 日全球上線前，AION 2 全球版到底支援哪些語言，對每一位非英語玩家都至關重要。當前 Steam 商店頁恰好列出八種支援語言，而中文——無論簡體還是繁體——都不在其中。本指南給出完整清單、語音與字幕細分、大區與語言的區別，以及對繁體中文玩家的實操含義。",
      sourceNote: "基於 AION 2 Steam 商店頁（2026-08-31 檢索並核對），並與 Massively Overpowered 的 Gamescom 2026 報導（確認 10 月 5 日在北美、南美、歐洲與亞洲上線）交叉核對。",
      keywords: ["Aion 2 語言支援", "Aion 2 支援語言", "Aion 2 無中文", "Aion 2 字幕", "Aion 2 Steam 語言"],
      sections: [
        section("what-steam-lists", "實列的 8 種語言", "Steam 目前將 AION 2 標為「英語及另外 7 種」。八種語言為：英語、法語、德語、西班牙語（西班牙）、日語、葡萄牙語（巴西）、俄語、韓語。這是截至 2026-08-31 商店頁上完整、可機器讀取的清單。這份清單的缺項值得注意：沒有義大利語、沒有波蘭語、沒有阿拉伯語，而——對本站讀者最關鍵——沒有簡體中文，也沒有繁體中文。商店頁會變，上線前請複查頁面。"),
        section("audio-subtitles", "語音與字幕細分", "八種語言全部標記為「完整語音」。僅三種語言同時帶有字幕：英語、日語、韓語。其餘五種——法語、德語、西班牙語（西班牙）、葡萄牙語（巴西）、俄語——介面與語音本地化，但未標記字幕文本。實操上，FR/DE/ES/PT-BR/RU 玩家應預期介面與配音為母語，而螢幕字幕文本回退英語。"),
        section("chinese-gap", "中文缺席", "早前的公告與舊報導將全球版描述為計畫支援十種語言，包含簡體與繁體中文。當前 Steam 頁面並未體現這一點：上面八種即全部列出，兩種中文均未出現。今日的全球 Steam 用戶端上，中文玩家無法依賴中文介面；回退語言是英語，僅日、韓提供全語音加字幕。以本指南核對日為準，請按英語介面做首發計畫。"),
        section("regions-vs-languages", "大區不等於語言", "NCSoft 宣布全球版在 PC（Steam 與 PURPLE）於北美、南美、歐洲與亞洲上線。這些是伺服器大區——你從哪裡連線——與介面語言是兩回事。任一大區的玩家原則上都可使用任何受支援的介面語言。"),
        section("what-it-means", "上線時的實操含義", "若你掌握多語，實際建議是先確認主用語言的覆蓋：介面、完整語音、字幕三者權重不同。對「熟悉文字 + 全語音 + 字幕」，英語、日語、韓語目前是穩妥之選。若你是繁體中文玩家，請按上線時使用英語介面做預算，並在任何本地化公告後複查商店頁。10 月 5 日免費遊玩上線與 9 月 17–18 日 LST、Steam Playtest 申請都是免費途徑，可在付費前確認哪些已本地化。"),
      ],
    }),
  },
};
